### ISSUE TITLE
MixedManga extension not working

### ISSUE THREAD

**Issue by Sapphire0924** [tachiyomiorg/tachiyomi-extensions#10003]
### Source information

Mixed Manga 1.2.15

### Steps to reproduce

1. Images are not loading when I opened any manhwa from mixed Manga in my library
2. WebView  works fine

### Expected behavior

Images should  automatically load and display after clicking on the title

### Actual behavior

The images are not loading and only the 'retry' button appears

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
Today suddenly it work for me. Does it fixed already?

**Comment by Sapphire0924** [comment]
Hi, I think it was fixed already... I sent the complain last year so I thought no one saw it so I migrated to another site and never checked on it so I'm not so sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
