### ISSUE TITLE
10000

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/tachiyomi-extensions#10000]
### Describe why this should be added

I will not let some weird request be our 10 000th

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
First

**Comment by ObserverOfTime** [comment]
![congratulations](https://user-images.githubusercontent.com/24971970/144739691-2df2f60d-e385-49e5-b27d-22608727d5fe.png)
