### ISSUE TITLE
Toonily extension not loading manga or pages

### ISSUE THREAD

**Issue by Spark9999** [tachiyomiorg/tachiyomi-extensions#10005]
### Source information

Toonily 1.2.19

### Steps to reproduce

1.open the toonily source to view or search for any manga
2.or, open any toonily manga that is saved to library but not downloaded 

### Expected behavior

The manga in library from toonily should open or the manga from toonily extension/source should load and open. 

### Actual behavior

The manga in library from toonily source is not loading any pages and keeps on loading. Same for the manga opened from the source/extension itself. 

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

The Webview for Toonily extension is opening and the manga can be read. Same for the website. Initially the Webview was not loading either and had some issues with their server but those are fine now. The toonily extension however is not loading any manga, and even if eventually it does load some manga it is the first few manga that it loads and beyond that it says "retry", basically to refresh the feed. However doubt so yields the same infinite loading and it never loads. Same for the manga from toonily source opened in the library which are not downloaded. Those are showing the chapters and all but on opening the chapters, the pages show infinite loading. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Omar-Abdul-Aziz** [comment]
It works fine on the same extension version but tachiyomi 0.12.1 haven't tested on 0.12.3 but I doubt it matters

Could it just be your connection? Try to open their website outside of tachiyomi

**Comment by brazor421** [comment]
Tachiyomi 0.12.3/toonily.com 1.12.19 works just fine. But I had the same bug a couple of days ago. Site and webview worked propely, but in app I was getting constat loading. So I decided to deal with it later. But later it miraculously got to work as it should be. So... I don't know what that was.

**Comment by Spark9999** [comment]
> It works fine on the same extension version but tachiyomi 0.12.1 haven't tested on 0.12.3 but I doubt it matters
> 
> Could it just be your connection? Try to open their website outside of tachiyomi

Is it my network ? No bcs another user is also facing this. I did open their website out of tachyomi as I mentioned, and it's opening. Only the extension itself is not working. Webview is working.

**Comment by Spark9999** [comment]
> Tachiyomi 0.12.3/toonily.com 1.12.19 works just fine. But I had the same bug a couple of days ago. Site and webview worked propely, but in app I was getting constat loading. So I decided to deal with it later. But later it miraculously got to work as it should be. So... I don't know what that was.

It did open in the morning today, for a while, and now it's back to the same issue of not loading up. I was additionally shown http 502 error in the extension and while opening the manga in the library from toonily it showed Java Lang exception unable to bypass cloudfare.

**Comment by fawadkhan121** [comment]
Use vpn

**Comment by Spark9999** [comment]
Fixed for now. Resolved on its own.
