### ISSUE TITLE
Mangadex extensions don't show all the chapter

### ISSUE THREAD

**Issue by SqueezedByte** [tachiyomiorg/tachiyomi-extensions#10006]
### Source information

MangaDex 1.2.144 (Language English)

### Steps to reproduce

Select Mission: Yozakura Family as manga
Open from Tachiyomi. Only show chapter 1
Open in webview. Show all the chapter 

### Expected behavior

To show all the chapter as in the webview

### Actual behavior

Only show chapter 1 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![Screenshot_2021-12-05-20-28-03-92_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/33869313/144760948-ee43bdaa-1fe8-4211-9215-62043b60860d.jpg)
![Screenshot_2021-12-05-20-28-09-14_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/33869313/144760953-5e13df5f-9bf8-49e5-9229-6ed49d90fc54.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
As you can see, those are links that take you to MangaPlus website and cannot be read from MangaDex website itself. The tachiyomi Mangadex extension also doesn't handle such links that take you to external sites
