### ISSUE TITLE
mwmanhwa.net

### ISSUE THREAD

**Issue by xeanz** [tachiyomiorg/tachiyomi-extensions#10019]
### Source name

mwmanhwa.net

### Source link

https://mwmanhwa.net/

### Language

English

### Other details

manhwamanga.net change name to mwmanhwa.net
(request for extension)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [x] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [x] I will fill out all of the requested information in this form.

**Comment by fawadkhan121** [comment]
The extension is manhwamanga.net download it in tachi app

**Comment by fawadkhan121** [comment]
This source is available by the name of manhwamanga.net
