### ISSUE TITLE
mangaboss: Only getting one page in chapter 

### ISSUE THREAD

**Issue by NishantTirthani** [tachiyomiorg/tachiyomi-extensions#10026]
### Source information

mangaboss

### Steps to reproduce

When I click on chapter I get only one page
![Screenshot_20211207-153944](https://user-images.githubusercontent.com/16254390/145009660-75fd5a12-fac9-4cb5-996b-66cd16b7df51.jpg)
Have to read in webview to read whole chapter

### Expected behavior

Should be able to read whole chapter

### Actual behavior

Read whole chapter

### Tachiyomi version

0.12.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FaTe-code** [comment]
I'm also getting this not only from one source but multiple sources mostly manhua/hwa sources
