### ISSUE TITLE
Source issue 

### ISSUE THREAD

**Issue by Arkmes** [tachiyomiorg/tachiyomi-extensions#10021]
### Source information

Asura scans 1.2.19 

### Steps to reproduce

Example:
1. Open the application.
2. And open any manhwas,mangas and such from the mentioned sources above.
3.  The images doesn't load and it says "No pages found"

### Expected behavior

The chapter should've loaded and shown the particular weebtoon,manga,manhwa,manhuas and such.

### Actual behavior
![Screenshot_2021-12-07-08-30-26-337_eu kanade tachiyomi](https://user-images.githubusercontent.com/95666833/144963454-b6265f80-e355-4a0e-83fe-648e8c3b0bdd.jpg)

The chapter didn't load, instead it showed "no pages found".

### Tachiyomi version

0.12.3

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#10020
