### ISSUE TITLE
xCaliBR Scans: Chapter not working

### ISSUE THREAD

**Issue by MugenNatsu** [tachiyomiorg/tachiyomi-extensions#10031]
### Source information

XCaliBer Scabs 1.2.14

### Steps to reproduce

Web view working. Can't read chaper with out download and can't download too. Also when trying to download temp file is showing that I'm downloading another chapter

### Expected behavior

It should be download Eternal Supreme chapter 46 byt it download chapter 42 and it stops at half

### Actual behavior

It should be downloading chapter 46

### Tachiyomi version

App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G996BXXU3BUKG Device brand: samsung Device manufacturer: samsung Device name: t2s Device model: SM-G996B Device product name: t2sxxx

### Android version

Android 12

### Other details

![Screenshot_20211208-050156_Tachiyomi](https://user-images.githubusercontent.com/91587646/145122942-06a4a867-3698-42fc-bc5d-c38772106e0d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
The chapter itself is that way in the site The are like 5-6 corrupted images before the actual chapter starts. So nothing we can do about this.

![image](https://user-images.githubusercontent.com/59261191/147412099-dde53aaa-080c-4479-a9e9-9a1adaee9c19.png)
