### ISSUE TITLE
Komikcast

### ISSUE THREAD

**Issue by Xyupi** [tachiyomiorg/tachiyomi-extensions#10039]
### Source name

Komikcast

### Source link

https://komikcast.id

### Language

Indonesia

### Other details

New website of komikcast

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
> New website of komikcast

tampilannya nampak seperti website kawe

**Comment by ZuveKun** [comment]
website aslinya tetep https://komikcast.com/

**Comment by Riztard** [comment]
so maybe if being added, name it "KomikCast.id (Unoriginal)"

**Comment by vetleledaal** [comment]
Appears to use WPMangaStream or WPMangaReader

**Comment by Xyupi** [comment]
> > New website of komikcast
> 
> tampilannya nampak seperti website kawe apa emang baru?

Menurut saya web itu cuma tumbal web utama "komikcast " Takut di ban kakaopage mungkin gara "solo leveling"
