### ISSUE TITLE
KomikIndo (ID) chapter error

### ISSUE THREAD

**Issue by sap471** [tachiyomiorg/tachiyomi-extensions#10038]
### Source information

KomikIndo 1.2.3

### Steps to reproduce

1. Open your comic as usual.
2. Try to read one chapter, randomly.
3. It's shown "Page Not Found"

### Expected behavior

Should show chapter image as usual

### Actual behavior

Some hover notificarion show up says "page not found"

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
yang `komikindo.co` apa `komikindoID` bisa semua soalnya
