### ISSUE TITLE
PM Scans Chain Validation Failed

### ISSUE THREAD

**Issue by aSimpleGuy** [tachiyomiorg/tachiyomi-extensions#10032]
### Source information

PMScans 1.2.11

### Steps to reproduce

1.Open Pm scans 

### Expected behavior

Should show available manga

### Actual behavior

Chain Validation Failed

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/145150274-cd85911b-5eab-4344-a70f-4acedd9d6ab1.png)
