### ISSUE TITLE
Mangachan (ru)

### ISSUE THREAD

**Issue by monolit** [tachiyomiorg/tachiyomi-extensions#10034]
### Describe why this should be added

Says no chapters on licenced, but it's exists 
Example: https://manga-chan.me/manga/95944-jujutsu-kaisen.html (tap read online)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
log in to your account via webview
![Screenshot_20220415-121723_Takoyomi.png](https://user-images.githubusercontent.com/35057681/163538317-fff4dd3d-26b2-4d75-bae8-28779c27770e.png)
