### ISSUE TITLE
Phoenix Fansub

### ISSUE THREAD

**Issue by 01SHAKA** [tachiyomiorg/tachiyomi-extensions#10044]
### Source information

Phoenix Fansub V.1.2.13

### Steps to reproduce

Marca el error HTTP error 404 al abrir un contenido, no muestra los capitulos

### Expected behavior

Debería de aparecer todos los capítulos

### Actual behavior

No marca los capítulos, marca error 404

### Tachiyomi version

TachiyomiJ2K V1.4.3

### Android version

Android 11

### Other details

Nada mas en un manga que guarde anteriormente, abre con normalidad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Appears to be fixed in #10338
