### ISSUE TITLE
Manga1st chapters only load one page

### ISSUE THREAD

**Issue by Jugom** [tachiyomiorg/tachiyomi-extensions#10056]
### Source information

Manga1st 1.2.15

### Steps to reproduce

In Manga1st extension open any manhua with new chapters and open the new chapter

### Expected behavior

When you open a new chapter it should load all chapter pages

### Actual behavior

 when you open a new chapter it only loads the first page

### Tachiyomi version

0.12.3

### Android version

Androis 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
Manga1st or manhuaus?

**Comment by Jugom** [comment]
1st

**Comment by Jugom** [comment]
actually, MangaGreat too... should I make a new report for that one too?

**Comment by CrepeTF** [comment]
> actually, MangaGreat too... should I make a new report for that one too?
> 

1 issue per ticket so yes, but check if there's a ticket already
