### ISSUE TITLE
MangaGreat chapters only load one page

### ISSUE THREAD

**Issue by Jugom** [tachiyomiorg/tachiyomi-extensions#10057]
### Source information

MangaGreat 1.2.15

### Steps to reproduce

In MangaGreat extension open any manga with new chapters and open the new chapter

### Expected behavior

When you open a new chapter it should load all chapter pages

### Actual behavior

when you open a new chapter it only loads the first page only

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mrehanabbasi** [comment]
ManhuaUS also has this problem.

**Comment by Bappamaiti** [comment]
Please fix this bug asap. Most of my manga are from this extension and now its not working properly.

Thanks for your hard work.
