### ISSUE TITLE
MangaSee Unexpected JSON token at offset 14

### ISSUE THREAD

**Issue by WeepingClown13** [tachiyomiorg/tachiyomi-extensions#10068]
### Source information

MangaSee 1.2.26

### Steps to reproduce

1. MangaSee » Bakemonogatari  » Download Chapter 87 

2. MangaSee » Ajin » Download Chapters 83.5 to 86

### Expected behavior

Chapters should be downloaded

### Actual behavior

Getting error message "Unexpected JSON token at offset 14" and skips to next download.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![IMG_20211210_091451](https://user-images.githubusercontent.com/95921427/145582997-23465673-da4c-42e8-9075-781e2fd74538.jpg)

[Downloads aren't being affected entirely but for specific chapters of certain manga. These two are what I currently encountered. Tried, deletion, re-download, clearing cache etc. but nothing worked. And unable to see the rest of the error message for some reason]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> I have tried the troubleshooting guide.

your examples aren't on the website. they may have removed them but it still exists in their db.
![example 1](https://user-images.githubusercontent.com/57241064/145584558-d59db32a-62af-4b7b-84a7-441517fb4871.png)
![example 2](https://user-images.githubusercontent.com/57241064/145584628-92d98b3a-a4d1-46d0-809a-36c4064b27b3.png)

**Comment by WeepingClown13** [comment]
Okay. So it'll be resolved once the chapters are added back eh. Thanks for the help. Also I didn't double check so sorry for that.
