### ISSUE TITLE
[Source Request] [Spanish] Niadd

### ISSUE THREAD

**Issue by GoWonn** [tachiyomiorg/tachiyomi-extensions#1007]
Niadd (Mangadogs) SOURCE:
  https://es.niadd.com

**Comment by edgarMejia** [comment]
I'll work on it.

**Comment by MerradOklom** [comment]
Gracias por tu arduo trabajo @edgarMejia
Solo quería comentar que creo que el catálogo de Niadd es el mismo de NineManga

**Comment by edgarMejia** [comment]
Hola @MerradOklom, se hace lo que se puede :) y te agradesco por la información, revisaré si el contenido es el mismo que NineManga, por el momento trabajare en el #924 

Por cierto, hice una lista de todos los source que has solicitado, los iré o iremos añadiendo con el tiempo.
Saludos.

**Comment by as280093** [comment]
Here the icons
[Niadd.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614379/Niadd.zip)

**Comment by PieroSebastianJoestar** [comment]
> source

Porfavor trata de añadir Niadd a la app :( Hay mangas que solo suben a Niadd y no a NineManga (Ejemplo: Ueno san wa Bukiyou y Undead Unluck)

**Comment by MerradOklom** [comment]
> Hay mangas que solo suben a Niadd y no a NineManga (Ejemplo: Ueno san wa Bukiyou y Undead Unluck) :(

Instala la extensión FoolSlide y usa la fuente de KirishimaFansub, ellos traducen el manga de Ueno-san.

**Comment by PieroSebastianJoestar** [comment]
> > Hay mangas que solo suben a Niadd y no a NineManga (Ejemplo: Ueno san wa Bukiyou y Undead Unluck) :(
> 
> Instala la extensión FoolSlide y usa la fuente de KirishimaFansub, ellos traducen el manga de Ueno-san.



> > Hay mangas que solo suben a Niadd y no a NineManga (Ejemplo: Ueno san wa Bukiyou y Undead Unluck) :(
> 
> Instala la extensión FoolSlide y usa la fuente de KirishimaFansub, ellos traducen el manga de Ueno-san.

Los de Kirishima fansub solo han traducido hasta el capítulo 30, en cambio los de Niadd ya han traducido hasta el capítulo 60 :(

**Comment by edgarMejia** [comment]
Ya estoy trabajando en esta extensión.

**Comment by MerradOklom** [comment]
@edgarMejia en éste pr hablaban de crear una Factory extension con esta y otras fuentes similares:
#3621

> Ya estoy trabajando en esta extensión.

En éste pr #3621 se habló sobre crear una extensión multifuente con esta y otras páginas que usan un tema similar.

**Comment by edgarMejia** [comment]
Gracias por la información, al parecer en ese paquete de sources retomarán Niadd

**Comment by Asura0818** [comment]
Hola, no pudieron agregar la extensión de NiAdd?
