### ISSUE TITLE
Alpha Scans pages not loading

### ISSUE THREAD

**Issue by ZEXERJK** [tachiyomiorg/tachiyomi-extensions#10071]
### Source information

Alpha Scans 1.2.11

### Steps to reproduce

1. Try to read the last chapters of one of the series
2. Some chapters load fine and some other have pages not loading at all

### Expected behavior

Chapter's pages should load fine like always.

### Actual behavior

Screenshot:

![1](https://user-images.githubusercontent.com/48049633/145636570-1becbe2c-9ff3-4e3c-bffe-33bb69dd03b5.jpg)

Sometimes the pages in between load just fine, and some don't.

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11

### Other details

I tried clearing cache and cookies but without success, sometimes it just won't load.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
cant reproduce, or maybe already fixed
