### ISSUE TITLE
it seems MangaStein's domain has changed.

### ISSUE THREAD

**Issue by kyoyacchi** [tachiyomiorg/tachiyomi-extensions#10070]
### Source information

MangaStein 1.2.15

### Steps to reproduce

1.Open the MangaStein source.
2.Wait for the response
3.And you'll see that it says "No results found." 

### Expected behavior

Tachiyomi should've reach the site.

### Actual behavior

It says "No results found."

### Tachiyomi version

0.12.3

### Android version

Android 8

### Other details

The new domain of MangaStein seems as "https://tr.asurascans.com" (Turkish)
the old url was "https://www.mangastein.com", it redirects to "https://tr.asurascans.com" anyway.
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by matmakif** [comment]
MangaStein is dead.
