### ISSUE TITLE
AnimaRegia: Missing status

### ISSUE THREAD

**Issue by Victor3050** [tachiyomiorg/tachiyomi-extensions#10076]
### Source information

AnimaRegia 1.2.6

### Steps to reproduce

 > 1. Install the extension 

> 2. Access any manga

> 3. See the stat

 

### Expected behavior

Extension statuses should appear as on the website.

### Actual behavior

Instead they just show up as "unknown"

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Just a note to my future self: the extension should remove the language tag from the titles name too.

**Comment by Victor3050** [comment]
The manga tags do not appear in the extension either.
