### ISSUE TITLE
xCaliBR Scans - Split image

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi-extensions#10086]
### Source information

xCaliBR Scans 1.2.14

### Steps to reproduce

Reading new chapters

### Expected behavior

Seeing complete picture
![IMG_20211213_034241](https://user-images.githubusercontent.com/35896230/145735708-14c854d6-4810-4c5c-9e11-f7e80565259e.jpg)

### Actual behavior

Magnified part of sliced picture. 
![Screenshot_20211213-033845](https://user-images.githubusercontent.com/35896230/145735353-70ba7ea7-9577-437c-ac31-a47659b1f3d2.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Except for first and last image that contains cover and etc. Other pages split vertically into several pages.

Same thing happened to flame scan some times a go and you did fix it there. So i think there is no need to recode. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by StKob** [comment]
There is also one where image is mirrored. I'm guessing that its something they are doing to hinder reader viewers cause webview shows correct images.

**Comment by FourTOne5** [comment]
So which manhua and chapter is this? I cant seem to find any chapter where images are splitted.
