### ISSUE TITLE
Hentai Kai: content of the extension does not appear.

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#10087]
### Source information

Hentai Kai 1.2.2

### Steps to reproduce

1- Open the latest tab on Hentai Kai extension.

2- No content appears.

### Expected behavior

When you open Hentai Kai, it shows the recent content.

### Actual behavior

When open the extension, it doesn't show anything.

### Tachiyomi version

0.12.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This extension was removed due to them obsfucating a lot the chapter URLs and we do not offer support to it anymore. Migrate to other sources.
