### ISSUE TITLE
minne

### ISSUE THREAD

**Issue by Wendell05** [tachiyomiorg/tachiyomi-extensions#10093]
### Source information

toonily

### Steps to reproduce

it did'nt load no matter what i do

### Expected behavior

need to fix that toonily is not loading 

### Actual behavior

it isnt loading

### Tachiyomi version

0.12.3

### Android version

Android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Low effort reports are not useful for getting help. Try going through the troubleshooting guide first and if still having issues, create another issue with more specific details.
