### ISSUE TITLE
ManhwaLand

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#10096]
### Source name

ManhwaLand

### Source link

https://manhwaland.biz/

### Language

Indonesian

### Other details

Please add this extension to tachiyomi because this extension not available in tachiyomi for read Manhwa R18 because SekaiKomik cant be used
![Screenshot_2021-12-14-09-19-25-97](https://user-images.githubusercontent.com/81138524/145921166-bc7a9e83-7112-4a8e-ad01-e4e324b2ebf8.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader

**Comment by alessandrojean** [comment]
Closing in favour of #11540 that has a more updated domain.
