### ISSUE TITLE
ManhwaID

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#10097]
### Source name

ManhwaID

### Source link

https://manhwaid.org/

### Language

Indonesian

### Other details

Please add this extension to tachiyomi because this extension not available in tachiyomi for read Manhwa R18 because SekaiKomik cant be used
![Screenshot_2021-12-14-09-21-55-39](https://user-images.githubusercontent.com/81138524/145921430-947f6c71-d1a0-4499-9098-917a5225181f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Uses Madara theme
