### ISSUE TITLE
Clicking on Myreadingmanga while searching = Freeze or Crash.

### ISSUE THREAD

**Issue by ignaciocastro** [tachiyomiorg/tachiyomi-extensions#10108]
### Source information

MyReadingManga 1.2.43

### Steps to reproduce

1. Search for anything on "Browse"
2. Click on MyReadingManga (any language) while still loading

### Expected behavior

Should open, show a load screen then show the chapters/results.

### Actual behavior

Either freezes for a good 20 seconds before loading or crashes app.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Tested in MIUI 12.5.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dragoon91786** [comment]
I've had similar issues ongoing through several versions. I was able to resolve it by closing and stopping the app, clearing cache, and restarting the phone. It doesn't always happen, but in my case appears to be partly a result of having an abundance of comics loaded in Tachiyomi that hogs down the app. It will take over a minute to load the app with multiple hangs, often with accompanying [Close or Wait] error messages—sometimes, the app will simply crash altogether or will show only an option to close the app. I find in particular this happens with MyReadingManga.

Not sure if my issues are connected with yours, though.
