### ISSUE TITLE
[Bug] Japanread - JSON parser

### ISSUE THREAD

**Issue by moi15moi** [tachiyomiorg/tachiyomi-extensions#10109]
### Source information

Japanread 1.2.8

### Steps to reproduce

1. Click to open a chapter. Ex: Lookism chapter 221: https://www.japanread.cc/manga/lookism/221

### Expected behavior

I should be able to open the chapter when I click on it.

### Actual behavior

Instead, I receive this error when I try to open a chapter: _Unexpected JSON token at offset 7: Expected EOF after parsing an object, but had c instead. JSON input: error code: 1020_

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by madanao** [comment]
![IMG_20211215_203821](https://user-images.githubusercontent.com/73294424/146253535-5385ec52-ef6c-441f-abb4-2829a7aa47c6.jpg)
Same as you, i can't read any chapter with this source atm. Thank you for the post !
