### ISSUE TITLE
 Nux Scans abonded

### ISSUE THREAD

**Issue by AKSSPARKPrince** [tachiyomiorg/tachiyomi-extensions#10105]
### Source information

en.kanade.tachiyomi.extension.en.nuxscans 1.2.1 

### Steps to reproduce

 Official site said dropping all chapters cause of getting not net worth out of it

### Expected behavior

Chapters should have been showing in Manga trying to open

### Actual behavior

Every manga is showing "no chapter found"

### Tachiyomi version

Tachiyomi SY 1.7.0 Preview build: 421

### Android version

Android 11

### Other details

![Screenshot_20211214-230258705](https://user-images.githubusercontent.com/75882250/146051924-37ac3cd9-0c2a-4b3b-9788-8df014e43aca.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Nothing we can do about scanlator dropping series but I'll fix the extension so you can read the chapters

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
