### ISSUE TITLE
Luscious error 

### ISSUE THREAD

**Issue by aideila** [tachiyomiorg/tachiyomi-extensions#10118]
### Source information

Luscious 1.2.15

### Steps to reproduce

1.Try to open a doujin 
2.this appears and no chapters appear
Element class

kotlinx.serialization.json.JsonArray is not a

JsonObject

### Expected behavior

I see chapters 

### Actual behavior

An error occurs and this shows up 
Element class

kotlinx.serialization.json.JsonArray is not a

JsonObject

### Tachiyomi version

App version: 0.12.3

### Android version

App version: 0.1Android version: 9 (SDK 28) Android build ID: CPH2083EX_11_A.65 Device brand: OPPO Device manufacturer: OPPO Device name: OP4BFB Device model: CPH2083 Device product name: CPH2083

### Other details

I have both Tachiyomi and Tachiyomi AZ they both don't work 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ELDR3** [comment]
Have the same issue updating the app and complete wipe and clean install both didn't work.

**Comment by jopejoe1** [comment]
Some changes in #10080 seem to have broken resolutions other than `Original`

So changing the image resolution to `Original` would be a temporary fix while waiting for an extension update.

**Comment by ELDR3** [comment]
> 

Changing Scale Type to Original didn't change anything still can't see any chapters/content
