### ISSUE TITLE
BILIBILI webview jump webpage error

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#10115]
### Source information

BILIBILI v1.2.2

### Steps to reproduce

Entering the webview will force a jump to this error page.

![image](https://user-images.githubusercontent.com/46775615/146143167-f6dc0bdc-049f-4f24-bf89-583979585ce9.png)

and The correct Chinese translation of this passage is

【此漫画的付费章节已从章节列表中过滤，暂时请用网页端或官方app阅读。】

![image](https://user-images.githubusercontent.com/46775615/146142874-4b2fbfbd-378b-4fd0-903c-e8e40775cf6f.png)

### Expected behavior

Jump to Original page

### Actual behavior

jump webpage error

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
not quite sure but that jump is probably made to open the manga in the Chinese Bilibili app. Can you provide the manga url so I can check.

**Comment by ZerOri** [comment]
> not quite sure but that jump is probably made to open the manga in the Chinese Bilibili app. Can you provide the manga url so I can check.

[https://manga.bilibili.com/m/detail/mc28241](url)

yep,I tested it.Open the mobile homepage of the comic in the mobile browser will not jump.On the mobile web,the chapter can only open in the Chinese Bilibili app.But the desktop is not limited.

**Comment by FourTOne5** [comment]
the jump is probably triggered by this APK download which we can't do anything about![Screenshot_20211215-145128](https://user-images.githubusercontent.com/59261191/146154258-32ec74e4-8b6d-416c-adcd-6a0ce88b1883.png)

**Comment by FourTOne5** [comment]
Also can you translate this to string to Chinese?

"Chapter image quality" 
"Chapter image format"

**Comment by ZerOri** [comment]
> 

Of course.

"Chapter image quality">"章节图像质量"
"Chapter image format">"章节图像格式"

**Comment by ZerOri** [comment]
> the jump is probably triggered by this APK download which we can't do anything about![Screenshot_20211215-145128](https://user-images.githubusercontent.com/59261191/146154258-32ec74e4-8b6d-416c-adcd-6a0ce88b1883.png)

It seems that the webview triggered the automatic download of website,it's so funny😂Damn!

**Comment by alessandrojean** [comment]
Thanks for the translations! I will add it to a next update of the extension.

**Comment by alessandrojean** [comment]
@ZerOri One last question: about the chapter image quality options, do you think it's needed to translate "Raw", "HD" and "SD" to Chinese or they can be left as they are now?

**Comment by ZerOri** [comment]
> 

For Chinese user,it should be translated.

"RAW">原图
"HD">高
"SD">低

and adjust the previous translation.

"Chapter image quality">"章节图片质量"
"Chapter image format">"章节图片格式"
