### ISSUE TITLE
Kill six billion demons is displaying each page as a chapter. 

### ISSUE THREAD

**Issue by Spart4n** [tachiyomiorg/tachiyomi-extensions#10117]
### Source information

Kill six billion demons 1.2.4

### Steps to reproduce

1. Open a book 
2. Select a chapter
3. Notice every page is another chapter

### Expected behavior

Previous versions of the extension had chapters that contained multiple pages. 

### Actual behavior

Each page listed as it's own chapter. 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Makes navigating on app annoying to have to change pages twice every page. Ruins flow of reading completed books. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stoponerr** [comment]
somebody please, I would love to read it on tachiyomi

**Comment by BartTerpstra** [comment]
will be fixed by https://github.com/tachiyomiorg/tachiyomi/pull/6998 and disabling forced chapter transition.

**Comment by tinyn-ces** [comment]
That fix has been merged, but in practice it doesn't work well. It never seems to pre-load enough to actually skip the page-chapter breaks. 

Also the page-chapter list is backwards. I guess to make new pages appear at the top? But it makes the reading order backwards. It's "ok-ish" to just "read backwards" as long as it's actually one page per chapter, but the occasional multi-page chapters are backwards when that happens.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
