### ISSUE TITLE
HenChan - error with manga parsing

### ISSUE THREAD

**Issue by jplie** [tachiyomiorg/tachiyomi-extensions#10127]
### Source information

HenChan 1.2.26
HenChan 1.2.27

### Steps to reproduce

1. Open HenChan parser
2. Select any manga
3. Click on read
4. Now you can see error with parsing images from henchan

### Expected behavior

Parsing from henchan should work (●__●)

### Actual behavior

Error with parsing images
---
![IMG_20211216_203332](https://user-images.githubusercontent.com/61517619/146424122-926e9ca5-3f74-4244-bd44-b3bfc8d21666.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by JiLleON** [comment]
same issue, but appeared after updating to version 1.2.27, on 1.2.26 everything was fine, back to 1.2.26 and everything works again (android 12, 0.12.3 and tachij2k fork)

**Comment by jplie** [comment]
> same issue, but appeared after updating to version 1.2.27, on 1.2.26 everything was fine, back to 1.2.26 and parser works again (android 12, 0.12.3 and tachij2k fork)

I got this problem on 1.2.26 and after updating to 1.2.27 nothing changed, the problem remained the same.

**Comment by RaCc0oN1** [comment]
Any fix?
