### ISSUE TITLE
Mangceh: Domain Changed

### ISSUE THREAD

**Issue by bgmondy** [tachiyomiorg/tachiyomi-extensions#10139]
### Source information

Mangceh 1.2.17

### Steps to reproduce

1. open app 
2. select mangaceh in source
3. that source can't appear because address changed

### Expected behavior

Manhwa and chapters should apper on app

### Actual behavior

Web view is working fine but app is giving 400 error because Mangceh changed their site address

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Aslam604** [comment]
Having same issue
