### ISSUE TITLE
covers don't work for kuma scans 

### ISSUE THREAD

**Issue by mateus1224321** [tachiyomiorg/tachiyomi-extensions#10149]
### Source information

kuma scans (kuma translation) 1.2.13

### Steps to reproduce

1 - put a manga from this font in the library

### Expected behavior

the manga appear with the cover in the library 

### Actual behavior

some manga appear without the cover in the library 

### Tachiyomi version

App version: 0.12.3 

### Android version

Android 11

### Other details

some manga from this font appear with the cover but others don't, no matter what I do 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Could you give example Manga, because all the ones with missing covers i find also have a broken cover on the website?

**Comment by Riztard** [comment]
its working for me
