### ISSUE TITLE
Asura Scans not chapter found 

### ISSUE THREAD

**Issue by Astrokinng** [tachiyomiorg/tachiyomi-extensions#10140]
### Source information

Asura scan 1.2.20

### Steps to reproduce

1. open the app
2. Update the library
3. The manga under asura scan don't get updated

### Expected behavior

While updating the library the manga should get updated as well 

### Actual behavior

The manga don't get updated for asura Scans ...

### Tachiyomi version

App version: 0.12.3-4011

### Android version

Android 11

### Other details

![Screenshot_20211218-111011](https://user-images.githubusercontent.com/89287848/146631125-53f5e539-fa0e-437c-acb6-fd5c8266df52.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Asura Scans often changes the url for a manga. 
To fix this migrate from Asura Scans to Asura Scans.

**Comment by Astrokinng** [comment]
> Asura Scans often changes the url for a manga. To fix this migrate from Asura Scans to Asura Scans.

Whatt . !!!??

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/source-migration/#source-migration
