### ISSUE TITLE
please fix realmscans

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#10158]
### Source information

Realm Scans 1.2.11

### Steps to reproduce

1.open extension
2.open any manhwa or manhua on the site
3. pull down and or try to read

### Expected behavior

it should update and work normally

### Actual behavior

it shows no pages found and or shows this message "Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference" 

### Tachiyomi version

tachiyomisy preview r421

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

#10051
