### ISSUE TITLE
Mangareader by Robin Studios

### ISSUE THREAD

**Issue by axcolleen** [tachiyomiorg/tachiyomi-extensions#10156]
### Source name

MangaReader by Robin Studios

### Source link

https://play.google.com/store/apps/details?id=com.comikin.reader2&hl=en_US&gl=US

### Language

English

### Other details

Many people have their mangas on that aggregator site and was wondering if you guys can create an extension for that. The one currently available isn't associated with Robin Studio.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Unless you can provide a site and not an app NO

**Comment by ObserverOfTime** [comment]
> It collects 20+ manga sources into one application, include mangahere, mangafox, mangareader, batoto, mangapanda, kissmanga, mangago, mangatown, readmanga, etc.

How do you expect us to make a Tachiyomi extension for an app that's a Tachiyomi alternative?
