### ISSUE TITLE
White Cloud Pavilion

### ISSUE THREAD

**Issue by Kabur17** [tachiyomiorg/tachiyomi-extensions#10154]
### Source name

White Cloud Pavilion

### Source link

https://whitecloudpavilion.com/manga/patreon/

### Language

English

### Other details

A lot of our releases are getting sniped with worse quality or just not taken from our website, so I'd like to help out our readers by seeing if I can get us added to Tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Uses MMRCMS
