### ISSUE TITLE
Updating from sources

### ISSUE THREAD

**Issue by Fatlazy** [tachiyomiorg/tachiyomi-extensions#10157]
### Source information

Mangadex, isekai scans, bato, leviathan scans

### Steps to reproduce

Click the update button or update covers 

### Expected behavior

It should update the manga covers or find new chapters that have been uploaded 

### Actual behavior

The updates take hours and when finally completed, no updating of new chapters or covers take place and instead I am left with an error message saying timeout

### Tachiyomi version

0.12.3

### Android version

Android version 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Go ask for help on discord cause this seems unrelated to the extensions
