### ISSUE TITLE
[Source Request] Pocket Comics

### ISSUE THREAD

**Issue by cecoates** [tachiyomiorg/tachiyomi-extensions#10151]
### Source name

Pocket Comics

### Source link

https://www.pocketcomics.com/

### Language

English

### Other details

Note: This is a different company/source than Magazine Pocket (not a duplicate).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Also has Chinese as language option
and similar API as https://comico.jp and https://www.comico.kr
