### ISSUE TITLE
manga1st chapters only load one page

### ISSUE THREAD

**Issue by miyushibana** [tachiyomiorg/tachiyomi-extensions#10150]
### Source information

manga1st 

### Steps to reproduce

open

### Expected behavior

show all

### Actual behavior

only shows 1

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

please do what you acknowledge...
#10056
