### ISSUE TITLE
GManga doesn't work

### ISSUE THREAD

**Issue by JxDirash** [tachiyomiorg/tachiyomi-extensions#10161]
### Source information

GManga 1.2.8

### Steps to reproduce

1. Open extension
2. Click on specific manga
3. Chapters should appear

### Expected behavior

Chapters should appear

### Actual behavior

Chapters didn't appear, with a massage that says "index 8, size 5".
![Screenshot_20211219-161355_Tachiyomi](https://user-images.githubusercontent.com/83741170/146676259-dcf2102d-c3cf-450f-a594-8e96cc68b663.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10445
