### ISSUE TITLE
I think this extension is better 

### ISSUE THREAD

**Issue by mubeen66613** [tachiyomiorg/tachiyomi-extensions#10165]
### Source name

1stkissmanga

### Source link

https://1stkissmanga.io/

### Language

English 

### Other details

I was reading some bilibili manhuas and encountered payment issues. So I was looking for alternatives. And it looked like many sites weren't out there to solve this, not even mangadex(well there translations weren't always in English). Eventually I came across this website and it gave me the satisfactory result. But Tachiyomi doesn't include this extension but contains a mirror site and that doesn't include those manhuas. So I think maybe this site will be beneficial 🙂🙂

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already exists ("1st Kiss").

**Comment by mubeen66613** [comment]
Well thanks, but I think there has been a misunderstanding. I think it isn't in official version though. Am I right??
Please confirm 🙂

**Comment by arkon** [comment]
> I think it isn't in official version though.

Not sure what that means. The extensions list is the same across the main app and all of the main forks.

**Comment by mubeen66613** [comment]
Well got it now🙂🙂
Thanks for the help (I mean it, you helped a lot) and sorry for bothering you. Got clumsy I guess.
