### ISSUE TITLE
FlameScans Is Super Slow in Tachiyomi

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi-extensions#10160]
### Source information

FlameScans 1.2.11

### Steps to reproduce

Use in any way flame scans and the waiting times are enormous.

### Expected behavior

To be like the website. The website is not slow but super fast, so I don't know what is the problem with the extension.

### Actual behavior

It is slow and unusable.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
This is intentional to not make the app ddos the site
<Insert Tachi DDoS Image Here>
