### ISSUE TITLE
MangaDex status, tags and description not updating automatically

### ISSUE THREAD

**Issue by YuiWelp** [tachiyomiorg/tachiyomi-extensions#10174]
### Source information

MangaDex 1.2.147

### Steps to reproduce

1. Add any manga that gets updated to library
2. After the manga receives it's last chapter and is supposed to get the "Completed" mark it stays on the Ongoing until user manually refreshes it

### Expected behavior

Manga that receives the completed mark on MangaDex site should automatically get it too

### Actual behavior

Manga status, gets stuck on Ongoing or Unknown even though the manga is finished, updated tags and descriptions are also stuck until user resets them manually

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

I refreshed library covers to see if it somehow resets the whole manga, used the "Refresh tracking" and it didn't help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Completed  in Tachiyomi does not mean the same as publication completed on MangaDex, since the scanlation could be behind.

**Comment by YuiWelp** [comment]
My point is that it doesn't update automatically, you have to manually go through everything for it to update. I worded it badly mb.
________________________________

**Comment by CarlosEsco** [comment]
Do you have a sample manga where this occurred?

**Comment by YuiWelp** [comment]
"This Italian Girl Has Become Such a Freeloader" I had to open it and refresh it by hand for it to start counting as "Completed"

Other examples:
"Joshikousei to Seishokusha-san"
"Trap Heroine" this one took me nearly two weeks to find due to the status not updating idk it may be just my problem
________________________________

**Comment by CarlosEsco** [comment]
I believe the problem you are having is because you do not have the enable library info (something along this line) enabled on your tachiyomi library update settings.  So it is only updating the chapter list.

**Comment by YuiWelp** [comment]
Oh shoot, you're right I haven't noticed that option. Thanks for the help and sorry for bothering <3

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
