### ISSUE TITLE
ManhuaFast chapters only load one page

### ISSUE THREAD

**Issue by miyushibana** [tachiyomiorg/tachiyomi-extensions#10171]
### Source information

Manhusfast 1.2.15

### Steps to reproduce

in Manga1st extension open any manhua with new chapters and open the new chapter

### Expected behavior

When you open a new chapter it should load all chapter pages

### Actual behavior

when you open a new chapter it only loads the first page

### Tachiyomi version

0.12.3

### Android version

a11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
Manga1st  or ManhuaFast 
and both work for me
