### ISSUE TITLE
Mic Mic Idol (gravure site)

### ISSUE THREAD

**Issue by 12345axc** [tachiyomiorg/tachiyomi-extensions#10173]
### Source name

Mic Mic Idol

### Source link

https://www.micmicidol.com/

### Language

Japan - Raw

### Other details

Not an manga or anything comic site, but a gravure site from various Japanese magazine and publication.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by PythonCoderAS** [comment]
Why would you use a manga reader app for a gravure site? They're not really structured to have chapters and "mangas".

**Comment by CarlosEsco** [comment]
If the site can work within the constraints of an extension(downloading images and the format/structure tachi can parse) then i see no reason it can't be potentially added.

**Comment by 12345axc** [comment]
@PythonCoderAS Tachiyomi already have E-hentai and some other website that host cosplay, CG, artbook, magazine, etc.

It can be done in similar way as Nhentai or E-Hentai.

**Comment by arkon** [comment]
It's a Blogger site, so chances are low. I'll leave it to whoever may be interested to look more into whether it fits the required structure though.

**Comment by PythonCoderAS** [comment]
@12345axc but ehentai and nhentai have a concept of image and image container -- photos can belong to a gallery, and the gallery provides a method of getting all the images that it has. If what @arkon says is true, then we can't be guaranteed that every post has an image, since blogger is not **primarily** designed to be a gallery.
