### ISSUE TITLE
MG Komik (ID): Chapter Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#10188]
### Source information

MG komik (ID) 1.2.17

### Steps to reproduce

Trying to read any chapter with the mgkomik extension gives back a 403 error. Webview works. List Chapter Work 

### Expected behavior

Being able to read and download the chapter.

### Actual behavior

![Screenshot_2021-12-22-14-22-54-038_eu kanade tachiyomi](https://user-images.githubusercontent.com/23666289/147040514-6680bfe5-da5b-4f37-b4e8-aab5e12e8ab6.jpg)
![Screenshot_2021-12-22-14-22-57-802_eu kanade tachiyomi](https://user-images.githubusercontent.com/23666289/147040522-ccd657a8-390d-4019-bf18-7e689b479c9e.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

No respons

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Update problem
~Http Error 403~

**Failed to Bypass Cloudflare**

**Comment by Riztard** [comment]
/edit-title "MG Komik (ID): Chapter Failed to Bypass Cloudflare"
