### ISSUE TITLE
Comixology

### ISSUE THREAD

**Issue by edgehub-cloud** [tachiyomiorg/tachiyomi-extensions#10184]
### Source name

Comixology

### Source link

https://comixology.com/

### Language

English, official

### Other details

Is it possible to use your own account to accessed purchased stuff or stuff available via comicxlogy premium. I like tachiyomi more and if possible would u guys mind Trying adding it.
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing it since an extension would most likely go against their ToS and would cause accounts being banned from their service. Also would require DRM cracking and it's not something extensions usually does.
