### ISSUE TITLE
Alpha Scans old chapter updates

### ISSUE THREAD

**Issue by DatHypnoboi** [tachiyomiorg/tachiyomi-extensions#10186]
### Source information

Alpha Scans 1.2.11

### Steps to reproduce

1. Add Alpha Scans series to library, such as Trapped in a Webnovel as a Good-for-Nothing 
 2. Mark all chapters as read
 3. Update library

### Expected behavior

No chapters should appear in the updates tab from Trapped in a Webnovel as a Good-for-Nothing, because there are no new chapters, and old chapters should not start downloading. 

### Actual behavior

Old chapters appear in the updates tab and begin downloading. 

### Tachiyomi version

TachiyomiSY 1.7. 0

### Android version

Android 12

### Other details

This issue is taking place on TachiyomiSY instead of vanilla Tachiyomi. Issue was fixed for Flame Scans by setting permanent URLs, but Alpha Scans has no option to do so. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>This issue is taking place on TachiyomiSY instead of vanilla Tachiyomi

Then this is not an issue with alpha scans extension. Please open a ticket on Sy's github or report it on his discord channel
