### ISSUE TITLE
Remove mangabat & mangakakalot

### ISSUE THREAD

**Issue by dtantono** [tachiyomiorg/tachiyomi-extensions#10190]
### Source information

Mangabat & mangakakalot

### Steps to reproduce

I checked in webview that these websites are gone forever and it needs to be removed to prevent confusion. 

### Expected behavior

mangabat and mangakakalot should be removed
![image](https://user-images.githubusercontent.com/29157187/147051012-72d686f1-a3da-48a4-8222-a792054b6944.png)

### Actual behavior

it shows up in the extension tab

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
They are still working fine for me

**Comment by dtantono** [comment]
But, you cannot update it anymore 
![image](https://user-images.githubusercontent.com/29157187/147053343-12ae54ce-6fb1-46ec-91e0-823021e26d32.png)

**Comment by jopejoe1** [comment]
Website still fully load
![kaka](https://user-images.githubusercontent.com/34899572/147053619-adfed2ca-5bcd-434d-ae4c-5bee6fb5aad0.png)

**Comment by arkon** [comment]
Those are fake messages, try using a VPN.

**Comment by dtantono** [comment]
I use proxy site and the website is up and well. But, the tachiyomi webview does not work
![Screenshot_20211222-164432_Tachiyomi](https://user-images.githubusercontent.com/29157187/147054808-00c14110-1567-4c73-ad79-7f0221916222.jpg)

![image](https://user-images.githubusercontent.com/29157187/147054703-ac9b5fe7-b907-4c9d-b47f-71eb49526584.png)

**Comment by dtantono** [comment]
Sorry my bad, I use a VPN and it works normally. So, I think this is a ban from my ISP or JP government and also I think these two sources have been under scrutiny by Japan institutions
