### ISSUE TITLE
Ninemanga.org (Unoriginal)

### ISSUE THREAD

**Issue by Durgesh002** [tachiyomiorg/tachiyomi-extensions#10195]
### Source name

NineManga

### Source link

http://ninemanga.org

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Durgesh002** [comment]
Hey, can the extension renamed as just 'Ninemanga.org' instead of being
'Ninemanga.org (Unoriginal)'? Is it that it will be as you mentioned with
unoriginal?

**Comment by alessandrojean** [comment]
I just renamed the issue title so it will not be closed by mistake as a duplicate. Marked as unoriginal since a website with this name already exists.

The final name of the extension is still up to the person that would work on it.

**Comment by Durgesh002** [comment]
Ok thanks.
