### ISSUE TITLE
Mangabat: Domain changed

### ISSUE THREAD

**Issue by Lovelesscatxxo** [tachiyomiorg/tachiyomi-extensions#10198]
### Source information

mangabat 1.2.8

### Steps to reproduce

1.open browse menu.
2.choose mangabat extension.
3.Issue 1: long delay/timeout.

4.check if website is working via "Go to website" globe icon.
5.issue 2: Website is redirecting.

### Expected behavior

issue 1: the extension should load content in less than 15 seconds at most.

issue 2:the website should go directly to the website which is currently the new website http://m.mangabat.com/m
![image](https://user-images.githubusercontent.com/50358360/147130009-d88b5d3a-072c-4280-a627-c4b79f9f5c27.png)

### Actual behavior

issue 1: the extension takes too long to load and sometimes fails.

issue 2: the website link is the old link http://m.mangabat.com/ which redirects to the official site after a countdown.
![image](https://user-images.githubusercontent.com/50358360/147130053-85176d2f-56fd-46ba-bbc3-75cd44776486.png)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

The website functions perfectly and with no delays or slowness. However, that is not the case on the app and there doesn't seem to be any issue on their end from my personal observation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The redirect page on `https://m.mangabat.com` is for the same domain and shouldn't impact the speed as it's only seen when opening the WebView.

From #10642 it sounds like an issue exclusive to previously added manga, in which case migrating back to MangaBat should solve the issue. It may also be related to intermittent use of [Cloudflare IUAM](https://blog.cloudflare.com/introducing-im-under-attack-mode/).

If this is not the case, do you have any concrete examples of manga that loads slowly?

**Comment by Seishirou101** [comment]
Closing as it seems like a non-issue, you can comment again answering vetleledaal's question if the issue persists.
