### ISSUE TITLE
Why Arab hentai sources didn't add me?

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#10206]
### Describe your suggested feature

Example of Arabic sources :
https://manhatic.com
https://arabshentai.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
- Already requested.
- 1 Issue per source
- Wrong request format

#8060

#6189
