### ISSUE TITLE
IsekaiScan Update Error

### ISSUE THREAD

**Issue by User56477385** [tachiyomiorg/tachiyomi-extensions#10207]
### Source information

IsekaiScans.com 1.2.19

### Steps to reproduce

1. First, is when you update your library It is supposed to be 5-10 minutes because of my 90 manhwa's in my library but in my issue it got 20-30 minutes.
2. Second, is when the update is finished all of those in Manhwa's,Manga etc, in IsekaiScans.com Didn't get an update it just says "Update Failed"
3. Third, is When opening the IsekaiScans.com In Chrome or browser it is okay but when i opened it in Webview using Tachiyomi It cannot load, even though i already tried it with my other phone it is still the same.

### Expected behavior

What should happen is when i clicked the update button it should be atleast 5-10 minutes and when it is finished there should be no "Update Failed" and also i already update all my Extension.

### Actual behavior

What happened instead is it takes me 20-30 minutes even with my 90mbps internet wifi.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![Screenshot_20211223-182149_HTML Viewer](https://user-images.githubusercontent.com/96574060/147229965-fe453da7-fb05-44da-b032-f03ad5eac213.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you're either looking at a different website with a very close name, cloudflare cache, or very lucky. Either way, they're having issues, so nothing can be done 
![1676-1029-max](https://user-images.githubusercontent.com/57241064/147237400-ab074bba-799d-4054-8a49-eaa4cf3c2402.png)
