### ISSUE TITLE
Jinmantiantang: No results found

### ISSUE THREAD

**Issue by BOSSzz** [tachiyomiorg/tachiyomi-extensions#10204]
### Source information

jinmantiantang 1.2.18

### Steps to reproduce

use jinmantiantang extension

### Expected behavior

should show comics

### Actual behavior

not found

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

this extension can was available some days ago but it can't work now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hjm7** [comment]
it on my phone also  can't work

**Comment by YuGhi-bug** [comment]
same problem

**Comment by hagane233** [comment]
me too
