### ISSUE TITLE
Hentaihere

### ISSUE THREAD

**Issue by KlyBly** [tachiyomiorg/tachiyomi-extensions#10219]
### Source name

Hentaihere

### Source link

https://hentaihere.com

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ZeroTaki** [comment]
Also hoping for this as this is a great replacement for the broken hentai2read that probably won't get fixed.
