### ISSUE TITLE
Aura scanlator

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#10218]
### Source name

Aura Scanlator

### Source link

https://www.aurascanlator.com/

### Language

Português pt-br

### Other details

Sei que já sugeri essa extensão, mas queria que vocês dessem uma olhada, que pelo que parece o site deu uma mudada
Me desculpem por qualquer inconveniente

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their search is broken and they're still using a Blogger website.

**Comment by Retashe** [comment]
OK thank you
