### ISSUE TITLE
[Komikcast.com] Failed to check chapter update.

### ISSUE THREAD

**Issue by DOTzX** [tachiyomiorg/tachiyomi-extensions#10217]
### Source information

Komikcast 1.2.20

### Steps to reproduce

1. Goto specific title, example: Seoul Station Druid
2. Check for update (swipe-down)

### Expected behavior

New chapter should arrive.

### Actual behavior

Failed to check chapter update.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Additional Context:
Android System Webview version 96.0.4664.104

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MoonLGH** [comment]
![image](https://user-images.githubusercontent.com/66781351/147399380-d8c05335-a7c3-4d8b-bbc8-31ca042eb2b8.png)
