### ISSUE TITLE
Mangakakalot mangas hosted on Manganato died

### ISSUE THREAD

**Issue by Nyaru3** [tachiyomiorg/tachiyomi-extensions#10226]
### Source information

Mangakakalot 1.2.7

### Steps to reproduce

Open, download and/or update any Mangakakalot manga hosted on Manganato (for example, "Kanojo, Okarishimasu"). You can see that in the "readmanganato.com" comment under the chapter number in the manga dashboard page.

### Expected behavior

Opening, downloading and/or updating properly

### Actual behavior

Some mangas from the Mangakakalot extension (126 out of 633, actually) don't open ("No pages found" message) or update ("Failed to connect to readmanganato.com/127.0.0.1:443" log message). Also, WebView doesn't work ("net::ERR_CONNECTION_REFUSED" error). Problem started 2 or 3 days ago, connecting from Italy.

### Tachiyomi version

TachiyomiSY 1.7.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nyaru3** [comment]
"Missing sources and known issues #3475" seems to refer to a different problem and doesn't help, I'm well aware of the usual Mangakakalot's "Source URL has changed" issue, this seems to be something new related to Manganato.

**Comment by Seishirou101** [comment]
the bot mistook manga host in your title, however your issue sounds like your isp or something a long those lines is blocking the site. I can open them fine. 
>  I have tried the troubleshooting guide.

please actually do what you acknowledge... if you think you have, you can go on discord and get help in #support

**Comment by Nyaru3** [comment]
I'm sorry, what part of the troubleshooting guide I missed that could help me? Because I already checked using a VPN, and I can confirm that https://readmanganato.com doesn't work, it redirects to https://manganato.com. Not sure if that's the problem for the extension, though.

**Comment by Seishirou101** [comment]
![2560-1390-max](https://user-images.githubusercontent.com/57241064/147396123-ff1ae4e3-f122-4579-b340-d1f54b68e802.jpg)
You are correct in that part should/would have helped if you were blocked that is why I told you to go to support in discord if that was the case. The mangakakalot website links the readmanganato url. The ext only gives you the website provides so there is nothing to be done there. However, it does indeed work for me both on desktop and on tachi so it is likely related to you.
