### ISSUE TITLE
[manga source] Animelon

### ISSUE THREAD

**Issue by Slinky5880** [tachiyomiorg/tachiyomi-extensions#10228]
### Source name

Animelon

### Source link

https://animelon.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
> [manga source] Animelon 

where is the manga?

**Comment by alessandrojean** [comment]
Anime-only website. Tachiyomi **does not** support anime as it is only a image viewer.
