### ISSUE TITLE
[KOMIKCAST.COM] HTTP Eror 403

### ISSUE THREAD

**Issue by zeeberr** [tachiyomiorg/tachiyomi-extensions#10229]
### Source information

Komik Cast 1.2.20

### Steps to reproduce

1. Goto Browse > Sources > Komikcast
2. HTTP Eror 403: Check website in WebView

### Expected behavior

Showing lists of manga

### Actual behavior

HTTP Eror 403

### Tachiyomi version

0.12.3

### Android version

7.8.9.10.11.12

### Other details

The website just recovered from DDoS ​​attack

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gusyoga57** [comment]
> ### Source information
> Komik Cast 1.2.20
> 
> ### Steps to reproduce
> 1. Goto Browse > Sources > Komikcast
> 2. HTTP Eror 403: Check website in WebView
> 
> ### Expected behavior
> Showing lists of manga
> 
> ### Actual behavior
> HTTP Eror 403
> 
> ### Tachiyomi version
> 0.12.3
> 
> ### Android version
> 7.8.9.10.11.12
> 
> ### Other details
> The website just recovered from DDoS ​​attack
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6621
