### ISSUE TITLE
IMHentai: Failing to fetch some images

### ISSUE THREAD

**Issue by explicit-hedonic** [tachiyomiorg/tachiyomi-extensions#10220]
### Source information

IMHentai 1.2.3

### Steps to reproduce

1. Click to IMHentai filter button
2. Set `Sort By:` to `Latest` & for 'Other languages`, check all languages
3. Search for the following titles (they are one of the many titles containing .png files with missing leading zeros in their filename)
   - `artist ::: sunnysundown` (go to page `22`, `24`, `25`)
   - `artist Stormbringer` (go to page `19`, `24`)
   - `[Gemuodou (gemuo)] Satomori no Miko Dainishou Choujo` *choose the 2nd result or title containing [Incomplete]* (go to page `4`)

### Expected behavior

Image visible when seeing in Tachiyomi app.

### Actual behavior

No image rendered. `Retry` button does not work in refreshing & getting the image data, even with different devices.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

.jpg and .gif images are rendered fine.

Only **.png** file with **missing leading zeros** in image filename are not rendered at all in Tachiyomi app IMHentai 1.2.3 extension. It works normally in webview and in browser.

These **.png** file with **missing leading zeros** causes the images unfetchable and undownloadable, leading to the complete download status set to be incomplete always due to the missing images.

Is .png file supported in IMHentai? Also, due to the app not recognizing the .png file, the leading zeros is not added and seems to be out of the loop for incrementally naming the filename as the rest .jpg & .gif files.

All the images filename and extension are checked in the Tachiyomi hidden `android/data/eu.kanade.tachiyomi/files/IMHentai(en)` folder itself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "IMHentai: Failing to fetch some images"
