### ISSUE TITLE
Cyanide & Happiness Broken

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#10224]
### Source information

Cyanide & Happiness 1.2.3

### Steps to reproduce

Open extension browse

### Expected behavior

Should load site "pages"

### Actual behavior

Blank Screen due to website update

### Tachiyomi version

0.12.3

### Android version

A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
They don't have a way to list all the available comics anymore so as long as we don't find a way to know what comics exist we can't realy fix this.

**Comment by SuperSonicHub1** [comment]
Anyone looked into scraping the API for this: https://play.google.com/store/apps/details?id=net.explosm.CyanideAndHappiness
