### ISSUE TITLE
Gmanga Http error 103, idex 4, size 2 

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi-extensions#10234]
### Source information

Gmanga 1.2.8

### Steps to reproduce

I update manga in gmanga extension

### Expected behavior

The manga list shoud be updated

### Actual behavior

An error message appears only with manga in the gmanga extension
And when i open the extention it opens naturally
but the error message still appears if i opened or updated any manga in the extention.

### Tachiyomi version

0.12.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicates of #10178
