### ISSUE TITLE
BacaManga

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#10237]
### Source name

BacaManga

### Source link

https://bacamanga.org/

### Language

Indonesian

### Other details

![Screenshot_2021-12-26-19-44-01-11](https://user-images.githubusercontent.com/81138524/147408457-3561f3de-2575-4ec1-9dd8-e39815c6a647.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Uses WPMangaStream theme

**Comment by MoonLGH** [comment]
hasProjectPage true
https://bacamanga.org/project/
