### ISSUE TITLE
supermanga source

### ISSUE THREAD

**Issue by rafalohaki** [tachiyomiorg/tachiyomi-extensions#10244]
### Source name

supermanga

### Source link

using 3 domains with the same updates
https://supermanga.co/
https://mangaleveling.com/
https://isekaiscan.eu/

### Language

English

### Other details

there is no such an extension. recently they bought fake isekaiscan domain to get more ppl but I think they worth it. THey get latest updates

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Uses Madara theme.

**Comment by jopejoe1** [comment]
> https://mangaleveling.com/

This site already has an extension the other 2 don't
