### ISSUE TITLE
WeLoveManga: HTTP error 404

### ISSUE THREAD

**Issue by dhilzyi** [tachiyomiorg/tachiyomi-extensions#10259]
### Source information

WeLoveManga 1.2.9

### Steps to reproduce

When you open the extension WeLoveManga, you eventually can see error says HTTP error 404.

### Expected behavior

this shouldn't be happen because in WebView I can see and can read perfectly

### Actual behavior

When open the extension, the extension shows nothing and error HTTL error 404

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 12345axc** [comment]
Probably related to #9739 #9282
As 1.2.8 and 1.2.9 difference is just an icon update.

**Comment by dhilzyi** [comment]
> Probably related to #9739 #9282 As 1.2.8 and 1.2.9 difference is just an icon update.

just got updated 1.2.9 still says error http 404, I still can see/read the manga through my favorite library from WeLoveManga though I still says error.

**Comment by Saizaku** [comment]
The issue should be that the library request path on the website was changed to `list-manga.html` rather then the `manga-list.html` which the fmreader generator uses.

**Comment by Linnest2020** [comment]
In Tachiyomi Stable 0.14.4 & WeLoveManga 1.4.12, the similar problem happend, it can not aceess the pictures and chapters, search nothing util entered Webview. I assume that it may because the DDoS protection for 5 sec?

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
