### ISSUE TITLE
MangaRock.es: The description has HTML tags

### ISSUE THREAD

**Issue by EverdistantUtopia** [tachiyomiorg/tachiyomi-extensions#10277]
### Source information

MangaRock.es 1.2.2

### Steps to reproduce

Description of man/ga/hwa/hua in code form

### Expected behavior

Normal description

### Actual behavior

![Screenshot_2021-12-30-01-07-58-884_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/89949285/147712146-00882fc2-a54d-4dcb-8510-1a0b456a8ae5.jpg)

### Tachiyomi version

Test version

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "MangaRock.es: The dscription have HTML tags"
