### ISSUE TITLE
Hitomi.la broken

### ISSUE THREAD

**Issue by looipp** [tachiyomiorg/tachiyomi-extensions#10271]
### Source information

Hitomi.la all 1.2.11

### Steps to reproduce

Tried accessing manga from the extension but everyone of them has issues loading and tells you to retry but will not load.

### Expected behavior

Should load the mangs
As

### Actual behavior

Does not load and gives you the retry button

### Tachiyomi version

0.12.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Wolfteam54** [comment]
It is happening to me too, I hope they solve it soon

**Comment by Wolfteam54** [comment]
I still have problems I installed it on another cell phone, it opens and closes
