### ISSUE TITLE
Muito Hentai

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#10276]
### Source name

Muito Hentai

### Source link

www.muitohentai.com

### Language

Português (Brasil)

### Other details

Site 18+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their search is broken (their manga doesn't appear in the search results) and some content does not load.
