### ISSUE TITLE
GMANGA error 400

### ISSUE THREAD

**Issue by Mohammed9457** [tachiyomiorg/tachiyomi-extensions#10275]
### Source information

GMANGA : Version 1.2.8

### Steps to reproduce

The GMANGA extension isn't working,  I keep getting an error message saying: **HTTP error 400** as you can see from the screen shot 
![Screenshot_20211229-223829_TachiyomiJ2K](https://user-images.githubusercontent.com/41828058/147705538-fd99d625-2f4f-4208-b41d-e279012541a1.jpg)
I tried to reinstall it but it didn't fix the problem. 

### Expected behavior

Should load the mangas

### Actual behavior

It instead give an HTTP error 

### Tachiyomi version

0.12.13

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#10161

**Comment by Mohammed9457** [comment]
@arkon Sorry i searched for the issue but that one didn't appear 😅.

**Comment by Semq245** [comment]
وش صار على المشكله انحلت ؟

**Comment by Mohammed9457** [comment]
> وش صار على المشكله انحلت ؟

No

**Comment by Semq245** [comment]
> > وش صار على المشكله انحلت ؟
> 
> No

فيه ثلاث مواقع عربية عطلانه بس عندك خبر يطولون هم ولا كيف ؟

**Comment by Mohammed9457** [comment]
> > > وش صار على المشكله انحلت ؟
> > 
> > 
> > No
> 
> فيه ثلاث مواقع عربية عطلانه بس عندك خبر يطولون هم ولا كيف ؟

ماعندي فكرة عن الموضوع لاكن مابعتقد انهم يطولون.
