### ISSUE TITLE
Dark Room Fansub

### ISSUE THREAD

**Issue by Zahyra16** [tachiyomiorg/tachiyomi-extensions#10274]
### Source name

Dark Room Fansub

### Source link

https://lector-darkroomfansub.blogspot.com/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Dayron15atn** [comment]
Is it possible to create an extension from a blog?
And if possible I hope they do it soon :)

**Comment by vetleledaal** [comment]
Uses ZeistManga v4, which is new to Tachiyomi
