### ISSUE TITLE
Futekiya

### ISSUE THREAD

**Issue by kirimayashi** [tachiyomiorg/tachiyomi-extensions#10285]
### Source name

Futekiya

### Source link

http://read.futekiya.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Pretty sure an extension would be against their ToS (to be more precise, paragraph 6-2) and could cause accounts to be banned from the service.

**Comment by ObserverOfTime** [comment]
I'm pretty sure every publisher has a similar clause in their terms. Like VIZ (§7b) for example.

> You may not use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, "scrape," "data mine" or in any way reproduce or circumvent the navigational structure or presentation of the Sites without VIZ Media's prior written consent.

**Comment by alessandrojean** [comment]
Yeah, they do have. But some ones are more strictly with that (like Kadokawa) and other ones aren't. I just commented to inform about it, since it's an official service. It depends on how Futekiya handles that.
