### ISSUE TITLE
MangaDex: Option to block Bilibili and Comikey

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi-extensions#10291]
### Describe your suggested feature

Since Group block is now live in API.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This would only be useful in the latest view since the ability to do so is only on the chapter list endpoint.  Browse and sorting by latest will still show them all

**Comment by alessandrojean** [comment]
/edit-title "MangaDex: Option to block Bilibili and Comikey"

**Comment by CarlosEsco** [comment]
@curche For this i would prefer
1.  bilibili, mangaplus, comikey and whatever the other one to be blocked always since they dont show in manga view anyways
2. a preference where additional UUID's can be added for a user, so it blocks during latest, and in the manga view

**Comment by curche** [comment]
1. would be good to block all groups marked `official` in /group attributes; sadly I have to find all those manually
2. comma separated UUIDs entered in preference would have to do for now

**Comment by CarlosEsco** [comment]
for 1.  ask dex to search the db for you they should be able to provide a list of uuids

**Comment by jasontbright** [comment]
Hello, found this when a bunch of chapters disappeared from a manga I was reading.  Why are you blocking bilibili by default?  I tried following the issue line and didn't find any explanation.
