### ISSUE TITLE
RawKuma

### ISSUE THREAD

**Issue by Zero1508** [tachiyomiorg/tachiyomi-extensions#10298]
### Source name

raw

### Source link

https://rawkuma.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It already exists.

**Comment by Zero1508** [comment]
i donot find web

**Comment by 12345axc** [comment]
Here: https://tachiyomi.org/extensions/#ja.rawkuma
You should enable Japanese language option to see Japanese extension.
