### ISSUE TITLE
Mangaowl : Domain changed

### ISSUE THREAD

**Issue by opposides** [tachiyomiorg/tachiyomi-extensions#10296]
### Source information

Mangaowl 1.2.23

### Steps to reproduce

open source normally

### Expected behavior

Normally Shows list of mangas 

### Actual behavior

1. doesnt show manga
2. it says "hostname not verified" bc the domain is still mangaowls.com

![Screenshot_20220101-202224_Tachiyomi](https://user-images.githubusercontent.com/96945287/147851800-13a34e07-ec47-4a20-9071-87d5272ed077.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

the original domain (mangaowls.com) got blocked in my country and it changed name to mangaowl.com. i found out that the domain in the app is still mangaowls.com

![Screenshot_20220101-204150_Samsung Internet](https://user-images.githubusercontent.com/96945287/147851936-78cb6043-6cc2-451e-8873-9fccbf21c1d2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
mangaowls.com still works so that is probably a copycat, not our fault your country blocks it. use a vpn or something similar or migrate.
