### ISSUE TITLE
Support for full-screen stretch

### ISSUE THREAD

**Issue by Lisso-lab** [tachiyomiorg/tachiyomi-extensions#10301]
### Describe your suggested feature

![Screenshot_20220102-000222_TachiyomiJ2K](https://user-images.githubusercontent.com/85261069/147861860-5748912f-f77b-4c61-9e08-fa068b1bceaa.jpg)
You can see at provided screenshot that there is black bar, and that is caused via enabling full screen apps: 
![Screenshot_20220102-000426_Settings](https://user-images.githubusercontent.com/85261069/147861895-9ca8e970-7021-4272-97f3-6e41dd598a99.jpg)
As such.

I cant be sure but there should be property for checking this android. 

### Other details

Im using fork called TachiyomiJ2K, but Tachiyomi should be same on this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong repo. Also please confirm if it's actually the case in the main app before making an issue.
