### ISSUE TITLE
Mangachill having pages not found

### ISSUE THREAD

**Issue by lovablesweet35** [tachiyomiorg/tachiyomi-extensions#10315]
### Source information

Manga chill

### Steps to reproduce

1.open the source which is mangachill
2.multiple manhwa is showing no pages such as titles: A Symbiotic Relationship Between A Rabbit And A Black Panther, A Capable Maid, and so on. Only 3 to 5 manhwa has chapters on my list.
3. Reading is not possible due to having no pages.

### Expected behavior

I have already read the chapter and it had pages before.

### Actual behavior

Pages no longer readable even though it is marked read.

### Tachiyomi version

0.12.3

### Android version

S21

### Other details

A staff has told that it may be a broken extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Both titles are working for me. @lovablesweet35 can you try with latest version?

**Comment by lovablesweet35** [comment]
> Both titles are working for me. @lovablesweet35 can you try with latest version?

Yep its working now thank you.
