### ISSUE TITLE
MangaSwat: pages dont load

### ISSUE THREAD

**Issue by zeredouni** [tachiyomiorg/tachiyomi-extensions#10318]
### Source information

mangaswat-v1.2.16

### Steps to reproduce

1. load any chapter of any manga

### Expected behavior

pages should load

### Actual behavior

gives error 'no pages found'

### Tachiyomi version

0.12.3

### Android version

android 7.1

### Other details

overrode url to [https://swatmanga.co](https://swatmanga.co)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Semq245** [comment]
متى يحلون المشكله عندك خبر يطولون هم ولا كيف ؟

**Comment by Saud-97** [comment]
The same issue have returned for the latest version of the extension v1.2.20.
No pages found error when opening/download a chapter. Works fine in WebView.

**Comment by midou221** [comment]
The site has only changed the links for chapters images to script
I think this will solve the problem

```
    private ArrayList<MangaPage>  scraperJsonElementSource(Document document){
        ArrayList<MangaPage> pages = new ArrayList<>();
        MangaPage page;
        try {
        Elements elementsMain = document.getElementsByTag("script");
        for (Element element : elementsMain) {
            if (element.data().contains("ts_reader")) {
                String removeMain = element.data().replace("ts_reader.run(", "").replace(");", ""); //object

                    JSONObject jsonObjectMain = new JSONObject(removeMain);
                    JSONArray sourcesObject = jsonObjectMain.getJSONArray("sources");
                    JSONArray imagesArray = sourcesObject.getJSONObject(0).getJSONArray("images");

                for (int i = 0; i < imagesArray.length(); i++) {
                    Object element2 = imagesArray.get(i);
                    page =  new MangaPage(element2.toString());
                    page.provider = Mangaswat.class;
                    pages.add(page);
                }
            }
        }
            return pages;

        } catch (JSONException e) {
            e.printStackTrace();
            return null;
        }
    }
```

**Comment by Saud-97** [comment]
If you have found a fix then please open a PR and reference that it closes this issue.

**Comment by houxemiya** [comment]
Still not working so far...
