### ISSUE TITLE
Hitomi.la doesn't work (403)

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi-extensions#10319]
### Source information

Hitomi.la 1.2.15

### Steps to reproduce

1. Open a manga in Hitomi.la
2. Read the manga.

### Expected behavior

Should load the manga pages

### Actual behavior

Showed the error "ReferenceError: identifier 'document' undefined"

### Tachiyomi version

Tachiyomij2k v1.4.4

### Android version

Android 7

### Other details

Xiaomi Redmi 4a
Android 7
2gb ram
16gb storage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mastaqpokemon** [comment]
Same issue occurred on Android 10 as well. First it was ReferenceError: identifier 'document' undefined, after restarted the phone just for good measure, it became ReferenceError: identifier 'gg' undefined.

**Comment by Basara-Hatake** [comment]
They keep changing it so that it breaks. For the record i personally wont bother fixing it anymore.

**Comment by mastaqpokemon** [comment]
Will just wait until they stop changing it. As it quite a pain to keep fixing it.

**Comment by alessandrojean** [comment]
They will probably keep changing things always when the extension is fixed. It's a cat and mouse game. It's better to migrate to other sources.

**Comment by ChenNdG** [comment]
Now the issue change to Error 403 ...

**Comment by 12345axc** [comment]
In case someone looking for alternative, a lot of Hitomi.la content is originally from E-Hentai.

**Comment by alessandrojean** [comment]
@12345axc Please do not recommend extensions.

> #### What source is the best / most popular / recommended? What is the replacement for source X? Where should I read manga Y?
> We don't recommend any sources. This is because Tachiyomi userbase is huge and recommending sources in the past caused them to go down. This has led to sources blocking Tachiyomi or intentionally breaking the extensions, asking to be removed from Tachiyomi, brigading our repositories with spam, or getting slower and slower until they stop working due to too many users.

**Comment by ChenNdG** [comment]
Even after the update I still have the 403 error, when I open with the webview the site works well and seem no problem with cloudflare

**Comment by arkon** [comment]
Please note that the update is not related to this issue.

**Comment by BrutuZ** [comment]
Apparently their subdomain is just checking for the `Referer` header now
![Console](https://i.imgur.com/kByGVkt.png)

**Comment by alessandrojean** [comment]
Keep in mind they're in a cat and mouse game with us, even if we update to add the Referer header, they will just change any other thing to break the extension again.

**Comment by alessandrojean** [comment]
Closing as the extension was removed (refer to #11613).
