### ISSUE TITLE
Toptoon+ not showing all the chapters

### ISSUE THREAD

**Issue by ajjmin** [tachiyomiorg/tachiyomi-extensions#10337]
### Source information

Toptoon+ 1.2.1

### Steps to reproduce

Toptoon+ extension
A brave new world webtoon

### Expected behavior

![Screenshot_20220105-001803029](https://user-images.githubusercontent.com/48009480/148101782-5f76211a-0e52-4c2b-aa11-ecb8a55ad9e2.jpg)

I can see other chapters using WebView but not available on actual app.

### Actual behavior

![Screenshot_20220105-001748922](https://user-images.githubusercontent.com/48009480/148101860-6e62e034-1c36-44eb-80d8-34c7f22cc34d.jpg)

Only 5 chapters available

### Tachiyomi version

Tachiyomi J2K 1.4.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension only shows the free chapters, it's intentional.
