### ISSUE TITLE
Error in extension 

### ISSUE THREAD

**Issue by Semq245** [tachiyomiorg/tachiyomi-extensions#10347]
### Source name

Swatmanga 

### Source link

https://swatmanga.com/

### Language

Arabic

### Other details

![Screenshot_٢٠٢٢٠١٠٥-٠٣٠٤٥١_Tachiyomi](https://user-images.githubusercontent.com/97077925/148140452-17be4e95-6145-4e0a-9679-9ddb10864111.jpg)
  I get an error and ask to try again when I open every chapter of this site

![Screenshot_٢٠٢٢٠١٠٥-٠٣٠٥١٨_Tachiyomi](https://user-images.githubusercontent.com/97077925/148140759-5edc35d7-a689-4c5e-abb5-de516e2c3c04.jpg)
This source is not working because they changed the website link  

![Screenshot_٢٠٢٢٠١٠٥-٠٣٠٦٠٤_Tachiyomi](https://user-images.githubusercontent.com/97077925/148140857-5c045670-7f25-4507-8862-e520541cf6b5.jpg)

 And when I search, I can't find the new site, so please add it ؟؟

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Semq245** [comment]
Sorry this is the correct link  
https://swatmanga.co/

**Comment by CrepeTF** [comment]
#10318

**Comment by Semq245** [comment]
So is the problem solved are u add new link ?

**Comment by arkon** [comment]
Do not create spam issues.
