### ISSUE TITLE
Gemanga - page not found

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#10346]
### Source information

Gmenga 1.2.16

### Steps to reproduce

1. Thinking of reading
2. Clicking on source
3. Doesn't work

### Expected behavior

Work!

### Actual behavior

Not work

### Tachiyomi version

12.3

### Android version

10

### Other details

![IMG_20220104_221200](https://user-images.githubusercontent.com/61906880/148124803-d836281e-8fe3-4708-b934-e63827588a6d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#10161

**Comment by shipoxx** [comment]
I forget to check before
