### ISSUE TITLE
ReadComicOnline's extension cannot fetch pages anymore

### ISSUE THREAD

**Issue by avillev** [tachiyomiorg/tachiyomi-extensions#10351]
### Source information

ReadComicOnline english 1.2.10

### Steps to reproduce

This works on any comics it seems, and started happening a few days before the creation of this ticket.

- take a comic (ex: gen13 (2006))
- start it

### Expected behavior

The page displays

### Actual behavior

A "no pages found" error will occur. 

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NotPageD** [comment]
it's working perfectly fine for me...

**Comment by avillev** [comment]
It stopped working for 3/4 days and came back since. I assume the web site had an issue. We can close this ticket.
