### ISSUE TITLE
Gmanga doesn't work

### ISSUE THREAD

**Issue by ahmedben19** [tachiyomiorg/tachiyomi-extensions#10370]
### Source information

Gmanga 1.2.8

### Steps to reproduce

When I open the extension Page 
"HTTP error 103" shows up
![Screenshot_20220106-082143](https://user-images.githubusercontent.com/83753944/148344624-08b7db13-15a1-4737-a1df-09db93c34324.png)

### Expected behavior

It should show me the manga

### Actual behavior

It show "HTTP error 103"

### Tachiyomi version

0.12.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
"I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue."

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10178
