### ISSUE TITLE
MMScans stopped working after site migration

### ISSUE THREAD

**Issue by XxZombiePikachu** [tachiyomiorg/tachiyomi-extensions#10396]
### Source information

MMScans 1.2.16

### Steps to reproduce

Try to look at any manga from MMScans in tachiyomi.

### Expected behavior

You can see manga chapters in web form, when pulling new chapters it finds and populates them.

### Actual behavior

Because they changed domains you get a webpage error/DNS not resolved when accessing web form view, when looking for updates tachiyomi just gives an error "connection closed".

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

MMScans completed a migration of their website today and have moved from https://mm-scans.com/ to https://mm-scans.org/
I believe this is the cause of the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
![Screenshot_2022-01-09-00-20-39-17](https://user-images.githubusercontent.com/79831076/148651678-ef745435-c6c9-410a-8868-62b2d0a89099.jpg)
