### ISSUE TITLE
Shea Manga ganti domain

### ISSUE THREAD

**Issue by Mugenjin07** [tachiyomiorg/tachiyomi-extensions#10392]
### Source information

Sheamanga 1.2.13

### Steps to reproduce

1 mengupdate versi ekstensi
2 mengganti domain yang terdapat di ekstensi
3 di web viewnya bisa teebuka halaman webnya karena domainnya otomatis berganti jika domain di ekstensi diganti pasti bisa di buka kembali

### Expected behavior

Seharusnya menampilkan manga yang terdapat di web bersangkutan dengan ekstensi
![Uploading Screenshot_20220108-101647090.jpg…]()

### Actual behavior

Di dalam aplikasi tidak dapat menampilkannya karena berbeda domain
![Screenshot_20220108-101912367](https://user-images.githubusercontent.com/82618225/148629462-e3cc2d6b-b91f-46cc-a40c-14866110e139.jpg)

### Tachiyomi version

Stable 0.12.3

### Android version

Android 10

### Other details

![Uploading Screenshot_20220108-101647090.jpg…]()
![Screenshot_20220108-101912367](https://user-images.githubusercontent.com/82618225/148629247-0a7f6df4-4571-4cc9-a07b-587c36848774.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arozaqf** [comment]
do you not english?
