### ISSUE TITLE
[Bug] <Bato.to ext>: <global searches return no results>

### ISSUE THREAD

**Issue by cecoates** [tachiyomiorg/tachiyomi-extensions#10401]
### Source information

tachiyomi-all.batoto-v1.2.18.apk

### Steps to reproduce

1. Search for a common term in global search, i.e. "villainess".
2. No search results for the Bato source.
![Screenshot 2022-01-08 20 49 03_edited](https://user-images.githubusercontent.com/10121835/148667294-3562d142-7297-4889-8e5a-fe0d5994bdc9.jpeg)
3. From Browse click on the Bato extension. Then click on the search icon within the Bato extension.
4. Search for the same term again, i.e. "villainess".
5. Now results are successfully found.

### Expected behavior

Search results should appear in the global search, not just when you specifically search via Browse->Bato.

### Actual behavior

No results are returned. Started after the last extension update.

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

Global searches when you click on a title within your library also return zero results. Even if you added that title via Bato in the first place and Bato is listed as the source.

Titles you've already added via Bato do seem to update correctly. You just can't easily search for new titles anymore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cecoates** [comment]
Just to be sure, I checked and same behavior occurs in v1.2.19.

**Comment by kyarosku** [comment]
this also extends to the migration search--cannot migrate from one source to a bato.to source (even if the source is in library already)
