### ISSUE TITLE
mangadex filds [hash, data, datasaver] are missing

### ISSUE THREAD

**Issue by Elicraftpvp** [tachiyomiorg/tachiyomi-extensions#10409]
### Source information

mangadex 1.2.150

### Steps to reproduce

try to load a manga chapter
error: ! Fields [hash, data, dataSaver] are required for type with serial name 'exh.md.dto.ChapterAttributesDto', but they were missing

### Expected behavior

load the chapters

### Actual behavior

dont load the chapters

### Tachiyomi version

1.7.0

### Android version

Android 11

### Other details

is just in mangadex extension, other sources are ok, in web view mangadex mage load normally

this shoud be a small change in mangadex API.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>1.7.0
Wrong repo since that's TachiyomiSy. Report to the correct repo or ask at the Discord Server

**Comment by arkon** [comment]
Update your extension.
