### ISSUE TITLE
Mangasail extension issue while updating manga or from library

### ISSUE THREAD

**Issue by cmurabito5** [tachiyomiorg/tachiyomi-extensions#10404]
### Source information

Mangasail 1.2.3

### Steps to reproduce

Description: Library update issue for a while for Mangasail, although multiple manual refreshes work

Step1: Refresh the library or refresh any manga from the source

### Expected behavior

Manga should be updated with newest chapters without any error

### Actual behavior

! Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
  # Mangasail (EN)
    - One Punch-Man

### Tachiyomi version

Tachiyomi SY Preview r425

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce, but from the error message it must be one of these lines causing it to fail:
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/6935c22ba4a9219b33fd527fab7fa9b12e9df281/src/en/mangasail/src/eu/kanade/tachiyomi/extension/en/mangasail/Mangasail.kt#L133
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/6935c22ba4a9219b33fd527fab7fa9b12e9df281/src/en/mangasail/src/eu/kanade/tachiyomi/extension/en/mangasail/Mangasail.kt#L120

**Comment by cmurabito5** [comment]
![Screenshot_2022-07-02-09-48-18-340_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/97380054/176986213-93d5980a-6d4b-4429-882f-60fa83cc77a9.jpg)
Try with the above mentioned manga (grand blue), able to reproduce by refreshing it in the library. The onepunch man manga seems to have been fixed itself from one of the tachi preview maybe.

Hope this helps!

**Comment by vetleledaal** [comment]
Thanks, that helped narrow it down. The issue was actually caused by an empty artist field, I'll submit a PR addressing this shortly.
