### ISSUE TITLE
Kumanga is broken

### ISSUE THREAD

**Issue by Dannylol12** [tachiyomiorg/tachiyomi-extensions#10414]
### Source information

Kumanga 1.2.7

### Steps to reproduce

![Screenshot_20220109-004155_TachiyomiJ2K](https://user-images.githubusercontent.com/97404576/148696264-5aae04c1-7dc1-4202-852a-03637593be94.jpg)
Comes from the extension of kumanga

### Expected behavior

![Screenshot_20220109-004155_TachiyomiJ2K](https://user-images.githubusercontent.com/97404576/148696206-11d96fb3-44b5-4cc7-b053-94c593a06d56.jpg)

### Actual behavior

![Screenshot_20220109-004155_TachiyomiJ2K](https://user-images.githubusercontent.com/97404576/148696192-e36afc0b-8b5c-4321-b5da-26f2cc506315.jpg)

### Tachiyomi version

1.4.4

### Android version

11

### Other details

![Screenshot_20220109-004155_TachiyomiJ2K](https://user-images.githubusercontent.com/97404576/148696231-85f43f6d-af81-4610-911c-0674647e5a7f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Sorry, could you send a video recording of the issue.

**Comment by Epetit555** [comment]
I have the same problem.
![Screenshot_20220113-221205_Tachiyomi](https://user-images.githubusercontent.com/97703479/149410728-dee2aacb-a0f8-4c59-8ba6-64d058e6caa0.jpg)
![Screenshot_20220113-221239_Tachiyomi](https://user-images.githubusercontent.com/97703479/149410714-c94dc15c-f1db-41b1-a6eb-f54113b130a9.jpg)

**Comment by michelord** [comment]
I have the same problem Kumanga detect malicious use  If I access from tachiyomi. But from an external browser it doesn't

**Comment by michelord** [comment]
I have the same problem Kumanga detect malicious use  If I access from tachiyomi. But from an external browser it doesn't
