### ISSUE TITLE
Gmanga http error 103 invalid index 4.size 2

### ISSUE THREAD

**Issue by saidsahra15** [tachiyomiorg/tachiyomi-extensions#10438]
### Source name

Gmanga

### Source link

www.gmanga.org

### Language

Arab

### Other details

The source gives two different problems.  First, when you open the manga in your favorites list or try to update it, it responds, http error 103 invalid index 4 size 2   /and secondly when you use source in explorer the response will be http 400 but the WebView work without problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
#10178
#10161

**Comment by saidsahra15** [comment]
Can you fix it

**Comment by CarlosEsco** [comment]
It's an open source app, anyone can contribute and fix extensions.  If there is an arab speaking dev that wants to fix it they can PR a fix.  If not then you wait or use a different source.
