### ISSUE TITLE
Dragon Translation: Missing chapter name

### ISSUE THREAD

**Issue by Marco-kun** [tachiyomiorg/tachiyomi-extensions#10435]
### Source information

Dragon Traslation 1.2.19

### Steps to reproduce

No aparecen los números de los capítulos en los manhwas

### Expected behavior

Que aparezcan que capítulo es y que fecha se subió 

### Actual behavior

Al ingresar manhwa aparecen en negro sin saber cuál capítulos es cual 
![Screenshot_2022-01-11-21-55-17-587_eu kanade tachiyomi](https://user-images.githubusercontent.com/85567345/149045378-4f79c9d9-0521-447a-980b-a1a0a1078f9a.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DarkDissaster** [comment]
La extensión no funciona

**Comment by vetleledaal** [comment]
Can't reproduce.
![pcbAm9T3Yx](https://user-images.githubusercontent.com/13540478/176980166-ae2be29f-f394-4732-bc08-e5f35739461d.png)
