### ISSUE TITLE
MangaDex: Add uploader blocks

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi-extensions#10432]
### Describe your suggested feature

The MangaDex API allows filtering out uploads by specific groups or uploaders. The extension already has the group blocking feature implemented (https://github.com/tachiyomiorg/tachiyomi-extensions/pull/10376), this request is to add the uploader-blocking functionality to the extension,.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
You hate some uploader? lol

**Comment by CarlosEsco** [comment]
You hate some uploader? lol

**Comment by BraveDude8** [comment]
https://api.mangadex.org/docs.html#operation/get-manga-id-feed

excludedUploaders[]

@CarlosEsco Long-requested feature in v3 to block no-group uploaders.

**Comment by kiriya-aoi** [comment]
There are more than a few uploaders who don't use groups that I have wanted to block for a long time.
