### ISSUE TITLE
Shimada Scans webview on but nothing shown in app

### ISSUE THREAD

**Issue by researchscum** [tachiyomiorg/tachiyomi-extensions#10431]
### Source information

Shimada Scans 1.2.11 [eu.kanade.tachiyomi.extension.en.shimadascans]

### Steps to reproduce

1. Access Browse ot Latest

### Expected behavior

Show list of comics

### Actual behavior

Doesn't show anything.

### Tachiyomi version

Version 0.12.3-4083

### Android version

Android 10.0

### Other details

Shimada web up
accessible from webview
none on the "Missing sources and known issues"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by researchscum** [comment]
up

**Comment by Riztard** [comment]
fixed by that pr
