### ISSUE TITLE
Junmei tu: Fail to download any gravure

### ISSUE THREAD

**Issue by 12345axc** [tachiyomiorg/tachiyomi-extensions#10439]
### Source information

Junmei tu 1.2.1

### Steps to reproduce

1. Open any entry
2. Click download button
3. Progress always stuck in the end, leading to fail operation

### Expected behavior

Download clear, and the gravure can be accessed

### Actual behavior

Progress always stuck in the end, for example: 56/56 downloaded, but not complete.

### Tachiyomi version

0.12.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 12345axc** [comment]
Ah, also
Group filter always fail to search any group name with space or dot.

**Comment by jopejoe1** [comment]
> Ah, also Group filter always fail to search any group name with space or dot. for example: `Bomb.tv` and `Weekly Playboy`.

Space and dot need to replaced with `_`

**Comment by tatular** [comment]
is there any work around to download from junmei tu?
