### ISSUE TITLE
Manhwahentai.me: No pages found

### ISSUE THREAD

**Issue by randw0** [tachiyomiorg/tachiyomi-extensions#10436]
### Source information

Manhwahentai.me 1.2.17

### Steps to reproduce

1. Open any manga on the manwhahentai.me extension
2. Try to open a chapter

### Expected behavior

Chapter loads

### Actual behavior

No pages found error

### Tachiyomi version

0.12.3-4083

### Android version

12 (SDK 31)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce.

https://user-images.githubusercontent.com/13540478/176981451-6d31860d-4f38-47e9-9d81-3b40d2693387.mp4

**Comment by Seishirou101** [comment]
if the issue still occurs you can comment or make a new issue.
