### ISSUE TITLE
Madokami: HTTP error 404 due to special characters in url

### ISSUE THREAD

**Issue by Sebleux** [tachiyomiorg/tachiyomi-extensions#10447]
### Source information

Madokami 1.2.5

### Steps to reproduce

Search and select **Jitsu wa Ore, Saikyou deshita?** in the Madokami source on Tachiyomi.

### Expected behavior

No error and the chapters should be displayed.

### Actual behavior

HTTP error 404 and no results.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

The manga **Jitsu wa Ore, Saikyou deshita?** exist in Madokami and contains 5 files. However you get a 404 error on Tachiyomi. I think the problem is due to the comma and the question mark in the url. The actual url for the manga on Madokami is : 

https://manga.madokami.al/Manga/J/JI/JITS/Jitsu%20wa%20Ore%2C%20Saikyou%20deshita%3F

The one Tachiyomi links to is : 

https://manga.madokami.al/Manga/J/JI/JITS/Jitsu%20wa%20Ore,%20Saikyou%20deshita

The "," is not encoded and "%3F" (ASCII for "?") is missing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by swosho** [comment]
Can confirm, happens with **Nande Koko ni Sensei ga!?** as well.

**Comment by mage-goo** [comment]
Can confirm that this still happens on Madokami 1.4.5 and on app 0.14.5
Also happens to [Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?](https://manga.madokami.al/Manga/M/MA/MAOU/Maou%20no%20Ore%20ga%20Dorei%20Elf%20wo%20Yome%20ni%20Shitanda%20ga%2C%20Dou%20Medereba%20Ii%3F)

Probably just need to sanitize reading the URL on [this line](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt#L87) and [this line](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt#L112), but I don't really have kotlin experience to do it myself.

**Comment by mage-goo** [comment]
Seems like changing [this line](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt#L69) into a simple `manga.url = element.attr("href")` is enough?
