### ISSUE TITLE
JMana: Chapter images do not load

### ISSUE THREAD

**Issue by jn1106** [tachiyomiorg/tachiyomi-extensions#10446]
### Source information

JMana 1.2.14

### Steps to reproduce

1.load any manga chapter

### Expected behavior

Pages load

### Actual behavior

The pages do not load

### Tachiyomi version

tachiyomi 0.12.3

### Android version

android 12

### Other details

Override BaseUrl : https://4.jjmana.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "JMana: Chapter images do not load"
