### ISSUE TITLE
Flame Scans prologue marked unread

### ISSUE THREAD

**Issue by DatHypnoboi** [tachiyomiorg/tachiyomi-extensions#10440]
### Source information

Flame Scans 1.2.12

### Steps to reproduce

1. Add "The Last Golden Child" to library
2. Mark prologue as read
3. Update series

### Expected behavior

"Chapter Prologue" should remain as read

### Actual behavior

"Chapter Prologue" is marked as unread

### Tachiyomi version

TachiyomiSY 1.7.0 + preview r426

### Android version

Android 12

### Other details

Tested on TachiyomiSY, both stable and preview builds 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
I can't reproduce this, does this still happen to you?

**Comment by vetleledaal** [comment]
Can't reproduce.

https://user-images.githubusercontent.com/13540478/176981738-a03cbf7c-d3fa-41d1-8cc3-270038c7fe73.mp4

**Comment by Seishirou101** [comment]
closed due to user not answering and can't be reproduced
