### ISSUE TITLE
Mangaowl: no pages found

### ISSUE THREAD

**Issue by awchau** [tachiyomiorg/tachiyomi-extensions#10453]
### Source information

Mangaowl 1.2.23

### Steps to reproduce

1. click chapter and wait for pages to load

### Expected behavior

The pages of the chapter should load for reading.

### Actual behavior

Jumps back to chapter list with a notif saying that there were no pages found.

### Tachiyomi version

 0.12.3

### Android version

Android 11

### Other details

I have already cleared the cache and cookies and everything.  I also tried to load up on webview and it works perfectly find and even loads up the chapters there. This happens with most of the titles from mangaowl that i could find saved in my library. It was also working fine right before the issue started (i.e i was finishing a chapter and loading a new one when jt occurred).
![Screenshot_20220114-052344_Tachiyomi](https://user-images.githubusercontent.com/60052922/149388681-77d1752c-a9b8-47e5-bf6b-75fce68018b1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hist0ri4** [comment]
You got any idea about when it'll be fixed?

**Comment by CaptainH2005** [comment]
#10461 #10460

**Comment by CaptainH2005** [comment]
Mangaowl #10460
