### ISSUE TITLE
Fenix Scanlator: Changed their name and domain

### ISSUE THREAD

**Issue by deividgabrielpeira** [tachiyomiorg/tachiyomi-extensions#10457]
### Describe your suggested feature

The extension: "Fenix ​​Scanlator" changed to "Mango Scan BR".

Therefore the fenixscanlator site was deleted and was migrated to "https://yugenmangas.com.br/"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Fill the ***issue report*** form next time.

**Comment by alessandrojean** [comment]
/edit-title "Fenix Scanlator: Changed their name and domain"

**Comment by alessandrojean** [comment]
Just to keep in the records that one of the "website owners" (don't actually checked) asked to an extension not to be made, but the request was denied since their website is actually an aggregator instead of a scanlator (that hosts only their own stuff).
