### ISSUE TITLE
MangaOwl is broken

### ISSUE THREAD

**Issue by Whattamellon** [tachiyomiorg/tachiyomi-extensions#10463]
### Source information

MangaOwl 1.2.24

### Steps to reproduce

1) Attempt to open any chapter. It doesn't seem to matter if the "play" button or direct-click on the chapter entry is used.
2) Error immediately pops up.

### Expected behavior

Chapter begins loading in the reader interface.

### Actual behavior

App remains on chapter list and error alert flashes at screen bottom. Error text: "Expected URL scheme 'http' or 'https' but no colon was found."

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sevencooper** [comment]
Not sure if this is the exact same issue but I ran into something similar. Try refreshing the chapter list - swipe down on a manga's page to reveal a loading icon.

Seems like the 1.2.24 patch updated the URL fetching logic - doing a refresh should update the chapter URLs using the new logic, this did the trick for me.

**Comment by Fujin-sama** [comment]
Plss fix the MangaOwl Extension for version 0.13.1, cause its hard to migrate all of the manga's i have in mangaowl to another extension
Plss fix it

**Comment by Yuhssification** [comment]
#10453

**Comment by Yuhssification** [comment]
Mangaowl Extension is broken for months now.  Please fix it.

**Comment by Fujin-sama** [comment]
Please fix the Mangaowl extension. It's been broken for almost 2 months

**Comment by Fujin-sama** [comment]
Please Fix the MangaOwl Extension already please
