### ISSUE TITLE
Mangaowl - no pages found

### ISSUE THREAD

**Issue by qnrrr01** [tachiyomiorg/tachiyomi-extensions#10462]
### Source information

Mangaowl 1.2.23

### Steps to reproduce

1. Opened tachiyomi
2. Choose the manga from mangaowl source
3. Choose the chapter
4. It doesn't open. 
5. It says no pages found

### Expected behavior

Loading for a few second and than opened.

### Actual behavior

Loading a few second and fo back to chapter interface saying no pages found

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

This happen for all the manga from mangaowl and sadly this is not the first time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

#10453
