### ISSUE TITLE
Not all manga/manhwa are being checked for updates

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi-extensions#10477]
### Source information

N/A

### Steps to reproduce

1. Refresh Library
2. Check Notification

### Expected behavior

Denominator should have the number of manga total

### Actual behavior

Only 40-50 are being checked

### Tachiyomi version

r4090

### Android version

Android 12 (Pixel Experience ROM)

### Other details

It's not a problem in the settings, since I didn't set the checking to just the ongoing.
![Screenshot_20220116-131710_Tachiyomi](https://user-images.githubusercontent.com/49813589/149648478-99ac34d9-d512-42d6-be28-4b0d364ad101.png)
![Screenshot_20220116-131714_Tachiyomi](https://user-images.githubusercontent.com/49813589/149648479-ac50c595-7360-4f6b-8eee-22dfc462833e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
multiple things to note:
1. > If this is an issue with the app itself, I should be opening an issue in the app repository.

2. youre using the Preview version, this was listed in the changelog for recent changes. In particular, [R4067](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r4067). So, not a bug

3. there is no real reason for updating all 248 manga in your library. You'll just end up spamming the website that usually leads to either the website blocking the app or the source becoming dead. Consider using [Categories](https://tachiyomi.org/help/guides/categories/) and update only 50 titles.
