### ISSUE TITLE
Loading pages take time of most extensions

### ISSUE THREAD

**Issue by AaronDragneel** [tachiyomiorg/tachiyomi-extensions#10478]
### Source information

Most extensions like Mangasee, Manga Rock Team and Manga-Raw.club

### Steps to reproduce

I try to open a manhwa or or manga but it takes a lot of time to load and sometimes it doesn't load.

### Expected behavior

It should load quickly.

### Actual behavior

it shouldn't take time to load.

### Tachiyomi version

TachiyomiJ2K Version. 1.4.4.

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#troubleshooting) first or ask for help in the [Discord server](https://discord.gg/tachiyomi) first. If it still doesn't fix it, open an individual issue for each extension later.
