### ISSUE TITLE
Not opennable

### ISSUE THREAD

**Issue by MangaFreak07** [tachiyomiorg/tachiyomi-extensions#10470]
### Source information

Shimadascans

### Steps to reproduce

You click on it : website issue

### Expected behavior

Get fixed so you can read on the extension Shimadascans

### Actual behavior

Nothing

### Tachiyomi version

Can't look at it or else I have to write everything again

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the form appropriately next time, this one isn't giving useful details about the issue.
