### ISSUE TITLE
Mangadex Chapters not displayed in tachiyomi 

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#10476]
### Source information

Mangadex 1.2.151

### Steps to reproduce

Open title I, the Strongest Demon, Have Regained My Youth?! on mangadex through tachiyomi only chp 51 are displayed 
Link https://mangadex.org/title/f6e7ce00-e09c-4ed2-b806-eb2fdc7a5f60

Through website can read 57

No redirect to other website required still inside tachiyomi these chapters not displayed

### Expected behavior

All uploaded chapters that are available to read on mangadex ( and do not require redirecting to external site) should be available to read through tachiyomi.

### Actual behavior

Chapters missing in various titles not jst the one given above as an example.

Few other titles : City of Sanctuary, Xiu Tu, Yuan Long, I Just Had to Pick up a Female Disciple, etc

### Tachiyomi version

App version: 0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Remove the Bilibili group UUID from the "Block groups by UUID" preference in the MangaDex extension settings.
