### ISSUE TITLE
Qiman56

### ISSUE THREAD

**Issue by RyomeSukuna** [tachiyomiorg/tachiyomi-extensions#10473]
### Source name

Qiman56

### Source link

http://qiman56.com/

### Language

Chinês

### Other details

Leitura.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the issue title appropriately with the website name next time, instead of just writing "Solicitação de extensão" every time.

It's better if you fill the form in English too.

**Comment by anenasa** [comment]
Duplicate of #4663?

**Comment by alessandrojean** [comment]
Looks like a mirror, yes. Closing it.
