### ISSUE TITLE
Anxious Frogs

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#10488]
### Source name

Anxious Frogs 

### Source link

https://www.anxiousfrogs.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
Domain is suspended.
![image](https://user-images.githubusercontent.com/84634607/150342379-5736e850-4a29-4e93-b636-c0c57ca6cb24.png)

**Comment by vipzzx** [comment]
The website is up
https://www.anxiousfrogs.com/
