### ISSUE TITLE
Manhwa18.cc: Can't download chapters

### ISSUE THREAD

**Issue by saalvation** [tachiyomiorg/tachiyomi-extensions#10495]
### Source information

Manhwa18.cc

### Steps to reproduce

I usually read and download manhwas from this source Manhwa18.cc, but today the source it's fine i can browse and read online without using webview BUT i cannot download any chapters from it. 

### Expected behavior

The chapters should be downloaded regulary

### Actual behavior

Not downloading at all, but still can be browse and read online

### Tachiyomi version

0.12.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by saalvation** [comment]
can u guys suggest me other sources to download manhwas18?

**Comment by vetleledaal** [comment]
Can't reproduce.

https://user-images.githubusercontent.com/13540478/176982238-9f469780-9a9e-440c-ba70-cfbce210fb1b.mp4

**Comment by alessandrojean** [comment]
Feel free to open a new issue if it happens again.
