### ISSUE TITLE
Imperfect Comics: Can't read or download chapters

### ISSUE THREAD

**Issue by Alexluther5** [tachiyomiorg/tachiyomi-extensions#10502]
### Source information

Imperfect Comics 1.2.18

### Steps to reproduce

1. Update the manga or Click the chapter to read
2. Try to Download

### Expected behavior

The download complete and should be able to be read.

### Actual behavior

The download don't start.When I try to read manga in the app, the black screen loads for a second and exits to the starting screen.

### Tachiyomi version

Tachiyomi J2K 1.0.17

### Android version

Android 9

### Other details

Webview is fine.
![IMG_20220119_004258](https://user-images.githubusercontent.com/84679545/149994777-74d9d08b-c319-4450-b1be-6fef23a6793f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
there is no imperfect scans, do you mean imperfect comic?

**Comment by Alexluther5** [comment]
> there is no imperfect scans, do you mean imperfect comic?

Yeah I mean Imperfect Comic 
My bad

**Comment by vipzzx** [comment]
just to add on. when i update library the manga from imperfect comics do update with the newest chapters. they are just not readable or downloadable

**Comment by alessandrojean** [comment]
/edit-title "Imperfect Comics: Can't read or download chapters"

**Comment by tyme2tb** [comment]
Same issue, but if I do webview a message saying I have an ad locker pops up and will not go away, so I was thinking it might be the issue

**Comment by vipzzx** [comment]
> Same issue, but if I do webview a message saying I have an ad locker pops up and will not go away, so I was thinking it might be the issue

That would only happen if you're using an ad blocker on your browser like brave. I do not have that pop up when I go to web view.

**Comment by poorloading** [comment]
glad to know it isn't just me with the issues.
