### ISSUE TITLE
MangaLink update Url

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#10519]
### Source name

MangaLink

### Source link

http://135.181.209.99

### Language

Arabic

### Other details

The source is down, if you can change the link to the site for this
 http://135.181.209.99

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

#10512
