### ISSUE TITLE
World Romance Translation: error 404

### ISSUE THREAD

**Issue by akunsik01** [tachiyomiorg/tachiyomi-extensions#10511]
### Source information

world romance translation 1.2.17

### Steps to reproduce

1. cant open error 404
2. lastestweb link "https://wrt.my.id/"

### Expected behavior

this should happen to update the extension

### Actual behavior

this happened instead error when open the extension but on web view is ok

### Tachiyomi version

App version: 0.12.3-4090 (standard, 769efd9d0, 72, 2022-01-15T21:07Z)

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "World Romance Translation: Changed their domain"
