### ISSUE TITLE
Geass Hentai 

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#10515]
Geass troca de site

Aparentemente Geass hentai agora funciona no site https://geassscan.net/hentais/
E não mais no antigo

### Other details

Me desculpem reportar esse problema aqui, não sei qual é o lugar certo em que se reporta esse tipo de problema

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You should open an issue using the **issue report** form instead. And the extension already uses this domain, but a lot of titles doesn't appear in the search in their own website, so nothing that can be done on the extension to fix it.

You can however use the *Open link in* feature that the extension have for now.

**Comment by Retashe** [comment]
Muito obrigado
