### ISSUE TITLE
Mangalink: Changed their domain

### ISSUE THREAD

**Issue by Fahdjud** [tachiyomiorg/tachiyomi-extensions#10512]
### Source information

Mangalink

### Steps to reproduce

The extension doesnt work it have 2 domain cc / org but no one of them is working 

### Expected behavior

It should be mangalink.io is the official website 

### Actual behavior

Give me error website on the two extantions

### Tachiyomi version

0.12.3

### Android version

12

### Other details

![Screenshot_20220119-174743_Tachiyomi](https://user-images.githubusercontent.com/98036366/150154227-7fb911f6-c960-4ec4-acfc-07e1224082fc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
No it's not their new domian it's totally different site and it's already have been added wait for the site to work
