### ISSUE TITLE
ZinChanManga: JSON parse error in popular

### ISSUE THREAD

**Issue by Jappyong** [tachiyomiorg/tachiyomi-extensions#10514]
### Source information

Zinchanmanga 1.2.1

### Steps to reproduce

Unexpected JSON token

### Expected behavior

The site should open but now it shows unexpected JSON token and tried retrying it but its still won't work. 

### Actual behavior

![Screenshot_2022-01-20-00-55-52-606_eu kanade tachiyomi](https://user-images.githubusercontent.com/87295246/150177712-a7e76af8-2925-4779-9964-583949ab6c55.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

It was functioning earlier but now when i open, it shows like that. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "ZinChanManga: JSON parse error in popular"
