### ISSUE TITLE
Xcalibr scans mirrored/split images

### ISSUE THREAD

**Issue by BellCranelUwU** [tachiyomiorg/tachiyomi-extensions#10528]
### Source information

XCalibr Scans 1.2.16

### Steps to reproduce

1) Open the XCalibr Scans on the list of extension on the app.
2) Select a random Manhwa and try to read 1 chapter
3) Manhwa opens with a mirrored image or split image, the image looks fine on webview.

### Expected behavior

The image should display properly.

### Actual behavior

The image appeared mirrored or split.

### Tachiyomi version

TachiJ2K 1.4.4

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by al-iskandar-github** [comment]
Yeah, this issue has also affected me as well.

**Comment by poorloading** [comment]
iv got all of this plus I sometimes get zoomed-in half images. some mangas will just have every later chapter zoomed in so you can only see the left side of it with no way to fix it, and even if you find a way to zoom it farther out the other half is just gone.

**Comment by Darkilen** [comment]
Same issue with xCaliBR Scans v1.2.17
