### ISSUE TITLE
Gufeng Manhua: Wrong images in thumbnails and chapters

### ISSUE THREAD

**Issue by ZWolken** [tachiyomiorg/tachiyomi-extensions#10533]
### Source information

Gufeng Manhua 1.2.4

### Steps to reproduce

Just every manga from this source shows
"重要通知
致所有古风漫画读者
为了用户更好的体验
即日起，古风漫画域名正式更改为www.gufengmh9.com"
Not only the cover picture but also the contents.

### Expected behavior

The regular use.

### Actual behavior

The pictures can show what actually happened.
![Screenshot_2022-01-21-16-25-28-71_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/76812845/150493743-078ab74b-d304-4e8f-aa96-368f7e158090.jpg)
![Screenshot_2022-01-21-16-29-46-36_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/76812845/150493772-ed9bf006-4b3d-4101-a8a8-d42a716c335d.jpg)
![Screenshot_2022-01-21-16-29-52-06_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/76812845/150493786-49152181-781d-44c9-8d2c-2178d506455b.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Gufeng Manhua: Wrong images in thumbnails and chapters"
