### ISSUE TITLE
MangaSee http error 520

### ISSUE THREAD

**Issue by Kobe8246** [tachiyomiorg/tachiyomi-extensions#10534]
### Source information

MangaSee 1.2.27

### Steps to reproduce

I tried reading One Piece ch.188.
It won't open, and there's a tiny box that says "https error 520"

### Expected behavior

It should just open the chapter

### Actual behavior

And instead it's taking me back to the chapter list and it says in a little box "https error 520"

### Tachiyomi version

Tachiyomi stable 0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EmeraldVoid** [comment]
I am also experiencing the same issue.

**Comment by Seishirou101** [comment]
mangasee is down

>Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
