### ISSUE TITLE
Anxious Frogs

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#10532]
### Source name

Anxious Frogs

### Source link

https://www.anxiousfrogs.me/

### Language

English

### Other details

Was mentioned that the domain was suspended #10488
The site is up
![Screenshot_20220121-032257_Chrome](https://user-images.githubusercontent.com/59638889/150492149-b1eb6d8c-8de7-4932-a9ff-1356664fda45.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Appears to use WPMangaReader, but the source references WPMangaStream

**Comment by vipzzx** [comment]
website changed to https://www.anxiousfrogs.me/
