### ISSUE TITLE
Tappytoon is downloading .bin files instead of a readable image format

### ISSUE THREAD

**Issue by ndsgamer4654** [tachiyomiorg/tachiyomi-extensions#10537]
### Source information

Tappytoon 1.2.4

### Steps to reproduce

I downloaded a chapter from tappytoon. It downloads fine but then it refuses to load the chapter. In my files manager it shows the images downloaded in a .bin format instead of jpg or png.

It can be fixed by renaming the files to a readable format though.

### Expected behavior

The files should download in a normal image format.

### Actual behavior

They download in .bin format.

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11

### Other details

The issue is fixed by renaming the file. Also someone on discord said that something similar happened with Tsumino

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
possibly may need the same fix as #8867

**Comment by ObserverOfTime** [comment]
The responses have the correct `Content-Type` and extension in the browser and even through `curl`.
Perhaps simply adding an `Accept` header (though not required in my testing) might fix the downloads?
I can't work on this for the next few days though, so you can go ahead and try either method if you want.

**Comment by ObserverOfTime** [comment]
Downloading works fine on my phone. Maybe it's an Android 11 bug?

**Comment by alessandrojean** [comment]
> Stable 0.12.3

Does it still happens in `v0.13.1` released today?

**Comment by ObserverOfTime** [comment]
Indeed, those images are served as `application/octet-stream`.
