### ISSUE TITLE
Project Time Scans

### ISSUE THREAD

**Issue by Drachenbar** [tachiyomiorg/tachiyomi-extensions#10540]
### Source name

Project Time Scans

### Source link

https://ptscans.tw/

### Language

English

### Other details

Used to be in the comiccake extension but wasn't added as it's own extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Uses the [MangaStarter] theme which doesn't have a multisrc yet as far as I can tell.

[MangaStarter]: https://www.codester.com/items/6001/mangastarter-build-a-manga-reader-with-wordpress
