### ISSUE TITLE
Bilibili Chinese Source classification error

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#10547]
### Source information

BILIBILI v1.2.4

### Steps to reproduce

Bilibili Chinese Source classification error

### Expected behavior

Source classification is 中文 not 中文（HANS），Bilibili only had Simplified Chinese comic, no need to add annotations and
is better to unify the Source title.
![Screenshot_2022-01-22-21-03-52-466_eu kanade tachiyomi](https://user-images.githubusercontent.com/46775615/150641185-246de32e-e5f6-4e5c-aa5d-7748def4c1d1.jpg)

### Actual behavior

**In principle, Chinese sources do not need to be divided into simplified and traditional Chinese, they are common in most cases.**

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The language can be changed, but the source title in this case it's better to keep as it is because there's another Bilibili website (Bilibili Comics) that also have Chinese content, so the Bilibili Manga title is used to differentiate between them.

**Comment by arkon** [comment]
For the sake of better categorization, I'd support being more specific whenever possible.

Those who can read both systems can still easily do so regardless of the categorization. Those who cannot can easily figure out what's relevant for them.

**Comment by ZerOri** [comment]
> The language can be changed, but the source title in this case it's better to keep as it is because there's another Bilibili website (Bilibili Comics) that also have Chinese content, so the Bilibili Manga title is used to differentiate between them.

Well, if you insist. I just thought it would be too messy.Can Chinese Bilibili(哔哩哔哩漫画)be classified into Chinese(中文) categories?

**Comment by alessandrojean** [comment]
I am with arkon on this now, it's indeed better to have a specific language code that easily allows people that aren't really familiarized with the language to be able to pick what it's better for them.

Other Chinese extensions can have their language changed to specific ones (`hans` or `hant`) so they can be grouped together again, though.

**Comment by ZerOri** [comment]
> I am with arkon on this now, it's indeed better to have a specific language code that easily allows people that aren't really familiarized with the language to be able to pick what it's better for them.
> 
> Other Chinese extensions can have their language changed to specific ones (`hans` or `hant`) so they can be grouped together again, though.

Almost all Chinese comic websites contain both simplified Chinese and traditional Chinese comics. Chinese users can understand simplified or traditional Chinese without any difficulty. This classification has no practical significance for user experience.

**Comment by FourTOne5** [comment]
> > I am with arkon on this now, it's indeed better to have a specific language code that easily allows people that aren't really familiarized with the language to be able to pick what it's better for them.
> > Other Chinese extensions can have their language changed to specific ones (`hans` or `hant`) so they can be grouped together again, though.
> 
> Almost all Chinese comic websites contain both simplified Chinese and traditional Chinese comics. Chinese users can understand simplified or traditional Chinese without any difficulty. This classification has no practical significance for user experience.

if you can find both traditional and simplified in Bilibili well change it to `zh`

**Comment by arkon** [comment]
> Chinese users can understand simplified or traditional Chinese without any difficulty. 

This is a generalization that I personally do not agree with.
