### ISSUE TITLE
Downloaded chapters getting (1) appended and becoming unreadable.

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#10554]
### Source information

Hentai2read (EN) 1.2.13, AllPornComic (EN) 1.2.15, Mangabat (EN) 1.2.9, Mangafreak (EN) 1.2.5, Webtoons.com (EN) 1.2.33

### Steps to reproduce

Put manga in library and set to automatically download

Wait.

### Expected behavior

Manga should display the appropriate number of chapters downloaded and be capable of reading those chapters

### Actual behavior

Some chapter folders get a (1) put somewhere in the name, sometimes at the end but not always. This makes those chapters unreadable but still increment the number of downloaded chapters badge.

### Tachiyomi version

 0.12.3 

### Android version

12

### Other details

App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXU4BULA
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

I had this bug before a few months ago but then it was exclusive to mangabat, I closed the issue because it hadn't happened for a few months. After reviewing the folders now, that was wrong of me, the earliest date modified of the folders is back in July.

The (1) seems to be able to appear anywhere in the name but it is consistent with which extension the chapter belongs to.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Can you show some screenshots of your file manager in these folders (that shows the full path)?

**Comment by AwesomeQuest** [comment]
![Screenshot_20220122-221418_X-plore](https://user-images.githubusercontent.com/15609837/150657163-b0bd142f-b1be-4cf7-9a9b-02eeb85f8abf.jpg)


> Can you show some screenshots of your file manager in these folders (that shows the full path)?

Searched for "(1)"

**Comment by scb261** [comment]
Example from Webtoons actually contains `(1)` in the name. `(1)` in the middle seems to be due to dot - your system tries to put it before the file extension.

As for main point of the issue - could you also check if there are any folders with similar names but without the `(1)` (e.g. instead of `_Chapter 158 (1)` it would be `_chapter 158`).

**Comment by AwesomeQuest** [comment]
Search function didn't return anything, so I searched through all of it manually and didn't find anything with ). in it. Also folders can't end with `.`

**Comment by scb261** [comment]
`).` was part of the sentence. I meant different case, like lowercase `c` or something. Just open folder for `Chronicles of Heavenly Demon` and see if there is any other folder for chapter 158.

**Comment by AwesomeQuest** [comment]
Ah. The unreadable folders are, I think, always accompanied by a readable counterpart. I do not see any character case discrepancy.

**Comment by scb261** [comment]
Try to remove both the `(1)` folder and the counterpart, and then redownload the chapter. A screenshot with both folders would also help.

**Comment by AwesomeQuest** [comment]
Before deleting
![Screenshot_20220123-000804_X-plore](https://user-images.githubusercontent.com/15609837/150659567-103d0faf-8dc5-4a0f-ba3c-f31f1d15dca9.jpg)
![Screenshot_20220123-000811_X-plore](https://user-images.githubusercontent.com/15609837/150659568-3bb6ba53-0937-4271-ae7b-a38f4ac43c27.jpg)
![Screenshot_20220123-000829_X-plore](https://user-images.githubusercontent.com/15609837/150659572-0e675310-9190-431d-b177-caa25e86ddc5.jpg)
![Screenshot_20220123-000945_X-plore](https://user-images.githubusercontent.com/15609837/150659576-3f26563e-b9c9-48c7-ab3f-60ada5f3325b.jpg)
![Screenshot_20220123-001031_X-plore](https://user-images.githubusercontent.com/15609837/150659580-9d5f5b75-8551-4590-8393-6fc318938175.jpg)
After deleting the counter part and the regular and re downloading the chapter there is no unreadable counterpart.

**Comment by KraXen72** [comment]
i also have this problem:
![Screenshot_20220907-102550_Tachiyomi.png](https://user-images.githubusercontent.com/21956756/189151668-676e26eb-ae14-4d93-8fb3-da737374ad33.png)
![Screenshot_20220906-194711_My Files.png](https://user-images.githubusercontent.com/21956756/189151723-7f9dbf47-5c8a-4a84-a9bb-f62f913a2016.png)

**Comment by KraXen72** [comment]
for me it happens on EVERY chapter (webtoons ext), and i even deleted and re-downloaded all of them, still nothing.

**Comment by scb261** [comment]
@KraXen72 Usually it's solved by removing downloads, maybe try to remove the webtoons folder or even the whole downloads folder.

Author of the issue has already solved the problem, so it should have been closed long time ago. And `(1)` is appended by your system, not by tachi or extension. This issue should be a part of tachiyomiorg/tachiyomi#7492 instead.
