### ISSUE TITLE
MangaOwl: Already read chapters reappearing on updates section

### ISSUE THREAD

**Issue by Axnoclound** [tachiyomiorg/tachiyomi-extensions#10552]
### Source information

Mangaowl 1.2.24

### Steps to reproduce

MangaOwl keeps updating everyday with most of the chapters that's already up.

### Expected behavior

When updating, it should be only the new chapters that shows in updates

### Actual behavior

It updates the last 10 chapters or more even though it was uploaded a few days ago
And it does this everyday.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![Screenshot_20220122-194219~2](https://user-images.githubusercontent.com/97826156/150649618-d5aa30fb-2fdd-44f1-b917-0fca4e7099a9.png)

Here it shows like that, not just this but all series' from mangaowl, even though it was out a few days or weeks or even months ego.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "MangaOwl: Already read chapters reappearing on updates section"

**Comment by arkon** [comment]
Merging with #10463
