### ISSUE TITLE
Summer Fansub

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#10556]
### Source name

Summer Fansub

### Source link

https://smmr.in/

### Language

Portuguese

### Other details

Yaoi, quase abri outro issue pra pirulito Rosa mas já tem, ainda bem que olhei kk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Uses WpMangaStream theme.

**Comment by alessandrojean** [comment]
Site seems to be closed. Open a new issue if they open a new website or this one goes back online again.
