### ISSUE TITLE
Dynasty extension not loading properly in the app

### ISSUE THREAD

**Issue by AliMaLu** [tachiyomiorg/tachiyomi-extensions#10560]
### Source information

Dynasty 1.2.16

### Steps to reproduce

1. Go to Dynasty-doujins to browse.
2. Search Touhou/Love Live/Bang Dream. (These are just some of the examples)
3. Only the Images chapter is shown while the rest of the chapters/doujins are not seen in the tachiyomi app.
4. Click webview and you'll notice that the chapters/doujins are shown in the webview but not on the app itself.

### Expected behavior

All the chapters/doujins should have loaded on the app.

### Actual behavior

Only the Images chapter is shown while the rest are missing.

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

Device is Samsung S9+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by StealthGrabix** [comment]
I would like to add that these issues extend to Dynasty-Series, Anthologies and Issues.  The amount of manga shown under the source is the same as what is shown on the first page of each respective category on the dynasty-scans site, but the additional pages (Page 2-13 of the Series category, for example) do not show up in the app Source.
