### ISSUE TITLE
Genkan.io Error 503 "lateinit property fingerprint has not been initialized"

### ISSUE THREAD

**Issue by SyncStelar** [tachiyomiorg/tachiyomi-extensions#10577]
### Source information

Genkan.io 1.2.4

### Steps to reproduce

Open Genkan.io in Browse and will get "lateinit property fingerprint has not been initialized".
Any manga that is already in library under genkan.io also shows error 503.
Can open Genkan.io in webview.

### Expected behavior

Expected to be able to browse and update mangas from Genkan.io

### Actual behavior

Open Genkan.io in Browse and will get "lateinit property fingerprint has not been initialized".
Any manga that is already in library under genkan.io also shows error 503.

### Tachiyomi version

J2K 1.4.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by h-hyuuga** [comment]
Open in webview first, then the source should behave normally

**Comment by SyncStelar** [comment]
Opening in webview still leaves me with the same error after closing webview.

**Comment by stevenyomi** [comment]
Removed in #15016.
