### ISSUE TITLE
What happened to MangaLink's source

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#10573]
### Source information

MangaLink 1.2.6

### Steps to reproduce

1- go to mangalink

### Expected behavior

open MangaLink

### Actual behavior

Source not open
![Screenshot_20220125-050215](https://user-images.githubusercontent.com/90999286/150898845-90e5af24-f8b3-4c08-a557-cab6ac0964a0.png)
![Screenshot_20220125-050236](https://user-images.githubusercontent.com/90999286/150898849-477ca668-db90-4d91-9a3d-b86eee668a7e.png)

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Working fine here, please try the [troubleshooting guide] first.

If you need additional support, ask it in #support on [Tachiyomi's Discord server].

[troubleshooting guide]: https://tachiyomi.org/help/guides/troubleshooting/
[Tachiyomi's Discord server]: https://discord.gg/tachiyomi
