### ISSUE TITLE
TOPTOON+: Login does not work

### ISSUE THREAD

**Issue by yamato44** [tachiyomiorg/tachiyomi-extensions#10596]
### Source information

Toptoon+ 1.2.2

### Steps to reproduce

1.opening toptoon+ source.
2.loading and the gives me this message " the e-mail or password provided are incorrect " but my account is working fine in the browser 

### Expected behavior

Comics showing up 

### Actual behavior

Gives me this message " the e-mail or password provided are incorrect "

### Tachiyomi version

0.12.1

### Android version

10

### Other details

my account is working fine in other browsers i also tried To log in with another accout but it didn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Do you login with any social media?

**Comment by yamato44** [comment]
> ~Do you login with any social media? The extension login only supports simple accounts.~
> 
> They seem to changed their API.

With simple account
