### ISSUE TITLE
Leviatan Scans deep linking

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi-extensions#10591]
### Source information

Leviatan Scans 1.2.24

### Steps to reproduce

There are multiple "issues/weirdness" using deep-links. Some example

A) Open a link that points directly to a chapter ex. https://leviatanscans.com/manga/filiarose-the-crown-of-thorns-prophecy/chapter-18/

B) Open a (temporary?) link that points to a chapter ex. https://leviatanscans.com/vv/manga/filiarose-the-crown-of-thorns-prophecy/chapter-18/

C) Open a link that points to the actual manga page ex. https://leviatanscans.com/manga/filiarose-the-crown-of-thorns-prophecy/

D) Open a (temporary) link that points to the actual manga page ex. https://leviatanscans.com/vv/manga/filiarose-the-crown-of-thorns-prophecy/

### Expected behavior

A/B) It opens either directly the interested chapter or the series
C/D) It opens the series

### Actual behavior

B/D)
in main tachi it keep loading (apparently forever) with no results
in tachi sy it ends loading with an empty result and it opens as a manga with no data and http error 404 (no title/description/chapters)
![Screenshot_20220128-182038_TachiyomiSY](https://user-images.githubusercontent.com/10052873/151595424-1ef72f52-f016-44c3-95ce-907dc099164f.png)

A)
main tachi loads forever
tachiyomi sy gets a result but if it is the first time caching / saving to database the series the entry loads with correct chapters, description and tags but without/"unknown" title.
![Screenshot_20220128-165631_TachiyomiSY](https://user-images.githubusercontent.com/10052873/151595764-d21d43dd-7c91-476b-8f75-389fa47d5f7d.png)
This stays even after looking up the manga trough the browse function and it is only resolved when clearing the database from the advanced settings
![Screenshot_20220128-165621_TachiyomiSY](https://user-images.githubusercontent.com/10052873/151595817-7e1d3d34-838f-4dbb-9d8f-47e702fb147a.png)

C)
main tachi loads forever
tachiyomi sy works correctly and opens the series

### Tachiyomi version

TachiyomiSY Preview r432 / Tachiyomi Preview r4103

### Android version

Android 11

### Other details

video of A on tachiyomiSY: https://youtu.be/LkjF14houqA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
this also affects other madara extensions

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
