### ISSUE TITLE
MangaDex: Remove Markdown tags from the description

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#10610]
### Describe your suggested feature

Some titles have markdown texts in their description/about and it looks realy bad on tachiyomi. 

[Orginal post](https://github.com/tachiyomiorg/tachiyomi/issues/6213)

### Other details

This can be fixed on the extension side by using some library like JetBrains/markdown to remove the Markdown tags. (Alessandro)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "MangaDex: Remove Markdown tags from the description"

**Comment by curche** [comment]
Hi, I've tried cleaning out the descriptions by filtering out
 - [hyperlinks](https://mangadex.org/title/fc7f2c19-0a26-4d89-9505-332fcb7d60c6)
 - [Extra Notes/Links section](https://mangadex.org/title/6670ee28-f26d-4b61-b49c-d71149cd5a6e/mieruko-chan)

You can try and install the apk with the changes from here: https://wormhole.app/KPz9O#5gR2g6C_RxMtSghbphsYtA
Let me know if it works and if not, example where it breaks

---
Notes:
Regex - https://regex101.com/r/KdvDsO/1
Diff -
```sh
> git diff
index a85afa7d6..e51b4bfec 100644
--- a/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt
+++ b/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt
@@ -75,7 +75,12 @@ class MangaDexHelper() {
         while (bbRegex.containsMatchIn(intermediate)) {
             intermediate = intermediate.replace(bbRegex, "$2")
         }
-        return Parser.unescapeEntities(intermediate, false)
+        val unescapedString = Parser.unescapeEntities(intermediate, false)
+        val linkRegex = "\\[([^]]+)\\]\\(([^)]+)\\)".toRegex()
+
+        return unescapedString
+            .substringBefore("---")        # Removes Extras/Links section
+            .replace(linkRegex, "$1")   # Removes any hyperlinks
     }
 
     /**
```

**Comment by curche** [comment]
Sigh, can't believe I sent the wrong apk :disappointed: 
anyways, this one should work: https://wormhole.app/YQJA3#WEErj6viCE_AjOaBfdMYXg

**Comment by SrW0nka** [comment]
> Sigh, can't believe I sent the wrong apk disappointed anyways, this one should work: https://wormhole.app/YQJA3#WEErj6viCE_AjOaBfdMYXg

np, I tested in sl, opm and in the manga from original post (dead dead demon's dededede destruction) and nothing changed
![image](https://user-images.githubusercontent.com/76596575/152383206-0d6f3487-7104-4619-bba0-94a21a8aa134.png)

**Comment by CarlosEsco** [comment]
@SrW0nka  did you swipe refresh?

**Comment by curche** [comment]
The app caches a lot. Swipe Refresh or Clear Database from Advanced settings

**Comment by SrW0nka** [comment]
> 

yep

**Comment by SrW0nka** [comment]
> The app caches a lot. Swipe Refresh or Clear Database from Advanced settings

I even remove from library > clear database > add again

**Comment by SrW0nka** [comment]
nvm, ext was listed as "untrusted", now it worked fine

**Comment by alessandrojean** [comment]
Why keep extra links if they aren't clickable?

**Comment by CarlosEsco** [comment]
@curche can you open a wip pr. So we can discuss stuff related there

**Comment by SrW0nka** [comment]
> Why keep extra links if they aren't clickable?

usually they have useful information, like if the manga has a adaptation in anime or smt like that

**Comment by curche** [comment]
> @curche can you open a wip pr. So we can discuss stuff related there

Alright

**Comment by curche** [comment]
Opened PR #10674
