### ISSUE TITLE
"No pages" when clicking on a new chapter

### ISSUE THREAD

**Issue by Xiaoruiii** [tachiyomiorg/tachiyomi-extensions#10611]
### Source information

MangaOwl 1.2.24

### Steps to reproduce

1. I searched a manga on mangaowl.
2. Clicked on one of the chapters and it's completely fine.
3. Added the manga into my library.
4. Tried to start reading the manga in my library but it shows "no pages found".

### Expected behavior

The content of the manga should be available for readers to start reading.

### Actual behavior

"No pages found" showed up, unable to read the manga. Also, I am unable to download the chapters of mangas in MangaOwl.

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

![Screenshot_20220130_100858](https://user-images.githubusercontent.com/98675145/151684000-3ba600a7-0e70-44ba-a5bd-a70a1f1a8e0e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#10464
