### ISSUE TITLE
Manga Nine fails to load chapters

### ISSUE THREAD

**Issue by EverdistantUtopia** [tachiyomiorg/tachiyomi-extensions#10623]
### Source information

1.2.16

### Steps to reproduce

The manga list loads but you can't see or read chapters

### Expected behavior

For the chapters and description to load

### Actual behavior

No author , description or chapters are shown

### Tachiyomi version

Preview version

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
The Manga Nine site is down and is redirecting to https://mangaweed.com now
