### ISSUE TITLE
Bilibili: Throwing HTTP 401 in user episodes checking

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi-extensions#10622]
### Source information

Bilibili v1.2.5

### Steps to reproduce

1. Sign in though WebView.
2. Open a title with already paid chapters.

### Expected behavior

The chapter list should load fine.

### Actual behavior

The chapter list is empty and the extension is throwing a HTTP 401 error.

### Tachiyomi version

r4118

### Android version

Android 12

### Other details

Probably the user episodes checking endpoint is missing something or the access token in the cookie is invalid/expired. The extension needs to handle this properly.

Example of title to check: The Blade of Evolution Walking Alone In The Dungeon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Issue found: It happens when the account is from Singapore.

The extension uses the `us-user` subdomain always instead of using the `sg-user` when needed.

**Comment by doughtier** [comment]
This is happening to me as well, and my account is most certainly not from Singapore. Started after I updated the BILIBILI extension to 1.2.5 today -- it worked fine yesterday.

**Comment by alessandrojean** [comment]
> This is happening to me as well, and my account is most certainly not from Singapore. Started after I updated the BILIBILI extension to 1.2.5 today -- it worked fine yesterday.

In your profile, what do you have next to your username? `#US` or something else?

Have you signed in via WebView? If so, was it a long time ago?

**Comment by doughtier** [comment]
> In your profile, what do you have next to your username? #US or something else?

Ah, I see what you meant by Singapore! It's `#SG`. How odd.

I'm currently signed into web. The `statistician.v3.buvid` cookie has the earliest date of all at 10-Dec-2021.

Let me know if you need any more details!

**Comment by alessandrojean** [comment]
Your issue should be really the one I described in this issue, otherwise if it was an expired token it would be fixed by opening WebView and trying again. Thanks for your information :+1:.

**Comment by doughtier** [comment]
Yes, I didn't realise that the number after the name was a region code. It really does sound like the same issue.
