### ISSUE TITLE
Add new manga extension

### ISSUE THREAD

**Issue by Sparky3803** [tachiyomiorg/tachiyomi-extensions#10636]
### Source name

Mangareader.to

### Source link

https://mangareader.to/

### Language

English, japanese

### Other details

Please add manga extension :- mangareader.to 
![Screenshot_2022_0131_180315](https://user-images.githubusercontent.com/98748410/151794545-baa345fa-7e2d-414e-b1c6-39b2e46824d3.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Sparky3803** [comment]
Please support guys

**Comment by Seishirou101** [comment]
and please read what you acknowledge. #9112

**Comment by Sparky3803** [comment]
Closed means i don't understand.
