### ISSUE TITLE
Mangareader.to

### ISSUE THREAD

**Issue by Sparky3803** [tachiyomiorg/tachiyomi-extensions#10637]
### Source name

mangareader.to

### Source link

https://mangareader.to

### Language

English, japanese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Sparky3803** [comment]
All manga are available in this site

**Comment by CarlosEsco** [comment]
still didnt read "I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue."

**Comment by Sparky3803** [comment]
Closed means . I don't understand

**Comment by CarlosEsco** [comment]
" I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue." 

There is an already open issue requesting this source.

**Comment by Sparky3803** [comment]
Thank you for the clarification.
