### ISSUE TITLE
Toomics (Korean)

### ISSUE THREAD

**Issue by cinnanom** [tachiyomiorg/tachiyomi-extensions#10644]
### Source name

Toomics

### Source link

https://www.toomics.com/

### Language

Korean

### Other details

The current extension only seems to refer to https://global.toomics.com/en; there isn't a Korean option in the extension languages and searching Korean titles available (for free) on https://www.toomics.com/ returns no results.

This has been requested before, but was closed without being implemented: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5167. 

(After visiting the global / English site, you can't access the Korean site without being redirected, unless you clear your cookies or bypass the main page: https://www.toomics.com/webtoon/waitfree)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> searching Korean titles available (for free) on https://www.toomics.com/ returns no results.

I didn't get this part, there isn't any free title on the website? So you want the extension to have support to sign in and read paid content, right?

**Comment by alessandrojean** [comment]
Yeah, the Toomics extension only have the Global website, the original and Korean one still needs to be added.
