### ISSUE TITLE
Mangaowl "no chapters found

### ISSUE THREAD

**Issue by Haesoo2** [tachiyomiorg/tachiyomi-extensions#10643]
### Source information

Mangaowl 1.2.24

### Steps to reproduce

There is no chapter found everytime i press my unread manhwa. Everything and everytime i try to read in mangaowl, it says that there is no chapter found.

### Expected behavior

There should be chapters found.

### Actual behavior

But it says "no chapters found".

### Tachiyomi version

0.13.0

### Android version

Andoid 11

### Other details

Please fix this soon 🥲

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Please do what you acknowledge. #10464
