### ISSUE TITLE
Nhentai (All) filter broken

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#10654]
### Source information

1.2.30

### Steps to reproduce

1. open nhentai (all)
2. open the filter button
3. click on Filter button again

### Expected behavior

it should filter giving as output mangas.

### Actual behavior

![IMG_20220202_113355](https://user-images.githubusercontent.com/75091899/152138153-a4c2d173-38ff-4bea-80e4-1c9957126704.jpg)

### Tachiyomi version

13.1

### Android version

android 8

### Other details

the filter works if you add tags, author, parodies etc... but if you want to just "sort by"(recent, popularity, today, week) the manga with any other filter, the bug occours.
Also when you open the extension to search the default "sort by" is Recent but on Nhentai (English) it is sorted by Popularity by default

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
This is a limitation of the website, the website needs some text search to apply sorting filters, the language specific versions get around this because they apply a language search.

**Comment by Seishirou101** [comment]
closing as it is a limitation of the website
