### ISSUE TITLE
CopyManga can't found manga list and chapter list

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi-extensions#10658]
### Source information

CopyManga 1.2.22(中文 拷贝漫画)

### Steps to reproduce

open manga list or refresh manga in self

### Expected behavior

load manga list and update manga chapter

### Actual behavior

load failed then show and toast “http error 404”
![Screenshot_2022-02-03-01-57-33-360_eu kanade tachiyomi](https://user-images.githubusercontent.com/97005405/152210772-26a12a48-9553-4901-95d7-348aade19a1a.jpg)
![Screenshot_2022-02-03-01-57-48-933_eu kanade tachiyomi](https://user-images.githubusercontent.com/97005405/152210794-34c85771-8e3e-4cab-aea2-e267e6b602c8.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

The new domain: www.copymanga.org

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CmmmmmmLau** [comment]
I think it's beacuse CopyManga changed their domain from www.copymanga.com to www.copymanga.org.

**Comment by 362516282** [comment]
The new website is www.copymanga.org, not the original .com
