### ISSUE TITLE
Newtoki / Manatoki: Domain Changes

### ISSUE THREAD

**Issue by tobyzulka** [tachiyomiorg/tachiyomi-extensions#10661]
### Source information

Newtoki / Manatoki 1.2.22

### Steps to reproduce

1. The domain NXDOMAIN
2. Domain number is not the same

### Expected behavior

I hope the domain number update

### Actual behavior

![Screenshot_2022-02-03-10-37-15-419_eu kanade tachiyomi](https://user-images.githubusercontent.com/20981211/152277404-c25e398e-6cdb-450f-be1b-2b150dcc6351.jpg)

### Tachiyomi version

1.2.22

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Change the URL to the newest domain that newtoki uses in the extension settings of this source.
