### ISSUE TITLE
MangaOwl: No Pages Found

### ISSUE THREAD

**Issue by Fujin-sama** [tachiyomiorg/tachiyomi-extensions#10668]
### Source information

MangaOwl 1.2.24

### Steps to reproduce

No pages found

### Expected behavior

The chapter will open after clicking the chapter you want to read

### Actual behavior

After clicking the chapter it says No Pages Found

### Tachiyomi version

0.13.1

### Android version

9

### Other details

No Pages Found

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
"I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue."

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10463
