### ISSUE TITLE
Remangas: Changed their domain

### ISSUE THREAD

**Issue by thanosluyang** [tachiyomiorg/tachiyomi-extensions#10666]
## Device information
* Tachiyomi version: 0.13.1
* Android version: 7

## Source information
* Source name: Remangas
* Source extension version: 1.2.8

## Steps to reproduce
1. Click on the extension.

## Issue/Request
Some manga are missing the chapters.

**Comment by jopejoe1** [comment]
The new domain is using Madara theme
