### ISSUE TITLE
Izneo: The chapter list is incomplete

### ISSUE THREAD

**Issue by Amane1239** [tachiyomiorg/tachiyomi-extensions#10671]
### Source information

izneo (webtoons) 1.2.2

### Steps to reproduce

When I try to read, for example "Talk to me Tenderly" which has 108 chapters on the site, and which I have access to with my account, in the end I only see the first 50 chapters on tachiyomi. 
(it's normal that it's in French, in any case it's the same for the English version)

![unknown](https://user-images.githubusercontent.com/92172310/152342884-535a0197-a10f-4bf9-8ee9-6c21b642e4da.png)

### Expected behavior

So I would like us to be able to see all the chapters available.

### Actual behavior

But instead, only the first 50 chapters are displayed

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

sorry in advance if I made a mistake in how to create an issue, this is the first time I've done it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Izneo: Not able to read the already paid chapters"

**Comment by alessandrojean** [comment]
/edit-title "Izneo: The chapter list is incomplete"

**Comment by ObserverOfTime** [comment]
Did you set your username and password in the extension settings?

**Comment by Amane1239** [comment]
> Did you set your username and password in the extension settings 

yes I did it

**Comment by ObserverOfTime** [comment]
They might be paginating the chapter list. I will check as soon as I can.
