### ISSUE TITLE
xCaliBR Scans - Split Image

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi-extensions#10681]
### Source information

xCaliBR Scans 1.2.16

### Steps to reproduce

Read new chapter of any manga, manhua, manhwa.

### Expected behavior

Each half of image use half of screen and order images not by name but by website default. 

### Actual behavior

Each half of image shows in full screen size and follows by next half.

For example it some times shows right part in full screen and as page 1.and in page 2 it shows left part as full screen. 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Same thing happened to some works on FlameScan and it got handled so solution already exists and just need to be used once more.

There was already #10528 but it refers to time with no fix pattern of which method (Mirror/Split) used by xCaliBR Scans. But right now website only use simple split image. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Please read what you acknowledge.
 >I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
 
#10528
