### ISSUE TITLE
French MangaDex

### ISSUE THREAD

**Issue by DonCappuccin0** [tachiyomiorg/tachiyomi-extensions#10692]
### Source information

Mangadex 1.2.154

### Steps to reproduce

1 install mangadex
2 go to mangadex french
3
![Screenshot_2022-02-04-09-34-38-84_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/95973966/152497702-6026ca3e-6020-45a0-bf22-4841dcc044e3.jpg)

### Expected behavior

open mangas

### Actual behavior

error api

### Tachiyomi version

0.13.1

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Looks like something is blocking your connection to mangadex, try the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/#what-are-some-common-issues) the section about `Unable to resolve host` should help you. If you still need help ask in the `#support` channel on the [tachiyomi discord server](https://discord.gg/tachiyomi).

**Comment by DonCappuccin0** [comment]
> Looks like something is blocking your connection to mangadex, try the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/#what-are-some-common-issues) the section about `Unable to resolve host` should help you. If you still need help ask in the `#support` channel on the [tachiyomi discord server](https://discord.gg/tachiyomi).

thank you
