### ISSUE TITLE
Comick.fun: error page

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi-extensions#10708]
### Source information

Comick.fun 1.2.9

### Steps to reproduce

1. search `okashi na tensei`
2. open chapter 30
3. go to page 11

### Expected behavior

page should load like on the website

### Actual behavior

retry button 

### Tachiyomi version

1.13.1

### Android version

A11

### Other details

not sure if this api issue or ext 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by meotimdihia** [comment]
@Riztard thanks for the report. It is the problem on Comick side. 😀
