### ISSUE TITLE
Mangkomik (Indonesian)

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#10701]
### Source name

Mangkomik

### Source link

https://mangkomik.com/

### Language

Indonesian

### Other details

Following on official Facebook page extension with codename Boosei(Indonesia) is no longer update anymore, and all projects move to https://mangkomik.com/
![IMG_20220205_045452](https://user-images.githubusercontent.com/23666289/152595269-553e43e8-3312-408f-8fe5-a8479119fae0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader

**Comment by TheKingTermux** [comment]
> ### Source name
> Mangkomik
> 
> ### Source link
> https://mangkomik.com/
> 
> ### Language
> Indonesian
> 
> ### Other details
> Following on official Facebook page extension with codename Boosei(Indonesia) is no longer update anymore, and all projects move to https://mangkomik.com/ ![IMG_20220205_045452](https://user-images.githubusercontent.com/23666289/152595269-553e43e8-3312-408f-8fe5-a8479119fae0.jpg)
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a title with source name.
> * [x]  I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
> * [x]  I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
> * [x]  I will fill out all of the requested information in this form.

Beneran ganti nih ?
Klo emang bener ntar dibuatin
Tag w ya

**Comment by ZekkenID** [comment]
> 

@TheKingTermux iya dah lama ganti

**Comment by TheKingTermux** [comment]
> > 
> 
> @TheKingTermux iya dah lama ganti

Ada genre dewasa ?

**Comment by ZekkenID** [comment]
@TheKingTermux nggak ada

**Comment by TheKingTermux** [comment]
> @TheKingTermux nggak ada

Ok masuk list
Mungkin beberapa hari kedepan dah up
Sabar ya

**Comment by TheKingTermux** [comment]
> > 
> 
> @TheKingTermux iya dah lama ganti

Boosei dah tutup ?
Klo dah tutup permanen sekalian w apus directory boosei nya
Klo masih ada up ya gausah w apus gtu

**Comment by ZekkenID** [comment]
@TheKingTermux dah tutup

**Comment by TheKingTermux** [comment]
> @TheKingTermux dah tutup

Ok w edit bentar

**Comment by TheKingTermux** [comment]
Boosei masih ada update loh
Seriusan udh ditutup ?

**Comment by TheKingTermux** [comment]
Dah up ya 😌
Selamat menikmati gan 😁
