### ISSUE TITLE
TOPTOON+: Chapters do not load when signed in

### ISSUE THREAD

**Issue by Ferreoly** [tachiyomiorg/tachiyomi-extensions#10707]
### Source information

Toptoon+ 1.2.3

### Steps to reproduce

1. Login with webview
2. Open a chapter with the app (free or paid)

### Expected behavior

The chapter should be opened

### Actual behavior

The chapter loads but after few seconds a blue bar appear and we are brought back to the manga page.

### Tachiyomi version

stable 0.13.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "TOPTOON+: Chapters do not load when signed in"

**Comment by alessandrojean** [comment]
Just a notice that they're starting to add reCAPTCHA to a lot of endpoints of their API, so if you have an account and have bought the chapters, I would suggest using their own app or their website to read, as they can easily detect and apply their ToS now.

**Comment by Ferreoly** [comment]
Okay thanks
