### ISSUE TITLE
Library update lacking a lot of manga

### ISSUE THREAD

**Issue by DarkQuasar88** [tachiyomiorg/tachiyomi-extensions#10713]
### Source information

Tachiyomi

### Steps to reproduce

1.  Updating the library

### Expected behavior

Update the entire library

### Actual behavior

Only updates some of the manga

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

It only updates 16 mangas.
![Screenshot_2022-02-06-00-09-34-50_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/99087651/152649338-b250dc09-f0dc-4e10-b459-2cba6baedc71.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read the release notes. https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
