### ISSUE TITLE
Gif not loading

### ISSUE THREAD

**Issue by Realppp** [tachiyomiorg/tachiyomi-extensions#10712]
### Source information

Luscious 1.2.18

### Steps to reproduce

1.merge chapters since that what casue the gif to not load previously
2.load any manga that have gifs in it

### Expected behavior

For the gifs to load in

### Actual behavior

The most of the gifs did not load in but is instead a image even though the website have it as a gif

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is #7232 still valid?

**Comment by Realppp** [comment]
> Is #7232 still valid?

Yep it's valid that why I did merge the chapters to make the gallery smaller however this gif not loading in is still occurring after merging chapters

**Comment by jopejoe1** [comment]
Could you give some examples the ones i tried where all working fine.

**Comment by Realppp** [comment]
> Could you give some examples the ones i tried where all working fine.

https://www.luscious.net/albums/hentai_gifs_330764/
This one especially I tried it with preview AZ,preview SY and stable

**Comment by jopejoe1** [comment]
Looks like some gif when they are resized by Luscious get turned into jpg, changing the Image resolution to `Original` should load the gif.

**Comment by Realppp** [comment]
> Looks like some gif when they are resized by Luscious get turned into jpg, changing the Image resolution to `Original` should load the gif.

Yep it's works I can close this issue now
