### ISSUE TITLE
ArabsHentai

### ISSUE THREAD

**Issue by simocv0** [tachiyomiorg/tachiyomi-extensions#10726]
### Source name

ArabsHentai

### Source link

https://arabshentai.com

### Language

Arabic

### Other details

Hentai manga and manhwa

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#6189

**Comment by simocv0** [comment]
> [# 6189](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6189)

why ?

**Comment by arkon** [comment]
Do not open duplicate issues.

**Comment by simocv0** [comment]
> Do not open duplicate issues.

OK When will the site be added?

**Comment by loocool2** [comment]
We do not provide ETAs

**Comment by simocv0** [comment]
> We do not provide ETAs

??

**Comment by Seishirou101** [comment]
This is open source project, people can work on anything they want and when they have time for it. There is no estimated time on any open issue or adding any source.
