### ISSUE TITLE
Resuming chapter picks the wrong chapter

### ISSUE THREAD

**Issue by BilalAG7** [tachiyomiorg/tachiyomi-extensions#10727]
### Source information

Colored Manga 1.2.16

### Steps to reproduce

1. Go to Naruto - Digital Colored Comics
2. Mark any number of chapters as read (I had the first 80 chapters read)
3. Click resume and it opens up Chapter 691.

### Expected behavior

It should open up the next chapter (Chapter 81)

### Actual behavior

It opens up Chapter 691

### Tachiyomi version

Preview r437

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
