### ISSUE TITLE
INKR: Could not parse the API response

### ISSUE THREAD

**Issue by cinnanom** [tachiyomiorg/tachiyomi-extensions#10737]
### Source information

INKR 1.2.3

### Steps to reproduce

1. Search for a title through Browse
2. Select a result from INKR

### Expected behavior

Selected title's information should be displayed

### Actual behavior

Only the cover image and title load; all other information is missing. 
Message displayed: "Could not parse the API response"

### Tachiyomi version

0.13.1

### Android version

Android 9

### Other details

Browse → Source → INKR = "No results found"
Browse → Source → INKR latest = blank screen
Library → Title (INKR source) → refresh = "Could not parse the API response"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
\edit-title "INKR: Could not parse the API response"
