### ISSUE TITLE
Imhentai is broken

### ISSUE THREAD

**Issue by Hounddraco** [tachiyomiorg/tachiyomi-extensions#10733]
### Source information

Imhentai 1.2.4

### Steps to reproduce

Open IMhentai 

### Expected behavior

Should show content 

### Actual behavior

Doesn't show any content 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Basara-Hatake** [comment]
their search is broken thats why it doesnt work
![image](https://user-images.githubusercontent.com/53382992/152691804-54f6c334-1580-4db3-b4c3-22de882463a4.png)

**Comment by alessandrojean** [comment]
Closing since it's a site issue.
