### ISSUE TITLE
The app only update parts of my mangas.

### ISSUE THREAD

**Issue by star2056** [tachiyomiorg/tachiyomi-extensions#10734]
### Source information

CopyManga 1.2.23

### Steps to reproduce

1. open app, on the bookshelf page
2.drag down/click top-right refresh button to update all mangas.

### Expected behavior

All of my mangas(locals not included) should be updated,  all 40 of them.

### Actual behavior

Only 19 mangas updated.
Now I have to click in to mangas and drag down to update them one-by-one.
![image](https://user-images.githubusercontent.com/26737255/152694462-809a8d2e-d942-4de6-950c-8a97ee596483.png)
![image](https://user-images.githubusercontent.com/26737255/152694606-6f79cb2e-8d52-4d67-bd17-828f9f09ec1b.png)
gephgui4（迷雾通） is not related about this, I closed gephgui4 and tachiyomi still only update 19 mangas.

### Tachiyomi version

0.13.1

### Android version

Android 6.0

### Other details

If dev need anything please tell me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please read the app update changelog.

https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
