### ISSUE TITLE
IsekaiScan.com: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by TaikiMatsuo** [tachiyomiorg/tachiyomi-extensions#10730]
### Source information

IsekaiScan.com 1.2.19

### Steps to reproduce

![Screenshot_2022-02-06-22-07-21-59_79aa9bf7c61e266c5f841e42245e214b](https://user-images.githubusercontent.com/99129480/152685030-f8abae02-4fac-459b-b0dc-b641f0f34c42.jpg)

### Expected behavior

This should open the main homescreen of iseakiscan.com

### Actual behavior

It cannot bypass cloudfare

### Tachiyomi version

App version: 0.13.1-4139 (standard, f5c6e80db, 74, 2022-02-05T21:07Z)

### Android version

Android version: 10 (SDK 29)

### Other details

cannot update mangas from isekanscan since it cannot bypass cloudfare 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
try these otherwise, `If the solutions provided do not fix the issue, the source has likely raised the Cloudflare protection level high enough that Tachiyomi is not able to access the site.`
