### ISSUE TITLE
Manhuagui: suggestion for the banned issue 

### ISSUE THREAD

**Issue by joyeli** [tachiyomiorg/tachiyomi-extensions#10744]
### Describe your suggested feature

It might be a hint which could avoid being banned from the Manhuagui. I am being banned immediately right after I updated the app to the latest version, before this bad thing happen, I have used it for almost half-year without being banned. 

For the **not banned** practice, I have been received an error message from the manhuagui-extension while getting manga information, the error is:

`Failed resolution of: Lkotlinux/coroutines/BuildersKt;` 

Reading manga is still going good under this error occur, besides getting the description of the manga. The manga description getting feature going well after being updated to the latest version, but **banned immediately** even I am still reading the first chapter right after the app update.

For now, I am rolled back to the older version and reading well without being banned besides the broken description getting feature. I believe this kind of experience might help to avoid being banned from the Manhuagui.

### Other details

My practice with and without being banned:

1. Tachiyomi v0.12.1 with manhuagui v1.2.9 **-> banned after a while**
2. Tachiyomi v0.12.3 with manhuagui v1.2.9 **-> banned after a while**
3. TachiyomiSY v1.7.0 (base on Tachiyomi  v0.11.1) with manhuagui v1.2.9 **->not banned**
4. TachiyomiSY v1.7.0 (base on Tachiyomi  v0.11.1) with manhuagui v1.2.10 **->not banned**
5. TachiyomiSY v1.7.0 (base on Tachiyomi  v0.11.1) with manhuagui v1.2.11 **->not banned**
6. TachiyomiSY v1.8.0 (base on Tachiyomi  v0.13.0) with manhuagui v1.2.11 **->banned after a while**
7. TachiyomiSY v1.8.1 (base on Tachiyomi  v0.13.1) with manhuagui v1.2.11 **->banned after a while**
8. Roll back to TachiyomiSY v1.7.0 with manhuagui v1.2.11 **->not banned** for now

Settings of manhuagui-extension for all the versions I have been used:

- mainSiteRatelimitPreference = 1
- imgCDNRatelimitPreference = 1

Addition settings of TachiyomiSY for all the versions I have been used:

- Page Preload amount = 4
- Download threads = 1
- Aggressively load pages = false

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Closing in favor of #14433.
