### ISSUE TITLE
Toonily extension doesn't show date anymore

### ISSUE THREAD

**Issue by onmyouji** [tachiyomiorg/tachiyomi-extensions#10753]
### Describe your suggested feature

Toonily extension doesn't show date anymore. Seems like there's a change on their website. Previously it would show date below the chapter (yyyy-mm-dd)

![Screenshot_20220208-132628](https://user-images.githubusercontent.com/8424198/152933786-6ffaf3ef-c8ea-4e0b-ade4-ea2535b7aa23.png)

### Other details

Website: https://toonily.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Update your app to 0.13.1

**Comment by alessandrojean** [comment]
Closing since the latest app version already shows dates when the extension doesn't provide. If you still want the extension set the value, open a new _issue report_ ticket instead of a feature request one.

**Comment by onmyouji** [comment]
> Closing since the latest app version already shows dates when the extension doesn't provide. If you still want the extension set the value, open a new _issue report_ ticket instead of a feature request one.

But I'm already using 0.13.1, it doesn't show dates. Only toonily extension has this issue though, my other extensions show dates.

Any suggestion how to troubleshoot this? I've already tried uninstall and reinstalling both tachiyomi and the extension.

**Comment by FourTOne5** [comment]
> 
> But I'm already using 0.13.1, it doesn't show dates. Only toonily extension has this issue though, my other extensions show dates.
> 

Seems like something is broken in the app please make a bug report in app repo

> Any suggestion how to troubleshoot this? I've already tried uninstall and reinstalling both tachiyomi and the extension.

Make a new proper bug report for toonily

**Comment by CrepeTF** [comment]
Just make a new bug report on this repo not a feature request, also not on the app repo either

**Comment by FourTOne5** [comment]
> Just make a new bug report on this repo not a feature request, also not on the app repo either

The app from 0.13.0 is suppose to show dates regardless if the ext gives one or not so this deserves a bug report in app repo
