### ISSUE TITLE
YugenMangas

### ISSUE THREAD

**Issue by Zahyra16** [tachiyomiorg/tachiyomi-extensions#10762]
### Source information

YugenMangas v1.2.16

### Steps to reproduce

I enter any Manga at random but it does not load the list of chapters.

### Expected behavior

Load Chapter With chapter name and chapter number

### Actual behavior

The list of Chapters appears but without the Chapter Number.

### Tachiyomi version

v0.13.1

### Android version

Android 8

### Other details

The web page has changed the way your chapter listing looks and the program is unable to list it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Veysinator** [comment]
I'm no expert and don't know how this translates into Android but on a PC manga app, adding 'div.chapter-link > a' for getting chapters fixed the issue, hope this helps.

**Comment by alessandrojean** [comment]
Already fixed by current versions of the extension.
