### ISSUE TITLE
Comikey: Add support for loading chapters through the official app

### ISSUE THREAD

**Issue by starg09** [tachiyomiorg/tachiyomi-extensions#10761]
### Describe your suggested feature

So it appears [Comikey now has an official android app in the Play Store](https://play.google.com/store/apps/details?id=com.comikey.banagher), released about a week or so ago. Taking a quick peek, it seems to properly handle permalinks to a specific chapter of any series, opening them directly in the app itself.

Would it be possible, as an option in settings (maybe opt-out as a temporary workaround, until someone can eventually look into #9075) for making opened chapters be handled through a browser opening? Sadly it probably wouldn't be able to recognize a chapter being read, or at what page you left. But it'd be handy, compared to the current way of "Pressing web view, opening the chapter, pressing options, opening in actual browser".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
no, use their app if you want to use it. migrate away from comikey or wait until 9075 is fixed.
