### ISSUE TITLE
copymanga: manga cannot be loaded

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi-extensions#10768]
### Source information

copymanga 1.2.23

### Steps to reproduce

first open manga
loading
failed
![Screenshot_20220209_124646_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/36665073/153123840-3e3f20ca-0ede-43fc-a796-2de1a253036f.jpg)

### Expected behavior

picture can be loaded after a while

### Actual behavior

this website can be opened in the webview
But pictures can't be loaded or download ed
, even the cover of the manga

### Tachiyomi version

Preview r4139

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by constfold** [comment]
Image loading works fine for me. But popular/latest manga is broken. 

I checked the source and have a little question: does `GET` also execute javascript? Because the website generates manga list by some scripts now.
