### ISSUE TITLE
Hiperdex - in Library tag broken. [NSFW]

### ISSUE THREAD

**Issue by Ninjistix** [tachiyomiorg/tachiyomi-extensions#10778]
### Source information

Hiperdex 1.2.20

### Steps to reproduce

1. Add several manga to library
2. browse source latest/popular
3. some of the manga added to the library don't show "in library" tag 

### Expected behavior

when browsing the source the in library feature allows you to keep track what is in your library or not

### Actual behavior

this bug can cause you to add the same manga multiple time's to your library from the same source.

### Tachiyomi version

TachiyomiJ2K v1.4.4

### Android version

Android 12

### Other details

[removed screenshots as requested]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Removed the screens cause they aren't necessary.  If you click on the browse manga and add to library again, does it now show marked correctly?  You just have duplicates in your library?

**Comment by Ninjistix** [comment]
if I click browse source, it says its not in library even though I have it in my library and currently reading it. when I add it again, it duplicates it in the library, from the same source. Furthermore if I go back to browse source after adding it again it's marked "in library", If I remove the first copy and leave the newly added one, when I go back to browse source if there's a new chapter, its not marked "in library" anymore, and I have to add it again.

**Comment by CarlosEsco** [comment]
thanks for the extra info, will help when someone attempts to fix it

**Comment by Seishirou101** [comment]
can you share the url of the one in your library and one you find in browse? I bet they're changing the url

**Comment by Ninjistix** [comment]
sure let me check.

**Comment by Ninjistix** [comment]
in the case of some other websites that change their url by adding random numbers, it seems that all the manga have a permanent url based on #9499 

(source)
https://hiperdex.com/manga/everything-is-agreed-upon-130222/
(library)
https://hiperdex.com/manga/everything-is-agreed-upon-271121/
(permanent url)
https://hiperdex.com/manga/everything-is-agreed-upon/

same goes for the above link
(permanent url)
https://hiperdex.com/manga/my-brothers-slipped-inside-me-in-the-bathtub/

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
