### ISSUE TITLE
Mangahub

### ISSUE THREAD

**Issue by Dragontiger33** [tachiyomiorg/tachiyomi-extensions#10774]
### Source name

Mangahub

### Source link

https://mangahub.io

### Language

English

### Other details

Mangahub doesn't show up on the extension since the update. When I add it through an apk, it then says that the extension is obsolete. Please fix this. Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension already exists. You need to uninstall your obsolete one and install the new one. Migration isn't necessary.
