### ISSUE TITLE
Shea manga -Change Domain-

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#10783]
### Source information

Shea manga 1.2.15

### Steps to reproduce

1. Open extension
2. 
![Screenshot_2022-02-11-00-06-18-907_eu kanade tachiyomi](https://user-images.githubusercontent.com/23666289/153435869-277b8703-9028-4a91-bd8a-723400050a1f.jpg)
3. Open in web view change domain to http://62.171.176.78/

### Expected behavior

NXDOMAIN

### Actual behavior

NXDOMAIN

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
Matiin `DNS over HTTPS` buat sekarang. DoH bermasalah kalo langsung konek/redirect ke ip
