### ISSUE TITLE
Mangceh: Changed their domain and theme

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#10784]
### Source information

Mangceh 1.2.18

### Steps to reproduce

1. Open extension http error 400
2. Open in web view change domain from https://mangceh.me/ to https://mareceh.com/

### Expected behavior

Manga not shown

### Actual behavior

Http Error 400

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Mangceh: Changed their domain and theme"

**Comment by TheKingTermux** [comment]
Dah up
Nunggu disetujuin Ama team inspeksi

**Comment by ZekkenID** [comment]
@TheKingTermux thank you

**Comment by TheKingTermux** [comment]
> @TheKingTermux thank you

Ok

**Comment by TheKingTermux** [comment]
Dah up ya gan 😁
Selamat menikmati
