### ISSUE TITLE
Allied Fansub

### ISSUE THREAD

**Issue by Veysinator** [tachiyomiorg/tachiyomi-extensions#10795]
### Source name

Allied Fansub

### Source link

https://alliedfansub.online

### Language

Turkish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader

**Comment by ArminArlert31** [comment]
> 



> Uses WPMangaReader

what does this mean is not added is there any other alternative to read sorry ı dont understand

**Comment by jopejoe1** [comment]
It means that the website is using the WPMangaReader theme, meaning it is simmilar to other sites also using the same theme.
