### ISSUE TITLE
Mangasusu NXDOMAIN

### ISSUE THREAD

**Issue by bgmondy** [tachiyomiorg/tachiyomi-extensions#10798]
### Source information

mangasusu 1.2.12

### Steps to reproduce

1. open browse
2. open mangasusu
3. issue here, can't open because 194.233.87.209 NXDOMAIN

### Expected behavior

this should can open and read

### Actual behavior

this happened can't open and read buat in web mode can

### Tachiyomi version

0.13.1

### Android version

Android 8

### Other details

i don't know this happened only me or no but i still tell this maybe another peoples the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZekkenID** [comment]
Matiin DOH mirip kasus yang ane buat
#10783

**Comment by Kwmwm** [comment]
``

**Comment by arkon** [comment]
Merging with #11019
