### ISSUE TITLE
Reaper Scans Turkey

### ISSUE THREAD

**Issue by ADAMA63** [tachiyomiorg/tachiyomi-extensions#10790]
### Source name

Reaper Scans Turkey

### Source link

https://tr.reaperscans.com/

### Language

Turkish

### Other details

turkısh webtoons

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara, needs to be added to ReaperScansFactory (which already exist for en and pt-br)

**Comment by Veysinator** [comment]
New domain is 'https://reaperscanstr.com'

**Comment by kyoyacchi** [comment]
Any updates on this?
