### ISSUE TITLE
Updates not give new chapter. Even in web still update. After update app

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#10797]
### Source information

Library updates

### Steps to reproduce

>Open tavhiyomi
>Refresh update/auto update 
>no update pop-up

If you want update you must refresh the manga/manhwa one by one. 

### Expected behavior

Popup new chapter in update slot or in the manga/manhwa.

### Actual behavior

Nothing new chapter available, but in web still updates. 

### Tachiyomi version

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z) Android version: 9 (SDK 28) Android build ID: 47.2.C.1.126 Device brand: KDDI Device manufacturer: Sony Device name: SOV36 Device model: SOV36 Device product name: SOV36_jp_kdi

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Read the changelog. https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
