### ISSUE TITLE
Nhentai, hitomi not showing in extensions browser

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#10803]
Tachiyomi version lastest stable
android 12 
Aex Rom

when i search nhentai or hitomi neither of them appear in browser extension, not a big deal since i can download the extensions manually from GitHub repo just weird, this happened after i update the app.
![Screenshot_20220212-055950_Tachiyomi.png](https://user-images.githubusercontent.com/64289536/153710702-ff02c137-acc5-47b9-8cd1-6bfb56b8f932.png)

**Comment by curche** [comment]
Do you have ALL and Eng sources enabled
You can do it from Sources > Extension - top right corner (translate button)

![Screenshot_20220212-180621_Tachiyomi_all](https://user-images.githubusercontent.com/72807749/153711631-47ba521b-ad40-4b1c-84b2-3193ef433f83.png)

**Comment by Mtkmanjaro** [comment]
@curche yeah i have enabled, edit solved after reinstall the app
