### ISSUE TITLE
update link Manga Pro Z

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#10817]
### Source name

update link Manga Pro Z

### Source link

https://mangaprotm.com

### Language

Arabic

### Other details

Please update the link because the old link to the source is no longer working

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is not a source request since the extension already exists. Please fill the issue report form instead.
