### ISSUE TITLE
Tappytoon.com - User does not have the license of requested content (even on unlocked chapters).

### ISSUE THREAD

**Issue by cecoates** [tachiyomiorg/tachiyomi-extensions#10827]
### Source information

TappyToon 1.2.5

### Steps to reproduce

1. Login to the Tappytoon extension via Webview.
2. Open the chapter list of a Tappytoon series in your library.
3. Refresh.
4. Chapters that appear unlocked in Webview remain locked within the Tachiyomi chapter list.

### Expected behavior

Chapters you've unlocked via the Tappytoon app/your Tappytoon account appear unlocked.

### Actual behavior

All chapters (except the ones that are always free, like the first three issues of a series) remain locked.

### Tachiyomi version

0.13.1

### Android version

Android 11 and Android 7

### Other details

Logging in view Webview and viewing chapters in Webview works fine. But chapters can't be downloaded or viewed via Tachiyomi.

I also tried reinstalling the extension, clearing cookies via the extension, and restarting Tachiyomi after logging in via Webview.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Restarting Tachiyomi shows the unlocked chapters properly for me.

Is there a particular series this occurs on? How did you unlock the chapters?

**Comment by cecoates** [comment]
I've restarted Tachiyomi, made sure the extension is updated to the most recent version, double-checked that I'm logged in via Webview. I've also refreshed the chapter list when I check, too.

Only the free chapters can be viewed or downloaded.

For me it doesn't matter whether you've unlocked a chapter with coins, or are using Wait Until Free.

It affects all series. As an example, here's Adelaide, which I'm reading as Wait Until Free:
![Screenshot_20220312-171632](https://user-images.githubusercontent.com/10121835/158038516-5b257c67-8b4e-4738-9943-adbfbc109130.png)
![Screenshot_20220312-171700](https://user-images.githubusercontent.com/10121835/158038517-678fbfea-8223-4d03-90be-fc018c75ccdc.png)

And here's A royal princess with black hair, which was unlocked with coins:
![Screenshot_20220312-172647](https://user-images.githubusercontent.com/10121835/158038552-835519f9-d7b0-48c8-a537-1c9e25d79c14.png)
![Screenshot_20220312-172131](https://user-images.githubusercontent.com/10121835/158038553-cbfad434-b15a-464f-8846-721d65b2e807.png)

The first 3-4 issues of most series are free, so those can be viewed/downloaded:
![Screenshot_20220312-172758](https://user-images.githubusercontent.com/10121835/158038581-a0646755-1308-4dbc-9b47-c5a9669fa430.png)

But nothing that you have to "unlock".

Tachiyomi 0.13.1 and extension version 1.2.6. The above screenshots are my Pixel 4a running Android 12, but behavior is the same on my Pixel C running Android 8, my Chromebook running Android 11, and even Memu running Android 7.

**Comment by cecoates** [comment]
Here's Chapter 49 of Royal Princess and Chapter 50 of Adelaide from the above examples opened in Webview, to demonstrate they're unlocked and viewable and that I'm logged in:

![Screenshot_20220312-173652](https://user-images.githubusercontent.com/10121835/158038766-59f5f8bf-6452-4722-b139-cdd5a6a222eb.png)
![Screenshot_20220312-173714-01](https://user-images.githubusercontent.com/10121835/158038837-0bf19ed5-9ce8-4efc-b2c0-13eb24de3119.jpeg)

**Comment by alessandrojean** [comment]
> I'm logging into Tappytoon via a Google rather than an email address and password

Google usually doesn't allow sign-in through WebView. Would be good if you can test if the issue occurs with a simple email/password account.

**Comment by cecoates** [comment]
I created a regular email/password login for Tappytoon for testing and I'm still getting logged out of Tappytoon between restarts. 

I reinstalled the extension again and cleared cookies in Tachiyomi to be safe. Tested it on all four devices, Pixel C, Pixel 4a, Pixelbook, and Memu. 

I'm kinda stumped. 

I also use Pocket and Tapas, and those seem to be staying logged in between restarts.

**Comment by alessandrojean** [comment]
Good you tried, so it's most likely related to how they implement their authentication maybe. Needs further investigation.

**Comment by ObserverOfTime** [comment]
I'm also signing in with Google and have no authorisation issues whatsoever. :thinking:
