### ISSUE TITLE
Hentai Cube duplicate pages

### ISSUE THREAD

**Issue by My2ndAngelic** [tachiyomiorg/tachiyomi-extensions#10820]
### Source information

Hentai Cube 1.2.15

### Steps to reproduce

1. Choose any manga
2. Just start reading in any mode

### Expected behavior

This should only display a page once

### Actual behavior

The extension display the same page twice for some reason, for every page.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mihawk1890** [comment]
It's happen again.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
