### ISSUE TITLE
Komga chapters won't load

### ISSUE THREAD

**Issue by dsheemstra** [tachiyomiorg/tachiyomi-extensions#10838]
### Source information

Komga 1.2.39

### Steps to reproduce

1. I set up my komga server
2. I see my different series when accessing the "Komga" source
3. When accessing one of those series, an error is given and no chapters load

### Expected behavior

I expect to see a list of all the chapters for the series

### Actual behavior

Instead it says "0 chapters" and gives error "Field 'seriesTitle' is required for type with serial name 'eu.kanade.tachiyomi.extens..."

### Tachiyomi version

0.13.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You probably need to update your Komga server.

**Comment by joaquin-rossi** [comment]
> You probably need to update your Komga server.

Can confirm that this worked for me.

**Comment by arkon** [comment]
Refer to [the changelog](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/komga/CHANGELOG.md) as needed.
