### ISSUE TITLE
IsekaiScan.com doesn't work anymore

### ISSUE THREAD

**Issue by MatisPrograms** [tachiyomiorg/tachiyomi-extensions#10834]
### Source information

IsekaiScan.com 1.2.19

### Steps to reproduce

1. Open chapter X using isekaiScan.com as source.
Or
2. Click on isekaiscan.com to browse scans

### Expected behavior

1. It should open the chapter like for any other extension

2. It should bring up a list of suggested scans that you can read from that source like for any other extension

### Actual behavior

When sending a request to the source website, there is no response thus having a timeout and then getting brought back to the previous page.

### Tachiyomi version

Aniyomi 0.12.3.6

### Android version

Android 11

### Other details

I have sent this issue to Aniyomi directly but since it was a problem with the manga extensions they told me to come here instead.

Recently the hole website was down (for several days) and when it went back online it became impossible to use the IsekaiScan.com extension due to probably changes that was done to the website (maybe more security)

App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 11 (SDK 30)
Android build ID: KB2000_21_211221
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus8T
Device model: KB2000
Device product name: OnePlus8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Looks like they're still down to me
![Screenshot_20220215-120438_Takoyomi.png](https://user-images.githubusercontent.com/70870719/154058776-6ed2cf90-bbce-4aa7-80bd-c315d5aff0d7.png)

**Comment by MatisPrograms** [comment]
Ooh it was working still very recently, but when it was online I was getting a Cloudflare error as if the website was blocking tachiyomi, because with a normal browser, you could use the website normally.

**Comment by CrepeTF** [comment]
Yeah checked now, couldn't access it through a dedicated browser, they're probably still having issues and their status could fluctuate
