### ISSUE TITLE
 YugenMangas: Wrong chapter list information

### ISSUE THREAD

**Issue by Omar9460** [tachiyomiorg/tachiyomi-extensions#10847]
### Source information

YugenMangas 1.2.16

### Steps to reproduce

![Screenshot_2022-02-17-04-29-00-576_eu kanade tachiyomi](https://user-images.githubusercontent.com/99868737/154437575-632b079a-ec3d-4e23-892d-c85ff8547f43.jpg)

this is how all the sleeves of the extension come out

### Expected behavior

The respective number of each chapter and its publication date should appear

### Actual behavior

all chapters have the same number and date

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

hadn't had any problems until the extension was updated and the old one was deprecated

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Omar9460** [comment]
> /edit-title" YugenMangas: Wrong chapter list information"

Thanks

**Comment by alessandrojean** [comment]
Already fixed by current versions of the extension.
