### ISSUE TITLE
TOPTOON+: Could not get the chapter images

### ISSUE THREAD

**Issue by NotBot9** [tachiyomiorg/tachiyomi-extensions#10846]
### Source information

Toptoon+ 1.2.4

### Steps to reproduce

Search for manhwa
Open the result from Toptoon+ site
Open any free chapter currently showing
Error message "Could not get chapter images"
Open the manhwa in webview and login to account
Open the chapter in webview, chapter shows up and displays correctly
Go back to Tachiyomi, open same chapter, does not open, same error.

### Expected behavior

Search for manhwa
Open the result from Toptoon+ site
Open any free chapter currently showing
 **Should ask to open chapter in webview/login via webview**
Open the manhwa in webview and login to account
Open the chapter in webview, chapter shows up and displays correctly
**Go back to Tachiyomi, open same chapter, chapter displays correctly and can be donloaded normally.**

### Actual behavior

Search for manhwa
Open the result from Toptoon+ site
Open any free chapter currently showing
Error message "Could not get chapter images"
Open the manhwa in webview and login to account
Open the chapter in webview, chapter shows up and displays correctly
Go back to Tachiyomi, open same chapter, does not open, same error.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the form correctly next time. They're adding captcha to a lot of their API endpoints, I recommend migrating to other sources.

**Comment by alessandrojean** [comment]
/edit-title "TOPTOON+: Could not get the chapter images"
