### ISSUE TITLE
Lien mort Scan-Manga (FR)

### ISSUE THREAD

**Issue by Freedent-72** [tachiyomiorg/tachiyomi-extensions#10843]
### Source information

Scan-Manga version 1.2.6

### Steps to reproduce

Ouvrir l'extension et observer l'impossibilité à accéder au site, même avec webview.

### Expected behavior

Accès à la source

### Actual behavior

Le lien renvoie vers une mauvaise adresse (https://www.scan-manga.com/403.html) au lieu de la bonne (https://m.scan-manga.com/?home). Le site se nomme toujours pareil mais il a du migrer. Impossible d'ouvrir le lien dans webview, il faut obligatoirement passer par le navigateur externe de l'application qui renvoie vers le bon lien.

### Tachiyomi version

App version: 0.13.1 (standard)

### Android version

 Android version: 10 (SDK 29)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Duplicate of #9720
