### ISSUE TITLE
Webnovel Extension not working

### ISSUE THREAD

**Issue by ThatOneIndian** [tachiyomiorg/tachiyomi-extensions#10845]
### Source information

WebNovel 1.2.18

### Steps to reproduce

1. open extension web view 
2. clicking on latest 
3. updates(when it did work)

### Expected behavior

open the webpage of the extension

when clicking on latest the catalog of updates should appear

newly uploaded chapters should appear instead of an error after finishing the updating process

### Actual behavior

![Screenshot_20220216-231213_HTML Viewer](https://user-images.githubusercontent.com/54968402/154424206-2dd2d6a9-d04c-4120-b302-bf7f55436b13.jpg)

returning errors

Failed to connect to webnovel.live/45.33.111.97 (port 443) from /28.38.31.62 (port 50640) after 10000ms

### Tachiyomi version

J2K 1.4.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
1. Your screenshot and the steps you did doesn't match
2. The site is down (check webview)

**Comment by ThatOneIndian** [comment]
Isn't this the website though? https://www.webnovel.com/stories/comic 
it seems up

**Comment by FourTOne5** [comment]
no you're using the source of webnovel.live which is down.

P.S. The source of webnovel.com is named "Webnovel.com"

**Comment by FourTOne5** [comment]
no you're using the source of webnovel.live which is down.

P.S. The source of webnovel.com is named "Webnovel.com"
