### ISSUE TITLE
Bilibili Comics: Some Free Chapters Not Being Shown

### ISSUE THREAD

**Issue by mrehanabbasi** [tachiyomiorg/tachiyomi-extensions#10844]
### Source information

Bilibili v1.2.6

### Steps to reproduce

1. Open BILIBILI COMICS source.
2. Open "Emperor-in-Law" manhua.
3. Swipe down to refresh.

### Expected behavior

All free-to-read chapters should show up as I am logged into my account in the webview.

### Actual behavior

Only the first 24 chapters are being shown.

### Tachiyomi version

Preview r4163

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Only chapters up to 24 are free, chapters from 25 are paid chapters which can be unlocked by waiting for some time or buying them with coins. After you have unlocked them they will be visible in the extension.

**Comment by alessandrojean** [comment]
Logging in into your account doesn't necessarily mean you will have access to paid chapters. You have to follow what jopejoe1 said. Please search if it isn't the case in WebView next time.
