### ISSUE TITLE
Mangadex issues in some magas chapter list is broken 

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#10857]
Tachiyomi version: 0.13.1 (74)
Android versión :12

in some mangas the list of charpters is incomplete, despite of in magadex web page all charpters are showed 

Tachiyomi app
![](https://i.imgur.com/nXjRuqx.png)

Web view mode of managdex
![](https://i.imgur.com/uBjeWBQ.png)

**Comment by curche** [comment]
There is an Icon besides to the left of Ch. 59 that lets you know that the chapter is available at a different Website
In this case, Ch 59 of Spy X Family is available in MangaPlus

Such chapters, which link to an outside/external site, will not be shown inside Tachiyomi Mangadex (EN) extension. You can read those chapters in that outside website or check if there are extensions in Tachiyomi for those websites

Also, the other Ch 59 is in a Different Language (not in EN) and so wont be shown in MangaDex (EN)

**Comment by alessandrojean** [comment]
Also please open a new issue using the website and following one of the forms next time.
