### ISSUE TITLE
Remanga extension broke

### ISSUE THREAD

**Issue by UselessKiska** [tachiyomiorg/tachiyomi-extensions#10853]
### Source information

Remanga 1.2.44

### Steps to reproduce

1. Update library
2.tadaaa!

### Expected behavior

Showing new chapters of mangas

### Actual behavior

"field 'publishers' is required for type with serial name 'bookdto', but it was missing"

### Tachiyomi version

App version: 0.13.1

### Android version

Android 10

### Other details

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 10 (SDK 29)
Android build ID: lineage_oneplus3-userdebug 10 QQ3A.200805.001 3fda701337
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus3T
Device model: ONEPLUS A3003
Device product name: lineage_oneplus3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pavkazzz** [comment]
Will take a look
