### ISSUE TITLE
Treemanga not working

### ISSUE THREAD

**Issue by allishona** [tachiyomiorg/tachiyomi-extensions#10862]
### Source information

Treemanga 1.2.16

### Steps to reproduce

1. Open the manga
2. Click the chapter
3. Click the latest chapter
4. Does not load. "Retry" (All other extensions actually work).

### Expected behavior

It should open the latest chapter of the manga and actually load it. 

### Actual behavior

It only keep saying "Retry".

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

![Screenshot_20220218-002415_Tachiyomi](https://user-images.githubusercontent.com/84158024/154685252-9a38c4ec-aae4-42e4-858b-2e049064b139.jpg)
![Screenshot_20220218-002403_Tachiyomi](https://user-images.githubusercontent.com/84158024/154685261-b69711b7-53b5-45fe-9fd3-05c416d112fa.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
cant reproduce
