### ISSUE TITLE
Pocket Comics error: "Field 'authors' is required for type with serial name"

### ISSUE THREAD

**Issue by cecoates** [tachiyomiorg/tachiyomi-extensions#10866]
### Source information

Comico 1.2.2

### Steps to reproduce

1. Install Comico extension.
2. Open Browse->Sources->Pocket Comics
3. Browse the Pocket Comics source.

### Expected behavior

Recent comics list loads without errors.

### Actual behavior

Sometimes the error seems to prevent the Recent list from loading. Usually it loads, but with an error message:

![Screenshot 2022-02-19 07 23 33](https://user-images.githubusercontent.com/10121835/154802722-728b7bff-da9c-4675-9fc5-41ae53551089.png)

### Tachiyomi version

0.13.1

### Android version

Android 11 and Android 7

### Other details

Extension seems to still work for searching and downloading. Error only appears when browsing the source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by plumber-craic** [comment]
Interesting. I get the same, but my field is seriesTitle

**Comment by ObserverOfTime** [comment]
> Interesting. I get the same, but my field is seriesTitle

That's not the same extension…
