### ISSUE TITLE
星世界

### ISSUE THREAD

**Issue by tatular** [tachiyomiorg/tachiyomi-extensions#10876]
### Source name

星世界 

### Source link

https://bgdmfcb.com/

### Language

Chinese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
The site has hidden most titles, so it's not worth making an extension now. You may want to close this issue.

**Comment by vetleledaal** [comment]
Site has been down for at least a week, closing.
