### ISSUE TITLE
Arcane Scan

### ISSUE THREAD

**Issue by Mylloon** [tachiyomiorg/tachiyomi-extensions#10882]
### Source name

Arcane Scan

### Source link

https://arcanescan.fr/

### Language

French

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader

**Comment by pixelroll** [comment]
This is the website of a French team, which translates the least advanced webtoons in France.
For example The Beginning After The End
In short, all webtoons available on this site get a very fast and high quality translation.
Thanks
