### ISSUE TITLE
H2R yields no search results with works tagged with "lolicon"

### ISSUE THREAD

**Issue by Axelrhode** [tachiyomiorg/tachiyomi-extensions#10880]
### Source information

Hentai2Read 1.2.13

### Steps to reproduce

1) Search any works tagged with "lolicon" (even a simple category search would do)
2) wait to load results
3) "no results found"

### Expected behavior

The extension should be able to show all works with the said tag

### Actual behavior

It yields no results instead

### Tachiyomi version

0.13.1

### Android version

Android 10

### Other details

Only lolicon yields that result, but shotacon works with no problem. Shotacon + lolicon is affected too.

On webview, the website shows all results. Only through the app/extension it doesn't. I've also used TachiyomiSY and J2K, so it just reinforces the idea its an extension problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Axelrhode** [comment]
So basically, lolicon is a bad search for the extension.

**Comment by Seishirou101** [comment]
I'm going to close this one since #11622 and I already asked there.
