### ISSUE TITLE
Mangahub not working

### ISSUE THREAD

**Issue by MLGrugu** [tachiyomiorg/tachiyomi-extensions#10888]
### Source information

Mangahub

### Steps to reproduce

Whenever I try to open the extension, it say that the extension cannot be used anyone.

### Expected behavior

Extension would open the show the list of mangas.

### Actual behavior

But it didn't open.

### Tachiyomi version

0.13.1

### Android version

11

### Other details

Not really.Just that Mangahub stopped working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Vayneart** [comment]
Yes, just now, all my mangahub titles are not accesible. Too bad that almost 70% of my titles are from mangahub... Please fix Iruichi :v

**Comment by arkon** [comment]
The website is clearly down, there's nothing to be done on Tachiyomi's side.

**Comment by arkon** [comment]
I'll keep this open since multiple people aren't bothering to check what's wrong.
