### ISSUE TITLE
TuttoAnimeManga not working

### ISSUE THREAD

**Issue by aslupo98** [tachiyomiorg/tachiyomi-extensions#10884]
### Source information

TuttoAnimeManga 1.2.3

### Steps to reproduce

Simply is not working.

### Expected behavior

A list of manga should appear, and also the saved manga should works.

### Actual behavior

But nothing. "No results found"

### Tachiyomi version

0.13.1

### Android version

11

### Other details

Sorry, but now i can't upload img. But i think is not important. Black screen and "no results found" when you open the extension.

I think TuttoAnimeManga staff updated the site, so the extension doesn't work anymore

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MLGrugu** [comment]
Same issue with me brother but a different extension.
