### ISSUE TITLE
Shounen Jump+: Add deeplink support

### ISSUE THREAD

**Issue by sad-kato** [tachiyomiorg/tachiyomi-extensions#10885]
### Describe your suggested feature

links that are in the shonen jump website "https://shonenjumpplus.com/" will open in tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Kinda hard to add this at the moment since they don't have a series page. All chapters of a series are only listed inside a chapter page, and this can change when they add new chapters, making the URL of the entry obsolete.
