### ISSUE TITLE
Remove Lynx Scans

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi-extensions#10883]
### Describe why this should be added

The site was DMCA'd several weeks back and now their hostname just redirects to their discord server now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by NotPageD** [comment]
this isn't the case anymore, their site is up again.
