### ISSUE TITLE
Error 429 

### ISSUE THREAD

**Issue by EmilioVal** [tachiyomiorg/tachiyomi-extensions#10899]
### Source information

TuMangaOnline 1.2.36

### Steps to reproduce

I just update my library and send error 429 and 18 fails

### Expected behavior

Normaly the library update

### Actual behavior

But the error 429 shows

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
429 == you were rate limited.  Don't download so much on the source and split your library into more than 1 source
