### ISSUE TITLE
Banana Crítica: Changed their domain

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#10906]
### Describe your suggested feature

Novo link 
https://dinastiacilly.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
Please use the proper [form](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new?assignees=&labels=Source+request&template=request_source.yml).

**Comment by alessandrojean** [comment]
Please fill the issue report form next time, this isn't the correct form for reporting domain changes.

**Comment by Samuel9santos** [comment]
New site link
https://dinastiacilly.com

**Comment by alessandrojean** [comment]
> New site link https://dinastiacilly.com

It was already reported in the issue, you don't need to comment that again.

**Comment by GasaiYunoV2** [comment]
Kkkkkkkkkkk desculpa, além de pedir novas extensões, eu ainda tô aprendendo a mexer nisso. Eu não sabia qual deles usar, não tinha nenhum explícito pra troca de link. Foi mal mesmo.
