### ISSUE TITLE
Setting reading direction for each book like Komga

### ISSUE THREAD

**Issue by catherney** [tachiyomiorg/tachiyomi-extensions#10913]
### Describe your suggested feature

In Komga, we could set each book to different reading direction we need(like manga from right to left,or webtoon mode). If there is any possible way to implement this function in tachiyomi through komga extensions, or by other way? Thanks a lot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Relevant issue from main app repo - https://github.com/tachiyomiorg/tachiyomi/issues/1664

**Comment by catherney** [comment]
> Relevant issue from main app repo - [tachiyomiorg/tachiyomi#1664](https://github.com/tachiyomiorg/tachiyomi/issues/1664)

Thanks for replying. What I think about is that if it is possible to auto-set reading direction
