### ISSUE TITLE
Everia.club: Some chapter images do not load

### ISSUE THREAD

**Issue by PhamKun** [tachiyomiorg/tachiyomi-extensions#10918]
### Source information

Everia.club version 1.2.1

### Steps to reproduce

1. Open Tachiyomi
2. Open Everia.Club
3. Open any Gallery

### Expected behavior

1. Every gallery should show their banner properly
2. When open a gallery, it show pictures, display correctly the amount of image on each page.

### Actual behavior

1. Some Gallery show its banner, but almost all of them doesnt
2. Picture in each gallery display like this: Not Loaded - Loaded - Not Loaded - Loaded. It seems the extension pickup more pictures than the page actually have. For example: A Gallery I was trying to see show 20 pictures, while I counted 15 in the WebView page.

### Tachiyomi version

1.13.1

### Android version

I tried it on my Pixel 6 - Android 12, and OnePlus 6T - Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Everia.club: Some chapter images do not load"
