### ISSUE TITLE
NewToki/Manatoki URL changed 

### ISSUE THREAD

**Issue by airflow0** [tachiyomiorg/tachiyomi-extensions#10914]
### Source information

NewToki/Manatoki v1.2.22

### Steps to reproduce

1. Install NewToki/Manatoki APK.
2. Nothing will load

### Expected behavior

Images and list of Manhwas should load 

### Actual behavior

Endless load screen.

### Tachiyomi version

Tachiyomi v0.13.1

### Android version

BlueStacks current Version

### Other details

I went into the code and changed the $domainNumber into an int and set it as 122, built the APK and loaded it on Bluestacks. It seems to work. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> While there is not a permanent fix you can use, you can go to the settings for the extension and change the domain to what's currently used.
Example fix - Changing the override from newtoki62.com to newtoki68.com in your extensions settings.

Have you tried changing it from extension settings instead of building the apk from scratch?

**Comment by Seishirou101** [comment]
Closing as this source is known to change urls often, which is why you can change the url like curche said.
