### ISSUE TITLE
[SOURCE REQUEST] Wecomics [ENG]

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#1092]
(CATALOGUE) SOURCE REQUESTS [ENG]:
Site: wecomics
Link: https://m.wecomics.com/index

**Comment by john24u** [comment]
Plez add this source..... recently tecent bought many comics and they are being uploaded on wecomics only as of now 

Translators have also dropped these comics as it was bought by tecent

So plezz add this source

**Comment by actrbb** [comment]
Yes man please add this source 'i am a great god' official release is available on this only....

**Comment by Samk19** [comment]
@actrbb ya dude i know how you feel my fav IL aka metal goddess soldiers is now on wecomics too (though im sad that they are starting it from the beginning).....

**Comment by as280093** [comment]
Here the icons
[Wecomics.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614382/Wecomics.zip)

**Comment by mra1412** [comment]
When will it be added?

**Comment by AbdullahM0hamed** [comment]
When someone decides to add it, and submits a PR.

**Comment by Hyoretsu** [comment]
Bump, Won't There Be a Problem if the Hero is Such a Horrible Person is another manhua only available there

**Comment by Godtier69247** [comment]
Rise Against Doomsday is another manhua only available there.

**Comment by mrehanabbasi** [comment]
Any idea whether someone's working in it or not?

**Comment by Godtier69247** [comment]
No Idea man, no one got back to me...
