### ISSUE TITLE
MangaPark: Missing chapters

### ISSUE THREAD

**Issue by einstein591** [tachiyomiorg/tachiyomi-extensions#10925]
### Source information

MangaPark v1.2.23

### Steps to reproduce

I am using the MangaPark extension and I look up "Naruto: The Seventh Hokage and the Scarlet Spring" (link: https://v2.mangapark.net/manga/naruto-the-seventh-hokage-and-the-scarlet-spring).

### Expected behavior

I should be seeing all ten chapters from the website on the app.

### Actual behavior

I only see the first chapter on the app.

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Does it work on v3? I don't think we should fix issues for their old ones since they've moved to v3

**Comment by einstein591** [comment]
I see more than one chapter, but I do not see all the sources for this manga.
