### ISSUE TITLE
Yaoi Toshokan: Some older chapter images do not load

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#10922]
### Source information

Yaoi Toshokan 1.2.18

### Steps to reproduce

Não baixa quase nenhum capítulo. Abro no webview e carrega as páginas normais mas no gerenciador de download fica lá tipo (19 páginas) e nunca começa, até expira e cancela.

### Expected behavior

Ler offline normalmente 

### Actual behavior

Não baixa as imagens 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the information in English next time to keep a pattern to contributors.

**Comment by SrW0nka** [comment]
After some time researching [examples](https://www.yaoitoshokan.net/manga/sotsugyousei/) I figure out some old images are just broken 
![image](https://user-images.githubusercontent.com/76596575/155620856-37195cd0-9a81-468e-8411-895494567656.png)

99% sure there's nothing wrong with the extension

**Comment by alessandrojean** [comment]
These chapters from this title are loading for me in the website though, but not on the extension. They probably changed something, I will take a look soon.

**Comment by KaraSupergirl** [comment]
Wonderful, updated and now it's working perfectly. I loved it, thank you very much.
