### ISSUE TITLE
Library Update Errors

### ISSUE THREAD

**Issue by Supert567** [tachiyomiorg/tachiyomi-extensions#10937]
### Source information

Readme, manganato

### Steps to reproduce

1.Update
2.Error notification and no chapter update
3. No profit
![Screenshot_2022-02-26-01-54-48-32_2c9606bce337650a539aceea20c7df58](https://user-images.githubusercontent.com/43806645/155833384-16dfc788-afdc-45fd-86d8-278f03e8ef3c.jpg)

### Expected behavior

It should just update 🤓

### Actual behavior

Picture seen above.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

I've got a total of 100+ manga saved and before updating to this most recent update they all updated. But now when I pull down to update only 17 manga update, and then I get errors for the rest. 
The weird thing is they STILL do update if I go one by one on each manga and update them alone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  I have tried the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) guide.

Atleast try to read what youre acknowledging...

**Comment by Supert567** [comment]
I have read the troubleshooting and haven't found the SPECIFIC issue that I am having or have overlooked it. Thank you kindly for the literal no help you gave and closed.
