### ISSUE TITLE
Manhwa Time: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#10939]
### Source information

Manhwa Time 1.2.15

### Steps to reproduce

1. Open Extension 

### Expected behavior

It should open 

### Actual behavior

Faild to bypass Cloudflare
![Screenshot_2022-02-26-11-56-38-377_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/93197738/155838928-74c02fe3-238c-441d-9227-5ef568eab53f.jpg)

### Tachiyomi version

App version: 0.13.1-4170 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Manhwa Time: Failed to bypass Cloudflare"

**Comment by Riztard** [comment]
site is dead? or region block?

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
