### ISSUE TITLE
MangaLink: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#10940]
### Source information

مانجا لينك 1.2.17

### Steps to reproduce

1. Open Extension 
2. Open Chapters normally 
3. Star Reading 
4. Failed to bypass Cloudflare 

### Expected behavior

It should open 

### Actual behavior

This Happens Instead 
![Screenshot_2022-02-26-12-10-31-138_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/93197738/155839220-01609d2b-c32a-4746-9048-53964e50f752.jpg)

### Tachiyomi version

App version: 0.13.1-4170 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
