### ISSUE TITLE
Asura Scans showing HTTP error 404

### ISSUE THREAD

**Issue by AnimePsychoT2** [tachiyomiorg/tachiyomi-extensions#10950]
### Source information

Asura Scans 1.2.23

### Steps to reproduce

![Screenshot_20220227-204048_Aniyomi](https://user-images.githubusercontent.com/100519479/155882970-7162022a-8e14-4fea-92ce-3c3d5c364c95.jpg)

### Expected behavior

It must open the chapter 

### Actual behavior

It's showed HTTP error 404

### Tachiyomi version

0.12.3.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by matmakif** [comment]
Domain changed.
Old adress: https://tr.asurascans.com/
New adress: https://asurascanstr.com

**Comment by kyoyacchi** [comment]
@AnimePsychoT2 It seems its working with new update of extension. Try updating the extension and see.

**Comment by AnimePsychoT2** [comment]
It works now. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
