### ISSUE TITLE
Allow for mass (but specific) read history deletion 

### ISSUE THREAD

**Issue by DaiyanB** [tachiyomiorg/tachiyomi-extensions#10957]
### Describe why this should be added

There are only two ways to delete one's history as of now and that's by either going one by one or deleting the all at once. I think adding a feature so that you could (for example) long press on a manga in the history tab and then it will allow you to select certain manga that you could then delete. Just like how you can long press a manga in your library to delete or long press a chapter to delete a bunch of chapters but not all of them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

Read why you acknowledge.
