### ISSUE TITLE
Shimada Scans: No results found

### ISSUE THREAD

**Issue by Balla-me** [tachiyomiorg/tachiyomi-extensions#10962]
### Source information

Shimada Scans 1.2.11

### Steps to reproduce

Go to Sources. Open Shimada Scans from the list. It shows "no results found".

### Expected behavior

Source should show the manga available on site.

### Actual behavior

Well.. It doesn't. 404 is understandable. But no results cries out dead source. Can't track manga through app with dead source.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
may be fixed by #11646, you can comment again if the issue still occurs.
