### ISSUE TITLE
WRT chapter image error

### ISSUE THREAD

**Issue by sibernaut** [tachiyomiorg/tachiyomi-extensions#10968]
### Source information

World Romance Translation 1.2.19

### Steps to reproduce

Read or download chapter from some manga

this one for sample [https://wrt.my.id/rouhou-ore-no-iinazuke-ni-natta-jimiko-ie-de-wa-kawaii-shika-nai-chapter-2-bahasa-indonesia/](https://wrt.my.id/rouhou-ore-no-iinazuke-ni-natta-jimiko-ie-de-wa-kawaii-shika-nai-chapter-2-bahasa-indonesia/)

### Expected behavior

Showing chapter images

### Actual behavior

Always show retry button

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
bisa aja di aku, coba troubleshoot lagi
