### ISSUE TITLE
Muito Hentai

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#10963]
### Source name

Muito Hentai

### Source link

www.muitohentai.com

### Language

Português (Brasil)

### Other details

#10276

I forgot to answer you in my last request about this extension, the site is not broken, they just divided the search into two categories, one for hentai manga and another for hentai animation.
You can search them here: https://www.muitohentai.com/mangas/

And all manga that I searched it was working normally...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Militinix** [comment]
@alessandrojean just to confirm one thing, the search bar on this site doesn't search by author, could you fix it by creating the extension?

**Comment by vetleledaal** [comment]
Site is geo-blocked. When you're in the wrong region you only get "NOT FOUND"

**Comment by Militinix** [comment]
I have tested a few sites and most are functioning normally, especially if you are in the US. 
Would this make it difficult to create the extension?
Given that this extension is not for all languages, but only for one?

**Comment by vetleledaal** [comment]
It's mostly a note to other contributors, as to not immediately dismiss the site as non-working
