### ISSUE TITLE
Browsing issue related to Madara extensions

### ISSUE THREAD

**Issue by Yros** [tachiyomiorg/tachiyomi-extensions#10979]
### Source information

1.2.21

### Steps to reproduce

Go into 'Sources' and open the related sources.

The issue appeared after the last extension update ([#10814](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/219bf0b1d215f8a4f928663c4672297c6c742eb4) ). 

Currently, the list of sources affected are :
Manhua ES (1.2.21)
Manhua Plus (1.2.21)
ManhuaUS (1.2.20)

Likely to be related to the recent issues:
[#10972](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10972) 
[#10975](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10975)
[#10980](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10980) 

### Expected behavior

![Screenshot_20220301-154329_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194430-73561924-26be-496e-8f0e-20cbfea71392.jpg)

### Actual behavior

![Screenshot_20220301-153516_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194156-ee616638-9f9c-4b65-81ba-af86d4fd5415.jpg)
![Screenshot_20220301-153521_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194261-cb5c73a3-893d-45a3-b4a2-701768551745.jpg) 

![Screenshot_20220301-154006_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194193-89b5df14-d25e-4cf1-a187-b0ebeea98d0f.jpg)

![Screenshot_20220301-154013_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194233-fd1bcd6f-04d3-4fe9-97c5-b116e97d0e62.jpg)

### Tachiyomi version

TachiyomiSY App version: 1.8.1 (standard, 07e28ca5c, 29, 2022-02-14T01:26Z) Preview build: 441

### Android version

Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.

### Other details

Additional points to note:
- Library update isn't affected. 
- Manually updating a manga from those sources isn't affected. 
- WebView works just fine. 
- Searches work just fine in the sources. Also, when cancelling the search, the 'browse' view appears without any issue.
![Screenshot_20220301-154318_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194243-fd9fc978-aee8-4103-bd0d-ee6cd43badf1.jpg)
 ![Screenshot_20220301-154329_TachiyomiSY](https://user-images.githubusercontent.com/735407/156194430-73561924-26be-496e-8f0e-20cbfea71392.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
To anyone that looks into this issue and are having the same issue: these websites are either incorrectly marking their manga content as video or text, or are using some outdated Madara version.

Ideally, it's up to the site owners to fix this, since the extension is just filtering the non-manga item based on the data provided by the website. But, until that doesn't happen, the extensions can have their selectors individually rollback, please open an issue for the source you're having issues if it's the case.

**Comment by alessandrojean** [comment]
Closing in favour of #10983.
