### ISSUE TITLE
Add manga Source 

### ISSUE THREAD

**Issue by Maretjr101** [tachiyomiorg/tachiyomi-extensions#10973]
### Source name

Mangkomik

### Source link

https://mangkomik.com/

### Language

Indonesia

### Other details

New website , the old one name kiryuu 
I mean is mangkomik is the new ID for kiryuu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Maretjr101** [comment]
Please open the the issue

**Comment by Soitora** [comment]
> Please open the the issue

No. Are you unable to read? The source you're requesting is already requested.
