### ISSUE TITLE
Hentai Manga Extension broken

### ISSUE THREAD

**Issue by ShadowHealer0** [tachiyomiorg/tachiyomi-extensions#10977]
### Source information

Hentai Manga 1.2.16

### Steps to reproduce

1. Opened Extension

### Expected behavior

1. Open Extension, Extension works fine.

### Actual behavior

1. Open Extension.
2. Error stating no results found.
![Screenshot_20220301-035000-400](https://user-images.githubusercontent.com/100694749/156173343-e6816512-6091-4e23-bc15-416b503dceab.png)
3. Opened WebView version
4. WebView works fine.
![Screenshot_20220301-035308-577](https://user-images.githubusercontent.com/100694749/156173501-1110932c-f159-4b39-a5a3-049b1e4b3f01.png)

### Tachiyomi version

Stable 0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing in favour of #10983.
