### ISSUE TITLE
Fleur Blenche: Extension can be removed

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#10970]
### Source information

Fleur Blenche 1.2.17

### Steps to reproduce

Just a warning that the site is not coming back, so they can delete the extension.

### Expected behavior

None, it's gone.

### Actual behavior

Offline 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

They hosted a site that has since been removed from here, so there's no point in expecting to switch domains anytime soon. Hope I got the label right this time...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Fleur Blenche: Extension can be removed"
