### ISSUE TITLE
Super Ecchi

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#10976]
### Source name

Super Ecchi

### Source link

https://superecchi.com

### Language

Português (Brasil)

### Other details

Site 18+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Site seems broken and search do not work. Please do check if the website is working fine and it's nor broken before requesting new sources.

In this case, pretty sure you can find this kind of content in a lot of other extensions already available.

**Comment by Militinix** [comment]
> Site seems broken and search does not work. Please do check if the website is working fine and it's not broken before requesting new sources.
> 
> In this case, pretty sure you can find this kind of content in a lot of other extensions already available.

In this case the search seems broken even, I will then try to talk to the owner of the site to see what he can do.
And in the absence of Hitomi this seems to be a good option.

**Comment by alessandrojean** [comment]
> And in the absence of Hitomi this seems to be a good option.

There are a lot of tons of extensions with this kind of content, explore more the app.
