### ISSUE TITLE
Manhwatop previous ext queue Dissapear

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#10986]
### Source information

Manhwatop 1.2.17

### Steps to reproduce

1. Already have some queue before updating ext
2. Updating extension
3. Library update
4. New chapter on queue, but on queue there are 2 manhwatop
5. After library update finish, i noticed that the old queue is dissapear.  Only new update after new extension is on queue
6. I add the old chapter to queue. 
7. After library update, it dissapear again

### Expected behavior

There sould be only 1 manhwatop on queue and no chapter should dissapear

### Actual behavior

Chapter on queue from previous version dissapear from queue

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Not sure how that would be fixed by the extension side, sounds like an app bug instead.
