### ISSUE TITLE
Manytoon.me 

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#10988]
### Source information

Manytoon.me 1.2.19

### Steps to reproduce

The page screen is blank no manhwa are showing but is working fine on webview

### Expected behavior

The manhwa titles should appear

### Actual behavior

Blank screen 

### Tachiyomi version

Stable 0.13.1

### Android version

11

### Other details

Note: this issue came after the new update of extensions   that came yesterday

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing in favour of #10983.
