### ISSUE TITLE
Madara: Missing titles in Popular and Latest

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi-extensions#10983]
The last update to the base Madara class changed the Popular and Latest selector to filter non-image content (novels in pure text format and videos, that the app does not support). This caused an issue in some particular sources where the "No results found" error is being thrown or some image-only type titles are missing from Popular and Latest.

This problem is caused when the source:
- Customizes their Madara theme code;
- Uses an outdated Madara version;
- Incorrectly flags image-only titles as video or text.

Ideally, it's up to the site owners to fix this (if it's the point 2 and 3 of the list below), since the extension is just filtering the non-image items based on the data provided by the website. Until that doesn't happen, the extensions can have their selectors rollback to the old one individually, please **_comment on this issue_** about the source you're having issues if it's the case.

Alternatively, you can still search for the titles, since the non-image type filter isn't applied to the search.

**Comment by Yros** [comment]
Currently reported sources having an issue:
- Hentai Manga
- HentaiWebtoon
- MangaGreat
- Manhua ES
- Manhua Plus
- ManhuaUS
- Manhwa68
- ManhwaTop

**Comment by alessandrojean** [comment]
> Currently reported sources having an issue:

These are addressed by PR #10981 at the moment. Thanks for reporting.

**Comment by fawadkhan121** [comment]
Manytoon.me is having the same issue as well

**Comment by alessandrojean** [comment]
> Manytoon.me is having the same issue as well

Addressed in the PR 👍🏻

**Comment by curche** [comment]
Also affected is *Shield Manga* extension
As reported here: 
 https://discord.com/channels/349436576037732353/349436576037732355/950045208563843072

Also note that the source has cloudflare and has a new domain (altho redirect worked fine for me); from #support: 
> https://shieldmanga.club redirects to https://shieldmanga.io
