### ISSUE TITLE
MangaSwato: No black background categories for Chapter

### ISSUE THREAD

**Issue by hani19998** [tachiyomiorg/tachiyomi-extensions#10996]
### Source information

MangaSwat 1.2.18

### Steps to reproduce

Open extension MangaSwat
1- Open chapters

### Expected behavior

Chapters must open or withstand Chapters 

### Actual behavior

Black background (chapter)
 does not download (chapter)

Note that when you enter the site, the chapter opens

### Tachiyomi version

0.13.1

### Android version

Android 10

### Other details

![Screenshot_20220302-211114](https://user-images.githubusercontent.com/100415641/156423843-29d1e9c0-29f9-456a-8d48-b252e4f6b10f.png)
![Screenshot_20220302-211105](https://user-images.githubusercontent.com/100415641/156423923-d5396c61-8fd9-4212-9836-fe9597fd5a51.png)
![Screenshot_20220302-211046](https://user-images.githubusercontent.com/100415641/156423934-f11b63ed-2a1d-47d6-88b1-f3f015b466eb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zeredouni** [comment]
(  Clear chapter cache and database and cookies and will work fine  )
