### ISSUE TITLE
漫画猫

### ISSUE THREAD

**Issue by isPoto** [tachiyomiorg/tachiyomi-extensions#11005]
### Source name

漫画猫

### Source link

https://www.maofly.com

### Language

Chinese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by din1028** [comment]
有人接手吗？这也是个不错的网站

**Comment by anenasa** [comment]
I will work on this.
我接手
