### ISSUE TITLE
Manhua Plus latest not showing 

### ISSUE THREAD

**Issue by JudiciousVick** [tachiyomiorg/tachiyomi-extensions#11001]
### Source information

Manhua plus 1.2.21

### Steps to reproduce

Browse
open in latest

### Expected behavior

Should show latest updates

### Actual behavior

Does not show latest but shows few titles and this only started after new extension update.

### Tachiyomi version

0.13.1-4174

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.
![Screenshot_20220303-124001](https://user-images.githubusercontent.com/59502042/156515182-b6f6edb1-23f6-4e2c-9f5e-5572729f8357.jpg)

**Comment by conztanz045** [comment]
#10983
