### ISSUE TITLE
Nocturnal Scans

### ISSUE THREAD

**Issue by Canine-a11y** [tachiyomiorg/tachiyomi-extensions#11004]
### Source name

Nocturnal Scans

### Source link

https://nocturnalscans.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Correct URL is https://nocturnalscans.com. Uses Madara.

**Comment by elhertz** [comment]
First time I couldn't find a source in tachiyomi.
Any ETA? Just curious. Thanks!

**Comment by alessandrojean** [comment]
> Any ETA? Just curious. Thanks!

There's no ETA for any requested source to be added. It gets added when any contributor wants to work on it.
