### ISSUE TITLE
The domain for mangasusu extension has change

### ISSUE THREAD

**Issue by Lutrick23** [tachiyomiorg/tachiyomi-extensions#11019]
### Source information

Mangasusu 1.2.13

### Steps to reproduce

Can't open the extension/eror when open because the link has change the domain

### Expected behavior

This should change the domain for the extension from mangasusu.co.in to mangasusu.cc or https://194.233.87.209/

### Actual behavior

Thiss happened because the domain change from mangasusu.co.in to mangasusu.cc or https://194.233.87.209/ should change the domain 

### Tachiyomi version

App version: 0.13.1-4174 (standard, 29c5c0af5, 75, 2022-02-26T21:08Z) Android version: 10 (SDK 29) Android build ID: Android-Q-build-20210816180653 Device brand: POCO Device manufacturer: Xiaomi Device name: citrus Device model: M2010J19CG Device product name: citrus_id

### Android version

Android 11

### Other details

Please i can't open the extension because the link of extansion has change the domain from mangasusu.co.in to mangasusu.cc or https://194.233.87.209/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Lutrick23** [comment]
> ### Source information
> Mangasusu 1.2.13
> 
> ### Steps to reproduce
> Can't open the extension/eror when open because the link has change the domain
> 
> ### Expected behavior
> This should change the domain for the extension from mangasusu.co.in to mangasusu.cc or https://194.233.87.209/
> 
> ### Actual behavior
> Thiss happened because the domain change from mangasusu.co.in to mangasusu.cc or https://194.233.87.209/ should change the domain
> 
> ### Tachiyomi version
> App version: 0.13.1-4174 (standard, 29c5c0af5, 75, 2022-02-26T21:08Z) Android version: 10 (SDK 29) Android build ID: Android-Q-build-20210816180653 Device brand: POCO Device manufacturer: Xiaomi Device name: citrus Device model: M2010J19CG Device product name: citrus_id
> 
> ### Android version
> Android 11
> 
> ### Other details
> Please i can't open the extension because the link of extansion has change the domain from mangasusu.co.in to mangasusu.cc or https://194.233.87.209/
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

**Comment by harphobia** [comment]
alternative URL https://mangasusu.cc

**Comment by Lutrick23** [comment]
> alternative URL https://mangasusu.cc

Yes how to change the domain extension in apk?

**Comment by ZekkenID** [comment]
Padahal tinggal matiin DOH(Dns over Http) aja dah beres

**Comment by alpqm** [comment]
ni mangasusu nggak bisa di baca chapter nya

**Comment by alpqm** [comment]
> Padahal tinggal matiin DOH(Dns over Http) aja dah beres

Cara sekarang gimana bro nggak bisa baca

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
