### ISSUE TITLE
Nhentai.to

### ISSUE THREAD

**Issue by shiroon123** [tachiyomiorg/tachiyomi-extensions#11029]
### Source name

Nhentai.to

### Source link

Nhentai.to

### Language

All

### Other details

This is a subdomain from nhentai

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
This looks like a shady nhentai clone to me. :thinking:

**Comment by Thund047** [comment]
Some of my favorites that got deleted from the original site and this is the one that have those, not only that you can also find them with the original codes.
