### ISSUE TITLE
xCaliBR Scans only showing half pages

### ISSUE THREAD

**Issue by Oridjinn1980** [tachiyomiorg/tachiyomi-extensions#11030]
### Source information

xCaliBR Scans 1.2.16

### Steps to reproduce

1. Open xCaliBR Scans
2. Open a newer release in webtoon style (Above Ten Thousand People, Immortal Emperor Luo Wuji)
3. Only one half of the strip will be shown, with the other half being on the next page.

### Expected behavior

The two pages should be merged into one
(Like in web view, which works fine)

### Actual behavior

You have 1 page split into 2 pages

### Tachiyomi version

0.13.1-4184

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicate #10528
