### ISSUE TITLE
Lazy mode

### ISSUE THREAD

**Issue by medfadil1** [tachiyomiorg/tachiyomi-extensions#11032]
### Describe your suggested feature

I recently found a reddit client that has an amazing feature called lazy mode
![Screenshot_20220306-210750_Infinity](https://user-images.githubusercontent.com/66218907/156940538-4401123d-7c9d-4b9e-93a6-bc95af1f0b26.png)
it's a nice auto scroll function.
this has some medical function too, for example repeating the same movement might lead to carpal tunnel syndrome.

### Other details

auto scroll 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong repo, already suggested.
