### ISSUE TITLE
IMHentai For input String :"" error

### ISSUE THREAD

**Issue by deeplyarnab** [tachiyomiorg/tachiyomi-extensions#11039]
### Source information

The same bug as #7992

### Steps to reproduce

The same as #7992

- Try to open/download the title
- Gives error `For input String :""`

### Expected behavior

Title should open or download

### Actual behavior

Gives error `For input String :""`

### Tachiyomi version

Preview r4183

### Android version

Android 11

### Other details

This wasn't present until before the last update of extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Seems to have fixed itself, as reported in Discord

Try refreshing the chapter, or go through Troubleshooting & Diagnosis steps on the website.
