### ISSUE TITLE
Remove manga1000/manga1001

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi-extensions#11047]
### Source information

MangaRaw1.2.4

### Steps to reproduce

open manga1000/manga1001

### Expected behavior

load manga list

### Actual behavior

manga1000 404
manga1001 time out

### Tachiyomi version

0.13.1

### Android version

Android 11 MIUI12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ringosham** [comment]
Both sites have been DMCA'd by Kodansha and will not be coming back.

**Comment by arkon** [comment]
We should probably remove the extensions.

**Comment by ringosham** [comment]
On a second note, comick.top seems to be the new domain of MangaRaw

We should migrate instead
