### ISSUE TITLE
Zinmanga,manhuaplus,manhuaus are broken

### ISSUE THREAD

**Issue by Estiak69** [tachiyomiorg/tachiyomi-extensions#11048]
### Source information

"Zinmanga 1.2.16" "ManhuaUs 1.2.20" "Manhua Plus 1.2.21

### Steps to reproduce

Many Manhua,Manhwa are not showing in recent page

### Expected behavior

Should show them all

### Actual behavior

Missing manhwa in app

### Tachiyomi version

0.13.1-4148

### Android version

Android 10

### Other details

![Screenshot_2022-03-08-22-36-35-613_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/88083213/157284614-fee7f50f-bc99-478e-ac1e-1f43edff733f.jpg)
![Uploading Screenshot_2022-03-08-22-36-24-003_eu.kanade.tachiyomi.debug.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
First, one source per ticket.

Second, closing in favour of #10983.
