### ISSUE TITLE
MyHentaiComics 404

### ISSUE THREAD

**Issue by DatHypnoboi** [tachiyomiorg/tachiyomi-extensions#11044]
### Source information

MyHentaiComics 1.2.2

### Steps to reproduce

1. Open the extension

### Expected behavior

The extension should show the site's contents

### Actual behavior

The extension shows a 404 error despite the site still being up

### Tachiyomi version

TachiyomiSY 1.7.0 and Preview r441

### Android version

Android 12

### Other details

Asking for a friend

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SolarAquarion** [comment]
MyHentaiComics I guess changed the place where they post the comics, or is it something else that is causing it to fail?

**Comment by PrivatePP** [comment]
Are there any news on this? It's been giving me error 404 for a long time

**Comment by DatHypnoboi** [comment]
Nope, just swap over to MyHentaiGallery, it's mostly better, with only minor downsides

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
