### ISSUE TITLE
[picacomic] Manga chapters over 40 pages cannot be downloaded in full

### ISSUE THREAD

**Issue by Gokou-Ruri** [tachiyomiorg/tachiyomi-extensions#11042]
### Source information

Picacomic 1.2.1

### Steps to reproduce

https://picaapi.picacomic.com/comics/61d546dec2f2764728fcb4ab
For example, the first chapter over 40 pages cannot be downloaded, but can be read online.

### Expected behavior

Content over 40 pages should be downloaded normally, e.g. page 41, page 42.

### Actual behavior

the first chapter over 40 pages cannot be downloaded, but can be read online. Only picacomic cartoons can do so, So I guess this should not be a problem with the main program. 

### Tachiyomi version

Stable 0.13.1 (2022/2/2 01:35)

### Android version

Android 11

### Other details

![Screenshot_20220308-115124_Tachiyomi](https://user-images.githubusercontent.com/26711804/157176160-3d680930-241b-4e25-b083-1f708ff5c637.png)

![249755](https://user-images.githubusercontent.com/26711804/157188426-721d4fe2-2749-4297-a78f-a14b82f4296a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lazureice** [comment]
duplicated with #10142 
重复了。原作者没有回复。
