### ISSUE TITLE
Removal Of SetsuScans Source

### ISSUE THREAD

**Issue by SatyamSSJ10** [tachiyomiorg/tachiyomi-extensions#11040]
### Source link

https://setsuscans.com

### Other details

I want to remove my website because I believe that most people are using tachiyomi to access my website. and the website views have considerably dropped

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by alessandrojean** [comment]
Just to inform that Madara sources send the same view count request that is done on browser.

**Comment by SatyamSSJ10** [comment]
actually the google analytics views, we want this because of the bilibili sponsorship

**Comment by FourTOne5** [comment]
> * [x]  Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)

Chapter 1- 3 of https://setsuscans.com/manga/nobukuni-san-does-she-likes-me says otherwise

**Comment by SatyamSSJ10** [comment]
Their website went off and I also asked permissions later so its legit

**Comment by SatyamSSJ10** [comment]
> > * [x]   Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
> 
> Chapter 1- 3 of https://setsuscans.com/manga/nobukuni-san-does-she-likes-me says otherwise

Their website went off and I also asked for permissions later so it's legit. We didn't stole that.
