### ISSUE TITLE
Mangadex extension not updating some series

### ISSUE THREAD

**Issue by Uncle-Squishy** [tachiyomiorg/tachiyomi-extensions#11061]
### Source information

MangaDex 1.2.157

### Steps to reproduce

Follow various manga
Try to update list

### Expected behavior

All series with updates should be updated

### Actual behavior

Some series do not update and haven't for a few months now. 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

I'm not sure how many series are affected, but I discovered this with Dosanko Gyaru. The series is at chapter 71 but the MangaDex extension anly has up to chapter 50 or so. It's current on the MangaDex website. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
For the example you gave, external sites aren't shown in the mangadex ext as they lead to another site. Use their respective ext to read them. In Dosanko Gyaru case, MangaPlus. As for your other series, since you gave no other example. I'm going to assume its of similar nature. If thats not the case, you can go on discord and get more help.

**Comment by Uncle-Squishy** [comment]
Ah,ales sense. I didn't catch that because I switched to a different source
since that was faster.
