### ISSUE TITLE
Failed to bypass cloudflare on toonily

### ISSUE THREAD

**Issue by epiccoub** [tachiyomiorg/tachiyomi-extensions#11067]
### Source information

Toonily 1.2.22

### Steps to reproduce

1. Im in Indonesia so i cant open toonily without cloud dns cloud flare
2. Can you fix it? 

### Expected behavior

When i open it, Its say on the screen "Failed to bypass cloudflare" 

### Actual behavior

Working porperly

### Tachiyomi version

0.13. 1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://tachiyomi.org/help/guides/troubleshooting/
