### ISSUE TITLE
Komga: Manually downloaded jxl files are renamed to jpg

### ISSUE THREAD

**Issue by TheHardew** [tachiyomiorg/tachiyomi-extensions#11072]
### Source information

Komga 1.2.39

### Steps to reproduce

1. Set up a komga server with jxl files inside cbz
2. Open the komga server in tachiyomi
3. Open some comic/manga
4. Scroll a few pages 
5. Exit back to chapter view
6. Download the whole chapter

### Expected behavior

The files tachiyomi downloaded should have the same name as in the cbz file.

### Actual behavior

The files tachiyomi downloaded (e.g. in `/sdcard/Tachiyomi/downloads/Komga (ALL)/[COMIC]/[CHAPTER]/`) have jxl extension if they were downloaded by scrolling and jpg extension if they were downloaded manually. The files are still jxl codestream files though.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Not sure if this is actually an extension problem, but without other sources serving jxl files I'm not sure how to test that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you mean when you save individual pages from the reader?

**Comment by TheHardew** [comment]
No, when I download the whole chapter either using the button next to the chapter selection or on the top when a combo box appears with options like "Unread", "All""...

**Comment by TheHardew** [comment]
It turns out, that the pages that did not have their extension changed from jxl to jpg are impossible to read and the total page count for the chapter is reduced. Before I thought this bug was relatively benign.

So just to make it clear:
1. Have a chapter with ~100 pages in komga with jxl files
2. Open it in tachiyomi, read ~5 pages
3. Download the whole chapter
4. This chapter now has only ~90 pages.

A workaround is to rename all the files from `*.jxl` to `*.jpg` (even though they are still jpeg xl files) or to delete the chapter and redownload it without reading any pages first.

**Comment by alessandrojean** [comment]
/edit-title "Komga: Manually downloaded jxl files are renamed to jpg"

**Comment by Seishirou101** [comment]
can you provide a sample cbz that can be used to test?

**Comment by TheHardew** [comment]
https://files.catbox.moe/ip3isl.cbz
Still happens on Tachiyomi 0.13.4, Komga extension 1.2.39, Komga "1.153.2".
I actually patched Komga before 1.154.0 released to generate larger thumbnails so it's not the latest one and it's not the 1.153.2 release, I do have the jpeg xl support via NightMonkeys though.

So just to be clear:
- open the komga extension from Tachiyomi
- open the cbz, scroll a few pages
- exit the comic viewer
-  download the cbz
- go into the download location

The first few pages will have `.jxl` extension. The rest will have `.jpg`. Tachiyomi will ignore the files with the proper extension, the number of pages one can read is reduced. The solution is to rename the `.jxl` files to `.jpg` or to delete the downloaded chapter and redownload it without opening it first.

**Comment by TheHardew** [comment]
The most pressing issue I think is that the files can not be read, so I think tachiyomi should open `.jxl` files if they are present.
The fact that it changes the extension is not ideal but a relatively minor issue.

**Comment by TheHardew** [comment]
https://files.catbox.moe/jgn56z.cbz

It's a cbz of 100 images of "rose" from imagemagick.
I realised my previous link might have infringed on an IP so I removed my last post so that the link would not be visible in the edit history and I post this link instead.

Still happens on Tachiyomi 0.13.4, Komga extension 1.2.39, Komga "1.153.2".
I actually patched Komga before 1.154.0 released to generate larger thumbnails so it's not the latest one and it's not the 1.153.2 release, I do have the jpeg xl support via NightMonkeys though.

So just to be clear:

open the komga extension from Tachiyomi
open the cbz, scroll a few pages
exit the comic viewer
download the cbz
go into the download location
The first few pages will have .jxl extension. The rest will have .jpg. Tachiyomi will ignore the files with the proper extension, the number of pages one can read is reduced. The solution is to rename the .jxl files to .jpg or to delete the downloaded chapter and redownload it without opening it first.](https://files.catbox.moe/ip3isl.cbz
Still happens on Tachiyomi 0.13.4, Komga extension 1.2.39, Komga "1.153.2".
I actually patched Komga before 1.154.0 released to generate larger thumbnails so it's not the latest one and it's not the 1.153.2 release, I do have the jpeg xl support via NightMonkeys though.

So just to be clear:

open the komga extension from Tachiyomi
open the cbz, scroll a few pages
exit the comic viewer
download the cbz
go into the download location
The first few pages will have .jxl extension. The rest will have .jpg. Tachiyomi will ignore the files with the proper extension, the number of pages one can read is reduced. The solution is to rename the .jxl files to .jpg or to delete the downloaded chapter and redownload it without opening it first.)

**Comment by Seishirou101** [comment]
When downloading, the app uses this [function](https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L463-L478) to try and find the extension for the file, so its failing to figure out its a jxl file and defaulting to jpg. However if you read some of the pages, it'll copy the images from the cache which seems to download it a different [way.](https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/data/cache/ChapterCache.kt#L157-L175) The pagelist for downloaded chapters is built using this [function](https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt#L36-L43) as one of the tests and its failing to identify jxl as an image format so its returning false therefore excluding it from the pagelist. As far as I'm aware, the online source does not use this to determine the page list. This is more of an app issue so I'm going to close this and open an issue there while referring to this issue.
