### ISSUE TITLE
EGY Manga doesn't open

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#11083]
### Source information

EGY Manga 1.2.16

### Steps to reproduce

1. Open the extension
2. it should open
3. It says " No Results Found "

### Expected behavior

It should open
![2](https://user-images.githubusercontent.com/93197738/157870940-249ec3dc-b624-46b8-a40c-76f71c8b97b6.jpg)

### Actual behavior

this happen instead
![1](https://user-images.githubusercontent.com/93197738/157870857-7a186786-c5bb-425c-a459-ef470e4d4129.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing in favour of #10983.
