### ISSUE TITLE
manga-1001.com

### ISSUE THREAD

**Issue by aruto77** [tachiyomiorg/tachiyomi-extensions#11080]
### Source name

Manga1001

### Source link

https://manga-1001.com/

### Language

Japanese

### Other details

alternative for Mangaraw because that site has already taken down by DMCA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
already a PR for this that is getting merged soon

**Comment by Riztard** [comment]
> already a PR for this that is getting merged soon

if you mean this #11058, its not

**Comment by ringosham** [comment]
This uses Madara. Put it in there instead of the current MangaRaw factory.
