### ISSUE TITLE
Gemanga doesn't open

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#11082]
### Source information

Gemanga 1.2.17

### Steps to reproduce

1. Opening extensions
2. it should open 
3. It says No results found

### Expected behavior

It should open
![2](https://user-images.githubusercontent.com/93197738/157869128-98be8d7f-bc49-48a3-b929-83d23ef727f4.jpg)

### Actual behavior

This happen instead
![1](https://user-images.githubusercontent.com/93197738/157869373-7c50580c-4623-497c-8564-213b5f9ee4b4.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing in favour of #10983.
