### ISSUE TITLE
Magus Manga: No results found

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#11081]
### Source information

Magus Manga 1.2.12

### Steps to reproduce

1. Open the extension
2. it should open 
3. It says " No Results Found "

### Expected behavior

it should open
![2](https://user-images.githubusercontent.com/93197738/157867664-a46a3a51-b7f5-439f-a935-0140f39839ce.jpg)

### Actual behavior

this happen instead 
![1](https://user-images.githubusercontent.com/93197738/157866388-ae9c3a86-71c1-4eff-88cd-586fff939c23.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
