### ISSUE TITLE
Asurascans extension can't download all the chapters 1st page

### ISSUE THREAD

**Issue by Sterbenm** [tachiyomiorg/tachiyomi-extensions#11107]
### Source information

AsuraScans 1.2.25

### Steps to reproduce

When i orwss the doenload button it waita for a while and then download the other pages except 1st page. Always 7/8 or 12/13 pages were downloaded and it shows error on manga's page.

### Expected behavior

Download all pages/images.

### Actual behavior

One page always missing and it gives error.

### Tachiyomi version

0.13.1

### Android version

Android 10

### Other details

I tried
![Screenshot_2022-03-15-01-20-36-333_eu kanade tachiyomi](https://user-images.githubusercontent.com/88272924/158270507-90b653cd-8a6d-4d1e-bb44-02061503f93c.jpg)
![Screenshot_2022-03-15-01-20-24-039_eu kanade tachiyomi](https://user-images.githubusercontent.com/88272924/158270517-a3385662-dd2a-4bd9-9d7f-8cead562f34b.jpg)
 to download turkish ones. I didnt try to download english ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sterbenm** [comment]
İ relize that asura have a image that redirectw to another manhwa. İ think extension tries to download that image and fail then download the whole chapter.
![Screenshot_2022-03-15-01-51-25-576_eu kanade tachiyomi az](https://user-images.githubusercontent.com/88272924/158273666-eb429e63-2e9b-4a65-8365-a9ee554b5028.jpg)

**Comment by kyoyacchi** [comment]
@Sterbenm Tek bir bölüm için diyorsan, hani şu "Yeniden Dene" diyen sürekli. Onu indirmene gerek yok zaten, orada eskiden o "chapter"in AsuraScans'dan "ç"alıntı olduğu yazıyordu ingilizce olarak. Pek hatırlamıyorum ne yazdığını sadece bu kalmış aklımda. Hala düzeltmediler ha bu arada onu :d

**Comment by Sterbenm** [comment]
@kyoyacchi tachiyomiden indirdikten sonra uygulamayı kapatıp file managerdan bölüme gidip sonundaki tmp yi siliyorum. sonra uygulamayı açıp indirmeleri ipral ediyorum. 1 sayfa eksik olsa da bölümü açıyor ve indirmiş olarak görüyor uygulama. biraz uğraştırıcı ki toplu bölüm olduğunda yorar.
