### ISSUE TITLE
YugenMangas: Failed to bypass cloudflare

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#11103]
### Source information

YugenMangas 1.2.17

### Steps to reproduce

1- Sources menu
2- Tap the YugenMangas font name to enter
3- See the Mangas

### Expected behavior

View the mangas from the source

### Actual behavior

When I go to the source, it shows failure to bypass cloudflare
![Screenshot_20220314-153139_Tachiyomi](https://user-images.githubusercontent.com/82852543/158239786-b97d1b43-c388-4099-a066-bc9ada354871.png)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

But when I go to webview, it enters normal
![Screenshot_20220314-153134_Tachiyomi](https://user-images.githubusercontent.com/82852543/158239831-6d2518af-63b6-4536-be00-55b5e0dee08a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They have a higher Cloudflare protection and the owner also threatened us some time ago, he didn't want the extension.

If [this section](https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues) in the Troubleshooting guide didn't help, nothing much we can do besides recommending migrating to other sources.

**Comment by Kaylenna** [comment]
Ok ^^ thanks anyway
