### ISSUE TITLE
Mangaworld must be updated

### ISSUE THREAD

**Issue by ed0fl3da** [tachiyomiorg/tachiyomi-extensions#11124]
### Source information

Mangaworld

### Steps to reproduce

Enter mangaworld 
Search manga One Piece
Open it

### Expected behavior

You can read latest chapters

### Actual behavior

There aren't the latest chapters

### Tachiyomi version

Latest

### Android version

Latest

### Other details

In the website of mangaworld there are the latest chapters but in the extension no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Works fine on my end.
Probably https://github.com/tachiyomiorg/tachiyomi/issues/6599
