### ISSUE TITLE
Manga-raw .com not loading

### ISSUE THREAD

**Issue by Dake647392** [tachiyomiorg/tachiyomi-extensions#11133]
### Source information

Manga-raw.com

### Steps to reproduce

Manga-raw extension is loading

### Expected behavior

Error in loading

### Actual behavior

Error in loading it's saying please wait

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

Please fix this shit

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There is no extension for a manga-raw.com

**Comment by Dake647392** [comment]
Sorry it was manga-raw.club
