### ISSUE TITLE
原本的comico已經停止服務了，希望能上架新的來源pocket comics，謝謝

### ISSUE THREAD

**Issue by j231004** [tachiyomiorg/tachiyomi-extensions#11140]
### Source name

pocket comics

### Source link

https://www.pocketcomics.com/

### Language

英語，中文

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Already exists. (#10210)

**Comment by jopejoe1** [comment]
Should probably be made into a multisrc as they are going under diffrent names

**Comment by j231004** [comment]
> Comico.

Thank you so much!!
