### ISSUE TITLE
ReadComicOnline "No results found"?

### ISSUE THREAD

**Issue by crispiny** [tachiyomiorg/tachiyomi-extensions#11141]
### Source information

ReadComicOnline 1.2.10

### Steps to reproduce

1. Open up the tachiyomi app
2. Click on ReadComicOnline extension
3. No homepage appears only "No results found"

### Expected behavior

I should see the comic covers upon clicking the extension and be able to search titles.

### Actual behavior

Nothing appeared and "No Results Found" was the only thing there. I tried to retry and restart my app to no avail. I also tried searching for titles in the search bar but "No Results Found" also appeared. 

### Tachiyomi version

0.13.1

### Android version

11 RKQ1.200826.002

### Other details

When opened in WebView, the site seems to be working. As well as if you click on the titles from the history, it loads properly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by garofalocine** [comment]
I hope it will be solved soon

**Comment by bicycleghost** [comment]
I have the same issue on Android 12. Also, if I select an issue from the history, it loads fine. It's just the browsing that doesn't work.

**Comment by Pinkarmor01** [comment]
I am having this exact same issue. I've tried all troubleshooting and even troubleshooted my device itself.

**Comment by vehosah** [comment]
Me too

**Comment by Natillax** [comment]
It also happens to me.

**Comment by Fai1edMit0sis** [comment]
The happened after updating to v1.4.4

**Comment by Natillax** [comment]
I hope they repair the extension soon. It's a very good webpage and extension to read comics...

**Comment by Blipbliptoryah** [comment]
> ### Source information
> ReadComicOnline 1.2.10
> 
> ### Steps to reproduce
> 1. Open up the tachiyomi app
> 2. Click on ReadComicOnline extension
> 3. No homepage appears only "No results found"
> 
> ### Expected behavior
> I should see the comic covers upon clicking the extension and be able to search titles.
> 
> ### Actual behavior
> Nothing appeared and "No Results Found" was the only thing there. I tried to retry and restart my app to no avail. I also tried searching for titles in the search bar but "No Results Found" also appeared.
> 
> ### Tachiyomi version
> 0.13.1
> 
> ### Android version
> 11 RKQ1.200826.002
> 
> ### Other details
> When opened in WebView, the site seems to be working. As well as if you click on the titles from the history, it loads properly.
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

I'm presenting the same issue, I tried on different networks with no luck, also I tried the troubleshooting.

The weird thing is that I can still read my bookmarked chapters fortunately, hope y'all could fix this source please, it makes this app really really robust.

**Comment by tiago-msg** [comment]
Same issue on my end.
Interestingly, comics that were already in my library can download and be read online as if there was no issue.
I just can't add more comics or search them up in the source. Weird.
