### ISSUE TITLE
Lector Manga: Chapter images do not load

### ISSUE THREAD

**Issue by Yeraqlx** [tachiyomiorg/tachiyomi-extensions#11154]
### Source information

Lectormanga 1.2.21

### Steps to reproduce

1. Entrar a cualquier historia que sea de Tumangaonline ó Lectormanga

2. Al ir cargando el capítulo solo hasta la imagen número 10 carga 

3. Para q cargue lo demás, debes salir de app y esperar unos minutos siendo bastante estresante 

### Expected behavior

Debería seguir cargando fluidamente como las anteriores imágenes sin problema

### Actual behavior

No carga de la imagen 10 hacia adelante, a menos que  salgas de la app a otra y esperar para que cargué todo unos minutos
![Screenshot_2022-03-17-03-13-49-063_eu kanade tachiyomi](https://user-images.githubusercontent.com/89624481/158750604-8fd38619-c235-45db-ac9c-8fdd1fe56975.jpg)
![Screenshot_2022-03-17-03-15-31-126_eu kanade tachiyomi](https://user-images.githubusercontent.com/89624481/158750606-4a90f27f-43e5-4f39-a561-f19aabcd2c4a.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Esto ya de había arreglado antes, pero después de una actualización de la extensión volvió este problema

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Natillax** [comment]
Me too

**Comment by alessandrojean** [comment]
/edit-title "Lector Manga: Chapter images do not load"

**Comment by seew3l** [comment]
Esto ocurre debido al ratelimit de las imágenes, puedes cambiar ese valor en los ajustes de la extensión.
