### ISSUE TITLE
CoCoManhua (OhManhua) doesn't show comic cover

### ISSUE THREAD

**Issue by Kinglsw** [tachiyomiorg/tachiyomi-extensions#11157]
### Source information

CoCoManhua (OhManhua) 1.2.10

### Steps to reproduce

1. Install CoCoManhua (OhManhua) extension
2. Open CoCoManhua (OhManhua)

### Expected behavior

Should show the comic cover.

### Actual behavior

The comic cover does not load, it always appears as a blank image

### Tachiyomi version

r4197

### Android version

Android 12

### Other details

![Screenshot_2022-03-17-16-12-40-712_eu kanade tach](https://user-images.githubusercontent.com/88313628/158765524-be69a7fb-43c4-4e92-8397-6944d2ac1105.jpg)
![Screenshot_2022-03-17-16-12-45-568_eu kanade tach](https://user-images.githubusercontent.com/88313628/158765533-b8251120-fd88-4491-bfd0-69ed61a44768.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kinglsw** [comment]
After my testing, I found that Preview r4197 and r4184 cannot load CoCoManhua manga covers. Earlier versions can load the manga cover normally (e.g. r4174,r4170)

**Comment by Kinglsw** [comment]
[r4174 tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/8296700/r4174.tachiyomi_crash_logs.txt)
[r4184 tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/8296701/r4184.tachiyomi_crash_logs.txt)
[r4197 tachiyomi_crash_logs(7).txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/8296702/r4197.tachiyomi_crash_logs.7.txt)
logs

**Comment by DchanN** [comment]
I'm have the same problem too have 2 extension can't load cover which CoCoManhua (ZH) and Kisslove (JA) both extension latest version, it's still fine before 2 latest update in Preview, can confirm the problem not in extension , because after try clear cookies and database in preview and still not work, I'm trying install latest stable version, of course with the same library (use backup from preview) and same setting include DoH, I'm have the video too for more easy watch the problem 

video :https://drive.google.com/file/d/1qffcNtsC0-RtbCi2ChHdcr_ELfD6yPvC/view

**Comment by zhongfly** [comment]
> After my testing, I found that Preview r4197 and r4184 cannot load CoCoManhua manga covers. Earlier versions can load the manga cover normally (e.g. r4174,r4170)

You should report this bug in https://github.com/tachiyomiorg/tachiyomi.
