### ISSUE TITLE
MangaHub shows timed out

### ISSUE THREAD

**Issue by hellbreakes** [tachiyomiorg/tachiyomi-extensions#11153]
### Source information

"MangaHub 1.2.12"

### Steps to reproduce

1.open the chapter
2.refresh it
3.Is shows refreshing circle for Minutes
4.timeout error

This error sometime appear and resolve itself but a day later it appears again

### Expected behavior

It should have refreshed chapter

### Actual behavior

It shows timed out 

### Tachiyomi version

"0.13.1"

### Android version

"android 11"

### Other details

It happens again and again..i checked this site on my firefox and it is not down but it is not working in tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
They were going down intermittently
