### ISSUE TITLE
Dmzj need a function of viewing the list

### ISSUE THREAD

**Issue by 1024kilobytes** [tachiyomiorg/tachiyomi-extensions#11162]
### Describe your suggested feature

Dmzj's app is full of ads, but Dmzj extension lack of the function of list, such as day ranking, week rangking etc. ,it can't replace the app completely

### Other details

![Screenshot_20220318-021845](https://user-images.githubusercontent.com/62324359/158869655-11c9cff2-2db6-4c71-a4f9-c40f645eb8fb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
same reason with https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11161#issuecomment-1072173082

**Comment by FourTOne5** [comment]
> same reason with [#11161 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11161#issuecomment-1072173082)

As i already said in the other issue It's very much doable you can check the Bato.to extension for example which has similar rankings.
