### ISSUE TITLE
copymanga need a function of viewing the list

### ISSUE THREAD

**Issue by 1024kilobytes** [tachiyomiorg/tachiyomi-extensions#11161]
### Describe your suggested feature

The fastest rise, nearly seven days, nearly thirty days and total rankings, if we can view these lists in the extension, it can completely replace copymanga's app
![Screenshot_20220318-020627](https://user-images.githubusercontent.com/62324359/158867977-02b4fbdf-6a02-4ac6-8462-506746bda35b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
It is impractical to share the same display area with the existing popularManga, which means that tachiyomi software is required to add an additional display area.
This is my personal opinion

**Comment by zhongfly** [comment]
> It is impractical to this ranking function share the same display area with the existing popularManga

1. The interface of the ranking function is different from popularManga,
2. Due to 1, the options of the ranking function cannot be mixed with popularManga, which is the key reason. For example, you have selected the existing popularManga love category, and selected the "fastest rising" in the ranking function, which interface do we obtain such manga from? The interface of the ranking function can only return the "fastest rising", it can't filter out the love category.

**Comment by FourTOne5** [comment]
> > It is impractical to this ranking function share the same display area with the existing popularManga
> 
> 1. The interface of the ranking function is different from popularManga,
> 2. Due to 1, the options of the ranking function cannot be mixed with popularManga, which is the key reason. For example, you have selected the existing popularManga love category, and selected the "fastest rising" in the ranking function, which interface do we obtain such manga from? The interface of the ranking function can only return the "fastest rising", it can't filter out the love category like popularManga

It's very much doable you can check the Bato.to extension for example which has similar rankings.

**Comment by zhongfly** [comment]
> It's very much doable you can check the Bato.to extension for example which has similar rankings.

It doesn't seem like an easy thing for me, there's nothing I can do……

**Comment by jopejoe1** [comment]
I assume @FourTOne5  is referencing this bit of code in Bato.to which switches the requested URL and parsing depending on the filter option.

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/c957b53b7b6bebc9876d9da86079fe7467ccb27a/src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt#L183-L202

**Comment by FourTOne5** [comment]
> I assume @FourTOne5 is referencing this bit of code in Bato.to which switches the requested URL and parsing depending on the filter option.

Exactly that.. Here's also MangaPark for example which takes a different approach

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/61dda33ce9eaa79a04a2f630434079b1642b1a33/src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt#L98-L164

> It doesn't seem like an easy thing for me, there's nothing I can do……
No one's telling you to do it

**Comment by zhongfly** [comment]
> No one's telling you to do it

I also hope to be able to enrich the functionality of this plugin, I just regret that I can't do anything about it.English is not good, sorry for the misunderstanding.
please don't be so serious.

**Comment by stevenyomi** [comment]
CopyManga is removed, so this should be closed.
