### ISSUE TITLE
Hentai Teca: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#11176]
### Source information

Hentai Teca 1.2.17

### Steps to reproduce

is failing to bypass the cloudflare

### Expected behavior

open normally 

### Actual behavior

It keeps loading, and when it finishes, the error

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

I wanted to know if it is possible to solve this error
Sorry for any English mistakes, I'm using Google translator 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Hentai Teca: Failed to bypass Cloudflare"
