### ISSUE TITLE
Yaoi Manga Online: Missing chapters

### ISSUE THREAD

**Issue by vevinawynn** [tachiyomiorg/tachiyomi-extensions#11175]
### Source information

Yaoi Manga online 

### Steps to reproduce

1 open browse
2 click yaoi manga online extension 
3 search and click  "A Man of Virtue by GGANG-E/ Wook – Ch. 27 [Eng]" in Yaoi Manga Online extension. 

### Expected behavior

For example you can search : "A Man of Virtue by GGANG-E/ Wook – Ch. 27 [Eng]" in Yaoi Manga Online extension. There should have been 53 chapter (as it is in browser)

### Actual behavior

However when you click: "A Man of Virtue by GGANG-E/ Wook – Ch. 27 [Eng]" in Yaoi Manga Online extension. There is only 1 chapter

### Tachiyomi version

0.12.3, and after update : Stable 0.13.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Timi-19** [comment]
Have you found any solution to this issue?

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
