### ISSUE TITLE
Add source  Arabic

### ISSUE THREAD

**Issue by fahad121264** [tachiyomiorg/tachiyomi-extensions#11180]
### Source name

Aresmanga

### Source link

https://aresmanga.com/

### Language

Arabic

### Other details

I would like to add an Arabic source that i think would be really help and thanks in advance
https://aresmanga.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
its old name is iiMANGA which exists and points to it.
