### ISSUE TITLE
komga seriesTitle error

### ISSUE THREAD

**Issue by kshkonan** [tachiyomiorg/tachiyomi-extensions#11186]
### Source information

komga 1.2.39

### Steps to reproduce

1.2.38 >1.2.39 update > If you reinstall later > error > TT help
tachiyomi > extexsion > komga > books cover TAP > (ALERT) error message and (PRINT) 0 chapters

↓ (ALERT) error message ↓
Field 'seriesTitle' is required for type with serial name 'eu.kanade.tachiyomi.extension.all.komga.dto.BookDto', but it was missing

Help me

### Expected behavior

The chapter should have opened after waiting for it to load

### Actual behavior

↓ (ALERT) error message ↓
Field 'seriesTitle' is required for type with serial name 'eu.kanade.tachiyomi.extension.all.komga.dto.BookDto', but it was missing

### Tachiyomi version

0.13.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Update Komga.

**Comment by alfredzw** [comment]
sorry  i also have this issue
  as you mean update komga, it;s to update komga NAS side docker or just update the komga plugin of tachiyuomi

**Comment by ghostbear** [comment]
Update Komga on your NAS
