### ISSUE TITLE
Readcomiconline not working anymore

### ISSUE THREAD

**Issue by onorinoDiTanna** [tachiyomiorg/tachiyomi-extensions#11188]
### Source information

ReadComicOnline 1.2.10

### Steps to reproduce

Open surce and browse comics list

### Expected behavior

Comics list should appear showing latest or hottest titles

### Actual behavior

No results found screen appears.

Website is reachable normally even from the built in browser in the app.

### Tachiyomi version

App version: 0.13.1-4202  

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#11141
