### ISSUE TITLE
[BUG] Mangahub downloading issue

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#11184]
### Source information

Mangahub 1.2.12

### Steps to reproduce

1. Select any msnga from mangahub 
2. Download any chapter
3. Now navigate to download queue 
4. The download will be paused
5. And if u try to resume it automatically pause again in a flash

### Expected behavior

Chapter should start downloading uninterruptly 

### Actual behavior

Chapter is not downloading 

### Tachiyomi version

0.13.1

### Android version

12

### Other details

Note: but we are able to read the chapter without downloading 

ALSO other sources are working fine i am able to download chapters from other sources 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
did you rename the Mangahub folder to MangaHub?

**Comment by Samk19** [comment]
No i didnt do that 
And in the tachiyomi download folder there were many folders with name mangahub (en) (numbers)

**Comment by Samk19** [comment]
After remaning Mangahub to MangaHub its working 

Thankyou
