### ISSUE TITLE
Fix everia club source

### ISSUE THREAD

**Issue by XOrinu** [tachiyomiorg/tachiyomi-extensions#11181]
### Source information

Everia.club 1.2.1

### Steps to reproduce

Issue : 
Didn't see a chapter.

### Expected behavior

It has a chapter

### Actual behavior

The chapter didnt show up. It says “ unparseable date : "" (at offset 0) ”

### Tachiyomi version

Tachiyomi v0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sudocanttype** [comment]
I'm going to try to fix this.

**Comment by curche** [comment]
Closing since #11458
