### ISSUE TITLE
Manga 1000 and 1001 extension change website.

### ISSUE THREAD

**Issue by shoyaya** [tachiyomiorg/tachiyomi-extensions#11192]
### Source name

Manga1000

### Source link

https://manga1000.top/

### Language

Japanese

### Other details

Can you update extension with this new website?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
manga1000 closed down #11047 so was removed, this may be a copycat, please open an extension request instead.
