### ISSUE TITLE
MangaPro is Down

### ISSUE THREAD

**Issue by Auri2307** [tachiyomiorg/tachiyomi-extensions#11194]
### Source information

MangaRaw 1.2.5

### Steps to reproduce

1. Open the MangaPro website at MangaPro.top either from browser or Webview.

### Expected behavior

The MangaPro website should load.

### Actual behavior

Comick.top loads instead of MangaPro.top. 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

The MangaPro website, which was a part of the MangaRaw extension, seems to be down. Attempting to visit the website (mangapro.top) simply redirects me to comick.top instead. 

I'm aware MangaPro extension was intended as an alternative to Manga1000/1001, but manga1000.top appears to be back up and running, so maybe that could be substituted for the defunct MangaPro?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ringosham** [comment]
This is not limited to Tachiyomi. mangapro.top is now returning 302 and points to comick.top.

Might need to remove mangapro.top from the extension if this is the case

**Comment by ringosham** [comment]
Speaking of manga1000.top, it seems like this is a mishmash of links that connects to all other different sites such as comick.top and syosetsu.top. The latter one serves light novels.

**Comment by ringosham** [comment]
Should be closed due to #11308
