### ISSUE TITLE
"Pages Not Found" in Jinmantiantang

### ISSUE THREAD

**Issue by hellguns** [tachiyomiorg/tachiyomi-extensions#11209]
### Source information

Jinmantiantang Version 1.2.23

### Steps to reproduce

When I tried to read, it showed no pages found. The same applies to other manga and webtoons from this source. I tried to clear cache, etc but it doesn't work. I tried it on my tablet and phone, and the same problem occured. It works fine when I tried to read it through webview. 

### Expected behavior

Being able to read it without needing to read it through webview.

### Actual behavior

I'm only able to read it through webview and not through the extension.

### Tachiyomi version

0.13.1

### Android version

Android 12 One UI 4.0

### Other details

My apologies if this isn't filled out properly. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by in-out** [comment]
same here

**Comment by su2353** [comment]
同上

**Comment by R14Z** [comment]
same for me

**Comment by junyaotan020517** [comment]
same issue. pls fix it. thx a lot

**Comment by YuGhi-bug** [comment]
same issue here
