### ISSUE TITLE
Falla a cargar imágenes

### ISSUE THREAD

**Issue by Fthv** [tachiyomiorg/tachiyomi-extensions#11201]
### Source information

IMHentai versión 1.2.6

### Steps to reproduce

![Screenshot_20220321-171736](https://user-images.githubusercontent.com/102137078/159422075-c638aede-919c-479b-82ae-b20105f373f5.jpg)
Cómo pueden ver no carga las imágenes y eso pasa entodos los doujinshi y no es la página

### Expected behavior

Que lo arreglen es una grandiosa aplicación la verdad me encanta tanto para leer manga y doujinshi

### Actual behavior

Antes tardaba mucho y ahora ni siquiera carga las imágenes luego luego te aparece el mensaje de reintentar
![Screenshot_20220321-171736](https://user-images.githubusercontent.com/102137078/159422711-2186aad7-574a-428b-bb5d-af765c06bc5a.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by D3xron** [comment]
Pon en ingles, la issue, gracias!

**Comment by NECHEPIR** [comment]
The same problem after the update

**Comment by curche** [comment]
Shud be fixed by #11195 
Update the extension. Follow through the troubleshooting guide ([click here](https://tachiyomi.org/help/guides/troubleshooting/)) just in case and try again.
If it still doesnt work, create a new issue
