### ISSUE TITLE
Zinmanga

### ISSUE THREAD

**Issue by KyF4** [tachiyomiorg/tachiyomi-extensions#11211]
### Source information

zinmanga

### Steps to reproduce

Zinmanga is showing "no chapters found" on all manga and manhwa/manhua

### Expected behavior

it should be just as normal showing regular updates

### Actual behavior

it says no chapters found and cannot be accessed through the app

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

can read through website but not the app 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
cannot reproduce
