### ISSUE TITLE
Immortal Updates: Chapter images are scrambled or do not load

### ISSUE THREAD

**Issue by Thifa30** [tachiyomiorg/tachiyomi-extensions#11214]
### Source information

Immortal Updates 1.2.19

### Steps to reproduce

1. Opening the chapter
2. Waiting for it to load.
3. The first page didn't show up, and the rest of the pages has broken images.

### Expected behavior

The chapter should load with normal, colored pages.

### Actual behavior

The first page didn't load, second page an announcement from Immortal Updates to read from their website, third page and the rest showing broken images.

### Tachiyomi version

0.13.1

### Android version

Android 8.1.0

### Other details

This is how it's shown in "Empress' Harem" chapter 282. The previous chapter, 281, looks normal.

![Screenshot_2022-03-23-03-34-58-006_eu kanade tachiyomi](https://user-images.githubusercontent.com/102187129/159571178-7937b036-95be-4730-b339-2d1c230572aa.jpg)
![Screenshot_2022-03-23-03-34-51-753_eu kanade tachiyomi](https://user-images.githubusercontent.com/102187129/159571194-a28ba59d-c843-4fcd-b440-a58888eab2c1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tyme2tb** [comment]
Same issue with "I have 999 abilities"

**Comment by mneko** [comment]
Seems to be trick panels like pmscans likes to do, instead of actually broken

**Comment by alessandrojean** [comment]
/edit-title "Immortal Updates: Chapter images are scrambled or do not load"

**Comment by gaRt3n** [comment]
It's to prevent crawler to copy these images. It seems to run a script to rescramble these images.

**Comment by Okedele** [comment]
Please will this issue be fixed or is there nothing that can be done?

**Comment by RaviMohanVerma** [comment]
Seems like no contributor is interested in fixing immortal updates extension.

**Comment by FourTOne5** [comment]
> Seems like no contributor is interested in fixing immortal updates extension.

Yeah you're right no one is interested it's not like it's hard to fix or something
