### ISSUE TITLE
MangaOwl: No pages found

### ISSUE THREAD

**Issue by Fujin-sama** [tachiyomiorg/tachiyomi-extensions#11212]
### Source information

Mangaowl 1.2.25

### Steps to reproduce

1. You will open any chapter of any manga in mangaowl
2. But it says no pages found

### Expected behavior

The chapter should view its pages

### Actual behavior

It say's No pages found when opening a chapter

### Tachiyomi version

0.13.1

### Android version

Android 9

### Other details

![Screenshot_20220323-014235_Tachiyomi](https://user-images.githubusercontent.com/97900048/159543703-16b601ce-8e8b-4fa8-9938-e8d45e50ffa3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Does refreshing the manga fix it? Pull down from the top.

This issue might crop up if the chapter URL was updated ages ago, and thus lacking the `s` parameter.

**Comment by Fujin-sama** [comment]
Its still not working. I already did what you told but still says no pages found

**Comment by alekc** [comment]
Just tried it out and cannot reproduce.

**Comment by AliceDragonSoul** [comment]
I have the same problem

**Comment by ahabbs20** [comment]
I have had the exact same issue. I've cleared cookies, reinstalled and have kept up to date with versions. Only way to access pages is through WebView

**Comment by olga2410** [comment]
I have the same problem

**Comment by Hatdog28** [comment]
I have the same exact issue. Even though, I already installed and uninstalled the MangaOwl, and keep on refreshing it. It's still not working. But I can search for the story that I want to find. But it's just appearing in the search results. And when I open it, it said no pages found, or it will load for a second and then go back to the list of the chapters.

**Comment by tdogubo** [comment]
Same problem here. I uninstalled the extension, then the app. Upgraded to the latest `Tachiyomi` version `0.13.4` and I still get the same issue. Only way to read manhwa is via WebView.
