### ISSUE TITLE
Mangadex: Comikey link? 

### ISSUE THREAD

**Issue by sshawnsamuell** [tachiyomiorg/tachiyomi-extensions#11213]
### Source information

Mangadex 1.2.158

### Steps to reproduce

Load chapters where mangadex links to comikey

### Expected behavior

Load the chapters

### Actual behavior

404 error

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

This probably doesn't effect a large amount of titles, but I realized this was an issue almost 2 months later for After God (https://mangadex.org/title/65fa324d-4075-4f59-a71c-2c82f69f6779/after-God). 
I was able to read Ch 1,so it wasn't an issue at some point, but between then and now no chapters have updated. 
The obvious answer is to just use the comikey source, which does work, but it took me 2 months to notice I wasn't getting updates and then had to figure out why.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
chapters from comickey are external, mangadex just lists them but since you can't read it in the mangadex extension it is purposely removed. it is intended.
