### ISSUE TITLE
manga.ovh

### ISSUE THREAD

**Issue by MWGuy** [tachiyomiorg/tachiyomi-extensions#11228]
### Source name

manga.ovh

### Source link

https://manga.ovh

### Language

Russian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by MWGuy** [comment]
Also this site have an API https://api.manga.ovh/swagger-ui/

**Comment by szchii** [comment]
+

**Comment by szchii** [comment]
want

**Comment by e-shl** [comment]
What is remarkable it?

**Comment by shzchi** [comment]
> Чем это примечательно?

This is a new user-friendly site gaining popularity. This is a good replacement for the outdated readmanga,ru and the decaying mangalib,me. Some translators are starting to go to this site.

I would like to see it added to tachiyomi.

**Comment by shzchi** [comment]
> ~Also this site have an API with documentation https://api.manga.ovh/swagger-ui/~
> 
> API now closed and will not be opened. Any attempts to add this site to the tachiyomi will result in retaliation from the site.

Why?

**Comment by stevenyomi** [comment]
Reopening this to avoid duplicates.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
