### ISSUE TITLE
NineManga: Chapter images does not load

### ISSUE THREAD

**Issue by VannevarB** [tachiyomiorg/tachiyomi-extensions#11222]
### Source information

NineManga v1.2.16

### Steps to reproduce

1. Open Manga
2. Open a chapter
3. Load images
4.  Read

### Expected behavior

1. Open a manga
2. Open a chapter
3. Load images

### Actual behavior

1. Open a manga
2. Open a chapter
3. Don't Load images

### Tachiyomi version

0.13.1

### Android version

Android 8

### Other details

He intentado con la webview y carga lento las imagenés.
Aqui un screenshot de la app

![Screenshot_2022-03-22-01-54-26](https://user-images.githubusercontent.com/61358702/159618621-6aafc46d-b498-40ed-aff3-fdd5e0af7f87.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "NineManga: Chapter images does not load"

**Comment by KasukeLp23** [comment]
I have the same problem

**Comment by FRNINEZY** [comment]
Yeah I have the same problem

**Comment by Sarkozy1210** [comment]
Yo también tengo el mismo problema

**Comment by efre1004** [comment]
También tengo ese problema

**Comment by psocake** [comment]
Double check WebView to make sure that the links are loading via web. Some of the older chapters and mangas are not loading via WebView/computer so it would be on ninemangas end to fix the loading issues and not the extension.

**Comment by Sc0o0p** [comment]
It is somehow working fine now.

**Comment by alekc** [comment]
cannot reproduce.
