### ISSUE TITLE
Anitation Arts: Changed domain and theme

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi-extensions#11237]
### Describe your suggested feature

From Their Discord

> Important Update!
Hello everyone, as everyone realized we haven't been releasing much chapters for the past 2 weeks. We have a reason for that.
We'll be changing our group name and move into a new domain & website.
https://akuzenaiarts.org/
The main reason for changing our website is because some unauthorized person gained backdoor access to our database and has been adding unwanted stuff. We have been trying to constantly removing it as soon as it was uploaded but it became annoying at this point. We also contacted the host regarding  this but it only had our hope let down and the theme provider suggested to change the name and move into a different domain to avoid further complications and risk of losing new data. After week of consideration we've decided to move into a new domain. We have increased Our security to Max in our new website. Oh, also please do share the news of our website change to as  any friends of yours as possible.
Note: Except for our twitter, domain and names in credit we won't be changing into our new name anywhere anytime soon... (Like our donation link names). It is so because for those who just mark the channel as read without seeing the message to catch on that we changed our group name.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Also changed theme to Madara, would require changing `versionId`

**Comment by alessandrojean** [comment]
/edit-title "Anitation Arts: Changed domain and theme"

**Comment by Riztard** [comment]
who is using the old domain then https://anitationarts.org 
last update is 1 week ago

**Comment by AntsyLich** [comment]
> who is using the old domain then https://anitationarts.org last update is 1 week ago

It's still owned by them but the new domain gets more update
