### ISSUE TITLE
Webtoon Hatti: Error when downloading a chapter

### ISSUE THREAD

**Issue by SpaceSemih** [tachiyomiorg/tachiyomi-extensions#11254]
### Source information

Webtoon Hatti v1.2.18

### Steps to reproduce

If I give an example, it gives an error because it sees 8 pages while there are 7 pages and cannot download the last page.

### Expected behavior

download episodes

### Actual behavior

download episodes

### Tachiyomi version

0.13.1 (1.02.2022 20:35)

### Android version

Android 11

### Other details

1. https://cdn.discordapp.com/attachments/349436576037732355/957353663041507428/WhatsApp_Image_2022-03-26_at_22.01.19.jpeg

2. https://cdn.discordapp.com/attachments/349436576037732355/957355136831868948/WhatsApp_Image_2022-03-26_at_22.05.52.jpeg

3. https://cdn.discordapp.com/attachments/349436576037732355/957356917695578132/WhatsApp_Image_2022-03-26_at_22.14.18.jpeg

4. https://www.hizliresim.com/4hb26vj

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Webtoon Hatti: Error when downloading a chapter"

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
