### ISSUE TITLE
Hiperdex genre list

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#11251]
### Describe your suggested feature

Remove the fetching data on the genres section of the filter replacing it with fixed genres list writing it directly in the extension (like a previous version of the extension). i am asking for it because every time i open hiperdex i have to scroll down, fetch the genres clicking on the button "press reset to attempt to fetch genres" and then the reset button. previously the genre list was fixed and i didn't have to do all this cranky stuff becuse the genre list was always there, fixed and without the need to fetch, worsening the QoL in the use of the extension. can you restore it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I think it would be just better to fix this app-side bug (of not reflecting the filter list changing) instead of removing it from the extension.

Dynamic tags/genres are in general better because they don't become outdated and don't require maintenance over time.

**Comment by Palloxin** [comment]
> I think it would be just better to fix this app-side bug (of not reflecting the filter list changing) instead of removing it from the extension. There were an issue in the app repository about it, IIRC, but I didn't find it now.
> 
> Dynamic tags/genres are in general better because they don't become outdated and don't require maintenance over time.

i just don't want to do the fetch od the genre list every sigle time. if it can be fixed it is good

**Comment by alessandrojean** [comment]
It just fetches one time already, the 'Reset'-thing is the bug I mentioned (of not showing the filters in the most updated state).

It's just bad worded in the extension, it should be something like "Press Reset to show the fetched Genres".

**Comment by alessandrojean** [comment]
This is also not specific to this extension, it is in the base Madara code.

**Comment by Palloxin** [comment]
So the genre filter disappeared, i can't use that anymore
