### ISSUE TITLE
Bento Manga

### ISSUE THREAD

**Issue by ChevalierdEon** [tachiyomiorg/tachiyomi-extensions#11253]
### Source name

BentoManga

### Source link

https://www.bentomanga.com/

### Language

French

### Other details

Hi,
The japanread site has become bentomanga. 
so it's a change of domain name.

thank you in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Valtrana** [comment]
Approve it 😀

**Comment by alessandrojean** [comment]
/edit-title "Japanread: Changed their name and domain"

**Comment by davido97410** [comment]
Approve it too

**Comment by alekc** [comment]
https://www.japanread.cc is still up and working in the app as well. no mention of the change of the domain on the website. 

Close?

**Comment by alessandrojean** [comment]
Maybe this one is just a mirror or a new and totally different website.

**Comment by MickaelB57** [comment]
Le site https://www.japanread.cc/ à temporairement était réouvert (pour corriger des problèmes). Mais son successeur est bien https://www.bentomanga.com/.

**Comment by MickaelB57** [comment]
The site https://www.japanread.cc/ was temporarily reopened (to correct some problems). But its successor is https://www.bentomanga.com/.

**Comment by lecomteb27** [comment]
I would like to inform you that since 72 hours, it is no longer possible to read the chapters on the Tachiyomi app with Japanread. Is it because of the name change?

**Comment by soadienne65** [comment]
Vous serez t'il possible de rajouter bentomanga vue que japanread ne fonctionne plus.

**Comment by alekc** [comment]
So, there are 2 issues in this extension. 1) thumbnails are not being downloaded if no referrer is present, easily fixed. 

Another is that japanread has dropped API and changed to obfuscated javascript loader.(https://pastebin.com/1Fk3A7Ty) realistically speaking I don't think anyone will spend required time (when publisher can easily change the source) to fix this given that the fix might be very short lived.

**Comment by davido97410** [comment]
So you say that the source will never come back ?

**Comment by Valtrana** [comment]
The best solution would be to create the BentoManga extension and develop a patch for Japanread, because currently Takiyomi cannot be used for any of these sources. Moreover, we absolutely do not know the date of Bentomanga's commissioning. The site is online, but a lot of Japanread users have complained because they don't like BentoManga and it's buggy. I even bet that when BentoManga is released, there will be even more Takiyomi users because it is easier to use than BentoManga xD
