### ISSUE TITLE
Asura Scans: Missing chapter pages

### ISSUE THREAD

**Issue by naveh94** [tachiyomiorg/tachiyomi-extensions#11259]
### Source information

Asura Scans 1.2.25

### Steps to reproduce

1. open any chapter

### Expected behavior

All of the chapter's images should load in order,
including the 1st image which is usually the chapter title:
![image](https://user-images.githubusercontent.com/34156105/160305618-821269d8-9172-420c-aa24-7d13c7265b0a.png)
![image](https://user-images.githubusercontent.com/34156105/160305643-6d393ca7-5b6b-4dc6-b40d-739d5a671727.png)

### Actual behavior

the extension instead starts on the 2nd or 3rd image of the chapter:
![image](https://user-images.githubusercontent.com/34156105/160305478-d727e9a2-1f5c-4696-a43d-f78df3daec15.png)
(on this example, the extension skipped both 1st and 2nd images of the chapter)

### Tachiyomi version

0.13.1

### Android version

Android 9

### Other details

According to previous issue reports, there was an issue where due to an image advert on the chapter pages, there were issues downloading the chapter.
This current issue feels like a result of an attempted fix to the previous issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BellCranelUwU** [comment]
The extension might be cutting off the pages before the ad. As seen on this screenshots
![Uploading Screenshot_20220513-173636_TachiyomiJ2K.jpg…]()

**Comment by BellCranelUwU** [comment]
The extensionmight be cutting off pages before an ad. As seen on these screenshots
![Screenshot_20220513-173636_TachiyomiJ2K](https://user-images.githubusercontent.com/88405325/168265329-719a3804-7a11-47a3-8f7e-b3436e312d0e.jpg)
![20220513_173158](https://user-images.githubusercontent.com/88405325/168265339-224b6c9d-e39b-44a8-8bdc-a3a130229d0e.jpg)

**Comment by BellCranelUwU** [comment]
The extension might be cutting off pages before an ad. As seen on these screenshots. 1st pic is from webview, 2nd pic is from the app
![Screenshot_20220513-172933_TachiyomiJ2K](https://user-images.githubusercontent.com/88405325/168265620-b1724820-04b5-406f-828c-2ec1cd5cb2d0.jpg)
![Screenshot_20220513-173636_TachiyomiJ2K](https://user-images.githubusercontent.com/88405325/168265612-469575a3-1068-4fd3-a3b2-dd58386e315c.jpg)
