### ISSUE TITLE
No pages found 

### ISSUE THREAD

**Issue by Chaosmayme** [tachiyomiorg/tachiyomi-extensions#11267]
### Source information

Manga-raw.club ver 1.2.8

### Steps to reproduce

When I select a chapter It closes automatically saying no pages found 

### Expected behavior

To view and read chaper

### Actual behavior

When I select a chapter It closes automatically saying no pages found

### Tachiyomi version

0.13.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AaronDragneel** [comment]
I'm getting the same issue

**Comment by Yujiniie** [comment]
Same here

**Comment by NidPlays** [comment]
> same here

**Comment by Beji-kun** [comment]
same problem too.

**Comment by Chaosmayme** [comment]
It's working now
