### ISSUE TITLE
Nhentai: Show favorites only not working

### ISSUE THREAD

**Issue by PixelSpartan** [tachiyomiorg/tachiyomi-extensions#11268]
### Source information

Nhentai 1.2.31

### Steps to reproduce

Access the extension 
Filter
"Show favorites only"

### Expected behavior

Doujin in the favorite section of the account should appear

### Actual behavior

Extension can't access/find the favorites : "No result", but can still detect if i'm connected (or not) on the webview

Also the homepage is "broken", it show the most popular doujin of all time when it's supposed to show the 5 most popular of the day and the new upload

### Tachiyomi version

0.13.1

### Android version

10 QP1A.190711.020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> Also the homepage is "broken", it show the most popular doujin of all time when it's supposed to show the 5 most popular of the day and the new upload

You can change that by using the `Sort By` filter. It's working fine, it's the default to show the most popular of all time (all extensions does that by default).

**Comment by alessandrojean** [comment]
/edit-title "Nhentai: Show favorites only not working"

**Comment by A49akash** [comment]
Until this issue is pushed in. An annoying round about is to open webview and go to favorites and then on your doujin click on open with browser (three dots) and then come back by selecting tachiyomi:nhentai . but is annoying and comes out to extensions page when you click back so waiting for this bug to get fixed.
