### ISSUE TITLE
Pocket Comics Login

### ISSUE THREAD

**Issue by BNX070** [tachiyomiorg/tachiyomi-extensions#11262]
### Describe your suggested feature

Add an option to login to Pocket Comic's account to view unlocked chapters. Currently apart from the free chapters the rest can't be viewed even if you have unlocked chapters on your pc account. Similar to how the Viz Media extension allows login to view unlocked chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you not just open in webview and login there?

**Comment by ObserverOfTime** [comment]
Actually, I'm probably thinking of another extension.

Pocket Comics uses a cookie which *should* be stored in the jar.

**Comment by jopejoe1** [comment]
Login in and reading unlocked chapter works for me.

**Comment by BNX070** [comment]
> > Tried that but it doesn't unlock chapters in tachiyomi.
> 
> Login in and reading unlocked chapter works for me. 
> Did you try refreshing the chapter list after login?

That did work lol. Thanks
