### ISSUE TITLE
Sekte Doujin: Chapter does not load

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#11270]
### Source information

Sekte Doujin 1.2.15

### Steps to reproduce

1. Open the source
2. Search any Manga, Manhua or Manhwa
3. Select a chapter
4. Chapter cant be loaded 
![Screenshot_2022-03-30-00-01-16-22_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/160667329-ac054e13-b250-4609-89a7-9228afcb7407.jpg)

### Expected behavior

All chapter in this source / ekstension cant be loaded and it just loop at spining circle 

### Actual behavior

The page must be working properly

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Sekte Doujin: Chapter does not load"

**Comment by shiroon123** [comment]
They change domain to sektedoujin.club
