### ISSUE TITLE
Origami Orpheans: Migrated to WpMangaReader

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#11278]
### Source information

Origami orpheans 1.2.20

### Steps to reproduce

1.Open added title/browse/latest

### Expected behavior

Load

### Actual behavior

Error 404

### Tachiyomi version

0.13.1

### Android version

A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They migrated their website to WpMangaReader.
