### ISSUE TITLE
ManhuaUS covers not loading

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#11276]
### Source information

ManhuaUS 1.2.22

### Steps to reproduce

1. Open a manga

### Expected behavior

Loads cover

### Actual behavior

Does not Load cover

### Tachiyomi version

r4215

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
Just tryed it in stable its indeed working.

**Comment by DchanN** [comment]
> Just tryed it in stable its indeed working.

we have the same issue then, already report https://github.com/tachiyomiorg/tachiyomi/issues/6797
maybe you can comment your problem there

**Comment by jopejoe1** [comment]
Closing in favor of  #6797
