### ISSUE TITLE
ReadComicOnline: Missing search results

### ISSUE THREAD

**Issue by Pinkarmor01** [tachiyomiorg/tachiyomi-extensions#11281]
### Source information

ReadComicOnline 1.2.11

### Steps to reproduce

1. Open ReadComicOnline extension
2. Search title (ex. Superman)
3. Only first 32 results will show when searching 

### Expected behavior

All titles with the word Superman should appear in the search. 

### Actual behavior

Only the first 32 results of a search will come up. I've tried other keywords and again only first 32 results come up. 

### Tachiyomi version

0.13.1

### Android version

Fire OS 7.3.2.2

### Other details

Search function was working properly before the ReadComicOnline extension was broken and then fixed. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing since the source was removed, and we don't give support to obsolete extensions.
