### ISSUE TITLE
Asura scans Error 520 

### ISSUE THREAD

**Issue by Hero-Kage** [tachiyomiorg/tachiyomi-extensions#11282]
### Source information

Asura Scans 1.2.25

### Steps to reproduce

Trying to update added series or loading the series from Asura Scans in the app shows the error.

### Expected behavior

Loading and update the series.

### Actual behavior

Shows error 520, web view shows an issue with Cloudflare.
Loading Asura Scans website in browser works, no Cloudflare or connection issues.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 5xx errors usually means the website server is having issues. What you're seeing in the WebView is probably a cached version of the website.

**Comment by Hero-Kage** [comment]
> HTTP 5xx errors usually means the website server is having issues. What you're seeing in the WebView is probably a cached version of the website.

With that hint I went and deleted the cookies in the app. That solved the issue for me
