### ISSUE TITLE
ReadComicOnline: Missing chapters

### ISSUE THREAD

**Issue by howldiaz** [tachiyomiorg/tachiyomi-extensions#11295]
### Source information

ReadComicOnline 1.2.11

### Steps to reproduce

1. Download ReadComicOnline extension
2. Search for any comic currently On Air.
3. Update the data so you can see the last chapter.
4. It wont reload.

### Expected behavior

It should update the list of said comic.

### Actual behavior

It doesn't update.

### Tachiyomi version

v0.13.1

### Android version

Android 11

### Other details

The problem itself isnt about the extension or whatever. It seems like ReadComicOnline.li (the page where it is getting the comics the app), no longer updates any comic. Instead I recommend using https://readcomicsonline.ru, which seems to be basically the same page, just that it updates titles.

I hope I didnt fail to post this issue here, and I hope it works with the page I just said.

Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing since the source was removed, and we don't give support to obsolete extensions.
