### ISSUE TITLE
Image error

### ISSUE THREAD

**Issue by ImaImmortal** [tachiyomiorg/tachiyomi-extensions#11309]
### Source information

Immortal updates 1.2.19

### Steps to reproduce

When I try reading a manhwa from the source there's glitch in loading image 

### Expected behavior

Fixing image glitch

### Actual behavior

![Screenshot_20220402-160823](https://user-images.githubusercontent.com/102857512/161379428-ff8408c6-5777-4164-9bc3-59fd3b0a14b4.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#11214
