### ISSUE TITLE
Neox Scarlator com problema de troca de URL

### ISSUE THREAD

**Issue by Budo420** [tachiyomiorg/tachiyomi-extensions#11305]
### Source information

Neox Scarlator 1.2.25

### Steps to reproduce

![Screenshot_20220402-020622](https://user-images.githubusercontent.com/102845577/161367374-5bfcc268-462a-42c7-8f20-562e927d1e4d.png)

### Expected behavior

Quando entro em algum mangá da fonte, eu poderia ler sem problemas, mas agora não consigo ler, não abre e aparece o error404 seguido disso

### Actual behavior

Agora fica aparecendo que a URL da fonte mudou e pede para migrar os mangás para a mesma fonte, mas já fiz isso duas vezes nos últimos dia, e aconteceu novamente o mesmo erro hoje. A cada 3 dias esse erro acontece

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Os mangás ficam indisponíveis e mesmo estando na biblioteca, quando vou olhar na fonte, não costa que eles estão na biblioteca. Daí tenho que apagar eles e fazer todo o processo novamente, e depois de 3 dias, acontece o mesmo erro. Não sei como resolver

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Eles que mudam a URL de tempos em tempos e não temos controle nenhum sobre isso e nem como contornar este problema. Se isso te incomoda, use outras fontes que não tenham esse comportamento.
