### ISSUE TITLE
ManhuaUS can't load cover images

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi-extensions#11306]
### Source information

ManhuaUS 1.2.22

### Steps to reproduce

1. Load any manga
2. The app won't be able to load the cover images while in the webview you can see them

### Expected behavior

Show the cover images

### Actual behavior

Not showing the cover images

### Tachiyomi version

r4215

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
extension doesn't have problem and it's seems duplicate https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11276

and this Preview bug will fixed soon https://github.com/tachiyomiorg/tachiyomi/issues/6797
