### ISSUE TITLE
Doujin Desu : Cant download chapter 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#11313]
### Source information

Doujindesu 1.2.2

### Steps to reproduce

1. Open Doujindesu
2. Search Hero manager
3. Download chapter 24
4. Cant download chapter (progress always 0 and not increase)
![Screenshot_2022-03-31-09-27-30-42_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/160964152-23f8f60e-58f4-4991-a07d-db18f80ca9bc.jpg)

### Expected behavior

Cant download chapter 

### Actual behavior

Chapter must be downloaded 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
> ![Screenshot_2022-04-26-00-16-41-661_com UCMobile intl](https://user-images.githubusercontent.com/23666289/165119700-a02756bf-329a-478b-8972-0fcaa6dc2fd5.jpg)
> 
> Emang dari sumber chapter nya yang error.

Makasih bro
Tpi dlu emg sempet bisa jadi download an dri pdf w apus 😅
Ganyangka bakal error lgi 🤦🏻‍♂️

**Comment by ZekkenID** [comment]
> Misal klo dri downloadan dimasukin entry nya Tachiyomi bisa gk ? Tachi kan dri gambar tuh nah yg pdf dijadiin gambar terus dimasukin entry nya tachi bisa gk ?

Menurut saya sih ribet harus convert² kek gitu mending download pdf reader dan langsung baca disitu. Kalau saya komik lokal download perfect viewer + add-on pdf

**Comment by TheKingTermux** [comment]
> > Misal klo dri downloadan dimasukin entry nya Tachiyomi bisa gk ? Tachi kan dri gambar tuh nah yg pdf dijadiin gambar terus dimasukin entry nya tachi bisa gk ?
> 
> Menurut saya sih ribet harus convert² kek gitu mending download pdf reader dan langsung baca disitu. Kalau saya komik lokal download perfect viewer + add-on pdf

Thanks bro
