### ISSUE TITLE
Setsu Scans no longer exists?

### ISSUE THREAD

**Issue by Meistermagier** [tachiyomiorg/tachiyomi-extensions#11316]
### Source name

Setsu Scans

### Source link

https://setsuscans.com/

### Language

English

### Other details

The Setsu scans extension did exist at one point and i had it until recently when i did a reinstall and i could not find the extension for Setsu Scans anywhere like it vanished from the face of the earth. It is also nowhere mentioned why Setsu Scans would have been removed. As far as I found.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Was removed as per request
Refer - https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11239#issuecomment-1080002953

**Comment by Meistermagier** [comment]
Oh then close this issue i somehow was not able to find this when i searched through the issues page.
