### ISSUE TITLE
Sekte Komik : Chapter does not load

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#11318]
### Source information

Sekte Komik 1.2.16

### Steps to reproduce

1. Open ekstention
2. Search any Manga Manhua or ManhwaManhwa
3. Select any chapter
4. Chapter cant be loaded
![Screenshot_2022-04-03-21-36-07-04_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/161433274-b4f29bce-655d-491e-9ad8-95005bdeb261.jpg)

### Expected behavior

Chapter cant be loaded and stuck at the spining circle 

### Actual behavior

Chapter must be loaded

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
This issue is slightly different from not being able to update a comic, as I prefer to read online on a certain extension.  In this extension I can't open any comics available in that extension

**Comment by Riztard** [comment]
work for me
