### ISSUE TITLE
Top Manhua: Changed their domain, name and theme

### ISSUE THREAD

**Issue by Beji-kun** [tachiyomiorg/tachiyomi-extensions#11321]
### Describe your suggested feature

Change source from https://topmanhua.com/ to http://readma.net/
So https://topmanhua.com/ its not actual because every time when i open I got forward to the readma.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Top Manhua: Changed their name and domain"

**Comment by Beji-kun** [comment]
Thank you for the correct classification

**Comment by alessandrojean** [comment]
/edit-title "Top Manhua: Changed their domain, name and theme"

**Comment by alekc** [comment]
Extension is working correctly, and there is no redirect from https://topmanhua.com/
