### ISSUE TITLE
HTTTP erorr 429

### ISSUE THREAD

**Issue by Yamiyie** [tachiyomiorg/tachiyomi-extensions#11324]
### Source information

1st kiss 

### Steps to reproduce

I'm banned again for reading too fast.I already reported many times but this issue is still not fixed.

### Expected behavior

I just want to read and update my library like i always do

### Actual behavior

I was banned 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

I wish y'all can hear me out once I'll keep reporting until this issue will be fixed.Pls help me

Thankyou!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please inform the extension version you're using since you didn't provided in the "Source information" field.

Make sure you're using the v1.2.24.

**Comment by CarlosEsco** [comment]
Update your extension and if you get unbanned  then try.  We can't control you being banned already
