### ISSUE TITLE
Cocomanhua changed domain

### ISSUE THREAD

**Issue by dorupogo** [tachiyomiorg/tachiyomi-extensions#11323]
### Source information

Cocomanhua

### Steps to reproduce

HTTP ERROR 403

### Expected behavior

Should open source

### Actual behavior

Http error 403

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If they changed the domain, it would be helpful if you had informed it in the Other details field.

**Comment by Nfivez** [comment]
https://www.cocomanga.com/ still seems to be the domain, but I cannot access it either.

**Comment by DchanN** [comment]
> https://www.cocomanga.com/ still seems to be the domain, but I cannot access it either.
> 
> EDIT: Okay, this is weird, I have tested cocomanga from another device, which is android 11. I can view all the manga fine but martial peaks which has over thousands of chapters not update at all. The device I can't access it at all is android 10.

I'm in android 10, and doesn't have any problem with access, can even read without any problem 
![Screenshot_20220404-095214529](https://user-images.githubusercontent.com/101858971/161461525-73152024-985d-415a-8139-aedf2a0830de.jpg)
![Screenshot_20220404-095232454](https://user-images.githubusercontent.com/101858971/161461539-7decd6f1-bf83-41c4-9f65-e5ebc7d2a1a1.jpg)

**Comment by Radio028** [comment]
I am also having same error issue viewing comics with the app, but there is no problem with web view.

**Comment by alessandrojean** [comment]
Since it's just Cloudflare and it's working for other people, I am closing it. If opening in WebView didn't solve it to you, you can only wait until they lower their protection (very unlikely to happen), trying other connections, or migrating to other sources.
