### ISSUE TITLE
field to bypass cloudflare

### ISSUE THREAD

**Issue by DzLahmer** [tachiyomiorg/tachiyomi-extensions#11328]
### Source information

Mangalink 1.2.19 , manga lek 1.2.18

### Steps to reproduce

What I open chapter a message Appear says field to bypass cloudflare
When I search for manga in this extension message apear says field to bypass cloudflare

### Expected behavior

Should open chapter

### Actual behavior

Massege says field to bypass cloudflare

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
1. We have no control over Cloudflare, if opening in WebView didn't solve it, nothing you can do besides waiting the website to lower the protection or migrating.
2. One source per ticket.
