### ISSUE TITLE
CoCoManhua: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by History-exe** [tachiyomiorg/tachiyomi-extensions#11334]
### Source information

CoCoManhua(OhManhua) 1.2.10 chinese

### Steps to reproduce

I have the proxy connection, so maybe not the network proble.
1. CoCoManhua setting is limit is 1, period is 2.
2. clink to the CoCoManhua extension.

### Expected behavior

show the manga. and can update the manga.

### Actual behavior

1. After several seconds(about 30 seconds), can't show the manga, only the error notify: Can't bypass cloudflare.
3. But I open the CoCoManhua web through the webview in tachiyomi it workes, and the web link is https://www.cocomanga.com

### Tachiyomi version

0.13.1

### Android version

Android 9

### Other details

In Webview I open one manga that in my bookshelf which is belonging to CoCoManga, which link is https://www.cocomanga.com//15336/, is works, I can see the manga list and the picture.

But when I slide down another error occur and show empty page with these code:

`网页无法打开
位于 https://xc.4po6iqp9.cn:8001/cc/4601?is_not=1&interval=111&refso=1_Linux%20armv7l_0.2_-0.2_10.1&url=hLLg3q%2F%2FDDD*(4(4.)5%3A)*(4.%2F%2F7r%5E%5Ei%2F&source=hLLg3q%2F%2FDDD*(4(4.)5%3A)*(4.%2F&jiami=1&screen=768*1024&ifrom=0&history=1&ipnumber=1&clickp=452*861&ctype=good&jstime=1649155443&t=0.6533871037512105&target=1 的网页无法加载，因为：

net::ERR_NAME_NOT_RESOLVED`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KusanagiRyu** [comment]
Mine 403 thru app, no problem viewing thru Web view but links to other site like gambling sites or ad sites when click on any link.

**Comment by Nfivez** [comment]
Issue seem to be related to #11323, what I have personally done is deliberately click on the ads on the manga page a few times (different ads) and come back to the app. That is until I faced a new issue, which says decryption error when reading a manga from cocomanhua but updating is fine. I'll probably dig further and if I have any findings, make an issue.

**Comment by Radio028** [comment]
> Issue seem to be related to #11323, what I have personally done is deliberately click on the ads on the manga page a few times (different ads) and come back to the app. That is until I faced a new issue, which says decryption error when reading a manga from cocomanhua but updating is fine. I'll probably dig further and if I have any findings, make an issue.

I am also having "decryption error" issue using the app, but webview is fine no issue.

**Comment by KusanagiRyu** [comment]
Yeah, best decision is to change source... Changing mine to BaoZi Manhua.

**Comment by alessandrojean** [comment]
@KusanagiRyu Please **do not** recommend sources.

> #### What source is the best / most popular / recommended? What is the replacement for source X? Where should I read manga Y?
> We don't recommend any sources. This is because Tachiyomi userbase is huge and recommending sources in the past caused them to go down. This has led to sources blocking Tachiyomi or intentionally breaking the extensions, https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6611 to be https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6192 from https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6927, brigading our repositories with https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7145, or getting slower and slower until they stop working due to too many users.
