### ISSUE TITLE
Akashi-deep

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi-extensions#11331]
### Source name

Aresmanga

### Source link

https://aresmanga.com/

### Language

Arabic and English 

### Other details

![Screenshot_20220404-153810_Chrome](https://user-images.githubusercontent.com/102795903/161580373-4100f605-554e-4931-b121-46cf2af7dc1c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
It already exists, its previous name is iiMANGA and is linked with it currently
