### ISSUE TITLE
Vapo Scan: Changed their theme to Madara

### ISSUE THREAD

**Issue by Diegofsp98** [tachiyomiorg/tachiyomi-extensions#11335]
### Source information

Vapo scan 1.2.16

### Steps to reproduce

No results fount when I click on the scan, but show in web view 

### Expected behavior

Show scan manga

### Actual behavior

Don't show scan manga 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their site seems to be down. Need to wait until it gets online again before changing anything in the extension.

**Comment by Raidre** [comment]
So pra avisar o site da vapo da voltou ao normal
