### ISSUE TITLE
Buon dua: Can't download chapters

### ISSUE THREAD

**Issue by nimma0001** [tachiyomiorg/tachiyomi-extensions#11330]
### Source information

Buon dua 1.21

### Steps to reproduce

Open tachi
Install buon dua 
Open buon dua
And download any album
It stop at 20th page

### Expected behavior

Should download all pages

### Actual behavior

Error at 20th page

### Tachiyomi version

R4513

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Badriluthfi** [comment]
> ### Source information
> Buon dua 1.21
> 
> ### Steps to reproduce
> Open tachi Install buon dua Open buon dua And download any album It stop at 20th page
> 
> ### Expected behavior
> Should download all pages
> 
> ### Actual behavior
> Error at 20th page
> 
> ### Tachiyomi version
> R4513
> 
> ### Android version
> Android 11
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

The answer is because in the website they only show 20 images per page
