### ISSUE TITLE
ReadComicOnline: No pages found

### ISSUE THREAD

**Issue by DuskWulf** [tachiyomiorg/tachiyomi-extensions#11338]
### Source information

ReadComicOnline 1.2.11

### Steps to reproduce

1. Open a comic from the library UI;
2. Try to open an issue/chapter from the list.

### Expected behavior

The issue/chapter would simply open under usual circumstances.

### Actual behavior

Receive the "No pages found" error message.

![Screenshot_20220405_200157_eu kanade tachiyomi](https://user-images.githubusercontent.com/73840890/161830534-105f5206-ceab-4268-8533-401a3dcf311b.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by onorinoDiTanna** [comment]
Same here. Yesterday it was working fine

**Comment by 4lt4n0rd** [comment]
Potentially linked to #9879 and #11240

**Comment by Youssefx00** [comment]
same issue here

**Comment by MoxFulder88** [comment]
It happens to me to but not on every comic. There are a few that works fine.

**Comment by 4lt4n0rd** [comment]
Potentially related to #9879, which was closed in #11240. This problem does persist for issues that *are* available in web view.

**Comment by redmiso** [comment]
Potentially related to #9879, which was closed in #11240. This problem does persist for issues that *are* available in web view.

**Comment by DuskWulf** [comment]
I can confirm that the issues I tested it for—under a handful of comics—were all available in WebView (not deleted) as that's what I've been using to read them in the interim. It should've occurred to me to mention that, sorry.

**Comment by nekomar** [comment]
Yeah, does not work for me as well. Pls fix it :(

**Comment by Devthereader** [comment]
This is my favorite site hope it is up and running soon.
