### ISSUE TITLE
Hiperdex lost genre filter after non-manga entries fix

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#11349]
### Source information

Hiperdex 1.2.23

### Steps to reproduce

check the genre filter, it disappeared

### Expected behavior

the genre list should be in the filter menù

### Actual behavior

there is no genre filter

### Tachiyomi version

0.13.1

### Android version

android 8

### Other details

after the mass update of the non-manga entries the genre filter got removed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's not showing because the genres request is failing because of Cloudflare, and Hiperdex is known for having a higher Cloudflare instance. I will see if I can do anything to fix it, but I wouldn't hope it much.

**Comment by alessandrojean** [comment]
Old version uses other method to get the genres. It's also not recommended to use outdated extensions, we also don't give support to it.
