### ISSUE TITLE
Colored Manga: HTTP error 500

### ISSUE THREAD

**Issue by sgern** [tachiyomiorg/tachiyomi-extensions#11346]
### Source information

Colored Manga 1.2.19

### Steps to reproduce

1. Go to Browse
2. Open Colored Manga

### Expected behavior

The manga list opens.

### Actual behavior

I get the error message "HTTP error 500: Check website in WebView".

### Tachiyomi version

tachyomiJ2K 1.4.4

### Android version

Android 11

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 5xx errors are server side and can't be fixed on the extension. Check if the website is not down by opening it in WebView like the error says you to do.

**Comment by alessandrojean** [comment]
Reopening since it's confirmed to be an extension-side issue somehow.

**Comment by curche** [comment]
Doesn't seem to be happening anymore. Browse works fine maybe sometimes a bit slow
Pages don't seem to load now and a new issue has been created. Refer #11911 
Closing this for now
