### ISSUE TITLE
Scroll Down Issue in 1stkiss

### ISSUE THREAD

**Issue by fuentez145** [tachiyomiorg/tachiyomi-extensions#11343]
### Source information

1st kiss 1.2.25

### Steps to reproduce

1. First step browse 1st kiss
2. Click Filter order by latest
3. The result will be shown but cannot be scroll down or adding more results

### Expected behavior

It should expand all the result when scrolling down after it filtered.

### Actual behavior

Instead it won't scroll down which cause the result can't be expand.

### Tachiyomi version

Stable 0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Should be fixed by #11359.
