### ISSUE TITLE
CoCoManhua: Decryption failed

### ISSUE THREAD

**Issue by Radio028** [tachiyomiorg/tachiyomi-extensions#11345]
### Source information

CoCoManhua(OhManhua) 1.2.10 chinese

### Steps to reproduce

1. Open any comic's chapter or select download chapter from CoCoManhua.

### Expected behavior

When select any chapter it should load the page of the chapter.
When select download it should start downloading. 

### Actual behavior

page closed immediately and showed "decryption failed" message for 1 second without any error code.
Unable to download the chapters after press download. 

### Tachiyomi version

0.13.1

### Android version

Android 8.0.0

### Other details

![Screenshot_20220406-221729](https://user-images.githubusercontent.com/88246894/161995990-2e8c0e2d-2145-455f-992b-f5bdf1658e55.jpg)

I have tried open through webview, there are no issue reading the comics through webview. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Radio028** [comment]
Too bad.... CoCoManhua is quite good updating the chinese comics. 
If someone has difficulty to find new Chinese sourse to replace, you can try baozimanhua.
Or if you have any other better chinese comics sourse please share.
Thank you.

**Comment by alessandrojean** [comment]
Please **do not** recommend sources.

> #### What source is the best / most popular / recommended? What is the replacement for source X? Where should I read manga Y?
> We don't recommend any sources. This is because Tachiyomi userbase is huge and recommending sources in the past caused them to go down. This has led to sources blocking Tachiyomi or intentionally breaking the extensions, [asking](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6611) to be [removed](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6192) from [Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6927), brigading our repositories with [spam](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7145), or getting slower and slower until they stop working due to too many users.

**Comment by tsunaliew** [comment]
Can we create another discord group to discuss chinese source so it will not bring any undesirable situation to taxhiyomi?
