### ISSUE TITLE
Mangame: Changed their domain

### ISSUE THREAD

**Issue by MikeZeDev** [tachiyomiorg/tachiyomi-extensions#11356]
### Source information

Mangame

### Steps to reproduce

All my sources on Mangame arent working when updating i always got no chapter found.

Apparently the website url changed to goodmanga.org, according to their homepage.

### Expected behavior

Updating chapters should be working.

### Actual behavior

N/A

### Tachiyomi version

0.13.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Mangame is working fine with their latest domain https://mangame.org/, we should close this
