### ISSUE TITLE
Readcomicsonline doesn't work 

### ISSUE THREAD

**Issue by Isaac2088** [tachiyomiorg/tachiyomi-extensions#11355]
### Source information

ReadComicsOnline 1.2.11

### Steps to reproduce

1. Go to browse
2. Open ReadComicsOnline
3. Click on any title 
4. Keeps coming up as "pages not found" 

### Expected behavior

I should be able to read them like normally 

### Actual behavior

It just backs out immediately and says "pages not found"

### Tachiyomi version

0.13.1

### Android version

Galaxy S21 5G

### Other details

Literally any other extension I use has worked perfectly, I have wifi issues here and there but they always end up loading in eventually 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#11338
