### ISSUE TITLE
Mangalek: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by 9MoIssam9** [tachiyomiorg/tachiyomi-extensions#11366]
### Source information

مانجا ليك:  1.2.20

### Steps to reproduce

1-Open app
2-Go to browse
3-Select مانجا ليك source
4-manga list appears
5-select any manga/manhwa
6-the chapters appear
7-when I select a chapter to read an error pops up (failed to bypass cloudflare) 

### Expected behavior

The chapter should open normally

### Actual behavior

An Error pops up (failed to bypass cloudflare)

### Tachiyomi version

 0.13.1 

### Android version

Android 11

### Other details

I tried مانجا ليك source with other device and it works perfectly but at my device(Samsung m51) it doesn't

I tried all the solutions that are at troubleshooting but no result

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ig4e** [comment]
+1 poco x3 pro

**Comment by BLACKxSUN** [comment]
Same bro in 1.2.16 it have been work sometimes and some not but now no chapter work

**Comment by GTO212** [comment]
نفس المشكلة عندي

**Comment by CHAOSX0** [comment]
same

**Comment by XOCV0** [comment]
Same bro

**Comment by Saud-97** [comment]
The current available workaround is by clearing webview data, another possible solution is https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11685 but that is unconfirmed if it would be implemented in future.

**Comment by CHAOSX0** [comment]
> The current available workaround is by clearing webview data, another possible solution is #11685 but that is unconfirmed if it would be implemented in future.

clearing webview data doesn't even work for me...

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
