### ISSUE TITLE
HanumanScan

### ISSUE THREAD

**Issue by 3DaXean** [tachiyomiorg/tachiyomi-extensions#11373]
### Source name

HanumanScan

### Source link

Hanumanscan.com

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader theme

**Comment by 3DaXean** [comment]
May I know how long does this usually take?

**Comment by FourTOne5** [comment]
> May I know how long does this usually take?

0s ~ ∞s. This'll get added when someone adds it no eta.

**Comment by 3DaXean** [comment]
> 

Thanks for the info. So there is a chance of not getting added at all.

**Comment by FourTOne5** [comment]
> > 
> 
> Thanks for the info. So there is a chance of not getting added at all.

Yes
