### ISSUE TITLE
MangaDenizi extention doesn't work

### ISSUE THREAD

**Issue by glaicodes** [tachiyomiorg/tachiyomi-extensions#11378]
### Source information

MangaDenizi 1.2.4

### Steps to reproduce

Install mangadenizi extension
Open "latest"

### Expected behavior

It should open "latest" 

### Actual behavior

![Screenshot_2022-04-08-11-32-40](https://user-images.githubusercontent.com/75806392/162411995-f0a44a6f-4cd2-4b5d-bf9f-669299db9229.png)

### Tachiyomi version

0.13.1

### Android version

Android 6

### Other details

I asked this in their discord, and they said they updated their SSL, maybe that's why. Also, you should get the permission from MangaDenizi staff. They don't like people using their work without permission. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
First, this is an issue with their certificate and we can't really fix it, it's up to them. Second, never mention Tachiyomi or the extensions to site owners. Third, we don't need any permission because we are not stealing and neither using their work, we are not an aggregator and Tachiyomi is just a fancy browser.
