### ISSUE TITLE
Webtoon TR : Missing chapters

### ISSUE THREAD

**Issue by SpaceSemih** [tachiyomiorg/tachiyomi-extensions#11371]
### Source information

Webtoon TR v1.2.19

### Steps to reproduce

1. open browse
2. click Webtoon TR extension
3. search and click "Mercenary Enrollment" in Webtoon TR extension.

### Expected behavior

For example you can search : "Mercenary Enrollment" in Webtoon TR extension. There should have been 0 chapter (as it is in browser)

### Actual behavior

However when you click: "Mercenary Enrollment" in Webtoon TR  extension. There is only 0 chapter

### Tachiyomi version

0.13.1 (1.02.2022 20:35)

### Android version

Android 11

### Other details

No response

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MrBasri** [comment]
i have too. extension version v1.2.20. it said no chapters found on any manga page.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
