### ISSUE TITLE
Doki1001

### ISSUE THREAD

**Issue by Xanokei** [tachiyomiorg/tachiyomi-extensions#11386]
### Source name

Doki 1001 

### Source link

https://doki1001.com/

### Language

Japanese

### Other details

This is manga1001 another new site, seems to be much cleaner and more refined then the previous sites.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by shoyaya** [comment]
It's different from Madara theme because it also has old chapters of jp mangas. Please reconsider to open this thread

**Comment by Xanokei** [comment]
site dead
