### ISSUE TITLE
Gatemanga: Failed to load image

### ISSUE THREAD

**Issue by hani19998** [tachiyomiorg/tachiyomi-extensions#11387]
### Source information

Gatemanga 1.2.20

### Steps to reproduce

Entry to the manga chapter

### Expected behavior

Open the manga chapter pictures

### Actual behavior

Class photos are not open

![Screenshot_20220408-192041](https://user-images.githubusercontent.com/100415641/162484200-58aa8c28-732f-456a-883b-68e5b96e58b0.png)

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
