### ISSUE TITLE
Remanga: HTTP error 400

### ISSUE THREAD

**Issue by SannoV** [tachiyomiorg/tachiyomi-extensions#11408]
### Source information

Remanga 1.2.47

### Steps to reproduce

When I try to open the manga list in the app, error 400 appears. Such an error exists only on this resource, and in webview the site is fully functional.
![Screenshot_2022-04-09-17-19-40-604_eu kanade tachiyomi](https://user-images.githubusercontent.com/45595167/162579190-006c8c38-a167-42cc-90db-78612aa850eb.jpg)
![Screenshot_2022-04-09-17-19-50-098_eu kanade tachiyomi](https://user-images.githubusercontent.com/45595167/162579192-d8c0a95b-0ce2-473a-8873-b0e7e2451d53.jpg)

### Expected behavior

A list of the latest updated manga or the top manga on the resource should open.

### Actual behavior

Instead, the error 400 always appears.

### Tachiyomi version

0.13.1

### Android version

Andriod 11

### Other details

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: surya
Device model: M2007J20CG
Device product name: surya_eea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
![Screenshot_2022-04-09-21-30-23](https://user-images.githubusercontent.com/63583961/162587132-1323d729-4111-4bb6-a977-119818869be2.png)
![Screenshot_2022-04-09-21-30-18](https://user-images.githubusercontent.com/63583961/162587137-2c9e907d-a71f-4ddf-8a71-72cca02df6c8.png)

**Comment by SannoV** [comment]
Everything works for me. I suppose this is related to the country from which the connection takes place? Since it works only in Russia as a resource for Russian speakers?
![Screenshot_2022-04-09-22-48-41-696_com yandex browser](https://user-images.githubusercontent.com/45595167/162589575-9a23bfcf-3786-477e-9a09-d2c546a6f531.jpg)

**Comment by SannoV** [comment]
I tried to use a vpn to access the site. The same error as yours appeared only when trying to log in using the USA.

**Comment by RaCc0oN1** [comment]
Ф
Anu fix?

**Comment by SannoV** [comment]
![Screenshot_2022-04-19-22-24-59-287_eu kanade tachiyomi](https://user-images.githubusercontent.com/45595167/164080345-e557bf75-a289-4658-a22e-d175667f1074.jpg)
Now the error has changed to this.😭

**Comment by e-shl** [comment]
> error 400

it was a breakdown on the website


> Теперь ошибка изменилась на это

and/but this site fixed the breakdown
