### ISSUE TITLE
Doujindesu change Domain

### ISSUE THREAD

**Issue by HikariHeaven** [tachiyomiorg/tachiyomi-extensions#11401]
### Source information

DoujinDesu vers. 1.2.2

### Steps to reproduce

1. Open Doujindesu extension, and can't access in normal
2. Just appeared text "212.32.226.234: NXDOMAIN"
3. Just access use open in WebView

### Expected behavior

This should happen to able access to Doujindesu in normal mode, but can't do it and just appeared "212.32.226.234: NXDOMAIN"

### Actual behavior

this happens instead of changing the original domain from doujindesu.xxx to domain 212.32.226.234

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

![Screenshot_2022-04-09-12-15-58-26_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/61365229/162557628-f6a3fa56-87e0-41bb-a691-5434c3b6dec1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZekkenID** [comment]
Sama issuenya seperti #10783

**Comment by HikariHeaven** [comment]
> Sama issuenya seperti #10783

Thank you..
Nice info.. so we have to turn off DoH in Tachiyomi settings, but we have to use a VPN, if we want to access, because doujindesu is detected as a banned web in Indonesia, fck off kominfo

**Comment by HikariHeaven** [comment]
Well... If you have a problem similar like me, the extension problem with NXDOMAIN error, you can turn off a DoH in Tachiyomi Setting, and use a VPN too.. so you can access that ext again.. Try it👍
