### ISSUE TITLE
Readcomiconline Doesn't load the comic pages when clicking retry 

### ISSUE THREAD

**Issue by UnholyNHoly** [tachiyomiorg/tachiyomi-extensions#11406]
### Source information

Readcomiconline 1.2.12

### Steps to reproduce

When I click retry the pages won't load.
All the comics on the extension does the same it won't load the pages

### Expected behavior

Can fix this new update of the extension problem? 

### Actual behavior

![Screenshot_20220409_215620_eu kanade tachiyomi](https://user-images.githubusercontent.com/103320865/162577392-5fbcbed6-85a3-4283-a720-57f00ee6333f.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheWrightStuff1994** [comment]
Please don't rid of this extension have over 9,000 comics from them I just can't redo them all!

**Comment by arkon** [comment]
Unless someone is willing to submit and maintain fixes for it, there's no point in keeping a broken source around.

**Comment by TheWrightStuff1994** [comment]
> Unless someone is willing to submit and maintain fixes for it, there's no point in keeping a broken source around.

Well is there a mass migrate way for me to transfer all my comics faster?

**Comment by FourTOne5** [comment]
Not in the main app.

**Comment by TheWrightStuff1994** [comment]
> Not in the main app.
So there is no way to mass migrate at all?

**Comment by curche** [comment]
Refer to https://github.com/tachiyomiorg/tachiyomi/issues/1729
OR check the guide https://tachiyomi.org/help/guides/source-migration/

**Comment by UnholyNHoly** [comment]
Is there any extension similar to readcomiconline? Because the comicextra is having the same issue too

**Comment by TheWrightStuff1994** [comment]
> Is there any extension similar to readcomiconline? Because the comicextra is having the same issue too

XOXO Comics I think you what you want.

**Comment by arkon** [comment]
We do not allow source recommendations to avoid high levels of redirected traffic and subsequently edging them to adopt anti-user changes.
