### ISSUE TITLE
Doujindesu

### ISSUE THREAD

**Issue by Daniii-weabo** [tachiyomiorg/tachiyomi-extensions#11411]
### Source information

Diujindesu.xxx

### Steps to reproduce

Open Doujindesu extension, and can't access in normal
Just appeared text "212.32.226.234: NXDOMAIN"
Just access use open in WebView

### Expected behavior

This should happen to able access to Doujindesu in normal mode, but can't do it and just appeared "212.32.226.234: NXDOMAIN"

### Actual behavior

this happens instead of changing the original domain from doujindesu.xxx to domain 212.32.226.234

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
This bug is the same as #11401
