### ISSUE TITLE
Manga mutiny not working

### ISSUE THREAD

**Issue by lobhas99** [tachiyomiorg/tachiyomi-extensions#11418]
### Source information

Manga Mutiny 1.2.8

### Steps to reproduce

1.Go to Browse
2.Source->Manga Mutiny

### Expected behavior

It should Show manga it has 

### Actual behavior

timeout

### Tachiyomi version

0.13.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If you open WebView, you will see their site is down, so nothing that can be done on the extension side.
