### ISSUE TITLE
Empire Webtoon: HTTP error 400

### ISSUE THREAD

**Issue by euijoonyeo** [tachiyomiorg/tachiyomi-extensions#11426]
### Source information

Empire Webtoon 1.2.20

### Steps to reproduce

the extension not working it used to be normally working but before 2 weeks it stops

### Expected behavior

.

### Actual behavior
I installed extension "Empire webtoon" normally but when I enter to the source for navigating it says: "HTTP error 400: check website in webview"

### Tachiyomi version

0.13.1

### Android version

7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please be more specific about what is not working and provide the errors you're getting.

Fill the fields correctly with the information requested, too.

Closing since it doesn't provide enough info.

**Comment by euijoonyeo** [comment]
> Please be more specific about what is not working and provide the errors you're getting.
> 
> Fill the fields correctly with the information requested, too.
> 
> Closing since it doesn't provide enough info.
I'm sorry.
I installed extension "Empire webtoon" normally but when I enter to the source for navigating it says: "HTTP error 400: check website in webview"

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
