### ISSUE TITLE
Comiconlinefree.net

### ISSUE THREAD

**Issue by Ehssank** [tachiyomiorg/tachiyomi-extensions#11424]
### Source name

Comiconlinefree

### Source link

https://comiconlinefree.net/

### Language

English

### Other details

Seems to have a Nice mix of older and newer Western comics that are now sorely needed after The removal of the readcomiconline extension. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
False alarm. Reopened and shouldn't get closed.

**Comment by dickyharper** [comment]
+1
I found Hellblazer at this address after ReadComicsOnline was deleted. I hope the Extension can be made.

**Comment by Silksbian** [comment]
i really hope someone can do this, all the other comic sources on tachiyomi suck

**Comment by StephenTheMoldovan** [comment]
please someone add this.
some comics that just return empty pages when I look them up on ComicExtra show up fine on this site.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
