### ISSUE TITLE
Readmanhwa Issue: Missing / in links. 

### ISSUE THREAD

**Issue by PolarboiY** [tachiyomiorg/tachiyomi-extensions#11429]
### Source information

Readmanhwa.com: 1.2.11

### Steps to reproduce

dont know

### Expected behavior

This should happen
Readmanhwa.com/(Manwha/Manga title with -) 

### Actual behavior

But what happend is basically
Readmanhwa.com(Manwha/Manga title) no /, causing it to not refresh properly and causes it to ignore refreshing it. 

### Tachiyomi version

0.13.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
any specific example? It works for me, although some chapters on some mangas are broken (even when accessed via browser)
