### ISSUE TITLE
MangaDig: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Beji-kun** [tachiyomiorg/tachiyomi-extensions#11437]
### Source information

MangaDig 1.2.2 english

### Steps to reproduce

1-Open app
2-Go to browse
3-Select source MangaDig
4-manga list appears
5-select any manga/manhwa
6-the chapters appear
7-when I select a chapter to read an error pops up (failed to bypass cloudflare)

### Expected behavior

The chapter should open normally

### Actual behavior

An Error pops up (failed to bypass cloudflare or deception failed). Imao
Try on this https://mangadig.com//16203/ and other Manga same problem

### Tachiyomi version

0.13.2

### Android version

Android 11 (Poco x3 pro)

### Other details

I try change DNS to Google, cloudflare. Nothing works on wifi and 4g connection  
There's video screen record with showing problem
[Screen record of problem](https://drive.google.com/drive/folders/111TjWRN6LdogdaiivLhBYL0YErAr1ZOU) 
![Screenshot_2022-04-12-04-22-11-257_eu kanade tachiyomi](https://user-images.githubusercontent.com/63636174/162866626-7f309585-73f7-43eb-b363-9e97283c499c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Beji-kun** [comment]
![Screenshot_2022-04-12-04-24-39-839_eu kanade tachiyomi](https://user-images.githubusercontent.com/63636174/162866822-3b2206b9-f9ec-46d1-bbaa-1d1bfda17648.jpg)

**Comment by Beji-kun** [comment]
Hey I wanna ask is there some solution or still not? Thanks for letting me know. 🙂

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
