### ISSUE TITLE
Manga Soul

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#11442]
### Source name

Manga Soul 

### Source link

https://www.manga-soul.com/?m=1

### Language

Arabic 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses ZeistManga v4, which is new to Tachiyomi

**Comment by shipoxx** [comment]
Closed

This website is not public you need to be in Patreon to unlock chapters !


Announcement:

[IMG_20220830_132020.jpg](https://user-images.githubusercontent.com/61906880/187435145-3704726f-999f-44d5-94a1-31ebff21fb33.jpg)

"You need to be in Patreon to unlock +18 chapters".

**Comment by shipoxx** [comment]
Closed

This website is not public you need to be in Patreon to unlock chapters !


Announcement:

[IMG_20220830_132020.jpg](https://user-images.githubusercontent.com/61906880/187435145-3704726f-999f-44d5-94a1-31ebff21fb33.jpg)

"You need to be in Patreon to unlock +18 chapters".

    @arkon sorry for ping but can you please close this issue (why above)
