### ISSUE TITLE
An extension that allows connection to an smb server or NAS

### ISSUE THREAD

**Issue by Heavyarms04** [tachiyomiorg/tachiyomi-extensions#11443]
### Describe your suggested feature

It would be perfect if some extension could act as an intermediary between tachiyomi and a smb server or a NAS without having to have a pc turned on all day, I know that there is konga but its problem is that I need to have the pc turned on and that access to the files can take more than 15 minutes after being downloaded to be reflected,  In addition 
There are comic applications that directly access the NAS servers smb and even hard drives connected to your router directly, I really hope that an extension of this style can be developed, unfortunately I do not have the knowledge to carry it out, if someone can help me either by creating it or instructing in its way of elaboration I would appreciate it

PS: I apologize for my lousy English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I'm confused you can install komga on your NAS, 

https://github.com/tachiyomiorg/tachiyomi/issues/6423

**Comment by ObserverOfTime** [comment]
Wouldn't it be possible to mount `Tachiyomi/local` as a SMB share and use it that way?

**Comment by loocool2** [comment]
Yes, we've confirmed users are able to mount and use a SMB share with a external app with both downloads and local as long as permissions are set up correctly
