### ISSUE TITLE
MangaBuddy: HTTP error 429

### ISSUE THREAD

**Issue by AlbertoPravisano** [tachiyomiorg/tachiyomi-extensions#11441]
### Source information

MangaBuddy (EN) 1.2.6

### Steps to reproduce

Updating library

### Expected behavior

All mangas are updated

### Actual behavior

Some mangas couldn't be updated

### Tachiyomi version

0.13.2

### Android version

Android 11

### Other details

I submitted the issue as stated in https://tachiyomi.org/help/guides/troubleshooting/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
aka stop slamming the source.  we can't control poor practices.  Though rate limiting should be added so this can be prevented some.
