### ISSUE TITLE
COCO漫画真就只能废弃了么？有没有办法在插件设置里让用户修改图片的密匙延长它寿命

### ISSUE THREAD

**Issue by strbug** [tachiyomiorg/tachiyomi-extensions#11454]
### Describe your suggested feature

目前我个人观察的中文国产漫画源了，网站自己花钱扒正版更新得及时的就是coco漫画和包子漫画。而包子漫画反人类的图片水印，极大的破坏条漫阅读体验。国产漫画目前盗扒第一巨头就是这个coco漫画了，真的只能废弃么？少了这个源，其他源要么更新慢，要么有些断更，体验很差。还是说coco漫画这网站不止换密匙，还会换算法，所以用户修改也不现实？

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
CoCo漫画被除掉了，因为他们把网页地址加密方法和加密钥匙一直改变。改来改去到我们修完一次他们已经不一样的加密算法。这给我们带了太的障碍，就决定除掉。回来的可能性很小。现在需要移民到别的网站去
