### ISSUE TITLE
Copymanga: Chapter images do not load

### ISSUE THREAD

**Issue by Sean1781031** [tachiyomiorg/tachiyomi-extensions#11467]
### Source information

Copymanga 1.2.24

### Steps to reproduce

1.open any manga chapters 
2.stuck at loading

### Expected behavior

images should load

### Actual behavior

stuck at loading forever
![Screenshot_20220415-005023_Tachiyomi](https://user-images.githubusercontent.com/68652201/163436372-99dab678-16cd-4271-ade5-c93ee241bbfe.png)
![Screenshot_20220415-005005_Tachiyomi](https://user-images.githubusercontent.com/68652201/163436380-328d47aa-8fca-405c-83de-e9d612c8779d.png)

### Tachiyomi version

0.13.2

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
This chapter also doesn't load for me. I also try viewing it from the website, and if I choose "大陆用户线路", images don't load, but if I choose "港台及海外线路", images load successfully.
In the extensions settings, there is an option to use overseas CDN, but this is not working properly. Their API has a header "region" for setting the region. Maybe it should be used to get image urls.
