### ISSUE TITLE
Manhwa18: No results found

### ISSUE THREAD

**Issue by TimoLS9921** [tachiyomiorg/tachiyomi-extensions#11466]
### Source information

Manhwa18 V1.2.8

### Steps to reproduce

1. Open the extension
2. Search for something (I searched for "three")
3. Upon searching a white box appears at the bottom of the screen saying "No results found" and a retry button. (I had two hits when searching for "three" but it still said no results were found so there is something wrong.

### Expected behavior

Show matching manga/manhwa/manhua without saying no results Found when finding results

### Actual behavior

Shows the manga/manhwa/manhua but also gives the "No results found" error even when there are matches.

### Tachiyomi version

App version: 1.8.1 (standard, d21dac8a2, 32, 2022-04-09T23:42Z) Preview build: 448

### Android version

Android version: 11 (SDK 30)

### Other details

![Screenshot_20220414-173925](https://user-images.githubusercontent.com/67267822/163426405-daffef5b-7805-4576-ba2d-6c51455c89e3.jpg)

I know that I have written that I've updated the app to version 0.13.2 but as I'm using the SY extension this isn't the case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Which manhwa18? There are at least 5 different plugins (.com, .net, cc, etc)

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
