### ISSUE TITLE
xkcd: title text does not support unicode

### ISSUE THREAD

**Issue by keinezeit8** [tachiyomiorg/tachiyomi-extensions#11465]
### Source information

xkcd 1.2.12

### Steps to reproduce

The comic from April 13ᵗʰ 2022 (https://xkcd.com/2606/) has an Unicode character in its title text. This is not being displayed, as seen below.

### Expected behavior

U+2A0B ⨋ Mathematicians need to calm down

### Actual behavior

![xkcd - 2606 - Weird Unicode Math Symbols - 2](https://user-images.githubusercontent.com/59264615/163418443-3787aa97-cd81-4a52-919c-d166abc2465f.png)

### Tachiyomi version

0.13.2-4242

### Android version

10 (SDK 29)

### Other details

I don't know if this is even worth patching, as it is a very rare edge case, but I wanted to mention it.
At least if it wont be fixed, this issue can be referenced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ringosham** [comment]
This is an upstream issue with fakeimg.pl which generates the text image

Side note it doesn't work with emojiis either
