### ISSUE TITLE
Latest Manga: Changed their domain

### ISSUE THREAD

**Issue by thedeadone68** [tachiyomiorg/tachiyomi-extensions#11471]
### Source information

latest manga version 1.2.2.1

### Steps to reproduce

i  just taped on it under  soures  and  it says failed to connect to  latestmanga.net/75.2.18.233 (port 443)

### Expected behavior

to show what thay have to read 

### Actual behavior

buffers for a minute then  it says failed to connect to  latestmanga.net/75.2.18.233 (port 443)

### Tachiyomi version

stable 0.13.2

### Android version

android 10

### Other details

i tryed it on my pc and  could not find the web sit but i found a web site for it thats https://latest-manga.com/                                    this url   but idk if its the same site 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Original domain has expired
