### ISSUE TITLE
loops with cloudflare in extensions

### ISSUE THREAD

**Issue by JavierAguilar1164** [tachiyomiorg/tachiyomi-extensions#11472]
### Source information

Tumangaonline, lectormanga

### Steps to reproduce

tumangaonline and readermanga extensions don't work because they get stuck in cloudflare

### Expected behavior

I should be able to update or be able to read the manga chapters of those extensions

### Actual behavior

It shows all the time http error 403 and when trying to view the extension page it stays in a loop with cloudflare

### Tachiyomi version

0.13.2

### Android version

Android 11

### Other details

![Screenshot_2022-04-15-02-17-54-689_eu kanade tachiyomi](https://user-images.githubusercontent.com/73663740/163529772-04db0704-c8ac-4378-a8ee-bd2edecc0070.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
These sources are well known for having a higher Cloudflare protection, and we don't really control its behavior. If opening in WebView didn't fix it, nothing you can do. We recommend migrating to better sources.

Also, in the next time, open one ticket per source.
