### ISSUE TITLE
Gekkou Scans: No pages found

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#11489]
### Source information

Gekkou Scans 1.2.15

### Steps to reproduce

Open: Chapter 125 https://gekkou.com.br/manga/secret-class or Chapter 112 https://gekkou.com.br/manga/stepmother-friends

### Expected behavior

load the Chapter

### Actual behavior

no pages found

### Tachiyomi version

0.13.2

### Android version

A11

### Other details

both chapters were reuploaded, maybe this is related with problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's because they're hosting their NSFW on other domain, so a separate extension needs to be created instead.

The current one is working correctly because in their normal domain, the examples provided really [doesn't have any pages](https://gekkou.com.br/manga/secret-class/125v2/1).
