### ISSUE TITLE
Local Source - No manga appearing

### ISSUE THREAD

**Issue by a1223334444** [tachiyomiorg/tachiyomi-extensions#11483]
### Source information

Local Source

### Steps to reproduce

1. Open Local Source

### Expected behavior

Manga should appear

### Actual behavior

There is nothing, but a sign that says no results found.

### Tachiyomi version

0.13.3

### Android version

Android 12

### Other details

![Screenshot_20220416-105835_My Files](https://user-images.githubusercontent.com/103804070/163660608-49c8d424-1840-41eb-a3f9-e2f8e8b002b2.jpg)
![Screenshot_20220416-105908_My Files](https://user-images.githubusercontent.com/103804070/163660611-574c751d-6b70-4016-8ca4-fd650ce3763d.jpg)
![Screenshot_20220416-105911_My Files](https://user-images.githubusercontent.com/103804070/163660612-88a64f97-6918-4a26-ab5b-963719e5f265.jpg)
![Screenshot_20220416-110023_Tachiyomi](https://user-images.githubusercontent.com/103804070/163660620-28277846-7efa-4a95-9a6f-e0cda206b92d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Make sure to follow the [guide](https://tachiyomi.org/help/guides/local-manga/) strictly.

It should be `/Tachiyomi/Local` and not `/Tachiyomi/downloads/Local` as it is in your screenshot.
