### ISSUE TITLE
Fakku.cc

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#11486]
### Source name

Fakku.cc

### Source link

https://fakku.cc/

### Language

English

### Other details

![Screenshot_2022-04-16-17-48-12-75](https://user-images.githubusercontent.com/79831076/163670396-f49e56dd-870a-4db4-9a83-5bb9e292b0e7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
No nsfw screenshots. Use the lanraragi extension to access it.

**Comment by conztanz045** [comment]
> No nsfw screenshots. Use the lanraragi extension to access it.

Im sorry 🙇🙇🙇
