### ISSUE TITLE
Mangagg: Not showing all manga

### ISSUE THREAD

**Issue by Brainlessmonke** [tachiyomiorg/tachiyomi-extensions#11491]
### Source information

Mangagg 1.2.22

### Steps to reproduce

1. Open mangaGG
2. Search for "i can copy talents"/"heavenly demon cultivation simulation" and other 

### Expected behavior

Shows the manga/manhwa that you're searching for 

### Actual behavior

Nothing shows up except certain manga

### Tachiyomi version

0.13.3

### Android version

Android 12

### Other details

It also happened to my other phone which has android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Does it shows if you disable the "Show only manga entries" filter?

**Comment by Brainlessmonke** [comment]
Yes thanks for the help🤦‍♂️

**Comment by alessandrojean** [comment]
So they're marking manga titles as novels or videos, the extension needs to skip the filtering. Will reopen the issue since it can affect more users.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
