### ISSUE TITLE
Newtoki update

### ISSUE THREAD

**Issue by GamingMajd** [tachiyomiorg/tachiyomi-extensions#11502]
### Source name

newtoki

### Source link

https://newtoki128.com

### Language

Korean

### Other details

This is the new site of newtoki please update it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
From the Discord server

> Can't browse Korean sources
> Some Korean sources use numbered domains that changes every 7 to 10 days to avoid being shut down. While there is not a permanent fix you can use, you can go to the settings for the extension and change the domain to what's currently used.

> For Example
> Changing the override from `newtoki62.com` to `newtoki68.com` in your extensions settings.

Can reopen in the (rare) case that this doesn't work
