### ISSUE TITLE
Gekkou Scans: No chapter found

### ISSUE THREAD

**Issue by thanosluyang** [tachiyomiorg/tachiyomi-extensions#11525]
### Source information

Gekkou Scans 1.2.16

### Steps to reproduce

1: Update, not all, some manga from library or directly from extension, like Asmodeus or Secret Class.

### Expected behavior

Chapters should be loaded. Webview is working.

### Actual behavior

Shows the message "No chapter found".

### Tachiyomi version

0.13.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
These chapters are in the other website of them. You need to migrate to the other extension.

You can check it by opening in WebView and seeing the URL is from the other domain they have.

**Comment by thanosluyang** [comment]
@alessandrojean Ok, I saw this, but what other extension, even after the update this extension isn't working.

**Comment by alessandrojean** [comment]
The extension for their hentai website, Gekkou Hentai. You shouldn't be able to read these titles in the main extension, it's the intended behavior.
