### ISSUE TITLE
Nude-Moon: Error during HTML parsing

### ISSUE THREAD

**Issue by PerfektNothing** [tachiyomiorg/tachiyomi-extensions#11526]
### Source information

Nude-Moon 1.2.8

### Steps to reproduce

I have been trying to open a source for a very long time, it always gives the same error, I am authorized through webview. Shows a similar error when trying to open any title.
![Screenshot_20220419_223855](https://user-images.githubusercontent.com/68145742/164083154-5feea331-70e0-44d2-ac91-00c06e2f21bf.jpg)
![Screenshot_20220419_223812](https://user-images.githubusercontent.com/68145742/164083312-ec61087f-cf6a-4040-b7df-976cca76494b.jpg)

### Expected behavior

Title opening

### Actual behavior

Error

### Tachiyomi version

0.13.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MM001-r** [comment]
This mistake is about six months old, maybe a little more... 
Hope to fix
