### ISSUE TITLE
Scylla Scans: Missing manga information

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#11533]
### Source information

Scylla Scans 1.2.5

### Steps to reproduce

1. Open Scylla Scans
2. Search: Marriage of Convenience

### Expected behavior

Show description and tags

### Actual behavior

Tags and description doesn't show and "unknown error" popup
![20220419_202307](https://user-images.githubusercontent.com/59638889/164125465-a715a46f-a9a6-43ea-ba7e-cb2546605b99.jpg)

### Tachiyomi version

J2k 1.4.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
caused by genre not listed in `MapOf` (translate genre thing)
maybe should ignore genre if not on the list
@ObserverOfTime
