### ISSUE TITLE
Mangadex: No chapters found on specific manga

### ISSUE THREAD

**Issue by Tau5** [tachiyomiorg/tachiyomi-extensions#11539]
### Source information

Mangadex 1.2.158

### Steps to reproduce

1. On Tachiyomi, browse in the Mangadex (English) extension for "One Piece"
2. Open the first result ("One piece", should be this [item](https://mangadex.org/title/a1c7c817-4e59-43b7-9365-09675a149a6f/one-piece))

### Expected behavior

The chapters available on the language should be shown

### Actual behavior

Even though there are plenty of chapters available for this item in english, the extension reports that no chapters were found

### Tachiyomi version

0.13.3

### Android version

Android 12L

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Externally linked chapters are not shown by design.  If you want to read those use the Manga Plus extension
