### ISSUE TITLE
MangaHere Thumbnails and Chapters Do Not Load

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi-extensions#11535]
### Source information

MangaHere 1.2.17

### Steps to reproduce

1. Go into browse or latest
2. Select a manga
3. Select any chapter
4. Wait for the images to load

### Expected behavior

Pages should load
Thumbnails should load

### Actual behavior

Pages return "The image could not be loaded"
Thumbnails are the broken paper icon

### Tachiyomi version

0.13.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SCrocky** [comment]
Issue confirmed on my device, version v0.13.3

**Comment by Hexahedron3BLD** [comment]
Issue confirmed on my Android 12 device, Tachiyomi version v0.13.3, Mangahere Extension version 1.2.17

**Comment by Akazotik** [comment]
Issue confirmed on my Miui 13, Android 12 device, Tachiyomi version r4266, Mangahere Extension version 1.2.17
