### ISSUE TITLE
iiManga: Source name and cover image must be changed.

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi-extensions#11532]
### Source information

iiManga (AR) v1.2.13

### Steps to reproduce

![image](https://user-images.githubusercontent.com/39028181/164122180-fb634a36-8676-4ed2-a848-67f1b14bd839.png)

This source name has changed from iiManga to **[ARESManga](https://aresmanga.com/)**

### Expected behavior

The extension package and name and picture must be changed.

### Actual behavior

The extension website URL has **changed** but the **name** wasn't changed.

**Comment by saud-97** [comment]
Also the source picture must be changed, I forgot to mention this.

**Comment by saud-97** [comment]
I noticed that updating the manga page doesn't work. But updating the manga from the global update will work normal. Not sure why.

**Comment by saud-97** [comment]
I think the update is bugged because it can't update the cover image correctly?
