### ISSUE TITLE
Zinchanmanga: HTTP error 429

### ISSUE THREAD

**Issue by euijoonyeo** [tachiyomiorg/tachiyomi-extensions#11545]
### Source information

zinchanmanga

### Steps to reproduce

1. I opened the app
2. I click update 
3. the issue is update failed tap here to see details, after tapping the details it appears to be HTTP error 429

### Expected behavior

It should update the list of manga normally 

### Actual behavior

this happened instead: upadate failed "HTTP error 429"

### Tachiyomi version

0.13.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Source has some draconian settings 
```
{
    "message": "10 per 1 minute"
}
```
