### ISSUE TITLE
Neox scanlator BR problem 404

### ISSUE THREAD

**Issue by Ky0jin** [tachiyomiorg/tachiyomi-extensions#11544]
### Source information

Neox scanlator 1.2.29

### Steps to reproduce

I'm getting 404 trying to read whatever content from neox scanlator 

### Expected behavior

It should work properly

### Actual behavior

I'm getting 404 error

### Tachiyomi version

0.13.3

### Android version

MIUI 13.0.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They change the URLs of the titles every few days and there's nothing we can do to fix this. You should migrate these titles from Neox to Neox to update the URL or just migrate to better sources that doesn't have this behavior.
