### ISSUE TITLE
Pin Button

### ISSUE THREAD

**Issue by Ryuto77** [tachiyomiorg/tachiyomi-extensions#11555]
### Describe your suggested feature

There Should Be A Pin Button To Pin Some Favourite Manga In Top. It Will Really Help Us To Read Our Favourite Manga Easy And We Can Find Them Quickly From Our List

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No Just Use Categories.
