### ISSUE TITLE
Tsumino: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by ChillyCrimson45** [tachiyomiorg/tachiyomi-extensions#11562]
### Source information

Tsumino 1.2.6

### Steps to reproduce

1. Open Tsumino
2. Loading
3. Failed To Bypass Cloudflare

### Expected behavior

It should open

### Actual behavior

It fails to bypass cloudflare even after using webview

### Tachiyomi version

0.13.3

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
