### ISSUE TITLE
Webnovel: Titles are broken

### ISSUE THREAD

**Issue by Kuro6804** [tachiyomiorg/tachiyomi-extensions#11576]
### Source information

Webnovel 1.2.3

### Steps to reproduce

1. browse Webnovel
2. click on any title

### Expected behavior

shows title normally

### Actual behavior

Once you've clicked on a comic and the cover and description have loaded the title changes from what it should be to the chapter count plus views, publisher and "Read In Library Add to Library".

![Screenshot_20220423-001107_TachiyomiSY](https://user-images.githubusercontent.com/90160508/164802396-0adf2836-661f-40be-b8d8-e416bc716e28.jpg)

### Tachiyomi version

TachiyomiSY Preview r449

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
webnovel.live is ded
