### ISSUE TITLE
Manytoon (Arabic)

### ISSUE THREAD

**Issue by tayani1989** [tachiyomiorg/tachiyomi-extensions#11585]
### Source name

Manytoon

### Source link

https://ar.manytoon.com/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by tayani1989** [comment]
When are you going to add it, please

**Comment by CrepeTF** [comment]
No ETA

**Comment by tayani1989** [comment]
Please 🙏 can you add it please 🥺

**Comment by alessandrojean** [comment]
All chapters are in English and can be accessed at the current existing English extension, so closing it.
