### ISSUE TITLE
MangaLink: Missing chapter upload dates

### ISSUE THREAD

**Issue by Bmswad1** [tachiyomiorg/tachiyomi-extensions#11584]
### Source information

مانجا لينك 1.2.22

### Steps to reproduce

1.Open any manga
2.open webview

### Expected behavior

Dates should match

### Actual behavior

All dates in extension appear as today

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

![Screenshot_20220423-155859_TachiyomiSY](https://user-images.githubusercontent.com/66433732/164909131-702cf7fc-5cf0-4c0c-b7ff-6a3496e9b6dd.jpg)
![Screenshot_20220423-155840_TachiyomiSY](https://user-images.githubusercontent.com/66433732/164909133-79cdb1d7-a9bc-4580-adb3-bf5b93cc8f09.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
