### ISSUE TITLE
MangaLink HTTP error 523 problem

### ISSUE THREAD

**Issue by JSN-Y** [tachiyomiorg/tachiyomi-extensions#11583]
### Source information

MangaLink 1.2.6

### Steps to reproduce

1.open the extension
2.the problem should show up right away

### Expected behavior

what should happen is that the extension open normally

### Actual behavior

![Screenshot_20220423-113620](https://user-images.githubusercontent.com/104008874/164892869-002d36bb-ae36-4c59-b9f3-69e9876b2e58.png)

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
I get a different error, I think they moved have server issues. https://mangalink.org/
![image](https://user-images.githubusercontent.com/39028181/164910658-a2ca6bde-9844-4f48-a2fd-c829dd6cf848.png)
![image](https://user-images.githubusercontent.com/39028181/164910666-362b900f-6116-4b54-9570-216027316790.png)

**Comment by alessandrojean** [comment]
HTTP errors 5xx are server side and can't be fixed on the extension. Most likely their website is having issues.
