### ISSUE TITLE
Sekai Komik: Changed their domain

### ISSUE THREAD

**Issue by Mugenjin07** [tachiyomiorg/tachiyomi-extensions#11587]
### Source information

Sekaikomik 1.2.20

### Steps to reproduce

Please update the domain

### Expected behavior

Should be able to open if the domain is updated to sekaikomik.live
![Screenshot_20220424-024453_Opera](https://user-images.githubusercontent.com/82618225/164939916-2c963fcf-dcf9-42bc-a8dd-723b0995afa0.png)

### Actual behavior

![Screenshot_20220424-024651_Tachiyomi](https://user-images.githubusercontent.com/82618225/164940331-a635b141-40e9-45e7-aca1-addf11d77459.png)
![Screenshot_20220424-024653_Tachiyomi](https://user-images.githubusercontent.com/82618225/164940351-f287bbd3-98e4-42dd-b2b3-096192cf6cf6.png)
I can't open even though I'm using webview

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

The problem will be solved if the domain is changed to Sekaikomik.live

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Atm website has very aggressive Cloudflare setting, which prevents tachiyomi from loading it even in webview/with random user agent.

**Comment by shilen898** [comment]
Changed their domain #11587
