### ISSUE TITLE
TeenManhua not showing all available manhwas

### ISSUE THREAD

**Issue by RenzRayark** [tachiyomiorg/tachiyomi-extensions#11586]
### Source information

TeenManhua 1.2.20

### Steps to reproduce

1. Click browse
2. Click TeenManhua Latest from sources
3. Scroll and observe available titles
4. Click "open in webview" icon
5. Observe available latest titles

Optional additional steps:
6.1 Go to tachiyomi. 
6.2 Click browse
6.3 Click teenmanhua extension from sources
6.4 Click search and enter an unviewable title (ex.Daisy: How to Become the Duke’s Fiancée or  I’m the Master of this Life)

### Expected behavior

All available manhuas in Teenmanhua website should be viewable through tachiyomi.

For the additional steps:
After being searched, the manhuas/manhwa should be available or viewable. 

### Actual behavior

Not all available manhwa or manhua titles are available/viewable through tachiyomi.

For the additional steps:
After being searched, it shows "no results found"

### Tachiyomi version

1.2.20

### Android version

Android 7

### Other details

I have some manhwas from teeanmanhua that are marked as "in library". If i search for some of these titles through either the global search or teenmanhua search, the result would be "no results found".

But even if I cant search or view these manhuwas if look for them in the extension, they are still updated normally if new chapters are added in the website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Does it appear if you uncheck the "Show only manga entries" filter?

**Comment by alessandrojean** [comment]
Closing since it appears after disabling the filter I told, the site is just incorrectly marking the titles as novel/video.
