### ISSUE TITLE
Asura Scans Long Loading Times

### ISSUE THREAD

**Issue by omid82700** [tachiyomiorg/tachiyomi-extensions#11598]
### Source information

Asura Scans v1.2.26

### Steps to reproduce

1. Browse Asura Scans

### Expected behavior

Load everything normally and not slow.

### Actual behavior

Usually http error 502. Or takes 2 mins to load comics and another 2 mins to load the image preview. And once you click on a comic, another 2 mins to load the description and chapters. Webview works perfectly fine.

### Tachiyomi version

0.13.4

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Asura have a rate limiting to avoid causing damage to their servers. It's intentionally made "slow" to avoid further problems.

Also, HTTP errors 5xx are server side and we can't fix it. You need to wait until they fix it.
