### ISSUE TITLE
Bug with captcha

### ISSUE THREAD

**Issue by Brobrobrobrobr** [tachiyomiorg/tachiyomi-extensions#11599]
### Source information

Com-x 1.2.16

### Steps to reproduce

After passing the captcha, the extension works

### Expected behavior

I can work with extension

### Actual behavior

Nothing happens, the captcha is not called again

### Tachiyomi version

Last 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
"Last" is not a valid Tachiyomi version. Please provide the _numeric_ version (ex. `v0.13.3`).

**Comment by alessandrojean** [comment]
Closing for lack of useful information such as the errors that are appearing.

Feel free to open a new issue with more information if you want it, though.
