### ISSUE TITLE
KillSixBillionDemons: Chapter list reversed

### ISSUE THREAD

**Issue by BartTerpstra** [tachiyomiorg/tachiyomi-extensions#11594]
### Source information

KillSixBillionDemons ver 1.2.4

### Steps to reproduce

open a book, and realise it's sorted ascending.

### Expected behavior

it should be sorted descending
(this allows downloading next X to be correct)

### Actual behavior

it is sorted ascending. 
1-2-3-4
(downloading next X instead download last chapters)

### Tachiyomi version

stable 0.12.1

### Android version

irrelevant

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BartTerpstra** [comment]
note: whomever attempts to fix this, be careful to not regress multi-page chapters to be backwards again.

**Comment by alekc** [comment]
@BartTerpstra do you have an example of multi-page chapters which can break?
