### ISSUE TITLE
Reaperscan(GS) have redone their website and url

### ISSUE THREAD

**Issue by JetonBreton** [tachiyomiorg/tachiyomi-extensions#11601]
### Source information

Reaper Scans v1.2.25

### Steps to reproduce

Launching the extension displaying no results

### Expected behavior

Displays the different scans offered by the site

### Actual behavior

Error No results found

### Tachiyomi version

0.13.4

### Android version

10

### Other details

They have recently redone their website and changed their old url: https://reaperscans.fr/ 
to now: https://new.reaperscans.fr/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's already available under the Reaper Scans in the `All` language. Install it and migrate your titles from the old extension to the new one.

**Comment by JetonBreton** [comment]
Thanks very much
