### ISSUE TITLE
"Unable to resolve host" issue

### ISSUE THREAD

**Issue by 8397110197** [tachiyomiorg/tachiyomi-extensions#11608]
### Source information

9anime gogoanime Sflix

### Steps to reproduce

Click on the extension
Select an anime 
Tap on the episode
"Should" start playing the videos

### Expected behavior

In aniyomi app, the anime extensions works perfectly fine, unless i try to play the video. It previously would take few seconds to load and start playing

### Actual behavior

It doesn't play the videos, it only shows a loading screen and shows " unable to resolve host...'

### Tachiyomi version

aniyomi-r4513.apk

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Tachiyomi does not support anime streaming. Make sure you're opening the issue in the correct repository.
