### ISSUE TITLE
Hitomi

### ISSUE THREAD

**Issue by RyomeSukuna** [tachiyomiorg/tachiyomi-extensions#11612]
### Source name

hitomi.la

### Source link

https://hitomi.la/

### Language

various

### Other details

the site has a wide variety of languages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It already exists...

**Comment by RyomeSukuna** [comment]
What would Tachiyomi's name be?

Em seg, 25 de abr de 2022 18:58, Alessandro Jean ***@***.***>
escreveu:

**Comment by alessandrojean** [comment]
Literally the site name, just search it on the extensions tab.
