### ISSUE TITLE
Hentai2read: Missing content for a category

### ISSUE THREAD

**Issue by Harsh-Khare-16** [tachiyomiorg/tachiyomi-extensions#11622]
### Source information

hentai2read 1.2.13

### Steps to reproduce

Just filter the mangas in hentai2read extention by selecting Lolicon category. All the content with that tag is missing.

### Expected behavior

It should show all result for that Lolicon category as well as other category including the content which falls in lolicon tag.

### Actual behavior

It just shows no results found when lolicon category is selected from the filter and also when selecting other categories it just eliminates the lolicon tag for example if selected category is teacher it will should show 100 results instead it eliminates the results with lolicon tag and will only show 50 results but this is working fine on website.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
I don't use hentai2read but a quick visit to the website and using that tag as a search returns nothing. Are you sure you're on the right website?

**Comment by Seishirou101** [comment]
![1920-1030-max](https://user-images.githubusercontent.com/57241064/168208102-723afcc3-95ed-467a-bd93-1c4fe1974527.png)
