### ISSUE TITLE
Mangadex not showing russian chapters

### ISSUE THREAD

**Issue by Discordbot24** [tachiyomiorg/tachiyomi-extensions#11624]
### Source information

Mangadex 1.2.158

### Steps to reproduce

1. Deselect all languagues in settinf of extension
2. Select english and russian. (Also tried with only russian)
3. Search for a title
4. Nothing showed up

### Expected behavior

Should show russian chapters aswell

### Actual behavior

Not showinf russian chapters. Even when english is turned off and i search the title in russian nothing shows up

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

I tried multiple titles and the websites shows russian chapters available. For some reason dutch does work even tho there are no chapters for that one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Discordbot24** [comment]
Sorry for my name i use this account for my discord bot thisbis not spam

**Comment by alessandrojean** [comment]
Make sure there are Russian chapters by opening in WebView. MangaDex doesn't have Russian translations for every title in their website, so a lot will be missing and the "No chapters found" is indeed expected.

**Comment by Discordbot24** [comment]
> Make sure there are Russian chapters by opening in WebView. MangaDex doesn't have Russian translations for every title in their website, so a lot will be missing and the "No chapters found" is indeed expected.

Yes i did that just like i said in additional information it still didnt work

**Comment by alessandrojean** [comment]
Working fine for me, make sure you entered MangaDex in the correct language or your ISP isn't blocking the requests. Try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) and ask for additional help at our [Discord](https://discord.gg/tachiyomi) if it doesn't work.

![Screenshot_20220427-095011_Tachiyomi](https://user-images.githubusercontent.com/14254807/165521909-325acc06-e8fa-4681-ac51-6f9821d8e5d7.jpg)

**Comment by Discordbot24** [comment]
Thx for some reason when using a vpn it started working no idea why. Thx again
