### ISSUE TITLE
Infernal Void Scans: No results found

### ISSUE THREAD

**Issue by BossLite23** [tachiyomiorg/tachiyomi-extensions#11625]
### Source information

Infernal Void Scans v1.2.17

### Steps to reproduce

when opening the source, it states "no results found"

### Expected behavior

I should be able to view a list of manga

### Actual behavior

It states "no results found"

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
their website is currently partially broken, more importantly is their search. which is used by tachi
