### ISSUE TITLE
ESMANGA

### ISSUE THREAD

**Issue by itsgukkie** [tachiyomiorg/tachiyomi-extensions#11621]
### Source name

ESMANGA

### Source link

https://esmanga.net/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Indeed seems just like a mirror, so closing it.

**Comment by itsgukkie** [comment]
> Se ve idéntico al [# 11620](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11620) (diseño y contenido sabio)

oh, it's true, you're right but, neither extension is available. So they look the same, for that reason I opened the application, I would like to know if they will add any of the two pages or not they will not be able to?
