### ISSUE TITLE
XOXO Comics: Show Categories to Filter in Browse

### ISSUE THREAD

**Issue by Agent-qt** [tachiyomiorg/tachiyomi-extensions#11631]
### Source information

XOXO Comics 1.2.3

### Steps to reproduce

1. Install XOXO Comics
2. open XOXO Comics 
3. Click the filter 

### Expected behavior

Shows catagories 

### Actual behavior

just showed reset, save and filter buttons 

### Tachiyomi version

1.8.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
its not even added yet, its not a bug then. more like requeast

**Comment by Soitora** [comment]
> its not even added yet, its not a bug then. more like requeast

what
![image](https://user-images.githubusercontent.com/10836780/165596809-f6e2b5db-e04b-4478-879c-09d1d8e2ec89.png)

**Comment by Riztard** [comment]
i mean the categories in filter, so there is no filter button

**Comment by Agent-qt** [comment]
![Screenshot_20220427-171455_TachiyomiSY.jpg](https://user-images.githubusercontent.com/104474621/165633283-ae9dbf64-f625-4899-95b8-40ade4f453dc.jpg) wdym?? the filter is there

**Comment by curche** [comment]
Its showing a dummy Filter button because you're on TachiyomiSy

If you check the main tachiyomi it doesnt exist

**Comment by Agent-qt** [comment]
Ohhhhh, my fault. But is there any chance that the catagories could be added ?? Or is it always gonna be a dummy filter?

**Comment by curche** [comment]
Well, that depends on whether someone wants to work on it. Be patient and hopefully someone will try a hand at it

I'll mark the issue as a Feature Request and edit the title to be bit more clear

**Comment by curche** [comment]
/edit-title "XOXO Comics: Show Categories to Filter in Browse"

**Comment by Agent-qt** [comment]
Alright, I appreciate the help, thx
