### ISSUE TITLE
Com-x: HTTP error 404

### ISSUE THREAD

**Issue by Brobrobrobrobr** [tachiyomiorg/tachiyomi-extensions#11635]
### Source information

Com-x

### Steps to reproduce

1. The extension requests the passage of the captcha
2. After passing the captcha, nothing has changed

### Expected behavior

After passing the captcha, the extension makes it possible to work with the application

### Actual behavior

Nothing 

### Tachiyomi version

0.13.14

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
ComX strengthened the protection against bots (in other words, dead for tachiyomi)

**Comment by e-shl** [comment]
>[CALL FOR HELP]AntiBot Cloud #12068

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475

**Comment by e-shl** [comment]
Alive again!
