### ISSUE TITLE
Mangakakalot: Chapters not loading beyond two pages

### ISSUE THREAD

**Issue by Gamerproq** [tachiyomiorg/tachiyomi-extensions#11642]
### Source information

Mangakakalot 1.2.8

### Steps to reproduce

1.Open source
2. Choose any manga/manhwa
3. Start any chapter

### Expected behavior

Chapter pages to load one by one

### Actual behavior

Chapter pages not loading beyond the first two

### Tachiyomi version

App version: 0.13.4-4299

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Cannot reproduce. Do you have a specific example / more detailed walkthrough?

**Comment by Gamerproq** [comment]
![Screenshot_20220428-232345_Tachiyomi](https://user-images.githubusercontent.com/52848057/165816531-6e132853-5b11-46ec-9300-98ec7cde59be.jpg)
![Screenshot_20220428-232342_Tachiyomi](https://user-images.githubusercontent.com/52848057/165816551-c5058ce5-b5e2-4415-b3dc-c44a506104e4.jpg)
![Screenshot_20220428-232320_Tachiyomi](https://user-images.githubusercontent.com/52848057/165816581-d3b36647-7e80-486f-a1af-fff7a778c1a7.jpg)
![Screenshot_20220428-232325_Tachiyomi](https://user-images.githubusercontent.com/52848057/165816610-a15d5c39-9022-4825-8246-2a8ef6bf82eb.jpg)
![Screenshot_20220428-232314_Tachiyomi](https://user-images.githubusercontent.com/52848057/165816639-0e17df60-bfab-4993-8e40-11624f8d4257.jpg)
![Uploading Screenshot_20220428-232303_Tachiyomi.jpg…]()

**Comment by alekc** [comment]
Nope, all good for me. Did you see this page: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475 ?
```
Mangakakalot "Source URL has changed" / duplicate entries for favorited manga: Mangakakalot changed URLs for some of the manga they host. In those cases, the older entry won't receive chapter updates and the newer entry may appear in search and browse as a duplicate or new entry that hasn't been favorited. You need to migrate those manga to receive new chapters (you can remigrate to Mangakakalot if you want to continue using it as a source). Depending on what version of Tachiyomi you use, there may be an option to receive notifications about failed chapter updates that would help you find which manga are effected.
```

I wonder if that could be the case. You can try to browse a manga on kakalot which you do not have yet in your catalog to see if the issue persist there as well.

**Comment by Gamerproq** [comment]
The extension was working fine until 2 days ago. Like no problem at all

**Comment by Gamerproq** [comment]
![Uploading Screenshot_20220429-055825_Tachiyomi.jpg…]()
![Uploading Screenshot_20220429-055833_Tachiyomi.jpg…]()

**Comment by Gamerproq** [comment]
I checked the latest updated titles on the mangakakalot extension and I got
the same problem for 34 out of the first 50 I checked that were not present
in my library.

**Comment by alekc** [comment]
@Gamerproq couple of questions:

- did you try to use alternative network (mobile/wifi/vpn)? 
- did you try all troubleshooting tips?

if above doesn't help try with tachiyomi preview, and enable verbose logging in advanced settings. Maybe something will popup there.

**Comment by Gamerproq** [comment]
I've tried multiple wifi networks as well as mobile data and hotspot. What all troubleshooting tips should I try?

**Comment by Gamerproq** [comment]
[tachiyomi_crash_logs.docx](https://github.com/tachiyomiorg/tachiyomi-extensions/files/8597106/tachiyomi_crash_logs.docx)
