### ISSUE TITLE
Kirishima Fansub: HTTP error 404

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11649]
### Source information

Kirishima Fansub 1.2 3

### Steps to reproduce

HTTP error 404: Open site in WebView

### Expected behavior

This should happen... The extension should work like any other

### Actual behavior

This happened instead... "HTTP error 404: Open site in WebView" and the extension does not show sleeves inside.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

![Screenshot_20220428-181208_Tachiyomi](https://user-images.githubusercontent.com/101371218/165868106-d245fd4d-e5f1-4499-bba4-743ef1ed9991.jpg)
![Screenshot_20220428-181225_Tachiyomi](https://user-images.githubusercontent.com/101371218/165868110-d1672ae6-e45a-4cb8-8b2e-282ebf4aa69b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
