### ISSUE TITLE
View comments

### ISSUE THREAD

**Issue by 7heMech** [tachiyomiorg/tachiyomi-extensions#11647]
### Describe why this should be added

Some sites have a comments section with stuff like disquis, and it really improves the user experience, so I was wondering if it was possible to implement that.
I was unsure if this is supposed to go to the extensions category.

Add the option to view comments.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Should be opened in the app repository and it has already been denied in the past.
