### ISSUE TITLE
Have the ability to delete local chapters/library in your Local Source Extension

### ISSUE THREAD

**Issue by AwayJob** [tachiyomiorg/tachiyomi-extensions#11659]
### Describe your suggested feature

Since you _own_ the files, you should techically do what ever you want within your phone.

I propose that you can have the ability to delete your local ebook/chapters through Tachiyomi by long pressing the ebook or have a recycle bin icon at the top and you select which ebook you gonna delete.  It's always a pain to wait my File Explorer to load and scroll down, click Tachiyomi, click local, then delete the ebook you have to free up some space. I hope you guys approve.

Thanks for reading my request. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The local source isn't an extension, so please open this issue in the app repository.
