### ISSUE TITLE
Legion Scans

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11651]
### Source name

Legion Scan

### Source link

https://legionscans.com/

### Language

Español

### Other details

![Screenshot_20220428-183258_Opera](https://user-images.githubusercontent.com/101371218/165868516-d58030c9-8b3e-47c2-be47-604f201a3dd1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader theme

**Comment by edmxn** [comment]
> Uses WPMangaReader theme

What is that? (if it's an extension, it doesn't come out) I really don't know much about this hehe

**Comment by vetleledaal** [comment]
The site is using a common theme, meaning it shares a lot of code and structure with other sites. Practically that means someone needs to add the site to [this file](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt), test it, and add custom logic as needed.

**Comment by edmxn** [comment]
> The site is using a common theme, meaning it shares a lot of code and structure with other sites. Practically that means someone needs to add the site to [this file](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt), test it, and add custom logic as needed.

I'll try
