### ISSUE TITLE
Manhwaindo

### ISSUE THREAD

**Issue by AhmadNaruto** [tachiyomiorg/tachiyomi-extensions#11656]
### Source name

manhwaindo

### Source link

https://manhwaindo.id/

### Language

Indonesian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses WPMangaReader theme

**Comment by AhmadNaruto** [comment]
> Uses WPMangaReader theme

you sure..?

**Comment by vetleledaal** [comment]
Site references MangaReader, and the structure matches at least on search and manga details. In any case, the site might have additional changes outside of the standard template.

Is there anything indicating it's not using MangaReader as a template?

**Comment by TheKingTermux** [comment]
> Uses WPMangaReader theme

In progress

**Comment by TheKingTermux** [comment]
How to add a individual genre for MultiSrc ekstension?

**Comment by TheKingTermux** [comment]
Done #11793
