### ISSUE TITLE
Doujindesu: Missing covers

### ISSUE THREAD

**Issue by Shiin-79** [tachiyomiorg/tachiyomi-extensions#11662]
### Source information

Doujindesu v1.2.2

### Steps to reproduce

Saat jelajah cover komik tidak tampil (gambar Cover rusak)

### Expected behavior

Bagaimana cara fix gambar cover yang rusak

### Actual behavior

Cover komik rusak

![image](https://user-images.githubusercontent.com/56505683/166005480-bc9d1ea3-cbaf-42a5-9269-3663a70ef8bc.png)

### Tachiyomi version

0.13.4

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
I confirmed it 🙂
Every time i refresh the library the cover always gone 🙂

**Comment by Shiiki012** [comment]
> I confirmed it Every time i refresh the library or It refresh automaticaly the cover always gone

@alessandrojean

**Comment by alessandrojean** [comment]
Wtf, no need to ping me. Wait until someone wants to work on it.

**Comment by TheKingTermux** [comment]
Not me

**Comment by CVIUS** [comment]
> Is there a possibility that a website using an IP address could affect the extension? Like the loss of the cover image, can't access, etc?

From https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11606#issuecomment-1110461797

"This is not a new domain, it's a RAW IP. We don't use RAW IPs in the extensions, as it's a non-secure measure. Use the alternatives provided before, like using a VPN or a Deep Packet Inspection bypasser to access it instead."

**Comment by TheKingTermux** [comment]
> > Is there a possibility that a website using an IP address could affect the extension? Like the loss of the cover image, can't access, etc?
> 
> From [#11606 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11606#issuecomment-1110461797)
> 
> "This is not a new domain, it's a RAW IP. We don't use RAW IPs in the extensions, as it's a non-secure measure. Use the alternatives provided before, like using a VPN or a Deep Packet Inspection bypasser to access it instead."

That not what i mean, but thanks for answer my question

**Comment by ArioVanish** [comment]
Sama bro padahal sebelumnya normal

**Comment by TheKingTermux** [comment]
> Sama bro padahal sebelumnya normal

Ini masalahnya Keknya ada di bagian official web Doujindesu nya sih karena masih pke IP mentah dan belum di daftarin ke Domain
Soalnya ekstensi dari Tachiyomi itu harus pke Domain
Mungkin emg masih bisa diakses, tpi emg kadang begini 😅

**Comment by Farhanulhakim** [comment]
ini domain nya ganti ya jadi bukan doujindesu(.)xxx lagi, gua dari awal nunggu di benerin tapi sampe sekarang masih belum di perbaiki juga

**Comment by TheKingTermux** [comment]
> ini domain nya ganti ya jadi bukan doujindesu(.)xxx lagi, gua dari awal nunggu di benerin tapi sampe sekarang masih belum di perbaiki juga

Untuk sekarang masih belum up Domainnya
Masih dalam keadaan IP address 
Sedangkan ekstensi dari Tachiyomi itu harus pke Domain
Jdi klo emg di ekstensinya ada error atau apa, itu kemungkinan besar akibat dari perubahan Domain ke IP address

**Comment by Farhanulhakim** [comment]
> > ini domain nya ganti ya jadi bukan doujindesu(.)xxx lagi, gua dari awal nunggu di benerin tapi sampe sekarang masih belum di perbaiki juga
> 
> Untuk sekarang masih belum up Domainnya Masih dalam keadaan IP address Sedangkan ekstensi dari Tachiyomi itu harus pke Domain Jdi klo emg di ekstensinya ada error atau apa, itu kemungkinan besar akibat dari perubahan Domain ke IP address Kita jg gabisa apa apa dikarenakan ekstensi sebelumnya masih aman aman aja ketika domain belum ganti (covernya ilang, ndxdomain, hostname not verified, dll) bisa diakali pake VPN kok Sans ae Mau diubah ke IP address jg gabisa di up Ama team inspeksi [#11606 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11606#issuecomment-1110461797)

jadi ini cuman bisa nunggu balik ke domain awal atau domain baru ya

**Comment by TheKingTermux** [comment]
> > > ini domain nya ganti ya jadi bukan doujindesu(.)xxx lagi, gua dari awal nunggu di benerin tapi sampe sekarang masih belum di perbaiki juga
> > 
> > 
> > Untuk sekarang masih belum up Domainnya Masih dalam keadaan IP address Sedangkan ekstensi dari Tachiyomi itu harus pke Domain Jdi klo emg di ekstensinya ada error atau apa, itu kemungkinan besar akibat dari perubahan Domain ke IP address Kita jg gabisa apa apa dikarenakan ekstensi sebelumnya masih aman aman aja ketika domain belum ganti (covernya ilang, ndxdomain, hostname not verified, dll) bisa diakali pake VPN kok Sans ae Mau diubah ke IP address jg gabisa di up Ama team inspeksi [#11606 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11606#issuecomment-1110461797)
> 
> jadi ini cuman bisa nunggu balik ke domain awal atau domain baru ya

Nunggu Doujindesu bikin Domain baru

**Comment by TheKingTermux** [comment]
Update :
- **Better filter**
![Screenshot_2022-08-02-16-58-27-67_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/182349121-c4ddc13a-7d37-42c3-be01-87830aa0abb0.jpg)

- **Full genre**
![IMG_20220802_165921.jpg](https://user-images.githubusercontent.com/50316075/182349208-76183333-7862-42dd-93ec-41a9cb4c0b34.jpg)

ToDo :
- **Repair thumbnail** 
![IMG_20220802_170459.jpg](https://user-images.githubusercontent.com/50316075/182349264-f2cd5c81-faab-4e74-8e97-3361c8d8959b.jpg)

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
