### ISSUE TITLE
ToonGod: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Hades68** [tachiyomiorg/tachiyomi-extensions#11665]
### Source information

ToonGod 1.2.22

### Steps to reproduce

1. Go to navigation Browse
2. Browse or latest source ToonGod

### Expected behavior

Successful show and browse manga list

### Actual behavior

- In Fragment List : Failed to bypass Cloudflare
- In WebView : Showing normaly
![Screenshot_2022-04-30-04-01-30-736_eu kanade tachiyomi](https://user-images.githubusercontent.com/32086492/166062021-bd923317-9eba-4ef2-8c72-21b561c5ce3f.jpg)
![Screenshot_2022-04-30-04-04-07-904_eu kanade tachiyomi](https://user-images.githubusercontent.com/32086492/166062039-2c5e8da8-1381-42ec-8fbb-6e0f78a0d10d.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11 - MIUI Global 12.0.3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by damnthethe** [comment]
I also cant open webview

**Comment by musrayney** [comment]
Facing the same issue, previously even webview not working. Now webview working but still cant load the list normally

**Comment by xHDSx** [comment]
same issue

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
