### ISSUE TITLE
chapter marks

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11667]
![Screenshot_20220429-142413_Tachiyomi](https://user-images.githubusercontent.com/101371218/166064215-bc3625be-0d71-47b8-97a5-9301efe3d6ce.jpg)
### Describe why this should be added

I suggest to put another way to mark the chapters, for the manga that have duplicate chapters (different versions of a single chapter) this because, I tried every method and none helped me to skip the duplicates, and use the "Mark" option in all the chapters You can slow down the loading of them, or if I want to have a certain chapter not marked and I activate the filters to "only marked" that chapter that I unmark will not come out, as with the option to mark the chapters as "Viewed"

### Other details

[My English is bad, I am using a translator to write this]

It would also serve an option that allows you to see the chapters of a single Group, to see only its version and skip the other versions

! I have the option to Show "Chapter Numbers" and not their titles to see if the duplicates were skipped and it didn't work

! This is a bit annoying when I only want to see one group's version, and not the others.

! I apologize if my request is a bit tedious or ignorant, I looked in your FAQ and found the "Solution" but, when I do that, what I mentioned above happens, to mark as read, at least in the extension that I use for some reason that I do not know the loading of images is slow (it is not wi-fi, since in other extensions it works correctly, but my internet is not so bad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

Please open the issue in the app repository instead, as it is an app feature you're requesting.
