### ISSUE TITLE
Group titles with multiple sources in the user's library together

### ISSUE THREAD

**Issue by MrP6k** [tachiyomiorg/tachiyomi-extensions#11687]
### Describe your suggested feature

Currently, when you add the same title from different sources to your library, they shows up like they are separate titles. Could it be grouped instead? Make it show up as one title, and when you click it it will show the multiple sources of the title that you selected to add to your library.

I feel like this would make it a lot less cluttered

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
1) not an extension issue.
2) its been rejected [before](https://github.com/tachiyomiorg/tachiyomi/issues/886) sort of
