### ISSUE TITLE
Jpmangas: Unable to connect to the extension

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#11692]
### Source information

Jpmangas v1.2.5

### Steps to reproduce

1. Go to the extension list
2. Tap the extension to browse it
3. The extension tries to connect for a long time only to show "HTTP Error 522 : Consult the site in WebView"
4. Tap the WebView button
5. After a long attempt the WebView shows the Cloudflare Error 522 page with the error on the host.

### Expected behavior

Tap the extension Jpmangas and browse it.

### Actual behavior

The extension shows: "HTTP Error 522: Consult the site in WebView"

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

It seems that the site changed domain. While the extension directs to https://jpmangas.co/ the new domain seems to be https://jpmangas.cc/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
WebView confirmed their site is down, nothing we can do to fix it on the extension. If their site doesn't work, the extension will also not work. Wait until they fix it or migrate.
