### ISSUE TITLE
Update skipped

### ISSUE THREAD

**Issue by JustinGamerLolp** [tachiyomiorg/tachiyomi-extensions#11696]
### Source information

Mangadex, Bato.to, Hiperdex, Kuma Scans(Kuma Translation),LHTranslation, Mangabuddy, Mangaclash, Mangalife, Manhwamanga.net, Manhwaworld, Mahwatop, Nhentai, NinemangaEN, Reaper Scans, Teenmanhua, WebtoonXYZ, 

### Steps to reproduce

First is that when I scroll down for more updates, it only updates124 of my reading material
Second is that I wait for the update to stop then the issue happened
The issue is that 2500 of my updates don't wanna  update their latest chapter.

### Expected behavior

The updates should be more than 2,600 and to be more faster because my extensions is the latest version

### Actual behavior

The updates can do only 124 and so laggy

### Tachiyomi version

1.5.0

### Android version

Android 11

### Other details

When I download the latest version of TachiJ2K, the error suddenly happens. Please fix the problem moderators of this app really appreciate your service for our fellow manga, manhwa readers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
read the changelog. also https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries

**Comment by JustinGamerLolp** [comment]
Thank you for the guide, I already solved my freatest problem and now I can
finally read at peace thank you tachiyomi
