### ISSUE TITLE
Manga Gohan: HTTP error 400

### ISSUE THREAD

**Issue by essegrev** [tachiyomiorg/tachiyomi-extensions#11701]
### Source information

Manga Gohan 1.2.21

### Steps to reproduce

1. Install Tachiyomi
2. Install Manga Gohan Extension
3. Open Manga Gohan Extension
4. Message「HTTP error 400: WebViewでサイトを開く」
5. Open WebView
6. Close WebView
7. Click Retry
8. Return [4]

### Expected behavior

When opening Manga Gohan extension, it should be load the manga lists

### Actual behavior

When opening Manga Gohan extension, it show sad emoji with error "HTTP error 400: WebView でサイトを開く"

Manga Gohan load without problem in WebView mode

### Tachiyomi version

0.13.4-4338

### Android version

Android 11

### Other details

It is very similar to the following issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kaonkaon** [comment]
its same as the error i got few month ago, it was fixed by changing the url to gokumanga.com

looks like they (manga gohan sides) changed the url again, now its "mangagohan.me"

may this help to someone who will fix this
