### ISSUE TITLE
BokugenTranslations

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11708]
### Source name

Bokugen Translation

### Source link

https://bokugents.com/

### Language

Español

### Other details

![Screenshot_20220502-195718_Opera](https://user-images.githubusercontent.com/101371218/166394248-fceb53c2-df65-4aba-8582-fe70b0993ad9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by edmxn** [comment]
> Uses Madara theme
> 
> ```kotlin
> dateFormat = SimpleDateFormat("MMM d, yyy", Locale("es"))
> ```

? i have no idea about that

**Comment by vetleledaal** [comment]
it's a common theme. wait for someone to implement it

**Comment by edmxn** [comment]
> it's a common theme. wait for someone to implement it

ohhh so cool
