### ISSUE TITLE
Noblesse Translations

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11706]
### Source name

Noblesse Translations

### Source link

https://www.noblessetranslations.com/

### Language

Español

### Other details

![Screenshot_20220502-195138_Opera](https://user-images.githubusercontent.com/101371218/166393865-a36b2901-bea4-426e-ac8e-b0b5f043c00b.jpg)
![Screenshot_20220502-195144_Opera](https://user-images.githubusercontent.com/101371218/166393866-7d14d42d-a073-4b98-ad77-ed46559c8da6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme
