### ISSUE TITLE
TecnoScan

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11707]
### Source name

Tecno Scann

### Source link

https://tecnoscann.com/

### Language

Español

### Other details

![Screenshot_20220502-195607_Opera](https://user-images.githubusercontent.com/101371218/166394169-1dd39d93-4905-45e1-b212-a7f387b37114.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme
```kt
dateFormat = SimpleDateFormat("MMM d, yyy", Locale("es"))
```

**Comment by vetleledaal** [comment]
Site has been down for at least a week, closing.
