### ISSUE TITLE
Manga347: HTTP error 404

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#11725]
### Source information

Manga347 1.2.23

### Steps to reproduce

Open manga347 extension

### Expected behavior

Mangas load normally

### Actual behavior

Error 404

### Tachiyomi version

0.13.4

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MrChuw** [comment]
not even the 404 error appears anymore.

**Comment by vetleledaal** [comment]
@Riztard did you make a PR for the linked commit?

**Comment by Riztard** [comment]
hmm looks like i forgot lmao, and now they change things again

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
