### ISSUE TITLE
Doujindesu can't acces

### ISSUE THREAD

**Issue by genji-666** [tachiyomiorg/tachiyomi-extensions#11728]
### Source information

Doujindesu 1.2.2

### Steps to reproduce

First Step

### Expected behavior

This should happen

### Actual behavior

This happen instead

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

![Screenshot_20220504-093312_Tachiyomi](https://user-images.githubusercontent.com/104878840/166616159-fd70f6b1-543f-4e8a-b2c9-37b3da017514.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> ## Indonesian NXDOMAIN error
> Indonesian carriers and ISPs are blocking sites using DNS, causing NXDOMAIN errors. They may prevent you from switching to other DNS providers using DNS hijacking/redirection, TCP reset attacks, SNI filtering, and Deep Packet Inspection.
> ### What can I do to fix it?
> Try turning on DNS over HTTPS under More 🡒 Advanced 🡒 DNS over HTTPS.
> ### That Didn't Work!
> Your ISP may be using the new blocking mechanism. Use a VPN or use a Deep Packet Inspection Bypass app like [DPITunnel-cli](https://github.com/zhenyolka/DPITunnel-android), [PowerTunnel](https://github.com/krlvm/PowerTunnel), or [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)
