### ISSUE TITLE
Allporncomic: Only loads first 20 items when using filter

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#11722]
### Source information

Allporncomic 1.2.20

### Steps to reproduce

Use the "Filter" feature of tachiyomi.

### Expected behavior

It should load all available entries.

### Actual behavior

Only loads first 20 items.

### Tachiyomi version

0.13.4

### Android version

android 12

### Other details

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXU4BVB4
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
It still happens in the version 1.3.26

**Comment by Palloxin** [comment]
In the 1.4.29 the bug is fixed. It doesn't limit to 20 entries anymore.
