### ISSUE TITLE
MG Komik: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#11727]
### Source information

MG Komik 1.2.22

### Steps to reproduce

1. Cant open Comics in this extension

### Expected behavior

Cant open manga in this extension

### Actual behavior

I cant open any manga in this extension because it says "Failed to Bypass the Cloudflare" , but when I open in webview it running normally

### Tachiyomi version

0.13.4

### Android version

Android 7.1.1

### Other details

![Screenshot_2022-05-04-09-13-08-23](https://user-images.githubusercontent.com/81138524/166615772-985af660-d7b4-4c0a-a78c-dfdae4b2233d.png)
![Screenshot_2022-05-04-09-12-32-16](https://user-images.githubusercontent.com/81138524/166615778-04849e7d-c7e9-4931-bc0f-e29b81a24e46.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Bisa nih 🙂
Dah terbukti bisa ya 
Gapake DNS Over HTTPS Ama VPN 😌

![Screenshot_2022-05-08-07-05-10-42_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/167276105-92133838-f5c0-4d42-9463-c238a4e0e7ac.jpg)

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
