### ISSUE TITLE
Hentaiteca 

### ISSUE THREAD

**Issue by Himosuke** [tachiyomiorg/tachiyomi-extensions#11729]
### Source information

Hentaiteca 1.2.21

### Steps to reproduce

![Screenshot_20220504-002614_Tachiyomi](https://user-images.githubusercontent.com/103377139/166619427-468e40f9-2b1f-42de-8abc-fd6f086626ca.jpg)

### Expected behavior

Deveria aparecer  obras nesse quadro

### Actual behavior

Aparece o Cloudflare, não atualiza  obras, mas ao abrir no webview está tudo normal, apenas não atualiza novos capítulos 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's nothing that can be done in this case. Wait until they decide to lower their protection or migrate.
