### ISSUE TITLE
Allporncomic: Reset filter button not working

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#11723]
### Source information

Allporncomic 1.2.20

### Steps to reproduce

Use the Filter feature and tick a tag tickbox
Press the reset button

### Expected behavior

The tag should be unticked

### Actual behavior

The tag remains ticked even if you exit the extension.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXU4BVB4
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
