### ISSUE TITLE
ReadMangaToday: Source not working after site update

### ISSUE THREAD

**Issue by hootshot** [tachiyomiorg/tachiyomi-extensions#11730]
### Source information

ReadMangaToday v1.2.9

### Steps to reproduce

Tapping on "Latest" or directly on the source.

### Expected behavior

Tapping on "Latest" should give us the latest uploaded manga chapters and tapping on the source should present the full catalog.

### Actual behavior

Tapping on "Latest" give us a blank screen. Tapping on source give us "No results found".

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

The site has a new design apparently, thus my suspicion of it breaking the extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by xmithosx** [comment]
I confirm the problem, not a bug but properly but don't work at the momment
