### ISSUE TITLE
Bilibili login error

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#11749]
### Source information

Bilibili 1.2.7

### Steps to reproduce

I have a bilibili account login via Facebook, but when i tried to login via tachiyomi, i can not login. Though when i tried via opera browser, i can login. Help please

### Expected behavior

I can login to my bilibili which using Facebook account

### Actual behavior

I can not login

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Usually social media sign in methods are disabled by the providers for WebView. In order to sign in through WebView you need to use a simple email/password Bilibili own account.
