### ISSUE TITLE
Henchan: Changed their domain

### ISSUE THREAD

**Issue by Curbin30** [tachiyomiorg/tachiyomi-extensions#11746]
### Source information

hentaichan / henchan

### Steps to reproduce

yep

### Expected behavior

normal work

### Actual behavior

don't working

### Tachiyomi version

last version

### Android version

Android 10

### Other details

new domain is xxx.hentaichan.live

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.
![Screenshot_2022-05-05-18-07-05-697_eu kanade tachiyomi](https://user-images.githubusercontent.com/61585408/166954130-e6cbc3c3-527e-4ae9-8c9c-a9178acb6310.jpg)
![Screenshot_2022-05-05-18-07-17-139_eu kanade tachiyomi](https://user-images.githubusercontent.com/61585408/166954135-309c3a11-7720-4036-8572-a56b88d3395c.jpg)
![Screenshot_2022-05-05-18-07-26-741_com android chrome](https://user-images.githubusercontent.com/61585408/166954141-3ecd6c9e-64ef-484a-8743-2a146fb86d15.jpg)

**Comment by alessandrojean** [comment]
Fixed by #11771.
