### ISSUE TITLE
Everia club cant open or download old chapter

### ISSUE THREAD

**Issue by XOrinu** [tachiyomiorg/tachiyomi-extensions#11741]
### Source information

Everia Club 1.2.2

### Steps to reproduce

Downloading the old released chapter on everia club extension. 

Ps. The new released chapter was work tho

### Expected behavior

The chapter opened or downloaded

### Actual behavior

It says “no pages found” when k tried to open the chapter.
And error when i tried to downloaded it

### Tachiyomi version

Tachiyomi v0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#10918
