### ISSUE TITLE
Hentailib: Crashing Tachiyomi

### ISSUE THREAD

**Issue by kentaai** [tachiyomiorg/tachiyomi-extensions#11752]
### Source information

ru.hentailib

### Steps to reproduce

Installing the ru.hentailib resource. Go to the library.

### Expected behavior

 A mistake, but not a crash 

### Actual behavior

  Crashes when switching to the source

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

 The resource is located in Russia, on the territory of which there are many sanctions, for this reason, the resource MAYBE not be able to load

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
@e-shl It's crashing because you're throwing an `Exception` inside the interceptor instead of a `IOException`. Interceptors when throwing exceptions should always use the `IOException`.

Also, remove the separate `authClient` and call stuff with only one `client`, the one already available in the class.
