### ISSUE TITLE
ShavelProiection

### ISSUE THREAD

**Issue by GreenScans** [tachiyomiorg/tachiyomi-extensions#11763]
### Source name

ShavelProiection

### Source link

https://www.shavelproiection.com/

### Language

Italian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme
```kt
dateFormat = SimpleDateFormat("d MMM yyy", Locale("it"))
```

**Comment by GreenScans** [comment]
How long will we have to wait?

**Comment by Soitora** [comment]
> How long will we have to wait?

Until someone decides to work on it. Feel free to do it yourself if you're impatient :)
