### ISSUE TITLE
Hentai20: HTTP error 403

### ISSUE THREAD

**Issue by skysonfire** [tachiyomiorg/tachiyomi-extensions#11770]
### Source information

Hentai20

### Steps to reproduce

Tested all the manga from the top list on tachi and all have the same error. 

I did have "secret class" in my library so when I tried to open web view , the end of the URL was "secret-class-22" then changed to 22 then 24 and it stayed on that. 

### Expected behavior

`

### Actual behavior

`

### Tachiyomi version

0.13.04

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by markuznw** [comment]
Subscribing to this. Still giving CF error and tried everything but it doesn't work

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
