### ISSUE TITLE
MangaLink: New domain 

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#11773]
### Source information

Mangalink 1.2.6 [ar]

### Steps to reproduce

So the website owner lose all his data due to some copyright issue i guess and now they have new domain

### Expected behavior

.

### Actual behavior

![IMG_20220507_125213](https://user-images.githubusercontent.com/61906880/167255263-9bbd0845-e647-4e77-a5ab-4f87c4c473d3.jpg)

### Tachiyomi version

0.13.4

### Android version

11

### Other details
New domain

https://mangalink.io/

Mangalink.org and other domain are dead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
It's not their new domain and this domain is already has been added look for مانجا لينك
