### ISSUE TITLE
Asura Scans: HTTP error 103

### ISSUE THREAD

**Issue by kira1752** [tachiyomiorg/tachiyomi-extensions#11778]
### Source information

Asura scans 1.2.26

### Steps to reproduce

Browse manga on asurascan

### Expected behavior

I could browse manga normally

### Actual behavior

I got http 103 error

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DJLevel3** [comment]
I have the same error, so it's not just one person having it

**Comment by Dook42** [comment]
Ditto

**Comment by arkon** [comment]
Dependant on https://github.com/tachiyomiorg/tachiyomi/issues/6623
