### ISSUE TITLE
Loki Scan

### ISSUE THREAD

**Issue by Asura0818** [tachiyomiorg/tachiyomi-extensions#11787]
### Source name

LOKI SCAN

### Source link

http://series.lokiscan.com/

### Language

Spanish (Es)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Is domain correct? http://series.lokiscan.com/ doesn't work for me, but http://lokiscan.com/ does.

**Comment by Asura0818** [comment]
> ¿Es correcto el dominio? http://series.lokiscan.com/ no me funciona, pero http://lokiscan.com/ sí.

Si, es esa que tu dices
