### ISSUE TITLE
Enigmanga

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#11783]
### Source name

Enigmanga

### Source link

https://enigmanga.com/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Use WPMangaReader

**Comment by BLACKxSUN** [comment]
> Use WPMangaReader

؟

**Comment by TheKingTermux** [comment]
> > Use WPMangaReader
> 
> ؟

Just give a extension theme for another member to work on it

**Comment by BLACKxSUN** [comment]
> 

Sorry but i dont know how to do that

**Comment by TheKingTermux** [comment]
> > 
> 
> Sorry but i dont know how to do that

its okay
Just wait for another member to work it

**Comment by BLACKxSUN** [comment]
> > > 
> > 
> > 
> > Sorry but i dont know how to do that
> 
> its okay Just wait for another member to work it

Hi bro ,Howlong will take?

**Comment by TheKingTermux** [comment]
> > > > 
> > > 
> > > 
> > > Sorry but i dont know how to do that
> > 
> > 
> > its okay Just wait for another member to work it
> 
> Hi bro ,Howlong will take?

I don't know.
Most of the members who contribute to this repository are people who freely contribute, and they are also free to want to do it or not. 
I can only make it if it's in English and Indonesian, and I don't know any other languages.
Sorry can't help.

**Comment by vetleledaal** [comment]
Site has been suspended
