### ISSUE TITLE
Baozimanhua: Support for a mirror alternative URL

### ISSUE THREAD

**Issue by tsunaliew** [tachiyomiorg/tachiyomi-extensions#11791]
### Describe your suggested feature

**Name of the website**
包子漫画 webmota

**Website URLs**
- Site: https://www.webmota.com/
- Manga List: https://www.webmota.com/classify
- Manga example: https://www.webmota.com/comic/feirenzai-fenzihudong
- Chapter online viewer example: https://www.webmota.com/comic/chapter/feirenzai-fenzihudong/0_758.html

**Languages**
List of languages supported by the website
Chinese

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
alternative Sites:
https://www.baozimh.com/

### Other details

From [source](https://github.com/manga-download/hakuneko/issues/4252)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
![Screenshot_20220509-103023853](https://user-images.githubusercontent.com/101858971/167330724-d4e56961-c0f8-40d4-a398-2aefb121e9fc.jpg)
![Screenshot_20220509-103011331](https://user-images.githubusercontent.com/101858971/167330731-c17f0511-7b43-4f08-807e-9e1685d56308.jpg)

What's the different? All I'm see it's same and the extension working fine

**Comment by tsunaliew** [comment]
The website (baozimh.com) was down last weekend, having an alternative url as backup might not be a bad idea. Just a small suggestion.

**Comment by tsunaliew** [comment]
![image](https://user-images.githubusercontent.com/8689637/167403730-395d2868-11a2-4e55-82c7-9e50fbeee5cd.png)
![image](https://user-images.githubusercontent.com/8689637/167403786-90b22449-ac0c-4367-9830-6b226ff181df.png)

As shown above, [baozimanhua](https://www.baozimh.com/) is down again but [alternative baozimanhua](https://www.webmota.com/) is working fine.
