### ISSUE TITLE
Mangakakalot: Apotheosis Duplicate, Missing and not Correctly Ordered Chapters

### ISSUE THREAD

**Issue by Nesaijn** [tachiyomiorg/tachiyomi-extensions#11798]
### Source information

Mangakakalot 1.2.8

### Steps to reproduce

1. Open the manga Apotheosis
2. Go to chapter 412
3. From there on the next like 4 chapters are pairwise duplicate

This is not the case when reading the manga online on [mangakakalot.to](https://mangakakalot.to/apotheosis-ascension-to-godhood-57062). Also the subchapters present in Tachiyomi are not present on the website.

Also chapters jump from point to point like the next chapter after 408 namely 408.2 is actually an earlier chapter. The chapter 409 after that continues where 408 left of but then chapter 409.2 goes again back to the earlier story right what happened at chapter 408.2.

Chapters 435, 436 and 436 are the same as chapters 432, 433 and 434 respectively.

At some parts the ordering is messed up like this and with that the chapter numbers do not match with the right one on the website. Also some seem to be missing.

For example, on the website chapter 417 is at chapter 425 in Tachiyomi and the chapters following on the website (418-420) are missing in the app, so that chapter 421 on web is chapter 426 in the app.

### Expected behavior

Non-duplicate, ordered and non-missing chapters in the Apotheosis manga

### Actual behavior

Duplicate, missing and not correctly ordered chapters in the  Apotheosis manga

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kiriya-aoi** [comment]
We don't have an extension for mangakakalot.to, the extension just called Mangakakalot is mangakakalot.com. You would be better served using the "Open in Webview" button than assuming you actually know the website URL...
