### ISSUE TITLE
A fonte HentaiTeca precisa ser atualizada 

### ISSUE THREAD

**Issue by Hrb002** [tachiyomiorg/tachiyomi-extensions#11805]
### Source information

HentaiTeca 1.2.21

### Steps to reproduce

Navegue até Browse -> HentaiTeca -> Browse / Latest

### Expected behavior

Navegue até Browse -> HentaiTeca -> Browse / Latest -> Show Manga

### Actual behavior

Navegue até Browse -> HentaiTeca -> Browse / Latest -> Show HTTP error 404

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

Obrigado equipe da Tachiyomi 👌🏽
![Screenshot_20220510-001835](https://user-images.githubusercontent.com/104945477/167536046-dde9719d-582a-4985-90b8-91da5ccd0d1d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's nothing we can do about it when they have a high level of Cloudflare protection. Migrate to better sources.
