### ISSUE TITLE
Doujindesu: Domain Changed

### ISSUE THREAD

**Issue by Sandres11** [tachiyomiorg/tachiyomi-extensions#11807]
### Source information

Doujindesu 1.2.2 / doujindesu.xxx

### Steps to reproduce

doujindesu web is not accessible via dns and they have changed their web to something else to be able to use dns

### Expected behavior

I think a list of comics will appear there

### Actual behavior

when I open the extension now an error occurs, and the webview doesn't appear anything

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

the owner of the web already said that doujindesu.xxx cannot be accessed by dns, and they changed the website to https://212.32.226.234 so that it can be accessed with or without dns. I hope tachiyomi staff changes the web link from doujindesu.xxx to https://212.32.226.234 because I don't understand :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZekkenID** [comment]
Same with issue #11401

**Comment by Sandres11** [comment]
> Same with issue #11401

Thankyou
