### ISSUE TITLE
Some errors on Tachiyomi Indonesia 

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#11812]
### Source information

https://telegra.ph/Some-Problems-with-Tachiyomi-Indonesia-05-10

### Steps to reproduce

I opened Tachiyomi and selected all the Extensions and bundled them together so that the problem could be solved.

### Expected behavior

Hopefully the problem can be solved

### Actual behavior

1. Some Websites change the domain
2. Some Comic Websites are dead
3. Failed to break through Cloudflare 

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

Tachiyomi Indonesia

List of Extensions where the website is dead and please delete it immediately
- Davey Scans
- GURU Komik
- Kaisar Komik
- KomBatch
- KomikManga
- KomikSay
- MangaIndonesia
- MangaYu
- Mangceh
- ManhuaID

The following is a list of websites that cannot be accessed because the website owner has changed the domain
- Doujindesu | Current domain -> https://212.32.226.234/
- Mangaku | Current domain -> https://mangaku.site/
- Mangakyo | Current domain -> https://mangakyo.me/
- Mangasusu | Current domain -> https://194.233.87.209/
- MangaSusu | Current domain -> https://194.233.87.209/
- SheaManga | Current domain -> http://62.171.176.78/

List of Extensions that can't penetrate Cloudflare 
- MGKomic

Please put the following Website into Extension on Tachiyomi
- Gudang Komik -> https://gudangkomik.com/
- ManhwaList -> https://manhwalist.com/
- KomikKita -> https://komikita.org/

I apologize if it is made into "txt" form because it will be very inconvenient if you write them one by one in "Issue", please solve this problem. Thank you

Telegraph : https://telegra.ph/Some-Problems-with-Tachiyomi-Indonesia-05-10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You should be opening this in the extensions repository, not in the app one. And also, about the websites using RAW IPs, they won't be changed, since it's not a secure measure to using RAW IPs to access websites instead of domains.

Please open a new issue in the right repository about the ones that can be removed, one individual for each one new you want to be added, and one individual for each one that changed the domain (and is **NOT** using RAW IPs).

**Comment by alessandrojean** [comment]
Sorry, didn't saw it's already in the extensions repo. but the comment above still applies, otherwise keep tracking would be difficult.

**Comment by Satriouz** [comment]
Can you remove the extension I mentioned above? because it's no longer useful

**Comment by alessandrojean** [comment]
Sure, I can take a look into it.

**Comment by TheKingTermux** [comment]
Banyak jg ya 🙂

**Comment by Satriouz** [comment]
Thanks for deleting it. Can URLs with numbers not be entered into Tachiyomi?

**Comment by Satriouz** [comment]
Soalnya banyak Website sudah kati, ketimbang tidak berguna mending di hapus 😞

**Comment by TheKingTermux** [comment]
> Thanks for deleting it. Can URLs with numbers not be entered into Tachiyomi?

You mean IP address ?

**Comment by TheKingTermux** [comment]
> Soalnya banyak Website sudah kati, ketimbang tidak berguna mending di hapus 😞

Bener jg si 🙂

**Comment by TheKingTermux** [comment]
Source Theme for
- KomiKita : ZManga
- ManhwaList : WPMangaReader
- Gudang Komik : Nope idk

**Comment by Satriouz** [comment]
> 

Maksudnya gimana bang 😒
