### ISSUE TITLE
Tinyview Comics

### ISSUE THREAD

**Issue by GemCandy** [tachiyomiorg/tachiyomi-extensions#11813]
### Source name

Tinyview Comics

### Source link

https://tinyview.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Don't think so seems to be only available on the their app.

![image](https://user-images.githubusercontent.com/59261191/167665603-3567081b-01af-4181-bfdb-5e680edb9c0d.png)

**Comment by GemCandy** [comment]
You can read things via the website too, but I do admit, the view is a tad wonky, I do have the app, but I thought it could be easier to put it all in one app, but if it's not possible, welp, thank you for reading none the less 👍
