### ISSUE TITLE
Masterkomik: Chapter images do not load

### ISSUE THREAD

**Issue by julptk** [tachiyomiorg/tachiyomi-extensions#11819]
### Source information

Masterlomik 1.2.15

### Steps to reproduce

1. Started reading
2. image not open
3. 

### Expected behavior

Should be open

### Actual behavior

But it doesn't fit like in the picture

### Tachiyomi version

0.13.4

### Android version

Android 6

### Other details

![Screenshot_20220511-130821](https://user-images.githubusercontent.com/56266781/167781595-b7eeb5b9-33af-481c-a1bd-218912b883bf.jpg)

It doesn't open when setting the image quality to medium or low, but it's fine when using high quality

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
![Screenshot_2022-05-12-11-07-26-54_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/167990553-8f5f04d4-2df3-41de-8b9b-a06ad0ea2aad.jpg)
![Screenshot_2022-05-12-11-08-24-31_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/167990562-aed1941a-845b-4274-b3f1-f042e8b50ca1.jpg)
![Screenshot_2022-05-12-11-08-30-20_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/167990563-310eb23b-3d2a-4da8-ac27-7bcb288351cf.jpg)


Broo it seem fine with me 🙂

**Comment by Riztard** [comment]
it load for me as well
