### ISSUE TITLE
Manhwaindo: HTTP error 404

### ISSUE THREAD

**Issue by Nvbeh6** [tachiyomiorg/tachiyomi-extensions#11817]
### Source information

Manhwaindo

### Steps to reproduce

Open manhwaindo

### Expected behavior

Open usually

### Actual behavior

![Screenshot_2022-05-11-07-52-53-649_eu kanade tachiyomi](https://user-images.githubusercontent.com/103346344/167747794-c7517233-0f29-4017-9bca-501b5c47d67d.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

if you open in webview it will open usually

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Just for sure
The override directory with source.kt must be same at sourcetheme.kt right ?
Is override source.kt is "Manhwa Indo", (source in the src folder) and the sourcetheme.kt is "ManhwaIndo" (source in the theme folder) can it still be run ?

**Comment by alessandrojean** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#multi-source-themes

**Comment by TheKingTermux** [comment]
> https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#multi-source-themes
> 
> You can ask for additional help in the #programming channel on [our Discord](https://discord.gg/tachiyomi).

Thanks bro
I Will ask later on Discord channel 
Because now i'm sick
