### ISSUE TITLE
Please Added Gudang Komik to Source | Bot immediately deletes if added to "Source Request"

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#11827]
### Describe your suggested feature

The bot immediately solves the problem and immediately deletes "Issue", after seeing it, it is added to Toomics which is not relevant, please add this website to Indonesia 

### Other details

Name Ekstension : Gudang Komik
URL -> https://gudangkomik.com/
Language : Bahasa Indonesia 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Same case as the other one, it was a duplicate. Please also use the correct form when requesting sources, you need to fill the source request issue form.
