### ISSUE TITLE
SOURCE REQUESTS: HentaiHere

### ISSUE THREAD

**Issue by hipslover392** [tachiyomiorg/tachiyomi-extensions#1182]
Please add english extension for hentaihere.com. the website is https://hentaihere.com/

**Comment by as280093** [comment]
Here the icons
[HentaiHere.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614400/HentaiHere.zip)

**Comment by Chaotiic28** [comment]
I also request this source. Thanks!
