### ISSUE TITLE
Doujindesu Change Domain

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#11822]
### Source name

Doujindesu

### Source link

https://212.32.226.234/

### Language

Bahasa Indonesia

### Other details

Doujindesu change domain, please change

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read #11439, including the comments.
