### ISSUE TITLE
Please added ManhwaList to Source

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#11826]
### Describe your suggested feature

Please add ManhwaList into Indonesian Extension, I don't understand why bots immediately solve the ManhwaList problem without the completion of inserting Source.

### Other details

Name Ekstension : Manhwa List
ManhwaList : https://manhwalist.com/
Language : Bahasa Indonesia 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It was closed because it is a duplicate, read the message. Someone already requested it before and it wasn't added yet, you need to wait.
