### ISSUE TITLE
Komik Kita

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#11825]
### Source name

Komik Kita

### Source link

https://komikita.org/

### Language

Bahasa Indonesia 

### Other details

Please added this web

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Hhmm........ Perasaan dah bilang klo req 3 ekstensi deh di #11812  🤣
Tpi gpp berhubung yg disitu di close biar di up lgi dah 🤣
Yg mau di req tadi masukin sini aja
Ganti judulnya ke "Add some Indonesian source"
Tpi berhubung yg Gudang Komik w gatau tema yg dipake apa jdi ya....... Nunggu org lain ya yg buat 😌

**Comment by Satriouz** [comment]
Disuruh buat ulang gan

**Comment by Satriouz** [comment]
ZManga apaan sih 😒
Memangnya Ekstensi itu ada?

**Comment by arkon** [comment]
This isn't a discussion forum.
