### ISSUE TITLE
Nhentai: persistent filter setting

### ISSUE THREAD

**Issue by soramui** [tachiyomiorg/tachiyomi-extensions#11838]
### Describe your suggested feature

Filter preference doesn't reset when reopening the extension. For example, if i set it to sort by recent and exclude tag X, then it will sort by recent and exclude tag X when i reopen the extension later.

Alternatively, make a setting to set the initial filter, currently it's by default is always empty and sorted by all time popular and can't be changed as far as i know. Even just a setting so that i can by default sort by recent would be nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
probably has to be done on the app level, and also already [requested](https://github.com/tachiyomiorg/tachiyomi/issues/1484)
