### ISSUE TITLE
Pin a favorite manga to the top of the category 

### ISSUE THREAD

**Issue by tatosgr** [tachiyomiorg/tachiyomi-extensions#11833]
### Describe why this should be added

I have a lot of different titles I'm currently reading, but I would like to have a way to pin an specific title to top so whenever that title get updated I'll see it at the top, obviously.

Those could be used by category, I guess.

If there is a way to do this that is already implemented please let me know, and thank you. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
not related to extensions and yes it can be done with categories, also already [requested](https://github.com/tachiyomiorg/tachiyomi/issues/3656)
