### ISSUE TITLE
A list for completed titles

### ISSUE THREAD

**Issue by tatosgr** [tachiyomiorg/tachiyomi-extensions#11837]
### Describe why this should be added

I keep a small list of my read titles on Google keep, but it would be nice just to have a section with a way to search for a title, regardless of the source, and mark it as read. A personal list that could be backed up with that rest of the stuff that are already 

I don't know if that possible, but it would a good addition, I hope. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
this does not seem to have anything to do with extensions, but you can possibly use a tracker or categories and put your completed titles in there.
