### ISSUE TITLE
DapRob

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11831]
### Source name

DapRob

### Source link

https://daprob.com/

### Language

Español

### Other details

![Screenshot_20220512-152043_Opera](https://user-images.githubusercontent.com/101371218/168170112-4792c19a-9b28-46d3-af2a-345ca8a5e891.jpg)

![Screenshot_20220512-152058_Opera](https://user-images.githubusercontent.com/101371218/168170118-3d22ef60-ceb1-4732-9cbe-7de2ce577b0e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme
```kt
dateFormat = SimpleDateFormat("dd/MM/yyy", Locale.US)
```
