### ISSUE TITLE
Clarify that Page.url should be absolute

### ISSUE THREAD

**Issue by kasperskier** [tachiyomiorg/tachiyomi-extensions#11845]
It should be clarified that `Page.url` should be absolute:
https://github.com/tachiyomiorg/extensions-lib/blob/150ba5f7c56c954c5ca3d0b2cfc5a974aa35f766/library/src/main/java/eu/kanade/tachiyomi/source/model/Page.kt#L5-L10

which is filled by these methods in `HttpSource`:
https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/source/online/HttpSource.kt#L238-L266

because this method does not prepend base URL:
https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/source/online/HttpSource.kt#L280-L288

while other request methods assume relative URL, which is confusing.

**Comment by arkon** [comment]
Moving to the extensions repo. We should include this in the contributing doc there.
