### ISSUE TITLE
Unable to read or download chapters from these sources

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#11846]
### Source information

FR Scan 1.2.6, Jpmangas 1.2.6, Lelscan-VF 1.2.5

### Chapter reading case

1. Open one of the sources mentioned int source information in the extension list
2. Select one of the manga
3. Select one of the chapters
4. The viewer opens up and start to load the pages
5. The message "The image could not be loaded" appears with the button retry
6. Push the button Retry
7. After trying to load images the same message appears

### Chapter downloading case

1. Open one of the mentioned sources and select a manga or choose a manga from one of those sources
2. Click the download button of a chapter
3. The download starts and stays at 0

### Chapter reading case

Open the chapter load the pages and read the chapter.

### Download reading case

Click the download button and download the chapter to completion.

### Chapter reading case

The reader shows the "The image could not be loaded" message with the option to retry

### Chapter downloading case

The download starts at 0 and stays at zero

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

The expected can happen for both cases by opening the WebView of the manga and loading a chapter there, however only the pages loaded in the WebView will be loaded in the reader or downloaded afterwards. Killing or exiting the app bring us back to square one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one ticket per source, otherwise keep tracking of what have already been addressed and what not becomes difficult.
