### ISSUE TITLE
Hentai Kai may now return to the extension repertoire

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#11841]
### Source information

Hentai Kai

### Steps to reproduce

1- Find it normally in extensions.
2- Open the chapters normally.

### Expected behavior

Open the chapters normally.

### Actual behavior

currently obsolete extension.

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

Previously this extension was removed for hiding chapters, which they are currently not doing anymore, so I believe the extension could come back. 

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10087#issuecomment-992047028

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This isn't a bug since the extension don't exist anymore. Please open an source request instead.
