### ISSUE TITLE
iiManga: Update manga details gets stuck in loop

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi-extensions#11844]
### Source information

iiManga (AR) v1.2.13

### Steps to reproduce

Update any manga manually.

### Expected behavior

Finish update normally.

### Actual behavior

The update will stay running non-stop. 
Which might cause additional network request for the source.
Force close didn't help to stop the update.

### Additional Info

I noticed that updating the manga page doesn't work, it get's stuck on a loading loop. **But updating the manga from the global update will work normal**. Not sure why. 

Just to clarify, the update actually pulls the chapter list normally but it wouldn't finish the update, I guess because it wasn't able to pull the cover image or update the rest of manga details?

I have tried to force close the app but the update process is still running when I opened the manga details which might cause additional network request for the source.

_Originally posted by @saud-97 in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11532#issuecomment-1112730461_

**Comment by saud-97** [comment]
Please add the [bug] tag since this was auto created via a comment it wasn't through the normal issue workflows.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
