### ISSUE TITLE
Jpmangas: Unable to read or download chapters

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#11853]
### Source information

Jpmangas v1.2.6

### Steps to reproduce

**_Chapter reading case_**

1. Open one the source the extension list
2. Select one of the manga
3. Select one of the chapters
4. The viewer opens up and start to load the pages
5. The message "The image could not be loaded" appears with the button retry
6. Push the button Retry
7. After trying to load images the same message appears

**_Chapter downloading case_**

1. Open the source and select a manga or choose a manga from one of those sources
2. Click the download button of a chapter
3. The download starts and stays at 0

### Expected behavior

**_Chapter reading case_**

Open the chapter load the pages and read the chapter.

**_Download reading case_**

Click the download button and download the chapter to completion.

### Actual behavior

**_Chapter reading case_**

The reader shows the "The image could not be loaded" message with the option to retry

**_Chapter downloading case_**

The download starts at 0 and stays at zero

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

The expected behavior can happen for both cases by opening the WebView of the manga and loading a chapter there, however only the pages loaded in the WebView will be loaded in the reader or downloaded afterwards. Killing or exiting the app bring us back to square one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
