### ISSUE TITLE
Reset Scans: Wrong timestamps on some series

### ISSUE THREAD

**Issue by staudond** [tachiyomiorg/tachiyomi-extensions#11862]
### Source information

Reset Scans 1.2.25

### Steps to reproduce

1. Open Reset Scans source
2. Select any series
3. The timestamps are either correct or shows todays date on all chapters

### Expected behavior

The timestamps should be same as on website

### Actual behavior

The timestamps on website are different than in app.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

The timestamps are correct for some series like "The Ultimate of All Ages" or "The Unwanted Undead Adventurer" and wrong for others like "Dungeon Reset" or "The Gamer".
![correct timestamps](https://user-images.githubusercontent.com/36927218/168421440-ebd3261b-c57f-4078-bbd2-93c4e9bf8a27.jpg)
![incorrect timestamps app](https://user-images.githubusercontent.com/36927218/168421437-4813c6b6-6699-4151-a6fb-2db76c6ffecc.jpg)
![incorrect timestamps web](https://user-images.githubusercontent.com/36927218/168421438-88b2683f-a51a-43ac-a1f1-03f8ff16ae10.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
nothing we can do, they didnt include the year in their timestamp
and tachi need full timestamp. it will become 1970 
maybe you should ask them to add year to the chapter timestamp
