### ISSUE TITLE
Ryukonesia

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#11865]
### Source name

Ryukonesia

### Source link

https://ryukonesia.net/

### Language

Indonesia 

### Other details

![Screenshot_2022-05-14-23-03-33-183_com UCMobile intl](https://user-images.githubusercontent.com/23666289/168429168-f9c4684c-edb9-4be8-a439-866b3297f286.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
I think it use WPMangaStream theme 
But Im not sure for that 🤔
But it seem pretty similar 🤔
Correct me of im wrong 😌
