### ISSUE TITLE
Mangabat: NXDOMAIN

### ISSUE THREAD

**Issue by minaxn** [tachiyomiorg/tachiyomi-extensions#11867]
### Source information

Mangabat 1.2.9

### Steps to reproduce

1. Tachiyomi tries to update the new chapter
2. The update got through
3. 2/3 of the favorited mangas can't update because tachiyomi can't find the source
4. error code NXDOMAIN

### Expected behavior

The mangas should update correctly

### Actual behavior

![Screenshot_20220515-050908_HTML Viewer](https://user-images.githubusercontent.com/105567837/168449599-3667a8a5-cb74-4f03-b9eb-62820705e411.jpg)

### Tachiyomi version

0.13.4.

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kyrieze** [comment]
Changed from read.mangabat.com to readmangabat.com, that leads to nxdomain, waiting for ext update

**Comment by minaxn** [comment]
but how can i migrate all of my mangas, all at once?? Is there a way??

**Comment by Kyrieze** [comment]
> but how can i migrate all of my mangas, all at once?? Is there a way??

Idk with vanilla tachiyomi, but I think there's a button there, I used Tachi fork by J2K, it has migrate all manga from a source on the migrate menu, good luck!

**Comment by minaxn** [comment]
I'm  using vanilla, guess time to migrate them one by one

**Comment by Kyrieze** [comment]
Backup all your tachi data, restore it on the tachi forks, it's works well :)

**Comment by minaxn** [comment]
Thx man
