### ISSUE TITLE
MangaStic: HTTP error 400

### ISSUE THREAD

**Issue by ratenS** [tachiyomiorg/tachiyomi-extensions#11879]
### Source information

MangaStic 1.2.20

### Steps to reproduce

1. Install MangaStic extension
2. Open MangaStic extension
3. Open Webview

### Expected behavior

The manga list should load like normal.

### Actual behavior

"HTTP error 400: Check website in WebView" error is shown.
And when viewed in WebView, instead of MangaStic, I get redirected to another website called Pukamanga.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by specterflare** [comment]
@alessandrojean The site moved to MangaStic.me, which was registered [like two months ago](https://www.whois.com/whois/mangastic.me).

**Comment by alessandrojean** [comment]
> The site moved to MangaStic.me, which was registered [like two months ago](https://www.whois.com/whois/mangastic.me).

Okay, but no need to ping me for that, I guess. Someone will take a look and fix it eventually if anyone wants to work on it.
