### ISSUE TITLE
kraw.org

### ISSUE THREAD

**Issue by onmyouji** [tachiyomiorg/tachiyomi-extensions#11871]
### Source name

kraw.org

### Source link

https://kraw.org

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Use WPMangaReader

**Comment by arkon** [comment]
@TheKingTermux Can you phrase your comments like "Uses xyz theme" in the future to avoid confusing people reading the issues that aren't familiar with how they work?

**Comment by TheKingTermux** [comment]
> 

Okay
Thanks for updating my comment
And thanks for telling me too
