### ISSUE TITLE
Baozimanhua: No pages found

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#11880]
### Source information

Baozhimanhua 1.2.3

### Steps to reproduce

1. Open baozhimanhua 我养成了一个病弱皇子
2. Open chapter 65, it shows no chapter
3. Open through webview, it show the image

### Expected behavior

It shoukd show pages and able to download

### Actual behavior

It shows no pages

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Radio028** [comment]
I have same issue on this source for all the Manga contents.
