### ISSUE TITLE
MangaDex: Cover does not load in a particular title

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#11886]
### Source information

MangaDex 1.2.158

### Steps to reproduce

Open extension
Find series Heavenly Jewel Change
No Cover despite having one in webview

### Expected behavior

Should have cover

### Actual behavior

Cover breaks

### Tachiyomi version

0.13.4

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As noticed by @curche, the cover file is probably wrongly renamed to JPEG.

```console
$ wget https://mangadex.org/covers/5949f68d-9202-40e8-bfbc-fc16e1849058/014330a0-1fc9-47a6-9a7a-5b17f500ff52.jpg
---
2022-06-09 22:59:17 (2.69 MB/s) - ‘014330a0-1fc9-47a6-9a7a-5b17f500ff52.jpg’ saved [1048576/1048576]

$ file 014330a0-1fc9-47a6-9a7a-5b17f500ff52.jpg 
014330a0-1fc9-47a6-9a7a-5b17f500ff52.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=12, height=840, bps=0, PhotometricIntepretation=RGB, orientation=upper-left, width=630], progressive, precision 8, 630x840, components 3
```

This is something that needs to be fixed on Dex's side.
