### ISSUE TITLE
Mangabat: Unable to resolve host

### ISSUE THREAD

**Issue by Kuroma974** [tachiyomiorg/tachiyomi-extensions#11883]
### Source information

Mangabat 1.2.9

### Steps to reproduce

1 Open tachiyomi 
2 Go on a bookmarked manga that has been bookmarked for more than 1 week (as the time of 16/05)
3 Try to refresh chapters

### Expected behavior

Update manga from mangabat

### Actual behavior

Show error - Unable to resolve host "read.mangabat.com": No address associated with hostname

### Tachiyomi version

0.13.4

### Android version

10

### Other details

They probably changed urls for most of the ones i read (629) but some are still working

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Lightjohn** [comment]
Can confirm most of my Mangabat subscriptions are not refreshed because of that bug.

**Comment by specterflare** [comment]
The site has changed to [m.mangabat.com/m](m.mangabat.com/m). See the [announcement banner cached by SimilarWeb](https://www.similarweb.com/website/read.mangabat.com).

**Comment by Theo-Bradley** [comment]
If you migrate each broken manga, and just select the same manga under the mangabat source it fixes the issue.

**Comment by Lightjohn** [comment]
I thought of that but migrating my 75+ mangas will take time. Can we expet an upgrade to fix that?

**Comment by Wildvine45** [comment]
I have like 100+ manga stuck in mangabat 

will this be fix if the app is updated or is the site it self is the problem?

**Comment by dns2887** [comment]
The bug because the url read.mangabat.com got DNS probe error.
The correct URL is either readmangabat.com or m.mangabat.com.

Hope the fix come as soon as possible.

**Comment by Seishirou101** [comment]
The url currently is m.mangabat.com, but they like to change urls. Migrate them back into mangabat or use another source.
