### ISSUE TITLE
Mangadex java.security.cert.certpathvalidatorexception: Trust anchor certification path not found.

### ISSUE THREAD

**Issue by Nidaime-erosennin** [tachiyomiorg/tachiyomi-extensions#11895]
### Source information

Mangadex 1.2.158

### Steps to reproduce

1. Open Tachiyomi
2. Go to the extension
3. Open webview
![Screenshot (May 17, 2022 10_24_10 AM)](https://user-images.githubusercontent.com/105691884/168722181-30632c57-ce1d-47ac-a40a-24bda17f5565.jpg)
![Screenshot_20220517-102202](https://user-images.githubusercontent.com/105691884/168722194-6eba121b-dfa0-4f84-90f7-a66a7135d98e.jpg)
w

### Expected behavior

It should've load the mangalist and open the website on webview.

### Actual behavior

Got a java.security.cert.certpathvalidatorexception: Trust anchor certification path not found message instead. Also unable to update manga.

### Tachiyomi version

0.13.4

### Android version

Android 6.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you need to manually install a certificate on your device:

1. Download the certificate from https://letsencrypt.org/certificates/ (Active → ISRG Root X1 → Self-signed → pem)
2. Install the certificate by following https://support.google.com/pixelphone/answer/2844832?hl=en (exact settings path may differ on your device)

If you need more help, you can go on discord and ask in #support

**Comment by Nidaime-erosennin** [comment]
Thank you. That solved it.
