### ISSUE TITLE
FR: MangaDex: Include "last chapter" info

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi-extensions#11898]
### Describe your suggested feature

On the MangaDex website, Manga that have ended publication have a "Last chapter" listed that shows the Volume and Chapter of the final release. I believe implementing this would be nice. 
This could also be used to supplement the "status", when it is unknown, but there is a last chapter listed, then it could be set as completed, or as no fully translated. 

### Other details

API location: `MangaAttributes/lastVolume` and `MangaAttributes/lastChapter`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> This could also be used to supplement the "status", when it is unknown, but there is a last chapter listed, then it could be set as completed, or as no fully translated.

The extension already does that to mark things as completed currently IIRC. But it should be doable to show that information somewhere, maybe in the description.

**Comment by mm12** [comment]
> The extension already does that to mark things as completed currently IIRC. But it should be doable to show that information somewhere, maybe in the description.

Thats weird, I see plenty of manga that have a final chapter listed but have the status "unknown". I thought that used `MangaAttributes/status`

**Comment by alessandrojean** [comment]
> I thought that used `MangaAttributes/status`

[It does](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt#L76-L98).

**Comment by CarlosEsco** [comment]
Once extensions lib 1.3 is implemented we can show publication complete.  As Alessandro said if you marked it complete then it would be excluded from future uploads as "complete" in tachiyomi means scanlated completely.

As for last chapter that only shows on the actual chapter on dex, and would look weird to append it to manga info and make the description look out of place.   For example
 https://mangadex.org/title/92bce3bb-3da7-42f2-bc69-4c8dbe6bf226/maou-to-ore-no-hangyakuki 
 doesnt show last chapter

**Comment by mm12** [comment]
> Once extensions lib 1.3 is implemented we can show publication complete. As Alessandro said if you marked it complete then it would be excluded from future uploads as "complete" in tachiyomi means scanlated completely.
> 
> As for last chapter that only shows on the actual chapter on dex, and would look weird to append it to manga info and make the description look out of place. For example https://mangadex.org/title/92bce3bb-3da7-42f2-bc69-4c8dbe6bf226/maou-to-ore-no-hangyakuki doesnt show last chapter

haha, been meaning to read that one. 

The one you linked _does_ show the last chapter though: (Left sidebar, bottom)
<img width="297" alt="Screen Shot 2022-05-18 at 11 26 45AM" src="https://user-images.githubusercontent.com/5874051/169094014-337a12e2-67af-490d-8226-9b0d34c95d21.png">
So I am a bit confused

**Comment by CarlosEsco** [comment]
somehow missed that earlier.  But either way. No plans to add that to the description
