### ISSUE TITLE
Comicastle: Chapter images does not load

### ISSUE THREAD

**Issue by lilfoxbear** [tachiyomiorg/tachiyomi-extensions#11900]
### Source information

Comicastle 1.2.3

### Steps to reproduce

1. Add thing to library
2. Try to read a few pages
3. Loading stops
4. Press retry... nothing

### Expected behavior

All the pages should load without issue.

### Actual behavior

It tried to load but eventually just goes back to the retry button. Even previous pages that loaded stop loading.

### Tachiyomi version

 0.12.3 

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lilfoxbear** [comment]
Tried to update the app and the issue still happens.

**Comment by Riztard** [comment]
load just fine for me
