### ISSUE TITLE
Reaper Scans ID: HTTP error 500

### ISSUE THREAD

**Issue by libran07** [tachiyomiorg/tachiyomi-extensions#11902]
### Source information

Reaper Scans 1.2.25

### Steps to reproduce

Browse > Open Reaper Scans Indonesian version > HTTP error 500

### Expected behavior

Manga list should appear.

### Actual behavior

Manga list not showing, 
but open in webview still working fine.

![a671c66b-3b11-401f-aa90-172719587339](https://user-images.githubusercontent.com/90138720/168979748-c2ece438-ed12-4bf9-bace-ef62b2352392.jpg)

### Tachiyomi version

TachiJ2k  1.5.2

### Android version

Android 7.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their website is broken and there's nothing that can be done on the extension side to fix it. Try opening one series in WebView and you will see a server side error. Wait until they fix it.
