### ISSUE TITLE
xCaliBR Scans: HTTP error 103

### ISSUE THREAD

**Issue by jrmgrz** [tachiyomiorg/tachiyomi-extensions#11907]
### Source information

XCaliBR Scans 1.2.17

### Steps to reproduce

When i open the source it shows http error 103. Check in webview (by the way it's working fine both on webview and browser

### Expected behavior

It should be okay when I open the source, I already tried all **troubleshooting** methods. it have cloudflare protection on site but I already bypassed it both on **webview** and in **browser**

### Actual behavior

I don't know where the http 103 error came from, if the issue is about cloudflare ddos protection it should be "**failed to bypass the cloudflare**" or something like that.

### Tachiyomi version

1.5.3

### Android version

Android 8

### Other details

Reading both on webview and browser is working

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by oCallMeViper** [comment]
Facing the same issue, wanted to ask #support on their discord , but i don't have permission, don't know how discord works. Need help ASAP. Regards

**Comment by kaizerboo** [comment]
Having same issue as well, think I had it for over a week

**Comment by vetleledaal** [comment]
wait for tachiyomiorg/tachiyomi#6623

**Comment by 8227846265** [comment]
I'm having the same issue as well.

I recorded the problem as well:
https://imgur.com/AXkXuHc

**Comment by Hellferion** [comment]
I have the issue on all forks of tachiyomi including original

**Comment by arkon** [comment]
Dependant on https://github.com/tachiyomiorg/tachiyomi/issues/6623
