### ISSUE TITLE
Colored Manga: No pages found

### ISSUE THREAD

**Issue by KenZaraki21** [tachiyomiorg/tachiyomi-extensions#11911]
### Source information

Colored Manga 1.2.21

### Steps to reproduce

1. Go to any manga in the library that is from coloredmanga.com
2. Download a chapter

### Expected behavior

The chapter should start downloading.

### Actual behavior

It says on my notification: No pages found. I tried the other chapters and other manga from coloredmanga but it's the same. Tried on Manganato and it works just fine.

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EstebanOD** [comment]
Can't even search for mangas in my case

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
