### ISSUE TITLE
Neox Scanlator: Changed the domain

### ISSUE THREAD

**Issue by luzfcb** [tachiyomiorg/tachiyomi-extensions#11914]
### Source information

Neox Scanlator

### Steps to reproduce

Try to navigate on Source . Nothing will be showed

### Expected behavior

Have a fully functional extension

### Actual behavior

the app does not update information about chapters and it is not possible to view the content of new chapters of the Neox Scanlator source, because the Neox Scanlator has changed the website domain.

The Neox Scanlator changed the domain
from: https://neoxscans.net
to: https://neoxscan.net

Note: For weeks, the old domain shows a message informing maintenance

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> A **Neox** mudou de domínio recentemente e isto está causando alguns erros na extensão, tal como **HTTP error 530** e similares. Para arrumar temporariamente, altere a URL de `https://neoxscans.net` para `https://neoxscan.net` em **Navegar → Extensões → Neox → Botão com engrenagem ⚙️ → URL da fonte** e reinicie o aplicativo. Alternativamente, você pode esperar por uma atualização na extensão se preferir.

Faça isso enquanto a extensão não é atualizada.
