### ISSUE TITLE
reading adjustment

### ISSUE THREAD

**Issue by bgmondy** [tachiyomiorg/tachiyomi-extensions#11912]
### Describe why this should be added

![Screenshot_2022-05-19-16-12-35-62](https://user-images.githubusercontent.com/76152689/169263005-f94d5a57-bae7-419f-8d27-1ff825d8d821.png)
this pict I screen Shot from tachi but have line distance between pict.

![Screenshot_2022-05-19-16-21-44-50](https://user-images.githubusercontent.com/76152689/169263382-1e05a7cf-6d90-4a08-8498-a5172a49612d.png)
then this pict I SS from comic screen no have line from distance.

I think we must fix that To narrow down the images on webtoon mode

### Other details

the difference is rarely between the image that gives the line when reading is even subtle but very obvious when taking screen shot

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Wrong repo
