### ISSUE TITLE
Nhentai (All) | add language filter bar

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#11919]
### Describe your suggested feature

I would like to filter out all the chinese translated contents, i know japanese and english but there is no way to filter out only chinese translated entries.

### Other details

they fill the results with useless duplications.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Use `-language:chinese` while searching?

**Comment by Palloxin** [comment]
> Use `-language:chinese` while searching?

doesn't work with tge save filter of tachisy, also too long to type

**Comment by jobobby04** [comment]
This is impossible since the NHentai search requires a search tag before it can exclude specific searches. You can't do `-chinese` without first searching for a specific thing. An example would be: `"big breasts" -chinese` would work, just `-chinese' would not.

**Comment by arkon** [comment]
Use the language specific sources. 

If you have an issue with SY-specific delegation behaviour, it doesn't belong in this repo.

**Comment by Palloxin** [comment]
i just mentioned tachisy, i don't have an issue with it. i want to mix english AND japanese without chinese, that is why i mentioned nhentai (all). not a specific one

**Comment by arkon** [comment]
No because it's already been explained why it isn't possible. Open another issue if the site behaviour ever changes.

**Comment by Palloxin** [comment]
mm, can't be added a conditional bar (language) that activates only if the tag bar has an include tag? i mean "you can write if the bar if the tag bar is empy" or something @jobobby04
