### ISSUE TITLE
Lala Manga

### ISSUE THREAD

**Issue by yurishein** [tachiyomiorg/tachiyomi-extensions#11923]
### Source name

Lala manga

### Source link

https://lalamanga.com/

### Language

English

### Other details

I have researched it in extension list but did not appear. It has a duplicate issue but i haven't seen the source in the source list in the webaite and also in app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by yurishein** [comment]
The source is it seen in the source list although it has duplicate issue and is closed and completed. I did not see the source name when i search it in the source list. Pls view it again wether the source is added or not.

**Comment by alessandrojean** [comment]
Your request is a duplicate of another request, that's why it was closed. The other request is still open so it was not added to the extensions list, and we can't provide an ETA on that either.

**Comment by yurishein** [comment]
Ohhhh tysm for replying i thought it was closed or completed. Thank you for informing me hehe
