### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by Boonni** [tachiyomiorg/tachiyomi-extensions#11932]
### Source information

MangaNelos.com 1.2.2

### Steps to reproduce

1. I open the app
2. Select a manga from the library
3. Press start or select a chapter
4. "HTTP error 500"

### Expected behavior

It should start the chapter

### Actual behavior

it said "HTTP error 500"

### Tachiyomi version

0.13.4

### Android version

6.0.1

### Other details

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 6.0.1 (SDK 23)
Device brand: OPPO
Device name: CPH1613

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
HTTP error 500 is their server issue, and now its working
