### ISSUE TITLE
مانجا نون

### ISSUE THREAD

**Issue by esraahassan2151** [tachiyomiorg/tachiyomi-extensions#11945]
### Source name

مانجا نون

### Source link

https://en.m4cut.com/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Manga Fun theme, which is new to Tachiyomi

**Comment by shipoxx** [comment]
New url
https://manganoon.com/

update your request

**Comment by alessandrojean** [comment]
Will not be added as per #13866, the scanlator team requested the extension removal.
