### ISSUE TITLE
Neox Scanlator: Too many follow up requests

### ISSUE THREAD

**Issue by dokjyoo** [tachiyomiorg/tachiyomi-extensions#11953]
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

1. Download
2. Error: Too Many Follow up Requests: 21

### Expected behavior

the download should happen

### Actual behavior

but the error: Too Many Follow Up Requests: 21 actually happen

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
From the Discord server #status-updates:

> A **Neox** mudou a URL deles novamente. Altere a URL da fonte de `https://neoxscan.net` para `https://neoxscans.net` em **Navegar → Extensões → Neox → Botão com engrenagem ⚙️ → URL da fonte**. Não é garantido que procedimento funcione. Migre para fontes melhores que não tenham esse péssimo hábito pois a extensão será potencialmente removida em breve.
