### ISSUE TITLE
Argos Scan: Changed their API schema

### ISSUE THREAD

**Issue by brunul** [tachiyomiorg/tachiyomi-extensions#11950]
### Source information

Argos Scans 1.2.20

### Steps to reproduce

1. Click on any series from Argos Scan extension
2. Try to refresh the selected manhwa/manga

### Expected behavior

It should list/download the the latest chapters

### Actual behavior

Get error on refresh

![photo_2022-05-23_14-11-34](https://user-images.githubusercontent.com/11947789/169872556-d6b8dc0c-5e1a-4103-b58d-424e16f69204.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Raidre** [comment]
it's taking a while to update the scan there was a problem admin

**Comment by alessandrojean** [comment]
> it's taking a while to update the scan there was a problem admin

There's no ETA, this is an open source project that people contribute when they have time.

**Comment by alessandrojean** [comment]
I will take a look into fixing this probably this weekend.
