### ISSUE TITLE
Neox Scanlator: Missing chapter titles

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#11954]
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

1- Sources menu
2- Tap the Neox Scanlator font name to enter
3- See the Mangas
4- Enter any manga

### Expected behavior

See manga chapters

### Actual behavior

When I update the manga the chapters disappear and only the day it launched remains
![Screenshot_20220523-232617_Tachiyomi](https://user-images.githubusercontent.com/82852543/169947561-1fa7a992-cb24-48f0-a653-0a54eb51fa4a.png)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

I think Neox Scanlator changed domain https://neoxscans.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> the domain changed again for the old one

There's another open issue for that.

**Comment by Kaylenna** [comment]
> They're changing a few things, the domain changed again for the old one ( https://neoxscans.net/ ) and I believe they may have changed a little the layout of the website ( not sure cause I don't use the website anymore, just the tachiyomi and forks )

The site layout has changed yes

**Comment by Kaylenna** [comment]
> e acredito que tenham mudado um pouco o layout do site ( não tenho certeza porque não uso o site mais, apenas o tachiyomi e os garfos)

The site layout has changed yes

**Comment by Kaylenna** [comment]
> and I believe they may have changed a little the layout of the website ( not sure cause I don't use the website anymore, just the tachiyomi and forks )

The site layout has changed yes

**Comment by MicOliv** [comment]
Sim, o layout mudou e agora os títulos e os números não aparecem mais

**Comment by MicOliv** [comment]
Yes, the layout has changed and the title and numbers no longer appear
