### ISSUE TITLE
Comick.fun use publication status  instead of translation status

### ISSUE THREAD

**Issue by Ziyadisalive** [tachiyomiorg/tachiyomi-extensions#11955]
### Source information

Comics.fun 1.2.9

### Steps to reproduce

I've noticed a problem with comick.fun , the issue is the manga status that it flags manga with,

So if a manga has finished serialisation in Japan, but has not been entirely translated, tachi uses the serialisation status and marks the manga as completed, meanwhile it's still receiving translations

So, can this be fixed?

### Expected behavior

The one that should be shown in tachi should be the translation status

### Actual behavior

But it shows the manga serialisation status instead

### Tachiyomi version

Tachiyomi SY 1.8.3 standard

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
/edit-title "Comics.fun use translation status instead of publication status"

**Comment by edgehub-cloud** [comment]
Method kotlinx.serialization.json.JsonElement eu.kanade.tachiyomi.extension.all.comickfun.ComickFun$mangaDetailsParse$$inlined$jsonFlatten$1.transformDeserialize(kotlinx.serialization.json.JsonElement) overrides final method in class Lkotlinx/serialization/json/JsonTransformingSerializer; (declaration of 'eu.kanade.tachiyomi.extension.all.comickfun.ComickFun$mangaDetailsParse$$inlined$jsonFlatten$1' appears in /data/app/~~zHiUN9azxvYbLNU5jn7Fbw==/eu.kanade.tachiyomi.extension.all.comickfun-ABPiyF9MLoTY0hTOpc_UjQ==/base.apk)
  # Comick.fun (EN)



Is this the errors?

**Comment by Ziyadisalive** [comment]
I have no idea what this means💀
