### ISSUE TITLE
MangaDig: Decryption failed

### ISSUE THREAD

**Issue by Beji-kun** [tachiyomiorg/tachiyomi-extensions#11968]
### Source information

MangaDig 1.2.2

### Steps to reproduce

1.Open comic
2. Select chapter what read / download 
3. Get bug Decryption failed

### Expected behavior

Chapter will be open or can download

### Actual behavior

Page closed immediately and showed "Decryption failed". Any error code not showing. It's unable read or download. 1 or 2 months ago have problem with cloudflare protection but now it's end this protection. But I can read it. Can you please repairs. There is only manga comics which isn't any others site in complete.
![Screenshot_2022-05-25-02-10-37-012_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/63636174/170152809-6c3f8e40-2720-4804-989a-636896fb4ec3.jpg)

Link to videos bug
https://drive.google.com/drive/folders/1XUnVslGVo5Ge1QpAZ6u91PTw5_n1YcWW

### Tachiyomi version

J2K 1.5.4 and Stable 0.13.4

### Android version

Android 12

### Other details

Cloudflare bypass is remove on this site. I try on my laptop, other phone and don't get it. But extension is broken. Can you please repair when **Cloudflare protection is now over** (**so only problem is this decryption failed process**) 🙂🙂🙂🙏🙏🙏
This site have manga comics when I can't find any other extension or site on internet. 
Thanks very much repairs ☺️☺️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Beji-kun** [comment]
Hi is there anybody which can tell about this bug 😅? It's almost week without assigned to anybody or comment.
Thanks

**Comment by poorloading** [comment]
getting this also

**Comment by dtantono** [comment]
me too as well

**Comment by MikeZeDev** [comment]
If the maintainer is interested i was able to extract the first two keys from the website (for the 2 slots array).
I still have to figure out the third one, damn devtool detection :D
