### ISSUE TITLE
Ninemanga gone down (potentially changed domain)

### ISSUE THREAD

**Issue by winkelnp** [tachiyomiorg/tachiyomi-extensions#11961]
### Source information

NineManga 1.2.16

### Steps to reproduce

1. Install NineManga extension
2. Try to browse/ open a manga / open webview

### Expected behavior

Manga list loads / manga loads / webview loads

### Actual behavior

Error / Error / Redirected to a garden supplies website

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
The extension works perfectly. Work normally.
