### ISSUE TITLE
add source "https://enigmanga.com/"

### ISSUE THREAD

**Issue by TachiApp** [tachiyomiorg/tachiyomi-extensions#11964]
### Source name

enig manga

### Source link

https://enigmanga.com/

### Language

"Arabic"

### Other details

web: https://enigmanga.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TachiApp** [comment]
Not issues deplicate

**Comment by alessandrojean** [comment]
It is a duplicate, there's another issue requesting this same website already open.

**Comment by TachiApp** [comment]
No, I thought it was not uploaded , the site is working for me!

[Uploading z2{3b4aa89} (ecf0976f-cc06-4a5a-b350-fcc8fdc0e250 id=0x7f0a03c2 tag=BaseCommentFragment) …]()
