### ISSUE TITLE
Source Request: niceoppai

### ISSUE THREAD

**Issue by altinat** [tachiyomiorg/tachiyomi-extensions#11969]
### Source name

niceoppai

### Source link

https://www.niceoppai.net/

### Language

Thai

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by altinat** [comment]
it's a duplicate issue but it's still no source added

**Comment by alessandrojean** [comment]
The referenced issue is still open, so it was not added yet. You need to wait until someone wants to work on it.
