### ISSUE TITLE
too many follow -up requests:21

### ISSUE THREAD

**Issue by Mkzinscans** [tachiyomiorg/tachiyomi-extensions#11979]
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

1. Não está dando para acessar os mangas da fonte neox scans 

### Expected behavior

Deveria dar para baixar e ler os mangas da fonte neox scans

### Actual behavior

Não está abrindo ou dando para baixar mangas pela fonte neox scans

### Tachiyomi version

0 13.4

### Android version

Android 11

### Other details

Não dá para ler nenhum manga da fonte neox scans

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate of #11953
