### ISSUE TITLE
]Add Filter Feature to Filter Out Content Already in Library When Browsing Source

### ISSUE THREAD

**Issue by rtran25** [tachiyomiorg/tachiyomi-extensions#11988]
### Describe your suggested feature

Currently users can sort content while browsing any source. The feature will add a filter option to filter out content that has already been favorited and in user's library.

Benefits
1. User's will only see content not already in their library
2. Potentially improving load times by excluding content 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong repo and already requested.
