### ISSUE TITLE
Comick.fun throwing a parsing error

### ISSUE THREAD

**Issue by mneko** [tachiyomiorg/tachiyomi-extensions#11989]
### Source information

comick.fun 1.2.9

### Steps to reproduce

Run a library refresh or do a pull to refresh on an individual comic hosted by comick.fun

### Expected behavior

These comics update like they should

### Actual behavior

Library refreshes have very single comick.fun entry fail with this error:
`Method kotlinx.serialization.json.JsonElement eu.kanade.tachiyomi.extension.all.comickfun.ComickFun$mangaDetailsParse$$inlined$jsonFlatten$1.transformDeserialize(kotlinx.serialization.json.JsonElement) overrides final method in class Lkotlinx/serialization/json/JsonTransformingSerializer; (declaration of 'eu.kanade.tachiyomi.extension.all.comickfun.ComickFun$mangaDetailsParse$$inlined$jsonFlatten$1' appears in /data/app/~~XmMVY4iqCz0-DHkJtT8C6Q==/eu.kanade.tachiyomi.extension.all.comickfun-RnoDH8zqSb2fWQvf2iC77Q==/base.apk)
`

Pull to refresh properly fetches new chapters, but this error pops up in a toast

### Tachiyomi version

TachiyomiSY preview r456

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Hopefully addressed by https://github.com/tachiyomiorg/tachiyomi/commit/d71224b40b4c4467f4876ace3505cae8bdf6da8d

**Comment by mneko** [comment]
Just confirmed it's an app error and not an extension one by rolling back to the previous version
