### ISSUE TITLE
Xinmeitulu: Cannot download images

### ISSUE THREAD

**Issue by kasperskier** [tachiyomiorg/tachiyomi-extensions#11984]
### Source information

Xinmeitulu

### Steps to reproduce

Download a chapter.

### Expected behavior

That chapter should download.

### Actual behavior

Only viewed/cached pages download. Others are stuck. A notification pops up stating there's something wrong.

Logcat shows nothing helpful. Tried to intercept the response and change content type from `image; charset=UTF-8` to `image/jpeg` but nothing happens. Cloudflare client also wouldn't help. Logging the requests shows that the app is constantly requesting the same page.

### Tachiyomi version

r4411

### Android version

11

### Other details

See #11956.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
> Tried to intercept the response and change content type from image; charset=UTF-8 to image/jpeg but nothing happens

Changing content type works for me. After changing content type to image/jpeg, downloading is successful without error.

**Comment by kasperskier** [comment]
> Changing content type works for me. After changing content type to image/jpeg, downloading is successful without error.

Thanks. I only changed header's content type, but I should change the media type (already inferred) of response body.
