### ISSUE TITLE
Removal of mangasy.com

### ISSUE THREAD

**Issue by MangaSY** [tachiyomiorg/tachiyomi-extensions#12007]
### Source link

https://www.mangasy.com

### Other details

Hello. I'm Manga SY the owner of www.mangasy.com. Could you guys please do me a favor? Can you guys please remove my website, www.mangasy.com from your Tachiyomi app? Do you all know that you all doing this by letting users read on your app will ruin my website? No one will come to my website and this will result in my website will be closed down one day. Our website is the original website and original translators and now we are having a hard time maintaining our website because a lot of thieves' websites already stealing our work to generate income. So I hope you guys please understand and don't be so cruel to treat a small website like us. Please at least respect and appreciate our hard work. 
Thank you.

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by curche** [comment]
Proof of ownership was provided over Discord by user `MangaSY#6118` 👍

**Comment by TheKingTermux** [comment]
Waiting approval for PR's 👍🏻
