### ISSUE TITLE
Manhua Dragon: Missing search results

### ISSUE THREAD

**Issue by jrmgrz** [tachiyomiorg/tachiyomi-extensions#12009]
### Source information

Manhua Dragon 1.2.20

### Steps to reproduce

The Manhua Dragon sites show all series (manga) on the sites but not in the app.
because of this feature 
![Screenshot_2022-05-29-23-10-29-46](https://user-images.githubusercontent.com/46257461/170876844-f5cf0b5b-8371-4332-b61a-1803a01b42f7.png)
supposed to filter out the novels not the actual comics

### Expected behavior

The Extension supposed to show all series

### Actual behavior

It's happening because of this feature
![Screenshot_2022-05-29-23-10-29-46](https://user-images.githubusercontent.com/46257461/170876923-ef63a098-524a-469c-9886-8bf5c201641a.png)
I don't know why it does filter out other series(comics). 

### Tachiyomi version

0.13.4

### Android version

Android 8

### Other details

I just discovered it a while ago because i notice some series is within the website but not on the extension

update: I noticed that the entries that have been filtered out has this on their titles
![IMG_20220529_232351](https://user-images.githubusercontent.com/46257461/170877385-1cad62ee-abc1-4259-a637-4a9424148579.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It filters out other comics because the website is in incorrectly labeling then as novels or videos, even when they're not. This can be manually disabled on the extension code, wait until someone wants to work on it.

**Comment by vetleledaal** [comment]
Resolved in https://github.com/tachiyomiorg/tachiyomi-extensions/commit/61646e9953dc8cf5c79b1f6a7609393ef1018afa
