### ISSUE TITLE
Image couldn't be loaded

### ISSUE THREAD

**Issue by euijoonyeo** [tachiyomiorg/tachiyomi-extensions#12016]
### Source information

"mangabuddy 1.2.6"

### Steps to reproduce

I tried to read a chapter 
and the image couldn't be loaded

### Expected behavior

"this should happen I enter the chaper and images show normally

### Actual behavior

"this happen instead Image couldn't be loaded 

### Tachiyomi version

0.13.4

### Android version

Android 7 

### Other details

other extensions show images and I don't have connection problems

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me, try troubleshoot if you didnt read it
