### ISSUE TITLE
MangaDex: Cause Already Initialized 

### ISSUE THREAD

**Issue by IDontKnow218** [tachiyomiorg/tachiyomi-extensions#12012]
### Source information

MangaDex 1.2.159

### Steps to reproduce

1. Open Source
2. Browse MangaDex
3. Error

Or

1. Open manga in library
2. Download or read
3. Error

### Expected behavior

Should download or read manga

### Actual behavior

Gives error when downloading or reading manga

### Tachiyomi version

v8.6.8-AZ

### Android version

Android 5.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> Android 5.1.1
> v8.6.7-AZ

You're using a fork and pretty much on an Android version the main app no longer supports.
We can't really provide support for such cases. You can go and ask the Az Dev tho
