### ISSUE TITLE
Viz: Next chapter is the previous one

### ISSUE THREAD

**Issue by FerusGrim** [tachiyomiorg/tachiyomi-extensions#12015]
### Source information

VIZ Shonen Jump

### Steps to reproduce

Read through a chapter, go to next.

### Expected behavior

Current:
Chapter 2

Next:
Chapter 3

### Actual behavior

Current:
Chapter 2

Next:
Chapter 1

### Tachiyomi version

App version: 0.13.4

### Android version

Bluestacks, fairly certain not relevant

### Other details

This bug is identical to Issue #10043 (Though, obviously, with a different provider extension)

There is a workaround which resolves this issue in that Issue report, as a temporary measure.

That bug report is resolved in PR #10050

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Not all series by them have a ascendent volume/chapter order in their website, the vast majority is descendent (as it should be). Can you provide a series as an example where this happens?

**Comment by FerusGrim** [comment]
Sorry for the late reply. I know it can be replicated with Dr. Stone.
