### ISSUE TITLE
8muses download won't complete

### ISSUE THREAD

**Issue by jankinT** [tachiyomiorg/tachiyomi-extensions#12011]
### Source information

8muses 1.2.2

### Steps to reproduce

download specific mangas, for example
![Screenshot_2022-05-29-19-21-12-588_eu kanade tachiyomi](https://user-images.githubusercontent.com/42428606/170897254-b586ead4-ff8b-4808-9ae1-b3c88714ae61.jpg)

### Expected behavior

when the meter fills up, the download should complete

### Actual behavior

the download won't complete, even if I deleted the tamp file and re-download.
it looks like this
![Screenshot_2022-05-29-19-31-13-759_eu kanade tachiyomi](https://user-images.githubusercontent.com/42428606/170897073-c7219cf6-d6ef-4812-87b9-7c1706c51404.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Couldn't reproduce with 8Muses 1.4.2 on Tachiyomi r6003 with the same title and chapter
