### ISSUE TITLE
Bato.to chapters not readable/downloadable

### ISSUE THREAD

**Issue by ysnsmth** [tachiyomiorg/tachiyomi-extensions#12026]
### Source information

Bato.to 1.2.22

### Steps to reproduce

1. open a chapter
2. "No pages found"
3. repeat

or i download a chapter but the red exclamation point shows up

### Expected behavior

the pages should show up and be downloadable

### Actual behavior

they aint readable/downloadable, although the webview does work and no captcha prompt.

when i tried to open a chapter within the webview only certain pages were loading and showing on the chapter tho so idk yall the experts ln this

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 11 (SDK 30)
Android build ID: RMX2151_11_C.17
Device brand: realme
Device manufacturer: realme
Device name: RMX2151L1
Device model: RMX2151
Device product name: RMX2151

(some discord user who goes by LoRi#1497 is also having my problem)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ysnsmth** [comment]
oh btw about 12 hours before i posted this^^^ everything was working just fine, this only happened when i took a nap and i woke up.

**Comment by ysnsmth** [comment]
> I know that bato is having some image server issues at the moment, so that could be a contributing factor.

i didn't know that, ig ill just have to wait until things get better🤷

**Comment by jadoff630** [comment]
> i didn't know that, ig ill just have to wait until things get better🤷

Yep. A fair number of their recent chapters are showing broken image links when reading in WebView. Their developer is looking into it.  Though that doesn't explain why much older chapters are also showing no pages found in tachi, but who knows.

**Comment by cheahcell** [comment]
> 
I'm having the same problem :(

**Comment by cheahcell** [comment]
> oh btw about 12 hours before i posted this^^^ everything was working just fine, this only happened when i took a nap and i woke up.


> oh btw about 12 hours before i posted this^^^ everything was working just fine, this only happened when i took a nap and i woke up.

I'm having the same prob, still can't read :(

**Comment by XarX12** [comment]
Same happened to me
