### ISSUE TITLE
I Can't open my mangaowl and bato.to web and There is a problems to update a new chapter

### ISSUE THREAD

**Issue by insyirah03** [tachiyomiorg/tachiyomi-extensions#12034]
### Source information

MangaOwl 1.2.25 and Bato.to 1.2.22

### Steps to reproduce

When I want to read the manga that I added to my library from that extension it can't be load and I must open it at the web. 
![Screenshot_2022_0601_155008](https://user-images.githubusercontent.com/95292477/171354743-8c3994e3-177a-438c-bfac-6818558c7bf8.jpg)
Or it say that "page not found". Usually it will come out "page not found".

### Expected behavior

The page should come out and I can just read from there

### Actual behavior

This is happened instead, I must read it at the web and not at the Tachiyomi app.

### Tachiyomi version

"0.13.4"

### Android version

"Android 10"

### Other details

Also, there is a problem when tuhe can't be load or shown.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicates of #12026 #11212
