### ISSUE TITLE
mangakakalot.to

### ISSUE THREAD

**Issue by itszux** [tachiyomiorg/tachiyomi-extensions#12057]
### Source name

mangakakalot.to

### Source link

mangakakalot.to

### Language

English

### Other details

There is an extention with mangakakalot.com but its different from this mangakakalot.to so can you add it ?
I'm not sure if they are totally different but I searched this manga Record Of Return on ...alot.com and its not there but its on ...alot.to

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment]
It looks like a mirror/copycat of `mangareader.to`.
