### ISSUE TITLE
EnigManga

### ISSUE THREAD

**Issue by TachiApp** [tachiyomiorg/tachiyomi-extensions#12058]
### Source name

EnigManga

### Source link

https://enigmanga.com/

### Language

"Arabic"

### Other details

mangareader theme WordPress 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TachiApp** [comment]
Is Not duplicated...

**Comment by arkon** [comment]
They're literally the same URL but ok

**Comment by TachiApp** [comment]
> They're literally the same URL but ok

some url from what ?

**Comment by TachiApp** [comment]
> They're literally the same URL but ok

can you tag #id of the same isses source ?
