### ISSUE TITLE
Yanp Fansub: Changed their theme to Madara

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#12069]
### Source information

1.2.13

### Steps to reproduce

Can't find any work. It stays "No results found".

### Expected behavior

show results 

### Actual behavior

No results when opening the extension. The site has had modifications, probably that's it.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Can't know what they changed to fix the extended since the website is password protected.

**Comment by KaraSupergirl** [comment]
I forgot the password, I'm sorry. The password is: caradepica 
(I won't even comment on the password)

**Comment by alessandrojean** [comment]
Managed to check. They changed their theme to Madara. Wait for an extension update.
