### ISSUE TITLE
Haomanwu: no results found

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#12071]
### Source information

Haomanwu 1.2.4

### Steps to reproduce

1. Go to Browse for extension
2. Click in extension
3. Click in latest from that extension

### Expected behavior

Able to show all possible manhua and all possible search and filter.

### Actual behavior

"NO RESULT FOUND"

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kasperskier** [comment]
This is because the site is missing a category page. I will fix this soon.
