### ISSUE TITLE
Mangahere: Wrong chapter list sorting when containing "vol"

### ISSUE THREAD

**Issue by KasaiDot** [tachiyomiorg/tachiyomi-extensions#12115]
### Source information

Mangahere 1.2.18 (and i assume the rest of them as well)

### Steps to reproduce

1. Go browse on the Mangahere source
2. Search for "Martial Peak" (as an example)
3. See that the "last"/top chapter tachiyomi gives us is 999.

### Expected behavior

The chapter number should always be sorted by the number then by prefix/suffix of the title (ex: "vol. ")

### Actual behavior

The chapters are not sorted the good way, and if a chapter doesn't contain the same title as the others, it is either down in the bottom or high up it the top.

### Tachiyomi version

0.13.4-4446

### Android version

Android 12

### Other details

![Screenshot_20220607-204658_Tachiyomi](https://user-images.githubusercontent.com/8779667/172459129-390f3b57-5af6-455e-a19e-13dffee94ce3.png)
![Screenshot_20220607-204715_Tachiyomi](https://user-images.githubusercontent.com/8779667/172459141-5bfdd7c2-8b12-420a-bfbf-cbebacf13eeb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
maybe for the fix can use mobile version of the website instead, its chapter list is only one and similar naming
https://m.mangahere.cc/manga/martial_peak/
https://www.mangahere.cc/manga/martial_peak/

![image](https://user-images.githubusercontent.com/16263232/194286654-9c870061-ae71-4e06-aad3-373ebdb7dd6d.png)
