### ISSUE TITLE
Source request readcomiconline.li

### ISSUE THREAD

**Issue by Pretender93** [tachiyomiorg/tachiyomi-extensions#12110]
### Source name

readcomiconline.li

### Source link

https://readcomiconline.li

### Language

English

### Other details

There is an existing readcomiconline extension but not all comics exist on the current one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Welding-Torch** [comment]
This is not ok. It is a source used by a lot of people, I myself have used it for years. Devs please take note.

**Comment by AntsyLich** [comment]
> This is not ok. It is a source used by a lot of people, I myself have used it for years. Devs please take note.

No one is getting paid to be in a cat and mouse game with the site
