### ISSUE TITLE
No extensions to update

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#12124]
### Source information

...

### Steps to reproduce

well i use an old tachiyomi version 0.10.12, because my android is 5.1.1 and the latest version is not supported, so how do i solve the extensions problem in the app

### Expected behavior

Updater extensões

### Actual behavior

...

### Tachiyomi version

0.10.12

### Android version

5.1.1

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We don't support Android 5 anymore and the extensions were updated to newer versions that outdated versions of the app doesn't support. You may want to use a fork that support your Android version or take a look if there's any custom ROM with a newer Android version for your device.
