### ISSUE TITLE
Komikcast: Changed their domain

### ISSUE THREAD

**Issue by Andrewttgff1** [tachiyomiorg/tachiyomi-extensions#12126]
### Source name

Komikcast

### Source link
https://komikcast.me/

### Language

Indonesian

### Other details

Komikcast has changed its domain 
 The problem is the cover. When refreshed the cover doesn't appear at all maybe because of the change of domain 
And the loading has to wait a long time
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill out the issue report form instead next time. This is not a source request as the extension already exists.
