### ISSUE TITLE
Asura Scans: HTTP error 429

### ISSUE THREAD

**Issue by 0rzoro06** [tachiyomiorg/tachiyomi-extensions#12138]
### Source information

Asurascans

### Steps to reproduce

1. Swipe down for update/ try to open or read a manga never at the same time
2. close app
3. gets notification of update failed error 429

### Expected behavior

If no new chapter nothing there should be no update failed notification .

### Actual behavior

instead it sends the notification like there was a new chapter and it just wasnt able to load it but when i check web view there is no new chapter so idk why im getting update failed notification.

### Tachiyomi version

0.13.4

### Android version

Galaxy S10E

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by geverin** [comment]
Too many requests, you got ip banned

**Comment by kli885** [comment]
I'm getting the same error. When I open in WebView I see the error but it loads if I refresh thr page.

**Comment by kktuin** [comment]
It fixed automatically for me 10 hours later
