### ISSUE TITLE
Mangacrab: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by DarkDissaster** [tachiyomiorg/tachiyomi-extensions#12130]
### Source information

Mangacrab 1.3.22

### Steps to reproduce

1.abro la extensión
2. Sale fallo al evitar el cloudflare

### Expected behavior

Debería por abrir la extensión y poder ver los mangas 

### Actual behavior

Pero en su lugar sólo sale que fallo al evitar el CloudFlare

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

![Screenshot_2022-06-08-19-31-08-911_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/172739608-25e4c922-1e07-47ee-a790-f404f13e2711.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please try this first and see if it helps.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by DarkDissaster** [comment]
@alessandrojean No funciona 
![Screenshot_2022-06-09-18-53-19-926_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/172963753-0d3149f8-bd17-451c-999c-9377efe05e1a.jpg)

**Comment by alessandrojean** [comment]
You got IP banned, nothing much really we can do about it unfortunately.

**Comment by DarkDissaster** [comment]
@alessandrojean pero en chrome si puedo ingresar a la pagina

**Comment by alessandrojean** [comment]
We don't really have a fix for this. Wait to see if the block goes away by itself or migrate to better sources. This is the last thing I can suggest, if you need any additional help, you are welcome to ask at our #support channel on [Discord](https://discord.gg/tachiyomi).

**Comment by DarkDissaster** [comment]
@alessandrojean ya encontré el problema resulta que los dueños de la pagina bloquearon a tachiyomi y es el porqué no se puede usar la extensión. Gracias

**Comment by algifarrr** [comment]
U can change ur private DNS to dns.adguard.com or using VPN. So u can bypass cloudflare.

Puede cambiar su DNS privado a dns.adguard.com o usar VPN. Entonces puedes evitar Cloudflare.

**Comment by Gaitan19** [comment]
Can you make an example of how fix the problem ¿?

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
