### ISSUE TITLE
Haomanwu: https is unavailable

### ISSUE THREAD

**Issue by zhongfly** [tachiyomiorg/tachiyomi-extensions#12168]
### Source information

Haomanwu 1.2.4

### Steps to reproduce

1. open popular manga of this extension or update manga from this extension

### Expected behavior

show mangas

### Actual behavior

```
! Hostname app2.haomanwu.com not verified:
    certificate: sha256/nheAzXGRx6+arDvB6F2EoJPQJQx8f0M1bYxFiApUBHU=
    DN: CN=app2.haoman6.com
    subjectAltNames: [app2.haoman6.com]
```

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

There is a problem with the ssl certificate of this website, which makes it impossible to use https to access it. It is recommended to ignore the certificate error or use http.

@kasperskier

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
It works fine for me. Android version is 12 on my device.

**Comment by zhongfly** [comment]
The owner of the website has now fixed the ssl certificate
