### ISSUE TITLE
Komik Cast: No pages found

### ISSUE THREAD

**Issue by Fahregi** [tachiyomiorg/tachiyomi-extensions#12162]
### Source information

Komikcast 1.3.25

### Steps to reproduce

1. 
I click on the manga I want to read
2
Click the chapter
3
and there the chapter can't be opened when it comes out there is a page not found and this happens to all manga in the extension (komikcast)

### Expected behavior

Can open the page

### Actual behavior

But the page cant found 

### Tachiyomi version

0.13.4

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Check if your extension is updated, since you haven't specified the version you currently have. A fix for that was already submitted.

**Comment by Darkforst12** [comment]
Sama seperti ku tachiyomi versi terbaru, komikcast terbaru, tetap sama ada masalah 'halaman tidak ditemukan'

**Comment by sinrasasaki** [comment]
updated to version 1.3.26, but still not working, if you pick chapter or resume button, the loading appear and then close again.
---------------
Tachiyomi Version : 0.13.4
Android Version : 12

**Comment by Princess137** [comment]
my brother uses komik cast 1.3.23 and it's WORK!!

**Comment by Darkforst12** [comment]
> 

Bagaimana aku mendownload versi sebelumnya?
