### ISSUE TITLE
Error Extension 

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#12172]
### Source information

Komikcast 1.3.26

### Steps to reproduce

1. Open Komikcast extension
2. Open any manga 

### Expected behavior

Can read manga/hwa/hua normally

### Actual behavior

After I update to the new version, i still can read the manga

### Tachiyomi version

0.13.4

### Android version

Android 7.1.1

### Other details

![Screenshot_2022-06-12-21-31-10-91](https://user-images.githubusercontent.com/81138524/173238470-b960e4cf-245d-486f-b223-a609f1bb33ae.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Try updating to 1.3.27 first.
