### ISSUE TITLE
Can't access Muctau inside tachiyomi

### ISSUE THREAD

**Issue by Marimo666** [tachiyomiorg/tachiyomi-extensions#12188]
### Source information

Muctau 1.3.22

### Steps to reproduce

1. Go to browser
2. Go to Extension and install muctau
3. After done installing go to sources and click muctau it will show HTTP erro 400: Check Website in Webview

### Expected behavior

This shouldn't happened. I just used muctau 2 days ago to download manga but noe it's showing this error. 

### Actual behavior

It can't be access inside tachiyomi and I'm unable to download the manga. 

### Tachiyomi version

App version: 0.13.4 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12213 has better information. This issue can be closed.
