### ISSUE TITLE
Mangaswat issue

### ISSUE THREAD

**Issue by uwKILLER** [tachiyomiorg/tachiyomi-extensions#12183]
### Source information

Mangaswat

### Steps to reproduce

![Screenshot_20220613_013428_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/107407548/173346515-89a33db2-ebf1-4a39-ad3e-03e92e3767f5.jpg)

### Expected behavior

... 

### Actual behavior

... 

### Tachiyomi version

1.5.4

### Android version

10

### Other details

![Screenshot_20220613_013428_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/107407548/173346715-806f0b90-4717-40f9-939c-844a6fcf3355.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
> so, is there anyone working on fixing this?

You can work on it if you want. Anyone can take over issues.

**Comment by CHAOSX0** [comment]
yeah I'll try learning kotlin and giving it a try

**Comment by uwKILLER** [comment]
Any news about the proplem?

**Comment by abdelhak1209** [comment]
yeah same here

**Comment by midou221** [comment]
It seems to me that the site hides script-where chapter images- when it can't set cookies
To solve the problem, you must open webview so that app set cookies, then you can browse the provider without any problems..
