### ISSUE TITLE
Earlymanga Chapters Issue

### ISSUE THREAD

**Issue by GangstaPichu** [tachiyomiorg/tachiyomi-extensions#12192]
### Source information

Earlymanga 1.2.17

### Steps to reproduce

Search up whatever manga, and click it. Check their site too see that it doesn't match. 

### Expected behavior

All manga shows and you can read it. 

### Actual behavior

Only one chapter shows and says page doesn't exist, despite going to the website for 100s of chapters ready to read. 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lokeshvs1106** [comment]
![Screenshot_2022-06-28-15-06-17-46_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/31844094/176147002-868de554-2561-42fa-884e-3441e9a520c9.jpg)
I also have the same problem
