### ISSUE TITLE
Manual Refresh 

### ISSUE THREAD

**Issue by Varsha0319** [tachiyomiorg/tachiyomi-extensions#12209]
### Source information

Every source in library 

### Steps to reproduce

1. Manual refresh the library
2. Library is not refreshing. 

### Expected behavior

To refresh all the items in library and notify the new chapter 

### Actual behavior

Not refreshing, or very slowly refreshing until some item and then closed. 

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read tachiyomiorg/tachiyomi#6599.
