### ISSUE TITLE
KissLove: Domain changed

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi-extensions#12207]
### Source information

KissLove v1.3.7 (日本語)

### Steps to reproduce

Browse -> Source-> KissLove -> Latest or Browse

### Expected behavior

Latest or Browse should show manga

### Actual behavior

Latest or Browse show klmag.net : NXDOMAIN

### Tachiyomi version

Preview r4466

### Android version

Android 10

### Other details

Domain change from https://klmag.net to https://klmanga.net/

There are extension update to ver 1.3.8 but seems not for fix, it's still NXDOMAIN

![Screenshot_20220615-100800962](https://user-images.githubusercontent.com/101858971/173721432-4868eec9-7caa-4967-b004-81fb275b2988.jpg)
![Screenshot_20220615-100931561](https://user-images.githubusercontent.com/101858971/173721541-5fd5edbd-2885-416d-8199-4780ed9f2d8b.jpg)
![Screenshot_20220615-024716051](https://user-images.githubusercontent.com/101858971/173666121-a177bf55-8048-4dfe-9df0-06aad409f670.jpg)
![Screenshot_20220616-002212166 (1)](https://user-images.githubusercontent.com/101858971/173878221-e4045923-2f24-412e-b2b5-50632ec71f40.jpg)
![Screenshot_20220616-002801421 (1)](https://user-images.githubusercontent.com/101858971/173878366-5b95efbe-0bdf-4812-a2f6-8c775650734e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#12225
