### ISSUE TITLE
Mangaowl.to

### ISSUE THREAD

**Issue by AlexDvorak7** [tachiyomiorg/tachiyomi-extensions#12201]
### Source name

Mangaowl

### Source link

https://mangaowl.to/home

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Will be renaming the issue appropriately

**Comment by soocrilhos** [comment]
i want this extension so bad 😩

**Comment by soocrilhos** [comment]
where is the update about it?
