### ISSUE TITLE
No list of extension

### ISSUE THREAD

**Issue by TsyuHkal** [tachiyomiorg/tachiyomi-extensions#12210]
### Source information

Tachiyomi

### Steps to reproduce

First i want to find another extension like adding but then there a no list of extension, i thought this was couse by my internet but then i try to find severel time and it no came out... So i try to reinstall tachiyomi and then samething happen, i aslo download from your web but i cant see my extension adding...please help me

### Expected behavior

![Screenshot_2022-06-16-01-46-11-34](https://user-images.githubusercontent.com/107532961/173752767-67505d67-5c02-4a09-be12-583da39255dd.png)

### Actual behavior

![Screenshot_2022-06-16-01-54-11-45](https://user-images.githubusercontent.com/107532961/173752934-a80fe449-77bc-41bf-b558-9e2ebcd231a8.png)

### Tachiyomi version

10.12

### Android version

5.1.1

### Other details

>
![Screenshot_2022-06-16-01-46-11-34](https://user-images.githubusercontent.com/107532961/173752556-6719f091-fe02-40a1-97ef-c5cbb5a8ed90.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Update your app

**Comment by CrepeTF** [comment]
Also wrong repo

**Comment by CrepeTF** [comment]
Actually since you're on Android 5 the latest version won't work so you will have to use the [TachiyomiAZ](https://tachiyomi.org/forks/TachiyomiAZ/)  fork

**Comment by CrepeTF** [comment]
Either that or flash a custom rom
