### ISSUE TITLE
KissLove: Wrong Domain

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#12216]
### Source information

KissLove v1.3.7 (日本語)

### Steps to reproduce

Browse -> Source-> KissLove -> Latest or Browse

### Expected behavior

Latest or Browse should show manga

### Actual behavior

Latest or Browse show klmag.net : NXDOMAIN

### Tachiyomi version

Latest

### Android version

Android 8

### Other details

The site domain has changed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
duplicate of my issue #12207 ? , either it's just copy paste from my issue except for Tachiyomi Version , Android Version and Description

**Comment by alessandrojean** [comment]
Indeed a duplicate, so closing this one.
