### ISSUE TITLE
Lolicon source not working. Domian changed 

### ISSUE THREAD

**Issue by KyleBroflowski** [tachiyomiorg/tachiyomi-extensions#12211]
### Source information

Lolicon 1.3.23 English

### Steps to reproduce

Browse or search within lolicon source. 

### Expected behavior

Pages and titles should load

### Actual behavior

No results found
Webview takes to https://lolicon.mobi/
The domain is same as on extention. Just gives no results found error. 

### Tachiyomi version

Version 0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment]
FYI: The domain that is used by the extension did not changed.

**Comment by KyleBroflowski** [comment]
@zbue I see, what else could be the issue?
