### ISSUE TITLE
Unable to resolve host: "lectortmo.com"

### ISSUE THREAD

**Issue by k-sketch** [tachiyomiorg/tachiyomi-extensions#12217]
### Source information

"TuMangaOnline 1.3.39

### Steps to reproduce

First I entered the application and tried to read a manga from the "TuMangaOnline" library, it stays loading for a while and takes me to the chapter selection showing this error: **_"Unable to resolve host "lectortmo.com": No address associated with hostname"_**, I already reinstalled the application, but the error continues only with that library. Other than that, manga from other libraries take longer to load before and after reinstalling the application.

### Expected behavior

Should let me read any chapter

### Actual behavior

**_"Unable to resolve host "lectortmo.com": No address associated with hostname"_**

[https://ibb.co/b6tRQrv](url)

### Tachiyomi version

0.13.4

### Android version

Android 9

### Other details

Features of my phone:
- Model: Huawei Y9 2019 JKM-LX3
- Ram: 3.0 gb

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
La extensión trabaja perfectamente

**Comment by k-sketch** [comment]
> 
It still comes out like in the image I uploaded as a test, if it's an isolated case I'll see if formatting the phone solves it :( , because I already uninstalled and installed the extension many times.

**Comment by KasukeLp23** [comment]
@k-sketch Apparently you have been banned from the page (many requests to the web) or because of problems with your contracted internet service.

**Comment by k-sketch** [comment]
Damn, the worst thing is that I stop reading for a while, getting a little off topic, can I appeal or something to be able to enter again? If not, I proceed to close the topic and thank you for responding quickly.
