### ISSUE TITLE
Shadow Mangas error

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#12218]
### Source information

Shadow Mangas 1.3.15

### Steps to reproduce

Open the extension

### Expected behavior

The web manga should appear normally

### Actual behavior

"No results found"

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

The website loads normally.
![Screenshot_20220615-210440_Tachiyomi](https://user-images.githubusercontent.com/101371218/173982347-dc54bee2-a7d2-483d-8a70-5d1e59ae0e16.jpg)
![Screenshot_20220615-210531_Tachiyomi](https://user-images.githubusercontent.com/101371218/173982435-c79a27fd-5d6b-44fc-8a94-df8d73b490c8.jpg)

And the same goes for the manga from that source that I already have in my library;
![Screenshot_20220615-210640_Tachiyomi](https://user-images.githubusercontent.com/101371218/173982547-c1c7caa1-1a84-431f-8ca8-fdfb7f2fe468.jpg)
![Screenshot_20220615-210701_Tachiyomi](https://user-images.githubusercontent.com/101371218/173982578-7aec312c-67f3-4ef6-a210-677e7eedf6a7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
> * [x] I have tried the troubleshooting guide.

Opening the site in WebView first resolves this issue. Site has some additional issues with images not loading, which is an issue with the site, and not the extension.

Site is using [LiteSpeed's reCAPTCHA protection](https://docs.litespeedtech.com/lsws/cp/cpanel/recaptcha/), which you could open a feature request in [the main repo](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose) to see if it can be bypassed.

**Comment by edmxn** [comment]
> > * [x]  I have tried the troubleshooting guide.
> 
> Opening the site in WebView first resolves this issue. Site has some additional issues with images not loading, which is an issue with the site, and not the extension.
> 
> Site is using [LiteSpeed's reCAPTCHA protection](https://docs.litespeedtech.com/lsws/cp/cpanel/recaptcha/), which you could open a feature request in [the main repo](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose) to see if it can be bypassed.

The extension was updated a while ago and this no longer happens, I completely forgot that I had made this Issue so I couldn't close it. Thanks for replying anyway
