### ISSUE TITLE
Vyvymanga

### ISSUE THREAD

**Issue by akmalmeaw** [tachiyomiorg/tachiyomi-extensions#12221]
### Source name

Vyvymanga

### Source link

https://vyvymanga.com/

### Language

English

### Other details

This source is a good source, it's the latest partner of mangaowl. This can help to cover up mangaowl if something happen to mangaowl such as broken website or else. Hope vyvymanga can be add to be an extension. Tq

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by SavoryBanana** [comment]
Mangaowl confirmed to have shut down I'll wait patiently for vyvymanga to be available as an extension.
