### ISSUE TITLE
CopyManga Error

### ISSUE THREAD

**Issue by ececleon** [tachiyomiorg/tachiyomi-extensions#12220]
### Source information

CopyManga 1.3.26

### Steps to reproduce

1 open source
2 select CopyManga recently update picture
3 cant access manga

### Expected behavior

The web manga should appear normally

### Actual behavior

Attempt to invoke virtual method java.lang.String org.jsoup.nodes.Eleme nt.attr(java.lang.String)' on a null object reference

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

![~`_8VSH)MPFQ6XK8E`@2AXS](https://user-images.githubusercontent.com/12274633/174103007-2cd2abdf-a8c6-40ba-8d72-8209aeb2f78c.jpg)
![Z%_A_HBLZH8U3PBTR}DYD%0](https://user-images.githubusercontent.com/12274633/174103027-615e8288-00f3-45ac-945c-9f8bdbb20cb1.jpg)
![%K)ATMEW5SS0LZ5OQWHR_71](https://user-images.githubusercontent.com/12274633/174103040-89c90be5-e599-4fa8-a29f-0aff2e12ac5e.jpg)
![)89%6UZ89O7YWFR`$PL2PBK](https://user-images.githubusercontent.com/12274633/174103047-c6aea1e0-2a7b-4d82-87cd-01f509778c1f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by erinacio** [comment]
I think they're intentionally blocking Tachiyomi's user agent. Simply `curl https://www.copymanga.org/` with `-H 'user-agent: Tachiyomi/1.0` would return a json indicating "Please download and use the latest app from the official website!", while just changing that to `Tachiyami/1.0` or just `curl/7.83.1` will return normal index page.

**Comment by ececleon** [comment]
> I think they're intentionally blocking Tachiyomi's user agent. Simply `curl https://www.copymanga.org/` with `-H 'user-agent: Tachiyomi/1.0'` would return a json indicating "Please download and use the latest app from the official website!", while just changing that to `Tachiyami/1.0` or just `curl/7.83.1` will return normal index page.

can I change user agent in my tachoyomi？or wait extension update？

**Comment by eventhorizonsky** [comment]
This plugin uses the `user-agent` is `Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 56.0.2924.87 Safari / 537.36`, through which to request the main page when certain probability will trigger "sorry! The content is not available in your area." ,Sometimes also can return to normal,But just only modify the the `user-agent` browser version number will no longer appear error message

**Comment by ececleon** [comment]
how I change user agent in my tachoyomi？or wait extension update？

**Comment by ececleon** [comment]
> This plugin uses the `user-agent` is `Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 56.0.2924.87 Safari / 537.36`, through which to request the main page when certain probability will trigger "sorry! The content is not available in your area." ,Sometimes also can return to normal,But just only modify the the `user-agent` browser version number will no longer appear error message


how I change user agent in my tachoyomi？or wait extension update？

**Comment by eventhorizonsky** [comment]
you can pull to local modification after the user-agent part of the code to build the app, but it seems the problem has been solved
