### ISSUE TITLE
ReadManhwa: Unparseable date

### ISSUE THREAD

**Issue by RavenIsh34** [tachiyomiorg/tachiyomi-extensions#12233]
### Source information

ReadManhwa 1.3.12

### Steps to reproduce

1. Open some content like Secret class
2. try to reload chapter
3. and you sea Unperseable Data 

### Expected behavior

Normal Behavior 

### Actual behavior

I can't read latest chapter 

### Tachiyomi version

Tachiyomi Sy r458

### Android version

Android 8.1.0

### Other details

![Screenshot_2022-06-18-09-58-37-63](https://user-images.githubusercontent.com/107761586/174444188-3d5f86d5-4bd8-4e58-a979-1cf770278c76.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Superseded by #17528
