### ISSUE TITLE
Mangaowl isn't working 

### ISSUE THREAD

**Issue by Bhupalideka** [tachiyomiorg/tachiyomi-extensions#12232]
### Source information

Mangaowl 1.3.25

### Steps to reproduce

![Screenshot_2022-06-18-13-15-20-080_eu kanade tachiyomi](https://user-images.githubusercontent.com/107747055/174428245-149519d1-ad0e-4dcc-a5f6-786c9cb990ca.jpg)

### Expected behavior

This should happen 

### Actual behavior

![Screenshot_2022-06-18-13-15-20-080_eu kanade tachiyomi](https://user-images.githubusercontent.com/107747055/174428291-3fb9efd1-5306-4050-b304-9c95663761d4.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
MangaOwl is down as the owner is going on break and took it down
