### ISSUE TITLE
MangaOwl is Broken

### ISSUE THREAD

**Issue by Flacco-Coder** [tachiyomiorg/tachiyomi-extensions#12240]
### Source information

MangaOwl English 1.2.25

### Steps to reproduce

1. Library update
2. Fails to update all manga belonging to MangaOwl 

### Expected behavior

Should Update all manga in source MangaOwl

### Actual behavior

Fails to update any manga from source MangaOwl

### Tachiyomi version

0.13.4

### Android version

7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#12232
