### ISSUE TITLE
Manhua Kiss

### ISSUE THREAD

**Issue by yurishein** [tachiyomiorg/tachiyomi-extensions#12241]
### Source name

Manhua Kiss

### Source link

https://manhuakiss.me/

### Language

English

### Other details

![Screenshot_20220619-183121](https://user-images.githubusercontent.com/80819031/174476700-038905d4-525b-4d93-9db8-9ed4d25237ba.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme
