### ISSUE TITLE
Mangabuddy: Chapter images do not load

### ISSUE THREAD

**Issue by candoshit** [tachiyomiorg/tachiyomi-extensions#12259]
### Source information

Mangabuddy 1.3.8

### Steps to reproduce

1- I tried Troubleshooting and followed all guides to fix it. 
2- I asked support on Discord. 
3-  Mangabuddy extension won't work, whatever manga I try open show me a "the image couldn't be loaded, retry". 

### Expected behavior

It should open normally 

### Actual behavior

It doesn't open no matter what I try, even though the Webview open without problems

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

![Screenshot_2022-06-19-22-36-45-072_eu kanade tachiyomi](https://user-images.githubusercontent.com/78657980/174631932-3878627d-4a44-4325-b684-a200ac2e19ba.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The extension only uses the first image server, which might be why it's working in WebView and not the extension.

What manga are you trying to read?

Can you check WebView and confirm the domain used for images? It should be `s1.mbcdnv1.xyz`. If the domain is different from `s1.mbcdnv1.xyz` adding an extension setting to select a server would probably work.

**Comment by vetleledaal** [comment]
The linked PR adds the ability to change the image server, please check if this solves it for you. The issue might also have been temperamental, according to the announcement on their site:
> Sorry you guys for the bad experiences on last few days with the site. With the f*cking change on the server caused some chapters do not load. If you still have the problems, please message to us.
