### ISSUE TITLE
Add KnightNoScanlation

### ISSUE THREAD

**Issue by Acsell7u7** [tachiyomiorg/tachiyomi-extensions#12253]
### Source name

Knight No Scanlation

### Source link

https://www.knightnoscanlation.com

### Language

Spanish

### Other details

![Screenshot_20220620-002852_Chrome](https://user-images.githubusercontent.com/74920978/174532090-da270dc2-0e8b-4eb5-bb86-2924e13c4833.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Removed as per Request and wont be added back. Refer to #3475
