### ISSUE TITLE
Inmanga not load

### ISSUE THREAD

**Issue by Metalskrull** [tachiyomiorg/tachiyomi-extensions#12251]
### Source information

Inmanga 1.3.2

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

Unable to resolve host "inmanga.com": No address associated with hostname.

### Tachiyomi version

0.13.4

### Android version

Fire OS 7.3.1.7

### Other details

Screenshot

![Screenshot_20220619-205220](https://user-images.githubusercontent.com/107822456/174513293-769abce5-1659-4fca-bcf8-29e4b26d9941.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

Please try the troubleshooting guide first. This is most likely a DNS issue in your network, as the website is fine.
