### ISSUE TITLE
Mcreader.net: HTTP error 404

### ISSUE THREAD

**Issue by Chaosmayme** [tachiyomiorg/tachiyomi-extensions#12261]
### Source information

Mcreader.net 1.3.12

### Steps to reproduce

It's not working it's opening in the web view but not working in normal mode

### Expected behavior

When opening view normally

### Actual behavior

It's shows https error 404

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

![Screenshot_20220620_213758_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94779387/174642753-e39a052d-6f9c-4c3f-ac67-71401c4224c9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Beji-kun** [comment]
Not working Latest (manga update) classic with filter work normal after this new update extension 😓😭
