### ISSUE TITLE
Comick.fun: Unexpected 'null' when string was expected

### ISSUE THREAD

**Issue by banjolore** [tachiyomiorg/tachiyomi-extensions#12272]
### Source information

comick.fun 1.3.11

### Steps to reproduce

1. click on "Latest" in comick.fun source
Alternatively,
1. Open comick.fun source
2. click filter
3. filter with one of genre `aliens`, `anthology`, `crossdressing`, `delinquents`, `doujinshi`, `ecchi`, `fan colored`, `genderswap`, `gyaru`, `horror`, `incest`, `loli`, `magical girls`, `medical`, `monster girls`, `ninja`, `office workers`, `official colored`,  `oneshot`, `philosophical`, `samurai`, `shota`, `slice of life`, `sports`, `superhero`, `traditional games`, `user created`, `vampires`, `virtual reality`, `yuri`, or `zombies`

### Expected behavior

The list of comics should appear as usual

### Actual behavior

Instead you get the error `unexpected 'null' when string was expected`.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zen1557** [comment]
Am facing a same issues when i scroll in comick.fun extension the error pop-up

```
Unexpected `null` when string was expected

```

**Comment by Azeizeil** [comment]
Issue can be resolved by uninstalling the extension and then re installing the extension. Worked for me just now

**Comment by banjolore** [comment]
As of uninstalling and reinstalling, I am still getting the same issue

**Comment by Leondre** [comment]
Reinstalling does not fix it. A simple way to reproduce is to filter by the 'genderswap', 'monster girls', or 'zombies' genres.
