### ISSUE TITLE
Solicitud de corrección de problemas

### ISSUE THREAD

**Issue by Azael1976** [tachiyomiorg/tachiyomi-extensions#12284]
### Source information

Tumangaonline 1.3.39, Mangamx 1.3.13

### Steps to reproduce

No poder descargar capítulos 

### Expected behavior

Descargar capítulos

### Actual behavior

Siempre permitía descargar capítulos 

### Tachiyomi version

0.13.4 

### Android version

Android 12

### Other details

Ninguno 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please (1) open one ticket per source and (2) be more descriptive in the fields, like specifying the steps to reproduce correctly. You may also want to try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) first.
