### ISSUE TITLE
MMScans: Specific Series won't download

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#12285]
### Source information

MMScans 1.3.25

### Steps to reproduce

Try to download chapter 1 of "I have max level luck"

### Expected behavior

Should download chapter

### Actual behavior

Giving an "unexpected error"

### Tachiyomi version

0.13.4 and r4889

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
its working, maybe some update fixing it or just site issue
