### ISSUE TITLE
Blacktoon179

### ISSUE THREAD

**Issue by akmalmeaw** [tachiyomiorg/tachiyomi-extensions#12287]
### Source name

Blacktoon

### Source link

https://blacktoon179.com/

### Language

Korea

### Other details

![Screenshot_20220623-001913_Chrome](https://user-images.githubusercontent.com/64727356/175083242-3f023707-37b0-438f-9782-ff7abb286f74.jpg)
![Screenshot_20220623-001920_Chrome](https://user-images.githubusercontent.com/64727356/175083345-4437bc98-c763-4fb5-a820-22e485c1e563.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by fiia161211** [comment]
https://blacktoon141.com/ 
Use this source link it's permanent and doesn't change.
