### ISSUE TITLE
Infernal Void Scans fail to load chapter list

### ISSUE THREAD

**Issue by MaskaraLester** [tachiyomiorg/tachiyomi-extensions#12295]
### Source information

Infernal Void Scans 1.3.18

### Steps to reproduce

1.  Open Infernal Void Scans Source
2.  Choose any manga

### Expected behavior

Displaying list of chapter

### Actual behavior

No Chapter found
example:
![Screenshot_2022-06-23-08-40-47-795_eu kanade tachiyomi](https://user-images.githubusercontent.com/100495803/175190711-6746941c-f7f9-4f97-86ca-1cadfc2fd409.jpg)

### Tachiyomi version

0.13.4

### Android version

MIUI 12 (Android 11)

### Other details

1. Opening title's in webview redirect to their home page instead.
2. Cant use search feature in this extension
3. Every titles in this extension have infinite(?) dupes
4. Exception, only this title works correctly
![Screenshot_2022-06-23-09-04-25-698_eu kanade tachiyomi](https://user-images.githubusercontent.com/100495803/175191626-5e2898e0-6b0b-4c55-ba52-2cdd1a4843db.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EdgeHRR** [comment]
They changed their domain....
