### ISSUE TITLE
Ace Scans Extension don't work

### ISSUE THREAD

**Issue by SqueezedByte** [tachiyomiorg/tachiyomi-extensions#12302]
### Source information

Ace Scans 1.3.14

### Steps to reproduce

Try to open a page 
https://acescans.xyz/manga/kawaii-joushi-o-komarasetai/

### Expected behavior

Open the page and show the picture

### Actual behavior

It gives this error : "**Expected URL scheme 'http' or 'https' but was 'data'**"

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by keinezeit8** [comment]
Related to #12224 
Duplicate?
