### ISSUE TITLE
Luminescans Bad Certificate and 404

### ISSUE THREAD

**Issue by keinezeit8** [tachiyomiorg/tachiyomi-extensions#12304]
### Source information

Lumine Scans 1.3.22

### Steps to reproduce

Open Lumine Scans

### Expected behavior

Show Mangas

### Actual behavior

Get "Hostname not verified"-Error

### Tachiyomi version

r4489

### Android version

Android 10 - LineageOS 17.1

### Other details

1. The Certificate is for the wrong domain. I know this is not part of Tachiyomi to fix, but it shows the state the site is in.
2. When Accepting the invalid certificate, you get a 404. As if the Website doesn't exist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTPS certificate is something the website needs to fix it, it's literally out of our range as you have said.
