### ISSUE TITLE
MangaBuddy: The browse and latest pagination is broken

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi-extensions#12301]
### Source information

MangaBuddy 1.3.8

### Steps to reproduce

Browse -> Sources -> MangaBuddy -> Browse or Latest

### Expected behavior

Browse -> Sources -> MangaBuddy -> Browse or Latest can keep scroll down to show more manga

### Actual behavior

Browse -> Sources -> MangaBuddy -> Browse or Latest can't keep scroll  down to show more manga, likely it's more stuck or stopped 

### Tachiyomi version

Preview r4489

### Android version

Android 10

### Other details

Checked in webview, manga that don't show in tachiyomi because scroll down stopped, being shown normally in website

https://user-images.githubusercontent.com/101858971/175238137-212e8450-4a10-450b-b596-b41cf63e96be.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment]
Pagination is also broken in MangaForest and MangaMad extension.

**Comment by Purlana** [comment]
The websites have removed the next page button which the root extension uses

**Comment by DchanN** [comment]
> The websites have removed the next page button which the root extension uses

yeah, it's seems that's the case, the day this bug appeared I'm check latest update in browser and notice next button missing, hopefully it can be resolved
