### ISSUE TITLE
copymanga : Extremely slow and unsteady loading speed

### ISSUE THREAD

**Issue by tyh0416** [tachiyomiorg/tachiyomi-extensions#12320]
### Source information

copymanga 1.3.28

### Steps to reproduce

1.open the source
2.the interface circling for a long time and much probably the error 504 take place
3.select a random manga
4.cover image can't loaded(or just in a extremely slow speed) , and when the chapters was loaded , the error 502 often take place

### Expected behavior

the error 502 and error 504 shouldn't take place frequently , and the covers and chapters should be loaded successfully

### Actual behavior

the error 502 and error 504 take place frequently , and the covers and chapters can't be loaded successfully the most time

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tyh0416** [comment]
unlike the extension , the website ( www.copymanga.org ) can display normally.

**Comment by stevenyomi** [comment]
> unlike the extension , the website ( [www.copymanga.org](http://www.copymanga.org) ) can display normally.

I'm getting 504's randomly when clicking around in my browser. Probably nothing to do with the extension.

**Comment by zhongfly** [comment]
> I'm getting 504's randomly when clicking around in my browser. Probably nothing to do with the extension.

I can confirm.Its official app is also often unable to connect.

**Comment by tyh0416** [comment]
the same situation as "issue #12314 " has been taken place at present

**Comment by stevenyomi** [comment]
> the same situation as "issue #12314 " has been taken place at present

You can change the Chrome version in the extension settings. Pretty sure this will affect Chrome users too.

**Comment by CmmmmmmLau** [comment]
> > unlike the extension , the website ( [www.copymanga.org](http://www.copymanga.org) ) can display normally.
> 
> I'm getting 504's randomly when clicking around in my browser. Probably nothing to do with the extension.

it seen like is website's issue, after update my chrome version to 103 in my PC, website will warn "This content is not available in your region."
I used Chrome DevTools change the chrome version from 103 to 102 in the User-Agent. It back to normal.

**Comment by zhongfly** [comment]
The website's server has been fixed, and both the browser and **its official app** are working fine.

**Comment by tyh0416** [comment]
> > the same situation as "issue #12314 " has been taken place at present
> 
> You can change the Chrome version in the extension settings. Pretty sure this will affect Chrome users too.

This will be solved if I turn the Chrome version 103 into 103.0.5060.53 , the 502 and 504 error seems to be fixed at present , but the books and chapters still hard to load in extension

**Comment by constfold** [comment]
Isn't the rate limit too stricter? manga list works fine as normal but it takes about >10s to load all covers in one page and more on book details. @stevenyomi any idea?

**Comment by tyh0416** [comment]
unfortunately , it spent me about >10s to load 2~3 covers in the page

**Comment by tyh0416** [comment]
It's interesting that I find a different speed between my phone and my tablet computer , on my phone , the speed is about 30kb/s , but on my tablet computer , the speed is approaching to 0 and the most covers loading failed

**Comment by stevenyomi** [comment]
关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。

关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。

**Comment by tyh0416** [comment]
> 关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。
> 
> 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。

Thank you , the running of extension in my phone is all right , and how can I adjust the speed in my tablet ? it can't load books and chapters anymore
![Screenshot_20220626_132905_eu kanade tachiyomi](https://user-images.githubusercontent.com/75163779/175800759-bb141f1b-53a4-4a15-92cf-c4766b4c1b8b.jpg)
it takes me about 2 minutes to load that

**Comment by tyh0416** [comment]
> 关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。
> 
> 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。

Thank you , the extension running on my phone is all right , but how can I adjust the speed on my tablet ? the speed >1kb/s couldn't load any books and chapters

**Comment by tyh0416** [comment]
> 关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。
> 
> 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。

Thank you , the extension running on my phone is all right , but how can I adjust the speed on my tablet ? the speed >1kb/s couldn't load any books and chapters

**Comment by tyh0416** [comment]
> 关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。
> 
> 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。

Thank you , the extension running on my phone is all right , but how can I adjust the speed on my tablet ? the speed <1kb/s couldn't load any books and chapters

**Comment by tyh0416** [comment]
> > 关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。
> > 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。
> 
> Thank you , the extension running on my phone is all right , but how can I adjust the speed on my tablet ? the speed <1kb/s couldn't load any books and chapters

![Screenshot_20220626_145443_eu kanade tachiyomi](https://user-images.githubusercontent.com/75163779/175803186-597faa05-5143-4d5e-b79d-fee627091227.jpg)
![Screenshot_20220626_145425_eu kanade tachiyomi](https://user-images.githubusercontent.com/75163779/175803188-1879075f-90ec-43cd-bd2d-95180d612a42.jpg)
that's the real situation of my tablet ( I've loaded for about 1 minute )

**Comment by tyh0416** [comment]
> > 关于限速：参考其他插件，目前这个限速是正常的，主要是想缓解 Tachiyomi 造成的压力。但是他们的连接似乎不太稳定，所以格外地慢。如果不限速，他们可能会采取更多手段来封锁，不过目前看来他们似乎也不是很满意。当初 Coco 漫画也有限速（不过是可以手动调整的），最后也还是被封掉了。
> > 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。
> 
> Thank you , the extension running on my phone is all right , but how can I adjust the speed on my tablet ? the speed <1kb/s couldn't load any books and chapters

![Screenshot_20220626_150301_eu kanade tachiyomi](https://user-images.githubusercontent.com/75163779/175803398-2aad15e5-111b-4385-92be-070fc66bc82e.jpg)
![Screenshot_20220626_145443_eu kanade tachiyomi](https://user-images.githubusercontent.com/75163779/175803446-e1fc4548-fa8b-4b6d-86c3-36627d448b6a.jpg)
that's the real situation happened on my tachiyomi ( I've loaded for about 2 minutes ) and it almost can't work anymore

**Comment by constfold** [comment]
Have you tried to clear cache and restart the app?

**Comment by constfold** [comment]
btw, I found a few covers are always failed to load due to this exception:
```
<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by tyh0416** [comment]
> Have you tried to clear cache and restart the app?

yes , I even uninstalled tachiyomi and copymanga extension and installed them again ,  but the problem has not been solved

**Comment by tyh0416** [comment]
btw , it brings out a much normal loading speed in webview
![Screenshot_20220626_191113_eu kanade tachiyomi](https://user-images.githubusercontent.com/75163779/175811501-eeb4beaa-608e-41ae-9240-ede5dd799111.jpg)

**Comment by stevenyomi** [comment]
I think there are some bad requests jamming the rate limit interceptor. Trying to rewrite this.

**Comment by OgalinLabM0** [comment]
![Screenshot_20220626_191821_eu kanade tachiyomi_edit_31864814917531](https://user-images.githubusercontent.com/94498750/175811690-a1956f50-1d32-4273-ab7f-c46db7674779.jpg)
![Screenshot_20220626_192148_eu kanade tachiyomi_edit_31883983674299](https://user-images.githubusercontent.com/94498750/175811694-d2cf0bf3-0989-4aa1-be69-ec95defdf3da.jpg)
103改102后还是打不开

**Comment by rainbowflesh** [comment]
Gota another two type of error during page load:

'''txt
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.fata()' on a null object reference
'''
