### ISSUE TITLE
Reaper scans extension not working 

### ISSUE THREAD

**Issue by Deltapl7s** [tachiyomiorg/tachiyomi-extensions#12339]
### Source information

Reaper Scans 1.3.26

### Steps to reproduce

Tried to download chapters says timeout and when tried to open latest chapters or just clicked it only shows black screen.

### Expected behavior

It should download chapters and should show manga covers

### Actual behavior

Showing black screen and timeout in downloads 

### Tachiyomi version

App version: 0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Someone777** [comment]
I can confirm.  I can view manga in the browser instantly but not in the app.  I get constant timeouts or 502 errors.

**Comment by alessandrojean** [comment]
They said recently their website is unstable, and what you see in WebView is most likely a cached version of the site.

It's something they need to fix and can't be addressed at the extension level.
