### ISSUE TITLE
Batoto update error

### ISSUE THREAD

**Issue by Nidaime-erosennin** [tachiyomiorg/tachiyomi-extensions#12333]
### Source information

Bato.to 1.3.26

### Steps to reproduce

1. Open Tachiyomi
2. Update manga from Batoto source
3. Open in webview

### Expected behavior

It should have updated smoothly and when opened in webview, the manga page should be shown.

### Actual behavior

Connection reset by peer and manga page blanking in webview
![Screenshot_20220626-184244_1](https://user-images.githubusercontent.com/105691884/175812821-d7cb1e6a-ef79-4099-b8de-982883709100.jpg)
![Screenshot_20220626-184423_1](https://user-images.githubusercontent.com/105691884/175812823-558e5f1f-8c36-4c76-9588-b605f41b93f2.jpg)
.

### Tachiyomi version

Tachiyomi 0.13.4

### Android version

Android 6.0

### Other details

I believe the reason for this is because Batoto has recently changed their URL into Battwo.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZekkenID** [comment]
![Screenshot_2022-06-29-12-08-28-728_eu kanade tachiyomi](https://user-images.githubusercontent.com/23666289/176342886-6ce9e49f-e016-4ded-b460-0ea855cf2052.jpg)

Reset by peer because your country blocked batoto 
You can change mirror in extension setting
