### ISSUE TITLE
Bato.to: Sometimes fails to show manga covers

### ISSUE THREAD

**Issue by reygrey666** [tachiyomiorg/tachiyomi-extensions#12341]
### Source information

Bato.to 1.3.27

### Steps to reproduce

1. Bato.to extension
2. Scrolling down
3. Some manga not showing the cover art

### Expected behavior

Showing every cover art

### Actual behavior

![Screenshot_20220627-144938_Tachiyomi](https://user-images.githubusercontent.com/88650369/175890741-3427ce0e-2da1-401a-ad55-ae07ca73e570.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

I need to open and refresh the manga that have no cover so it can show the cover every time I seeing one. I can't always recognize the manga just from titles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hzaz0320** [comment]
I also have this problem

**Comment by AntsyLich** [comment]
Can't reproduce. Make a new issue if it happens again
