### ISSUE TITLE
CopyManga extension can only view 5 pages

### ISSUE THREAD

**Issue by brithbutter** [tachiyomiorg/tachiyomi-extensions#12347]
### Source information

CopyManga 1.3.29

### Steps to reproduce

1. Pick any manga with CopyManga Extension
2. Pick one chapter and view

### Expected behavior

There should be more than 5 pages of content

### Actual behavior

There are only 5 pages of content

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

I've observed the chapter with the CopyManga web page, however, it has a banner that shows "Only use CopyManga App can view all pages". I am afraid this issue can not be properly fixed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rainbowflesh** [comment]
![Screenshot_20220628_013233](https://user-images.githubusercontent.com/20819692/176000988-f2a981d1-f572-43df-ac2b-a4ea63d51675.jpg)
Open in webview will see copy manga limit view page, lead you to download the application.

**Comment by brithbutter** [comment]
> Working on a fix.

Glad to know this information and a lot thanks for the work.

**Comment by stevenyomi** [comment]
> Glad to know this information and a lot thanks for the work.

If this cat-and-mouse game goes out of control, we will have to remove the extension sadly.
