### ISSUE TITLE
Copymanga Error

### ISSUE THREAD

**Issue by WindBT47** [tachiyomiorg/tachiyomi-extensions#12362]
### Source information

Copymanga 1.3.30

### Steps to reproduce

Open copymanga.

### Expected behavior

This should display the manga list

### Actual behavior

Unexpected JSON token at offset 0: Expected start of object '{' but had ' ' instead JSON input:

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kuronekonokuro** [comment]
#12356 
Change user agent in extension settings

**Comment by HashLiver** [comment]
> #12356 Change user agent in extension settings

Doesn't work for me. I have already tried:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
```

**Comment by WindBT47** [comment]
> #12356 Change user agent in extension settings

Thanks it works

**Comment by WindBT47** [comment]
> #12356 Change user agent in extension settings

Sorry, the same problem in #12367
