### ISSUE TITLE
MangasTk: Changed their domain

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi-extensions#12366]
### Source information

MangasTk - 1.3.21

### Steps to reproduce

Open extension

### Expected behavior

It appears normally

### Actual behavior

Nothing appears due to the domain change they made to the page

### Tachiyomi version

0.13.4

### Android version

Android 7

### Other details

Chanfe of domain: Of **".com"** to **".net"**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by VannevarB** [comment]
Mangatk continues with domain ".com" in 1.3.22

**Comment by DarkOverl0rd** [comment]
This is the problem... The new theme is a variant of WP Marada
![Mangastk](https://user-images.githubusercontent.com/49003434/191584225-653aec54-162d-43df-9ade-c1bf076fb624.png)
