### ISSUE TITLE
CopyManga Read and Download Error 

### ISSUE THREAD

**Issue by Nathaniel-Wu** [tachiyomiorg/tachiyomi-extensions#12370]
### Source information

CopyManga 1.3.30

### Steps to reproduce

Settings:
Domain: copymanga.org
User-Agent: some desktop user-agent I got from https://tool.lu/useragent
Website version: 2022.06.22 (What is this anyway? I can't find it anywhere either on the desktop or the mobile layout of the website.)
Oversea connection: enabled
WebP: enabled
Convert to Simplified Chinese: disabled

Find any comic from CopyManga then read or download a chapter.

### Expected behavior

Should be able to read and download comic chapters.

### Actual behavior

Whenever trying to read or download any comic chapter from CopyManga, I get a "参数错误"/parameter error prompt.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

If open the comic in WebView, it says "Sorry! This content is not available in your region", same as in issue #12367, but I'm not sure if this is the same problem in a different form.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nathaniel-Wu** [comment]
I updated to 1.3.31 and it doesn't happen anymore, at least for now, hooray

**Comment by KoSChicken** [comment]
All chapters are replaced by 12 horror pictures. I think they've find some way to identify request from tachiyomi.

**Comment by stevenyomi** [comment]
> All chapters are replaced by 12 horror pictures. I think they've find some way to identify request from tachiyomi.

Cannot reproduce. Please post your user agent, webpage version, and manga name.

**Comment by KoSChicken** [comment]
> > All chapters are replaced by 12 horror pictures. I think they've find some way to identify request from tachiyomi.
> 
> Cannot reproduce. Please post your user agent, webpage version, and manga name.

user-agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44
source config:
![Screenshot_2022-06-30-15-55-40-938_eu kanade tach](https://user-images.githubusercontent.com/7444820/176624177-0d2ec03c-1c13-4493-86b5-e3dffbf41adb.png)
manga name and result:
![Screenshot_2022-06-30-15-54-48-820_eu kanade tach](https://user-images.githubusercontent.com/7444820/176624235-0f42b7ac-0204-4359-a2ec-d3b8fe8e14fb.png)

**Comment by stevenyomi** [comment]
I've identified the reason. I think it's time to remove the extension. I'll probably maintain a copy of the extension in my repo.

**Comment by KoSChicken** [comment]
> I've identified the reason. I think it's time to remove the extension. I'll probably maintain a copy of the extension in my repo.

agree, play this cat-mouse game with them is meaningless.

**Comment by Steve-cn** [comment]
> All chapters are replaced by 12 horror pictures. I think they've find some way to identify request from tachiyomi.



> I've identified the reason. I think it's time to remove the extension. I'll probably maintain a copy of the extension in my repo.

For me, 1.3.28 is still available, you can try it.

**Comment by misaka10843** [comment]
For some reason I don't seem to have the picture in the description, it seems to be because of some setting issue, or perhaps the phase has been removed to prevent tachiyomi from accessing the place?
(is using the same user-agent)

In my guess is that some of tachiyomi's requests were obtained by copymanga and judged out, but for some reason not most of the time judged out all lead to only a small probability of occurrence, it seems that as long as the user-agent can be replaced

![Screenshot_2022-07-02-09-04-22-726_eu kanade tachiyomi](https://user-images.githubusercontent.com/69132853/176981108-1cdab348-0cab-433c-a75a-fce829901d39.jpg)
![Screenshot_2022-07-02-09-04-34-225_eu kanade tachiyomi](https://user-images.githubusercontent.com/69132853/176981111-de53456b-cfae-4c49-b38e-b500a1a3388a.jpg)
