### ISSUE TITLE
Adding categories for source

### ISSUE THREAD

**Issue by 0bkhtr0** [tachiyomiorg/tachiyomi-extensions#12379]
### Describe your suggested feature

I used more than 10 extension for my reading. The issue happen when i use global search because it will spend so much time. My idea is we add categories feature like in the library but for extension. For example i want to search a certain manhwa, i only need to go to the categories that have extension for manhwa only. I think this feature will be helpful especially to segregate purely NSFW extension. I hope you like the idea. Thanks in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with the app itself, I should be opening an issue in the app repository.
 
 also already [requested](https://github.com/tachiyomiorg/tachiyomi/issues/1904)
