### ISSUE TITLE
Comick.fun: Unparseable date

### ISSUE THREAD

**Issue by spiwocoal** [tachiyomiorg/tachiyomi-extensions#12373]
### Source information

Comick.fun 1.3.11

### Steps to reproduce

1. Browse for any manga on Comick.fun (i.e. Jujutsu Kaisen)
2. Refresh the manga status

### Expected behavior

Should correctly receive, parse and display manga status and data.

### Actual behavior

`Unparseable date: "2022-06-26T18:29:28Z"` toast appears.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

The date string provided is formatted correctly using the ISO 8601 standard, so the Comick.fun API seems to be supplying the dates correctly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheMerricat** [comment]
For additional reference, this was working as of yesterday (Jun 28) and stopped working today. No updates have been made on my side with regards to the app or the extension. Things that I was subscribed to just simply stopped working with the same error message as reported above.

**Comment by Azeizeil** [comment]
I experienced the same bug and tried uninstalling the app and installing the new one and updated all of my extensions but still no use. For now the solution seems to be just to migrate to another extension

**Comment by zen1557** [comment]
I experience the same bug and i also facing a "null" problem from comick.fun extension.

**Comment by PizzaMcrust** [comment]
Experienced it too, can't even fix it with re-installing everything, Even the app.

**Comment by meotimdihia** [comment]
@everyone Hi, I have fixed the bug with Tachiyomi.

Thanks, everyone for reporting and discussing the bug.
The problem happened because the date format was changed when I updated libraries for my API backend.
It changed from `2022-06-20T09:09:32+00:00` => `2022-06-20T09:09:32.752Z`. Both is `ISO 8601 standard` but the Tachiyomi plugin can't detect the new string.

**Comment by Riztard** [comment]
> @zen1557 please provide the screenshot and create a new issue.

@meotimdihia maybe this #12272
