### ISSUE TITLE
NoyAcg

### ISSUE THREAD

**Issue by poliexz** [tachiyomiorg/tachiyomi-extensions#12385]
### Source name

NoyAcg

### Source link

https://app.noy.asia

### Language

Chinese

### Other details

It is NSFW content and requires login account to use

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by poliexz** [comment]
You can use this invitation code: ccfce015a

**Comment by Wangjn258** [comment]
看不懂，但是好高级的样子
