### ISSUE TITLE
jinmantiantang unparseable date:""

### ISSUE THREAD

**Issue by vjfVbOnXPVX8HCP** [tachiyomiorg/tachiyomi-extensions#12388]
### Source information

jinmantiantang 1.3.28

### Steps to reproduce

comic only have one chapter will report an error

### Expected behavior

something wrong

### Actual behavior

as normally

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
I will fix this.
