### ISSUE TITLE
Assorted Scans failed to update

### ISSUE THREAD

**Issue by Enryu231** [tachiyomiorg/tachiyomi-extensions#12383]
### Source information

Assorted Scans

### Steps to reproduce

1. Open manga Cuprum No Hanayome
2. Try to update

### Expected behavior

Manga should update just fine

### Actual behavior

![Screenshot_20220630-222642](https://user-images.githubusercontent.com/108476768/176705846-a3a2bafe-4b0e-4474-8b0c-20c89c147c6c.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Will be fixed by #12380 when it's merged.

**Comment by alessandrojean** [comment]
Closed by #12380.
