### ISSUE TITLE
Remove Hunters Scan

### ISSUE THREAD

**Issue by Hunterscan** [tachiyomiorg/tachiyomi-extensions#12392]
### Source link

https://huntersscan.xyz

### Other details

Removal of hunters scan from the application in order to reduce the amount of current advertisements that appear on the site

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Soitora** [comment]
Confirmed ownership on Discord
I have not checked if any of the Requirements are met however

**Comment by alessandrojean** [comment]
Has content from many other scanlators.

One of the examples: https://huntersscan.xyz/series/i-have-a-dragons-heart/capitulo-1/

**Comment by alessandrojean** [comment]
Denying it for now as it don't met all the requirements for the removal. The scanlator team is welcome to adapt the website to fill the requirements and ask the removal again if they want.

It's worth mentioning the extension has a severe rate limiting of 1 request per 2 seconds already.

**Comment by alessandrojean** [comment]
Reopening as proof of authorization from the other scanlators was provided to @Soitora's DM too.

**Comment by alessandrojean** [comment]
The extension was removed by PR #12399.

We can't force users that decide to keep the extension installed to not use it any more though.
