### ISSUE TITLE
MangaBuddy: HTTP error 429

### ISSUE THREAD

**Issue by Khlez** [tachiyomiorg/tachiyomi-extensions#12397]
### Source information

Mangabuddy 1.3.8

### Steps to reproduce

1. Click the update button
2. Library is supposed get updated with new chapters for each manga isf they are available 

### Expected behavior

Library updated 

### Actual behavior

A lot of mangas did not get updated. It showed 103 updates failed.

### Tachiyomi version

Tachiyomi v 0.13.4.

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
> You need to provide what error are you getting that are making the global update to fail.

![Screenshot_20220702-011450483](https://user-images.githubusercontent.com/101858971/176943181-1367e17d-f2ea-45d0-89df-ed2da54167a1.jpg)

I'm getting http error 429 from error notif, after test my category include mangabuddy source, choose the first title from error list and do manual refresh and indeed get http error 429, but after few minutes decide to test again with sama title, the error gone, tested with another title in error notice too.

First try 

https://user-images.githubusercontent.com/101858971/176943004-8c3b82fc-ea3e-46ac-8cdb-4bd83fba4126.mp4



Try again a few minutes later

https://user-images.githubusercontent.com/101858971/176942717-d7b90ddd-8123-4e1e-897c-d5438b4b83aa.mp4

**Comment by alessandrojean** [comment]
HTTP 429 just means you got temporary banned due to doing a lot of requests to the website. This usually happens if you read much or download too much stuff.

**Comment by DchanN** [comment]
> HTTP 429 just means you got temporary banned due to doing a lot of requests to the website. This usually happens if you read much or download too much stuff.

I'm didn't read or download before do update test, maybe because too much request update check. Normally me didn't have that's error ( only have little full read manga in mangabuddy), maybe because I'm temporally disable skip for test make that's error

**Comment by vetleledaal** [comment]
The linked PR will hopefully prevent this issue in the future -- rate limiting was added to mangabuddy.com. For existing bans you'll have to wait it out or use a VPN.
