### ISSUE TITLE
Zero Scans: JSON parsing is failing

### ISSUE THREAD

**Issue by nickchanny** [tachiyomiorg/tachiyomi-extensions#12390]
### Source information

Zero Scans 1.2.5

### Steps to reproduce

1. Download Zero Scan Extension
2. Go to a random manga (Eg: Second Life Ranker)
3. Update list of libraries

### Expected behavior

Chapters should be updated to display the latest chapters

### Actual behavior

Update failed to occur
Error Message: 
Expected start of the object '{', but had 'EOF' instead

Perhaps the website changed the way the page was written

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Seems to work fine now
