### ISSUE TITLE
"no chapter found" in mangakakalot

### ISSUE THREAD

**Issue by UNKNONYM0US** [tachiyomiorg/tachiyomi-extensions#12394]
### Source information

Mangakakalot (En) 1.3.8

### Steps to reproduce

Update your mangas

### Expected behavior

It will get updated

### Actual behavior

It didn't got updated due to the error "no chapter found"

### Tachiyomi version

0.13.4

### Android version

11

### Other details

Proof:
![Screenshot_2022-07-01-18-15-39-82_8d485484d290ec17555e7acc83d01a83](https://user-images.githubusercontent.com/104273959/176876400-adcb7590-1293-469b-8caa-e68705ab5e4a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
kakalot likes to change urls often. I checked some of those on your list and they work fine. You'll have to migrate back into kakalot or use another source.
