### ISSUE TITLE
Nhentai: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by benoyel** [tachiyomiorg/tachiyomi-extensions#12405]
### Source information

Nhentai 1.3.34

### Steps to reproduce

![Screenshot_20220702-045225](https://user-images.githubusercontent.com/58552261/176987085-10af9fb1-0d86-4dfd-8345-c7cb3676a4bd.png)

![Screenshot_20220702-045247](https://user-images.githubusercontent.com/58552261/176987094-aeeba47d-b90b-42bb-ae54-0814ee8f3886.png)

![Screenshot_20220702-045256](https://user-images.githubusercontent.com/58552261/176987112-a8d57b0e-05db-4874-8539-10e4344b9a99.png)

![Screenshot_20220702-045311](https://user-images.githubusercontent.com/58552261/176987105-eb0038b2-e50c-4aa1-83af-a9afe7fbd59e.png)

### Expected behavior

![Screenshot_20220702-045517](https://user-images.githubusercontent.com/58552261/176987129-6fea4d64-bf6a-4bd5-9c59-faed10a11b50.png)

### Actual behavior

![Screenshot_20220702-045247](https://user-images.githubusercontent.com/58552261/176987147-3e7bda65-2d5c-49bf-96a1-6dcad3ab0ec4.png)

![Screenshot_20220702-045311](https://user-images.githubusercontent.com/58552261/176987153-eb85de07-77c7-4577-8052-5ec05d228301.png)

### Tachiyomi version

0.13.4

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Don't post NSFW stuff in GitHub...

**Comment by alessandrojean** [comment]
Also this specific Cloudflare issue on Nhentai usually is dependant on the country you're on. Try using a VPN or DNS over HTTPS as suggested first.

**Comment by Omar-Abdul-Azeez** [comment]
Same issue it opens in browser but not in app nor webview

**Comment by YouBoi234** [comment]
Is there anything else i can do? To fix it? Or wait to get updated?

**Comment by vetleledaal** [comment]
Fixed in v0.13.5 / r4622
