### ISSUE TITLE
Hanuman

### ISSUE THREAD

**Issue by 3DaXean** [tachiyomiorg/tachiyomi-extensions#12404]
### Source name

Hanuman Scan

### Source link

Hanumanscan.com

### Language

English

### Other details

Uses WPMangaReader theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Don't close your old issue to bump it in the list.

Duplicate of #11373.
