### ISSUE TITLE
Mangareader chapter jumbled up

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#12428]
### Source information

Mangareader 1.2.2

### Steps to reproduce

Read any manhwa on mangareader( idk if it's the same with manga since i dont read manga on mangareader but yeah)

![Screenshot_20220704_093030](https://user-images.githubusercontent.com/78807765/177071819-66810b49-97a6-4874-93fe-2d71391c2861.jpg)
![Screenshot_20220704_093036](https://user-images.githubusercontent.com/78807765/177071828-5bda8a6f-93b0-43e2-839e-d1fec5f8112e.jpg)
![Screenshot_20220704_093044](https://user-images.githubusercontent.com/78807765/177071836-f0df0c8b-62de-496c-a93e-f921a071a78e.jpg)
![Screenshot_20220704_093050](https://user-images.githubusercontent.com/78807765/177071840-eb232015-0319-4c16-b603-dde0fcbe7dbc.jpg)

### Expected behavior

Work normally

### Actual behavior

The images are jumbled up like a puzzle 

### Tachiyomi version

TachiyomiSY preview r463

### Android version

Android 11

### Other details

Oh yeah, sometimes some chapters dont get jumbled up and i dont really know why they do that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by juniorjacob** [comment]
It appears they simply added their jumbling technique to manhwa now as well since manga already looks like this and get solved in the extensions display mechanic. Should be a simple fix for them but might take some time for them to notice.

**Comment by CrepeTF** [comment]
Works fine on my end on the same manhwa on v1.3.2 and app version 0.13.5
