### ISSUE TITLE
MyAnimelist HTTP error 401

### ISSUE THREAD

**Issue by Nvbeh6** [tachiyomiorg/tachiyomi-extensions#12439]
### Source information

MyAnimelist

### Steps to reproduce

1.
![IMG_20220705_071918](https://user-images.githubusercontent.com/103346344/177227796-5f28683f-82f9-490e-a6bd-4b6de976687f.jpg)
2.
![IMG_20220705_071934](https://user-images.githubusercontent.com/103346344/177227805-5f960e03-b092-499d-bfb7-fca68a19424e.jpg)
3.
![Screenshot_2022-07-05-07-18-41-101_eu kanade tachiyomi](https://user-images.githubusercontent.com/103346344/177227817-c86b136b-ba97-4716-9344-5aad7496fa7d.jpg)

### Expected behavior

not error

### Actual behavior

![Screenshot_2022-07-05-07-18-41-101_eu kanade tachiyomi](https://user-images.githubusercontent.com/103346344/177227841-086a7cd5-07a7-4106-9b64-5d927245b4e0.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Logout of Mal and relogin

**Comment by Nvbeh6** [comment]
thanks
