### ISSUE TITLE
Comicdom 520\502

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#12430]
### Source information

Comicdom 1.3.23

### Steps to reproduce

Open up the extension

### Expected behavior

Work normally

### Actual behavior

Error 502 or 520

### Tachiyomi version

TachiyomiSY preview r463

### Android version

Android 11

### Other details

At first i thought it was maintenance but it's been a week or so and its still not working and i checked through webview it shows this weird display
![Screenshot_20220704_133305](https://user-images.githubusercontent.com/78807765/177095303-c312a7bf-af3d-445a-9455-59eb04ce5555.jpg)
But it works perfectly fine through the browser.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
5xx are server sided errors, the website was slow and did not work for me when I tried through the browser and was the same as what you saw in webview , so you may have either seen a cached version or you weren't on the right website. Nothing we can do about that.
