### ISSUE TITLE
tumanhwas.club

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#12445]
### Source name

Tumanhwas

### Source link

https://tumanhwas.club

### Language

español

### Other details

Please add 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alpqm** [comment]
when will this be added @TheKingTermux

**Comment by TheKingTermux** [comment]
> when will this be added @TheKingTermux 

No need to ping me. Wait until someone wants to work on it.

**Comment by alpqm** [comment]
> kapan ini akan ditambahkan?

How long does it take to add

**Comment by alessandrojean** [comment]
There's no ETA. This is an open source project that contributors work when they want and when they have some free time. It can take months to never happening.
