### ISSUE TITLE
happymh can't bypass cloudflare

### ISSUE THREAD

**Issue by mojunisme** [tachiyomiorg/tachiyomi-extensions#12449]
### Source information

happymh 1.2.2

### Steps to reproduce

showing can't bypass cloudflare when open or download any chapter.

### Expected behavior

read or download image normally

### Actual behavior

showing can't bypass cloudflare when open or download any chapter.

### Tachiyomi version

0.13.4

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mojunisme** [comment]
so how to change UA, happymh doesn't have a UA change option.

**Comment by vetleledaal** [comment]
Fixed in v0.13.5 / r4622
