### ISSUE TITLE
tachiyomi slow to update

### ISSUE THREAD

**Issue by Frozik29** [tachiyomiorg/tachiyomi-extensions#12448]
### Source information

All extensions

### Steps to reproduce

click refresh and wait

### Expected behavior

should update fast, I have 50 manga in my library and tachiyomi for update in the middle and it takes a long time, and usually it stops at numbers: 19, 20 or 21

### Actual behavior

takes a long time and hangs on numbers: 19, 20 21

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

I've already tested using different WiFi and it still didn't work, I've tried using 4g and it didn't work, even when I disable my wifi the update hangs and doesn't continue as usual

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
>  I have tried the troubleshooting guide.

Please refer to the troubleshooting guide first. As you state it happens with all your sources, it's more likely an network issue wich may be fixed by following the steps in the guide. Please also be more descriptive next time, "all extensions" tells us nothing.
