### ISSUE TITLE
Nhentai 

### ISSUE THREAD

**Issue by jtmp2r** [tachiyomiorg/tachiyomi-extensions#12458]
### Source information

All 1.3.34

### Steps to reproduce

All I get is the loading screen when I try to read manga from this source.

### Expected behavior

I expect I can still read and save the manga from this source.

### Actual behavior

Just a load screen.

### Tachiyomi version

0.13.4

### Android version

OnePlus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
nhentai has raised their Cloudflare protection level. Wait for them to lower it to continue using the source.
