### ISSUE TITLE
Sources flare

### ISSUE THREAD

**Issue by TachiApp** [tachiyomiorg/tachiyomi-extensions#12466]
### Source information

manga lionz, manga speak , manga starz , manga lek , manga link

### Steps to reproduce

all that source not working: manga lionz, manga speak , manga starz , manga lek , manga link.

### Expected behavior

because couldflare error

### Actual behavior

Do they all stop working at the same time?😏 

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> I have tried the troubleshooting guide

Please follow the troubleshooting guide and the section that refers to Cloudflare issues. If it doesn't solve it, there's nothing we can do about it, you can wait for the source to lower their protection or migrate to better sources. Also please open one ticket per source next time.
