### ISSUE TITLE
MyRedingManga won't load manga in app or in webview

### ISSUE THREAD

**Issue by Jvlier** [tachiyomiorg/tachiyomi-extensions#12463]
### Source information

MyRedingManga 1.2.43

### Steps to reproduce

Open app, nothing loads.
Before this issue, opening webview would load manga then manga would update and load after refreshing app but now can't even load in webview. Also can't complete captcha to gain access to manga in webview.

### Expected behavior

You should be able to load manga within the app or in webview.

### Actual behavior

Nothing loads. 
Captcha on webview broken however opening in browser after webview, the website itself works fine.

### Tachiyomi version

0.13.4

### Android version

11

### Other details

![Screenshot_2022-07-06-23-39-09-54_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/84441821/177655659-8820feff-f39c-48e2-8e4f-54c528b77fe6.jpg)
![Screenshot_2022-07-06-23-39-15-45_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/84441821/177655675-c4bd9cb3-a469-41b8-ab10-ce6826806a08.jpg)
![Screenshot_2022-07-06-23-39-23-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/84441821/177655682-4a08ab2c-209e-4f23-8c62-a4455a7bc03c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Davevalerio** [comment]
I have a similar problem to me It appears Update skipped in the Tachiyomi APK, I still haven't solved it, you think it's because of the extensions

**Comment by RhakieVenice** [comment]
You should try clearing the myreadingmanga extension cache and data, then go back to webview and solve the captcha.

**Comment by Davevalerio** [comment]
> como es lo de resolver el Captcha? Puedes mostrarme un pantallazo

**Comment by Davevalerio** [comment]
> > Debe intentar borrar la memoria caché y los datos de la extensión myreadingmanga, luego volver a la vista web y resolver el captcha.
> 
> No funciona, borré ambos antes de volver a intentarlo, pero una vez que resuelves el captcha, dice "por favor, espera mientras revisamos tu navegador" y luego vuelve a pedir el captcha, en un ciclo infinito.
> 
> (Puede valer la pena señalar que tengo cloudflare habilitado en la configuración avanzada debido a que MangaDex no funciona de otra manera).

You can try in the advanced configuration (DNS over HTTPS the different options

**Comment by RhakieVenice** [comment]
> @RhakieVenice I've already tried, for some reason it doesn't work for me. I even re-tried following your instructions, but it still asks me for captcha in a loop. I've cleared cache and data from the Myreadingmanga extension, then I opened Tachiyomi and cleared the cookies of the MRM extension. Then opened one of the manga in my library that have MRM as a source, went to webview, solved the captcha but it STILL asked me for captcha again and again.

Maybe try updating your android webview. I have that same problem a month ago and it worked for me. I'm using tachiyomisy btw

**Comment by Farbfrosch** [comment]
I have the exact same issue. I hope it can be fixed T_T

**Comment by yasnil03** [comment]
same with me, loop on the captcha 😭

**Comment by vetleledaal** [comment]
Fixed in v0.13.5 / r4622
