### ISSUE TITLE
Wont update

### ISSUE THREAD

**Issue by Sweepstakes0** [tachiyomiorg/tachiyomi-extensions#12462]
### Source information

Manga diamond 

### Steps to reproduce

Won't update having a problem with loading updates. Updates has failed

### Expected behavior

I want to have all my manga be updated

### Actual behavior

None

### Tachiyomi version

0.12.3

### Android version

Android 9 plus

### Other details

Won't allow updates for my manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I will fill out all of the requested information in this form.

**Comment by Davevalerio** [comment]
I have the same problem, meme appears Update Skipped :(

**Comment by CrepeTF** [comment]
There's no manga diamond extension also you are not even on the latest version of the app even after ticking the acknowledgement
