### ISSUE TITLE
WebtoonXYZ

### ISSUE THREAD

**Issue by iBlueit3011** [tachiyomiorg/tachiyomi-extensions#12465]
### Source information

WebtoonXYZ 1.3.24

### Steps to reproduce

Open "Webtoonxyz" in browse
Refreshing library

### Expected behavior

Display manga and update existing manga in library from source

### Actual behavior

Failed to update manga in library and failed to bypass cloudflare.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed in v0.13.5 / r4622
