### ISSUE TITLE
cloud flare

### ISSUE THREAD

**Issue by Hotaro-kn** [tachiyomiorg/tachiyomi-extensions#12479]
### Source information

MangaLionz 1.3.22

### Steps to reproduce

Cloud flare error 

### Expected behavior

cloud flare error 

### Actual behavior

Cloud flare error 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed in v0.13.5 / r4622
