### ISSUE TITLE
murimscan.run

### ISSUE THREAD

**Issue by DilipPatel007** [tachiyomiorg/tachiyomi-extensions#12474]
### Source name

Murimscan

### Source link

https://murimscan.run/

### Language

English 

### Other details

![Screenshot_2022-07-08-00-20-21-791_com android chrome](https://user-images.githubusercontent.com/78421789/177849873-14639c06-8952-4d85-9165-df1ad7580b7f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme
