### ISSUE TITLE
Haoman8: site under maintenance

### ISSUE THREAD

**Issue by EricFoodTab** [tachiyomiorg/tachiyomi-extensions#12483]
### Source information

haoman8 1.3.2

### Steps to reproduce

trying to use haoman8

### Expected behavior

will be able to load normally and webview will be normal

### Actual behavior

show 404 in tachiyomi and is in maintenance

### Tachiyomi version

0.13.4

### Android version

Android 9

### Other details

the website in webview is https://caiji.haoman8.com/ . If i remove caiji in browser, the website will be able to load normally again.

the new domain is https://www.haoman8.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
That is not a domain change. I'll investigate this later.

**Comment by stevenyomi** [comment]
The current `caiji` site is under maintenance and let's wait for a few more days to see if it will come up again. If not, we'll remove the source.

Better change the title to `Haoman8: site under maintenance`.

The mentioned `www` site should be considered another source and will probably be made into an extension.

**Comment by stevenyomi** [comment]
The site is up. This issue can be closed.
