### ISSUE TITLE
Readkomik Cloudflare issue

### ISSUE THREAD

**Issue by Haiju78** [tachiyomiorg/tachiyomi-extensions#12487]
### Source information

Readkomik 1.3.16

### Steps to reproduce

1. Cant access extension cause of "failed to bypass Cloudflare"

2 Cant access the content of extension cause said problem

### Expected behavior

Able to access extension and the content of extension 

### Actual behavior

"Failed to bypass Cloudflare "

### Tachiyomi version

1.5.5

### Android version

Xiaomi 11t pro

### Other details

![Screenshot_2022-07-09-03-56-02-610_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/97692498/178064311-455df2b3-26eb-481e-be88-d8a2e75eac74.jpg)
![Screenshot_2022-07-09-03-55-19-125_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/97692498/178064325-467ea907-a109-466f-93e1-806ff8a6e091.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed in v0.13.5 / r4622

**Comment by Haiju78** [comment]
In the next update right?

**Comment by vetleledaal** [comment]
For TachiyomiJ2K you need to wait for the next release.
