### ISSUE TITLE
Cloudflare 

### ISSUE THREAD

**Issue by kell20** [tachiyomiorg/tachiyomi-extensions#12503]
### Describe your suggested feature

fix Cloudflare to make it work a little better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
We have no control over cloudflare
