### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by Marinx211** [tachiyomiorg/tachiyomi-extensions#12513]
### Describe your suggested feature

can the creator do the like when you bookmark the chapter you can rename it too. because its to hard to remeber the important chapter if only a bookmark, so if you can bookmark the important and raname this its easier to find important chap

Ps:im bad at English
![Screenshot_20220709_154732](https://user-images.githubusercontent.com/106808221/178128212-1ec7aaf0-64d3-4b6a-acb9-e3d06e2dd358.jpg)

Like you bookmark the chapter and raname this to mc and fmc finally kiss for example 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

Wrong repository.
