### ISSUE TITLE
Toonkor: Changed their domain

### ISSUE THREAD

**Issue by sriwijaya572** [tachiyomiorg/tachiyomi-extensions#12514]
### Source information

Toonkor 1.2.4

### Steps to reproduce

1. Tap browse icon
2. Select source
3. (Installed toonkor) find and choose toonkor source
4. Connection closed

### Expected behavior

After I selected the toonkor source, previously all the comics list was displayed even though it was a little long

### Actual behavior

But what happened instead it said connection closed, and when I checked the source
It has changed the domain to
https://toonkor125.com

### Tachiyomi version

App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z) 

### Android version

Android version: 8.1.0 (SDK 27) Android build ID: OPM1.171019.026

### Other details

![Screenshot_20220710_101504](https://user-images.githubusercontent.com/108703365/178129884-32faeeb8-8e1f-4461-95f6-3df14afd77d8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
I'm try to use Toonkor extension override BaseUrl and input the new url.
![Screenshot_20220710-163830911](https://user-images.githubusercontent.com/101858971/178138714-71bff464-1095-4e9d-949a-b4146802bb4e.jpg)

It's somehow success , open webview show website with new url ( can see in video below) but seems the extension still broken because when try to update manga said chapter not found, when try to read said toon_img script not found, when do browse said not found, and in latest don't show anything


https://user-images.githubusercontent.com/101858971/178138721-4ac9c3bd-b8bf-4075-ab57-e082395684f0.mp4

**Comment by DchanN** [comment]
Changed domain to https://toonkor125.com via Toonkor extension override BaseUrl work
![Screenshot_20220721-210301422](https://user-images.githubusercontent.com/101858971/180226124-e7184425-f051-4ad3-bc84-2732db02397b.jpg)

the only broken it's cover don't show (like broken icon) when browse, search, and open latest. But when select manga and manga info page show cover immediately load, but when go back to latest screen the cover still don't show(preview (it's show when re-open latest)) but in stable the cover show when go back to latest screen


https://user-images.githubusercontent.com/101858971/180226174-751f1d8f-e33a-43b2-ba78-c5031dac62f1.mp4

Stable 

https://user-images.githubusercontent.com/101858971/180227752-938e3d40-04d9-4af3-bc1e-6d5ad28822a9.mp4



But when manga already in library, it's working fine without any issue (Preview)


https://user-images.githubusercontent.com/101858971/180226343-d187cc4b-9952-447d-adf9-cd834901cfb6.mp4

**Comment by TheKingTermux** [comment]
Latest url
https://toonkor158.com

**Comment by abdulmannans** [comment]
@alessandrojean I think we should close this issue as toonkor is taken down.

**Comment by NeKoOuO** [comment]
@sriwijaya572 I think you should close this issue it's too old btw i recreate a new one

**Comment by sriwijaya572** [comment]
@NeKoOuO oh well
I forgot to closed it
Thanks
