### ISSUE TITLE
Add heavier rate limiting to MangaBuddy

### ISSUE THREAD

**Issue by paras1t3s** [tachiyomiorg/tachiyomi-extensions#12512]
### Source information

MangaBuddy 1.3.10

### Steps to reproduce

1. I update my library.
2. It ends
3. I have more than a hundred errors from the same source
![Screenshot_20220709-181856_HTML Viewer](https://user-images.githubusercontent.com/109004378/178125569-1c68c6ec-9d32-4f6b-b410-470c8ad846dd.jpg)

### Expected behavior

It should remove the ban and update the chapters of the mangas that I have added from that source
![Screenshot_20220709-182054_Firefox](https://user-images.githubusercontent.com/109004378/178125596-b0944ac1-c20c-4bf3-9d9e-cee561375969.jpg)

### Actual behavior

it repeats the error every time I update my library

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Was already added in #12484
