### ISSUE TITLE
NHentai extension Can't seem to work

### ISSUE THREAD

**Issue by synchro2223** [tachiyomiorg/tachiyomi-extensions#12520]
### Source information

Nhentai 1.3.34

### Steps to reproduce

It has been showing me blanks and i suspect it can't by pass the cloudflare thing and i've tried to open the browser through app and doesnt show anything.

but when i use chrome or firefox to open up nhentai website it works. any fix to this?

### Expected behavior

-

### Actual behavior

-

### Tachiyomi version

-

### Android version

-

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Didn't fill out template.
