### ISSUE TITLE
InariManga: No results found

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#12523]
### Source information

InariManga 1.3.14

### Steps to reproduce

When you enter the extension manhwas do not appear

### Expected behavior

New chapters or manhwas that have the extension should appear

### Actual behavior

Manhwas do not appear, on the contrary it says they do not exist but if you enter the original page it works
![Screenshot_2022-07-10-12-51-06-528_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/178141796-115e0c08-f2c7-4156-9e34-7747299a110b.jpg)

### Tachiyomi version

0.13.5

### Android version

Miui 12.5.8

### Other details

![Screenshot_2022-07-10-12-51-39-447_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/178141813-9155f950-9354-4c31-b73a-f87217fb2441.jpg)

The page works what doesn't work is the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Theme was changed from MangaThemesia to a heavily modified Madara theme

**Comment by Suiren5** [comment]
> 

¿Y no se puede eliminar y volver a poner?

**Comment by vetleledaal** [comment]
Tachiyomi doesn't host any content, the site operator changed the layout and a change in the extension is required.
(TL) Tachiyomi no alberga ningún contenido, el operador del sitio cambió el diseño y se requiere un cambio en la extensión.

**Comment by Suiren5** [comment]
> Tachiyomi no aloja ningún contenido, el operador del sitio cambió el diseño y se requiere un cambio en la extensión. (TL) Tachiyomi no alberga ningún contenido, el operador del sitio cambió el diseño y se requiere un cambio en la extensión.

¿Y se podría hacer? Yo no sé hacerlo, pero si tú supieras, te lo agradecería eternamente TwT

**Comment by vetleledaal** [comment]
(TL) Tachiyomi es de código abierto, cualquiera es libre de contribuir, por lo que no se pueden dar garantías sobre cuándo y en qué se trabajará.

**Comment by Suiren5** [comment]
> (TL) Tachiyomi es de código abierto, cualquiera es libre de contribuir, por lo que no se pueden dar garantías sobre cuándo y en qué se trabajará.

Esta bien, pensé que a lo mejor tú sabías, pero una cosa, ¿Al menos puedes quitar la extensión y así la vuelvo a pedir?
