### ISSUE TITLE
Alceascan

### ISSUE THREAD

**Issue by libran07** [tachiyomiorg/tachiyomi-extensions#12528]
### Source name

Alceascan

### Source link

https://alceascan.my.id/

### Language

Indonesian

### Other details

![alceascan](https://user-images.githubusercontent.com/90138720/178155273-cafff463-fec9-4df6-a18a-9e9227feaba3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses ZManga theme
