### ISSUE TITLE
Mangalib: HTTP error 419

### ISSUE THREAD

**Issue by Brobrobrobrobr** [tachiyomiorg/tachiyomi-extensions#12529]
### Source information

Mangalib 1.3.81

### Steps to reproduce

Extension is capable 

### Expected behavior

The extension does work 

### Actual behavior

The extension literally doesn't work

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BrainRTP** [comment]
I have same problem

**Comment by BrainRTP** [comment]
@Brobrobrobrobr you can update to v1.3.83. This version fix problem :) 
You can close this issue.
