### ISSUE TITLE
ManhwaChill: HTTP error 400

### ISSUE THREAD

**Issue by Kodoku1919** [tachiyomiorg/tachiyomi-extensions#12535]
### Source information

ManhwaChill 1.3.21

### Steps to reproduce

1. Pressing the extension name (manhwachill)
2. Error 400

### Expected behavior

It would show the menu after pressing the extension.

### Actual behavior

![SmartSelect_20220711-103458_Aniyomi](https://user-images.githubusercontent.com/109061185/178202272-f282fae2-a995-420e-b452-133ca170f1ea.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Sir you are using Aniyomi and not Tachiyomi

**Comment by stevenyomi** [comment]
Can reproduce here. The filename thing seems unrelated.

**Comment by Kodoku1919** [comment]
Sorry but I don't get it. What filename ? And what are those unrelated ?
Please let me know

**Comment by stevenyomi** [comment]
> What filename ? And what are those unrelated ?

Your screenshot's filename is `SmartSelect_20220711-103458_Aniyomi`, which is shown in the Discord channel notification, so people mistakenly thought you were using Aniyomi.

**Comment by Kodoku1919** [comment]
Ah okay, I thought Aniyomi and Tachiyomi are the same, so I sent both.

**Comment by Riztard** [comment]
currently the website is broken
