### ISSUE TITLE
MangaPark v3: Missing chapters when there's a dropdown list

### ISSUE THREAD

**Issue by GrimSkinSama** [tachiyomiorg/tachiyomi-extensions#12537]
### Source information

Mangapark v3 1.0.16

### Steps to reproduce

1. Access Mangapark V3 extension from browse menu
2. Look for "Yu-Gi-Oh! Duelist" Manga
3. On the app it will show "Chapter 0"
4. Select the web view and find the "Chapter 0"
5. Expand the "Chapter 0" Drop Down List

### Expected behavior

I was hoping that the Tachiyomi App able to read sources if it was planted inside a DDL such as this case.

### Actual behavior

The app are only showing the bigger menu which resulting that user are only able to access the first chapter of the manga.

### Tachiyomi version

0.13.5

### Android version

Android 10

### Other details

![App and WebView Screenshot](https://user-images.githubusercontent.com/109073313/178241694-3d4b0e8c-304b-42bf-909a-31522ef078b6.PNG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
Question: Is the number of pages the same on both the site and the app?

**Comment by GrimSkinSama** [comment]
> Question: Is the number of pages the same on both the site and the app?

By number page do you mean when I click the Chapter 0 on the app? If yes, the answer is no.
When I click the chapter 0 on the app, the pages shown are only Vol.1 Ch.1 from the site.

cc : @lasersPew

**Comment by GrimSkinSama** [comment]
> Well here's the thing they messed up when uploading. If you look at other series those dropdown is used to group various versions of a chapter. So this is not an extension issue.
> 
> ![image](https://user-images.githubusercontent.com/59261191/178489102-02a3d3e3-fbdf-471b-94d6-f30e29559b07.png)
> 
> Edit: We can show all versions of a chapter but who would would want bunch of duplicates just to fix a oopsie mangapark made? Edit 2: They have an email on the site you can contact.

whoa, that's just not good. oh well, guess I'll just have to use it as it is. Not sure if someone from mangapark would be willing to fix these kind of issues.
