### ISSUE TITLE
Allporncomic site WebView issue. 

### ISSUE THREAD

**Issue by fam007e** [tachiyomiorg/tachiyomi-extensions#12536]
### Source information

Allporncomic 1.3.21

### Steps to reproduce

Open the extension to browse.
Open in android "WebView".
Captcha verification.
Opening inside app via retrying. 

### Expected behavior

After captcha verification, going back to app and retrying the browse option to view in app structure. 

### Actual behavior

The captcha verification always restarts after completing verification. It doesn't open the original website in the WebView. I have used experimental captcha verification feature also but with or without this enabled it's not working. My WebView app is updated to it's latest edition (version 103.0.5060.71).

### Tachiyomi version

Tachiyomi v8.7.0-AZ

### Android version

Android 11

### Other details

Also could this extension's search option be modes to use its site's older search option because recent search option gives truncated search results (maximum 20).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This was fixed in v0.13.5 / r4622. No ETA for when this will be fixed in TahciyomiAZ.

> Also could this extension's search option be modes to use its site's older search option because recent search option gives truncated search results (maximum 20).

Open another issue for this specifically.
