### ISSUE TITLE
Doujindesu 212.32.226.234: NXDOMAIN

### ISSUE THREAD

**Issue by BANANA25323** [tachiyomiorg/tachiyomi-extensions#12547]
### Source information

Doujindesu

### Steps to reproduce

1. Tap source "Doujindesu"
2. 212.32.226.234: NXDOMAIN

### Expected behavior

Cant show page. It just showing error messege "212.32.226.234: NXDOMAIN" it it happened from the previous version. It never fixed. Please fix it.

### Actual behavior

It must showing any comic or page with many tittle of comic like others source

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kell20** [comment]
Mintak ekstensi baru bro

**Comment by kell20** [comment]
kek manhwaland

**Comment by loocool2** [comment]
**Indonesian NXDOMAIN error**
Indonesian carriers and ISPs are blocking sites using DNS, causing NXDOMAIN errors. They may prevent you from switching to other DNS providers using DNS hijacking/redirection, TCP reset attacks, SNI filtering, and Deep Packet Inspection.
**What can I do to fix it?**
Try turning on DNS over HTTPS under More 🡒 Advanced 🡒 DNS over HTTPS.
**That Didn't Work!**
Your ISP may be using the new blocking mechanism. Use a VPN or use a Deep Packet Inspection Bypass app like [DPITunnel-cli](https://github.com/zhenyolka/DPITunnel-android), [PowerTunnel](https://github.com/krlvm/PowerTunnel), or [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)
