### ISSUE TITLE
Asura Scans Extension

### ISSUE THREAD

**Issue by Hellferion** [tachiyomiorg/tachiyomi-extensions#12552]
### Source information

Asura Scans 1.3.30

### Steps to reproduce

1. Open Extension
2. 2. That's where you see Connection Closed

### Expected behavior

It should show the Asura Scans full library and let you read chapters in tachiyomi app.

### Actual behavior

It only shows Connection closed for both the extension and the chapters in my library, even when opened in Web view. Error shows on J2k, SY & Standard.

### Tachiyomi version

Tachiyomi j2k v.1.5.5

### Android version

Android 12

### Other details

It was working fine till yesterday.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their server is having issues at the moment and there's nothing we can do on the extension side to fix it. Wait until they fix it or migrate to better sources.
