### ISSUE TITLE
source request: `LuminousScans`

### ISSUE THREAD

**Issue by lorrding** [tachiyomiorg/tachiyomi-extensions#12555]
### Source name

LuminousScans 

### Source link

https://luminousscans.com/

### Language

English

### Other details

the website seems to be somewhat similar to https://flamescans.org/ that already have an extension (I can't find any pr or issue mentioning it though).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by lorrding** [comment]
alright is there a page where I can find every scan team that have been blacklisted ?

**Comment by CrepeTF** [comment]
just tap the link the in the bot reply
