### ISSUE TITLE
The ability to sort or group titles by sources in library. 

### ISSUE THREAD

**Issue by ovingiv** [tachiyomiorg/tachiyomi-extensions#12564]
### Describe your suggested feature

By the filter button in the top right then under the Sort tab, have a new choice named Sources. 

Choosing this will group titles by sources alphabetically by both the sources name and title of manga. Then vice versa by choosing it a second time. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

Wrong repository.
