### ISSUE TITLE
I need to add mnhaestate source

### ISSUE THREAD

**Issue by abdulloh-otaku** [tachiyomiorg/tachiyomi-extensions#12566]
### Source name

mnhaestate

### Source link

https://mnhaestate.com/

### Language

arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by abdulloh-otaku** [comment]
this website is different. it's not what you think

**Comment by alessandrojean** [comment]
It's not, it's exactly the same scanlator team and it will not be added back as they requested the removal. Respect their decision.
