### ISSUE TITLE
WebtoonXYZ unavailable 

### ISSUE THREAD

**Issue by DanielGARCIA12** [tachiyomiorg/tachiyomi-extensions#12561]
### Source information

WebtoonXYZ 1.3.24

### Steps to reproduce

WebtoonXYZ suddenly stops working and it's stuck. It cannot bypass the cloudflare and i tried all sorts of things such as clearing cache, cookies, changing DNS over HTTPS, clearing webview data and it's still stuck.

### Expected behavior

After a few or two refreshes, it would normally bypass the cloudflare and the source will start working.

### Actual behavior

The source is stuck on loading and wouldn't bypass the cloudflare. This makes the source unavailable, thus, not enabling the readers to read their favorite manwhas/mangas

![Screenshot_2022-07-13-00-29-45-44_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/109166367/178545749-36345477-8872-432d-8b15-ddc9c9f64ea7.jpg)
![Screenshot_2022-07-13-00-29-59-13_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/109166367/178545783-26142d41-1689-4776-bcd5-0fc00109d98d.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

WebtoonXYZ is working perfectly fine on browsers such as google but it does not work on the Tachiyomi app. Hoping that you will respond to this issue and the source will be fixed. Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They raised their Cloudflare protection and there's nothing we can do about it. Wait until they decide to lower their protection (unlikely to happen) or migrate to better sources that doesn't do that.
