### ISSUE TITLE
MangaReader: Add read volumes option

### ISSUE THREAD

**Issue by dan8443** [tachiyomiorg/tachiyomi-extensions#12573]
### Describe your suggested feature

Unlike other sites mangareader.to has volumes option to read, I want to request this feature in Tachiyomi(please🤞) 
no other source has this feature

![Screenshot 2022-07-13 153641](https://user-images.githubusercontent.com/99420590/178708878-dbb5a70f-72b5-4bd4-a443-6a1989c751c7.png)

maybe can be done by adding another extension by the same source by replacing chapters with volumes (Ignore this I don't know anything technical)

### **I found a volume since app can support**
![Screenshot 2022-07-13 160711](https://user-images.githubusercontent.com/99420590/178714755-dc78315f-a699-4caf-91ab-3f2a8ef61cf6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Kinda weird to add volume support since the app itself has no concept of volume.

**Comment by dan8443** [comment]
> Kinda weird to add volume support since the app itself has no concept of volume.

they are like chapters just bundled together. Most volumes are original digital copies in good quality and  Help to switch between physical to digital and vice versa

**Comment by ObserverOfTime** [comment]
This could be doable with a preference but it would apply to all series, even those without volumes.
