### ISSUE TITLE
Kanzenin can't filtering genre

### ISSUE THREAD

**Issue by BANANA25323** [tachiyomiorg/tachiyomi-extensions#12575]
### Source information

Kanzenin 1.3.15

### Steps to reproduce

1. Open Tachiyomi apps
2. Move to browse menu
3. Open Kanzenin sourch extensions
4. Tap filter button bottom right corner
5. Select any genre (only 1)
6. Tap filter
7. No results found

### Expected behavior

Showing any comics with selected genre on filter button

### Actual behavior

Cant found Can't find any comics with genre that I want "no results found"

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This was fixed in #12918, genres are now automatically fetched
