### ISSUE TITLE
picacomic: invalid accept header

### ISSUE THREAD

**Issue by ForeverNightmare** [tachiyomiorg/tachiyomi-extensions#12577]
### Source information

picacomic 1.3.2

### Steps to reproduce

1.Open Tachiyomi apps
2.Move to browse menu
3.Open picacomic extensions
4.The page will shows "请在扩展设置界面输入用户名和密码"(Please enter username and password in the extension setting interface)
5. Click "open in webview"
6. Webpage shows "code:400 error:1001 message:the format of accept header is invalid" 

### Expected behavior

Showing some comics

### Actual behavior

Showing nothing except ""请在扩展设置界面输入用户名和密码"(Please enter username and password in the extension setting interface)" and 3 icon "retry", "open in webview", "help"

### Tachiyomi version

0.13.5

### Android version

Android 12 and Andorid 11

### Other details

I also didn't find the so called "extension setting" interface so I have no place to enter my username and password. But the invalid accept header seems to be an worse issue so I name this issue with it. Maybe they are 2 different issues?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
这不是插件问题，是你使用Tachiyomi遇到的疑问，请不要在该仓库中以Bug分类发issue！

如果使用的是Tachiyomi，请在应用的“浏览”→“扩展插件”中找到相应插件进行设置
