### ISSUE TITLE
Japscan : Cannot search for mangas

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#12574]
### Source information

Jpascan 1.2.29

### Steps to reproduce

1.Got to the extension list
2.Select the source Japscan
3.Tap the search button and enter the name of a manga
4. The message "HTTP error 403 open the site in WebView appears instead of the result page"

### Expected behavior

See the result(s) of my search.

### Actual behavior

The page shows "HTTP error 403 open the site in WebView appears instead of the result page"

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

Switching to cellular the page shows that there is no result even if the manga searched is on the homepage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gushaa** [comment]
Hello,

There is a general bug on Japscan, you already have a issue [here](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12491)

**Comment by aboudiom59** [comment]
> Hello,
> 
> There is a general bug on Japscan, you already have a issue [here](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12491)

I'm not so sure if it's a general bug or just that the site changed. Like for a while I couldn't read chapters there on my browser with AdBlock on but it went back to normal a few days ago. Not to mention that now I can actually read chapters in the WebView which I never could before because the images didn't show up.
