### ISSUE TITLE
[NHentai] tags aren't separeted only by the comma, also by the space 

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#12588]
### Source information

Nhentai 1.3.34

### Steps to reproduce

1. Open nhentai
2. open filter section and type -oppai loli
3. start the search

### Expected behavior

The extension should exclude the tag "oppai loli"

### Actual behavior

The extension excludes only "oppai"  AND include "loli"

### Tachiyomi version

0.13.5

### Android version

Android 8

### Other details

the extension sees the space the same as the comma, if i type "mature, milf, sister" the extension gives the same result if i type "mature milf sister"
This problem doesn't allow me to exclude the tags with 2 words in it like "oppai loli" since if i type -oppai loli the extension will exclude only oppai and including loli in the results, and i don't want it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MatchaSoba** [comment]
This search behaviour is defined by [the site itself](https://nhentai.net/info/) under the Search section. If you wish to do an exact search for a tag containing a space you should wrap the tag in double quotes.

**Comment by curche** [comment]
Closing this as the extension is working as intended. 
Refer to the site's search options to fine tune your searches. Thanks @MatchaSoba!
