### ISSUE TITLE
Failed to bypass cloudflare 

### ISSUE THREAD

**Issue by Hamndle** [tachiyomiorg/tachiyomi-extensions#12586]
### Source information

Manga starz 1.3.22

### Steps to reproduce

1-open chapter
2-chapter doesn't open
3- failed to bypass cloudflare
4- try to open chapter in browse
5- Browsing by browsing
6-browse page about to blank

### Expected behavior

Chapter shoud open 

### Actual behavior

Chapter doesn't open and failed to bypass cloudflare Show me

### Tachiyomi version

0.13.5

### Android version

Android 9.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#8367
