### ISSUE TITLE
Change domain

### ISSUE THREAD

**Issue by 69iscool2** [tachiyomiorg/tachiyomi-extensions#12596]
### Source information

Komikcast 1.3.27

### Steps to reproduce

Komikcast.com change domain to komikcast.me please upgrade extensions

### Expected behavior

Open komikcast

### Actual behavior

Can't open komikcast 

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Gan itu udh diubah loh domain ekstensinya

`Clossed due not planned`

**Comment by 69iscool2** [comment]
> 
Ah sorry ternyata wifi w yg bermasalah 🙏
