### ISSUE TITLE
Use localized covers & titles in MangaDex extension when available

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#12592]
### Describe your suggested feature

Currently the extension always will use the Jap cover, however some titles (few ones tbh, but it's a pretty new feature) already have localized covers.

### Other details

https://mangadex.org/title/b17187ee-f7c0-44a3-8967-3401249fe715/shitto-na-watashi-to-shikku-na-aitsu?tab=art
https://mangadex.org/title/8c47260f-a754-4977-9040-5b1cb28c43f5/rad-and-rinpu?tab=art

Example with localized covers for Portuguese Br

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This, if ever implemented, should be an option. Not everyone likes to use the localized option (myself included).

**Comment by SrW0nka** [comment]
> This, if ever implemented, should be an option. Not everyone would like to use the localized cover (myself included).

Good point, we should add this feature accompanied by a new option in the extension settings letting the user choose. The default option must be using the localized covers, since our decisions (translating the settings of the ext, using localized descriptions and even translating the tags) point to the use of the localized data

taking advantage, we must also add the localized titles (letting the user choose too)

**Comment by curche** [comment]
Hi, note that as per [MangaDex Site Rules](https://mangadex.org/rules) 
Section 1.7 Cover Images [for manga entries] specifically 1.7.3
> The main cover of a work should be in the same original language as the work itself. Do not translate covers yourself and upload them. 

As such, the examples provided do not comply with the above and the entries will be cleaned up

Now, that aside, I understand the general idea with localized covers and localized alt-titles. However, fetching covers is a different network request and the *extension* will have to decide for the user on whether to show the latest cover, first cover (or a random cover)
The main cover for an entry is currently the same as what MangaDex has. If Dex decides to provide one cover title per language (something a bit more complex than alt-titles ig), it'll be easier to integrate it into the extension. 
Apart from that, Neko might be a better place for this: Have a separate screen which shows all Covers and then let the user manually select a cover of their choice.

Closing this for now
