### ISSUE TITLE
New toast: "No chapters in this language" for MangaDex

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#12591]
### Describe your suggested feature

When a title don't have chapters in the language but there's in another one, instead of "No chapter" show "No chapters in this language"

### Other details

https://discord.com/channels/349436576037732353/694092459839455243/997492090298695680

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I don't think this is doable without making an extra request to the `/feed` endpoint without the `translatedLanguage[]` filter set to check if the quantity returned is greater than the filtered list or by modifying the extension to filter the whole chapter list internally, which shouldn't be the ideal as using their API directly is way more efficient. Also the `/feed` endpoint is paginated, so there are cases where more than one additional request would be required.

"No chapters found" is still a correct error being thrown for this particular situation; users should be able to open the WebView to check if an entry has chapters in the selected language or not.

Closing for now, but can be reopened in the future if Dex returns a `unfilteredTotal` value in the API response which doesn't include the filters in the counting.

**Comment by alessandrojean** [comment]
Actually reopening since it should be doable with one extra request to the manga details endpoint that has a `availableTranslatedLanguages` field.

**Comment by alessandrojean** [comment]
After further discussion with some other contributors, it's not really worth as "No chapters found" is correct in this use case.
