### ISSUE TITLE
MangaDex not fetching new chapter despite API returning it

### ISSUE THREAD

**Issue by gr3ger** [tachiyomiorg/tachiyomi-extensions#12611]
### Source information

MangaDex 1.3.165

### Steps to reproduce

1. Add [Chainsaw Man](https://mangadex.org/title/a77742b1-befd-49a4-bff5-1ad4e6b0ef7b/chainsaw-man)
2. Watch as chapter 98 is not in the list

[The api does return the chapters](https://api.mangadex.org/manga/a77742b1-befd-49a4-bff5-1ad4e6b0ef7b/aggregate), it is just not shown in tachiyomi for some reason.

### Expected behavior

Chapter 98 should be available

### Actual behavior

Chapter 98 is not fetched

### Tachiyomi version

0.3.15

### Android version

Android 12

### Other details

At first I thought it was just a cache issue, but after several days I decided to check the API itself and it seems that is not the case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's an external chapter, Dex doesn't have it. If you click it on the website it will redirect you to MangaPlus. The extension is working as expected in not showing it.
