### ISSUE TITLE
MangaBuddy: HTTP error 429

### ISSUE THREAD

**Issue by Chashi2904** [tachiyomiorg/tachiyomi-extensions#12613]
### Source information

MangaBuddy 

### Steps to reproduce

No 'ew chapter are being download when i update the library 

### Expected behavior

Every new chapter should be download 

### Actual behavior

No new chapter is being download 

### Tachiyomi version

0.13.5 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
HTTP 429 means you've been banned by the site (most likely for excessive network requests), it might be temporary, but there's not been much feedback on this.

The rate limiting was tuned to be more strict in MangaBuddy v1.3.10, did you use this version? It should avoid this issue altogether, but it might have to be further adjusted.

**Comment by DchanN** [comment]
> HTTP 429 means you've been banned by the site for excessive network requests, it might be temporary, but there's not been much feedback on this.
> 
> The rate limiting was tuned to be more strict in MangaBuddy v1.3.10, did you use this version? It should avoid this issue altogether, but it might have to be further adjusted.

I'm use v1.3.10 as soon the ext get updated, and still have that's error, it's seems trigger by how much manga get checked by global update, for now me make some category and exclude it from global update, then divide manga from mangabuddy about 50-60 series in each category and do manually category update

**Comment by vetleledaal** [comment]
Did you get the error _after_ updating to v.1.3.10? Updating the extension wont automatically unban you.

Yes, the error shows after updating a lot of manga in a short amount of time.

**Comment by DchanN** [comment]
> Did you get the error _after_ updating to v1.3.10? Updating the extension wont automatically unban you.
> 
> Yes, the error shows after updating a lot of manga in a short amount of time.

nope, get the error before updating to v1.3.10 , it's around when you update extension for fix pagination, but it's only temporally ban, can access again after a while

**Comment by vetleledaal** [comment]
Right, so it seems like MangaBuddy gives you 30 API calls, which is reset after some amount of minutes (<30min). Cached responses doesn't count towards this. Changing the rate limit to 1 per 4s just uses up the allocation slower, and making it even slower to not produce any errors is probably too slow to be usable.

**Comment by DchanN** [comment]
> Right, so it seems like MangaBuddy gives you 30 API calls, which is reset after some amount of minutes (<30min). Cached responses doesn't count towards this. Changing the rate limit to 1 per 4s just uses up the allocation slower, and making it even slower to not produce any errors is probably too slow to be usable.

yeah, that's why me didn't make issue about this, because it's depended on how much manga get updated, and it's different to everyone, that's why me split my manga from mangabuddy to several category and manually update category in different time when I'm don't have time to check via latest update.

**Comment by Chashi2904** [comment]
Yes I'm currently using this version

**Comment by Riztard** [comment]
fixed #12484

**Comment by DchanN** [comment]
> fixed #12484

This error still happen after extension update, if u read the comment above, if this closed, new same issue maybe will open again by some people use this source
