### ISSUE TITLE
MangaSpark: unable to read chapters and covers are broken

### ISSUE THREAD

**Issue by bessstr** [tachiyomiorg/tachiyomi-extensions#12616]
### Source information

MangaSpark

### Steps to reproduce

1 If I open the class, he fires me immediately. 

### Expected behavior

It should have been opened

### Actual behavior

I open it but it kicks me out. It should have been opened

### Tachiyomi version

0.13.5

### Android version

android 11

### Other details

The problem is that the source is not working properly💔

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If I open the class, he fires me immediately

Please be more specific and inform any errors or issues you're getting. This doesn't help us much about the issue.

**Comment by vetleledaal** [comment]
Seems like covers and chapters are broken. Covers are broken under Popular/Latest. Chapters error out with "Failed to bypass Cloudflare."

Additionally release date isn't properly parsed.

**Comment by vetleledaal** [comment]
/edit-title "MangaSpark: unable to read chapters and covers are broken"
