### ISSUE TITLE
[AnimeSama] 0 chapters

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#12628]
### Source information

AnimeSama 1.3.1

### Steps to reproduce

1. Browse extension
2. Open any manga
3. Shows 0 chapters

### Expected behavior

Chapters should be listed

### Actual behavior

App shows 0 chapters but there are manga chapters on WebView though

### Tachiyomi version

TachiJ2K 1.5.6

### Android version

10

### Other details

![Screenshot_20220719_074036_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/56766778/179666761-850d42ae-5fce-4276-ae26-90ee46b0a0bd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Entries that don't have manga chapters in the are not supported. From what I can tell, only entries that have [scans] in the title have actual chapters

**Comment by Mitia99** [comment]
@loocool2 Entries such as? Can't find one manga with available chapters in this extension though it is a great source
