### ISSUE TITLE
Mangasee and Mangalife cover.thumbnail not showing

### ISSUE THREAD

**Issue by Kilikx2** [tachiyomiorg/tachiyomi-extensions#12639]
### Source information

Mangasee 1.3.29 & Mangalife 1.3.25

### Steps to reproduce

1. Open mangasee or mangalife on sources using browse mode or latest mode
2. Wait for thumbnail image to load

### Expected behavior

Thumbnail showed image for each manga cover

### Actual behavior

Manga cover fails to load 

### Tachiyomi version

0.1.35

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
current cover url for website is temp.compsci88 and old one is cover.nep.li. should probably wait if it changes back since the current cover has temp in name or programmatically figure out cover url and not hard-coding it.
