### ISSUE TITLE
Doujindesu: Missing genres

### ISSUE THREAD

**Issue by AETHER0009** [tachiyomiorg/tachiyomi-extensions#12637]
### Describe your suggested feature

I hope the developer can complement the genres in the doujindesu extension.In tachiyomi there are only genres from age regression to muscle. Whereas in the web version doujindesu there is more than that. Please help perhaps more genres can be added. Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AETHER0009** [comment]
Oke gan makasih

**Comment by TheKingTermux** [comment]
![IMG_20220802_165921.jpg](https://user-images.githubusercontent.com/50316075/182347886-f6f84357-3a8e-45f3-b0d9-7cb90d25d554.jpg)
Sudah dicoba gan
Mungkin ntar up klo Doujindesu dah bikin domain baru.
Untuk thumbnail mungkin masih belum bisa muncul
