### ISSUE TITLE
baozi manhua chapter split page if image more than 50 包子漫画

### ISSUE THREAD

**Issue by kuronekonokuro** [tachiyomiorg/tachiyomi-extensions#12642]
### Source information

Baozi manhua 1.3.9

### Steps to reproduce

open any manhua with more than 50 images 
For example 
https://cn.webmota.com/comic/chapter/gaonenglaixi-yebixiaopei/0_219.html
https://cn.webmota.com/comic/chapter/morenzhishang-boyidongman_e/0_141.html
https://cn.webmota.com/comic/chapter/shenchongjinhua-yuewenmanhua_d/0_122.html

Will tell you to 点击进入下一页 after 50 image in WebView
Extension won't parse next page

### Expected behavior

Extension should parse more than 50 image 

### Actual behavior

Stuck at 50 image

### Tachiyomi version

0.13.5

### Android version

Android 10

### Other details

![IMG_20220720_053800](https://user-images.githubusercontent.com/103270649/179853051-9e01370b-b172-4127-8bc3-2d88cb08ea20.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kuronekonokuro** [comment]
https://www.webmota.com/comic/chapter/zhujiemorizaixian-yanhuochengchengyuanzhu/0_151_4.html
@stevenyomi

**Comment by stevenyomi** [comment]
> page 4 not loaded in tachiyomi

I have identified the problem. Will fix it soon.
