### ISSUE TITLE
Source request 

### ISSUE THREAD

**Issue by kiyoko-otomo** [tachiyomiorg/tachiyomi-extensions#12640]
### Source name

 SWAT manga

### Source link

https://swatmanga.co/

### Language

Arabic 

### Other details

It doesn't have a cloudflare ( i think) I'm using Adguard dns for ad blocking and it's working fine for me in this site, so i don't think it will have the “failed to bypass cloudflare„ issue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
already exists, its under MangaSwat
