### ISSUE TITLE
Komga: Publishing Finished status

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi-extensions#12644]
### Describe your suggested feature

The Komga extension should be able to utilize the status `SManga.PUBLISHING_FINISHED` for certain series. I envision this being used when a Series on Komga meets these conditions:

- Status is set to Ended,
- Total Book Count has been set, and
- the number of books is less than the Total Book Count.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
What's the difference between publishing finished and ended?

**Comment by kiriya-aoi** [comment]
One main difference is that Completed manga are excluded from updating by default - my own use case is that when I fetch metadata for Komga, the Ongoing/Ended status is set based on the publication status. I like this in Komga because I can set the total number of books: I can see that a series is completely published, I just don't have all of it yet.
