### ISSUE TITLE
KOMiKU

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#12660]
### Source name

KOMiKU

### Source link

https://komiku.com

### Language

Indonesia 

### Other details

Please add this source

![Screenshot_2022-07-21-14-24-01-184_com kiwibrowser browser](https://user-images.githubusercontent.com/23666289/180136037-a4848deb-96e8-4240-a11c-7e064a77aa09.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Uses WPMangaReader theme 
Is NSFW? No
