### ISSUE TITLE
Bakkin: Chapter number are parsed to incorrect values

### ISSUE THREAD

**Issue by RossSmyth** [tachiyomiorg/tachiyomi-extensions#12668]
### Source information

Bakkin 1.3.4

### Steps to reproduce

1. Have Anilist or something connected with Tachiyomi
2. Open the Bakkin extension
3. Open a series (Yuru Yuri for example)
4. Read the latest chapter (currently 164)
5. See that Tachiyomi has now marked chapter 264 as read

### Expected behavior

I would expect that chapter 164 would be detected

### Actual behavior

It seems that "264" is parsed from the name "Volume 20 - Chapter 164: Game-dat Getup"
This happens with all of the chapters, and not just the latest, and also in other series from Bakkin.

### Tachiyomi version

J2K 1.5.6

### Android version

Android 11

### Other details

My guess is that if "$vol" is removed from this line, it would be fixed.
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/5972fde3e48282465e211acae29b98a44bd17f1b/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/bakkin/BakkinJSON.kt#L13

For Oomuru-ke it is 10 above the latest chapters fwiw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
This is not a bug since the chapter number actually corresponds to the index of the chapter in the list.
Yuru Yuri has 265 chapters including the covers and other special chapters which are not numbered.

**Comment by RossSmyth** [comment]
Every other extension I have used does the expected thing. For example Dynasty Scans has most of the Bakkin releases of Yuru Yuri, 233 of them to be exact, but when I read the latest chapter my Anilist status is updated to 162, not 233 as Bakkin does. This is what I expect and is correct.

This is a bug, it would be nearly pointless to update to the cumulative chapter total of a source.
