### ISSUE TITLE
MangaDex not fetching new chapter despite API returning it

### ISSUE THREAD

**Issue by soredake** [tachiyomiorg/tachiyomi-extensions#12662]
### Source information

mangadex 1.3.165

### Steps to reproduce

1) add made in abyss to list
2) it only shows chapters up to 57

### Expected behavior

All available chapters should be shows, api shows up to 63.2

https://api.mangadex.org/manga/80422e14-b9ad-4fda-970f-de370d5fa4e5/aggregate

### Actual behavior

It shows only 57 chapters, instead of 63.2

### Tachiyomi version

0.13.5

### Android version

Android 12L

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Works fine at my end. Check the following:
1. Are you using MangaDex (ENG)?
2. Did you already try swiping down to refresh chapter list?

**Comment by soredake** [comment]
1) Yes
2) Yes

I will reinstall app and see if problem persists.

**Comment by soredake** [comment]
After reinstalling app all works as expected, sorry for the noise.

**Comment by curche** [comment]
Likely a stale cache thing or similar.
If it occurs again, try Clearing Cache/Database from More > Settings > Advanced and other steps in Troubleshooting guide instead of going to the last resort
