### ISSUE TITLE
Japscan: Stuck downloads

### ISSUE THREAD

**Issue by choco-latin** [tachiyomiorg/tachiyomi-extensions#12672]
### Source information

japscan 1.3.30

### Steps to reproduce

The extension is broken in the sense that it is impossible to open or download chapters. It seems that the extension is still able to connect to the website, since it still gets updates for new chapters. 
The research in the ’explore’ tab also fails.
Webview successfully reaches the website.

### Expected behavior

Opening and downloading chapters

### Actual behavior

Failure to download, as described above.

### Tachiyomi version

0.13.5

### Android version

android 10

### Other details

I’ve seen that the previous related issues got closed, so i hope that it is ok that i opened this new issue.

Last update was done in PR #12609 

See also issues #12574 and #12491

I did not try to clear my cache and database as i was afraid to lose data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by king07-0** [comment]
the site change there img url from https://c.japscan.ws/ to https://cdn.statically.io/img/c.japscan.ws/ 
so:
1. change the url in the kotlin file line 382
2. increment the graddle version
3. run the pipeline
I build a debug apk to test it and the dowload seems good
I'll try to create a PR later but if someone else are faster...

**Comment by choco-latin** [comment]
Thank you for your time @king07-0 , I'm gonna check that!
