### ISSUE TITLE
Yugen Mangas: No results found

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#12673]
### Source information

Yugenmangas 1.3.25

### Steps to reproduce

When you enter there is no manhwa error 500
![Uploading Screenshot_2022-07-21-17-29-12-704_eu.kanade.tachiyomi.jpg…]()

### Expected behavior

 Let the manhwas be seen

### Actual behavior

When you enter there is no manhwa error 500
![Screenshot_2022-07-21-17-29-12-704_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/180253586-f90d0f61-0cbf-4aae-9e82-849074348b32.jpg)

### Tachiyomi version

0.13.5

### Android version

Miui 12.5.8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Already fixed by current versions of the extension.
