### ISSUE TITLE
Manga-Scantrad: Unable to connect with the source

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#12681]
### Source information

Manga-Scantrad 1.3.24

### Steps to reproduce

1. Go to the source list
2. Open the Manga-Scantrad source
3. Source takes a while trying to load before showing the message "Impossible to overturn Cloudflare"
4. Open the WebView of the source
5. Complete the captcha
6. Site redirect me to the captcha and repeat.

### Expected behavior

After completing the captcha I should be redirected to the site. From there I should be able to access Manga-Scantrad from the source

### Actual behavior

The site in the WebView continue to redirect me to the captcha page no matter how many times I complete it.

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

I can acces the site normally in the browser

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
