### ISSUE TITLE
Mangagg: Can't find the manhwa they actually have in WebView

### ISSUE THREAD

**Issue by moiashi** [tachiyomiorg/tachiyomi-extensions#12682]
### Source information

Mangagg 1.3.24

### Steps to reproduce

1) Installed Mangagg for migration source
2) Looked up manhwas (specifically A Love Contract with the Devil) in Mangagg via Tachiyomi browser section and Mangagg extension
3) But couldn't find any even though it's available in the webview

### Expected behavior

Devil № 4 or A Love Contract with the Devil should have appeared in Mangagg
![Screenshot_2022-07-22-08-58-34-301_com ecosia android](https://user-images.githubusercontent.com/109772227/180339403-a33533ce-b505-40c9-947f-32cb12bf1809.jpg)

### Actual behavior

A Love Contract with the Devil cannot be found. I've also tried searching Lookism since I saw it in the home page in webview, but nothing appears from Mangagg
![Screenshot_2022-07-22-08-52-40-392_eu kanade tachiyomi](https://user-images.githubusercontent.com/109772227/180339577-07155173-6fc6-4733-9e9b-0335d58eeb53.jpg)
![IMG_20220722_085259](https://user-images.githubusercontent.com/109772227/180339579-88e7b4fa-32de-4b71-9496-748dbf1bd12c.jpg)
![IMG_20220722_085339](https://user-images.githubusercontent.com/109772227/180339585-0979fbdc-2be6-494d-ac85-1b46e9e58199.jpg)
![IMG_20220722_085431](https://user-images.githubusercontent.com/109772227/180339587-b19ab3d9-e3eb-4a9f-859f-a56587d6f0f5.jpg)
![Screenshot_2022-07-22-08-54-51-068_eu kanade tachiyomi](https://user-images.githubusercontent.com/109772227/180339589-09765bfa-9a17-48a1-a8d0-94470492f1ef.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Does it appear if you disable the "Show only manga entries" filter?

**Comment by moiashi** [comment]
> Does it appear if you disable the "Show only manga entries" filter?

Sorry for the late reply! I just tried what you asked since I never knew about it and the result has appeared. Thank you so much! 😔🫶🏽
