### ISSUE TITLE
Manga9co: Covers do not load

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#12680]
### Source information

Manga9co 1.3.2

### Steps to reproduce

Browse the extension or load a manga page

### Expected behavior

The thumbnail and the details being shown

### Actual behavior

The thumbnail is broken and is not retrieved 

### Tachiyomi version

Latest

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KoSChicken** [comment]
cannot reproduce. network problem maybe.
![Screenshot_2022-07-22-12-19-23-794-edit_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/7444820/180361777-2b9c4914-3651-4d36-bb66-17bceb6ef006.jpg)

**Comment by sohilsayed** [comment]
Don't think it's an internet problem because the site itself is showing it
![Screenshot_20220722-192620](https://user-images.githubusercontent.com/66560257/180492429-ed703b73-f3b1-4844-bc15-f77f4074d935.png)
![Screenshot_20220722-192459](https://user-images.githubusercontent.com/66560257/180492476-aea224bd-5df9-4e68-b2e8-b82ae22ea54c.png)
![Screenshot_20220722-192451](https://user-images.githubusercontent.com/66560257/180492492-c7ec2eaf-bf25-4d06-b194-d2c6f111eb48.png)
