### ISSUE TITLE
Local Source

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#12683]
### Source information and language

Local Source

### Steps to reproduce

1. Open the "Local" source

### Expected behavior

1. The manga that I have in the tachiyomi/local folder load and appear normally.

### Actual behavior

Nothing comes out, not even the reason for the bug

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

![Screenshot_20220721-211602_Tachiyomi](https://user-images.githubusercontent.com/101371218/180355646-bc865e47-2a9d-43ae-ae78-b0eac4f9228e.jpg)
![Screenshot_20220721-211613_My Files](https://user-images.githubusercontent.com/101371218/180355658-b74237fb-c688-4449-a6b8-b6b308fa2ebf.jpg)

This only happens when I add the "Bleach" folder which contains 52 chapters in .cbr, I remove it from there and the rest loads normally, I wonder why this happens, I would appreciate an answer, I guess it is because of the weight, but it has no logic because the Opm folder (JAP) weighs 7gb and loads normally, I checked the Bleach files and they have nothing harmful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

The local source is a built-in source into the app, so you need to open the issue in the app repository instead.
