### ISSUE TITLE
MangaStic: Changed their domain

### ISSUE THREAD

**Issue by Styx870** [tachiyomiorg/tachiyomi-extensions#12696]
### Source information and language

MangaStic 1.3.23

### Steps to reproduce

1. Go to MangaStic source
2. Tap any manhwa (shows no chapters found)
3. Tap source, redirects to "https://mangastic.com/" their old website with a countdown

### Expected behavior

Should be pulling from "https://mangastic.me/" their new updated website instead of their old website "https://mangastic.com/"

### Actual behavior

Displays available manhwas with no chapter available because it pulls from their old website domain

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nellyisanon** [comment]
Was about to open this same issue

**Comment by Neverdusk** [comment]
I'm also having the same "no chapters" issue. I see titles but every manga's page is empty. Using app version 13.5, extension version 1.3.24.

**Comment by jpmc** [comment]
Chiming in to also say "having the same issue"
App Version: 0.13.5
Extension Version: 1.3.24

**Comment by elizabbetta** [comment]
Me apareció lo mismo solo que mi versión de la app es la 0.13.6 y la de la extensión es 1.3.24
