### ISSUE TITLE
Koushoku: Search and Filter is not working properly

### ISSUE THREAD

**Issue by KazKaz90** [tachiyomiorg/tachiyomi-extensions#12693]
### Source information and language

Koushoku 1.3.7 (English)

### Steps to reproduce

Just doing what a normal person should do.

### Expected behavior

Should work as intended

### Actual behavior

https://user-images.githubusercontent.com/90075041/180494999-1a9b24f2-9c2a-4e04-a90c-4a8c352335a6.mp4

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KazKaz90** [comment]
@alessandrojean I'm not sure why you changed the title, the Search function is also broken, some entries aren't found even when the entire title is entered. They are visible, however, when you filter by artist or search for a specific **word** on that entry, which is extremely frustrating.

**Comment by KazKaz90** [comment]
Another bug (this also happens on forks)
I  will not make a separate issue about this since it's on the same source extension.

Title is messed up

![Screenshot_20220723-184118.png](https://user-images.githubusercontent.com/90075041/180602373-32b1a4df-7338-40d0-b188-56f64685579e.png)

Title on the site

![Screenshot_20220723-184306.png](https://user-images.githubusercontent.com/90075041/180602463-0f4853a5-4f66-40fb-a101-6eadea61c02d.png)

**Comment by alessandrojean** [comment]
It's better if you open another issue about the title as it's a different problem, and it will help to keep track on what have been addressed and what not.

And about this issue title, I likely erased the "Search" by mistake, my bad.
