### ISSUE TITLE
ZinChanmanga: HTTP error 429

### ISSUE THREAD

**Issue by Clary22** [tachiyomiorg/tachiyomi-extensions#12692]
### Source information and language

ZinChanmanga and MangaBuddy

### Steps to reproduce

1. Open the category that you want to update.
2. With your finger slide down from the top of  the screen to manually update all the titles for this category.
3. Or, you can you can select the global update option from the tree dots at the right side corner of the screen.

### Expected behavior

After the updates are done, the error http 429 shouldn’t show up every time in the error report.

### Actual behavior

The error http 429 keeps showing up in the error report, I know one time is normal because it can be temporarily but it has been happening for two months and the titles are not the same every time. I even started updating ones a day, and using the skip updating titles option with the app, but the error is still coming back.

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
For MangaBuddy check #12613

**Comment by ObserverOfTime** [comment]
Duplicate of #11934
