### ISSUE TITLE
8Muses Comics - Unable to resolve host "8muses.love"

### ISSUE THREAD

**Issue by benoyel** [tachiyomiorg/tachiyomi-extensions#12698]
### Source information and language

8Muses Comics 1.3.23

### Steps to reproduce

![Screenshot_20220723-003955](https://user-images.githubusercontent.com/58552261/180584162-787e1431-7ca7-41ac-b151-917e86a479cb.png)
![Screenshot_20220723-004027](https://user-images.githubusercontent.com/58552261/180584185-c5bf33f1-d9fc-4b36-8fc3-65ee0375abcd.png)

### Expected behavior

![Screenshot_20220723-005716](https://user-images.githubusercontent.com/58552261/180584232-0983c620-9423-4a1c-8979-d563cc85fd21.png)

### Actual behavior

![Screenshot_20220723-003955](https://user-images.githubusercontent.com/58552261/180584243-c28dc157-b5b9-4935-b070-c48ea6f95509.png)

### Tachiyomi version

0.13.5

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
whois says: `Registry Expiry Date: 2022-07-26T23:59:59.000Z`
they might renew it, but we'll see in 3 days
