### ISSUE TITLE
WuxiaWorld: No Chapters Found

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#12705]
### Source information and language

WuxiaWorld 1.3.24

### Steps to reproduce

Pick a series
Receive "No Chapters Found" but WebView has chapters

If series is already in library from before becoming broken, chapter links still work

### Expected behavior

Should find chapters

### Actual behavior

Finds none

### Tachiyomi version

SY r464, Preview r4631

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
probably they change the manga url, try refresh or migrating to itself (wuxia world)
