### ISSUE TITLE
Kuaikanmanhua: Random failure on reading/downloading

### ISSUE THREAD

**Issue by donmor** [tachiyomiorg/tachiyomi-extensions#12700]
### Source information and language

Kuaikanmanhua 1.3.10

### Steps to reproduce

1. Find `穿越后除了我都是重生的` in this source
2. Open a chapter, `77` for example
3. Try clicing `download` on this chapter

### Expected behavior

1. Content show up
2. Chapter downloaded

### Actual behavior

1. Certain page fails to show up
2. Download fails, prompting `Expected URL scheme 'http' or 'https' but no colon was found`

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

Usually happens on the first page of a chapter. Not reproduced on other books yet.

This may be related to the previous #12480 .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
Only reproducible in 穿越后除了我都是重生的? This comic is no longer available for read.
這本漫畫已經下架了，會不會是發生錯誤的原因？

**Comment by donmor** [comment]
并没有下架啊。。可能是我在app买了所以有
