### ISSUE TITLE
Nana ナナ

### ISSUE THREAD

**Issue by KazKaz90** [tachiyomiorg/tachiyomi-extensions#12711]
### Source name

Nana ナナ

### Source link

https://nana.my.id

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses LANraragi, but seems like `/api/search` returns 404.

**Comment by RePod** [comment]
From /tutorial:

EXTERNAL READERS ARE NOT SUPPORTED
This is a highly modified version of lanraragi, external readers are not supported. Don't complain to lanraragi devs / external readers devs.

**Comment by KazKaz90** [comment]
I see, thanks anyway.
