### ISSUE TITLE
Problème lecture Japscan

### ISSUE THREAD

**Issue by Freedent-72** [tachiyomiorg/tachiyomi-extensions#12718]
### Source information and language

Japscan 1.3.30 Français

### Steps to reproduce

Démarrer un scan via la source Japscan et le lire.

### Expected behavior

Lecture des images du scan.

### Actual behavior

Impossibilité de lire les images du scan. Chargement infini malgré la fibre optique et le redémarrage de l'application. Ce problème arrive depuis plusieurs jours.

### Tachiyomi version

App version: 0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed in #12714
