### ISSUE TITLE
Nettruyen: Changed their domain

### ISSUE THREAD

**Issue by ilovekaguya** [tachiyomiorg/tachiyomi-extensions#12724]
### Source name

Nettruyen

### Source link

http://www.nettruyenme.com/

### Language

Vietnamese

### Other details

Nettruyen has changed their source to nettruyenme.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the Issue report form next time when this happens, this isn't the right form for this case.
