### ISSUE TITLE
E-Hentai: Missing some tags in the filters

### ISSUE THREAD

**Issue by shirooo39** [tachiyomiorg/tachiyomi-extensions#12720]
### Source information and language

E-Hentai 1.3.17 Enforced English

### Steps to reproduce

1. Go to the browse menu
2. Tap on the extension
3. Open up the filter menu
4. Tap on the "Female Tags section"
5. Search for "emotionless sex" or "prositution" on the list

### Expected behavior

I expected all of the tags on the E-Hentai site can be searched through the extension.

### Actual behavior

some of the tags present on the site are not present in the extension.

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

There are some number of tags that are missing in the extension, that I'm aware of.
For example:
- "female:emotionless sex"
- "female:prostitution"
- "male:ghost"

It's bugging me out that some tags are not present as I find it sooo much easier to search on Tachiyomi than on the E-Hentai site itself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MatchaSoba** [comment]
Tags have not been updated for at least 2 years, and the misc tags section is extremely incomplete since there are thousands of tags in that category, not sure if it's more appropriate to manually update the tags once or change the implementation to dynamically retrieve the tags every time? [List of official EH tags](https://ehwiki.org/index.php?title=Category:Tag&pagefrom=dougi#mw-pages)

**Comment by shirooo39** [comment]
> Tags have not been updated for at least 2 years, and the misc tags section is extremely incomplete since there are thousands of tags in that category, not sure if it's more appropriate to manually update the tags once or change the implementation to dynamically retrieve the tags every time? [List of official EH tags](https://ehwiki.org/index.php?title=Category:Tag&pagefrom=dougi#mw-pages)

I just noticed that there's a search button on the top right corner.
can the search function pass tags search?
if it can pass the tags, I think the workaround is just let user search for the tags from the search field.

for example, I didn't see the f:prostitution tag anywhere on the available tags in the filter.
I can still use the filter but then I can also use the search field to search for the tags that are not available in the filter.

**Comment by MatchaSoba** [comment]
Yes, it has always been possible to search for tags through the top search bar. I agree it would be more convenient to do so through the filter menu though. However, given that there are 719 tags in the fetish category alone, adding every single one would make the filter menu a nightmare to scroll through. Maybe you could specify what kind of tags you would like to be added?
