### ISSUE TITLE
MangaReader: scrambled images

### ISSUE THREAD

**Issue by Dmonzoro** [tachiyomiorg/tachiyomi-extensions#12722]
### Source information and language

MangaReader 1.3.2 

### Steps to reproduce

![Uploading Screenshot_2022-07-25-09-45-50-642_eu.kanade.tachiyomi.jpg…]()

### Expected behavior

Pages should have loaded so the reader can read the page and can understand 

### Actual behavior

The pages appear in checkers pattern so 

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Do you have any specific examples? Manga name and chapter would be sufficient

**Comment by stevenyomi** [comment]
Can't reproduce this. I checked random chapters in the manga mentioned and there's nothing scrambled.

It's probably because appending `&query` to the URL is error-prone. I'm gonna use fragment to mark scrambled images in the next PR.
