### ISSUE TITLE
Sheamanga.my.id

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#12748]
### Source name

Sheamanga.my.id

### Source link

http://62.171.176.78/

### Language

Indonesia

### Other details

18+

and note,
![image](https://user-images.githubusercontent.com/40079068/181187767-0b493aab-8b22-4a64-86e9-8381e9792686.png)
the picture above is not shea manga but this is web https://sheakomik.com/.
please change this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We don't use raw IPs as this is not a good habit. Don't they have a new domain? If it's not the case, you need to wait for them to register a new one.
