### ISSUE TITLE
Crunchy-DL

### ISSUE THREAD

**Issue by Dudovisque** [tachiyomiorg/tachiyomi-extensions#12740]
### Source name

Crunchy-DL

### Source link

https://crunchy-dl.com/

### Language

Portuguese

### Other details

The website is https://crunchy-dl.com/ but have anime and mangás almost all mangás have links like 
https://crunchy-dl.com/manga/name of manga\ (ex: https://crunchy-dl.com/manga/spy-x-family/) the site need a account verify with discord, if this a problem, i can talk with the owner for provide a account without a verification, 
In the home have few mangas, but have a lot in the site that you can acess with link

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Tachiyomi WebView doesn't allow authentication with social media providers in WebView (it's a WebView limitation imposed by the providers itself as security measures) and the website also have a higher Cloudflare protection enabled.

**Comment by Dudovisque** [comment]
oh, okay, i understand, thankyou

**Comment by Dudovisque** [comment]
i checked here and the pages with /manga/* don't have cloudflare protection, so i think this help, and without a account verification that i said is possible make a extension ?

**Comment by alessandrojean** [comment]
> without a account verification that i said is possible make a extension

If the manga details page, listing and chapters are accessible without any verification (ie I can just open a browser and read it directly), yes. If they do change that, feel free to open a new issue and request it again.
