### ISSUE TITLE
Golden Manga

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#12749]
### Source name

Golden-Manga

### Source link

https://golden-manga.me

### Language

Arabic

### Other details

We hope that it will be added because it bears the same faces and faces as a source (GMANGA) Comparison photos between the two sites
1- GMANGA
![Screenshots_2022-07-27-10-45-55](https://user-images.githubusercontent.com/87826849/181191673-2843295c-cf04-459c-969c-c6806f895e18.png)
2- Golden-Manga
![Screenshots_2022-07-27-10-46-36](https://user-images.githubusercontent.com/87826849/181191797-841a2325-b841-403e-a0a2-068ebd16dd6d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
New URL: https://golden-manga.me/

**Comment by alaweeGAMAR** [comment]
please add

**Comment by ZoMpziO** [comment]
Please add it

**Comment by ZoMpziO** [comment]
Please
