### ISSUE TITLE
MangaHub.fr

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#12743]
### Source name

MangaHub

### Source link

https://mangahub.fr

### Language

French

### Other details

I discovered this site a very short time ago and since many sources don't have the mangas I want to read, so I suggest this site which looks pretty good. There is some hentai too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme.
```kt
dateFormat = SimpleDateFormat("d MMM yyy", Locale("fr"))
```
