### ISSUE TITLE
MangaFlix

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#12747]
### Source name

MangaFlix

### Source link

https://mangaflix.fr/

### Language

French

### Other details

I saw that the extension was already available in Arabic, but this one is in French and I think it would be nice if it would be part of it too. ^^

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's not ideal to use raw IPs to access websites and as far I can tell there isn't any extension that does that.

Doesn't they have a proper domain?

**Comment by Showzur** [comment]
Vous avez raison, il est vrai qu'il est préférable d'utiliser un domaine, cependant je n'ai pas trouvé de domaine pour ce site, cependant la seule chose que j'ai trouvée pour accéder à ce site est ce lien :

http://ec2-3-124-244-136.eu-central-1.compute.amazonaws.com
or
https://ec2-3-124-244-136.eu-central-1.compute.amazonaws.com

**Comment by Showzur** [comment]
You are right, it is true that it is better to use a domain, however I did not find a domain for this site, however the only thing I found to access this site is this link :

http://ec2-3-124-244-136.eu-central-1.compute.amazonaws.com
or
https://ec2-3-124-244-136.eu-central-1.compute.amazonaws.com

**Comment by Showzur** [comment]
I think I found the real field, I apologize, I correct that: 

https://mangaflix.fr/
