### ISSUE TITLE
Zbulu: loading image (My Toon, HolyManga, etc.)

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#12755]
### Source information and language

My toon 1.2.4

### Steps to reproduce

The manhwas chapters should appear on tachi 

### Expected behavior

The manhwa chapter should load 

### Actual behavior

The manhwa chapters are not loading 

### Tachiyomi version

0.13.5

### Android version

11

### Other details

![Screenshot_20220727-163349_Tachiyomi](https://user-images.githubusercontent.com/57017947/181240870-7cbb37e5-ce3c-45f0-8bdf-2bd791bfd3d1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fawadkhan121** [comment]
Its not a single but the whole manhwa on site its working in webview

**Comment by vetleledaal** [comment]
/edit-title "Zbulu: loading image (My Toon, HolyManga, etc.)"

**Comment by vetleledaal** [comment]
Also an issue for HolyManga, which uses the same theme, Zbulu.
