### ISSUE TITLE
Mangakatana

### ISSUE THREAD

**Issue by ashyrlur** [tachiyomiorg/tachiyomi-extensions#12752]
### Source information and language

Mangakatana V 1.3.6

### Steps to reproduce

![Screenshot_20220727_162224](https://user-images.githubusercontent.com/78615132/181200168-92235ff6-5685-4493-bfcc-b3ca0b6024fc.jpg)

### Expected behavior

![IMG_20220727_162349](https://user-images.githubusercontent.com/78615132/181200209-b6e70683-7289-4f56-83f4-5b3297b97b0c.jpg)

### Actual behavior

![Screenshot_20220727_162224](https://user-images.githubusercontent.com/78615132/181200241-90dc78cc-4571-4959-84b0-4ee1cf21e6f3.jpg)

### Tachiyomi version

Latest stable (0.13.5)

### Android version

Android 12

### Other details

See the difference? It's not really that much of a big deal to me but it's still a bug and it happens quite a few times already and i checked in webview the image are good. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Tried disabling crop borders on the reader settings of the app?
