### ISSUE TITLE
Hentaiteca has cloudflare problem.

### ISSUE THREAD

**Issue by Jefferson975** [tachiyomiorg/tachiyomi-extensions#12766]
### Source information and language

Hentaiteca 1.3.24 (Brasil)

### Steps to reproduce

1. Tap browse within the app.
2. enter hentaiteca.
3. the page does not load.
4. and says it is not bypassing cloudflare.

### Expected behavior

I expected the extension to load itself normally.

### Actual behavior

instead, the extension says it's not getting around cloudflare.

### Tachiyomi version

0.13.5

### Android version

Android 8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We can't do anything as they have a higher Cloudflare protection. Migrate to better sources instead.
