### ISSUE TITLE
MangaHub: broken chapter images

### ISSUE THREAD

**Issue by Psycho00001** [tachiyomiorg/tachiyomi-extensions#12773]
### Source information and language

Mangahub 1.3.13

### Steps to reproduce

1. Go to mangahub
2.click any manga
3.view a chapter
4.image couldn't be loaded
![Screenshot_20220729-150646](https://user-images.githubusercontent.com/90850908/181703043-50b52e29-5d4f-4fee-9d7c-a7a697946e7e.png)

### Expected behavior

This should happen if i click any chapter and the image should load 

### Actual behavior

This happen instead the image couldn't load

### Tachiyomi version

0.13.5

### Android version

Asus m1 max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by crazydevil9** [comment]
Same here

**Comment by ggabriel1016** [comment]
Same here, any way to fix this?

**Comment by Beji-kun** [comment]
Same problem for sources https://1manga.co/ 
Which has same pattern
![Screenshot_2022-07-29-08-30-26-985_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63636174/181744275-834fce29-3afb-4b4c-8db0-04c0b0355128.jpg)
![Screenshot_2022-07-29-08-30-29-745_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63636174/181744306-a7951345-0a4f-462d-84ba-94b1c0b9c86a.jpg)

**Comment by crazydevil9** [comment]
> Same here, any way to fix this?

Only ones who do the updates and fixes can do ut let's hope they do.

**Comment by Icefire113** [comment]
Same here
