### ISSUE TITLE
Mangahub doesn't load

### ISSUE THREAD

**Issue by Saltyapplepies** [tachiyomiorg/tachiyomi-extensions#12772]
### Source information and language

Mangahub 1.3.13

### Steps to reproduce

As usual i tried to open the chapter but it only says "retry"

### Expected behavior

It should open the new chapter but it doesn't. 

### Actual behavior

For all mangas on mangahub, the retry screen comes

### Tachiyomi version

1.5.6

### Android version

Android 12

### Other details

![Screenshot_20220729-123736_TachiyomiJ2K](https://user-images.githubusercontent.com/87009772/181690621-6b4f2e53-5897-4548-92a3-163c9e7a2177.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Beji-kun** [comment]
Sámer problem with source https://1manga.co/
![Screenshot_2022-07-29-08-30-29-745_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63636174/181697244-3ea6efd5-6797-4faa-9eee-2a2d50129fac.jpg)
![Screenshot_2022-07-29-08-30-26-985_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63636174/181697260-975129f5-176c-4253-ba41-8de1d13dd077.jpg)

**Comment by Riztard** [comment]
close in favour of #12773
