### ISSUE TITLE
Nhentai Failed to bypass Cloudfare 

### ISSUE THREAD

**Issue by Zambiap** [tachiyomiorg/tachiyomi-extensions#12784]
### Source information and language

Nhentai 1.3.35

### Steps to reproduce

1.Failed to Bypass Cloudfare 
2.Webview doesn't work properly (all white and letters) 

### Expected behavior

It should open properly and webview is looks exactly as it should be on website 

### Actual behavior

It didn't open properly and fail and I've also tried all sorts of things to fix it but it still didn't work 

### Tachiyomi version

0.13.5

### Android version

Android 6.0.1

### Other details

![Screenshot_20220729_220243](https://user-images.githubusercontent.com/110188155/181778180-0ec8eeec-bd93-43fb-8bde-0ab982e473f5.png)

![Screenshot_20220729_214223](https://user-images.githubusercontent.com/110188155/181778205-133fb5b9-2d5c-4c52-8679-37c9a30afc50.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EndEavor23** [comment]
I tried to uninstall it and hope to install it again but it didn't appear anymore, maybe they've removed it

**Comment by raziel100** [comment]
I have the same issue has well. For a workaround for now. You can do what the user abdelkd have said in issue #13015 have said

Change the user agent at Settings -> Advanced -> Default user agent string
Put this line instead 
Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36

Restart tachiyomi, try to enter NHentai, you'll receive the cloudfare erro, just click to open in webview after loading will work just fine, at least for me have been working
