### ISSUE TITLE
Mangahub

### ISSUE THREAD

**Issue by kedar773** [tachiyomiorg/tachiyomi-extensions#12786]
### Source information and language

Mangahub 1.3.13 

### Steps to reproduce

1. Selecting manhwa from the source list
2. Retrying if it's failed to load

### Expected behavior

The manhwa should open

### Actual behavior

After 3-5 sec it displays "image can't be loaded"
![Screenshot_20220729-232208](https://user-images.githubusercontent.com/62484275/181817018-bdf60f04-9d06-4749-9945-62a809ea62f0.png)

### Tachiyomi version

0.13.5

### Android version

9

### Other details

Other sources are working fine except for mangahub

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#12773
