### ISSUE TITLE
Random Scans: Changed their domain

### ISSUE THREAD

**Issue by VilksIT8** [tachiyomiorg/tachiyomi-extensions#12787]
### Source information and language

Random Scan 1.3.27 (portuguese)

### Steps to reproduce

the Source URL of the random scan extension has been changed by scanlator and when accessing the extension appears on the screen
 HTTP ERROR 500: Check website in webview

### Expected behavior

the extension should be opened normally for selecting or reading a manga

### Actual behavior

when opening the extension appears on the screen
HTTP Error 500: Check website in webview

### Tachiyomi version

0.13.5

### Android version

Android 8.0.0

### Other details

Scanlator changed the site's source domain to .com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Raidre** [comment]
A URL mudou para:
ramdomscans.com
