### ISSUE TITLE
Mangahub gives HTTP error 403 not from Cloudflare 

### ISSUE THREAD

**Issue by Tsankov03** [tachiyomiorg/tachiyomi-extensions#12794]
### Source information and language

Mangahub 1.2.10 (English)

### Steps to reproduce

To reproduce :

> 1. Open a manga from Mangahub

> 2. Open a random chapter

### Expected behavior

Opening the chapter images

### Actual behavior

I get HTTP error 403. 
There are no problem when I open it from WebView and no issues with Cloudflare either

### Tachiyomi version

App version: 0.13.5 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ayush982** [comment]
Same

**Comment by ansanyyi** [comment]
same 😭

**Comment by Miellenials** [comment]
This website blocking some attempts on webview
![Screenshot_20220730-155949](https://user-images.githubusercontent.com/65380422/181903967-1b1201c3-90ad-4066-96ca-9dcefcec2fb2.png)

This one normally open on webview
![Screenshot_20220730-160952](https://user-images.githubusercontent.com/65380422/181903981-8984935f-32ab-4fc9-b394-29ef11e30641.png)

The tachiyomi app always got 403 error, suspected it got redirected to ads site that cant be opened
![Screenshot_20220730-160934](https://user-images.githubusercontent.com/65380422/181903986-c3aea47f-a3c9-44c0-82af-a340aeef94a4.png)

**Comment by 110408** [comment]
Same

**Comment by Leverpastej** [comment]
Same error for me
Phone: Samsung Note20 Ultra 5G
Android version: 12
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N986BXXU4FVG3
Device brand: samsung
Device manufacturer: samsung
Device name: c2s
Device model: SM-N986B
Device product name: c2sxeea

**Comment by crazydevil9** [comment]
Same as me. I'm hopping it's getting fixed tho if it getting banned or removed I hope these don't happen mangahub and isekaiscan I normally the best sources go to so I hope it returns

**Comment by KylerParker504** [comment]
Same

**Comment by crazydevil9** [comment]
> Same

If u like a other source till they fix mangahub theirs ether mangaBuddy or mangacultivator they seem update n latest chapters to isekai or cultivator type mangas or ones similar. Also isekaiscan good place. Let's just hope it gets fixed soon but it's better not rush who trying fix it if rushed their be more or one or two problems. But if not rushed it be fixed without any problems hopefully

**Comment by alessandrojean** [comment]
Update the extension for a fix, closing as it's working now.
