### ISSUE TITLE
1Manga.co not working

### ISSUE THREAD

**Issue by geverin** [tachiyomiorg/tachiyomi-extensions#12790]
### Source information and language

1Manga.co

### Steps to reproduce

1. Open chapter from 1Manga
2. Error image can't load 

### Expected behavior

Load image 

### Actual behavior

Gives error

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kissieh** [comment]
This problem has already spread to many extensions, and this is the first time i see the team struggling this much to fix a bug, hope it doesn't happen again after this...
