### ISSUE TITLE
hentaivn not working because hentaivn.moe changed to hentaivn.fun

### ISSUE THREAD

**Issue by vuondao915** [tachiyomiorg/tachiyomi-extensions#12793]
### Source information and language

HentaiVN 1.2.12 (Vietnamese)

### Steps to reproduce

1. Open Hentaivn
2. Can't load

### Expected behavior

load manga, image

### Actual behavior

unable to resolve host "hentaivn.moe": No address associated with hostname

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Will be fixed in #12760
