### ISSUE TITLE
Miau Scan

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#12807]
### Source information and language

Miau Scan 1.3.14

### Steps to reproduce

No se ven las portadas
![Uploading Screenshot_2022-07-30-18-18-59-037_eu.kanade.tachiyomi.jpg…]()

### Expected behavior

Deberían verse las portadas 

### Actual behavior

No se ven las portadas

### Tachiyomi version

0.13.5

### Android version

Miui 12.5.8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce. Can you provide an example manga where this is an issue?

(TL) No se puede reproducir. ¿Puede proporcionar un ejemplo de manga en el que esto sea un problema?

**Comment by vetleledaal** [comment]
Still can't reproduce, try following the guide for broken covers: https://tachiyomi.org/help/faq/#why-are-some-cover-thumbnails-corrupted-white-showing-a-broken-page-or-wrong
