### ISSUE TITLE
issuu

### ISSUE THREAD

**Issue by chacuchu** [tachiyomiorg/tachiyomi-extensions#12819]
### Source name

issuu

### Source link

https://issuu.com/

### Language

all the languages

### Other details

I'm very sorry my English is very bad and I don't know anything about programming but I hope it helps you.

The page does not have many ads, or pop-up screens (if that can intervene)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This is a digital publishing software. How is Tachiyomi able to parse this website in any way?

**Comment by samlux04** [comment]
Right, it has a marketplace for books, magazine, maybe comics too. Not relevant to tachiyomi.

**Comment by alessandrojean** [comment]
Closing as far way off-topic.
