### ISSUE TITLE
KomikMama: changed domain

### ISSUE THREAD

**Issue by encualbino** [tachiyomiorg/tachiyomi-extensions#12833]
### Source information and language

Komikmama 1.3.14

### Steps to reproduce

the Source URL of komikmama extension has been changed

### Expected behavior

the extension should be opened normally for selecting or reading a manga

### Actual behavior

when opening the extension appears on the screen
Failed to connect to /99.83.154.118 (port 443) from /192.168.1.4 after 30000ms

### Tachiyomi version

0.13.5

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Domain changed from https://komikmama.net to https://komikmama.co
