### ISSUE TITLE
Comick: chapters marked Official group in Website do not have group associated to them

### ISSUE THREAD

**Issue by Paradox3759** [tachiyomiorg/tachiyomi-extensions#12831]
### Source information and language

Comick.fun Ver. 1.3.12

### Steps to reproduce

1. Install Extension.
2. Search for a Manga in the extension.
3. Add a Manga from having chapters from no source.
4. Click on Filter.
5. Click on Scanlator.
6. Checking and Unchecking "No source" option not available.

### Expected behavior

"No Source" option should be visible for checking and Unchecking in Scanlator Tab.

### Actual behavior

"No source" option doesn't show up in Scanlator Tab resulting in removal of chapters in Manga when checked or unchecked any other source.

### Tachiyomi version

TachiyomiSY Ver. 1.8.4

### Android version

Android 8.1.0

### Other details

![IMG_202204145](https://user-images.githubusercontent.com/110382529/182111144-20fec51b-f24e-4f08-bc49-6a973f2c5cd8.jpg)
If unchecked or checked any other source, the chapters from No source also gets hidden because of this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
While the Scanlator Filter doesn't exist in main app, I'll have to label this as a Sy bug/request

That said, checking on few examples, there's still a "missing group"
Example:
1. Check Konosuba https://comick.fun/comic/konosuba-god-s-blessing-on-this-wonderful-world
2. Extensions lots of chapters with no group associated
3. Open webview. These chapters are marked as Official group

**Comment by curche** [comment]
/edit-title "Comick: chapters marked Official group in Website do not have group associated to them"
