### ISSUE TITLE
Category hopper 

### ISSUE THREAD

**Issue by Hxyxyd** [tachiyomiorg/tachiyomi-extensions#12845]
### Source name and language

Manga 

### Describe your suggested feature

Library and categories 

Can you add like a transaction animation to move between categories
Like when you slide on the category hopper instead of changing it's position you can move between categories and then it comes back to it's position (middle or right or left)

### Other details

Can you add like a transaction animation to move between categories
Like when you slide on the category hopper instead of changing it's position you can move between categories and then it comes back to it's position (middle or right or left)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
This isn't j2k

**Comment by Hxyxyd** [comment]
> This isn't j2k

My bad
