### ISSUE TITLE
WoopRead: can't read the novel chapters in-app

### ISSUE THREAD

**Issue by sswanlake** [tachiyomiorg/tachiyomi-extensions#12855]
### Source name and language

WoopRead (English)

### Describe your suggested feature

Most of the WoopRead titles are novels, rather than manga, but the extension has no way to parse the text to show it in the Tachiyomi app, you need to navigate to the source website to read the chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://tachiyomi.org/help/faq/#can-tachiyomi-read-light-novels
