### ISSUE TITLE
Webtoons.com: add support for genres in filter

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi-extensions#12859]
### Source information and language

Webtoon.com

### Steps to reproduce

No genre and not even image loading properly 

### Expected behavior

It should have filter 

### Actual behavior

There no filter and image loading properly 

### Tachiyomi version

Stable 0.13.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "Webtoons.com: add support for genres in filter"

**Comment by vetleledaal** [comment]
Please open another issue for images not loading properly. You need to provide more information such as what manga and chapter this occurs on.
