### ISSUE TITLE
Uzay Manga HTTP ERROR 400

### ISSUE THREAD

**Issue by kyoyacchi** [tachiyomiorg/tachiyomi-extensions#12864]
### Source information and language

Uzay Manga 1.3.24 - Turkish

### Steps to reproduce

1.Install Uzay Manga
2. Try to use it.
3. You won't be able to use it since it says HTTP ERROR 400

### Expected behavior

it should work properly.

### Actual behavior

Here is the actual behavior
![Screenshot_20220804-162146](https://user-images.githubusercontent.com/63583961/182857771-a25737d4-aa9b-4f51-bf4b-1c5ceef2112a.jpg)

### Tachiyomi version

1.5.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Theme changed from Madara to MangaThemesia
