### ISSUE TITLE
Persisting Koushoku IP Ban

### ISSUE THREAD

**Issue by djo-bidin** [tachiyomiorg/tachiyomi-extensions#12869]
### Source information and language

1.3.12

### Steps to reproduce

1. Koushoku is included in the global search list (using the search tool in Browse) and returns results (not sure if this also happens for the opposite).
2. Enter koushoku from aforementioned search list.

My current workaround is to search for manga from each source individually (e.g. sadpanda, nhentai) rather than from the global search list. This includes entering koushoku directly via the extension. I haven't been given the ban hammer from this yet.

### Expected behavior

Should be able to browse the site via Tachiyomi normally.
Accessing the website on a web browser (e.g. Bromite) does not give this behavior.

### Actual behavior

Accessing koushoku.org via global search will result in a temporary IP ban.
Gives HTTP Error 403.

### Tachiyomi version

TachiyomiAZ v8.7.1-AZ/Tachiyomi v0.13.5

### Android version

Android 10

### Other details

If this overlaps with #12851, please feel free to merge it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AcidAntics** [comment]
When trying to read items that are already in your library from Koushoku, you get this error (I removed possible item identifier for privacy)
![Screenshot_20220806-115559_TachiyomiJ2K](https://user-images.githubusercontent.com/110342980/183229207-dcffaf08-1006-4281-9211-e6ffb0968b62.jpg)
