### ISSUE TITLE
Some broken Turkish sources.

### ISSUE THREAD

**Issue by kyoyacchi** [tachiyomiorg/tachiyomi-extensions#12863]
### Source information and language

Turkish

### Steps to reproduce

https://noxsubs.com/ (Noxsubs)

https://puzzmos.com/ (Puzzmos)

https://uyuyanbalik.com/ (Uyuyan Balık)

### Expected behavior

All of them should have work properly

### Actual behavior

doesn't work.

### Tachiyomi version

1.5.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source, otherwise it's difficult to us to keep track on what have been already addressed and what not.
