### ISSUE TITLE
Mangasushi Extension issue

### ISSUE THREAD

**Issue by rs8167** [tachiyomiorg/tachiyomi-extensions#12878]
### Source information and language

Mangasushi 1.3.26

### Steps to reproduce

Browsing the extension will result in the issue

### Expected behavior

While browsing, a list of manga should appear

### Actual behavior

![IMG_20220806_182615](https://user-images.githubusercontent.com/47599276/183249820-c4bfe98f-f1c2-426f-ae53-f4556c105b15.jpg)

### Tachiyomi version

TachiyomiSY version 1.8.4 

### Android version

Android 11

### Other details

Apparently it's trying to load manga from wrong website i.e. mangasushi.net 

The correct website is mangasushi.org

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by supersaiyandoyle** [comment]
Same, got a similar message when I tried to update, everything from mangasushi kicked back the error.

**Comment by rs8167** [comment]
After checking it again, the website is working
