### ISSUE TITLE
Auto open series info upon searching six digit codes

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi-extensions#12877]
### Source name and language

NHentai(All), Cubari(All)

### Describe your suggested feature

1. User types 6 digit codes on the search bar.
2. User clicks Enter
3. source searches manga info then app opens it automatically.

### Other details

Another thing, It would be nice if we have 'to the horny' mode to directly open the reader and not the series info. Also, Would like it to alert users if the series they searched has blacklisted tags(which can be added in the settings(of the extension or the app)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Nhentai: just search `id:6digitcode`.
There'll anyways be edge cases (eg: title which actually contains 6digit number in its name) so a prefix based search is always preferred 

Cubari: just search `cubari:source/slug`
Note that cubari doesnt have 6digit codes, you need to specify `source` (imgur/reddit/nh/etc) **and** `slug` (6digit code/alphanumeric identifier/etc)

> directly open the reader and not the series info. 

I understand the use case and this can easily be generalized to the case of manga/oneshots which only have 1 chapter. You can make a request at the Tachiyomi App repo
(Personally, would just recommend adding to library and using the Start Reading button)

> Would like it to alert users if the series they searched has blacklisted tags (which can be added in the settings(of the extension or the app)

Make a separate request. Alternative would be to just have saved search filters ig but that's a different topic

Closing with above said reasons. Please make sure to create only 1 request per issue
