### ISSUE TITLE
zerobyw fail to connect

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#12874]
### Source name and language

zerobyw 中文 0.13.9

### Describe your suggested feature

add a new domain name(http://www.zerobywidu.com),
The current domain name cannot be resolved in some regions。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
wrong form
