### ISSUE TITLE
vomic

### ISSUE THREAD

**Issue by Baoziqinru** [tachiyomiorg/tachiyomi-extensions#12891]
### Source name

vomic

### Source link

http://www.iewoai.com/#/home

### Language

Chinese

### Other details

This website has a lot of comic resources, it is recommended to make plug-ins, thank you 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Uses the same theme as Mangabz.
