### ISSUE TITLE
"Multi" as language instead of "All"

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi-extensions#12892]
### Describe why this should be added

"Multi" will be more appropriate to classify source/extension as they contain multiple languages and not *all*.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Related: https://github.com/tachiyomiorg/tachiyomi/pull/7200#issuecomment-1139148769

**Comment by arkon** [comment]
App rewording was merged for next release. You'd want to also update the website.
