### ISSUE TITLE
Harimanga Dates not showing

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#12901]
### Source information and language

Harimanga English 1.3.25

### Steps to reproduce

1. Go into Harimanga extension
2. Select any manga
3. Dates will only show for the most recent (maybe up to 3 to 5 days)

### Expected behavior

Show all the upload dates

### Actual behavior

Only shows dates up to 3 days

### Tachiyomi version

J2K 1.5.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me
