### ISSUE TITLE
Newtoki

### ISSUE THREAD

**Issue by AlejandroTodoroki26** [tachiyomiorg/tachiyomi-extensions#12907]
### Source name

Newtoki

### Source link

https://newtoki147.com/

### Language

Coreano 

### Other details

Ya está el módulo solo hace falta actualizarlo para que pueda funcionar 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
From Tachiyomi Discord:

> Some Korean sources use numbered domains that changes every 7 to 10 days to avoid being shut down. While there is not a permanent fix you can use, you can go to the settings for the extension and change the domain to what's currently used.

> Changing the override from `newtoki62.com` to `newtoki68.com` in your extensions settings
