### ISSUE TITLE
Holy manga extension bugged

### ISSUE THREAD

**Issue by Meh21091997** [tachiyomiorg/tachiyomi-extensions#12921]
### Source information and language

Holy manga 1.3.5 TLS issue

### Steps to reproduce

Don't know

### Expected behavior

It should open fine not crash

### Actual behavior

It crashes

### Tachiyomi version

Tachoyami 13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Unable to reproduce. No log file was provided, but make sure you have a WebView implementation installed, see https://tachiyomi.org/help/guides/troubleshooting/#update-webview. This is required for some extensions where the site uses Cloudflare's I'm Under Attack Mode.
