### ISSUE TITLE
MangaHub: HTTP error 403

### ISSUE THREAD

**Issue by hidayatsohif** [tachiyomiorg/tachiyomi-extensions#12929]
### Source information and language

 Mangahub 1.3.14 (English)

### Steps to reproduce

1. Go to Mangahub source
2. Click on the latest button.
3. Error appeared.
4. Try the troubleshooting guide, but the error still appeared.

### Expected behavior

Something like this should happen

![WhatsApp Image 2022-08-10 at 6 48 55 PM](https://user-images.githubusercontent.com/87002030/183883841-57f4c74e-2df4-46ed-80c9-bab6e154ac66.jpeg)

### Actual behavior

This happens instead
![WhatsApp Image 2022-08-10 at 6 48 54 PM](https://user-images.githubusercontent.com/87002030/183883876-c179c8f4-0787-46d3-9595-ea710b189f92.jpeg)

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 110408** [comment]
Same

**Comment by Beji-kun** [comment]
Same bug appears on extension 1Manga.co
Problem is with load new chapter but reading old chapter which is loaded isn't problem.

**Comment by jpxiller** [comment]
Same
