### ISSUE TITLE
MangaHub: HTTP error 403 as #12929

### ISSUE THREAD

**Issue by meromex** [tachiyomiorg/tachiyomi-extensions#12936]
### Source information and language

Mangahub 1.3.15 (English)

### Steps to reproduce

1. Go to Mangahub source
2. Click on the latest button.
3. Error appeared.
3. Try the troubleshooting guide, but the error still appeared.

### Expected behavior

Something like this should happen
![183883841-57f4c74e-2df4-46ed-80c9-bab6e154ac66](https://user-images.githubusercontent.com/34610160/184055476-3d84f304-14ef-4e32-b905-4964be74c3aa.jpeg)

### Actual behavior

This happens instead
![Screenshot_20220810-213254](https://user-images.githubusercontent.com/34610160/184055558-ae665a0a-84a8-40f2-b5b8-794fa4357e7a.png)

### Tachiyomi version

App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)

### Android version

Android version: 11 (SDK 30) Android build ID: RPAS31.Q2-59-17-4-3-8

### Other details

Shortly after the fix on #12929 it started to happen again. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
i have tested in preview has well, and it's not working, i have clean cache, cookies and webview data and it's still not working
