### ISSUE TITLE
Very Important extension 

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi-extensions#12933]
### Source name

newtoki148

### Source link

https://newtoki148.com/webtoon?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0

### Language

Korean

### Other details

![Uploading Screenshot_20220810-230534_Chrome.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Newtoki already exists as an extension. Update the domain in the extension settings if that's a problem you're having.

**Comment by Akashi123-deep** [comment]
Perhaps they change the link on Tachiyomi " newtoki 177.com "
But I ' looking for  " https://newtoki148.com "
You know what I mean?

Thanks for your help

**Comment by alessandrojean** [comment]
Change the URL in the extension settings.

Browse > Extensions > Newtoki > Gear button > URL
