### ISSUE TITLE
Azure scans: error 404

### ISSUE THREAD

**Issue by avillev** [tachiyomiorg/tachiyomi-extensions#12942]
### Source information and language

Azure scans 1.3.15

### Steps to reproduce

All search and downloads from this plugin are failing.

### Expected behavior

It should work

### Actual behavior

Error 404

### Tachiyomi version

0.13.5

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Their site is broken, you should probably try getting in touch with them.

**Comment by Blackklegend** [comment]
> Their site is broken, you should probably try getting in touch with them.

Hmmm, how so? It works fine here if I open on browser/WebView 
https://azuremanga.com/

**Comment by avillev** [comment]
I confirm, the website is up and running

**Comment by AntsyLich** [comment]
Did you try doing the same step you do on tachi? Open the site > Open a series > Open a chapter

**Comment by avillev** [comment]
Ok now I get it, 404 there as well.
