### ISSUE TITLE
Bad link for extension reaperscan (FR)

### ISSUE THREAD

**Issue by Thomas-unique** [tachiyomiorg/tachiyomi-extensions#12957]
### Source information and language

Reaperscan 1.3.29 (french)

### Steps to reproduce

Bad link

### Expected behavior

Search for new chapters on reaperscan.com

### Actual behavior

Search for new chapters on new.reaperscan.com

### Tachiyomi version

13.5

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Adam935** [comment]
it's done so u can close it
