### ISSUE TITLE
MangaHub: GraphQL Error

### ISSUE THREAD

**Issue by Psycho00001** [tachiyomiorg/tachiyomi-extensions#12959]
### Source information and language

Mangahub 1.3.13

### Steps to reproduce

Open 1manga.co
Open any manga
Click any chapter cant load

### Expected behavior

Should able to read any chapter in 1manga.co

### Actual behavior

Cant load any manga chapter
![Screenshot_20220813-171144](https://user-images.githubusercontent.com/90850908/184477414-b54e2a87-7d3f-4174-a9cd-2b185718621e.png)

### Tachiyomi version

0.13.5

### Android version

Asus m1 max

### Other details

#12931 
![Screenshot_20220813-171144](https://user-images.githubusercontent.com/90850908/184477529-f4a44abb-65c1-40d1-a704-e72cfd5e8155.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by meromex** [comment]
Can confirm same issue 
![Screenshot_20220813-043129](https://user-images.githubusercontent.com/34610160/184477966-99911c9b-e5a9-4dbe-865d-67495ee7c4e6.png)

**Comment by arkon** [comment]
This also affects the following sources that are basically just the same website:

1Manga.co, MangaFox.fun, MangaHere.onl, MangaHub, Mangakakalot.fun, MangaNel, MangaOnline.fun, MangaPanda.onl, MangaReader.site, MangaToday, and MangaTown (unoriginal)
