### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Eddie300** [tachiyomiorg/tachiyomi-extensions#12962]
### Source information and language

Submanga(spanish),tumanga.net(spanish) and kirishima fansub (spanish)

### Steps to reproduce

Error 404 in the app and works in the web 

### Expected behavior

Error 404

### Actual behavior

Error 404

### Tachiyomi version

0.13.5

### Android version

Android 9

### Other details

I don't know, I hope it helps haha

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
please open one issue per source, and it looks like kirishima fansub is already known #11649
