### ISSUE TITLE
Mangapark giving JSON issue

### ISSUE THREAD

**Issue by ianisomega** [tachiyomiorg/tachiyomi-extensions#12963]
### Source information and language

Mangapark

### Steps to reproduce

Open Mangapark
Select any chapter of any manga, manhwa, manhua, etc.

### Expected behavior

This shouldn't happen

### Actual behavior

When trying to read any Mangapark Chapter of anything, gives the message
Unexpected JSON Token at offset 17: Expected EOF after parsing, but had = instead JSON input: document.domain = 'mangapark.net'

### Tachiyomi version

0.13.5

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Edgard666** [comment]
Same for me.

**Comment by ahmedzs321** [comment]
I am facing a similar issue on Android 10

**Comment by Frooodle** [comment]
Likewise for me

**Comment by thegreatdk** [comment]
Same for me, I use android 11 with latest tachiyomi version and extension

**Comment by crest1993** [comment]
i think the issue occurs when mangapark release v5 version, now the v3 version url is mangapark.net/v3x

**Comment by PPCRUSHER** [comment]
Same for me, why did they even release v5 why not just improve v3

**Comment by RosaliaDeGudalupe** [comment]
Some for me, I'm using Android 13.0.7 with last stable version of tachiyomi (0.13.6)

**Comment by Etouq** [comment]
Same issue for me, I'm using android 12 with miui 13 and latest tachiyomi and mangapark version. Hoping this gets fixed soon, I can't read any of my manga
