### ISSUE TITLE
Asura Scans: Updating Issue

### ISSUE THREAD

**Issue by Sordorack** [tachiyomiorg/tachiyomi-extensions#12969]
### Source information and language

Asura Scans 1.3.31 (English)

### Steps to reproduce

1. Update Chapters
2. Everything is updating except Asura Scans

### Expected behavior

Everything should update normally

### Actual behavior

(Almost) all Asura Scans series have some error reported in relation to updating, here are the ones found:
"No Chapters found",
"HTTP error 404", and
"Too many follow-up requests: 21"

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Matakor** [comment]
I am having the same three error sets. Only for Asura Scans.

**Comment by Nozdak** [comment]
I have the same Problem

**Comment by nzoba** [comment]
Most Asura Scans urls have changed. Just migrate all these manga from Asura Scans to Asura Scans to update them

**Comment by kushagra9000** [comment]
"Too many follow-up requests: 21" is what i am also getting after resolving the 404 error on asura

**Comment by mmalyska** [comment]
How can you migrate(refresh urls) all mangas? I have a lot of them and doing it one by one is tiresome.

**Comment by hindraxxx** [comment]
> Most Asura Scans urls have changed. Just migrate all these manga from Asura Scans to Asura Scans to update them

@nzoba can you elaborate on how to do this? on extension list there's only have 1 asura scans, and i have seen no setting to change the url manually

**Comment by kushagra9000** [comment]
Just migrate each manga one by one

**Comment by kushagra9000** [comment]
How is the too many follow up request :21 going to resolve though?

**Comment by hindraxxx** [comment]
ah got it @kushagra9000 re-migrate it to asura scans again solving it..
but yeah it's too much of a hassle to migrate it 1by1 as i have around 40s manhwa from asura lol

**Comment by David05-0** [comment]
Why does AsuraScans don't update the chapters or is there an issue again

**Comment by CrepeTF** [comment]
Asura Scans has changed URLs for many of their manhwa. Migrate from Asura Scans to Asura Scans to continue reading those manhwa.
