### ISSUE TITLE
Manhwas.net(Spanish)

### ISSUE THREAD

**Issue by Himosuke** [tachiyomiorg/tachiyomi-extensions#12970]
### Source information and language

Manhwas.net 1.3.2

### Steps to reproduce

It doesn't load the manhwas, in the webview it has a new design and I don't know if it was the cause, but the extension doesn't work, only in the webview.

### Expected behavior

Load manhwas normally, download and update library normally.

### Actual behavior

It does not load new chapters, error updating the library and it is not possible to download new chapters.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

A message appears on the Recent screen "bixbox must not be full".
also appears
java.lang.String.org.jsoup.nodes.Element.text()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
Same problem with the extension

**Comment by OliverSDL** [comment]
also appears

  java.lang.String.org.jsoup.nodes.Element.text()

**Comment by manuelRT1** [comment]
Encountering solution?

**Comment by Himosuke** [comment]
> Solução de encontro?

No, just wait for a new extension update, it shouldn't go past this week, I hope!

**Comment by manuelRT1** [comment]
I hope so, although manhwasNet 1.3.2 just came out, will they update it again?

**Comment by Himosuke** [comment]
> Espero que sim, embora o manhwasNet 1.3.2 tenha acabado de sair, eles vão atualizá-lo novamente?

I believe so, because there was only a layout update and some improvements to the site, so this week we will have an answer

**Comment by alessandrojean** [comment]
There's no ETA for any issue to be fixed. Contributors work on it when they want/have time to it.
