### ISSUE TITLE
Mango scan br

### ISSUE THREAD

**Issue by Chellyph14** [tachiyomiorg/tachiyomi-extensions#12971]
### Source name

Mango scan br

### Source link

https://yugenmangas.com.br/

### Language

Português

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Chellyph14** [comment]
Isso é um erro,pois esse que esta na seção TODOS é uma extensão em inglês,  e eu estou solicitando uma extensão "mango scan br " em português .

**Comment by alessandrojean** [comment]
Já existe, a versão em português está dentro da extensão que engloba todos os idiomas do site.

**Comment by Chellyph14** [comment]
Yes , I found it , thanks for helping me .
