### ISSUE TITLE
MangaHub: Hitting the API rate limit

### ISSUE THREAD

**Issue by ansanyyi** [tachiyomiorg/tachiyomi-extensions#12982]
### Source information and language

MangaHub 1.3.17

### Steps to reproduce

1. Click Series from MangaHub
2. Click Any chapter
3. Error will show up and it will not load
![Screenshot_2022-08-14-12-04-37-783_eu kanade tachiyomi~2](https://user-images.githubusercontent.com/110255796/184522141-0cbe725d-1754-405a-b508-6d1860526a4c.jpg)

### Expected behavior

the chapter should load

### Actual behavior

it doesn't load

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

Happen after reading a couple of manga/manhwa/mahua chapterd

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by meromex** [comment]
As much as I hate to say it can confirm, issue was not immediate, just update it, worked for a bit and then it started giving the error, like a limiter after reading for a bit. 
![Screenshot_20220814-015643-865](https://user-images.githubusercontent.com/34610160/184526052-4c853749-e7a3-4876-9729-879d3919617a.png)

**Comment by raziel100** [comment]
Yeah, I'm getting the same error, if you wait for a couple of minutes it get working again until the same error appears

**Comment by Beji-kun** [comment]
For me reinstall extension 1manga.cc working 🙂

**Comment by Beji-kun** [comment]
For me reinstall extension **1MANGA.CO** working only temporary 
After few reading I got this messages . Reinstall and clean cookies not working...
![Screenshot_2022-08-15-02-43-36-379_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63636174/184561285-f8d6e3d9-e6d6-41a6-9c92-9388675dad63.jpg)

**Comment by Seishirou101** [comment]
This also affects the following sources that are basically just the same website:

1Manga.co, MangaFox.fun, MangaHere.onl, MangaHub, Mangakakalot.fun, MangaNel, MangaOnline.fun, MangaPanda.onl, MangaReader.site, MangaToday, and MangaTown (unoriginal)

**Comment by Arielfontoura** [comment]
I'm having the same problem...

**Comment by takomine** [comment]
I think it got worse. You just can't read anything anymore

![298636337_589037189327497_672901901257344016_n_proc](https://user-images.githubusercontent.com/108466107/185131466-1bc24734-823c-4268-896a-844b7755b301.jpg)
