### ISSUE TITLE
Imperfect comics Error 404

### ISSUE THREAD

**Issue by ecv03** [tachiyomiorg/tachiyomi-extensions#12989]
### Source information and language

Imperfect Comics 1.3.23

### Steps to reproduce

Imperfect comics says Error 404

### Expected behavior

It should show all the manhwa 

### Actual behavior

Error 404 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/190145385-70914569-15eb-4d16-9bfe-80cfc5355908.png)
its working for me
