### ISSUE TITLE
library update errors

### ISSUE THREAD

**Issue by Tyraelnrxc** [tachiyomiorg/tachiyomi-extensions#12985]
### Source information and language

Asura Scans 1.3.31 (english)

### Steps to reproduce

1. i refresh/ update my library
2. i don't see any update on one of the extension
3. one of the extensions got errors

### Expected behavior

i always update my library 2-3 times a day to see if there's any update on library 

### Actual behavior

this past 2 days everytime i refresh/ update my library i'll always received an error reports such as; error 404 & error 429

![Screenshot_2022-08-14-22-14-51-375_com android htmlviewer](https://user-images.githubusercontent.com/82530011/184543450-504b82f5-4728-483d-842a-22aa1e887b4a.jpg)

### Tachiyomi version

0.13.5

### Android version

android 11

### Other details

![Screenshot_2022-08-14-22-13-44-141_eu kanade tachiyomi](https://user-images.githubusercontent.com/82530011/184543415-2544ecf1-48a2-4bdc-9c11-3ccc49e61a6e.jpg)

I don't see any update available on the extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Asura Scans has changed URLs for many of their manhwa. Migrate from Asura Scans to Asura Scans to continue reading those manhwa.

I suggest you follow the #status-updates channel on the [discord server](https://discord.gg/tachiyomi) or our [Twitter ](https://twitter.com/tachiyomiorg) to get news on stuff like this.
