### ISSUE TITLE
Issues with the Asura Scans extension

### ISSUE THREAD

**Issue by Awesome-Yua** [tachiyomiorg/tachiyomi-extensions#12980]
### Source information and language

Asura Scans 1.3.31 (All) 

### Steps to reproduce

![IMG_20220814_071908](https://user-images.githubusercontent.com/78890130/184519215-c3169920-b7b4-450d-8b0f-d769c6fdfc53.jpg)

### Expected behavior

Smoothly updates the library

### Actual behavior

Does not update the library

### Tachiyomi version

App version: 0.13.5 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Awesome-Yua** [comment]
Hope that you can look into it soon!!

**Comment by hindraxxx** [comment]
+1 having the same issues

**Comment by TheKingTermux** [comment]
Duplicate of #12969
