### ISSUE TITLE
Comic.fun

### ISSUE THREAD

**Issue by Marinx211** [tachiyomiorg/tachiyomi-extensions#12999]
### Source information and language

Comick.fun 1.3.12 (ENGLISH)

### Steps to reproduce

Issue is when i migrate my manga even the setting of comick.fun is only English 
![Screenshot_20220815_164628](https://user-images.githubusercontent.com/106808221/184605009-74d358f6-146a-4feb-8990-79a773c506e1.jpg)
The non-english translation are included 
![Screenshot_20220815_165146](https://user-images.githubusercontent.com/106808221/184605763-fe902c51-0f65-4f78-a973-b40e37587806.jpg)
![Screenshot_20220815_165158]
![IMG_20220815_165650](https://user-images.githubusercontent.com/106808221/184606531-ff342938-0639-4589-a718-9053eda221f4.jpg)it has 923 chapter when you migrate it

I wish it fix. the only problem is migrate but when you search it directly the comick.fun it worked well 
![IMG_20220815_165544](https://user-images.githubusercontent.com/106808221/184606626-00186cfd-f90e-4988-b7be-35dc5008a7b7.jpg)when you search it directly not migrate it only has 149 chapter because its only English translation 

### Expected behavior

This should happen when you migrate it
![Uploading IMG_20220815_165544.jpg…]()

### Actual behavior

This happen instead 
![IMG_20220815_165650](https://user-images.githubusercontent.com/106808221/184607047-60f46479-68a1-4318-8a0d-8d7db56fc3f9.jpg)

### Tachiyomi version

Im using tachij2k ver. 1.5.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you would need to disable it in browse screen
