### ISSUE TITLE
Manhwas.net error: content must not be null

### ISSUE THREAD

**Issue by AlejandroTodoroki26** [tachiyomiorg/tachiyomi-extensions#13008]
### Source information and language

Manwhas.net 1.2.2

### Steps to reproduce

No funciona no deja ver nada en cuanto entras 

### Expected behavior

Debería de abrir y poner las portadas de los manwhas y abrir para r leer 

### Actual behavior

No funciona te da un mensaje que dice 
Bixbox must not be bull
Y no abre nada ni te deja ver nada 

### Tachiyomi version

1.5.6

### Android version

Android 11

### Other details

![Screenshot_20220815-182905](https://user-images.githubusercontent.com/109183168/184747631-5f2bea91-c9e0-436b-8838-20b7242acdb7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "Manhwas.net error: bixbox must not be null"

**Comment by DarkDissaster** [comment]
@vetleledaal la página cambió la apariencia y ahora no deja actualizar ni ver los mangas la versión actual de Manwhas.net es la 1.3.3 espero puedan solucionar este problema

**Comment by vetleledaal** [comment]
error is now "content must not be null", changing the title to reflect this to (hopefully) get less duplicate issues

**Comment by vetleledaal** [comment]
/edit-title "Manhwas.net error: content must not be null"

**Comment by YagamiRyu** [comment]
@vetleledaal But if this error is past, the current one is not found and they have it as closed.

**Comment by YagamiRyu** [comment]
@vetleledaal But if this error is past, the current one is not found and they have it as closed.

**Comment by vetleledaal** [comment]
Doesn't really matter as it's broken either way. Having 5+ issues for the same thing, but with different error messages is counter productive.

**Comment by OliverSDL** [comment]
I agree that having 5 titles for a problem is counterproductive, but I think it would be better to have a current one and have it there than to have one that goes completely unnoticed
