### ISSUE TITLE
Asura Scans extension not working with some specific mangas

### ISSUE THREAD

**Issue by RazredgeBR** [tachiyomiorg/tachiyomi-extensions#13001]
### Source information and language

Asura Scans; Version: 1.3.31; Language: All

### Steps to reproduce

The extension will always give an error when trying to update a couple of mangas, specifically "Legend of Asura – The Venom Dragon" and "Reformation of the Deadbeat Noble". Each has its own error message, and both has been happening for a week.
Opening through the in app browser, Legend of Asura – The Venom Dragon goes straight to the latest chapter, not to the chapter selection. Meanwhile Reformation of the Deadbeat Noble doesn't get anywhere, when trying to use a mobile browser the link will open endless pop ups, but never arrive anywhere. Meanwhile opening it through a desktop browser the page works normally and the chapters are available.

### Expected behavior

Both mangas should just load the current available chapters.
Opening Legend of Asura – The Venom Dragon through the browser should go to the chapter selection.
Reformation of the Deadbeat Noble should load the chapter selection page when using the "browse" button.

### Actual behavior

Legend of Asura – The Venom Dragon errors by saying no new chapters are available, and the "browse website" button goes straight to the latest chapter.

Reformation of the Deadbeat Noble errors by not loading chapters nor the page at all.

### Tachiyomi version

Version 0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RazredgeBR** [comment]
Managed to find a workaround. By removing and adding again both of them, they now sync correctly, but in the process I lost my downloaded and read chapters list. Not a huge deal, just a small hassle.

**Comment by Loxeris** [comment]
This just happened to me with all the asura scans I had in my library.
Library update just failed for all of them.

In order to fix it and not lose my read list and tracking, I used the migrate option and selected asura again, links got fixed and everything is back to normal again.

**Comment by Seishirou101** [comment]
yes they changed urls so you would need to migrate asura to asura to fix any broken links.
