### ISSUE TITLE
captcha page keeps reloading

### ISSUE THREAD

**Issue by junyaotan020517** [tachiyomiorg/tachiyomi-extensions#13011]
### Source information and language

Happymh ver1.3.2 (中文 Chinese )

### Steps to reproduce

i cant read the manga .captcha page keeps reloading

### Expected behavior

i think is the app problem ?

### Actual behavior

pls help me to solve it

### Tachiyomi version

0.13.6

### Android version

emui 12

### Other details

captcha page keeps reloading. if i use on my browser the problem was solved .but i cant complete the captcha using tachi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
Probably Cloudflare is blocking user agent used by Tachiyomi again. You can change user agent in settings as a workaround.
(I am currently using "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv: 103.0) Gecko/20100101 Firefox/103.0" and I am able to bypass.)

**Comment by LenKiMo** [comment]
I'm using TachiyomiJ2K so I'm not too familiar with it, it seems that the extension itself doesn't provide the ability to change the User Agent yet. So the change UA mentioned here is the global UA of the Tachoyomi App?

**Comment by junyaotan020517** [comment]
> Probably Cloudflare is blocking user agent used by Tachiyomi again. You can change user agent in settings as a workaround. (I am currently using "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv: 103.0) Gecko/20100101 Firefox/103.0" and I am able to bypass.)

let me try

**Comment by junyaotan020517** [comment]
> I'm using TachiyomiJ2K so I'm not too familiar with it, it seems that the extension itself doesn't provide the ability to change the User Agent yet. So the change UA mentioned here is the global UA of the Tachoyomi App?

i also not sure about the new user agent setting

**Comment by junyaotan020517** [comment]
> Probably Cloudflare is blocking user agent used by Tachiyomi again. You can change user agent in settings as a workaround. (I am currently using "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv: 103.0) Gecko/20100101 Firefox/103.0" and I am able to bypass.)

may i know which dns are u using, i change to ur setting but still cannnot overbypass.

**Comment by junyaotan020517** [comment]
> Probably Cloudflare is blocking user agent used by Tachiyomi again. You can change user agent in settings as a workaround. (I am currently using "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv: 103.0) Gecko/20100101 Firefox/103.0" and I am able to bypass.)

sorry is my problem after i restart my phone, i can bypass it using ur link, really appreciate with ur help
