### ISSUE TITLE
Readkomik: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Haijuketsu** [tachiyomiorg/tachiyomi-extensions#13015]
### Source information and language

Readkomik 1.3.16

### Steps to reproduce

Cant open manga from extension 

### Expected behavior

Can open any manga from extension 

### Actual behavior

Proceed Cloudflare failed to bypass 
![Screenshot_2022-08-16-14-58-31-957_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/92423380/184819943-c9a58396-bbb9-4e33-af61-d476fcbebcfd.jpg)
![Screenshot_2022-08-16-14-58-27-759_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/92423380/184819949-88b90f84-3a8d-426c-bacb-eecd3677eae0.jpg)

### Tachiyomi version

v. 1.5.6

### Android version

Xiaomi 11T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
NHentai (EN)  is facing the same issue. If I open in the browser it works. But in Tachiyomi or in webview is just remain in this loop

**Comment by Tau5** [comment]
This is also happening to me with MyReadingManga, WebView loops and browser works

**Comment by Kriell** [comment]
I'm also having the same problem.

**Comment by skycat2216** [comment]
having same problem

**Comment by abdelkd** [comment]
I had the issue with nhentai,  Changing the user agent at Settings -> Advanced -> Default user agent string

this should work
'Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36'

**Comment by nakano0505** [comment]
> I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> 
> this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`

it works,thank you very much

**Comment by skycat2216** [comment]
> I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> 
> this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`

You are my lifesaver

**Comment by Kriell** [comment]
> I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> 
> this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`

It worked, thank you man

**Comment by raziel100** [comment]
> I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> 
> this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`

It has worked for me. Thanks

**Comment by Tau5** [comment]
> I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> 
> this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`

It isn't working for MyReadingManga

**Comment by matheousse** [comment]
> I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> 
> this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`

Unfortunately hasn't worked for me, even though regular Android Mozilla works, opening nhentai via webview still loops, and same error on Tachi too

**Comment by Kriell** [comment]
> > I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> > this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`
> 
> It isn't working for MyReadingManga

I tested on MyReadingManga (ver. 1.3.43) and it worked. Try changing the user string again and force stop tachiyomi then open it again to see if it works.

**Comment by Tau5** [comment]
> > > I had the issue with nhentai, Changing the user agent at Settings -> Advanced -> Default user agent string
> > > this should work `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36`
> > 
> > 
> > It isn't working for MyReadingManga
> 
> I tested on MyReadingManga (ver. 1.3.43) and it worked. Try changing the user string again and force stop tachiyomi then open it again to see if it works.

I tried this and it worked, thank you!

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
