### ISSUE TITLE
Asura scans won't update.

### ISSUE THREAD

**Issue by Nazaroshi** [tachiyomiorg/tachiyomi-extensions#13019]
### Source information and language

Asura Scans 1.3.32

### Steps to reproduce

1. First update the whole library.
2. Wait for it to finish.
3. Then you will get an error notification that the source couldn't update.

### Expected behavior

What should happen is, after the update of library the newly updated manhwa/manga should appear.

### Actual behavior

What happened instead is you will get an error notification that the source can't be updated.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

![Screenshot_2022-08-16-21-27-00-575_com android chrome](https://user-images.githubusercontent.com/105725852/184891605-d9fdd09e-25a2-4c0b-a456-6c43b58c7282.jpg)
![Screenshot_2022-08-16-21-26-55-637_com android chrome](https://user-images.githubusercontent.com/105725852/184891624-322875e2-65d7-47ac-86d8-44f036d52a27.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
they changed urls for their entries, migrate from asura to asura.
