### ISSUE TITLE
MangaSwat link changed

### ISSUE THREAD

**Issue by TachiApp** [tachiyomiorg/tachiyomi-extensions#13021]
### Source information and language

manga swat

### Steps to reproduce

new link : 

### Expected behavior

change domain 

### Actual behavior

change domain 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
What's the new domain?

**Comment by TachiApp** [comment]
> What's the new domain?

mangaswat.me

**Comment by 7allom** [comment]
> What's the new domain?

Did you solve the issue?
