### ISSUE TITLE
Myreadingmanga: recaptcha issue

### ISSUE THREAD

**Issue by Hiroyuuki** [tachiyomiorg/tachiyomi-extensions#13026]
### Source information and language

MyReadingManga 1.3.43 (English)

### Steps to reproduce

1. Open/click 'myreadingmanga' extension
2. Open in webview
3. Confirm cloudfare 'I am human' by choosing the correct options the system are asking you to click.

### Expected behavior

After answering the recaptcha correctly, the cloudfare will verify you are human and will redirect you to the site.

### Actual behavior

After answering the quiz part, the page will load a bit and will return to the start asking you to verify again turning into a never ending loop.

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

Yes, I answer the captcha correctly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Farbfrosch** [comment]
I have the same problem. I hope it gets fixed soon :(

**Comment by Jvlier** [comment]
Can confirm this is happening to me too

**Comment by remex24** [comment]
Samething it was working fine about maybe 3 days ago now its not opening its stuck in an infinite loop

**Comment by Hiroyuuki** [comment]
Pretty sure this occurs after the recent update.

**Comment by remex24** [comment]
> 

Any way to solve it?

**Comment by LineLegacy** [comment]
I have the same problem, the Monday the site works fine

**Comment by yasnil03** [comment]
Try to do this, I saw it on the #13015: 

Go to Settings > Advanced > Default user agent string then put this instead

Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36
 
after that closed Tachiyomi and reopen it.

**Comment by Hiroyuuki** [comment]
> Try to do this, I saw it on the #13015:
> 
> Go to Settings > Advanced > Default user agent string then put this instead
> 
> Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36
> 
> after that closed Tachiyomi and reopen it.

I just tried doing this and it instantly worked normally. Thank you!

**Comment by Farbfrosch** [comment]
> Try to do this, I saw it on the #13015:
> 
> Go to Settings > Advanced > Default user agent string then put this instead
> 
> Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Mobile Safari/537.36
> 
> after that closed Tachiyomi and reopen it.

It worked! Thank youu!
