### ISSUE TITLE
Asura scans chapter issues

### ISSUE THREAD

**Issue by Skrungle** [tachiyomiorg/tachiyomi-extensions#13032]
### Source information and language

Asura Scans 1.3.33

### Steps to reproduce

Load app
Find any asura scans comic
Try to refresh for a chapter
No chapter found

### Expected behavior

It should load a chapter because I know one has been updated because I'm in their discord 

### Actual behavior

Says no chapters or a long error code

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Asura Scans changed manga url. you need to migrate from Asura to Asura toget new chapters
