### ISSUE TITLE
Image cannot load

### ISSUE THREAD

**Issue by Wahyudihindra72** [tachiyomiorg/tachiyomi-extensions#13035]
### Source information and language

Koushoku

### Steps to reproduce

1.open browse
2.open manga
3.image cannot load

### Expected behavior

Image load

### Actual behavior

Image cannot load

### Tachiyomi version

0.13.6

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#12954 or #12920 probably
