### ISSUE TITLE
Mangakatana 

### ISSUE THREAD

**Issue by Viva1HA** [tachiyomiorg/tachiyomi-extensions#13039]
### Source information and language

Mangakatana version 1.2.8

### Steps to reproduce

Opened the app,
Some mangas don't show icons/covers/wallpaper/thumbnail
Some chapters have missing pages with a "this image could not be loaded" message 

### Expected behavior

All pages present 

### Actual behavior

Missing pages
Dunno if u can see my screenshots 
![Screenshot_20220817-034542](https://user-images.githubusercontent.com/95601264/185063625-7bb1bd0c-86c4-4899-b50f-cd3b9e4ba711.png)
![Screenshot_20220817-034605](https://user-images.githubusercontent.com/95601264/185063627-9dc484b1-f975-46f7-be21-b8808edda3c0.png)
![Screenshot_20220817-034559](https://user-images.githubusercontent.com/95601264/185063630-7b6db0af-c596-4e55-a334-062202248724.png)

> 

### Tachiyomi version

App version: 0.13.6 

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>Mangakatana version 1.2.8

managakatana version is 1.3.6 please follow what you acknowledge, there is also an open issue about it when you do update #13062
