### ISSUE TITLE
Realm scan wired chapter 

### ISSUE THREAD

**Issue by iMo-ali** [tachiyomiorg/tachiyomi-extensions#13038]
### Source information and language

Realm scan 1.3.20

### Steps to reproduce

1. Update a manga
2. A new chapter titled Capter {{Number}} will appear 

### Expected behavior

The last chapter should appear 

### Actual behavior

A nonexistent chapter appers 
![Screenshot_20220817-103535_Bluecord](https://user-images.githubusercontent.com/61813980/185062878-2cee05c7-8536-474c-84f0-ab6193e15658.jpg)

### Tachiyomi version

J2k v1.5.6

### Android version

Android 12

### Other details

It happens in all the mangas in realm scan 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Make sure you are actually on 1.3.20. If you are just refresh the manga

**Comment by iMo-ali** [comment]
> Make sure you are actually on 1.3.20. If you are just refresh the manga

![Screenshot_20220817-105843_TachiyomiJ2K](https://user-images.githubusercontent.com/61813980/185066060-f11a6a9f-04cb-44e4-a6b3-6dbff3c445cf.jpg)
I am at the latest version its because of 1.3.20 that i got the new issue and i has been reported in discord also not just me

**Comment by AntsyLich** [comment]
Well did you try manually refreshing the manga? Cause the issue has been fixed on 1.3.20

**Comment by iMo-ali** [comment]
Manually refreshing it fixed it thanks 👌
