### ISSUE TITLE
Mangahub / Mangakakalot.fun API rate limit

### ISSUE THREAD

**Issue by vncrack** [tachiyomiorg/tachiyomi-extensions#13040]
### Source information and language

Mangakakalot.fun 1.3.9

### Steps to reproduce

1. Choose mangakakalot.fun source
2. Read manga for a while

### Expected behavior

Mangas still load normally

### Actual behavior

![Screenshot_20220817-163431_Tachiyomi](https://user-images.githubusercontent.com/78357927/185086156-363082fb-c8bf-4ea5-9661-9e9fb0cf3802.png)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
MangaHub is getting the same error too

**Comment by raziel100** [comment]
Can you read the chapter in webview? Here in MangaHub I click to open I  webview, choose the chapter I want, he goes and load the page with the chapters but few seconds latter it force me back to chapter list to select again, I have tried more than 10 different Manga, but when I force it to open in Chrome browser works just fine

**Comment by meromex** [comment]
> Can you read the chapter in webview? Here in MangaHub I click to open in webview, choose the chapter I want, he goes and load the page with the chapters but few seconds latter it force me back to chapter list to select again, I have tried more than 10 different Manga, but when I force it to open in Chrome browser works just fine

Same question since I have the fans issue with web view

**Comment by Sibgeir** [comment]
This behavior extend to the mangahub extention too.
You are able to read it through webview but not through the app itself.
It resets back to normal behavior after a while bute comes back eventually if you read too much

**Comment by raziel100** [comment]
> This behavior extend to the mangahub extention too. You are able to read it through webview but not through the app itself. It resets back to normal behavior after a while bute comes back eventually if you read too much

i don't even need to read "much", after 3 chapters i get this, and i have waited more or less 40min for it to stop getting this message

**Comment by Icefire113** [comment]
If you clear your cookies (Settings > Advanced > Clear cookies) it works as a temporary fix till the error shows up again

**Comment by raziel100** [comment]
> > > This behavior extend to the mangahub extention too. You are able to read it through webview but not through the app itself. It resets back to normal behavior after a while bute comes back eventually if you read too much
> > 
> > 
> > i don't even need to read "much", after 3 chapters i get this, and i have waited more or less 40min for it to stop getting this message
> 
> You can temporarily bypass that by changing dns over https in the settings

Really? I'll try that

**Comment by Kissieh** [comment]
Issue still exists btw

**Comment by Sibgeir** [comment]
Very much still active, yes
