### ISSUE TITLE
My toon not working

### ISSUE THREAD

**Issue by Shingekyu** [tachiyomiorg/tachiyomi-extensions#13041]
### Source information and language

My Toon 1.3.5 (English)

### Steps to reproduce

The chapters don't load

### Expected behavior

The chapters should normally load and should Show the manhwa

### Actual behavior

It's just loading 

### Tachiyomi version

"0.13.6"

### Android version

"Android 12"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ImRyley** [comment]
I'm having the same issue and when trying to download a chapter it says "Unexpected URL scheme 'http' or 'https' but no scheme was found for"
I believe HolyManga had a similar [issue](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12992)

**Comment by vetleledaal** [comment]
Fixed in #13055
