### ISSUE TITLE
API limit exeeded

### ISSUE THREAD

**Issue by eyaaadd0099** [tachiyomiorg/tachiyomi-extensions#13044]
### Source information and language

Mangahub.io

### Steps to reproduce

1.start reading a chapter
2.it will automatically exit full ye chapter saying api limit exeeded 

### Expected behavior

The chapter should show up and can be able to read

### Actual behavior

The chapter automatically closes and can't able to read

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#12982
