### ISSUE TITLE
manga updates

### ISSUE THREAD

**Issue by alphastigma213** [tachiyomiorg/tachiyomi-extensions#13045]
### Source information and language

Asura Scans 1.3.33(all)

### Steps to reproduce

1.no chapters found
2.HTTP ERROR 404
3.too many follow up request

### Expected behavior

all my saved manga on that extension should have status ongoing

### Actual behavior

but now it has become unknown and failing to update

### Tachiyomi version

0.13.6

### Android version

andriod 11

### Other details

![Screenshot_2022-08-17-22-04-52-208_com android chrome](https://user-images.githubusercontent.com/111441300/185154566-637db676-7a49-46c6-9c6a-553ef4d44d03.jpg)
![Screenshot_2022-08-17-22-04-47-326_com android chrome](https://user-images.githubusercontent.com/111441300/185154588-7f798779-29c8-4633-8c7c-0a938dc72a98.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
asura changed the urls, migrate from asura to asura
