### ISSUE TITLE
IMHentai might be bugged

### ISSUE THREAD

**Issue by MG-Rapper** [tachiyomiorg/tachiyomi-extensions#13051]
### Source information and language

IMHentai 1.3.8 English

### Steps to reproduce

Open Extension to browse. 

### Expected behavior

It should show a list of manga/doujinshi and comics.

### Actual behavior

Gives me an error that says "IMHentai search is overloaded try again later".

### Tachiyomi version

13.6

### Android version

Android 10

### Other details

Tried changing the sorting and limiting what categories to show, and it still didn't work. 

As I was about to make a screenshot of the error, the extension started working again, but I think it worth looking into, just in case. 

I wish I could show how to reproduce this bug, but cannot provide the necessary details. In the future, if it happens again, I'll try my best to think what I did to cause the error and provide the proper steps to reproduce the bug. 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce. Seems like an intermittent site issue, which Tachiyomi can't do anything about anyways.
