### ISSUE TITLE
Tapas: "Unexpected JSON token" when custom User-Agent is set

### ISSUE THREAD

**Issue by vetleledaal** [tachiyomiorg/tachiyomi-extensions#13061]
### Source information and language

Tapas 1.3.16

### Steps to reproduce

1. More > Settings > Advanced > Network > Default user agent string
2. Set to `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.97 Mobile Safari/537.36`
3. Restart Tachiyomi
4. Browse > Sources > Tapas
5. Open "My Unexpected Marriage"
6. Refresh

### Expected behavior

Chapters are shown

### Actual behavior

Chapters are not shown, toast is shown instead:
```
! Unexpected JSON token at offset 15: Expected EOF after parsing, but had h instead at path: $
JSON input: 



<!DOCTYPE html>
<html>
<head>
    <title>.....
```

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

An appropriate User-Agent should be set in the extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suhan-paradkar** [comment]
Yep... I can be reproduce this issue.....

**Comment by breaking-loss** [comment]
Do you have a custom ROM installed

**Comment by vetleledaal** [comment]
> Do you have a custom ROM installed

Shouldn't matter as I can reproduce it on multiple ROMs, but yes, I'm using `LineageOS 18.1-20220815-NIGHTLY`

**Comment by suhan-paradkar** [comment]
Well... It happens to me on stock android 9, Oppo ColorOS 6.1

**Comment by Tau5** [comment]
Can reproduce the issue
