### ISSUE TITLE
MangaKatana only loads 1 page per chapter

### ISSUE THREAD

**Issue by tgy456** [tachiyomiorg/tachiyomi-extensions#13062]
### Source information and language

Manga Katana 1.3.6

### Steps to reproduce

Open Tachiyomi:
1-Open Manga Katana Source
2-Click whatsoever manga
3-Click any episode
4-You ses manga chapters Page is 1/1

### Expected behavior

When you open manga, you will see that the pages should be in normal number.

![Screenshot_2022-08-18-10-16-35-226_eu kanade tachiyomi](https://user-images.githubusercontent.com/111487296/185333879-636aee26-7c5a-4f54-a8f1-8bb75f26ec31.jpg)

### Actual behavior

No matter how many chapters I have opened manga, all pages appear 1/1 
![Screenshot_2022-08-18-09-38-15-431_eu kanade tachiyomi](https://user-images.githubusercontent.com/111487296/185332952-dadcb2c5-48bd-4df0-a414-24fc5fe1774b.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

I tried other sources but I do not encounter this issue

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FoxXav** [comment]
Same issue for me.
