### ISSUE TITLE
Mangafreak Failed to Bypass Cloudflare 

### ISSUE THREAD

**Issue by MikaelaMuller** [tachiyomiorg/tachiyomi-extensions#13068]
### Source information and language

Mangafreak 1.3.6

### Steps to reproduce

Install Mangafreal extension
Open menu

### Expected behavior

List of latest manga should appear

### Actual behavior

![Screenshot_20220819-024136_Aniyomi](https://user-images.githubusercontent.com/91151184/185470337-49c9b2ff-3634-484d-bc43-758bd0a5d933.png)

Didn't work
Followed the "Troubleshooting guide" on "Cloudflate Guide"
Unable to follow any steps because the "Solve captcha" screen never appeared in any other steps both in webview and in browser following the "Cloudflare Guide"

### Tachiyomi version

r4514

### Android version

Android 12

### Other details

Tachiport used: Aniyomi Preview ver

App version: 0.12.3.7-4514 (standard, d8f9ea7e1, 72, 2022-07-09T10:33Z)
Android version: 12 (SDK 32)
Android build ID: lineage_a7y17lte-userdebug 12 SP2A.220405.004 eng.filipr.20220501.145005 test-keys
Device brand: samsung
Device manufacturer: samsung
Device name: a7y17lte
Device model: SM-A720F
Device product name: lineage_a7y17lte

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 4ph071c** [comment]
I'm having this exact issue. Tried all the troubleshooting steps listed in the guide, updated to 0.13.6 direct from GitHub, but nothing has worked and I do not even see a captcha from Cloudflare.

**Comment by 4ph071c** [comment]
OK, I had luck getting it to load info and chapter lists by changing the default useragent, as described in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13015#issuecomment-1217706355, however, I am unable to download the actual manga, and it gives the following error "Expected URL scheme 'http' or 'https', but no scheme was found".

**Comment by aboudiom59** [comment]
> OK, I had luck getting it to load info and chapter lists by changing the default useragent, as described in [#13015 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13015#issuecomment-1217706355), however, I am unable to download the actual manga, and it gives the following error "Expected URL scheme 'http' or 'https', but no scheme was found".

Just go back to the default user agent when you download, it worked for me..

**Comment by 4ph071c** [comment]
That didn't do anything for me, I get the Cloudflare error again when I change it back.

**Comment by aboudiom59** [comment]
> That didn't do anything for me, I get the Cloudflare error again when I change it back.

No I mean just for downloading, after that you will have to change it back to the previous user agent to bypass Cloudflare. Yeah I know it's unnecessarily complicated. Copy the user agent that works before resetting it to default, that way after downloading you can just paste it back.

**Comment by FedericoHeichou** [comment]
I set in the app my Google chrome user agent and it worked

```
Mozilla/5.0 (Linux; Android 11; AC2003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36
```

**Comment by 4ph071c** [comment]
> > That didn't do anything for me, I get the Cloudflare error again when I change it back.
> 
> No I mean just for downloading, after that you will have to change it back to the previous user agent to bypass Cloudflare. Yeah I know it's unnecessarily complicated. Copy the user agent that works before resetting it to default, that way after downloading you can just paste it back.

You have to restart the app for changes to take effect.

**Comment by 4ph071c** [comment]
> I set in the app my Google chrome user agent and it worked
> 
> ```
> Mozilla/5.0 (Linux; Android 11; AC2003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36
> ```

I'm not having any luck with this either. It still says it expects http or https when I try to download anything.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).

**Comment by 4ph071c** [comment]
The troubleshooting guide does not solve the issue.
