### ISSUE TITLE
Happymh CloudFlare bypass Failed 

### ISSUE THREAD

**Issue by lrmalaysia** [tachiyomiorg/tachiyomi-extensions#13067]
### Source information and language

happymh 1.3.2

### Steps to reproduce

Not able to bypass the CloudFlare from the extension when read the comic. Using browser is able to bypass but not inside the App. 

Visit the website through the APP is fine but not read the comic chapter.

### Expected behavior

able to read the comic chapter 

### Actual behavior

always loop on CloudFlare if open through in app web view.

### Tachiyomi version

1.3.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please read #13011

**Comment by lrmalaysia** [comment]
> Please read #13011

how to change the user agents? I found only DNS over HTTPS but can't resolve.

**Comment by TheKingTermux** [comment]
> > Please read #13011
> 
> how to change the user agents? I found only DNS over HTTPS but can't resolve.

You need to upgrade your Tachiyomi version to [0.13.6 (Latest)](https://github.com/tachiyomiorg/tachiyomi/releases/download/v0.13.6/tachiyomi-v0.13.6.apk)

**Comment by lrmalaysia** [comment]
> > > Please read #13011
> > 
> > 
> > how to change the user agents? I found only DNS over HTTPS but can't resolve.
> 
> You need to upgrade your Tachiyomi version to [0.13.6 (Latest)](https://github.com/tachiyomiorg/tachiyomi/releases/download/v0.13.6/tachiyomi-v0.13.6.apk)

Got it. Fdroid dont have latest version yet. need download manually

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
