### ISSUE TITLE
[ Asura Scans ] Remove Rate Limiter On Manual Browse and Chapter Check

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi-extensions#13074]
### Describe why this should be added

Whenever I'm checking `Latest` page of `Asura Scans` source. The loading speed of the following scenario are:
- When browsing the series list, the series cover images load too slow
- When browsing the chapter list of the series, the chapter list load too slow.

I remember there was a mention that some sources have rate limit (e.g. Asura Scans).

Please deploy the rate limit only when doing `Library` Global or Manual Update

This is so that when user manually check a specific source latest release in the Source page. It would be easier to browse series a user wants to read, and they can check easily how many chapters are available, especially during when Asura Scans release a new series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension doesn't know the context (if it's a global update or a manual update/view), so this is not technically possible.
