### ISSUE TITLE
after empty default user agent string happymh cant access 

### ISSUE THREAD

**Issue by junyaotan020517** [tachiyomiorg/tachiyomi-extensions#13073]
### Source information and language

happymh (嗨皮漫画）

### Steps to reproduce

1. after i clear my default user string to empty
2. all of the extension can be use except happymh
3. webview of happymh work normal and the captcha can be bypass
4. but when i read using tachi it show failed to bypass

### Expected behavior

after bypass using webview it should show normal

### Actual behavior

always show failed to bypass when using the extension

### Tachiyomi version

0.13.6

### Android version

emui 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It should be obvious that it should be a valid user agent string and an empty one doesn't count as valid...
