### ISSUE TITLE
Photos of the chapters of mangaswat doesn't load ( there's no image)

### ISSUE THREAD

**Issue by BenaliAziz** [tachiyomiorg/tachiyomi-extensions#13070]
### Source information and language

Mangaswat (1.3.24) ( العربية)

### Steps to reproduce

![Screenshot_20220818-204822_Tachiyomi](https://user-images.githubusercontent.com/111535060/185482014-f0e8da96-fdaf-4652-84ad-2fd6e7866408.jpg)

### Expected behavior

I don't know what to write here

### Actual behavior

I don't know what to write here

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment]
There was the same issue but thay closed it for no reason

**Comment by arkon** [comment]
#13021

**Comment by 7allom** [comment]
> #13021

Bro is closing every issue mentioned  mangaswat

**Comment by OMARYeHia19** [comment]
What can I do wait until they fixed or what?
