### ISSUE TITLE
Manga swat give a 403 (forbidden) status code 

### ISSUE THREAD

**Issue by OMARYeHia19** [tachiyomiorg/tachiyomi-extensions#13079]
### Source information and language

MangaSwat 1.3.24 (arabic) 

### Steps to reproduce

1. Open/download a chapter 

### Expected behavior

Chapter pages load normally 

### Actual behavior

Chapter pages gives an error (403 status code)
![Screenshot_20220819-094710](https://user-images.githubusercontent.com/106982306/185576518-b40c9bd7-e2a4-4da3-97a0-d62290930c33.png)
![Screenshot_20220819-094725](https://user-images.githubusercontent.com/106982306/185576593-bc583c84-27bc-4d7e-99cd-49fe7f962d64.png)
 
### Tachiyomi version

0.13.6

### Android version

Android 7

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by lokeshvs1106** [comment]
The manga shows new chapter. But when we open it. It shows only the title page(cover page) nothing else. It is happening for all the manga present in the mangakalot extension

**Comment by Seishirou101** [comment]
Probably related to #13021
