### ISSUE TITLE
Webtoon18 redirects to a fake site 

### ISSUE THREAD

**Issue by Gadetron** [tachiyomiorg/tachiyomi-extensions#13071]
### Source information and language

Webtoon18

### Steps to reproduce

Open webtoon18 via the extension menu

### Expected behavior

Should open the website 

### Actual behavior

Redirects to a random unrelated site

### Tachiyomi version

1.8.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
the website redirects, all the extension is doing is doing the same.
