### ISSUE TITLE
ManhwaIndo.id eror cover

### ISSUE THREAD

**Issue by Shiiki012** [tachiyomiorg/tachiyomi-extensions#13080]
### Source information and language

ManhwaIndo 1.3.19 (Id)

### Steps to reproduce

when opening the manhwaindo extension comic cover error

### Expected behavior

Showing a comic cover image

### Actual behavior

Error comic cover image - Manhwaindo.id
![image](https://user-images.githubusercontent.com/56505683/185585273-e3d7ffef-d317-4689-8dca-c9744ba3712d.png)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
I just checked the extension on my phone and the covers were loading. Are you still having this problem?

**Comment by TheKingTermux** [comment]
Actually it load well for me to

![Screenshot_2022-08-25-14-04-06-39_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/186597754-192196de-0515-4c74-b91d-6d8b70259c9b.jpg)
