### ISSUE TITLE
Too many requets: 21

### ISSUE THREAD

**Issue by coolbeastman1** [tachiyomiorg/tachiyomi-extensions#13086]
### Source information and language

Asura Scans all 1.13.31

### Steps to reproduce

1. Go to webtoon
2. Try to update it
3. Get the error message "Too many Requests: 21"

### Expected behavior

It should update the chapters

### Actual behavior

It doesn't update and I get the message "too many requests: 21"

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
your extension is out of date, but for this error you most likely just need to migrate asura to asura
