### ISSUE TITLE
Failed bypass cloudfare

### ISSUE THREAD

**Issue by Madoja** [tachiyomiorg/tachiyomi-extensions#13082]
### Source information and language

Nhentai 1.3.35

### Steps to reproduce

Can't open nhentai extension even after clearing cache and cookies.
Still cant open after viewing using webpage.

### Expected behavior

Show the updates

### Actual behavior

Failed bypass cloudfare

### Tachiyomi version

13.6

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
This is a duplicate from #12784
