### ISSUE TITLE
Komik Cast: Pagination broken

### ISSUE THREAD

**Issue by Subadrunz** [tachiyomiorg/tachiyomi-extensions#13106]
### Source information and language

Komik Cast 1.3.29 (Indonesia)

### Steps to reproduce

1. Click update in komikcast extension.
2. Scroll down.
3. And its get looping 

### Expected behavior

normal as usual 

### Actual behavior

Extension is looping, and idk What to do. 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

![IMG_20220820_192426](https://user-images.githubusercontent.com/107401290/185746173-088d9937-2176-4c2e-88b2-73cec0d3b15a.jpg)
![IMG_20220820_192530](https://user-images.githubusercontent.com/107401290/185746175-09d200a8-6d6e-48fb-9009-026dcc0c046d.jpg)
![IMG_20220820_192703](https://user-images.githubusercontent.com/107401290/185746177-660fa9c4-32cf-4a45-83c4-e55b134e05b4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
Notes for whoever works on this:
Komik Cast uses the /page/# system rather than the ?page=# system on the search / filter pages.

**Comment by arispati** [comment]
PR for this has been merged, @Subadrunz please try the latest version. if solved, please close this issue.

**Comment by Subadrunz** [comment]
Thank you :)
