### ISSUE TITLE
Asura Scans latest update filter doesn't work

### ISSUE THREAD

**Issue by RaidBuster** [tachiyomiorg/tachiyomi-extensions#13111]
### Source information and language

Asura Scans 1.3.33

### Steps to reproduce

When using filter to sort by latest updates doesn't work 

### Expected behavior

Normal

### Actual behavior

The filter result is sort by A-Z

![Screenshot_2022-08-20-21-19-28-097_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/185750928-1ef18256-e138-44ef-921e-1d94e225bb5c.jpg)
![Screenshot_2022-08-20-21-19-32-301_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/185750932-692745de-da7d-4662-8843-8ab19402bb2d.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

I encounter this problem too in other extension on Flame scans v 1.3.18 and Gabut scans v 1.3.18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by U5ermisaki777** [comment]
Pls fix asura scan
