### ISSUE TITLE
AllPornComic: pagination doesn't work when using a filter

### ISSUE THREAD

**Issue by oge2k** [tachiyomiorg/tachiyomi-extensions#13114]
### Source information and language

Allporncomics 1.3.24

### Steps to reproduce

1. Go to extensions
2. Open the allporncomics extension
3. Click on filters
4. Use a genre

### Expected behavior

When a genre is used it should show all the entries available that match it

### Actual behavior

When the genre is used it will only return 20 entries, even if there are more matches to this genre

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

If you use a genre in webview it brings up more than 20 entries

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
I think this is happening for a couple of mouths for now, at least we can read and download chapters without problems

**Comment by vetleledaal** [comment]
/edit-title "AllPornComic: pagination doesn't work when using a filter"

**Comment by Palloxin** [comment]
This still happens in the extension version 1.3.27.
Using filtered searches on this extension will only give 20 entries. It doesn't load other results. onky the first 20.

**Comment by Palloxin** [comment]
In the 1.4.29 the bug is fixed. It doesn't limit to 20 entries anymore. Despite tag choice being unaffected the bug is technically fixed.
