### ISSUE TITLE
Failed to bypass Cloudflare for Mangahasu

### ISSUE THREAD

**Issue by Heisenberg012** [tachiyomiorg/tachiyomi-extensions#13122]
### Source information and language

Mangahasu

### Steps to reproduce

Please help me

### Expected behavior

Work normally
List of latest manga should appear
### Actual behavior

Failed to bypass Cloudflare for Manghasu
Always keeping loading when webview

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

![Screenshot_20220821-142205_Tachiyomi](https://user-images.githubusercontent.com/111677055/185779582-f153ed5e-22c7-4d96-95b4-7535b48c14bf.jpg)
![Screenshot_20220821-142218_Tachiyomi](https://user-images.githubusercontent.com/111677055/185779587-9304e8d1-bc3f-413a-9e02-09350d6d0e30.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
