### ISSUE TITLE
Chapter not loading Asura Scan

### ISSUE THREAD

**Issue by w00ogly** [tachiyomiorg/tachiyomi-extensions#13121]
### Source information and language

Asura Scan 1.3.33

### Steps to reproduce

When clicking a manhwa on Asura scans it immediately kicks you saying no pages found

### Expected behavior

When clicking a chapter it should load or at the very least have a black screen for slow loading.

### Actual behavior

Instead it doesn't and puts you back to the manhwa page and displays a quick message saying no pages found.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by asdkant** [comment]
I'm on TachiJ2K and the same thing happened to me

**Comment by poorloading** [comment]
i have this and the cover pages are not loading either
