### ISSUE TITLE
Extention not working but used to work

### ISSUE THREAD

**Issue by Lurker427** [tachiyomiorg/tachiyomi-extensions#13127]
### Source name and language

nhentai 

### Describe your suggested feature

It used to work but now has stopped, of this could be resolved then it would be great. It was thr only good and working extention. 

### Other details

Not much, just the source needs to be put back or errors needed to be sorted out please. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Search the existing issues.
