### ISSUE TITLE
Name Komga instances

### ISSUE THREAD

**Issue by cyberweasel** [tachiyomiorg/tachiyomi-extensions#13125]
### Source name and language

Komga (ALL)

### Describe your suggested feature

I would like to be able to name the Komga instances with what they do instead of "Komga (ALL)", Komga (2) (ALL)", & Komga (3) (ALL)". I use the instances to login as different users.  I didn't see this request anywhere else. Not sure if this is possible.  Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This isn't currently possible, nor are there plans to allow for renameable sources as it's pretty niche.
