### ISSUE TITLE
Cloudflare looping on NHentai

### ISSUE THREAD

**Issue by le-cretin** [tachiyomiorg/tachiyomi-extensions#13128]
### Source information and language

NHentai v1.3.35

### Steps to reproduce

1. Try to open the NHentai extension on Tachiyomi
2. Extension does not open
3. Attempt to open in using in-app webpage
4. Cloudflare loop
5. Open in browser
6. Access NHentai
7. Return to app
8. Unable to access NHentai

### Expected behavior

1. Click on extension to open it
2. Get access to NHentai extension

### Actual behavior

![Screenshot_20220822-012700_Tachiyomi](https://user-images.githubusercontent.com/111713700/185818217-411f1771-bf21-4dcc-95b5-61579db3ce60.jpg)
![Screenshot_20220822-012515_Tachiyomi](https://user-images.githubusercontent.com/111713700/185818229-4761ed31-ffd2-4af2-9f10-405ba57f7742.jpg)
![Screenshot_20220822-013036_Samsung_Internet](https://user-images.githubusercontent.com/111713700/185818240-c1aebc1f-d1d4-4b02-a67f-c91e7f466d83.jpg)
![Screenshot_20220822-013120_Samsung_Internet](https://user-images.githubusercontent.com/111713700/185818244-45dc4d06-ece9-47e0-b409-cc0f7a369952.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Even after opening NHentai in browser, samsung browser in this case, still get a cloudflare error. Don't have this with any of my other extensions. Started having this problem prior to updating to 0.13.6 then after update, issue still persisted. 
Tried uninstalling/reinstalling the extension but to no avail. 
Also tried the workaround in #12784 but that did not work either.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by adsewse2015** [comment]
Try this user agent string instead

Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Mobile Safari/537.36
