### ISSUE TITLE
Ehviewer

### ISSUE THREAD

**Issue by leo110636** [tachiyomiorg/tachiyomi-extensions#13135]
### Source name

Ehviewer

### Source link

https://github.com/xiaojieonly/Ehviewer_CN_SXJ

### Language

Chinese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
thats a ehentai viewer and ehentai already exists.

**Comment by leo110636** [comment]
> 
ok，thank you
