### ISSUE TITLE
Api key invaild or expired

### ISSUE THREAD

**Issue by KylerParker504** [tachiyomiorg/tachiyomi-extensions#13144]
### Source information and language

MangaHub

### Steps to reproduce

1. Open mangahub
2. Open manga
3. Try read few chapter
4. Unable read other manga 
5. Its says [ API key Invaild or Expired ]

### Expected behavior

Its should open normally

### Actual behavior

But it seem there limit how many chapter i can read

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KylerParker504** [comment]
![Uploading Screenshot_20220823-004438_Tachiyomi.jpg…]()

**Comment by Chronosishere** [comment]
Same Issue on Android 9.

If User reinstall the extention then the User can again read few more chapters or User will have to wait 15-20 minutes for the API key to refresh.

Previously the issue was stated as API RATE LIMIT.

**Comment by Kiezelstein** [comment]
I can't even read beyond 2 chapters anymore. I slept and it still says API rate limit thing and sometimes expired.

**Comment by knotekt** [comment]
After 1.3.20 update the 'Clear cookies' workaround no longer works. Mangahub is pretty much unusable.

**Comment by Lyonie** [comment]
Mine still work after clear chapter cache & cookies.

**Comment by knotekt** [comment]
> People also suggested remove mangahub [#13158 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13158#issue-1348465768)

If the website owners break it on purpose every time, I also see no reason to keep fixing it every other day. Its just a shame as its reasonably fast, has quick updates and finding a similarly good source is kinda a pain.

**Comment by raziel100** [comment]
> > People also suggested remove mangahub [#13158 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13158#issue-1348465768)
> 
> If the website owners break it on purpose every time, I also see no reason to keep fixing it every other day. Its just a shame as its reasonably fast, has quick updates and finding a similarly good source is kinda a pain.

Does even exist? I have tried searching a similar site but I couldn't

**Comment by BladeWise** [comment]
Apart from the issue of finding another good source as replacement, the fact that there is no mass migration in Tachiyomi (unless some forks are used like j2k) makes dropping an extension painful for users.

**Comment by alessandrojean** [comment]
Closing in favour of #13158

Migrate to better sources.
