### ISSUE TITLE
Happy manga not working

### ISSUE THREAD

**Issue by tatular** [tachiyomiorg/tachiyomi-extensions#13146]
### Source information and language

happymh 1.3.2

### Steps to reproduce

1. Open happy manga
2. open any manga
3. failed to load any manga
4. it says failed to bypass cloudflare
5. open WebView to complete catcha
6. but the captcha won't stop. it keep on prompting asking to click for captcha

### Expected behavior

should be able to read manga after completing the captcha

### Actual behavior

couldn't load manga. it says failed to bypass cloudflare. when in WebView, the captcha keep on prompting asking to click the captcha.

### Tachiyomi version

0.13.6

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kuronekonokuro** [comment]
Change User Agent in tachiyomi settings

**Comment by Fukuda99** [comment]
Finally it's work for me after days. T.T
Thanks!

linked for default agent: https://www.whatismybrowser.com/guides/the-latest-user-agent/
