### ISSUE TITLE
Mangatown extension "No pages found" for some manga

### ISSUE THREAD

**Issue by wedsa5** [tachiyomiorg/tachiyomi-extensions#13150]
### Source information and language

Mangatown English 1.2.6

### Steps to reproduce

1. Select Mangatown extension and then search (or do global search)
2. Search for "sayonara eri"
3. Select the manga
4. See that it lists 1 chapter
5. Select chapter or click start
6. See "No pages found" toast 
7. Click WebView to open the manga in the browser
8. See that there are pages for this manga

### Expected behavior

The pages should be properly fetched for this manga and displayed

### Actual behavior

Getting a "No pages found" error toast message

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Other manga load normally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by dec05eba** [comment]
It's weird. The mobile page (m.mangatown.com) for that manga has 1 chapter but the non mobile page (mangatown.com) has no chapters.

**Comment by wedsa5** [comment]
oh that's really strange
