### ISSUE TITLE
Prima Scans: Failed to bypass CloudFlare

### ISSUE THREAD

**Issue by Frozik29** [tachiyomiorg/tachiyomi-extensions#13152]
### Source information and language

Prima Scans 1.3.26

### Steps to reproduce

You should use the extension normally

### Expected behavior

would work normally

### Actual behavior

When using the extension appears "Failed to ignore cloudflare"

### Tachiyomi version

TachiyomiJ2K 1.5.7

### Android version

Android 11

### Other details

This error does not appear on the site, only on Tachiyomi, and I've tried everything in the problems tab to solve it but it didn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's nothing we can do about it, wait until they lower their protection or migrate to better sources.
