### ISSUE TITLE
Remove MangaHub

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi-extensions#13158]
### Describe why this should be added

Clearly becoming a cat and mouse game and any further maintenance of the source is just not worth the effort and delaying the inevitable.

### Other details

MangaHub users just migrate elsewhere ffs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
I don't get your point.  Yeah MangaHub is always breaking, but you can search the updates, update new chapters, only reading is getting problems, it's not the best, but you can put to download and wait until everything is downloaded, or using to at leas know what chapter you have read and read the chapters you haven't read in browser, no?

**Comment by alessandrojean** [comment]
There's no point in wasting time to keep fixing an extension that within hours the website owners do something to break it. It's in the cat and mouse game state, so it's better to just migrate to better sources.
