### ISSUE TITLE
Mangás Chan: lateinit property title has not been initialized

### ISSUE THREAD

**Issue by Frozik29** [tachiyomiorg/tachiyomi-extensions#13167]
### Source information and language

Mangás Chan 1.3.18

### Steps to reproduce

Enter the extension or enter the "recent" option and click on any manga

### Expected behavior

Expected to have manga description and recent chapters update

### Actual behavior

The manga has no information or tags on what type he is, such as "Shounen". And the chapters don't update at the same time as the website, sometimes it takes hours for a chapter that came out on the website well before, update on Tachiyomi

### Tachiyomi version

TachiyomiJ2K 1.5.8

### Android version

Android 11

### Other details

On the website the information and tags are described there, and the updated manga appears much earlier on the website, and on Tachiyomi the manga doesn't update together, it takes time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> and the updated manga appears much earlier on the website, and on Tachiyomi the manga doesn't update together, it takes time

We don't have any control over that, the extension checks for new chapters on the manga details page on the website, if they take more time to appear there, there's nothing we can do.

The lateinit title issue can however be solved.

**Comment by Frozik29** [comment]
ok, the real problem is the description of the manga and the genres that don't appear, thanks

**Comment by Frozik29** [comment]
if I try to change the author and description at the same time, only one of the two appears, and if I put the author first, the description disappears, the opposite also happens

**Comment by Frozik29** [comment]
only that
