### ISSUE TITLE
junmeitu not working

### ISSUE THREAD

**Issue by tatular** [tachiyomiorg/tachiyomi-extensions#13178]
### Source information and language

junmeitu 1.3.3

### Steps to reproduce

1. open junmeitu
2. open any album
3. some album can be loaded but when open it says the image couldn't be loaded.
4. some album couldn't be loaded and a message saying "Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference"

### Expected behavior

any album should be able to open and load.

### Actual behavior

some album can be loaded but when open, the image couldn't be loaded 
some album couldn't be loaded and says "Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference"

### Tachiyomi version

0.13.6

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can not reproduce the second problem. The first problem is related to the site - the image shouldn't be able to load either if you check the web page.

By the way, the second mirror is down and I'll PR to remove it.
