### ISSUE TITLE
Request of removal of swatmanga

### ISSUE THREAD

**Issue by Odarku** [tachiyomiorg/tachiyomi-extensions#13171]
### Source link

https://swatmanga.me/

### Other details

Hello.  I would like to ask for the removal of my website swatmanga.me

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by CarlosEsco** [comment]
Swatmanga.co also needs removed

**Comment by Odarku** [comment]
Can u please delete also our previous domaine which is swatmanga.co because it's still there and once u enter it , you will be redirected to the new domaine  swatmanga.me
. Thank you
