### ISSUE TITLE
Portal Yaoi 

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#13179]
### Source name and language

Portal Yaoi (portuguese)

### Describe your suggested feature

https://portalyaoi.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open an source request issue next time.

**Comment by KaraSupergirl** [comment]
Wow, how did I miss the option? It was the source request wasn't it? I was pretty sure I had put it on.

**Comment by alessandrojean** [comment]
You filled out the feature request issue, that's different from the source request one. Feature request is used to request new features to already existing extensions.
