### ISSUE TITLE
MR Yaoi Fansub 

### ISSUE THREAD

**Issue by KaraSupergirl** [tachiyomiorg/tachiyomi-extensions#13180]
### Source name and language

MR Yaoi Fansub (portuguese)

### Describe your suggested feature

https://mrtenzus.com
password: bluvmecome
It can change at any time so if you decide to do it and the password has already been changed, just let me know and I'll send you the new one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Also again, please use the source request issue form.
