### ISSUE TITLE
MangaXYZ: Add rate limiting to requests

### ISSUE THREAD

**Issue by ThatsKrazy** [tachiyomiorg/tachiyomi-extensions#13182]
### Source information and language

MangaXYZ 1.3.8

### Steps to reproduce

i update my library and it says 129 update error 
and shows error 429

### Expected behavior

i expected a good outcome

### Actual behavior

it says Error 429

### Tachiyomi version

1.8.5

### Android version

Android 8

### Other details

[Screenshot_20220825-135815_Chrome](https://user-images.githubusercontent.com/112059542/186586393-3ade9faa-f254-4e66-9932-b8b5570b1540.jpg)`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
429 means you were rate limited by the site.

@vetleledaal when are next doing some extension work can you add a higher rate limit to the source

**Comment by vetleledaal** [comment]
Per the other issues, this applies to all MadTheme sources

**Comment by LycNeptune** [comment]
Please add more rate limit of mangamax too.. that can refresh 1000 manga in 2 hour
