### ISSUE TITLE
Asking to bring it back

### ISSUE THREAD

**Issue by prox05** [tachiyomiorg/tachiyomi-extensions#13184]
### Source name and language

Mangahub (english) 

### Describe your suggested feature

Could you please bring back mangahub.  I now its irritating when its say API is full, read on mangahub.io, but i have to many manga (453) on it.  So if you could bring it back for a few months, so that i can find another extension for my manga, thank you. 

### Other details

If you could add something where you can request something that isn't being shown, just like this request isn't a real application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by prox05** [comment]
Ok, thank you. But if you could bring it for a few months.  2 months most, as i have said that I have too many manga on it.

**Comment by vetleledaal** [comment]
MangaHub was actively blocking every fix from Tachiyomi's side within hours. So "just" making it available for 2 months is a big ask. You can see the back and forth [in the logs](https://github.com/tachiyomiorg/tachiyomi-extensions/commits/ccd9dd989c267b8bbf0df5b3dc53340ace78e50a/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangahub/MangaHubGenerator.kt)

**Comment by meromex** [comment]
Shame they won, mangahub beat tachiyomi.
