### ISSUE TITLE
Mangareader shows wrong chapter release dates

### ISSUE THREAD

**Issue by tegutistgut** [tachiyomiorg/tachiyomi-extensions#13187]
### Source information and language

Mangareader 1.3.2

### Steps to reproduce

1. Open Tachiyomi
2. Search any manga and go there where to see the chapter list
3. Every chapter was released "today"

### Expected behavior

It should show the actual release date of the manga.

Either the official release date (from e.g. Shonen Jump, etc.) or the release date on the website from Mangareader

### Actual behavior

It shows that the chapter has released "today" unless you have added the manga to your library. Then it shows the release date of the day when you added the manga to your libary.

### Tachiyomi version

0.13.6

### Android version

Android 12 and 11, any version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
where exactly do you see this date on the website? when a site provides no date, it falls back to when you fetch the chapter. so working as intended.
