### ISSUE TITLE
Asura Scans: Doesn't work with a mobile User-Agent

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi-extensions#13181]
### Source information and language

Asura Scans 1.3.34

### Steps to reproduce

1. Set the default user agent string to a mobile useragent
2. open any manga from asura scans and attempt to read it

### Expected behavior

able to read, pages load fine

### Actual behavior

toast notification syaing: no page found

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

This only happens when a mobile user agent is set as default. It works perfectly fine with a desktop user agent.

So the extension should have a desktop user agent as an override to fix this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DieSmilePN** [comment]
Same happening to me. MyReadingManga works on mobile user agent but Asura doesn't. Asura work on desktop user agent. When I try adding both user agent. It just keep crashing.

**Comment by RazredgeBR** [comment]
Any plans on fixing this?
