### ISSUE TITLE
LKDTT changed domain 

### ISSUE THREAD

**Issue by QuangTKD** [tachiyomiorg/tachiyomi-extensions#13183]
### Source name

LKDTT 1.3.1

### Source link

https://lkdtt.net/

### Language

Vietnamese

### Other details

LKDTT changed domain from "lkdtt.com" to "lkdtt.net"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
I just tried the extension and it seems to be working still. The .com domain redirects to the .net domain and doesn't expire until early 2024. Does this need to be fixed?

**Comment by QuangTKD** [comment]
> I just tried the extension and it seems to be working still. The .com domain redirects to the .net domain and doesn't expire until early 2024. Does this need to be fixed?

Hi, thank you for letting me know. However, on my Tachiyomi SY and J2K, the extension does not redirect to the .net domain (most likely because my country's internet has blocked domain .com) so my library can't be updated. I used VPN on my phone and it aslo not redirect. Maybe it only works on PC. 

Kindly help to fix it.

Many thanks
