### ISSUE TITLE
Doge Manga

### ISSUE THREAD

**Issue by Siegfredal** [tachiyomiorg/tachiyomi-extensions#13192]
### Source name

Doge Manga

### Source link

https://dogemanga.com

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Siegfredal** [comment]
Please add this site. This is as good as mangahub

**Comment by Siegfredal** [comment]
None are as complete as this site

**Comment by stevenyomi** [comment]
Language should be Chinese.

**Comment by stevenyomi** [comment]
English version of this site just scrapes MangaDex and MangaReader.to (including scrambled images) - not worth doing.

**Comment by Siegfredal** [comment]
> English version of this site just scrapes MangaDex and MangaReader.to (including scrambled images) - not worth doing.

Nope. There are licensed manga too
