### ISSUE TITLE
MyReadingManga

### ISSUE THREAD

**Issue by Fujin-sama** [tachiyomiorg/tachiyomi-extensions#13199]
### Source information and language

MyReadingManga 1.3.44

### Steps to reproduce

1. Open the source
2. Answer the Cloudflare
3. Access the site

### Expected behavior

When opening the source you need to answer the cloudflare to access the site then you will have access after answering.

### Actual behavior

But the actual behavior will be, after answering the cloudflare it will let you answer another instead of giving access to the site

### Tachiyomi version

0.13.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Billarin** [comment]
Hello, I am also experiencing the same problem but fixed it by changing tachiyomi user agent.
You can refer to here for the fix:
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13026#issuecomment-1221498879
However, I noticed you are using android 9 and the fix above is for android 10, if you really have checked about your phone's android system and it is indeed 9, try looking for an android 9 user agent here:
https://www.whatismybrowser.com/guides/the-latest-user-agent/

**Comment by DieSmilePN** [comment]
Your User agent is on Desktop version try Using this 

Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.97 Mobile Safari/537.36 

U can change the android version to 9 or 13 and the chrome version same on your chrome you using now or latest, it doesn't really matter as long are in Mobile User-agent. But if you use that Asura Scans won't work. Asura scan only work Desktop User-agent for now.

Mozilla/5.0 (Macintosh; Intel Mac OS X 12_5_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

The default is Desktop version. Just Reset default user agent when you're done using MyReadingManga. The developers set it to desktop version anyway its work fine almost anywhere except MyReadingManga

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
