### ISSUE TITLE
Manhua Plus: No results found

### ISSUE THREAD

**Issue by Fujitive** [tachiyomiorg/tachiyomi-extensions#13190]
### Source information and language

Manhua Plus 1.3.30 (English) 

### Steps to reproduce

1. open manhua plus extension
2. cannot view nor browse manhua/manga
3. showing no results found

### Expected behavior

view and browse manhua/manga should happen

### Actual behavior

no results found

### Tachiyomi version

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z) Android version: 10 (SDK 29) Android build ID: MED-L29 10.1.0.309(C636E4R3P1) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWMED-MR Device model: MED-LX9 Device product name: MED-L29

### Android version

Android 10

### Other details

![Screenshot_20220826_012610](https://user-images.githubusercontent.com/112114312/186733059-67bb7ea5-39d8-4993-9958-c930a6f23b65.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RazredgeBR** [comment]
Their servers were down for a few minutes, but they're back now

**Comment by happywillow0** [comment]
Hi @Fujitive, this extension looks like it is working on my end. Are you still having this issue?

**Comment by Fujitive** [comment]
> Hi @Fujitive, this extension looks like it is working on my end. Are you still having this issue?

it's okay now, 5 days ago wasn't
