### ISSUE TITLE
Nude-Moon: HTML parsing is failing

### ISSUE THREAD

**Issue by Jokerdrim** [tachiyomiorg/tachiyomi-extensions#13191]
### Source information and language

Nude-Moon 1.3.8 (Russian)

### Steps to reproduce

1. Open Nude-Moon extension
2. I see manga list with same cover
3. Occurs error

### Expected behavior

Open and read manga

### Actual behavior

When opening a manga in the application, an error occurs! Attempt to invoke virtual method 'org.jsoup.nodes.Element org.jsoup.nodes.Element.parent()' on a null object reference. Same error when updating manga. Through the webview, everything opens.

### Tachiyomi version

Preview r4821

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
Sorry but I can't read russian. Is the website working? When I try to open up a chapter, it says something something please visit nude-moon.com.

**Comment by Jokerdrim** [comment]
> Sorry but I can't read russian. Is the website working? When I try to open up a chapter, it says something something please visit nude-moon.com.

I forgot to tell. To read manga in website you need an account. Without it you will see blank page
