### ISSUE TITLE
Too many requests ban

### ISSUE THREAD

**Issue by JoseQuervoBoi** [tachiyomiorg/tachiyomi-extensions#13205]
### Source information and language

cant update some chapters 

### Steps to reproduce

1. Open App.
2. Check Updates.
3. 42 failed updates. 
4. Check issue. 
5. Need to Report.

### Expected behavior

1. Open App.
2. Check Updates. 
3. Most if not all Update.
4. Enjoy App.

### Actual behavior

1. Open App.
2. No Updates.
3. Says Most failed if not all. Some do update, not many though.
4. Need to report. 

### Tachiyomi version

0.13.6

### Android version

Galaxy A21

### Other details

Hopefully its fixed soon, thank you for your time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
But which source…

**Comment by alessandrojean** [comment]
Closing as there's not enough information. Please also check the update errors and explicity say what they are.

You might find a better support for this at our [Discord server](https://discord.gg/tachiyomi).
