### ISSUE TITLE
Manhwas.men: Changed their theme to Madara

### ISSUE THREAD

**Issue by enjoe842** [tachiyomiorg/tachiyomi-extensions#13201]
### Source information and language

Manhwas Men - English & RAW

### Steps to reproduce

Manhwas.men changed their web theme, so the old extensions doesn't work anymore. please update, thank you

### Expected behavior

can be opened normally

### Actual behavior

HTTP error 404 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment]
Uses Madara Theme
