### ISSUE TITLE
Koushoku: Chapter images doesn't load

### ISSUE THREAD

**Issue by devilo-dot** [tachiyomiorg/tachiyomi-extensions#13203]
### Source information and language

Koushoku(English)

### Steps to reproduce

1.install to koushoku 
2.go to koushoku
3.click a book/doujin
4.click the chapter
5.cant load the pages (issue)
6.try other doujin 
7.same problem the pages cant load
8.try webview the pages loading without a problemad the pages (issue)

### Expected behavior

1.install to koushoku 
2.go to koushoku
3.click a book/doujin
4.click the chapter
5. Pages loading  
6. Read the book 

### Actual behavior

1.install to koushoku 
2.go to koushoku
3.click a book/doujin
4.click the chapter
5.cant load the pages (issue)
6.try other doujin 
7.same problem the pages cant load
8.try webview the pages loading without a problem

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by devilo-dot** [comment]
Sorry if i do something wrong cuz First time ,using github

**Comment by TheKingTermux** [comment]
#12954 or #12920 probably

**Comment by happywillow0** [comment]
Hello. Can you confirm if the website is working? When I try to view the pages by clicking on one of the previews, the new page doesn't load anything for me.

**Comment by devilo-dot** [comment]
Yeah the site is working but u right when i go to webview and click 1 doujin and select the pages ,the pages didnt load

**Comment by catchra** [comment]
yeah the same thing happens to me as well if I go into webview no picture show up unless I keep refreshing it

**Comment by conztanz045** [comment]
It load on me in the webview but not in the extension
