### ISSUE TITLE
Mangás Chan: manga descriptions and delay in updating chapters

### ISSUE THREAD

**Issue by Frozik29** [tachiyomiorg/tachiyomi-extensions#13210]
### Source information and language

Mangás Chan 1.3.18

### Steps to reproduce

 Enter the extension or enter the "recent" option and click on any manga

### Expected behavior

Expected to have manga description and recent chapters update

### Actual behavior

The manga has no information or tags on what type he is, such as "Shounen". And the chapters don't update at the same time as the website, sometimes it takes hours for a chapter that came out on the website well before, update on Tachiyomi

### Tachiyomi version

TachiyomiJ2K 1.5.8

### Android version

Android 11

### Other details

On the website the information and tags are described there, and the updated manga appears much earlier on the website, and on Tachiyomi the manga doesn't update together, it takes time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Don't close your old issue to bump a new one.

Duplicate of #13167
