### ISSUE TITLE
Bato.to: Complete tag should be used on completed works instead of on-going one

### ISSUE THREAD

**Issue by Billarin** [tachiyomiorg/tachiyomi-extensions#13211]
### Source information and language

Bato.to English 1.3.29

### Steps to reproduce

One of Bato.to filter settings is to filter which ones have completed works and which have ongoing one.
However, I noticed that Bato.to has 3 status which is on-going, completed, and publishing finished.
On-going as its name suggests meaning that the work is still ongoing whether the raw that is not posted and the translated one that is posted in bato.to.
Completed mean that both the publishing and translation is done.
Publishing finished means that the work has been completed and published but is not posted yet/translated yet.
When using completed filter, it should have only showed the completed one but instead, it also shows the publishing finished one, therefore, creating confusion. It would be nice if this could be fixed so we can find what we want efficiently without any issues since I am looking for works that are posted already not works that have been published but not yet posted in the extension.

### Expected behavior

When the completed filter is used, only **COMPLETED** works both in publishing and translation should have been shown.

### Actual behavior

When the completed filter is used, it shows both **COMPLETED** and **ON-GOING BUT COMPLETED IN PUBLISHING BUT NOT IN TRANSLATION AND NOT YET POSTED.**

### Tachiyomi version

0.13.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rowgath** [comment]
Took a quick look at Batoto's site and it seems that this is a limitation caused by how their site and search works. The "Status" filter seems to be vaguely named and works more like "Status of Original work" .
