### ISSUE TITLE
Mangakatana missing pages.

### ISSUE THREAD

**Issue by Kissieh** [tachiyomiorg/tachiyomi-extensions#13239]
### Source information and language

Mangakatana 1.3.8

### Steps to reproduce

Read chapters of some manhwas

### Expected behavior

Full chapter

### Actual behavior

Fail to load some pages permanently.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

None.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by dec05eba** [comment]
It's likely a problem with the image server and it also fails to load the pages on mangakatana website. You can try changing image  server in Browser -> Extensions -> MangaKatana Settings -> Press the settings icon for English and select server preference "Server 2" or "Server 3". If that doesn't work but it does work on the mangakatana website then please provide an example manhwa that fails to load pages.

**Comment by Kissieh** [comment]
> It's likely a problem with the image server and it also fails to load the pages on mangakatana website. You can try changing image server in Browser -> Extensions -> MangaKatana Settings -> Press the settings icon for English and select server preference "Server 2" or "Server 3". If that doesn't work but it does work on the mangakatana website then please provide an example manhwa that fails to load pages.
What you said does seem to work

**Comment by Kissieh** [comment]
What you said does work + uninstalling and reinstalling the source again seems to have the same effect, thank you.
