### ISSUE TITLE
Updates failed for anything on asura scans 

### ISSUE THREAD

**Issue by Harry1177** [tachiyomiorg/tachiyomi-extensions#13230]
### Source information and language

Asura scans 1.3.34

### Steps to reproduce

I try and update all of my library and everything  other then the stuff I read on asura scans will update which is where I read most of my manhwa 
I have tried waiting for it to work again but its been 2 weeks 

### Expected behavior

I should just be able to update my library and then read any new chapters  that have came out 

### Actual behavior

I update my library and all that happens is it get told that 10 updates have failed and that is all I have had for 2 weeks

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please specify which errors are you getting.

**Comment by Harry1177** [comment]
It will give me a to many requests error

**Comment by alessandrojean** [comment]
Asura changed a lot of URLs for their series. Migrate your entries from Asura to Asura to update the URLs.
