### ISSUE TITLE
Mangahasu down

### ISSUE THREAD

**Issue by Kissieh** [tachiyomiorg/tachiyomi-extensions#13238]
### Source information and language

Mangahasu 1.3.16

### Steps to reproduce

Update your library

### Expected behavior

Update successful 

### Actual behavior

Failed to bypass cloudfare

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

None.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by Kissieh** [comment]
Best alternative right now for mangahub and mangahasu?
