### ISSUE TITLE
ManhwaClub: Fails with unparseable relative dates

### ISSUE THREAD

**Issue by azeunkn0wn** [tachiyomiorg/tachiyomi-extensions#13237]
### Source information and language

ManhwaClub v1.3.5

### Steps to reproduce

1. Browse Sources
2. select ManhwaClub (Latest)
3. select any manga/manhwa (preferably the most recent) 

### Expected behavior

Manga details with chapter list will be displayed

### Actual behavior

manga chapters are null. received an error about the date being unparsable. 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

It became impossible to migrate a manga/manhwa into ManhwaClub source if the manga have new chapter recently, because of this error. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by azeunkn0wn** [comment]
![Screenshot_2022-08-28-05-20-13-951_eu kanade tachiyomi](https://user-images.githubusercontent.com/6234843/187049085-d43c429f-4839-4ab8-992a-1fb223797f36.jpg)

**Comment by azeunkn0wn** [comment]
issue still not fixed

**Comment by bman-95** [comment]
It is still not fixed.

**Comment by AntsyLich** [comment]
Superseded by #17528
