### ISSUE TITLE
Kissmanga.in failed to bypass Cloudflare but working fine in webview

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi-extensions#13261]
### Source information and language

Kissmanga.in 1.3.26 (English)

### Steps to reproduce

1. Take a manhua from kissmanga.in
2. Wait for further chapter updates
3. Refresh manhua manually

### Expected behavior

The extension/app should fetch latest manga and show

### Actual behavior

The first time I refreshed Manhua, the app showed HTTP Error 503
When I refreshed it again it just showed failed to bypass cloudflare even though the extension is working fine in webview and browser

### Tachiyomi version

0.13.6

### Android version

Andriod 11

### Other details

Here's a video of the bug -
[tachiyomi.webm](https://user-images.githubusercontent.com/92982808/187151520-f259d3c5-899b-4d43-8b6a-19972f14ea1b.webm)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
