### ISSUE TITLE
Tapas & Webtoons: Chapters with Author's Notes fail to download

### ISSUE THREAD

**Issue by Throun** [tachiyomiorg/tachiyomi-extensions#13279]
### Source information and language

Tapas 1.3.16, Webtoons.com 1.3.35

### Steps to reproduce

1. Enable author's notes in source settings
2. Go to any work with author's notes
3. Download a chapter that contains notes

### Expected behavior

The chapter is downloaded.

### Actual behavior

The download fails with HTTP error 500.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Tapas and Webtoons started having issues at the same time, so I don't _think_ it's a server-side problem.
It seems that chapters that were uploaded prior to August 25-26 are not affected, but I can't confirm.
Any chapters without author's notes download fine, including for works with affected chapters.
Reading the chapters is fine, but the note won't load.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by altaccosc** [comment]
Thanks for using my feature!! I've just made a PR that should fix it :D

**Comment by altaccosc** [comment]
You're right! I also found out half an hour ago after rewriting it that the original API got fixed. I still think this new version looks a bit better, though.
