### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by 4ngels** [tachiyomiorg/tachiyomi-extensions#13281]
### Source name

Apotheosis manga online 

### Source link

https://readapotheosis.com/

### Language

English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
This site is one of those sites where it only has one manga. Is there something really special about this site that you don't have on any of the other sites that have this manga series?

**Comment by stevenyomi** [comment]
It scrapes from Manhua Plus. You can download that extension (https://tachiyomi.org/extensions/#en.manhuaplus).
