### ISSUE TITLE
Chapters doesn't work (from 2 months)

### ISSUE THREAD

**Issue by BenaliAziz** [tachiyomiorg/tachiyomi-extensions#13285]
### Source information and language

مانجا لينك(1.3.26)

### Steps to reproduce

The chapters don't load 
![Screenshot_20220831-134618_Tachiyomi](https://user-images.githubusercontent.com/111535060/187682178-c67d2169-8618-4463-b1e6-7eb3ffb9ca42.jpg)

### Expected behavior

This should work 

### Actual behavior

As faster as you can

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
