### ISSUE TITLE
Pepper & Carrot Webcomic

### ISSUE THREAD

**Issue by Johnny5sword** [tachiyomiorg/tachiyomi-extensions#13308]
### Source name

Pepper & Carrot

### Source link

https://www.peppercarrot.com/en/webcomics/index.html

### Language

Multiple

### Other details

A free(libre) and open-source webcomic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Did someone say open-source webcomic? :eyes:

**Comment by stevenyomi** [comment]
> Did someone say open-source webcomic? 👀

Check the website yourself. It is indeed open-source.

**Comment by stevenyomi** [comment]
Gonna try doing this one.

**Comment by ObserverOfTime** [comment]
Not if I beat you to it.
