### ISSUE TITLE
Able to hide Categories

### ISSUE THREAD

**Issue by Fujin-sama** [tachiyomiorg/tachiyomi-extensions#13301]
### Describe why this should be added

As we know as of now you can put lock on the tachiyomi app, but some people knows the password to the lock and see some manga, manhua, and manhwa we dont want others to see.

### Other details

Able to hide categories.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
