### ISSUE TITLE
My Wife is a Demon Queen

### ISSUE THREAD

**Issue by ArchCelestial** [tachiyomiorg/tachiyomi-extensions#13306]
### Source name

Read My Wife is a Demon Queen 

### Source link

https://demonqueen.online/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
This site is one of those sites where it only has one manga. Is there something really special about this site that you don't have on any of the other sites that have this manga series?

**Comment by ArchCelestial** [comment]
It's cool

**Comment by ArchCelestial** [comment]
Essentially this is the only site that gives a better translation for the series.

**Comment by popinloopy** [comment]
This website is also not the one who translates it and is therefore a little behind when a new chapter comes out. Use the MangaGreat extension to get it directly, they are the ones who translate and upload the chapters. That website is just a reuploader that also has issues on earlier chapters with duplicates and out of order panels, iirc.

**Comment by alessandrojean** [comment]
@popinloopy Please DO NOT recommend extensions.

**Comment by stevenyomi** [comment]
Uses Madara theme.
