### ISSUE TITLE
mcreader.net: lateinit property title has not been initialized

### ISSUE THREAD

**Issue by BismarkoNobilas** [tachiyomiorg/tachiyomi-extensions#13318]
### Source information and language

mcreader.net 1.3.15

### Steps to reproduce

1. Open the "Latest" from the source
2. Open manga that has never been opened before (Don't have a description yet)

### Expected behavior

Expected to have manga description and there is no notification

### Actual behavior

The manga has no description and a notification appears "lateinit property title has not been initialized"

### Tachiyomi version

Preview 0.13.6-4845

### Android version

Android 11

### Other details

On the website/web view the information and tags are described. There are existing similar issues but for other extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BismarkoNobilas** [comment]
After updating to 4884, the previous issue where the description didn't show up was resolved. only when refreshing the manga a "lateinit property title has not been initialized" notification appears, but everything seems to be working properly.

**Comment by MrAndre96** [comment]
This also happens with the source Mangahere when you refresh the manga
