### ISSUE TITLE
[Source request] [Portuguese - Brazil] DDA scan

### ISSUE THREAD

**Issue by jotasete** [tachiyomiorg/tachiyomi-extensions#1331]
Please be able to make an extension of this site.  Thanks for listening

https://ddascan.blogspot.com/?m=1

**Comment by alessandrojean** [comment]
It's kinda hard to do a extension because the scanlator uses a blog, and the content in the posts doesn't have a pattern that a extension needs.

**Comment by jotasete** [comment]
I see, I thought it wasn't really going to be possible 😔.  Thank you anyway

**Comment by SnakeDoc83** [comment]
I think it's doable, I was working on an extension for it a while back but
it got pushed to the back burner.  I'll take another look.

**Comment by alessandrojean** [comment]
@SnakeDoc83 if you have found a pattern in the posts, good luck.

**Comment by jotasete** [comment]
@SnakeDoc83 It was going to be awesome, but this blog is really confusing.  As @alessandrojean said

**Comment by alessandrojean** [comment]
Closing this because they apparently aren't active anymore since the last update was on April 2020, and the site isn't a proper online reader as explained before.
