### ISSUE TITLE
NineAnime: all_imgsurl not found

### ISSUE THREAD

**Issue by Tcholly** [tachiyomiorg/tachiyomi-extensions#13315]
### Source information and language

NineAnime 1.3.3

### Steps to reproduce

1. Open manga from nineanime source
2. Open a chapter

### Expected behavior

Open chapter to read

### Actual behavior

Fails to open chapter with message all_imgsurl not found

### Tachiyomi version

Tachiyomij2k 1.5.8

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by YukiRed** [comment]
I got this problem also.
Any idea how to solve?
