### ISSUE TITLE
Mangadex not showing newest chapters in app, but are available in webview

### ISSUE THREAD

**Issue by BlankUnknown** [tachiyomiorg/tachiyomi-extensions#13328]
### Source information and language

Mangadex

### Steps to reproduce

Can't see the newest chapters of chainsaw man in mangadex extension, only in webview are they available. Have tried to update app and refresh manga, but nothing happens. 

### Expected behavior

Should come with newest chapters

### Actual behavior

Doesn't update for the new chapters

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
These are external chapters, Dex doesn't host them.  Click and you will be redirected to another website. The extension is working as expected by not showing them.
