### ISSUE TITLE
Asura Scans Certain Titles not Updating

### ISSUE THREAD

**Issue by GangstaPichu** [tachiyomiorg/tachiyomi-extensions#13325]
### Source information and language

Asura Scans 1.3.36

### Steps to reproduce

Click on a title not updated for awhile that you may have left in the dark waiting for updates. Like: 
![Screenshot_20220902-135204_Tachiyomi](https://user-images.githubusercontent.com/88961592/188211479-54f5321a-8be6-4c0b-9f56-17fb65a6f031.jpg)

Then go to the web page and check if it has updated after updating the page a couple times cause it feels like ages when they have set schedules for releasing. Like: 
![Screenshot_20220902-135216_Tachiyomi](https://user-images.githubusercontent.com/88961592/188211628-428d3f93-ab83-4635-817f-1d8a994da297.jpg)

### Expected behavior

To always update titles. 

### Actual behavior

Updayes certain ones and not others. Like the title "The Newbie is too strong" is getting updated and some others. 

Some titles to name not being updated: The Lord’s Coins Aren’t Decreasing?! (Stuck on chapter 73, no updates it says), I Reincarnated As The Crazed Heir (stuck on chapter 58, says the same thing), and Player Who Can’t Level Up (stuck on chapter 74, says the same). Only to name a couple.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Asura changed a lot of links from their series. Migrate from Asura to Asura to update them and pull to refresh to fetch the new chapters.
