### ISSUE TITLE
MangaWT: Theme Changed

### ISSUE THREAD

**Issue by chocolax** [tachiyomiorg/tachiyomi-extensions#13335]
### Source information and language

MangaWT 1.3.25 (Turkish)

### Steps to reproduce

1. Search manga
2. HTTP error 400

### Expected behavior

Should able to find the manga

### Actual behavior

HTTP error 400

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

Theme changed from Madara to MangaStream.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Theme migration from *Madara* to *MangaThemesia*
