### ISSUE TITLE
Pig Rabbit Scans

### ISSUE THREAD

**Issue by jasshira266** [tachiyomiorg/tachiyomi-extensions#13330]
### Source name

PigRabbitScans

### Source link

https://www.pigrabbitscans.org/

### Language

Español (es)

### Other details

An account is needed to access, Only need an E-mail.
Madara Theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Lenoyr** [comment]
Dead site bro

**Comment by jasshira266** [comment]
> 

Well yes, it's already expired, very late hahahaha
