### ISSUE TITLE
Search chapters by title

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#13332]
### Describe why this should be added

This would work well for extensions like kemono, which have many chapters and sometimes finding a specific art (chapter) is difficult, especially when the titles are in another language. I could also search for "x" art by its date, but sometimes the order of chapters is messed up even after setting the sort by date option

### Other details

![1662185745773](https://user-images.githubusercontent.com/101371218/188258511-238cd9a7-6862-41ff-a5c4-2298c6acdf69.png)
![1662185856507](https://user-images.githubusercontent.com/101371218/188258514-67b7d3cf-72f1-417b-96af-16d72b3a4f07.jpg)
![IMG_20220903_002047](https://user-images.githubusercontent.com/101371218/188258594-958893b5-2b82-414f-8d62-a25b7d6023a4.jpg)

uhh, something like this? 
i looked in the app and there was no option for this, at least I see it as something that would be useful

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
This would have to be implemented in the app itself rather than the extensions.

**Comment by edmxn** [comment]
> This would have to be implemented in the app itself rather than the extensions.

dmn wrong section
