### ISSUE TITLE
PISCANS

### ISSUE THREAD

**Issue by libran07** [tachiyomiorg/tachiyomi-extensions#13344]
### Source name

Pi Scans

### Source link

https://piscans.com/

### Language

Indonesian

### Other details

![d16d6c68-7c3d-4132-8658-3944a0285181](https://user-images.githubusercontent.com/90138720/188318155-7ba90774-a628-460c-a246-0c39edd63f57.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Uses Madara theme.

**Comment by vetleledaal** [comment]
> Uses Madara theme.

More like MangaThemesia, the chapters just look like how Madara would do it.
