### ISSUE TITLE
One specific manhwa's updates stopped showing

### ISSUE THREAD

**Issue by popinloopy** [tachiyomiorg/tachiyomi-extensions#13347]
### Source information and language

Asura Scans 1.3.36, English

### Steps to reproduce

1. Add "Return of the Crazy Demon" to your library
2. Try to update it
3. Notice only up to chapter 52.5 appears
4. Use the WebView button
5. Get very confused by why that takes you directly to chapter 53
6. View the manhwa's chapter select page and see it goes up to 56 currently

### Expected behavior

Chapters 53-56 should show up when updating/refreshing, WebView button should take you to the disambiguation page

### Actual behavior

53-56 do not appear, WebView button takes you to chapter 53

### Tachiyomi version

Stable 0.13.6

### Android version

Android 12

### Other details

Probably something that has to be fixed by Asura Scans, but I didn't know where else to report it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Asura changed a lot of their titles URL, it happens pretty often. Migrate from Asura to Asura to update the entry in your library or remove it and add it again from the Browse screen.
