### ISSUE TITLE
Akuma.moe NSFW

### ISSUE THREAD

**Issue by MikaelaMuller** [tachiyomiorg/tachiyomi-extensions#13342]
### Source name

Akuma

### Source link

akuma.moe

### Language

Various languages

### Other details

NSFW, contains content not catalogued in the popular NSFW sources. 

### Note
This IS a duplicate (labeled stale, not sure if im allowed to do this because idk if i can reopen issues) 
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6199#issue-833929378

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Yeah you can open a new issue for a stale, auto-closed source request. It is totally fine. You don't need to mark it as duplicate.

**Comment by skysonfire** [comment]
yeah hopefully we get to see that one soon
