### ISSUE TITLE
Gabut Scans: Expected URL Scheme

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#13355]
### Source information and language

Gabut Scans 1.3.21

### Steps to reproduce

Open tachiyomi
Open Gabut Scans 
Download any chapter
Error Expected URL Sceme "http" or "https" but no Sceme ............

### Expected behavior

Chapter can be downloaded 

### Actual behavior

Error Expected URL Sceme "http" or "https" but no Sceme ............
![IMG_20220905_183057](https://user-images.githubusercontent.com/50316075/188439060-5d341e2f-ede3-45c0-83b5-73bbfebfb164.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce. Any example manga where this issue shows up? Does the issue disappear if you refresh or migrate the manga back to Gabut Scans?

**Comment by TheKingTermux** [comment]
Ohh it work now
After migrating to another source ane migrate back to Gabut Scans
