### ISSUE TITLE
Leviatan Scans: HTTP error 400 

### ISSUE THREAD

**Issue by I-Am-C0der** [tachiyomiorg/tachiyomi-extensions#13353]
### Source information and language

Leviatan Scans 1.3.35 (English)

### Steps to reproduce

1.Install Leviatan Scans 1.3.35
2.Select Nocturnal Scans in Browse->Source

### Expected behavior

This should show list of Manhwa/Manga available in the site

### Actual behavior

**But it's showing Error 400**

![Leviatan](https://user-images.githubusercontent.com/51527183/188407714-3612da3c-07af-4ca7-a1d5-1d450476a965.jpeg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

 The webview is working without any issues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
Same here, i think the URL change

**Comment by NotPageD** [comment]
Exactly, they changed it to en.leviatanscans.com
