### ISSUE TITLE
Mcreader not bypassing CloudFlare 

### ISSUE THREAD

**Issue by Viva1HA** [tachiyomiorg/tachiyomi-extensions#13365]
### Source information and language

mcreader version 1.3.15

### Steps to reproduce

Opening app
Opening chapter

### Expected behavior

Read my chapter 

### Actual behavior

Chapter not loading
Closes after a couple of seconds
Failed to bypass CloudFlare message pops out
Tried following the troubleshooting steps a couple of times, but it didn't work

### Tachiyomi version

App version: 0.13.6 

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Beji-kun** [comment]
Try change user agent string instead 

Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Mobile Safari/537.36

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by Viva1HA** [comment]
What's a user agent string?
    On Tuesday, September 6, 2022 at 06:00:33 a.m. EDT, Adam Kocourek ***@***.***> wrote:  
 
 


Try change user agent string instead

Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Mobile Safari/537.36
