### ISSUE TITLE
Komik Cast and KomikIndoID: Filter Pagination broken 

### ISSUE THREAD

**Issue by Subadrunz** [tachiyomiorg/tachiyomi-extensions#13366]
### Source information and language

Komik Cast 1.3.33 (Indonesia) and KomikIndoID 1.2.4 (Indonesia)

### Steps to reproduce

1.  Use filter in komik cast or KomikIndoID extension
2. Choose any genre or type 
3. Scroll down 
4. watch what happens 

### Expected behavior

Can use filters conveniently 

### Actual behavior

When using filters, the Pagination is broken (looping)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

![IMG_20220906_192852](https://user-images.githubusercontent.com/107401290/188637117-cc53c457-3f02-4dfe-9881-abe7e0dc6f40.jpg)
![IMG_20220906_193017](https://user-images.githubusercontent.com/107401290/188637125-d56b4000-f125-459a-a9f4-f0d2bc4e7fd7.jpg)
![IMG_20220906_193113](https://user-images.githubusercontent.com/107401290/188637133-caa18e7e-8b18-4bb7-af38-90faedac420c.jpg)
![IMG_20220906_193212](https://user-images.githubusercontent.com/107401290/188637142-aef6ad3d-8485-441b-b939-a9c626e2ed41.jpg)
![IMG_20220906_193311](https://user-images.githubusercontent.com/107401290/188637146-46c152f8-3d3b-42b7-827b-cbe08f11bc2c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This has been fixed for komikcast.

**Comment by CarlosEsco** [comment]
Open a new issue for the other source. And next time one issue per a ticket
