### ISSUE TITLE
Reaperscans not working

### ISSUE THREAD

**Issue by Lumi6x9** [tachiyomiorg/tachiyomi-extensions#13376]
### Source information and language

Reaper scans  1.3.30 (English) 

### Steps to reproduce

1. Open Tachiyomi
2. Click on browse
3. Click on **Reaper scans**

### Expected behavior

It should have shown library of **Reaper scans**

### Actual behavior

"No results found"
![Screenshot_20220907-080139](https://user-images.githubusercontent.com/92018454/188781638-e07f3ab2-5400-41ab-b082-f57456319a2e.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

Nothing yeah
![Screenshot_20220907-080139](https://user-images.githubusercontent.com/92018454/188781778-ecd602fa-bae5-4d69-bf8f-70af0e388697.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jedel1043** [comment]
Um, Reaper is on maintenance...

**Comment by alessandrojean** [comment]
Reaper Scans's site is broken, wait until they fix it. Nothing we can do on the extension side.

**Comment by Slepnair** [comment]
Still down, site says maintenance is almost done.
