### ISSUE TITLE
Meus Mangás: no results found

### ISSUE THREAD

**Issue by Frozik29** [tachiyomiorg/tachiyomi-extensions#13375]
### Source information and language

Meus Mangás 1.3.9

### Steps to reproduce

click on the extension

### Expected behavior

Show the catalog with the mangas

### Actual behavior

no results appear

### Tachiyomi version

TachiyomiJ2K 1.5.9

### Android version

Android 11

### Other details

when you click on "lastet" the mangas that were recently added appear

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Frozik29** [comment]
![Screenshot_20220906-232325_TachiyomiJ2K](https://user-images.githubusercontent.com/106293562/188775550-b45ca917-49ad-4005-a779-8c9de621df02.jpg)

**Comment by alessandrojean** [comment]
They removed the popular series section on their website so it's expected to series not to show as the extension can't obtain an information that they doesn't provide anymore. Search and other stuff are reported to still be working though.

If you do really need to see the popular listing, try other sources that do provide that information.
