### ISSUE TITLE
[SOURCE REQUEST] LOLScans

### ISSUE THREAD

**Issue by Ry4023** [tachiyomiorg/tachiyomi-extensions#1337]
[LOLScans Website](https://lolscans.com/)
[LOLScans Reader](https://forums.lolscans.com/book/r.php)
Also seems to use a PHP CMS, [Manga and Webcomic Reader 2000](https://bitbucket.org/40163650/manga-and-webcomic-reader-2000/src/master/), not sure if any other websites use it currently.

**Comment by as280093** [comment]
Here the icons
[LOLScans.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612710/LOLScans.zip)

**Comment by CVIUS** [comment]
dead site
