### ISSUE TITLE
Komiku : can't get past coldfiare while browsing comics 

### ISSUE THREAD

**Issue by Pengamen1kaos** [tachiyomiorg/tachiyomi-extensions#13402]
### Source information and language

Indonesia 1.3.14

### Steps to reproduce

1.when I want to search for example "One Piece" it can't be written Failed to break through coldfiare

### Expected behavior

1.there should be a search result 

### Actual behavior

please fix it as soon as you can 😭

### Tachiyomi version

0.13.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pengamen1kaos** [comment]
![Screenshot_20220908-235515_Tachiyomi](https://user-images.githubusercontent.com/111288479/189184336-8ebf42dc-9f29-4450-bbc1-55956c0773fc.jpg)
 Ah I forgot to give this photo

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
