### ISSUE TITLE
Manhua kiss: Changed their domain

### ISSUE THREAD

**Issue by elizabbetta** [tachiyomiorg/tachiyomi-extensions#13407]
### Source information and language

Manhua kiss v1.3.24 English 

### Steps to reproduce

1. Go to Manhua kiss source
2. Tap any manhwa (shows no chapters found)
3. Tap source, redirects to "https://manhuakiss.me/" their old website with a countdown

### Expected behavior

Should be pulling from "https://manhuakiss.com/" their new updated website instead of their old website "https://mangastic.me/"

### Actual behavior

Displays available manhuas with no chapter available because it pulls from their old website domain

### Tachiyomi version

1.3.24

### Android version

8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment]
This issue can be closed. The URL was updated in #13481 for a duplicate request #13477.
