### ISSUE TITLE
Walpurgis Scan: HTTP error 400

### ISSUE THREAD

**Issue by Fatdest** [tachiyomiorg/tachiyomi-extensions#13404]
### Source information and language

Walpurgis Scan v1.3.26

### Steps to reproduce

when i try to open the extention on  the app it says http error 400
![photo_2022-09-08_21-01-34](https://user-images.githubusercontent.com/97848675/189204579-bc88d875-c1a7-43c8-a015-1ac2f3a64e47.jpg)

### Expected behavior

it should show the list of mangas available

### Actual behavior

http error 400

### Tachiyomi version

Tachiyomi 0.13.6

### Android version

Android 10

### Other details

the reason is probably because recently the website has gone through some modifications (they dont'use the madara theme anymore, they switched to mangastream)
the owner of the website has also changed the domain from walpurgiscan.altervista.org to walpurgiscan.com  (the previous link still works because you get redirected to the new one but it can still cause problems).
I hope that the extention can be fixed.
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Domain was changed to `https://www.walpurgiscan.com` and theme changed to MangaThemesia
