### ISSUE TITLE
Reaper scan problems

### ISSUE THREAD

**Issue by demon456blade** [tachiyomiorg/tachiyomi-extensions#13410]
### Source information and language

Reaper Scan 1.3.30

### Steps to reproduce

The issue is that all the chapters read have been removed while old chapters are again and again coming the update feed

### Expected behavior

We should be getting the updates of new chapter and have read chapters shown

### Actual behavior

All chapters are shown unread while old manga chapters are coming again and again

### Tachiyomi version

0.13.6

### Android version

Lates android

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
They're down for maintenance.

**Comment by demon456blade** [comment]
Ah I see thx for the info My boi

**Comment by Pheonix747hs** [comment]
Yep,seems in general their site is having difficulties, my bad :p

**Comment by vetleledaal** [comment]
According to the site:
> The site is operational again for the time being via a temporary fix.
Our developers are working on a permanent fix that will likely be implemented in the coming few weeks.

Can't replicate the reported issue as of now, so it appears to have been fixed.
