### ISSUE TITLE
MangaDex source open in browser doesn't work

### ISSUE THREAD

**Issue by jrdp18** [tachiyomiorg/tachiyomi-extensions#13412]
### Source information and language

MangaDex 1.3.167

### Steps to reproduce

1. Search and open manga in Sources and pick a MangaDex one, or pick a comic in your Library which uses MangaDex source
2. Click WebView and it will load the comic page
3. Click the 3 dots on the upper right corner
4. Select "Open in browser"

### Expected behavior

It should automatically open in one of your default browsers or ask you to pick a browser.
![Screenshot_2022-09-09-12-23-34-374_android](https://user-images.githubusercontent.com/1020288/189271635-0dbe889d-0d51-498c-916a-6b6c6dc0f62a.jpg)

### Actual behavior

It looks like it tried searching within the Tachiyomi app, appending the comic id
![Screenshot_2022-09-09-12-20-18-186_eu kanade tachiyomi](https://user-images.githubusercontent.com/1020288/189271583-dda10fc5-9065-4645-8df1-ab62ec7988b8.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
It's because you set the MangaDex extension as the default way to open MangaDex links. Tap MangaDex in the **extension** list and tap **app info**, then check for an option to reset all default settings.

**Comment by jrdp18** [comment]
I did not. Right now, when I open MangaDex links in Chrome it just opens in Chrome. Back then there would be a browser selection (like the 1st screenshot) and I'd see and option to select Tachi.

This is what the options look after App Info.
![Screenshot_2022-09-09-13-27-29-161_com miui securitycenter](https://user-images.githubusercontent.com/1020288/189277955-70c2e182-15ba-408e-aa8f-c964f2831957.png)
I tried Clear data. Uninstalling the extension, exit Tachi then reinstalling. But still goes like that.

**Comment by stevenyomi** [comment]
> Right now, when I open MangaDex links in Chrome it just opens in Chrome.

This is the correct behavior. The URL intent is only triggered when you tap a MangaDex link in Chrome. You can test that.

Try this too: system settings - apps - default apps - open links - MangaDex extension.

**Comment by meromex** [comment]
I have the opposite issue, mangadex doesn't work in tachiyomi, always fails to load the image and goes to refresh but works fine in web view 
![Screenshot_20220909-024409-593](https://user-images.githubusercontent.com/34610160/189298849-02a6404b-7e54-41c8-ab64-c319be69cf7e.png)

**Comment by stevenyomi** [comment]
> I have the opposite issue, mangadex doesn't work in tachiyomi, always fails to load the image and goes to refresh but works fine in web view 

Check https://status.mangadex.org. If the issue persists, you should open another issue.

**Comment by meromex** [comment]
Seems tachiyomi is blocked 
![Screenshot_20220909-172830-023](https://user-images.githubusercontent.com/34610160/189454406-d4cad300-1679-486e-a49d-fbd4feaa5b6b.png)
