### ISSUE TITLE
Mangadex Source Down but Website is Up

### ISSUE THREAD

**Issue by CDC128** [tachiyomiorg/tachiyomi-extensions#13421]
### Source information and language

Mangadex 1.3.167

### Steps to reproduce

Open Mangadex Source

### Expected behavior

Browse Titles

### Actual behavior

Page doesn't load only shows HTTP error 503 and even webview doesnt work

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

Tried opening it on a browser site works fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfu** [comment]
this appears to be intentional (albeit temporary), see the [Mangadex status page](https://status.mangadex.org):

> Update - We have continued investigating, to no avail so far. We have managed to bring the site back up for everyone **at the expense of third-party clients** and some of the more computationally expensive features of the site (chapter reading statuses, that is).

(emphasis mine)
