### ISSUE TITLE
Mangabz shows the "... none object reference" notification and can't be reached

### ISSUE THREAD

**Issue by History-exe** [tachiyomiorg/tachiyomi-extensions#13423]
### Source information and language

Mangabz 1.3.6 (Chinese)

### Steps to reproduce

1. Auto / Manual update this manga [不要欺负我、长瀞同学](https://xmanhua.com/105xm/) of the Mangabz (Already try the main site and the mirror site, none of them work)
 All the updates are already set as "skip the manga that has unread","skip the not read yet", "skip the finished"

### Expected behavior

Update successfully

### Actual behavior

1. The manga already read the latest chapter, an alert will appear for updates.
It is `Attempt to invoke virtual method'org.jsoup.select.Elements org.jsoup.nodes.Element.children()' on a null object reference`
![photo_2022-09-10_13-17-15](https://user-images.githubusercontent.com/33642965/189471334-82af8595-f253-41d4-9e35-7893a05b3c04.jpg)

2. There are also unread chapters of the manga that can read the chapters normally, but cannot be updated, and the same notification.

### Tachiyomi version

0.13.6 (2022-08-14 23:52)

### Android version

Android 9

### Other details

1. In the webview mode, the site is fine and there are the chapters. It is not block or something else.
2. The vomic(version 1.3.1 Chinese) extention also has this notification, Both of Mangabz and the vomic can't be reach in the Search section now.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce here for either Mangabz or vomic. Try migrating the manga to the same source or switching network.

**Comment by stevenyomi** [comment]
Also make sure your default user agent string is a PC one.

**Comment by History-exe** [comment]
> Also make sure your default user agent string is a PC one.

Worked, thx.
