### ISSUE TITLE
Tappytoon

### ISSUE THREAD

**Issue by alireda22** [tachiyomiorg/tachiyomi-extensions#1342]
https://www.tappytoon.com/

**Comment by as280093** [comment]
Here the icons
[tappytoon.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612702/taaptoon.zip)

**Comment by Arekkusu1998** [comment]
I downloaded Tachiyomi APK from [here](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.10.7): I want to download through my Android Simulator «BluStacks 4.2» some manhwa / webtoon that I found on **Tappytoon** and whose reading is forbidden by the tokens system.
Tappytoon isn't into the Extensions list - will it be added???
Also, will it be possible to read and download the **not-Free** chapters too???

**Comment by CrepeTF** [comment]
@Arekkusu1998 
No Tachiyomi does not bypass paid chapters, and it will not in the future either .

If you want to read a paid chapter from the source, login through webview and buy the chapter or already own it to begin with.

**Comment by Arekkusu1998** [comment]
Thanks for the useful clarification, @**CrepeTF**.
I also hope that Tappytoon Comics will be added to the Extensions (if I knew the programming language I would do it myself, but I'm an Tech semi-illiterate🙄).

**Comment by cecoates** [comment]
Functionality similar to the Tapas extension would be excellent.

That extension lets you login to your Tapas account via webview, then you're able to download chapters that you've paid for/unlocked.
