### ISSUE TITLE
Reaper scans manhwas not opening 

### ISSUE THREAD

**Issue by Pheonix747hs** [tachiyomiorg/tachiyomi-extensions#13422]
### Source information and language

Reaper scans 1.3.30

### Steps to reproduce

1.save a manwha to list
2.open it

### Expected behavior

Manhwa should open

### Actual behavior

Loads for a bit and then reader crashes with http 502 code, although the webview still works
All other site extensions are working as far as I can check 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#13410
