### ISSUE TITLE
nHentai cant bypass cloudflare

### ISSUE THREAD

**Issue by BANANA25323** [tachiyomiorg/tachiyomi-extensions#13427]
### Source information and language

NHentai 1.3.36 (All)

### Steps to reproduce

1. Open tachiyomi
2. Tap Browse menu
3. Open NHentai extention
4. Failed to bypass cloudflare

### Expected behavior

Showing any manga/manhwa/manhua

### Actual behavior

Failed to bypass cloudflare even if i change my DNS to cloudflare of disable it, when i open NHentai its showing "Failed to bypass cloudflare"

### Tachiyomi version

1.3.36

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by heartlog** [comment]
@BANANA25323 try clearing cookies.
And then click any (nhentai) manga and click webview.

Wait....
After the website is opened, it'll solve your problem.

**Comment by vetleledaal** [comment]
You are expected to open the WebView if the automated process fails. Cloudflare might be giving you a captcha, or require some additional time.
