### ISSUE TITLE
Manhwas.net: fewer manga than expected are shown under latest

### ISSUE THREAD

**Issue by alpqm** [tachiyomiorg/tachiyomi-extensions#13437]
### Source information and language

Manhwas 1.3.3

### Steps to reproduce

1.Press the latest button in the manhwas.net extension 
2.There are only a few comics displayed

### Expected behavior

Should have spawned a lot of comics

### Actual behavior

Only a few comics are shown 

### Tachiyomi version

0.13.6

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "Manhwas.net: fewer manga than expected are shown under latest"

**Comment by lleccar** [comment]
It is normal, the website only shows a few
