### ISSUE TITLE
request for Aresmanga's source removal from tachiyomi app

### ISSUE THREAD

**Issue by Volver555** [tachiyomiorg/tachiyomi-extensions#13430]
### Source link

https://aresmanga.com/

### Other details

this an ownership proofk if it's enough: 
https://aresmanga.com/owner.html

it has my discord account if there is anything else required.
please contact me there, with my sincere thank!

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by loocool2** [comment]
Proof of ownership has been DMed to me
