### ISSUE TITLE
Mangadex HTTP error 503

### ISSUE THREAD

**Issue by kschou95** [tachiyomiorg/tachiyomi-extensions#13431]
### Source information and language

Mangadex

### Steps to reproduce

Just try to open the source.

Here's a video proof
https://youtube.com/shorts/fDr9qHmnCnY

### Expected behavior

Expected to show mangas from mangadex.

### Actual behavior

Error 503 instead and didn't show mangas.

### Tachiyomi version

0.13.6

### Android version

Android 13

### Other details

I thought Mangadex was having a maintenance, but when i checked using browser, Mangadex works.
Using google dns, on my router, in tachiyomi app settings, and even in android's connection settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DrCryllus** [comment]
Mangadex is currently "Temporarily" blocking Tachiyomi connections due to server issues. Check the Mangadex Reddit and Twitter. Or their discord, if you really want information.

**Comment by Breadoggo** [comment]
Exact same thing happened to me.

**Comment by alessandrojean** [comment]
Closing as it's temporary intentional from Dex side until they fix their infrastructure. Wait for that or use other sources in the meanwhile, there's no ETA.
