### ISSUE TITLE
Manga Weebs

### ISSUE THREAD

**Issue by TheGoldenSun** [tachiyomiorg/tachiyomi-extensions#13443]
### Source information and language

Manga Weebs 1.3.30

### Steps to reproduce

1. Fix the date

2. Double check if the date is in order.

3. Improve manhua translations within manga weebs correctly. 

### Expected behavior

Improving translations and date that should be fixed.

### Actual behavior

![Screenshot_20220911_150926](https://user-images.githubusercontent.com/104534608/189545360-e7ea3b11-d8b7-4947-85af-375fba486495.jpg)

### Tachiyomi version

r4904

### Android version

Android 11

### Other details

Whenever I tried reloading manga weebs extension twice to double check if the date would be corrected properly but it does not show the present year besides the past year 1970. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The website doesn't provide the year, so there is nothing to fix. As a side-effect the year is set to 1970, as this is when the unix timestamp starts counting from.

The default order is to use the same as the site.

**Comment by TheGoldenSun** [comment]
Do me a favor Vetle, tell your friend on discord not to notify me to issue a pointless report like this again then, thank you for telling me. 

Sent from miss moriarty  
 
  On Mon, Sep 12, 2022 at 6:09 PM, Vetle ***@***.***> wrote:   


The website doesn't provide the year, so there is nothing to fix. As a side-effect the year is set to 1970, as this is when the unix timestamp starts counting from.

The default order is to use the same as the site.
