### ISSUE TITLE
Too many follow up requests (21)

### ISSUE THREAD

**Issue by Thepope5** [tachiyomiorg/tachiyomi-extensions#13448]
### Source information and language

Asura scans (english)

### Steps to reproduce

Mangas not refreshing as they used to, started to refresh each one manually, but some can be refreshed while others cant

### Expected behavior

Refreshanga, get a new chapter

### Actual behavior

Too many follow up requests 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment]
> Asura Scans has changed URLs for many of their manhwa. Migrate from Asura Scans to Asura Scans (as in, migrate manhwa to itself) to continue reading those manhwa.
