### ISSUE TITLE
Doujindesu: Change website appearance

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#13444]
### Source information and language

Doujindesu 1.2.2 (ID)

### Steps to reproduce

Add Doujin to library
Refresh all Comic in Tachi
Error `Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object referen

### Expected behavior

Doujin must be refresh

### Actual behavior

Error `Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object referen
![Screenshot_2022-09-12-04-48-52-61_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/50316075/189550443-5d84ac1b-12eb-449a-9025-7dbba68f712b.jpg)

### Latest Information 
![IMG_20220912_180111](https://user-images.githubusercontent.com/50316075/189638062-c226f817-29ab-4635-9c8b-3c3af6006dce.jpg)

The Doujindesu website is changes in appearance and add addition of new features

### Doujindesu domain
Still can be accessible with https://doujindesu.xxx (by using a VPN)
IP raw domain https://212.32.226.234 (By not using a VPN & absolutely can't be used in tachi extension due non-secure measure)

### Latest update
Main page is can be accessible with my local coding, _description (it appears now)_, _author (it appears now but still confusing)_, _stats (it appears now)_

![Screenshot_2022-09-26-18-46-25-24_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/192268519-04876a2b-a315-4ba7-8163-a910369ea77a.jpg)

![Screenshot_2022-09-26-18-46-27-99_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/192268537-e6ccc666-1609-41c6-a3ee-f275eee10265.jpg)

![Screenshot_2022-09-28-16-36-59-98_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/192753670-3c69e8db-bc5f-40a2-8bbf-24e285d57af0.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AhriVastayan1** [comment]
Gua juga mikir gitu sih, pas doujindesu mt jam 11 malam, pas besok ny di tachi udh gk bisa dibuka, tapi di web view bisa

**Comment by TheKingTermux** [comment]
> Gua juga mikir gitu sih, pas doujindesu mt jam 11 malam, pas besok ny di tachi udh gk bisa dibuka, tapi di web view bisa 

Codenya berubah semua gan
Tinggal nunggu dibenerin

**Comment by Justanoobb** [comment]
Berarti ini extension nya kudu diupdate ya? Ato ini karena tampilan webnya belum 100%?

**Comment by TheKingTermux** [comment]
> extension nya kudu diupdate ya?
> Ato ini karena tampilan webnya belum 100%?

Mungkin bisa jadi karena web nya belum 100% fix

**Comment by Justanoobb** [comment]
Gabisa difix kah? Webnya kayaknya udah jadi.

**Comment by TheKingTermux** [comment]
> Gabisa difix kah? 

Kontributor Tachiyomi bisa ngerjain klo mereka mau
Jdi gaada tenggat
Intinya sabar aja buat updatenya

**Comment by Justanoobb** [comment]
Ok bang, makasih infonya
