### ISSUE TITLE
New version of the Mangadex extension after maintenance not working

### ISSUE THREAD

**Issue by saikafjk** [tachiyomiorg/tachiyomi-extensions#13453]
### Source information and language

Mangadex 1.3.167

### Steps to reproduce

1. Open Tachiyomi
2. Open Browse
3. Open MangaDex extension (Latest)

### Expected behavior

What should happen is you should see all the current manga available on MangaDex with the latest updates

### Actual behavior

What shows up is HTTP Error 503, and when opened in WebView, it shows the temporary maintenance page

![image](https://user-images.githubusercontent.com/15058079/189797082-003013fe-78d4-4a9b-ad7d-13372401e055.png)

### Tachiyomi version

0.13.6 (14/08/22 23:52)

### Android version

EMUI 10.1

### Other details

Please note that I have tried uninstalling and reinstalling the app and the extension, and the same error occurs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jasshira266** [comment]
There is no bug, what happens is that mangadex is in "internal" maintenance and according to has temporarily blocked tachiyomi to continue with what they have pending and that is the only measure they have so far, but as for the normal web outside tachiyomi, you can enter, is waiting for mangadex, as regards tachiyomi I think they have nothing to do but wait.
