### ISSUE TITLE
Esomanga HTTP error 400

### ISSUE THREAD

**Issue by Scorwx** [tachiyomiorg/tachiyomi-extensions#13459]
### Source information and language

Esomanga 1.3.24 (Turkish)

### Steps to reproduce

1.Browse Sources
2-Select Esomanga(Latest)

### Expected behavior

Manga list will be displayed

### Actual behavior

Manga list will didnt display and it says "HTTP error 400"

### Tachiyomi version

0.13.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Scorwx** [comment]
![20220913_222416](https://user-images.githubusercontent.com/102318206/189991573-68278e7d-c6cd-4b46-a694-8eeb1d4daa92.jpg)
Here is a screenshot

**Comment by kyoyacchi** [comment]
Dili de yazar mısın yanına "Turkish" diye.
