### ISSUE TITLE
mangadex: 1-api-call library update

### ISSUE THREAD

**Issue by sourcehutman** [tachiyomiorg/tachiyomi-extensions#13457]
### Source name and language

MangaDex (All)

### Describe your suggested feature

Hi!

Library updates make a number of API calls that scale linearly with the number of mangas to update. However, mangadex exposes an API to get the updates with one API call only:

https://api.mangadex.org/docs/swagger.html#/Feed/get-user-follows-manga-feed

Benefits of using this method instead of the current way:
- less traffic for low-bandwidth users
- less DDoS for MangaDex
- faster library updates

Cons:
- need to login

Benefit of implementing this instead of using [neko]:
- grouped updates with other extensions, instead of split between two apps
- subjective, but I prefer the tachiyomi UI

[neko]: https://tachiyomi.org/forks/Neko/

### Other details

Is there any previous work here on the github repos? Even unfinished, it'd be nice to read and be a better starting point.

I believe this is an important issue to solve, whether a big rewrite is needed or not. A tracking issue is better than nothing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
It doesn't seem doable.

- This endpoint only returns latest chapters of multiple manga instead of all chapters. It's impossible to do merge update in Tachiyomi currently because the extension knows nothing about the local chapters.
- The extension doesn't know when a batch update starts, so we can't trigger that API in a definite timing.
