### ISSUE TITLE
Comic-Walker

### ISSUE THREAD

**Issue by Alaharon123** [tachiyomiorg/tachiyomi-extensions#1346]
https://comic-walker.com/

Has lots of free comics. This has been requested before and there's a bunch of technical stuff at https://github.com/riderkick/FMD/issues/327 that may be of help but best I can tell that issue was closed and the site was never added

**Comment by as280093** [comment]
Here the icons
[comic-walker.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612695/comic-walker.zip)
