### ISSUE TITLE
Mangafreak search is disabled 

### ISSUE THREAD

**Issue by AbdallahAhmedHamda** [tachiyomiorg/tachiyomi-extensions#13472]
### Source information and language

Mangafreak 1.3.7 English

### Steps to reproduce

When i search or go into mangafreak it says failed to bypass cloudflare but it updates already existing manga correctly and when i open in webview only the search is bugged but when i open in my browser everything is fine

### Expected behavior

Manga should appear when i search

### Actual behavior

No kanga appears on search and failed to bypass cloud flare when i open the extension

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jbcbezerra** [comment]
same here

**Comment by artflphenix** [comment]
I am having the same issue. don't know if the webview is the issue that it cannot redirect properly to the search page results

**Comment by 808scotti** [comment]
Same here

**Comment by wdiasjunior** [comment]
Had the same issue.
Fixed it by changing the default user agent on Tachioyomi to the one below.
`Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.86 Mobile Safari/537.36`

**Comment by 808scotti** [comment]
> Had the same issue. Fixed it by changing the default user agent on Tachioyomi to the one below. `Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.86 Mobile Safari/537.36`

How odd.  I copied & pasted the user agent you provided, saved, and then restarted Tachiyomi, but no joy.  Thanks for sharing this though.

**Comment by wdiasjunior** [comment]
Try also cleaning cookies and WebView data.

**Comment by 808scotti** [comment]
> Try also cleaning cookies and WebView data.

Thanks, I hadn't thought of that. I did so and restarted Tachiyomi but still get the "Failed to bypass Cloudflare" error.

**Comment by wdiasjunior** [comment]
Have you tried opening the manga in WebView after making these changes?

**Comment by 808scotti** [comment]
I did just now, but it never gets past the "Entering Mangafreak..." page with the smiling graphic.

**Comment by dryx01** [comment]
The bug persists, even when we try to go on the webview to valid the captcha.
Any advances since then ?

**Comment by vetleledaal** [comment]
Open WebView, tap any manga and solve the Cloudflare captcha. The issue stems from the home page _not_ being behind Cloudflare's IUAM.

Otherwise check https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare
