### ISSUE TITLE
MangaKatana load 1 page a chapter

### ISSUE THREAD

**Issue by prhehns** [tachiyomiorg/tachiyomi-extensions#13486]
### Source information and language

MangaKatana 1.3.8

### Steps to reproduce

1 Open any titles from mangakatana
2 Open a chapter
3 It just load a page in a chapter

### Expected behavior

Load all pages of a chapter

### Actual behavior

It just load a page

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FoxXav** [comment]
Hi,

It's a new var name for the image table like some times ago. We can add it like like last time :
`...
private val imageArrayThzqRegex = Regex("""var thzq=\[([^\[]*)]""")
...
val imageArrayThzq = document.select("script:containsData(var thzq)").firstOrNull()?.data()
    ?.let { imageArrayThzqRegex.find(it)?.groupValues?.get(1) }
...
        val pagesThzq =
            imageArrayThzq?.let {
                imageUrlRegex.findAll(it).asIterable().mapIndexed { i, mr ->
                    Page(i, "", mr.groupValues[1])
                }
            } ?: emptyList()
        return if (pagesYtaw.size >= pagesHtnc.size) {
            if (pagesThzq.size >= pagesYtaw.size) {
                pagesThzq
            } else {
                pagesYtaw
            }
        } else {
            if (pagesThzq.size >= pagesHtnc.size) {
                pagesThzq
            } else {
                pagesHtnc
            }
        }
`

Or else perhaps we could firstly identify the image table to use by finding 
`obj.attr('data-src', thzq[i]);`
present near the definition of the image table. it could help even if new var are used but we must be sure that this declaration is always there.

**Comment by Kuroyuusha** [comment]
I am facing this same issue in mangakatana. Such as:Only 1 page opens

**Comment by Viva1HA** [comment]
Happens to me to, im on android 9
