### ISSUE TITLE
WNACG: change domain

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#13497]
### Source name and language

WNACG(Chinese)

### Describe your suggested feature

     the URL is currently unopenable in China,and domestic website has been updated.
     Please update the URL,or add the image URL that can be used in China.
     the new URL: "https://www.htcomic.top",
                        "https://www.htmanga.top",
                        "https://www.wnacg.top"
      
  
     
      
        

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Why are you closing and reopening this constantly? Just leave it open and wait for someone to add it.

**Comment by RX93CN** [comment]
&nbsp; &nbsp;The network I use has not been stable for some time now.This caused a delay in my operation when i try to close the issue.
&nbsp; &nbsp;I am sorry for my opertion ,i will reopen this issue soon



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 26, 2022 10:55 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [tachiyomiorg/tachiyomi-extensions] WNACG (Issue #13497)




 
Why are you closing and reopening this constantly? Just leave it open and wait for someone to add it.
