### ISSUE TITLE
Zahard: HTTP error 404

### ISSUE THREAD

**Issue by Dook42** [tachiyomiorg/tachiyomi-extensions#13491]
### Source information and language

Zahard English 1.2.7

### Steps to reproduce

Open extension in app

### Expected behavior

You should see a list of series you can follow to chapters 

### Actual behavior

404 error

### Tachiyomi version

Stable 0.13.6

### Android version

Android 8.1.0

### Other details

Site works in web view & browers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Mrjules00** [comment]
Issue extends to Zahard 1.3.6, Tachiyomi version 0.13.6
Android version 12
I
n Library Tab, Attempt to sync/update new manga chapters from zahard.xyz

Upon completion, Sync will fail and you will obtain an error that no chapters were found.

Mangas bookmarked from their source/extension are giving the error no "no chapters found", sync for new chapter updates are failing

Also, when you go to their source from the browse > source tab, the page for zahard says http error 404 but upon following the link "Open in Webview, the site is up and running
![Screenshot_20220917-165134_Tachiyomi](https://user-images.githubusercontent.com/105057821/190896584-1b142d2a-3643-4264-999e-38605992d00e.jpg)
![Screenshot_20220917-170300_HTML Viewer](https://user-images.githubusercontent.com/105057821/190896592-864c1e8c-a758-4963-b348-bde9adcb2902.jpg)

**Comment by asifx12** [comment]
Issue also present in Tachiyomi J2K 1.5.9, Zahard 1.2.7, Android 12

**Comment by Pilou26021** [comment]
They change the architecture of the website and the link that connect to the scan. So for now its not working.

**Comment by williamdif** [comment]
Any updates on this?

**Comment by Dook42** [comment]
So it's been nearly 5 months. Despite someone reporting that they were changing domains nothing has changed on the site in this time. The site itself still works, and the images within it have been pulling from the same place as far as I can tell. Hopefully this can be checked again soon

**Comment by scb261** [comment]
From #16027:
> Domain needs to be changed to zahard.xyz

@priyanshu-singhania the extension already uses zahard.xyz. Both .org and .xyz seems to be working in a browser. If you have any details you want to add - comment on this issue.

**Comment by priyanshu-singhania** [comment]
> From #16027:
> 
> > Domain needs to be changed to zahard.xyz
> 
> @priyanshu-singhania the extension already uses zahard.xyz. Both .org and .xyz seems to be working in a browser. If you have any details you want to add - comment on this issue.

That is the problem, the website is working but no content is fetched and it is showing HTTP Error 404 on browsing.

**Comment by priyanshu-singhania** [comment]
> > From #16027:
> > > Domain needs to be changed to zahard.xyz
> > 
> > 
> > @priyanshu-singhania the extension already uses zahard.xyz. Both .org and .xyz seems to be working in a browser. If you have any details you want to add - comment on this issue.
> 
> That is the problem, the website is working but no content is fetched and it is showing HTTP Error 404 on browsing. That means there is a problem with the extension as it is not showing any content.
As you can see below
![Screenshot_20230411_174136_TachiyomiSY](https://user-images.githubusercontent.com/44305006/231158742-7dfa266a-a491-469b-84e3-0b387cbe91d7.jpg)
![Screenshot_20230411_174140_TachiyomiSY](https://user-images.githubusercontent.com/44305006/231158761-20f82ea6-60d7-4551-b0f1-873e633696a2.jpg)

**Comment by garvongithub** [comment]
Experiencing the same in TachiyomiJ2K
version 1.6.4, Please update this :(

**Comment by HoodIronyEnjoyr** [comment]
Experiencing the same in Tachiyomi
version 14.6 and extension version 1.4.7 pls fix

**Comment by Jkd1st** [comment]
Any updates on Zahard it still down

**Comment by HoodIronyEnjoyr** [comment]
It updated to version 1.4.8 but it still shows error 404.
