### ISSUE TITLE
Hachimanga

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi-extensions#13503]
### Source name

Hachimanga 

### Source link

https://hachimanga.com/

### Language

Japanese - 日本語

### Other details

Source back after dead for 3 months, still have the hatachi manga extenstion and try both browse(popular), manual search,  and latest working fine, chapter list and manga page can be load and read too, website structure likely not change because extension working fine, so the last old code still work fine. Hope this source can back to Tachiyomi

PS : edited request due new Domain change

![Screenshot_20220918-104455973 (1)](https://user-images.githubusercontent.com/101858971/190883372-b97969f7-9a83-4412-8a1a-2473ba5a19e4.jpg)
![Screenshot_20220918-103355151](https://user-images.githubusercontent.com/101858971/190883378-59c48e1e-05b0-464e-a043-3d28803adcea.jpg)
![Screenshot_20220918-104428458](https://user-images.githubusercontent.com/101858971/190883381-65b516cb-df14-4740-9d4b-7e345fa4d9d9.jpg)
![Screenshot_20220918-103401487](https://user-images.githubusercontent.com/101858971/190883386-5c2f6432-6226-4271-89ac-3d9f48842250.jpg)
![Screenshot_20220918-103415668](https://user-images.githubusercontent.com/101858971/190883395-63d9e2da-7886-422d-977a-07b4ee344976.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
May I ask which Tachiyomi is that?

**Comment by DchanN** [comment]
> May I ask which Tachiyomi is that?

Main Tachiyomi Preview r4929

**Comment by Reykani** [comment]
seems the source link has changed to https://hachimanga.com/

should we close this to open new source request ?

**Comment by alessandrojean** [comment]
There's no need.

**Comment by DchanN** [comment]
> seems the source link has changed to https://hachimanga.com/
> 
> should we close this to open new source request ?

thanks for information, already edited the request
