### ISSUE TITLE
Mangabuddy updated problem

### ISSUE THREAD

**Issue by Rkyl3** [tachiyomiorg/tachiyomi-extensions#13502]
### Source information and language

Tachiyomij2k mangabuddy

### Steps to reproduce

Very slow updated and not all of them got to update and you rxpect me wait for an hours just for that

### Expected behavior

Its ok for it to be slow but not that slow to wait for an hour and it should updated all in my library

### Actual behavior

Its all lagging when i try to updated it all and slow as f*ckk 

### Tachiyomi version

Tachiyomij2k 1.5.9

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/190891567-ff64b960-f555-4ead-a8a6-fb2e1c8524ec.png)
