### ISSUE TITLE
Zero scans, new website design 

### ISSUE THREAD

**Issue by HNEnd** [tachiyomiorg/tachiyomi-extensions#13507]
### Source information and language

Zero Scans English 1.3.6.

### Steps to reproduce

If you have the extension installed.
- try to open it in > browse

### Expected behavior

Opens a list of manga's as any other extensions would.

### Actual behavior

App crashes.

### Tachiyomi version

Preview 0.13.6-4929 (standard, 0086743a5, 84, 2022-09-17T21:10Z)

### Android version

Android version: 12 (SDK 31)

### Other details

![Screenshot_2022-09-18-23-35-01-610_com android chrome](https://user-images.githubusercontent.com/74346601/190929095-76e6aee6-30bd-496d-b6ad-e9ec89dec169.jpg)
[tachiyomi_crash_logs (3).txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/9595295/tachiyomi_crash_logs.3.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Matakor** [comment]
Agreed, browse crashes, but for manga already favorited, it appears to still update properly. (Or at least a couple have for me)

**Comment by AntsyLich** [comment]
This is a bug with new app preview. MangaReader.to also crashes with similar error
