### ISSUE TITLE
Mangakakalot.is

### ISSUE THREAD

**Issue by ABooru** [tachiyomiorg/tachiyomi-extensions#13519]
### Source name

Mangakakalot.is

### Source link

https://www.mangakakalot.is/

### Language

English

### Other details

While called similar to Mangakakalot, I've noted that this one has many series being updated that are not on the other Mangakakalot or others sites, like World's End Harem: After World. I'm not sure if would be a good thing to add this one as a separate source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Same theme as in #12057

**Comment by ABooru** [comment]
> Same theme as in #12057

Yes, it does really seems to be the same, and I see there is already a mangareader.to extension, so, if mangareader is the original one, then I'll close this issue.

**Comment by arkon** [comment]
Could still be added.
