### ISSUE TITLE
Lateinit property title has not been initialized 

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#13512]
### Source information and language

Mangaraw 1.3.3

### Steps to reproduce

When opening a chapter or just viewing information about a manga this error pop up: "Lateinit property title has not been initialized "

### Expected behavior

Opening a manga in mangaraw source 

### Actual behavior

The manga opens but this error pops up:
Lateinit property title has not been initialized 

### Tachiyomi version

Latest

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Please provide app version, manga name and screenshot.

**Comment by sohilsayed** [comment]
![Screenshot_20220920-104836](https://user-images.githubusercontent.com/66560257/191212901-fdd89781-2e84-493f-96e2-b80b3105f9f4.png)
Here is a picture of the error manga name is ちょっとだけ抜けちゃう柊さん
It's the manga9co mirror in manga raw extension

**Comment by stevenyomi** [comment]
Still can't reproduce with the mentioned chapter. Could you provide the app crash logs and describe more? Did you add it to library before the extension updated to v1.3.3? Have you tried removing it and readd it by searching in the source?

**Comment by sohilsayed** [comment]
--------- beginning of main
09-20 18:17:47.078 22015 22015 E ResourceType: Style contains key with bad entry: 0x0101056d
09-20 18:17:47.078 22015 22015 E ResourceType: Style contains key with bad entry: 0x0101058c
09-20 18:17:47.078 22015 22015 E ResourceType: Style contains key with bad entry: 0x01010604
09-20 18:17:47.078 22015 22015 E ResourceType: Style contains key with bad entry: 0x01010605
09-20 18:17:47.079 22015 22015 E ResourceType: Style contains key with bad entry: 0x0101056d
09-20 18:17:47.079 22015 22015 E ResourceType: Style contains key with bad entry: 0x0101058c
09-20 18:17:47.079 22015 22015 E ResourceType: Style contains key with bad entry: 0x01010604
09-20 18:17:47.079 22015 22015 E ResourceType: Style contains key with bad entry: 0x01010605
09-20 18:17:47.110 22015 22015 E ResourceType: Style contains key with bad entry: 0x0101056d
09-20 18:17:47.110 22015 22015 E ResourceType: Style contains key with bad entry: 0x0101058c
09-20 18:17:47.110 22015 22015 E ResourceType: Style contains key with bad entry: 0x01010604
09-20 18:17:47.110 22015 22015 E ResourceType: Style contains key with bad entry: 0x01010605
App version: 0.13.6-4929 (standard, 0086743a5, 84, 2022-09-17T21:10Z)
Android version: 8.0.0 (SDK 26)
Android build ID: 48.1.A.2.109
Device brand: Sony
Device manufacturer: Sony
Device name: G3212
Device model: G3212
Device product name: G3212

This problem happens when opening any manga in the latest tab and even after reinstalling the extension nothing changes

**Comment by stevenyomi** [comment]
Reproduced on latest preview but not on latest stable. It's probably an issue with the app.
