### ISSUE TITLE
Earlymanga source needs update.

### ISSUE THREAD

**Issue by Zicc0** [tachiyomiorg/tachiyomi-extensions#13517]
### Source information and language

Earlymanga 1.3.19 English

### Steps to reproduce

Open extension in app

### Expected behavior

Should show manga and stuff

### Actual behavior

Shows nothing

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Website updated recently so it broke the extension in app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
There is an update on the extension, everything working fine.
