### ISSUE TITLE
Readcomiconline

### ISSUE THREAD

**Issue by blackbowman** [tachiyomiorg/tachiyomi-extensions#13528]
### Source name

Readcomiconline

### Source link

https://readcomiconline.li/

### Language

English 

### Other details

This is definitely the best 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by blackbowman** [comment]
It's not the same as what is already there, this one is even better

**Comment by AntsyLich** [comment]
The extension is matched by the url you provided. You probably added space in the name so it showed the other one

**Comment by alessandrojean** [comment]
It already exists as the bot replied.

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/50221eb16f45ec948962fb1a55fa5ed7ba311210/src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt#L39
