### ISSUE TITLE
Asura scans library refresh issue

### ISSUE THREAD

**Issue by Star-slayer41215** [tachiyomiorg/tachiyomi-extensions#13525]
### Source information and language

Asura scans 1.3.37

### Steps to reproduce

1) refresh library
2) library update error shows only titles which use Asura scans as "update(s) failed"

### Expected behavior

New chapter updated for Asura scans

### Actual behavior

After refreshing library only tiles which use the Asura scans source fail to update 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

This issue has presisted for multiple tachiyomi app and Asura scans source updates for the past few months

This is the fail log:- 

For help on how to fix library update errors, see https://tachiyomi.org/help/guides/troubleshooting

! Too many follow-up requests: 21
  # Asura Scans (EN)
    - Reincarnation of the Suicidal Battle God
    - Return of the Disaster-Class Hero

! No chapters found
  # Asura Scans (EN)
    - Solo Max-Level Newbie

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hindraxxx** [comment]
try to goes to your series, click migrate and re-migrate it to asura and it will solve the issue.

This issue has been happening multiple times and right now the only solution is this, as tachiyomi did not provide you with multiple migrate (there's a coupling in their apps that cause them difficulty to implement this) and i don't even know whether you can fix this by waiting extension update released by Tachiyomi

**Comment by Star-slayer41215** [comment]
Today when i refreshed the Library the 3 series were updated with the missing chapters and no failure notifications, maybe the Dev's saw the bug and fixed it anyways thanks hindraxxx for trying to help
