### ISSUE TITLE
Please implements booktoki extension from newtoki

### ISSUE THREAD

**Issue by chongjae** [tachiyomiorg/tachiyomi-extensions#13535]
### Source name and language

newtoki(ko)

### Describe your suggested feature

마나토끼 / 뉴토끼 정말 잘 쓰고 있습니다.
이번에 북토끼 사이트가 신설되었는데, 혹시 구현 가능하신 분 있는 지 궁금합니다.

Manatoki/ Newtoki is using it really well.
The Book Rabbit site was newly established, and I wonder if anyone can implement it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
That's a novel site. Tachiyomi is NOT a novel reader.
