### ISSUE TITLE
BoyLove (Chinese) cloudflare bypass issue

### ISSUE THREAD

**Issue by rebeccafeng1995** [tachiyomiorg/tachiyomi-extensions#13530]
### Source information and language

BoyLove 1.3.4 (Chinese)

### Steps to reproduce

Source HTTP error 503

### Expected behavior

Normal loading manga and search page

### Actual behavior

Continue to get stuck on cloudflare check, clikcing on the extension to search shows error 503, in chrome the website works fine

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by rebeccafeng1995** [comment]
Okay, have tried both solutions in troubleshoot already and neither works. I guess the only solution is to wait for it to return to normal then?
