### ISSUE TITLE
A new update or a new resource for MangaWT.

### ISSUE THREAD

**Issue by MelasculaSins** [tachiyomiorg/tachiyomi-extensions#13539]
### Source name

MangaWT

### Source link

https://mangawt.com/

### Language

Turkish

### Other details

Old theme: Madara

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You should fill the [issue report form](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new?assignees=&labels=Bug&template=report_issue.yml) instead, this one isn't the right one as it's intended to request new sources to be added.
