### ISSUE TITLE
I request all Tachiyomi devs to add ReadComicOnline back into Tachiyomi

### ISSUE THREAD

**Issue by Welding-Torch** [tachiyomiorg/tachiyomi-extensions#13547]
### Source name

ReadComicOnline

### Source link

https://readcomiconline.li

### Language

English

### Other details

So, the ReadComicOnline extension has been not functioning, and it has been ignored by developers over many, many months. I would like to make a sincere request to ALL devs to PLEASE focus on making this extension work again. It is a very popular website, with an AMAZINGLY large database of Comic Books and Manga. It is fast and prompt in it's service, and I have been a reader of it for over a decade. It used to be my go to source to read comic books always, on PC or on my phone, until I discovered that I could access it through Tachiyomi. Then the very way I read comic books changed, and I felt like this was finally a modern way to enjoy the medium on smartphones and tablets. 

However, since the devs stopped supporting the extension due to a "cat-and-mouse chase", so many people have been unable to access the comics from this site. I URGE the devs to STRONGLY reconsider this. I understand that you may be frustrated with maintaining this extension. But please also try to understand that there are many, many people who use this extension daily. I know I used it daily, and it brought a lot of **joy** to my life. I bet there are many others who have had the same experience. 

It is a sincere request: If any devs can make this extension work again, please do so. 

Thank you ❤️ 

---
@alessandrojean 
Thread where dev stopped supporting --> https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11407

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Seems to work fine for me, if you're running into an issue, make a bug report instead.
