### ISSUE TITLE
Komik Cast Cloudflare Block

### ISSUE THREAD

**Issue by harphobia** [tachiyomiorg/tachiyomi-extensions#13549]
### Source information and language

Komik Cast 1.3.36 (Indonesia)

### Steps to reproduce

Just open the extension page.

### Expected behavior

After open extemsion page. manga list show.

### Actual behavior

After open extemsion page. "Failed to bypass Cloudflare" notification show.

### Tachiyomi version

1.5.9 Tachiyomi J2K

### Android version

Android 10

### Other details

this case just like nHentai extension ago. failed to bypass cloudlare.
but in this case. can't use trick open via browser and back to app again.
![alt text](https://cdn.discordapp.com/attachments/988876574612922428/1022505943046565969/Screenshot_2022-09-22-20-52-31-695_eu.kanade.tachiyomi.j2k.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
