### ISSUE TITLE
False chapter release full of ads

### ISSUE THREAD

**Issue by kassuhei** [tachiyomiorg/tachiyomi-extensions#13548]
### Source information and language

Mangahere 1.3.19

### Steps to reproduce

False chapter full of only ads
Apotheosis ch.975

### Expected behavior

False chapter full of only ads
Apotheosis ch.975

### Actual behavior

False chapter full of only ads
Apotheosis ch.975

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

False chapter full of only ads
Apotheosis ch.975

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
what ad are you seeing? from a quick glance, they themselves uploaded a release that was fake from ultmanga for apotheosis ch 975

**Comment by kassuhei** [comment]
Ye that chapter exactly, i dont know if i should flag those chapters here or let them be since theyre fake chapters as you said. 
Ive seen those kinds before so i thought id ask if i come by them again

**Comment by Seishirou101** [comment]
you would report them on their website, we only display what they show.
