### ISSUE TITLE
Reaper Scans: Changed their theme to a custom one

### ISSUE THREAD

**Issue by MicOliv** [tachiyomiorg/tachiyomi-extensions#13556]
### Source information and language

Reaper Scans 1.3.30 (Português Brasil)

### Steps to reproduce

click on the extension

### Expected behavior

it was supposed to work normally

### Actual behavior

this error 404 appears

### Tachiyomi version

TachiyomiJ2K 1.5.9

### Android version

Android 11

### Other details

the site apparently updated recently and I don't know if it hasn't updated on Tachiyomi yet but I'm reporting it here, the English version of the extension is working normally so I thought I should do that, and I saw that the 404 error only appears when the site or manga goes down, but as I saw that I was not down I made this report

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MicOliv** [comment]
thanks for all the work, i appreciate it very much! @alessandrojean

**Comment by Guto312** [comment]
O que é "RS"?

**Comment by MicOliv** [comment]
@alessandrojean the portuguese version no longer appears, is it a bug or is it just like that?

**Comment by MicOliv** [comment]
ah sorry, I had not seen that there is a separate version only in Portuguese, thank you very much for your work!

**Comment by MicOliv** [comment]
the genres are back but now the descriptions don't appear 😂 sorry for causing so much work, I don't even know half of how much work it must be

**Comment by alessandrojean** [comment]
Please next time open new issues to report new bugs instead of commenting on an older and already closed one.
