### ISSUE TITLE
Newtoki (KOR)

### ISSUE THREAD

**Issue by mazyuin** [tachiyomiorg/tachiyomi-extensions#13557]
### Source information and language

Newtoki/Manatoki 1.3.24

### Steps to reproduce

I found 2 bugs as of now
The first:
1. Open Newtoki by the Browse>Source
2. Tap on any series
3. Tap webview and clear the captcha verification if possible
4. Go back to the series page
The second : 
1- Tap the Newtoki/Manatoki by the Browse/Extension
2- Tap the setting of Newtoki

### Expected behavior

The first : can view the page with all the chapter list
The second: can edit the url base of Newtoki

### Actual behavior

The first : you got the java.string error
The second: can't change it and instead tachiyomi got force closed

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

![IMG_20220924_103624](https://user-images.githubusercontent.com/89907961/192078572-d8c0c317-60d3-465c-bb35-b15464a43c34.jpg)
For the second issue, you can open Manatoki setting without any force close AND i can't get anything from dumping the crash log other than my device information
I tried uninstalling the extension but nothing works

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Working on a fix.
