### ISSUE TITLE
Gremory Mangas

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#13563]
### Source name

Gremory Mangas

### Source link

 https://gremorymangas.com/

### Language

Español

### Other details

This page is very complete, more than many that are already in the app, honestly, it would be great if they added it :)
![Screenshot_20220924-073133_Opera](https://user-images.githubusercontent.com/101371218/192100850-e310eae5-42ea-4771-ae50-5f96a466020a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
