### ISSUE TITLE
 Problem marking chapters

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#13564]
### Source information and language

Senpai Ediciones 1.3.21 (Español) TuMangaOnline 1.3.39 (Español)

### Steps to reproduce

Open a chapter
Try dialing it from the reader

### Expected behavior

It should be marked with no problem

### Actual behavior

The app freezes for a few seconds

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

![Screenshot_20220924-082458_Tachiyomi](https://user-images.githubusercontent.com/101371218/192103599-3019970c-caa0-4810-9437-0489b13e9ebf.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
What sort of "marking" are you talking about?

Bookmarking or Marking as read?

**Comment by edmxn** [comment]
> What sort of "marking" are you talking about?
> 
> Bookmarking or Marking as read?

Mark the chapter as favorite, in the image u can see what I was referring to

**Comment by alessandrojean** [comment]
Since the extensions don't handle bookmarking chapter in their codes, I am closing this. Please report in the app repository.
