### ISSUE TITLE
Mangadex: No chapters in pornographic Doujinshi anymore

### ISSUE THREAD

**Issue by ArkfrostLumas** [tachiyomiorg/tachiyomi-extensions#13561]
### Source information and language

Mangadex 1.3.167

### Steps to reproduce

Whenever I search for any specific theme (e.g. Magic, or Demons) in the content rating pornographic section, it shows all the available doujinshi, but when I tap on them they always have 0 chapters available.
When I tap on WebView however there are always all the chapters available.

What I found out is that you must create and log into an account on Mangadex to make the checkbox to display pornographic content appear in the display settings.

However since I cannot log in to my Mangadex Account within Tachiyomi it always uses the default user options to display content, so most pornographic content gets automatically filtered out and therefore isn't shown in the app.

Interestingly, older doujinshi I added to my library before Mangadex had those 2ish weeks outage recently still work just fine.

### Expected behavior

I should be able to tap on any doujinshi and see the available chapters, since all languages are toggled on by default.
Alternatively I should be able to somehow log in to my mangadex account so it can pull the display settings from there. 

### Actual behavior

As explained before, chapters aren't displayed when I filter by content reading pornographix, and by a specific theme. 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mazyuin** [comment]
I don't get this bug. I can find, view, and open all the available chapters by using content filter p@rn and one theme

**Comment by alessandrojean** [comment]
Can you provide some titles as an example where this behaviour occurs?

**Comment by ArkfrostLumas** [comment]
Ugh... I found the mistake, and like always it was a was error:

For some reason the German version of the Mangadex Source Extension has moved up in my Sources list and that version only finds chapters in German, while excluding all other chapters in other languages.

Removed the German only version and now it's working.
