### ISSUE TITLE
Fusion Scanlation: No results found

### ISSUE THREAD

**Issue by Myztery97** [tachiyomiorg/tachiyomi-extensions#13570]
### Source information and language

Fusion Scanlation (Spanish)

### Steps to reproduce

Good day, Fusion Scanlation is down but the webview still works, I will thank you is repair the isue.

### Expected behavior

It should show the series.

### Actual behavior

Show it the error "No se han encontrado resultados"

### Tachiyomi version

0.13.6

### Android version

12

### Other details

Manwha.men (English) is down too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Theme was changed from MangaThemesia to Madara
