### ISSUE TITLE
Hentai Scantrad

### ISSUE THREAD

**Issue by Snakegreen020** [tachiyomiorg/tachiyomi-extensions#13584]
### Source name

Hentai Scantrad

### Source link

https://hentai.scantrad-vf.cc/

### Language

French

### Other details

https://hentai.scantrad-vf.cc/manga/les-amis-secrets/
https://hentai.scantrad-vf.cc/manga/infidele/

Yes +18 site

Thank you for adding this new site and I love your work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by WoodlyBasquin56** [comment]
> ### Source name
> Hentai Scantrad
> 
> ### Source link
> https://hentai.scantrad-vf.cc/
> 
> ### Language
> French
> 
> ### Other details
> https://hentai.scantrad-vf.cc/manga/les-amis-secrets/ https://hentai.scantrad-vf.cc/manga/infidele/
> 
> Yes +18 site
> 
> Thank you for adding this new site and I love your work
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a title with source name.
> * [x]  I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
> * [x]  I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
> * [x]  I will fill out all of the requested information in this form.

**Comment by Kreliam** [comment]
@KirinRaikage Madara

**Comment by KirinRaikage** [comment]
@Kreliam t'es bouillant ! A deux doigts de pouvoir implémenter des extensions toi même 😁

**Comment by Kreliam** [comment]
> @Kreliam t'es bouillant ! A deux doigts de pouvoir implémenter des extensions toi même 😁

Hahah je commence à apprendre le html pour faire du web scrapping 😁

**Comment by KirinRaikage** [comment]
Les selectors CSS en plus et puis c'est bon t'es rodé !

**Comment by Kreliam** [comment]
> Les selectors CSS en plus et puis c'est bon t'es rodé ! 

Pas besoin d'apprendre le php ?

**Comment by KirinRaikage** [comment]
Nan si tu veux juste dev Android le PHP ça sert à rien dans ce cas là

**Comment by Kreliam** [comment]
> Nan si tu veux juste dev Android le PHP ça sert à rien dans ce cas là 

Même pour le web scraping le php ça peut dépanner 🤣 ?

**Comment by KirinRaikage** [comment]
Oui fin si tu fais juste du Web scraping pour faire du Web scraping faut que ça ait une finalité donc soit faire un site Web avec ta partie front et ta partie back en PHP soit je sais pas faire des projets en Python, Kotlin ou autre
CSS, JS, et Kotlin (et Gît) t'as une bonne base pour implémenter des extensions sur Tachi par exemple, t'as pas besoin de PHP en plus de ça

**Comment by Kreliam** [comment]
> Oui fin si tu fais juste du Web scraping pour faire du Web scraping faut que ça ait une finalité donc soit faire un site Web avec ta partie front et ta partie back en PHP soit je sais pas faire des projets en Python, Kotlin ou autre. 
> 
> CSS, JS, et Kotlin (et Gît) t'as une bonne base pour implémenter des extensions sur Tachi par exemple, t'as pas besoin de PHP en plus de ça 

D'accord ça reste un complément mais pas urgent dans ce projet

**Comment by Kreliam** [comment]
@Snakegreen020
