### ISSUE TITLE
Mangaplus: Easy access to local chapters not available online anymore?

### ISSUE THREAD

**Issue by Clydefrosch22** [tachiyomiorg/tachiyomi-extensions#13592]
### Source name and language

Manga Plus by Shueisha

### Describe your suggested feature

So ocassionally i put an interesting manga in the mangaplus extension on follow with every intention to come back and read it regularily, and then I don't.

Eventually, older chapters get removed from mangaplus and they disappear from the list of chapters in the library, even though they're still on local storage.
After reading the first few chapters that are always available, continuing on the next chapter becomes cumbersome, either needing to start in an earlier chapter and skipping ahead or using history (which becomes hard when you read a lot of things and history grows large).

Preferably, it would be cool if chapters could be populated based on whats present in local storage.

If it's not possible to keep chapters in the list because it's populated by data on manga plus servers, any other way to quickly access and select a local chapter to continue reading from a certain manga (maybe via the ... menu?) would be appreciated

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you are shown what is on the website, if you want to read those chapters, you can move them to local but you can't be shown what is not on available to you on the webbsite.
