### ISSUE TITLE
Pikiran Wibu

### ISSUE THREAD

**Issue by VendingMp** [tachiyomiorg/tachiyomi-extensions#13596]
### Source name

Pikiran Wibu

### Source link

https://pikiran-wibu.com

### Language

Indonesian

### Other details

hope you make this extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by MeLoseAgain** [comment]
I hope more with this website it has a lot of manga and doesn't have a lot of ads it's good and I see this is not responding for a month

**Comment by MeLoseAgain** [comment]
@Riztard can you add?
