### ISSUE TITLE
Vyvymanga: Some chapters marking themselves as unread

### ISSUE THREAD

**Issue by manuqp** [tachiyomiorg/tachiyomi-extensions#13603]
### Source information and language

Vyvymanga v1.3.1 (English)

### Steps to reproduce

1. Mark chapter as read
2. Update the manga 

### Expected behavior

New chapters should appear

### Actual behavior

All extras like notices, updates and ads appear again as not read in a lot of mangas (see attached video for better explanation)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

This used to happen in another extensions like old mangaowl so it should be fixable. Thanks!

https://user-images.githubusercontent.com/48988022/192483225-b6d108fd-903d-40e4-8b20-6be58d0a3705.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This happens whenever the chapter URL updates, except for chapters with a chapter number. The solution for MangaOwl relied on an easily predictable chapter URL, so that's not really usable here as VyvyManga appears to be encrypt the URLs.

Not sure how one would work around this without additional network calls.
