### ISSUE TITLE
Aqua Manga: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Atlanticboy** [tachiyomiorg/tachiyomi-extensions#13602]
### Source information and language

Aqua Manga 1.3.25

### Steps to reproduce

When opening any chapters in a manga from Aqua Manga extension the chapter starts to load but after some time it suddenly stops and shows tet failed to bypass cloudflare.

### Expected behavior

the chapters should open after loading

### Actual behavior

When opening any chapters in a manga from Aqua Manga extension the chapter starts to load but after some time it suddenly stops and shows tet failed to bypass cloudflare. Becase of this can't even download chapters. But in WebView the chapters are opening correctly.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Priyanshu263** [comment]
Same problem, please fix it as soon as possible.

**Comment by Atlanticboy** [comment]
Can this be resolved or will we have to migrate the mangas? Nowadays, many tachiyomi sites are having same problem like reaperscans.

**Comment by Megalodon0501** [comment]
> Can this be resolved or will we have to migrate the mangas? Nowadays, many tachiyomi sites are having same problem like reaperscans.

Yeah same.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. **If it doesn't work, migrate to other sources or wait until they lower their protection.**

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
