### ISSUE TITLE
KomikIndoID: HTTP error 404

### ISSUE THREAD

**Issue by mranggaaditya** [tachiyomiorg/tachiyomi-extensions#13604]
### Source information and language

KomikIndoID

### Steps to reproduce

1. When i open KomikIndoID extensions i got error like this "HTTP error 404: Check website in WebView"
![image](https://user-images.githubusercontent.com/72933615/192498888-0a41608f-f5d0-4c70-b3db-f087e0737364.png)
2. Next i get in to the webview and not find any trouble in webview
![image](https://user-images.githubusercontent.com/72933615/192499302-9dc1aabc-5121-4c2b-99cf-26d1c68d6e33.png)
3. When i back to the KomikIndoID extensions its still HTTP error 404: Check website in WebView
![image](https://user-images.githubusercontent.com/72933615/192499378-e21fd5cd-75a1-4a36-bde5-87d6020e3287.png)

### Expected behavior

should like this
![image](https://user-images.githubusercontent.com/72933615/192500030-b73244ab-0e0b-413a-8df4-7f6574a4977d.png)

### Actual behavior

i don't know why this problem happen, but.. i hope tachiyomi fix this soon
Thankyou ^^

### Tachiyomi version

0.13.6

### Android version

Android 8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RaidBuster** [comment]
I'm having the same problem too.
