### ISSUE TITLE
Mcreader: lower thumbnail quality while browsing

### ISSUE THREAD

**Issue by HeroSharma** [tachiyomiorg/tachiyomi-extensions#13608]
### Source information and language

mcreader.net 1.3.15(English)

### Steps to reproduce

1.When i browse Mcreader.net extension i get lower quality manga covers.
2. When i open manga it loads different cover which have higher quality.
3. Issue here is manga information takes too long to load because of cover loads after i open manga.

### Expected behavior

It should have only 1 type of manga cover which loads while browsing extension.

### Actual behavior

Mcreader have 2 different Manga covers
If browse extension covers comes at a lower quality but if you open manga, cover reload into a high quality one(which also causes manga information load slower)

### Tachiyomi version

0.13.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
i think the slowness comes from the chapter loading from another url, causing it to do another call/request

**Comment by HeroSharma** [comment]
> i think the slowness comes from the chapter loading from another url, causing it to do another call/request

I guess so, maybe because sites changed their url 3 times
Extension gets basic update which simply change site url while scrapping manga code doesn't get updated
