### ISSUE TITLE
YaoiMangaOnline: No Pages Found

### ISSUE THREAD

**Issue by Yazhkx** [tachiyomiorg/tachiyomi-extensions#13609]
### Source information and language

Yaoi Manga Online 1.2.2

### Steps to reproduce

Open app > Browse > Yaoi Manga Online > Select Title > Select Chapter

### Expected behavior

Shows the list of chapters

### Actual behavior

Deletes chapter list and shows 'no pages found' error

### Tachiyomi version

0.13.6

### Android version

EMUI 12

### Other details

Please fix this extension, this source has more titles available compared to others.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closed in favor of #14982
