### ISSUE TITLE
HentaiVN: Changed their domain

### ISSUE THREAD

**Issue by tktmgn20** [tachiyomiorg/tachiyomi-extensions#13619]
### Source information and language

HentaiVN 2.8.1 Vietnamese

### Steps to reproduce

change domain to (  hentaivn.la ) thx

### Expected behavior

change domain to (  hentaivn.la ) thx

### Actual behavior

change domain to (  hentaivn.la ) thx

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

change domain to (  hentaivn.la ) thx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have updated all installed extensions.

Your extension is out of date. hentaivn already points to https://hentaivn.la
