### ISSUE TITLE
NoxSubs: Extension can be removed

### ISSUE THREAD

**Issue by kyoyacchi** [tachiyomiorg/tachiyomi-extensions#13634]
### Source information and language

NoxSubs 1.3.21 (Turkish)

### Steps to reproduce

1. Try to use noxsubs extension.

### Expected behavior

It should work

### Actual behavior

It's down.
![Screenshot_20220929-235206](https://user-images.githubusercontent.com/63583961/193139979-e7a6a99d-e9cd-4620-9ce7-618111c2b811.jpg)

### Tachiyomi version

1.5.9

### Android version

Android 11

### Other details

This one is down too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
@alessandrojean can you edit tags of this one too?

**Comment by AntsyLich** [comment]
According to their twitter last update was a year ago. And they have sold all their translated chapters to another group
