### ISSUE TITLE
Reaper Scans manhwas not updating

### ISSUE THREAD

**Issue by vicrodri** [tachiyomiorg/tachiyomi-extensions#13639]
### Source information and language

Reaperscans 1.3.31

### Steps to reproduce

both global update and individual manhwa updates don't work. Comics stuck on latest entries.

Example: on site "The great mage returns after 4000 years" goes by chapter 144 and in app still gets chapter 143.

### Expected behavior

Update chapter list

### Actual behavior

chapter list not updated

### Tachiyomi version

Stable 0.13.6

### Android version

Android 9

### Other details

Reaper scans site has weird cache issues

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dook42** [comment]
They preformed server maintenance after which most URLs were changed & extension gives a 404 error. Site now works in webview & browsers.

**Comment by ChillyCrimson45** [comment]
the extension only needs update in order to work

**Comment by arkon** [comment]
#13735
