### ISSUE TITLE
MangaPark v3: Unable to bypass Cloudflare Challenge through WebView

### ISSUE THREAD

**Issue by atmazzerexe** [tachiyomiorg/tachiyomi-extensions#13655]
### Source information and language

MangaPark v3 1.3.18

### Steps to reproduce

1. Go to WebView of any MangaPark V3 entry
2. Try to solve the hCaptcha/click "Verify that you are human" button/click the Cloudflare button

### Expected behavior

Captcha challenge solved and I can open MangaPark properly again.

### Actual behavior

Cloudflare will return to hCaptcha request or Cloudflare will show a quick message of "Failure" after clicking the button and goes back to the Cloudflare button challenge(s).

### Tachiyomi version

r4977

### Android version

Android 11 (AOSP)

### Other details

Clearing cache, cookies, and changing Tachiyomi's User Agent doesn't help.
I have tried to open their link through Firefox and Chrome from both of my PC and Android using the exact IP address from my VPN and was able to solve the challenge and open the link. Android System WebView also works.
Using 1.1.1.1 does allow me to just open it normally through Tachiyomi WebView as it won't ask for challenge, but I prefer to use my own VPN.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
![Screenshot_20220930-203005](https://user-images.githubusercontent.com/63583961/193324923-aa0dd9a4-26cc-4a11-a029-cec89b82715b.jpg)
No problem for me..

Can you try to use ```Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0``` user agent, just like how i use it.

**Comment by atmazzerexe** [comment]
> Can you try to use `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0` user agent, just like how i use it.

I have tried Chrome, Firefox, and Safari user agent before this and none of them are working.

![Screenshot_20221001-011439_Tachiyomi](https://user-images.githubusercontent.com/14852623/193333340-5fe6e136-6d74-48f3-b8e8-86b531bb3f1a.png)

Here's the video of how it went.

https://user-images.githubusercontent.com/14852623/193333622-108bc95e-0635-42d2-b986-3e2aa7fd9b45.mp4

**Comment by alessandrojean** [comment]
Cloudflare also fingerprints each of your devices and browsers, so just using the same IP in other devices and being able to bypass there doesn't necessarily imply it will bypass on Tachiyomi's WebView. Since you're using a VPN and it does work without it, it could also mean your VPN IP + device + browser (Tachi WebView) got flagged by Cloudflare.

If changing the UA and following other procedures listed on the website haven't work, nothing more you can do. You can wait for them to lower their protection, migrate to other sources, or don't use a VPN (since you said it's working without it).

Closing as there's really nothing that can be done about it.
