### ISSUE TITLE
Maid scan

### ISSUE THREAD

**Issue by Chellyph14** [tachiyomiorg/tachiyomi-extensions#13657]
### Source name

Maid scan

### Source link

https://miauscan.com/genres/maid-scan/

### Language

Português

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I will leave this one open as there's Portuguese content showing up on the Spanish extension. Ideally the extension should be made into an `all` lang with both.
