### ISSUE TITLE
webtoons.com downloaded chapter don't show anymore after becoming daily pass

### ISSUE THREAD

**Issue by blaxcky** [tachiyomiorg/tachiyomi-extensions#13650]
### Source information and language

webtoons.com

### Steps to reproduce

1. Download all chapters of a webtoon 
2. Webtoon becomes daily pass and only some of the first chapters are free anymore
3. Tachiyomi shows only the chapters that are now free

### Expected behavior

Tachiyomi should also show the downloaded chapters. It doesn't make sense to have all the chapter downloaded but only show the ones that are available on the web.

### Actual behavior

Tachiyomi only shows the few chapters that are free now.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is similar to the behaviour present in the MANGA Plus extension.

You can use the [local source](https://tachiyomi.org/help/guides/local-manga/) to read these orphaned downloads.

Also the extension doesn't have access to what's already downloaded and what's not, so it's more an app issue, although there are no plans to show previously downloaded existent chapters in the chapter list.
