### ISSUE TITLE
Image Resolution and format issue for Bilibili Comics Extension

### ISSUE THREAD

**Issue by saminwas** [tachiyomiorg/tachiyomi-extensions#13664]
### Source information and language

BILIBILI COMICS v1.3.7 (English)

### Steps to reproduce

1. Provide an option to download the images as .webp.
2. Download original Image instead of sd quality image.
3. Further Explained down below.

### Expected behavior

The original image has a resolution of 2400 x 6168 and is .webp format. The image was downloaded using hakuneko v6.17.

![Downloaded Using Hakuneko - Not Upscaled](https://user-images.githubusercontent.com/111482404/193392339-14925862-6cf6-4f88-8814-ac8e8a3cab89.jpg)

### Actual behavior

The same image downloaded using tachiyomi has a resolution of 1200 x 3084.

![Downloaded Using Tachiyomi](https://user-images.githubusercontent.com/111482404/193392322-d2de34b7-486c-4e67-bc59-5ea8f65cf150.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

- **The image format for every image in bilibili is webp regardless of raw, hd, sd.**
- **A option to download the image in .webp format would be preferred.**

I uploaded .jpg images as .webp is not supported by github. The original .webp images can be found in the .zip file below.

[Example Images.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/9689532/Example.Images.zip)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
The options are already available in the extension settings.
