### ISSUE TITLE
Nhentai.net: Option to change default sort

### ISSUE THREAD

**Issue by Fmoment1** [tachiyomiorg/tachiyomi-extensions#13680]
### Source name and language

Nhentai (English / ALL)

### Describe your suggested feature

If we search for something using this extension, be it a name, tag or category, the results are always sorted by "most popular" by default. If we want to view the recent postings or only the most popular of the week, we have to open the filter menu and scroll down to change it every time we open the extension.

Could there be an option in the extension settings to **always** use a specific sort when searching on this extension? As in, if I set the default sort as "recent", search results in the extension will **always** be sorted by recently posted entries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by breaking-loss** [comment]
Do you like the new layout of nhentai ?
