### ISSUE TITLE
Komikindo.ID: HTTP error 404

### ISSUE THREAD

**Issue by Rezzxaek** [tachiyomiorg/tachiyomi-extensions#13687]
### Source information and language

Komikindo.id 1.3.5

### Steps to reproduce

1. Komikindo.ID extension can be opened without any problems
![Screenshot_2022-10-02-17-03-48-094_eu kanade tachiyomi](https://user-images.githubusercontent.com/114849865/193448852-cb84ef89-04e6-4096-b1ac-5b6852ff5637.jpg)
2.Then i want to search manga 
![Screenshot_2022-10-02-17-09-39-382_eu kanade tachiyomi](https://user-images.githubusercontent.com/114849865/193448975-aeeb7d32-b2a5-418a-9bcd-0b62095bd783.jpg)
3.  After search I get HTTP error 404
![Screenshot_2022-10-02-17-04-20-438_eu kanade tachiyomi](https://user-images.githubusercontent.com/114849865/193449353-208327e7-03b3-4d3d-930a-63c23bd603d6.jpg)

### Expected behavior

This should happen after i search 
![Screenshot_2022-10-02-17-25-08-986_eu kanade tachiyomi](https://user-images.githubusercontent.com/114849865/193449519-1989fa88-ba7d-4cd8-8930-d600c328bf52.jpg)

### Actual behavior

When i search this happen instead
![Screenshot_2022-10-02-17-04-20-438_eu kanade tachiyomi](https://user-images.githubusercontent.com/114849865/193449404-368d683c-66b5-4044-b343-98785484898d.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

I hope tachiyomi fix this soon 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
I confirmed it

**Comment by Riztard** [comment]
tachi is using this search
![image](https://user-images.githubusercontent.com/16263232/193556490-89e93e6f-8c8c-4c14-989b-d45fae0907e9.png)

**Comment by Rezzxaek** [comment]
Already fixed thankyou
