### ISSUE TITLE
Komga: The request was rejected because the URL contained a potentially malicious String "//"

### ISSUE THREAD

**Issue by jdenm8** [tachiyomiorg/tachiyomi-extensions#13682]
### Source information and language

Komga 1.3.42

### Steps to reproduce

1. Configure Komga source with a "/" on the end, 
    Example: http://{IP address}:{port}/
2. Attempt to view source

### Expected behavior

Tachiyomi should connect to Komga and return available books in the library

### Actual behavior

In Tachiyomi: 
HTML 500 Error

On Server: 
As part of a larger stack dump, the following exception is printed to Komga container terminal (and the Komga log):
`ERROR 1 --- [http-nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"`

### Tachiyomi version

Preview r4977 (56722140c, 27.09.22 7:30am)

### Android version

Android 9

### Other details

Webview connects to the server correctly, presenting an Authentication page or the Komga Dashboard. 
Komga version is v0.157.1-master running in Docker 20.10.3-1308 .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
FYI url never ends with a "/" you're supposed to set the url as "http://{IP address}:{port}"

**Comment by jdenm8** [comment]
When you're connecting to the root of a website, my understanding is that the forward slash is typically included in the URL. Every browser, including Webview, does this. The Download Link on the Tachiyomi homepage has one too. While `url` as a variable may expect there to be no slash on the end, I believe that it's not uncommon for a URL to have one.

I'm not aware of the requirement to omit the last slash being documented anywhere. The only documentation for the Komga extension I'm aware of is in the Tracking Guide, and it doesn't mention this.

An `if` statement to see if one already exists (since one is currently tacked on the end regardless) strikes me as a relatively simple change.

**Comment by Seishirou101** [comment]
https://komga.org/guides/tachiyomi.html#install-and-configure
regardless, its already been talked about to always remove it just no one has gotten around to it as its just as easy to not use a trailing /
you can look at one of the other self hosted extensions as I believe one of them remove it as well, if you'd like to make a pr.
