### ISSUE TITLE
cloudware block 

### ISSUE THREAD

**Issue by freedomkilla** [tachiyomiorg/tachiyomi-extensions#13683]
### Source information and language

happymh 1.3.2

### Steps to reproduce

1. updating manga/manhwa
2. got skipped
3. browse website 
4. verify cloudware loop non stop

### Expected behavior

1. update manga/manhwa
2. new chapter will show up
3. download new chapters

### Actual behavior

1. update manga/manhwa
2. new chapter didnt show up
3. nothing to download

### Tachiyomi version

0.13.6

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
