### ISSUE TITLE
Bring back nhentai's old layout

### ISSUE THREAD

**Issue by breaking-loss** [tachiyomiorg/tachiyomi-extensions#13684]
### Source name and language

Nhentai 1.3.36

### Describe your suggested feature

I humbly request you to bring back the og layout of nhentai ( only the filter button on the bottom right hand side of the screen ) . the new layout feels like it is taking too much of space . Another request of mine is to launch keyboard on pressing the search icon .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
>  If this is an issue with the app itself, I should be opening an issue in the app repository.

This is not handled by the extension at all.
