### ISSUE TITLE
Henchan: Changed their domain

### ISSUE THREAD

**Issue by Vasillii0** [tachiyomiorg/tachiyomi-extensions#13698]
### Source information and language

hentaichan / henchan [RU] 

### Steps to reproduce

Try to log in 

### Expected behavior

Normal work

### Actual behavior

dont working
![Screenshot_2022-10-03-20-18-32-467_eu kanade tachiyomi](https://user-images.githubusercontent.com/57034088/193640438-21c71ffb-57b7-4ce3-bf3f-0b89af3ccd5f.jpg)
![Screenshot_2022-10-03-20-18-37-208_eu kanade tachiyomi](https://user-images.githubusercontent.com/57034088/193640442-14e40eaf-8df8-4f11-bcac-8ce9d24927a2.jpg)
![Screenshot_2022-10-03-20-18-40-253_eu kanade tachiyomi](https://user-images.githubusercontent.com/57034088/193640447-41a907b6-126f-481e-a246-f08c526bf42f.jpg)
**[Image removed due to containing NSFW]**

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

New domain is http://y.hchan.live/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Vasillii0** [comment]
Sorry, I cant add lables "Domain changed"

**Comment by alessandrojean** [comment]
I added for you, but please also next time don't post any NSFW picture on GitHub.
