### ISSUE TITLE
【SOURCE REQUEST : SOUDONGMAN chinese manga】

### ISSUE THREAD

**Issue by Andi234Pisces** [tachiyomiorg/tachiyomi-extensions#1370]
(CATALOGUE) SOURCE REQUESTS:
Link : http://www.soudongman.com
nice to read chines manhua for update and not need premium to read, , free read and always update

**Comment by as280093** [comment]
[soudongman.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612631/soudongman.zip)
Here the icons
