### ISSUE TITLE
Bilibili Comics: Missing original resolution option

### ISSUE THREAD

**Issue by alenwai** [tachiyomiorg/tachiyomi-extensions#13717]
### Source information and language

Bilibili Comics v1.3.7

### Steps to reproduce

1) Even if the highest quality format Raw is chosen in the extension settings, the downloaded image only has half the resolution.

### Expected behavior

The original image has a resolution of 2400 x 6168.
The image was downloaded using hakuneko v6.17.

![hakuneko](https://user-images.githubusercontent.com/111482404/193982740-8a6053fa-45a1-4afc-b403-b4f3927bd859.jpg)

### Actual behavior

The same image downloaded using tachiyomi has a resolution of 1200 x 3084, even if the highest quality setting Raw is chosen.

![tachiyomi](https://user-images.githubusercontent.com/111482404/193982788-690957cd-a52a-43e0-983f-a1f56cf91c34.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

The above images reference links.
Manhua Name: [Above Myriads](https://www.bilibilicomics.com/detail/mc1524), [Episode 1](https://www.bilibilicomics.com/mc1524/137396), Page 2/59.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Very curious as to why you need that high res image when you're just gonna read it on a mobile device.

**Comment by loocool2** [comment]
This is more of a feature request since we're already exposing all the available option to the user right now, Hakuneko is downloading a quality level that's not normally exposed to the user.
