### ISSUE TITLE
Manga fenix 

### ISSUE THREAD

**Issue by Marco-kun** [tachiyomiorg/tachiyomi-extensions#13738]
### Source information and language

Manga Fenix 1.3.26  (español)

### Steps to reproduce

Al entrar a la extensión marca un error de que fallo el evitar el cloudflare y sucede lo mismo al abrir por webview 

### Expected behavior

Debería abrir a la página manga-fenix.com 

### Actual behavior

No puede llegar la página debido al cloudflare 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

![Screenshot_2022-10-06-21-52-02-270_eu kanade tachiyomi](https://user-images.githubusercontent.com/85567345/194444389-adb78701-04ac-4dee-bf92-96feb28b7261.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
please refer to https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
