### ISSUE TITLE
Reaper Scans: Changed domain

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#13735]
### Source information and language

Reaper Scans 1.3.34 (Portuguese - Brazil)

### Steps to reproduce

1. Open Reaper Scans
2. See the Mangas

### Expected behavior

Enter Reaper Scans, see the mangas

### Actual behavior

![Screenshot_20221006-145442_Tachiyomi](https://user-images.githubusercontent.com/82852543/194384843-9cf61401-345e-4a52-a099-59cc4031a788.png)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Reaper Scans changed the domain from https://reaperscans.com.br/ to https://reaperscans.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaMoradi** [comment]
This is quite different to #13639 we might need to treat each language differently now?

**Comment by I-Am-C0der** [comment]
Not only Portuguese Language, English extension is also not working.
