### ISSUE TITLE
The source is not working 

### ISSUE THREAD

**Issue by firstdarsh** [tachiyomiorg/tachiyomi-extensions#13739]
### Source information and language

Manga Starz 1.3.26

### Steps to reproduce

When I open any manga chapter it stays on for a very long time and doesn't open the chapter 

### Expected behavior

Expected after the download period to open the chapter 

### Actual behavior

After a very long download period, it comes out of the chapter and does not work, and after repeatedly opening the same chapter or any other chapter, it still does not work.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by XOCV0** [comment]
Hope this get fixed soon

**Comment by alessandrojean** [comment]
Please be more specific about what does not work, the images doesn't load, you get any errors?

Closing as it lacks information. Feel free to open a new issue with more detailed information.
