### ISSUE TITLE
Yungen mangas error 400

### ISSUE THREAD

**Issue by tengutenshi** [tachiyomiorg/tachiyomi-extensions#13740]
### Source information and language

Yungen mangas not showing up 

### Steps to reproduce

It got removed? 

### Expected behavior

? 

### Actual behavior

? 

### Tachiyomi version

Latest 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
From Tachiyomi's Discord:

> 🇪🇸 El sitio en Español de **YugenMangas** cambió su tema, lo que rompió la extensión. Para seguir leyendo tus manga desde esta fuente, **desinstala** la extensión obsoleta que estaba disponible en la sección **Todos** e **instala la nueva** disponible en la sección **Español**. Después, tendrás que **migrar** los elementos de tu biblioteca desde la fuente marcada como `989793618887201018` a YugenMangas para actualizar las URLs.
> 
> 🇧🇷 A fonte brasileira da **YugenMangas** foi separada dos outros idiomas por conta de mudanças nos sites. Para continuar lendo seus mangás desta fonte, **desinstale** a extensão obsoleta que estava na seção Todos/Multi e instale a nova disponível na seção **Português (Brasil)**. Não é necessário migrar.
