### ISSUE TITLE
Mangabuddy is not working. No pages found. The domain change to mangamirrow.

### ISSUE THREAD

**Issue by skybloodx0824** [tachiyomiorg/tachiyomi-extensions#13745]
### Source information and language

Mangabuddy 1. 3. 11 English

### Steps to reproduce

1. Try opening the chapter it stated no pages found. 
2. Some titles can be read but most of it doesn't work.
3. Open webview and all the chapter can be open and read there.
4. Try clear cache and it still shows no pages found.
5. Already clear the cookies and webview data still the same.
6. When open the chapter in webview, the domain change to mangamirror.com

### Expected behavior

It should open normally.

### Actual behavior

It takes 2 second to load but then it stated no pages found.

### Tachiyomi version

App version: 0.13.6 

### Android version

Android 11

### Other details

![Screenshot_2022-10-07-19-15-23-705_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/194540922-52b27eb8-f511-4b99-a4cd-d2b033bd3ade.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by w00ogly** [comment]
Works perfectly fine for me though.

**Comment by skybloodx0824** [comment]
Myb for you but I already have two person who says theirs doesn't work too.

**Comment by w00ogly** [comment]
I checked again using what your reading and it doesn't work

**Comment by shiroku-2022** [comment]
The problem is still going on.
It happens on me also, and only on MangaBuddy. Other sources are working just fine.

**Comment by skybloodx0824** [comment]
> I checked again using what your reading and it doesn't work

Yep it doesn't work since yesterday.

**Comment by skybloodx0824** [comment]
> The problem is still going on.
> It happens on me also, and only on MangaBuddy. Other sources are working just fine.
> Hope it can be fixed.
> 
> By the way I could open some title (only a few of them)  just fine before refreshing them. Once I refreshed those title for new update, it wouldn't load and kept saying "No Pages Found".

Yep true that. I do hope they will fix it soon.
