### ISSUE TITLE
Kisslove manga changing link error

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#13754]
### Source information and language

KissLove v1.3.9

### Steps to reproduce

Search for a manga that i opened earlier and open it

### Expected behavior

Chapters opening normally 

### Actual behavior

Page give me no chapters found and the webview gives me a wrong page error

### Tachiyomi version

Latest preview

### Android version

Android 8

### Other details

My guess is that happend because they changed the manga links also want to mention that i tried deleting the extension and removing the cached data and nothing changed and this error happens only for manga i opened
![Screenshot_20221007-233250](https://user-images.githubusercontent.com/66560257/194663039-bc8a6cef-b0a6-42c9-8ca7-b2eca9929fc8.png)
 before 
![Screenshot_20221007-233241](https://user-images.githubusercontent.com/66560257/194663062-52fd5366-c650-4a5e-b250-747853c10ed8.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
this is website fault not extension issue, a little manga in klmanga.net (kisslove) have this issue ( manga become missing or not found in website) , if there are chapter list in tachiyomi that's mean you have it before the manga page in website got broken if a new manga you want read/added it's show nothing

the fact in website have broken manga link get update ( show in latest in website with new chapter number in title ) so tachi recognize that's as update, but when u open there are no new chapter and try to refresh u only get notice chapter not found, when u open in webview inside tachiyomi u will get 404 Sorry! Page not found!

this is the website link : https://klmanga.net/mzga-yofukashi-no-uta-raw.html when u open it will redirect to https://klmanga.net/404.html


https://user-images.githubusercontent.com/101858971/194684548-4968178f-8fd3-4da1-9860-1b1e618b95c3.mp4

**Comment by sohilsayed** [comment]
Yeah i know this us the site problem i was just reporting and asking if there is a way to Remove old cached links from tachiyomi

**Comment by DchanN** [comment]
Think this can be closed, broken page already being fixed and chapter load fine now, confirm this fix for other manga from kisslove too in my library

https://user-images.githubusercontent.com/101858971/197402955-d01703ce-e2b3-4aca-84a2-9aa0b321b31f.mp4
