### ISSUE TITLE
Sinensis: Changed the domain

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#13764]
### Source information and language

Sinensis 1.3.27 (Portuguese - Brazil)

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Sinensis changed the domain from https://sinensisscans.com/ to https://sinensisscans.com/home/ and the name is no longer Sinensis, it is now Sinensis Scan

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Just a tip for the next similar issues: there's now a URL change report form, you can use it as it's more quickier to report there next time :)

**Comment by alessandrojean** [comment]
Submitted a fix, after installing the new update when available, if you have any chapter downloaded, you will need to rename the source folder to match the new source name.
