### ISSUE TITLE
Viz Shonen Jump: App freezes while downloading 

### ISSUE THREAD

**Issue by snintendog** [tachiyomiorg/tachiyomi-extensions#13767]
### Source information and language

Viz Shonen Jump 1.3.14

### Steps to reproduce

Have a Viz account and pay the 1.99 for the shonen jump subscription. 

Log in with the tachi browser.

Download a chapter from Viz at random pages it freezes and spits out a Format can't be read.

### Expected behavior

Download fully and skip the ad it is likely freezing on.

### Actual behavior

 It freezes and stops the download. some times it can complete if the ad doesn't appear. note i have a subscription to Viz and logged in via tachiyomi browser. Never stops the self promo ads just how Viz does it.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

It's likely the self promotion ads they like to insert randomly in chapter screwing it up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Would be a little hard to debug that as it's restricted to someone with a subscription account that are willing to fix that, will need to wait some time.

As a side note, although the extension does support signing in through WebView, it's more like a convenience and not quite recommended as it's against their ToS. It's recommend to use their app if you can.

**Comment by snintendog** [comment]
> Will be a little hard to debug that as it's restricted to someone with a subscription account that are willing to fix that, will need to wait some time.
> 
> As a side note, although the extension does support signing in through WebView, it's more like a convenience and not quite recommended as it's against their ToS. It's recommend to use their app if you can.

Trust me their app is the worst you can get my browser is a better reader than that. tachi is better in all ways and it doesn't cause an android meltdown restart loop like theirs does.

**Comment by alessandrojean** [comment]
I also forgot to ask: please provide a manga and a chapter where this occurs as an example for someone that wants to work on fixing the issue please.

**Comment by snintendog** [comment]
Seraph of the end ch119 pg 31, 33, 35
Kaiju no.8 ch69
Twinstar exorcists ch 112 pg 32,34 will hop on my phone to show what a browser view of an Ad looks like in a moment

**Comment by snintendog** [comment]
![Screenshot_20221009-094939](https://user-images.githubusercontent.com/5448989/194760617-60b74248-5f35-4639-aae8-8d5b045e9f55.png)
This one trigger on page 46 of seraph of the end ch119

**Comment by alessandrojean** [comment]
Does this happens in any chapter available for free? If so I can probably try to debug it.

**Comment by alessandrojean** [comment]
I just checked the extension code, it doesn't even try to fetch these fake pages that are ads, it just makes requests for actual image pages. Viz however changed a little how the requests are being done, so maybe that's what are causing some issues for you. I can't manage to make the app freezes on my device on some free chapters I tried for now, can you also specify what's your device?

**Comment by snintendog** [comment]
Its a 2020 Moto Gstylus and yes the 3 recent chapters on VIZ are typically Free no account needed on running series. I do use other sources but they dont have the issue.

**Comment by snintendog** [comment]
as for only free content no most of JOJO part 5 that is locked as the issue with the ads as well but they keep the ad on the very last page i did check and the page count is +1 to other sources than viz when it had an ad. Side note if i dont DL and load each page individually for Chapters with ads in Tachi it works chapter 119 of seraph reports 44 pages when doing that instead of 46.

**Comment by alessandrojean** [comment]
The page count is +1 because the first blank page is also counted as a valid page by Tachiyomi while Viz itself doesn't count it, so it's not the ad in this case. We can't remove the blank page at the beginning, as that caused issues in the past in chapters that starts with a double spread.

**Comment by alessandrojean** [comment]
@snintendog Can you check if your issue is the same as #5622?
