### ISSUE TITLE
Hide Titles/Manga

### ISSUE THREAD

**Issue by feradr** [tachiyomiorg/tachiyomi-extensions#13763]
### Source name and language

ALL

### Describe your suggested feature

I think a nice feature would be to be able to hide Some Mangas from the default view that exists today, as a way to prevent access to +18 content for those who don't want it to be shown in the Default View or even in the Categories.

### Other details

This Hide feature would hide the Mangas, not displaying notifications of the hidden content, being accessed through the settings or something similar and if possible with access blocking with a password, so I can peacefully show my Mangas whenever I want, but hiding/restricting the contents Adults.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
