### ISSUE TITLE
Early Manga: Some chapters are not displayed

### ISSUE THREAD

**Issue by lokeshvs1106** [tachiyomiorg/tachiyomi-extensions#13766]
### Source information and language

Early manga 1.3.19

### Steps to reproduce

Search a manga and it shows only one chapter present but actually there are many chapters present.
For some manga it is showing the actual chapters and for some it isnt. It is not reliable.

### Expected behavior

It should display the actual chapters that are present for the manga or present in the website up to date. For some manga it is showing the actual chapters and for some it isnt. It is not reliable.

### Actual behavior

When i search globally or search specifically in mangadex. It shows only one chapter without displaying the actual chapters that are present. I have checked in the website and there are chapters present there.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
So are you reporting about Mangadex or EarlyManga? And why didn't you provide actual examples in the reproduction steps?

**Comment by lokeshvs1106** [comment]
> So are you reporting about Mangadex or EarlyManga? And why didn't you provide actual examples in the reproduction steps?

Both

**Comment by alessandrojean** [comment]
Mangadex doesn't host licensed content, open in WebView and check if they are not external and hosted in another websites first. Try reading there to check.

**Comment by Seishirou101** [comment]
As you didn't provide any manga to reproduce the issue, I will be closing, the 10~ manga i checked on earlym matched the website. You may create another issue while giving examples if the issue persists.  As alessandrojean said, mangadex is most likely intentionally.
