### ISSUE TITLE
One Piece Ex: HTTP error 103

### ISSUE THREAD

**Issue by MicOliv** [tachiyomiorg/tachiyomi-extensions#13775]
### Source information and language

One Piece Ex 1.3.5 (Brasil)

### Steps to reproduce

Click in the extension

### Expected behavior

would work normally

### Actual behavior

this HTTP error 103 appears

### Tachiyomi version

TachiyomiJ2K 1.5.9

### Android version

Android 11

### Other details

the site works normally, maybe it could be the design that is giving this error, I've never had this error before so I don't know

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's already fixed in the Preview version of the app, wait until the app gets an update, it's really something that isn't worth fixing on the extension side.

**Comment by MicOliv** [comment]
Ok thanks

**Comment by carloshbcabral** [comment]
> It's already fixed in the Preview version of the app, wait until the app gets an update, it's really something that isn't worth fixing on the extension side.

r5018? Still not working :/.

**Comment by alessandrojean** [comment]
Checked now, the app has the fix but their website have some issues that are making the loading progress get stuck at 99% on WebView, making it to not be able to bypass the HTTP 103. There's really nothing we can do about it, you need to wait for them to solve this loading issue. Alternatively you can just use other sources in the meanwhile or read the official One Piece releases that are also free and available in Portuguese.
