### ISSUE TITLE
Cubari refuses to open or download any manga chapters.

### ISSUE THREAD

**Issue by DrEngineer1** [tachiyomiorg/tachiyomi-extensions#13772]
### Source information and language

Cubari 1.3.14 (All)

### Steps to reproduce

1. Open up a manga using Cubari
2. Try downloading or reading it

### Expected behavior

It should have opened the chapter up or downloaded it.

### Actual behavior

However there was two different things that happened with it.

1. When trying to download this happened. 
![Screenshot_20221008-125949](https://user-images.githubusercontent.com/85132109/194721536-db5611af-e96e-4789-8cfb-5d23bdc8f7f2.png)

2. When opening a chapter it brings up the black screen and  current page scroll setting message as usual to load the image. But it then kicks you out back to the chapter select and produces a blank message.

### Tachiyomi version

Stable 0.13.6

### Android version

Android version: 10

### Other details

It could have just been the one manga or that Cubari only works via opening it in the website.
EDIT #1:
Only Chapters that I recently found out that do work for the manga I'm trying to read (https://cubari.moe/read/gist/Z2lzdC9mdW5reWhpcHBvLzcxMjRhZjUyMWExMDU5NDVhNGRmNmEzMzFjOWZjZTU5L3Jhdy9vcG0td2MuanNvbg) are from 100 to the latest chapter. Everything thing else seems to not work.
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me, any specific source/link?

**Comment by DrEngineer1** [comment]
> work for me, any specific source/link?
Here's the manga I was trying to read. It works just fine off the website just not in the app,
https://cubari.moe/read/gist/Z2lzdC9mdW5reWhpcHBvLzcxMjRhZjUyMWExMDU5NDVhNGRmNmEzMzFjOWZjZTU5L3Jhdy9vcG0td2MuanNvbg

**Comment by DrEngineer1** [comment]
Correction: only chapters 100 to the latest chapter work. Everything else less than 100 seems to fail loading.

**Comment by mobi2002** [comment]
> @mobi2002 @alessandrojean Cubari 1.4.17 and Tachiyomi 0.14.5 didn't fix the issue for me.

Any specific link? I checked it through the monster link above and fixed the issue found on that.

**Comment by XioR112** [comment]
Monster works for me.

**Comment by mobi2002** [comment]
> @mobi2002 @alessandrojean Cubari 1.4.17 and Tachiyomi 0.14.5 didn't fix the issue for me.

open a new issue
