### ISSUE TITLE
Reaper Scans: Missing Images

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi-extensions#13784]
### Source information and language

Reaper Scans 1.3.32

### Steps to reproduce

[Example chapter](https://reaperscans.com/comics/2126-angelic-lady/chapters/30762985-chapter-2)

Open the chapter and scroll down

### Expected behavior

All pages present

### Actual behavior

One or some pages are missing

### Tachiyomi version

Tachiyomi r5018 / TachiyomiSY r483

### Android version

Android 12

### Other details

The page appears correctly in webview
![Screenshot_20221009_144359_Firefox Beta](https://user-images.githubusercontent.com/10052873/194757724-232b3589-5427-4ce8-ae1f-cc87ea0a8e8c.jpg)

But is missing the final section in tachiyomi
![Screenshot_20221009_144252_TachiyomiSY](https://user-images.githubusercontent.com/10052873/194757768-44e3052b-7330-4396-9757-dc2d962d10bb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sharkalone** [comment]
I have the same problem with "This is the Law". But the problem only seems to show when (down)loading a chapter with an even number of pages. I tried some of the last chapters of "This is the Law" :

- Chapters 58 to 62, 13 pages each, no problem
- Chapters 57, 63 & 64, 12 pages, only half is (down)loaded

I tried with and without the auto-split, no change.

**Comment by Sharkalone** [comment]
I just check "Angelic Lady", the same problem occurs :

- Chapter 1, 23 pages, no problem
- Chapters 2 & 3, 12 pages, only half is loading
- Chapter 4, 11 pages, no problem

the new extension don't lik even number chapters ^^'

**Comment by RazredgeBR** [comment]
Also happened to the latest chapter of Overheated (c. 147).

I believe this issue is related to "infinite scrolling".

**Comment by minermaniac447** [comment]
I'm still getting this issue even after the new most recent versions of this extension are installed - if a chapter has an even number of images, some (it seems like the second half?) of the images do not get recognized, either when downloaded or viewed directly.

My test chapters: Nano Machine ch 77 has the full chapter loaded (15 images) while 78 and 79 do not (and have an even number of images)

Other info - on the most recent version of the app and the reaper scans extension; Android 12

**Comment by Sharkalone** [comment]
Did you upadate to the last version of the extension? I don't have a problem on either 77, 78 or 79.

**Comment by alessandrojean** [comment]
@minermaniac447 Try checking if you have done that first:

> The English **Reaper Scans** has been made into a standalone extension. To retain progress, install the new Reaper Scans extension available under the English section. If you haven't migrated already after the redesign, you will need to migrate from Reaper Scans to Reaper Scans to update the URLs. If you have already migrated, no extra migration is needed.
> 
> Note that **Reaper Scans**'s search is terrible so it may require a manual search or trying different search terms to find the correct entry to migrate to.
> 
> If you're running into issues, try restarting the app.
> 
> **Protip:** If you only use the English source, you can now uninstall the All/Multi Reaper Scans extension.

If you have done, the chapter you're trying to read might be cached, try Clearing the database and Clear chapter cache in the advanced settings of the app and try again after it.

**Comment by minermaniac447** [comment]
Whoops - that did it, thank you and sorry for reopening the issue!
