### ISSUE TITLE
Error while updating mangas from reaper scans

### ISSUE THREAD

**Issue by sirzento** [tachiyomiorg/tachiyomi-extensions#13782]
### Source information and language

Reaper Scans 1.3.32

### Steps to reproduce

1. having mangas in bibliothek from the previos reaper scan site.
2. Updated to the latest reaper scans version
3. Refresh on the new page to load the latest chapters

### Expected behavior

Chapters should load normally

### Actual behavior

No chapters are updated and error messages is thrown.

Error message:

```
! Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
  # Reaper Scans (EN)
    - Damn Reincarnation
    - God of Blackfield
    - I’m the Max-Level Newbie
    - Kill The Hero
    - Overgeared
    - Swordmaster’s Youngest Son – Manhwa
    - The Great Mage Returns After 4000 Years
    - The Return of The Disaster-Class Hero
    - The World After the Fall
```

### Tachiyomi version

0.13.6

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by henrik9999** [comment]
> To retain progress for entries from Reaper Scans, update and migrate all entries from Reaper Scans to Reaper Scans.
