### ISSUE TITLE
Reaper Scans Missing

### ISSUE THREAD

**Issue by amzifauzi** [tachiyomiorg/tachiyomi-extensions#13798]
### Source information and language

Reaper Scans 1.3.35

### Steps to reproduce

1. Install version 1.3.35
2. Installed, but source is missing

### Expected behavior

It should be shown in the sources

### Actual behavior

But it is not

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by I-Am-C0der** [comment]
Refer #13747 for fix

**Comment by amzifauzi** [comment]
> Refer #13747 for fix

Worked, thank you.
