### ISSUE TITLE
Void Scans NXDomain

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi-extensions#13797]
### Source information and language

Infernal Void Scans 1.3.25

### Steps to reproduce

1. Open Internal Void Scans

### Expected behavior

See Void Scan Library

### Actual behavior

error void-sancs.com: NXDOMAIN

### Tachiyomi version

Tachiyomi R5018

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me 
have you really tried troubleshoot?
