### ISSUE TITLE
Reaperscans extension update

### ISSUE THREAD

**Issue by Nitineshwar** [tachiyomiorg/tachiyomi-extensions#13809]
### Source information and language

Reaperscans

### Steps to reproduce

Reaperscans has undergone a significant site change and now the new website is up. The URL to reaperscans is the same as before (reaperscans.com). The site is up and running however tachiyomi hasn't been receiving updates from it and now I can't even see the extension in the "Browse" section on the app. 
Reaperscans said they cant do anything about this and it's tachiyomi devs who have to fix it on their end.

### Expected behavior

To be able to get chapter updates from reaper scans as usual.

### Actual behavior

Source not found error .

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
From Tachiyomi's Discord #status-update:

> The English Reaper Scans has been made into a standalone extension. To retain progress, install the new Reaper Scans extension available under the English section. If you haven't migrated already after the redesign, you will need to migrate from Reaper Scans to Reaper Scans to update the URLs. If you have already migrated, no extra migration is needed.
> 
> Note that Reaper Scans's search is terrible so it may require a manual search or trying different search terms to find the correct entry to migrate to.
> 
> If you're running into issues, try restarting the app.
> 
> Protip: If you only use the English source, you can now uninstall the All/Multi Reaper Scans extension. 

Also please don't ask about extensions or Tachiyomi to site owners as we're not affiliated with them.

> Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
