### ISSUE TITLE
Reaper Scans lost ability to search novels

### ISSUE THREAD

**Issue by merryscarlet** [tachiyomiorg/tachiyomi-extensions#13802]
### Source information and language

1.3.35

### Steps to reproduce

Launching Reaper Scans show no filter and only shows manhwas.

### Expected behavior

Should be able to filter and search for novels

### Actual behavior

No novels are viewable. Novels can be found through webview.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Example Swordmaster's Youngest Son - Novel was added to my library previously and now does not link back to the page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Tachiyomi is not meant to support text-based contents nor is it a general-purpose tracker if that's what you were using it for.
