### ISSUE TITLE
mcreader extension

### ISSUE THREAD

**Issue by MadTurbate** [tachiyomiorg/tachiyomi-extensions#13800]
### Source information and language

"mcreader.net 1.3.16(English)"

### Steps to reproduce

![Screenshot_20221010_212305_eu kanade tachiyomi](https://user-images.githubusercontent.com/115486333/194903209-72a02874-7d8a-4586-9d09-932bfefa0670.jpg)

### Expected behavior

images normally load fast

### Actual behavior

images never load (only the promo at the end or the source of the material)

### Tachiyomi version

0.13.6

### Android version

EMUI 12

### Other details

webview works

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sreesiddhi** [comment]
They changed the website from https://www.mcreader.com to https://www.mreader.co

**Comment by DrProphet0** [comment]
The base URL is set correctly in the extension
baseUrl = "https://www.mreader.co"
But getting error "Expected URL scheme 'http' or 'https' but no colon was found"
Which is usually a cache error
I have cleared chapter cache, database cache, cleared cookies but the problem remains
After reinstalling the problem persists.

**Comment by MadTurbate** [comment]
additional info: the promo images load but not the main images
![Uploading Screenshot_20221011_195215_eu.kanade.tachiyomi.jpg…]()

**Comment by DrProphet0** [comment]
Well it works now after changing user agent string.

**Comment by MadTurbate** [comment]
changing default user agent string to a chrome user agent fixed the problem thanks to DrProphet0

**Comment by MadTurbate** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

this worked for me
