### ISSUE TITLE
MangaPanda

### ISSUE THREAD

**Issue by hidayatsohif** [tachiyomiorg/tachiyomi-extensions#13812]
### Source name

MangaPanda

### Source link

http://mangapanda.in/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses a custom Madara theme

**Comment by Riztard** [comment]
> Uses a custom Madara theme

i think its paprika theme

**Comment by vetleledaal** [comment]
Site looks different on desktop and mobile, not sure what they're doing to differentiate. 
![Screenshot from 2022-10-14 07-26-01](https://user-images.githubusercontent.com/13540478/195769391-4888387a-4216-4ad3-9438-20210138ffdf.png)
![Screenshot from 2022-10-14 07-29-55](https://user-images.githubusercontent.com/13540478/195769395-3c2d0d00-764b-4d15-97f9-c158b2efa8ef.png)
