### ISSUE TITLE
Reaper scans not appearing under Source

### ISSUE THREAD

**Issue by FreeZeID** [tachiyomiorg/tachiyomi-extensions#13814]
### Source information and language

English

### Steps to reproduce

1. install Reaper scans extension
2. Go to Source

### Expected behavior

Reaper scans should be there

### Actual behavior

It it isn't

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

![Screenshot_20221011-115955_Tachiyomi](https://user-images.githubusercontent.com/47861681/195060299-97c6133d-9f2e-45e6-92af-cb0da607eec5.jpg)
![Screenshot_20221011-115936_Tachiyomi](https://user-images.githubusercontent.com/47861681/195060309-03722b53-ad1e-4242-aa99-0eef847377b7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FreeZeID** [comment]
Re installing does not change anything

problem appear after last Update

**Comment by henrik9999** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13809#issuecomment-1273913153

**Comment by FreeZeID** [comment]
there are 2 Reaper scans Extension the working on is lower in the List
