### ISSUE TITLE
Mangabuddy :Trust anchor for certification path not found

### ISSUE THREAD

**Issue by KFA999** [tachiyomiorg/tachiyomi-extensions#13813]
### Source information and language

1.3.12

### Steps to reproduce

1. Checking for some updates for my novel on sources at the browse tab for mangabuddy
2. When opening the mangabuddy source page an error comes up (java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)

### Expected behavior

The source page of mangabuddy should as usual show list of updated manga/manhwa/manhua

### Actual behavior

An error code shows up and the usual list is not present
![Screenshot_2022-10-11-17-34-53-95_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/109713508/195055594-d3d830be-61c4-476c-a6d3-302c322ed0d3.jpg)
![Screenshot_2022-10-11-17-34-56-93_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/109713508/195055608-d627d600-5563-449a-bf5f-b5d1b1194cfe.jpg)

### Tachiyomi version

0.13.6

### Android version

12

### Other details

I've tried opening the source ( mangabuddy.com ) at my browser ( google chrome ), and the site is accessible.

I just wanted to know if the issue is with the extension or the website itself and if it is fixable. Thank you for checking out my request and sorry for the intrusion 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by iMo-ali** [comment]
Same it appears to be an issue with the source i tried deleting cookies and database still the same hopefully it will be fixed soon

**Comment by vetleledaal** [comment]
mangamirror.com (used by MangaBuddy) is blocked for some users (unknown cause), so this is not an issue with the extension, but rather the site. You could try enabling DoH to bypass it, otherwise a VPN should work.

https://tachiyomi.org/help/faq/#what-is-dns-over-https
