### ISSUE TITLE
Reaper Scan extension is not showing in sources list after installing 

### ISSUE THREAD

**Issue by amritazad** [tachiyomiorg/tachiyomi-extensions#13823]
### Source information and language

Reaper Scan 1.3.35 language all

### Steps to reproduce

Install the reaper Scan extension
Check the sources list

### Expected behavior

Reaper Scan name should be listed in sources after installing the extension 

### Actual behavior

Not showing in sources list 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13809#issuecomment-1273913153
