### ISSUE TITLE
Saved Manhwa: Chapter not found

### ISSUE THREAD

**Issue by huacheng3** [tachiyomiorg/tachiyomi-extensions#13825]
### Source information and language

Mangabuddy 1.3. 12

### Steps to reproduce

Saved Manhwa from the library:
Every chapter page cannot be found.(picture 1)

While the unsaved Manhwas is available(pic2)
![Screenshot_20221012_174808](https://user-images.githubusercontent.com/115542577/195310687-d28f133f-9e78-4f17-af29-4c6e16936550.jpg)
 
![Screenshot_20221012_174759](https://user-images.githubusercontent.com/115542577/195310786-8c5d805b-f563-4f3d-a39f-884da5ea8f6d.jpg)

### Expected behavior

The saved Manhwas in the library are available and the mark are still there.

### Actual behavior

The mark disappear and the chapters are not available in the library 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

I hope the issue will be fix soon wahhh I miss my babiessssss

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
After updating to 1.3.2 you need to refresh the manga by pulling down on the manga or refreshing your library. This is due to changes on the site allowing external chapters.

**Comment by huacheng3** [comment]
> After updating to 1.3.12 you need to refresh the manga by pulling down on the manga or refreshing your library. This is due to changes on the site allowing external chapters.

Wahhh thank you the extension is finally working again!!
