### ISSUE TITLE
Request for a "Delete all downloaded chapters not in library" button

### ISSUE THREAD

**Issue by kaizerboo** [tachiyomiorg/tachiyomi-extensions#13824]
### Describe why this should be added

Was trying to clean up space on my phone when I realized that after migrating sources, the original sources does not automatically delete downloaded chapters. These chapters are taking up a significant amount of space on my phone and by the time I found out about this, I have already migrated a large number of mangas.

Hence the request for a "deleted all downloaded chapters not in library" button.

Also, a separate but related request, I would like another button to delete "unreadable" chapters.
For example, Bilibili frequently releases a manga for free, and would paywall every chapter after the 10th after it has a 100 chapters. With auto download on, this would result in the chapters 11-100 to be downloaded but not readable via Tachiyomi.
I wouldn't mind if both functions were put into a single button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Isn't this the problem with the Tachiyomi app?  Why did you make an issue in Tachiyomi Extension?

**Comment by curche** [comment]
FYI https://github.com/tachiyomiorg/tachiyomi/issues/1767
