### ISSUE TITLE
Tapas 1.3.18 is not loaded by Tachiyomi 

### ISSUE THREAD

**Issue by laurentlbm** [tachiyomiorg/tachiyomi-extensions#13839]
### Source information and language

Tapas 1.3.18 (English)

### Steps to reproduce

1. Install the Tapas extension*

\* It might not show up (another bug or possibly the same). In that case, download it from the site: https://tachiyomi.org/extensions/#en.tapastic

### Expected behavior

"Tapas" should show up under **Browse** > **Sources**

### Actual behavior

It's nowhere to be found.

### Tachiyomi version

0.13.6

### Android version

12

### Other details

The previous version of the extension (1.3.17) works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Enable NSFW sources

**Comment by laurentlbm** [comment]
> Enable NSFW sources

Thanks! That's frustrating though, because there was nothing in the app to say that the rating of the extension had changed or that it was disabled. The extension just stopped working and showing up.

**Comment by vetleledaal** [comment]
tachiyomiorg/tachiyomi#5948 is tangentally related, but was closed as it was intended behavior. You could open another issue in the tachiyomi repo if you know of a better way to handle cases like this.
