### ISSUE TITLE
Reaper Scan: new Web site, all manga doesnt work anymore

### ISSUE THREAD

**Issue by loiccsl** [tachiyomiorg/tachiyomi-extensions#13834]
### Source information and language

Reaper Scans 1.3.35 english

### Source new URL

https://reaperscans.com/

### Other details

I think the URL is the same as before but the page paths are not the same at all. The mangas recovery does not work at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Can you confirm whether you've followed the following instructions:

> The English Reaper Scans has been made into a standalone extension. To retain progress, install the new Reaper Scans extension available under the English section. If you haven't migrated already after the redesign, you will need to migrate from Reaper Scans to Reaper Scans to update the URLs. If you have already migrated, no extra migration is needed.
Note that Reaper Scans's search is terrible so it may require a manual search or trying different search terms to find the correct entry to migrate to.
If you're running into issues, try restarting the app.
Protip: If you only use the English source, you can now uninstall the All/Multi Reaper Scans extension.

**Comment by alessandrojean** [comment]
Closing as the extension is already updated to match their new design. Please follow the instructions provided above.
