### ISSUE TITLE
mcreader.net/mreader.net chapters not loading

### ISSUE THREAD

**Issue by Helkyoo** [tachiyomiorg/tachiyomi-extensions#13836]
### Source information and language

mcreader.net/mreader.net

### Steps to reproduce

Just try opening one chapter in the extension

### Expected behavior

Chapters should load when opened 

### Actual behavior

But It's not loading, unlike other extensions which works perfectly 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Can you try the instructions as said in the following message:

> If you're encountering a Trust Anchor issue on MangaBuddy, turn on DNS over HTTPS under More > Settings > Advanced and select any of the options. If that option does not work, try a different one.

**Comment by Helkyoo** [comment]
Nothing changed

**Comment by Helkyoo** [comment]
Weirdly enough I just figured that only some mangas has this problem, some seem to work. It's weird because with webview It's clearly loading.

**Comment by Helkyoo** [comment]
Got some of the ones that were not working by downloading, but if I delete de download it will no fix the issue. Weird

**Comment by MadTurbate** [comment]
try this user agent string under settings>advanced

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
