### ISSUE TITLE
Astra Scans 

### ISSUE THREAD

**Issue by AstraScans** [tachiyomiorg/tachiyomi-extensions#13845]
### Source link

Astrascans.com

### Other details

I want you to remove this site because I am translating and you are causing me a lot of losses

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by AstraScans** [comment]
I want you to remove this site because I am translating and you are causing me a lot of losses

**Comment by arkon** [comment]
Who did you DM on Discord?

**Comment by AstraScans** [comment]
Yes, MDL

**Comment by AstraScans** [comment]
I want you to remove the site and thank you

**Comment by AstraScans** [comment]
The name of the site astrascans.com

**Comment by arkon** [comment]
Who's MDL?

**Comment by AstraScans** [comment]
![Screenshot_2022-10-16-18-02-43-945_com discord](https://user-images.githubusercontent.com/115717979/196048381-d0b0a0fd-becd-4f53-9d3f-f47dec95158f.jpg)
Talk to this person and give me your link

**Comment by arkon** [comment]
I'm sorry, your responses are incomprehensible.

Please DM a staff member on Discord proof of site ownership.

I'm also confused how you're having losses considering there's no ads on the website. Are you selling user data?

**Comment by AstraScans** [comment]
The site is mine if it's not mine, why would I talk to you?

**Comment by AstraScans** [comment]
The staff at the Discord don't answer

**Comment by AstraScans** [comment]
What do you want to verify the ownership of the website

**Comment by AstraScans** [comment]
You're stealing my content and you want to verify ownership, where is the logic in this?

**Comment by curche** [comment]
Proof of Ownership was confirmed via Discord 👍

**Comment by Riztard** [comment]
> You're stealing my content and you want to verify ownership, where is the logic in this?

btw tachiyomi is just like a modified web browser
fyi
