### ISSUE TITLE
Mangafreak: Issue with cloudflare

### ISSUE THREAD

**Issue by Bornohn** [tachiyomiorg/tachiyomi-extensions#13844]
### Source information and language

Mangafreak English 

### Steps to reproduce

Says that it couldn’t bypass clowdflare 
Then I open in web view but the website shows no site inspection. 
Then I retry to connect but it still shows the same isse.

### Expected behavior

After opening in web view it should be able to bypass clawdflare.

### Actual behavior

Instead it still shows that it cannot bypass clowdflare.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LuxTempestas** [comment]
Same problem here, already cleaned cookies, webview data, all the caches...

**Comment by feeddanoob** [comment]
Changing the user agent works for mangafreak but I noticed it also breaks asurascans making that source have a page not found error for any manga

**Comment by alessandrojean** [comment]
Closing as possible solutions are in the link provided before by LuxTempestas. If none works, wait until the site owners decide to lower the Cloudflare protection or migrate to other sources.
