### ISSUE TITLE
Manga pro changed the link

### ISSUE THREAD

**Issue by BenaliAziz** [tachiyomiorg/tachiyomi-extensions#13841]
### Source information and language

Manga pro1.3.24

### Steps to reproduce

![Screenshot_20221013-074325_Tachiyomi](https://user-images.githubusercontent.com/111535060/195563025-d9767bd2-240e-44de-b164-4cae56a47c82.jpg)

### Expected behavior

They changed the link

### Actual behavior

Same thing

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the "URL change report" form instead and do provide their new URL there. Closing as it lacks information.
