### ISSUE TITLE
مانجا ليك failed to bypass cloudflare 

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#13857]
### Source information and language

مانجا ليك 1.3.24 arabic

### Steps to reproduce

Failed to bypass cloudflare 

### Expected behavior

It should opens the chapter

### Actual behavior

It don't download and it says failed to bypass cloudflare 

### Tachiyomi version

1.8.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
