### ISSUE TITLE
Manganoon: Extension removal request

### ISSUE THREAD

**Issue by manganoon** [tachiyomiorg/tachiyomi-extensions#13866]
### Source link

https://manganoon.com/

### Other details

![Screenshot_20221015_143342_com android chrome](https://user-images.githubusercontent.com/115876113/195984284-0c7613b5-b8e0-4092-974e-8864134f2631.jpg)

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by arkon** [comment]
Please DM a staff member on Discord proof of site ownership.

**Comment by loocool2** [comment]
Proof of ownership has been given along with confirmation that content hosted is their own.
