### ISSUE TITLE
Re-adiction recent for argos scan

### ISSUE THREAD

**Issue by Gui02789** [tachiyomiorg/tachiyomi-extensions#13864]
### Source name and language

Argos scan 

### Describe your suggested feature

It has as to re-add the recent argos scan extension function ??

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Not really sure if I understand what you mean, but it's not actually possible as their API for that is very clunky. If someday they enhance their API behavior it might be possible to enable latest again.

**Comment by Gui02789** [comment]
Thanks for the reply alessandro
