### ISSUE TITLE
WNACG: Images do not load

### ISSUE THREAD

**Issue by 2936747557** [tachiyomiorg/tachiyomi-extensions#13865]
### Source information and language

WNACG 1.3.7

### Steps to reproduce

1.打开tachiyomi
2.打开WNACG
3.无法正常工作（试了代理vpn和不代理vpn都不行，今天突然出现的问题昨天正常）
![Screenshot_20221015_130004](https://user-images.githubusercontent.com/102228434/195969633-53ccd374-5bd7-446f-a68c-b60ccc6d245f.jpg)
![Screenshot_20221015_130036](https://user-images.githubusercontent.com/102228434/195969638-2e855b9b-d492-4bf3-bbcd-a50d928a4512.jpg)

### Expected behavior

应该正常显示网站漫画列表并加载图片

### Actual behavior

网站漫画加载失败

### Tachiyomi version

0.13.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jay02105** [comment]
從web清除cookie可暫時解決此問題，但一段時間後會無法加載

**Comment by weibut** [comment]
應該是大陸對這個功能變數名稱（wnacg.top）牆了。 圖片加載返回
PKIX path building failed: sun.security.provider.certpath. SunCertPathBuilderException: unable to find valid certification path to requested target
但是使用（ https://www.htcomic.top/ ）就是正常的。
1.3.7從wnacg.org變更為wnacg.top，所以引起這類問題
