### ISSUE TITLE
Kiryuu failed to bypass cloudflare

### ISSUE THREAD

**Issue by enzok30** [tachiyomiorg/tachiyomi-extensions#13875]
### Source information and language

Kiryuu 1.3.27 Indonesia

### Steps to reproduce

failed to bypass cloudflare

### Expected behavior

it should display the page

### Actual behavior

Still failed

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
sudah bisa lagi, mungkin webnya lagi di utak atik kemaren
coba troubleshoot kalo gabisa
