### ISSUE TITLE
NewToki doesn't get it's number updated 

### ISSUE THREAD

**Issue by taynara2** [tachiyomiorg/tachiyomi-extensions#13889]
### Source information and language

NewToki/ManaToki 1.3.25 (Korean)

### Steps to reproduce

Just go to the configuration of the extension, then update the number and leaves. The number actually doesn't get updated.

https://user-images.githubusercontent.com/52222614/196174726-2f8e12ad-37c9-42f1-91b9-7cbfb5a17497.mp4

### Expected behavior

Was expected to have the number updated after leaving the extension configuration.

### Actual behavior

It ignores the number you put after leaving the configuration.

### Tachiyomi version

13.6

### Android version

12 SDK31

### Other details

Crash log. 
--------- beginning of main
10-17 08:46:23.677  4389 21566 E SchedPolicy: Failed to find cgroup for tid 4389
10-17 08:47:17.886  4389 22215 E SchedPolicy: Failed to find cgroup for tid 4389
10-17 08:47:41.227  4389  4389 E SwipeRefreshLayout: Got ACTION_MOVE event but don't have an active pointer id.
10-17 08:47:41.251  4389  4389 E SwipeRefreshLayout: Got ACTION_MOVE event but don't have an active pointer id.
10-17 08:47:41.271  4389  4389 E SwipeRefreshLayout: Got ACTION_MOVE event but don't have an active pointer id.
10-17 08:51:24.553  4389 24434 E SchedPolicy: Failed to find cgroup for tid 4389
10-17 08:53:30.798  4389 26042 E SchedPolicy: Failed to find cgroup for tid 4389
10-17 08:55:13.774  4389 27191 E SchedPolicy: Failed to find cgroup for tid 4389
10-17 08:56:15.531  4389 27572 E SchedPolicy: Failed to find cgroup for tid 4389
App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G991BXXU5CVGC
Device brand: samsung
Device manufacturer: samsung
Device name: o1s
Device model: SM-G991B
Device product name: o1sxxx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Working on a fix.
