### ISSUE TITLE
Ninja scan does not work

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#13891]
### Source information and language

Ninja Scan Brasil 1.3.25

### Steps to reproduce

The browser scan is working perfectly, but the in-app extension is not.

### Expected behavior

it should work normally the same as a few days ago.

### Actual behavior

HTTP error 500:verifique o site na webview

### Tachiyomi version

0.13.6

### Android version

10.0

### Other details

No detalhe 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP error 500 means their server is having issues. If you open a manga details page on WebView you will see the chapters doesn't load. You need to wait for them to fix that, we can't do anything on the extension side.
