### ISSUE TITLE
A large list of sources that no longer work or have bugs.

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi-extensions#13908]
### Describe why this should be added

| Source Name 		|			 Reason    | 
| --------------- 	| --------------- 	   | 
| Ace scans						| Expired domain |
| astral library				| 	Abandoned website |
| beast scans 					| Expired domain |
| beemanga 						| Chapter error No pages found |
| BeastManhua  					| Not loading library |
| BlockManga					| 	Expired domain |
| Catonheadtranslations			| Abandoned website |
| edelgard scans				| 	Expired domain |
| eternal scans					| Expired domain |
| hatigarm scans				| 	Expired domain |
| heroz scalation				| 	Expired domain |
| iskultrip scans				| 	Expired domain |
| kiara 						| 	Not loading library |
| kiseki manga					| Expired domain |
| kokomanga						| Expired domain |
| latest manga					| Expired domain |
| levelerscans					| Expired domain |
| lumine scans					| Expired domain |
| man manga						| Expired domain |
| manga funny					| 	Expired domain  |
| manga hero					| 	Expired domain |
| manga leveling				| 	hour on chapter name |
| manga linkz					| 	Expired domain |
| manga riki					| 	Expired domain |
| manga sky 					| 	As far as I've seen, there's no more manga on the site. |
| manga weeaboo					| Expired domain #13488  |
| manga weed 					| 	Expired domain |
| manga347						| Not loading library |
| manga47						| 	Expired domain |
| manga4all 					| 	Not loading the chapters of manga |
| manga68.net					| 	Expired domain |
| mangadogs.fun					| Expired domain |
| mangadrago					| 	Expired domain |
| mangafort						| Expired domain |
| mangakitsune					| Not showing library |
| mangalime						| Expired domain |
| mangamax						| Expired domain #13898  |
| mangamoli						| Expired domain |
| mangarex						| Expired domain |
| mangarock.es					| Expired domain |
| mangarok						| Error in loading manga info |
| mangasmile					| 	Abandoned website |
| mangatk						| 	Expired domain |
| mangawise						| Expired domain |
| mangaxp						| 	Not showing library |
| mangayami						| 404 on try to load chapters |
| mangakakalots (unoriginal)	| 	Expired domain |
| mangas18						| Expired domain |
| mangazuki.me					| Expired domain |
| manhua raw					| 	Expired domain |
| manhuabox						| Expired domain probaly |
| manhuachill					| 	Abandoned website |
| manhuadex						| Expired domain |
| manhuamanga.net				| 	Abandoned website no more images for the chapter |
| manhalo						| 	Expired domain |
| manhwa chill					| Expired domain or Abandoned website |
| manhwaclub					| 	Abandoned website probaly |
| manhwamanga.net				| 	Not loading library |
| manhwanelo					| 	Expired domain |
| manhwaxz						| Expired domain |
| manhwaraw.net					| Expired domain |
| manycomic						| Not loading library |
| martialscans					| Expired domain |
| merakiscans					| 	redirect to asure manga |
| method scans					| Expired domain |
| mhmanga						| 	Expired domain |
| mykomiks						| Expired domain |
| mystical merries				| Not loading library |
| nineanime						| chapter load error all_imgsurl error #13315  |
| non-stop scans				| 	Expired domain |
| oh no manga					| 	Abandoned website |
| pomanga						| 	Expired domain or Abandoned website |
| rain of snow					| novel text base site |
| random scans					| Expired domain |
| random translations			| 	Expired domain |
| raw-manga						| Not loading the chapters of manga |
| readmangafox					| Expired domain |
| remoscans						| Expired domain |
| renascence scans (renascans)	|	Expired domain |
| seafoam scans					|	Expired domain |
| shield manga					|	access denied problaly Abandoned website |
| silent manga audition			|	text base site? |
| skull scans					|	Expired domain |
| skyraws						|	Expired domain |
| skymanga						|	Expired domain |
| sleepy panda scans 			|	Expired domain |
| supermanga					|	Expired domain |
| tappytoon.net					|	No more website. just ask to download the app |
| the cat scans					|	Expired domain |
| timelessleaf					|	The creator will stop supporting the site soon. |
| todaymic						|	Not loading library |
| unemployed					|	Expired domain |
| webtoon18						|	Expired domain |
| webcomics 					|	Not loading library #10959 |
| webtoonstop					|	Timeout |
| white cloud pavilion			|	404 |
| zahard						|	Not loading library #13491 |
| bsasmenu.com					|	Expired domain |

### Other details

I just checked if it was open in the application, if it was loading any manga chapter and webview, I didn't go after to see if the domain was changed.

I tested from Brazil without VPN

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
fixed autoclose, readmangafox was the one causing issues since it matches with mangafox regex

also, could you make it into a markdown table so that its a bit more easier to read?
| Source Name | Reason |
|--------------|--------|
|   Name1          | Reason1 |
| Name2           |   Reason2 |

**Comment by MrChuw** [comment]
> could you make it into a markdown table so that its a bit more easier to read?

I can do yes I hadn't seen how the preview turned out.

**Comment by HeroSharma** [comment]
Shield manga probably region blocked for you
Shield manga showing http error 400 while working in webview

**Comment by alessandrojean** [comment]
Will be closed by #13911. As one issue for a bunch of sources makes tracking difficult, this one will be closed after the PR merge. The remaining sources with problems should be made into individual issues.
