### ISSUE TITLE
Reaper Scans (English): JSON parse failing, again

### ISSUE THREAD

**Issue by psychopomp9** [tachiyomiorg/tachiyomi-extensions#13916]
### Source information and language

Reaper scans 1.3.38

### Steps to reproduce

1. Open a manga
2. Try to update it

### Expected behavior

It should update the manga, and add new chapters

### Actual behavior

Giving JSON error as Toast

### Tachiyomi version

0.13.6

### Android version

Android 9

### Other details

![Screenshot_2022-10-18-17-22-33-328_eu kanade tachiyomi](https://user-images.githubusercontent.com/67730075/196548068-c05e8f3e-5c25-4146-a3ed-7df7531eab7b.jpg)
Adding ss

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
Happens on Android 12 as well, I think the android version is unrelated.

**Comment by TechNaWolf** [comment]
Also in android 12 experiencing the same issue.
