### ISSUE TITLE
Kemono: No results found due to site redesign

### ISSUE THREAD

**Issue by Redactx** [tachiyomiorg/tachiyomi-extensions#13928]
### Source information and language

Kemono 1.3.3 (Latest)

### Steps to reproduce

1. Simply attempt to open Kemono under any circumstance. (Sources » Kemono)

### Expected behavior

Extension should work normally and show results. 

### Actual behavior

Kemono doesn't show any results, and can solely be accessed via Webview.

### Tachiyomi version

Version 0.1.3.6 

### Android version

Android 11

### Other details

Kemono has recently recieved a UI overhaul, possibly rendering previous access methods obsolete. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As a side note, search and chapters still work fine, just the popular/latest listings that needs to be fixed.

**Comment by Redactx** [comment]
> As a side note, search and chapters still work fine, just the popular/latest listings that needs to be fixed.

Ah! I forgot to include that, but I experience that as well.
