### ISSUE TITLE
Unable to update library or view new chapters for Reaper Scans extension

### ISSUE THREAD

**Issue by NerdEmbryo** [tachiyomiorg/tachiyomi-extensions#13922]
### Source information and language

Reaper Scans 1.3.38 (english)

### Steps to reproduce

1. Add Manhwas to library from this extension
2. click update library

### Expected behavior

When pressing update, the app searches for any new chapter is released or not

### Actual behavior

It doesnt update and shows update failed with error showing:
"expected start of the object '{', but had 'EOF' 
instead at path: $
JSON input: .....si":100}'
crossorigin="anonymous"></script.
</body>
</html>
![ReaperScans Error](https://user-images.githubusercontent.com/116137957/196596385-4f7f8df4-3772-4b98-a08c-272c8cc39064.jpeg)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NerdEmbryo** [comment]
Previously in extension version 1.3.37(english)
while trying to update it showed:
couldnt find livewire data
but webview was working fine

**Comment by ArjixWasTaken** [comment]
This ain't a new ticket, did you really search?

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13916

**Comment by NerdEmbryo** [comment]
> This ain't a new ticket, did you really search?
> 
> #13916

im sorry im new to this.
i tried searching with reaper scans as keyword and checked bith open and closed issue.
i swear this one didnt come up when i searched earlier.
im sorry for this.
