### ISSUE TITLE
Pop-up error when cheking for updates

### ISSUE THREAD

**Issue by Bigleone** [tachiyomiorg/tachiyomi-extensions#13925]
### Source information and language

Reaperscana 1.3.38 english

### Steps to reproduce

1. Opening latest on the source
2. Opening a comic
3. Scroll down to check for new capters
4. Error pop up
![Screenshot_20221019-160449_Tachiyomi](https://user-images.githubusercontent.com/23405336/196715766-0a743bd9-938f-42f6-bd8a-f04cfab819f7.jpg)

### Expected behavior

It should check if there are new chapters

### Actual behavior

An error pops up

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NerdEmbryo** [comment]
#13916 same issue already posted
