### ISSUE TITLE
Reaper Scans (English): Some pages doesn't load

### ISSUE THREAD

**Issue by cmurabito5** [tachiyomiorg/tachiyomi-extensions#13936]
### Source information and language

Reaper scans 1.3.39

### Steps to reproduce

1) Open tachiyomi sy
2) search the reaper scans extension
3) open any manga
4) click on any chapter

### Expected behavior

Pages should be loaded as same as the webview. 

### Actual behavior

2 pages keeps on loading even if the rest of chapter is loaded.. These 2 pages are not existent in webview. 

Webview:
![IMG_20221020_221333](https://user-images.githubusercontent.com/97380054/197013225-62b4694b-ec46-4a00-94a8-86775a80150e.jpg)

In app:
![IMG_20221020_221313](https://user-images.githubusercontent.com/97380054/197013239-fe9fdfc7-55aa-4332-8aa4-38dd64efcf14.jpg)

### Tachiyomi version

App version: 1.8.5 (standard, 57351c68d, 42, 2022-10-18T21:58Z) Preview build: 484 Android version: 12 (SDK 31) Android build ID: SKQ1.211006.001 test-keys Device brand: Xiaomi Device manufacturer: Xiaomi Device name: zeus Device model: 2201122G Device product name: zeus_in

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by aykirito** [comment]
unable to reproduce. i able load any manga chapter perfectly. have you considering clear cache within app?

**Comment by cmurabito5** [comment]
> unable to reproduce. i able load any manga chapter perfectly. have you considering clear cache within app?
> 
> Edited: using Tachiyomi 1.13.6 (not SY)

Still the same.. I am still able to reproduce after clearing cache and clearing cookies within the extension.

**Comment by thu2468** [comment]
i think it happening when u change user agent

**Comment by Gusser93** [comment]
Still getting same error as discribed in  #14819. Using 
App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 10 (SDK 29)
Android build ID: 52.1.A.3.49
And plugin version
1.3.41
Tachiyomi is reinstalled. Caches and Co are cleard. User-Agent is the default one. I tried the user-agent from my working browser, but that fails too.
Testet from germany, even tried Cloudflare DoH.
