### ISSUE TITLE
Extension 

### ISSUE THREAD

**Issue by Napierx** [tachiyomiorg/tachiyomi-extensions#13930]
### Source information and language

Reaper scan 1.3.38

### Steps to reproduce

Not updating

### Expected behavior

Update properly

### Actual behavior

![Screenshot_2022-10-20-09-19-38-056_eu kanade tachiyomi](https://user-images.githubusercontent.com/115440569/196852123-2e62148b-684c-4f84-9637-4adf5ddc4ae5.jpg)

### Tachiyomi version

1.3.38

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NerdEmbryo** [comment]
#13916 same issue as this one
