### ISSUE TITLE
Omega Scans: Some pages doesn't get downloaded

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi-extensions#13943]
### Source information and language

Omega Scans 1.3.21 (English)

### Steps to reproduce

Go to the webtoon "Not Friends" and try to download chapter 7 and chapter 12.

### Expected behavior

It should download like a normal chapter.

### Actual behavior

For some reason, page 1 from ch7 won't get downloaded and page 8 from ch12 won't get split.

### Tachiyomi version

r5071

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hyoretsu** [comment]
*page 5 from chapter 12. Both load fine in WebView.

**Comment by hyoretsu** [comment]
I'd disabled error notifications so I didn't know this, but the HTTP error's 504

**Comment by stevenyomi** [comment]
See #15949
