### ISSUE TITLE
Clayrer: HTTP error 404

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#13946]
### Source information and language

Clayrer 1.3.21

### Steps to reproduce

No funciona sale error 404
![Uploading Screenshot_2022-10-21-22-58-47-385_eu.kanade.tachiyomi.jpg…]()

### Expected behavior

Debería verse los manhwas

### Actual behavior

Aparece error 404 y la página original si funciona
![Screenshot_2022-10-21-22-58-47-385_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/197287787-c10935a6-af82-4d2b-9648-e983d1711844.jpg)
![Screenshot_2022-10-21-22-58-59-442_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/197287790-29774f85-9ea5-4088-9723-6502e26104a1.jpg)

### Tachiyomi version

0.13.6

### Android version

Miui 13.0.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
That site is making changes to the theme code.

**Comment by Riztard** [comment]
cant reproduce, its working
