### ISSUE TITLE
ReadComicOnline: Pagination is broken

### ISSUE THREAD

**Issue by lvlahraam** [tachiyomiorg/tachiyomi-extensions#13941]
### Source information and language

ReadComicOnline 1.3.13

### Steps to reproduce

Ok, so I'm trying to read the "Saga" comic that was in 2012 but when I search for it since the search in the app is sorted in alphabetical and the search limit by the extension is 32
I can't access or find the comic

### Expected behavior

To show more than 32 comics when searched

### Actual behavior

It would be better to make the search limit more than 32 or sort the comics in popularity or make it possible to search with the url from the website or you could add more options to filter, cause even after that I had selected the genre for the comic the search result didn't change at all

### Tachiyomi version

0.13.6

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lvlahraam** [comment]
Sorry I wrote the name for the extension so Wrong..., It's ReadComicOnline

**Comment by stevenyomi** [comment]
Just edit the title and content yourself.

**Comment by Ehssank** [comment]
> Just edit the title and content yourself.

How would one do this? I signed up for an account on the website but there is no option to Edit existing titles. I'm really happy this extension returned but I must admit that this bug is annoying. Not a big deal but annoying nonetheless.

**Comment by stevenyomi** [comment]
> How would one do this?

This is a reply to the original poster typing the name of the extension wrong. They deleted their reply of this typo after editing.

You should just wait for someone to fix it or migrate.
