### ISSUE TITLE
Baozi Manhua: HTTP error 403

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#13949]
### Source information and language

中文 1.3.12

### Steps to reproduce

Unable to connect to website

### Expected behavior

Able to search and browse

### Actual behavior

Http error 403

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
The website is working just fine over here. Can you add more info?

**Comment by Bishopop6** [comment]
Sorry for the inconvenience, the source did not work yesterday but I tried
it today and its working fine. Please carry on and close the issue. Thank
you.

**Comment by Clouddark75** [comment]
> Sorry for the inconvenience, the source did not work yesterday but I tried it today and its working fine. Please carry on and close the issue. Thank you.

Cool, probably the site was down.

@alessandrojean, you can close this one.
