### ISSUE TITLE
Multporn new adress

### ISSUE THREAD

**Issue by Romb38** [tachiyomiorg/tachiyomi-extensions#13956]
### Source information and language

Multporn (English)

### Source new URL

multporn.xxx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
the current address still works, and even on their website, i don't see anything mentioning multporn.xxx but instead 2.multporn.net, so probably just a copy cat

**Comment by alessandrojean** [comment]
What Seishirou said. Open a Source request issue if you want this new one to be added instead.
