### ISSUE TITLE
List with sources that can be removed and sources that needs the NSFW label

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi-extensions#13958]
### Describe why this should be added

|          **Source**           |              **Expired domain**               | **Issue** |
| :---------------------------: | :-------------------------------------------: | :-------: |
|           yuri-ism            |                Expired domain                 |           |
|  read webcomic manga online   |                Expired domain                 |           |
|      read solo leveling       | Expired domain probaly (ssl handshake failed) |           |
| read nanatsu no taizai manga  |                Expired domain                 |           |
|         read jojolion         |                Expired domain                 |           |
|           mangatoro           |      Expired domain or Abandoned website      |           |
|         letltgo scans         |                Expired Domain                 |           |
|     hajime no ippo manga      |                Expired domanin                |           |
|        assorted scans         |                Expired domain                 |           |
|           gogoscans           |                Expired domain                 |           |
|           comicdom            |                Expired domain                 |           |
|          24hromance           |            probaly Expired domain             |           |
|   read one punch man online   | Expired domain probaly (ssl handshake failed) |           |
|    read black clover manga    |  Probaly Expired domain or Abandoned website  |           |
|          mangasmile           |      Expired domain or Abandoned website      |           |
| read kaguya-sama: love is war |                Expired domain                 |           |
|          arc-relight          |                Expired domain                 |           |
|         timelessleaf          | The creator will stop supporting the site soon. |           |

-------------------------------------------------------------------------------------------------------

Here are 3 sources that I think should be marked as +18 as most of the content on the sites consists of hentai.

| **Source** |                        **Expired domain**                         | **Issue** |
| :--------: | :---------------------------------------------------------------: | :-------: |
| mangazuki  |                    only hentai missing tag +18                    |           |
|  mangairo  | Large amount of hentai content, it would be good to put tag +18 |           |
|  boyslove  |                    only hentai missing tag +18                    |           |

### Other details

timelessleaf: https://timelessleaf.com/2022/09/26/important-announcement-dear-all-readers/

I have nothing to add besides again, all tested from Brazil without VPN.

Just to vent, I think it would be good to remove the sources that are only from a manga, as most stop working after the manga hype dies.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> I think it would be good to remove the sources that are only from a manga, as most stop working after the manga hype dies.

The existing sources for these websites exist because it's easy to add them, as they all use the same theme. If they die a time after the hype or not, not really something we have control.

**Comment by alessandrojean** [comment]
Arc-Relight doesn't have an expired domain also, it's working perfectly fine.
