### ISSUE TITLE
Legion Scan: No results found

### ISSUE THREAD

**Issue by Skygio** [tachiyomiorg/tachiyomi-extensions#13957]
### Source information and language

Legion Scan 1.3.21 (Español)

### Steps to reproduce

Can't find manga library

### Expected behavior

Load manga library

### Actual behavior

Can't find manga library

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
Switched to Madara from MangaThemesia

**Comment by Lenoyr** [comment]
Same problem
