### ISSUE TITLE
YugenMangas (Spanish): Changing the series URL every time 

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#13950]
### Source information and language

Yugenmangas 1.3.3 (español)

### Steps to reproduce

Los capítulos no actualizan en tachiyomi, sale como que hay un error cuando entras en el manhwa desde Tachiyomi, pero si entras desde Chrome funciona bien el capitulo
![Screenshot_2022-10-22-18-20-49-354_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/197350466-5697b645-43e2-4e5d-a393-f491a17602eb.jpg)
![Screenshot_2022-10-22-18-22-44-530_com android chrome](https://user-images.githubusercontent.com/104227072/197350467-a252a4c1-92fe-4a36-a8d2-c99c25b16512.jpg)

### Expected behavior

Los capítulos deberían actualizarse sin problemas

### Actual behavior

Los capítulos aunque pone como que se ha actualizado, no actualizan
![Screenshot_2022-10-22-18-24-21-996_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/197350495-1ed66113-a495-4749-99c9-cf650a800b08.jpg)
![Screenshot_2022-10-22-18-24-51-510_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/197350501-ddf558fc-cbb6-46bc-8b13-13480f211877.jpg)

### Tachiyomi version

0.13.6

### Android version

Miui 13.0.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They started changing the series URL every new chapter they release. Wait for a extension update that may fix that, but it's not guaranteed. Consider starting migrating to better sources that doesn't have this bad behavior with the URLs.

**Comment by Clouddark75** [comment]
Is the theme code itself, the creator keeps making changes and improvements to the code, it applies to Reaperscans BR too, so yugenmangas haven't much to do with it. Wish I could help with this one, you can't apply an variant for the last part of the Manga url title?

**Comment by Clouddark75** [comment]
> They started changing the series URL every new chapter they release. Wait for a extension update that may fix that, but it's not guaranteed. Consider starting migrating to better sources that doesn't have this bad behavior with the URLs.

Is the theme code itself, the creator keeps making changes and improvements to the code, it applies to Reaperscans BR too, so yugenmangas haven't much to do with it. Wish I could help with this one, you can't apply an variant for the last part of the Manga url title?

**Comment by alessandrojean** [comment]
Yes, they're changing stuff, but they changing the series URL every new chapter they release is a intentional feature to break apps like Tachiyomi.
