### ISSUE TITLE
Manga PLUS: JSON parsing is failing

### ISSUE THREAD

**Issue by atmazzerexe** [tachiyomiorg/tachiyomi-extensions#13951]
### Source information and language

MANGA Plus by SHUEISHA 1.3.38 (English)

### Steps to reproduce

1. Go to "Browse"
2. Open Manga Plus as your source

### Expected behavior

You will be able to browse the source.

### Actual behavior

![Nox_2022-10-23_00-26-27_9CBDR6CoVL](https://user-images.githubusercontent.com/14852623/197354137-2cfe164e-a593-4212-85a0-4211cb0935c1.png)

### Tachiyomi version

r5085

### Android version

Android 11

### Other details

This bug doesn't affect existing manga on your library, you still can read it from there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Uh, they certainly forgot to set the author value for some series. Can be fixed on the extension side though, wait for an update.

**Comment by curche** [comment]
yep, there's no author for 53rd entry in the json
<img width="721" alt="Screen Shot 2022-10-22 at 13 08 27" src="https://user-images.githubusercontent.com/72807749/197356151-44f58292-e345-4e3c-815a-95957e83d4ad.png">
