### ISSUE TITLE
Manga Leveling: Time the chapter was posted in the chapter title

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi-extensions#13962]
### Source information and language

manga leveling

### Steps to reproduce

1. Open the source
2. Choose one manga
3. See the chapter names

### Expected behavior

Only the chapters name.

### Actual behavior

Time the chapter was posted in the title

### Tachiyomi version

J2K v1.5.9

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
Theme code needs to be updated to get chapter name using a different selector.
`chapter.name = urlElement.text()`
