### ISSUE TITLE
Manga4all: No chapters found

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi-extensions#13964]
### Source information and language

manga4all 1.3.27

### Steps to reproduce

1. Open the source.
2. Choose one manga.
3. Open.

### Expected behavior

Load manga chapters

### Actual behavior

Not loading the chapters of manga

### Tachiyomi version

J2K v1.5.9

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
Address now redirecting to https://www.mangalilo.com/

**Comment by Riztard** [comment]
probably just remove and add new ext since they also change their name

**Comment by abdulmannans** [comment]
@alessandrojean As they have changed their name we should close this.

**Comment by Riztard** [comment]
> Address now redirecting to [mangalilo.com](https://www.mangalilo.com/)

looks like the new one also dead
