### ISSUE TITLE
AZManhwa: HTTP error 404

### ISSUE THREAD

**Issue by Reduy** [tachiyomiorg/tachiyomi-extensions#13968]
### Source information and language

AZManhwa v1.3.24 English

### Steps to reproduce

1. Open the extension
2. Get HTTP error 404

### Expected behavior

Loads the source

### Actual behavior

Results in an error

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

![image](https://user-images.githubusercontent.com/37929793/197382921-be45df80-56ca-4dbf-a515-a269176a6ae2.png)

Others encountered same issue, but never reported it. They were asked to create a ticket but never did as it seems.

Webview works fine.

Thank you in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
@vetleledaal wdym by factory source? wat factory source?

**Comment by Riztard** [comment]
> It's in Madara, but didn't write a comment since this is a bug issue (read: existing extension) and not a source request issue.

does it change theme or just because its 'madara' you add a "factory source" tag?

**Comment by Riztard** [comment]
maybe need new tag 
![image](https://user-images.githubusercontent.com/16263232/205882740-a45a3a0c-5154-480b-ac32-09a1cd81d41c.png)
