### ISSUE TITLE
Kiara: No results found

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi-extensions#13961]
### Source information and language

kiara 1.3.24

### Steps to reproduce

1. Open the source

### Expected behavior

Load the library 

### Actual behavior

Not loading library 

### Tachiyomi version

J2K v1.5.9

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
For the next requests, please do specify what errors are you getting exactly, as "Not loading library" is very generic and doesn't help much to be honest.

**Comment by Riztard** [comment]
last update from their website `08 Jan 2022` also their chapter images seems dead/ cant be loaded

**Comment by Riztard** [comment]
seems like its dead
