### ISSUE TITLE
Scan Hentai Menu

### ISSUE THREAD

**Issue by Snakegreen020** [tachiyomiorg/tachiyomi-extensions#13975]
### Source name

Scan Hentai Menu

### Source link

https://scan.hentai.menu/

### Language

French

### Other details

https://scan.hentai.menu/manga/adopte-moi/chapitre-30/
Yes Site for over +18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by Snakegreen020** [comment]
Ok

Le jeu. 27 oct. 2022 à 12:16 PM, Vetle Ledaal ***@***.***> a
écrit :

**Comment by Snakegreen020** [comment]
I didn't know why I was unsubscribed but will this extension be released by the madara theme

**Comment by Snakegreen020** [comment]
I won't make the same mistake again but I would like to be subscribed again

**Comment by WoodlyBasquin56** [comment]
Can you tell me when it will be available

**Comment by Kreliam** [comment]
@KirinRaikage Madara

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage Tu peux l'ajouter au nouvelle extension

**Comment by Kreliam** [comment]
> T'inquiète pas c'est dans la boucle chef @WoodlyBasquin56 :p ; je ferai une pull request prochainement avec toutes les extensions françaises qui utilisent Madara

Après ça il reste plus beaucoup de site de scantrad français

**Comment by KirinRaikage** [comment]
Tu les utilises toutes ? Ou tu fais les demandes juste au cas où ?

**Comment by Kreliam** [comment]
> Tu les utilises toutes ? Ou tu fais les demandes juste au cas où ?
> 
> Le 30 juin 2023, 20:41 +0200, Kreliam ***@***.***>, a écrit :
> 
> > > T'inquiète pas c'est dans la boucle chef @WoodlyBasquin56 :p ; je ferai une pull request prochainement avec toutes les extensions françaises qui utilisent Madara
> 
> > Après ça il reste plus beaucoup de site de scantrad français
> 
> > —
> 
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > You are receiving this because you were mentioned.Message ID: ***@***.***>
> 
> 

J'ai fait les demandes sur le GitHub pour qu'il soit répertorié au cas où 

Par la suite j'ai cherché d'autre site de scan français sur internet je trouve que dés sites pas a jour ou des clones

**Comment by WoodlyBasquin56** [comment]
Je lis sur presque tout en faite

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage D'accord

**Comment by Kreliam** [comment]
@Snakegreen020
