### ISSUE TITLE
Koomanga: Redirect to Beetoon.net

### ISSUE THREAD

**Issue by MikeZeDev** [tachiyomiorg/tachiyomi-extensions#13977]
### Source information and language

Koomanga 1.3.6

### Source new URL

Beetoon.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Closing in favor of #15842
