### ISSUE TITLE
Heroxia

### ISSUE THREAD

**Issue by lunarpix** [tachiyomiorg/tachiyomi-extensions#13980]
### Source name

Heroxia

### Source link

https://www.heroxia.com

### Language

Indonesia

### Other details

18+/NFSW=YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Uses MangaThemesia theme

**Comment by alpqm** [comment]
Heroxia lengkap kah?

**Comment by TheKingTermux** [comment]
Update URL :

https://heroxia.com/

**Comment by TheKingTermux** [comment]
This issues already completed
But forget to add "Closes #......# in the PR
So can be closed now
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/14190
