### ISSUE TITLE
Manhwatop: Changed their domain

### ISSUE THREAD

**Issue by Striqes** [tachiyomiorg/tachiyomi-extensions#13984]
### Source information and language

Manhwatop 1.3.26

### Steps to reproduce

1. Go to any manhwa that is using the manhwatop extension.
2. Open WebView.
3. The WebView will not redirect to normal manhwatop site and will open a different site's home page.

### Expected behavior

WebView will redirect to chosen mahwa's page on manhwatop

### Actual behavior

Redirected to a different site causing the extension not to read anything.

### Tachiyomi version

0.13.6

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
Manhwatop change it's url into https://manhwamanhua.com/

**Comment by Riztard** [comment]
> Manhwatop change it's url into [manhwamanhua.com](https://manhwamanhua.com/)

their url still work? https://manhwatop.com

**Comment by stevenyomi** [comment]
https://manhwamanhua.com/ is a different site now.
