### ISSUE TITLE
InManga: Chapter images does not load

### ISSUE THREAD

**Issue by venom483746564** [tachiyomiorg/tachiyomi-extensions#13986]
### Source information and language

Inmanga 1.3.2 (español)

### Steps to reproduce

it's impossible to read any manga, the images don't charge

### Expected behavior

the images should charge

### Actual behavior

the images don't charge 

### Tachiyomi version

0.13.6

### Android version

Android 8

### Other details

fix it please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
I am able to load chapter pages, please check if this is a manga specific issue and also see if you are able to view it in web view.

**Comment by Seishirou101** [comment]
Since OP has not answered and just as suyash01 said, the few manga that I have checked seem to work fine. You may reopen with more details if the issue persists.
