### ISSUE TITLE
Ler Mangá

### ISSUE THREAD

**Issue by SrCrono** [tachiyomiorg/tachiyomi-extensions#13991]
### Source name

Ler Mangá

### Source link

https://lermanga.org

### Language

Brazilian Portuguese

### Other details

__

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by SrCrono** [comment]
Site changed theme

**Comment by Ruanss2000** [comment]
Há alguma ideia pra colocar esse site como fonte? Aparentemente esse tópico ja está aberto a um tempo

**Comment by alessandrojean** [comment]
Não há uma estimativa, fontes são adicionadas conforme os colaboradores tem tempo livre e desejam implementar algo. É um projeto de código aberto e sem fins lucrativos no fim das contas.
