### ISSUE TITLE
Batoto roundrobin mirrors

### ISSUE THREAD

**Issue by pigsflew** [tachiyomiorg/tachiyomi-extensions#13994]
### Source name and language

Batoto (All)

### Describe your suggested feature

When downloading actual pages from Bato, why not use their mirrors to distribute load?

Use the selected mirror to browse, search, and fetch metadata, roundrobin all currently available mirrors to download the actual page contents.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Having multiple mirrors is not same as having multiple server. You can have 100s of mirrors pointing to the same server.

Also bato.to's CDN server has no mirrors

**Comment by pigsflew** [comment]
Why do they bother with having so many mirrors at all then? Traditionally a "mirror" (e.g. for distributions of linux) is alternate hosting for the actual data which allows people to sort of "manually" distribute their load or choose a closer source for the data to hopefully improve retrieval and download speeds.

You can have a single domain hit a thousand servers, you *can* have multiple domains point to the same server, but neither of those cases would rightly be called "Mirrors".

The CDN being in front of the actual file downloads makes sense though. Thanks for responding!

**Comment by loocool2** [comment]
They keep getting banned from Google search and other search engines, and having all those mirrors is their attempt at dodging these bans
