### ISSUE TITLE
cloudflare extension

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi-extensions#14008]
### Source information and language

Constellar Scans 1.3.22 ( English)

### Steps to reproduce

![Screenshot_2022-10-28-01-01-46-325_eu kanade tachiyomi](https://user-images.githubusercontent.com/102795903/198419669-77d777a9-43a7-46e7-81b2-5e742cc7af59.jpg)

### Expected behavior

transcend cloudflare

### Actual behavior

just keep loading

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. *If it doesn't work, migrate to other sources or wait until they lower their protection.*

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
