### ISSUE TITLE
Yuri-ism

### ISSUE THREAD

**Issue by RealShadowFury** [tachiyomiorg/tachiyomi-extensions#14007]
### Source information and language

Yuri-ism

### Source new URL

https://yuri-ism.com/

### Other details

this source was mistakenly removed very recently, reported as NXDOMAIN. it has, in fact, just moved. the source was removed in the following commit: #13983 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their new website is just a WordPress blog with a improper structure to an extension and their online reader link redirects to a page in Dynasty Scans website with all their releases, which already have an extension and you likely can read their content there.
