### ISSUE TITLE
Sekaikomik: Chapter images doesn't load

### ISSUE THREAD

**Issue by Naruu76** [tachiyomiorg/tachiyomi-extensions#14017]
### Source information and language

Sekaikomik 1.3.29/Indonesian 

### Steps to reproduce

1. Open Sekaikomik Extension
2. Select a comic
3. Open a chapter
4. The image couldn't be loaded

### Expected behavior

Please fix the sekaikomik extension because the image can't be load

### Actual behavior

Doesn't load
![IMG_20221028_235448](https://user-images.githubusercontent.com/116903678/198691269-46e5c846-b6f8-4c05-9348-8f4477c8788c.jpg)

### Tachiyomi version

0.14.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Andreaslur** [comment]
Bro kok lu bisa akses sekai?

**Comment by Naruu76** [comment]
> 

Gk tau bro, tiba2 bisa aja sebelumnya kek lu jga. pdhl gk pake vpn

**Comment by TheKingTermux** [comment]
Perasaan bbrp hari lalu bisa 🙂
Kok skrg gk muncul ya 🙂

**Comment by Naruu76** [comment]
> Perasaan bbrp hari lalu bisa 🙂 Kok skrg gk muncul ya 🙂

Gk tau juga malahan kasusnya sama kek Doujindesu, Sektedoujin juga begitu🥲

**Comment by Raptor-bit** [comment]
Sekaikomik Changed their domain to: https://www.sekaikomik.pro/
