### ISSUE TITLE
Reaperscans extension not working

### ISSUE THREAD

**Issue by NoSc0pe** [tachiyomiorg/tachiyomi-extensions#14039]
### Source information and language

"Reaperscans 1.3.35 (multi)" 

### Steps to reproduce

1. Download reaperscans extension
2. Try to find reaper scans in sources 
3. It does not appear

### Expected behavior

It should appear in sources
And comics should load 

### Actual behavior

Extension not in sources
- previously working comics cannot load the links

### Tachiyomi version

0.14.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If you're trying to use their English website, install the Reaper Scans extension available under the English section, and not the Multi one. It was split from Multi as they changed their website theme.

**Comment by alessandrojean** [comment]
Closing in favour of the previous comment, if it's not the case please comment and it can be reopened.

Also there's this guide from Tachiyomi's Discord #status-update channel:

> The English Reaper Scans has been made into a standalone extension. To retain progress, install the new Reaper Scans extension available under the English section. If you haven't migrated already after the redesign, you will need to migrate from Reaper Scans to Reaper Scans to update the URLs. If you have already migrated, no extra migration is needed.
> 
> Note that Reaper Scans's search is terrible so it may require a manual search or trying different search terms to find the correct entry to migrate to.
> 
> If you're running into issues, try restarting the app.
> 
> Protip: If you only use the English source, you can now uninstall the All/Multi Reaper Scans extension.
