### ISSUE TITLE
Imhentai: Crashing the app while searching

### ISSUE THREAD

**Issue by DarkDissaster** [tachiyomiorg/tachiyomi-extensions#14034]
### Source information and language

Imhentai 1.3.8 Multi

### Steps to reproduce

1.abro la extensión
2.intento buscar la palabra "gerente"
3.se cierra la aplicación 

### Expected behavior

Debería darme el resultado de dicha búsqueda 

### Actual behavior

En su lugar me cerró la aplicación 

### Tachiyomi version

0.14.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
`v0.14.0` isn't the most updated version. Can you update to `v0.14.1` and check if it still happens?

**Comment by Seishirou101** [comment]
As the op has not responded, I will assume that the issue is fixed as I can't get it to crash, however the extension may not work correctly anyways #13051. Please reopen with a crashlog preferably in the app repo if the issue still occurs.
