### ISSUE TITLE
MangaDex: "First volume cover" setting also enables "Data saver"

### ISSUE THREAD

**Issue by MajorTanya** [tachiyomiorg/tachiyomi-extensions#14043]
### Source information and language

MangaDex 1.3.171

### Steps to reproduce

1. Go to the source settings section of MangaDex (any language seems to work)
2. Enable the new "First volume cover" setting
3. Go back to the language list
4. Open the same language's settings again
5. "First volume cover" and "Data saver" are both enabled

### Expected behavior

Only the first volume cover setting should be enabled

### Actual behavior

"First volume cover" and "Data saver" settings are both enabled

### Tachiyomi version

0.14.1

### Android version

Android 12

### Other details

App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_eea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Oops, good catch! Will fix this in a moment and submit a new update.
