### ISSUE TITLE
Komga: Tracker not working

### ISSUE THREAD

**Issue by JonatanCz** [tachiyomiorg/tachiyomi-extensions#14059]
### Source information and language

Komga (Multi 1.3.43)

### Steps to reproduce

1. Enable Komga tracker in settings
2. Add manga from Komga to library
3. Try to enable tracking for the manga

### Expected behavior

Tracking enabled, read progress should update

### Actual behavior

After opening tracker selection popup, a notification shows: "HTTP error 401"
After clicking "Add tracking", a notification shows: "No matching result was found" (translated - was in my system's language even though app language is set to English)
When I try to update read chapters in manga, which had the tracking already enabled "HTTP error 401" notification shows again.

### Tachiyomi version

Preview r5172 (cac80daa7, 10/30/22 10:45 PM)

### Android version

Android 11 (LineageOS)

### Other details

The tracking works normally in the stable version 0.14.1 (9.10.22 5:53 PM)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Tracking is handled by the app and not by the extension itself, so you should open the issue in the app repository actually.

**Comment by JonatanCz** [comment]
> Tracking is handled by the app and not by the extension itself, so you should open the issue in the app repository actually.

Oh, I didn't know that. Thank you, I will open the issue in the app repo as you told me to.
