### ISSUE TITLE
Hentai20: Changed their domain

### ISSUE THREAD

**Issue by Satwik-Sahu** [tachiyomiorg/tachiyomi-extensions#14050]
### Source information and language

Hentai20 1.3.26

### Source new URL

https://hentai20.io

### Other details

The extension webview goes to hentai20.s before redirecting to the new one. The Browse -> Sources leads to error 400. Going to site and opening a specific manga and then using Open in extension method also doesn't work as the supported web addresses for the extension is only the .s form.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by dejavui** [comment]
Closed #14477
