### ISSUE TITLE
"Open chapter in browser" opens API request result instead of web reader for some sources like MangaDex

### ISSUE THREAD

**Issue by hazu-89** [tachiyomiorg/tachiyomi-extensions#14051]
### Source information and language

MangaDex

### Steps to reproduce

1. Open a MangaDex chapter in the Tachiyomi reader
2. Click the topmost left button to open chapter in browser

### Expected behavior

The MangaDex web reader should open in webview with the selected chapter.

### Actual behavior

The result of the MangaDex API is opened in webview instead (`{"result":"ok","baseUrl":"...",...}`).

### Tachiyomi version

0.14.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Yeah, that's intentional for now while the extensions aren't updated to match the app updated code. When the forks add support to it it will be updated and fixed.

**Comment by hazu-89** [comment]
Thanks for clarifying! I'll leave the issue up until it's fixed for other people to see, if you don't mind.
