### ISSUE TITLE
Nana: Browsing is crashing the app

### ISSUE THREAD

**Issue by HikariHeaven** [tachiyomiorg/tachiyomi-extensions#14058]
### Source information and language

Nana 1.3.1 vers.

### Steps to reproduce

1. Just click Nana Ext in source.
2. Waiting
3. Suddenly, my tachiyomi is Force Close

### Expected behavior

This should happen where i can access nana normally

### Actual behavior

This happened instead where I tried to access it using tachiyomiJ2K and it worked.

### Tachiyomi version

0.14.1

### Android version

Android 11

### Other details

I tried use tachiyomiJ2K and it worked
I don't know why in tachiyomi is not worked & force close

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please provide the crash logs too.

**Comment by HikariHeaven** [comment]
--------- beginning of system
11-01 00:10:51.310 25027 25027 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
11-01 00:12:16.832 25027 25027 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
11-01 00:12:16.832 25027 25027 E ACRA    : java.lang.IllegalStateException: ResultSet returned more than 1 row for mangas.sq:getMangaByUrlAndSource
11-01 00:12:16.832 25027 25027 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsOneOrNull(Query.kt:46)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$awaitOneOrNull$2.invokeSuspend(AndroidDatabaseHandler.kt:44)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$awaitOneOrNull$2.invoke(AndroidDatabaseHandler.kt:13)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$dispatch$2.invokeSuspend(AndroidDatabaseHandler.kt:35)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$dispatch$2.invoke(AndroidDatabaseHandler.kt:11)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.TransactionContextKt$withTransaction$2$1$1.invokeSuspend(TransactionContext.kt:29)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:155)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:30)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:77)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.TransactionContextKt$withTransaction$2$1.invoke(TransactionContext.kt:18)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at com.squareup.sqldelight.TransacterImpl.transactionWithResult(Transacter.kt:36)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.TransactionContextKt$withTransaction$2.invokeSuspend(TransactionContext.kt:42)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:155)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:30)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:77)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:7)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at eu.kanade.data.TransactionContextKt$acquireTransactionThread$2$2.run(TransactionContext.kt:12)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-01 00:12:16.832 25027 25027 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
11-01 00:12:16.832 25027 25027 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@78d9e8d, Dispatchers.Main]
11-01 00:12:17.020 27544 27544 E .tachiyomi:acr: Unknown bits set in runtime_flags: 0x40000000
11-01 00:12:17.026 27544 27544 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
11-01 00:12:17.034 27544 27544 E RefClass: java.lang.reflect.InvocationTargetException
11-01 00:12:17.806 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:17.881 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:17.885 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:17.892 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:17.896 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:17.914 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:20.762 27605 27605 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
11-01 00:12:20.769 27605 27605 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
11-01 00:12:20.778 27605 27605 E RefClass: java.lang.reflect.InvocationTargetException
11-01 00:12:20.934 27605 27630 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.066 27605 27630 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.215 27605 27668 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.346 27605 27693 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
11-01 00:12:21.364 27605 27701 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:21.475 27605 27605 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
11-01 00:12:21.865 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.875 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.878 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.881 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.916 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.919 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:21.940 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:24.765 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:24.778 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:24.795 27544 27544 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:24.923 27544 27544 E ANR_LOG : >>> msg's executing time is too long
11-01 00:12:24.923 27544 27544 E ANR_LOG : Blocked msg = { when=-7s771ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 } , cost  = 7374 ms
11-01 00:12:24.924 27544 27544 E ANR_LOG : >>>Current msg List is:
11-01 00:12:24.924 27544 27544 E ANR_LOG : Current msg <1> = { when=-7s372ms what=0 target=android.app.job.JobServiceEngine$JobHandler obj=android.app.job.JobParameters@e95efc4 }
11-01 00:12:24.924 27544 27544 E ANR_LOG : Current msg <2> = { when=-6s938ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
11-01 00:12:24.925 27544 27544 E ANR_LOG : Current msg <3> = { when=-3s982ms what=0 target=android.os.Handler callback=rx.android.schedulers.LooperScheduler$ScheduledAction obj=rx.android.schedulers.LooperScheduler$HandlerWorker@a7cfead }
11-01 00:12:24.925 27544 27544 E ANR_LOG : Current msg <4> = { when=-54ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
11-01 00:12:24.925 27544 27544 E ANR_LOG : Current msg <5> = { when=-7ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
11-01 00:12:24.926 27544 27544 E ANR_LOG : Current msg <6> = { when=+943ms what=131 target=android.app.ActivityThread$H obj=android.app.ActivityThread$ProviderRefCount@5ce9d73 }
11-01 00:12:24.926 27544 27544 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
11-01 00:12:27.171 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:27.189 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:27.313 27605 27910 E SQLiteLog: (284) automatic index on C(manga_id)
11-01 00:12:27.313 27605 27910 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-01 00:12:28.011 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:28.081 27605 27605 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:28.083 27605 27605 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:28.084 27605 27605 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:28.087 27605 27605 E ANR_LOG : >>> msg's executing time is too long
11-01 00:12:28.087 27605 27605 E ANR_LOG : Blocked msg = { when=-7s292ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction LaunchActivityItem,ResumeActivityItem } , cost  = 6750 ms
11-01 00:12:28.087 27605 27605 E ANR_LOG : >>>Current msg List is:
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <1> = { when=-7s290ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction TopResumedActivityChangeItem, }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <2> = { when=-7s286ms what=9999 target=android.app.ActivityThread$H }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <3> = { when=-7s135ms what=0 target=android.view.Choreographer$FrameHandler callback=android.view.Choreographer$FrameDisplayEventReceiver }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <4> = { when=-7s103ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <5> = { when=-6s975ms what=149 target=android.app.ActivityThread$H obj=android.os.BinderProxy@df388eb }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <6> = { when=-6s912ms what=0 target=android.os.Handler callback=org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0 }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <7> = { when=-6s733ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
11-01 00:12:28.087 27605 27605 E ANR_LOG : Current msg <8> = { when=-6s571ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda1 }
11-01 00:12:28.088 27605 27605 E ANR_LOG : Current msg <9> = { when=-6s569ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda1 }
11-01 00:12:28.088 27605 27605 E ANR_LOG : Current msg <10> = { when=-6s552ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda1 }
11-01 00:12:28.088 27605 27605 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
11-01 00:12:28.264 27605 27698 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:28.274 27605 27698 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:28.287 27605 27698 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:28.293 27605 27698 E libEGL  : Invalid file path for libcolorx-loader.so
11-01 00:12:28.523 27605 27698 E ion     : ioctl c0044901 failed with code -1: Invalid argument
11-01 00:12:28.709 27605 27982 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:28.772 27605 27605 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:31.409 27605 27934 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:31.415 27605 27934 E Parcel  : Reading a NULL string not supported here.
11-01 00:12:31.492 27605 27934 E Parcel  : Reading a NULL string not supported here.
App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z)
Android version: 11 (SDK 30)
Android build ID: RMX2180_11_C.13
Device brand: realme
Device manufacturer: realme
Device name: RMX2180
Device model: RMX2180
Device product name: RMX2180T2

**Comment by curche** [comment]
Seems like an unexpected App bug, can you check if it still crashes in Preview version which might have fixed it?
Choose Preview from here. It installs as a separate app https://tachiyomi.org/download/
