### ISSUE TITLE
Bug Japscan - Unable to read and download 

### ISSUE THREAD

**Issue by kanidalo** [tachiyomiorg/tachiyomi-extensions#14088]
### Source information and language

Japscan 1.3.33

### Steps to reproduce

1. Refresh the manga/manhua etc..
2. The new chapter appears
3. Download the new chapter
4. Read the new chapter

### Expected behavior

Read and download the chapter

### Actual behavior

1. Refresh the manga/manhua etc.. OK
2. The new chapter appears OK
3. Download the new chapter NOT OK
4. Read the new chapter NOT OK

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

There is this problem only on some webtoons

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ugoschieli** [comment]
Same for me

**Comment by kanidalo** [comment]
With the latest update many chapters work again but not all of them especially the webtoons

**Comment by alessandrojean** [comment]
Closing as should be fixed by #14109. @kanidalo, please open a new issue about the webtoons and provide some examples there as well.
