### ISSUE TITLE
Kirei Cake: redirects to Dex group page

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#14089]
### Source information and language

Kirei Cake 1.3.3

### Steps to reproduce

Open series or extension browse
Tap webview

### Expected behavior

Should load series or series list

### Actual behavior

No results found

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

Site auto redirects to Dex. May be their notification that site is dying and being moved to just Dex uploads

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Drachenbar** [comment]
Got in touch with a member of the group who said the site is only down temporarily for maintenance and will be back up soon

**Comment by RunningDroid** [comment]
To update this:
- reader.kireicake.com returns NXDOMAIN
- kireicake.com loads but:
  - clicking the link to a manga just causes the cover of the manga to pop up
  - clicking the "read" button at the top redirects to the MangaDex group page (via a bit.ly link for some reason)

![Screenshot_20221219-212309.jpg](https://user-images.githubusercontent.com/486393/208567334-4a75ed73-07ed-44be-b6fb-886ca1d70364.jpg)
