### ISSUE TITLE
A url da extensão "Cerise scan" foi alterada.

### ISSUE THREAD

**Issue by Erick17x** [tachiyomiorg/tachiyomi-extensions#14085]
### Source information and language

Cerise Scans (pt-br)

### Source new URL

https://cerisescan.com

### Other details

A extensão "Cerise Scans" teve o URL alterado pelos proprietários, por favor altera-lo no aplicativo. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Update to 1.3.27 - [Link](https://tachiyomi.org/extensions/#pt.cerisescans)
