### ISSUE TITLE
Mangabat: Changed their domain

### ISSUE THREAD

**Issue by RocGoddess** [tachiyomiorg/tachiyomi-extensions#14080]
### Source information and language

Mangabat 1.3.9 (English)

### Steps to reproduce

1. Search for manga
2. Click manga under mangabat source
3. Message comes up saying "unable to resolve host "read.mangabat.com": no address associated with hostname"

### Expected behavior

Clicking on mangabat source should allow to access the manga on the working mangabat sites.

### Actual behavior

Instead, the manga opens on the defunct read.mangabat.com. This happens even for manga saved in my library that use the working sites. They still work and update like they should but if I search for them and click on magabat, the "unable to resolve host" message comes up.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_20221101-125108_Tachiyomi](https://user-images.githubusercontent.com/80088483/199236633-142aecdd-c305-4098-b30a-4bae1656b0c2.jpg)
![Screenshot_20221101-125115_Tachiyomi](https://user-images.githubusercontent.com/80088483/199236639-fc0aad85-ca53-4b8a-8743-6c70faf802d0.jpg)
![Screenshot_20221101-125127_Tachiyomi](https://user-images.githubusercontent.com/80088483/199236641-44e9cc6d-5a00-46c1-8f07-7e9ce9c43bbd.jpg)

These are screenshots showing the difference between a mangabat manga in my library and the same manga when accessed through search.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by abdulmannans** [comment]
@alessandrojean this issue is resolved and the URL is updated to the latest which is [this](https://h.mangabat.com/).
