### ISSUE TITLE
Japscan not updating / downloading

### ISSUE THREAD

**Issue by CesarMattaM** [tachiyomiorg/tachiyomi-extensions#14082]
### Source information and language

Release v0.14.2

### Steps to reproduce

Add japscan as a source
Try to download any manga

### Expected behavior

It should download

### Actual behavior

it dosen't download

### Tachiyomi version

Release v0.14.2

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The **JapScan** extension uses a very complicated method of accessing pages. If you encounter a manga that does not load or is scrambled, use a different source to read.
