### ISSUE TITLE
Option to choose scans on TuMangaOnline mangas

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#14095]
### Source name and language

TuMangaOnline (Español)

### Describe your suggested feature

I can't write, sorry in advance

To be able to choose the chapters of the scan (name of the scan) specifically that I want to appear only

• The option so that repeated chapters are not shown in the source configuration is useless when I only want to see the version of a scan but another scan takes a chapter first (as this is the case, the version of the chapter of the first scan that uploaded it appears to the web, while the version of the scan that I want to see does not appear)

• Filtering chapters is sometimes complicated, because I don't want to mark ALL the chapters so that I only get the ones from "that" scan. Then unchecking them and blah blah blah, is tedious, the "Unread" option is also useless, because when I want to start a manga with many chapters (like one piece, or bleach) and I only want to see the version of a scan, to be marking each chapter is even more tedious (although it is the same as filtering with the favorites mark)

In short, the option to block scans by UUID of MangaDex but in reverse in TuMangaOnline

### Other details

![IMG_20221101_222815](https://user-images.githubusercontent.com/101371218/199400195-786fba0f-3355-4e94-b809-705e2540bb88.jpg)

Something like that, obviously better visually

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AncientCatz** [comment]
You mean like a filter?

**Comment by edmxn** [comment]
> You mean like a filter?

Hmm, yes

**Comment by alessandrojean** [comment]
In the way you worded and by the screenshot that would be an app feature request and not an extension one. That being said, there's already an issue about sources like that in the app repository that's open.
