### ISSUE TITLE
Manhuas.net: Remove unnecessary words from title

### ISSUE THREAD

**Issue by AncientCatz** [tachiyomiorg/tachiyomi-extensions#14096]
### Source name and language

Manhuaus.net (English)

### Describe your suggested feature

_I want to remove some unnecessary words but for some reason I can't fork this repo, so I submitted this issue._

Using replace function and regEx pattern, it should be like this
![IMG_20221102_105916](https://user-images.githubusercontent.com/69200720/199405171-c8af34f9-e03a-4b0b-b91a-9463c941f7cb.jpg)

### Other details

Replace function with regEx:
`.replace("<regEx pattern with escaped special characters>".toRegex(), "")`
or
`.replace("""<regEx pattern>""".toRegex, "")`
regEx pattern for chapter; `.+?(?=(?<=[a-zA-Z]\s)([a-z]+\s[0-9]+$))` or `.+?(?=chapter|Chapter)`
regEx function for title; `"\\s(manhua)$".toRegex(setOf(IGNORE_CASE)`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We only need to remove manhua from title since the app removes entry title from chapter

**Comment by AncientCatz** [comment]
> We only need to remove manhua from title since the app removes entry title from chapter 

So can't? I tried it with Aniyomi extension and it worked

**Comment by alessandrojean** [comment]
That's just a HTML selector that needs to be tweaked in the override as the source uses Madara IIRC.

**Comment by AntsyLich** [comment]
> That's just a HTML selector that needs to be tweaked in the override as the source uses Madara IIRC.

No the word are actually appended to the title. Manhwa has "manhwa" appended to its title

**Comment by alessandrojean** [comment]
That's bad, but okay...
