### ISSUE TITLE
NETCOMICS: Popular page problem 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#14092]
### Source information and language

NETCOMICS (ID)

### Steps to reproduce

Open source
Go to popular selector
No more pages

### Expected behavior

Showing a popular manga 

### Actual behavior

Error no more pages
![Screenshot_2022-11-02-08-17-01-79_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/199372064-eb18d8d4-539d-4d47-b9e3-55749df22bcf.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The site doesn't show anything at https://www.netcomics.com/free when the language is set to "Bahasa Indonesia", which is how the extension checks for popular manga

**Comment by TheKingTermux** [comment]
Ohh I see
Thanks for answering my issues
