### ISSUE TITLE
Mcreader.net: Chapter images does not load

### ISSUE THREAD

**Issue by Dorakku** [tachiyomiorg/tachiyomi-extensions#14108]
### Source information and language

mcreader.net 1.3.16

### Steps to reproduce

1. Pick any manga and chapter
1. Manga pages don't load in Tachiyomi but work in web view

### Expected behavior

When you read any manga chapter it loads using the tachiyomi app so you may scroll

### Actual behavior

Manga pages dont load at all but loads when using web view version

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arhamsc** [comment]
I am also facing the same issue after I changed the user string to my device user string for the source Readkomik to work. As readkomik uses cloud flare it doesn't let me in unless I change the user string. But when I do so, mc reader does not load the chapters even though they load in web view.

**Comment by Dorakku** [comment]
Found the solution to the problem of mcreader source not loading images. the DOMAIN of mcreader.net was changed to mreader.net.

**Comment by DchanN** [comment]
> Found the solution to the problem of mcreader source not loading images. the DOMAIN of mcreader.net was changed to mreader.net.

already change a month ago by this pull request https://github.com/tachiyomiorg/tachiyomi-extensions/pull/13728 , it's like related to user agent string try reset or change it, in my case, resetting user agent string to default make the chapter load

**Comment by njscorpion** [comment]
> 

Still the same

**Comment by arhamsc** [comment]
> > Found the solution to the problem of mcreader source not loading images. the DOMAIN of mcreader.net was changed to mreader.net.
> 
> already change a month ago by this pull request #13728 , it's like related to user agent string try reset or change it, in my case, resetting user agent string to default make the chapter load

I use Readkomik and MCReader mainly, Readmomik has cloud fare protection so i set changed default user string to my device's user string, readkomik works, but MCReader stops loading images in the reader.

**Comment by Seishirou101** [comment]
You will have to find one that works for both then, as this seems like a cloudflare issue, I will be closing. Please refer to https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues, as like dchanN says, it is working fine with the default user agent.
