### ISSUE TITLE
Don't know which wrapper to use, PLEASE HELP

### ISSUE THREAD

**Issue by sinnghabhay80** [tachiyomiorg/tachiyomi-extensions#14100]
### Source information and language

Tapas 1.3.18

### Steps to reproduce

Sorry to ask this in issue because I don't actually know where to ask this.

It happended when i was trying to make some changes in the tapastic.kt file 

### Expected behavior

I had contributed in fix/feature in tapastic.kt a while back and as  i remember it had tapasticGenerator at that time and it working fine and the extension was bbuilding an d running fine. 

### Actual behavior

The TapasticGenerator is probably gone now(idk), it chooses LibGenerator as default as of now but is not actually working in building the extension and giving the error

This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.2.1 or newer.

, can some one please tell me what wrapper to use for building Tapastic extension, I don't actually have a lot a experience in this arena so it would be helpful if anyone can help me as soon as possible. 

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

PLEASE HELP, I WOULD LIKE TO ADD SOME NEW THINGS TO THE TAPASTIC EXTENSION THAT I SPOTTED WHILE USING THE EXTENSION.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Just update your android plugin if you're using IntelliJ or use Android Studio. You can get help with programming stuff in the #programming channel on the official [Tachiyomi's Discord](https://discord.gg/tachiyomi).
