### ISSUE TITLE
failed to bypass cloudflare (Empire Webtoon)

### ISSUE THREAD

**Issue by euijoonyeo** [tachiyomiorg/tachiyomi-extensions#14114]
### Source information and language

"Empire Webtoon 1.3.25 (Arabic) "

### Steps to reproduce

1. I tried to read chapters
2. it failed and show failed to bypass cloudflare 

### Expected behavior

" the chapters should showing normally 

### Actual behavior

this happen instead failed to bypass cloudflare 

### Tachiyomi version

0.14.2

### Android version

Android 7

### Other details

I checked the webview and chapters running normally and there is no captcha to resolve 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
