### ISSUE TITLE
SISI GELAP: Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by FathiRaihan** [tachiyomiorg/tachiyomi-extensions#14112]
### Source information and language

SISI GELAP 1.3.27 (Indonesia) 

### Steps to reproduce

1. Open the SISI GELAP extension
2. Wait a while
3. And the following text will appear 
![Screenshot_2022-11-04-00-57-40-491_eu kanade tachiyomi](https://user-images.githubusercontent.com/107458534/199799757-4ada148e-b2ce-4072-97dd-1eb1232e5617.jpg)

### Expected behavior

![Screenshot_2022-11-04-00-57-49-192_eu kanade tachiyomi](https://user-images.githubusercontent.com/107458534/199799993-7cf83087-ecfe-4535-afb3-f68776dc88fe.jpg)

### Actual behavior

![Screenshot_2022-11-04-00-57-40-491_eu kanade tachiyomi](https://user-images.githubusercontent.com/107458534/199800861-40c31cfd-7a96-4930-a8a9-996d2b7233dc.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
