### ISSUE TITLE
Readkomik "failed to byp

### ISSUE THREAD

**Issue by pengzky43** [tachiyomiorg/tachiyomi-extensions#14116]
### Source information and language

Readkomik 1.3.22

### Steps to reproduce

1. Open Tachiyomi
2. Open Browse
3. Select readkomik
4. Click open webview

### Expected behavior

The website should load and bypass cloudfare protection.

### Actual behavior

The webview is stuck on cloudfare protection loading page. Always refreshes

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Site works by only changing the user agent to my chrome app user agent but make the Asurascans extension not work. Keeps showing "No Pages Found"
Used User agent:
Mozilla/5.0 (Linux; Android 11; 220333QAG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36
![Screenshot_2022-11-04-05-20-58-541_eu kanade tachiyomi](https://user-images.githubusercontent.com/74085963/199836573-5b9df3d8-34d9-4ea2-8edc-2e3aafa5214d.jpg)

![Screenshot_2022-11-04-05-16-35-872_eu kanade tachiyomi](https://user-images.githubusercontent.com/74085963/199835862-173a60d3-0cdf-435f-b283-88b06529124c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
