### ISSUE TITLE
Failed to bypass Cloudfare (Colored Manga)

### ISSUE THREAD

**Issue by Plawaan** [tachiyomiorg/tachiyomi-extensions#14113]
### Source information and language

Colored Manga 1.3.25 (English)

### Steps to reproduce

1. Download Colored Manga 1.3.25 Extension
2. Open Colored Manga Extension

### Expected behavior

Tachiyomi will show Colored Manga comics

### Actual behavior

Failed to bypass Cloudfare

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

1. I tried changing the user agent to be the same with my Chrome, Google, Firefox
2. No VPN or any DNS modification
3. I tried WIFI and Cellular Data
4. I tried changing DNS and followed the troubleshooting guide and tutorials via Reddit and Youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Some websites have a higher Cloudflare protection, and there's nothing we can do in the extension side to fix this if you already tried the listed solutions on the Tachiyomi website. The only thing you can do is wait for them to lower their Cloudflare protection or migrate to other sources.

**Comment by Plawaan** [comment]
Alright, thanks! 👍
