### ISSUE TITLE
Asura Scans: Changed their domain

### ISSUE THREAD

**Issue by pengzky43** [tachiyomiorg/tachiyomi-extensions#14110]
### Source information and language

Asurascans 1.3.22

### Source new URL

https://asura.gg

### Other details

Change of user agent makes chapter appear "No Pages found" even though it has pages shown during webview.
webview still works because it still redirects the old url to the new url.
Used User agent:
Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
About the user agent thing: use a desktop one and not a mobile one. It's known it doesn't work with mobile user agents.

**Comment by MajorTanya** [comment]
I can only see Asura Scans 1.3.37 in the extension list, and that seems to be loading fine

**Comment by pengzky43** [comment]
> About the user agent thing: use a desktop one and not a mobile one. It's known it doesn't work with mobile user agents.

Tried the default user agent but makes the other extension failed to bypass cloudfare. So i have to change every time i need to see updated cahoters on both extension.
