### ISSUE TITLE
Adult Painful Nightz (Failed to bypass Cloudflare)

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi-extensions#14119]
### Source information and language

Adult Painful Nightz 1.3.24 (English)

### Steps to reproduce

1. Open Tachiyomi and head over to Browse (Maghanap)
![image](https://user-images.githubusercontent.com/31158494/199869469-5a79f14e-eb1a-44b8-b7fc-38e5aca749d8.png)
2. On Sources Tab (Mga Source), tap on Adult Painful Nightz, then tap Open in WebView on the top right (or "Open in Webview" if it times out)
![image](https://user-images.githubusercontent.com/31158494/199869836-342be9c4-d5cc-4887-81d2-1913dd1a7e57.png)
3. Wait several seconds (or minutes) to do Cloudflare do its thing
![image](https://user-images.githubusercontent.com/31158494/199870192-e6098a88-d954-4310-a757-2ab813159a5f.png)
4. If it succeeds, the webpage should load and go back to the source to refresh the library.

### Expected behavior

Supposed to load the page after a few attempts. (I'm using Kiwi Browser with the Privacy Pass extension)
![image](https://user-images.githubusercontent.com/31158494/199870680-d2d90528-88ed-4d50-b872-8c3059950403.png)

### Actual behavior

Stuck on the Cloudflare loading screen for more than a minute 
![image](https://user-images.githubusercontent.com/31158494/199871144-c18cb0c3-6d41-4bab-b2dc-655f41562879.png)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

- Running with WSA version 2208.40000.5.0 on Windows 11 version 22H2 build 22621.675

![image](https://user-images.githubusercontent.com/31158494/199871669-765384aa-f38f-4875-81a7-a03d6b1b5c31.png)

- I'm using Filipino here but added a little bit of English translation required to reproduce the issue
- I checked on the URL on the WebView had the cf_chl_rt_tk on its link, it should redirect to the page instead of being stuck on Cloudflare
- The ISP used here is PLDT (Philippines)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Some sources have a higher Cloudflare protection, and we can't do anything about it. As you already tried the listed solutions on the troubleshooting guide, only thing left to do is waiting until they lower their protection or migrate to other sources.
