### ISSUE TITLE
Alphascans java.security.cert.CertPathValidatorException

### ISSUE THREAD

**Issue by pengzky43** [tachiyomiorg/tachiyomi-extensions#14129]
### Source information and language

Alphascans 1.3.22

### Steps to reproduce

1. Open browse
2. Select alphascans

### Expected behavior

Manga should load here

### Actual behavior

![Screenshot_2022-11-05-13-49-57-920_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/74085963/200104655-b77b0ba7-e854-4ca8-aec5-463d78e8e9c6.jpg)

### Tachiyomi version

TachiJ2k 1.5.9

### Android version

Android 11

### Other details

While checking website in browser, it seems to changed into comic scans and give the new link to the site. They maybe change the site and url?
![Screenshot_2022-11-05-13-51-30-172_com android chrome](https://user-images.githubusercontent.com/74085963/200104717-f2700c53-ab04-461e-b5e9-8d4873cd67c8.jpg)
And the new link is [https://cosmicscans.com](https://cosmicscans.com) 
![Screenshot_2022-11-05-13-55-16-632_com android chrome](https://user-images.githubusercontent.com/74085963/200104836-e369a4d5-cd6c-425a-b7c3-d7667eb02a37.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Cosmic scans and alpha scans are different sources, alpha scans has shut down after the group leader went AWOL. Alpha scans will likely end up being completely removed and cosmic scans can be added as a new source.

**Comment by AntsyLich** [comment]
What loo said except a extension for Cosmic Scans already exists
