### ISSUE TITLE
Painful Nightz Scan (Failed to bypass Cloudflare)

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi-extensions#14120]
### Source information and language

Painful Nightz Scan 1.3.25

### Steps to reproduce

1. Open Tachiyomi and head over to Browse (Maghanap)
![image](https://user-images.githubusercontent.com/31158494/199872678-96b301b9-631e-4e13-985a-d770dd902420.png)

2. On Sources Tab (Mga Source), tap on Painful Nightz Scan, then tap Open in WebView on the top right (or "Open in Webview" if it times out)
![image](https://user-images.githubusercontent.com/31158494/199872891-bc50a341-ad9b-42aa-bcbd-8a0d20f76b47.png)

3. Wait several seconds (or minutes) to do Cloudflare do its thing
![image](https://user-images.githubusercontent.com/31158494/199872944-3aa75be2-2978-41fa-b566-9219763e993b.png)

4. If it succeeds, the webpage should load and go back to the source to refresh the library.

### Expected behavior

Supposed to load the page after a few attempts. (I'm using Kiwi Browser with the Privacy Pass extension)
![image](https://user-images.githubusercontent.com/31158494/199873126-368653e9-2281-4542-9249-cb755d588839.png)

### Actual behavior

Stuck on the Cloudflare resolve page for more than a minute
![image](https://user-images.githubusercontent.com/31158494/199873196-7530ec34-a2ca-4a78-8cf6-cb902e5239b4.png)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

- Running with WSA version 2208.40000.5.0 on Windows 11 version 22H2 build 22621.675

![image](https://user-images.githubusercontent.com/31158494/199871669-765384aa-f38f-4875-81a7-a03d6b1b5c31.png)

- I'm using Filipino here but added a little bit of English translation required to reproduce the issue
- I checked on the URL on the WebView had the cf_chl_rt_tk on its link, it should redirect to the page instead of being stuck on Cloudflare
- The ISP used here is PLDT (Philippines)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by amboris** [comment]
same for kissmanga.in

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
