### ISSUE TITLE
Unlimited Loop after opening webview for bypassing cloudflare

### ISSUE THREAD

**Issue by aruto77** [tachiyomiorg/tachiyomi-extensions#14128]
### Source information and language

WebtoonXYZ 1.3.27 (English)

### Steps to reproduce

1. Opening source
2. get a notification "failed to bypass cloudflare"
3. opening webview to verifying as human
4. after clicking verify only getting loop in same verifying page

### Expected behavior

After clicking/tapping verify in webview it should redirect to the web

### Actual behavior

But what happen is looping on cloudflare verifying page

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Serakna** [comment]
I've got the exact same problem with the KissManga extension
I hope that this is the right place
I just made my account exactly to write it here because i thought it could help

**Comment by MassinLaj** [comment]
Same problem with the Flamescans extension.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

That being said, some sources have a higher Cloudflare protection and we can't do anything about it. If the steps described in the guide doesn't work, only things left to do is migrate to other sources or wait until they lower their protection.
