### ISSUE TITLE
Flamescan Infinite Cloudflare Loading

### ISSUE THREAD

**Issue by XY0511** [tachiyomiorg/tachiyomi-extensions#14130]
### Source information and language

Flame Scans 1.3.23 Multi

### Steps to reproduce

Open Extension
Open WebView
Wait

### Expected behavior

It should complete it's cycle but it's just loops, it's not my internet cause I can open it in Browser but not in WebView

### Actual behavior

Just Loops

### Tachiyomi version

14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tsunaproxD** [comment]
Yep, can't pass the claudflare

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by tsunaproxD** [comment]
> i able to fixed failed to bypassed cloudflare by changing default agent string to: Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.91 Mobile Safari/537.36
> 
> make sure (Linux; Android 13) included if not it won't work on my test. im using android 8 btw
> 
> Give a try and let us know if it work on your end :)

Yessssss, this solve the problem thx men.
