### ISSUE TITLE
Comicextra extension isn't working 

### ISSUE THREAD

**Issue by Sersi001** [tachiyomiorg/tachiyomi-extensions#14133]
### Source information and language

Tachiyomi comicextra extension v 1.3.11

### Steps to reproduce

Kindly help on new working extension version of comicextra

### Expected behavior

To work

### Actual behavior

Not working 

### Tachiyomi version

Latest

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill correctly the fields and provide steps to reproduce and other information on what errors are you facing.

"Isn't working" doesn't help much, and it's pretty generic.
