### ISSUE TITLE
Apache source

### ISSUE THREAD

**Issue by DIEGOF132** [tachiyomiorg/tachiyomi-extensions#14138]
### Source name

Apache source

### Source link

https://localhost/

### Language

All

### Other details

Basically it would be an extension that would communicate with a server running Apache, and on the server we would leave all the files organized in the same way as we left them in the local source.

This extension would help in creating local servers. 

Note: I know of the existence of the "Komga" font, it helps in creating local fonts, but in my opinion it would be much more practical to upload everything to a web server (I put Apache, but Nginx would also be nice) via FTP or directly on the server mirroring the local font.

 I don't know if it's easy to do, I'm still venturing into the world of programming. 

Thank you very much for your attention! :) 

Note: I'm Brazilian, sorry for any spelling mistakes, my English is not very good, I'm using Google to help me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
essentially #11443 but it also has already been rejected before tachiyomiorg/tachiyomi#6422
