### ISSUE TITLE
Haoman6(g-lens): images doesn't load

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#14139]
### Source information and language

haoman6(g-lens)1.3.3

### Steps to reproduce

1.open Haoman6(g-lens) Extension
2.select a comic and open a chapter
3. The image couldn't be loaded

### Expected behavior

please fix the extension that image couldn't be loaded

### Actual behavior

The image couldn't be loaded

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Please provide manga name and chapter number.

**Comment by RX93CN** [comment]
I've checked again，the image can be loaded now, but It has not been loaded frequently in recent days. 
The vomic extension also can't load images frequently.

**Comment by RX93CN** [comment]
I've checked again，the image can be loaded now, but the image has not been loaded frequently in recent days.

**Comment by stevenyomi** [comment]
There's nothing much we can do. Same for vomic as it's an aggregator site.

**Comment by RX93CN** [comment]
Thanks for your  reply,maybe it's because of website or network problems .I'll think of another way to solve it. Then I will close this issue.
