### ISSUE TITLE
Alpha Scans Url Change

### ISSUE THREAD

**Issue by XY0511** [tachiyomiorg/tachiyomi-extensions#14131]
### Source information and language

Alpha Scans 1.3.22 (English)

### Source new URL

https://cosmicscans.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Alpha Scans' leader ran away after taking all the money so one of the admin took all their series under Cosmic Scans. This is not a url change and a extension for Cosmic Scans already exists
