### ISSUE TITLE
BestManhua: No results found

### ISSUE THREAD

**Issue by blaizeris** [tachiyomiorg/tachiyomi-extensions#14147]
### Source information and language

BestManhua 1.3.26 English

### Steps to reproduce

1.Open the extension ....this will show no results
2.Open webiew ...opens the site and manhua are present and available.

### Expected behavior

It should show the manhua that the website has.

### Actual behavior

Instead of showing manhua it says no results but when view in webview you can see all the manhua that should be there.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
looks like they change the website theme

**Comment by vetleledaal** [comment]
Reposting from the other issue (thanks @Clouddark75 ):
> The source uses liliana theme, and the images are loaded through ajax.
