### ISSUE TITLE
Problem in manga starz 

### ISSUE THREAD

**Issue by Abdullahele** [tachiyomiorg/tachiyomi-extensions#14146]
### Source information and language

Manga starz

### Steps to reproduce

 I don't have issue i want solution and fix it

### Expected behavior

I expected when i enter it work

### Actual behavior

I want when i enter it work and i can read any manga

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the information requested correctly and specify any error messages and issues you're getting. Closing as it lacks useful information.
