### ISSUE TITLE
Doujindesu still doesn't work 

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#14142]
### Source information and language

Doujindesu

### Steps to reproduce

1. Open doujindesu
2. Appear a doujin cover
3. Can be read 

### Expected behavior

Image appears in application, contents can be read, fast loading images 

### Actual behavior

Nothing appears and can't open anything 
![Screenshot_20221031-065926](https://user-images.githubusercontent.com/70476061/200165020-22cee58a-c7c8-489c-bff5-a56b19ea5065.png)
![Screenshot_20221031-065949](https://user-images.githubusercontent.com/70476061/200165023-9af3ff0f-c398-45f3-b418-d6b070ddffea.png)

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

Every time tachiyomi update always like this... Please help.
And can you make "koushoku" can be downloaded again? Please... 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
I think the bot just reading Koushoku instead Doujindesu
Yeah no problem
Because it a duplicate issues
