### ISSUE TITLE
Kissmanga.in failing on cloudflair with loop

### ISSUE THREAD

**Issue by cain0z** [tachiyomiorg/tachiyomi-extensions#14152]
### Source information and language

Kissmanga.in 1.3.26 

### Steps to reproduce

Extension shows blank screen and when clicking the Web view it just loops on finding if the device is secure. When opening in chrome it works as expected on the same device.

### Expected behavior

Manga loads in list and downloads as required.

### Actual behavior

Looping cloudflair 

### Tachiyomi version

App version: 1.5.9 jay2king

### Android version

Andriod 12

### Other details

Have cleared cookies for tachiyomi as well as removed and reinstalled the extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
