### ISSUE TITLE
Bulu Manga: Changed their domain

### ISSUE THREAD

**Issue by ChanchanReal** [tachiyomiorg/tachiyomi-extensions#14159]
### Source information and language

Bulu Manga 1.3.6

### Source new URL

https://ww3.beetoon.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by ChanchanReal** [comment]
Is this extension done done... . Up

**Comment by kaikamei9** [comment]
Any Update ?
