### ISSUE TITLE
Tachidesk: Search functionality

### ISSUE THREAD

**Issue by Sirver51** [tachiyomiorg/tachiyomi-extensions#14167]
### Source name and language

Tachidesk (All)

### Describe your suggested feature

Currently, attempting to search for a manga causes the extension to display "Only Empty search is supported!", meaning that manga has to be found by manual scrolling, which is inefficient when dealing with hundreds of entries. Search should instead work like it does on the WebUI i.e. via the search endpoint exposed by Tachidesk-Server (or via client-side filtering, if viable).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Sirver51** [comment]
Has anyone started work on this? If not, I will give it a try in the next couple of weeks. I've only tried Kotlin once and have never built anything for Android, but looking at the code it seems like it should be doable, even if the method I have in mind is a bit hacky.

**Comment by wychwitch** [comment]
I was about to open my own issue, when I stumbled across this.

Without search I cant migrate my library to suwayomi/tachidesk, even trying to perform an empty search doesnt work! I wouls love to not have to manually import everything

**Comment by Sirver51** [comment]
@wychwitch That's actually why I wanted the feature in the first place - without search, migration doesn't work. I just started work on trying to implement this myself yesterday, but I have no idea if I'll succeed.

The main issue is that Tachidesk itself doesn't implement a REST API for searches on the library, and only exposes that functionality via the front-end. This means that the extension has no easy endpoint to call for it, so the only way I can see to do this is to get the details of the entire library and search through it on the client side, which AFAIK is not how it's usually supposed to work - search should be handled by the server so that the results you get through the app and through the web are the same.

The biggest problem for me - apart from not knowing Kotlin and having no idea what half the syntax does - is that the function that handles search is supposed to return a Response object, which means that we have to make a bunch of requests to get all the library details, extract the JSON, merge them, filter them, manually construct a Response object with that final JSON, and return that. This might work just fine, or might cause all kinds of problems because of header mismatches or something - I honestly have no idea, and won't until I actually try it.

If one of the regular devs/maintainers could pitch in on whether this makes sense to do this way, that would be helpful. I considered trying to implement the search API functionality on the Tachidesk server side, but after a brief look through that code I think I'm slightly more confident in doing this than adding to that, at least for now. I don't see any issues relating to local library search via API on the Tachidesk repo, so I'll probably open one on the off-chance that it's trivial for them to implement and they just haven't bothered until now because it's available via the front-end.

**Comment by Sirver51** [comment]
So there's on crucial problem with my original idea of how to make this work: `searchMangaRequest` returns a `okhttp3.Request` (not a `okhttp3.Response`), which then gets executed by the main Tachiyomi app. This means that there's no proper way to implement the search on the client side like I was thinking unless we changed the main Tachiyomi code in ways that would likely break every other extension.

That said, I did work around this issue: I packaged the search results in the body of a POST `Request` object, pointed it at a dummy API that reflects the POST data back ([this is the one I used](https://jsonplaceholder.typicode.com/)), reformatted it to the correct format in `searchMangaParse`, and then passed it on to `popularMangaParse`. This works, and returns the search results correctly, albeit with a bit of stutter in the process (which may not come up for libraries smaller than mine).

Of course, this is a terrible way of doing things for any number of reasons, but especially because of the external dependency and requirement of internet access. Theoretically, I should just be able to point this at the main server endpoint and get the original `Request` object from the 404 `Response`, but the Tachiyomi app intercepts 404s and 500s and (understandably) doesn't continue the chain of execution in the extension, which means I'm stuck with the dummy API thing. Unfortunately, I can see no other way to do this on the extension side - the only way forward would be to modify the server side code. I will take another look at potentially doing that when I have time.

@alessandrojean, @arkon, @AriaMoradi - sorry to bother you, but from what I can see you're the ones with the most experience on this extension; could you give me a quick sanity check to make sure my conclusions are correct and that there isn't anything obvious I'm missing?

**Comment by alessandrojean** [comment]
> but the Tachiyomi app intercepts 404s and 500s

Just override the fetch methods and you can get rid of that. What checks for error status code is the `asObservableSuccess()`, which you can replace by `asObservable()` and handle all response codes by the extension side.

You should be able as well to just do a request to the list all entries endpoint appending the query as a fragment (`#$query`) in the URL and then getting the fragment in the `searchMangaParse` through `response.request.url.fragment!!`, which you can use to filter the response array by the query.

**Comment by AriaMoradi** [comment]
So, we decided to mostly implement resource management API on Tachidesk-Server and leave custom use cases to clients to implement.

About implementing this feature, I'd override `fetchSearchManga` from `eu.kanade.tachiyomi.source.online.HttpSource`, essentially you just need to construct a `MangasPage` object in cases that search query is not empty which I believe should be easy to implement once you have all the mangas fetched and are searching that string locally.

**Comment by Sirver51** [comment]
Thank you both for your input! I had seen the `fetchSearchManga` method in the contribution explainer, but assumed that it had been renamed or something when I didn't see it in the code; it didn't occur to me that I'd have to override it. Overriding that method and using `asObservable` instead did the trick, and search works about as I'd expect it to; I will submit the PR shortly.

A couple of notes:

> You should be able as well to just do a request to the list all entries endpoint appending the query as a fragment (`#$query`) in the URL and then getting the fragment in the `searchMangaParse` through `response.request.url.fragment!!`, which you can use to filter the response array by the query.
> 
> Alternatively, if you don't like the fragment way, you can send it as a query parameter, or through a header or even by a tag in the Request, any of them should work fine and you will be able to access it through the parse method.

I had thought of this, but didn't know if arbitrarily long headers and/or URLs would cause an issue - in my library, some of the categories have enough entries that the list is over 16KiB gzipped. Of course, it's better than what I ended up trying, but at that point I'd forgotten it was an option.

> So, we decided to mostly implement resource management API on Tachidesk-Server (we have to support a dozen clients and it doesn't make sense to cater to non-general needs) and leave custom use cases to clients to implement, If this proves to be too hard or resource consuming then you are free to make PRs to the server but that should not a search api, but more resource APIs as needed.

I understand the need to prioritize the general use case, but is it not a common requirement to search the user's full library? Especially since migration can't work without it?

> About implementing this feature, I'd override `fetchSearchManga` from `eu.kanade.tachiyomi.source.online.HttpSource`, essentially you just need to construct a `MangasPage` object in cases that search query is not empty by transforming the api result via a search reducer.

I think this is what I've ended up doing, but I'll admit I don't fully understand what that last part means - are you referring to filtering the results by the search query?

**Comment by Sirver51** [comment]
PR submitted, let me know if anything needs changing. Not sure I've done it right as it's my first one.
