### ISSUE TITLE
Mangalionz: Chapters do not load

### ISSUE THREAD

**Issue by Bokuiio6** [tachiyomiorg/tachiyomi-extensions#14160]
### Source information and language

Mangalionz 1.3.24 العربية

### Steps to reproduce

1. Make manga and manhwa available for reading in this site on the app
2. Make sure that the site are actually connected with the app
3. The problem is when I click on any chapter of any manga or manhwa in this site on the app it starts loading and at the end it not works 

### Expected behavior

Make the chapters of any manga in this site works in the app

### Actual behavior

Idk

### Tachiyomi version

0.14.2

### Android version

12

### Other details

![Screenshot_20221107_103651_eu kanade tachiyomi](https://user-images.githubusercontent.com/112907511/200263600-932633cb-861f-4f10-b19e-212ed0727ada.jpg)
![Screenshot_20221107_103628_eu kanade tachiyomi](https://user-images.githubusercontent.com/112907511/200263606-3883bc56-5e24-40d1-bb37-589e51f8bd3c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. If it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
