### ISSUE TITLE
vyvymanga error 500

### ISSUE THREAD

**Issue by RaidBuster** [tachiyomiorg/tachiyomi-extensions#14163]
### Source information and language

vyvymanga 1.3.3

### Steps to reproduce

Open vyvymanga

### Expected behavior

Normal

### Actual behavior

![Screenshot_2022-11-07-19-22-55-501_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/200310062-946517d3-9d13-4b3c-bc7d-f1877d75c5ac.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP error 5xx are server side errors, so check if the site is working fine on WebView first, it could be in maintenance for example.
