### ISSUE TITLE
Kissmanga Cloudflare not working

### ISSUE THREAD

**Issue by Shinryuuk** [tachiyomiorg/tachiyomi-extensions#14165]
### Source information and language

Kissmanga.in 1.3.26 (English)

### Steps to reproduce

Manga not updating
Opened extension
Opened Webview

### Expected behavior

Extension should have loaded
Webview should have loaded after refreshing the page & clearing cookies

### Actual behavior

Extension failed to bypass Cloudflare
Webview did not load even after refreshing & clearing cookies
After opening in browser only then did the page load

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

Kissmanga has not been updating for a few days already 
![Screenshot_20221107-204545_Tachiyomi](https://user-images.githubusercontent.com/117651695/200315962-210fcb7a-16b8-4482-9064-771413510003.jpg)
Webview also didn't work even after waiting for more than 5 minutes
![Screenshot_20221107-205146_Tachiyomi](https://user-images.githubusercontent.com/117651695/200315975-cff12a2b-d686-40ca-8460-a972b0fe18d7.jpg)
Only when the page was opened in browser did it work
![Screenshot_20221107-205211_Chrome](https://user-images.githubusercontent.com/117651695/200316610-7bb17578-8888-4a88-8e9b-7f9bf785488f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. **If it doesn't work, migrate to other sources or wait until they lower their protection.**

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
