### ISSUE TITLE
Manga Origines Cloudfare issue

### ISSUE THREAD

**Issue by anbzerc** [tachiyomiorg/tachiyomi-extensions#14173]
### Source information and language

Manga Origines 1.3.27(french / francais)

### Steps to reproduce

1. Open a manga from Manga Origines, Cloudfare error
2. Open a webview
3. Cloudfare check keep charging during ~5min and show a verify you're human button 
4. The button does not work

### Expected behavior

The mange should charge, and verify you're human button work 

### Actual behavior

The manga does not charge, and webview can't redolve Cloudfare issue

### Tachiyomi version

0.14.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
