### ISSUE TITLE
Reaper Scans Indonesia

### ISSUE THREAD

**Issue by fikiismyname** [tachiyomiorg/tachiyomi-extensions#14178]
### Source name

Reaper Scans 

### Source link

https://reaperscans.id/

### Language

Indonesia

### Other details

Uses "Madara" theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by fikiismyname** [comment]
It's a different language

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/8924c4a6fc87e66ad6be3df90f70ae04b7b5f081/multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt#L52

???
