### ISSUE TITLE
Kissmanga.in Cloudflare bypass

### ISSUE THREAD

**Issue by Whitepumpkin24** [tachiyomiorg/tachiyomi-extensions#14172]
### Source information and language

Kissmanga.in 1.3.26

### Steps to reproduce

1. Opening a chapter that comes from kissmanga.in then says "Failed to bypass Cloudflare"
2. Then I click Webviewto verify and it just keeps looping "checking if the site connection is secure"
3. when I click "open in browser" I can easily verify the connection, but with the webview I can't
4. as a result I can't open any manga that the source is from kissmanga.in

### Expected behavior

in other sources i can easily bypass the cloudflare but not when the source is from kissmanga.in

### Actual behavior

can't bypass cloudflare that the source is kissmanga.in (keeps looping in to checking if the site connection is secure)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
