### ISSUE TITLE
Imitui Manhua & Picacomic error

### ISSUE THREAD

**Issue by huajideshutiao** [tachiyomiorg/tachiyomi-extensions#14183]
### Source information and language

Picacomic 1.3.2 ; Imitui Manhua 1.3.10

### Steps to reproduce

Read comics under relevant book sources normally.

### Expected behavior

The program works normally

### Actual behavior

Imitui Manhua can only load pictures on the first page
![Screenshot_2022-11-08-15-21-13-897_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/38980554/200502952-92c266ba-3f97-4ebf-b49f-d654ddd8699c.jpg)

Picacomic cannot display the cover of some comics
![Screenshot_2022-11-08-15-22-35-805_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/38980554/200502970-57a6b453-80b8-4814-8160-2b9ff2b8d161.jpg)

I'm sure it's not a network problem

### Tachiyomi version

0.14.2-5202

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source, otherwise it keeps difficult to track what have been addressed and what not.
