### ISSUE TITLE
Sisi Gelap Change Their domain

### ISSUE THREAD

**Issue by almondflwr** [tachiyomiorg/tachiyomi-extensions#14181]
### Source information and language

SISI GELAP (Indonesia)

### Source new URL

sigel.asia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Why you opened 2 equal issues?
#14180
