### ISSUE TITLE
Wwbtoonxyz cludflare bug

### ISSUE THREAD

**Issue by Shiraishi2** [tachiyomiorg/tachiyomi-extensions#14185]
### Source information and language

Webtoonxyz

### Steps to reproduce

![Screenshot_20221108-184141_TachiyomiJ2K](https://user-images.githubusercontent.com/117728825/200543934-561eef80-f41a-4640-9e01-ccf998085b8c.jpg)

### Expected behavior

It should authorize the user when the connection is secured

### Actual behavior

but it keep repeating its loading without end

### Tachiyomi version

0.14.2

### Android version

samsung galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
