### ISSUE TITLE
Only blank chapter shows in all manga from Bulu manga

### ISSUE THREAD

**Issue by Kingfire4545** [tachiyomiorg/tachiyomi-extensions#14186]
### Source information and language

Bulu Manga 1.3.6 (English)

### Steps to reproduce

Updated library.
All manga from Bulu manga, just a blank chapter with no name.

### Expected behavior

New chapters to show

### Actual behavior

No chapters appear, just a blank chapter with no name.
![WhatsApp Image 2022-11-08 at 12 37 46 (1)](https://user-images.githubusercontent.com/78020619/200543246-ffd4e467-6b83-4a11-abc1-9606e57dd3a9.jpeg)
![WhatsApp Image 2022-11-08 at 12 37 46](https://user-images.githubusercontent.com/78020619/200543260-c5dd08d4-66cb-4954-b300-aab5e2367cbf.jpeg)
![WhatsApp Image 2022-11-08 at 12 37 47 (1)](https://user-images.githubusercontent.com/78020619/200543267-7519deb5-cb2d-4a9f-ba22-f81b0d0cb9e9.jpeg)
![WhatsApp Image 2022-11-08 at 12 37 47](https://user-images.githubusercontent.com/78020619/200543277-2eda3646-7672-4a9f-a1b7-1e6ecb86fabf.jpeg)
![WhatsApp Image 2022-11-08 at 12 37 48](https://user-images.githubusercontent.com/78020619/200543281-86df8ec0-86b9-414b-872a-279ed0d69104.jpeg)

### Tachiyomi version

0.14.2

### Android version

Android 8.1 Go Edition

### Other details

This only happens in Bulu Manga, nowhere else I checked. All of the manga from Bulu manga is affected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Related to #14159
