### ISSUE TITLE
Extension errors 

### ISSUE THREAD

**Issue by bgmondy** [tachiyomiorg/tachiyomi-extensions#14182]
### Source information and language

Doujindesu 1.3.3 (Indonesian), Sekaikomik 1.3.29 (Indonesian) 

### Steps to reproduce

1. Click source
2. Type any titles
3. Cover not appeared
4. Image in chapter not appeared too

### Expected behavior

-

### Actual behavior

-

### Tachiyomi version

0.14.2

### Android version

Android 7

### Other details

![Screenshot_2022-11-08-14-22-35-95](https://user-images.githubusercontent.com/76152689/200500516-968b2e6f-b529-43b4-b34c-924938326941.png)
Cover not appeared 
![Screenshot_2022-11-08-14-22-49-11](https://user-images.githubusercontent.com/76152689/200500587-643a040d-65df-49c1-ab02-50f66b06af4b.png)
Chapter name errors
![Screenshot_2022-11-08-14-24-58-53](https://user-images.githubusercontent.com/76152689/200500670-ac9d770d-2799-4caa-bdee-366bb7c62d70.png)
Image can't be loaded 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's already an open issue for these, also please next time you report an issue, open one issue per source, otherwise it keeps difficult to track what have been addressed and what not.
