### ISSUE TITLE
Webtoon.xyz takes very long or many time to connect 

### ISSUE THREAD

**Issue by Lyonie** [tachiyomiorg/tachiyomi-extensions#14187]
### Source information and language

Webtoon.xyz 1.3.27

### Steps to reproduce

Going into webtoon.xyz source but failed to bypass cloudflare and open in webview, it just keep checking,

### Expected behavior

Going into webtoon.xyz successfully. 

### Actual behavior

Source failed to bypass cloudflare & might take many time to keep retrying on webview to bypass. If using chrome I can easily bypass in 2 seconds. 

### Tachiyomi version

0.14.2

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Shiraishi2** [comment]
Same

**Comment by Lyonie** [comment]
After updated to 1.3.28, it still the same. Now retrying for 5min still not able bypass cloudflare.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, migrate to other sources or wait until they lower their protection.
