### ISSUE TITLE
MangaKatana not working

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi-extensions#14197]
### Source information and language

MangaKatana

### Steps to reproduce

Browse source Mangakatana
Download any chapter

### Expected behavior

Chapter should download

### Actual behavior

Not downloading it says chain validation error

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
works for me, try the troubleshooting guide again. if still happen give more detailed steps
