### ISSUE TITLE
Source broken

### ISSUE THREAD

**Issue by MonomoySama** [tachiyomiorg/tachiyomi-extensions#14205]
### Source information and language

Colored Manga 1.3.25

### Steps to reproduce

1. Opening the source

### Expected behavior

It just loading... Nothing is showing after opening source

### Actual behavior

There should be manhwa/mangas showing there. Few days ago it was fine though

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
its working for me, maybe site issue/try troubleshoot if still didnt work
