### ISSUE TITLE
Mangakyo Cannot load the page

### ISSUE THREAD

**Issue by Raptor-bit** [tachiyomiorg/tachiyomi-extensions#14219]
### Source information and language

Mangakyo 1.3.21 (Indonesia)

### Steps to reproduce

1. When opening Mangakyo Extension 
2. It loads nothing

### Expected behavior

When open, manga should pop up

I try opening it on my browser and works just fine
![Screenshot_2022-11-11-00-02-37-54](https://user-images.githubusercontent.com/53387197/201162225-e9763a10-f0f1-4a6c-8a64-e87fe0ea56af.png)

### Actual behavior

But this happened instead
![Screenshot_2022-11-11-00-02-15-50_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/53387197/201161849-d23f6009-7015-46b0-9b67-2848b2c748e1.png)
Even on webview
![Screenshot_2022-11-11-00-02-22-51_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/53387197/201161958-d7ee719b-f98e-44b0-94c5-8524f0139a5f.png)

### Tachiyomi version

0.14.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Change website URL from [https://www.mangakyo.me](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt#L61-L61) to https://mangakyo.me/

**Comment by Raptor-bit** [comment]
> Change website URL from https://www.mangakyo.me
> 
> [Last Mangakyo Url](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt#L61-L61)
> 
> to https://mangakyo.me

Gua bikin laporan baru ajakah bang??

**Comment by Raptor-bit** [comment]
Ni domainnya berubah kan?

**Comment by TheKingTermux** [comment]
Nope
Gausah gpp
Edit aja issue nya
Ama titlenya jg diganti
