### ISSUE TITLE
Doujindesu problem 

### ISSUE THREAD

**Issue by Meshin1** [tachiyomiorg/tachiyomi-extensions#14212]
### Source information and language

1.3.3 Indonesia

### Source new URL

https://doujindesu.xxx/

### Other details

https://user-images.githubusercontent.com/117889252/201010284-479fb43c-9b81-4ef2-8cda-15407e0ccaba.mp4

I've used vpn and my internet is also stable,and the website is fine too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Well
I think you should read this
[Doujindesu Missing Page](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14004#issuecomment-1304775495)

**Comment by Meshin1** [comment]
> 

Oh ok Thank you, I haven't been able to find the case before, sorry, sorry 🥲

**Comment by AhriVastayan1** [comment]
Bukan cuma doujindesu sih, sekai komik juga sama

**Comment by Meshin1** [comment]
> Bukan cuma doujindesu sih, sekai komik juga sama

Iya gw jg kaget soal nya kaga baca dd ama sekai tau tau gitu

**Comment by TheKingTermux** [comment]
Well silahkan baca #14017 buat SekaiKomik

**Comment by KurangJagoBhsInggris** [comment]
> Well silahkan baca #14017 buat SekaiKomik

Terus untuk doudesnya gimana solusinya ?
Gw baca² isinya cuma diskusi gak ada penyelesaian ato gua aja yang kurang paham ?

**Comment by TheKingTermux** [comment]
> Terus untuk doudesnya gimana solusinya ?
>> Gw baca² isinya cuma diskusi gak ada penyelesaian ato gua aja yang kurang paham ?

Well untuk solusi mungkin langsung baca lewat web DouDesu nya langsung.
Karena ini bukan masalah dari ekstensinya, melainkan dari sumbernya yang menolak akses
Sedang dicari cara bypassnya
