### ISSUE TITLE
Block by Cloudflare

### ISSUE THREAD

**Issue by BlackSmoke100** [tachiyomiorg/tachiyomi-extensions#14217]
### Source information and language

Webtoonxyz 1.3.27 (English)

### Steps to reproduce

1.Click the Webtoonxyz extension and you cant see any list of webtoon
2.
3.Block by cloudflare

### Expected behavior

When you click the Webtoonxyz extension i should be able to ssee the list of webtoon already

### Actual behavior

I cant see any Webtoon when I click the Webtoonxyz 

### Tachiyomi version

0.14.2

### Android version

Android 8.1.0

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
