### ISSUE TITLE
lateinit property title has not been initialized

### ISSUE THREAD

**Issue by Mastahzixtynine** [tachiyomiorg/tachiyomi-extensions#14214]
### Source information and language

Manhwa-raw Multi 

### Steps to reproduce

First step: I click the "Manhwa-raw" Multi language extension

Second step: I click the title that I want to read and refresh it to get new chapter update.

Issue: it says "lateinit property title has not been initialized" when refreshed

### Expected behavior

This should be happening: Refresh the Title and new chapter appears

### Actual behavior

This happened instead: it says lateinit property title has not been initialized and no new chapter was updated

### Tachiyomi version

0.14.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ANS1087** [comment]
![2022-11-11 11-10-08](https://user-images.githubusercontent.com/103411532/201271499-77403201-a277-4f34-87fc-60c916260820.png)

I am having the same problem with my NeatManga extension
