### ISSUE TITLE
MangaMx: Changed their domain

### ISSUE THREAD

**Issue by Allen1016** [tachiyomiorg/tachiyomi-extensions#14227]
### Source information and language

MangaMx 1.1.13 (español)

### Steps to reproduce

Abre la extensión , busca en la barra de búsqueda o filtra un manga, y lo encuentas

### Expected behavior

Abrí la barra de búsqueda o filtrar un manga, te saldrían los resultados 

### Actual behavior

No funciona la barra de búsqueda ni los filtros 

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

La barra de búsqueda sale expected of the objetc 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please next time fill the URL change report form instead and do provide their new URL to help eventual contributors that are willing to work on fixing the issue.

**Comment by MajorTanya** [comment]
Old URL forwards to https://manga-oni.com, but its Cloudflare protection interferes with updating the code properly.
I have the changes ready, but I can't PR them because it fails to bypass Cloudflare.
