### ISSUE TITLE
Manhwaid

### ISSUE THREAD

**Issue by fgt7** [tachiyomiorg/tachiyomi-extensions#14226]
### Source name

Manhwaid.info

### Source link

https://manhwaid.info

### Language

Indonesia

### Other details

18+/NFSW=YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Closed due removed request from the scanlator team of ManhwaId #10751, and wouldn't be added back.

Please read #3475 for another detail
