### ISSUE TITLE
Not Functioning Resources 

### ISSUE THREAD

**Issue by rlngcdn** [tachiyomiorg/tachiyomi-extensions#14223]
### Source information and language

Kissmanga.in 1.3.27 (English)

### Steps to reproduce

Source not functioning 

### Expected behavior

Source should be functional

### Actual behavior

![Screenshot_20221111-022810](https://user-images.githubusercontent.com/117939210/201177279-04b4dcc2-898c-4ecb-a12d-a1576c250467.jpg)
![Screenshot_20221111-022839](https://user-images.githubusercontent.com/117939210/201177444-7204beed-efc2-45cb-ae9e-eae74d1d8a5e.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 7.1.1

### Other details

none

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArzuHrpt** [comment]
I was about to submit a new issue myself about this. I can open the website on browser and i am able to pass the bot check. But on app i can not pass that and it always gives me the same error.

**Comment by curche** [comment]
> I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

Please actually try the three different ways referred to at the link
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

if neither works, then there's no other option than wait it out or using another source
