### ISSUE TITLE
Installed extension but can't use

### ISSUE THREAD

**Issue by NguyenDat176** [tachiyomiorg/tachiyomi-extensions#14229]
### Source information and language

MangaRaw 1.3.4, Sen Manga 1.3.5, WeLoveManga 1.3.11 (japanese)

### Steps to reproduce

1. I found that these is no raw manga in tab extension 
2. Download MangaRaw(ja.manga9co), Sen Manga(ja.senmanga), WeLoveManga(ja.rawlh)... extensions from https://tachiyomi.org/extensions  
3. Install it
4. Those extensions is in tab extension but tab source not have
5. I turn off 'Only include pinned sources' and try to find some mangas but it not display any mangas from those extensions

### Expected behavior

Can find mangas from those extension

### Actual behavior

I can't 

### Tachiyomi version

0.14.2

### Android version

Android 10

### Other details

Device:OnePlus 7 Pro 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
https://tachiyomi.org/help/faq/#why-can-i-not-see-sources-that-i-have-installed
