### ISSUE TITLE
Source request for allanime.site/manga

### ISSUE THREAD

**Issue by Anchipo** [tachiyomiorg/tachiyomi-extensions#14233]
### Source name

All Anime

### Source link

https://allanime.site/manga

### Language

English

### Other details

Good site with huge library and relatively unknown.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Berserk0001** [comment]
Yes very good site...

**Comment by Berserk0001** [comment]
Use this. https://allanime.to/manga .site domain is down...
