### ISSUE TITLE
Dead IMGs make Tachiyomi crash

### ISSUE THREAD

**Issue by moucdori** [tachiyomiorg/tachiyomi-extensions#14231]
### Source information and language

MangaSco 1.3.27 (English)

### Steps to reproduce

1. Open "Martial art Reigns" from "MangaSco" extension
2. Open chapter 492 or 493
3. Chapter 492 crashes Tachiyomi instantly, chapter 493 crashes when scrolling to the IMG at fault

IMGs makes Tachiyomi crashes instead of just show a black screen with a "can't load IMG" like error.

![Screenshot_2022-11-11-12-48-17-818](https://user-images.githubusercontent.com/34278089/201342500-9d3cd1b2-3801-4db5-a225-90cfbc256fb0.jpeg)
![Screenshot_2022-11-11-12-57-10-299](https://user-images.githubusercontent.com/34278089/201342525-c26d2e0e-d680-4658-9b97-380861670b5a.jpeg)
IMGs are also dead with WebView and local download don't work either (folder show IMGs as .tmp instead of .webp)

### Expected behavior

The chapter should show without crash till the end of it

### Actual behavior

Tachiyomi crashes when opening a chapter with faulty IMGs at the beginning or midway if the faulty IMG is later in the chapter

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Didn't really know in which GitHub repo post this cause it's related to a specific source but it's also related to a weird behaviour from Tachiyomi ...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
this has nothing to do with the extension as you said that the images are broken in webview, please reopen your issue on the app repo with crash logs as that would be the correct place.
