### ISSUE TITLE
Reaper Scans (English): Can't load any manga chapters

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi-extensions#14248]
### Source information and language

Reaper Scans 1.3.39 EN

### Steps to reproduce

1. Open a random manga
2. Click on a chapter

### Expected behavior

Manga chapter should load

### Actual behavior

Nothing loads and only shows the number of pages the chapter has

Also it can't download any of the chapters. When a global update happens it will give this error:
![Screenshot_20221114-104455](https://user-images.githubusercontent.com/6564956/201758167-d31b0d6e-34ec-4e4b-804e-909809c010bb.jpg)

### Tachiyomi version

r5232

### Android version

Android 11

### Other details

![Screenshot_20221113-213925](https://user-images.githubusercontent.com/6564956/201543605-1acc53a8-3ce2-4cbc-a92d-d3156e3a0ac2.jpg)

(When opening a webview I can just load the chapter pages)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
This has already been fixed in the past btw but now I'm having this issue again...

**Comment by ArjixWasTaken** [comment]
The retry button doesn't even pretend to retry, so I think the link for the image itself is not valid or smth.

**Comment by ArjixWasTaken** [comment]
Yep, just as I thought

![Screenshot_2023-01-06-07-24-39-577_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/53124886/210935976-2e3bf4d5-c46e-453b-8ff4-a5800e80b1a9.jpg)
