### ISSUE TITLE
Manta chapters only load partially 

### ISSUE THREAD

**Issue by nobile01** [tachiyomiorg/tachiyomi-extensions#14240]
### Source information and language

Manta Comics 1.3.3 (English) 

### Steps to reproduce

1. Open a chapter from any series from Manta
2. Scroll down, after around page 7 everything loads black (even though there may be over 20 pages left) 
3. Happens with both series in library and not in library
4. Even when downloading the chapter, it's still only partial 

### Expected behavior

Chapters should load with the images

### Actual behavior

Less more than half the chapter doesn't load, it's just a black screen

### Tachiyomi version

App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z) 

### Android version

Android version: 13 (SDK 33) Android build ID: TP1A.220905.004 Device brand: google Device manufacturer: Google Device name: raven Device model: Pixel 6 Pro Device product name: raven

### Other details

I've asked other tachiyomi users and they also have that same problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jamesnorritz** [comment]
Chapters are now behind paywall. Logging into google account gets you only 1 free pass per day. Which gets you one chapter per day. 
![image](https://user-images.githubusercontent.com/91746163/205733318-7d7a320b-48aa-49c8-a910-a5b12d378054.png)

**Comment by remanzzo** [comment]
> Chapters are now behind paywall. Logging into google account gets you only 1 free pass per day. Which gets you one chapter per day. ![image](https://user-images.githubusercontent.com/91746163/205733318-7d7a320b-48aa-49c8-a910-a5b12d378054.png)



The paywall isn't a new thing in Manta, but after the last update the bug appeared in chapters that are not free. The free ones (usually the 9 firsts) load completely, and all chapters behind the paywall don't load after page 6 anymore.
