### ISSUE TITLE
Babel TOON Source request

### ISSUE THREAD

**Issue by FaTe-code** [tachiyomiorg/tachiyomi-extensions#14246]
### Source name

Babel TOON

### Source link

https://babeltoon.com/

### Language

English

### Other details

There seems to be (English), (Manhua) and (Novel) in the titles of manhua. (Manhua) doesn't show up in browse tab but does in home.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme

**Comment by FaTe-code** [comment]
MangaThemesia theme? How and where do I find it?

**Comment by vetleledaal** [comment]
It's an implementation detail, meaning it shares a common pattern between multiple sites. It still needs to be implemented and tested. You can see the similar sites here: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/8117f0b935986d746414f465c06b9050f1daadec/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt

**Comment by vetleledaal** [comment]
Site is empty, shows some cPanel error page
