### ISSUE TITLE
Webtoon.xyz 

### ISSUE THREAD

**Issue by Azeezzibran19** [tachiyomiorg/tachiyomi-extensions#14245]
### Source information and language

Webtoon.xyz 1.3. 28

### Steps to reproduce

Cloudflare has increased

### Expected behavior

Should work when clicked the button

### Actual behavior

Webwiew is not working hence the extension doesnt work

### Tachiyomi version

0.14.2

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
