### ISSUE TITLE
HTTP error 426 Olympus Scanlation

### ISSUE THREAD

**Issue by Lxninnn** [tachiyomiorg/tachiyomi-extensions#14257]
### Source information and language

Olympus Scanlation 1.3.26 (Español) 

### Steps to reproduce

1. No cargan los cómics cuando se buscan dentro de la extensión
2. 

### Expected behavior

Al buscar en la extensión deberían aparecer cómics y cargar correctamente 

### Actual behavior

Al bajar para buscar cómics lanza  "HTTP error 429: abrir sitio en WebView" 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#14738
