### ISSUE TITLE
Manhwa18.cc No Pages Found error

### ISSUE THREAD

**Issue by AgentX2006** [tachiyomiorg/tachiyomi-extensions#14259]
### Source information and language

all.manhwa18.cc 1.3.29 English

### Steps to reproduce

1. Try to read any chapter .
2. Get "No Pages Found" error.

### Expected behavior

Chapter should load.

### Actual behavior

Chapter fails to load with "No Pages Found" error.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Worked fine before the latest update to the extension. After updating to version 1.3.29 last night it broke.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dexroneum** [comment]
fixed for next build
