### ISSUE TITLE
Anime search error extension MangaMx 

### ISSUE THREAD

**Issue by CamiloBladeYT** [tachiyomiorg/tachiyomi-extensions#14254]
### Source information and language

MangaMx 1.2.13

### Steps to reproduce

Open the app and enter the explored and touch MangaMx, search any anime tittle and boom to show the error

### Expected behavior

See all similar  titles animes 

### Actual behavior

No show nothing only this error 

![Screenshot_20221113-234032](https://user-images.githubusercontent.com/87965425/201578241-923aba83-4695-4adb-a202-39bec66f438e.png)

### Tachiyomi version

0.14..2

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
1. You're in the wrong app
2. #14227
