### ISSUE TITLE
Cosmic Scans doubling pages

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#14266]
### Source information and language

Cosmic Scans 1.3.21 (English)

### Steps to reproduce

Open any chapter of any manga.
Notice that all pages appear twice 

### Expected behavior

Pages should only appear once.

### Actual behavior

Two pages where there should be one.

### Tachiyomi version

 0.14.2 

### Android version

Android version: 12 (SDK 31)

### Other details

App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXS4BVI2
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RaidBuster** [comment]
I encounter the same problem too

**Comment by nobile01** [comment]
I can confirm to have the same problem, all images are duplicated.
On webview the chapters are fine, it's only showing duplicated on tachiyomi.

Extension: Cosmic Scans (en.cosmicscans)
Extension version: 1.3.21
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220905.004
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
