### ISSUE TITLE
Nhentai (All/Multiple) gives very few entries as result

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#14263]
### Source information and language

Nhentai 1.3.36

### Steps to reproduce

1. open nhentai (multiple)
2. open filter and insert "-futanari,-tentacles,-yaoi,milf" jn the tag sectiom
3. insert ">25" in filter by page
4. sort by "Recent"
5. start search

### Expected behavior

Normal amount of entries as result 

### Actual behavior

6 entries as result. Six, we are talking about nhentai

### Tachiyomi version

0.14.2 (tachi sy last preview with nhentai enchantment turned off)

### Android version

Android 8

### Other details

On Nhentai (English) this doesn't occour

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Remove the comma while searching the tags, use spaces to separate them. Just tried and it's working perfectly fine. Please refer to their search syntax guide on their website too.

**Comment by Palloxin** [comment]
nvm, seems a problem with tachisy strangely. sorry for the bother :(

**Comment by alessandrojean** [comment]
Anyway just tested on Multiple too and working as expected. Seems indeed to be something related to the SY delegation so you should report there.
