### ISSUE TITLE
Bilibili Download Stay Temp.

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi-extensions#14262]
### Source information and language

BiliBili 1.3.11

### Steps to reproduce

Download chapter from bilibili

### Expected behavior

Download complete and ready to read

### Actual behavior

Download complete but status on folder stay temp.
![Screenshot_20221115-155729~2](https://user-images.githubusercontent.com/34748019/201875249-189aaec1-2bc0-4cdb-8a28-cc38dd8997c4.png)
![Screenshot_20221115-155754](https://user-images.githubusercontent.com/34748019/201875302-14031626-7852-40d1-a5cf-727188b3798c.png)

### Tachiyomi version

R5242

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
That's an error of Preview version of the app when you download to SD cards specially. Should already be fixed in the next version.

**Comment by AntsyLich** [comment]
Issue is with latest preview. Follow tachiyomiorg/tachiyomi#8537
