### ISSUE TITLE
Manhwa18.cc No page Found

### ISSUE THREAD

**Issue by Troybake** [tachiyomiorg/tachiyomi-extensions#14260]
### Source information and language

Manhwa18.cc 1.3.29

### Steps to reproduce

1. I clicked on one the chapters on Manhwa18 it does not open but it show "No pages found"

### Expected behavior

It should load a page but it does not just brings you back to chapter selection 

### Actual behavior

It shows loading for 3 second then it brings me back to chapter selection 

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dexroneum** [comment]
fixed for next build
