### ISSUE TITLE
Tapas Login With IDMs

### ISSUE THREAD

**Issue by Masonjar13** [tachiyomiorg/tachiyomi-extensions#14268]
### Source information and language

Tapas 1.2.19 English

### Steps to reproduce

1. Open Tapas extension from source.
2. Select globe icon.
3. Tap on Login > Continue with Facebook OR Continue with Google.

### Expected behavior

Prompt for respective IDM login.

### Actual behavior

Results in about:blank page, which does not allow logging in using Facebook/Google IDMs.

### Tachiyomi version

Stable 0.14.2

### Android version

Android 11

### Other details

Android System WebView 107.0.5304.105

This happens in other browsers when using Desktop mode, but works fine if it is in mobile view. Based on the page UI, it appears to be presenting in Desktop mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
That's intentional, Google, Facebook and other providers intentionally disallow sign-in through WebView in any website to avoid known credential stoling attacks. Use a simple email/password account to sign-in instead. Something we really can't fix as it's like that by design by the providers.
