### ISSUE TITLE
MangaDex API: Unable to connect

### ISSUE THREAD

**Issue by Dari8987898** [tachiyomiorg/tachiyomi-extensions#14274]
### Source information and language

MangaDex 1.3.175

### Steps to reproduce

1. Open the app and go on the Library tag
2. Update the library (by dragging down on the screen)

### Expected behavior

When updating, the app should visualize and add the new chapters.

### Actual behavior

When finished updating error comes out: [x number of titles from MangaDex] Update failed.
This doesn't happen on other sources.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

When opening the error notification a browser page opens, with the following message:

! Failed to connect to api.mangadex.org/127.0.0.1:443
  MangaDex (EN)
  - [Manga 1]
  - [Manga 2]
  - etc.

If i try to open the manga in the webview mode the following error comes out:

Web page not available
https://mangadex.org/title/87ffa375-bd2c-49ba-ba0c-6d78ea07c342/kuroiwa-medaka-ni-watashi-no-kawaii-ga-tsuujinai
net::ERR_CONNECTION_REFUSED

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This means something in your network is blocking your access to MangaDex. Some router brands and ISPs are known for doing that. Check if you can add the MangaDex domains to a exclusion list or use DNS via HTTPS or a VPN to bypass the block.

**Comment by Dari8987898** [comment]
I used the DNS over HTTPS of Google and it seems to work now, thank you very much
