### ISSUE TITLE
1stkissmanga Issue with global update

### ISSUE THREAD

**Issue by QuakeBeard** [tachiyomiorg/tachiyomi-extensions#14277]
### Source information and language

1st Kiss English 1.3.33

### Steps to reproduce

1. Check on website if the comic has new chapters
2. Hit global update
3. Notice that nothing updated and I still see that the latest chapter is from June
4. Issue acquired ;c

### Expected behavior

No new chapters show up

### Actual behavior

No new chapters show up

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
make sure every chapter is marked as read, and you can drag down in the manga page to refresh manual
