### ISSUE TITLE
I can't use the filter option and it shown way less mangas than before

### ISSUE THREAD

**Issue by Absractarsenal** [tachiyomiorg/tachiyomi-extensions#14276]
### Source information and language

E-Hentai 1.3.17 (English)

### Steps to reproduce

1. In ehentai use the search or filter option.
2. Search for any tag in any of them or artist in them.

### Expected behavior

It should show the mangas related to tags and as much as it has.

### Actual behavior

But it shows error in filter and very less things in search

### Tachiyomi version

0.14.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by PrivatePP** [comment]
Happens to me as well. If you go to E-Hentai popular/recent tab, the extension is only able to load no more than 25 items.
