### ISSUE TITLE
How can I get deprecated extension releases?

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#14270]
### Describe why this should be added

Wrong tag. Sorry.

How can I download old extensions? I need to test an idea.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Outdated and obsolete extensions aren't available easily as we don't offer support to them. Using these extensions can lead to issues like making the app to crash.
