### ISSUE TITLE
Failed to bypass cloudflare

### ISSUE THREAD

**Issue by amgadreyad98** [tachiyomiorg/tachiyomi-extensions#14282]
### Source information and language

Mangalionz

### Steps to reproduce

1-Try to open a chapter in any manha
2-It show failed to bypass cloudflare
3-Try all solutions in troubleshooting guide
4-Still have the problem
5-It happened once before and got working alone

### Expected behavior

The chapter open and load the pages

### Actual behavior

The circle still loading and then show 
Failed to bypass couldflare

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
