### ISSUE TITLE
Manga Freak not loading 

### ISSUE THREAD

**Issue by thediningtable** [tachiyomiorg/tachiyomi-extensions#14288]
### Source information and language

Mangafreak 1.3.7

### Steps to reproduce

Click a title in your library originating from the Mangafreak extension, refresh page, obtain failed to bypass cloudfare 

### Expected behavior

New chapters should load

### Actual behavior

Title page loads for a few seconds, Failed to bypass Cloudfare message appears 

### Tachiyomi version

0.14.2-5242

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MohsenSameti** [comment]
Yeah, same for me. I think its because url is changed from w13 to w14.

**Comment by tsunaproxD** [comment]
I have cloudfire error.

**Comment by MohsenSameti** [comment]
It gives me cloudflare error too. I tried all fixes and nothing worked

**Comment by alessandrojean** [comment]
Please actually try the three different ways referred to at the link
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**if neither works, then there's no other option than wait it out or using another source.**

**Comment by diirtyhippy** [comment]
Having the same issue here. Tried everything on the list that was linked, and even tried WebView beta. Nothing worked, guess we gotta wait 😵
