### ISSUE TITLE
Mangalek (مانجا ليك) not working 

### ISSUE THREAD

**Issue by Novamanx** [tachiyomiorg/tachiyomi-extensions#14281]
### Source information and language

مانجا ليك 1.3.27 (Arabic)

### Steps to reproduce

it's like it's working to load avatars of manga 
When I try any chapters or download them it join in loop of loading at regular looad... and the download get stop if I try to download 

### Expected behavior

Chapters load or gets download  

### Actual behavior

It's not even loading or downloading any chapter 

![Screenshot_٢٠٢٢١١١٧-١٢١١٠٣_Tachiyomi](https://user-images.githubusercontent.com/115431595/202404492-798d73f3-524c-4cb1-9cf4-b1052f3a7548.jpg)
![Screenshot_٢٠٢٢١١١٧-١٢١٢٠٧_Tachiyomi](https://user-images.githubusercontent.com/115431595/202404575-ff786afe-9b71-4bdc-9d9a-7d3819ea84a5.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by XOCV0** [comment]
I Hope this is going to get fix soon

**Comment by gto2121** [comment]
نفس المشكله عندي

**Comment by araby9566** [comment]
وانا

**Comment by OMARYeHia19** [comment]
الموضوع ده اصلاً بقاله فترة كبيرة و كل شوية المشكلة تتكرر في الاول كان وجود مانجا سوات و فلايم سكانز مهون الموضوع بس دلوقتي مفيش غير مانجا ليك

**Comment by OMARYeHia19** [comment]
There no arabic extension I can migrate my manhwas into it so please fix manga lek
