### ISSUE TITLE
Web Comic Gamma Plus: web ui changed

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi-extensions#14292]
### Source information and language

Web Comic Gamma Plus 1.3.3

### Steps to reproduce

open Web Comic Gamma Plus

### Expected behavior

load manga list

### Actual behavior

no list

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Web Comic Gamma Plus changed their web ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
I'll fix this soon.
