### ISSUE TITLE
MyHentaiGallery - Unexpected URL scheme 'http' or 'https'

### ISSUE THREAD

**Issue by annonmerchy** [tachiyomiorg/tachiyomi-extensions#14299]
### Source information and language

MyHentaiGallery (1.3.4)

### Steps to reproduce

1. Choose any manga from extension browse
2. Attempt to download manga

### Expected behavior

Successful Download

### Actual behavior

"Expected URL scheme 'http' or 'https' but no scheme was found for "

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

[tachiyomi_crash_logs.txt](https://gist.github.com/7f1af06e42934d4b4ad83ad1e7a7675a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce this issue. Can you provide an example manga where this occurs?

**Comment by annonmerchy** [comment]
Tested on Tachiyomi and it works. I originally thought that it didn't work on both Tachiyomi and TachiyomiSY, but I guess I was wrong.
Since this issue doesn't seem to be related to the extension and doesn't occur on the non-fork version, feel free to close this.
