### ISSUE TITLE
E-Hentai: Search Not Working

### ISSUE THREAD

**Issue by w00ogly** [tachiyomiorg/tachiyomi-extensions#14298]
### Source information and language

E-Hentai 1.3.17 (All)

### Steps to reproduce

Open extension and search 

![Screenshot_20221118_135557_TachiyomiJ2K](https://user-images.githubusercontent.com/111436425/202810129-7c009a6e-512a-421d-8be8-fc2a648689d3.jpg)
![Screenshot_20221118_135614_TachiyomiJ2K](https://user-images.githubusercontent.com/111436425/202810147-53dec864-0bcd-402d-8b53-4736a75b4514.jpg)

### Expected behavior

Should display search results. 

### Actual behavior

Instead, a message saying "no results found" appears even though webview works fine.

### Tachiyomi version

TachiyomiJ2K 1.5.9

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate/relationed to #14276.
