### ISSUE TITLE
I want Tempest Manga to be removed

### ISSUE THREAD

**Issue by YukiHimeTempest** [tachiyomiorg/tachiyomi-extensions#14296]
### Source link

https://manga.tempestfansub.com

### Other details

I'm the founder of Tempest Manga and I request the removal of my site from Tachiyomi.

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Soitora** [comment]
1. Which server mod did you provide ownership info to?
2. Why are you hosting other scans on your website? There's not just Tempest Fansubs on there, I found multiple others.
3. It seem you're auto refreshing the ads on your website to increase revenue, are you aware that this might cause your ad account to get suspended?

**Comment by YukiHimeTempest** [comment]
1. Soitora
2. We're keeping on of other scanses' droped series, so we can able to continue series on which chapter they droped at. And of course we asked permission for it and they gave. Right now there's one active scans that working with us, but they're also a part of our group so its not a big deal.
3. We're not in the control of the advertisement. We contracted with a advertisement company and they controling the ads

**Comment by YukiHimeTempest** [comment]
I would appreciate if you remove my site from your application.

**Comment by Soitora** [comment]
Seems fine to mine, at least the scans and ownership part
