### ISSUE TITLE
Does not work AllHentai ❗

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi-extensions#14305]
### Source information and language

Allhentai 1.3.30 (Russian)

### Steps to reproduce

We go to the extension and see this 
![Screenshot_2022-11-19-15-52-15-94_680d03679600f7af0b4c700c6b270fe7](https://user-images.githubusercontent.com/71752683/202851977-6667945b-ad6b-4a4b-9150-e11f3da50fc2.jpg)
![Uploading Screenshot_2022-11-19-15-51-33-04_afd66b7916d19a60815f56273408b73e.jpg…]()

### Expected behavior

Normal operation of the application

### Actual behavior

Does not work 
![Screenshot_2022-11-19-15-52-15-94_680d03679600f7af0b4c700c6b270fe7](https://user-images.githubusercontent.com/71752683/202851996-d155cac2-4e6d-48e8-ab92-dd040bdf7324.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MM001-r** [comment]
change domain manually

**Comment by vetleledaal** [comment]
Superseded by #15091
