### ISSUE TITLE
BaoziMH Not Working

### ISSUE THREAD

**Issue by RyoheiXD** [tachiyomiorg/tachiyomi-extensions#14304]
### Source information and language

Baozi ManHua 1.3.14

### Steps to reproduce

1. Tried to read manhwa from Baozi MH
2. Cannot access as message "no page found"
3. When click Webview another message pop out ; "cn.baozimh.com
Checking if the site connection is secure
cn.baozimh.com needs to review the security of your connection before proceeding." 

### Expected behavior

Should have load the contents 

### Actual behavior

"HTTP error 403 Check website in Webview" & "cn.baozimh.com
Checking if the site connection is secure
cn.baozimh.com needs to review the security of your connection before proceeding."

### Tachiyomi version

0.14.2

### Android version

Android 10

### Other details

![Screenshot_2022-11-19-19-12-16-551_eu kanade tachiyomi](https://user-images.githubusercontent.com/118604528/202847828-f78fe3cd-b5b9-41a8-ba54-cd0ac5321015.jpg)
![Screenshot_2022-11-19-19-12-10-314_eu kanade tachiyomi](https://user-images.githubusercontent.com/118604528/202847830-b99edf1b-aebe-45fc-bad0-665c13d978e1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by chent7** [comment]
Btw the page is just looping hCaptcha, so the page is probably down.

**Comment by stevenyomi** [comment]
Doesn't happen for me. Check your user agent string setting and the troubleshoot guide.

> Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.
>
> https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by RyoheiXD** [comment]
> Doesn't happen for me. Check your user agent string setting and the troubleshoot guide.
> 
> > Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.
> > https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

I tried to access via webview but stucked at verifying CAPTCHA, but when I use chrome and load the website is fine.

I did tried to change user string as the troubleshoot guide but issue still persist. 
![IMG_20221120_063601](https://user-images.githubusercontent.com/118604528/202874186-9f2953fb-9490-4d2f-a8a0-f364b65fa9fb.jpg)
![IMG_20221120_063544](https://user-images.githubusercontent.com/118604528/202874189-ec921544-1fa6-48e2-8d2b-7552b218effe.jpg)

**Comment by Radio028** [comment]
I am having exactly same issue too.

**Comment by puffyqi** [comment]
It works for me after I change my user agent string to the respective OS string. Eg. If is samsung phone, use android samsung chrome user agent string

**Comment by puffyqi** [comment]
The baozimh.org (包子漫画导航）will crash the tachiyomi app

**Comment by Howard20181** [comment]
Tachiyomi's defaule UserAgent block by that site, chang to another one
e.g. the result from Chrome's `about:version`
![image](https://user-images.githubusercontent.com/40033067/202969408-5fc683ad-5b8a-4f00-97ba-9140923565f6.png)

**Comment by Radio028** [comment]
> Tachiyomi's defaule UserAgent block by that site, chang to another one
> e.g. the result from Chrome's `about:version`
> ![image](https://user-images.githubusercontent.com/40033067/202969408-5fc683ad-5b8a-4f00-97ba-9140923565f6.png)
> 

Thanks it works.
