### ISSUE TITLE
connect reset

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#14306]
### Source information and language

Imitui Manhua

### Steps to reproduce

1. open Imitui Manhua extension
2. connect reset

### Expected behavior

The images can be loaded

### Actual behavior

please fix the connection

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_2022-11-19-21-50-06-055_eu kanade tachiyomi](https://user-images.githubusercontent.com/110704357/202854081-c094cea8-757c-4892-b8d0-4098a5024b75.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Check your internet connection.
