### ISSUE TITLE
Mangahasu failed to bypass cloudflare

### ISSUE THREAD

**Issue by renachansama** [tachiyomiorg/tachiyomi-extensions#14315]
### Source information and language

Mangahasu 1.3.16 

### Steps to reproduce

Can't update the mangahasu extension or open it. It says failed to bypass the cloudfare

### Expected behavior

Usually its easy to use and open

### Actual behavior

Now its just stuck like that for almost 2 weeks now

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please refer to the **Solving Cloudflare issues** section and the two following sections at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. Some sources intentionally have a higher Cloudflare protection level to block apps like Tachiyomi. Try changing the user agent string by following the aforementioned guide, but this is a last measure; if it doesn't work, migrate to other sources or wait until they lower their protection.
