### ISSUE TITLE
Baozi Manhua missing pages after page 50

### ISSUE THREAD

**Issue by PathTripper** [tachiyomiorg/tachiyomi-extensions#14313]
### Source information and language

Baozi Manhua 1.3.14

### Steps to reproduce

1. Open manhua in Tachiyomi that has more than 50 pages, [Example here](https://www.webmota.com/comic/chapter/xiuzhenliaotianqun-yuewenmanhuahuolixiongmao_d/0_540.html#531%20%E9%87%91%E4%B8%B9%E5%8C%96%E6%B9%96).
2. Only able to read / download 50 pages in app.

### Expected behavior

Should be able to read all pages even if it is more than 50 pages.

### Actual behavior

Only up to 50 pages of manhua can be read / downloaded.

### Tachiyomi version

0.14.2

### Android version

12

### Other details

I think this was previously fixed in #14198 i.e. version 1.3.13, but after the update to 1.3.14 in #14255 , it broke again. Not sure if it is related.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Are you encountering issues with Cloudflare protection?

**Comment by stevenyomi** [comment]
I get it. I used Simplified Chinese and didn't cover Traditional Chinese variant. Will include the fix in #14310.
