### ISSUE TITLE
Most good Arabic sources not loading 

### ISSUE THREAD

**Issue by Mohamed164x** [tachiyomiorg/tachiyomi-extensions#14329]
### Source information and language

Azora 1.3.30 (Arabic) - Manga Starz 1.3.28 (arabic) - مانجا ليك 1.3.27 (arabic) - مانجا لينك 1.3.28 (arabic)

### Steps to reproduce

These are the only Arabic sites that is updating new chaps everyday, when I click refresh button it shows the new chapters normally but when i try to open the chapters it stand still on the loading icon then gets me out of chapter, when i open the Webview it doesn't show that the source is broken and i can read in the webview but when i return to try to open it again in the app it doesn't work and keeps the same loading chapter mark then kicks me out of the chap

### Expected behavior

It should open and load for some time then the chapter opens normally 

### Actual behavior

It just keeps loading the gets me out of chapter 

### Tachiyomi version

0.14.2

### Android version

11

### Other details

![Screenshot_2022-11-21-10-04-02-001_eu kanade tachiyomi](https://user-images.githubusercontent.com/76754557/202996553-c68f7138-a795-469c-93b9-7583b02d8746.jpg)

It just stays like this then close the chapter 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by XOCV0** [comment]
Fix pleass

**Comment by alessandrojean** [comment]
Please open one issue per source and do try the troubleshooting guide in the acknowledgements.
