### ISSUE TITLE
Extra empty Page bugs in Realmscans

### ISSUE THREAD

**Issue by Katsuhi20** [tachiyomiorg/tachiyomi-extensions#14339]
### Source information and language

Realm scans, English 1.3.24

### Steps to reproduce

every end of a page there's a blank page that can't be open or won't load tried it on different books but they all have it 
![Screenshot_20221122-094414](https://user-images.githubusercontent.com/118784304/203197569-44f66998-255a-4563-94a3-8da09c7c4e73.jpg)
![Screenshot_20221122-094353](https://user-images.githubusercontent.com/118784304/203197613-871260fd-a702-49b8-b1e9-d12da6e3a4c3.jpg)

### Expected behavior

normally there should be no blank page at every end of a page

### Actual behavior

there is a extra page empty and can't be open or loaded every end of a page

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

other extensions works just fine only problem is Realmscans

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Issue doesn't happen anymore

**Comment by AntsyLich** [comment]
Started happening again so I'll reopen the issue

**Comment by Akash1616** [comment]
Cannot download from realm scan and also while reading, extra page is created for each page repeatedly

**Comment by AntsyLich** [comment]
@Akash1616 restart tachi
