### ISSUE TITLE
PMScans: Changed their name and domain

### ISSUE THREAD

**Issue by Avay121** [tachiyomiorg/tachiyomi-extensions#14331]
### Source information and language

PMScans (English)

### Source new URL

https://my.rackusreads.com

### Other details

URL for PMScans (EN) changed to RackUsReads :- https://my.rackusreads.com
Please update the URL
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by abdulmannans** [comment]
@alessandrojean URL for this is updated and resolved.

**Comment by AntsyLich** [comment]
@abdulmannans don't keep pinging Alessandro. Leave a comment a someone will act on it

**Comment by keplerk** [comment]
It now uses https://rackusreads.com instead of https://my.rackusreads.com but at today 09/13/2023 they seem to have deleted all their series and it throws a 404 for anything.
