### ISSUE TITLE
Cant download chapters on realmscans

### ISSUE THREAD

**Issue by pengzky43** [tachiyomiorg/tachiyomi-extensions#14338]
### Source information and language

Realmscans 1.3.24

### Steps to reproduce

1. open Browse
2. Select realmscans
3. Download any chapter of any manga.

### Expected behavior

It should download chapter.

### Actual behavior

![Screenshot_2022-11-22-09-04-39-026_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/74085963/203189755-f158d8ab-e161-4b2b-9ad1-add6caf1a1f2.jpg)
![Screenshot_2022-11-22-09-01-50-562_com android chrome](https://user-images.githubusercontent.com/74085963/203189762-37aa81c7-525b-4c43-900c-435d104a32ab.jpg)

### Tachiyomi version

1.5.9

### Android version

Android 11

### Other details

![Screenshot_2022-11-22-09-14-04-737_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/74085963/203190380-f809d111-082d-4de9-a100-a06b540bf64a.jpg)
There is a gap between loaded images that was not there on viewing it on the website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
looks like i forgot to pr again and keep using it for my own lmao

**Comment by Jaren1112** [comment]
hmm it was fine 3days ago, now it won't load any pages in a chapter
