### ISSUE TITLE
Manhwa-raw "No Chapter Found"

### ISSUE THREAD

**Issue by Mastahzixtynine** [tachiyomiorg/tachiyomi-extensions#14337]
### Source information and language

Manhwa-raw Multi 

### Steps to reproduce

1. First I choose Manhwa-raw multi extension
2. After choosing I click on specific title of what I will read
3. When I refresh for new chapter, it says "No Chapter Found" while in browser it has a new chapter

### Expected behavior

When refreshing a new chapter shall be appearing.

### Actual behavior

What happened was, it says "No Chapter Found" even tho in browser it has a new chapter

### Tachiyomi version

0.14.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by dragneel152** [comment]
I believe this a domain change issue
