### ISSUE TITLE
Manga

### ISSUE THREAD

**Issue by alpqm** [tachiyomiorg/tachiyomi-extensions#14346]
### Source information and language

Mangasusu 1.3.22 (Indonesia)

### Steps to reproduce

1.Enter the mangasusu extension
2.Select the comic you want to read 
3.Select chapter and Page not found 
![Uploading Screenshot_2022_1122_204955.jpg…]()

### Expected behavior

The chapter image should appear 

### Actual behavior

![Screenshot_2022_1122_204955](https://user-images.githubusercontent.com/101073177/203331838-935afbf9-2f1f-41eb-83cc-95b4e678a0d6.jpg)

### Tachiyomi version

0.14.2

### Android version

11

### Other details

This happens throughout the comic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
most likely related to #11019
