### ISSUE TITLE
MangaSushi URL Change.

### ISSUE THREAD

**Issue by VenerableSimp** [tachiyomiorg/tachiyomi-extensions#14349]
### Source information and language

Mangasushi 1.3.29 (English)

### Source new URL

https://mangasushi.org

### Other details

Going to the old URL will direct you to the new one automatically. But even then, it won't update in the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
the url is already https://mangasushi.org so i'm not sure what old url you're being directed too, but you can ask for help in discord.

**Comment by VenerableSimp** [comment]
It directs me to https://mangasushi.net first, then redirect me to
https://mangasushi.org
But the series from extension mangasushi won't update. And when I tried
using webview from the series, it directs me to https://mangasushi.org
homepage instead.
