### ISSUE TITLE
Filtering in Tachiyomi (0.14.2) yields no results using E-hentai extension (1.3.19)

### ISSUE THREAD

**Issue by bubbaburger12** [tachiyomiorg/tachiyomi-extensions#14342]
### Source information and language

E-Hentai English 1.3.19

### Steps to reproduce

1. Open E-Hentai extension
2. Select filter menu
3. Select any of the following tags (yaoi, yuri, enforce language, ect)
4. Hit Filter button
5. No results found

### Expected behavior

Show latest sources with the selected tags

### Actual behavior

Extension shows "no results found" no matter the tag selected

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed in 1.3.20
