### ISSUE TITLE
Hentai2Read Extensions change source ?

### ISSUE THREAD

**Issue by PahleviEins** [tachiyomiorg/tachiyomi-extensions#14341]
### Source information and language

Hentai2Read English 1.3.14

### Source new URL

https://hentai2read.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by dejavui** [comment]
Closed #14443

**Comment by AntsyLich** [comment]
This is a different site and "https://hentai2read.com" still works. If you want a extension for this site open a source request.
