### ISSUE TITLE
Vex Manga

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#14343]
### Source name

Vex Manga

### Source link

https://vexmanga.net

### Language

Arabic

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by yemenihandsome** [comment]
@vetleledaal 
He changed his title, but there is a problem that only one page appears in it

**Comment by Doo77m** [comment]
ممكن رابط الاضافة لو تكرمت
كلمني بتويتر في حال عدم استطاعتك وضعه
@somebode11

**Comment by tayani1989** [comment]
Please add this source
