### ISSUE TITLE
TuMangaOnline

### ISSUE THREAD

**Issue by SrCrono** [tachiyomiorg/tachiyomi-extensions#14350]
### Source name and language

https://lectortmo.com

### Describe your suggested feature

If possible add the language Portuguese or Brazilian Portuguese because there are Brazilian translations of both the manga and the site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension already exists and it doesn't seem the site have an option to filter by language so not possible to split into multiple sources.
