### ISSUE TITLE
Problems at search at MangaMx 1.3.13

### ISSUE THREAD

**Issue by tjuanax** [tachiyomiorg/tachiyomi-extensions#14354]
### Source information and language

MangaMx 1.3.13

### Steps to reproduce

1. Open the source
2. Tap the button "Search"
3. Search any manga
4. Issue here

### Expected behavior

You find the manga you search

### Actual behavior

Appear a code problem and can't appear the manga

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

It's happening since two weeks and can't search any manga.
I tried uninstall the source and download again, but this doesn't work. 
Here I put a screenshot of the problem
![Screenshot_20221122-224316_Tachiyomi](https://user-images.githubusercontent.com/118871747/203468807-2c748008-7a39-453c-8225-76e5e1902390.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Superseded by #14504
