### ISSUE TITLE
Mangahasu bypass cloudfare

### ISSUE THREAD

**Issue by aofukai7** [tachiyomiorg/tachiyomi-extensions#14351]
### Source information and language

Mangahasu 1.2.16

### Steps to reproduce

![Screenshot_20221123-070248_TachiyomiJ2K](https://user-images.githubusercontent.com/64181165/203445160-63a1776d-7e64-46e3-801c-c66c11053f8d.jpg)

### Expected behavior

Can we get an extension update for mangahasu

### Actual behavior

The extension didnt update since it happened 

### Tachiyomi version

1.5.9 J2K

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, wait until they lower their protection or migrate to other sources.
