### ISSUE TITLE
Mangadex chapters don't load 

### ISSUE THREAD

**Issue by dingleberry53** [tachiyomiorg/tachiyomi-extensions#14359]
### Source information and language

Mangadex 1.3.175

### Steps to reproduce

At first it wasn't loading specific chapters from Innocent Rogue (16,33,81 if that would help), I logged out from the mnag6adex setting6 and relogged in and it only loaded a couple of pages then stopped

### Expected behavior

load pages inside a chapter 

### Actual behavior

![Screenshot_20221123_171140](https://user-images.githubusercontent.com/100795982/203590551-68380378-5e08-4012-8570-3b8429e88562.png)

doesn't load the pages for whatever reason

### Tachiyomi version

1.8.5 sy

### Android version

Android 10

### Other details

here's a crash log

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The MangaDex extension doesn't support sign in through the settings so this is likely an SY specific issue. Please open an issue in the SY repository instead.
