### ISSUE TITLE
Cosmic Scans repeating pages

### ISSUE THREAD

**Issue by e786** [tachiyomiorg/tachiyomi-extensions#14352]
### Source information and language

Cosmic Scans 1.3.21 English

### Steps to reproduce

1. Get on Cosmic scans
2. Click on any series with the latest chapters and you will see.

### Expected behavior

The pages should be twice as short with no repeating pages

### Actual behavior

Pages are twice as long and makes scrolling down a tedious task to find new scenes in the chapter.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Only works for latest chapters
Have tried other ways to fix this but never worked
Haven't seen anyone else talk about this problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nobile01** [comment]
I can confirm to have the same problem, all images are duplicated.

Extension: Cosmic Scans (en.cosmicscans) 
Extension version: 1.3.21
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220905.004
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
