### ISSUE TITLE
MangaPark v3

### ISSUE THREAD

**Issue by SrCrono** [tachiyomiorg/tachiyomi-extensions#14360]
### Source name and language

https://mangapark.net

### Describe your suggested feature

I can filter by language, because even if I activate only the language I want, when I open a chapter it shows another language And change name from v3 to v5

### Other details

Add option already available on the site to filter by language

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Extension already exists and have all languages they provide as individual sources.

**Comment by SrCrono** [comment]
> Extension already exists and have all languages they provide as individual sources.

Yes, but when I play it, it shows a chapter in another language and the site is v5, not v3

**Comment by alessandrojean** [comment]
Then open an issue report instead and do provide reproductive examples where this happens there.
