### ISSUE TITLE
MangaLionZ Failed to bypass Cloud flare 

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#14361]
### Source information and language

MangaLionZ 1.3.26

### Steps to reproduce

1. Open extension
2. Select any manga/hua/hwa
3. Try to read it
4. Nothing happens
5. It say failed to bypass Cloud flare 

### Expected behavior

It should open 

### Actual behavior

This happens
![Screenshot_2022-11-23-20-50-39-040_eu kanade tachiyomi](https://user-images.githubusercontent.com/93197738/203626189-6896e7ca-98e7-40f5-a738-225d4ab3c8d6.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, wait until they lower their protection or migrate to other sources.
