### ISSUE TITLE
七夕漫画域名更改

### ISSUE THREAD

**Issue by No8686** [tachiyomiorg/tachiyomi-extensions#14363]
### Source information and language

QiXiManhua (1.3.5)

### Source new URL

http://m.qiximh3.com/

### Other details

图源加载不出，web可以打开；
报错：Cannot begin reading element , unexpected token :10 at path :$ JSON input :

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by YuGhi-bug** [comment]
same problem

**Comment by EricFoodTab** [comment]
maybe write it in english as some mods/admins may not understand what you typed in details
