### ISSUE TITLE
Mangafreak base url update

### ISSUE THREAD

**Issue by ashley-how** [tachiyomiorg/tachiyomi-extensions#14376]
### Source information and language

Mangafreak 1.3.7

### Source new URL

https://w14.mangafreak.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by RazredgeBR** [comment]
# This NEEDS FIXING!!
Please don't just dismiss this issue and refer to the bot instructions.
