### ISSUE TITLE
Mangafreak failing to load chapters from Onepunch-Man

### ISSUE THREAD

**Issue by RazredgeBR** [tachiyomiorg/tachiyomi-extensions#14373]
### Source information and language

Mangafreak 1.3.7 (English)

### Steps to reproduce

It won't load new chapters. App gives an error.
The source is also somewhat broken. Doesn't load anything besides the "latest" list. Search is also not working.
I did my due diligence in order to try and fix it on my end. Nothing worked. I did the most basic stuff multiple times to be sure.

### Expected behavior

Expect the new chapters to appear on the list.
The page should also load when trying to use the browser.
Extension should load "Popular" category and search should work as well.

### Actual behavior

Chapters already on the list work, but always fails to load the new one to the list. Browser is also not loading.
Going through the extension has mixed results, but it's not working as intended anyway.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_20221125-014934928](https://user-images.githubusercontent.com/82561645/203905110-33ffbb77-9b55-4d36-8297-cfc0bd027306.jpg) (Trying to load the webview)
![Screenshot_20221125-020750121](https://user-images.githubusercontent.com/82561645/203905374-f225a419-f468-4b45-a01a-0e8abc902b1e.jpg) (the list as it currently is)
![Screenshot_20221125-020855644](https://user-images.githubusercontent.com/82561645/203905461-b76f8de1-d580-4cd7-b700-7e85b50854d8.jpg) (Actual webpage when loaded through the OperaGX browser. There is one new chapter that is not being discovered by the app)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> Browser is also not loading.

Please actually refer to what the bot posted in #14372 ...

Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

> **If they don't work, migrate to other sources or wait until they lower their protection.**

**Comment by RazredgeBR** [comment]
> > Browser is also not loading.
> 
> Please actually refer to what the bot posted in #14372 ...
> 
> Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
> 
> > **If they don't work, migrate to other sources or wait until they lower their protection.**

Hello. That issue was posted by me as well. And I would not be posting twice if following those instructions fixed the issue. That's why I was very careful not to mention "cloudflare" in this issue, and made myself very clear about the fact that I did my due diligence, I emphasized that I even did everything twice.

So, could you possibly at least check this issue before dismissing it?
