### ISSUE TITLE
Hentaidexy

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#14397]
### Source information and language

Hentaidexy 1.3.28 English

### Source new URL

https://www.hentaidexy.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by dejavui** [comment]
Closed #14477

**Comment by BLACKxSUN** [comment]
Note : they closed there website and open another one and use the link that i put it

**Comment by BLACKxSUN** [comment]
> Note : they closed there website and open another one and use the link that i put it

Just so there is no confusion, this happened before I posted

**Comment by BLACKxSUN** [comment]
![Screenshot_20221209-190955_Tachiyomi](https://user-images.githubusercontent.com/93000786/206744332-cad38fbe-b7f7-453f-b6c8-53a5f2eabad9.jpg)

Its still not work
