### ISSUE TITLE
New URL for comicextra.com

### ISSUE THREAD

**Issue by Generator** [tachiyomiorg/tachiyomi-extensions#14402]
### Source information and language

ComicExtra 13.11 (English)

### Source new URL

https://ww1.comicextra.com/

### Other details

www.comicextra.com redirects to ww1.comicextra.com breaking the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by dejavui** [comment]
Closed #14443
