### ISSUE TITLE
Mangastic domain changed

### ISSUE THREAD

**Issue by relenayui** [tachiyomiorg/tachiyomi-extensions#14407]
### Source information and language

Mangastic english

### Steps to reproduce

1. Go to mangastic source
2. Does not show any manga list.
3. Tap source, redirects to "https://mangastic.io/" 

### Expected behavior

Should be pulling from "https://mangastic.io/"  their new updated website instead of their old website "https://mangastic.me/"

### Actual behavior

Shows error 400

### Tachiyomi version

0.14.2

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Azim** [comment]
4 months, still not fixed
