### ISSUE TITLE
Meitua.top url change

### ISSUE THREAD

**Issue by Masrurkeepit** [tachiyomiorg/tachiyomi-extensions#14410]
### Source information and language

Meitua.top 1.3.2 (All)

### Source new URL

https://meitu1.one

### Other details

please change the url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by dejavui** [comment]
Closed #14443
