### ISSUE TITLE
Fiz manga site not found 

### ISSUE THREAD

**Issue by Ironmanash** [tachiyomiorg/tachiyomi-extensions#14414]
### Source information and language

Fiz manga 1.3.26

### Steps to reproduce

Open chapter 
Error code http 404

### Expected behavior

Should be able to read chapter 

### Actual behavior

Gives error message

### Tachiyomi version

Stable 0.14.2

### Android version

Android version: 12 (SDK 31) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me, try troubleshooting again
