### ISSUE TITLE
Hentai20 bypass failure

### ISSUE THREAD

**Issue by Nuclearpopsical** [tachiyomiorg/tachiyomi-extensions#14425]
### Source information and language

Hentai20 1.3.28 (English)

### Steps to reproduce

1. Open tachiyomi
2. Select extensions tab
3. Open hentai20
4. Select web view

### Expected behavior

Checkmark should appear and hentai20 site opens in web view as well as app.

### Actual behavior

The bypass page continuously refreshes without bypassing.

### Tachiyomi version

0.14.2

### Android version

Android 13

### Other details

I had this issue once about 9 months ago in the past and changing the dns over http setting fixed it however this time none of the steps for troubleshooting worked

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If they don't work, migrate to other sources or wait until they lower their protection.
