### ISSUE TITLE
Komik cast

### ISSUE THREAD

**Issue by Payyforger** [tachiyomiorg/tachiyomi-extensions#14423]
### Source name

Komik Cast

### Source link

https://komikcast.site/

### Language

Bahasa indonesia

### Other details

Http 404

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Payyforger** [comment]
Saya tidak bisa mengakses sumber tersebut

**Comment by TheKingTermux** [comment]
It's not a "Source Request"
It's a "Bug" actually 
You can open an issues for "Bug" if you have problem like this, not "Source Request"
