### ISSUE TITLE
Problema na fonte Izakaya

### ISSUE THREAD

**Issue by Kirito-Senpai9** [tachiyomiorg/tachiyomi-extensions#14421]
### Source information and language

Izakaya 1.3.27

### Steps to reproduce

Não está carregando os mangás no aplicativo e nem faz download
The manga is not loading in the application and it does not download
![Screenshot_20221130-125749_Tachiyomi](https://user-images.githubusercontent.com/90297461/204846554-2c10cd92-20dd-418a-9097-b94b765a5a4a.jpg)
![Screenshot_20221130-125740_Tachiyomi](https://user-images.githubusercontent.com/90297461/204846562-ae68954b-1154-44c9-b4f3-3cbad8696d93.jpg)

### Expected behavior

Ela deveria exibir os mangás e carregar quando for navegando

### Actual behavior

![Screenshot_20221130-125749_Tachiyomi](https://user-images.githubusercontent.com/90297461/204846784-cb7511fb-b8de-4216-9e5a-ad5858bac732.jpg)
![Screenshot_20221130-125740_Tachiyomi](https://user-images.githubusercontent.com/90297461/204846794-40ceda1d-d73c-4af6-b944-8bb8a4eb6cc2.jpg)

### Tachiyomi version

 0.14.2

### Android version

Android 11

### Other details

Fonte Izakaya não carrega nem exibi os mangá no Tachiyome
Izakaya font does not load or display manga on Tachiyome 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their website is down and you can confirm that by the infinite loading on WebView on the screenshot you sent. Please do try the troubleshooting steps linked in the acknowledgements section first also.
