### ISSUE TITLE
Raw-manga Chapter Not Found

### ISSUE THREAD

**Issue by HeroSharma** [tachiyomiorg/tachiyomi-extensions#14431]
### Source information and language

Raw-manga 1.3.1(English)

### Steps to reproduce

1 Browse Raw-manga
2.Open manga

3. Not chapter found

### Expected behavior

If i open manga there should be chapter list available 

### Actual behavior

I open manga and there's no chapter found 

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by whghjyh** [comment]
I also encountered this bug, and I hope it can be solved.
