### ISSUE TITLE
مانجا ليك ar.mangalek (failed to bypass cloudflare)

### ISSUE THREAD

**Issue by MineStar3rab** [tachiyomiorg/tachiyomi-extensions#14438]
### Source information and language

When open any chapter's the say failed bypass cloudflare

### Steps to reproduce

1. Open مانجا ليك
2. Open any manga
3. open the chapter
4.  Failed to bypass cloudflare
![Screenshot_2022-12-02-13-45-01-693_eu kanade tachiyomi](https://user-images.githubusercontent.com/49875399/205285786-0660ca3b-9594-4273-91c2-8c5fa08683e0.jpg)

### Expected behavior

They should open chapter reader

### Actual behavior

![Screenshot_2022-12-02-13-51-24-836_eu kanade tachiyomi](https://user-images.githubusercontent.com/49875399/205286820-ec35ca2c-a8bc-405c-8eea-598b06730281.jpg)
![Screenshot_2022-12-02-13-51-26-797_eu kanade tachiyomi](https://user-images.githubusercontent.com/49875399/205286823-d9928922-ac13-4cf1-acd5-332ad18fb7b1.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 10

### Other details

This problem has been going on for about 2 weeks now please solve it quickly

Thanks for read that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MineStar3rab** [comment]
I've tried that but it didn't work

**Comment by alessandrojean** [comment]
Then wait until they lower their protection or migrate to other sources.
