### ISSUE TITLE
Ozul scan

### ISSUE THREAD

**Issue by uwKILLER** [tachiyomiorg/tachiyomi-extensions#14447]
### Source information and language

Ozul scan, 1.3.21, Arabic

### Steps to reproduce

Image nor loaded 

### Expected behavior

Cheaper load 

### Actual behavior

![Screenshot_20221203_124638_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/107407548/205478354-0a0d3a91-d0b5-4419-af00-572f70117caf.jpg)

### Tachiyomi version

1.8.5

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
load just fine for me
