### ISSUE TITLE
Request to back removed Source  (manga swat ) steal from anther scannes

### ISSUE THREAD

**Issue by Novamanx** [tachiyomiorg/tachiyomi-extensions#14456]
### Source information and language

https://swatmanga.me/  (arabic)  

### Steps to reproduce

join mangaswat (https://swatmanga.me/)

join First hunter (https://swatmanga.me/manga/first-hunter/)

roll down you will find prove that its from anther scanne called comicdom.org :
![image](https://user-images.githubusercontent.com/115431595/205509272-ed5b320d-c29e-4bf5-9c99-dd89659d6863.png)

### Expected behavior

not find prove

### Actual behavior

finded prove of steal from ather scannes so we can request to extention to back

### Tachiyomi version

0.14.2

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
i believe they use is as raw provider, since comicdom is only english translation (i think) 
idk if that still count

**Comment by CarlosEsco** [comment]
@BelalKing777 can you provide more samples. Translating from another language isn't stealing the scans
