### ISSUE TITLE
No limit reading

### ISSUE THREAD

**Issue by Ireadtofast** [tachiyomiorg/tachiyomi-extensions#14459]
### Source name and language

IsekaiScan.com

### Describe your suggested feature

It should not limit the readers reading time becauae its suck..i want to rewd all day but they said timeout and i cant read it now.

### Other details

Limit the rwder reading time is good but i want to read it all day because its a 2,800+ chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Timeout means the extension didn't managed to reach the website in time, there's no limit imposed in the extension at all. Try the troubleshooting guide linked in the acknowledgements section first and check in WebView if their server isn't having issues, which likely is the case.
