### ISSUE TITLE
remove shinobiscans extension

### ISSUE THREAD

**Issue by FabriSS** [tachiyomiorg/tachiyomi-extensions#14457]
### Source link

https://shinobiscans.com/

### Other details

this is the url of the extension
https://github.com/tachiyomiorg/tachiyomi-extensions/tree/d0793a1741a80b22537c77327810d4fc2185baa1/multisrc/overrides/madara/shinobiscans

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by FabriSS** [comment]
I have sent proof of ownership to OncePunchedBot

**Comment by OncePunchedMan** [comment]
proof of ownership has been sent to me. is valid

**Comment by FabriSS** [comment]
what are the lead times?
