### ISSUE TITLE
Mangas Origines: net::ERR_FAILED

### ISSUE THREAD

**Issue by Cawaa** [tachiyomiorg/tachiyomi-extensions#14458]
### Source information and language

Mangas Origines 1.3.29 FR

### Steps to reproduce

1. Go to Manga Origines extension
2. Select any series
3. Refresh chapters 
4. Either the selected series is not up to date (old chapter and cannot bypass cloudflare) or it just says "cannot bypass cloudflare"
5. Click on webview
6. This appears
![IMG_20221204_232740](https://user-images.githubusercontent.com/112283826/205519304-be4fc831-5ced-48f8-a2b8-fa19aa6a031b.jpg)

### Expected behavior

I should just be able to view the chapters normally

### Actual behavior

Instead this appears
![IMG_20221204_232740](https://user-images.githubusercontent.com/112283826/205519378-e4c0a2cd-be81-48b0-9f21-1cb8960331a5.jpg)

### Tachiyomi version

App version: 0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dekizo** [comment]
hello just to inform you all you can do with mangas origins extension it's now is to see the list of works they offer since they raised up the cloudflare protection

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, migrate to other sources or wait until they lower their protection.
