### ISSUE TITLE
Manga extensions 

### ISSUE THREAD

**Issue by TheGoldenSun** [tachiyomiorg/tachiyomi-extensions#14472]
### Source information and language

Bato.to 1.3.30 (multi) 

### Steps to reproduce

1. All Manga extensions not just bato.to isn't loading properly when tapping onto the word latest 

### Expected behavior

Improve for all manga extensions to load.

### Actual behavior

When tapping "latest" onto any other manga extensions it doesn't seem to load every single manga stories besides what's on the popular column.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

![Screenshot_20221205_051047](https://user-images.githubusercontent.com/104534608/205710879-4f7244d3-6d30-410d-89d3-1a1adf389bc4.png)

I hope someone is able to resolve this because it's been happening to me before and after I managed to update my Tachiyomi preview app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce this issue, this is most likely an issue with your internet connection. Have you tried any of the Bato.to mirrors? Should be in the extension settings. If that doesn't work you could try enabling DoH or using a VPN. If you need further assistance I would recommend [asking in the Discord ](https://discord.gg/tachiyomi) or [check out the troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

**Comment by vetleledaal** [comment]
Also, if this is an issue with _all_ extensions you should [open an issue in the main repo](https://github.com/tachiyomiorg/tachiyomi) instead.
