### ISSUE TITLE
Vicio Hentai

### ISSUE THREAD

**Issue by jeanz3ra** [tachiyomiorg/tachiyomi-extensions#14484]
### Source name

Vicio Hentai

### Source link

https://viciohentai.com/

### Language

Brazilian Portuguese

### Other details

18+ Adult Content = YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Simple blog that doesn't guarantee a proper fixed structure for an extension to be made, closing it.
