### ISSUE TITLE
Library - Sort by Artist

### ISSUE THREAD

**Issue by blackheart911126** [tachiyomiorg/tachiyomi-extensions#14480]
### Describe why this should be added

Spotting duplicate manga/manhwa in library especially from different sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/205827539-459609b0-5164-4544-aad9-7c4d5803d896.png)
