### ISSUE TITLE
MangaMX

### ISSUE THREAD

**Issue by andysan02** [tachiyomiorg/tachiyomi-extensions#14504]
### Source information and language

MangaMx Español 1.3.13

### Source new URL

https://manga-oni.com/

### Other details

MangaMx cambió de URL y nombre a MangaOni

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Duplicate of #14227
