### ISSUE TITLE
Mangasee: When in browse mode, most cover images fail to load

### ISSUE THREAD

**Issue by Thomasedv** [tachiyomiorg/tachiyomi-extensions#14518]
### Source information and language

Mangasee 1.3.34 (English)

### Steps to reproduce

1. Got to Browse
2. Find Mangasee in your sources and click it to start browsing mangas

### Expected behavior

Covers should load as expected. (One by one presumably, since there seems to be a rate limit on Mangasee, I don't have a problem with that.)

### Actual behavior

Usually one cover loads, then the rest one by one get a broken image symbol as the application tries to load the images for the rest of the covers. 

### Tachiyomi version

r5349 (3749cee28, 10/12/22) - latest dev at time of writing

### Android version

Android 11

### Other details

Possibly related to #12680, though this is another source, so perhaps some deeper issues than the extension one. Granted, the other sources I use do not exhibit this issue. 

Reiterating that this is **not** that it loads slowly. 

Opening a specific manga will load the cover after a while once the requests finish up, refreshing inside a mange will also refresh the cover. But in the browse overview for any sorting (popular/latest) it won't load images. 

The last changes to thumbnail handling seems to be in this change #12654. I don't know the language or how the implementation works, but if I were to make half of an educated guess it seems the thumbnail url is saved to avoid making multiple calls to the website for the thumbnail urls. Might be that this url isn't universal, which means that when the id for another manga is inserted, it 404s or something like that. (I couldn't find any way to read logs on my phone without root/adb, and the crash log doesn't mention anything naturally.) The more I think about it, the more certain I'm this could be the cause. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> I have tried the troubleshooting guide.
clear your db will generally fix this issue.

**Comment by Thomasedv** [comment]
Indeed it did. I thought Clear DB was a wipe all method, which I wasn't prepared to do... Sorry for that 😓
