### ISSUE TITLE
YugenMangas search not found

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#14519]
### Source information and language

YugenMangas 1.3.6 (Español)

### Steps to reproduce

look for something (mangas, whatever)

### Expected behavior

manga should appear

### Actual behavior

"No results found" appears

### Tachiyomi version

Tachiyomi Stable 0.14.2 

### Android version

Android 12

### Other details

![Screenshot_20221211_154629_Tachiyomi](https://user-images.githubusercontent.com/101371218/206930888-5a6c7318-6855-4494-ac77-122c5f3afe06.jpg)
![Screenshot_20221211_154640_Tachiyomi](https://user-images.githubusercontent.com/101371218/206930889-cfed1574-508c-46bc-a6db-09e3e6df7ded.jpg)
the web search section does work

It's one of the best sources, would be appreciated 🙇🏻

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seew3l** [comment]
Additional: It only finds the manga on the first page, if nothing is found, it does not continue searching

**Comment by alessandrojean** [comment]
The search uses their All series page, which they don't show some series there, and we can't fix that, it's up to them. We can't use their search for now as it lacks information for the extension. Try playing with the filters in the extension as well or wait until they fix that.
