### ISSUE TITLE
manman

### ISSUE THREAD

**Issue by RyomeSukuna** [tachiyomiorg/tachiyomi-extensions#14521]
### Source name

manman

### Source link

https://www.hanman.cyou/

### Language

Chinese

### Other details

+18 / NSFW: yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by RyomeSukuna** [comment]
Yes, it's working fine!

Em ter, 13 de dez de 2022 07:24, stevenyomi ***@***.***>
escreveu:

**Comment by stevenyomi** [comment]
> Yes, it's working fine!

Could you post a link to any chapter that loads correctly for you? The images are all 404 at my end.

**Comment by RyomeSukuna** [comment]
it's loading fine for me.

Em ter, 13 de dez de 2022 09:04, stevenyomi ***@***.***>
escreveu:

**Comment by stevenyomi** [comment]
> it's loading fine for me.

Please post a **link** to a **chapter** that loads fine for you.
