### ISSUE TITLE
komikcast

### ISSUE THREAD

**Issue by alpqm** [tachiyomiorg/tachiyomi-extensions#14523]
### Source information and language

komikcast 1.3.39

### Steps to reproduce

1.The latest press of the Komikcast extension
2.Some comic covers appear, some don't appear 
![Screenshot_2022_1212_154622](https://user-images.githubusercontent.com/101073177/207003515-6ff678fa-4bf3-42cb-96a9-6bbaf0f0ea42.jpg)

### Expected behavior

There should be a lot of cover images that appear 

### Actual behavior

Many cover images do not appear 

### Tachiyomi version

0.14.2

### Android version

11

### Other details

![Screenshot_2022_1212_154622](https://user-images.githubusercontent.com/101073177/207003788-1f6e6d1b-8a2a-49a2-be2b-8f8ef9eaf53c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Might be related to tachiyomiorg/tachiyomi#8476

**Comment by Riztard** [comment]
also it works for me. have you really tried the troubleshooting guide?
