### ISSUE TITLE
Bato the image is cropped

### ISSUE THREAD

**Issue by RaidBuster** [tachiyomiorg/tachiyomi-extensions#14533]
### Source information and language

Bato.to 1.3.30

### Steps to reproduce

Read any comic

### Expected behavior

![Screenshot_2022-12-13-13-27-33-007_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/207243285-9a5f40a4-3c71-485e-a065-f20c529c0d1d.jpg)
![Screenshot_2022-12-13-13-27-44-151_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/207243363-9211543e-e862-402a-8d64-74ee68bd47a9.jpg)

### Actual behavior

![Screenshot_2022-12-13-13-22-40-591_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/207243016-c716eaac-c840-4f71-a297-1616c9a01d77.jpg)
![Screenshot_2022-12-13-13-22-47-457_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/207243025-56124027-e7b6-4922-971a-c8b10daafe30.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
turn off crop borders
