### ISSUE TITLE
QueensManga extension can be removed

### ISSUE THREAD

**Issue by euijoonyeo** [tachiyomiorg/tachiyomi-extensions#14536]
### Source information and language

"queensmanga 1.3.27 (Arabic)"

### Steps to reproduce

Queensmanga changed their domain to https://golden-manga.me/

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.14.2

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The new site is already requested in #12749
