### ISSUE TITLE
[TruyenQQ] changed their domain

### ISSUE THREAD

**Issue by dtsdt** [tachiyomiorg/tachiyomi-extensions#14550]
### Source information and language

TruyenQQ 1.3.7 (Tiếng Việt)

### Source new URL

https://truyenqqvip.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Closed in favour of #14623
