### ISSUE TITLE
Domain change

### ISSUE THREAD

**Issue by lunarpix** [tachiyomiorg/tachiyomi-extensions#14558]
### Source information and language

DoujinDesu 1.3.3 (indonesia) 

### Source new URL

https://212.32.226.234/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Using RAW IPs is not a good idea. If they ever register a new domain, feel free to open a new issue.
