### ISSUE TITLE
MangaForest Http error 404

### ISSUE THREAD

**Issue by bluuulines** [tachiyomiorg/tachiyomi-extensions#14564]
### Source information and language

MangaForest 1.3.10

### Steps to reproduce

Download manga/manhwa updates

### Expected behavior

Proceed in downloading the update contents

### Actual behavior

Returns `HTTP error 404`

### Tachiyomi version

Tachij2k 1.5.9

### Android version

Android 11

### Other details

https://media.discordapp.net/attachments/349436576037732355/1052941577745600613/Screenrecording_20221215_213154.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Domain changed to https://mangaforest.me/
