### ISSUE TITLE
worldmanhwas

### ISSUE THREAD

**Issue by lunarpix** [tachiyomiorg/tachiyomi-extensions#14565]
### Source name

worldmanhwas.com

### Source link

https://worldmanhwas.com/

### Language

Indonesia

### Other details

18+/NSFW=YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by alpqm** [comment]
Up👍

**Comment by alpqm** [comment]
Please add soon 🙏

**Comment by alpqm** [comment]
@TheKingTermux 🙏😅

**Comment by TheKingTermux** [comment]
> @TheKingTermux 🙏😅

Di ping donk 🤣

**Comment by alpqm** [comment]
> > @TheKingTermux 🙏😅
> 
> Di ping donk 🤣

Tapi kan biasa nya ente yang nambahin ekstensi indo

**Comment by TheKingTermux** [comment]
> Tapi kan biasa nya ente yang nambahin ekstensi indo

Gajuga sih
Ada 1 org lagi kok

**Comment by alpqm** [comment]
> > Tapi kan biasa nya ente yang nambahin ekstensi indo
> 
> Gajuga sih Ada 1 org lagi kok

kalau mau mintak ekstensi indo tinggal PING ente aja lah😁😅

**Comment by alpqm** [comment]
> > > Tapi kan biasa nya ente yang nambahin ekstensi indo
> > 
> > 
> > Gajuga sih Ada 1 org lagi kok
> 
> kalau mau mintak ekstensi indo tinggal PING ente aja lah😁😅

Biar cepat ditambahinya

**Comment by TheKingTermux** [comment]
> > kalau mau mintak ekstensi indo tinggal PING ente aja lah😁😅
> 
> Biar cepat ditambahinya

W dah ditandain anj*r 🤣

**Comment by alpqm** [comment]
> > > kalau mau mintak ekstensi indo tinggal PING ente aja lah😁😅
> > 
> > 
> > Biar cepat ditambahinya
> 
> W dah ditandain anj*r 🤣

🤣

**Comment by alpqm** [comment]
> > Tapi kan biasa nya ente yang nambahin ekstensi indo
> 
> Gajuga sih Ada 1 org lagi kok

Siapa tu

**Comment by TheKingTermux** [comment]
> Siapa tu

@Riztard

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/208234167-b2933fd7-2b6a-4b28-99b1-fbe4983b5316.png)

**Comment by alpqm** [comment]
> ![image](https://user-images.githubusercontent.com/16263232/208234167-b2933fd7-2b6a-4b28-99b1-fbe4983b5316.png)

🤨🤫
