### ISSUE TITLE
Clarify use of "Factory source" tag

### ISSUE THREAD

**Issue by vetleledaal** [tachiyomiorg/tachiyomi-extensions#14568]
### Describe why this should be added

The "Factory source" tag may be ambiguous in some contexts, especially in connection with the "Bug" tag.

When used alongside the "Source request" tag it is pretty clear. This means the yet-to-be-added site uses either some existing factory/multisrc or can be made into one due to the theme being common across multiple sites.

However, when it comes to "Bug" issues it is unclear what the "Factory source" tag means. It could mean that the existing extension is a factory/multisrc. Alternatively it could mean that the existing extension is moving to a factory/multisrc.

Use of the "Factory source" tag should either be clarified or another tag should be added to account for this ambiguity.

### Other details

Brought up by @Riztard in #13968. Please correct me if I've misinterpreted what you previously mentioned.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Renamed to "Can be added to source factory".

**Comment by vetleledaal** [comment]
Right, so there's no desire to tag bug issues that happen to be part of a source factory?

**Comment by arkon** [comment]
I don't think so. I think it's relatively rare for there to be a bug that requires the base source factory to be changed, but we can add another label if that seems necessary.

**Comment by vetleledaal** [comment]
I think it's useful to more easily differentiate source factory issues from individual extensions. The extra complexity for compiling source factory extensions and consideration of changes affecting other sites is of note.

I would prefer a tag if possible. Do let me know so I can either remove or replace tags made in error.

**Comment by arkon** [comment]
Renamed back to "Factory source" and updated description to "Requested source can be added to multi-source factory or report affects multiple sources in factory".

**Comment by Riztard** [comment]
now what about sources using a multi-src theme but no multi-src factory yet

**Comment by arkon** [comment]
Move then to factories then

**Comment by Riztard** [comment]
so use the "Factory source" tag?

**Comment by arkon** [comment]
If you think the tag use is ambiguous, just leave a clarifying comment on what you mean when adding it.
