### ISSUE TITLE
HentaiHand: No results found

### ISSUE THREAD

**Issue by EmanuelRD21** [tachiyomiorg/tachiyomi-extensions#14566]
### Source information and language

HentaiHand 1.3.7

### Steps to reproduce

![Screenshot_20221215-131410](https://user-images.githubusercontent.com/120670631/207926708-7866adb5-167d-4dcd-89b9-7d7a979d536c.png)

When entering the HentaiHand extension through the Tachiyomi Application, it does not show the manga, but in the web version it works perfectly 

### Expected behavior

The expected behavior would be to show manga available from the outside

### Actual behavior

does not load anything

### Tachiyomi version

0.14.2

### Android version

Android 9.0

### Other details

hope they can solve it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Closing in favor of #16951
