### ISSUE TITLE
Ciayo comics extension cannot grab Indonesian comic chapter

### ISSUE THREAD

**Issue by MikuDroid** [tachiyomiorg/tachiyomi-extensions#1457]
https://www.ciayo.com/id is for Indonesian translated comis
https://www.ciayo.com/en is for English translated, both on same domain

**Comment by as280093** [comment]
Here the icons
[ciayo.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612561/cyida.zip)

**Comment by MikuDroid** [comment]
Thanks for adding ciayo to the extension!

**Comment by happywillow0** [comment]
Did you enable the Indonesia language in the catalog screen? 
It should be there in the language filters button on the top right.

**Comment by MikuDroid** [comment]
> Did you enable the Indonesia language in the catalog screen?
> It should be there in the language filters button on the top right.

Unfortunately i can't find the Indonesian language option on catalog screen, i can only find Indonesian option for webtoon.

**Comment by MikuDroid** [comment]
Latest ciayo extension can't grab Indonesian comics, it's says "page list is empty" after pressing the chapter. However it browse the comic title just fine.

**Comment by curche** [comment]
No longer relevant since Ciayo has been removed (Refer #5509)
