### ISSUE TITLE
ManhuaHot: chapter images don't load

### ISSUE THREAD

**Issue by Rubberxgum** [tachiyomiorg/tachiyomi-extensions#14573]
### Source information and language

ManhuaHot 1.3.26 (English)

### Steps to reproduce

1. Select a manga from ManhuaHot.
2. Open a chapter from that manga.
3. Wait for images to load.

### Expected behavior

The images should load after a few seconds.

### Actual behavior

Images don't show up even after waiting for minutes.

### Tachiyomi version

TachiJ2K 1.5.9

### Android version

Android 12

### Other details

Image doesn't load in WebView too. But it does show up  on browser. This issue exist in OG Tachiyomi too so it's definitely an issue with the extension.

![Screenshot_20221216-175556_Pixel Launcher](https://user-images.githubusercontent.com/90501519/208074116-9a587955-20a7-4e3e-b57e-da5dd4a52e8f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rubberxgum** [comment]
What does the "factory source" tag mean? Will this issue be fixed?

**Comment by vetleledaal** [comment]
> What does the "factory source" tag mean?

See #14568
> Will this issue be fixed?

Maybe. No ETAs are given as anyone can work on issues as they wish.
