### ISSUE TITLE
[Kemono] Only the first page can be displayed

### ISSUE THREAD

**Issue by Hakoyu** [tachiyomiorg/tachiyomi-extensions#14576]
### Source name and language

[Kemono] All

### Describe your suggested feature

There are many pages in the site, and all of them need to be displayed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> "You can change how many posts to load in the extension preferences."

**Comment by Hakoyu** [comment]
> > “您可以在扩展首选项中更改要加载的帖子数量。”

Thank you
