### ISSUE TITLE
AstronomicalScans

### ISSUE THREAD

**Issue by revers95** [tachiyomiorg/tachiyomi-extensions#14606]
### Source name

AstronomicalScans

### Source link

https://www.astronomicalscan.it/

### Language

Italiana

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by revers95** [comment]
Hi I would like to kindly ask if I could ask how the process was going to get the page for my site (AstronomicalScan) inside tachiyomi!!! Excuse me for bothering you

**Comment by revers95** [comment]
Hi I would like to kindly ask if I could ask how the process was going to
get the page for my site (AstronomicalScan) inside tachiyomi!!! Excuse me
for bothering you

Il lun 19 dic 2022, 19:00 CrepeTF ***@***.***> ha scritto:

**Comment by alessandrojean** [comment]
The issue is open, so it's needed to wait until some contributor have free time and choose to implement it. We can't really provide an ETA because of that.

**Comment by revers95** [comment]
Alright thanks I just wanted to know how it was progressing thank you very much for information I will look forward to it sorry again for the trouble!

**Comment by vetleledaal** [comment]
Domain is parked
