### ISSUE TITLE
Can't search on extensions(nox emulator)

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#14618]
### Source information and language

All sources

### Steps to reproduce

1. Open any source, 
2. tap on searching tab, 
3. write the name of manga
4. Clicking enter

### Expected behavior

The source is searching for named manga etc.

### Actual behavior

Nothing happens.

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

Searching in library working without problem. Before version 0.14 sources worked too. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
