### ISSUE TITLE
Readmanga failed to load image

### ISSUE THREAD

**Issue by Makishimu120** [tachiyomiorg/tachiyomi-extensions#14627]
### Source information and language

Readmanga 1.3.54 (русский)

### Steps to reproduce

1.open any manga
2.Flipping
3.See loaded pages

### Expected behavior

Pages loaded

### Actual behavior

Some pages load normally and some do not load at all. Tried from mobile internet and WiFi. rebooted phone, cleared cache. did not help. Even when I try to download the chapter, it gives an error http 300

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

Viewing a chapter in webview works great, but this is not a solution to the problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DarkHole1** [comment]
Same problem. Some manga (e.g. One-Punch Man) loads correctly, but a lot of don't load at all (e.g. Toaru Majutsu no Index)

**Comment by slehernaf** [comment]
it's really weird, especially since they have a tachiyomi [clone](https://github.com/crazy-tea-party/android/releases/tag/vr-0.95.0)  with stripped down functionality that seems to work just fine.
