### ISSUE TITLE
TruyenQQ "No pages found" error

### ISSUE THREAD

**Issue by minhngoc25a** [tachiyomiorg/tachiyomi-extensions#14624]
### Source information and language

TruyenQQ 1.3.8 (Vietnamese)

### Steps to reproduce

1. Open Tachiyomi >> Browse
2. Under Sources, tap TruyenQQ
3. The app loads comic entries successfully. Click on any comic entry.
4. Click on any chapter. The chapter exits immediately with the "No pages found" error.

### Expected behavior

Tachiyomi should've loaded the chapters normally, regardless of the URL change in #14623. This is because Tachiyomi supports fast redirects (slow redirect puts the page on countdown for a few seconds before redirecting, and it doesn't work because of the "return error after a certain time passes" algorithm implemented in Tachiyomi).

### Actual behavior

The chapter exits immediately with the "No pages found" error.

### Tachiyomi version

0.14.2

### Android version

Android 9, Redmi 5

### Other details

https://youtube.com/shorts/hxyBKxlZcZw?feature=share

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Root cause #14623
