### ISSUE TITLE
Random scan, fail to bypass cloudflare

### ISSUE THREAD

**Issue by Skyprak** [tachiyomiorg/tachiyomi-extensions#14626]
### Source information and language

Random scan (português-brasil)-1.3.41

### Steps to reproduce

Sign in to webview or source

### Expected behavior

![20221220_203530](https://user-images.githubusercontent.com/115963154/208786393-8fb7515f-b86f-4da5-ade9-d1881b8a5e47.jpg)

Loading, updating and display of scan works

### Actual behavior

![20221220_203207](https://user-images.githubusercontent.com/115963154/208786656-bfd80179-184a-4f70-8302-03f735405427.jpg)
![20221220_203151](https://user-images.githubusercontent.com/115963154/208786660-7f6e694f-bc30-4732-b05f-b8ce48967258.jpg)

Infinite loading to bypass cloudflare

### Tachiyomi version

0.14.2

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
