### ISSUE TITLE
KlanKomik: domain is parked, can be removed

### ISSUE THREAD

**Issue by Mozzaru** [tachiyomiorg/tachiyomi-extensions#14635]
### Source information and language

Klankomik 1.3.22

### Steps to reproduce

![Screenshot_2022-12-22-22-57-32-52_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209174349-16a9dccf-02a5-4a62-aa13-167274e531d0.jpg)
![Screenshot_2022-12-22-22-57-26-36_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209174315-7fa0de20-8527-4550-8801-3b2dc4ae9f3f.jpg)

### Expected behavior

![Screenshot_2022-12-22-22-57-26-36_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209174252-4e1fe3b5-dc33-4984-9dac-7aea66cf5bb5.jpg)
![Screenshot_2022-12-22-22-57-32-52_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209174273-715235af-93bf-4983-8c85-8e2596b1a7ac.jpg)

### Actual behavior

![Screenshot_2022-12-22-22-57-26-36_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209174156-5388d9f7-2cdb-431a-9f74-d7b74bbe3392.jpg)
![Screenshot_2022-12-22-22-57-32-52_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209174172-874aed01-5e38-4f19-968e-0186f6ed4b0e.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

![Screenshot_2022-12-22-22-57-26-36_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209173947-39c66907-6e18-40e5-96bd-857af60e0564.jpg)
![Screenshot_2022-12-22-22-57-32-52_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209173977-8804b600-f2ab-4639-b3a3-48ea137c6291.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
That's a parked domain, the extension can be removed.

**Comment by vetleledaal** [comment]
/edit-title "KlanKomik: domain is parked, can be removed"
