### ISSUE TITLE
Vyvymanga URL change

### ISSUE THREAD

**Issue by RaidBuster** [tachiyomiorg/tachiyomi-extensions#14632]
### Source information and language

Vyvymanga 1.3.3 English

### Source new URL

https://vyvymanga.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
@arkon or @CarlosEsco seems this one doesn't get's closed by PR #14644

**Comment by AntsyLich** [comment]
No need to mention anyone just comment if issue needs to be closed
