### ISSUE TITLE
Manhwa-Latino extension does not grab the chapters of any manhwa

### ISSUE THREAD

**Issue by Ram3021** [tachiyomiorg/tachiyomi-extensions#14634]
### Source information and language

Manhwa-Latino 1.3.20 (Español)

### Source new URL

https://manhwa-latino.com/

### Other details

![Screenshot_2022-12-22-10-19-18-14_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/121246444/209171100-6b0fe291-c948-42df-a617-769962cfd84d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension already uses this URL you provided. Please do fill the Issue report form instead as this one is not the correct one for this.
