### ISSUE TITLE
Please fix extension 

### ISSUE THREAD

**Issue by Mozzaru** [tachiyomiorg/tachiyomi-extensions#14636]
### Source information and language

Mg komik 1.3.28

### Steps to reproduce

can't read in the mgkomik extension, in other extensions can you please fix it

### Expected behavior

can't read in the mgkomik extension, in other extensions can you please fix it🙏

### Actual behavior

can't read in the mgkomik extension, in other extensions can you please fix it🙏

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

![Screenshot_2022-12-22-23-55-51-08_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209186917-458cf374-06c6-4d84-ab20-8d28a14be9df.jpg)
![Screenshot_2022-12-22-23-55-54-87_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209186945-3030cc5e-bf39-416a-98d4-2a78f2735a8c.jpg)
![Screenshot_2022-12-22-23-56-00-92_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209186973-20e00ec5-0ab7-4ec1-b768-266dc1a9e226.jpg)
![Screenshot_2022-12-22-23-56-15-87_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209186987-a87c3751-96d3-4ba2-be13-383a631be765.jpg)
![Screenshot_2022-12-22-23-56-20-46_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/209187000-6ff8910e-27c8-4069-9fe4-a5d800e17f9b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the issue form correctly and provide the information requested.
