### ISSUE TITLE
WebtoonXYZ cannot bypass Cloudflare 

### ISSUE THREAD

**Issue by chet-sudo** [tachiyomiorg/tachiyomi-extensions#14648]
### Source information and language

WebtoonXYZ 1.3.29 (English)

### Steps to reproduce

1. Open WebtoonXYZ
2. Tachiyomi loading forever
3. Open in-app browser, redirected to Cloudflare, and it also loads forever

### Expected behavior

Can bypass Cloudflare 

### Actual behavior

Stuck in Cloudflare 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, migrate to other sources or wait until the source lower their protection, no ETA.
