### ISSUE TITLE
Extensions not updating

### ISSUE THREAD

**Issue by Rohan-Somadder** [tachiyomiorg/tachiyomi-extensions#14658]
### Source information and language

MangaDex 1.3.176

### Steps to reproduce

Go to the extensions tab and try to update any existing extension.

### Expected behavior

The extensions should update automatically.

### Actual behavior

Recently when a new update came for the MangaDex extension -
1. I tried updating it but it kept downloading the update and there was no progress
2. furthermore when I moved into another tab and came back the update was cancelled 
3. and this happens in loops.
4.  I also tried to reinstall the extension but then it doesn't download the update
5.  This is happening for all the extensions that have received an update.

### Tachiyomi version

Stable 0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Something in your connection is likely blocking your access to GitHub. Try following the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/) first, specially the DNS over HTTPS and VPN part.
