### ISSUE TITLE
MangasTK: No pages found

### ISSUE THREAD

**Issue by Ram3021** [tachiyomiorg/tachiyomi-extensions#14665]
### Source information and language

MangasTK 1.3.27 (Español)

### Steps to reproduce

1. Download the extension
2. Open the extension
3. Choose any manga or manhwa

### Expected behavior

![Screenshot_2022-12-24-10-11-38-90_a87fd7db6caa850b517aa6fa9d2fcd0e](https://user-images.githubusercontent.com/121246444/209439740-b2f71edb-32b6-4f84-85c5-753c00a055e0.jpg)

### Actual behavior

![Screenshot_2022-12-24-10-10-41-00_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/121246444/209439769-c1ab3973-c1f9-4582-94f5-6db52fb2455b.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Duplicate #14175?
