### ISSUE TITLE
Checking if the site connection is secure in ozul scans

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#14666]
### Source information and language

Ozul scans 1.3.21 العربية

### Steps to reproduce

https://user-images.githubusercontent.com/97411710/209442565-f968d56f-e407-48db-b865-ee6e5564726e.mp4

It just keep checking 

### Expected behavior

It should finish within a seconds

### Actual behavior

It just keep checking and the site refresh it self

### Tachiyomi version

1.8.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, migrate to other sources or wait until the source lower their protection, no ETA.
