### ISSUE TITLE
Comick.fun unreliable search results

### ISSUE THREAD

**Issue by AnataBakka** [tachiyomiorg/tachiyomi-extensions#14668]
### Source information and language

Comick.fun 1.3.17 (Multi)

### Steps to reproduce

Search, for example, for either "pokemon adventures" or "wu dong qian kun" on the comick.fun extension.

### Expected behavior

The extension finds the results the website does.

### Actual behavior

The extension does not find the correct results.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AnataBakka** [comment]
Some screenshots

![Screenshot_2022-12-24-02-11-14-68_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/78822218/209454293-2d5915f4-40b9-4e2d-90eb-b8326d5aa60e.jpg)
![Screenshot_2022-12-24-02-13-25-03_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/78822218/209454294-936287f7-0546-46d6-825b-daf34bb6eea6.jpg)
![Screenshot_2022-12-24-02-10-57-18_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/78822218/209454295-a7dcd545-4a3a-482b-ad73-37a841dccaa1.jpg)
![Screenshot_2022-12-24-02-13-37-01_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/78822218/209454296-7b2d00cb-874f-4ad9-974c-a0c527ee9720.jpg)

**Comment by mobi2002** [comment]
The extension was updated and now uses a different search endpoint. I can find the mentioned manga by searching now. 

If you still face this issue on the latest version of the extension, then please comment about it.
