### ISSUE TITLE
Japscan: "No results found" error after changing user agent

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#14675]
### Source information and language

Japscan 1.3.34

### Steps to reproduce

1. Change the user agent to bypass Cloudflare for an extension, here Sushi-Scan
2. Open the extension Japscan to view a manga
3. The page shows the message "No results found"

### Expected behavior

Open the extension and see the library of mangas

### Actual behavior

The page "No results found"
![Screenshot_20221225-153344](https://user-images.githubusercontent.com/51856879/209474251-03a844db-e0b3-4d44-8210-f04e5dabc42f.png)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

It is impossible to download any chapter in that state and trying to read one only shows the reader for a moment before automatically exiting with a blank error message popping up. However putting the user agent to default seems to solve it, sometimes you have to restart your device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You will have to find a User Agent that works for both sources you use, as you can't set one individually for each source.
