### ISSUE TITLE
Aresmanga URL change

### ISSUE THREAD

**Issue by OSGINSAN** [tachiyomiorg/tachiyomi-extensions#14676]
### Source information and language

Aresmanga (Arabic)

### Source new URL

https://aresmanga.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by mooomo3030** [comment]
I agree with this
