### ISSUE TITLE
Beta Hiper Cool

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#14679]
### Source name

Beta Hiper Cool

### Source link

https://beta.hiper.cool/

### Language

Português pt-br

### Other details

+18 = Sim

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Better to wait until they make the Beta website their current one as I want to avoid package name conflicts.

**Comment by alessandrojean** [comment]
Site seems to be dead.
