### ISSUE TITLE
MangaPark v3: unable to open chapters, Unexpected JSON token at offset 17

### ISSUE THREAD

**Issue by Malaziqua** [tachiyomiorg/tachiyomi-extensions#14689]
### Source information and language

Mangapark v3 1.3.16

### Steps to reproduce

1. I click on the manga/manhwa I want to view
2. I click on the chapter I want to read
3. Unexpected JSON token at offset 17: Expected EOF after parsing, but had = instead at path: $
JSON input: document.domain = 'mangapark.net'

### Expected behavior

I would expect to access any chapter upon clicking on it

### Actual behavior

Instead, it only loads the page view format and then clicks out back to the chapters menu

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "MangaPark v3: unable to open chapters, Unexpected JSON token at offset 17"

**Comment by vetleledaal** [comment]
Fixed by #13046
