### ISSUE TITLE
DONT WORKING SITE

### ISSUE THREAD

**Issue by diefordabi** [tachiyomiorg/tachiyomi-extensions#14690]
### Source information and language

Jiangziatoon (TURKİSH) 

### Steps to reproduce

Jiangziatoon the site gives the problem not connecting while with wifi connection. gives error. but it works with mobile data. pls help me for wifi error 

### Expected behavior

work with both mobile data and wifi 

### Actual behavior

pls help me 

### Tachiyomi version

0.14.2

### Android version

Android

### Other details

![Screenshot_20221227_161936](https://user-images.githubusercontent.com/121502277/209681025-10997107-4841-4525-9796-88f571693e3b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by diefordabi** [comment]
help me

**Comment by arkon** [comment]
If it works on one network, then it's an issue specific to your device/network.

See https://tachiyomi.org/help/guides/troubleshooting/ for a starting point. We don't provide generic IT support.

**Comment by diefordabi** [comment]
> Tek bir ağda çalışıyorsa bu, cihazınıza/ağınıza özgü bir sorundur.
> 
> Başlangıç ​​noktası için [https://tachiyomi.org/help/guides/troubleshoing/ adresine](https://tachiyomi.org/help/guides/troubleshooting/) bakın . Genel BT desteği sağlamıyoruz.

There is no problem in the internet network because other sites are opening ://

**Comment by diefordabi** [comment]
Not a problem with the Internet because other sites are opening ://Huawei telefonumdan gönderildi-------- Orijinal mesaj --------Gönderici: arkon ***@***.***>Tarih: 28 Ara 2022 Çar 01:46Al: tachiyomiorg/tachiyomi-extensions ***@***.***>Cc: diefordabi ***@***.***>, Author ***@***.***>Konu: Re: [tachiyomiorg/tachiyomi-extensions] DONT WORKING SITE (Issue #14690)
If it works on one network, then it's an issue specific to your device/network.
See https://tachiyomi.org/help/guides/troubleshooting/ for a starting point. We don't provide generic IT support.
