### ISSUE TITLE
Bato.to thumbnail not loading

### ISSUE THREAD

**Issue by derinakcay8** [tachiyomiorg/tachiyomi-extensions#14694]
### Source information and language

Bato.to 1.3.30 (English)

### Steps to reproduce

Any thumbnails are  not loading in the bato.to source
![Screenshot_20221228-012821_Tachiyomi](https://user-images.githubusercontent.com/121522858/209728068-8337a2dd-7fcc-4582-b43b-6d1588afcb3c.jpg)
![Screenshot_20221228-012831_Tachiyomi](https://user-images.githubusercontent.com/121522858/209728072-bcf6a8c9-954d-49f6-b4d7-eaaff62bb521.jpg)

### Expected behavior

Thumbnail should load

### Actual behavior

Any Thumbnails not loading

### Tachiyomi version

0.14.2

### Android version

Andrid 11

### Other details

I try every mirror select but everyrime thumbnail not  loading.I try vpn and dns and still thumnnail not loading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
See [FAQ: Why are some cover thumbnails corrupted, white, showing a broken page, or wrong?](https://tachiyomi.org/help/faq/#why-are-some-cover-thumbnails-corrupted-white-showing-a-broken-page-or-wrong)
Related issue tachiyomiorg/tachiyomi#8476
