### ISSUE TITLE
ManhuaZone: Error 400 in app, works in WebView

### ISSUE THREAD

**Issue by Vaturobi** [tachiyomiorg/tachiyomi-extensions#14696]
### Source information and language

ManhuaZone 1.3.26

### Steps to reproduce

1. Open extension
2. Error 400 appears
3. Check web view site is working

### Expected behavior

This should happen list of manga/manhua/manhwa appears and able to download 

### Actual behavior

The website itself seem to be working but the app only shows error 400.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "ManhuaZone: Error 400 in app, works in WebView"
