### ISSUE TITLE
Boylove pages are not loading

### ISSUE THREAD

**Issue by Morse069** [tachiyomiorg/tachiyomi-extensions#14692]
### Source information and language

Boylove 1.3.8 (Chinese)

### Steps to reproduce

Try changing the url.

### Expected behavior

The pages must load when opening a manga

### Actual behavior

None of the pages load the website works perfectly fine

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

I reinstall the extension and i change the url in the settings it just doesnt work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Is this the same issue as in #14663?

**Comment by stevenyomi** [comment]
> Is this the same issue as in #14663?

Yes, this is a duplicate.
