### ISSUE TITLE
Aresmanga URL change 

### ISSUE THREAD

**Issue by iBloox** [tachiyomiorg/tachiyomi-extensions#14708]
### Source information and language

apk/tachiyomi-ar.iimanga-v1.3.24.apk(arabic)

### Source new URL

https://aresmanga.net/

### Other details

NSFW= NO
Id changed 
Code 404

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension is already using this domain.

**Comment by iBloox** [comment]
404 in app
Working in WebView

**Comment by alessandrojean** [comment]
Open a new issue report instead to report this. This isn't the correct form to report this 404 issue.
