### ISSUE TITLE
Mangahub extension not working

### ISSUE THREAD

**Issue by Davidbolt121199** [tachiyomiorg/tachiyomi-extensions#14713]
### Source information and language

Mangahub 1.3.21(English) 

### Steps to reproduce

![Screenshot_2022-12-29-01-04-15-269_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/209864776-e91cfb78-3f15-47eb-9787-c4dc615da922.jpg)

### Expected behavior

It should show latest updated manga 

### Actual behavior

Can't see latest updates of manga or update library

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Davidbolt121199** [comment]
But mangahub extension was added few days ago and was working properly

**Comment by vetleledaal** [comment]
Will be addressed by #14710, which also fixes the issue moderator

**Comment by Davidbolt121199** [comment]
Thank you so much
