### ISSUE TITLE
Unable to download on Mangareader extension

### ISSUE THREAD

**Issue by ramblingmind** [tachiyomiorg/tachiyomi-extensions#14715]
### Source information and language

MangaReader.to 1.3.3

### Steps to reproduce

1. Pick manga "High School DxD"
2. Download Chapter 1
3. Downloading chapter attempts to download

### Expected behavior

The file should download normally.  All other extensions working except this one.

### Actual behavior

Error message "Invalid Location: com.hippo.unifile.TreeDocumentFile@e9afee3" appears 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Doesn't seem to be an issue with the extension.

Can you retry and post the crash logs?

**Comment by AntsyLich** [comment]
Ensure that you have enough space to download chapters
