### ISSUE TITLE
Mangasee (download) works if you use the Source in the app, but not parsed from browser (returns with a weird JSON parse error) and doesn't seem to exist on the library even there the same entry

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi-extensions#14718]
### Source information and language

MangaSee 1.3.34

### Steps to reproduce

1. Start Firefox for android
2. Browse any MangaSee catalog (e.g. searching for "Heroine for Hire")
3. Tap the three-dots (app menu) -> then "Open in App"
![image](https://user-images.githubusercontent.com/31158494/209935726-bdfa43a2-5a28-46d3-8116-b4235811e133.png)
4. This will open the Global Search, then tap on the Mangasee source
![image](https://user-images.githubusercontent.com/31158494/209935998-2126520a-efd3-447f-b4b8-9a87897ce326.png)
5. Try downloading any one of the chapters
6.  Until this error pops out:
![image](https://user-images.githubusercontent.com/31158494/209936492-6b5f73c3-acda-440c-9dd2-0b33a38f29ec.png)
7. Try again by going to back to the Home of the app, then selecting Browse -> Sources -> MangaSee
8. Search with the same title "Heroine for Hire" and tap that entry
![image](https://user-images.githubusercontent.com/31158494/209936814-4660a1fe-b686-4961-bdf5-f154a21107b9.png)
9. Try download anything there, this time, it succeeds without a JSON error unlike the "parsed to browser edition"
![image](https://user-images.githubusercontent.com/31158494/209936968-ccf5efd9-06cc-44ce-83d7-0b85573ddfcf.png)

### Expected behavior

If you send a MangaSee link (shared from a browser) and try to download it, it should download without issue.
(e.g.)
![image](https://user-images.githubusercontent.com/31158494/209937120-88d15b69-3b18-4e5b-b9ed-44fe9d04aaec.png)

### Actual behavior

If you send a MangaSee link (shared from a browser) and try to download it, it fails immediately with the JSON issue. But browsing from the Source on the app, the download succeeds for some reason.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

Note:
1. The version from the "Parsed from browser" doesn't register with the version from the Sources from the app itself
a. From Browse-> Sources -> MangaSee
![image](https://user-images.githubusercontent.com/31158494/209937423-0ca48a23-f41a-4df2-9f96-f75a63e5c2f2.png)
b. Open in App (Firefox)
![image](https://user-images.githubusercontent.com/31158494/209937656-549d46d7-4c21-40b2-b01e-83afa7ba6afa.png)
2. The language is in Filipino but the same issue in English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
probably related to #12958
