### ISSUE TITLE
Error 429, source Olympus Scanlation

### ISSUE THREAD

**Issue by JoanLozano** [tachiyomiorg/tachiyomi-extensions#14738]
### Source information and language

Olympus Scanlation, 1.3.26 Multi

### Steps to reproduce

1. Open olympus in the app
2. Show error

### Expected behavior

Shows the updates manwhas 

### Actual behavior

This error happened before when you want to see the updates, it only showed some and when you see more the error appears, now it shows the error directly

### Tachiyomi version

0.14.2

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Error 429 usually means you're exceeding some rate limit. The current rate limit is 1req per 2sec for pt-BR, and nothing for es.

Please provide the following info, so the issue can be looked into further:
- Version you use (es or pt-BR).
- Error message (if any) in WebView.
