### ISSUE TITLE
MangaHub: some images do not load

### ISSUE THREAD

**Issue by Davidbolt121199** [tachiyomiorg/tachiyomi-extensions#14736]
### Source information and language

Mangahub 1.3.21(English) 

### Steps to reproduce

There is an issue of loading pages in a chapter
![Screenshot_2022-12-31-00-39-31-073_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/210104647-00367395-32b8-44f8-b693-dc8c4a7af20c.jpg)

### Expected behavior

All the pages should have been loaded properly. 

### Actual behavior

Some pages are not been uploaded properly by mangahub source. There is an issue of loading pages. 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "MangaHub: some images do not load"

**Comment by vetleledaal** [comment]
Please provide an example manga and chapter this issue occurs on

**Comment by Davidbolt121199** [comment]
Manga: Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii? 
Chapter no 49
Manga: Kage no Eiyuu no Nichijou-tan
Chapter no 25
Manga: Isekai de Tochi o Katte Noujou o Tsukurou
Chapter no 38

**Comment by Davidbolt121199** [comment]
Recently updated manga 
Manga: A Man With A Thousand Skills Started to Summon a Beast in Different World! 
Chapter no 53 
This time i am attaching screenshot 
![Screenshot_2022-12-31-09-02-11-212_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/210123534-951010b2-314e-4086-a8b3-f88034135e4b.jpg)

**Comment by mobi2002** [comment]
Looking into this, those images are bad and this causes the reader to fail in displaying them.
```
12-31 12:12:48.770 29100 29358 E ImageDecoder: bad adaptive filter value
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: Failed to decode tile
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: java.lang.RuntimeException: Null region bitmap
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.decodeRegion(ImageDecoder.java:18)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:9)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 12:12:48.771 29100 29358 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
```
Not an extension side issue

**Comment by Davidbolt121199** [comment]
So is this problem going to continue.

**Comment by vetleledaal** [comment]
> So is this problem going to continue.

probably.

maybe @Riztard ran into this issue when implementing it. can reproduce the issue, but not sure what the root cause is. maybe Cloudflare related?

**Comment by Davidbolt121199** [comment]
Same problem Chapter pages are not loaded 
Shinjiteita Nakama-tachi ni Dungeon 
Chapter no 69
![Screenshot_2023-01-08-21-35-12-015_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/211206817-80cc4826-88fd-4976-bd95-88347c93787a.jpg)
Please solve this problem

**Comment by Davidbolt121199** [comment]
There are many manga chapter page loding issues coming please solve this problem 🙏🙏🙏🙏

**Comment by Davidbolt121199** [comment]
Now whenever you open a manga and open a chapter it will always says retry. Before this few pages where to be uploaded but now all pages say retry.

**Comment by Davidbolt121199** [comment]
Plzz solve this issue
