### ISSUE TITLE
Asura can't load or download chapters

### ISSUE THREAD

**Issue by setzke** [tachiyomiorg/tachiyomi-extensions#14747]
### Source information and language

Asura Scans - Multi 1.3.38

### Steps to reproduce

1. Go into *any* Asura Scans manga
2. Click any non-downloaded chapter
3. See "The image couldn't be loaded."

Additionally:
1. Go into *any* Asura Scans manga
2. Download a chapter
3. When attempting to download, error is thrown in notifications: "Expected URL scheme 'http' or 'https' but no scheme was found for /cdn-c.."

### Expected behavior

Chapters should load or download normally.

### Actual behavior

"The image couldn't be downloaded." when viewing, or when downloading get "Expected URL scheme 'http' or 'https' but no scheme was found for /cdn-c.."

### Tachiyomi version

0.14.2

### Android version

Android 13

### Other details

Tried clearing caches, reinstalling Asura, changing user agent, togging DoH, and even turning on a VPN.

Verbos crash log, showcasing this happening twice (once with Reaper and once with Asura... not sure which is which)

https://pastebin.com/K7eGY7Kb

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tsunaproxD** [comment]
Same, I suppose the issue is the new website

**Comment by setzke** [comment]
I did various more things, but I believe in the end one thing fixed this -- cleared Tachiyomi app cache from Android settings.

**Comment by hindraxxx** [comment]
correct this is related to the new website i believe @tsunaproxD @setzke, clearing appcache on mine doesn't fix this.

It happened because there is no chapter detected on asura scans as shown here.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/18219222/210168089-e0e38e35-0750-4668-9b4a-e3e67e6d2721.png">


it'll take a while for maintainer to move the extension to the new website if they decide to do so, if not, we need to wait asura to fix the "old" website to show the list

**Comment by Riztard** [comment]
why are we keeping this open if its a site issue

**Comment by setzke** [comment]
> why are we keeping this open if its a site issue

Not sure. My issue wasn't about zero chapters, and I resolved my own problem. I'm closing it again.
