### ISSUE TITLE
ManhuaZone HTTP error 400 issue

### ISSUE THREAD

**Issue by Atlanticboy** [tachiyomiorg/tachiyomi-extensions#14748]
### Source information and language

em.manhuazone

### Steps to reproduce

When opening the extention it shows HTTP error 400. I tried checking the website its opening correctly. But not in tachiyomi extension.

### Expected behavior

It should open like other extension but nothing.

### Actual behavior

It should open like other extension but nothing.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Same as #14696?
