### ISSUE TITLE
New "Asura Scans" site

### ISSUE THREAD

**Issue by Scramuel** [tachiyomiorg/tachiyomi-extensions#14750]
### Source name

Asura Scans

### Source link

https://beta.asurascans.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hindraxxx** [comment]
The new asura site is still under development hence the name beta. If you joined the discord, you'll see they ofteen did a rollback on their deployment. So i would vote against adding the new asura extension for now (maybe until the site itself is stable).

**Comment by Scramuel** [comment]
You gave a good point.
I agree with you.
Thanks for four comment.
