### ISSUE TITLE
Muctau is not working

### ISSUE THREAD

**Issue by ptchie** [tachiyomiorg/tachiyomi-extensions#14761]
### Source information and language

Muctau 1.3.29 (English)

### Steps to reproduce

1. Refresh the manhwa
2. Open the manhwa 
3. Check the mew update
4. Can't load the new chapter
5. Checks their website
6. Website directing me to Bibimanga instead

### Expected behavior

I could have read the new chapters and could have opened their website

### Actual behavior

New chapters didn't load and I can't go to their own website.

### Tachiyomi version

0.14.2

### Android version

EMUI 12.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mireithemage** [comment]
@ptchie Muctau is now Bibimanga. It changed last year. 

The problem that is currently happening is that the link that shows up when you do webview is "https://www.bibimanga.com/" which is wrong. The correct link should be "https://bibimanga.com/". This is why nothing from the Muctau extension works right now. I hope this is an easy fix. FYI I am not a mod.
