### ISSUE TITLE
Inazu Manga: Error 400 Works in WebView

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#14770]
### Source information and language

Inazu Manga (ID) 1.3.26

### Steps to reproduce

Open the extension
Error 400

### Expected behavior

Can show the manga list 

### Actual behavior

Error 400

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Superseded by #17810
