### ISSUE TITLE
ManhuaID: Dead

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi-extensions#14787]
### Source information and language

v1.3.8

### Steps to reproduce

open in webview

### Expected behavior

ded

### Actual behavior

dead

### Tachiyomi version

0.14.2

### Android version

A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Shiin-79** [comment]
ManhuaID change Domain https://manhua.id/

**Comment by Shiin-79** [comment]
This is website manhuaid ? 
https://manhua.id/

**Comment by Riztard** [comment]
> This is website manhuaid ? [manhua.id](https://manhua.id/)

nah, thats a knockoff
