### ISSUE TITLE
Ninemanga only showing 2 pages per chapter

### ISSUE THREAD

**Issue by KINGAWESOME123** [tachiyomiorg/tachiyomi-extensions#14798]
### Source information and language

Ninemanga 1.3.17

### Steps to reproduce

Browse any manga with the source

### Expected behavior

There should be full chapters

### Actual behavior

You will only see 2-3 pages on all chapters, going onto their site shows full chapters, only tachiyomi doesnt

### Tachiyomi version

0.14.2

### Android version

Android 13

### Other details

On the source's site, you can see the full chapter, only tachiyomi shows 2 pages per chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KINGAWESOME123** [comment]
It might possible be a anti tachi system they put up or something

**Comment by jonsomarlo** [comment]
I have reviewed the issue and it seems that the problem could be related to a change in the request, which loads 10 images at once. Additionally, the code snippet 'document.select("div.pic_box img.manga_pic").first()' suggests that only the first image of each group is being obtained, which could explain why a chapter with 20 images only shows 2 images, and the same happens with one with 60 images that only displays 6 images.

Although I am not sure if this is the exact problem, it seems like a reasonable possibility to consider.
