### ISSUE TITLE
Unable to load manhwa and update chapters.

### ISSUE THREAD

**Issue by Radio028** [tachiyomiorg/tachiyomi-extensions#14807]
### Source information and language

6manhua / Qixi manhua 1.3.6

### Steps to reproduce

1. Go to browse at sources tab
2. click 6漫画 "latest" 

### Expected behavior

After click "latest" it should load all the comic titles.
![Screenshot_20230105-205246](https://user-images.githubusercontent.com/88246894/210784456-6d5d9e2b-457b-464c-b42d-7eee8f0379b5.jpg)

### Actual behavior

It did not shows any comics but instead giving error message "unable to resolve host....." 
![Screenshot_20230105-170642](https://user-images.githubusercontent.com/88246894/210784043-f33a415f-5fe9-4a40-bdd8-15a5aa873e3b.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 8.0.0

### Other details

There are no problem open through webview, the website working fine using webview. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rj2537** [comment]
Same but for 1st kiss websites
