### ISSUE TITLE
ManhwaManga.net: "No results found" under popular

### ISSUE THREAD

**Issue by Aesthora** [tachiyomiorg/tachiyomi-extensions#14809]
### Source information and language

ManhwaManga.net 1.3.8 

### Steps to reproduce

![Screenshot_2023-01-06-00-49-57-405_eu kanade tachiyomi](https://user-images.githubusercontent.com/122042367/210835429-9db26b62-237f-478c-8f1d-7e51d49b9df6.jpg)

But the webview works

### Expected behavior

It should shows titles of many manhwa, mostly 18+

### Actual behavior

No results found

### Tachiyomi version

0.14.2

### Android version

MIUI Global 13.0.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
/edit-title "ManhwaManga.net: \"No results found\" under popular"
