### ISSUE TITLE
AllTopManga down

### ISSUE THREAD

**Issue by Blaubeermuffin** [tachiyomiorg/tachiyomi-extensions#14801]
### Source information and language

AllTopManga v.1.3.26

### Steps to reproduce

Simply go to their normal url.

### Expected behavior

Normal website and extension operation.

### Actual behavior

The web page at https://alltopmanga.com/ could not be loaded because:

net::ERR_NAME_NOT_RESOLVED

### Tachiyomi version

App version: 1.8.5 Preview build: 498

### Android version

Android 12

### Other details

The website seems to be down for a week already and since it hasn't been properly reported here or on the Discord, I created this issue. If that's wrong, feel free to close it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The domain doesn't have any A records https://dnschecker.org/#A/alltopmanga.com
Can probably be removed, unless this is planned maintenance
