### ISSUE TITLE
Nitro scans showing null

### ISSUE THREAD

**Issue by NiaeRahs** [tachiyomiorg/tachiyomi-extensions#14818]
### Source information and language

Nitro scans 1.3.27 (English)

### Steps to reproduce

Update library

### Expected behavior

manga update

### Actual behavior

fail to update library
show '! null' in fail update notification

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_20230105-074151_Chrome](https://user-images.githubusercontent.com/122067398/210914229-073ce327-f6e3-49a5-a159-81f6757ec107.jpg)
web view is fine. But in app, only until manga entry seem ok but there are no chapters.And the existing mangas in library can't be read

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
redirect to mangabaz

**Comment by vetleledaal** [comment]
Site is back up, extension works as-is.
