### ISSUE TITLE
Comico (JA), MangaRaw(JA) Not Working 

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [tachiyomiorg/tachiyomi-extensions#14814]
### Source information and language

JA=Japanese

### Steps to reproduce

Search for raw chapters using japanese characters

Get results from Comico (has this =~= looking symbol) and/or MangaRaw (the one with all the porn malware)

Try to open any chapter for viewing

### Expected behavior

Read chapter

### Actual behavior

Comico entries appear sarch results, but clicking on any chapter from them just shows a "not found" error popup.

MangaRaw is the the same, except the error is "bad-base64..."

### Tachiyomi version

TachiyomiSY 1.8.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source, otherwise it makes difficult to track what have been addressed and what not.
