### ISSUE TITLE
Team X shows only 100 chapter in everything 

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#14811]
### Source information and language

Team X 1.2.10 (Arabic) 

### Steps to reproduce

Open team X extension
Select anything
It shows 100 chapters even though there are more than 300 or 400 chapters 

### Expected behavior

I should be able to read all chapters not 100

### Actual behavior

This happens instead
![Screenshot_2023-01-05-20-53-55-598_eu kanade tachiyomi](https://user-images.githubusercontent.com/93197738/210859307-3f20d8c6-c6f5-402f-bc0d-64aa9ddceba2.jpg)
![Screenshot_2023-01-05-20-53-49-209_eu kanade tachiyomi](https://user-images.githubusercontent.com/93197738/210859321-4bb8b779-1ded-4f8d-8312-46e1a2491e9c.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed by #14827
