### ISSUE TITLE
TeamX : Search is not accepted

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#14820]
### Source information and language

TeamX 1.2.10

### Steps to reproduce

1- Enter the source 
2- Search for manga
3- Doesn't search

### Expected behavior

It should search by name 

### Actual behavior

But did not search the source 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/87826849/210947570-517c54dc-7aad-47fc-8567-276bf7dfd83d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Their website does the same thing, so this is just emulating that

**Comment by CarlosEsco** [comment]
Might have found a work around
