### ISSUE TITLE
大佬还有一个Everia.club也打不开了

### ISSUE THREAD

**Issue by 2936747557** [tachiyomiorg/tachiyomi-extensions#14822]
### Source information and language

Everia.club 1.3.3

### Steps to reproduce

1.打开tachiyomi
2.打开Everia.club
3打开失败

### Expected behavior

应该正常显示写真列表

### Actual behavior

扩展打开失败
![Screenshot_20230106_154534](https://user-images.githubusercontent.com/102228434/210955088-4142a1b9-3475-4ee3-b3e1-ab113b34a6bc.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Check your internet connection.
