### ISSUE TITLE
Reaper scans does not update/work since last site update

### ISSUE THREAD

**Issue by vicrodri** [tachiyomiorg/tachiyomi-extensions#14830]
### Source information and language

Reaperscans 1.3.41

### Steps to reproduce

update reaper comics or try to access through the in app browser 

### Expected behavior

comics updating as usual, in app browser work 

### Actual behavior

comics dont update and accessing the site through the in app browser gets stuck in the "check your a human" page forever.

### Tachiyomi version

Stable 0.14.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, wait until they lower their protection or migrate to other sources.

**Comment by XTerminatorGR** [comment]
I fixed it by changing my user agent in Settings --> Advaced to (copy paste it in the field and restart the app):

Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.128 Mobile Safari/537.36

**Comment by XTerminatorGR** [comment]
Also try opening one by one your series in an external browser as it tends to get stuck
