### ISSUE TITLE
Slowly loading

### ISSUE THREAD

**Issue by rianza** [tachiyomiorg/tachiyomi-extensions#14836]
### Source information and language

Neumanga 1.3.1

### Steps to reproduce

If you want to read and load for a long time in other extensions, it's normal
open webview somewhat normal again

### Expected behavior

If you want to read and load for a long time in other extensions, it's normal

### Actual behavior

If you want to read and load for a long time in other extensions, it's normal

![Screenshot_2023-01-07-14-16-05-73_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/116883839/211139171-54a6af78-9188-4636-a3a5-706c1ca2574b.jpg)

### Tachiyomi version

1.6.0 (TachiyomiJ2K)

### Android version

Android 11

### Other details

![Screenshot_2023-01-07-14-16-05-73_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/116883839/211139128-bcab95d8-4c8d-403b-bef1-0a273c07c1ff.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
