### ISSUE TITLE
Baozi Manhua not working

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#14832]
### Source information and language

Zh.baozimh.org 1.3.17 (中文）

### Steps to reproduce

Unable to browse, there is human autentication

### Expected behavior

Pls fix

### Actual behavior

Pls fix

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by Bishopop6** [comment]
Hi, i have tried all thr solution but still does not work for me.

**Comment by stevenyomi** [comment]
> Hi, i have tried all thr solution but still does not work for me.

Try changing the user agent string to another desktop browser's.

If it still doesn't work, there's nothing we can do. I have no problems with it here.
