### ISSUE TITLE
Gabut Scans: Chain validation failed

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#14834]
### Source information and language

Gabut Scans 1.3.23

### Steps to reproduce

Open source
Chain validation failed 

Open via WebView
Show blank page

### Expected behavior

Can show manga list 

### Actual behavior

Error chain validation failed or blank page in WebView 

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

![Screenshot_2023-01-07-09-14-13-09_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/211127130-c736ac4f-d3a8-4351-8466-d01905936fae.jpg)
![Screenshot_2023-01-07-09-14-16-67_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/211127134-1d0bfb23-ebd5-4f26-908c-68ff040f8506.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
redirected to existing ext `duniakomik.id`
