### ISSUE TITLE
Error 429 Reaper Scans TachiyomiSy

### ISSUE THREAD

**Issue by Jalt3r** [tachiyomiorg/tachiyomi-extensions#14848]
### Source information and language

Reaper Scans 1.3.41

### Steps to reproduce

1. Pull down manual refresh on series or automatic updates for source in library
2. Updates library with latest chapter
3. Notification with error 429

### Expected behavior

Updates to the newest chapter if there is one

### Actual behavior

Does not update and error 429

### Tachiyomi version

1.8.5

### Android version

Android 13

### Other details

It says error 429 and after waiting for a couple days to go back and check I have the same issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Retashe** [comment]
the same is happening to me too, but it shows the chapters just can't download or read

**Comment by Jalt3r** [comment]
I'm going to go ahead and close this. Seems it's due to them migrating hosts
