### ISSUE TITLE
Leviatan Scans blocking Tachiyomi - No pages found

### ISSUE THREAD

**Issue by Readerenjoyer** [tachiyomiorg/tachiyomi-extensions#14841]
### Source information and language

Leviatan Scans 1.3.40

### Steps to reproduce

1. Open any webtoon/novel/manhwa that on leviatan scans. 
2. Open any chapters/pages.
3. Loading logo.
4. Get kicked to main webtoon/novel/manhwa directory and shows 'No pages found'.
5. Open in webview of said webtoon/novel/manhwa
6. Open any chapters/pages on webview.
7. Shows loading logo endlessly until tomorrow
8. Done

### Expected behavior

Clicked and showed loading logo. 
Opened the pages to read.

### Actual behavior

Click and shows loading logo.
Kick backed to main webtoon/novel/manhwa directory and shows 'No pages found'
![Screenshot_20230108_032059_eu kanade tachiyomi](https://user-images.githubusercontent.com/122176658/211167117-495e6c1b-e0f6-45fb-b81d-d5dfc48abfd2.jpg)
![Screenshot_20230108_031933_eu kanade tachiyomi](https://user-images.githubusercontent.com/122176658/211167119-ad9b508c-f105-45a1-a297-f4a8b3f246d3.jpg)

### Tachiyomi version

0.14.3

### Android version

EMUI 12.0.0

### Other details

Im using Huawei P30 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Readerenjoyer** [comment]
Tested on normal website on chrome phone, loaded normally, only on the app does not load and the app webview just show loading logo infinitely spinning. 
![Screenshot_20230108_033638_com android chrome](https://user-images.githubusercontent.com/122176658/211167640-4b59cde1-519f-4929-9bc5-6270ba730b60.jpg)

**Comment by Readerenjoyer** [comment]
Asked few person on android, same answer not my emui probs.

**Comment by setzke** [comment]
I experience this as well with Galaxy S22 Ultra. I even installed and switched to WebView Dev 110.0.5481.23 instead of standard Webview 108.0.5359.128 but no change. Site loads but pages/images in chapter do not load in Tachiyomi or in Tachiyomi's webview. Outside of Tachiyomi, site and images load normally.

**Comment by CrepeTF** [comment]
/edit-title "Leviatan Scans blocking Tachiyomi - No pages found"

**Comment by CrepeTF** [comment]
![Screenshot_20230109-055528_Aliucord.png](https://user-images.githubusercontent.com/70870719/211248329-5a877ccc-383c-4c20-b176-e2eff9225570.png)

**Comment by Readerenjoyer** [comment]
Aight sadge day
