### ISSUE TITLE
Reintroduce mangas.in

### ISSUE THREAD

**Issue by Nekrant02** [tachiyomiorg/tachiyomi-extensions#14846]
### Source name

Mangas.pw

### Source link

https://mangas.in

### Language

Español

### Other details

Formerly it was in the application and it was deleted from it, currently I know of another application that introduces this extension as a manga reader (animews) and I wanted to apply again for the introduction of this application as an available extension
Look for the reason why the extension was deleted but it is not found in the list of deleted extensions

It would be useful to reintroduce this extension because it updates the chapters faster and has a larger repository of manwhas than other options that are currently available.

Thanks in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
It was removed because #9489 but it wasn't added to the list somehow.
