### ISSUE TITLE
 paginas nao carregando 

### ISSUE THREAD

**Issue by Gui02789** [tachiyomiorg/tachiyomi-extensions#14856]
### Source information and language

Reaper Scan 1.3.41 português (Brasil)

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.14.3

### Android version

Android 9

### Other details

Pages are no longer loading 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all the fields from the issue form correctly and do provide some chapters as examples where this happens.
