### ISSUE TITLE
Chapters that show up on Mangadex's website aren't on the app

### ISSUE THREAD

**Issue by Amilton78** [tachiyomiorg/tachiyomi-extensions#14853]
### Source information and language

Mangadex 1.3.176 (Brazilian Portuguese)

### Steps to reproduce

1.Search chainsaw man on Mangadex
2.Chose the regular, not the coloured version, translated to Brazilian Portuguese
3.See the latest chapter on the app is the 97th

### Expected behavior

The latest chapter, as of January the 8th of 2022, is the 116th on Mangadex's website

### Actual behavior

The latest chapter on the app is the 97th

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

Example image https://imgur.com/a/aaTcXan

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
These chapters aren't hosted on MangaDex, they're external. Try reading on the MangaDex website and you will be redirected to another website instead. The extension is working as expected by not showing these.
