### ISSUE TITLE
Cloudflare looping issue

### ISSUE THREAD

**Issue by rraindayy** [tachiyomiorg/tachiyomi-extensions#14851]
### Source information and language

Myreadingmanga 1.3.46

### Steps to reproduce

I try to access Myreadingmanga extension but it keeps looponing the cloudflare security verify check. I have tried:

1. Clearing cookies
2.  Reinstalling extension
3. Opening on web browser (it opens on external browser) but the cloudflare in app browser still loops

### Expected behavior

After going through the cloudflare verification, it should load up the extension/site. 

### Actual behavior

Cloudflare verification keeps looping even after how many inputs 

### Tachiyomi version

Myreadingmanga 1.3.46

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, wait until they lower their protection or migrate to other sources.
