### ISSUE TITLE
1st Kiss: HTTP error 429

### ISSUE THREAD

**Issue by ahkazak23** [tachiyomiorg/tachiyomi-extensions#14850]
### Source information and language

1st Kiss v1.3.34(English)

### Steps to reproduce

1.trying to update my library
But source not workink htp error 429

### Expected behavior

Should successfully update 

### Actual behavior

Not updating. Giving error

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

Plz help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ReachedTheApex** [comment]
+1 happening to me too
