### ISSUE TITLE
MangaBTT

### ISSUE THREAD

**Issue by CaoCuong12** [tachiyomiorg/tachiyomi-extensions#14864]
### Source name

MangaBTT

### Source link

https://mangabtt.com/

### Language

English

### Other details

Need To Add This Website To Tachiyomi App
This website has only been active for a few months and has been recommended by many people on facebook groups (manga/manhua/manhwa) with a large number of members.
should add website to Tachiyomi app

Some features of the website:
User-friendly interface, easy to read manga and full features of a manga website
fast loading speed
very few ads and no malicious ads/Adult
No manga Adult 18+
**Update manga very quickly, there are some manga that are not available on other websites and some manga by translation website update chapters much faster than other websites.
for example: Reality Quest , +99 Wooden Stick, Mercenary Enrollment, Quest Supremacy...**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CaoCuong12** [comment]
> .Request to review the issue of adding a new source (MangaBTT)





> Sự cố này đã bị đóng vì nó trùng lặp với #11795 . Điều đó có nghĩa là trước đó đã có người khác yêu cầu thêm trang web này dưới dạng tiện ích mở rộng.
> 
> _Đây là một hành động tự động. Nếu bạn cho rằng đây là một sự nhầm lẫn, vui lòng bình luận về nó để vấn đề có thể được mở lại nếu cần._

**Comment by stevenyomi** [comment]
Sources are added when someone is willing to work on it. There is no ETA.

**Comment by CaoCuong12** [comment]
> Sources are added when someone is willing to work on it. There is no ETA.

can i pay to add mangabtt source to Tachiyomi app
can anyone help me?
