### ISSUE TITLE
1st Kiss Error 429

### ISSUE THREAD

**Issue by 4cactusjackburgers** [tachiyomiorg/tachiyomi-extensions#14872]
### Source information and language

1stKiss Manga 1.3.34. English 

### Steps to reproduce

Update library
Only source that gives error 429

### Expected behavior

Update library normally 

### Actual behavior

Gives error 429 and possible ip ban

### Tachiyomi version

0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
#14850
