### ISSUE TITLE
HTTP error 429 or Too Many Requests Problem

### ISSUE THREAD

**Issue by Smallredpanda** [tachiyomiorg/tachiyomi-extensions#14873]
### Source information and language

1st Kiss English

### Steps to reproduce

Refresh/update library

### Expected behavior

New chapters would populate in the update tab and a notification of the chapters

### Actual behavior

Notification that a number of updates failed and maybe 1 or 2 items in library are updated

### Tachiyomi version

0.14.3

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
#14850
