### ISSUE TITLE
Hiperdex (en): cloudfire unlocked on webview and yet it says "impossible to bypass"

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#14897]
### Source information and language

Hiperdex 1.3.32

### Steps to reproduce

1. Go to hiperdex, impossible to bypass
2. open webview, wait it unlocks
3. go back to tachi extension and try to load the maim screen

### Expected behavior

Bypass CloudFlare 

### Actual behavior

Cloudfire not bypassed despite me unlocking it on webview

### Tachiyomi version

tachiSY r498 (it's right before the release of 0.14.3)

### Android version

Android 8 miui 8

### Other details

https://user-images.githubusercontent.com/75091899/211812452-d3edb138-2a60-44ba-b7b1-65e13b9ae222.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This source is known for having a higher Cloudflare protection for a good time already. Try the Cloudflare Troubleshooting guide entirely, including the "Changing your user agent" section.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, wait until they lower their protection or migrate to other sources, there's really nothing we can do about it.

**Comment by alessandrojean** [comment]
The WebView is almost a complete browser, so Cloudflare can run and do additional checks and they are probably passing, which let you enter the website. The extension however has a more limited client that's not technically a browser so it lacks some stuff Cloudflare uses to check, hence the failing.

**Comment by Palloxin** [comment]
Is an improvement of it being developed? just curious, i will not inquire any further

**Comment by alessandrojean** [comment]
Not for now and I don't think it's technically doable at the moment.
