### ISSUE TITLE
1st kiss: HTTP error 429

### ISSUE THREAD

**Issue by Cielewej** [tachiyomiorg/tachiyomi-extensions#14892]
### Source information and language

1st kiss (EN)

### Steps to reproduce

I cannot update the new chapters of manga in the 1st kiss. Its always failing.

### Expected behavior

If i click tha global update it should all update the mangas in any extension.

### Actual behavior

Instead the 1st kiss(EN) extension always dailing. And always saying its an error of 429.

### Tachiyomi version

Tachiyomi version 0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
What extension version are you using? You did not provided this information requested in the form.

**Comment by Cielewej** [comment]
1st kiss [EN]
This is the extension that i am using. Sorry for the late reply

**Comment by scb261** [comment]
#17897
