### ISSUE TITLE
MangaScantrad (source FR) cloudflare problem

### ISSUE THREAD

**Issue by Valtrana** [tachiyomiorg/tachiyomi-extensions#14901]
### Source information and language

Manga-Scrantrad 1.3.29

### Steps to reproduce

1. Refresh source and chapters

### Expected behavior

New chapters should appear

### Actual behavior

Source can no longer be updated due to cloudflare****
![Screenshot_20230110_094634_Tachiyomi](https://user-images.githubusercontent.com/102482690/211898070-c648cf6a-78b4-4fc4-ba64-8327c0e58a29.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 13

### Other details

I have already tried the solutions proposed on your forum but nothing works. I'm not the only one having this problem. Would it be possible to fix the problem? It's already the third FR source that has the same problem. (MangaScrantrad, JapanRead and Manga-Origin) They are in the best sources FR. Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Cloudflare Troubleshooting guide and follow it entirely, including the "Changing your user agent" section on the link below.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it still doesn't work, wait until they lower their protection or migrate to other sources.
