### ISSUE TITLE
Hiperdex need bypass Cloudflare

### ISSUE THREAD

**Issue by afkafa** [tachiyomiorg/tachiyomi-extensions#14905]
### Source information and language

Hiperdex 1.3.32

### Steps to reproduce

1. Open Hiperdex source
2. Get infinite loading
3. In webview, you can open it normally after bypass Cloudflare

### Expected behavior

Should show list of mangas

### Actual behavior

Get 503 error

### Tachiyomi version

0.14.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Cloudflare Troubleshooting guide and follow it entirely, including the "Changing your user agent" section on the link below.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it still doesn't work, wait until they lower their protection or migrate to other sources.
