### ISSUE TITLE
Coomer.party extension not updating with latest images 

### ISSUE THREAD

**Issue by Darkzeroblade** [tachiyomiorg/tachiyomi-extensions#14915]
### Source information and language

Coomer 1.3.5

### Steps to reproduce

1. Install coomer extension
2. Look up user alfonsina297
3. Source will only have 3 chapters, the latest being 6/5/2022 (thumbnail preview also broken)
4. Navigate to https://coomer.party/onlyfans/user/alfonsina297 you will see post from 10/23

### Expected behavior

Coomer should be updating and pulling these images

### Actual behavior

Coomer extension appears to have stopped updating the gallery since 6/5/2022

### Tachiyomi version

0.14.3

### Android version

Android 11

### Other details

This happens in all branches of tachiyomi. The main one as well any different flavors such as SY or J2K

Unsure if the extension is unusable now or if there is an issue pulling the data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
That post doesn't have any image so it will intentionally not be shown in the extension. The extension only shows posts that does have images inside it, so it's working as expected.
