### ISSUE TITLE
SekaiKomik.live: Changed their domain

### ISSUE THREAD

**Issue by CanULetMeIn** [tachiyomiorg/tachiyomi-extensions#14910]
### Source name

Sekaikomik

### Source link

https://www.sekaikomik.pro/

### Language

Bahasa indonesia

### Other details

18+/NSFW = YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
An extension of this website already exists with the name of **Sekaikomik**, under the **Indonesian** section.

**Comment by vetleledaal** [comment]
For some reason there's 2 extensions with the same name/id
```kt
SingleLang("Sekaikomik", "https://www.sekaikomik.live", "id", isNsfw = true, overrideVersionCode = 9),
SingleLang("Sekaikomik", "https://www.sekaikomik.site", "id", isNsfw = true, overrideVersionCode = 8),
```

https://www.sekaikomik.site is dead, while https://www.sekaikomik.live redirects to https://www.sekaikomik.pro
