### ISSUE TITLE
Existing mangas now have 0 chapters 

### ISSUE THREAD

**Issue by HannahBagtasos** [tachiyomiorg/tachiyomi-extensions#14916]
### Source information and language

1stKiss 1.3.35 , 1st Kiss Manga.love 1.3.29 , 1st Kiss Manhua 1.3.31

### Steps to reproduce

1. Update manga, sees no updates, found activity unusual 
2. Click into a recent manga
3. Manga displays 0 chapters 
4. After updating Tachiyomi app today, some mangas haven't been updating. All chapters are gone for majority manga from 1stKiss and variations of 1stKiss, as if they never existed
Some were mangas I read only 2 days ago, now saying 0 chapters.

### Expected behavior

Displaying how many chapters in the manga.
Eg Father, I Don’t Want to Get Married!, Chapters 1-96

### Actual behavior

Displaying 0 chapters , eg Father, I Don’t Want to Get Married! Chapters 0

### Tachiyomi version

App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z) 

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
1st Kiss lost all their chapters due to a hack. If you would like to prevent orphaned downloads or prevent losing read, do not update entries from 1st Kiss until they've gotten their chapters back.
