### ISSUE TITLE
Mangakatana chain validation failed

### ISSUE THREAD

**Issue by Viva1HA** [tachiyomiorg/tachiyomi-extensions#14921]
### Source information and language

Mangakatana version 1.3.9 (english)

### Steps to reproduce

Open source or manga chapter
Get message "chain validation failed"

### Expected behavior

Reading mangas

### Actual behavior

Chain validation failed

### Tachiyomi version

0.14.3

### Android version

9

### Other details

![Screenshot_20230113-022531](https://user-images.githubusercontent.com/95601264/212261739-9aaa1c87-0c14-4a74-90e6-913cb708651f.png)
![Screenshot_20230113-022515](https://user-images.githubusercontent.com/95601264/212261746-1e0761bf-6fc0-4da9-bf1d-acde05442f49.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you will have to wait until they renew their certificate.
