### ISSUE TITLE
Mangago: Manga covers do not load when not initialized

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi-extensions#14920]
### Source information and language

Mangago 1.3.8

### Steps to reproduce

1. Open the extension (Popular/Latest/Search query)

### Expected behavior

Covers should load

### Actual behavior

Covers do not load when manga is not initialized

### Tachiyomi version

0.14.3

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
fixed in [05154fc](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/05154fc045ae9323d98f7a5b0e31be2087e0fd69), forgot to link this issue oops
