### ISSUE TITLE
Azora: Changed their domain

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#14925]
### Source information and language

Azora العربية 1.3.31

### Source new URL

https://azoranov.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Asmamanhwa** [comment]
When azora will be fixed?

**Comment by alessandrojean** [comment]
When someone have time and wants to work on it. There's no ETA.
