### ISSUE TITLE
MangaSwat: Changed their domain

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#14926]
### Source information and language

Mangaswat 1.3.28 arabic

### Source new URL

https://swatmanga.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Source was falsely accused of stealing other scans and is going to be removed again

**Comment by nasyaldnya** [comment]
> Source was falsely accused of stealing other scans and is going to be removed again


Is it the same issue here!? #14456   I see no evidence for stealing 

We need more clarification

**Comment by BLACKxSUN** [comment]
They are steal some chapters They were late in translating it but after some months they remove The logo (its so easy for them) of the other team that translated the chapters
Look at this photoes , the translat is same with out any work

![٢٠٢٣٠١١٥_٠٣٠٩٢٦](https://user-images.githubusercontent.com/93000786/212502597-428cf232-f67e-4738-a690-d2aa17fa4145.jpg)
This is the orginal website that translat the chapters
https://aresmanga.net/martial-arts-reigns-chapter-435/

![٢٠٢٣٠١١٥_٠٣٠٩٠٦](https://user-images.githubusercontent.com/93000786/212502649-54d32f7a-87be-4890-8e7b-3bd8a6b8a954.jpg)
And this is swarmanga that steal the chapters
https://swatmanga.net/1367722/m/martial-arts-reigns-435/

![٢٠٢٣٠١١٥_٠٣١٧٢٠](https://user-images.githubusercontent.com/93000786/212502843-ea81fb79-1525-460e-b399-8270cbf8f279.jpg)
And this photo from there discord, they say if you take the first a few chapters we translat so we will take your's too (they letf the work on this manhwa for like 4months without any chapter and when any team try complete it they say they are steal *lol* )
This there link of discord if you want check go for "اعلانات" channl on date 2022/10/08
On the end i say the steal some chapters from some work no all chapter but this is still steal!

**Comment by BLACKxSUN** [comment]
> Source was falsely accused of stealing other scans and is going to be removed again

Hi bro can you check the comment above?

**Comment by CarlosEsco** [comment]
> > Source was falsely accused of stealing other scans and is going to be removed again
> 
> Hi bro can you check the comment above?

We are looking into, not going to just add as soon as someone posts something.

**Comment by nasyaldnya** [comment]
> > > Source was falsely accused of stealing other scans and is going to be removed again
> > 
> > 
> > Hi bro can you check the comment above?
> 
> We are looking into, not going to just add as soon as someone posts something.

I expect what is happening is that the MangaSwat team was translating a lot of work and They were late in translating some chapters, so one of the Teams took the previous chapters from the MangaSwat and started translating from where the MangaSwat team finished

After a while, the MangaSwat team took the translation from the other team and started working on the translation again
