### ISSUE TITLE
NHentai "In Library" filter

### ISSUE THREAD

**Issue by Lukyzzz** [tachiyomiorg/tachiyomi-extensions#14929]
### Source name and language

NHentai (English / Multi )

### Describe your suggested feature

A filter that hide doujinshi that's already on your library and vice versa, that way it would be easier to find doujinshi that you didn't hear of or forgot to add to the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension doesn't have access to what you have in your library, so it's not possible to filter that in the extension side. IIRC this was also requested on the app and was denied before, but need to double-check.

**Comment by Lukyzzz** [comment]
Oh, sorry, thought it could be done since it shows "in library" when I use the extension

**Comment by alessandrojean** [comment]
That "In Library" badge is shown by the app, the extension doesn't set that or anything similar.

**Comment by Lukyzzz** [comment]
Yeah, just checked, it was suggested 3y ago, a pity, but I guess it's probably not gonna happen
