### ISSUE TITLE
Updated series name in Komga server not showing in Tachiyomi

### ISSUE THREAD

**Issue by unfinishedh** [tachiyomiorg/tachiyomi-extensions#14922]
### Source information and language

Komga 1.3.43

### Steps to reproduce

I am facing an issue which I am not sure if it lies on the server or the extension, so apologies if I posted on the wrong place.

When I add a new series on my Komga server, they use to appear with the following name convention "series (release year)", which I normally edit to remove the year and just keep the series name.

I realized though that, after changing it, some titles keep showing the old names when I check the series on the server within the app via Browse > Sources > Komga and never get updated. If I click on the webview, they appear correctly though in the web browser. 

The issue seems to happen randomly. Some of the series show the new updated name, but those that don't, never get the new one. My guess is that the first time a new series is detected in the server when accessed through the app, the name is cached and doesn't get refreshed? So depending on whether they are shown the first time, before or after editing, they appear with one or the other.

### Expected behavior

After editing the name of a series in the Komga server, get the updated name in Tachiyomi as well.

### Actual behavior

The old name "series (release year)" is displayed instead.

### Tachiyomi version

Tachiyomi Preview r5405 (30e030bb8)

### Android version

Android 10

### Other details

As mention at the beginning, I am not sure if the issue lies on the extension or the server. Feel free to request any other details if needed. Here is the info of the server as well, just in case it is relevant:

OS: Rasperry Pi OS 64 bit
Version: *.jar, v0.158.0-master

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
they are cached most likely, remove them from your library if they are, and clear your db.
