### ISSUE TITLE
1st kiss not working properly 

### ISSUE THREAD

**Issue by 4cactusjackburgers** [tachiyomiorg/tachiyomi-extensions#14923]
### Source information and language

1stKiss Manga 1.3.35. English 

### Steps to reproduce

Trying to read/Update library
All of the titles from 1st kiss give error no chapters found 

### Expected behavior

Open, read, download and update chapters normally 

### Actual behavior

Gives error no chapters when there are chapters 

### Tachiyomi version

0.14.3

### Android version

Android 11

### Other details

Some 1st kiss titles work but not all of them

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
From the discord server:
> 1st Kiss lost all their chapters due to a hack. If you would like to prevent orphaned downloads or prevent losing read chapter progress, do not update entries from 1st Kiss until they've gotten their chapters back.
