### ISSUE TITLE
Baozi manhua outdated url (武炼巅峰)

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#14939]
### Source information and language

Zh.baozimh.org 1.3.18 (中文）

### Steps to reproduce

The manhua url is already changed and its not updating in  tachiyomi.

https://cn.baozimh.com/comic/wuliandianfeng-pikapi. (Old version no more update)

https://cn.baozimh.com/comic/wuliandianfeng-pikapi_7ajf1b
(New version, with new update)

### Expected behavior

Please change if its possible.

### Actual behavior

.

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Thanks for reporting, but there's currently no way to update it automatically as the old page doesn't have any sort of link to the new one. It doesn't even show up in the search result.

You can find the new one in the popular listing, or use the intent filter by either
- clicking the link https://cn.baozimh.com/comic/wuliandianfeng-pikapi_7ajf1b in a browser, or
- searching `id:wuliandianfeng-pikapi_7ajf1b` in the source.

**Comment by stevenyomi** [comment]
Closing as the old URL now redirects to the new one.
