### ISSUE TITLE
大佬，禁漫天堂更新后打不开了

### ISSUE THREAD

**Issue by 2936747557** [tachiyomiorg/tachiyomi-extensions#14937]
### Source information and language

jinman tiantang 1.3.33

### Steps to reproduce

1.打开tachiyomi
2.点击禁漫天堂
3.打开失败
![Screenshot_2023-01-14-14-27-06-282_eu kanade tachiyomi](https://user-images.githubusercontent.com/102228434/212459201-878640c5-089b-4768-a282-c9821368bd19.jpg)
![Screenshot_2023-01-14-14-27-13-992_eu kanade tachiyomi](https://user-images.githubusercontent.com/102228434/212459274-8fb2feb4-5317-4430-ac85-5c4853a462dc.jpg)

### Expected behavior

应该正常打开禁漫天堂并显示漫画

### Actual behavior

打开失败

### Tachiyomi version

0.14.3

### Android version

安卓13

### Other details

已经试了，插件中自带的所有线路没有效果，我又试着开启代理后还是不行

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Check your user agent string and network connection.

**Comment by 2936747557** [comment]
多谢大佬，已经恢复访问了，😂我什么都没动，估计是网络波动，这几天翻墙越来越不稳定了
