### ISSUE TITLE
Unable to load chapters for any 1st kiss websites

### ISSUE THREAD

**Issue by Rj2537** [tachiyomiorg/tachiyomi-extensions#14936]
### Source information and language

1st kiss v1.3.35, 1st kiss manga.love v1.3.29,1st kiss mangia v1.3.31

### Steps to reproduce

1. Go to click on browse
2. Click on any of the following extensions: 1st kiss, 1st kisa manga.love,1st kiss manhua
3.click on any title

### Expected behavior

![Screenshot_2023-01-14-11-44-32-30_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/114636049/212458720-9a4e3bc6-e921-4993-a44c-8ddcae971264.jpg)
Should load like this^

### Actual behavior

Loads like this
![Screenshot_2023-01-14-11-45-40-49_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/114636049/212458757-6973ce4c-1066-4ba0-b151-2eebfb019d0b.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 12 (Color OS 12.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
They have trouble, so they delete the chapter and going to reupload it. They estimate it in a week
