### ISSUE TITLE
Cerise Scans: No pages found

### ISSUE THREAD

**Issue by Deivil5** [tachiyomiorg/tachiyomi-extensions#14963]
### Source information and language

Cerise scans BR 1.3.30

### Steps to reproduce

![Screenshot_2023-01-15-15-17-42-026_eu kanade tachiyomi](https://user-images.githubusercontent.com/106024327/212559475-bf75643f-9b87-4f5a-a425-b1680fe39b5a.jpg)

### Expected behavior

Be able to read and download the manga

### Actual behavior

It is not possible to download or read the mangas.

### Tachiyomi version

0.14.3

### Android version

10

### Other details

When I try to read it, it says there are no pages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Erick17x** [comment]
Estou com o mesmo problema. Todos os mangas nessa fonte não estão conseguindo baixar imagens.
