### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by Ariettty** [tachiyomiorg/tachiyomi-extensions#14966]
### Source name and language

Mangaowl

### Describe your suggested feature

I would like to request extension Mangaowl

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
MangaOwl shut down months ago. It no longer exists.
