### ISSUE TITLE
Tritinia Scan URL changed yet again

### ISSUE THREAD

**Issue by Dremor** [tachiyomiorg/tachiyomi-extensions#14973]
### Source information and language

TritiniaScan 1.3.30 (English)

### Steps to reproduce

1.  Install the latest extension
2. Try to visualise the manga list

### Expected behavior

Mangas are listed

### Actual behavior

HTTP error 405

### Tachiyomi version

0.14.3

### Android version

Android 13

### Other details

Related to !14605 and !14854

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dremor** [comment]
The website seem to be back to the .org url reverted by !14854

**Comment by CedMIX-Productions** [comment]
I was going to create a bug report, same error 405 (url redirect [open webview]), but returns a 404 (not found when updating one of the entries)
![image](https://user-images.githubusercontent.com/31158494/213859097-7fc69cc2-8e8a-443d-b81c-8bc622a0fc7b.png)
Note: from com to org domain change
