### ISSUE TITLE
MangaBuddy - pages can't load

### ISSUE THREAD

**Issue by Sibgeir** [tachiyomiorg/tachiyomi-extensions#14970]
### Source information and language

MangaBuddy 1.3.12

### Steps to reproduce

Step 1 : Go to any manga/manwha in the MangaBuddy Catalog
Step 2 : open any chapter

### Expected behavior

The chapter should load one page at a time

### Actual behavior

Failed to load, retry button appear on each page.

### Tachiyomi version

App version: 1.6.0 

### Android version

Android 12

### Other details

Works fine through webview.
Fully loaded or partially loaded for some in source website

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sibgeir** [comment]
Wrong alternate version github
Ma bad

**Comment by GaniyuWi** [comment]
I also have this same problem
