### ISSUE TITLE
Add this extension please 

### ISSUE THREAD

**Issue by Sultanabdo1** [tachiyomiorg/tachiyomi-extensions#14971]
### Source name

Azoranov

### Source link

https://azoranov.com/

### Language

Arabic 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Already exists.

**Comment by Sultanabdo1** [comment]
They changed their domain and don't 
 open
![Screenshot_2023-01-16-14-20-17-409_eu kanade tachiyomi](https://user-images.githubusercontent.com/114279430/212676985-d6446af4-7a33-4d34-befd-3b3b62acf758.jpg)

**Comment by alessandrojean** [comment]
Already reported in #14925
