### ISSUE TITLE
Azora

### ISSUE THREAD

**Issue by 5OSA** [tachiyomiorg/tachiyomi-extensions#14976]
### Source information and language

Azora 1.3.31 arabic 

### Source new URL

https://azoranov.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Duplicate of #14925
