### ISSUE TITLE
Online chapters working but downloaded chapters doesn't work

### ISSUE THREAD

**Issue by TogeHekigiri** [tachiyomiorg/tachiyomi-extensions#14997]
### Source information and language

All Extensions

### Steps to reproduce

Example:
1. reading an online chapter and downloading it
2. After downloading chapter, images won't load

### Expected behavior

Downloaded chapters images should work

### Actual behavior

Downloaded chapters not working even though it's perfectly fine when it's not downloaded

### Tachiyomi version

0.14.3

### Android version

Android 6.0

### Other details

![Screenshot_2023-01-17-19-06-39](https://user-images.githubusercontent.com/122873212/212883572-83877486-88d9-439f-9072-a85ccb12bb63.png)
![Screenshot_2023-01-17-19-06-55](https://user-images.githubusercontent.com/122873212/212883598-bf47a067-007a-4c1e-aa52-33bddc0c1133.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TogeHekigiri** [comment]
I have been restarting the app for the past hour but it still doesn't work...

**Comment by stevenyomi** [comment]
Check storage/SD card sections of https://tachiyomi.org/help/guides/troubleshooting/. This is an app issue, and I suggest you get support from the #support channel on Discord.
