### ISSUE TITLE
Coffe Manga extension 400 Bad Request Issue

### ISSUE THREAD

**Issue by chocola-addams** [tachiyomiorg/tachiyomi-extensions#14992]
### Source information and language

Coffe Manga 1.3.27 (English)

### Steps to reproduce

1. Go to Browse, tab Extensions
2. Install Coffee Manga extension
3. Go to tab Sources
4. Go to Coffe Manga to see the mangas 

### Expected behavior

Insted of the error message, the mangas should be displayed

### Actual behavior

The mangas are not  displayed, insted is an error message Bad request error 400 (if I go to the webview it works fine)
![image](https://user-images.githubusercontent.com/61542955/212844937-66103940-0e13-426a-8f31-ad10add94171.png)

### Tachiyomi version

0.14.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Yaoimkay** [comment]
Am having the same issue on manga kio and mangastic
