### ISSUE TITLE
Can you add this extension 

### ISSUE THREAD

**Issue by Sultanabdo1** [tachiyomiorg/tachiyomi-extensions#14999]
### Source name

Swatmanga

### Source link

https://swatmanga.net/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> This will not be added back as the scanlator team has requested it to be removed. Read Missing sources and known issues #3475 for more information.
