### ISSUE TITLE
Hiperdex domain changed

### ISSUE THREAD

**Issue by LegacyPhil** [tachiyomiorg/tachiyomi-extensions#14995]
### Source information and language

Hiperdex english

### Source new URL

1sthiperdex.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by MaudiH** [comment]
I just indeed opened a ticket , luckily I have found this opened already 

![eivdencehiperdex](https://user-images.githubusercontent.com/12390457/212973968-043f99b9-6efd-4069-8074-dc736e3a0dc2.png)

![hiperdexnewurl](https://user-images.githubusercontent.com/12390457/212973973-1bf700a8-74a4-4c09-8abc-ffc0835145c8.png)
