### ISSUE TITLE
Hiperdex.com changed its website to  1sthiperdex.com/

### ISSUE THREAD

**Issue by MaudiH** [tachiyomiorg/tachiyomi-extensions#15001]
### Source information and language

Hiperdex 1.3.32

### Source new URL

https://1sthiperdex.com/

### Other details

since yesterday or the day before as I update my hiperdex manhwas it displays HTTP error 400 , upon checking in the webview , I noticed the url has been redirected to https://1sthiperdex.com/
![eivdencehiperdex](https://user-images.githubusercontent.com/12390457/212972911-6c3c5bba-b66f-4112-b629-5bfebc6fc67b.png)
please check the other pic with the new url 
![hiperdexnewurl](https://user-images.githubusercontent.com/12390457/212973397-688de8a7-cabd-483e-8b68-5e6068f40196.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Duplicate of #14995
