### ISSUE TITLE
Bato.to: show a toast to restart the app when changing mirror

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi-extensions#15006]
### Source name and language

Bato.to

### Describe your suggested feature

When user changes the setting for mirror, it should show a toast saying to restart the app, similar to how it's done in Komga

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/04f8307fd944635f4aae010c9721007111595fb0/src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt#L492

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Won't fix - 51f35d8d755b798b7430e3ca42185861ce842ef6
