### ISSUE TITLE
Japscan CloudFare Issue

### ISSUE THREAD

**Issue by Abd1709** [tachiyomiorg/tachiyomi-extensions#15002]
### Source information and language

Japscan 1.3.35

### Steps to reproduce

Japscan just doesnt work. Whenever i want to open a chapter, it makes « Size :0,Index:0 ».

### Expected behavior

Chapters from japscan should work. 
Updating from japscan extension should work.

### Actual behavior

« Size :0 , Index :0 » when i open any chapter from Japscan extension.
Impossible to update chapters from japscan extension (infinite loading)

### Tachiyomi version

0.14.3-5452

### Android version

Android 11

### Other details

I tried every single things from the troubleshoot guide regarding the cloudfare and it still doesn’t work. Thanks in advance for your help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Cloudflare can be solved following this guide: https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

The actual error is "Size: 0, Index: 0" when opening a chapter
