### ISSUE TITLE
bato.to down 

### ISSUE THREAD

**Issue by MaudiH** [tachiyomiorg/tachiyomi-extensions#15007]
### Source information and language

bato.to 1.3.31

### Steps to reproduce

Click on bato.to latest , filter or popular to browse titlea 
You reiceve error messsage as shown above 
![Screenshot_20230118-030921~3](https://user-images.githubusercontent.com/12390457/213058546-d3134249-98b0-43d2-a5e2-6b8ef5955e0f.png)

### Expected behavior

When browsing bato.to .
It loads its the titles along its images from the server.

### Actual behavior

The same image 
![Screenshot_20230118-030921~3](https://user-images.githubusercontent.com/12390457/213059380-ba0f8afc-4228-4136-8c60-baac89038470.png)
Since it is down

### Tachiyomi version

0.14.3

### Android version

Android 10

### Other details

To insure it's not an extension or scraper error  . 
I have Tried with webview it keeps blank page .
Pinged and checked isitdown  from several sites and bato.to is down however mirrors such as mangatoto are not

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

**Comment by raziel100** [comment]
![Screenshot_20230118-094722_TachiyomiJ2K](https://user-images.githubusercontent.com/11368528/213175398-d39fa7f6-7755-4ebc-8c99-51d01e44aaf7.jpg)

The source is already on again, I believe this issue can be closed
