### ISSUE TITLE
Sinensis 

### ISSUE THREAD

**Issue by gatinhecomunista** [tachiyomiorg/tachiyomi-extensions#15019]
### Source information and language

Sinensis Scan - Português

### Source new URL

https://sinensisscans.com/manga/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Fixed by #15145.
