### ISSUE TITLE
Japscan and Manga-Scantrad down - error Cloudfare

### ISSUE THREAD

**Issue by SenninShinkiro** [tachiyomiorg/tachiyomi-extensions#15015]
### Source information and language

Manga-Scantrad v1.3.30 - Japscan v1.3.35

### Steps to reproduce

Manga-Scantrad Japscan just doesnt work. Whenever I want to open a chapter, it makes « Impossible de contourner Cloudfare ».

### Expected behavior

Chapters from japscan and Manga-scantrad should work.

### Actual behavior

Impossible to read chapter or update.
Loading and error message "cloudfare"

### Tachiyomi version

0.14.3

### Android version

Android 13

### Other details

Change agent : No work
uninstall/install app : No work
Try Webview : No Work.
Cache WebView : No Work
Try with other device : No work.
Delete Caches : No Work
Dowload extension from https://tachiyomi.org/extensions/ : No work

Thank you in advance for your help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Japscan has been updated. Try fixing your other Cloudflare issues by following https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues.

**Comment by SenninShinkiro** [comment]
Hello,

For cloudfare as mentioned above I have already done the tests: without success.

I see that Japscan has been updated but what about manga-scantrad?

Besides with the update of japscan there are always errors. One of you could test ?

You will see in attachment the webview error that there is with japscan.
On the other hand with manga scantrad the webview works... but still impossible to read chapters in the library.

Thank you in advance 
![Screenshot_20230119_073820_TachiyomiJ2K](https://user-images.githubusercontent.com/123007331/213373191-bce7d379-41de-418f-9df9-382a3bd153aa.jpg)

**Comment by stevenyomi** [comment]
If the methods don't work, either migrate to other sources or wait until they lower their protection. There isn't much we can do.

**Comment by beerpiss** [comment]
The JapScan update was to ratelimit the extension and hopefully stop them from raising their Cloudflare level in the future; we can't do much about the current issue.
