### ISSUE TITLE
HTTP error 520 asurascans

### ISSUE THREAD

**Issue by TheAssassinRaven** [tachiyomiorg/tachiyomi-extensions#15021]
### Source information and language

Asura Scans  Multi Vers. 1.3.40

### Steps to reproduce

1. Go to source and try opening asurascans 
2. Error 520 pop's up 
3. Clicking Webview 
4. There, it states that th host has a problem 

### Expected behavior

Now i conclude that if i were to open asurascans via the same link as the app does, but on a separate browser, the same problem should appear.

### Actual behavior

But when i go on a separate browser, the problem doesn't appear, and i can see all the mangas they have

### Tachiyomi version

0.14.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
does this still happen?

**Comment by vetleledaal** [comment]
Closing due to no response.
