### ISSUE TITLE
Failure to bypass cloudflare 

### ISSUE THREAD

**Issue by yuributa** [tachiyomiorg/tachiyomi-extensions#15038]
### Source information and language

Mangafreak 1.3.8 (English)

### Steps to reproduce

1. Browse the library
2.  Open in Webview

### Expected behavior

Both instances show the manga library.

### Actual behavior

Both instances fail to bypass cloudflare. The website itself works.

### Tachiyomi version

r5452

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Try the methods in https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If none works, migrate to other sources or wait for the site to lower their protection level.

**Comment by windumasta** [comment]
same issue with some app
like japscan 
![Screenshot_20230122_125255_Tachiyomi](https://user-images.githubusercontent.com/13628729/213946908-aed6dde1-681f-444c-8952-8d2532a8dbba.png)
