### ISSUE TITLE
Imperfect comics site shut down

### ISSUE THREAD

**Issue by xlogisticsx** [tachiyomiorg/tachiyomi-extensions#15048]
### Source information and language

Imperfect comics 1.3.32

### Steps to reproduce

Site times out in all browsers. [Announcement made in their Discord](https://discord.com/channels/693221120144310432/693534488851906581/1063654570204610631)  about shutting down the site and collaborating with Manhwa Freak going forward. Screenshot also included.

![Screenshot_20230120_234952_Discord](https://user-images.githubusercontent.com/61717678/213844380-b8ede0a9-e1d8-4155-b216-d40926a00e67.jpg)

### Expected behavior

Site responds

### Actual behavior

Site times out

### Tachiyomi version

0.14.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by poorloading** [comment]
Well that explains a lot lol
