### ISSUE TITLE
Poder dar prioridad a una extención al momento de buscar un manga 

### ISSUE THREAD

**Issue by CR4ZYDANI** [tachiyomiorg/tachiyomi-extensions#15051]
### Source information and language

Todas

### Steps to reproduce

Al tener muchas extenciones la app busca en varias extenciones y justo la que más utilizo la deja hasta el último 

### Expected behavior

Que se pueda dar prioridad a las extensiones al momento de buscar un manga 

### Actual behavior

Tarda mucho en buscar los mangas al tener muchas extenciones
Se que es normal que tarde más por tener muchas extenciones

### Tachiyomi version

Última versión 

### Android version

Android 11

### Other details

Otra cosa es que al buscar un manga no siempre encuentra los que busco como aquí que hice la misma búsqueda dos veces y tuve diferentes resultados.
También cuando estoy leyendo un manhwa no siempre cargan todas las partes por así decirlo, cómo los manhwas no tienen páginas y son más como tiras largas no sabría cómo describir, pero si noto que al volver al leer de nuevo el capítulo aparecen imágenes o partes que no estaban antes.

(No manejo bien github y como no se inglés pues aquí envío todo los que tengo por aportar 😅😁)

Pdt. Agregen más extenciones en español como https://hitomi.la/
![Screenshot_2023-01-21-04-41-44-761_eu kanade tachiyomi](https://user-images.githubusercontent.com/73937080/213861320-966560b1-445c-43db-9abc-a33960765f90.jpg)
![Screenshot_2023-01-21-04-40-14-886_eu kanade tachiyomi](https://user-images.githubusercontent.com/73937080/213861322-0236f528-5202-4f49-9f51-ddcdfde84c97.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CR4ZYDANI** [comment]
No entiendo inglés y por eso puse eso, pero en lo demás por favor 🙏😔

**Comment by beerpiss** [comment]
activar la opción "Solo incluir fuentes ancladas" en la configuración y ancla las fuentes en las que quieras buscar.

> traducido por deepl
