### ISSUE TITLE
WNACG 讀取超時

### ISSUE THREAD

**Issue by jay02105** [tachiyomiorg/tachiyomi-extensions#15068]
### Source information and language

WNACG 1.3.10 中文

### Steps to reproduce

1.打開Tachiyomi
2.打開WNACG
3.讀取超時

### Expected behavior

顯示漫畫列表

### Actual behavior

讀取超時

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

![Screenshot_2023-01-22-15-43-53-829_eu kanade tachiyomi](https://user-images.githubusercontent.com/116051165/213906095-ecb2cbd6-b306-45a7-86c9-fff034b2afaa.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Check your network connection.
