### ISSUE TITLE
Tritinia Scans: HTTP error 405

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#15070]
### Source information and language

TritiniaScans 1.3.30 (english)

### Steps to reproduce

Open TritiniaScans extension

### Expected behavior

Mangas should load normally

### Actual behavior

Error 405 is showing
In Web view page working normally

### Tachiyomi version

0.14.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
works for me, maybe fixed by madara update thing or just temporary issue
