### ISSUE TITLE
https://www.htmanga.top 無法使用

### ISSUE THREAD

**Issue by jay02105** [tachiyomiorg/tachiyomi-extensions#15072]
### Source information and language

WNACG 1.3.10 中文

### Source new URL

https://www.wnacg.top

### Other details

已確定連線正常且能使用其他漫畫網站，只有htmanga無法使用

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
你提供的那个网址大陆无法访问，所以被换掉了。

请你到 https://www.wnacglink.top/ 看一下除了提到的两个网址，其他三个你是否可以访问。

**Comment by jay02105** [comment]
確定其他三個能使用，只有htmanga無法連上
