### ISSUE TITLE
[SOURCE REQUEST][French] Scan Manga

### ISSUE THREAD

**Issue by Savitarkurosaki** [tachiyomiorg/tachiyomi-extensions#1508]
Many mangas and regular updates
Source: http://m.scan-manga.com/?sm

**Comment by Savitarkurosaki** [comment]
Up

**Comment by Lyoses** [comment]
Yeah

**Comment by Elfayer** [comment]
Link provided is dead, new valid URL: https://scans-mangas.com/

**Comment by Savitarkurosaki** [comment]
None of them
The Link works fine with me
![Screenshot_20200507_141810_com android chrome](https://user-images.githubusercontent.com/55365920/81305756-3c424600-906e-11ea-889d-70098a5d472a.jpg)

**Comment by Savitarkurosaki** [comment]
I resend
https://m.scan-manga.com/?sm

**Comment by Mitia99** [comment]
up

**Comment by Mitia99** [comment]
> Link provided is dead, new valid URL: https://scans-mangas.com/ or is it https://scansmangas.xyz/ ?
@Elfayer 
These are another sources.Just the same name.

**Comment by Mitia99** [comment]
@arkon 
Additional information if it can help.The site doesn't work with an adblock.

**Comment by PastaGringo** [comment]
UP :)

**Comment by Carducci243** [comment]
Hello is there Any update concerning this source coming to tachiyomi?
