### ISSUE TITLE
Immortal Updates - descrambler still needs to de-invert colors

### ISSUE THREAD

**Issue by mneko** [tachiyomiorg/tachiyomi-extensions#15081]
### Source information and language

Immortal Updates 1.3.30

### Steps to reproduce

Example manga: I Just Want To Be Killed chapter 141, page 12 and after

Random user agent setting doesn't matter 

### Expected behavior

Normal looking panels

### Actual behavior

![Screenshot_20230123-091311_TachiyomiSY](https://user-images.githubusercontent.com/927948/214075510-d9d31195-c1e4-4df0-8005-9845068b814c.jpg)

### Tachiyomi version

1.8.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
Images are already inverted; however they are inverted indiscriminately, even on already inverted ones. Will fix soontm
