### ISSUE TITLE
Tumanga.net extension isn't working 

### ISSUE THREAD

**Issue by GoblinOfHaze** [tachiyomiorg/tachiyomi-extensions#15090]
### Source information and language

TuManga 1.3.28 (Spanish)

### Steps to reproduce

1. Use TuManga.net extension
2. Open any manga to read
3. Won't open, says "tumanga.net"

### Expected behavior

Manga chapters have to open

### Actual behavior

Manga chapters won't open

### Tachiyomi version

0.14.3

### Android version

Android 8

### Other details

I think this site has been deleted but I see that no one really knows what happened.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Lenoyr** [comment]
Dead site bro
check: https://dnschecker.org/#A/Tumanga.net

**Comment by GoblinOfHaze** [comment]
> Dead site bro check: https://dnschecker.org/#A/Tumanga.net

Thanks for the confirmation, the site left without trace and nobody has been talking about it.
