### ISSUE TITLE
Тачиёми не видит скачанные главы

### ISSUE THREAD

**Issue by Stan-tab** [tachiyomiorg/tachiyomi-extensions#15092]
### Source information and language

Возмонжно во всех источниках

### Steps to reproduce

1. Скачиваю главу
2. Данные по ней обновляются
3. Тачиёми перестаёт видеть главу

### Expected behavior

Я бы хотел, чтобы тачиёми не переставал показывать скачанные главы.

### Actual behavior

К сожалению придётся удалить папку с мангой и заного скачать

### Tachiyomi version

0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Translation tldr:

> Tachiyomi doesn't recognize downloads after manga update, possibly all sources. Need to remove the downloaded chapter folder and redownload it.

There are multiple potential reasons for this (the source you're using changing chapter names, app permissions, your OS handling file names not as expected). You can go to #support channel on [Discord](https://discord.gg/tachiyomi) to get help with troubleshooting the issue.

**Comment by alessandrojean** [comment]
Closing as it lacks information. Please follow the suggestions by scb261 and ask for help at our Discord.
