### ISSUE TITLE
Load.la: HTTP error 404

### ISSUE THREAD

**Issue by kaushilptl** [tachiyomiorg/tachiyomi-extensions#15124]
### Source information and language

load.la

### Steps to reproduce

On my browser when I open the url load.la, it gives me a blank page, and when I refresh a page that I had kept opened from last week, it gives me the error 404 not found.

### Expected behavior

The expected behavior should be to launch the website.

### Actual behavior

The url load.la is actually loading a blank page.

### Tachiyomi version

0.14

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
There's no extension for this site, the site is dead either way
https://www.reddit.com/r/Hentoid/comments/10o0463/anyone_know_what_happened_to_loadla/
