### ISSUE TITLE
Zerobyw: Changed their domain

### ISSUE THREAD

**Issue by PKDSETER111** [tachiyomiorg/tachiyomi-extensions#15134]
### Source information and language

zero搬运网 1.3.13 (zh)

### Source new URL

http://zerobyw.top/

### Other details

No response

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
New URL (from #15424): http://www.zerobyw1060.com/
