### ISSUE TITLE
mangastk.xyz

### ISSUE THREAD

**Issue by Lenoyr** [tachiyomiorg/tachiyomi-extensions#15130]
### Source name

mangastk.xyz

### Source link

https://mangastk.xyz/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by VannevarB** [comment]
This week MangasTK returned to the old domain (.net)

**Comment by VannevarB** [comment]
mangastk.net is dead now. the site owners decided to split their project in two. Now mangastk.xyz for sfw manga/manhwa/novels and mangastk18.com for nsfw.
