### ISSUE TITLE
Japscan Cloudflare error

### ISSUE THREAD

**Issue by DaMakoumba** [tachiyomiorg/tachiyomi-extensions#15142]
### Source information and language

Japscan 1.3.37

### Steps to reproduce

1. Open Japscan extension for showing manga titles
2. Loading
3. Cloudflare error. 

### Expected behavior

Mangas library should open. 

### Actual behavior

Cloudflare error. 

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, migrate to other sources.
