### ISSUE TITLE
Hijala

### ISSUE THREAD

**Issue by xkingxn** [tachiyomiorg/tachiyomi-extensions#15143]
### Source name

hijala

### Source link

https://hijala.blogspot.com/

### Language

Arabic 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses ZeistManga theme

**Comment by XOCV0** [comment]
Add this site please

**Comment by MeLoseAgain** [comment]
@alessandrojean close it's issues

**Comment by alessandrojean** [comment]
Closing, but doesn't need to ping me next time for this.
