### ISSUE TITLE
Problem downloading some manga chapters

### ISSUE THREAD

**Issue by Zahyra16** [tachiyomiorg/tachiyomi-extensions#15151]
### Source information and language

YugenMangas (Spanish)

### Steps to reproduce

Problem downloading some chapters of some manga, e.g.

https://yugenmangas.net/series/segunda-vida-para-ser-un-ranker

The last 2 chapters I can read online but when I download them, it downloads the images but then stops.

Checking tachiyomi's download folder, the whole chapter downloaded but in the download section it looks like pages are missing.

![Screenshot_2023-01-27-17-49-20-431_eu kanade tachiyomi](https://user-images.githubusercontent.com/92189825/215222133-357f8459-bac1-43b7-8de5-06ba7e1bad80.jpg)

I was checking and I see that the website changed from YugenMangas.com to Yugenmangas.net.
But no change in the web design

### Expected behavior

Download the chapters

### Actual behavior

Error downloading chapters

### Tachiyomi version

0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Checked their API for this chapter you provided as an example, their website isn't returning some valid images in the end of the chapter, so they fail to load and makes the download to fail too. In their website these images doesn't load as well (they're loaded but hidden, and don't show the broken image icon, but they're there). This is something they need to fix really but I think the extension can probably ignore these ones.
