### ISSUE TITLE
Japscan possible solution 

### ISSUE THREAD

**Issue by Genki74** [tachiyomiorg/tachiyomi-extensions#15152]
### Source information and language

Japscan 1.3.37 

### Steps to reproduce

1) open tachiyomi
2) go in option
3) go in advanced
4) in default user agent string replace the default one with yours found here https://www.whatismybrowser.com/guides/the-latest-user-agent/
5) restart tachiyomi
6) open japscan in webview
7) wait for it to pass cloudflare
8) done

### Expected behavior

Japscan work

### Actual behavior

Japscan don't work

### Tachiyomi version

R5465

### Android version

Android 9

### Other details

Please do not close this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Genki74** [comment]
Just, the recent filters do not work, but you can have your Manga chapters updated

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If you tried everything listed in our guide and it still doesn't work, only thing you can do is wait until they lower their protection or migrate to other sources.

Closing as there's really nothing we can do.

**Comment by Akhofreeze** [comment]
> ### Source information and language
> Japscan 1.3.37
> 
> ### Steps to reproduce
> 1. open tachiyomi
> 2. go in option
> 3. go in advanced
> 4. in default user agent string replace the default one with yours found here https://www.whatismybrowser.com/guides/the-latest-user-agent/
> 5. restart tachiyomi
> 6. open japscan in webview
> 7. wait for it to pass cloudflare
> 8. done
> 
> ### Expected behavior
> Japscan work
> 
> ### Actual behavior
> Japscan don't work
> 
> ### Tachiyomi version
> R5465
> 
> ### Android version
> Android 9
> 
> ### Other details
> Please do not close this
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

This solution worked for me.
