### ISSUE TITLE
Title not appearing on different devices

### ISSUE THREAD

**Issue by s03ki** [tachiyomiorg/tachiyomi-extensions#15159]
### Source information and language

Mangadex 1.3.177, english

### Steps to reproduce

1. Open Mangadex extension (device H)
3. Choose "latest" option
4. Scroll to check title update
5. Redo the same on another device (device S)

### Expected behavior

Title list on both devices are the same since both device has the same app and extension version

### Actual behavior

Some title on device S is missing compared to device H

Device H
`
![Screenshot_20230128_210102_Tachiyomi](https://user-images.githubusercontent.com/70456820/215271973-1c92dd20-018c-4b85-b6fb-5f665ea12cfa.jpg)
![Screenshot_20230128_211736_Tachiyomi](https://user-images.githubusercontent.com/70456820/215271979-b29208fe-8f88-4d00-b83b-3bdf507fda3b.jpg)
`

Device S
`
![Screenshot_20230128_210102_eu kanade tachiyomi](https://user-images.githubusercontent.com/70456820/215271997-c9a38d0e-d0ab-41ba-9586-a64e5d9c67b1.jpg)
![Screenshot_20230128_211737_eu kanade tachiyomi](https://user-images.githubusercontent.com/70456820/215272002-2b9146dc-5ce2-4dac-8a6f-f786e13e1b5b.jpg)
`

### Tachiyomi version

0.14.3

### Android version

13

### Other details

Device S android 13, device H android 10, both devices has the same extension and app setting

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Your other device likely have different settings for the content rating. Check the extension settings on both devices (Browse > Extensions > MangaDex > ⚙️ on the language you use > Content rating).
