### ISSUE TITLE
Hbrowse

### ISSUE THREAD

**Issue by LegacyPhil** [tachiyomiorg/tachiyomi-extensions#15173]
### Source information and language

Hbrowse 1.3.7

### Steps to reproduce

Doesn't open

### Expected behavior

Access to the site

### Actual behavior

This extension has been down for many days

### Tachiyomi version

0.14.3

### Android version

Andriod s20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do provide more information besides "doesn't open". What error messages are you getting?

**Comment by LegacyPhil** [comment]
> Please do provide more information besides "doesn't open". What error messages are you getting?

Error code 521

**Comment by alessandrojean** [comment]
This is a server side error, check if the website is opening in WebView. By being a server side error, we can't do anything, the site owners that need to fix it. If you need additional support, ask at our #support channel in [Discord](https://discord.gg/tachiyomi).
