### ISSUE TITLE
The Hentai

### ISSUE THREAD

**Issue by RyomeSukuna** [tachiyomiorg/tachiyomi-extensions#15179]
### Source name

The Hentai

### Source link

https://thehentai.net/

### Language

Portuguese & English

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The search doesn't seem to have a proper language filter so this makes things difficult for an extension.
