### ISSUE TITLE
MangaHub: Parsing is failing

### ISSUE THREAD

**Issue by Davidbolt121199** [tachiyomiorg/tachiyomi-extensions#15181]
### Source information and language

Mangahub 1.3.21(English) 

### Steps to reproduce

1. Manga new chapters are not uploading.
2. New manga chapters are not showing.

### Expected behavior

It should have uploaded new chapters.

### Actual behavior

Instead showing 
![Screenshot_2023-01-30-20-42-04-244_eu kanade tachiyomi-edit](https://user-images.githubusercontent.com/121578582/215517943-4641f698-169c-47df-82d3-7dc93a44337d.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Davidbolt121199** [comment]
New manga chapters not showing.
![Screenshot_2023-01-30-20-51-19-930_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/215518673-a3c42785-0ab4-4b9b-bdda-706ed483bc31.jpg)

**Comment by Davidbolt121199** [comment]
The issue is not fixed it shows same
![Screenshot_2023-01-31-09-37-02-354_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/215660543-0d726a4f-bd05-4338-8a87-ab299a33c73e.jpg)

**Comment by raziel100** [comment]
The same error is still happening, and if you continue trying it will update the list, but with this error
![Screenshot_20230131-085630_TachiyomiJ2K](https://user-images.githubusercontent.com/11368528/215753764-056cc806-cd33-47ed-bd36-19d3bbfc501d.jpg)
