### ISSUE TITLE
Tengo error 429

### ISSUE THREAD

**Issue by LufeQM** [tachiyomiorg/tachiyomi-extensions#15192]
### Source information and language

Tu Manga Online Tmo

### Steps to reproduce

Primero entre a la app y cuando actualizo directorio me apareció 2 mangas que fallaron por un error 429 
Segundo poco a poco cada que actualizaba sea aumentaba más mangas empezó con dos y ahora tengo más de diez mangas con ese error 

### Expected behavior

No debería de fallar a actualización, debería dar normal, todo se omite por culpa de el error 429

### Actual behavior

En su lugar ahora casi ningun manga que tengo se actualiza 

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

Ya no se que hacer 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seew3l** [comment]
En ajustes de la extensión, reduce el ratelimit para el sitio web (por defecto debe estar en 10, prueba reducirlo a 5)

**Comment by alessandrojean** [comment]
This happens when you do a lot of requests to the same source, try the seew3l suggestion and also spread your library items into more sources.
