### ISSUE TITLE
Extensions not downloading or updating 

### ISSUE THREAD

**Issue by Monono58** [tachiyomiorg/tachiyomi-extensions#15194]
### Source information and language

HentaiWebtoon 1.3.28 (English)

### Steps to reproduce

Don't have any idea how this started and happened. 
Started after latest update of 0.14.3

### Expected behavior

Source should be downloaded or updated if already downloaded.

### Actual behavior

Extensions does not download or the already downloaded are not updating.

### Tachiyomi version

0.14.3

### Android version

Android 9

### Other details

Updating Extensions does not have any effect and it shows downloading whole time on already downloaded extensions.
Trying to download a new extension results in the same as before.
Tried changing DNS over HTTPS.
Tried changing user agent string.
Tried changing installer from legacy to Packageinstaller to Shizuku.
Tried changing network.
Restarted device multiple times.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
This is not related to the extension.

I suggest asking for help in the #support channel in the Discord server.

Note: 0.14.3 did not change anything related to installing extensions, so it might be an issue with your device/system.
