### ISSUE TITLE
MangaHub: Wrong chapter numbers

### ISSUE THREAD

**Issue by ncarvalho99** [tachiyomiorg/tachiyomi-extensions#15200]
### Source information and language

MangaHub 1.3.23 (English)

### Steps to reproduce

1. Go in any manga using MangaHub extension
2.  If had already  accessed a manga from MangaHub and refresh, it wlll show new chapters that doesn't exist. But if go to one that was not accessed before, it'll appear some chapters that the string is not correctly structured and if try enter one of these new chapters, it'll not connect and will report an error

### Expected behavior

Shouldn't appear this addictional chapters that doesn't go anywhere

### Actual behavior

Show addictional chapters that doesn't go anywhere and the string is not correctly structured and gives the following error: "Expected URL scheme 'http' or 'https' but not scheme was found for"

### Tachiyomi version

0.14.3

### Android version

Android 13

### Other details

This is how normally should have been 
![Screenshot_20230131-143633](https://user-images.githubusercontent.com/47823287/215884285-639af99b-c082-4aa1-ad73-3520a29068aa.png)

This is how it was after the Issue #15186 was closed
![Screenshot_20230131-143647](https://user-images.githubusercontent.com/47823287/215884741-3057ee18-dd01-4196-a159-a93108f9104f.png)

![Screenshot_20230131-143729](https://user-images.githubusercontent.com/47823287/215884759-bc39a673-3011-4841-848d-d85df606016b.png)

And after update the extension to 1.3.24 it became like that
![Screenshot_20230131-162554](https://user-images.githubusercontent.com/47823287/215884843-bd0360a5-a3a1-4028-adcb-f9867b9bff03.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
this has already be fixed in #15198 but for some reason have failed to build the apk.

**Comment by raziel100** [comment]
The app extension was builded, but for some reason the string for the chapters name became a little crazy ![image](https://user-images.githubusercontent.com/11368528/215880251-4671a889-0f3c-4613-ae33-96a5bce439b7.png)

**Comment by ncarvalho99** [comment]
This is how normally should have been 
![Screenshot_20230131-143633](https://user-images.githubusercontent.com/47823287/215884285-639af99b-c082-4aa1-ad73-3520a29068aa.png)

This is how it was after the Issue #15186 was closed
![Screenshot_20230131-143647](https://user-images.githubusercontent.com/47823287/215884741-3057ee18-dd01-4196-a159-a93108f9104f.png)

![Screenshot_20230131-143729](https://user-images.githubusercontent.com/47823287/215884759-bc39a673-3011-4841-848d-d85df606016b.png)

And after update the extension to 1.3.24 it became like that
![Screenshot_20230131-162554](https://user-images.githubusercontent.com/47823287/215884843-bd0360a5-a3a1-4028-adcb-f9867b9bff03.png)

**Comment by alessandrojean** [comment]
The website owners are constantly changing stuff to intentionally break the extension. We recommend start using other extensions instead as this will not stop anytime soon and have already happened before.
