### ISSUE TITLE
MIUI 13.0.13 can install extensions

### ISSUE THREAD

**Issue by luc-yang** [tachiyomiorg/tachiyomi-extensions#15215]
### Source information and language

All 

### Steps to reproduce

Xiao Mi phone with MIUI 13.0.13 can not install any extensions, warning that "解析软件包时出现问题“.

### Expected behavior

Extensions should be installed successfully.

### Actual behavior

Extensions installedfailed.

### Tachiyomi version

0.14.3

### Android version

MIUI 13.0.13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
