### ISSUE TITLE
Manhwa-Latino HTTP Error 403

### ISSUE THREAD

**Issue by Zer03021** [tachiyomiorg/tachiyomi-extensions#15211]
### Source information and language

Manhwa-Latino 1.3.22 (Español)

### Steps to reproduce

1. Open the Extensión

### Expected behavior

![Screenshot_2023-02-02-08-29-16-40_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/216325804-fe19f3af-7515-4b7d-b602-a5369192415e.jpg)

### Actual behavior

![Screenshot_2023-02-02-08-25-15-68_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/216326033-7bda8de5-2b53-495f-be0a-54b4ef9e77e3.jpg)
![Screenshot_2023-02-02-08-23-25-74_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/216326074-c43856a7-50a4-444f-aad0-44ee8332d0aa.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seew3l** [comment]
try this:
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by Zer03021** [comment]
thanks, it helped meEl 2 feb. 2023 12:01 p. m., seew3l ***@***.***> escribió:
try this:
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
