### ISSUE TITLE
MangaHub: Missing chapters

### ISSUE THREAD

**Issue by JOZU101** [tachiyomiorg/tachiyomi-extensions#15216]
### Source information and language

Mangahub 1.3.26 (English)

### Steps to reproduce

1. Open the app
2. Open the extension
3. Open any manga 
4. Some of them has missing chapter, page not found & some image could not be loaded. 

### Expected behavior

Normal manga in mangahub extension without missing a chapter.
![inbound8899787332195770070](https://user-images.githubusercontent.com/124290733/216538666-4b6479b8-e726-4268-a92f-24a3a7df683a.jpg)

### Actual behavior

Error missing chapter and page couldn't be loaded/found.
![inbound8611501037611034310](https://user-images.githubusercontent.com/124290733/216538962-f51179ca-11c2-46f9-9c10-826c6ba8e244.jpg)
![inbound668414786484217349](https://user-images.githubusercontent.com/124290733/216538972-f77346b4-302f-4b3f-8b41-42cdb0e3e759.jpg)
![inbound9022791760433300180](https://user-images.githubusercontent.com/124290733/216538976-057d5f31-3d37-44a4-93d2-7f481b5b9438.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 11

### Other details

Detail above.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
See #14736 for the missing page issue

**Comment by Seishirou101** [comment]
possibly already fixed by #16229, but currently has an issue #16297
