### ISSUE TITLE
Japscan just don't work

### ISSUE THREAD

**Issue by Na2SO** [tachiyomiorg/tachiyomi-extensions#15229]
### Source information and language

Japscan 1.3.38

### Steps to reproduce

1) Download the extension Japscan in tachiyomi app
2) Open Japscan 
3) Bug and crash

### Expected behavior

Normally, all the manga should be visible and when open it, display all chapters. 

### Actual behavior

Bug and crash. 

### Tachiyomi version

0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
> To dump crash logs go to More → Settings → Advanced then enable verbose logging then restart Tachiyomi.
Reproduce the crash and go to More → Settings → Advanced then tap Dump crash logs.
You can disable verbose logging afterwards.

**Comment by AlCiavi** [comment]
The extensions just doesn't work. We can load sources, check it in WebView, but the pages don't load in the app. Thank you for your concern.

**Comment by Mylloon** [comment]
> The extensions just doesn't work. We can load sources, check it in WebView, but the pages don't load in the app. Thank you for your concern.

What you describe is probably #15749
