### ISSUE TITLE
Comick can't parse dates

### ISSUE THREAD

**Issue by jfcaraujo** [tachiyomiorg/tachiyomi-extensions#15231]
### Source information and language

Comick 1.3.19 En

### Steps to reproduce

Update any manga from source
Open new manga (without cache) from source

### Expected behavior

Should show chapters

### Actual behavior

Error: unparseable date 2023-01-19T01:31:20Z (for example)

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GamaG27** [comment]
I also have the same problem No matter the language or if it is Tachiyomi stable or preview.
