### ISSUE TITLE
Mehaze.ID

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#15240]
### Source name

Mehaze.ID

### Source link

https://mehaze.id/

### Language

Indonesia 

### Other details

NSFW? Yup
Theme? Idk but appear to use WordPress theme 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Domain has no A record, is it working for you?

**Comment by TheKingTermux** [comment]
Like the website is broken for now
Idk why....
Actually when I created this issue the website was still running normally and without any problems
**Closed for now**
If the website comes back from the dead I will make a new issue
