### ISSUE TITLE
Hiperdex: changed their domain

### ISSUE THREAD

**Issue by konta09** [tachiyomiorg/tachiyomi-extensions#15244]
### Source information and language

hiperdex

### Source new URL

https://1sthiperdex.com

### Other details

error 400

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by MaudiH** [comment]
I think adding a mirror option in the settings like batoto might be a solution since they switch back and forth between hiperdex.com  and 1sthiperdex.com

**Comment by MohammadAdiyudha** [comment]
Yeah, i think mirror like batoto really helpful in hiperdex
