### ISSUE TITLE
isekaiscan.com source url change

### ISSUE THREAD

**Issue by Samajestay** [tachiyomiorg/tachiyomi-extensions#15253]
### Source information and language

isekaiscan.com 1.3.32

### Source new URL

isekaiscan.top

### Other details

Webview still shows the old url in .com but a quick google search gives out isekaiscan.top as a replacement.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
As said above
