### ISSUE TITLE
Manga168 no results found

### ISSUE THREAD

**Issue by Kittoshi** [tachiyomiorg/tachiyomi-extensions#15265]
### Source information and language

Manga168.com

### Steps to reproduce

Search manga168 and manga168
Try to add another language
still No results found

### Expected behavior

Manga168 exist

### Actual behavior

No results found

### Tachiyomi version

0.14.1

### Android version

Andriod 10

### Other details

I has pull request to add this extensions and the bot said that already has a request for this website. But its show no results found

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
the request is still open.
