### ISSUE TITLE
Inability to use offline

### ISSUE THREAD

**Issue by Zer03021** [tachiyomiorg/tachiyomi-extensions#15263]
### Source information and language

LectorManga 1.3.25 (Español)

### Steps to reproduce

1. Having a chapter of any manga downloaded from the library
2. NO MOBILE DATA OR WIFI ACTIVATED
3. Open chapter
the tachiyomi application closes automatically

### Expected behavior

Should see the downloaded chapters (before the application update they were displayed).

### Actual behavior

automatically the application closes automatically (but only with sleeves of that LectorManga extension)

### Tachiyomi version

0.14.4

### Android version

Android 11

### Other details

Before the update (0.14.4) everything was working fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As a side note to whoever wants to fix this: it's probably crashing the app because the `pageListRequest` is actually doing an request before returning the one needed. This method should not make any requests at all, it just should straight up return the first request needed, additional ones need to be done in the `pageListParse` method.
