### ISSUE TITLE
IsekaiScan.com timeout issue

### ISSUE THREAD

**Issue by shawnfeds** [tachiyomiorg/tachiyomi-extensions#15261]
### Source information and language

IsekaiScan.com

### Steps to reproduce

clicked the extension in the browse tab sources

### Expected behavior

should open the source and load the source mangas

### Actual behavior

shows timeout page

### Tachiyomi version

0.14.4

### Android version

Android 12

### Other details

The source does not in the webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
not our issue, the page doesn't even load in webview
