### ISSUE TITLE
NewToki : Add login feature for CAPTCHA

### ISSUE THREAD

**Issue by chongjae** [tachiyomiorg/tachiyomi-extensions#15266]
### Source name and language

newtoki

### Describe your suggested feature

The daily new updated library requires a captcha. 
However, if you log in, you can skip the captcha. 
I propose a logic that updates the library after logging in by entering an ID and password in the settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by chongjae** [comment]
I didn't have a captcha to login until yesterday, but when I checked today, I needed to enter the captcha to login.
So..I think it can not be used.

**Comment by stevenyomi** [comment]
I mean logging into the website using your ID and password in WebView.

**Comment by chongjae** [comment]
Yes. It is possible. Also, After login, i dont need to input captcha.

**Comment by stevenyomi** [comment]
Closing as login through WebView is working.

The login page has Captcha so it's hard to implement a settings in the extension. Making login information survive domain number change is also very difficult since migrating cookies locally will be very hacky, and we don't know the cookie structures, plus registering an account requires a Naver email.
