### ISSUE TITLE
Wrong pages displayed in hunter x hunter coloured manga

### ISSUE THREAD

**Issue by Hellboy31104** [tachiyomiorg/tachiyomi-extensions#15269]
### Source information and language

Read Hunter x Hunter Manga Online 1.3.4 (English)

### Steps to reproduce

The chapters of the coloured manga have haikyuu manga pages mixed with it. 
Example: Chapter 7 pages 1 and 2. 
Example: Chapter 22 pages 2 and 3

### Expected behavior

The pages of hunter x hunter coloured manga should have been displayed. 

### Actual behavior

The pages of haikyuu coloured manga are being displayed

### Tachiyomi version

0.14.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
not our problem

![image](https://user-images.githubusercontent.com/92439990/217503248-773d5e13-a7a1-49a5-860f-677321db3f30.png)
