### ISSUE TITLE
Problème avec japscan : impossible de télécharger des chapitres 

### ISSUE THREAD

**Issue by Km950** [tachiyomiorg/tachiyomi-extensions#15272]
### Source information and language

Japscan 1.3.38

### Steps to reproduce

Lorsque j'essaye de télécharger un chapitre je reçois un message d'erreur  (impossible de contourner couldflare)
`
![20230208_122614](https://user-images.githubusercontent.com/106619268/217516956-2b0a5faf-b432-4e9a-927a-fa0d328f72ad.jpg)
`

### Expected behavior

Normalement le téléchargement devrait se lancer 

### Actual behavior

`
![20230208_122614](https://user-images.githubusercontent.com/106619268/217517199-da67f4c9-0852-4c7a-8b19-f5797c524760.jpg)
`

### Tachiyomi version

0.14.4 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

If it doesn't work, migrate to other sources.
