### ISSUE TITLE
Zinchanmanga.net to .com

### ISSUE THREAD

**Issue by aomicat** [tachiyomiorg/tachiyomi-extensions#15276]
### Source information and language

ZinChanManga 1.4.5

### Source new URL

https://zinchanmanga.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by aomicat** [comment]
Domain needs to be change

**Comment by WonHoney** [comment]
Domain Change to "https://zinchanmanga.com/"

**Comment by aomicat** [comment]
Domain needs to be changed to https://zinchanmanga.com/
