### ISSUE TITLE
Komga Extension MissingFieldException when trying to load comics

### ISSUE THREAD

**Issue by JMartJonesy** [tachiyomiorg/tachiyomi-extensions#15270]
### Source information and language

Komga 1.3.45

### Steps to reproduce

1. Install Komga Extension
2. Configure Komga credentials
3. Browse Komga Library
4. Click any Library entry

### Expected behavior

Load available chapters under library entry.

### Actual behavior

Loads library entry details such as image, bios, but does not load available chapters under that entry.

![Screenshot_20230207_223302_Tachiyomi](https://user-images.githubusercontent.com/1325192/217454708-15ba04f5-6443-4cd9-8102-c57e6e6216a6.jpg)

### Tachiyomi version

0.14.4

### Android version

Android 13

### Other details

This worked a few months ago but coming back to Komga i now see this error for all my comics. Tried uninstalling Komga as well as Tachiyomi but still seeing this error. Also tried adding new comics but those failed as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you verify your komga server version?
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/komga/CHANGELOG.md#1345

**Comment by JMartJonesy** [comment]
I updated to the latest docker version last night
https://hub.docker.com/layers/gotson/komga/latest/images/sha256-46edb36ae60f1b267dffa4feed526b604f630aff007f0b0e35b4b636dff51c9d?context=explore

**Comment by CarlosEsco** [comment]
@gotson

**Comment by gotson** [comment]
@JMartJonesy can you provide startup logs of your Komga server?

**Comment by JMartJonesy** [comment]
@gotson Here are the logs, doing this from my phone so i apologize it's in an html page and the logs are in reverse order but should have all the startup logs you request.

You'll need to rename to a  .html file to open and see the logs

[komga-docker-startup-logs.log](https://github.com/tachiyomiorg/tachiyomi-extensions/files/10693150/komga-docker-startup-logs.log)
