### ISSUE TITLE
Animated Glitched Scans 'No Pages Found' Error

### ISSUE THREAD

**Issue by HaarisAhmed2001** [tachiyomiorg/tachiyomi-extensions#15279]
### Source information and language

Animated Glitched Scans - English 1.3.24 

### Steps to reproduce

1. Download Extension
2. Pick a series
3. Reload the series page
4. You will be notified with a 'No Pages Found' Error

### Expected behavior

You should be able to read the chapter normally.

### Actual behavior

You get the 'No pages found' Error when loading and reading a series from the Animated Glitch Scans extension.

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
I think this has been fixed, at least it works fine on my device.
