### ISSUE TITLE
1stkiss HTTP Error 400

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#15281]
### Source information and language

1st Kiss 1.3.36

### Steps to reproduce

1. view latest / popular
2. http error 400
3. webview ok

### Expected behavior

view manga list should be fine

### Actual behavior

http error 400

### Tachiyomi version

0.14.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BeingNiNa** [comment]
I guess still no SOLUTION! 😔

**Comment by gr8falcon** [comment]
Same issue http error 400 in 1st kiss..

**Comment by Trishan01** [comment]
Same here.

**Comment by Trishan01** [comment]
Http error 400
