### ISSUE TITLE
ZinchanManga got new domain. 

### ISSUE THREAD

**Issue by lognim** [tachiyomiorg/tachiyomi-extensions#15295]
### Source information and language

ZinChanManga 1.3.5 (English)

### Source new URL

https://zinchanmanga.com

### Other details

I hope to accept this brief request. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Duplicate of #15276
