### ISSUE TITLE
Cosmic Scans Indonesia

### ISSUE THREAD

**Issue by libran07** [tachiyomiorg/tachiyomi-extensions#15299]
### Source name

Cosmic Scans

### Source link

https://cosmicscans.id/

### Language

Indonesian

### Other details

![3fbcc059-eed4-4c04-8f63-b64f2e6a0a66](https://user-images.githubusercontent.com/90138720/218157716-53988f28-8449-4fb8-a5b8-e1ef27cc2b0d.jpeg)
![9d49fc9b-c590-463b-8976-ea8d8f7089df](https://user-images.githubusercontent.com/90138720/218157853-7c9b10f5-1142-4833-a388-937e53aa521a.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
