### ISSUE TITLE
Fix IsekaiScan

### ISSUE THREAD

**Issue by Hoodtitan** [tachiyomiorg/tachiyomi-extensions#15306]
### Source information and language

English 1.3.35 

### Steps to reproduce

1. Open IsekaiScan 
2. Loading
3. Time out

### Expected behavior

What should happen is that you open IsekaiScan it loads and different manga or manhwa show up.

### Actual behavior

This happend instead it was loading and just timed out.

### Tachiyomi version

0.14.4 

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their website is down, there's nothing we can do.
