### ISSUE TITLE
Add BentoManga

### ISSUE THREAD

**Issue by NeverReset** [tachiyomiorg/tachiyomi-extensions#15309]
### Source name

BentoManga

### Source link

https://www.bentomanga.com/

### Language

French

### Other details

Hi,
The japanread.cc has become bentomanga.com

So it's no longer possible to update / check new series

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Adam935** [comment]
+1

**Comment by chichid95** [comment]
+1
