### ISSUE TITLE
Original Quality Image From WebNovel Comics

### ISSUE THREAD

**Issue by omodia** [tachiyomiorg/tachiyomi-extensions#15305]
### Source name and language

WebNovel (English)

### Describe your suggested feature

The image quality is different when downloaded from hakuneko and tachiyomi.
- So please add an option to download the original image from WebNovel comics.
- See below attached images for reference. The original image is not blurry and is higher quality.

### Other details

For Example, [The Ultimate Scheming System, Chapter 001](https://www.webnovel.com/comic/the-ultimate-scheming-system_12272676305179201),
- The first image is 800 x 1122.
- The same image downloaded from hakuneko is 1536 x 2155.

- ### Image Downloaded Using Tachiyomi/Image that can be seen on webnovel comics while reading

![1](https://user-images.githubusercontent.com/116664905/218241586-cec9da13-8e55-4886-aa2b-0613b3d0b7d4.jpg)

- ### Image Downloaded Using Hakuenko

![01](https://user-images.githubusercontent.com/116664905/218241558-0bef90aa-6b98-4b02-96e9-1201cc8a384b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
I'll look into it
