### ISSUE TITLE
failed to bypass cloudflare realm scan

### ISSUE THREAD

**Issue by BEST8OY** [tachiyomiorg/tachiyomi-extensions#15301]
### Source information and language

Realm Scan (EN) 1.3.29

### Steps to reproduce

Can't update anything 

### Expected behavior

Manhwas should get updated 

### Actual behavior

They don't 

### Tachiyomi version

0.14.14

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BEST8OY** [comment]
Not sure why it is closed
Because the website doesn't have any cloudflare protection

**Comment by alessandrojean** [comment]
It does have, since you're getting the "Failed to bypass Cloudflare" error. Try following the guide as the bot said and if nothing solves it, wait until they lower their protection or migrate to other sources.

**Comment by SystemOdmin** [comment]
I started to have the same issue. No update about about increased protection in their discord or on the site. 
In webview site opens normally. In the app, there is nothing happening for about 20-30 seconds, only then I get Cloudflare error. 
Done all usual checks as by the guide. 
Tachiyomi 0.14.4
Android 10
The issue coincided with me updating Android System Webview. 
Can you check if it is really server-side?

**Comment by EarthMan123** [comment]
Solution is quite easy actually.

Just got to Settings -> Advanced -> Default user agent string

and change it with the following

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by SystemOdmin** [comment]
Didn't work for me yesterday but worked today, it seems I didn't restart app properly. Thank you.
