### ISSUE TITLE
DragonTranslation HTTP Error 400

### ISSUE THREAD

**Issue by Zer03021** [tachiyomiorg/tachiyomi-extensions#15313]
### Source information and language

DragonTranslation 1.4.32 (Español)

### Steps to reproduce

1. Open the extension

### Expected behavior

![Screenshot_2023-02-11-11-44-11-25_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/218267551-0ccb0557-5a69-4129-ad02-dbef8cf9a98f.jpg)

### Actual behavior

![Screenshot_2023-02-11-11-43-24-85_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/218267597-3333fc17-8c06-4dca-8e11-d59fd4d67504.jpg)

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seew3l** [comment]
The website no longer works, the scan abandoned it to move to another (YugenMangas). There is a site "dragontranslation.net" but the scan says that it is not official. I don't know if the extension should be removed.

**Comment by alessandrojean** [comment]
Don't post NSFW screenshots in GitHub.

**Comment by Sovietico1** [comment]
> El sitio web ya no funciona, el escaneo lo abandonó para pasar a otro (YugenMangas). Hay un sitio "dragontranslation.net" pero el escaneo dice que no es oficial. No sé si la extensión debe ser eliminada.

A mi parecer deberian actualizar la extencion con la nueva URL ya que es muy buena pagina aunque no sea del scan oficial.
