### ISSUE TITLE
Isekaiscans timeout

### ISSUE THREAD

**Issue by SwiftGrim** [tachiyomiorg/tachiyomi-extensions#15318]
### Source information and language

Isekaiscans.com(En) 

### Steps to reproduce

Going through libraries of isekaiscans

### Expected behavior

Loading libraries of isekaiscans

### Actual behavior

Connection timeout 

### Tachiyomi version

0.14.4

### Android version

Android 10

### Other details

![Screenshot_20230212_012225](https://user-images.githubusercontent.com/100683056/218281700-c8072bee-0ef8-4896-86ae-b13f0ffc2ea5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their website is down, there's nothing we can do about it.
