### ISSUE TITLE
[Source Request] mhscans

### ISSUE THREAD

**Issue by lenase0077** [tachiyomiorg/tachiyomi-extensions#15319]
### Source name

mhscans

### Source link

https://mhscans.com/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by OncePunchedMan** [comment]
Proof of ownership provided. Source will not be added

**Comment by OncePunchedMan** [comment]
> I'm the owner of mhscans.com and i would like you to not add the page on tachiyomi, since my website have poor resources since its a new page.
