### ISSUE TITLE
Mangapark v5

### ISSUE THREAD

**Issue by Gumball1980** [tachiyomiorg/tachiyomi-extensions#15310]
### Source name and language

eu.kanade.tachiyomi.extension.all.mangapark

### Describe your suggested feature

This extension should have the support to mangapark v5 new website. Some titles are only in v5 and not in V3.
Also, some chapters are doubled in the site, can you add the support to view both chapters (same you did for mangadex)?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by RakdosOrzohov** [comment]
That's the same problemi I'm having. I switched from MangaPark to MangaPark v3 but there are still no update on the manga on my list. Any chance to have te update to the MangaPark v5 versione?

**Comment by Geired25** [comment]
I have the same problem  there will be any resolution?
