### ISSUE TITLE
Fix this extension

### ISSUE THREAD

**Issue by arfannn88** [tachiyomiorg/tachiyomi-extensions#15322]
### Source information and language

ToonGod 1.4.32 (English)

### Steps to reproduce

Does not working

### Expected behavior

Nothing is showing only loading

### Actual behavior

It should work because it's a good website.

### Tachiyomi version

0.14.4

### Android version

Android 11

### Other details

Make it working again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EarthMan123** [comment]
Solution is quite easy actually.

Just got to Settings -> Advanced -> Default user agent string

and change it with the following 

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by arfannn88** [comment]
Didn't work bro

**Comment by EarthMan123** [comment]
Worked for me.

You shouldn't use Private DNS or DoH

**Comment by vetleledaal** [comment]
Works fine. You need to change your UA to a mobile Chrome User-Agent. https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
