### ISSUE TITLE
Mangapark no results

### ISSUE THREAD

**Issue by LegacyPhil** [tachiyomiorg/tachiyomi-extensions#15335]
### Source information and language

Mangapark 1.4.23

### Steps to reproduce

Just click on the mangapark extension

### Expected behavior

Should be able to browse normally

### Actual behavior

Most of the time says no results even when only on the popular section. Half of the manga connected to it says no chapter

### Tachiyomi version

0.14.4

### Android version

S20 +

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed by #16215
