### ISSUE TITLE
Olympus Scan: Changed their domain and theme

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#15330]
### Source information and language

Olympus scan 1.4.28 (español)

### Source new URL

https://olympusscans.com/

### Other details

Traspaso de pagina, ahora van a subir los manhwas en otra página

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Lightdennn** [comment]
pls change url

**Comment by ElAguZWe** [comment]
Change url pls :(
