### ISSUE TITLE
Please add babelwuxia.com

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#15337]
### Source name

Babel Wuxia

### Source link

babelwuxia.com

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by FaTe-code** [comment]
I second this, please add babel wuxia.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
