### ISSUE TITLE
HentaiKai

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#15349]
### Source name

HentaiKai

### Source link

https://hentaikai.com/

### Language

Português (Brasil)

### Other details

This font can already go back to being an extension, it has been months without obfuscating the chapter URLs and it doesn't look like it will happen again.

Note: there are some manga with several chapters and others with only 1, if you can also make the reader consider this.

Site 18+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
False close?

**Comment by scb261** [comment]
Not false close, it just wasn't added to the list of removed sources 
#9999
#11887

**Comment by alessandrojean** [comment]
Added to the removed list in #15355
