### ISSUE TITLE
Realm scans

### ISSUE THREAD

**Issue by Lharci** [tachiyomiorg/tachiyomi-extensions#15343]
### Source information and language

Realmscans

### Steps to reproduce

Tap on browse.
Go to sources.
Click on an extension to display manhwa/manhua/manga info to add to library or just browse through them 

### Expected behavior

When you open an installed extension, you can usually browse to see and maybe add new/existing manhwa/manhua/manga to your library. 

### Actual behavior

But for some time now, realmscans doesn't show that, instead, it shows this message: "Failed to bypass Cloudfare".
It can only be used via webview

### Tachiyomi version

0.14.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SystemOdmin** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15301#issuecomment-1427100008
