### ISSUE TITLE
Thumbnail for some manga not loading

### ISSUE THREAD

**Issue by Morse069** [tachiyomiorg/tachiyomi-extensions#15342]
### Source information and language

Myreadingmanga 1.4.46   Mangabuddy 1.3.13

### Steps to reproduce

First step open the said extension
Second step scroll down and some manga entries doesn't load the cover

### Expected behavior

Thumbnail must load to all entries

### Actual behavior

![IMG_20230213_200209](https://user-images.githubusercontent.com/121346796/218454265-3bf27527-3c5e-4190-8a00-3ae1f48c8af0.jpg)
![IMG_20230213_200215](https://user-images.githubusercontent.com/121346796/218454271-8d9902db-460f-467d-b301-1166d059f2b7.jpg)

### Tachiyomi version

0.14.0

### Android version

Android 10

### Other details

Even if you try to refresh it in the entry it doesn't load outside
I tried the guide it doesn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do open one issue per source, otherwise it keeps difficult to track what's already fixed and what's not.
