### ISSUE TITLE
Manhwa-Latino no muestra paginas

### ISSUE THREAD

**Issue by Sovietico1** [tachiyomiorg/tachiyomi-extensions#15356]
### Source information and language

Manhwa-Latino 1.4.22 (español)

### Steps to reproduce

1.abrir la extension Manhwa-Latino
2. seleccionar cualquier manhwa o manga
3. abrir capitulo

### Expected behavior

Deberia mostrar las paginas de los capitulo

### Actual behavior

No muestra las paginas de ningun capitulo

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seew3l** [comment]
The page now splits the images into 2x2. I'm not sure if the app supports these cases

**Comment by Sovietico1** [comment]
¿Que procede en estos casos?
