### ISSUE TITLE
Zinchan manga nx domain

### ISSUE THREAD

**Issue by hatimurni** [tachiyomiorg/tachiyomi-extensions#15368]
### Source information and language

Zinchan manga

### Steps to reproduce

Update it via mass update and opened it manually

### Expected behavior

Manga should be updated, 

### Actual behavior

But instead it always failed to open, it said nx domain, but when open it via webview it can be opened

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by aomicat** [comment]
#15276
