### ISSUE TITLE
New Isekaiscan 

### ISSUE THREAD

**Issue by Deemillion10** [tachiyomiorg/tachiyomi-extensions#15374]
### Source name

Isekaiscans

### Source link

http://isekaiscan.top/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by noornee** [comment]
came here to create an issue concerning this and I'm glad it's here.
the extension keeps timing out cos the site is down (the one with [.com](isekaiscan.com) domain name)

**Comment by livinstun** [comment]
is http://isekaiscan.top/ and http://isekaiscan.com/ the same or is it an entirely different site?

**Comment by livinstun** [comment]
https://www.patreon.com/IsekaiScan
i have read on their patreon site that they are moving to the new site.
