### ISSUE TITLE
Mangafire.to

### ISSUE THREAD

**Issue by SrCrono** [tachiyomiorg/tachiyomi-extensions#15370]
### Source name

MangaFire.to

### Source link

https://mangafire.to/home

### Language

Multi language

### Other details

Have 18+/NSFW

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by grphine** [comment]
how long ago was mangafire released? I only came across it today and then found this source request lol

**Comment by reremer** [comment]
wow so many request.. i was just about to

**Comment by Helpful-Neko** [comment]
I wanna have this source added too 😸

**Comment by SGthecoder** [comment]
Please add mangafire
