### ISSUE TITLE
Extension won't update

### ISSUE THREAD

**Issue by AnimeDroid8** [tachiyomiorg/tachiyomi-extensions#15378]
### Source information and language

All extensions

### Steps to reproduce

When I open the app it shows I need to update ally my downloaded extension. 
1. I press update it downloads and nothing happens
2. I deleted a extension by mistakes and try to re download it but it won't. 
3. Any and all extension is the same it shows a download icen than nothing happens.

### Expected behavior

When I press update or install on any extension it should download and than update and install or download and install. 

### Actual behavior

When I press update or install nothing happens. 

### Tachiyomi version

0.14.4

### Android version

Android 10

### Other details

It was ok until last week this happened suddenly. I didn't want to report it as it only prevented me from updating . it didn't have much effect than but now one of my main extension got deleted by mistake. I really need help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
