### ISSUE TITLE
Chochox request 

### ISSUE THREAD

**Issue by Legion0017** [tachiyomiorg/tachiyomi-extensions#15371]
### Source name and language

https://chochox.com

### Describe your suggested feature

I would love to have this extension to be able to download and have more comics available 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the source request form instead, this isn't the proper one for this case.
