### ISSUE TITLE
关于禁漫天堂插件更改网址源建议

### ISSUE THREAD

**Issue by aizaimosaou** [tachiyomiorg/tachiyomi-extensions#15377]
### Source name and language

禁漫天堂（jinmam tiantang）

### Describe your suggested feature

问题:它可以在设置中更改网址域名，但有时网址域名变动速度很快，现有的域名并不是特别好用

建议:希望可以增加一个可自定义网址域名的功能，可以方便用户自行在漫画源插件的基础上，手动解决一些问题

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Isn't that already possible under the extension settings? "使用镜像网址"
TL: 这在扩展设置中不是已经可以做到了吗？"使用镜像网址"

**Comment by aizaimosaou** [comment]
镜像网址是有的，但该网站网址变动比较频繁，国内线路已经失效了。
然后想着反馈，再等提交后，可能过段时间又失效了。所以才希望添加，改插件的自定义的网址源。

如果该建议还需要考虑的话，希望可以先添加https://jmcomic1.group这个国内线路



这个是目前最新的禁漫天堂的国内线路
