### ISSUE TITLE
komiklab status Not known

### ISSUE THREAD

**Issue by Start38** [tachiyomiorg/tachiyomi-extensions#15375]
### Source information and language

komiklab 1.4.25 Indonesia

### Steps to reproduce

1. open comiclab extension
2. Choose a comic
3. comics do not show status and synopsis

### Expected behavior

It should Show status and synopsis

### Actual behavior

Does not show status and synopsis

### Tachiyomi version

0.14.4

### Android version

11

### Other details

![Screenshot_2023_0216_230446](https://user-images.githubusercontent.com/120931895/219422921-e4bfdf36-2ab9-4fa5-a072-eaa5fd6b3f7e.jpg)

![IMG_20230220_133814](https://user-images.githubusercontent.com/120931895/220031910-9f40f61a-b709-46cf-b231-727fb655ad44.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Start38** [comment]
when will this be fixed

**Comment by Start38** [comment]
![Uploading IMG_20230220_133814.jpg…]()

**Comment by TheKingTermux** [comment]
There is no ETA
