### ISSUE TITLE
Extension:Gelbooru

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi-extensions#15392]
### Source name

Gelbooru 

### Source link

https://gelbooru.com/index.php?page=post&s=list&tags=all

### Language

En

### Other details

It's just like pixiv collection of many Photos
18/NSFW images also there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
I don't think an image board is really fit for a comic reading app...so each image will be a manga with a single chapter and a single page?

**Comment by alessandrojean** [comment]
Yeah, besides that it's way out of the purpose of the app, so closing it.
