### ISSUE TITLE
Reaperscan id 

### ISSUE THREAD

**Issue by Start38** [tachiyomiorg/tachiyomi-extensions#15404]
### Source information and language

Reaperscan id 1.4.39 Indonesian

### Source new URL

https://shinigami.id/

### Other details

change of display extension and url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by libran07** [comment]
Fyi, I don't think they are part of reaperscan anymore, so not only the domain has changed but the source name should also be changed.
