### ISSUE TITLE
Reaper Scans (ID): changed their domain and name to shinigami.id

### ISSUE THREAD

**Issue by Bambang023** [tachiyomiorg/tachiyomi-extensions#15408]
### Source information and language

Reaper Scans 1.4.39 (Multi) 

### Source new URL

https://shinigami.id/

### Other details

Reaper Scans change url and name

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by FathiRaihan** [comment]
Apakah akan lama pengerjaannya? Hehehe just asking

**Comment by AccXyzAinz** [comment]
🥳
