### ISSUE TITLE
Baozi Manhua Slow page loading

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#15401]
### Source information and language

Zh.baozimh.org 1.4.18 (中文）

### Steps to reproduce

Download and loading for manhua in baozimh is very slow. I have check that it is not my wifi speed that is causing it. 

### Expected behavior

I don't know if it was the website that is slow or the app itself. 

But i read on the website itself is smooth and fast loading. But when i come back to tachiyomi, the loading take ages to load.

### Actual behavior

Idk if agent string will affect the loading speed but please provide me a solution thx.

### Tachiyomi version

0.14.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Closing as stale.
