### ISSUE TITLE
teamx

### ISSUE THREAD

**Issue by blacky136** [tachiyomiorg/tachiyomi-extensions#15422]
### Source link

https://team1x1.fun/

### Other details

I'm owner of teamx and I want to remove my website from you app tachiyomi since it drop my profit.
I'm using google adense and you can check by yourself.

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by blacky136** [comment]
you can check our mark here. [https://ibb.co/MZ3jCvv](url)
and login in the chapters and you will find.
another proof: [https://mangalek.com/manga/apotheosis/1035/](url) that the stolen one.
the orginal one: [https://team1x1.fun/series/apotheosis/1035](url) you can see the our mark here.

**Comment by scb261** [comment]
Even if someone stole from you, it still doesn't disprove that you steal from others (again, see #14783)

**Comment by petanon** [comment]
teamx owner let us use your site from this app to download chapters or make a way to download from your site and create a android app for us
