### ISSUE TITLE
KomikIndoID Change Link Address so the old ip was broken

### ISSUE THREAD

**Issue by Ardo25** [tachiyomiorg/tachiyomi-extensions#15425]
### Source information and language

KomikIndoID (Indonesia)

### Source new URL

https://komikindo.pro/

### Other details

****
![Screenshot_20230221_081827](https://user-images.githubusercontent.com/125936428/220225165-5de7b934-7521-438d-8821-6e2365f5fcff.jpg)
![Screenshot_20230221_081836](https://user-images.githubusercontent.com/125936428/220225190-e7a63423-4bbf-454a-b95e-6602ebf0a83e.jpg)
![Screenshot_20230221_081919](https://user-images.githubusercontent.com/125936428/220225199-7c677003-79cd-4207-9fe5-97dff3bfa04f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Ardo25** [comment]
my all favourite comic are there but i can't open and know the new chapter because the tachiyomi komiindoid broken :(

**Comment by telesia66** [comment]
anjinglah kaga di notice notice ni ganti url
