### ISSUE TITLE
Nhentai Cloudflare Bypass Issue

### ISSUE THREAD

**Issue by j-meme** [tachiyomiorg/tachiyomi-extensions#15428]
### Source information and language

Nhentai 1.4.36

### Steps to reproduce

1. Open any source, saved or not
2. Also does not load the source library

### Expected behavior

Should load fine, was working a week ago and has stopped since.

### Actual behavior

Always get Cloudflare bypass issue

### Tachiyomi version

0.14.5

### Android version

Android 10

### Other details

This is NOT a temporary IP ban, I have tested this on two devices on 2 seperate networks with the same result.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the "Solving Cloudflare issues" section and the two consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try changing the user agent string by following the link below, but this is a last measure, if it doesn't work, migrate to other sources or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
