### ISSUE TITLE
[Manga Plus] dealing with the constant changing of available chapters

### ISSUE THREAD

**Issue by Noriller** [tachiyomiorg/tachiyomi-extensions#15435]
### Source name and language

Manga Plus by Shueisha

### Describe your suggested feature

Not sure if possible, but to keep track of read chapters even when they are not available to read.

In this case it could show the chapter was read, but that it's not available at the moment.

It could save only the read and/or downloaded chapters, but if you delete and mark unread it could "disappear", then when it's available again, it download fresh.

### Other details

Every time they change the available chapters I get dozens or hundreds of new chapters to download.

New chapters are something else, but already-read chapters are annoying.

This way I don't have to mind just the available changes of chapters I've read and don't want to again, but can still get new ones or clean those I want to download and read again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's nothing we can do as when they add these chapters again they change their IDs and URLs so Tachi detects them as newer chapters. Not something the extension and neither the app can fix it.
