### ISSUE TITLE
RavenScans update

### ISSUE THREAD

**Issue by zenyman1992** [tachiyomiorg/tachiyomi-extensions#15433]
### Source name

RavenScans

### Source link

https://ravenscans.com

### Language

English

### Other details

the current RavenScans extension is using old site, can you please update it to the new site. thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [x] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
