### ISSUE TITLE
Nana : No page Found 

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi-extensions#15445]
### Source information and language

Nana 1.4.2 English 

### Steps to reproduce

Some entry shows error like No page Found while in webview they are present 

### Expected behavior

Some manga should open like other but it shows error like no page found

### Actual behavior

It's shows error like this for some entry not all

  

### Tachiyomi version

0.14.5

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Solovertical** [comment]
If video not playing well 
https://user-images.githubusercontent.com/109901807/220545876-f7e67872-ea90-474a-9a39-889ea12dcc12.mp4

**Comment by CarlosEsco** [comment]
@Solovertical don't post NSFW content
