### ISSUE TITLE
Remove ReaperScans

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#15440]
### Source link

https://reaperscans.id/

### Other details

ReaperScans has been acquired by a sponsor, therefore they changed the domain, which is where the source extension is no longer useful

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by arkon** [comment]
Duplicate of #15408
