### ISSUE TITLE
JinmanTiantang1.4.34 picture lost

### ISSUE THREAD

**Issue by YuGhi-bug** [tachiyomiorg/tachiyomi-extensions#15454]
### Source information and language

JinmanTiantang1.4.34 chinese

### Steps to reproduce

1.JinmanTiantang
2.魯蛇的多重宇宙-第12話
3.open

### Expected behavior

![image](https://user-images.githubusercontent.com/65033074/220896831-8b1f297e-40ee-4a89-9e03-ce561f30b0d5.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/65033074/220895348-3a2839d0-46c1-479c-bbbf-76ee219d8f22.png)
![image](https://user-images.githubusercontent.com/65033074/220899569-817bbedf-a906-4783-9fe5-996a22fdc2ad.png)
![image](https://user-images.githubusercontent.com/65033074/220899641-9c515185-a756-4564-a4cd-d051b8c1b4fb.png)

### Tachiyomi version

0.14.5

### Android version

android 12

### Other details

sometime clean up cache can fixed
website open is normal

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
I cleaned up some code in #15838 so this will **_probably_** be fixed.

If it still happens after the update, comment here to let me know.
