### ISSUE TITLE
add extension Shinigami ID

### ISSUE THREAD

**Issue by dzaeqy** [tachiyomiorg/tachiyomi-extensions#15453]
### Source name

Shinigami ID

### Source link

https://shinigami.id/

### Language

Indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#15408

**Comment by kolinrno** [comment]
> ### Nama asal
> Identitas Shinigami
> 
> ### Tautan sumber
> https://shinigami.id/
> 
> ### Bahasa
> Indonesia
> 
> ### Detail lainnya
> _Tidak ada respon_
> 
> ### Terima kasih
> * [x] Saya telah mencari masalah yang ada dan ini adalah tiket baru, **BUKAN** duplikat atau terkait dengan masalah terbuka atau tertutup lainnya.
> * [x] Saya telah menulis judul dengan nama sumber.
> * [x] Saya telah memeriksa bahwa ekstensi tersebut belum ada di [daftar ekstensi situs web](https://tachiyomi.org/extensions/) atau aplikasi.
> * [x] Saya telah memeriksa bahwa ekstensi tersebut belum ada dengan mencari di [repositori GitHub](https://github.com/tachiyomiorg/tachiyomi-extensions/) dan memverifikasi bahwa ekstensi tersebut tidak muncul di basis kode.
> * [x] Saya akan mengisi semua informasi yang diminta dalam formulir ini.

haha pake kotatsu aja gan
