### ISSUE TITLE
Katakomik

### ISSUE THREAD

**Issue by libran07** [tachiyomiorg/tachiyomi-extensions#15455]
### Source name

Katakomik

### Source link

https://katakomik.online/

### Language

Indonesian

### Other details

18+/NSFW = no

![katakomik](https://user-images.githubusercontent.com/90138720/220900231-b28839e8-d77c-429c-93d7-745e5068f91d.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
