### ISSUE TITLE
Komga and Kavita duplicate three when I search

### ISSUE THREAD

**Issue by sdvina** [tachiyomiorg/tachiyomi-extensions#15452]
### Source information and language

Komga 1.4.45 (Multi) Kavita 1.4.9 (Multi)

### Steps to reproduce

![微信图片_20230223120548](https://user-images.githubusercontent.com/10064158/220819172-6d37f6c2-3024-4cbd-9d0d-24425277bf74.jpg)
![微信图片_20230223120531](https://user-images.githubusercontent.com/10064158/220819179-7ac8d42b-5f19-48fc-9846-bfab65bba2b0.jpg)

### Expected behavior

display one

### Actual behavior

display three

### Tachiyomi version

0.14.5

### Android version

Android 12

### Other details

![微信图片_20230223120553](https://user-images.githubusercontent.com/10064158/220819387-50bcafe5-dfa8-4de1-8c8b-9dccb9fb60ff.jpg)
![微信图片_20230223120558](https://user-images.githubusercontent.com/10064158/220819395-fc471205-5be1-4d06-b612-ca36be7516bb.jpg)
![微信图片_20230223121240](https://user-images.githubusercontent.com/10064158/220819811-0b2a094f-cb79-42ab-9238-2e0ada91bdae.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
its for when you have multiple komga or kavita servers you want to connect to. You can filter them out so it only shows one.
