### ISSUE TITLE
Mirai Scans

### ISSUE THREAD

**Issue by libran07** [tachiyomiorg/tachiyomi-extensions#15458]
### Source name

Mirai Scans

### Source link

https://miraiscans.com/

### Language

Indonesian

### Other details

18+/NSFW = no

![MiraiScans01](https://user-images.githubusercontent.com/90138720/221059631-4190941c-d00e-4708-b491-3dde9d35b676.jpeg)

![MiraiScans02](https://user-images.githubusercontent.com/90138720/221059673-868453de-60b9-47b9-a1f8-0c3778fb03d6.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
