### ISSUE TITLE
Shinigami.id

### ISSUE THREAD

**Issue by Bubik111** [tachiyomiorg/tachiyomi-extensions#15450]
### Source name

Shinigami

### Source link

https://shinigami.id

### Language

Bahasa Indonesia

### Other details

Reaperscans.id is not part of the reaperscans now, they got sponsored by someone and change the url to shinigami.id

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Bubik111** [comment]
Umm.. sorry i dont see other people opens a issue too.

**Comment by kataceking** [comment]
> Umm.. sorry i dont see other people opens a issue too.

Does that mean reaperscan not get an existension update?
