### ISSUE TITLE
MangaFox Not loading

### ISSUE THREAD

**Issue by ENDvious** [tachiyomiorg/tachiyomi-extensions#15469]
### Source information and language

MangaFox 1.4.6 (EN)

### Steps to reproduce

Open any MangaFox Chapter

### Expected behavior

Chapter loads

### Actual behavior

Chapter fails to load, Empty error message pops up

### Tachiyomi version

0.14.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
> i did some digging it seems that pages or images load a little differently on the mobile version of mangafox .theres no chapterfun script
> 
> but instead we can load the whole chapter on this url
> https://m.fanfox.net/roll_manga/ooyukiumi_no_kaina/c002/
>  
> edit:
> oh upon checking the source again it seems it was there or still there
> i think more likely the last two commits did made the extensions not work or either manga fox did some minor changes which makes only unintentionally made tachiyomi to fail but not other apps with old updates like mangadlr or hakuneko
> old build of the extension seems to throw an error related to jsoup null something  and newer build with the same version seems just shows loading then back to chapterlist as i tested on a wsa instance on a physical phone it shows a blank error
> 
> ill try to test the initial build of mangafox extentsion before feb 8
> 
> @beerpiss
> 
> 
> 

there was a packed script that contained the chapter URLs at one point, then mangafox mobile changed back to their old reader

you probably just need to revert my recent commit on the source
