### ISSUE TITLE
help I guess??? I'm not even sure what type of issue I should make this

### ISSUE THREAD

**Issue by omega7pro** [tachiyomiorg/tachiyomi-extensions#15462]
### Source information and language

everything 

### Steps to reproduce

I'll be really brief with this to not waste too much time. Due to the 0.14.x updates hating every device I have, I'm going to revert to the 0.13.6 version of tachiyomi, which actually works as intended on my device. The problem I have is the fact my stupid butt didn't think things through and updated every extension (about 8 total) that I use. However, because of my stupidity, I can not longer revert to 0.13.6 as the extensions are no longer recognized and no longer open any item in my library. However, I cannot return to any 0.14.x update (as all are broken on my end). So, my question is this: is there a place I can go to to get extensions that work on 0.13.6 while being as "new" as possible?

### Expected behavior

Not sure what to put here to be honest.

### Actual behavior

Not sure what to put here either.

### Tachiyomi version

0.14.5

### Android version

Android 11 on tablet, Android 12 on phone

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
We don't provide support for outdated versions of the app and/or extensions. If you have an issue - you can report the actual issue instead of asking for an outdated version.
