### ISSUE TITLE
Manhwa18.net: Extension broken

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi-extensions#15460]
### Source information and language

Manhwa18.net 1.4.8 (English)

### Steps to reproduce

1. Open browse

### Expected behavior

Entries load normally

### Actual behavior

HTTP error 404: Check website in WebView 

Website loads in webview, but not in app

### Tachiyomi version

0.14.5

### Android version

Android 13

### Other details

Entries pages URL appear to have changed

Previous: https://manhwa18.net/manga-queen-bee-acera.html

Current: https://manhwa18.net/manga/queen-bee-manhwa

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AKIRA4175** [comment]
is:open label:Bug
