### ISSUE TITLE
Unable to see chapters of a particular Manga. 

### ISSUE THREAD

**Issue by Beech0408** [tachiyomiorg/tachiyomi-extensions#15478]
### Source information and language

Mangabuddy 1.4.13

### Steps to reproduce

I tried to read a Manga from mangabuddy, so I went straight to the Mangabuddy extension in Sources. I checked for the Manga, it was there, but Please help

### Expected behavior

It was supposed to show me the Manga's chapters. 

### Actual behavior

Whenever I click on it, a long error message always pops up and I found out that the number chapters of the Manga is zero. I checked the Manga while using Webview and it is normal. I attached a screenshot of the pop-up message. 
![Screenshot_20230225-163351](https://user-images.githubusercontent.com/118119005/221366526-afe9d7ad-0ff1-4131-8e35-a015f1f5d8c2.png)

### Tachiyomi version

Tachiyomi SY version  stable 1.9.0

### Android version

8.1.0

### Other details

I await your reply. Thank you in advance. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#15474
