### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by fatmaarini** [tachiyomiorg/tachiyomi-extensions#15471]
### Source information and language

Bato.to

### Steps to reproduce

ERR_CONNECTION_RESET

### Expected behavior

Aku berharap bisa kembali seperti semula 

### Actual behavior

ERR_CONNECTION_RESET

### Tachiyomi version

0.14.4

### Android version

Android 9

### Other details

ERR_CONNECTION_RESET 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fatmaarini** [comment]
Yang tau tolong beritahu 🙏

**Comment by curche** [comment]
>  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

Did you try the troubleshooting guide? Because the err_connection_reset sounds like your internet service provider is creating issues
Which can be solved by changing to DNS over HTTPS, or using a VPN
