### ISSUE TITLE
Mangabuddy 502 Bad Gateway

### ISSUE THREAD

**Issue by raziel100** [tachiyomiorg/tachiyomi-extensions#15474]
### Source information and language

Mangabuddy 1.4.13

### Steps to reproduce

1. Enter extension
2. Get any manga in the list
3. Try to update chapter list

### Expected behavior

The chapter list should be updated

### Actual behavior

It's getter a json error and because of that is not updating the list
![Screenshot_20230225-085218_Tachiyomi](https://user-images.githubusercontent.com/11368528/221355375-3511e65a-9f00-43f8-9967-83dcdd539741.jpg)

### Tachiyomi version

App version: 0.14.5-5563 & App version: 1.6.2 Tachiyomi j2k

### Android version

Android 11

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by XY0511** [comment]
I guess this isn't "just me" problem.

**Comment by DchanN** [comment]
Maybe this issue can be closed, can't reproduce the error



https://user-images.githubusercontent.com/101858971/223454858-aecc2621-4d60-4243-a4af-7703f09e0061.mp4
