### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by briantgosling** [tachiyomiorg/tachiyomi-extensions#15486]
### Source name and language

hentaiera.com

### Describe your suggested feature

pls add it Hentaiera.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
use the right template next time, but #12904
