### ISSUE TITLE
Useragent issue "No pages found"

### ISSUE THREAD

**Issue by Yato0226** [tachiyomiorg/tachiyomi-extensions#15489]
### Source information and language

Asura Scans 1.4.42

### Steps to reproduce

1. Change the default useragent to android useragent
2. Restart the app
3. Find any series in asurascan extension and read any chapter (Idk if there's other extension experiencing this)
4. It's gonna have an error "No pages found"

(I think it's just the useragent is not latest that's why it's broken but just Idk anything about that at all I'm only using useragent because I found out that the default useragent is consuming too much data)

### Expected behavior

It's going to be able to found any pages in chapter

### Actual behavior

Having an error "No pages found"

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RazredgeBR** [comment]
I can confirm the same error, even trying with multiple different user agent strings (Chrome, Opera and Firefox), all had the same problem.

App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.F721BXXS1BWA2
Device brand: samsung
Device manufacturer: samsung
Device name: b4q
Device model: SM-F721B
Device product name: b4qxxx
