### ISSUE TITLE
Vex Manga : Only one page appears from the chapter

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#15485]
### Source information and language

Vex Manga 1.4.24 (Arabic)

### Steps to reproduce

1- Access to the source
2- Open manga
3-Chapter open
4-Only one page appears

### Expected behavior

The entire chapter must appear

### Actual behavior

Only one page of the chapter appears

### Tachiyomi version

0.14.5

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/87826849/221395124-6dd9c39f-4eaf-4745-a7bf-5a123f62ce2d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Doo77m** [comment]
ممكن رابط الاضافة لو تكرمت

**Comment by stevenyomi** [comment]
This source does not exist yet.

**Comment by stevenyomi** [comment]
@yemenihandsome Warning: Next time you do the following things you will be blocked:

- Reporting false app version (obviously you're using SY instead of main Tachi 0.14.x)
- Posting comment in other issues/PRs begging for sources to be added
- Reporting issues about or caused by unofficial extensions
