### ISSUE TITLE
Olympus 

### ISSUE THREAD

**Issue by JACKMONST** [tachiyomiorg/tachiyomi-extensions#15481]
### Source information and language

Olympus Scanlation 1.4.28

### Source new URL

https://olympusscans.com

### Other details

Se ha cambiado la pagina 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate of #15330
