### ISSUE TITLE
Comickfun Null

### ISSUE THREAD

**Issue by FabledSword** [tachiyomiorg/tachiyomi-extensions#15500]
### Source information and language

all.comickfun 1.4.20

### Steps to reproduce

1. Update library
2. Wait extended period of time for library to update
3. Update states that multiple updates failed

### Expected behavior

The chapter should be showing no failed updates when library update is concluded after 2 minutes to update the library

### Actual behavior

Wait for 10 minutes for update and receive all stories on comick to have failed due to nullpointerexception: null

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment]
This most likely occurred when they were migrating their database. The issue can be closed for now. 

However, if the issue persists with the latest version of the extension, please mention the name of the series in which it occurs.
