### ISSUE TITLE
Olympus Scanlation changed URL

### ISSUE THREAD

**Issue by ElAguZWe** [tachiyomiorg/tachiyomi-extensions#15506]
### Source information and language

Olympus Scanlation (Spanish) 1.4.28

### Source new URL

https://olympusscans.com/

### Other details

They replaced the old page with a new one, just like the URL.

The problem is recent (more than two weeks ago), until yesterday when I was reading quietly and today they made a total change to their page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#15330
