### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by briantgosling** [tachiyomiorg/tachiyomi-extensions#15501]
### Source information and language

Nhentai

### Steps to reproduce

The Nhentai extension keeps on loading despite me having a good internet 

### Expected behavior

It should be fast just like the website version 

### Actual behavior

it is so slow 

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We don't have any control over the source speed. Try the troubleshooting guide and if it doesn't help ask for additional help on our Discord server.

https://tachiyomi.org/help/guides/troubleshooting/
