### ISSUE TITLE
The images are too tall in Baozi ManHua

### ISSUE THREAD

**Issue by Nachogao** [tachiyomiorg/tachiyomi-extensions#15514]
### Source information and language

Baozi Manhua 1.4.18 (Chinese)

### Steps to reproduce

1. Open any manga of this extension. 
2. For example "斗罗大陆2" chapter 363.

### Expected behavior

There will appear a standard image with the correct proportions.
Like this:
![1677542092501](https://user-images.githubusercontent.com/64711160/221716254-01fdaa57-f64d-4471-9898-4f514f5c2f5f.jpg)

### Actual behavior

An image stretched image.
Like this:
![1677542092486](https://user-images.githubusercontent.com/64711160/221716289-8f5c33ea-a567-4848-ac65-7de957de718f.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

It looks begins today, I hadn't seen it yesterday.
If I watch it in WebView, It is in standard proportions.
It looks like they have stretched the image and changed it on the page to standard proportions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
change your scale type in the reader options probably.
