### ISSUE TITLE
Reaper Scans (Spanish)

### ISSUE THREAD

**Issue by JTwyla** [tachiyomiorg/tachiyomi-extensions#15518]
### Source name

Reaper Scan

### Source link

https://reaperscanes.xyz/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Lenoyr** [comment]
The site died, they moved to 'LegionAsia,' which was later renamed to 'mhscans' as well.

**Comment by bapeey** [comment]
The site changed its name to "MHScans", which will not be added due to the owner's request. #15319
