### ISSUE TITLE
Dushimh

### ISSUE THREAD

**Issue by PayLater666** [tachiyomiorg/tachiyomi-extensions#15521]
### Source name

Dushimh

### Source link

https://www.dushimh.com

### Language

China

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site doesn't seem to work
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/13540478/8cbcb2bb-1108-4b50-a292-9d6de65b14cc)
https://app.21cloudbox.com/reachability-test/0d43dab3-1719-40f4-95ce-3fbd42241713/
