### ISSUE TITLE
Downloads keep getting timeout on the mangakakalot extension 

### ISSUE THREAD

**Issue by Ayush62** [tachiyomiorg/tachiyomi-extensions#15523]
### Source information and language

mangakakalot 1.4.8 English

### Steps to reproduce

i select a series form the mangakakalot extension and press on download.

### Expected behavior

all the chapters should download and within a day.

### Actual behavior

the download times out the whole time and after 5 days is still not downloaded.

### Tachiyomi version

0.14.5

### Android version

13 (SDK 33)

### Other details

it's only on this extension. the other extensions work with out any problem even when i am download around a 100 chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
they change links to their images often and temp ban people who try to download a lot which would stop tachi from completing the download, you're better off using another source.
