### ISSUE TITLE
Manhwas net error 403

### ISSUE THREAD

**Issue by Myztery97** [tachiyomiorg/tachiyomi-extensions#15536]
### Source information and language

Manhwas net 1.4.5

### Steps to reproduce

When Open the extension it show a message error HTTP Error 403.

### Expected behavior

When Open the extension it'd show the list of series 

### Actual behavior

It show the error 403

### Tachiyomi version

Tachiyomi 0.14.5 stable 

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Try the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/), especially the Cloudflare section. If it doesn't help, there's anything else you can do, migrate to other sources or wait until they lower their protection.
