### ISSUE TITLE
Mangabuddy giving Error 522

### ISSUE THREAD

**Issue by Imnewhere12** [tachiyomiorg/tachiyomi-extensions#15537]
### Source information and language

Mangabuddy 1.4.13

### Steps to reproduce

1. Clicking on manga chapter in library doesn't load chapter.

### Expected behavior

Reading from source should load no problem and be viewable.

### Actual behavior

When trying to pull chapter a 522 error is given Instead.

### Tachiyomi version

App version: 0.14.5 

### Android version

Android 13

### Other details

It looks like the URL has changed when using Google to pull up main site it gives a https://mangabuddy.com/official url however on that page it shows no manga but shows a click to go to homepage button clicking that brings you to https://mangabuddy.com/home where all the manga is located and can be read no problem.   

![Screenshot_20230301_102227_Samsung Internet](https://user-images.githubusercontent.com/122816969/222200423-7780c0dc-cc8c-426a-8972-1679d57fcac8.jpg)

![Screenshot_20230301_102406_Samsung Internet](https://user-images.githubusercontent.com/122816969/222200459-730dfc60-f528-4f56-803e-bf4dad2211d5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 5xx errors are server side and can't be fixed on the extension side, you're likely seeing a cache on the browser. Wait until they fix it.
