### ISSUE TITLE
Reaper Scans (English): Add option to use random latest user-agent

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#15539]
### Source name and language

Reaper Scan

### Describe your suggested feature

Please add custom user agent for the following extension that require desktop user agent like Asura scan

### Other details

![Screenshot_2023-02-26-01-25-07-22](https://user-images.githubusercontent.com/79831076/222205190-67542f6a-fb57-457e-964c-26033f18c8bc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
#15513

**Comment by alessandrojean** [comment]
Please specify which Reaper Scans instance as well, as there's a lot of languages they have sites and each one uses a different theme, hence they're different and separate extensions.

**Comment by conztanz045** [comment]
> Please specify which Reaper Scans instance as well, as there's a lot of languages they have sites and each one uses a different theme, hence they're different and separate extensions.

Sorry i dont get you there is only one reaper scan(EN)?

**Comment by alessandrojean** [comment]
There is not...? There's a Brazilian, a multi-lang, and the English one.

But well, you made it clear it was about the English one now.

**Comment by conztanz045** [comment]
> There is not...? There's a Brazilian, a multi-lang, and the English one.
> 
> But well, you made it clear it was about the English one now.

Thanks
