### ISSUE TITLE
MangaNyaa

### ISSUE THREAD

**Issue by SrCrono** [tachiyomiorg/tachiyomi-extensions#15545]
### Source name

MangaNyaa

### Source link

https://manganyaa.com

### Language

Multi language

### Other details

contains English, Spanish and brazilian portuguese and changing the language of the site also changes the manga list to the selected language

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by SrCrono** [comment]
sorry for that request, i forgot to check before

**Comment by alessandrojean** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9379#issuecomment-936659447
