### ISSUE TITLE
Vocês podem botar o neox scan?

### ISSUE THREAD

**Issue by Seilllla** [tachiyomiorg/tachiyomi-extensions#15555]
### Source name and language

Português (Brasil)

### Describe your suggested feature

Uma scan nova

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Besides the fact that Neox will not be added back, this isn't the right issue form to fill to ask to new sources to be added. Please pay attention to this as well in next usages.
