### ISSUE TITLE
Mi Optimization messed up Extensions

### ISSUE THREAD

**Issue by XeeK6** [tachiyomiorg/tachiyomi-extensions#15556]
### Source information and language

None of the extensions are installed after prompt a loading bar appears and install option reappears

### Steps to reproduce

Mobile: Mi Mix 2s
Was previously using Tachiyomi
Turned off Mi optimization and extensions stopped working and could not be installed anymore
Tried to reinstall app many times problem does not go away

### Expected behavior

Install prompt should appear on phone and extension should be installed 

### Actual behavior

No install prompt not even asking unknown source permission after reinstalling of Tachiyomi app

### Tachiyomi version

0.14.5

### Android version

Mi Ui 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
