### ISSUE TITLE
YugenMangas - The search function does not work well

### ISSUE THREAD

**Issue by JhulShock** [tachiyomiorg/tachiyomi-extensions#15552]
### Source information and language

YugenMangas 1.4.11 (Spanish)

### Steps to reproduce

1. Use the search function of the extension
2. Enter the name of the manhwa
3. No manhwa appears

The same thing happens when you try to migrate the manhwa, the extension does not find its own manhwa

![WhatsApp Image 2023-03-02 at 12 11 05 AM](https://user-images.githubusercontent.com/21696690/222337085-6d423680-d371-4295-b523-109fb8e212c5.jpeg)![WhatsApp Image 2023-03-02 at 12 12 30 AM](https://user-images.githubusercontent.com/21696690/222337063-c16b387a-91a7-4fa5-86ab-ba58f086c983.jpeg)
![WhatsApp Image 2023-03-02 at 12 11 08 AM](https://user-images.githubusercontent.com/21696690/222337077-f2f70e38-86db-455f-9843-edaee05d78ca.jpeg)

### Expected behavior

1. Use the search function of the extension
2. Enter the name of the manhwa
3. Show the manhwa related to the entered words

### Actual behavior

Can't find the manhwa you want, even though it's in the library

### Tachiyomi version

0.14.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
can you find it on the website using the same search term?

**Comment by Seishirou101** [comment]
Not sure, if you have the beginning symbol, but using `El Heroe de Nivel` returns nothing for me from their website so the website's search probably sucks

**Comment by alessandrojean** [comment]
They search is pretty bad, yes. Closing as we can't really fix this on the extension side.
