### ISSUE TITLE
KomikindoID

### ISSUE THREAD

**Issue by cyberhome404** [tachiyomiorg/tachiyomi-extensions#15553]
### Source information and language

KomikindoID 1.4.8

### Source new URL

https://komikindo.pro/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicate of #15425
