### ISSUE TITLE
Manhwas.net: HTTP error 403

### ISSUE THREAD

**Issue by Hayashi13q4** [tachiyomiorg/tachiyomi-extensions#15563]
### Source information and language

Manhwas.net 1.4.5

### Steps to reproduce

First I enter the extension and it gives me the 403 error, then I open the webview and it does not load the page, but if I open the webview in the browser it does enter the page

### Expected behavior

It should be able to update the manhwas but it doesn't

### Actual behavior

instead of that it gives me the 403 error

### Tachiyomi version

0.14.5

### Android version

Android 13

### Other details

`
![Screenshot_20230302_193246_Tachiyomi](https://user-images.githubusercontent.com/109044821/222609085-dbe896fe-e9e9-4796-ac43-c9dc0e719a30.jpg)
![Screenshot_20230302_193307_Tachiyomi](https://user-images.githubusercontent.com/109044821/222609087-14e718ae-42d3-4876-95d3-eb5c431fad3a.jpg)
`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
Funciona perfectamente

**Comment by playalexx** [comment]
A mí no me funciona, Error 403.
