### ISSUE TITLE
manga18fx: most features broken

### ISSUE THREAD

**Issue by ivopr** [tachiyomiorg/tachiyomi-extensions#15571]
### Source information and language

manga18fx 1.4.32 (English)

### Steps to reproduce

1. Install extension
2. Search or browse, it'll error on search, when browsing it'll loop the latest mangas and not load more.

### Expected behavior

Well, it should fetch and show things correctly.

### Actual behavior

It isn't fetching and showing things correctly.

### Tachiyomi version

Latest J2K (1.6.2) and 0.14.5

### Android version

Android 13

### Other details

Also, I've tried checking things on the page and code, and as far as I've seen everything seems right. Also tried `curl`ing a search and it returned the expected html. If someone are able to at least shed me some light I can put up a PR. 

EDIT:  
When clicking to Open in WebView it redirects to site home instead of search url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ivopr** [comment]
seems like It fixed itself so this is now unneeded

**Comment by ivopr** [comment]
oh, well, It didn't, but i've found out that 2 char searches seems to work

**Comment by stevenyomi** [comment]
Can't reproduce.
