### ISSUE TITLE
RealmScans

### ISSUE THREAD

**Issue by rahxosp** [tachiyomiorg/tachiyomi-extensions#15586]
### Source link

https://realmscans.com/

### Other details

I am writing to request the removal of a realmscans extension from Tachiyomi. This application has been causing significant revenue loss to our scanlation group and we believe its continued availability on your platform is detrimental to our financial well-being.

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Soitora** [comment]
I've received proof of ownership

I have not controlled that the site complies with our ad policy
