### ISSUE TITLE
Reaperscans : Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by SantanuLayek** [tachiyomiorg/tachiyomi-extensions#15609]
### Source information and language

Reaper Scans English 1.4.42

### Steps to reproduce

Go to Reaper Scans Extension, or Update any comic from that source.

### Expected behavior

1. Extension Loads successfully, Manga Updates Successfully.

### Actual behavior

1. Failed to Bypass Cloudflare

### Tachiyomi version

0.14.5

### Android version

Android 12

### Other details

It has been 2 weeks now that I have been encountering this problem, Please fix this as soon as possible, as a good chunk of the comics/manhwas I read are from Reaperscans. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Azim** [comment]
> * Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.

Is not solved by the cloudflare workaround steps in the link

**Comment by SantanuLayek** [comment]
It's working.

**Comment by Azim** [comment]
> It's working.
Gives me infinite captcha even after all of the troubleshooting steps in place

**Comment by DatHypnoboi** [comment]
> 

What user agent do you use? None of the ones I tried have worked

**Comment by Azim** [comment]
> > 
> 
> What user agent do you use? None of the ones I tried have worked

Reaperscans just fixed itself today appearantly
