### ISSUE TITLE
Readd aresmanga

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#15606]
### Source name

Aresmanga

### Source link

https://aresmanga.net/

### Language

Arabic

### Other details

They are steal from other source
Look at this work all chapters under 154 Belonging to other source like team x , ozul scane , swatmanga

https://aresmanga.net/series/the-eternal-supreme/
This pic from 154 , even the logo for ozul scane showed

![Screenshot_٢٠٢٣٠٣٠٦-٠٣١٠٠٧_Tachiyomi](https://user-images.githubusercontent.com/93000786/223099868-a8a91776-5468-4932-8152-280dfc492d02.jpg)

Not only this work , but alot of them under date 2023/1/1

So the request to remove their source is rejected

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Volver555** [comment]
As a response to your claim, this is not right, this serie was first started by us when part of the team was on swatmanga than it became a collab serie with ozul later on, these old chapters were lost sadly when we were trying to change databases (got dmg'd somhow), so we asked ozul to lend the chapters in their website since they are basicly the same as ours...

also there a lot of collab series between us, and this for  example is one of them: https://ozulscans.com/against-the-gods-chapter-582/

Hopefully this clears out the missunderstanding!!

![image](https://user-images.githubusercontent.com/113272610/223102287-3cd1f02b-6f74-47f9-8a9d-99a0fd615b14.png)

**Comment by zoroboro08** [comment]
I'm an old ares manga follower and I guarantee that they are not stealers, in fact, I was one of their followers since they were called iimanga before, they are doing a good job... I don't know what're all these claims about but they are one of the best AR scanlations in the field right now

**Comment by zoroboro08** [comment]
I'm an old ares manga follower and I guarantee that they are not stealers, in fact, I was one of their followers since they were called iimanga before, they are doing a good job... I don't know what're all these claims about but they are one of the best AR scanlations in the field right now

**Comment by KAZE2-1** [comment]
I'm a big fan of AresManga and I assure you that the translation and quality of AresManga is one of the best AR translations if its not the best, which makes many Scans feel jealous of what they are achieving, so they make false claims and  they try obstruct their path to success.

**Comment by BLACKxSUN** [comment]
> As a response to your claim, this is not right, this serie was first started by us when part of the team was on swatmanga than it became a collab serie with ozul later on, these old chapters were lost sadly when we were trying to change databases (got dmg'd somhow), so we asked ozul to lend the chapters in their website since they are basicly the same as ours...
> 
> also there a lot of collab series between us, and this for example is one of them: https://ozulscans.com/against-the-gods-chapter-582/
> 
> Hopefully this clears out the missunderstanding!!
> 
> ![image](https://user-images.githubusercontent.com/113272610/223102287-3cd1f02b-6f74-47f9-8a9d-99a0fd615b14.png)

This is not a justification. All sites do this. You leave a certain work for a while, and when another site tries to complete it, you call them thieves.

**Comment by arkon** [comment]
Please keep discussions about this in #15396.
