### ISSUE TITLE
DuniaKomik.id wrong chapter release date

### ISSUE THREAD

**Issue by RaidBuster** [tachiyomiorg/tachiyomi-extensions#15605]
### Source information and language

DuniaKomik.id 1.4.25

### Steps to reproduce

1. Open DuniaKomik
2. Open any manga

### Expected behavior

The release date should be the same as the one on the website.

### Actual behavior

![Screenshot_2023-03-06-10-51-19-557_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/223015978-638e06a0-a162-4135-a10a-f715cede4486.jpg)
![Screenshot_2023-03-06-10-50-56-066_eu kanade tachiyomi](https://user-images.githubusercontent.com/47489073/223015984-513e9aa7-c43c-4345-bf7d-5260c832d04a.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MuhamedZ1** [comment]
#17166 fixed this issue
