### ISSUE TITLE
one page causes reboot

### ISSUE THREAD

**Issue by jet-black-ninja** [tachiyomiorg/tachiyomi-extensions#15615]
### Source information and language

asura scan 1.4.44 english 

### Steps to reproduce

doctors rebirth manhua 
loading page 3 of chapter 1 reboots the app. 
page 2 and 4 are fine . tried by downloading the chapter. 

### Expected behavior

the page should load

### Actual behavior

the app reboots . 

### Tachiyomi version

0.14.5

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

most likely image is too big, you can try turning on auto split in the download options and download it
