### ISSUE TITLE
Vyvymanga cover not showing and webview redirects to google

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#15622]
### Source information and language

Vyvymanga English 1.4.4

### Steps to reproduce

1. Go into source
2. Select any manga
3. go into webview from manga
4. Also the same when you go to webview from souce page

### Expected behavior

show manga cover image and go to web page of manga or of the source

### Actual behavior

doesn't show some manga cover images
go to web page but it redirects to google

### Tachiyomi version

J2K 1.6.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
duplicate of #15488 and maybe #15035

**Comment by vipzzx** [comment]
yes it is.
