### ISSUE TITLE
uzaymanga.com And www.ruyamanga.com cloudflare pybass problem

### ISSUE THREAD

**Issue by By-PorfecTo** [tachiyomiorg/tachiyomi-extensions#15627]
### Source information and language

Uzay Manga :Turkish 1.4.29 and Rüya Manga :Turkish 1.4.29 

### Steps to reproduce

cloudflare not doing pybass

### Expected behavior

Rüya manga Webviev doing cloudflare pybas 

### Actual behavior

Rüya manga library not updating

Uzay manga doesn't do pybass in either case

### Tachiyomi version

0.14.5

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.

Also please next time open one issue per source.
