### ISSUE TITLE
Bypass Filter Original Language when doing Global Search in MangaDex

### ISSUE THREAD

**Issue by 23SRLITheGamer** [tachiyomiorg/tachiyomi-extensions#15620]
### Source name and language

MangaDex (EN)

### Describe your suggested feature

When I'm browsing MangaDex, I would usually browse the Latest tab, with the filter original language of Japanese turned on in the settings.
This is because using Filter with Original Language set to Japanese and sorted by newest(down arrow) chapter uploaded at, would not give me manga that has an update in just English. (it would give me a list of all Japanese manga, that has recently been updated, even if it's not in English.)
But when I'm searching for a specific manga (which can be Korean or Chinese), I would look for them in all of my installed extensions, which includes Mangadex.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension doesn't have the information the user is doing a global search and bypassing this would require to change the default search done manually inside the source (which already have the filters you can play with). So, not possible.
