### ISSUE TITLE
Mangadex sort by newest chapter uploaded be consistent with language filtered latest tab.

### ISSUE THREAD

**Issue by 23SRLITheGamer** [tachiyomiorg/tachiyomi-extensions#15626]
### Source name and language

MangaDex (EN)

### Describe your suggested feature

I just want the consistency of the Latest tab showing the latest updated manga in accordance with the language settings you have set in the extension settings when you use the Filter option with the newest chapter uploaded at the option.
I understand if you guys cannot do it as the filter uses Mangadex's API which does not differentiate between languages from Case #9762, but I don't understand how it would work on the Latest tab as it does shows only the ones that latest update is on the English language.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 23SRLITheGamer** [comment]
Ok, I also just saw the comment about the API on #9079. I guess what I would want is a different Latest tab for each native/original language then but that would be way too specific for a general extension I would assume. Where should I go to request such a feature?

**Comment by alessandrojean** [comment]
You should request it on the app repository, although I think it will be denied eventually. Closing as it's an API limitation and we can't do anything about it.
