### ISSUE TITLE
cancel or change the “特殊漫画ID列表” feature in DMZJ

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi-extensions#15630]
### Source name and language

DMZJ（中文）

### Describe your suggested feature

some manga are added to a list called “特殊漫画ID列表(1)” or “特殊漫画ID列表(2)” automaticly, then some of these manga can't be updated correctly (many chapters won't show in the app, but can be seen in the webview), if delete the manga in the list, it can be updated correctly .
please cancel this feature or add a switch to decide whether to open it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Please provide some examples of such manga.

**Comment by stevenyomi** [comment]
@362516282 Please provide examples or this issue will be closed.
