### ISSUE TITLE
ShingamiID

### ISSUE THREAD

**Issue by Andreaslur** [tachiyomiorg/tachiyomi-extensions#15648]
### Describe why this should be added

Do not add the ShinigamiID to the Tachiyomi request from staff ShinigamiID

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Please message Riztard#9806 id: 266533152074235905 for further details

**Comment by Riztard** [comment]
@Andreaslur 
shouldve be using source removal form, which has this checklist
> [ ] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM *
 [ ] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site) *
 [ ] Site is not infested with user-hostile features (e.g., invasive or malicious ads) *
 
 and the 2nd one isnt fulfilled so... rejected
________________________________________
 nomor 2 tidak terpenuhi, jadi ditolak
