### ISSUE TITLE
Failed To Get Extensions List

### ISSUE THREAD

**Issue by GautamJii** [tachiyomiorg/tachiyomi-extensions#15651]
### Source information and language

Extensions are not showing 

### Steps to reproduce

Failed to get extensions list

### Expected behavior

Full extensions list should been shown

### Actual behavior

Only installed extensions list is showing

### Tachiyomi version

App version: 0.12.3.10 (standard, 7722361, 72, 2023-02-09T10:47Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.A315FXXS2DWA2 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

### Android version

Android 11

### Other details

This is my first time reporting a issue if i have typed something wrong please try to understand. Thank You 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Closing since you're in the wrong place
