### ISSUE TITLE
IsekaiScan.eu (unoriginal) HTTP Error 400

### ISSUE THREAD

**Issue by SkyNalix** [tachiyomiorg/tachiyomi-extensions#15655]
### Source information and language

IsekaiScan.eu (unoriginal) 1.4.29 (English)

### Steps to reproduce

1. Open the extension in Tachiyomi

### Expected behavior

It should show all the mangas available on the source

### Actual behavior

But instead i get the error "HTTP error 400. Check website in WebView"

### Tachiyomi version

0.14.5

### Android version

Andoid 13

### Other details

It started happening a week ago. When opening the source in webview everything work fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by muerto212** [comment]
I think it's because the url address changed from isekaiscan.eu to isekaiscan.to
