### ISSUE TITLE
Nhentai has stopped working 

### ISSUE THREAD

**Issue by Ronnie9999** [tachiyomiorg/tachiyomi-extensions#15666]
### Source information and language

"Nhentai 1.4.36(All)"

### Steps to reproduce

When the extension is opened it shows
"Failed to Bypass Cloudware"

### Expected behavior

The extension used to open and load manga perfect with the filter feature working just fine.

### Actual behavior

The extension doesn't not open and shows a message
"Failed to Bypass Cloudware"

### Tachiyomi version

"1.4.36"

### Android version

Android 13

### Other details

App and extension is updated to the latest version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
