### ISSUE TITLE
Group MIGRATE

### ISSUE THREAD

**Issue by Me-cha** [tachiyomiorg/tachiyomi-extensions#15665]
### Describe why this should be added

There should be a feature of Group migration of selected MANGA's /MANHWA's 
In browse section we have migrate there if we want to migrate multiple manga's we have to do it one by one 
It is very troubling when there are many manga's to migrate.
This situation occurs when we delete any extension.
To avoid this please add group migration feature 
It can work like when we select multiple books(manga's) and migrate them, they are migrated to selected source and gives us the list of unavailable/not found books .we can then migrate them to different source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

there is already a request for it anyways.
