### ISSUE TITLE
Failed to Bypass Cloud Flare

### ISSUE THREAD

**Issue by masstheunknown1** [tachiyomiorg/tachiyomi-extensions#15663]
### Source information and language

Nhentai 1.4.36

### Steps to reproduce

1.I can't use the extension using the app
2.But  i can go into their website via browser
3.it failed to Bypass the cloud flare

### Expected behavior

I should've been able to read the doujins i bookmarked 

### Actual behavior

But it failed to Bypass the cloud flare and won't load the source

### Tachiyomi version

0.14.5

### Android version

Android 10

### Other details

Also i can't update the extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
