### ISSUE TITLE
Mangakio is not working 

### ISSUE THREAD

**Issue by Mashiyat14** [tachiyomiorg/tachiyomi-extensions#15673]
### Source information and language

Mangakio 1.4.29

### Source new URL

https://mangakio.me/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed by #17396
