### ISSUE TITLE
Hentailib, cloudflare

### ISSUE THREAD

**Issue by pokedim13** [tachiyomiorg/tachiyomi-extensions#15678]
### Source information and language

Hentailib 1.4.35

### Steps to reproduce

1) install hentailib extension
2) open any manga
3) to see the error, it was not possible to bypass cloudflare

### Expected behavior

-

### Actual behavior

-

### Tachiyomi version

0.14.5

### Android version

11

### Other details

I kind of passed everything on how to repeat the mistake. So if something else is needed, I will try to give

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by PuppyLo** [comment]
They have changed their domain, so there is an error. It would be convenient if you can enter the site address yourself in the settings
