### ISSUE TITLE
No page found

### ISSUE THREAD

**Issue by Code0016** [tachiyomiorg/tachiyomi-extensions#15676]
### Source information and language

Bilibili 1.4.11

### Steps to reproduce

1.identify the problem

### Expected behavior

This should happen cause the bypass not working 

### Actual behavior

Usually bilibili extension before update can use smoothly without problem like page not found 

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
I used bilibili and it's fine

**Comment by alessandrojean** [comment]
Please do specify more details and provide actual reproductive steps, including some examples where this happens. The extension doesn't try to bypass any payment and never will do that. Closing as it lacks useful information.
