### ISSUE TITLE
[Request] for view tab for all the downloaded chapters that are not in Library

### ISSUE THREAD

**Issue by Ba7z** [tachiyomiorg/tachiyomi-extensions#15680]
### Source name and language

All Extensions

### Describe your suggested feature

Reason to add this feature:
(Same as the "Updates" tab but the data are the downloaded chapters that are not in the library)
1. When you accidentally downloaded a chapter and forget to put it in the library or forget the manga name. it's hard to search the manga one by one just to delete the downloaded chapters.
2. If you just want to read the manga but you don't like it that much and you don't want it to put in your library. You just want to read it then delete it after that.
3. Checking the manga if it's good and you just want to download a few chapters then choosing if you want to delete it or put it in the library after reading the downloaded chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
