### ISSUE TITLE
Failed To Get Manga Extension 

### ISSUE THREAD

**Issue by polaxgwapo018** [tachiyomiorg/tachiyomi-extensions#15703]
### Source information and language

Manga

### Steps to reproduce

Example :
1. Open the Aniyomi
2. Open Browse
3. Open Manga Extension

### Expected behavior

The List of manga extension should load after clicking the manga extension.

### Actual behavior

After clicking the manga extension the toast word says Failed to get Extensions

### Tachiyomi version

0.12.3.10

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
Aniyomi issues are not Tachiyomi issues, unless you can reproduce it with Tachiyomi.
