### ISSUE TITLE
Nhentai doesn't load because of Cloudflare infinite captcha loop

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi-extensions#15707]
### Source information and language

Nhentai 1.4.36

### Steps to reproduce

1. Open Nhentai extension

### Expected behavior

Should give the series

### Actual behavior

Doesn't give any series and gives Cloudflare error

### Tachiyomi version

1.6.3

### Android version

Android 7

### Other details

tried opening it on webview, doesn't work. Tried using a browser, Firefox, it did load.

Crash logs:

App version: 1.6.3 (standard, b6d11b775, 101, 2023-03-13T20:08Z)
Android version: 7.1.2 (SDK 25)
Android build ID: N2G47H
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: rolex
Device model: Redmi 4A
Device product name: rolex

--------- beginning of system
--------- beginning of main
03-14 18:37:44.495 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101056c
03-14 18:37:44.495 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101058c
03-14 18:37:44.495 32205 32205 E ResourceType: Style contains key with bad entry: 0x01010605
03-14 18:37:44.495 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101062c
03-14 18:37:44.495 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101062d
03-14 18:37:44.495 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101062e
03-14 18:37:44.554 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101056c
03-14 18:37:44.554 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101058c
03-14 18:37:44.554 32205 32205 E ResourceType: Style contains key with bad entry: 0x01010605
03-14 18:37:44.554 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101062c
03-14 18:37:44.554 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101062d
03-14 18:37:44.554 32205 32205 E ResourceType: Style contains key with bad entry: 0x0101062e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by lasersPew** [comment]
Cleared Cache, WebView data, chapter data even covers, changed useragent, and reinstalled nhentai extension 3 damn times and still doesn't work. Like literally.

**Comment by alessandrojean** [comment]
Nothing you can do then, use other sources or wait until they lower their protection.
