### ISSUE TITLE
MangaFreak failing to bypass cloudflare

### ISSUE THREAD

**Issue by Cistmist** [tachiyomiorg/tachiyomi-extensions#15714]
### Source information and language

Mangafreak 1.4.8 (English)

### Steps to reproduce

Tried opening in WebView to check for cloudflare, and if it's from a manga title I get an infinite cloudflare verification screen.

An example:
1- Library titles refresh will return Failed to bypass error.
2- Pressing on the extension will return Failed to Bypass with a blank screen.
3- Pressing on Latest on the extension, shows a list of manga which is up-to-date, though clicking a title won't load the number of chapters.
4- In the case of a manga I already have the number of chapters visible, reading them and downloading works though updating for new chapters doesn't.

### Expected behavior

Should be able to update titles and view number of chapters.

### Actual behavior

1- Library titles refresh will return Failed to bypass error.
2- Pressing on the extension will return Failed to Bypass with a blank screen.
3- Pressing on Latest on the extension, shows a list of manga which is up-to-date, though clicking a title won't load the number of chapters.
4- In the case of a manga I already have the number of chapters visible, reading them and downloading works though updating for new chapters doesn't.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Loafbreads** [comment]
I have that kind of problem as well in the nhentai extension it happened as well

**Comment by buhbbl** [comment]
Do you have the same issue when opening the website on your normal browser? 

Also, could you try adding the your phone browser's user agent to `Settings > Advanced > "Default user agent string"`. The user agent for your phone browser can be found by visting to [this site](https://www.whatismybrowser.com/detect/what-is-my-user-agent/) using you mobile browser.

**Comment by Lickitahm** [comment]
> Do you have the same issue when opening the website on your normal browser?
> 
> Also, could you try adding the your phone browser's user agent to `Settings > Advanced > "Default user agent string"`. The user agent for your phone browser can be found by visting to [this site](https://www.whatismybrowser.com/detect/what-is-my-user-agent/) using you mobile browser.

It seems like this is happening for nHentai as well, the issue is that someone hardcoded the user agent string and changing it does nothing: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15719

**Comment by ChristianCiach** [comment]
> It seems like this is happening for nHentai as well, the issue is that someone hardcoded the user agent string and changing it does nothing: #15719

The hardcoded user agent only applies to nhentai. There is no such thing in the source code of the mangafreak extension.

**Comment by Lickitahm** [comment]
> > It seems like this is happening for nHentai as well, the issue is that someone hardcoded the user agent string and changing it does nothing: #15719
> 
> The hardcoded user agent only applies to nhentai. There is no such thing in the source code of the mangafreak extension.

Thought it may be the same problem as Mangafreak keeps looping on the cloudflare page for me as well. It works with normal Chrome on my tablet and I tried even using a VPN, different DNS and network as well as a new user agent string but to no avail.

**Comment by Cistmist** [comment]
> Do you have the same issue when opening the website on your normal browser?
> 
> Also, could you try adding the your phone browser's user agent to `Settings > Advanced > "Default user agent string"`. The user agent for your phone browser can be found by visting to [this site](https://www.whatismybrowser.com/detect/what-is-my-user-agent/) using you mobile browser.

No it works fine on my browser (Chrome).
I did try change the default user agent before I did the post and it did nothing.
