### ISSUE TITLE
Yugenmangas Error Downloading chapters 

### ISSUE THREAD

**Issue by Zahyra16** [tachiyomiorg/tachiyomi-extensions#15710]
### Source information and language

Yugenmangas 1.4.11(Spanish)

### Steps to reproduce

An error similar to #15151 

### Expected behavior

Download chapters without problem 

### Actual behavior

![Screenshot_2023-03-14-10-56-13-942_eu kanade tachiyomi](https://user-images.githubusercontent.com/92189825/225061442-5b394eae-abe4-4b3e-9c31-a0a9de2821b3.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As explained previously in #15151, we can't do anything about it as it's a website issue.
