### ISSUE TITLE
EarlyManga closeing my tachi

### ISSUE THREAD

**Issue by ruuno123** [tachiyomiorg/tachiyomi-extensions#15716]
### Source information and language

EarlyManga 1.4.20

### Steps to reproduce

1. i open the EarlyManga Extension "latest" label
2. then it clost my tachi(it was working fine in the morning)
3. if i use just the "popular(just click the "earlymanga" ) then working.

### Expected behavior

dont close my tachi

### Actual behavior

its close my tachi if i open with "latest"

### Tachiyomi version

0.14.0

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
 
 though you should update the app before making a post.
