### ISSUE TITLE
N Hentai isnt working

### ISSUE THREAD

**Issue by SwiftGrim** [tachiyomiorg/tachiyomi-extensions#15719]
### Source information and language

NHentai

### Steps to reproduce

Open browse
Go to sources
Open NHentai

### Expected behavior

It should load the site

### Actual behavior

It's is not responding 

### Tachiyomi version

0.14.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Steve-cn** [comment]
same question，Failed to bypass Cloudflare

**Comment by MahaVailo13** [comment]
I have tried changing my client, and works in normal browser. But still same problem

**Comment by Tuz** [comment]
For some reason @vetleledaal [hardcoded](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/471a45ba959e90498db4ef27b8f6f066efe28576) user agent, so changing it in global settings not helping.

**Comment by vetleledaal** [comment]
> For some reason

> set User-Agent to get past Cloudflare

In any case, undoing that commit might work

**Comment by ChristianCiach** [comment]
Agreed. https://github.com/tachiyomiorg/tachiyomi-extensions/commit/471a45ba959e90498db4ef27b8f6f066efe28576 hardcodes a user-agent that simulates a browser version that is now almost a year old and very unlikely to be used by actual humans. No wonder cloudflare assumes this to be a bot.
