### ISSUE TITLE
Cloudflare Japscan

### ISSUE THREAD

**Issue by Freedent-72** [tachiyomiorg/tachiyomi-extensions#15724]
### Source information and language

Japscan 1.4.39 Français 

### Steps to reproduce

1 Démarrer l'application
2 Ouvrir la source Japscan
3 Impossible de contourner le cloudflare

### Expected behavior

Lecture des scans

### Actual behavior

Impossible de lire les scans même quand on applique les conseils via l'aide internet. J'ai tout essayé (cache, cookies, navigateur...) et impossible de contourner la barrière.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
