### ISSUE TITLE
MMScans Domain change

### ISSUE THREAD

**Issue by WolfZero49** [tachiyomiorg/tachiyomi-extensions#15736]
### Source information and language

MMScans English 1.4.32

### Source new URL

mm-scans.org

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
This should be closed as already fixed
