### ISSUE TITLE
Not workibg source

### ISSUE THREAD

**Issue by Zeggy02** [tachiyomiorg/tachiyomi-extensions#15742]
### Source information and language

Bulu manga 1.4.7

### Steps to reproduce

Error file said that it caoud not connet to bulu manga 

### Expected behavior

It have upadated the mangas 

### Actual behavior

What happening instead is the updates are failing

### Tachiyomi version

Stable 1.9.0

### Android version

Andriod 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Closing in favor of #15842
