### ISSUE TITLE
MangaBuddy Missing Pages

### ISSUE THREAD

**Issue by BadMoose9** [tachiyomiorg/tachiyomi-extensions#15744]
### Source information and language

MangaBuddy 1.4.13 English

### Steps to reproduce

1. Open extension
2. Click on any manga
3. Click on any chapter

### Expected behavior

All pages should be visible

### Actual behavior

Only 2 pages show up

### Tachiyomi version

1.14.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rubiee-1** [comment]
I have this problem too. Only 1-2 pages were showing and then the chapter ends

**Comment by issam662** [comment]
same issue. just 2 images load and the rest is missing

**Comment by asterlillian** [comment]
Same issue, but the website is completely fine

**Comment by R-iku** [comment]
Same issue. Only 2 pages are available and the other pages are missing

**Comment by LadyinSpy** [comment]
Same issue, that's why I uninstalled tachiyomi temporary but when I downloaded it again, still same. Only 2 pages are available. 
Is there a possibility of going back to the way it was?

**Comment by clyezen** [comment]
i always used webview for now because this problem , or use different extension
