### ISSUE TITLE
Forbidden 403 error in extension

### ISSUE THREAD

**Issue by Morse069** [tachiyomiorg/tachiyomi-extensions#15741]
### Source information and language

YaoiLib 1.4.19 (Russian/Русский)

### Steps to reproduce

Log in webview 
Click any manga 
It says 403 forbidden

### Expected behavior

You can access any manga after logging in

### Actual behavior

![IMG_20230317_150326](https://user-images.githubusercontent.com/121346796/225835509-d29e329d-8fb7-4be3-8806-2e538a350ddc.jpg)
![IMG_20230317_150331](https://user-images.githubusercontent.com/121346796/225835516-2c1ace7f-feb4-43da-9a4c-11dd257d39d9.jpg)

### Tachiyomi version

0.14.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
I can't reproduce it

**Comment by e-shl** [comment]
@Morse069 what authorization did you use?
