### ISSUE TITLE
Japscan: Unable to download

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#15749]
### Source information and language

Japscan 1.4.39

### Steps to reproduce

1. Open a manga from the source
2. Select a chapter to download
![Screenshot_20230317-235635](https://user-images.githubusercontent.com/51856879/226071967-6611dd9c-8601-406a-a9a4-45dd6f5168f4.png)

3. Download gets stuck at zero and doesn't budge
![Screenshot_20230317-235805](https://user-images.githubusercontent.com/51856879/226071996-6445159f-30de-4879-811e-e3e3fa8f404f.png)

4. Notification shows up saying the failed to bypass couldflare error
![Screenshot_20230317-235828](https://user-images.githubusercontent.com/51856879/226072063-433f0adc-5e76-4551-bfdb-eca5673efd10.png)

### Expected behavior

The download should start and then end

### Actual behavior

Download gets stuck at zero

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

Japscan uses cloudflare on its chapter viewer however I am able to successfully with my user agent, and despite that the chapter is still undownloadable and trying to simply read it shows an unable to load image error

![Screenshot_20230317-235725](https://user-images.githubusercontent.com/51856879/226072301-f29784de-cbeb-4b7d-ac12-5f358a37006e.png)

![Screenshot_20230317-235701](https://user-images.githubusercontent.com/51856879/226072332-b66a1812-3f65-4651-a5c6-d2f515a189ac.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LeonardoRubuz** [comment]
I have the same issue since the past three months

**Comment by ashuralong** [comment]
I have the same issue...

**Comment by RamAdam0** [comment]
me too
