### ISSUE TITLE
Please remove some Unusable/Useless 中文（Chinese)  extensions

### ISSUE THREAD

**Issue by song2daodao** [tachiyomiorg/tachiyomi-extensions#15754]
### Source information and language

Unusable : 1. bz Manhua (zh.bzmanhua) 2. Haomanwu (zh.haomanwu) 3. Kuaikuai Manhua (zh.kuaikuai) 4. Tudou Manhua (zh.ptcomic) Useless : 5. BH3 (zh.bh3)  6. Terra Historicus (zh.terrahistoricus)

### Steps to reproduce

**The Unusable part : 1. bz Manhua (zh.bzmanhua) 2. Haomanwu (zh.haomanwu) 3. Kuaikuai Manhua (zh.kuaikuai) 4. Tudou Manhua**

Basically, these plugins are not loading the site correctly.

![01](https://user-images.githubusercontent.com/99074946/226102205-9cc9915f-2b44-4c07-b313-658281bb45cf.png)
They are not well maintained by the uploader, especially the "bz Manhua" extension, It points to the same site as another chinese extension, but this one unusable. Please remove these unusable plugins. 

**The Useless part  : 5. BH3 (zh.bh3)  6. Terra Historicus (zh.terrahistoricus)**

I don't know what the point of these two extensions is. Basically it's a collection of doujinshi from Honkai 3 and Arknights, but not pointing to some collection of manga sites. There are only 6 manga in "Terra Historicus extension". A single manga in "BH3 extension" (split up into many chapters, maybe 40, but it's actually just 1 manga in this extension)

![02](https://user-images.githubusercontent.com/99074946/226102240-3965f0b8-9620-4f9a-9912-3cd1fc6e133a.png)
![03](https://user-images.githubusercontent.com/99074946/226102253-131470b6-c155-4013-8dcb-c80c66f2c8e4.png)
![05](https://user-images.githubusercontent.com/99074946/226102260-02b53a11-b2c1-4bd5-80cc-2e2a0c890293.png)

You can easily find the doujinshi for Honkai 3 and Arknights in other "manga collection plugins". So why should I download these two extensions. Are these two extensions some kind of game advertisement? Please remove these two useless plugins.

### Expected behavior

_

### Actual behavior

_

### Tachiyomi version

latest

### Android version

12

### Other details

The other Chinese extensions are well enough maintained, so there is no need for more useless extensions. This is a pain in the ass when selectively downloading and uninstalling extensions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by song2daodao** [comment]
> 崩三和方舟的是有人请求做的官方站，没有什么问题，不会删除。

那其余的失效插件能删除吗？找插件的时候真的很头大，一片无效的（没有图标/都是同一个图标的那几个插件，不知道谁上传的），tachiyomi的插件又不好卸载。

至于那两个官方站插件，好吧，理解。但是其他插件一搜就能搜到这两个插件对应的漫画，也就那几本，后续也不会更新了。就。。。也许在插件名上标注的更清楚会好点，挑插件很累

**Comment by stevenyomi** [comment]
> tachiyomi的插件又不好卸载

在插件列表长按插件就可以卸载。
