### ISSUE TITLE
Komikindo url change

### ISSUE THREAD

**Issue by clyezen** [tachiyomiorg/tachiyomi-extensions#15764]
### Source information and language

KomikIndoID 1.4.8 (Indonesia)

### Source new URL

https://komikindo.pro/

### Other details

pls change the new url of the extension to https://komikindo.pro/ , current url is https://komikindo.id/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicate of #15425
