### ISSUE TITLE
Add allanime.to extension 

### ISSUE THREAD

**Issue by DilipPatel007** [tachiyomiorg/tachiyomi-extensions#15768]
In an effort to have a more manageable issue backlog, we're closing issues older than 1 year. If you think your request or report is still relevant and may benefit others, please open a new issue.

_Originally posted by @github-actions[bot] in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6197#issuecomment-1086008312_

**Comment by scb261** [comment]
Open a new issue using `Source request` template https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose

This will help to manage issues for users and for the moderator bot
