### ISSUE TITLE
MangaBuddy mangas only has 2 pages

### ISSUE THREAD

**Issue by kairusds** [tachiyomiorg/tachiyomi-extensions#15779]
### Source information and language

MangaBuddy 1.4.14 (English)

### Steps to reproduce

Find a manga on the source 

### Expected behavior

It should have more than 2 pages.

### Actual behavior

Manga only has 2 pages

### Tachiyomi version

0.14.5-5625

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> Update your Mangabuddy extension ([v1.4.14](https://tachiyomi.org/extensions/#en.mangabuddy)); 
> After that, delete downloaded chapters that were affected by the issue, and tap Clear Chapter Cache under More > Settings > Advanced Settings to continue using the source.
