### ISSUE TITLE
Arcane Scans

### ISSUE THREAD

**Issue by SaminIIslam** [tachiyomiorg/tachiyomi-extensions#15781]
### Source name

ArcaneScans

### Source link

https://arcanescans.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by MeLoseAgain** [comment]
if this site has a lot of series I will commit 😅

**Comment by FaTe-code** [comment]
Also need it as it locks some pages from other sites. And only they do some manhwa which not tled anywhere else

**Comment by vetleledaal** [comment]
Uses Madara theme
