### ISSUE TITLE
htcomic.top Is Dead, Again

### ISSUE THREAD

**Issue by skycat2216** [tachiyomiorg/tachiyomi-extensions#15798]
### Source information and language

紳士漫畫(WNACG)

### Source new URL

htmanga3.top

### Other details

Already tested with steps in #15072 
If not use TLS to secure transmission, The URL will redirect to htmanga3.top automatically
But starts with https:// would cause connection error
Happens on Tachiyomi and a Chromium core browser is not from CN

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by zicaitang** [comment]
Can administrators solve such problems?

**Comment by zicaitang** [comment]
老哥，如果能解决请说一下怎么操作。感谢Brother, if you can solve it, please explain how to operate it. thank

**Comment by stevenyomi** [comment]
Just wait patiently.

耐心等待有人来修复。

**Comment by skycat2216** [comment]
> 老哥，如果能解决请说一下怎么操作

願意的話學#15074也能解決

**Comment by zicaitang** [comment]
> > 老哥，如果能解决请说一下怎么操作
> 
> 愿意的话学 #15074 也能解决

看不懂（小白一个），能教一下吗？之前版本没更新能用，更新后就看不了了。谢谢你的回复

**Comment by kschou95** [comment]
我自己試著改了url。自己測試能行。
如果要用的話，要先卸載official的。安裝的時候安卓會問你

commits:
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/15830/commits/61816c5df0d84cef1afaf4c0394508c83d5ca98f

release:
https://github.com/kschou95/tachiyomi-extensions/releases/tag/tachiyomi-wnacg

**Comment by zicaitang** [comment]
> 更改了URL。测试了我自己的工作。 如果您想使用它，您将需要卸载官方版本的扩展，并信任源，如果未知源未启用。 我自己试着改了url。 自己测试能行。 如果要用的话，要先卸载official的。 安装的时候安卓会问你
> 
> 提交： [97851ef](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/97851ef68e6d90f45e40e839e31363f6ace57700)
> 
> 发布： https://github.com/kschou95/tachiyomi-extensions/releases

管理员已经修好了，但还是谢谢你了
