### ISSUE TITLE
Can visit western comics in webview but not download or read in app (comicextra /readcomiconline.to) 

### ISSUE THREAD

**Issue by HereticWilson** [tachiyomiorg/tachiyomi-extensions#1579]
App version: 0.8.4
Comicextra version: 1.2.3
Readcomiconline version: 1.2.5

So when trying to download comics from either source once it gets to about 200 pages downloaded the downloads just stop. I can still visit the title in question in webview and even the page the download stopped at, but there is no captcha or anything and once the download stops I can't get it to resume or read the issue in the normal in app reader.

**Comment by SnakeDoc83** [comment]
Can you post an example for each (comic name, chapter)?

**Comment by joseph619** [comment]
Readcomiconline works fine for me, I just download Strange Tales Issue 1-3

**Comment by HereticWilson** [comment]
> Can you post an example for each (comic name, chapter)?

Sure I am currently stuck on Wonder Woman (2006) issue 39 pg 61on Comic Extra and yet I can go right into webview, view that exact page, with no captcha or "wait 5 seconds" screen.

**Comment by SnakeDoc83** [comment]
Slightly going to change how ComicExtra builds its page list--might help, might not.

As for ReadComicOnline, I don't know.  There's a few issues open on it: https://github.com/inorichi/tachiyomi-extensions/issues/1500, https://github.com/inorichi/tachiyomi-extensions/issues/1193, https://github.com/inorichi/tachiyomi-extensions/issues/258.  Although some have reported issues, others report it works fine.  Hard to guess what the issue is.

**Comment by joseph619** [comment]
Did you try manually opening  some random comic chapters? Might have to give quite a few tries, since the issue is elusive.

**Comment by SnakeDoc83** [comment]
I tried maybe 10 comics. 

Maybe there's an issue with Cloudflare or Blogspot.  Maybe a rate-limiter needs to be added.  I'll try looking at some more chapters later.

**Comment by HereticWilson** [comment]
> I tried maybe 10 comics.
> 
> Maybe there's an issue with Cloudflare or Blogspot. Maybe a rate-limiter needs to be added. I'll try looking at some more chapters later.

Interesting, and you could download any of them without issues throughout? For me it always happens when I getting close to 200 pages consecutively downloaded.

**Comment by SnakeDoc83** [comment]
After I updated Comicextra I tested it by downloading 20-something chapters without an issue.  Just downloaded 10 chapters (300+pages) on RCO and it went fine.

**Comment by scb261** [comment]
Both are bumped several versions already (ComicExtra 1.2.6 and ReadComicOnline 1.2.9) and work fine for me. If you still having problems - open new issue, one issue per source
