### ISSUE TITLE
Shinigami.id http error 502

### ISSUE THREAD

**Issue by RoSiCyBeR** [tachiyomiorg/tachiyomi-extensions#15817]
### Source information and language

Shinigami.id

### Steps to reproduce

1. Open shinigami.id
2. Open any random chapter

### Expected behavior

Open chapter via app any number chapter get 502

### Actual behavior

![Screenshot_20230324-154527](https://user-images.githubusercontent.com/34416860/227470576-116837f9-1c21-4723-ad4d-743a517a0102.png)

### Tachiyomi version

Tachiyomi 0.14.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RoSiCyBeR** [comment]
I checked on discord they were only told to clear cache

**Comment by alessandrojean** [comment]
HTTP error 5xx are server side errors and we can't fix it on the extension side. You need to wait for them to fix it instead.
