### ISSUE TITLE
ManHuaGui R18 error issue

### ISSUE THREAD

**Issue by foolishtroy** [tachiyomiorg/tachiyomi-extensions#15812]
### Source information and language

ManHuaGui 中文 1.4.16

### Steps to reproduce

1. Setting > Browse > NSFW (18+) sources - Turn on "Show in sources and extension lists"
2. Restart app and open ManHuaGui
3. Open R18 manga with hidden chapter list such as 出包王女Darkness, DARLING in the FRANXX.

### Expected behavior

Hidden list of R18 chapters should be viewable.

### Actual behavior

Chapter list doesn't show, error message:
IllegalStateException：您需要打开R18作品显示开关并重启软件才能阅读此作品

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
提示的这个开关在单独的插件设置里面（浏览 → 插件 → 某个插件右边的设置 → 齿轮按钮）。

The mentioned toggle is in extension settings, not app settings.
