### ISSUE TITLE
Shinigami.id 502 error

### ISSUE THREAD

**Issue by Forgetmenot7** [tachiyomiorg/tachiyomi-extensions#15823]
### Source information and language

"Shinigami 1.4.28 (Indonesia)"

### Steps to reproduce

1. When you enter shinigami
2. Then you choose one manga to read
3. Start loading then http error 502

### Expected behavior

It should let me read the chapter of the manga.

### Actual behavior

The manga came out and there was an error message

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

the manga immediately came out and it said http error 502

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP errors 5xx are server side errors, we can't do anything to fix it. Wait until they fix it.
