### ISSUE TITLE
About Dmzj special manga id, chapter list

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi-extensions#15831]
### Source name and language

Dmzj v1.4.35 Chinese

### Describe your suggested feature

some manga have other series, but when become special manga, other series don't show in chapter list
for example: id:46611 id:50559 have other series but not show in chapter list
I hope other series can show in chapter list

### Other details

Chinese suggest: 一些特殊漫画有其他系列但是不会显示在章节列表里，希望能显示出来

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
这是做不到的，所谓特殊漫画就是被隐藏了，隐藏后没有方法可以获取到其他系列。

除非你在隐藏之前获取过章节列表，然后不再更新章节。

如果你想要插件自动阻止更新隐藏后的漫画，以便保留其他系列入口，可以开一个新的 Issue 申请添加这个功能。

**Comment by Endowpea** [comment]
> 这是做不到的，所谓特殊漫画就是被隐藏了，隐藏后没有方法可以获取到其他系列。
> 
> 除非你在隐藏之前获取过章节列表，然后不再更新章节。
> 
> 如果你想要插件自动阻止更新隐藏后的漫画，以便保留其他系列入口，可以开一个新的 Issue 申请添加这个功能。

我发现src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/ApiV3.kt里的mangaInfoUrlV1这个api返回的数据里list旁边还有一个alone有其他系列的数据，合并一下是不是就是完整的章节列表了

**Comment by stevenyomi** [comment]
> 我发现src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/ApiV3.kt里的mangaInfoUrlV1这个api返回的数据里list旁边还有一个alone有其他系列的数据，合并一下是不是就是完整的章节列表了

我检查了一下，那个只有单行本数据，部分神隐的作品里有其他汉化版并不包含在内，不过我会把这个单行本加上。
