### ISSUE TITLE
Reaper Scans (En) downloading issuses

### ISSUE THREAD

**Issue by ClnSrt** [tachiyomiorg/tachiyomi-extensions#15846]
### Source information and language

Reaper Scans 1.4.42 (En)

### Steps to reproduce

1.Instal the English extension of Reaper Scans
2. Pick a random manga
3. Download a chapter 

### Expected behavior

You should have the chapter downloaded

### Actual behavior

The chapter doesn't download and an error that says: "excepted URL scheme 'http'or 'https'but no scheme was found for" pops up

### Tachiyomi version

0.14.5

### Android version

12

### Other details

When I try to read the chapter without downloading it the number of pages is written but every other page (1/2) appears

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Probably related to #15791
