### ISSUE TITLE
Webnovel.com strange behaviour when "Privileged Chapters" are unlocked

### ISSUE THREAD

**Issue by Kuro6804** [tachiyomiorg/tachiyomi-extensions#15849]
### Source information and language

Webnovel.com 1.4.6

### Steps to reproduce

1. Unlock a "Priviledged"/Early Access Chapter on the Webnovel app.
2. Log in through WebView in Tachiyomi.
3. Refresh list.

### Expected behavior

Shows list of all chapters available through their website.

### Actual behavior

List only shows the Privileged Chapters.

### Tachiyomi version

TachiyomiSY r504

### Android version

Android 10

### Other details

Privileged Chapters aren't actually available through their website, only the app, so they can't even be opened through Tachi.

Webnovel also _very_ frequently logs me out, but I'm not sure that's something that can be resolved on Tachi's end, so I didn't wanna open a separate issue. Just thought I'd mention it in case it can be solved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Hey hello. Can you come to the Tachi discord server and give me a mention (AntsyLich#0401) in the #support channel
