### ISSUE TITLE
No sources found

### ISSUE THREAD

**Issue by 12Vine** [tachiyomiorg/tachiyomi-extensions#15856]
### Source information and language

"Drakescans 1.4.30 (english)"

### Steps to reproduce

1. Try a different user string
2. Try download the site again
3. No chapter still

### Expected behavior

This happened the extension have the chapters pulled out or nothing inside

### Actual behavior

No chapters are in this extension

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

Well the site has pumped their security but no chapter even i change the user string .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
Drake Scan is having problems with their website. It has nothing to do with the extension or Tachi.
