### ISSUE TITLE
dmzj: some comics can't be loaded 

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#15853]
### Source name and language

dmzj

### Describe your suggested feature

    网址更新后，部分原先收藏的漫画连接被重置，能否重新构建这部分漫画的链接。

### Other details

![Screenshot_2023-03-26-18-45-09-964_eu kanade tachiyomi](https://user-images.githubusercontent.com/110704357/227772357-8d7e36e6-177a-4d50-a4ee-f8b375f77379.jpg)
![Screenshot_2023-03-26-18-38-38-550_eu kanade tachiyomi](https://user-images.githubusercontent.com/110704357/227772363-2ecfde4a-d215-4f9c-aa19-532bf20db531.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by RX93CN** [comment]
目前测试得到，api.dmzj.com端口的问题导致部分漫画无法加载

**Comment by zhongfly** [comment]
你选错了issue类别，应该选"Issue report"

**Comment by wh201906** [comment]
The comic you mentioned is not available now
你提到的这两部漫画似乎已经下架了

<details><summary>Website</summary>
<p>

![图片](https://user-images.githubusercontent.com/62299611/227866509-8df7a9f6-e524-4156-96ff-7ff991a78f52.png)
![图片](https://user-images.githubusercontent.com/62299611/227866554-a657cf66-b61b-4d3e-9233-6903d905527f.png)

</p>
</details>

**Comment by stevenyomi** [comment]
#15859 暂时弹出消息提示无法获取特殊漫画的信息，之后如果有其他办法再恢复。另外，新版本合并后，如果本地之前已有特殊漫画的章节目录，则可以正常观看。

**Comment by Steve-337** [comment]
看样子是之前用的api已经被设定解析到127.0.0.1，不可用了。应该是只能等找到其他api了
