### ISSUE TITLE
French source : manga-scan.co

### ISSUE THREAD

**Issue by AlCiavi** [tachiyomiorg/tachiyomi-extensions#15864]
### Source name

Manga Scan

### Source link

https://manga-scan.co

### Language

French

### Other details

Hello,
This source is excellent for french users. No cloudflare and a very large catalog of mangas/manhwas/webtoons.
Thank you for your concern.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
MMRCMS theme? Not 100% sure

**Comment by AlCiavi** [comment]
What do you mean by sure @KirinRaikage ?

**Comment by KirinRaikage** [comment]
I was wondering what theme Manga-Scan uses in order to implement the extension @AlCiavi

**Comment by AlCiavi** [comment]
And this theme causes problems for the integration? I don't know anything about it, I'm sorry. @KirinRaikage

**Comment by KirinRaikage** [comment]
Nope, I'm merely asking the devs,
It's even the opposite : If it's that theme, it will make the implémentation way easier.

**Comment by AlCiavi** [comment]
Oh, I just understood what you meant! Sorry for the misunderstanding, I'm not 100% fluent.
Anyway, it would be great, because Sushi Scan is excellent in quality and quantity, but still quite unstable and the strong alternatives are a little lacking lately.

**Comment by AlCiavi** [comment]
Up, we need more sources since Sushi-Scan is having lots of problems.
