### ISSUE TITLE
Nhentai URL change

### ISSUE THREAD

**Issue by FOXTROXHACKS** [tachiyomiorg/tachiyomi-extensions#15916]
### Source information and language

Nhentai 1.4.37

### Source new URL

Https://nhentai.to

### Other details

The url changed from **https://nhentai.net** to **https://nhentai.to**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No it didn't, request a new source.
