### ISSUE TITLE
Arçura Fansub

### ISSUE THREAD

**Issue by Slnzafr** [tachiyomiorg/tachiyomi-extensions#15923]
### Source name

Arçura Fansub

### Source link

https://arcura.me/

### Language

Turkish 

### Other details

18+/NSFW= YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by 7Nekoma** [comment]
> ### kaynak adı
> Arçura Fansub
> 
> ### kaynak bağlantı
> https://arcurafansub.com/
> 
> ### Dil
> Türkçe
> 
> ### Diğer detaylar
> 18+/NSFW= EVET
> 
> ### teşekkürler
> * [x] Mevcut sorunları araştırdım ve bu yeni bir bilet, yinelenen veya başka bir açık veya kapalı sorunla ilgili **DEĞİLDİR .**
> * [x] Kaynak adıyla bir başlık yazdım.
> * [x] Uzantının [web sitesi uzantıları listesinde](https://tachiyomi.org/extensions/) veya uygulamada mevcut olmadığını kontrol ettim.
> * [x] [GitHub deposunu](https://github.com/tachiyomiorg/tachiyomi-extensions/) arayarak uzantının mevcut olmadığını kontrol ettim ve kod tabanında görünmediğini doğruladım.
> * [x] Bu formda istenen tüm bilgileri dolduracağım.

**Comment by vetleledaal** [comment]
domain is parked
