### ISSUE TITLE
Mangazodiac

### ISSUE THREAD

**Issue by VDT1ST** [tachiyomiorg/tachiyomi-extensions#15928]
### Source name

Mangazodiac

### Source link

https://mangazodiac.com/

### Source language

VIETNAMESE

### Other details

18+/NSFW= YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by VDT1ST** [comment]
I WANT TO CHANGE THE LANGUGE PART OF #15927 TO VIETNAMESE SO I POST THIS AGAIN.

**Comment by curche** [comment]
I think you could have just Edited your other issue
Anyways, i've closed that one and will keep this one open

**Comment by beerpiss** [comment]
Uses MangaThemesia
