### ISSUE TITLE
Omega Scans: changed to Hean CMS

### ISSUE THREAD

**Issue by Eliasfrost** [tachiyomiorg/tachiyomi-extensions#15949]
### Source information

Omegascans 1.4.25

### Source language

English

### Steps to reproduce

Extension not working

### Expected behavior

Extension in working condition

### Actual behavior

Extension not usable

### Tachiyomi version

App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z) Android version: 11 (SDK 30) Android build ID: RMX1971_11_F.06 Device brand: realme Device manufacturer: realme Device name: RMX1971 Device model: RMX1971 Device product name: RMX1971

### Android version

Android 11

### Other details

Omega scans updated their website so the old extension is not useful now and a new one is needed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Eliasfrost** [comment]
N

**Comment by stevenyomi** [comment]
/edit-title "Omega Scans: changed to Hean CMS"
