### ISSUE TITLE
Mangabuddy: chapters don't match title

### ISSUE THREAD

**Issue by Yukiya070** [tachiyomiorg/tachiyomi-extensions#15958]
### Source information

Mangabuddy 1.4.14

### Source language

English

### Steps to reproduce

.

### Expected behavior

The titles and the chapters inside the manga are the same

### Actual behavior

The titles and the chapters and story inside the manga are different. Not the same.

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Please provide a manga as an example and provide screenshot.

**Comment by kmsheth** [comment]
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/33102803/547b6919-1805-4550-9a23-abe0cb97044b)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/33102803/0f998514-da33-4415-b676-aada8204d08f)
Manga name: 1/24 Romance

**Comment by alekc** [comment]
This is not an extension issue (strictly speaking). Site's api on the page https://mangabuddy.com/api/manga/1-24-romance/chapters?source=detail returns 7 chapters from wrong manga
