### ISSUE TITLE
禁漫天堂搜索问题

### ISSUE THREAD

**Issue by huajideshutiao** [tachiyomiorg/tachiyomi-extensions#15957]
### Source information

Jinman Tiantang 1.4.35

### Source language

Chinese

### Steps to reproduce

使用jm号搜索（形如jm123456或123456，网页两种皆可）

### Expected behavior

能显示jm号对应的漫画

### Actual behavior

空白/无漫画

### Tachiyomi version

0.14.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Endowpea** [comment]
输入JM:123456搜索对应JM号可以搜到

**Comment by huajideshutiao** [comment]
> 

确实
那能否优化成和网页相同的行为？毕竟有时候看到id想不起来要大写jm加上冒号
