### ISSUE TITLE
Senkuro (ru)

### ISSUE THREAD

**Issue by shzchi** [tachiyomiorg/tachiyomi-extensions#15983]
### Source name

Senkuro

### Source link

https://senkuro.com

### Source language

Russian 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
What is remarkable it?

**Comment by shzchi** [comment]
> What is remarkable it?
> 
> Discussed and tested extensions here [@Tachiyomi_RUS](https://t.me/Tachiyomi_RUS)

This site is quite recent and therefore not very popular, but some people are already moving to it in the same way they are to manga. ovh. People start moving to other sites for many reasons.

**Comment by Timur-0** [comment]
The Senkuro website is a modern platform for reading manga, ranobae and comics. It offers users the opportunity to read manga and other materials online in Russian, with convenient functionality and regular updates of translations of the world's most popular manga.Thus, Senkuro is noteworthy for its aim to provide convenient reading of manga and comics in Russian, as well as for its rapid content updates, making it an attractive choice for fans of Asian culture and manga.

**Comment by SterbenS6** [comment]
developers please add source senkuro

**Comment by SterbenS6** [comment]
developers please add source

**Comment by SterbenS6** [comment]
developers add this source

**Comment by SterbenS6** [comment]
разработчики добавьте это источник ?

**Comment by SterbenS6** [comment]
when will the source be added?
