### ISSUE TITLE
Source change of Toongod

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi-extensions#15980]
### Source information

ToonGod 1.4.32

### Source language

English

### Source new URL

https://www.toongod.org/home/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by OncePunchedMan** [comment]
while the url to the homepage changed. it didn't for requests like popularMangaRequest and such.
However i found that the site uses heavy cloudflare protection

**Comment by kingmj2000** [comment]
the url I have mentioned has minimum cloudflare bypass failures, I have even tried it one other phones, if opened using the https://www.toongod.org/home/

it has less failures compared to default toongod.prg or toongod.com
