### ISSUE TITLE
Add Option to Hide Categories

### ISSUE THREAD

**Issue by Kentemman** [tachiyomiorg/tachiyomi-extensions#15991]
### Source name

Category

### Source language

English

### Describe your suggested feature

The suggested feature is to add an option for users to hide certain categories. Currently, the app does not have this functionality, and users have to scroll through all categories to find the ones they are interested in.

By adding this feature, users will have more control over their reading preferences and can customize the app to suit their needs. The option to hide categories can be either permanent or temporary, depending on the user's preference.

This feature would improve the user experience of Tachiyomi and make it more user-friendly and customizable. Therefore, I would like to request that the Tachiyomi development team consider adding this feature in a future update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
You should open the issue in app repository. Nonetheless, this is a duplicate requests that was rejected, see https://github.com/tachiyomiorg/tachiyomi/issues/1508#issuecomment-899064847.
