### ISSUE TITLE
Official MangaPlus posts on MangaDex no longer work

### ISSUE THREAD

**Issue by DatHypnoboi** [tachiyomiorg/tachiyomi-extensions#16001]
### Source information

MangaDex 1.4.177

### Source language

English

### Steps to reproduce

1. Open series with official MangaPlus posts, such as Kuchi ga Saketemo Kimi Ni Wa or Blue Box
2. Try to read or download an official chapter

### Expected behavior

The chapter should be openable and downloadable like they used to be

### Actual behavior

A 404 error is thrown

### Tachiyomi version

TachiyomiSY 1.9.0 Preview r504

### Android version

Android 12

### Other details

Base Tachiyomi doesn't seem to show official posts on Mangadex, so this has only been tested on SY, but it seems to be an extension issue rather than an app issue, hence posting this here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
MangaDex just gives you a link to Manga Plus. Use Manga Plus extension to read those chapters.

As for TachiyomiSY - it has its own features related to MangaDex and Manga Plus. If it doesn't work correctly - report it to TachiyomiSY.
