### ISSUE TITLE
PhoenixManga

### ISSUE THREAD

**Issue by Lenoyr** [tachiyomiorg/tachiyomi-extensions#16007]
### Source name

Phoenixmanga

### Source link

https://phoenixmanga.com/

### Source language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by seba1107** [comment]
This is not a source request, it's a domain change.

**Comment by Lenoyr** [comment]
> This is not a source request, it's a domain change. The extension name is "Phoenix Fansub". Spanish language.
No, "Phoenix Fansub" is "https://phoenixmangas.com/", "Phoenixmanga" is "https://phoenixmanga.com/", the detail is in the "s"

"Phoenix Fansub"
![imagen](https://user-images.githubusercontent.com/65477084/232690983-d8f14d10-df92-4c48-9cc3-ce49995e2655.png)

"Phoenixmanga"
![imagen](https://user-images.githubusercontent.com/65477084/232691016-9072e63e-1452-4224-8971-f5468474aa79.png)

**Comment by edmxn** [comment]
> > This is not a source request, it's a domain change. The extension name is "Phoenix Fansub". Spanish language.
> > No, "Phoenix Fansub" is "https://phoenixmangas.com/", "Phoenixmanga" is "https://phoenixmanga.com/", the detail is in the "s"
> 
> "Phoenix Fansub" ![imagen](https://user-images.githubusercontent.com/65477084/232690983-d8f14d10-df92-4c48-9cc3-ce49995e2655.png)
> 
> "Phoenixmanga" ![imagen](https://user-images.githubusercontent.com/65477084/232691016-9072e63e-1452-4224-8971-f5468474aa79.png)

The web belongs to the same fansub, Phoenix Fansub, on the previous website (which is now inaccessible) they say they changed their domain.

**Comment by vetleledaal** [comment]
Site is down, error code: 502
