### ISSUE TITLE
WestManga: Manga Title "Title Not Found" makes all manga to 1 if they are on 1 source

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#16010]
### Source information

WestManga 1.4.26

### Source language

Indonesia 

### Steps to reproduce

- Add this manga
https://westmanga.info/manga/my-daughter-is-the-final-boss/
- Download all chapter (if you want)
- Then add this manga
https://westmanga.info/manga/perfect-surgeon/

### Expected behavior

Fixed the title on the 2 manga so that it doesn't have the title "Title Not Found"

### Actual behavior

The 2 manga will be 1 because they have the same title, namely "Title Not Found"

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

For more details, you can see this video 

https://user-images.githubusercontent.com/50316075/230750699-3bb63e6e-2869-4763-a921-568ecc5ae457.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rewtio** [comment]
URL [https://westmanga.info/manga/my-daughter-is-the-final-boss/](https://westmanga.info/manga/my-daughter-is-the-final-boss/) is redirected to 404 page

The issue is no longer can be reproduce, 
Did it still occur in some other manga?

**Comment by TheKingTermux** [comment]
Maybe it still occur, but i didn't find a `Title Not Found` Manga/Manhua/Manhwa on it
Soo closing for now
If it still occurred when i search another `Title Not Found` i Will opened this Issue again
