### ISSUE TITLE
Manga-TR Chapters won't load

### ISSUE THREAD

**Issue by vBrash** [tachiyomiorg/tachiyomi-extensions#16013]
### Source information

Manga-TR

### Source language

Turkish

### Steps to reproduce

Try to read any manga on Manga-TR
![Screenshot_20230409_202118_Tachiyomi](https://user-images.githubusercontent.com/53212046/230787042-ed4dd4dd-af00-4972-bc21-7cce96afdb9b.jpg)

### Expected behavior

Chapters should seen and readable

### Actual behavior

It just shows logo of Manga-TR
![Screenshot_20230409_201842_Tachiyomi](https://user-images.githubusercontent.com/53212046/230786981-2eb04968-baf4-434c-ab3f-4e082ade9bee.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArminArlert31** [comment]
still ongoing

**Comment by Tarik366** [comment]
Actual problem causing by site,

First i think that causing by user agent and i try in a working user agent. But it didn't works in app. So i think that causing by sites move sensitive security

The Webwiew doesn't loads the site.
<img alt="Screenshot_2023-10-21-08-39-58" src="https://github.com/tachiyomiorg/tachiyomi-extensions/assets/67359075/b1a18a4d-a0ce-42c2-b0b5-d2b7fee6fa53" width="400">

Expected output:
 
<img alt="Screenshot_2023-10-21-08-42-27" src="https://github.com/tachiyomiorg/tachiyomi-extensions/assets/67359075/b3b3b6a0-24dc-486a-b8e9-9e352cd4a358" width="400">

<img alt="Screenshot_2023-10-21-08-42-31" src="https://github.com/tachiyomiorg/tachiyomi-extensions/assets/67359075/0a667cf5-a6b5-4fa7-a8de-e6d2212851e1" width="400">
