### ISSUE TITLE
Manga-FR

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#16022]
### Source name

Manga-FR

### Source link

https://manga-fr.me/

### Source language

French

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by AlCiavi** [comment]
What improvement this source brings compared to the existing ones?

**Comment by Mitia99** [comment]
@AlCiavi It's one of the only two sources I found which uploads Solo leveling in French (the other one is [Sololevelingscan](https://ww4.sololevelingscan.com/)

**Comment by AlCiavi** [comment]
@Mitia99 Sushi-Scan does upload Solo Leveling no?

**Comment by Mitia99** [comment]
@AlCiavi I didn't know that source. I tried searching "Solo leveling scan vf" on google and only got the soirces I mentioned before.

Thanks for the tip.
