### ISSUE TITLE
MangaSwat: Changed their domain

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#16030]
### Source information

Mangaswat 1.3.29 arabic

### Source language

Arabic

### Source new URL

https://swatmanga.me/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by M0GALAL** [comment]
https://swatmanga.me/
