### ISSUE TITLE
Bato.to Pages Failing to load.

### ISSUE THREAD

**Issue by HaarisAhmed2001** [tachiyomiorg/tachiyomi-extensions#16037]
### Source information

Bato.to 1.4.31

### Source language

Multi

### Steps to reproduce

1. Select a series in your library or on your updates page which has bato.to as it's source.
![Screenshot_20230411-184630_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305140-357f65c0-bfe3-469f-87be-d54f257a492a.jpg)
![Screenshot_20230411-184642_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305275-cfed10db-1647-48a5-950e-ffc4f238fbf8.jpg)

2. (Optional) update/reload the page.
![Screenshot_20230411-184646_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305294-ae5683e4-800a-4a92-b7d6-f0c43b36b5c9.jpg)

3. Pick any chapter available. 
![Screenshot_20230411-184702_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305361-da86373f-d77e-4e91-9ebd-76b97939f8e7.jpg)

4. Wait for pages to load in.
![Screenshot_20230411-184717_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305397-4912c827-371b-445a-b7b2-c79f08a0b680.jpg)

5. (Optional) check if pages are fine by clicking the web view option and checking on the original pages.
![Screenshot_20230411-185141_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305564-7d582dc2-51bd-4690-9c74-bf24f75e49e6.jpg)
![Screenshot_20230411-185155_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305597-7b400e3b-3851-4377-ac61-028c765f0f96.jpg)

### Expected behavior

All of the pages within that chapter should be loading up or fully loaded in.
![Screenshot_20230411-185155_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305658-2c4c051c-0570-4644-a44f-7859b934c38f.jpg)

### Actual behavior

Only a few pages will load in, after those first few are loaded, the following pages will only show errors, reloading them does not work.
![Screenshot_20230411-184717_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305713-9e1735c1-6816-4f1d-a1b3-2f7b722d55fa.jpg)
![Screenshot_20230411-184733_Tachiyomi](https://user-images.githubusercontent.com/60004984/231305739-5d297f24-ac9d-4ee5-a2bd-8b36f35365d6.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> I have tried the troubleshooting guide.

Bato.to returns temporary links for pages, and it should be solved by following the troubleshooting guide. Did you actually try the guide?

**Comment by HaarisAhmed2001** [comment]
Never mind, I found the fix, I apologize for the post
