### ISSUE TITLE
Add Extension Setting to Change URL for MangaSwat

### ISSUE THREAD

**Issue by slimessan** [tachiyomiorg/tachiyomi-extensions#16048]
### Source name

Mangaswat

### Source language

Arabic

### Describe your suggested feature

There are extensions that change the link periodically.
Therefore, I suggest adding a feature in the extension settings allowed to manually modify a link without waiting for an update
 wanted a setting to change url without updating extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
false positive by the bot as that wasn't the intention of the request. Reopening

**Comment by curche** [comment]
/edit-title "Add Extension Setting to Change URL for MangaSwat"
