### ISSUE TITLE
Ghost Download

### ISSUE THREAD

**Issue by Kahgae** [tachiyomiorg/tachiyomi-extensions#16040]
### Source information

None

### Source language

English

### Steps to reproduce

1. Click "download" 
2. In "Downloads"; Bleach Chapter 605: 5/13, 6/13 etc.
3. Download 100%
4. Section becomes blank in order to signify that the downloads are done.

### Expected behavior

In other words, when I download something ,sometimes it get stuck at 100% (e.g 13/13). Sometimes, pausing it and resuming it works. But most of the time, I have to restart the app in order to restart the download. Kind of like ghost downloading.

### Actual behavior

"Ghost" Download
1. Download 6/13
2. Finish Download 13/13
3. Issue: Stays at 13/13
4. Restart app
5. Downloads are paused and have to resume all downloads again

### Tachiyomi version

 0.14.5 

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
You're supposed to fill in `Source information` information when reporting extension bugs. If you're reporting app bug, you should do it in the app repository - https://github.com/tachiyomiorg/tachiyomi/issues/new/choose

Try disabling `Save as CBZ archive`. It looks like your device takes a while to compress downloaded images into cbz.
