### ISSUE TITLE
Obsolete Extensions 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [tachiyomiorg/tachiyomi-extensions#16054]
### Source name

Comick, holy manga, manga buddy, bato.to, mangadex and manga pill

### Source language

English

### Source link

N/A

### Other details

![Screenshot_20230413_194808](https://user-images.githubusercontent.com/104534608/231906926-867d976b-92e9-46ed-84a3-a24ea250ce14.png)

May, someone tell me why all six of my favorite extensions are declared as obsolete? I've been using them from morning to afternoon today. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You disabled 18+ extensions on settings, enable it in order to use 18+ extensions.
