### ISSUE TITLE
Manga16fx Browsing not working

### ISSUE THREAD

**Issue by Baymax325** [tachiyomiorg/tachiyomi-extensions#16055]
### Source information

Manga18fx

### Source language

English

### Steps to reproduce

1. I tried searching the title and a blank page appears
2. Tried to search in WebView and it worked just fine
3. Reinstalled the extension and tried searching again, the same thing happened in step 1

### Expected behavior

Should be able to browse

### Actual behavior

Can't browse 

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. What keyword did you search with?

**Comment by Baymax325** [comment]
Try searching for a manhwa like solo leveling, overgeared, etc.. Some of the title work but mkst don't.

**Comment by stevenyomi** [comment]
Sorry I was using 1.3.x but this issue was introduced when it was bumped to 1.4.x. This is the same as #15571.

**Comment by Baymax325** [comment]
Did it get updated? I can't download the extension

**Comment by stevenyomi** [comment]
It should be fixed in v1.4.33. Restart your app and wait until the update shows in your extension list.
