### ISSUE TITLE
FreeMangaTop: Opt-out from manga-entries filter

### ISSUE THREAD

**Issue by K3end0** [tachiyomiorg/tachiyomi-extensions#16057]
### Source information

FreeMangaTop 1.4.29

### Source language

English

### Steps to reproduce

1. Open the source in "browse" or try to search for a comic in the source.
2. Notice it doesnt work and only shows 5 comics.
3. Go into "filter" and disable "show only manga entries".
4. Source now works.

### Expected behavior

Source should be able to show comics and allow for searching.

### Actual behavior

Source doesnt work and can only show 5 comics with the "show only manga entries" option enabled. 

### Tachiyomi version

Stable 0.14.5

### Android version

Android 13

### Other details

Attached below is a before image with "show only manga entries" enabled, and after image with the option disabled.
Before
![Before](https://user-images.githubusercontent.com/71897667/232048305-99492d9e-3af0-41f7-b4c6-06fd9b055e1b.jpg)

After
![After](https://user-images.githubusercontent.com/71897667/232048311-87607f8a-ad05-4ad0-95d9-da53b8002990.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#16062
