### ISSUE TITLE
Doujindesu url not found

### ISSUE THREAD

**Issue by Nvbeh6** [tachiyomiorg/tachiyomi-extensions#16064]
### Source information

Doujindesu 1.4.3

### Source language

Indonesia 

### Steps to reproduce

1.Open Doujindesu
2.Open Any Chapter
3.Error (Page Not Found)

### Expected behavior

Show the chapter

### Actual behavior

Page Not Found 

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by OncePunchedMan** [comment]
Working fine for me, try a vpn or dns over https

**Comment by TheKingTermux** [comment]
Yup also working for me in Indonesia (using VPN)
