### ISSUE TITLE
Cerise Scans: Failing to build chapter URLs

### ISSUE THREAD

**Issue by Niinh4** [tachiyomiorg/tachiyomi-extensions#16060]
### Source information

Cerise Scans 1.4.32

### Source language

Português 

### Steps to reproduce

![Screenshot_20230414_232927_Tachiyomi](https://user-images.githubusercontent.com/130812238/232179525-5eefe811-fab1-40ae-8dbc-84cdae0e50da.jpg)

1- click to download
2- the issue on the screenshot appear 

### Expected behavior

the chapter should download 

### Actual behavior

the chapter don't download 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Erick17x** [comment]
Estou com o mesmo problema, todos os meus mangas dão este erro

**Comment by alessandrojean** [comment]
Not able to reproduce, it might be some temporary issue with their site. If it happens again, please open a new issue.
