### ISSUE TITLE
LeerCapitulo: Pages are in wrong order

### ISSUE THREAD

**Issue by TUMAWA** [tachiyomiorg/tachiyomi-extensions#16070]
### Source information

LeerCapitulo

### Source language

Español

### Steps to reproduce

Cuando cargo el capitulo las páginas estan desordenas la última página aparese al principio y las demas estan. escladas.

### Expected behavior

Debería aparecer ordenado

### Actual behavior

Su cedió al cargando el capitulo

### Tachiyomi version

Stable 0.14.5

### Android version

Android 13

### Other details

Al parecer solo pasa con la extensión de leerCpitulo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DarkDissaster** [comment]
La versión en español está igual y cuando se entra en Webview las páginas del capítulo salen ordenadas, sólo en la aplicación están mal
