### ISSUE TITLE
VIZ Shonen Jump: File Format could not be determined

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#16074]
### Source information

VIZ Shonen Jump 1.4.5

### Source language

English

### Steps to reproduce

Attempt to download a series

### Expected behavior

Should download

### Actual behavior

Download fails "File Format could not be determined"

### Tachiyomi version

r5707

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do provide examples of series and chapters where this happens.

**Comment by kiriya-aoi** [comment]
Kill Blue ch 1, Tenmaku Cinema ch 1, ch 2, Blue Box ch 1-3, ch 95-97, etc. (these being the ones I just checked).

This first started happening in TachiyomiSY [a few weeks back](https://discord.com/channels/349436576037732353/566585518171881493/1090705102756663338) and in Tachiyomi Preview as of r5707. This is specifically for downloads, reading works fine.
