### ISSUE TITLE
YugenMangas Error 400 downloading some chapters

### ISSUE THREAD

**Issue by Mariolr93** [tachiyomiorg/tachiyomi-extensions#16088]
### Source information

YugenMangas

### Source language

Spanish

### Steps to reproduce

1. YugenMangas Extension
2. Search "El retorno de una leyenda"
3. Download chapters 85, 86, 87, 88, 89
4. It gets stuck missing a page, and never finishes downloading

### Expected behavior

Download all chapter pages

### Actual behavior

It gets stuck missing a page, and never finishes downloading, and gets Error 400

### Tachiyomi version

0.14.6

### Android version

Android 13 (One UI 5.0)

### Other details

Website is good but Tachiyomi gets error 400
This does not happen in all chapters, only in some
And when viewing the chapter online, there is a page that never loads, while in webview it's fine

![Screenshot_20230418_024345_Tachiyomi](https://user-images.githubusercontent.com/19262204/232723898-122770ef-70cf-43b5-9c9f-031c043806f7.png)
![Screenshot_20230418_024355_Tachiyomi](https://user-images.githubusercontent.com/19262204/232723902-9e979618-cd94-4304-94a9-f051bb3efc57.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
That image is also broken on the website, the file itself has a ", " (kinda the same thing as some files with a dot on it, that the site refused to load) in the middle of of the image name and the website fails to load it. They need to fixed there, but someone could add another exception on the extension to skip files with "," on it.

**Comment by alessandrojean** [comment]
Closing as its a site issue. The extension shouldn't handle this particular cases as it's working as expected by showing the same error from the site.
