### ISSUE TITLE
VIZ Shonen Jump: JPEG EXIF metadata parsing failing sometimes

### ISSUE THREAD

**Issue by yuty06** [tachiyomiorg/tachiyomi-extensions#16094]
### Source information

Viz Shonen Jump 1.4.16

### Source language

English

### Steps to reproduce

1. Download manga (this instance "Kubo Won't Let me be Invisible" chapter 26 to 32)

### Expected behavior

Chapter should download

### Actual behavior

1. Download goes to last page
2. Error message (on chapter 26):  "JPEG data is expected to begin with 0xFFD8 (ÿØ) not 0x3c3f"
3. Download will never complete, stuck on last page but not pausing

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Same exact error on Aniyomi/Aniyomi beta.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Do you have any example where this occurs in a free chapter? I can't test and reproduce your issue as I don't have a subscription (and it's even region locked here).

**Comment by alessandrojean** [comment]
`0x3c3f` decodes to `<?` which could be the beginning of an HTTP 403 response (which is in HTML), as it happened in the past (#5622). A next extension version might fix by showing a proper error, but this is likely VIZ side, and they need to fix it. You can confirm this by opening the chapters in WebView and checking if all pages are loading; if they're not loading in WebView or a browser, the only thing you can do is waiting for them to fix it or contact their support to report this issue.

**Comment by yuty06** [comment]
> Do you have any example where this occurs in a free chapter? I can't test and reproduce your issue as I don't have a subscription (and it's even region locked here).

Sadly all the other chapters work, same for other manga's free chapters

**Comment by yuty06** [comment]
> `0x3c3f` decodes to `<?` which could be the beginning of an HTTP 403 response (which is in HTML), as it happened in the past (#5622). A next extension version might fix by showing a proper error, but this is likely VIZ side, and they need to fix it. You can confirm this by opening the chapters in WebView and checking if all pages are loading; if they're not loading in WebView or a browser, the only thing you can do is waiting for them to fix it or contact their support to report this issue (without mentioning the extension as it goes against their ToS and they could ban your account).

It seems to work in browser, although ive noticed Viz has a high page count than tachiyomi

**Comment by alessandrojean** [comment]
Can you update your extension and try to download again and tell what errors are you getting?

**Comment by yuty06** [comment]
> Can you update your extension and try to download again and tell what errors are you getting after the update, if any?

Sorry for the late reply. It still isn't working, but now the error message I get when trying to download is: "something went wrong while trying to fetch the page."

**Comment by alessandrojean** [comment]
Yeah, this confirm my theory. It's the error thrown now when the image is broken or returning an error, and nothing can be done on the extension side to fix it as it's an error with the website itself. You need to wait for them to eventually fix it.

In the meanwhile, you can probably read these chapters without downloading. Thanks for testing again, though, appreciated.

**Comment by yuty06** [comment]
> Yeah, this confirm my theory. It's the error thrown now when the image is broken or returning an error, and nothing can be done on the extension side to fix it as it's an error with the website itself. You need to wait for them to eventually fix it.
> 
> In the meanwhile, you can probably read these chapters without downloading, by skipping the pages that have issues. Thanks for testing again, though, appreciated.

Le big rips, thanks a bunch for trying though. Have a great one
