### ISSUE TITLE
CosmicScans: HTTP error 404

### ISSUE THREAD

**Issue by Indra9158** [tachiyomiorg/tachiyomi-extensions#16091]
### Source information

CosmicScans.id 1.4.26

### Source language

Indonesia

### Steps to reproduce

can't open it in tachiyomi but it can in webview
![Screenshot_2023-04-18-21-48-40-869_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/131175266/232806041-f7bf47a5-7723-4a73-a1f6-ecdcd27d2335.jpg)

### Expected behavior

this extension can open in tachiyomi, and i moved to TachiyomiJ2K

### Actual behavior

but when i instal/movedl in TachiyomiJ2K, the extension can't open and it's says HTTP error 404, and when i open webview it can.

### Tachiyomi version

TachiyomiJ2K v1.6.5

### Android version

Android 9

### Other details

actually i use Redmi 6A and the MIUI version it's MIUI Global 11.0.8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by julptk** [comment]
same
