### ISSUE TITLE
Some entries on bato.to do not load and are stuck loading indefinitely

### ISSUE THREAD

**Issue by sillysack69** [tachiyomiorg/tachiyomi-extensions#16092]
### Source information

Bato.to 1.4.31

### Source language

English

### Steps to reproduce

1. Search for Hayate no Gotoku! (Official) or Tomb Raider King [Official] or Release That Witch (Official) or The Great Wish
2. Click on their entry

### Expected behavior

The entry should load quickly along with the cover, description, and chapter list, without any spinning icon hovering above indefinitely.

### Actual behavior

Entry loads the chapter list (which works and chapters can be read from within the app) but cover often fails to load and descriptions do not load. The loading icon keeps spinning indefinitely. WebView works fine. All other bato.to entries load and work just fine. It's these two in particular that behave like this.

### Tachiyomi version

0.14.6

### Android version

Android 8

### Other details

I think this problem only arises on entries with a lot of chapters (all of the above series have >300 chapters). curche on discord tachiyomi support pointed out that sket dance does not work either and has around 280 chapters,
EDIT: The Great Wish has 142 chapters and displays this problem as well. So just wanted to add that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Won't fix - 51f35d8d755b798b7430e3ca42185861ce842ef6
