### ISSUE TITLE
Crash on Luscious when I disabled the transitions between chapter 

### ISSUE THREAD

**Issue by Gerardalbert21** [tachiyomiorg/tachiyomi-extensions#16109]
### Source information

Luscious 1.4.19

### Source language

Multiple

### Steps to reproduce

1. Choose one entry on the extension Luscious
2. Disable the transitions between chapter
3. Choose a chapter and read multiple chapter
4. Tachiyomi SY crash

### Expected behavior

I can view all chapter without tachiyomi sy crashing

### Actual behavior

Tachiyomi SY crash after a few chapter 

### Tachiyomi version

SY 1.9.3 preview 508

### Android version

Android 13

### Other details

Only on tachiyomi SY

https://user-images.githubusercontent.com/88115070/233408987-2ac43113-bf7d-4c52-b429-a5655eccc893.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gerardalbert21** [comment]
Also on kemono party

**Comment by alessandrojean** [comment]
Assuming this is Tachiyomi SY specific as it happens on more than one extension. Open an issue in Tachiyomi SY repository about it.
