### ISSUE TITLE
Mangkomik: Changed their name and domain

### ISSUE THREAD

**Issue by AyiJr** [tachiyomiorg/tachiyomi-extensions#16116]
### Source information

MangKomik v1.4.26

### Source language

Indonesian

### Source new URL

https://sirenkomik.my.id/

### Other details

Mangkomik change name and chance domain to Sirenkomik

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Aerty-G** [comment]
Still No update huh?
