### ISSUE TITLE
KissKH

### ISSUE THREAD

**Issue by Redowansky** [tachiyomiorg/tachiyomi-extensions#16120]
### Source information

KissKH 13.1

### Source language

English

### Source new URL

https://kisskh.co

### Other details

This site is used for  watching Chinese and korean drama/movies, suddenly 3 days ago,the extension stopped working, After i got to know they've changed their domain,
Before it was: "kissKh.me"

Now it's:kisskh.co
I've fixed the extension by editing the extension app, signed the app with testkey, please upload the fixed Extension on your source server.
![Screenshot_20230421-133828](https://user-images.githubusercontent.com/117475214/233601325-d2b47306-ff80-44b1-b1ef-0ab4de9da3c0.png)

[Fixed Extension](https://doodrive.com/f/2d7kd1) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Tachiyomi doesn't support video streaming.

**Comment by Redowansky** [comment]
sorry I've posted on wrong place
