### ISSUE TITLE
Raijin Scans

### ISSUE THREAD

**Issue by Chikimaro** [tachiyomiorg/tachiyomi-extensions#16129]
### Source name

Raijin Scans

### Source link

http://raijinscans.fr/

### Source language

French

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
There is an issue with the certificate : Chain validation failed while trying to implement the extension. It's not on Tachiyomi's side.
Uses Madara theme.

**Comment by Kreliam** [comment]
> There is an issue with the certificate : Chain validation failed while trying to implement the extension. It's not on Tachiyomi's side. Uses Madara theme. We'll probably need to wait until Raijinscans renew their certificate.

excusez moi kirin tu a revérifier  le certificat de RaijinSans 🤔 ?

**Comment by KirinRaikage** [comment]
Je viens de regarder, ça marche ! J'implémente ça dès que possible :D

**Comment by Kreliam** [comment]
> Je viens de regarder, ça marche ! J'implémente ça dès que possible :D

Merci beaucoup kirin  ,  tu est un boss  👌

**Comment by Kreliam** [comment]
@Chikimaro

**Comment by Chikimaro** [comment]
Parfait ! Merci bg.
