### ISSUE TITLE
Sushi-Scan [FR] - User agent, Cloudflare, http and https

### ISSUE THREAD

**Issue by AlCiavi** [tachiyomiorg/tachiyomi-extensions#16124]
### Source information

Sushi-Scan 1.4.28

### Source language

French 

### Steps to reproduce

This is a complex problem. I will explain it in the details at the end. I'm just trying to read old sources from Sushi-Scan. Actually I already had this problem I solved on my own a while ago.
Some sources have images in http instead of https in their address. 
For example : go to Sushi-Scan, source Berserk, try to open volume 1 to 41, it will fail even in WebView, but the last chapters will load. 

### Expected behavior

Once Cloudflare is bypassed, it should load the scan like in actual browser. 

### Actual behavior

Some scans don't work in WebView and in the app but load in browser. I'll explain the entire issue below. 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Hello,
First of all, I already had some problems a while ago with Sushi-Scan. Some sources on the site have images in http instead of https (the 1st volumes of Berserk, Alice in Borderland, Hokuto no Ken Ultimate, the 1st volumes of One Piece, etc), it is this discovery that allowed me to understand that Tachiyomi and WebView had a problem to display images in http coming from Sushi-Scan.
At that point, my solution was to find a random user agent in the extension's settings until I found this one that worked: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/ 537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0 (YX GX Edition)"

Except that since this morning, Sushi-Scan has increased its Cloudflare protection and only this user agent that I use for all my extensions works "Mozilla/5.0 (Linux; Android 13; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36" to override Cloudflare. All user agents get the error "java.io.IOException: Failed to bypass Cloudflare" even if I override Cloudflare via WebView. The problem is that even with WebView and the previous user agent I was using to display the images in http, it doesn't work anymore.

Besides Cloudflare, because I know that Tachiyomi can't do much about it (even if I manage to override it with a specific user agent), can you tell me with which user agent I can read the http images with WebView and thus in Tachiyomi?

Sushi-Scan is by far the best French extension and without it we quickly find ourselves very limited in source...
Thank you very much for reading and for your help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AlCiavi** [comment]
Don't close it Cloudflare is only mentioned

**Comment by AlCiavi** [comment]
I'll repoen it

**Comment by AlCiavi** [comment]
@alessandrojean Can I at least ask some questions? 
Why is Sushi-Scan the only extension I know where you can change the user agent only for the extension and have a random one at each startup? 
Are other users experiencing the same problems as me? 
Thanks for your answers.

**Comment by stevenyomi** [comment]
> Why is Sushi-Scan the only extension I know where you can change the user agent only for the extension and have a random one at each startup?

Some extensions use this strategy while others don't. However, this does not always work. Wait for them to lower protection and stop commenting on closed issues.
