### ISSUE TITLE
KomikCast.net

### ISSUE THREAD

**Issue by Raeliuss** [tachiyomiorg/tachiyomi-extensions#16128]
### Source information

Komik Cast 1.4.43

### Source language

Indonesia

### Source new URL

https://komikcast.net

### Other details

Komikcast.net is a newer and more updated resource than Komikcast.site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Raeliuss** [comment]
please change the URL source to https://komikcast.io, it's the newest one

**Comment by Seishirou101** [comment]
it is already komikcast.io, i will close this as it seems .net is no longer relevant.
