### ISSUE TITLE
Komga: Add support to AVIF images

### ISSUE THREAD

**Issue by DeuvsTer** [tachiyomiorg/tachiyomi-extensions#16133]
### Source name

Komga

### Source language

English

### Describe your suggested feature

Please add support for the avif format on the client side when reading from the Komga server in Tachiyomi.

### Other details

https://github.com/gotson/komga/issues/942#issuecomment-1518479407 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I'm wondering whether the Tachiyomi app could provide a list of supported media types, so we could replace https://github.com/tachiyomiorg/tachiyomi-extensions/blob/3f1137cba5ff1acadf5304024663ea6b12eb0db0/src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt#L631

**Comment by gotson** [comment]
@arkon do you think exposing the supported image formats to extension could be considered ?

**Comment by arkon** [comment]
Yes we can provide a list of MIME types, but that'd have to be a new version of the extensions-lib, which would require a new  stable app version with a minimum extension-lib version bump.

You'd be better off doing it in the extension for now until that's available.

**Comment by gotson** [comment]
> Yes we can provide a list of MIME types, but that'd have to be a new version of the extensions-lib, which would require a new stable app version with a minimum extension-lib version bump.
> 
> You'd be better off doing it in the extension for now until that's available.

That's what i thought. I just sent a PR, but if we can prepare for the future (no rush), so at some point we can remove that code, that would be appreciated.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/commit/ccd4143d9dc839f9246b405e98f5bad1770ba302
