### ISSUE TITLE
Manhwa/webtoons resolution 

### ISSUE THREAD

**Issue by Damineflir** [tachiyomiorg/tachiyomi-extensions#16130]
### Describe why this should be added

![Screenshot_20230421-225029](https://user-images.githubusercontent.com/131507935/233761465-5ce807ba-49c4-495b-b80a-462069e8afc5.png)
This kind of thing needs to be fixed on some sources. They cut a break changing the resolution almost every other "page" so it's irritating and a pain to read when they cut the bubbles him half or cut a facial reaction on some of the pictures.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Damineflir** [comment]
![Screenshot_20230421-231253](https://user-images.githubusercontent.com/131507935/233761771-8b5581c3-7198-423f-bb51-5596540dad08.png)
Heres another example of wtf

**Comment by Seishirou101** [comment]
turn off crop borders
