### ISSUE TITLE
S2Manga: image couldn't be loaded

### ISSUE THREAD

**Issue by Yumicakes017** [tachiyomiorg/tachiyomi-extensions#16144]
### Source information

Manhua Sy 1.4.29, S2Manga 1.4.29

### Source language

English 

### Steps to reproduce

1.I tried reloading it
2.Then check If I need to bypass cloudflare in the website 
3.Clear the cache
4.Un-install and Re-install the extension 
5.Try reloading it again 

### Expected behavior

Show images 

### Actual behavior

It show "The image couldn't be loaded" instead

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Manhua SY is reported in #16018
