### ISSUE TITLE
MangaHub: Unable to Read Manga/Manhwa

### ISSUE THREAD

**Issue by PheonixGamer09** [tachiyomiorg/tachiyomi-extensions#16140]
### Source information

Mangahub 1.4.27(English)

### Source language

English

### Steps to reproduce

1. It shows " The image couldn't be loaded" when manga/manhwa old and new chapters are open on Tachiyomi app.
2. Some pages of manga/manhwa pages shows images issue.
3. It shows "No page found" when new manga/manhwa chapters are open on Tachiyomi app.
4. When new manga/manhwa chapter open it shows no page found.
4. On website it shows all images and page without any problem.

### Expected behavior

1. Normally in mangahub extension when opened any manga chapter it shows all uploaded images just as websites.
2. All images and pages should have been uploaded perfectly and properly without any problem in manga/manhwa of every chapters.

### Actual behavior

1. Images of 2-3 pages are not loaded on chapters of manga/manhwa.
2. New manga/manhwa chapter shows no page found.
![image](https://user-images.githubusercontent.com/128516302/233837839-7bbcc5fd-0475-4342-9328-7a12ab56379c.png)
![image](https://user-images.githubusercontent.com/128516302/233837864-5346692a-9b55-4a32-9e14-6def51abef36.png)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

![image](https://user-images.githubusercontent.com/128516302/233838020-bb4ec209-3cd9-45f7-9910-108f9824b1e0.png)

![image](https://user-images.githubusercontent.com/128516302/233837994-6272f0af-95de-4319-97c3-8d0ce7f3b4d8.png)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Davidbolt121199** [comment]
Plzz resolve this issue

**Comment by Davidbolt121199** [comment]
Even after update issue still continues.

**Comment by Slowlife01** [comment]
> Even after update issue still continues.
> 

Can you provide example manga
