### ISSUE TITLE
Only Manual update In Feed tab.

### ISSUE THREAD

**Issue by Raizel000** [tachiyomiorg/tachiyomi-extensions#16148]
### Describe why this should be added

Please make it so that the Feed Only update itself MANUALLY, because it automatically update itself whenever we go to feed tab, so we can't compare the Manga we have with the Mangas on different website to check which website updated it first. so please make it so that Feed tab don't update automatically.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This isn't SY

**Comment by Raizel000** [comment]
Can you give the link to where i can upload this request for Tachiyomi SY ,
because wherever i look for it, your website is opening.

**Comment by AntsyLich** [comment]
https://github.com/jobobby04/TachiyomiSY
