### ISSUE TITLE
Bento Manga: No results found

### ISSUE THREAD

**Issue by NeverReset** [tachiyomiorg/tachiyomi-extensions#16146]
### Source information

Bento Manga 1.4.11

### Source language

French

### Steps to reproduce

1. Install "Bento Manga" extension if not already installed
2. Click on "Latest" on Browse tab
3. Error: No results found
4. Try to search or select "Popular" or "Filter" tab, same error

![Popular_no_results](https://user-images.githubusercontent.com/79910346/233869940-ded18f7b-65bf-4125-a805-2f8517f9628e.png)

![Latest_no_results](https://user-images.githubusercontent.com/79910346/233869947-b019e9f1-337f-451b-ac10-4d49c60584b8.png)

### Expected behavior

It should display the list of series and the research should works

### Actual behavior

No series is displayed, you can't search for a series either in the extension or in a global search with all sources.

However, the Webview works and the chapters are updated.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mclouu** [comment]
En effet problème identique
