### ISSUE TITLE
Kunmanga "no results found" issue

### ISSUE THREAD

**Issue by Haruscream05** [tachiyomiorg/tachiyomi-extensions#16150]
### Source information

Kunmanga 1.4.29

### Source language

English

### Steps to reproduce

1. Open extension
![Screenshot_2023-04-24-17-14-14-24_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/131659066/233953322-12c29a81-18fd-419f-b83e-12cb625edfc0.jpg)
2. No results found 
![Screenshot_2023-04-24-17-14-19-52_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/131659066/233953500-03c337d9-0888-4baf-8dc9-1eab7047999d.jpg)

### Expected behavior

Shows the manga

### Actual behavior

No results found

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Haruscream05** [comment]
I got 400+ of migration if this doesn't get fixed so pls fixed it. Tnx in advance.

**Comment by stevenyomi** [comment]
Fixed by #16167.
