### ISSUE TITLE
Leviatan Scans: No Results Found

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#16152]
### Source information

Leviatan Scans 1.4.41

### Source language

English

### Steps to reproduce

Browse extension

### Expected behavior

Should load series

### Actual behavior

No results found

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

Something during the site reset broke the extension. Series who's links are the same as before still work, just no way to browse or search for new series/migration

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaDeAzure** [comment]
Just to add that it seems that Leviathan Scans is currently under maintenance and the whole extension may need to be reworked. It does seem to be using a somewhat common template as a basis, though. I believe they have almost finished their migration and are not uploading their stuff.

**Comment by alessandrojean** [comment]
They're still using Madara, it's just the same issue as #16165.
