### ISSUE TITLE
MangaRead.org No content via extension 

### ISSUE THREAD

**Issue by anarionIv** [tachiyomiorg/tachiyomi-extensions#16161]
### Source information

MangaRead.org 1.4.29

### Source language

English 

### Steps to reproduce

1. Open Tachiyomi
2. Open 'Browse' in bottom menu
3. Have 'Sources' selected in top menu
4. Find MagaRead.org Extension
5. Tap on 'Latest' or Extension Name
6. See 'No results found'

### Expected behavior

Tap on the extension name or latest should display a list of mangas and webtoons

### Actual behavior

Tapping on the extension leads to a 'No results found' error page. Checking the webview shows the Mangaread.org website is available.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by WhiskeyTango66** [comment]
I'm glad someone open ticket for this, mangaread.org was overhauling their search engine and databases, I think this was the cause that make the extension broken
