### ISSUE TITLE
ManhuaUS: No results found due to Madara update

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi-extensions#16165]
### Source information

ManhuaUS 1.4.33

### Source language

English

### Steps to reproduce

Browse -> Find ManhuaUS Extension -> Select Browse/Latest

### Expected behavior

Show Manga Catalog / Manga List

### Actual behavior

Show No Results Found

### Tachiyomi version

Preview r5725

### Android version

Android 10

### Other details

![image](https://user-images.githubusercontent.com/101858971/234103052-7d6810b6-7289-4b0f-8537-152406fe0eb8.png)
![image](https://user-images.githubusercontent.com/101858971/234103086-c955c117-c701-45b1-a34a-470f0d583ce3.png)
![image](https://user-images.githubusercontent.com/101858971/234103962-056d063a-45f9-4a92-9863-5a9f99b18fc7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
from their discord : an attack from hackers to all websites using the madara theme! It has been discovered by the theme developer and we will update the site in the next few hours!

![image](https://user-images.githubusercontent.com/101858971/234106407-24d75a66-78dc-4a4a-92d7-bae3f54182f6.png)

seems all source use Madara Theme right now all broken due update from Theme Developer , maybe related with #16162 and #16150 because use madara theme too

**Comment by alessandrojean** [comment]
I will take a look and redo the manga-entry filter if needed. For now you should be able to at least use the Popular listing by disabling the "Show only manga entries" filter.
