### ISSUE TITLE
Cover picture not loading

### ISSUE THREAD

**Issue by Moonfoxy57** [tachiyomiorg/tachiyomi-extensions#16164]
### Source information

1.4.31

### Source language

English

### Steps to reproduce

1. Cover picture are crack
2. Cover picture are blank
3. And if i want cover picture i have to update each story

### Expected behavior

In story there should be a cover picture

### Actual behavior

Cover picture are crack or black And if i want cover picture i have to update each story please fix it.

### Tachiyomi version

1.6.6

### Android version

Android 9

### Other details

I just want cover picture in all story 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by regg17** [comment]
Bato.to

**Comment by alessandrojean** [comment]
Bato.to uses temporary cover URLs that expire over time, we can't do anything about it. Refresh the covers in the advanced settings of the app periodically.
