### ISSUE TITLE
DMZJ: chapter errors of some manga in the "特殊漫画ID列表"

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi-extensions#16177]
### Source information

DMZJ 1.4.38

### Source language

中文

### Steps to reproduce

for example, the latest chapter of this manga is 15, it can be seen in the webview
![Screenshot_2023-04-25-19-56-56-274_eu kanade tach](https://user-images.githubusercontent.com/36665073/234272711-dd3393d0-1521-48c2-b82e-38e6f6a7cf66.jpg)

but only 13 was shown in the app
![Screenshot_2023-04-25-19-56-47-491_eu kanade tach](https://user-images.githubusercontent.com/36665073/234272741-8ff9c6aa-969b-403a-bf42-0972782fd977.jpg)

if remove this manga in that list ,it can be update correctly
![Screenshot_2023-04-25-19-57-16-908_eu kanade tach](https://user-images.githubusercontent.com/36665073/234272757-181341c2-699c-4f80-8d63-90b569a878c1.jpg)

### Expected behavior

the latest chapter(15) can be shown

### Actual behavior

the latest 2 chapters are missing
![Screenshot_2023-04-25-19-56-47-491_eu kanade tach](https://user-images.githubusercontent.com/36665073/234272659-0c2c3b9f-c60c-43b0-9c3b-75156ff34f63.jpg)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 362516282** [comment]
it depends on the device, this bug can't be repeated on different device every time, so things are totally different on my tablet and phone, 
my suggestion is to add a switch to let users decide whether to enable the "特殊漫画ID列表" function.

**Comment by zhongfly** [comment]
你举例的第1个漫画应该不是“特殊漫画”，能在网页上看到的都不该是“特殊漫画”。重新添加后就没问题了的话，我觉得也不是问题，可能是 特定插件版本下添加的漫画+动漫之家特殊情况 产生的。既然难以复现，那也很难找出原因…

而第2个漫画，我在dmzj社区版上用4级号也没看到漫画内容，应该是属于版权问题隐藏。这个问题在之前出现过类似的，可能是由于不同的接口获取到了不同的数据(特殊漫画需要用与普通漫画不同的接口)。具体的我就不清楚了

特殊漫画是会在简介里显示的：
![Screenshot_20230426104310](https://user-images.githubusercontent.com/11155705/234453241-146021d0-f05e-4045-9b4f-36473348bfa9.png)

**Comment by stevenyomi** [comment]
如同楼上所说，“特殊漫画列表”是由于图源限制添加的标记，目的是对已知的特殊漫画不要反复加载无用的资源，不是一个功能。

你所提到的第一个漫画我个人没遇到这个情况。有可能是前一阵子接口不稳定导致的，但理论上不应该会出现，有可能是你正好在接口没调试好的时候检查了更新，具体情况也只能靠猜测。

考虑到目前的插件代码里是可以去掉的，也不会造成普通作品的目录反复横跳，只不过特殊漫画会多加载一些无用资源，之后会直接去掉这个。

**Comment by 362516282** [comment]
好的，我这边平时的解决方案就是去 列表中清空所有漫画再进行一遍更新

**Comment by stevenyomi** [comment]
> 好的，我这边平时的解决方案就是去 列表中清空所有漫画再进行一遍更新

没有用的，只是一个标记而已，是特殊漫画的加载第二次还是一样的。

理论上是不可能出现漫画清空标记之后能加载出更多章节的情况的。
