### ISSUE TITLE
Shinigami: HTTP error 404

### ISSUE THREAD

**Issue by Start38** [tachiyomiorg/tachiyomi-extensions#16180]
### Source information

Shinigami 1.4.29

### Source language

Indonesian 

### Steps to reproduce

1.Open the shinigami extension 
2.And it shows error 404

### Expected behavior

It should feature various comics

### Actual behavior

Error 404

### Tachiyomi version

0.14.6

### Android version

11

### Other details

![Screenshot_2023_0425_222046](https://user-images.githubusercontent.com/120931895/234325057-9585abf7-af01-43b8-906b-ee2ffca1887d.jpg)
![Screenshot_2023_0425_222113](https://user-images.githubusercontent.com/120931895/234325172-0a5bbad9-ba72-48d6-bcb0-f2b15ddf5914.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kataceking** [comment]
Wahh sama bang
