### ISSUE TITLE
ManhwaHentai.me: No results found

### ISSUE THREAD

**Issue by NameLess1909** [tachiyomiorg/tachiyomi-extensions#16181]
### Source information

Manhwahentai.me

### Source language

English

### Steps to reproduce

This morning i can still open the source extension but after the extension ask for update and i update the extension now i cant use it its say no result

### Expected behavior

..

### Actual behavior

..

### Tachiyomi version

V8.7.4-az

### Android version

Android 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the issue form correctly and provide all requested information. Also make sure to include the extension version you're at.
