### ISSUE TITLE
mangalek java.io.IOException: timeout

### ISSUE THREAD

**Issue by MoXerous** [tachiyomiorg/tachiyomi-extensions#16199]
### Source information

مانجا ليك 1.4.31

### Source language

العربية

### Steps to reproduce

1. opened the source
2. this happened java.io.IOException: timeout

### Expected behavior

should open

### Actual behavior

could not bypass cloudflare
java.io.IOException: timeout

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by T3MYA11** [comment]
🙏

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
