### ISSUE TITLE
Hentaichan / henchan change their URL 

### ISSUE THREAD

**Issue by Vasillii0** [tachiyomiorg/tachiyomi-extensions#16198]
### Source information

Henchan 1.4.40

### Source language

Russian 

### Source new URL

https://x.henchan.pro/

### Other details

NSFW
![Screenshot_2023-04-26-20-26-34-599_eu kanade tachiyomi](https://user-images.githubusercontent.com/57034088/234656649-b98ecd16-3c7b-444e-95a0-f865c4208609.jpg)
![Screenshot_2023-04-26-20-26-45-203_eu kanade tachiyomi](https://user-images.githubusercontent.com/57034088/234656658-b4a2abbf-f732-476d-8191-55c2ede1b7ef.jpg)
![Screenshot_2023-04-26-20-20-49-830_com yandex browser](https://user-images.githubusercontent.com/57034088/234656661-d072b110-a2d6-4d04-82dc-c3e55b8a0ccf.jpg)
![Screenshot_2023-04-26-20-33-56-686_eu kanade tachiyomi](https://user-images.githubusercontent.com/57034088/234656874-429a035b-b608-461b-8719-889fd0cd1f9c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
![Screenshot_20230426-231817714.jpg](https://user-images.githubusercontent.com/35057681/234667091-3ed734cd-d27d-4108-a0e3-845608787689.jpg)

**Comment by Vasillii0** [comment]
Thanks 👍
