### ISSUE TITLE
Bato.to: Last chapter page throws HTTP error 500

### ISSUE THREAD

**Issue by Nagendra-456** [tachiyomiorg/tachiyomi-extensions#16208]
### Source information

Bato 1.4.31

### Source language

Multi

### Steps to reproduce

The error 500 is displayed while downloading from chapters from bato and after doing force stop and restarting the app and then again it shows new 502 error during download and stops at the last page of the chapter

### Expected behavior

The download should complete normally as it happens...

### Actual behavior

The download of the chapters get stuck at the last page after error notification 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 5xx errors are server side, and we can't do much about it. Closing as it's something the site owners need to fix.

**Comment by AntsyLich** [comment]
Seems to be also happening in the site where a random page throws 5xx so as Alessandro said nothing we can do in particular.
