### ISSUE TITLE
LeerCapitulo: Chapters does not open

### ISSUE THREAD

**Issue by DarkDissaster** [tachiyomiorg/tachiyomi-extensions#16209]
### Source information

Leercapitulo 1.4.3 (Español) 

### Source language

Español 

### Steps to reproduce

1.entrar en un manga que esté en dicha extensión
2.intetar abrir o descargar un capítulo 

### Expected behavior

Debería poder ver o descargar los capítulos correctamente 

### Actual behavior

En su lugar aparece un mensaje " Index:45, Size:15" y no se abre 
![Screenshot_2023-04-27-14-25-58-065_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/234971888-3597b582-9540-4fb7-9b14-3af95213ce14.jpg)
![Screenshot_2023-04-27-14-32-14-656_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/234971904-5f8c335a-0685-4643-9510-1a492f86a96d.jpg)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

![Screenshot_2023-04-27-14-32-14-656_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/234972088-47b94a3b-5f15-44c2-b11f-911e925e1c8d.jpg)
![Screenshot_2023-04-27-14-25-58-065_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/234972093-4d7b69fa-bbf1-4510-90c5-f3ae794bd833.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TUMAWA** [comment]
Encontraron una solución???

**Comment by jjgreedo** [comment]
Not functioning 04/29/2023 at 4:32 P.m.

**Comment by KaiZer32s** [comment]
Hola, ahora hay un nuevo error con la extensión, si carga el capítulo pero no cargan las imágenes dentro de este.
![Screenshot_20230429-193528_Tachiyomi](https://user-images.githubusercontent.com/132122155/235329885-a7a99786-93e5-433a-8688-cf9a30b24782.jpg)

**Comment by SU-YAN18** [comment]
No han podido arreglarlo

**Comment by Demiseman** [comment]
Quién le está dando Closed? Que no ven que no sirve en lo absoluto?

El error ahora es más agravado, ya no da códigos de erro, todo es null...

Yo igual puedo leer en inglés en otro sitio, pero es ridículo que cierren el treat y hagan caso omiso a las personas que están comentando aquí...

**Comment by alessandrojean** [comment]
We don't support LeerCapitulo anymore, read the bot message. Migrate your entries to other sources.
