### ISSUE TITLE
Komik Cast: java.io.IOException

### ISSUE THREAD

**Issue by hyuuzetz** [tachiyomiorg/tachiyomi-extensions#16205]
### Source information

Komik Cast 1.4.43

### Source language

Indonesia

### Source new URL

https://komikcast.site/

### Other details

![Screenshot_2023-04-27-09-54-06-977_eu kanade tachiyomi](https://user-images.githubusercontent.com/131972194/234858391-c1dcb357-daac-403b-8559-851c44685412.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by hyuuzetz** [comment]
i can't access this extension because of this can you fix it?
![Screenshot_2023-04-27-09-54-06-977_eu kanade tachiyomi](https://user-images.githubusercontent.com/131972194/234859514-95cea71e-9856-4efc-bf03-6f4bffb0a1a5.png)

**Comment by stevenyomi** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
