### ISSUE TITLE
WebView Error Extensions 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [tachiyomiorg/tachiyomi-extensions#16219]
### Source information

Manga sushi (version: 1.4.32) LHtranslation (version: 1.4.30)

### Source language

English

### Steps to reproduce

1. Open Manga sushi then LHtranslation.
2. Clear the cookies within WebView.
3. Check if the browser is working.
4. Blackout of the WebView then reload manga. sushi and LHtranslation extension again to see if there's any errors.

### Expected behavior

Reloading WebView while clearing cookies before a user backs out of WebView afterwards needs improvement if any HTTP errors is remaining.

### Actual behavior

I've been clearing cookies and reloading both WebView extensions in manga sushi and LHtranslation twice to see if I encountered any errors, it seems that this type of error is HTTP error idk what that means but I'm sure you guys would know. 

![Screenshot_20230428_120951](https://user-images.githubusercontent.com/104534608/235204767-8840db1d-f7d2-414b-9880-0cf8f43194af.png)
![Screenshot_20230428_120748](https://user-images.githubusercontent.com/104534608/235204771-a047bdc3-8efa-4b8f-92f6-cce2faf370d4.png)
![Screenshot_20230428_121132](https://user-images.githubusercontent.com/104534608/235204775-3c695a2a-0f9e-4935-94de-b3ca0235e136.png)

### Tachiyomi version

r5725

### Android version

Android 12

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source, otherwise it keeps difficult to track what have been addressed and what not.
