### ISSUE TITLE
hentaivn after solve captcha, it still appears to fail

### ISSUE THREAD

**Issue by WarmSeeker6** [tachiyomiorg/tachiyomi-extensions#16226]
### Source information

HentaiVN 1.4.22

### Source language

Vietnamese

### Steps to reproduce

it should be loaded normally

### Expected behavior

a list of manga appears after open on WebView and wait for cloudfare checking or solve captcha box

### Actual behavior

after cloudfare checking or solve captcha box, have access to the site, it still fails
![image](https://user-images.githubusercontent.com/130319694/235289359-9e733b91-9a8a-4952-826f-a0d82a8f22e8.png)
![image](https://user-images.githubusercontent.com/130319694/235289366-9c82caba-b459-4e05-aba4-d712bf986080.png)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
