### ISSUE TITLE
cloudflare 

### ISSUE THREAD

**Issue by alaweeGAMAR** [tachiyomiorg/tachiyomi-extensions#16225]
### Source information

مانجا ليك 1.4.31

### Source language

arabic 

### Steps to reproduce

open source or
open manga in source
cloudflare this happens because the new test from this site
please help 

### Expected behavior

open source or manga 

### Actual behavior

![Screenshot_2023-04-29-10-06-38-228_eu kanade tachiyomi](https://user-images.githubusercontent.com/126943315/235289165-ac1caa08-877f-463f-8677-4b81efdce57f.jpg)
![Screenshot_2023-04-29-10-06-13-087_eu kanade tachiyomi](https://user-images.githubusercontent.com/126943315/235289169-72dcae68-5162-4b46-8e51-71465d965b08.jpg)

### Tachiyomi version

0.14.6

### Android version

12

### Other details

The problem is not only with me. I am in a group, and everyone is complaining and looking for a solution. I hope to solve the problem quickly 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
