### ISSUE TITLE
TruyenQQ: Changed their domain

### ISSUE THREAD

**Issue by ddtg123** [tachiyomiorg/tachiyomi-extensions#16236]
### Source information

TruyenQQ

### Source language

Vietnamese

### Source new URL

https://truyenqqq.vn/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by minhngoc25a** [comment]
Note: Domain changed again, to https://truyenqqne.com/.
