### ISSUE TITLE
Incorrect URL change in origin

### ISSUE THREAD

**Issue by Skyprak** [tachiyomiorg/tachiyomi-extensions#16234]
### Source information

Leercapitulo 1.4.3

### Source language

Spanol

### Steps to reproduce

![20230429_111131](https://user-images.githubusercontent.com/115963154/235307374-75af8323-8575-463f-9535-3fde2e3df10e.jpg)

enter the webview, which will erroneously show the url of the leercapitulo as (olympusscan.top/) thus causing the application not to load the pages, nor to show all the works present on the agglomerator site

![20230429_111555](https://user-images.githubusercontent.com/115963154/235307535-744796d5-b63c-4d24-bc3e-c06f04b1819d.jpg)

they also mistakenly changed the name in the "extensions" tab to olympusscan.top which is actually a translator scan while leercapitulo.com is a working cluster

### Expected behavior

![20230429_112133](https://user-images.githubusercontent.com/115963154/235307786-6ffc0fc8-b791-4995-8217-8e17f7f2e43b.jpg)

opening of the webview and showing the correct url leercapitulo.com

### Actual behavior

![20230429_111131](https://user-images.githubusercontent.com/115963154/235307866-bd169b4e-abbd-4b66-979c-b55ed6fe9046.jpg)

webview opening and erroneously showing url like olympusscan.top

![20230429_111555](https://user-images.githubusercontent.com/115963154/235308091-77c3976a-0398-4736-98bf-ee8c35c2d677.jpg)

including erroneously named also in the tab "extensions with the nomenclature "leercapitulo / olympusscan.top "....which is not correct because olympusscan is a translator scan, while leercapitulo is an agglomerator of work

### Tachiyomi version

Stable 0.14.6

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DarkDissaster** [comment]
![Screenshot_2023-04-29-09-45-31-629_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/235308802-3e4b34d6-b2d0-47b1-b535-84a2de0c2855.jpg)
![Screenshot_2023-04-29-09-45-40-563_eu kanade tachiyomi](https://user-images.githubusercontent.com/79143206/235308803-a6d3daf7-9009-4c67-9db0-63cc46483c31.jpg)
Solo dale en engranaje y después en mirror cambia a la url de leercapitulo

**Comment by Skyprak** [comment]
I was informed how to change there url
