### ISSUE TITLE
Mangaswat: Changed their domain

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#16231]
### Source information

Mangaswat 1.4.33

### Source language

Arabic

### Source new URL

http://swatmanga.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by omarallsharkawy** [comment]
فكك من مانجا سوات خلينا في مانجا ليك

**Comment by M-Cry** [comment]
According to this post in the Manga Swat Discord server, the site is down for maintenance, and they don't have a clear time when the site will be up.

![site.jpg](https://user-images.githubusercontent.com/42918650/236398981-2447b0fd-19eb-4f33-88dc-bee8505aea19.jpg)



if they ever change the url for the site, you can change it within the extension settings as in this video.

https://user-images.githubusercontent.com/42918650/236400855-4cca1e5b-c323-47ce-a326-ea39f745b9e5.mp4

you will need to restart the application after the change.
