### ISSUE TITLE
ManyToon: Redirecting to ToonLove.me

### ISSUE THREAD

**Issue by Narvon** [tachiyomiorg/tachiyomi-extensions#16237]
### Source information

ManyToon 

### Source language

English 

### Steps to reproduce

Try to open ManyToon with the app.
Lists are not loading.
Website via the app opens not ManyToon, but is redirected to ToonLove.me

### Expected behavior

Loading of content from ManyToon 

### Actual behavior

Loading nothing over the app. Blank liet

### Tachiyomi version

App version: 1.6.6 (standard, 21a2705c7, 104, 2023-04-19T22:38Z) Android version: 13 (SDK 33) Android build ID: TQ2A.230405.003.E1 Device brand: google Device manufacturer: Google Device name: bluejay Device model: Pixel 6a Device product name: bluejay

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce the redirection.

**Comment by Narvon** [comment]
Strange, but is the list loading on your device or do you also get a blank list as you open it in the app? Not the website via the app.
