### ISSUE TITLE
Asura scans seems to be down

### ISSUE THREAD

**Issue by TempestEnjoyer** [tachiyomiorg/tachiyomi-extensions#16249]
### Source information

Error code 502

### Source language

All languages

### Steps to reproduce

Attempt to refresh a asura scans item

### Expected behavior

Refresh 

### Actual behavior

Fail

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Closing in favor of #16251
