### ISSUE TITLE
HenChan: Changed their domain

### ISSUE THREAD

**Issue by Maximumpowee** [tachiyomiorg/tachiyomi-extensions#16242]
### Source information

Henchan change url

### Source language

Russian

### Source new URL

https://x.henchan.pro/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16198
