### ISSUE TITLE
Force browser mode to see chapter

### ISSUE THREAD

**Issue by mickae1** [tachiyomiorg/tachiyomi-extensions#16244]
Some source asked to be removed because they lost money. 
Maybe if you add a feature, that for them, you force the user to use browser to see the chapter.

They will not lost money in this case, and they will allow tachiyomi to be used to track new release.

Also this new pull in progress will help their server to not be polled every time when it's not necessary:
https://github.com/tachiyomiorg/tachiyomi/pull/5734

**Comment by alessandrojean** [comment]
Please do not edit and delete the issue form structure. Already replied in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16243#issuecomment-1528913003, it's not possible with how the extensions work.

Also this isn't the repository to open issues related to app feature requests, as stated in the acknowledgement section you deleted when editing.
