### ISSUE TITLE
Too Many Follow Requests : 21

### ISSUE THREAD

**Issue by SantanuLayek** [tachiyomiorg/tachiyomi-extensions#16248]
### Source information

Asura Scans 1.4.45

### Source language

Mutli

### Steps to reproduce

Update Comic from the Source. 
Comic shows new chapter.

### Expected behavior

Comic Shows new chapter

### Actual behavior

JavaIoException: Too many follow requests : 21

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

This issue happened for the first time today. At first I thought that it might be because I updated 94 comics at once, but previously I used to update 120 comics at once and it never happened. I read about the issue in the tachiyomi website, where it shows that It may happen if the source bans my IP if I read too often or too fast. I just want to know whether this ban is temporary or permanent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Merging with #16251
