### ISSUE TITLE
LeerCapitulo: Pages do not load

### ISSUE THREAD

**Issue by TUMAWA** [tachiyomiorg/tachiyomi-extensions#16240]
### Source information

Leercapitulo versión  1.4.4

### Source language

Español

### Steps to reproduce

Debería de cargar las paginas

### Expected behavior

Carga normal en las paginas de los capítulos 

### Actual behavior

No cargo las paginas y ni deja recargarlo

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details

Solo sucede en la extensión de Leercapitulo 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jjgreedo** [comment]
still not working 04/29/2023 at 4:40 p.m.
