### ISSUE TITLE
Force browser only mode for a source

### ISSUE THREAD

**Issue by mickae1** [tachiyomiorg/tachiyomi-extensions#16243]
### Source name

Realm scan

### Source language

English

### Describe your suggested feature

Realm scan asked to remove the extension because it cause revenu lost.

I understand that, is it possible that for realm scan we are redirected to the browser to show their work?

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15586#issue-1609909116

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mickae1** [comment]
I understand but if we add the feature that for certain extension, the only possibility to see chapter are by using browser like Firefox, chrome. They will agree.
So I'm asking to add this feature in extension.

And after that we can asked them if they agree to it?

**Comment by alessandrojean** [comment]
That's not possible and would go against the extension functionality and how they're structured. Just read through the browser directly if you want to keep consuming their stuff.
