### ISSUE TITLE
Viz: Show Locked Chapters

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#16250]
### Source name

Viz Shonen Jump 1.4.17

### Source language

English

### Describe your suggested feature

It'd be nice if it would show all locked chapters similar to Tapas extension settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There isn't much sense in having this feature in this particular extension as they're subscription based, that meaning all missing chapters on free are available if you have a subscription and have signed in through WebView.

Tapas and others make sense as you can unlock chapters individually by using coins, so being able to see if you have already bought/unlocked a chapter or not it's useful in that case.

This can be considered again if the extensions get a proper support to locked/unlocked/free chapters indicator in the future though, so closing for now.
