### ISSUE TITLE
Asura scan not updating http error

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#16258]
### Source information

Asura Scans 1.4.45

### Source language

All

### Steps to reproduce

Asura scan extension suddenly not showing updates with http 502 and 404 error 

### Expected behavior

When i usually update normally the update worked before yesterday 

### Actual behavior

But now it keeps showing http error

### Tachiyomi version

r5745

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16251#issuecomment-1529306990

**Comment by stickyff** [comment]
I have the exact same issue

**Comment by CyrilAg** [comment]
me too
