### ISSUE TITLE
Asura Scans: HTTP error 404 and Too Many Follow-up Requests

### ISSUE THREAD

**Issue by MNNabawi** [tachiyomiorg/tachiyomi-extensions#16251]
### Source information

Asura Scans 1.4.45

### Source language

All language 

### Steps to reproduce

1. Open the chapter list of an old ongoing series.
2. Refresh the chapter list.
3. HTTP error 404

### Expected behavior

Chapter Refreshed 

### Actual behavior

Error 404

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

I found out that the link from tachiyomi chapter list (chapter list web view) and the actual link (Asura Scans site homepage -> chapter list of the series) are different.

Example
Link from tachiyomi chapter list : https://asura.gg/manga/player-who-returned-10000-years-later/

The actual link : https://www.asurascans.com/manga/8239705535-player-who-returned-10000-years-later/

*Might be redirecting issues.
** Doesn't effect new series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 1-minute-to-midnight** [comment]
same issue here

**Comment by FireCheck** [comment]
It seems to be a problem with the permanent link option, because after desactivating it in the extension settings the manga can be found in the extension but you have to migrate all of the mangas of the source to it again.
![Screenshot_2023-05-01-05-26-00-731-edit_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/84283461/235399772-aaa5b4d9-d732-4d46-885a-59759cf02429.jpg)

![Screenshot_2023-05-01-05-26-14-509-edit_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/84283461/235399770-39bd13f1-ece3-4b30-b8d2-0136c4c9777e.jpg)

![Screenshot_2023-05-01-05-25-37-805-edit_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/84283461/235399773-1c74157f-d196-40a4-af0f-55673ef972c9.jpg)

![IMG_20230501_052649.jpg](https://user-images.githubusercontent.com/84283461/235399771-c658a397-5e35-4eb8-9cfb-3f85f97319d4.jpg)

**Comment by TDWiz** [comment]
Solution does not work for me, I have same everything as above. I even tried to reinstall and it didn't work.

**Comment by rizqiimani** [comment]
Had the same problem, above solution works partially. At some point there are some titles that can't be searched (but can be searched after modifying the keyword) kind of a lot of effort to migrate one by one, I have over 40 titles subscribed 😂

**Comment by BEST8OY** [comment]
> Had the same problem, above solution works partially. At some point there are some titles that can't be searched (but can be searched after modifying the keyword) kind of a lot of effort to migrate one by one, I have over 40 titles subscribed 😂

No need for one by one migration
Categorize based on source 
Select all asura entries
And use migration tool

**Comment by rizqiimani** [comment]
> > Had the same problem, above solution works partially. At some point there are some titles that can't be searched (but can be searched after modifying the keyword) kind of a lot of effort to migrate one by one, I have over 40 titles subscribed 😂
> 
> No need for one by one migration Categorize based on source Select all asura entries And use migration tool

How to categories by source? I can't seem to be able to do that

Also what to do for some titles that can't be searched (since Migrating is looking for exact title word) ?

**Comment by BEST8OY** [comment]
> How to categories by source? I can't seem to be able to do that
> Also what to do for some titles that can't be searched (since Migrating is looking for exact title word) ?

I just migrated 50 entries from asura scan.
To categorize based on source click on icon next to 🔍 then Group
I didn't have any issue for 50 entries, so I can't help you with search problem.
Try it maybe it worked well for you too

**Comment by rizqiimani** [comment]
> > How to categories by source? I can't seem to be able to do that
> > Also what to do for some titles that can't be searched (since Migrating is looking for exact title word) ?
> 
> I just migrated 50 entries from asura scan. To categorize based on source click on icon next to 🔍 then Group I didn't have any issue for 50 entries, so I can't help you with search problem. Try it maybe it worked well for you too

Are you sure it's a native feature to Tachiyomi and not some forks of Tachiyomi? Cause mine only shows ordinary filters, and no option to categorize by source let alone migrate multiple titles at once

**Comment by Seishirou101** [comment]
if you need support, please use the discord. This is for tracking issues.
