### ISSUE TITLE
Mangakatana Chapters not found

### ISSUE THREAD

**Issue by Thifa30** [tachiyomiorg/tachiyomi-extensions#16269]
### Source information

Mangakatana 1.4.9

### Source language

English

### Steps to reproduce

1. I try to update the chapters I followed
2. 
![Screenshot_2023-05-02-18-31-55-945_com android chrome](https://user-images.githubusercontent.com/102187129/235661358-3087ad75-6b99-41e2-990f-9eff1c62c782.jpg)

### Expected behavior

It should update, or if it's not updated then there shouldn't be a notification about no chapters can be found

### Actual behavior

![Screenshot_2023-05-02-18-31-55-945_com android chrome](https://user-images.githubusercontent.com/102187129/235661599-f5243749-82c8-4dc4-b024-94aad3e9f713.jpg)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

I already tried to erase cache and cookies. still have the same problems

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
did you try the troubleshooting guide? I tried 3 entries on your list and they work fine. You possibly need to just migrate from mangakatana to mangakatana if they changed the urls

**Comment by Thifa30** [comment]
I did try the troubleshooting guide. It's kinda weird to be honest, because if I tried to read chapters of the manga from Mangakatana, I can still open it, but whenever I tried to do a Global Update it keep showing "manga chapter not found" and not giving me any updates (even when I had checked directly to the website and see that yes, there's some manga that was updated)

**Comment by Riztard** [comment]
> did you try the troubleshooting guide? I tried 3 entries on your list and they work fine. You possibly need to just migrate from mangakatana to mangakatana if they changed the urls

same for me, probably they just changed url just like seish said
