### ISSUE TITLE
Asura scans http error 

### ISSUE THREAD

**Issue by aditya5375** [tachiyomiorg/tachiyomi-extensions#16274]
### Source information

Asura scans 

### Source language

English 

### Steps to reproduce

Asura scans manhwa not getting refreshed because of http error 

### Expected behavior

The mahwa should load 

### Actual behavior

This bug has been showing up since 26th april 2023

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

![Screenshot_20230502-081754_WPS Office](https://user-images.githubusercontent.com/131780536/235592311-a26a8045-a444-458a-a55b-7f07a8529f1a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#16251
