### ISSUE TITLE
Asura Scans New Url for some manga

### ISSUE THREAD

**Issue by Dustedix** [tachiyomiorg/tachiyomi-extensions#16283]
### Source information

Asura Scans 1.4.45

### Source language

English

### Source new URL

https://www.asurascans.com/. Example new link in some manhwa : https://www.asurascans.com/manga/8239705535-villain-to-kill/

### Other details

Probably asura implement new code filtering for some manhwa to access

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Dustedix** [comment]
Already found the solution

**Comment by astro-ray** [comment]
@Dustedix what is the solution?

**Comment by ziyadkhaled** [comment]
Same problem what is the solution?
