### ISSUE TITLE
No result on phantom scans

### ISSUE THREAD

**Issue by 12Vine** [tachiyomiorg/tachiyomi-extensions#16287]
### Source information

Phantoscans 1.4.26

### Source language

English

### Steps to reproduce

1. Diagnose the issue
2. Try web view and the webview works
3. Same result no result found

### Expected behavior

The extension, i tried to webview it but the webview work the extension works for few second then change no result found

### Actual behavior

Keep notifying no result find

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

![Screenshot_2023-05-03-19-47-29-180](https://user-images.githubusercontent.com/129012648/235910588-b320cffb-6a28-4a9d-8d2e-099bea43bc3e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce. Are you still having this issue?
