### ISSUE TITLE
LeerCapitulo Pluggin dont work at all

### ISSUE THREAD

**Issue by Demiseman** [tachiyomiorg/tachiyomi-extensions#16285]
### Source information

Null un all responses, no Code error

### Source language

English, espanish

### Steps to reproduce

1>you cant see
2 you cant download anything
3 ifntou delete an old manga, and try to download ornsee, dont work at all

Im updated all stuff un 64 bits, i tested all tachiyomi diferent versiones and leer capítulo dont work at all...

### Expected behavior

Null

### Actual behavior

Null

### Tachiyomi version

Last

### Android version

Last

### Other details

I can see the Web versión of LeerCapitulo, butnintachiyomy its screw...

And i dont like the website view at all xD...

![Screenshot_2023-05-03-13-17-57-533_eu kanade tachiyomi](https://user-images.githubusercontent.com/132454777/235902245-1934c585-7318-4ced-81f0-5f6e3c39a184.jpg)
![Screenshot_2023-05-03-13-18-11-573_eu kanade tachiyomi](https://user-images.githubusercontent.com/132454777/235902249-d4fcb1d4-b29f-441f-b3b4-4e755719f169.jpg)

Dont even have annerror Code to investigate, and i cant program in this languaje :c inonly know C#

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by dixion1309** [comment]
ERROR
