### ISSUE TITLE
Mizu Mangás: Migrated from Madara to a proper CMS

### ISSUE THREAD

**Issue by DAILYVIXENS** [tachiyomiorg/tachiyomi-extensions#16286]
### Source name

Mizu Mangás

### Source language

Portuguese PT-BR

### Source link

https://mizumangas.com.br/

### Other details

The site was offline but is now active again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The source already exists, they just migrated from Madara to a proper and custom CMS.
