### ISSUE TITLE
No update on ManhuaFast latest panel

### ISSUE THREAD

**Issue by uniqueunique7x7** [tachiyomiorg/tachiyomi-extensions#16296]
### Source information

ManhuaFast 1.4.31

### Source language

English

### Steps to reproduce

Source Latest Panel

### Expected behavior

Latest Panel is showing 3 4 days old latest panel .. in webview its showing current updates but not in tachi extension

### Actual behavior

3 4 days old updated mangas

### Tachiyomi version

1.4.31

### Android version

Android 13

### Other details

When i do global update i am getting new updates but not showing on source latest update panel .. lastest panel is of 3 4 days old latest updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scorp200** [comment]
it doesn`t load pages nor updates as of May 5th 23'

**Comment by Riztard** [comment]
looks like site issue, its late 15 min for me.
their homepage latest vs manga list filter is different
https://manhuafast.com/manga/?m_orderby=latest
