### ISSUE TITLE
Asura Scans broke

### ISSUE THREAD

**Issue by diefordabi** [tachiyomiorg/tachiyomi-extensions#16308]
### Source information

Asura Scans 1.4.45

### Source language

Turkish

### Steps to reproduce

I can see the site and webtoons, but when I try to read the chapters, it says page not found.. 
(The site also opens in the app and browser)
And asura's English browser http error 404. and turkish browser is working but app broke
help me please

### Expected behavior

maybe asura should be nice... nd Should work better 

### Actual behavior

It should become a smooth and beautiful app nd browser

### Tachiyomi version

0.14.6

### Android version

Android 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by diefordabi** [comment]
gl

**Comment by kyoyacchi** [comment]
#16251
