### ISSUE TITLE
1st kiss not being parsed correctly

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi-extensions#16316]
### Source information

1st kiss 1.4.38

### Source language

English

### Steps to reproduce

Download multiple chapters from a series in 1st kiss (because it doesn't happen with all the chapters.
when a chapter fails to download (due to a small number of pages failing), open that chapter. Open the chapter in WebView to validate what the images are supposed to be in the actual web page.

### Expected behavior

Chapters download/render normally

### Actual behavior

A few pages show the error message "the image coulnd't be loaded". It seems that these are either publicity or blank separators (see screenshot, where the two pages around the faulty image are clearly consecutive). The first image for the chapter in the example is a video that has nothing to do with the chapter and it also shows the same message.

![Screenshot_20230504-183406_TachiyomiJ2K](https://user-images.githubusercontent.com/3915542/236335538-aee68f2a-56e5-4c11-992b-d3f296c4bd90.jpg)

### Tachiyomi version

J2K v1.6.6

### Android version

Android 11 / OneUI 3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
i found the problem. its because they now have 2 object with the same id to reference the image.  but i don't know how to fix it. their code example is posted below
```
<div class="page-break no-gaps">
  <img id="image-0" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E" class="wp-manga-chapter-img" data-lazy-src="https://my1.1stkmgv1.com/manga_64452d84ab355/5f4e3c571e60d3dce7d03ed691bc179f/0.jpg">
<noscript>
<img id="image-0" src="
  https://my1.1stkmgv1.com/manga_64452d84ab355/5f4e3c571e60d3dce7d03ed691bc179f/0.jpg" class="wp-manga-chapter-img">
</noscript>
  </div>

```

**Comment by samanta-widjaja** [comment]
just now it become fine again

**Comment by scb261** [comment]
#17897
