### ISSUE TITLE
Unable to download and install sources

### ISSUE THREAD

**Issue by LCarrot1** [tachiyomiorg/tachiyomi-extensions#16319]
### Source information

Mangadex 1.3.175, Nhentai 1.3.36

### Source language

English

### Steps to reproduce

1. I click on update all or indivisual updates.
2. The updates are not downloading
3. They show an error
4. 

### Expected behavior

The update should have downloaded and been installed

### Actual behavior

As set in reproduction

### Tachiyomi version

0.14.6

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

Also make sure you have 18+ sources enabled and if you're using MIUI, turn off MIUI optimizations.
