### ISSUE TITLE
Kavita extension fails to show Publication status

### ISSUE THREAD

**Issue by EnArvy** [tachiyomiorg/tachiyomi-extensions#16318]
### Source information

Kavita 1.4.10

### Source language

Multi

### Steps to reproduce

1. Set up Kavita
2. Get metadata using Komf
3. Most metadata works fine
4. Publication status is visible on Kavita webview but Tachiyomi says Unknown 

### Expected behavior

Publication status for manga should show correct status 

### Actual behavior

Publication status is Unknown 

### Tachiyomi version

0.14.16

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fyannk** [comment]
I've made some changes for myself including this one

https://github.com/fyannk/tachiyomi-extensions/commit/80d8151ec782ba3ed8e091a12dcb204961bfa2ff

Default (1.14.10) :
![kavita_before](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/1781664/e597f45c-6acc-44f3-9c49-a03619361885)

With this commit :
![kavita_after](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/1781664/a4460d17-fda1-4f2a-aa8e-6222df250b1a)

@majora2007 what do you think ? (maybe I should do a PR for just the status and not my other changes)

**Comment by majora2007** [comment]
I don't use this extension at all, can you explain what I'm looking at?

@ThePromidius

**Comment by ThePromidius** [comment]
From what i see it fixed pub status and also shows tags. (currently only genres iirc)
Feel free to pr. Fixes are always welcomed :)
I'm still looking into updating the filters with the reworked one in Kavita so that might take some time to see light so you might want to just pr into this repo instead of the fork.

**Comment by fyannk** [comment]
@ThePromidius no problem for that :)

do you want me to remove my hacky thing for mangaDetailsRequest or not ? (with putting the library id in the genres)

I did that mainly because i kept having nullpointers when going on webview

**Comment by ThePromidius** [comment]
Honestly i don't know what you mean without looking at the code.
I started working in the new filter, feel free to drop by the kavita discord and we can discuss there with more detail.

**Comment by Eskuero** [comment]
Might this be causing the updates to be skipped? I don't have unread chapters so I was wondering if an "Unknown" status would make Tachiyomi to skip checking updates

**Comment by ThePromidius** [comment]
That shouldn't be the case. Theoretically, Tachiyomi scans chapters list and compares last chapter in the list vs the new one, not manga status.

**Comment by Eskuero** [comment]
According to
https://tachiyomi.org/docs/faq/library#why-is-global-update-skipping-entries
it does skip global updates if the series has a completed status which is
why I was wondering if an unknown status could been causing it too.

**Comment by BrutuZ** [comment]
I assumed it was excluded from global updates due to its [update strategy](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#update-strategy), but after a quick peek at the code it doesn't seem to be the case
