### ISSUE TITLE
Babel Wuxia: Chapters not showing up in Reader

### ISSUE THREAD

**Issue by Sharpshots** [tachiyomiorg/tachiyomi-extensions#16329]
### Source information

Babel Wuxia

### Source language

English

### Steps to reproduce

1. Click on manga
2. Go into reader mode
3. No chapter present in reader

Note: there may be some outliers that show the chapters in reader mode

### Expected behavior

Reader would display chapters that are available/seen in webview mode

### Actual behavior

Reader does not display any chapters

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FaTe-code** [comment]
Have the same issue, no pages loading and source library doesn't update chapters or covers.
