### ISSUE TITLE
To many follow up request  : 21

### ISSUE THREAD

**Issue by DeZer04** [tachiyomiorg/tachiyomi-extensions#16320]
### Source information

Komik Cast 1.4.43

### Source language

Indonesia

### Steps to reproduce

1. I was reading comic until 15 chapter
2. I want to go to chapter 16 but the error showing

### Expected behavior

I dont know

### Actual behavior

I dont know

### Tachiyomi version

0.14.6

### Android version

12

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Superseded by #17969
