### ISSUE TITLE
We hope to add a manual link to all sources

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#16327]
### Source name

all extensions 

### Source language

all luggage 

### Describe your suggested feature

A manual source must be added to all sources because sometimes the sources change their website link, so there will be no need to open a new case for the source And we manually change the website link, for example, there is an application Kotatsu This feature I will attach to you a picture of the feature So that we write the source link manually when its link changes 

### Other details

There are some sources that do not have this feature, such as Chinese sources, for example
There is an app with this feature called (Kotatsu) This is a video recording of the desirable feature 

https://user-images.githubusercontent.com/87826849/236597935-9302d937-ccc3-43ae-a993-d643a3c3b282.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's actually better to just add to explicit sources that have this bad behavior of changing the URLs constantly. It's not worth adding this to every single extension in the repository.
