### ISSUE TITLE
Asura Scans (Turkish): webtoon pages not found

### ISSUE THREAD

**Issue by diefordabi** [tachiyomiorg/tachiyomi-extensions#16339]
### Source information

Asura Scans (Turkish): webtoon pages not found"

Asura Scans 1.4.45 

### Source language

Turkish 

### Steps to reproduce

Asura Scans turkish webtoon or manga appear, new episodes are added, but webtoons manga is not reading. always and On all webtoons say "page not found". Other sites or webtoons are running. I moved Webtoons but still the asura is broken. I did everything but stilll broke. AND This is just broken for TURKİSH ASURA. PLEASE HELP US
(I renewed the extensions but they are still broken) 

### Expected behavior

The problem must be solved and not live again. 

### Actual behavior

MY WEBTOONS MUST BE SAVED

### Tachiyomi version

0.14.6

### Android version

Android 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
/edit-title "Asura Scans (Turkish): webtoon pages not found"
