### ISSUE TITLE
HentaiVN: new domain with lower protection

### ISSUE THREAD

**Issue by leonminus** [tachiyomiorg/tachiyomi-extensions#16349]
### Source information

HentaiVN 1.4.23

### Source language

Vietnamese

### Source new URL

hentaivn.team

### Other details

The old URL still work but the raised their Cloudflare protection, but the new doesnt
i dont understand how to code and change the domain but i think if someone gonna help u can just copy and renew the URL .team. Sorry if i say something wrong because i know coding is very hard.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
/edit-title "HentaiVN: new domain with lower protection"
