### ISSUE TITLE
Allporncomic extension throwing Java IOException

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi-extensions#16354]
### Source information

Allporncomic 1.4.29

### Source language

English

### Steps to reproduce

Open the extension, data does not load

### Expected behavior

Should display different comics

### Actual behavior

Throws Java IOEXCEPTION 
![Screenshot_2023-05-07-19-41-03-793_eu kanade tachiyomi](https://user-images.githubusercontent.com/25505145/236682865-849eb48a-ddb2-4ead-9c44-da11ba3fae64.png)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alexphilip0019** [comment]
Open in webview also does not load the site but opening it in browser chrome works and site loads

**Comment by alessandrojean** [comment]
Website seems down as it timed out. Try the troubleshooting guide in the acknowledgements section you checked. This isn't something that can be fixed on the extension side.
