### ISSUE TITLE
can the mangatoon extension be updated?

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi-extensions#16358]
### Source information

mangatoon 1.4.4

### Source language

Multi

### Steps to reproduce

not updating

### Expected behavior

not updating

### Actual behavior

not updating
I know it's limited but maybe there's an update😁
Thanks 

### Tachiyomi version

Last

### Android version

Android 11

### Other details

not updating
I know it's limited but maybe there's an update

![Screenshot_2023-05-07-23-09-12-98_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/236689137-6b0102c3-65a1-47d0-b1b1-64e3453c6adc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I will assume this is about the missing chapters. As the source name suggests (limited), it will show only the free to read chapters. To read paid stuff you will need to use their site or app.
