### ISSUE TITLE
can't open comic

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi-extensions#16352]
### Source information

Bato.to 14.3.1

### Source language

ID

### Steps to reproduce

WebView mode doesn't work either

### Expected behavior

WebView mode doesn't work either

### Actual behavior

WebView mode doesn't work either

### Tachiyomi version

Last

### Android version

Android 11

### Other details

![Screenshot_2023-05-07-18-11-51-01_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/236674176-a4e37af9-71b7-4167-b6ba-309aa8f6bf59.jpg)
![Screenshot_2023-05-07-18-11-46-78_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/236674177-f5e6e2df-c05a-4670-ba9f-c66c8bc30ece.jpg)
![Screenshot_2023-05-07-18-11-32-95_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100791931/236674178-072aa3fa-f919-4164-aca2-76326deb97a1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
You can open it if you use DOH or VPN

**Comment by TheKingTermux** [comment]
You can open it if you use DOH or VPN

**Comment by mozzaru** [comment]
Ok thanks

**Comment by mozzaru** [comment]
> Ok thanks

Oot sir 
Can mangatoon be updated?
