### ISSUE TITLE
Change url Noromax

### ISSUE THREAD

**Issue by Start38** [tachiyomiorg/tachiyomi-extensions#16367]
### Source information

Noromax 1.4.6

### Source language

Indonesian 

### Source new URL

https://noromax.my.id/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Start38** [comment]
when will the extension be fixed

**Comment by kitsu2** [comment]
@OdisBy
