### ISSUE TITLE
MangaSwat error 404

### ISSUE THREAD

**Issue by T3MYA11** [tachiyomiorg/tachiyomi-extensions#16375]
### Source information

MangaSwat 1.4.33

### Source language

Arabic 

### Steps to reproduce

can't view the source
can't refresh the manga chapters
http error 404 but the website  working fine in WebView 
![Screenshot_2023-05-09-09-07-14-961_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/92279646/237008587-15eecafb-fbfd-420a-9ddb-e3ffe73eab77.jpg)

### Expected behavior

the source need update from tachiyomi app it was working before last update 
the domain still the same 
https://swatmanga.net/ 

### Actual behavior

http 404 error 

### Tachiyomi version

tachiyomij2k 1.6.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by khader-nat** [comment]
Mangaswat changed their domain from https://swatmanga.me/ to https://swatmanga.net/

**Comment by khader-nat** [comment]
Swat manga changed their domain from swatmanga.me to swatmanga.net

**Comment by Odarku** [comment]
كادمن لموقع سوات عم قولك انت لا تمتلك من نخوة العروبة من شيء ولا من الرجولة شيء ولن تمتلكها ابدا واتمنى مستقبلا ينسرق منك جهدك و تبكي عليه .....فالدنيا دوارة ... كمل هكذا احسنت.
