### ISSUE TITLE
Trapscans

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi-extensions#16378]
### Source name

Trap Scans

### Source language

English

### Source link

https://trapscans.com

### Other details

Redirects to account has been suspended page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
Hmmm, is up here.

**Comment by loocool2** [comment]
Seems like they're back up
