### ISSUE TITLE
Manhua source do be broken

### ISSUE THREAD

**Issue by lukor79** [tachiyomiorg/tachiyomi-extensions#16382]
### Source information

1st Kiss Manhua 1.4.33

### Source language

English

### Steps to reproduce

see discord support page idk how to upload an image

### Expected behavior

the source working

### Actual behavior

error 404 but the website isn't down

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

idk wht to put here

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kiriya-aoi** [comment]
They changed url (to 1stkissmanga.plus, it redirects), and new series urls don't map to old series urls.
