### ISSUE TITLE
La URL de ninemangaes ha cambiado

### ISSUE THREAD

**Issue by llpro11** [tachiyomiorg/tachiyomi-extensions#16400]
### Source information

NineManga 1.4.17

### Source language

Español

### Source new URL

https://my.ninemanga.com/

### Other details

The URL that Ninemangaes is using has changed to https://es.ninemanga.com/ and now it has changed to https://my.ninemanga.com/ l please fix this bug and change the url thanks for your attention.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
That url is old with the last update in 2018, the correct url is `es.ninemanga.com`
This issue can be closed
