### ISSUE TITLE
Komik Lab URL change

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#16418]
### Source information

Komik lab 1.4.26

### Source language

English

### Source new URL

https://komiklab.com

### Other details

![Screenshot_2023-05-12-16-22-05-75](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/79831076/d686e3f9-8b67-455d-afe7-fc889751a0a1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
Please reopen

**Comment by AntsyLich** [comment]
@conztanz045 why the hell did you close this as completed

**Comment by conztanz045** [comment]
Look like there move the english site to the indonesia site

**Comment by conztanz045** [comment]
So its extension problem?

![Screenshot_2023-05-12-16-40-04-95](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/79831076/73ed195e-b279-4e4b-9db7-f806ef0ef0d5)

All english is there now
