### ISSUE TITLE
Stuck/failed to bypass cloudfire

### ISSUE THREAD

**Issue by Senbun33** [tachiyomiorg/tachiyomi-extensions#16416]
### Source information

Manhwa18

### Source language

English

### Steps to reproduce

Wont bypass cloudflare
tried all troubleshooting, changed wifis also used data no hope

cloudflare bypass keeps repeating, itried clicking for half an hour no hope.

i saw one post that maybe the website increased their cloudflare security that tachiyomi cant bypass but might as well let you guys know

### Expected behavior

should bybass cloudflare and able to browse manhwa

### Actual behavior

Stuck on Bypass cloudflare 

### Tachiyomi version

If their is bypass, normaly I click on the brower logo at the top and then then do the bypass thongy and i will be able to browse 

### Android version

android 12

### Other details

its been like this but some time i can bypass but now I doesn't 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
