### ISSUE TITLE
MangaDex Latest error: Polymorphic serializer was not found for class discriminator 'creator'

### ISSUE THREAD

**Issue by malikmubarok69** [tachiyomiorg/tachiyomi-extensions#16429]
### Source information

MangaDex 1.4.177

### Source language

English

### Steps to reproduce

1. Browse
2. Source
3. Mangadex (English) 
4. Latest

### Expected behavior

It usually shows the latest updated chapters on mangadex

### Actual behavior

but now it just shows an error:
Polymorphic serializer was not found for class discriminator 'creator' 
JSON input:
{"id" :"38310449-6932-4feb-8b0e1844aebdc3bd","type":"creator"}

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

![Screenshot_20230514-042050](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/24262412/c3994b48-20de-444b-bd1a-062b86993554)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by walidh2000** [comment]
Yeah same happened to me when I tried to check just now

**Comment by malikmubarok69** [comment]
> Yeah same happened to me when I tried to check just now

right? we can update the chapters just fine from the library but can't see the list of latest chapters is inconvenient

**Comment by Quantumdrone** [comment]
The filter tab has the same issue, but only for changing the sorting method. So in short, there's an issue with changing the sorting method to "Chapter uploaded at", "Content created at", or "Content info updated at".

The rest of the sorting methods have no issue.

**Comment by MIC132** [comment]
I get that when updating mangas, but only some (get few) and I think I saw it from multiple sources, not just dex.

**Comment by lord-ne** [comment]
I saw this issue when clicking a link to open a manga, and when refreshing chapters of a manga.

Best guess, MangaDex slightly changed their API response format, added something new , which is messing with how Tachiyomi is parsing it. I doubt it's a hard fix, but if this issue is the kind of thing I think it is, maybe we should try to modify the extension a bit to be more able to ignore extra information? I would take a stab at it myself but I don't have any time for the next few days

**Comment by CedMIX-Productions** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/cc5b172d-cd15-4786-a32e-8f3701294360

I tried to document (in a video format) as possible if it possible to recreate that same error. (Live ADB logs included)
Using Tachiyomi 0.14.6 with MangaDex 1.4.177 on WSA build 2302.40000.9.0
1. Go to Browse -> Sources -> MangaDex
2.  Go to "Popular" tab, displays it fine.
3. When you go to the "Latest" tab, it displays the following error:
```
Polymorphic serializer was not found for class discriminator 'creator'
JSON input:
{"id":"<insert uuid here>","type:"creator"}
```

**Comment by Mtkmanjaro** [comment]
also the web view is not working for mangadex, I have the same issue when trying to update the library

![Screenshot_20230514-023156.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/64289536/98550c87-7c42-4b3e-a24d-9d0feb2cb2aa)

**Comment by MIC132** [comment]
> also the webview is not working for mangadex, I have the same issue when trying to update the library

The webview works fine for me, so that's weird. (even on mangas that have that error when tryig to update)

**Comment by amayra** [comment]
i can't see that least update too

**Comment by Azerzra** [comment]
It displays the same thing too when trying to search for a series

**Comment by KasAgg21** [comment]
But it is still showing error
![Screenshot_20230514_183426_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/73023696/b7fdd8b3-d3f6-4773-9563-55c921c7f66f)

**Comment by CarlosEsco** [comment]
It was just merged in you have wait for the build to be released
