### ISSUE TITLE
No deja descargar capitulos

### ISSUE THREAD

**Issue by Carmen010601** [tachiyomiorg/tachiyomi-extensions#16426]
### Source information

InariManga 1.4.30

### Source language

Español

### Steps to reproduce

Al dar descargar el capítulo, inmediatamente manda error y dice que no hay páginas, así sucede con todos los capítulos que quiero descargar.

### Expected behavior

Debería descargar los capítulos al tener una fuente wifi

### Actual behavior

Aunque tenga wifi no los descarga y solo aparece que no hay páginas 

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 12 (SDK 31) Android build ID: S0RCS32.41-10-19-14 Device brand: motorola Device manufacturer: motorola Device name: caprip Device model: moto g(30) Device product name: caprip_retail

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seew3l** [comment]
Podrias proporcionar el nombre del manga con el que tienes ese problema?
