### ISSUE TITLE
Latest chapter of Berserk in readberserk.com not being updated

### ISSUE THREAD

**Issue by mbrozzo** [tachiyomiorg/tachiyomi-extensions#16420]
### Source information

Read Berserk Manga 1.4.3

### Source language

English

### Steps to reproduce

1. Install Read Berserk Manga 1.4.3
2. readberserk.com publishes a new chapter (chapter 372 in my case) with a temporary image (see below) indicating that said chapter still has to be published
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/22538059/84366787-c27a-4953-b8c9-e3ab6bc6ac60)
4. readberserk.com publishes said chapter: the temporary image is gone, in its place there is the actual chapter
5. Update Read Berserk Manga source in Tachiyomi (Library -> Read Berserk Manga -> move finger downwards)

### Expected behavior

The new chapter is updated with the new pages replacing the temporary image.

### Actual behavior

The new chapter is NOT updated with the new pages and only the temporary image can be viewed.

### Tachiyomi version

0.14.16

### Android version

Android 10

### Other details

Of course I have checked and the new pages can bee seen in the WebView.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Clear chapter cache should fix this
https://tachiyomi.org/docs/guides/troubleshooting/diagnosis#primary-diagnosis
