### ISSUE TITLE
worldmanhwas.in

### ISSUE THREAD

**Issue by lunarpix** [tachiyomiorg/tachiyomi-extensions#16431]
### Source information

Worldmanhwas 1.4.30

### Source language

Indonesia

### Source new URL

https://worldmanhwas.in/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Start38** [comment]
https://worldmanhwas.bar/

**Comment by scb261** [comment]
Closing in favor of #16793 since it has newer URL and the issue moderator bot checks it to find duplicates
