### ISSUE TITLE
MAL extension

### ISSUE THREAD

**Issue by Imon24** [tachiyomiorg/tachiyomi-extensions#16438]
### Source name

myanimelist

### Source link

https://myanimelist.net/

### Source language

English

### Other details

Need a myanimelist extension to observe the top list of manga and anime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
You can't read manga on it so it has no qualification to be an extension
