### ISSUE TITLE
Toonkor

### ISSUE THREAD

**Issue by Arjecortes123** [tachiyomiorg/tachiyomi-extensions#16448]
### Source information

ko.toonkor v1.4.4

### Source language

Korean

### Source new URL

https://toonkor.com

### Other details

hi admin this is my first time reporting an issue but thank you for developing the app 🥰❤

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
@Arjecortes123 
This URL is dead i recreate a new issue so close this one

**Comment by vetleledaal** [comment]
Closing in favor of #18744
