### ISSUE TITLE
Filters not working for Mangadex extension

### ISSUE THREAD

**Issue by AsuraSloth** [tachiyomiorg/tachiyomi-extensions#16443]
### Source information

Mangadex 1.4.177

### Source language

English

### Steps to reproduce

1. Click on Browse
2. Click on Mangadex
3. Click on Latest
4. Error 

### Expected behavior

Should filter Manga and display the results

### Actual behavior

We get this error below

![Screenshot_20230515-025627_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/85283488/4ddce010-5884-4728-97e4-24ad7340ccb3)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> I have updated all installed extensions.
