### ISSUE TITLE
Help The image couldn't be loaded 

### ISSUE THREAD

**Issue by VikrantBa** [tachiyomiorg/tachiyomi-extensions#16449]
### Source information

Source= manhwa18.cc

### Source language

English 

### Steps to reproduce

Help
The image couldn't be loaded
Source= manhwa18.cc

### Expected behavior

Help
The image couldn't be loaded
Source= manhwa18.cc

### Actual behavior

Help
The image couldn't be loaded
Source= manhwa18.cc

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

Help
The image couldn't be loaded
Source= manhwa18.cc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
It looks fine to me

![IMG_20230515_174900.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/50613c12-1f7d-405f-8f08-070a00452604)

![IMG_20230515_174836.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/384d13bf-5e1e-48ca-97d5-1e41c8ae31ca)

**Comment by alessandrojean** [comment]
Please do fill the issue form appropriately and provide extra information such as chapters and manga where this happens. Closing as it lacks information.
