### ISSUE TITLE
Anime-same site update

### ISSUE THREAD

**Issue by Urbexed** [tachiyomiorg/tachiyomi-extensions#16455]
### Source information

Anime-Same 1.4.1

### Source language

Français

### Source new URL

https://anime-sama.fr/

### Other details

The site made an update, the extension returns the 404 error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Urbexed** [comment]
Update

**Comment by scb261** [comment]
The extension already uses this URL. You should open bug report instead.
