### ISSUE TITLE
If I close the app in the middle of the chapter, I loose that chapter...

### ISSUE THREAD

**Issue by philitingar** [tachiyomiorg/tachiyomi-extensions#16450]
### Source information

Bato.to 1.4.31

### Source language

English

### Steps to reproduce

1. Read manga
2. Be in the middle of a chapter
3. Close the phone while the app is still open( it can happen even after 5 minutes)
3. Open the phone and the app is still open
4. When trying to read the current page I was on was ok , the next pages could not be loaded.
5. Closing and re- opening the app doesn't work. 
6. Attached you have a small video of what the manga looks like after I quit and reopened the app to see if it would fix the problem. 

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/108877052/1bc3c4ef-65b0-41cf-8e55-b1ace072aadc

### Expected behavior

I should be able to pick up where I left off and read through the manga without problems.

### Actual behavior

The page I was on loads the next doesn't.
None of the pages load until the end of the chapter.
Though the next chapter(after the one that didn't load) would load without problems.
I am not able to load those pages.

### Tachiyomi version

0.14.6

### Android version

Andriod EMUI 12.0.0.142

### Other details

This happened to me for a long time now, I have not written as I thought it might get fixed. My phone is up to date in updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Bato.to returns temporary URLs for images, you need to clear chapter cache in advanced settings. In future you can download chapters beforehand or use a different source
