### ISSUE TITLE
CosmicScans.ID: HTTP error 404

### ISSUE THREAD

**Issue by Shiin-79** [tachiyomiorg/tachiyomi-extensions#16473]
### Source information

CosmicScans.id 1.4.26

### Source language

Indonesia

### Steps to reproduce

The extension can't open and it's says HTTP error 404, and when i open webview it can.
![eror](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/56505683/f9697b65-26c5-4f37-9143-fea23e570276)

### Expected behavior

can't open the extension

### Actual behavior

The extension can't open and when i open webview it can.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Maybe need to add "/manga" on [overrides/mangathemesia/cosmicscansid/src/CosmicScansID.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/overrides/mangathemesia/cosmicscansid/src/CosmicScansID.kt#L5-L5)

Example:
`https://cosmicscans.id/manga/limit-breaker/`

```kotlin
class CosmicScansID : MangaThemesia("CosmicScans.id", "https://cosmicscans.id", "id", "/manga") {
```
