### ISSUE TITLE
Cerise Scans

### ISSUE THREAD

**Issue by Erick17x** [tachiyomiorg/tachiyomi-extensions#16489]
### Source information

Cerise Scans 1.4.33

### Source language

Português 

### Steps to reproduce

Primeira forma: 

1. Pesquiso o manga
2. Aparece mensagem de erro na extensão 

Segunda forma:
1. Vou em navegar 
2. Entro na extensão
3. Aparece a mensagem de erro 

![Screenshot_20230518_172941_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113395265/ad059588-3258-4724-8b6e-0b66f2643399)

### Expected behavior

Pesquisar um manga e aparecer ele ma extensão 

### Actual behavior

Pesquiso o manga e dá erro

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This means their website is down likely. Check if it's working on WebView and if it is, try the troubleshooting guide.

**Comment by Erick17x** [comment]
I identified through discord that the website URL has changed, should I send it here in the comment or open a new ticket?
