### ISSUE TITLE
Three Queens Scanlator com problemas

### ISSUE THREAD

**Issue by Erick17x** [tachiyomiorg/tachiyomi-extensions#16488]
### Source information

Three Queens Scanlator 1.4.32

### Source language

Portugues

### Steps to reproduce

A extensão está dando um erro no Java, 
![Screenshot_20230518_172011_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113395265/ce37e4c3-eada-49e4-8ba8-c45b61982528)

### Expected behavior

Pesquisar um manga e ele aparecer

### Actual behavior

Eu pesquiso o manga e ele dá o erro no java

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This means their HTTPS certificate is setup incorrectly or something in your network is hijacking your connection to the site. If it's the first case, there's nothing we can do and you need to wait for them to fix it, if it's the second case, you can try the troubleshooting guide linked in the acknowledgements section.

Also please consider filling the issues form in English to not get limited by only Portuguese speakers to triage and help in your issue.
