### ISSUE TITLE
Update comic at source Mangahere 

### ISSUE THREAD

**Issue by Hafizmohd88** [tachiyomiorg/tachiyomi-extensions#16491]
### Source name

Mangahere

### Source language

English

### Describe your suggested feature

Please update comic at source Mangahere to latest update

There several comic at Mangahere not updated so long time but at other source if up-to-date (MangaSee)

Example Title Comic not updated at Mangahere:
1) All-Out
2) Gun Blaze West
3) Fantasista 

# I prefer read only at one source: Mangahere, to avoid heavy traffic but because there some comic not updated, I installed several sources like MangaSee just for read the comic. 
Recommended for update. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
