### ISSUE TITLE
Wrong title should be On-Going I/o Complete 

### ISSUE THREAD

**Issue by Hafizmohd88** [tachiyomiorg/tachiyomi-extensions#16490]
### Source information

Mangahere

### Source language

English

### Steps to reproduce

Wrong title should be On-Going I/o Complete 

Unable to receive any update because title comic is Complete I/o should be On-Going.

Please fix it. 

Source: Mangahere
Comic : Solo Leveling 

### Expected behavior

Wrong title should be On-Going I/o Complete 

Unable to receive any update because title comic is Complete I/o should be On-Going.

Please fix it. 

Source: Mangahere
Comic : Solo Leveling 

### Actual behavior

Wrong title should be On-Going I/o Complete 

Unable to receive any update because title comic is Complete I/o should be On-Going.

Please fix it. 

Source: Mangahere
Comic : Solo Leveling 

### Tachiyomi version

0.14.6

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hafizmohd88** [comment]
![IMG_20230519_094726](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/134025032/765cb891-7e0a-4676-8af3-11e99ee7fe73)

Should be On-Going I/o Complete.
Solo Leveling is one of the best comic, not received update is very bad.

**Comment by Seishirou101** [comment]
its listed as completed on their website

Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
