### ISSUE TITLE
فشل في تجارز Cloudflare

### ISSUE THREAD

**Issue by Hmam2005** [tachiyomiorg/tachiyomi-extensions#16492]
### Source information

مانجا ليك 1.4.31

### Source language

العربية

### Steps to reproduce

عندما ابحث عن المانجا المطلوبه تظهر لي نافذه تقول فشل في تجارز Cloudflare ولا يظهر نتائج البحث المطلوبه 

### Expected behavior

يجب ان يظهر نتائج البحث المطلوبه 

### Actual behavior

لا يظهر نتائج البحث المطلوبه 

### Tachiyomi version

0.4.16

### Android version

Android emui 9.1.0

### Other details

![Screenshot_20230519_052130_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/134026727/8f8a12bb-6749-4186-98aa-7f97a763b185)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.

**Comment by Hmam2005** [comment]
> راجع قسم حل مشكلات Cloudflare على https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues . إذا لم ينجح الأمر ، فانتقل إلى مصادر أخرى أو انتظر حتى تبرهنوا من حمايتهم.

جربت حل مشكلة من الرابط بس نفس الشي ما فاد
عندي مصادر كثيرة بس هاذه الوحيد الي في كل الي احتاجه
