### ISSUE TITLE
Source request: Loner Translations

### ISSUE THREAD

**Issue by AlMohnad** [tachiyomiorg/tachiyomi-extensions#16529]
### Source name

Loner Translations

### Source link

https://loner-tl.blogspot.com/

### Source language

Arabic

### Other details

Single manga translator
![Screenshot_٢٠٢٣-٠٥-٢١-٠٢-٠٤-٣٥-٨٢١_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/134175138/3be1629e-8437-4e22-bc17-b9c38b410f7d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses ZeistManga theme
