### ISSUE TITLE
Asura Sans Bookmark Problem

### ISSUE THREAD

**Issue by CerealKiller7** [tachiyomiorg/tachiyomi-extensions#16538]
### Source information

Asura Scans 1.4.46

### Source language

English

### Steps to reproduce

1. Open the extension to browse
2. Bookmark or save to library any manhwa
3. Refresh the manhwa
4. Exit the extension 
5. Open the extension on browse again
6. Open the manhwa on webview that has been saved on the library

### Expected behavior

Manhwa that are saved on the library from extension A should have an indication when browsing said extension A.

### Actual behavior

You can save the same manhwa more than once without limit. Migration doesn't help. Webview redirect's to the homepage of the extension. Updating the manhwa still loads the chapters.

### Tachiyomi version

Tachiyomi J2K 1.6.6

### Android version

Android 13

### Other details

When the extension was updated I kept the older version as it worked having permanent URLs disabled. Only updated to the current version because the old one wasn't pointing at the correct URL of the extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kentemman** [comment]
Same Issues

**Comment by CerealKiller7** [comment]
Yo, I don't know what you did but the problem still occurs.

**Comment by CerealKiller7** [comment]
The issue still occurs
