### ISSUE TITLE
Algodão Doce

### ISSUE THREAD

**Issue by fujoshiit2** [tachiyomiorg/tachiyomi-extensions#16545]
### Source name

Algodão Doce Scan

### Source link

https://xn--mfiadoce-8ya.com.br/

### Source language

Português

### Other details

Uses Madara Theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Site is password protected and hence an extension can't be created at the moment since we need to be able to open the website to test and code the extension. Closing for the moment, but can be reopened and added if the password is provided.
