### ISSUE TITLE
Pola Gacor Princess > Link Pola Slot Gacor Starlight Princess Terbaru 2022 2023

### ISSUE THREAD

**Issue by gunungmaruku** [tachiyomiorg/tachiyomi-extensions#16557]
### Source information

https://twtr.to/hwat1

### Source language

https://twtr.to/appsct

## [►👉 DAFTAR AKUN GAMPANG GACOR](https://twtr.to/appsct)

Pola gacor princess merupakan provider starlight princess slot terbaik dan merupakan provider slot terfavorit di indonesia. Dimana pada provider pola gacor princess anda gampang untuk merasakan maxwin hingga jutaan rupiah bahkan ratusan juta. Game slot yang sering dimainkan orang seperti sweet bonanza dapat anda mainkan di link pola gacor princess. Slot online terpercaya link pola gacor princess juga memiliki pelayanan yang baik, dari cs 24 jam, proses deposit 1 menit dan link untuk mengecek rtp secara real time. Semua game pragmatic play dapat anda mainkan dengan minimal bet rp. 200 Dengan minimal deposit hanya 25k rupiah.

Hanya dengan modal 25 ribu saja anda pasti akan memenangkan uang dengan minimal 100 ribu dan jika anda sangat beruntung maka anda akan merasakan maxwin dengan 5000x bet anda. Semakin besar anda deposit, kemungkinan menang anda juga akan besar. Di pola gacor princess dengan modal yang receh akan merasakan tarik dana rasa sultan jika anda mengikuti trik, tips dan pola yang kami berikan dan bermain di jam yang sesuai dengan pengalaman member kami. Anda juga dapat menanyakan trick dan tips bermain game slot online ke wa cs 24 jam dan live chat pola gacor princess dengan respon yang sangat memuaskan. Disini juga dapat melakukan deposit dengan berbagai macam bank, e-wallet dan juga pulsa. Anda juga dapat mengajak teman anda untuk bermain di pola gacor princess dan anda akan berhak mendapatkan free bet dari link pola gacor princess, dan langsung dapat di tarik dana kan tanpa to.

### Expected behavior

Able to show all possible manga and manwha and all possible search and filter.

### Actual behavior

No results found

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Dude it like phising website 🙂
And it's an online gambling website 🤦🏻‍♂️
Can someone Delete, Remove, or Hidden this Issues?
