### ISSUE TITLE
Comick.fun: Add option to use low quality covers

### ISSUE THREAD

**Issue by Berserk0001** [tachiyomiorg/tachiyomi-extensions#16572]
### Source name

Comick

### Source language

English

### Describe your suggested feature

Manga covers loads very slow on comick extension.
I tested the image url and found that if you add -s before .jpg on the image url then the cover images are compressed..Please do this..
https://meo.comick.pictures/pzn60-s.jpg (59.19 KB)

https://meo.comick.pictures/pzn60.jpg (464.16 KB)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
/edit-title "Comick.fun: Add option to use low quality covers"

**Comment by Berserk0001** [comment]
Thanks
