### ISSUE TITLE
Mangex wont load any Manga

### ISSUE THREAD

**Issue by Ylgnik** [tachiyomiorg/tachiyomi-extensions#16573]
### Source information

Mangadex 1.4.178

### Source language

English

### Steps to reproduce

1.Download Mangadex
2.Open any Manga and pages fail to load. I've tried data and wifi and it won't even download them. It works in the browser part.

### Expected behavior

Manga should load?

### Actual behavior

Manga doesn't load

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tokisuno** [comment]
experiencing the same issue on my onyx boox note5

**Comment by alessandrojean** [comment]
Closing as this is not an extension issue.
