### ISSUE TITLE
jinman tiantang

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#16589]
### Source information

jinman tiantang 1.4.36

### Source language

Chinese

### Steps to reproduce

1.Connect to a VPN
2.Open the  jinman tiantang extension
3.Click on any of them，the manga catalog could not be loaded

### Expected behavior

The manga catalog could  be loaded

### Actual behavior

The manga catalog could not be loaded

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

On the webview, it shows that Cloudflare cannot be bypassed.
This may be caused by the network environment in some regions, but at present, even if you use a VPN, you will not be able to load the manga catalog properly.
![Screenshot_2023-05-26-18-27-01-512_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/b1af22a4-2b17-4dc4-93cd-ba2ae758725d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
That's an issue of your VPN. Try changing your network environment. Or select another mirror URL in extension settings.
