### ISSUE TITLE
[Webtoons] Author's notes missing

### ISSUE THREAD

**Issue by SebiderSushi** [tachiyomiorg/tachiyomi-extensions#16593]
### Source information

Webtoons 1.4.39

### Source language

English

### Steps to reproduce

1. Install Tachiyomi
2. Allow All files access
3. Set up a download directory
4. Install Webtoons extension
5. Choose which languages to enable. For each, open language settings and enable "Show author's notes"
6. Add a comic with authors notes, for example "As Per Usual" by Dami Lee
8. Open the first chapter (Optionally, download it beforehand)
9. Look inside

### Expected behavior

See author's notes at the end of the chapter.

### Actual behavior

No author's notes.

I have downloaded the same chapter with Tachiyomi in the past and that file contains author's notes. If i download it now it doesn't.

### Tachiyomi version

Stable 0.14.6 (official build)

### Android version

LineageOS 18.1 (Android 11)

### Other details

I don't know if the feature stopped working with a recent update to Tachiyomi or the Webtoons Extension.
I can only pin it down to a timeframe. The latest chapter of a webcomic where author's notes were consistently downloaded successfully on my device has an mtime of `2023-05-04 15:12`. The next chapter was released `2023-05-11`, i'm not entirely sure when i downloaded it but it's the first chapter where i noticed the author's notes were missing. If i redownload older chapters now they also don't contain any author's notes while my local copies do.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by altaccosc** [comment]
Sorry for not catching this sooner! Thanks for reporting it :D
I've been rather busy and haven't been reading much...
But now I've fixed it! Just need to wait for it to be merged :)
