### ISSUE TITLE
fakeimg.pl is down, breaks XKCD source and Swords Comic source 

### ISSUE THREAD

**Issue by lord-ne** [tachiyomiorg/tachiyomi-extensions#16595]
### Source information

xkcd 1.4.13, Swords Comic 1.4.3

### Source language

English

### Steps to reproduce

Open any chapter in XKCD or Swords Comic. Go to second page to view title text 

### Expected behavior

Page with title text should appear 

### Actual behavior

"Retry" button appears 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

XKCD (in some languages) and Swords Comic depend on an external website, [fakimg.pl](https://wwe.fakeimg.pl), to render the title text as images. The website appears to currently be down. 

If the website remains down for an extended period of time, we will need to update these extensions to use a different website.

(As a sidenote, I've always been slightly uncomfortable with the idea that these extensions depend on an unrelated external website to function. Perhaps we could explore some method of generating an image of the title text locally, and putting a base64 data URL as the image url of the Page? This could potentially be a more robust solution)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
fakeimg.pl is up again, closing.

> (As a sidenote, I've always been slightly uncomfortable with the idea that these extensions depend on an unrelated external website to function. Perhaps we could explore some method of generating an image of the title text locally, and putting a base64 data URL as the image url of the Page? This could potentially be a more robust solution)

Please open a feature request for this.
