### ISSUE TITLE
Disaster Scans Website Changes

### ISSUE THREAD

**Issue by MaxMaiche** [tachiyomiorg/tachiyomi-extensions#16596]
### Source information

Disaster Scans 1.3.30

### Source language

English

### Steps to reproduce

They changed their website so the source is dead

### Expected behavior

Load new chapter 

### Actual behavior

Error 404

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by C0LiSii0N** [comment]
Change of structure more than adress change, for exemple;
https://disasterscans.com/manga/martial-peak
Changed to;
https://disasterscans.com/comics/11422-martial-peak

Also, need to accept cookie before being able to interact with the website.

**Comment by I-Am-C0der** [comment]
Hope they fix this soon. 2 weeks worth of Martial Peak chapters are pending for me to read😅

**Comment by MaxMaiche** [comment]
> 

Read it online, got 17 chapter already xddd
