### ISSUE TITLE
Nix Mangás: No chapters found

### ISSUE THREAD

**Issue by Erick17x** [tachiyomiorg/tachiyomi-extensions#16603]
### Source information

Nix Mangás 1.4.2

### Source language

Português(Brasil)

### Steps to reproduce

1. I look for and find a manga in the extension. 
2.  open the manga, and i see my problem

### Expected behavior

1. I look for and find a manga in the extension. 
2.  open the manga, add it to the library and download the chapters

### Actual behavior

I open the manga, but I can't see or download the chapter.  only works through webview

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Erick17x** [comment]
Sorry, I forgot to send the images.
I am sending now. 

Appears like this in the APP
![1](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113395265/f10b3018-f942-4656-9875-45cd62ad92e4)

And it appears like this in WEBVIEW
![2](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113395265/da5ffdc0-e802-4d39-958e-00461dd41ce6)

**Comment by Erick17x** [comment]
Good evening, 

The problem continued
![Screenshot_20230612_214703_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113395265/f1a90c5c-4c57-4071-b4e1-967383909ee7)

**Comment by Erick17x** [comment]
![Screenshot_20230612_215338_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113395265/40fdcec7-9781-4fda-b9d5-9dc1c64bc92c)

**Comment by alessandrojean** [comment]
The update isn't available yet, you need to wait for it to appear in the app.
