### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by Haiyoe** [tachiyomiorg/tachiyomi-extensions#16601]
### Source name

Siren Komik

### Source link

https://sirenkomik.my.id

### Source language

Indonesian

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Haiyoe** [comment]
Duplicate Complaint

I am filing this complaint because, the site or website that I registered for source was detected _**Duplication**_, even though this is the first time I registered it, maybe there are _**other people out there who registered it too**_, but I hope the source request can be approved.

**Comment by TheKingTermux** [comment]
> Duplicate Complaint
> 
> I am filing this complaint because, the site or website that I registered for source was detected _**Duplication**_, even though this is the first time I registered it, maybe there are _**other people out there who registered it too**_, but I hope the source request can be approved.

Uhh... someone already made a similar issue on #16116 where someone has asked to make a source request.
So what the bot is doing is correct
