### ISSUE TITLE
No chapters found on Latis Books (Bodysuit 23)

### ISSUE THREAD

**Issue by ORLOX93** [tachiyomiorg/tachiyomi-extensions#16624]
### Source information

Latis Books 1.4.4

### Source language

English

### Steps to reproduce

1. Open Bodysuit 23 comic.
2. try to update by swiping down.
3. No chapters found.

### Expected behavior

New chapters should appear if available (at the moment there aren't) or no message should appear if there aren't new chapters.

### Actual behavior

The no chapters found message and a little error shows up every time i update the category the comic is in.

### Tachiyomi version

0.14.6

### Android version

Android 8

### Other details

The mesage also shows up when updating the library/category.

The problem seems to be that they added an /obligatory-warning/ page that shows up before the archive, also the structure of the archive seems to have changed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Enriath** [comment]
I am unable to reproduce this on Tachiyomi v0.14.6, extension v1.4.4, Android 11.

The obligatory warning page does not really affect the extension, as it goes directly to /archive/, where the warning is not shown.

**Comment by ORLOX93** [comment]
It was affecting it, but at some point the message stopped appearing. Seems like i forgot to mention that old chapters where working fine, the problem was only if you tried to get new chapters.

As i said, one day like a week or two after i posted the issue, the problem just fixed itself.
