### ISSUE TITLE
Kumapoi Change Domain

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi-extensions#16626]
### Source information

Kumapoi 1.4.25

### Source language

ID

### Source new URL

https://komiksay.site

### Other details

on the website there are features for 18+ and not, so please add features too 
Thanks 🙏😁

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by nexxy110708** [comment]
Is it the same website as Kumapoi? Because when I searched for the Hero Villain manhwa, I couldn't find it
