### ISSUE TITLE
not open comic doujin

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi-extensions#16629]
### Source information

Doujindesu 1.4.3

### Source language

ID

### Steps to reproduce
------- beginning of system
--------- beginning of main
05-31 19:58:04.705  9503  9617 E libEGL  : Invalid file path for libcolorx-loader.so
05-31 19:58:10.723  9503 12779 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.16
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2

Cannot open comic

### Expected behavior

Cannot open comic
I use dns but it still doesn't work
And mode WebView no work

### Actual behavior

![Screenshot_2023-05-31-19-42-43-17_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100791931/738d70e5-fb82-470b-9949-af4843ce4695)

### Tachiyomi version

Last

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
If you use Tachiyomi in normal mode (Not using WebView) then it won't work, please read #14004 for explanation.
If you use WebView (which is available in the application) then you must use a VPN (if it is blocked) or change the [Android User Agent (Please see here how to change it)](https://tachiyomi.org/help/guides/troubleshooting/#changing-your-user-agent)
