### ISSUE TITLE
vomic

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#16625]
### Source information

vomic 1.4.1

### Source language

Chinese

### Steps to reproduce

1.打开插件里任意漫画
2.选择漫画任意章节

### Expected behavior

漫画可以加载出内容

### Actual behavior

只加载出一页
![Screenshot_2023-05-31-13-53-14-189_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/21b68ca4-36b2-4252-9b70-4fbf73981c81)

### Tachiyomi version

0.14.6

### Android version

Android12

### Other details

app插件里无法正常加载，网页版则没问题

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
请提供网页版正常加载的截图，以及对应链接。

**Comment by RX93CN** [comment]
![Screenshot_2023-05-31-14-03-13-637_com mmbox xbrowser](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/7de6d8e4-b49e-4b24-9f31-7ccb1efd3469)
网站:http://www.vomicmh.com
![Screenshot_2023-05-31-14-05-34-242_com mmbox xbrowser](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/96427dc6-cd7f-473f-ad28-3f1226f6eab4)
网站:http://www.iewoai.com/#/home

**Comment by RX93CN** [comment]
插件提供的两个站点在tachiyomi里无法正常加载，在浏览器网页中能正常观看
