### ISSUE TITLE
Cuu Truyen chapter can watch, chapter can't watch

### ISSUE THREAD

**Issue by dejavui** [tachiyomiorg/tachiyomi-extensions#16623]
### Source information

Cuutruyen 1.4.5

### Source language

Vietnamese

### Steps to reproduce

1. Select Random manga
2. Open Random 2 chapter in manga

### Expected behavior

Cuutruyen need update scrips

### Actual behavior

@beerpiss You need to update ext Cuutruyen ^^
Are you the one who uploaded the manga to MangaDex? If so, you can inbox the translation team to upload files images highres ^^

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
> Are you the one who uploaded the manga to MangaDex? If so, you can inbox the translation team to upload files images highres ^^

Who The Fuck Asked?

**Comment by beerpiss** [comment]
Also please specify what manga you're having issues with, Random is a song, not a manga.

**Comment by dejavui** [comment]
> Also please specify what manga you're having issues with, Random is a song, not a manga.
https://photos.app.goo.gl/nKQEwGFqrroQVZHW6

**Comment by beerpiss** [comment]
Settings -> Advanced -> Clear chapter cache and try again.

![Screenshot_20230531-152319.png](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92439990/f7a63cb3-dac9-45d7-9f03-b097faac3438)

**Comment by dejavui** [comment]
> Settings -> Advanced -> Clear chapter cache and try again.
> 
Clear cache now read manga no problem. Thank
Cuutruyen Manga search is still a bit problematic. 
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/62763969/7fe62483-9da5-47fc-aeeb-4e237fda5e2b)

**Comment by beerpiss** [comment]
Close this one and create a separate issue. Also for the love of god, please stop pinging me specifically to fix something.
