### ISSUE TITLE
Arena scans.net have raised their Cloudflare protection level

### ISSUE THREAD

**Issue by BrownIndianGuy** [tachiyomiorg/tachiyomi-extensions#16635]
### Source information

Arena Scans 1.4.26

### Source language

English 

### Steps to reproduce

![Screenshot_20230531-232320~2](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/54560621/3728a42c-1451-4875-b9b0-c5101b26dcfc)

### Expected behavior

It should load fine (?)

### Actual behavior

The site won't load neither in app or webview

### Tachiyomi version

App version: 1.9.3 (fork sy)

### Android version

Android version: 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Aniell4** [comment]
having same issue

**Comment by vetleledaal** [comment]
No longer using Cloudflare's IUAM
