### ISSUE TITLE
KomikIndoID has changed their url domain

### ISSUE THREAD

**Issue by telesia66** [tachiyomiorg/tachiyomi-extensions#16643]
### Source information

komikindoid 1.4.9

### Source language

Indonesia

### Source new URL

https://komikindo.app/

### Other details

komikindoid 1.4.9

Old URL
https://komikindo.pro/

Source new URL
https://komikindo.app/

please update the new url
please update the new url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by telesia66** [comment]
![Uploading images (32).jpeg…]()

**Comment by telesia66** [comment]
![images (32)](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/128944707/346b06c5-6755-4023-b5e3-04a039542152)

**Comment by Azerzra** [comment]
Yes please
