### ISSUE TITLE
Banana-Scan

### ISSUE THREAD

**Issue by Kreliam** [tachiyomiorg/tachiyomi-extensions#16640]
### Source name

Banana-Scan

### Source link

https://banana-scan.com/

### Source language

French

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Urbexed** [comment]
Mais il a l'air trop bien ce site ! Je connaissais pas merci 😂

**Comment by Kreliam** [comment]
> Mais il a l'air trop bien ce site ! Je connaissais pas merci 😂

De rien , j'espère que tu apprécie bientôt la nouvelle extension qui arrive   👍

**Comment by KirinRaikage** [comment]
Salut, le site devrait arriver très prochainement, j'essaie juste de corriger un souci de date dans les chapitres !

**Comment by Kreliam** [comment]
> Salut, le site devrait arriver très prochainement, j'essaie juste de corriger un souci de date dans les chapitres !

Merci beaucoup 😃
