### ISSUE TITLE
Mangakomi Error 500 

### ISSUE THREAD

**Issue by 00grezt** [tachiyomiorg/tachiyomi-extensions#16656]
### Source information

Mangakomi 1.4.34

### Source language

English

### Steps to reproduce

1. I open the latest on Mangakomi extension to see if there's any new chapter / update.
2. It shows "Error 500 : Check website in WebView."
3. I open the WebView. It's looks normal.
4. I go back to the apps and it's still show "Error 500".

![Screenshot_2023-06-02-06-00-00-30_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31199044/0785fe2d-9d09-4fe1-b7cc-0f19f51fb914)
![Screenshot_2023-06-02-06-00-16-96_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31199044/0bc92a30-53ae-414f-a7a5-9f43d5207b63)

### Expected behavior

Showing the latest chapter.

### Actual behavior

Error 500

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 00grezt** [comment]
.

**Comment by Riztard** [comment]
working fine
cant reporoduce
