### ISSUE TITLE
TachiyomiSY extensions gets deleted everytime I close app.

### ISSUE THREAD

**Issue by AnuragDevx** [tachiyomiorg/tachiyomi-extensions#16659]
### Source information

All

### Source language

English 

### Steps to reproduce

1. Extensions downloaded.
2. Comics added to library.
3. Chapters readable and downloadable right after installation.
4. Close/Exist the app.
5. Reopening the app and the comics in library still present.
6. But extensions not showing
7. Comics not readable.

### Expected behavior

After installation extensions and adding books to library and opening the app after closing. It should show all the downloaded extensions.

### Actual behavior

The extensions gets removed from the app after closing the app. But the extensions are still shown installed on device in device settings.

### Tachiyomi version

TachiyomiSY- "1.9.3"

### Android version

Android 10

### Other details

I recently formatted my device and was installing the app and importing backup but all extensions were removed after opening it. Tried reinstalling but that didn't workout.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please report this in SY repository instead.
