### ISSUE TITLE
Jiangzaitoon: Changed their domain 

### ISSUE THREAD

**Issue by moryldz** [tachiyomiorg/tachiyomi-extensions#16661]
### Source information

Jiangzaitoon v1.4.30

### Source language

Turkish

### Source new URL

https://jiangzaitoon.io/

### Other details

Jiangzaitoon changed their domain
![IMG_20230602_090119](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/135305026/ad39c90f-d9e8-4f39-ac6c-b8046dde9127)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by 7Nekoma** [comment]
Bu bağlantı kapalı. 
Birkaç gün sonra yeni bağlantıyı paylaşacaklar.

**Comment by 7Nekoma** [comment]
"sorunu kapat" kısmından bu gönderiyi kapatabilir misin?
Yeni linki paylastim, eski olanla karıştırıp onu yüklemesinler 💖

**Comment by stevenyomi** [comment]
New domain: #16698
