### ISSUE TITLE
KomikIndoID 

### ISSUE THREAD

**Issue by RamaDark** [tachiyomiorg/tachiyomi-extensions#16665]
### Source name

KomikIndoID 

### Source language

Bahasa Indonesia 

### Source link

https://komikindo.pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16643
