### ISSUE TITLE
Nekopost is unable to search manga.

### ISSUE THREAD

**Issue by veerawatS** [tachiyomiorg/tachiyomi-extensions#16678]
### Source information

Nekopost 1.4.9

### Source language

Thai

### Steps to reproduce

1. Install the latest extension
2. Try to search manga

### Expected behavior

List expected manga(s).

### Actual behavior

return "HTTP error 520"

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Path "$fileHost/dataJson/dataProjectName.json" is invalid, so the way to search manga need changed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
They added encryption to the search API without updating the frontend, so the site itself is broken.

Nothing can be done from Tachiyomi's side. You should direct the issue (broken search on the site) to them directly:
- https://www.facebook.com/nekopost
- https://line.me/ti/g2/2ho-sWbz_43cDiAYeWQH5g?fbclid=IwAR0j9Olf3oD_sQUxcl9VSoWLBoymkaww-Sq4Gr0T6oMlrA7ORWu8c5P72cY
- https://discord.gg/QVfcuEtp5t
