### ISSUE TITLE
XOXO Comics Extension "No Chapters Found, NullPointerException: Null"

### ISSUE THREAD

**Issue by JosephYLee** [tachiyomiorg/tachiyomi-extensions#16671]
### Source information

XOXO 1.4.3

### Source language

English

### Steps to reproduce

1. Browse for extension "XOXO Comics"
2.  Install "XOXO Comics"
3. Navigate to the "Sources Tab"
4. Select XOXO Comics
5. When selected all books state "No Chapter Found" and provide the error "NullPointerException: Null"

### Expected behavior

When a book is selected the chapters should populate and allow downloading/adding to library

### Actual behavior

When selected all books state "No Chapter Found" and provide the error "NullPointerException: Null"

### Tachiyomi version

1.6.6

### Android version

Android 13

### Other details

The website is online, when opened in web view books are able to be read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Foxlass** [comment]
Same issue here. Was working fine just a few minutes ago.

**Comment by Weebnurr** [comment]
It has stopped working.

**Comment by PokemasterDude** [comment]
Same issue, plus I cannot search on the extension (it only provides the first few "trending" comics), and comics I've already added to my library respond with "no pages found" per issue UNLESS I already have said issue downloaded, which in that case it works fine.

**Comment by EvanSinaga** [comment]
Can someone confirm, is that because domain name? Instead of xoxocomics.net, the extension use xoxocomics.com

**Comment by maurorb** [comment]
Having the same problem here. Downloaded comics work fine, but can't search new ones nor read the ones I saved without downloading.
The site works fine. Just the extension seems to be having issues

**Comment by GreenTambourine** [comment]
Still not working here. If it is because of the domain name, is there a way for users to fix it on our end?
