### ISSUE TITLE
Hentaivn change domain 

### ISSUE THREAD

**Issue by CuongBa956** [tachiyomiorg/tachiyomi-extensions#16686]
### Source information

HentaiVN 1.4.24

### Source language

Vietnamese

### Source new URL

https://hentaivn.site

### Other details

The old domain name is still working properly but can't pass cloudflare. According to the announcement from the website owner, this domain name will not have cloudflare protection.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Fixed by #16681
