### ISSUE TITLE
Manga Hentai "no result found"

### ISSUE THREAD

**Issue by AstroAnasTariq** [tachiyomiorg/tachiyomi-extensions#16687]
### Source information

Manga Hentai 1.4.31

### Source language

English

### Steps to reproduce

when open the extension there is no data found

### Expected behavior

listed mangas

### Actual behavior

 no data found

### Tachiyomi version

1.4.31

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anotherluffy** [comment]
I can confirm that it is still an issue.
