### ISSUE TITLE
Fiz manga cover not loading 

### ISSUE THREAD

**Issue by Ironmanash** [tachiyomiorg/tachiyomi-extensions#16699]
### Source information

Fiz manga 1.4.29

### Source language

English 

### Steps to reproduce

Open any manga on fiz extension 
No covers load 

### Expected behavior

The covers you appear 

### Actual behavior

The cover are blank or black 

### Tachiyomi version

App version: 0.14.6 

### Android version

13 (SDK 33)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by heartlog** [comment]
Addition info (fore help)
Fizmanga changed/moved/merged it's website with `1stkissmanga.me`.
Some code has changed from original fizmanga(old) website.

I suggest changing extension name. BC: original domain is actually redireting to 1stkissmangame.
