### ISSUE TITLE
Komiksan

### ISSUE THREAD

**Issue by julptk** [tachiyomiorg/tachiyomi-extensions#16701]
### Source information

Komiksan 1.4.26

### Source language

Indonesian

### Steps to reproduce

he change derectory manga from /manga to /list

### Expected behavior

load all manga list

### Actual behavior

nothing there, just blank

### Tachiyomi version

0.14.6

### Android version

Android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by OdisBy** [comment]
What is the url of Komiksan?

**Comment by julptk** [comment]
komiksan.ml

**Comment by vetleledaal** [comment]
> komiksan.ml

that domain does not resolve for me. did they move?

**Comment by AvuxDemons** [comment]
> > komiksan.ml
> 
> that domain does not resolve for me. did they move?

hello , sorry for the source down 
we're moving to https://komiksan.link
