### ISSUE TITLE
Source:Batoto  cover not loading.

### ISSUE THREAD

**Issue by heartlog** [tachiyomiorg/tachiyomi-extensions#16712]
### Source information

Bato.to 1.4.31

### Source language

Multi, english

### Steps to reproduce

1. Add mangas from bato.to source
2. Close app & clear cache Or restart mobile.
3. Cover of some manga will not load, even after doing universal update.(same behaviour when auto metadata update is on)

### Expected behavior

Cover should load at least after doing global update.

### Actual behavior

Instead of manga cover **black portion** is shown.
![Screenshot_20230610_184627_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/76758776/9f5c0d03-e9cd-4828-b68f-6519e5ac1124)
*Please ignore name of manga

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

The cover only loads of i individually load(refresh) manga one by one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jack-weilage** [comment]
I had this exact same problem, and solved it by following the steps in [this comment](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/8850#issuecomment-906875162).

LMK if that works for you as well.

**Comment by alessandrojean** [comment]
Closing as this is the site's fault as they use temporary URLs for the covers.
