### ISSUE TITLE
Rh2PlusManga: Show "No page found" when click to read

### ISSUE THREAD

**Issue by nonnapat110347** [tachiyomiorg/tachiyomi-extensions#16715]
### Source information

Rh2PlusManga 1.4.33

### Source language

TH

### Steps to reproduce
[<img src="https://img.pic.in.th/Screenshot_20230611_004718_Tachiyomi.jpeg" alt="Screenshot_20230611_004718_Tachiyomi.jpeg" border="0" />](url)
**1.** whatever going to read any manga, it always shows "No page found".
.
**p.s. I checked in the webview, it's normal, but in the tachiyomi app it shows "No page found".**

### Expected behavior

**Normally, when we click to read  It must show the image of the manga.**

### Actual behavior

**Normally, when we click to read  It must show the image of the manga.**

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details
**I checked with other extensions, it's normal, it's only the extension of Rh2plusManga their only show "No page found".**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by godSlap10122** [comment]
I have the same problem with manganelo, it keeps saying no page found event though the new chapter is still fine on the website

**Comment by nonnapat110347** [comment]
> I have the same problem with manganelo, it keeps saying no page found event though the new chapter is still fine on the website

You have the same problem as me.
