### ISSUE TITLE
Mangahub

### ISSUE THREAD

**Issue by kkeyden** [tachiyomiorg/tachiyomi-extensions#16723]
### Source information

Mangahub 1.4.31

### Source language

English

### Steps to reproduce

I cannot read any mangahub scan on tachiyomi 

### Expected behavior

Normaly I use mangahub as my source to read on tachiyomi.

### Actual behavior

Everytime I want to read with mangahub, it says " API rate limit excessed! Go to mangahub.io to
continue reading!"

### Tachiyomi version

Stable 0.14.6

### Android version

Android 12

### Other details

![Screenshot_20230611-170130_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/129910874/3767ff81-2c5b-4e6f-92c9-f68097e110e1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#16481

**Comment by kkeyden** [comment]
Thank you
