### ISSUE TITLE
AllHentai: Chapters are not updated

### ISSUE THREAD

**Issue by kin1199** [tachiyomiorg/tachiyomi-extensions#16733]
### Source information

AllHentai 1.4.36

### Source language

Russian 

### Steps to reproduce

1. Go to the Tachiyomi app
2. Go to the AllHentai source
3. Choose any manga
4. Try to update the manga

### Expected behavior

The chapters should be updated as they are on the site

### Actual behavior

Chapters are not updated, although they are on the site

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

The chapters stopped updating after installing the new version of the AllHentai 1.4.36 extension
![Screenshot_2023-06-13-19-49-43-112_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/119662851/1c6a6138-d4fe-4a9a-b8cc-3c249892f264)
![Screenshot_2023-06-13-19-49-28-555_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/119662851/07fa7f44-7421-437b-a2ee-e0d713463a06)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nyartie** [comment]
The same trouble. Also tried to change link to previous version n reinstall add-on, but nothing changed.

**Comment by MM001-r** [comment]
All the same problem. For almost a week he writes that there are no chapters, although they are on the site ...

**Comment by kin1199** [comment]
The extension has been updated to version 1.4.37, and the bug has been fixed in it, now the extension works like clockwork
