### ISSUE TITLE
Mangaswat can't update the chapters

### ISSUE THREAD

**Issue by Tian-77** [tachiyomiorg/tachiyomi-extensions#16740]
### Source information

ar.mangaswat 1.4.33

### Source language

"Arabic"

### Steps to reproduce

Can't update any new chapters it keeps saying "no chapters found"

### Expected behavior

It should be able to update the new chapters

### Actual behavior

But this message appears "no chapters found"

### Tachiyomi version

1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment]
![Screenshot_2023-06-15-13-08-14-032_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97411710/ad5829bb-ca35-4b8d-a234-1432debe8431)

**Comment by MRmustafa478** [comment]
I just want to mention that with being all above right , the old chapters is still working the problem is only with the new chapters .
And the WebView don't have any problems .

**Comment by MRmustafa478** [comment]
![Uploading IMG_٢٠٢٣٠٦١٧_١٧٢٢٥٤.jpg…]()

**Comment by MRmustafa478** [comment]
![Uploading IMG_٢٠٢٣٠٦١٧_١٧٢٢٥٤.jpg…]()

**Comment by MRmustafa478** [comment]
![Uploading IMG_٢٠٢٣٠٦١٧_١٧٢٢٥٤.jpg…]()
