### ISSUE TITLE
No page found & no chapter found

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#16745]
### Source information

.

### Source language

.

### Steps to reproduce

I've been looking in the issues and many of them having this problem even though the source is not down

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the information asked. Closed for lack of information.

**Comment by 7allom** [comment]
> Please do fill the information asked. Closed for lack of information.

No i don't mean only myself but even other Tachiyomi users
