### ISSUE TITLE
Reaper Scans (English): No pages found

### ISSUE THREAD

**Issue by Turhvjbufv** [tachiyomiorg/tachiyomi-extensions#16756]
### Source information

reaperscans 1.4.43

### Source language

English 

### Steps to reproduce

Download reaperscans extension and open the source, choose any manhwa and open any chapter, will show no pages 

### Expected behavior

Shows manhwa's pages

### Actual behavior

Shows "no pages found"

### Tachiyomi version

tachiyomi sy r522

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaMoradi** [comment]
chapter pages also fail to download.

**Comment by Hawksaran** [comment]
Same for me also

**Comment by asdkant** [comment]
Same happens with TachiyomiJ2K v1.6.6 / reaperscans v1.4.43

**Comment by nobile01** [comment]
This is the error I get now 
![Uploading Screenshot_20230621-112530.png…]()

**Comment by Turhvjbufv** [comment]
Reaperscans is obsolete since they keep breaking the extension

**Comment by Turhvjbufv** [comment]
> > Reaperscans is obsolete since they keep breaking the extension @Kenn876 @nobile01
> 
> They don't seem to break the extension though. Atleast according to the Reddit the issue is more with CloudFlare which sort of could be true if you have have lot of comics on your reading list from there and update all of them regularly. Sadly can only wait Tachiyomi team to bring the extension back at some point

> maybe Not intentionally but they do break the extension

**Comment by arkon** [comment]
Not much point in speculating here, it's intentional on their side so it's a waste of time and effort for us to try to constantly fix the extension.

Either use a different source that has the same content or read on their website to give them the ad revenue that they're probably seeking.

**Comment by Lharci** [comment]
Hmm, this is quite disappointing😕.. I prefer to download chapters and read them later cause of network, and now this happens🤦‍♂️

**Comment by Turhvjbufv** [comment]
Same lol yeah it sucks but what can we do
