### ISSUE TITLE
Manwa.me download and read only showing 3 pages

### ISSUE THREAD

**Issue by rebeccafeng1995** [tachiyomiorg/tachiyomi-extensions#16752]
### Source information

Manwa 1.4.2

### Source language

Chinese

### Steps to reproduce

1. Open any manga
2. Click on a chapter
3. Shows normal chapter pages (all pages)
4. Repeat step 3-4 for other chapters of the same manga or different manga from this extension
5. Open webview of the chapter that shows only 3 pages
6. Click on open in browser from drop down

1. Add 10 chapters to download
2. Switch to download screen for monitoring

### Expected behavior

Shows all pages from any chapter, all chapters added to download shows the number of pages to be downloaded that matches the actual page number of the chapter

### Actual behavior

After opening 3-4 or sometimes 5 chapters, the manga chapter will start to show only 3 pages. All subsequent chapters from the mnaga or other manga from this extension will only show the first 3 pages. 

Open webview from tachiyomi, and the manga still only shows 3 pages. But once open in browser from the drop down, the manga shows all pages again (browser in tachiyomi shows the same 3 pages seen in tachiyomi app, but browser view is normal for the manga).

The downloads from this extension has the same problem, where after downloading about 4 chapters, the page number turns to 3 for all subsequent chapters for all manga from this extension. 

This can be fixed by clear cookie, but once cookie is cleared the website kicks out the log in and requires new log in for hidden manga. 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
This also happens for me on browser (Firefox on Android). So this is probably server issue.

**Comment by stevenyomi** [comment]
Is this still happening? If not. I'll close this issue.

**Comment by rebeccafeng1995** [comment]
Still happening, Im still using the clear cookies trick as of now.

**Comment by rebeccafeng1995** [comment]
I will open a new request as issue has changed.
