### ISSUE TITLE
1st kiss manhua

### ISSUE THREAD

**Issue by Killer31g** [tachiyomiorg/tachiyomi-extensions#16762]
### Source information

1st kiss manhua 1.4.33

### Source language

English

### Steps to reproduce

1st kiss works normally but app doesn't load chapters.

### Expected behavior

Chapters should load and be able to be downloaded

### Actual behavior

The "java.io.IOException: Failed to bypass Cloud flare" error appears

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Would help if you put the full error message, just the IOException part doesn't help much to describe the issue.

**Comment by Killer31g** [comment]
> 

I updated the information

**Comment by alessandrojean** [comment]
Closed automatically as there isn't much to be done about the Cloudflare thing. Follow the troubleshooting guide linked at the acknowledgements section, if it doesn't work, migrate to other sources.
