### ISSUE TITLE
The app is great, but please allow users to display two pages of content on one screen and provide an option "first page is the cover".

### ISSUE THREAD

**Issue by ManakaSajou** [tachiyomiorg/tachiyomi-extensions#16771]
### Describe why this should be added

The app is great, but please allow users to display two pages of content on one screen and provide an option "first page is the cover". This option is quite effective when facing Japanese manga and some tablet devices. The specific scenario is that a tablet device can decide whether to turn on the option of "**displaying two pages on the same screen**" according to its own needs and screen size. And decide whether the first page is a cover page, **if it is a cover page, the first page will be displayed separately, and the second page will start in the mode of displaying two pages on one screen**. This is a huge boost for the user's experience, and for some devices with odd resolutions, an excellent reading experience is also possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
