### ISSUE TITLE
No Results Found for Mangagreat extension

### ISSUE THREAD

**Issue by Chandanjk** [tachiyomiorg/tachiyomi-extensions#16785]
### Source information

MangaGreat 1.4.32

### Source language

English

### Steps to reproduce

Open Mangagreat Source

It is working fine in webview

### Expected behavior

It should show results

### Actual behavior

No results found

### Tachiyomi version

0.14.6

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Wonka006** [comment]
Having the same issue with this extension.

**Comment by Chandanjk** [comment]
Any update on this?

**Comment by tyme2tb** [comment]
Same issue, also any existing manga I hav fails. Although if I hit webview for an existing manga it loads fine.

**Comment by perara-chen** [comment]
I am also having the same issue.

**Comment by conztanz045** [comment]
Please fix this
