### ISSUE TITLE
Reaper scans no pages found

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#16794]
### Source information

Reaper scans 1.4.43

### Source language

English

### Steps to reproduce

Open extension
Open manga
Try to read a chapter
"No pages found"

### Expected behavior

Able to read chapter 

### Actual behavior

"No pages found"

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.A725FXXS5DWD2
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Turhvjbufv** [comment]
#16756

**Comment by AwesomeQuest** [comment]
Resolved with update 1.4.45
