### ISSUE TITLE
WorldManhwas change URL

### ISSUE THREAD

**Issue by Jeankirs** [tachiyomiorg/tachiyomi-extensions#16793]
### Source information

WorldManhwas 1.4.30

### Source language

Indonesian

### Source new URL

WorldManhwas.bar

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Start38** [comment]
https://worldmanhwas.bar/

**Comment by Start38** [comment]
@OdisBy

**Comment by kitsu2** [comment]
![Uploading Screenshot_20230625_110200.jpg…]()
