### ISSUE TITLE
Reaper Scans not able to read chapters

### ISSUE THREAD

**Issue by HNEnd** [tachiyomiorg/tachiyomi-extensions#16806]
### Source information

Reaper Scans 1.4.44

### Source language

English

### Steps to reproduce

Try to open a any chapter with reaperscans as the source.

### Expected behavior

You're able to read the chapter.

### Actual behavior

When opening a chapter it closes and a error pops up

![Screenshot_2023-06-21-03-10-46-073_eu kanade tachiyomi debug](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/74346601/81f683ff-761e-4e2a-87a0-60a382218be7)

### Tachiyomi version

Preview App version: 0.14.6-5845 

### Android version

Android version: 13 (SDK 33) 

### Other details

 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/11811297/tachiyomi_crash_logs.txt)

You are able to browse the source but not read it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16804 and #16805
