### ISSUE TITLE
Reaper Scans Expected '{' But Had 'EOF' Instead

### ISSUE THREAD

**Issue by Aragolt** [tachiyomiorg/tachiyomi-extensions#16804]
### Source information

Reaper Scans 1.4.44

### Source language

English

### Steps to reproduce

1. Select a title
2. Open a chapter
3. Wait for error message to appear

### Expected behavior

The first page of the chapter should begin loading.

### Actual behavior

Returns to the chapter page with the error message:

Expected start of the object '{', but had 'EOF' instead at path: $ JSON input: .....si":100}' crossorigin="anonymous"></script>
</body>
</html>

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

![Screenshot_20230620-180217_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97773467/c0c9d9f2-2152-477e-85a3-b513d2db120c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pa3ckP7** [comment]
Apparently, reaperscans has upgraded its protection again, we now have a bot check on chapter load (normally you'd encounter such protection on site load not chapter load). Another thing to note is that the bug does not happen on all manga some are exempt (e.g. return of the frozen player, legendary spear knight), but those still exhibit the same protection on chapter load, but not the bug

**Comment by Aragolt** [comment]
@Pa3ckP7
I've tested the manga you listed as exempt from this issue (return of the frozen player and legendary spear knight) under the same conditions listed above and found this error occurring on both of them.
![Screenshot_20230620-190149_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97773467/8668076a-d113-4813-8923-6de0d30b19af)
![Screenshot_20230620-190125_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97773467/ade73515-2ff4-4383-9f02-5aaec04bd82f)

**Comment by Pa3ckP7** [comment]
Might be a cache thing as i was able to read chapter 87 of frozen player and 98 of spear knight, but not 377 of demonic emperor.

**Comment by Pa3ckP7** [comment]
This needs to be re opened. The supposed patch sure did fix the EOF thing, but not the bug as a whole as now we get the following
`Unexpected JSON token at offset 19: Expected string literal but 'null' literal was found at path: $.effects.html Use coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.
JSON input: {"effects":{"html":null,"dirty":["first"]},"serve...........`

**Comment by Turhvjbufv** [comment]
Opened a new issue for that
