### ISSUE TITLE
Using ".org/home" in ToonGod Url

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi-extensions#16803]
### Source information

ToonGod 1.4.33

### Source language

English

### Source new URL

https://www.toongod.org/home/

### Other details

Using the ". org/home" at end of url instead of ".com" reduces the failure to load due to cloudflare in many devices.
if only ".com" is used in url, after 7 to 10 uses the IP is blocked and site cannot be access any longer even after using vpns. But "Toongod.org/home" still works
I have tested this using chrome in 5 of my phones.
3 using tachiyomi, 2 using tachiyomi SY

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Duplicate of #15980
