### ISSUE TITLE
Reaper Scans (English): No pages found

### ISSUE THREAD

**Issue by Kenn876** [tachiyomiorg/tachiyomi-extensions#16807]
### Source information

Reaper Scans 1.4.44

### Source language

English

### Steps to reproduce

Download reaperscans extension and open the source, choose any manhwa and open any chapter, will show no pages. And you can't download the pages.

### Expected behavior

Shows manhwa pages and allows for download of pages

### Actual behavior

When trying to read or download a chapter of a manhwa on the app it doesn't load it.

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

It keeps saying this:

Expected start of the object '{', but had 
'EOF' instead at path: $
JSON input: .....si":100}'
crossorigin="anonymous"></script>
</body>
</html>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> Reaper Scans 1.4.44


https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16804 and #16805
