### ISSUE TITLE
Manhwaplus

### ISSUE THREAD

**Issue by Jeankirs** [tachiyomiorg/tachiyomi-extensions#16813]
### Source name

Manhwaplus

### Source link

https://manhwaplus.pro/

### Source language

Indonesia

### Other details

18+/NSFW = YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site looks dead, closing

> Welcome to nginx!
> 
> If you see this page, the nginx web server is successfully installed and working. Further configuration is required.
> 
> For online documentation and support please refer to [nginx.org](http://nginx.org/).
> Commercial support is available at [nginx.com](http://nginx.com/).
> 
> Thank you for using nginx.
