### ISSUE TITLE
Readcomiconline being weird

### ISSUE THREAD

**Issue by fo544** [tachiyomiorg/tachiyomi-extensions#16821]
### Source information

 Readcomiconline

### Source language

English

### Steps to reproduce

I tried to read an issue of a comic from this extension and I was hit with a "Unable to parse rgaurd script"

### Expected behavior

It would usually work

### Actual behavior

![Screenshot_20230622_010433_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/137374452/e7cd5033-c63e-4606-bd95-454e6fc9fbf6)

### Tachiyomi version

0.14.6

### Android version

A22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Closing in favor of #16822 to avoid multiple issues

**Comment by Mrxbelly** [comment]
I'm also receiving the same error when trying to read from read comics online

**Comment by ZetaEsper** [comment]
yup same here went to go read more Flash and it just hit me with this shit
