### ISSUE TITLE
VCPVMP thumbnails issue

### ISSUE THREAD

**Issue by UniverseCodex01** [tachiyomiorg/tachiyomi-extensions#16826]
### Source information

1.4.9

### Source language

Spanish and English

### Steps to reproduce

Go to VCP extension and serach for old uploads, some of the comics has broken thumbnails or replaced thumbnail with Will Smith face, on web view mode, thumbnails are normal. With the newest update of extension Will Smith face was removed from comics pages but still on thumbnails.

### Expected behavior

See original comics thumbnails that can be visible on web view mode.

### Actual behavior

Some thumbnails are broken or are replaced with Will Smith face.

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

![Screenshot_2023-06-22-11-38-07-629_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/93066706/1eb3c8aa-58eb-4b5b-8100-73b84d766b43)
![Screenshot_2023-06-22-11-37-59-255_eu kanade tachiyomi~2](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/93066706/38b6d26d-4c45-4763-9a4b-a797305042d8)
![Screenshot_2023-06-22-11-38-48-117_eu kanade tachiyomi~2](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/93066706/c84c1d80-8c6a-4d53-a27b-ee3e99b5f8a9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Try clearing the database in advanced settings of the app, if it doesn't work clear the app cache (DON'T CLEAR THE DATA)

**Comment by UniverseCodex01** [comment]
Partially worked, now broken thumbnails are fixed but Will Smith thumbnail still present in some comics. Thanks for the idea:)

**Comment by bapeey** [comment]
Did you clear app cache? The cover that appears in the photo loads correctly for me

**Comment by UniverseCodex01** [comment]
> Did you clear app cache? The cover that appears in the photo loads correctly for me

You have reason, the problem was that I was cleaning cache from the app and not directly on app info section, now I cleared cache directly and problems are fixed, thanks so much for the idea :)

**Comment by UniverseCodex01** [comment]
Problem already fixed on last extension update, go to Tachiyomi app info and clear app cache.
