### ISSUE TITLE
ReadComicOnline: Unable to parse Rguard script

### ISSUE THREAD

**Issue by Beyparm** [tachiyomiorg/tachiyomi-extensions#16822]
### Source information

ReadComicOnline 1.4.14

### Source language

English

### Steps to reproduce

1. Try to open any comic on readcomiconline
2. Get asked to solve captcha in webview
3. Solve captcha
4. New message of "Unable to Parse Rguard script"

### Expected behavior

Comic opens and I can continue reading Ultimate Spider-Man like the basic bitch I am

### Actual behavior

Comic does not open and I can't enjoy my daily dose of MJ & Peter melodrama

### Tachiyomi version

0.14.6

### Android version

Galaxy S22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Bjy23-blu** [comment]
I'm about to read transformers im so hyped but sheesh

**Comment by Bjy23-blu** [comment]
I'm about to read transformers im so hyped but sheesh

**Comment by El-Didico** [comment]
I have the exact same phone, I was trying to read the exact same Comic and I'm having the exact same problem 😭😭😭
![Screenshot_20230622_191517_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/137433576/3549a1aa-da7d-4339-924b-1c0c8b46eada)

**Comment by Ehssank** [comment]
Same problem here. Although i am able to continue reading the issue i started on before this error message showed up. I hope it doesn't take as long as last time the extension was broken to resolve. That was a rough couple of months. Gambare!
