### ISSUE TITLE
Changing a extension url to a new, correct and available one

### ISSUE THREAD

**Issue by JacobGGG** [tachiyomiorg/tachiyomi-extensions#16830]
### Source information

ToonGod 1.4.33

### Source language

English

### Source new URL

https://www.toongod.org/home/

### Other details

Current url "toongod.org" can't be used. This is a solution and please pay attention and add the solution to the extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by JacobGGG** [comment]
This is not a duplicate issue but a solution

**Comment by curche** [comment]
> Please do not let the bot close this as this is a available solution

And that is exactly what was reported in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15980#issuecomment-1510428130 as well
Ergo this is a duplicate to an extension problem with a possible solution already suggested albeit no action taken yet
