### ISSUE TITLE
Domain changed

### ISSUE THREAD

**Issue by Aplukat** [tachiyomiorg/tachiyomi-extensions#16834]
### Source information

KumaPoi 1.4.25

### Source language

Indonesia 

### Source new URL

https://kumapoi.club/

### Other details

please fix this it has been more than a week of this problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate of #16825. Don't close old issues to bump duplicate new ones.
