### ISSUE TITLE
Error de Extensión 

### ISSUE THREAD

**Issue by Inquisidor117** [tachiyomiorg/tachiyomi-extensions#16848]
### Source information

Manhwas.net

### Source language

Español 

### Steps to reproduce

Al abrir la WebView desde la app y resolver el capcha de cloufired,al terminar de verificarlo me sale error 

### Expected behavior

Algunas veces me pasaba lo mismo y solo abría la WebView desde la app, cargaba y la extensión ya funcionaba.

### Actual behavior

![Screenshot_2023-06-23-23-21-15-23_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/136776694/80358e6d-1281-4880-aff5-540b1b68189e)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the [Cloudflare Troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues) guide linked in the acknowledgements section. If it doesn't work, migrate to other extensions or wait until they lower their protection.
