### ISSUE TITLE
Cubari Query format error

### ISSUE THREAD

**Issue by ToxicDragon** [tachiyomiorg/tachiyomi-extensions#16857]
### Source information

1.4.19

### Source language

English

### Steps to reproduce

1. Search for manga
2. Check list, navigate to cubari

### Expected behavior

Mangas from Cubari are found and shown

### Actual behavior

3. The error message "Unable to parse. Is your query in the format of cubari:<source>/<slug>?" is shown

![Screenshot_20230625-114311](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/3375142/1b6c63ba-4679-430b-9251-775b27aec18d)

![Screenshot_20230625-113814](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/3375142/6a4a60b8-cdea-4525-a173-9cf9c4f15ca8)

### Tachiyomi version

0.14.6

### Android version

Android 14 beta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/cubari/README.md
