### ISSUE TITLE
Manga Fenix

### ISSUE THREAD

**Issue by Unknoweird** [tachiyomiorg/tachiyomi-extensions#16869]
### Source information

Manga Fenix 1.4.31

### Source language

Español

### Steps to reproduce

1. Entro a la extensión
2.  Aparece error relacionado con el java

### Expected behavior

![Screenshot_20230625-165428](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/101126322/9086f43b-e50b-4219-a12c-bbbd66c546d6)

### Actual behavior

![Screenshot_20230625-163341](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/101126322/57e44bad-1b3e-4fca-b6ea-b88a2959c968)

### Tachiyomi version

TachiJ2K 1.6.6

### Android version

Android 10.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please follow the Cloudflare troubleshooting section linked in the acknowledgements section you checked. If it doesn't work, migrate.

https://tachiyomi.org/help/guides/troubleshooting/
