### ISSUE TITLE
Readallcomics.com

### ISSUE THREAD

**Issue by Ehssank** [tachiyomiorg/tachiyomi-extensions#16860]
### Source name

ReadAllComics.com

### Source link

https://readallcomics.com/

### Source language

English

### Other details

Seems like a good replacement for "The extension that shall not be named". Jokes aside, we could use some more options for sources focusing on Western comics. The last time the main extension went down, it became quite apparent that The existing options was not really cutting it.

Thank you for all your Hard work. We appreciate you! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by thestrangevisitor** [comment]
Yes. It would be great if western comics readers get more sources to read. ComicExtra, Comicastle, XOXO Comics are good but not as reliable as ReadComicOnline. So kindly add readallcomics to your vast array of extensions so western comics enjoyer can enjoy comics. Thanks for all your hard work.
