### ISSUE TITLE
[JapScan] Get Error during download : "Attendait 2 chaînes de recherche dans ZJS, a trouvé 0"

### ISSUE THREAD

**Issue by MrSpoot** [tachiyomiorg/tachiyomi-extensions#16898]
### Source information

JapScan 1.4.40

### Source language

French

### Steps to reproduce

Step to reproduce : 
1. Get scan from Japscan source (I my case is Mushoku Tensei)
2. Try to read chapter
3. An error appear after some seconds, and close the player

### Expected behavior

When i want to read chapter, the player should open and display chapter, without error

### Actual behavior

When I open a chapter, the player opens then after a few seconds it closes with an error

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ronycohen** [comment]
hi, I got the same issue.
