### ISSUE TITLE
Adopt kotatsu's clod fare resolver method

### ISSUE THREAD

**Issue by breaking-loss** [tachiyomiorg/tachiyomi-extensions#16896]
### Describe why this should be added

I do not know any coding but i have observed that while tachiyomi-extensions suffer from " unable to solve captcha " from time to time the kotatsu's inbuilt sources doesn't have this problem .

For example n-hentai in kotatsu is working now but the n-hentai in tachiyomi-extensions is not working . The webviev is not able to solve the captcha . 

Please forgive me if this suggestion is dumb . I don't have any experience in coding . 

### Other details

The source for kotatsu :
https://github.com/KotatsuApp/Kotatsu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

Also don't try to bypass the repository issue filters by censoring words such as the Cloudflare name.
