### ISSUE TITLE
N-Hentai not working

### ISSUE THREAD

**Issue by breaking-loss** [tachiyomiorg/tachiyomi-extensions#16891]
### Source information

N-hentai 1.4.37

### Source language

English

### Steps to reproduce

1. Use a vpn
1. Open the nhentai source 
2. Go to webview
3. Solve the clod fare ( add a u and l ) captcha as instructed in https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
4. Click I am human box

### Expected behavior

The captcha should return success and redirect to main site

### Actual behavior

After the captcha ,failure is shown even after retrying 4-5 times .

### Tachiyomi version

r5863

### Android version

Android 13

### Other details

Others have already raised the issue but got removed due to github actions . because of clod fare ( add u and l ) . please remove the criteria

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
From the link you posted:
> You can try the following suggestions to help resolve Cloudflare challenges. **If they don't work, migrate to other sources or wait until they lower their protection.**

**Comment by breaking-loss** [comment]
> From the link you posted:
> 
> > You can try the following suggestions to help resolve Cloudflare challenges. **If they don't work, migrate to other sources or wait until they lower their protection.**

Isn't this a problem with tachiyomi-extension itself . Accessing through browser works well . I am pretty sure it always gets fixed after an update to the source .

**Comment by Mtkmanjaro** [comment]
yes works well in browser no problem with cloudflare, but in the extension you get stuck in a loop when trying to pass cloudflare check

**Comment by mrbrinclhoff** [comment]
So I've been trying all the troubleshooting steps for the cloudflare protection to no avail but found what finally worked for me. 
Settings > Advanced > Network 
DNS over HTTPS - Set to cloudflare. 
That finally fixed it for me. Try it out and let me know if that fixes it for you as well. If so, might be something someone can include in the troubleshooting steps.

**Comment by Mtkmanjaro** [comment]
> So I've been trying all the troubleshooting steps for the cloudflare protection to no avail but found what finally worked for me. 
> Settings > Advanced > Network 
> DNS over HTTPS - Set to cloudflare. 
> That finally fixed it for me. Try it out and let me know if that fixes it for you as well. If so, might be something someone can include in the troubleshooting steps. 

nah I'm literally using cloudflare DNS on my whole device from network settings, the problem is whiting the extension, you get stuck in a loop trying to pass cloudflare check, in normal web browser there's not such problem you can pass cloudflare check in seconds.

**Comment by mrbrinclhoff** [comment]
Can at least give it a try to see if it does anything.

**Comment by kyuubi08** [comment]
I have also attempted this, tried all the suggested fixes, including the above suggestion, and an still getting the error

**Comment by alessandrojean** [comment]
Make sure to follow the changing the user agent section in the troubleshooting guide as well. If it doesn't work, migrate or wait until they lower their protection.

Locking the issue as support related messages should go through or [Discord server](https://discord.gg/tachiyomi).
