### ISSUE TITLE
Showing cloudfare issues and trouble shooting ain't working 

### ISSUE THREAD

**Issue by Eco128** [tachiyomiorg/tachiyomi-extensions#16890]
### Source information

Nhentai , Manhwa raw, Aqua manga, Az manhwa, Best manhua, Doujins

### Source language

English 

### Steps to reproduce

![Screenshot_2023-06-27-17-31-37-865_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/121341283/8f50a9b1-a294-40de-8125-d70b017c398f)
![Screenshot_2023-06-27-17-30-18-265_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/121341283/7e8e98c4-993c-4d39-9cd5-a279de02b35e)

### Expected behavior

Completing the captcha should have fixed it, but there is none

### Actual behavior

Failed to bypass cloudfare 

### Tachiyomi version

App version: 1.9.3 (standard, 18d3615, 50, 2023-04-18T21:33Z) Preview build: 0 Android version: 12 (SDK 31) Android build ID: SKQ1.211019.001 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by breaking-loss** [comment]
Try not to include cloudfare in your issue it gets auto removed by github bot . use coud fare ( with u and l as the 2nd word) instead I your future issues .
