### ISSUE TITLE
Allanime URL change

### ISSUE THREAD

**Issue by jorgeflbrito** [tachiyomiorg/tachiyomi-extensions#16907]
### Source information

Allanime 1.4.4

### Source language

English

### Source new URL

https://allanime.ai/

### Other details

Allanime changed URL and now it doesn't open chapters of added manga and doesn't allow new searches, only allows to open in webview because it redirects to the new url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by jorgeflbrito** [comment]
I've changed the domain from allanime.co to allanime.to and the extension started working again.
I still suggest that the extension is updated to included the new domain

**Comment by AntsyLich** [comment]
Since you've changed it why not make a PR?

**Comment by jorgeflbrito** [comment]
> Since you've changed it why not make a PR?

The extension as an option to choose a domain, only has 2 options. I didn't change the code, only used the option the developer left there to choose a different domain that is still available
