### ISSUE TITLE
Manhuaren extension no value for response 

### ISSUE THREAD

**Issue by Ragebun** [tachiyomiorg/tachiyomi-extensions#16909]
### Source information

manhuaren 1.4.8

### Source language

Chinese

### Steps to reproduce

1. kick in the popular/lastest filter in browse with the source: manhuaren
2. It will show up "No value for response"

### Expected behavior

It should show up a list of manga 

### Actual behavior

It did not show any manga and show the "No value for response" and " JSONException : No value for response" message 

### Tachiyomi version

Stable 0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DasCrystal** [comment]
```
{
  "errorResponse": {
    "code": 40005,
    "subCode": "",
    "message": "签名错误"
  }
}
```

This is what manhuaren response in extension popular's webview.

(The mean of 签名错误 is "Signature error")

And source (https://www.manhuaren.com/search/) is alive.

**Comment by treebearbb** [comment]
Got the same problem here

**Comment by fatalwinter85** [comment]
Same problem. Manhuaren can't be connect in Tachiyomi. But if go to its original website, is normal.

**Comment by ArthurDouble** [comment]
The wrong response of 40005 is from the site http://mangaapi.manhuaren.com/

**Comment by DasCrystal** [comment]
Maybe use website as source directly will be a good approach?

**Comment by sao-coding** [comment]
可能要用爬蟲
除非再一次反編譯他app

**Comment by haozihong** [comment]
The desktop website of Manhuaren (https://www.dm5.com/) might be a better choice. 

The [crawler of Manhuaren in another project](https://github.com/kanasimi/work_crawler/blob/master/comic.cmn-Hans-CN/dm5.js) also uses https://www.dm5.com/.

**Comment by Aizefaroudo** [comment]
I have the same problem.

**Comment by FinalSnow** [comment]
Mamhuaren moved their adress and we need new source to install their new app...

**Comment by leoballl** [comment]
The issues seems to have came back

**Comment by sao-coding** [comment]
Can this issues be reopened?

**Comment by FinalSnow** [comment]
Manhuaren update their app to a new one. The old one can not use lol.

**Comment by john-stones5** [comment]
One point to note, it worked consistently for 9 hours until the bug appeared again. Don't know if it helps.

**Comment by fatalwinter85** [comment]
Just now in tachiyomi got manhuaren update, but after updated the problem still the same.

**Comment by hahahakt** [comment]
Same problem here... 1.4.8 still not working

**Comment by treebearbb** [comment]
1.4.10 not working angin

**Comment by DasCrystal** [comment]
> 1.4.10 not working angin 

It's waiting for merge, don't worry.

**Comment by leoballl** [comment]
> > 1.4.10 not working angin
> 
> It's waiting for merge, don't worry.

May i ask what do you mean by merge, thanks

**Comment by JasonHK** [comment]
> > > 1.4.10 not working angin
> > 
> > It's waiting for merge, don't worry.
> 
> May i ask what do you mean by merge, thanks

@leoballl 

> Merging takes the changes from one branch (in the same repository or from a fork), and applies them into another. This often happens as a "pull request" (which can be thought of as a request to merge), or via the command line. A merge can be done through a pull request via the GitHub.com web interface if there are no conflicting changes, or can always be done via the command line.
> 
> from <https://docs.github.com/en/get-started/quickstart/github-glossary#merge>

**Comment by DasCrystal** [comment]
> > > 1.4.10 not working angin
> > 
> > It's waiting for merge, don't worry.
> 
> May i ask what do you mean by merge, thanks

Basically, there are 2 steps to apply a extension modify officially.
First, someone will issue a Pull Request, which contains the code to apply.

Second, the official will review the code, if it is good to be applied, then the official will "merge" these code into Tachiyomi official extensions.

**Comment by treebearbb** [comment]
It works for 9 hours and now it git the same problem angin
