### ISSUE TITLE
problems in kemono and coomer

### ISSUE THREAD

**Issue by toto1414** [tachiyomiorg/tachiyomi-extensions#16911]
### Source information

kemono and coomer

### Source language

All

### Steps to reproduce

In the coomer source, it does not bring all the content, it suffices to bring only 37 chapters, and in the kemono source, it suffices to bring only 47 chapters. 

### Expected behavior

Should bring more chapters

### Actual behavior

The chapters are below the source site

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's an extension setting to increase the amount of posts to fetch. Make sure you have increased its value if you want more posts to show up.

**Comment by toto1414** [comment]
> 

Thanks solve it
