### ISSUE TITLE
BentoManga cloudflare loop

### ISSUE THREAD

**Issue by VeryOldpApY** [tachiyomiorg/tachiyomi-extensions#16919]
### Source information

BentoManga 1.4.14

### Source language

Français

### Steps to reproduce

Click in the app: 
- Browse 
- Source 
- Bento Manga 
- WebView

In the WebView: 
- Validate cloudflare 
- Wait 
- Validate cloudflare 
- Wait
- Validate cloudflare 
- Wait
- etc...

### Expected behavior

Display site

### Actual behavior

Display cloudflare

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Follow the entire Cloudflare Troubleshooting guide available at the acknowledgements section you checked. If it doesn't work, migrate or wait until they lower their protection.
