### ISSUE TITLE
KomikindoID no pages found

### ISSUE THREAD

**Issue by CanULetMeIn** [tachiyomiorg/tachiyomi-extensions#16921]
### Source information

KomikIndoID 1.4.10

### Source language

Indonesia

### Steps to reproduce

1. Open any comic
2. Select chapter
3. Its says "no pages found"

### Expected behavior

The comic should be appears and you can read the comic

### Actual behavior

Its says "no pages found"

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FakeModz** [comment]
BacaKomik also
