### ISSUE TITLE
NHentai Failed to Bypass Cloudfair

### ISSUE THREAD

**Issue by Degenerate6975** [tachiyomiorg/tachiyomi-extensions#16935]
### Source information

NHentai 1.4.37

### Source language

English

### Steps to reproduce

1. Utilize any NHentai function
2. Receive message stating failed to bypass cloudfair

### Expected behavior

Should be able to utilize the extension as intended 

### Actual behavior

Fails to bypass cloudfair 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

in particular the cloudflare part.

**Comment by AaronDragneel** [comment]
Yeah getting the same problem.
