### ISSUE TITLE
Ozul scans 

### ISSUE THREAD

**Issue by YYSS15** [tachiyomiorg/tachiyomi-extensions#16931]
### Source information

Ozul scans 

### Source language

Arabic 

### Steps to reproduce

Failed to bypass cloud fire 

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by YYSS15** [comment]
![Screenshot_20230629-221628](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132961602/ada444a5-47bb-412c-84ed-b93987fe10fb)

**Comment by alessandrojean** [comment]
Please do follow the entire Cloudflare section in the troubleshooting guide linked in the acknowledgements section you checked. If it doesn't work, migrate to other sources or wait until they lower their protection.
