### ISSUE TITLE
Webtoontr cloudflare sorunu

### ISSUE THREAD

**Issue by yaoihentanime** [tachiyomiorg/tachiyomi-extensions#16932]
### Source name

Webtoontr 1.4.30

### Source language

Türkçe 

### Source link

https://webtoon-tr.com/

### Other details

![Screenshot_20230629-230023_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/136040662/3de8aae1-b3b5-42cd-9845-d60aa19f1e74)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
