### ISSUE TITLE
Golden Mangás: Manga details parsing is broken

### ISSUE THREAD

**Issue by GTV33** [tachiyomiorg/tachiyomi-extensions#16946]
### Source information

Golden Mangás 

### Source language

Portuguese

### Steps to reproduce

![Screenshot_2023-06-30-21-53-37-955_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/102895449/007e824c-61c5-4391-864b-5d53e3766fb4)

this applies to all mangas added to the app by the Golden Mangás extension

### Expected behavior

Normally the application looks for updates and installs them automatically without any problems.

### Actual behavior

whenever you put it to an automatic update, the chapters do not update and are disconnected from the site

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

this problem started four days ago

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The parsing is working fine. What happens is that from time to time the site owners change the manga URLs, which lead to outdated entries in your library. Migrate from Golden to Golden to update the URLs from items in your library.
