### ISSUE TITLE
Mangafreak's Cloudflare issue

### ISSUE THREAD

**Issue by MikaelaMuller** [tachiyomiorg/tachiyomi-extensions#16958]
### Source information

Mangafreak 1.4.9

### Source language

English

### Steps to reproduce

Install Extension
Then open the extension

### Expected behavior

List of every manga available on the website

### Actual behavior

Stuck on cloudflare
![Screenshot_20230702-013341_Aniyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/91151184/bc15e7a0-3118-47a4-87de-359167d399a0)

Even after following the Cloudflare guide the issue remains. Changing user agent, clearing webview and cookie data, nothing works.

### Tachiyomi version

App version: 0.14.6

### Android version

Android version: 12 (SDK 32) Android build ID: SQ3A.220705.004 Device brand: samsung Device manufacturer: samsung Device name: a02q Device model: Samsung Galaxy A02S Device product name: a02qnaxx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Wait until they lower their protection or migrate to other sources.
