### ISSUE TITLE
Japscan: Error "Les deux tentatives de désembrouillage ont échouées" when reading

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#16957]
### Source information

Japscan 1.4.41

### Source language

French

### Steps to reproduce

1.Select a manga from source
![Screenshot_20230701-160911](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/9e793437-2f70-4078-a889-2aa8029d4f3f)

2. Open a chapter
3. Reader is nigh immediately closed and the message error "Les deux tentatives de désembrouillage ont échouées" shows up, translating to "The two descrambling attempts failed"
![Screenshot_20230701-161014](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/9baac0ef-d8d7-4bef-be91-24ca3414213a)

### Expected behavior

Open the chapter and read

### Actual behavior

Reader is nigh immediately closed and the message error "Les deux tentatives de désembrouillage ont échouées" pops up, translating to "The two descrambling attempts failed"

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

Same error shows up when downloading
The chapters are readable in the WebView 
![Screenshot_20230701-161049](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/01bfb3dd-71c7-44e1-b7cc-1e8da5a2ffde)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kreliam** [comment]
Same in my side

**Comment by DaMakoumba** [comment]
Same bug here 🙁
