### ISSUE TITLE
Nhentai not working 

### ISSUE THREAD

**Issue by Kuuhakuxx** [tachiyomiorg/tachiyomi-extensions#16962]
### Source information

Nhentai version 1.4.37

### Source language

Multi 

### Steps to reproduce

Tried Uninstaller nhentai and downloading it again not working. But verifying keeps on failing so can't access nhentai in tachiyomi.

### Expected behavior

..

### Actual behavior

![Screenshot_20230702_115225_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/122075694/58823c3e-46a5-4af3-8c43-4e8591648dfb)

### Tachiyomi version

0.14.6

### Android version

Android version 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.

**Comment by PrivatePP** [comment]
@vetleledaal Is it a problem of outdated user agent in the extension? #13130

**Comment by vetleledaal** [comment]
@PrivatePP the user-agent was removed from the extension in #15727, so it is up to the app to provide it. In this case updating the user-agent works, see the previously linked guide if you are unsure on how to do that.
