### ISSUE TITLE
bug CloudFlare 

### ISSUE THREAD

**Issue by Ardo25** [tachiyomiorg/tachiyomi-extensions#16963]
### Source information

KomikIndoID (Indonesia) 1.4.11

### Source language

indonesia

### Steps to reproduce

first open the komik indo 
second open in webview 
three verif it but i can't verification, always verification failed, if in another browser it was can 

![Screenshot_20230702_104146](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/125936428/2f3ea9d0-76d9-4041-89e6-81e2f5da220b)
^
This was from a chrome (another Browser)

![Screenshot_20230702_104730](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/125936428/6455c60f-2d4e-4075-889d-0362da7a3369)
^
and this was from tachiyomi 

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/125936428/32ace94c-45be-45ea-9032-2c7876c2826a
^
this was video if need some details 

### Expected behavior

idk what this make happen but i think was is the problem from tachiyomi...

### Actual behavior

i'm Sure this Problem is From Tachiyomi

### Tachiyomi version

0.14.6

### Android version

Funtouch OS ; PD1911F_EX_A_7.5.6

### Other details

always loop in the webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
