### ISSUE TITLE
Toonkor cloudflare verification failure, even in webview

### ISSUE THREAD

**Issue by rubicon31** [tachiyomiorg/tachiyomi-extensions#16972]
### Source information

Toonkor 1.4.4

### Source language

korean

### Steps to reproduce

cloudflare verification fails for toonkor, even in webview through the app

### Expected behavior

cloudfare verification should succeed

### Actual behavior

cloudflare verification fails

### Tachiyomi version

0.14.6

### Android version

android 11

### Other details

tested on different devices, while it works in a normal browser it fails on tachiyomi, even in webview. already tried changing dns and user agent with no results. domain has already been overwritten at time of posting to the latest one: toonkor226

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The troubleshooting guide states in bold that if none of the instructions works, only thing you can do is migrate to other sources or wait until the source lowers their protection.
