### ISSUE TITLE
Bato.to can't load

### ISSUE THREAD

**Issue by happiisyaro** [tachiyomiorg/tachiyomi-extensions#16975]
### Source information

Bato.to 1.4.31

### Source language

All language

### Steps to reproduce

1. Can't load when first open it
2. Failed to connect
3. Java.net socket timeout
4. Web view didn't work either

### Expected behavior

Open normally and you see the cover of manga list

### Actual behavior

Can't load to the page and java.net pop out. I'd been try it many time and still same. Web view also just loading with no result.

### Tachiyomi version

0.14.6

### Android version

Android 9

### Other details

Usually you open and all the mangas pop out. This time, only Java.net time out and i try many time it still remain the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
loads fine for me, maybe you're being blocked or you need to do cloudflare. you can try doh/vpn or maybe a different mirror.
