### ISSUE TITLE
Mangadex crushes tachiyomi 

### ISSUE THREAD

**Issue by hatem07** [tachiyomiorg/tachiyomi-extensions#16991]
### Source information

Mangadex 1.4.182

### Source language

English

### Steps to reproduce

After installing the plugin mangadex when i try to open the source tachiyomi crushes . 

### Expected behavior

The source should open and show manga list 

### Actual behavior

App crushes

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
already fixed, update to the latest when it is out
