### ISSUE TITLE
Webtoons.com not searching other languages

### ISSUE THREAD

**Issue by jurquizo-dev** [tachiyomiorg/tachiyomi-extensions#17002]
### Source information

Webtoons.com 1.4.39

### Source language

"Español"

### Steps to reproduce

1. Extensions->Webtoons.com->settings.
2. Enable Español.
3. Go to search on Webtoons.com.
4. Look for webtoon "Cartas en la pared".

### Expected behavior

It should show the official spanish version of the webtoon with the info from [here](https://www.webtoons.com/es/romance/cartas-en-la-pared/list?title_no=3288).

### Actual behavior

It says there is no match and shows me other webtoons only from the english version.

### Tachiyomi version

0.14.6

### Android version

Android 10 MIUI 12.0.17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Use the extension found under the Spanish section. You are probably using the English version.

**Comment by alessandrojean** [comment]
Managed to find just fine under the _Español_ section in the app. Do what bapeey said and double check if you're searching under the right source.
