### ISSUE TITLE
Invalid completion title on Omniscient reader's viewpoint 

### ISSUE THREAD

**Issue by StephenWachira-glitch** [tachiyomiorg/tachiyomi-extensions#17001]
### Source information

Manga reader

### Source language

English 

### Steps to reproduce

Open Source Manga reader
Click on Omniscient reader's viewpoint
Label shows completed yet it is ongoing

### Expected behavior

Expected to see ongoing manga

### Actual behavior

Shows completed series 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
thats what the website shows it as, blame them.
