### ISSUE TITLE
Manhuaren 1.4.9 is still broken

### ISSUE THREAD

**Issue by Iplayolg** [tachiyomiorg/tachiyomi-extensions#17008]
### Source information

Manhuaren 1.4.9

### Source language

Chinese

### Steps to reproduce

Tap Browse > Sources > Manhuaren

### Expected behavior

Manga list should shows up

### Actual behavior

No value for response

### Tachiyomi version

0.14.6

### Android version

Android 12L

### Other details

Open in WebView:
{
  "errorResponse":  {
      "code": 40005,
      "subCode": "",
      "message": "簽名錯誤" //means signature error
  }
}

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by john-stones5** [comment]
One point to note, it worked consistently for 9 hours until the bug appeared again. Don't know if it helps.

**Comment by Iplayolg** [comment]
sorry I should reply in other closed thread..
