### ISSUE TITLE
New Source Website

### ISSUE THREAD

**Issue by LtMost** [tachiyomiorg/tachiyomi-extensions#17016]
### Source name

yiffer.xyz

### Source language

English

### Describe your suggested feature

Website can be found at [yiffer.xyz](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/yiffer.xyz)
Other Details

Good hub for a lot of furry porn comics.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Use the `Source request` template instead of the `Feature request` template
