### ISSUE TITLE
Yugenmangas changed url

### ISSUE THREAD

**Issue by elizabbetta** [tachiyomiorg/tachiyomi-extensions#17014]
### Source information

Yugenmangas

### Source las
Spanish 
### Source new URL

Yugenmangas.net

### Other details

The page "https://yugenmangas.com" changed its url to "yugenmangas.net" So I request the change of url to the extension 

![Screenshot_20230704-082654](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112213932/e24b51a4-3441-4bc3-a36b-80771ecffa30)

![Screenshot_20230704-082648](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112213932/1610ab73-7e79-40cc-b5cf-2e6ce12baf95)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by elizabbetta** [comment]
I add capture of the new url

![Screenshot_20230704-085044](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112213932/bb21f5c5-8175-474e-a5db-27c40d93af0c)

**Comment by alessandrojean** [comment]
> I have updated all installed extensions.

The extension is already using this new URL.

**Comment by elizabbetta** [comment]
> > He actualizado todas las extensiones instaladas.
> 
> La extensión ya está usando esta nueva URL.
Si, ya actualice la extensión pero sigue sin funcionar 
![Screenshot_20230704-090730](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112213932/cb52ae4a-8ffd-4afd-a8a3-0967f2567a1a)

**Comment by alessandrojean** [comment]
That's an error the website needs to fix.

**Comment by danielblafer** [comment]
> That's an error the website needs to fix.

It is a problem with the ssl certificate, although it is a problem of the site, other tools such as "Free Manga Downloader" bypass these problems.....

so...wouldn't it be good to rethink the code for this kind of cases; in which the ssl certificate fails but the web is operative?

**Comment by alessandrojean** [comment]
It isn't a good and secure approach to blindly accept wrong/bad certificates and neither use HTTP, so no.
