### ISSUE TITLE
extension hide

### ISSUE THREAD

**Issue by YahyeDeero** [tachiyomiorg/tachiyomi-extensions#17028]
### Source name

All

### Source language

English 

### Describe your suggested feature

I would like to hide any extension in tachiyomi whether they are in *sources* or *extensions*

### Other details

Maybe add a hidden room in browser to hide your *source* or *extension*

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
