### ISSUE TITLE
Izakaya: Bad URLs while downloading chapters

### ISSUE THREAD

**Issue by godestroyer666** [tachiyomiorg/tachiyomi-extensions#17021]
### Source information

Izakaya 1.4.30

### Source language

Portuguese

### Steps to reproduce

1. I can't download the chapters
2. the error sign keeps appearing

### Expected behavior

I can download the chapters

### Actual behavior

I can't download the chapters

### Tachiyomi version

1.6.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as reported to be working again by the opener in Discord.
