### ISSUE TITLE
Mangas-Origines.fr (Unnoficial)

### ISSUE THREAD

**Issue by Kreliam** [tachiyomiorg/tachiyomi-extensions#17031]
### Source information

Mangas Origines v1.4.33

### Source language

French

### Source new URL

https://mangas-origines.fr/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Same issue as Sushi Scan : Both domains exist (.xyz and .fr)
But .fr doesn't suffer from the same issues as .xyz (Cloudflare domain)
Shouldn't be a bug issue but a request of the new domain

**Comment by Kreliam** [comment]
> Same issue as Sushi Scan : Both domains exist (.xyz and .fr)
> 
> But .fr doesn't suffer from the same issues as .xyz (Cloudflare domain)
> 
> Shouldn't be a bug issue but a request of the new domain/source
> 
> 

Le .xyz n'est rien plus qu'un clone du site original avant sont hack

**Comment by KirinRaikage** [comment]
Oui mais là. xyz contient beaucoup plus d'œuvres et est beaucoup plus régulièrement mis à jour que l'autre donc si on considère que c'est un bug c'est une régression de l'extension (même si elle ne remarche que depuis peu)

**Comment by Kreliam** [comment]
> Oui mais là. xyz contient beaucoup plus d'œuvres et est beaucoup plus régulièrement mis à jour que l'autre donc si on considère que c'est un bug c'est une régression de l'extension (même si elle ne remarche que depuis peu) 

Tant que personne ce plaint c'est l'essentiel 🤣🤣

**Comment by KirinRaikage** [comment]
Can someone re-categorize this request please?

**Comment by Kreliam** [comment]
> Can someone re-categorize this request please? 

@alessandrojean

**Comment by Gildrox** [comment]
Hi
the site (.xyz) is a hack site of the original (.fr) which was under maintenance until now, (.xyz) is more provided but the fact remains that it can be more dangerous than the original if my opinion matters to you I support the desire to change the domain to .fr

**Comment by Mitia99** [comment]
> Oui mais là. xyz contient beaucoup plus d'œuvres et est beaucoup plus régulièrement mis à jour que l'autre donc si on considère que c'est un bug c'est une régression de l'extension (même si elle ne remarche que depuis peu) 

Beaucoup d'œuvres jsp mais là je suis en train de chercher "The Beginning After The End" et je me rend compte qu'il n'est plus dispo sur .xyz (dispo sur .fr)
J'espère qu'il y aura une intégration du domaine .fr

**Comment by KirinRaikage** [comment]
Ça me va perso,  vu le nombre de requêtes qui arrivent dernièrement je pense qu'on va ajouter une nouvelle source qui pointe sur .fr
Qu'on appellerait genre MangasOrigines.fr (pour bien le distinguer de l'autre)
