### ISSUE TITLE
Manhuaren 1.4.10 no value for response

### ISSUE THREAD

**Issue by DasCrystal** [tachiyomiorg/tachiyomi-extensions#17033]
### Source information

Manhuaren 1.4.10

### Source language

Chinese

### Steps to reproduce

Browse -> Sources -> 漫画人 Extension 

### Expected behavior

Show a list of manga

### Actual behavior

Shows "no value for response"

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

This time still "signature error".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sao-coding** [comment]
Some manga chapters were blocked in the first few hours
ex:
```json
{
  "response": {
    "mangaName": "关于我转生后成为史莱姆的那件事",
    "mangaCoverimageUrl": "http://mhfm4us.cdndm5.com/19/18071/20180918162019_1080x830_263.jpg",
    "mangaPicimageUrl": "http://mhfm2us.cdndm5.com/19/18071/20180918161959_630x840_199.jpg",
    "mangaId": 18071,
    "mangaAuthor": "川上泰树，伏濑",
    "mangaAuthors": [
      "川上泰树",
      "伏濑"
    ],
    "mangaGrade": "8.0",
    "mangaTheme": "科幻魔幻",
    "mangaHot": 223052574,
    "mangaIntro": "普通上班族三上悟（37，童贞）遇刺身亡。迎接他的，是转生后的异世界史莱姆生活……",
    "mangaIsNewest": 0,
    "mangaIsOver": 0,
    "mangaNewsectionName": "第108话",
    "mangaNewsectionTitle": "试看版",
    "mangaNewestTime": "2023-06-27 15:31:35",
    "mangaIsVulgar": 0,
    "mangaVulgarDescription": "",
    "mangaVulgarTitle": "",
    "mangaVulgarImage": "",
    "mangaSectionType": 2,
    "mangaHideReason": "抱歉,该漫画已经被屏蔽",
    "mangaWords": [],
    "mangaRolls": [],
    "mangaEpisode": [],
    "mangaStyle": 0,
    "mangaDrama": 0,
    "mangaWhoset": 0,
    "mangaConnotation": 0,
    "shareUrl": "https://www.manhuaren.com/manhua-gywzshcwslmnjs/",
    "shareContent": "普通上班族三上悟（37，童贞）遇刺身亡。......",
    "shareIcon": "http://mhfm5us.cdndm5.com/19/18071/20180918161959_180x240_25.jpg",
    "mangaDetailVersion": "d8e5c4e7854dfd6e1b546e2f125f0a89",
    "isShowRelateClub": 0,
    "relateClubId": "",
    "readSectionId": 0,
    "readSectionPage": 0,
    "readSectionApppage": 0,
    "mangaNewsectionId": 1420609,
    "isFrame": 0,
    "isFrameApp": 0,
    "frameAppUrl": "",
    "frameSource": "",
    "frameSourceLogo": "",
    "mangaLabel": [],
    "mangaReads": "2.23亿",
    "isShowFighting": 0,
    "mangaFightingCapacity": "234.63亿",
    "isMustPay": 0,
    "authority": 0,
    "payedList": {},
    "hasUnlockDate": 0,
    "showListType": 0,
    "promotionList": {},
    "isDownloadSelectAll": 0,
    "mangaIsVip": 0,
    "payMangaSections": {},
    "mangaType": 0,
    "mangaLanguage": 0,
    "mangaProperty": 1,
    "uploadUsers": [],
    "uploadUrl": "",
    "readModeType": 0,
    "rewardRank": 0,
    "enableReward": 0
  }
}
```

**Comment by ADeeeee** [comment]
In my case, some of the mangas works now and some doesn't and the error message looks like the same as before: 40005, signiture error.

**Comment by DasCrystal** [comment]
For me, whole Manhuaren are unaccessable on Tachiyomi.

@ADeeeee Are you sure you aren't reading from cache?

**Comment by ADeeeee** [comment]
Ah, you're right. It was partial okay once I updated the plugin to 1.4.10. I did read some mangas directly when I searched the latest updates.

It seems pretty tricky for blocking the API requests of 3rd parties...
