### ISSUE TITLE
Hentaivn changed its domain

### ISSUE THREAD

**Issue by leonminus** [tachiyomiorg/tachiyomi-extensions#17048]
### Source information

HentaiVN 1.4.25

### Source language

Vietnamese

### Source new URL

hentaivn.tv

### Other details

It has another domain:
Hentaivn.autos
M.hentaivn.site
But looks like they have Cloudflare protect
Please try someone don't have Cloudflare

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by minhngoc25a** [comment]
Current site URL returned to normal conditions. Please close issue.
