### ISSUE TITLE
Removal request of Shingeki no Shoujo

### ISSUE THREAD

**Issue by ReLoia** [tachiyomiorg/tachiyomi-extensions#17043]
### Source link

https://shingekinoshoujo.it/

### Other details

Hi! I'm not the actual owner of the website but I created the extension (after approval by the owner). Now, the owner is asking me to remove the extension because it's causing problems to the website.
I DMed a member of the staff of the discord server: `soitora`.

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by arkon** [comment]
@Soitora Please confirm.

**Comment by ReLoia** [comment]
Any update on this issue? Should I page a PR with the deletions?

**Comment by Soitora** [comment]
> Any update on this issue? Should I make a PR with the deletions?

If all three requirements are fulfiled, then you can make a PR for it's removal.
