### ISSUE TITLE
Change the position of the *Entries*

### ISSUE THREAD

**Issue by YahyeDeero** [tachiyomiorg/tachiyomi-extensions#17051]
### Source name

All

### Source language

All

### Describe your suggested feature

If its possible i would like the ability to change the position and the raw of the entries.

For example: if an entry or let's called it like for example *solo levelling* is in *raw 5* i would like to move it to *raw 1* without replacing it with another existed entry and without any complicate steps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This isn't an issue with a specific extension.
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose). 
Please read the acknowledgements you checked.
I assume you want to move entries between sources. You'd have to use migration for that. https://tachiyomi.org/help/guides/source-migration/

**Comment by YahyeDeero** [comment]
> This isn't an issue with a specific extension.
> 
> > If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> 
> Please read the acknowledgements you checked. I assume you want to move entries between sources. You'd have to use migration for that. https://tachiyomi.org/help/guides/source-migration/

I know dude but it takes a time while i want is just to move the entries just with swaps
