### ISSUE TITLE
ReaperScans(Brasil) error 404

### ISSUE THREAD

**Issue by Ruanss2000** [tachiyomiorg/tachiyomi-extensions#17062]
### Source information

ReaperScans lastversion

### Source language

Português(Br)

### Steps to reproduce

Enter manga page
Refresh page, no update nothing.
Error 404

Obs: in the site or WebView is working without problem 

### Expected behavior

Refresh page, update working without problem or message

### Actual behavior

Error 404 without update nothing

### Tachiyomi version

Last version

### Android version

Android 11

### Other details

Only in extension ReaperScans(Brasil)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Brazilian Reaper is known for changing their URLs constantly. The extension try to do its best to find the new URL of the entries but it will not always work. Migrate from Reaper to Reaper to update the URL or just migrate to better sources that doesn't have these bad behaviours.
