### ISSUE TITLE
Manhuaren 1.4.11 no value for response

### ISSUE THREAD

**Issue by DasCrystal** [tachiyomiorg/tachiyomi-extensions#17061]
### Source information

Manhuaren 1.4.11

### Source language

Chinese

### Steps to reproduce

Browse -> Sources -> 漫画人 Extension

### Expected behavior

List manga.

### Actual behavior

Said "no value for response"

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

It's "signature error", too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
@felixfon Is the app constantly updating to change the request format? If it is, the extension should be removed due to cat-and-mouse game.

**Comment by felixfon** [comment]
> @felixfon Is the app constantly updating to change the request format? If it is, the extension should be removed due to cat-and-mouse game.

The server didn't change the format, but the validation was stricter after the extension was updated.

**Comment by DasCrystal** [comment]
> > @felixfon Is the app constantly updating to change the request format? If it is, the extension should be removed due to cat-and-mouse game.
> 
> @stevenyomi The server didn't change the format, but the validation was stricter after the extension was updated.

Yes, Manhuaren looks not pretending to block Tachiyomi, perhaps they just dealing with real bot.

**Comment by sao-coding** [comment]
Should we use a crawler instead?

**Comment by williamkitchong** [comment]
Please do not remove the extension. Manhuaren is the best source for Chinese manga.
All of my manga are using this extension.
