### ISSUE TITLE
mangakakalot and manganeto chapter not loading 

### ISSUE THREAD

**Issue by myselfsumandutta** [tachiyomiorg/tachiyomi-extensions#17063]
### Source information

Mangakakalot 1.4.8 Manganato 1.4.7

### Source language

English 

### Steps to reproduce

1. Click on browse 
2. Go to source tab
3. Open mangakakalot/manganato 
4. Click on any manga
5. Open chapter
6. From 3rd page images are not loading. 

EDIT: TRY WITH THIS MANGA (SOME MANGA ARE WORKING OTHER'S ARE NOT) -
The World Of Otome Games Is Tough For Mobs

### Expected behavior

The images should load normally 

### Actual behavior

From 3rd page no images are loading.

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
cannot reproduce (however, occasionally its pretty slow)

**Comment by myselfsumandutta** [comment]
> cannot reproduce (however, occasionally its pretty slow)

Please  try with these manga - World Of Otome Games Is Tough For Mobs, Takarakuji De 40-Oku Atattandakedo Isekai Ni Ijuu Suru, Reborn As A Barrier Master

Having issue with almost all the manga, the error says- the  image couldn't  be loaded (try again)

**Comment by alekc** [comment]
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/302807/4061f679-1027-4fae-8d42-f056f95a44c5)

**Comment by myselfsumandutta** [comment]
Uninstall and install this one ( tachiyomi-arm64-v8a-v0.14.6.apk) and the issue fixed.
