### ISSUE TITLE
MangaInUa not loading any chapters

### ISSUE THREAD

**Issue by Teashrock** [tachiyomiorg/tachiyomi-extensions#17073]
### Source information

MangaInUa 1.4.3

### Source language

Ukrainian

### Steps to reproduce

1. Install MangaInUa.
2. Look up for any manga in it.
3. Click on it.
4. See text "No chapters" ("Немає розділів").

### Expected behavior

Being able to download and read the list of manga chapters from MANGA/in/UA.

### Actual behavior

Seeing manga on MANGA/in/UA, but the extension doesn't see any chapters.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

It also refuses to read or download chapters in manga already added.
I tried clearing cookies and WebView cache, then changing user agent. But neither of these helped.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment]
Source is loading chapter list via an Ajax request now with active check of the `user_hash` value. Random (or an old one) do not work, so an additional effort in researching a way around it is required. Stopping working on this one, if anyone want to have a go feel free to do so.

**Comment by Snikewin** [comment]
The same problem
