### ISSUE TITLE
Sushi-scan: recent page doesn't match with site

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#17089]
### Source information

Sushi-scan 1.4.30

### Source language

French

### Steps to reproduce

1. Enter the extension
2. Select recent
3. The recent page shows a list of manga that doesn't show the more recent updates

### Expected behavior

The page should show the latest updated mangas

### Actual behavior

The page shows the latest updates but not the more recent ones. Essentially it is outdated.
Here's what it shows for me
![Screenshot_20230712-180626](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/0a1a66a9-af27-4c8b-a754-92eb3a4c6a8a)
Here's the actual latest updates
![Screenshot_20230712-180647](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/61d55221-c441-4fe6-a6b0-9af8ae4e1e38)
And here's where the recent page starts matching with the site
![Screenshot_20230712-180716](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/442de945-f82a-4c54-bb8b-2f4237ef20f5)
Right now for me it seems to be between 3 to four days out of date

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

This only concerns the recent update page. A manga if updated will actually show its latest chapters. It's just the "recent" page that seems to be outdated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extensions based on MangaThemesia theme doesn't use the home page of the site to get the latest releases, it uses the archive page sorted by updated. Likely their site have a slow cache in that page, so it takes a while for their uploads to appears there as well, which in this case isn't something the extension should try to fix it.
