### ISSUE TITLE
Luscious (NSFW) - The images are divided as if they were chapters

### ISSUE THREAD

**Issue by JhulShock** [tachiyomiorg/tachiyomi-extensions#17092]
### Source information

Luscious 1.4.19

### Source language

English / Many languages

### Steps to reproduce

1.- Enter any manga/comic.
2.- Each comic/manga should have only 1 multi-page chapter, but instead have many 1-page chapters.

### Expected behavior

Each comic should contain all the pages in a single episode.

### Actual behavior

Each comic is divided into multiple chapters of 1 single page.

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

![a81feb59-893d-4789-966b-662cb7f6f06f](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/21696690/47d5de23-5839-4173-bbae-ede43a3fabce)

![51a6cf70-fc09-477a-8109-4f6e1784246e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/21696690/0e0faa2f-b35a-4eae-931a-994a6d5f5b2c)

![3b8ccca6-27fb-425e-822a-aca06b16c560](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/21696690/992847d8-7183-4419-bb88-b82ceadd5cfa)

![b84af67d-561f-4455-8feb-72f9939c41ea](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/21696690/86826c0a-f568-4568-9a66-c697903081c1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This behavior is intended, and explained [in the Luscious-specific FAQ](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/a973b0aa595f9467cb66ce0c270873f5a7cfa15d/src/all/luscious/README.md#why-is-each-page-a-chapter).
