### ISSUE TITLE
please provide a new function with happymh

### ISSUE THREAD

**Issue by engineer011** [tachiyomiorg/tachiyomi-extensions#17095]
### Source name

happymh

### Source language

Chinese

### Describe your suggested feature

please provide a new function to adjust access point and interval time.it's a good way to avoid Android detection

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
What is access point and interval time? You can explain in Chinese.
