### ISSUE TITLE
Yugemangas no esta resulto

### ISSUE THREAD

**Issue by Striven100** [tachiyomiorg/tachiyomi-extensions#17105]
### Source information

Yugenmangas

### Source language

Español

### Steps to reproduce

Desde hace ya dos semanas que no se puede acceder, no es nada nuevo pero las medidas tomadas hasta ahora no funcionan

### Expected behavior

Deberia de poder ver normalmente

### Actual behavior

En su lugar, esta igual q antes, no se puede acceder a la extencion ni leer los comics

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Cual es el error específicamente? Sube una captura del mensaje que aparece al tratar de acceder

**Comment by bapeey** [comment]
Eso es un problema de la pagina, el certificado que usan ("GTS CA 2P2") no esta disponible en versiones antiguas de Android. Al parecer solo esta disponible a partir de Android 11. 
Lee #17014

**Comment by Striven100** [comment]
Solo para avisar, hoy yugenmangas volvio a funcionar normalmente, no se la razon, no hice nada. Solo de repente pude acceder
