### ISSUE TITLE
WNACG No results found

### ISSUE THREAD

**Issue by ninsuko** [tachiyomiorg/tachiyomi-extensions#17108]
### Source information

WNACG 1.4.14

### Source language

Chinese

### Steps to reproduce

1. Browser
2. Sources -> WNACG
3. No results found display

### Expected behavior

List of available manga should be display by default instead of No results found.

### Actual behavior

No results found
Click "Retry" will get the same result
Click "Open in WebView" would see list of manga correctly shown with URL www.htmanga9.top

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce.
