### ISSUE TITLE
KomikLab: Indonesian site has shut down

### ISSUE THREAD

**Issue by AhmadHaical** [tachiyomiorg/tachiyomi-extensions#17107]
### Source information

https://www.dynadot.com/forsale/komiklab.net?drefid=2071

### Source language

Indonesia 

### Source new URL

https://komiklab.com/

### Other details

Komiklab changed its domain link from net to com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
That's the English site. If you took 1 minute to actually visit the English site you'll notice the Indonesian stuff has moved to https://soulscans.my.id (which has a open source request https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16544)

**Comment by AntsyLich** [comment]
/edit-title "KomikLab: Indonesian site has shut down"
