### ISSUE TITLE
MintManga cannot load chapters for many titles

### ISSUE THREAD

**Issue by Steex** [tachiyomiorg/tachiyomi-extensions#17115]
### Source information

Mintmanga 1.4.61

### Source language

Russian

### Steps to reproduce

1. Open the MintManga source
2. Search for a title "Эннеада" (eng: "Ennead")
3. Open the found manhwa's page.

### Expected behavior

The chapter list is displayed.

### Actual behavior

* Chapters are not loaded ("0 chapters")
* The notification is displayed: "Для просмотра контента необходима авторизация через WebView" (An authentication via WebView is required to see the content)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

MintMangs is a part of GroupLe multisource.

Not all titles are affected by the issue. For example, the title "Человек-бензопила" (Chainsaw Man) is loaded correctly.
If any title (either affected or not affected by the bug) is opened in the WebView, its chapters are always available, without signing in.

**Example URLs**

* Affected: https://mintmanga.live/enneada__A35c96
* Not affected: https://mintmanga.live/chelovek_benzopila__A5327

**Some analysis**

I presume that the reason for this behavior is in file /multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt, line 204. There's a condition `if ((document.select(".expandable.hide-dn").isNotEmpty()` which is true for affected titles.

Nevertheless, the further structure of the pages seem to be the same for both affected and not affected titles. So the chapter extraction code should actually work in both cases.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
Everything works correctly. Сhapters in such Affected mangas cannot be opened without authorization and they will just cause errors.

**Comment by Steex** [comment]
The title Ennead cannot load chapter names from the Tachiyomi interface, but is opened without problem via WebView. I had never authenticated there, in fact I do not even has an account.
Both browsers I tried (Firefox and Chrome) also load content of this title normally, and the structure of web page seem to be the same as for not affected titles.

![ennead-1_resize](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/1201510/727a1721-568c-416d-b3e4-e6552fe0d1e3)

![ennead-3_resize](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/1201510/e8d347a7-24f9-4daf-95e7-e82fe2a8b294)
