### ISSUE TITLE
Add skip manga in library when browsing

### ISSUE THREAD

**Issue by llreizh** [tachiyomiorg/tachiyomi-extensions#17116]
### Describe why this should be added

I think skip manga when in library when browsing will pratical

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong place to request this.

Already added in preview version: https://github.com/tachiyomiorg/tachiyomi/issues/2941
