### ISSUE TITLE
Extension issue 

### ISSUE THREAD

**Issue by YAZEED148** [tachiyomiorg/tachiyomi-extensions#17125]
### Source information

Azora 1.4.36

### Source language

Arabic

### Steps to reproduce

I try to read manga
the extension won't work
the problem is the extension doesn't work

### Expected behavior

It should work

### Actual behavior

It should work

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

The extension won't work 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the information requested appropriately. "It doesn't work" means absolutely nothing and doesn't help into fixing the issue.

**Comment by YAZEED148** [comment]
the domain changed

في الأحد، ١٦ يوليو ٢٠٢٣, ٢:١٦ ص Alessandro Jean ***@***.***>
كتب:
