### ISSUE TITLE
I have a prob with an extension

### ISSUE THREAD

**Issue by Atifsaid** [tachiyomiorg/tachiyomi-extensions#17127]
### Source information

Azora1.4.36

### Source language

Arabic

### Steps to reproduce

Http error 521 : check website in webview

### Expected behavior

This never happened to me before since i started using tachi
 

### Actual behavior

It tells me to check webview and when i check it works normal i don't know why

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

I tried troubleshooting and it didn't work out

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 5xx errors are server side and the site owners that needs to fix it, nothing that can be done on the extension side.
