### ISSUE TITLE
Sushi-Scan : Manga in the library aren't registered as such in the extension

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#17133]
### Source information

Sushi-scan 1.4.31

### Source language

French

### Steps to reproduce

1. Have mangas from the source prior to the 1.4.31 update
2. Open the extension
3. None the manga previously added to the library are registered as such in the extension and basically ^presented as unadded

### Expected behavior

Mangas added previously added should be shown as added in the extension

### Actual behavior

Mangas added previously are shown as unadded in the extension

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

Everything else is including updates works. It's just that the extension doesn't seem to register the mangas that were previously added as in the library. If it can't be fixed then I guess mass migrations to the same source is the option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Maybe miss migrate, it's not somethng that we can solve anyway, it's probably the main drawback of the update

**Comment by aboudiom59** [comment]
> Maybe mass migrate, it's not somethng that we can solve anyway, it's probably the main drawback of the update P. S: I don't have the same bug as you since the update so maybe cleaning cookies, database etc could help

Guess I'll mass migrate thanks for the reply.
