### ISSUE TITLE
Asura Scans: Changed their domain

### ISSUE THREAD

**Issue by typicookie** [tachiyomiorg/tachiyomi-extensions#17136]
### Source information

Asura Scans 1.4.48

### Source language

English

### Source new URL

https://asura.gg/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Hawksaran** [comment]
One update came today but not fixed
