### ISSUE TITLE
hentaila.tv

### ISSUE THREAD

**Issue by Jipson2003** [tachiyomiorg/tachiyomi-extensions#17143]
### Source name

https://hentaila.tv/

### Source link

https://hentaila.tv/

### Source language

español

### Other details

pagina de hentai

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Also wrong repo
