### ISSUE TITLE
Asura Scans Null error

### ISSUE THREAD

**Issue by TheDeicide** [tachiyomiorg/tachiyomi-extensions#17147]
### Source information

Asura Scans 1.4.48

### Source language

English 

### Steps to reproduce

1. Updating A mamhwa from asura scans
2. Showing NullPointerError: null

### Expected behavior

While updating any manhwa from asura scan, it should get updated without showing any error. 

### Actual behavior

It's showing NullPointerError: Null

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have updated all installed extensions.
