### ISSUE TITLE
hentaila extensions

### ISSUE THREAD

**Issue by Jipson2003** [tachiyomiorg/tachiyomi-extensions#17142]
### Source name

HentaiLa

### Source language

español

### Source link

https://www3.hentaila.com/doweb

### Other details

hello, i want to report an error in the spanish hentaila extension, when i open a chapter it doesn't load and stays loading and when i change the server it doesn't give me the option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
wrong repo
