### ISSUE TITLE
NHentai: Forced random UA causing cloudflare issue

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#17155]
### Source information

Nhentai 1.4.38

### Source language

English

### Steps to reproduce

Open extension

### Expected behavior

Normal behavior

### Actual behavior

Give java.io.exception:failed to bypass cloudflare (works fine in webview and i change my user agent) 

### Tachiyomi version

0.14.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
/edit-title "NHentai: Forced random UA causing cloudflare issue"

**Comment by newholder** [comment]
Ah, so it's not only me that can't open nhentai. it's ok on the webview, bit failed on the app

**Comment by itsprakashp** [comment]
Try using latest android user agent. 

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

https://www.whatismybrowser.com/guides/the-latest-user-agent/android

**Comment by newholder** [comment]
Doesn't work. But, just a few moments ago, there's an update to the extension. It works immediately.
