### ISSUE TITLE
Disable source from updating titles in library

### ISSUE THREAD

**Issue by tonizombie** [tachiyomiorg/tachiyomi-extensions#17164]
### Source name

NHentai

### Source language

all.nhentai

### Describe your suggested feature

It's totally useless to check for new chapters for nHentai titles as they are single chapter entries.
The app even gives warning when updating larger libraries that it could "harm" sources so skipping this extension should be good.

### Other details

I asked this before in discord and was told that this is already supported feature in the API.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
nhentai already is setup to only update once, are you saying your nhentai entries are being updated?

**Comment by tonizombie** [comment]
> nhentai already is setup to only update once, are you saying your nhentai entries are being updated?
For me yes, i have ~1800 entries in library in total and the update notification has the same number, so i would assume that they are being updated

**Comment by scb261** [comment]
Update strategy is stored for each manga separately. You probably added those entries before the change was made in the extension. Enable "Automatically refresh metadata" and update once, this should fetch the new strategy for the next time.

**Comment by alessandrojean** [comment]
Closing as the source is already marking the entries to not be updated.
