### ISSUE TITLE
肉漫屋无法观看

### ISSUE THREAD

**Issue by sha-mao** [tachiyomiorg/tachiyomi-extensions#17168]
### Source information

Roumanwu 1.4.4

### Source language

中文

### Steps to reproduce

直接点击某一漫画观看

### Expected behavior

应该要正常加载出来

### Actual behavior

直接提示空白退出漫画页面

### Tachiyomi version

0.14.6

### Android version

安卓13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kinyeah** [comment]
Same issue here.

When clicking in to an episode, it will load at first. Then it just returns to the catalog automatically and then shows up a blank spot at the bottom like this.

![Screenshot_20230719_011915_Tachiyomi.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/86000583/0c9cb460-dd0b-4ec9-9f77-8bc0f191b2a1)

This is the 肉漫屋 extension page

![Screenshot_20230719_010623_Tachiyomi.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/86000583/cb16a428-c44c-4b14-90bb-c20eec536bfb)
