### ISSUE TITLE
adding feature to download the zip file instead

### ISSUE THREAD

**Issue by arozaqf** [tachiyomiorg/tachiyomi-extensions#17179]
### Source name

death toll scan

### Source language

english

### Describe your suggested feature

add an option to download the zip file instead of using the per chapter download

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Extensions doesn't support this.
