### ISSUE TITLE
ReadAllComics displaying no pages found on all results

### ISSUE THREAD

**Issue by christop23** [tachiyomiorg/tachiyomi-extensions#17174]
### Source information

ReadAllComics 1.4.1

### Source language

English

### Steps to reproduce

1. Open tachiyomi
2. Go to extensions section and select readallcomics
3. Select anything from the displayed list
4. Try to read any chapter
5. You can see the "pages not found" error being displayed on screen

### Expected behavior

While clicking chapters, it's supposed to load pages instead of the error

### Actual behavior

It's displaying "pages not found" error

### Tachiyomi version

0.14.6

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MohnJadden** [comment]
Having the same issue with a fresh install of the extension (9 PM GMT -4 on 7/18/23) on Android 10. Un-installed all other extensions, un-installed Tachiyomi, reinstalled Tachiyomi and only Readallcomics, and the issue persists.
