### ISSUE TITLE
Manhuaren: failed to load listing and chapter pages

### ISSUE THREAD

**Issue by Erbzur** [tachiyomiorg/tachiyomi-extensions#17170]
### Source information

Manhuaren 1.4.12

### Source language

Chinese

### Steps to reproduce

1. open any chapter of a manga, such as chainsaw man

### Expected behavior

Load manga pictures successfully

### Actual behavior

Indicated unable to load the picture

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
@felixfon Time to remove extension I guess?

**Comment by Erbzur** [comment]
> I can't reproduce it on my device. @Erbzur Can you provide more info?

{
  "errorResponse": {
    "code": 40011,
    "subCode": "",
    "message": "缺少token",
    "rgtk": null
  }
}
these are what I found when fetching the api

**Comment by lok77chan** [comment]
> > I can't reproduce it on my device. @Erbzur Can you provide more info?
> 
> { "errorResponse": { "code": 40011, "subCode": "", "message": "缺少token", "rgtk": null } } these are what I found when fetching the api

I am having same issue. This has been the case for me for all the recent patch. The message in this json mean "missing token" just in case.
![Screenshot_20230719-110835](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/15722025/04bf88d4-e156-48c2-b2cc-908ff57ee70b)

>

**Comment by LAGMAN-TW** [comment]
I was able to make it work with VPN. Although I can see the images, the WebView showed the same error message for me

**Comment by john-stones5** [comment]
I've never had this problem but the old "no value for response" thing appears again just now.

**Comment by stevenyomi** [comment]
Closing due the fix in #17202. Open a new issue if it happens again.

**Comment by Erbzur** [comment]
Now it comes back to "no value for response" issue again. The new version didn't fix the original problem.

**Comment by Erbzur** [comment]
> > Now it comes back to "no value for response" issue again. The new version didn't fix the original problem.
> 
> I think the issue is the same as before because the current device model has been blocked again.

When you say "device model", dose it means user agent? If so can I test accessibility by changing UA in tachiyomi settings?

**Comment by stevenyomi** [comment]
> When you say "device model", does it means user agent? If so can I test accessibility by changing UA in tachiyomi settings?

No, the model is also reported in HTTP headers, which you can't change in the app.

**Comment by stevenyomi** [comment]
/edit-title "Manhuaren: failed to load listing and chapter pages"

**Comment by a0193143** [comment]
"No value for response" error still persist.
