### ISSUE TITLE
LynxScans Not Showing New Chapters

### ISSUE THREAD

**Issue by FriedGenera** [tachiyomiorg/tachiyomi-extensions#17186]
### Source information

LynxScans 1.4.7

### Source language

English

### Steps to reproduce

1.Open Any Series On LynxScans
2.Refresh for Newest Chapters

### Expected behavior

The newest chapters should show up in the chapter list for the series.

### Actual behavior

The chapter list does not update with the newest chapters. They appear when I go to webview however. 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Site now using MangaThemesia
