### ISSUE TITLE
[Source Request] NSSKL Translations

### ISSUE THREAD

**Issue by kresendonada** [tachiyomiorg/tachiyomi-extensions#1718]
### Source Website
Website can be found at https://manga.nerjemah.in

### Other Details
The group who translate manga with love and in Indonesian languange.

**Comment by happywillow0** [comment]
You can find the group's translations on Mangadex which would be quickest and easiest:
https://mangadex.org/group/9999/nsskl-translations

**Comment by as280093** [comment]
here is the icon:
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3880167/ic_launcher.1.zip)
