### ISSUE TITLE
Nhentai doesnt loads up

### ISSUE THREAD

**Issue by SwiftGrim** [tachiyomiorg/tachiyomi-extensions#17224]
### Source information

NHentai 1.4.39

### Source language

Multi Language

### Steps to reproduce

Should load up the page either from extension or from web view. 

### Expected behavior

Should load up the popular category but I get java. Io. Joe expectation. 

### Actual behavior

Doesn't load up, cloud flare failure, verification failure from web view as well. Even if extension not working, the web view should work no? But that seems to not work either 

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

--------- beginning of main
07-22 19:57:05.529 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:57:05.540 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:57:05.579 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:59:00.498 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:59:00.507 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:59:00.573 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:59:41.519 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:59:41.527 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 19:59:41.553 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 20:00:52.954 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 20:00:52.963 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
07-22 20:00:53.007 27393 27393 E RtgSchedManager: endActivityTransaction: margin state not match
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 10 (SDK 29)
Android build ID: MAR-L21MEB 10.0.0.273(C185E3R3P1)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWMAR
Device model: MAR-LX1A
Device product name: MAR-LX1A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do actually follow the Cloudflare section on the troubleshooting guide you checked on the acknowledgements section.

> I have tried the troubleshooting guide.
