### ISSUE TITLE
jinmantiantang Some mirrored urls repeat Cloudflare human-machine verification an unlimited number of times

### ISSUE THREAD

**Issue by a2509067968** [tachiyomiorg/tachiyomi-extensions#17230]
### Source information

jinmantiantang 1.4.38

### Source language

Chinese

### Steps to reproduce

点开扩展程序，进入漫画目录，打开网页验证Cloudflare，通过验证，出现漫画目录，观看漫画。
Open the extension, go to the Comics directory, open the web page to verify Cloudflare, through the verification, the comics directory appears, and watch the comics.

### Expected behavior

出现漫画目录，观看漫画
Comics catalog, watch comics.

### Actual behavior

在验证步骤无限重复Cloudflare
Repeat Cloudflare indefinitely in the verification step

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

具体url为:18comic.vip，18comic.org
同时镜像网站最后三个打不开，希望增加自定义镜像网站
The url is 18comic.vip, 18comic.org
At the same time, the last three mirror websites can not be opened, and I hope to add a custom mirror website。
Thank you for your hard work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.

> At the same time, the last three mirror websites can not be opened, and I hope to add a custom mirror website

Turn off your VPN when using the last three mirrors. Also, the last three mirrors will update automatically. You can't find any mirrors other than those. If you do, open a new issue to report.
