### ISSUE TITLE
MangaSwat search and last update not working 

### ISSUE THREAD

**Issue by T3MYA11** [tachiyomiorg/tachiyomi-extensions#17238]
### Source information

MangaSwat 1.4.36

### Source language

Arabic 

### Steps to reproduce

1.if i tried to search for a manga . it doesn't work out. just showing a random mangas
2. the same happened if i uesd latest just showing a random mangas

### Expected behavior

it should work like this 
![Screenshot_2023-07-23-23-06-28-060_eu kanade tachiyomi j2k](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92279646/576e231a-9d72-4d60-9636-b1d1aa1b6c1d)

### Actual behavior

but this happened instead 
![Uploading Screenshot_2023-07-23-23-07-49-827_eu.kanade.tachiyomi.j2k.jpg…]()

### Tachiyomi version

tachiyomij2k 1.6.6

### Android version

Android 11

### Other details

my library working and updating fine no problem with it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by T3MYA11** [comment]
![Uploading Screenshot_2023-07-23-23-07-49-827_eu.kanade.tachiyomi.j2k.jpg…]()

**Comment by T3MYA11** [comment]
![Uploading Screenshot_2023-07-23-23-17-26-762_eu.kanade.tachiyomi.j2k.jpg…]()

**Comment by T3MYA11** [comment]
![Uploading Screenshot_2023-07-23-23-19-22-717_eu.kanade.tachiyomi.j2k.jpg…]()

**Comment by vetleledaal** [comment]
Can't reproduce the issue you are having with the latest tab in standard Tachiyomi.


<img src="https://github.com/tachiyomiorg/tachiyomi-extensions/assets/13540478/f1a4818e-76be-45ad-b7a9-d24bad48bc21" width="80%" height="80%">

**Comment by T3MYA11** [comment]
okay now the problem still exist and also I can't update the manga In my library it doesn't give me error or anything just not updating also latset and mangal list just showing a 25 manga and most of them not even have new chapters in the website

**Comment by Tian-77** [comment]
![Screenshot_2023-07-24-04-56-04-697_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/133915977/c711863f-7257-4136-8ab1-f37a1712e993)
It also doesn't show all the manags in the site it just shows a few of them
