### ISSUE TITLE
WNACG/htmanga No Result

### ISSUE THREAD

**Issue by kschou95** [tachiyomiorg/tachiyomi-extensions#17266]
### Source information

WNACG 1.4.14

### Source language

Chinese

### Steps to reproduce

Just open the source

Video proof of issue: https://youtube.com/shorts/oM4dFBbOBYg?feature=share

### Expected behavior

manga list should show

### Actual behavior

show no result found

Video proof of issue: https://youtube.com/shorts/oM4dFBbOBYg?feature=share

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

same as issue #17108 but not sure why can't replicate and closed despite the issue is still there.

logcat attached. will try to help devs with more logs when requested.
[logcat.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12175046/logcat.txt)

webview works only

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Still can't reproduce. What's the country of your IP?

**Comment by kschou95** [comment]
> Still can't reproduce. What's the country of your IP?

malaysia. it is still the same even i'm using a vpn. dns is set to google dns.

**Comment by stevenyomi** [comment]
[tachiyomi-zh.wnacg-v1.4.14-debug.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12175600/tachiyomi-zh.wnacg-v1.4.14-debug.zip)

Try installing this debug build (rename extension to .apk), open browse, then share the crash logs again.

**Comment by kschou95** [comment]
> [tachiyomi-zh.wnacg-v1.4.14-debug.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12175600/tachiyomi-zh.wnacg-v1.4.14-debug.zip)
> 
> Try installing this debug b

[logcat.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12175769/logcat.txt)
uild (rename extension to .apk), open browse, then share the crash logs again.

here's the logcat as requested. hope its the correct way.
using command "adb shell" then "logcat | grep eu.kanade.tachiyomi"

**Comment by stevenyomi** [comment]
You can navigate to app settings -> advanced -> share crash logs. If you're using adb shell, don't grep as the result I'm logging does not have the package name and might span multiple lines.

**Comment by kschou95** [comment]
> You can navigate to app settings -> advanced -> share crash logs. If you're using adb shell, don't grep as the result I'm logging does not have the package name and might span multiple lines.

oh sorry, just noticed the app got a crashdump function
here's it
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12175871/tachiyomi_crash_logs.txt)

**Comment by stevenyomi** [comment]
Seems that you're using a mobile User Agent string. This extension needs a desktop one (like the default).

**Comment by kschou95** [comment]
> Seems that you're using a mobile User Agent string. This extension needs a desktop one (like the default).

oh about this. i changed the user string due to failing nhentai's cloudflare check.

now i reset it back to default, and nhentai now can't pass cloudflare. after ticking the verify human box, it shows failure.

i'll check if there's an open issue for it later and open one if there isn't. thanks for the help.

**Comment by kschou95** [comment]
> Seems that you're using a mobile User Agent string. This extension needs a desktop one (like the default).

hello sir, sorry to bother, i had opened an the issue #17273 but seems like the bot just straightaway closes it. is there any other way to let the devs know that it's the user string issue that's affecting it?

**Comment by stevenyomi** [comment]
You can open a feature request to add User Agent override setting to nhentai.
