### ISSUE TITLE
Dragontea the image couldn't Load and Cloudflare failure

### ISSUE THREAD

**Issue by thu2468** [tachiyomiorg/tachiyomi-extensions#17278]
### Source information

Dragontea 1.4.31

### Source language

English

### Steps to reproduce

Cloudflare Issue:
1. Open source
2.  Webview
3.  Click Your a human
4. it say failure

If you get past the cloudflare issue
1. Open a manga
2. Open a chapter
3. Image cant be loaded error

### Expected behavior

cloudflare should be success as there a old version with cloudflare success when you check your a human

Image should load

### Actual behavior

cloudflare failing

image not loading

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

So the working cloudflare dragontea version i got working was a old one 
https://github.com/Riztard/tachiyomi-extensions/blob/riz-ext/multisrc/overrides/madara/dragontea/src/DragonTea.kt
This one works. I tried using the Custom user agent in the latest dragontea version and it didnt work still say failure

In the latest dragontea version i am sometime able to load the list of manga but image will not load for it

Here a logcat of it trying to grab the image

https://pastebin.com/nNf0xMmB

logcat is taken from the old version but should still be the same i think as the code grabing img is the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
I'd fix but Android Studio isn't cooperating. For anyone wanting to look into this:

The image attributes are encrypted:
```html
<img id="{&quot;ct&quot;:&quot;3vEu2EVu46aew6uGpfvmZw==&quot;,&quot;iv&quot;:&quot;13f54983bd004433b52d26d122c91796&quot;,&quot;s&quot;:&quot;307061c7a45030b4&quot;}" data-src="{&quot;ct&quot;:&quot;suqgVy5Lwz4ieTa2TARdA+b1EW+7oPwkYOz+cUfz4w2wrYrOEnPpDStP3a3ft1Q2uo+B\/Mq6ryCL0ahAOEMU05iiY24\/zPVoWBNU7oGxfqDq5jsNRcOTl6\/oxZHvGEpxkLeHdnnahi6nycdb2+FF8omvU8QGVPrVemsYqh+X5Lw=&quot;,&quot;iv&quot;:&quot;67aff246c8b7382788ed3ec086bb0fd5&quot;,&quot;s&quot;:&quot;4f35440953182048&quot;}">
```

Decrypt it the same way you decrypt Madara's chapter protection:
```kotlin
val srcData = json.parseToJsonElement(img.attr("data-src")).jsonObject

val unsaltedCiphertext = Base64.decode(srcData["ct"]!!.jsonPrimitive.content, Base64.DEFAULT)
val salt = srcData["s"]!!.jsonPrimitive.content.decodeHex()
val ciphertext = SALTED + salt + unsaltedCiphertext

val src = CryptoAES.decrypt(Base64.encodeToString(ciphertext, Base64.DEFAULT), password)
```

The current password is `releasethestormy888`.

**Comment by urekxmazino** [comment]
> releasethestormy888

interesting i just tried it and seems the password is not currect do u mind sharing do did u find the password

**Comment by beerpiss** [comment]
> > releasethestormy888
> 
> interesting i just tried it and seems the password is not currect do u mind sharing do did u find the password

[Works for me](https://pl.kotl.in/am0OLPcQR)

**Comment by thu2468** [comment]
how does the code supposed to be implemented?

**Comment by thu2468** [comment]
i assume you gotta parse the CT and S from the link?

as the example link looks like this?
https://dragontea.ink/novel/it-all-starts-with-playing-game-seriously/chapter-137/%7B%22ct%22:%22r+g6F11waTEUYx4DJvglNTx/PEx3P/o+anvoZE1fDe3F3r4ARiHVUPxbcsMdSF2y+5zqdfKggn5vQ17WqSBWAEa2W2aYK9ycnK04PVobNzc0HUyc9ii4lcM8vMsJuQX69MSNhzJWd9mqq5zz+30kyPiJSaLwzIZG1Wu+MWtYozI=%22,%22iv%22:%226e8a796428c730b4e6ab4f93d895515c%22,%22s%22:%2287714c02b18ea592

**Comment by thu2468** [comment]
> > releasethestormy888
> 
> interesting i just tried it and seems the password is not currect do u mind sharing do did u find the password

password is in script i think
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/1341488/6d2d14c8-a86c-4026-849b-6bff4460d37d)

**Comment by thu2468** [comment]
![Screenshot_20230802_141816_TachiyomiSY](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/1341488/4ff0a229-2253-4198-a649-85b2e06408af)
Not working with the fix getting error

**Comment by alessandrojean** [comment]
Please open a new issue.
