### ISSUE TITLE
NHentai User Agent String Override

### ISSUE THREAD

**Issue by kschou95** [tachiyomiorg/tachiyomi-extensions#17274]
### Source name

NHentai

### Source language

english, chinese, japanese, multi

### Describe your suggested feature

Changing the user agent string for the NHentai extension to "Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.5790.136 Mobile Safari/537.36" without affecting the main tachiyomi app settings. This is to pass the cloudflare check without affecting other sources.

### Other details

As mentioned in issue #17273 , its the user agent string (default) that's affecting the cloudflare check. Changing the user agent string that works for NHentai will affect other source as happened in issue #17266 .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
the [nhentai extension](https://tachiyomi.org/extensions/#all.nhentai) (ver 1.4.39) already has a custom user agent setting
