### ISSUE TITLE
Manga reader Api rate limit excessed

### ISSUE THREAD

**Issue by Gerr-san** [tachiyomiorg/tachiyomi-extensions#17272]
### Source information

Mangareader.site  1.4.22

### Source language

English

### Steps to reproduce

> I Just read 2 or 3 chapter of the manhua and download some of the chapter 
And the next thing popping up in the app is something like 

> this
![Screenshot_20230727_105257_TachiyomiSY](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/140680465/b7959d53-495e-4dbf-baca-2b6b5cbcea57)

I mean... the heck! its directing me to Open mangahub.io instead of mangareader's web that im using.

In this state you can neither read the chapter nor download it.. and this happen to all the library on this extension 

### Expected behavior

The chapter inside the extension is no problem all is readable there's no missing chapter whatsoever 

### Actual behavior

The main problem is the  of Api rate limit excessed is so frecuent its so annoying

### Tachiyomi version

Tachiyomi sy 1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
they use the same codebase so probably the same backend. #16481
