### ISSUE TITLE
HentaiVN: Add mirror option to choose from multiple domains

### ISSUE THREAD

**Issue by leonminus** [tachiyomiorg/tachiyomi-extensions#17280]
### Source name

Hentaivn 1.4.27

### Source link

Hentaivn.tv   hentaivn.autos  m.hentaivn.site

### Source language

Vietnamese

### Other details

I still have 1.4.26 hentaivn.autos apk, reinstalled it and it works again 8))
This website has 3 domains, sometime one of these  has CF protection but another one hasnt. I hope someone can post three version of each extension's domain on Tachi's extension list web, or at least keep the old apk version download availably , so we can use the vesion that have domain work on Tachiyomi. Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
/edit-title "HentaiVN: Add mirror option to choose from multiple domains"
