### ISSUE TITLE
Olympus scanlation

### ISSUE THREAD

**Issue by Daniel200y** [tachiyomiorg/tachiyomi-extensions#17299]
### Source information

Olympusscanlation.com

### Source language

Spanish, Español

### Source new URL

https://olympusscans.com/

### Other details

They destroyed the previous url and created a new one so that the images on the page load faster

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already exists.

**Comment by Daniel200y** [comment]
> Ya existe.

No existe realmente su dominio fue camiviado y tiene nueva pagina.

**Comment by alessandrojean** [comment]
The extension already uses their new domain for a while.

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/723dd523fe6f20e7d5e53b8e10a5a0bb4bccc8f2/src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/OlympusScanlation.kt#L21
