### ISSUE TITLE
SlimeRead

### ISSUE THREAD

**Issue by SrCrono** [tachiyomiorg/tachiyomi-extensions#17307]
### Source name

SlimeRead

### Source link

https://slimeread.com

### Source language

Brazilian Portuguese

### Other details

It has some works +18 (some pornhwas and some hentais)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Probably GeoBlocked using CloudFlare, like many PT/BR website. I cant view it.

**Comment by alessandrojean** [comment]
Some stuff are locked under login, like the listing of series in their site, and also their API seems to be very well hidden, and using CSS selectors is hard as they're using TailwindCSS. Gonna close it for now.
