### ISSUE TITLE
Olympus Scanlation Removal

### ISSUE THREAD

**Issue by Daniel200y** [tachiyomiorg/tachiyomi-extensions#17300]
### Source link

https://olympusscanlation.com/

### Other details

the site is no longer supported because it has a new domain

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by alessandrojean** [comment]
The extension already uses their new domain for a while.
