### ISSUE TITLE
Mangahasu can't load chapters

### ISSUE THREAD

**Issue by GrimAngel9** [tachiyomiorg/tachiyomi-extensions#17308]
### Source information

Mangahasu 1.4.16

### Source language

English 

### Steps to reproduce

1. Select any manga from Mangahasu extension
2. Select to read any chapter 

### Expected behavior

Chapter should load the images

### Actual behavior

Source tries to load, and then return to chapter selection with the message:

> For input string: ""

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

![Screenshot_2023-07-29-11-15-52-611_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/140904097/fb7cef94-b66a-42be-add2-71d5dce15f49)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
working fine for me
cant reproduce
