### ISSUE TITLE
Manga18fx suddenly http 502 error

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#17312]
### Source information

Manga18fx

### Source language

English 

### Steps to reproduce

Usually it works as other suddenly it shows error 502 and tells to check webview but even after checking nothing changes it was working fine before an hour 
![Screenshot_2023-07-29-23-10-22-82_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/977841dd-e602-482a-9013-fbc1e3931abd)

### Expected behavior

Should show manwhas

### Actual behavior

Shows 502 error 

### Tachiyomi version

R5955

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 5xx errors are server side, which means you need to wait for the site owners to fix it.

**Comment by Hawksaran** [comment]
Ohh ok I was scared for a second thank u will.wait
