### ISSUE TITLE
mangabz v.1.4.7 can't loaded in tachiyomi

### ISSUE THREAD

**Issue by History-exe** [tachiyomiorg/tachiyomi-extensions#17319]
### Source information

mangzbz v.1.4.7

### Source language

Chinese

### Steps to reproduce

Normal use the mangabz extension, can't load anything.
The webview of the main site and mirror site is fine.

### Expected behavior

load something or some error code.

### Actual behavior

Actual behavior like this:
![图片](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/33642965/2a2858ab-1629-4d01-892e-2b7466aef930)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

user-agent is: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
webview is: Android System Webview 115.0.5790.138

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
Your user-agent is wrong, so the mangabz is returning mobile version of the website. You should use user-agent for desktop.

**Comment by History-exe** [comment]
Sorry for disturbing you. Could we add the **custom user-agent to mangabz extension**?

More and more sites has rise their cloudflare protection level. I found the only **solution to pass the rised cloudflare test is use your real webview user-agent.**

Such as nhentai, for me. nhentai needs to set your real webview uesr-agent to pass the cloudflare protection. And the zh.baozimanhua needs too. Set the real webview user-agent will pass sites.

But mangabz needs you set the desktop user-agent, I need to switch user-agent to view it but abandon other sites.

According to my test results, the user-agent requirements of the websites are as follows:
|  site   | cloudflare level | user-agent |
|  ----  | ----  | ----  |
| mangabz  | normal or no | fake desktop requirement |
| nhentai  | high | real webview user-agent |
| baozimanhua  | high | real webview useragent |

**Comment by stevenyomi** [comment]
Most extensions with high Cloudflare protection level already have random/custom UA settings. Most websites require standard desktop UA, so it's not feasible to add settings to all of them.

The app will eventually add a feature to set UA per extension, but there's no ETA.

**Comment by History-exe** [comment]
Thank you for reply. Now I understand it.
