### ISSUE TITLE
Filter or Sort without "raw" Source title so I can Select and download chapters that only English subs 

### ISSUE THREAD

**Issue by mohamed-magdy26** [tachiyomiorg/tachiyomi-extensions#17327]
### Source name

it's not related to specific extensions as some have it and some don't 

### Source language

English

### Describe your suggested feature

Some chapters are followed by raw and I would love to download only English so if we can to be able to filter chapters without raw
or sort them by name but taking into consideration the raw in the title so we can be able to select all English or sequence of chapters instead of the following approach

![256671293-74df6d34-1ac6-4ff6-b613-ae8bc4c2d7aa](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/66481427/5b1ea647-81a5-40b8-bbe4-36fd74ca4197)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do specify which source is this

**Comment by stevenyomi** [comment]
And you can only request multiple languages to be split for one extension per issue.

**Comment by mohamed-magdy26** [comment]
I think you don't get what I mean it's not related to a specific extension or source it's all about sometimes some sources
having what you can see in the screenshot provided and we can't sort them like collecting all these raw together and 
all these English or without anything together so we can multi-select all of the theme

**Comment by stevenyomi** [comment]
That should be an issue of the extension - a source should only have one language, in this case it can be split into a multi-language extension with 2 sources.

If you insist on filtering by chapter title, this issue is tracked in https://github.com/tachiyomiorg/tachiyomi/issues/7925.

**Comment by mohamed-magdy26** [comment]
I can't see that search icon anywhere in my app version of [0.14.6]
well, maybe the following will help more understand what I'm facing here
all that I want to hide is these chpaters that have the word "raw" to be able to select the ones without that word

![source on](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/66481427/5b71b3b2-3e39-4d85-aef2-02ea2f2138e0)

![numbers on](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/66481427/d86674ad-55e3-4802-ba76-856d2ab1c5c8)

**Comment by stevenyomi** [comment]
> I can't see that search icon anywhere in my app version of [0.14.6]

Search by chapter doesn't exist yet. Someone else requested it in https://github.com/tachiyomiorg/tachiyomi/issues/7925. If it is implemented, that issue will be closed.
