### ISSUE TITLE
Baozi Manhua: pages don't load

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#17322]
### Source information

Baozi Manhua 1.4.20

### Source language

中文

### Steps to reproduce

打开任意漫画，随机加载一章节

### Expected behavior

漫画可以正常加载，而非显示无法加载

### Actual behavior

插件内漫画无法加载图片，webview内可以正常加载，使用vpn 也无法加载

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

![Screenshot_2023-07-31-12-46-33-852_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/83eefa91-4419-4dff-bcad-5a8648db26a8)
![Screenshot_2023-07-31-12-41-28-412_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/5ac79c16-9e6c-4c43-b18a-157bb8d13ed2)
和#16568情况不同，现在插件可供选择的6个站点在正常网络情况下都无法加载图片，webview可以正常加载。在使用VPN情况下，前四个站点有cloudfare保护，需要验证，图片也无法正常加载，webview可正常加载。可能是网站修改了图片链接格式，或者加了保护。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by duziliang1989** [comment]
确实，哪位大神给修复一下，拜托了
