### ISSUE TITLE
[Bug] Dilbert : IP ban when downloading year/loading multiple years for the first time

### ISSUE THREAD

**Issue by ardittristan** [tachiyomiorg/tachiyomi-extensions#1733]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: r1531
* Android version: 8.0.0

## Steps to reproduce
1. load multiple years for the first time shortly after eachother. or start downloading all chapters of a single year

### Expected behavior
the year should download/load.

### Actual behavior
after loading a year the download stops after about 50 chapters and the site stops being accessible for the rest of the day from any device on the same ip.

**Comment by jfcaraujo** [comment]
Pretty sure that there is nothing tachiyomi can do, since it's the site that it's ip banning.
My advice is either wait or use a vpn.

**Comment by CarlosEsco** [comment]
Rate limiting should probably be added for this
