### ISSUE TITLE
KomikIndoID URL change

### ISSUE THREAD

**Issue by CharlieRivalno** [tachiyomiorg/tachiyomi-extensions#17331]
### Source information

KomikIndoID 1.4.11

### Source language

Indonesia

### Source new URL

komikindo.pro

### Other details

KomikIndoID change the domain link to komikindo.pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by JosueSosa01** [comment]
.

**Comment by vetleledaal** [comment]
Superseded by #17945
