### ISSUE TITLE
jinman tiantang 

### ISSUE THREAD

**Issue by lxyabc98** [tachiyomiorg/tachiyomi-extensions#17347]
### Source information

jinmantiantang 1.4.38

### Source language

Chinese

### Steps to reproduce

@stevenyomi 
无法自动获取正确的大陆线路

### Expected behavior

https://[jmcomic2.bet](https://jmcomic2.bet/)/ 
发布页为，
 jm-comic1.club
 jm-comic.club
jm-comic2.ark
其中只有第一个可用，后2个我这里目前显示无法访问

### Actual behavior

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/7cec9eab66d12ae063c4a984f075a6329b362c64/src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/JinmantiantangPreferences.kt
https://[stevenyomi.github.io/source-domains/jmcomic.txt](https://stevenyomi.github.io/source-domains/jmcomic.txt)
得到结果为 jm-comic3.art,jm-comic.club,jm-comic2.ark

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
https://stevenyomi.github.io/source-domains/jmcomic.txt 已更新。

每日中午 12:00 左右更新，如果下次更新不及时，可到 https://github.com/stevenyomi/source-domains/issues 反馈。
