### ISSUE TITLE
Peach Scan mudou seu domínio 

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#17340]
### Source information

Peach Scan 1.4.31

### Source language

Português

### Steps to reproduce

Deveria entrar 

### Expected behavior

Deveria entrar nomalmente 

### Actual behavior

Não entra 

### Tachiyomi version

O.14.6

### Android version

Android 11

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the URL change form instead and do inform their new domain and consider writing it in English as not every contributor speaks Portuguese.
