### ISSUE TITLE
swatop

### ISSUE THREAD

**Issue by ahmedezzat69** [tachiyomiorg/tachiyomi-extensions#17342]
### Source information

Mangaswat 1.4.37

### Source language

العربية

### Steps to reproduce

Problem with manga updates

### Expected behavior

These are the latest chapters added to the site
![Screenshot_2023-08-01-12-25-20-068_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/122267012/09ad0976-465f-4a22-b99e-5d8f9ec09380)

### Actual behavior

But the app shows old chapters
![Screenshot_2023-08-01-12-26-36-254_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/122267012/430943ca-45a3-49dc-a97e-29519f049915)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The extension pulls manga from the page linked by the "عرض الكل" button. Sorted by "الافتراضي". They are probably just cached differently.
![Screenshot from 2023-08-05 12-03-29](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/13540478/40670dcf-b433-4d05-b781-4021d88c4c6d)
