### ISSUE TITLE
Add English translations to Newtoki's settings, filters, sorting options, etc.

### ISSUE THREAD

**Issue by iD-666** [tachiyomiorg/tachiyomi-extensions#17351]
### Source name

Newtoki

### Source language

Korean

### Describe your suggested feature

![IMG_20230802_122209](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/139281826/5018096a-e5f0-49e5-8b3c-261745ece494)

If the app language is set to English: all settings, filters, sorting options, etc., will be in English, just like [Strings.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/Strings.kt).

&nbsp;

&nbsp;

For [NewTokiWebtoon.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiWebtoon.kt)

```
"Day of the Week:" // 요일
    Pair("All", "전체"),
    Pair("Monday", "월"),
    Pair("Tuesday", "화"),
    Pair("Wednesday", "수"),
    Pair("Thursday", "목"),
    Pair("Friday", "금"),
    Pair("Saturday", "토"),
    Pair("Sunday", "일"),
    Pair("10 Days", "열흘")

"Initial Consonant:" // 초성
    Pair("All", "전체"),
    Pair("ㄱ", "ㄱ"),
    Pair("ㄴ", "ㄴ"),
    Pair("ㄷ", "ㄷ"),
    Pair("ㄹ", "ㄹ"),
    Pair("ㅁ", "ㅁ"),
    Pair("ㅂ", "ㅂ"),
    Pair("ㅅ", "ㅅ"),
    Pair("ㅇ", "ㅇ"),
    Pair("ㅈ", "ㅈ"),
    Pair("ㅊ", "ㅊ"),
    Pair("ㅋ", "ㅋ"),
    Pair("ㅌ", "ㅌ"),
    Pair("ㅍ", "ㅍ"),
    Pair("ㅎ", "ㅎ"),
    Pair("a-z", "a-z"),
    Pair("0-9", "0-9")

// Should be possible to select multiple genre just like in the site
"Genre:" // 장르
    Pair("All", "전체"),
    Pair("Fantasy", "판타지"),
    Pair("Action", "액션"),
    Pair("Comedy", "개그"),
    Pair("Mystery", "미스터리"),
    Pair("Romance", "로맨스"),
    Pair("Drama", "드라마"),
    Pair("Wuxia", "무협"),
    Pair("Sports", "스포츠"),
    Pair("Slice of Life", "일상"),
    Pair("School", "학원"),
    Pair("Adult", "성인"),
    Pair("Boys' Love / Girls' Love", "BLGL"),
    Pair("Korea", "한국"),
    Pair("China", "중국")

"Sorting" // 정렬
    Pair("Default (Update)", "as_update"), // 기본
    Pair("Popularity", "as_view"), // 인기순
    Pair("Recommendation count", "as_good"), // 추천순
    Pair("Star rating", "as_star"), // 별점순
    Pair("Comment count", "as_comment"), // 댓글순
    Pair("Bookmark count", "as_bookmark") // 북마크순
```

&nbsp;

**[Strings.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/Strings.kt) doesn't seem to work even though the app language is Korean.**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Won't fix - 51f35d8d755b798b7430e3ca42185861ce842ef6
