### ISSUE TITLE
[FR] FuryoSquad

### ISSUE THREAD

**Issue by Cypral** [tachiyomiorg/tachiyomi-extensions#17357]
### Source name

FuryoSquad

### Source language

French

### Source link

https://furyosquad.com/

### Other details

Source closed 2 days ago.

https://twitter.com/FuryoSquad/status/1684987082450845697

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
La source dans Tachiyomi va du coup rester, juste y'aura une update qui pointera vers la nouvelle URL. @Cypral
