### ISSUE TITLE
[FR] FuryoSociety

### ISSUE THREAD

**Issue by Cypral** [tachiyomiorg/tachiyomi-extensions#17358]
### Source name

FuryoSociety

### Source link

https://furyosociety.com/

### Source language

French

### Other details

New team continuing the legacy of the now dead FuryoSquad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hasanpasha** [comment]
I don't like furries.

**Comment by KirinRaikage** [comment]
Did the website change a lot? I didn't know the old website but it seems like it's using the same CSS selectors etc so maybe it could be only a URL change to do in the code.

**Comment by Pestenxir** [comment]
> Did the website change a lot? I didn't know the old website but it seems like it's using the same CSS selectors etc so maybe it could be only a URL change to do in the code.

No nothing change on the website
