### ISSUE TITLE
Some chapters are removed

### ISSUE THREAD

**Issue by MaksNPC** [tachiyomiorg/tachiyomi-extensions#17363]
### Source information

I don't know what to write here sorry

### Source language

Russian

### Steps to reproduce

Some downloaded chapters are deleted after clearing the cache using the native Xiaomi app

### Expected behavior

I don't know what to write here sorry

### Actual behavior

I don't know what to write here sorry

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

I don't know what to write here sorry

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do provide the requested information.

**Comment by MaksNPC** [comment]
It is possible for more details or an article with training for people who do not know
