### ISSUE TITLE
wnacg 網址已被更換

### ISSUE THREAD

**Issue by jay02105** [tachiyomiorg/tachiyomi-extensions#17360]
### Source information

WNACG 1.4.14

### Source language

中文

### Source new URL

https://www.htmanga9.top/ 

### Other details

如果上面htmanga9無法使用，下面的網址也可以使用
https://www.htmanga7.top/
https://www.htmanga5.top/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
在插件设置里面可以直接更换。
