### ISSUE TITLE
WNACG 網址無效

### ISSUE THREAD

**Issue by jay02105** [tachiyomiorg/tachiyomi-extensions#17362]
### Source name

WNACG 

### Source language

中文

### Source link

https://www.htmanga6.top/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
在插件设置里面可以直接更换。
