### ISSUE TITLE
Cloudflare blocked

### ISSUE THREAD

**Issue by Lucie0712** [tachiyomiorg/tachiyomi-extensions#17372]
### Source information

Nhentai.net

### Source language

English

### Steps to reproduce

1.open nhentai
2.unable to bypass cloudlare
3.open webview
4.do verification

### Expected behavior

Verification success and can use extension again

### Actual behavior

Consistent verification failure

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

I've already cleared cache and webview, changed my user agent string, but nothing helped.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by iD-666** [comment]
It works fine for me. If you can open it in your browser, go to [ipleak.net](https://ipleak.net) and then copy your user agent. Use that as your Tachiyomi's user agent.

**Comment by alessandrojean** [comment]
> I have tried the troubleshooting guide.

As the guide states, if nothing works, migrate to other sources or wait until they lower their protection.
