### ISSUE TITLE
[EN] Peace Scans

### ISSUE THREAD

**Issue by lord-ne** [tachiyomiorg/tachiyomi-extensions#17371]
### Source name

Peace Scans

### Source link

https://peacescans.com/

### Source language

English

### Other details

Contains SFW and NSFW series.

I'll probably implement this myself in a few days, but I wanted to open an issue first so someone can point out if this website can already be covered by an existing multisource.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site says: Invalid SSL certificate Error code 526
