### ISSUE TITLE
Voyce.Me: Bad JSON parsing

### ISSUE THREAD

**Issue by harukenji** [tachiyomiorg/tachiyomi-extensions#17404]
### Source information

Voyce 1.4.2

### Source language

English

### Steps to reproduce

1.Browse any manhwa in voyce source.
2.Try to read any chapter.
3.The chapter won't open or load due to extension issue.

### Expected behavior

Should be able to read any titles from the voyce source

### Actual behavior

Throwing errors
![Screenshot_20230806_060922_TachiyomiSY](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75812645/97c1f78d-3913-4145-a002-80a86aec7243)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Needs investigation, but last time I checked it was actually an issue with their API. Will double check.
