### ISSUE TITLE
Hentaivn new extension doesn't work

### ISSUE THREAD

**Issue by leonminus** [tachiyomiorg/tachiyomi-extensions#17415]
### Source information

HentaiVN 1.4.28

### Source language

Vietnamese

### Steps to reproduce

On library 

### Expected behavior

Show and able to read h manga

### Actual behavior

Dont load manga

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

Web still have a strange protection, but new version of this extension cant load and read the manga
In 1.4.26, i still can see the manga at library and cant read 8))

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Turn on random UA in extension settings.

**Comment by vetleledaal** [comment]
> ### Source information
> 
> HentaiVN 1.4.28

Also update to 1.4.29
