### ISSUE TITLE
Hentaivn not show manga with UA changed

### ISSUE THREAD

**Issue by leonminus** [tachiyomiorg/tachiyomi-extensions#17419]
### Source information

HentaiVN 1.4.29

### Source language

Vietnamese

### Steps to reproduce

Changed ua in extension settings and even in app's advanced settings

### Expected behavior

Read manga

### Actual behavior

The manga now dont even show up

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

I used vpn too, but it doesnt work
My agent (hope this ok to post):
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
You should try using desktop user agents since that's what the extension was designed to parse.

**Comment by dejavui** [comment]
@leonminus I see the UA library has a problem with ext ¯\_(ツ)_/¯  More features add bug. You can use the apk temporary, I delete  UA library. While waiting for the bug to be fixed ^^
[tachiyomi-vi.hentaivn-v1.4.29.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12274341/tachiyomi-vi.hentaivn-v1.4.29.zip)
