### ISSUE TITLE
Nhentai rip

### ISSUE THREAD

**Issue by Siomairhysss** [tachiyomiorg/tachiyomi-extensions#17417]
### Source information

Nhentai 1.4.39

### Source language

All

### Steps to reproduce

I can't get any site updates through the extension 

### Expected behavior

the extension should pop up doujins

### Actual behavior

Doesn't pop up anything 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

that's all thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the requested information correctly, including any errors you're getting. Assuming by the source, you might be having some Cloudflare issues, so try the troubleshooting guide linked in the acknowledgements section you checked as well.

**Comment by QWERTIOX** [comment]
It's [cloudflare issue](https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues), there is nothing much that tachiyomi can do. Try using not official nhentai

**Comment by duziliang1989** [comment]
may be it can be solved by using a new site as like: https://nhentai.wtf/
