### ISSUE TITLE
[Toonily] Incorrect (double) page count leading to failed downloads

### ISSUE THREAD

**Issue by VisionProlonged** [tachiyomiorg/tachiyomi-extensions#17411]
### Source information

Toonily 1.4.42

### Source language

English

### Steps to reproduce

1.Attempt to browse or download the affected chapters.
2. Twice the page count in shown when viewing and downloading. (checked through a browser which shows the same "ending page" for each chapter)

Problematic pages: (all links are NSFW)
1. Dance Department’s Female Sunbaes 
 - [Chapter 36](https://toonily.com/webtoon/dance-departments-female-sunbaes/chapter-36/) | Actual - 12, Shown - 24
 - [Chapter 40](https://toonily.com/webtoon/dance-departments-female-sunbaes/chapter-40/) | Actual - 8, Shown - 16  
2. Is This The Way You Do It?
 - [Chapter 17](https://toonily.com/webtoon/is-this-the-way-you-do-it/chapter-17/) | Actual - 12, Shown - 24
3. The Hole is Open 
 - [Chapter 20](https://toonily.com/webtoon/the-hole-is-open/chapter-20/) | Actual - 7, Shown - 14

In the last one "The hole is open" the download was left running for a while and it shows downloaded 13/14  and downloads  invalid .jpg files of 355B each for the pages 08-13.
 The last correct download is 007.jpg (the actual ending page)

Also there are quiet a few number of chapters across various titles with the same issue, this list is not exhaustive. 

### Expected behavior

The correct page numbers are shown and downloads complete when all pages are downloaded.

### Actual behavior

Because the page count is messed up downloads do not complete and are left in queue. 
The correct no of  pages are downloaded and then it waits for non existent pages to download

### Tachiyomi version

0.14.6

### Android version

Android 13.1

### Other details

Nothing really, great issue template!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
It's a site issue, they have broken image links mixed in. 
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48650614/d79e8b03-d143-4bc3-9acd-1efa42de3a7a)
