### ISSUE TITLE
hentaifox 1.4.4

### ISSUE THREAD

**Issue by duziliang1989** [tachiyomiorg/tachiyomi-extensions#17421]
### Source information

hentaifox 1.4.4

### Source language

English

### Source new URL

https://hentaifox.cc/

### Other details

a much better site，more stable. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Superseded by #17442
