### ISSUE TITLE
DoujinDesu

### ISSUE THREAD

**Issue by niveanyctra** [tachiyomiorg/tachiyomi-extensions#17424]
### Source information

DoujinDesu 1.4.4 (Indonesia)

### Source language

Indonesia

### Source new URL

doujindesu.tv

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Kinatzu123** [comment]
> 

H

**Comment by TheKingTermux** [comment]
**This Issue Can Be Closed Now**

This issue has been fixed in #17429
