### ISSUE TITLE
Request searching "Posts" Feature

### ISSUE THREAD

**Issue by Kimphunh** [tachiyomiorg/tachiyomi-extensions#17426]
### Source name

Kemono

### Source language

Multi

### Describe your suggested feature

It makes it possible for readers to search Posts of any Artist

### Other details

There should be 2 search options, search for artists, or search for posts

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Not possible as the posts are considered a chapter, and the app doesn't support a search for chapters. Also making each post a separate entry would be a mess.
