### ISSUE TITLE
NHentai 1.4.39

### ISSUE THREAD

**Issue by duziliang1989** [tachiyomiorg/tachiyomi-extensions#17422]
### Source information

NHentai 1.4.39

### Source language

English

### Source new URL

https://nhentai.wtf/

### Other details

a much better site，more stable. an easier way to solve the problem of cloudflare or something else.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Not affiliated with nhentai.net. Open a source request for the whole cohort: 8muses.uk, 9hentai.uk, 9hentai.us, doujin.uk, doujindesu.uk, doujins.cc, doujins.uk, doujinshi.uk, ehentai.uk, hentai-hentai-hentai.com, hentai2read.xyz, hentaifox.cc, hitomi.vip, hitomila.xyz, nhentai.cam, nhentai.guru, nhentai.jp.net, nhentai.uk, nhentai.world, nhentai.wtf, porncomics.uk
