### ISSUE TITLE
Olympus Scanlation: Changed their domain

### ISSUE THREAD

**Issue by Unknoweird** [tachiyomiorg/tachiyomi-extensions#17431]
### Source information

Olympus Scanlation 1.4.3

### Source language

Spanish

### Source new URL

https://olympusv2.gg/

### Other details

Esto pasa muy seguido?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by ElAguZWe** [comment]
No, no pasa muy seguido, revisa el discord de Olympus Scans, de la nada cambiaron el url otra vez.

**Comment by Unknoweird** [comment]
No pensé que me responderían. Gracias y si me di cuenta, nomás que pasó muy
de repente de nuevo jaja

**Comment by ElAguZWe** [comment]
No pasa nada bro, toca esperar a que actualicen o reemplacen la extensión no más, si supiera como se hace haría mi aporte...
