### ISSUE TITLE
No puedo entrar a olympus

### ISSUE THREAD

**Issue by Striven100** [tachiyomiorg/tachiyomi-extensions#17435]
### Source information

Olympus Scan

### Source language

Españom

### Steps to reproduce

No puedo entrar a los cap o a la fuente

### Expected behavior

Deberia poder, no hice ningun cambio

### Actual behavior

![Screenshot_20230807-152028_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/138946506/44a85088-abf1-4972-9749-2220c5c51368)
![Screenshot_20230807-152022_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/138946506/64d1e01a-9aa9-46db-bfcc-72755d5b7c3d)

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#17431
