### ISSUE TITLE
Manga Oni no carga correctamente

### ISSUE THREAD

**Issue by Striven100** [tachiyomiorg/tachiyomi-extensions#17440]
### Source information

manga-oni.com

### Source language

Español

### Steps to reproduce

No cargan los mangas, y tampoco la busqueda.

### Expected behavior

Hasta ahora funcionaba bien, no se cuando dejo de funcionar

### Actual behavior

![Screenshot_20230808-120917_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/138946506/5d265f1a-3d5d-415a-97ba-ba1221ee5819)
![Screenshot_20230808-120817_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/138946506/faaf2b14-4739-4f9a-8e3d-bec9814addf6)

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
La página esta caída
