### ISSUE TITLE
Ozul scans: domain changed 

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#17448]
### Source information

Ozul scans 1.4.26

### Source language

Arabic

### Source new URL

https://ozulmanga.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by HisuianZoroark69** [comment]
All features are working normally without changing the domain since the server redirects automatically. I don't see the need to change it.
