### ISSUE TITLE
Mangareader no results found 

### ISSUE THREAD

**Issue by Cac0ph0ny** [tachiyomiorg/tachiyomi-extensions#17449]
### Source information

Mangareader 1.4.4

### Source language

English 

### Steps to reproduce

Step 1: Open Mangareader English source
Step 2: Shows "no results found"

### Expected behavior

Show the manga available on the Mangareader site

### Actual behavior

Shows "no results found", not showing any manga at all
![Screenshot_20230808-224639_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/62515652/233f8c6f-74b0-4539-bf62-798b5486a1d5)

### Tachiyomi version

0.14.6

### Android version

Android 9

### Other details

Webview loads the site as normal
![Screenshot_20230808-224221_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/62515652/abdb6b90-9b90-4474-91e9-457d219fd1a6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
working fine
cant reproduce
