### ISSUE TITLE
MangaDex v1.4.186 : Searching with list i.d. does not return pornographic enteries

### ISSUE THREAD

**Issue by garvongithub** [tachiyomiorg/tachiyomi-extensions#17456]
### Source information

MangaDex v1.4.186

### Source language

Multi

### Steps to reproduce

1. Make a list with Pornographic rated entries
2. Search with list i.d.
 For example: For this [list](https://mangadex.org/list/1ba2f365-3cf3-445e-ab34-621d4ef15e75/trying?tab=titles) the search term would be list:1ba2f365-3cf3-445e-ab34-621d4ef15e75

### Expected behavior

The search should return all enteries in the list.

### Actual behavior

The search returns all entries except pornographic rated entries, even when in the extensions settings the content filter option is turned on for pornographic rating.

### Tachiyomi version

0.14.6

### Android version

13

### Other details

The above list contains 1 Pornographic entry. Neko returns all enteries.
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/77321589/79944bad-d183-435a-a1e0-daf31d775110)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/77321589/e6f377cc-bcd4-4a80-a370-df7ab79cd3e8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Probably related to a missing `contentRating[]` query parameter in the `searchMangaListParse` method.

Adding the code below should fix it.

```kotlin
url.addQueryParameter("contentRating[]", MDConstants.allContentRatings)
```
