### ISSUE TITLE
Peach Scan: Changed their domain and theme

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#17453]
### Source information

Peach Scan 1.4.31

### Source language

Português

### Steps to reproduce

appears check the site in the webview

### Expected behavior

should normally enter the extension

### Actual behavior

HTTP error

### Tachiyomi version

O.14.6

### Android version

Android 11

### Other details

the domain has been changed to: https://peachscan.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please use the URL change report next time.
