### ISSUE TITLE
Ninja Scan: Changed their domain

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#17454]
### Source information

Ninja Scan 1.4.32

### Source language

Português

### Steps to reproduce

![Screenshot_20230809-105721035](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90201611/9f3dccb0-a1bb-4f93-85aa-1d232c990e62)

### Expected behavior

should normally enter the extension

### Actual behavior

does not enter because the domain has changed

### Tachiyomi version

O.14.6

### Android version

Android 11

### Other details

domain changed to:https://ninjascan.site/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please use the correct issue forms next time.
