### ISSUE TITLE
Teamx domain changed

### ISSUE THREAD

**Issue by Ammaralkaaki** [tachiyomiorg/tachiyomi-extensions#17468]
### Source information

Team x 1.4.11

### Source language

Arabic

### Source new URL

https://teamxnovel.com/

### Other details

The domain changed from https://team1x1.fun/
To 
https://teamxnovel.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by ALKIFY** [comment]
> ### مصدر معلومات
> فريق x 1.4.11
> 
> ### لغة المصدر
> عربي
> 
> ### مصدر URL جديد
> https://teamxnovel.com/
> 
> ### تفاصيل أخرى
> تم تغيير النطاق من https://team1x1.fun/ إلى https://teamxnovel.com/
> 
> ### شكر وتقدير
> * [x] لقد بحثت في المشكلات الحالية وهذه بطاقة جديدة **وليست** مكررة أو متعلقة بقضية أخرى مفتوحة أو مغلقة.
> * [x] لقد كتبت عنوانًا قصيرًا ولكنه غني بالمعلومات.
> * [x] لقد قمت بتحديث جميع الملحقات المثبتة.
> * [x] لقد فتحت WebView وتحققت من أن عنوان URL المصدر لم يتم تحديثه بعد.
> * [x] سأقوم بملء جميع المعلومات المطلوبة في هذا النموذج.

منتظرين التحديث الجديد
