### ISSUE TITLE
Can't read anything Japscan

### ISSUE THREAD

**Issue by Mousssous** [tachiyomiorg/tachiyomi-extensions#17478]
### Source information

Japscan 1.4.43

### Source language

"French"

### Steps to reproduce

1. Click on Japscan source or make a global search
2. Select a manga/webtoon/manhwa (no matter which one)
3. Click on a chapter of the selected manga

### Expected behavior

The manga's chapter images should appear

### Actual behavior

Error : "Attendait 2 chaines de recherche dans ZJS, en a trouvé 88"
And brought me back to chapter selection

### Tachiyomi version

"0.14.6"

### Android version

"Android 10"

### Other details

This type of error already happened several times and has already been fixed, apparently it's a lookup tables problem. The number of "zjs" found may change depending on the manga selected. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Okay, now we're starting to hit a rock where Japscan, despite all our efforts, is fixed, broken, fixed, broken again.
We're playing a really annoying game where Japscan keeps breaking the extension on purpose. 
I would personally remove the extension.
WDYT?

**Comment by aboudiom59** [comment]
> Okay, now we're starting to hit a rock where Japscan, despite all our efforts, is fixed, broken, fixed, broken again. We're playing a really annoying game where Japscan keeps breaking the extension on purpose. I would personally remove the extension. WDYT?

Well Japscan is the french source with the most content, like by far, there is a lot of content there that isn't anywhere else, sushi-scan is a better site but it's not even touching the sheer content there. But honestly if they're just gonna purposefully break the extension for traffic they're not gonna get anyway maybe it's just better to give up and leave it alone. It'd be a shame but unless the site actually comes to some sort of agreement maybe it's not worth the effort.
