### ISSUE TITLE
Add an Override BaseUrl option to team x

### ISSUE THREAD

**Issue by Bmswad1** [tachiyomiorg/tachiyomi-extensions#17484]
### Source name

Team X

### Source language

العربية

### Describe your suggested feature

when the domain name changes [this happens frequently], we can use this option temporarily until extension is updated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> this happens frequently

I don't think so. The current outdated domain was available since November 2022.
