### ISSUE TITLE
Mixed Manga: error while downloading

### ISSUE THREAD

**Issue by fourquestionmarksokay** [tachiyomiorg/tachiyomi-extensions#17487]
### Source information

Mixed Manga 1.4.32

### Source language

English

### Steps to reproduce

Open any title and try to download a chapter.

### Expected behavior

The download should complete successfully.

### Actual behavior

An error occured that says "Expected URL scheme 'http' and 'https' but no scheme was found for "

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Note the space after 'for' which probably means that the source used `img` links that looks like `//cdn.example.net/test.img`), which works on browsers normally (as they will automatically assume that's https) but is *probably* unaccounted for here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
redirect to existing ext LikeManga
