### ISSUE TITLE
Manwa page not found issue

### ISSUE THREAD

**Issue by Mcforwin** [tachiyomiorg/tachiyomi-extensions#17502]
### Source information

Manwa 1.4.2

### Source language

Chinese

### Steps to reproduce

1. Open any manga chapter on manwa will return a no page found error.
2. However, opening the webview will have a normal behaviour to go to the manga page to allow you to select the chapter to view via webpage.

### Expected behavior

Pages should loud automatically on manwa instead of returning no page found error.

### Actual behavior

No page found on opening any chapter on manwa

### Tachiyomi version

0.14.6

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rebeccafeng1995** [comment]
I have this issue as well since yesterday. Clearing cookie, chnaging source of image, or restarting the app does not work to fix this issue.

**Comment by Mcforwin** [comment]
The same issues remains persistent. Hopefully someone can fix it.

**Comment by rebeccafeng1995** [comment]
文件分享取消了，不过没事，没那么着急，坐等更新

**Comment by lingwunb666** [comment]
> 文件分享取消了，不过没事，没那么着急，坐等更新

有大佬给了我一种新的解决方案，明天我测试下

**Comment by Mcforwin** [comment]
> > 文件分享取消了，不过没事，没那么着急，坐等更新
> 
> 有大佬给了我一种新的解决方案，明天我测试下

问题解决了！感恩！
