### ISSUE TITLE
Dead source  mangaarbteam

### ISSUE THREAD

**Issue by urekxmazino** [tachiyomiorg/tachiyomi-extensions#17500]
### Source name

mangaarbteam.com

### Source language

Arabic 

### Source link

https://mangaarbteam.com/

### Other details

website is dead and showing  ERR_NAME_NOT_RESOLVED

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
I'll suggest making one issue for all the sites together
