### ISSUE TITLE
Yugen Mangas (Spanish): Changed their domain

### ISSUE THREAD

**Issue by Autovot** [tachiyomiorg/tachiyomi-extensions#17511]
### Source information

Yugenmanga 1.4.22

### Source language

Español, (Spanish)

### Source new URL

https://yugenmangas.lat

### Other details

Checked webview
![Screenshot_20230813-020517-017](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/87210193/6d1e699a-0900-462a-a4ee-c938d663147f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The site seems to be very broken at the moment, will need to wait some time before they fix to update the extension.
