### ISSUE TITLE
Qmanga5.net had been changed to Qmanga8.com

### ISSUE THREAD

**Issue by Kimphunh** [tachiyomiorg/tachiyomi-extensions#17517]
### Source information

Qmanga5.net

### Source language

Vietnamese

### Source new URL

Qmanga8.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Kimphunh** [comment]
What the heck man? It not a "new request for add a new source" it is "url changed"
Pls reopen it!?!

**Comment by MikeZeDev** [comment]
> What the heck man? It not a "new request for add a new source" it is "url changed"
> Pls reopen it!?!

Its a bot. Sometimes bots make mistakes
