### ISSUE TITLE
Japscan cloudflare

### ISSUE THREAD

**Issue by Freedent-72** [tachiyomiorg/tachiyomi-extensions#17529]
### Source information

Japscan 1.4.43

### Source language

Français 

### Steps to reproduce

Ouvrir un scan
Attendre

### Expected behavior

Nous devrions pouvoir lire le manga via l'application.

### Actual behavior

Impossible de lire le manga via l'application et le web view fonctionne une fois sur 2.
Message d'erreur non habituel quand le cloudflare bloque.

### Tachiyomi version

App version: 0.14.6

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As the troubleshooting guide states in the Cloudflare section, if none of the steps works, migrate or wait until the source lowers their protection.
