### ISSUE TITLE
Unofficial sources did not appear after the last update

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#17541]
### Source information

MangaStrom 1.3.6

### Source language

Arabic

### Steps to reproduce

Entering the list of sources, this source did not appear, knowing the previous updates. It used to appear. I worked hard on it to add it. I modified the old mangalink source that was deleted from Qiomi, but now it no longer appears. Why what is the problem?
![Screenshot_20230814184237](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/87826849/536adc59-63a8-40e0-8d98-8cc19e181b19)

![Screenshot_٢٠٢٣٠٨١٤-١٨٤٨٤٨](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/87826849/93905b5c-36d8-4640-a1b4-1e8bb5e759c8)

### Expected behavior

The source should appear after the last update. I do not want to go back to the old update. Please solve the problem, if possible

### Actual behavior

This is the source, my file has disappeared and no longer appears. I have modified an old version of Mangalinek 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

@arkon @alessandrojean 
MangaLink is back as mangastrom

https://mangastorm.org/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Also the app doesn't support 1.3 extensions anymore. Don't use obsolete extensions as they cause issues in the app. It's working as expected by not showing it.
