### ISSUE TITLE
1st kiss change to likemanga.io

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#17544]
### Source information

1st Kiss 1.4.40

### Source language

English

### Source new URL

https://likemanga.io

### Other details

Announcement in their website 

![Screenshot_2023-08-15-15-28-47-952_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/53214405/73a4e79a-1d82-45b2-a55b-53d0d4a76531)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
this is not a simple domain change, the extension will need to be rewritten from scratch. Should convert this to  `Source Request`
