### ISSUE TITLE
asura scans not loading/downloading

### ISSUE THREAD

**Issue by Turhvjbufv** [tachiyomiorg/tachiyomi-extensions#17567]
### Source information

asura scans 1.4.51

### Source language

English 

### Steps to reproduce

Open any manhwa in asura scans and try to download/view any chapter

### Expected behavior

Should download/show the chapter 

### Actual behavior

Doesn't download/shows this image could not be loaded" 

### Tachiyomi version

tachiyomi sy r528

### Android version

Android 12 

### Other details

Not tachiyomisy specific problem. Other people also have this problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Site issue, it's broken on their end.
