### ISSUE TITLE
Tencent Comics is crashed.

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#17563]
### Source information

Tencent Comics 1.4.6

### Source language

中文(Chinese)

### Steps to reproduce

Unable to load content and read comics

### Expected behavior

No

### Actual behavior

No

### Tachiyomi version

0.14.6

### Android version

Andriod 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do provide the requested information and any error messages you're getting. This is very vague and doesn't help into solving the issue.

**Comment by Clouddark75** [comment]
If you're using a Mobile user agent you will get an error to fetch or read anything because the page did some changes, it works fine if you use a user agent for Desktop, on Tachi.

**Comment by Clouddark75** [comment]
So, the extension will need an update to handle the changes or you can use a Desktop user agent for the time being, it probably will get you problems with extensions that are coded for mobile mode and have a Desktop and mobile experience with too many changes with their selectors (keep that in mind).
