### ISSUE TITLE
Failed Downloads

### ISSUE THREAD

**Issue by 20Navi03** [tachiyomiorg/tachiyomi-extensions#17576]
### Source information

MangaDex 1.4.187

### Source language

English 

### Steps to reproduce

I tried get the new chapters of the series I am reading
Then the app notifies me of an error
It says to many request of actualization
On the website says that maybe my ip is banned

### Expected behavior

The new should have been delivered like for otehr sources

### Actual behavior

It doesnt happen like already mentioned

### Tachiyomi version

0.14.6

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> On the website says that maybe my ip is banned

No, you're not. Could you show a screenshot of the error you see?

> I tried get the new chapters of the series I am reading

Could you give an example? 
What manga/chapter are you trying to read

In addition, try the following:
Turn on Data Saver in extension settings (Browse > Extensions > MangaDex > Settings > English/Language > ⚙️ > Data Saver)
Then clear cache/database to clear up older links (More > Settings > Advanced > Clear Cache/Database (for mangadex)
And then try reading the same chapter again

**Comment by 20Navi03** [comment]
Here is the error that happensAlso, maybe i explained badly but the issue is when i try to update this error happens, it only happens on this extension.Enviado desde mi Galaxy
-------- Mensaje original --------De: nicki ***@***.***> Fecha: 17/8/23  19:21  (GMT+01:00) Para: tachiyomiorg/tachiyomi-extensions ***@***.***> Cc: 20Navi03 ***@***.***>, Author ***@***.***> Asunto: Re: [tachiyomiorg/tachiyomi-extensions] Failed Downloads (Issue #17576) 

On the website says that maybe my ip is banned

No, you're not. Could you show a screenshot of the error you see?

I tried get the new chapters of the series I am reading

Could you give an example?
What manga/chapter are you trying to read
In addition, try the following:
Turn on Data Saver in extension settings (Browse > Extensions > MangaDex > Settings > English/Language > ⚙️ > Data Saver)
Then clear cache/database to clear up older links (More > Settings > Advanced > Clear Cache/Database (for mangadex)
And then try reading the same chapter again

**Comment by BraveDude8** [comment]
>  On the website says that maybe my ip is banned

Can you take a screenshot of where you're seeing this IP ban message, and post it here please?

**Comment by 20Navi03** [comment]
I wasn't send a message of ip ban it was said on the help site that is linked on the imaged i was sent in the section of the problem i was having.Enviado desde mi Galaxy
-------- Mensaje original --------De: BraveDude8 ***@***.***> Fecha: 17/8/23  20:04  (GMT+01:00) Para: tachiyomiorg/tachiyomi-extensions ***@***.***> Cc: 20Navi03 ***@***.***>, Author ***@***.***> Asunto: Re: [tachiyomiorg/tachiyomi-extensions] Failed Downloads (Issue #17576) 

On the website says that maybe my ip is banned

Can you take a screenshot of where you're seeing this IP ban message, and post it here please?

**Comment by alessandrojean** [comment]
Please do reply in GitHub directly and not by email, so you can attach the screenshots.

**Comment by vetleledaal** [comment]
No response, closing as can't repro
