### ISSUE TITLE
MangaDex: Change capitalization of the genres

### ISSUE THREAD

**Issue by anonymous5555522222** [tachiyomiorg/tachiyomi-extensions#17570]
### Source information

MangaDex 1.4.187

### Source language

English

### Steps to reproduce

Add any new manga entry to your library.

### Expected behavior

Tag would display as "Slice of Life".

### Actual behavior

Tag displays as "Slice of life" instead.

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

Most people probably do not care, but with the last update, only the first letter in a tag gets capitalized. Previously, tags looked much better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Isn't a bug, could have opened a feature request to change the capitalization instead.

**Comment by anonymous5555522222** [comment]
> Isn't a bug, could have opened a feature request to change the capitalization instead.

Sorry about that. But I just wanted to point out that this is not exclusive to the "Slice of Life" tag. For example, "Traditional Games" shows up as "Traditional games" now, and any other tag with more than one word.

**Comment by alessandrojean** [comment]
I will change it again to match how the website shows it, at least in English.
