### ISSUE TITLE
mgkomik/cosmicscan: Issue doesn't open comic

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi-extensions#17582]
### Source information

comisscan.id  1.4.27
mg komik 1.4.36
### Source language

Id

### Steps to reproduce

Doesn't open comic and web mode Webview aman
Already using DNS still doesn't open 

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

Last

### Android version

Android 11

### Other details

![Screenshot_2023-08-18-11-57-25-87_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100791931/3cbbf283-7622-47e5-82ce-601de0636472)
![Screenshot_2023-08-19-18-38-46-89_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100791931/84ba1437-076a-48bd-a53b-865f0805ab8b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source. And also about Cloudflare, refer to the "Solving Cloudflare issues" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.

**Comment by mozzaru** [comment]
@alessandrojean 
I saw that on the mg comic site, change the domain to https://mgkomik.id/
Whether it will penetrate or not, I don't know
