### ISSUE TITLE
MangaSwat has new bypass cloudflare

### ISSUE THREAD

**Issue by YYSS15** [tachiyomiorg/tachiyomi-extensions#17598]
### Source information

MangaSwat 1.4.37

### Source language

Arabic 

### Steps to reproduce

When I open the extension take a few seconds and show me this error 
![Screenshot_20230819-181131](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132961602/947501e2-1c5d-408c-930e-ae6d89f1711d)
``

### Expected behavior

This shouldn't be happen 

### Actual behavior

This happened every time I enter or update this extension 

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the Cloudflare section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) guide. As stated there, if nothing works, migrate to other sources or wait until they lower their protection.
