### ISSUE TITLE
Team X: The image couldn't be loaded

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi-extensions#17595]
### Source information

Team X 1.4.12

### Source language

Arabic

### Steps to reproduce

Intermittent image issue from the extension , where Tachyomi downloads the chapter piece by piece
![Screenshot_2023-08-19-11-17-01-413_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/102795903/8d1fb5f1-73b3-4e39-9dd2-f5c2d1e6eb71)
![IMG_20230819_112447](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/102795903/1367137b-6bb6-4413-8bb1-551dde6c4cac)

### Expected behavior

A long one piece chapter ( webtoon ) 

### Actual behavior

Tachyomi downloads the chapter piece by piece

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please provide additional information, such as which manga and chapter this is.

**Comment by Akashi123-deep** [comment]
> Please provide additional information, such as which manga and chapter this is.

Apotheses last chapter, the problem isn't image couldn't load it load but it like fragmented

**Comment by alessandrojean** [comment]
The site itself divides the images, so it's expected they are downloaded as pages, there's nothing wrong in this point. The only error is the one present in your screenshot.

**Comment by Akashi123-deep** [comment]
> 
So what the solution of this , can someone add feature to avoid this

**Comment by Akashi123-deep** [comment]
> The site itself divides the images, so it's expected they are downloaded as pages, there's nothing wrong in this point. The only error is the one present in your screenshot.

So what the solution of this , can someone add feature to avoid this

**Comment by AntsyLich** [comment]
Did you try clicking retry as I suggested?

**Comment by Akashi123-deep** [comment]
> Did you try clicking retry as I suggested?

That first thing I did before came here
