### ISSUE TITLE
manhuagui "Source not installed", even though it is installed

### ISSUE THREAD

**Issue by CometstarMH** [tachiyomiorg/tachiyomi-extensions#17609]
### Source information

manhuagui 1.4.16

### Source language

Chinese (zh)

### Steps to reproduce

1. Open any manga chapter from this source

### Expected behavior

Start reading the chapter 

### Actual behavior

Show the message "Source not installed"

### Tachiyomi version

r6019, r6011

### Android version

Android 13

### Other details

I tried reinstalling the extension, from both inside the app and https://tachiyomi.org/extensions/, and I can see the extension app in the system Apps list. But it seems Tachiyomi cannot detect the extension. The extension list inside the app always show the extension as uninstalled ("Install" button is shown). All the other extensions are ok.
It works on stable version 0.14.6 though. It can detect this and all the other, so I think this issue is specific to this extension with preview version Tachiyomi?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by deadblue0910** [comment]
I have same question in TachiyomiSY Preview build: 528,and it’s normal in TachiJ2K v1.6.6

**Comment by CometstarMH** [comment]
seems this is duplicated by tachiyomiorg/tachiyomi#9915 and fixed in tachiyomiorg/tachiyomi-extensions@3a409ba93af516b36427dcaf7ab0ffd2fb52b059 in the app repository
the new version is 1.4.17, but manga now need to be migrated to the "new" source
