### ISSUE TITLE
Change link

### ISSUE THREAD

**Issue by slimessan** [tachiyomiorg/tachiyomi-extensions#17605]
### Source name

For all extensions 

### Source language

Arabic

### Describe your suggested feature

Please add the option to modify the link in the list inside the red circle in photo

![Screenshot_20230820_005529](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/127403390/29b90666-4523-466e-a586-c9cee53ef99c)
If the image does not appear, a circle surrounds the list from within the manga page that contains:edit categories,  migrate,  share 

### Other details

Sometimes when the website link is changed,I have to delete my manga list and then add it again. This feature, which allows changing the manga link directly, will make it much easier for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This is not a feature extensions can provide. [tachiyomiorg/tachiyomi](https://github.com/tachiyomiorg/tachiyomi/) would be the correct repo.


> Sometimes when the website link is changed,I have to delete my manga list and then add it again.

You can migrate manga instead, see [Migrating on Stable/Preview](https://tachiyomi.org/help/guides/source-migration/#migrating-on-stable-preview)

**Comment by slimessan** [comment]
> This is not a feature extensions can provide. [tachiyomiorg/tachiyomi](https://github.com/tachiyomiorg/tachiyomi/) would be the correct repo.
> 
> 
> > Sometimes when the website link is changed,I have to delete my manga list and then add it again.
> 
> You can migrate manga instead, see [Migrating on Stable/Preview](https://tachiyomi.org/help/guides/source-migration/#migrating-on-stable-preview)

Why its same website and Same programming ?

**Comment by Clouddark75** [comment]
Migrating to the same source or another is your best option, it should maintain your your history and downloads (if any).

**Comment by slimessan** [comment]
> Migrating to the same source or another is your best option, it should maintain your your history and downloads (if any). 

Unfortunately, there is only one Arabic site that translates it,Thanks for the speed of support
