### ISSUE TITLE
swatmanga

### ISSUE THREAD

**Issue by slimessan** [tachiyomiorg/tachiyomi-extensions#17600]
### Source information

https://swatop.club/

### Source language

Arabic

### Steps to reproduce

Bypass

### Expected behavior

Cloudflare 

### Actual behavior

Bypass cloudflare 

### Tachiyomi version

0.14.6

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the Cloudflare section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) guide. As stated there, if nothing works, migrate to other sources or wait until they lower their protection.

Also please do fill the requested information appropriately next time.
