### ISSUE TITLE
readkomik extension not working for tensura 107+

### ISSUE THREAD

**Issue by KnawKx** [tachiyomiorg/tachiyomi-extensions#17607]
### Source information

Readkomik 1.4.27

### Source language

English

### Steps to reproduce

try to read any tensura chapter after kmanga took over

### Expected behavior

should load normally and be able to download

### Actual behavior

when try to read normally nothing loads just blank pages
when try to download the chapter it errors
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/63046682/b1606727-c5c3-4289-81cf-8573eef94520)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/63046682/db8e833a-a3ec-4c9c-b46d-601c692c6ce8)

### Tachiyomi version

i use tachiyomi fork for windows Suwayomi/Tachidesk-Server 0.7.0

### Android version

i use tachiyomi fork for windows

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#16459 probably, but looking at the website, the images are messed up and it has a general comment of `If the image is error, please change to server 2 (Go to the top then change to Default 2), if still error', use vpn`
