### ISSUE TITLE
Fr-Scan (Madara) the search does not work

### ISSUE THREAD

**Issue by pixelroll** [tachiyomiorg/tachiyomi-extensions#17619]
### Source information

fr.frdashscan 1.4.32

### Source language

French

### Steps to reproduce

try to read any manga

### Expected behavior

- search for a manga: obtain the corresponding manga if present on the site

### Actual behavior

- search for a manga: we get no results even if present on the site

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

It is the only source that allows you to have regular updates without Cloudflare available in French.  It is really important for the French community.  Thank you for your work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Could you tell us more about the "infinite loading" issue? From my tests I didn't have the issue.
For Cloudflare issues on French extensions, you can usually solve them by using a custom user-agent.

**Comment by pixelroll** [comment]
> Could you tell us more about the "infinite loading" issue? From my tests I didn't have the issue. For Cloudflare issues on French extensions, you can usually solve them by using a custom user-agent.

it was actually a mistake on my part, I didn't have optimal test conditions. There are no loading problems.

**Comment by KirinRaikage** [comment]
OK cool!
