### ISSUE TITLE
Mono manga source remove

### ISSUE THREAD

**Issue by PanPan-p** [tachiyomiorg/tachiyomi-extensions#17634]
### Source link

https://monomanga.com/

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Soitora** [comment]
Proof of Ownership recieved.
