### ISSUE TITLE
IOS Komga: trust self signed ssl certificates

### ISSUE THREAD

**Issue by Tiny66** [tachiyomiorg/tachiyomi-extensions#17648]
### Source name

IOS Komga 1.4.47

### Source language

chinese

### Describe your suggested feature

I run komga server in my local network, it sits behind reverse proxy with https(self signed certificate) enabled.
when I try to open IOS komga extension in tachiyomi app I get error
![64741158a94d980408b8fe237554917](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48283218/63d189d4-7e85-4746-b477-a39800462624)
Is it possible to add an option in source setting to trust self signed certificates, or file input where certificate for source can be placed?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
There is no iOS version of tachiyomi so not related to us. Also even if this was related to the extension, this has been done long ago #4581
