### ISSUE TITLE
The Siyah Melek site turned into the Gri Melek site

### ISSUE THREAD

**Issue by MelasculaSins** [tachiyomiorg/tachiyomi-extensions#17656]
### Source information

Gri Melek

### Source language

Turkish

### Source new URL

https://grimelek.com/

### Other details

Madara theme
+18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Closing in favor of  #18484
