### ISSUE TITLE
MangaDex is showing "unable to parse TLS packet header"

### ISSUE THREAD

**Issue by UnownDragon666** [tachiyomiorg/tachiyomi-extensions#17651]
### Source information

MangaDex 1.4.188

### Source language

Multi

### Steps to reproduce

Browse > Sources > MangaDex
It says that it's a javax.net.ssl.SSLException: Unable to parse TLS package header.

### Expected behavior

All the respective manga from MangaDex to show up.

### Actual behavior

javax.net.ssl.SSLException: Unable to parse Tls package header.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by UnownDragon666** [comment]
I changed the DNS over HTTPS to cloudflare and it started to work again.

**Comment by UnownDragon666** [comment]
Nvm it's back, it just works momentarily when changing DoH

**Comment by Seishirou101** [comment]
That's related to your connection, if doh didn't work. Your options are VPN, use a different connection, or find the thing blocking/hijacking connection to md and white list MD.
