### ISSUE TITLE
Mangaswat domain changed 

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#17667]
### Source information

Mangaswat 1.4.37

### Source language

Arabic

### Source new URL

https://stmgs.com/

### Other details

I was able to change it through the app but there was another problem that the chapters weren't able to update
And when open the manhwa in the webview it redirects me to the main menu 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by sephmedina** [comment]
will take a look

**Comment by sephmedina** [comment]
I tested on Samsung Tablet S7 using version 1.4.37.

Seems like site is redirecting to new url "https://stmgs.com/" successfully. Titles are also displayed successfully in webview with redirect too.

I can open pull request anyways since redirect may not work in future.
