### ISSUE TITLE
Pages not loading after 2nd page mangakakalot

### ISSUE THREAD

**Issue by God-Slayer01** [tachiyomiorg/tachiyomi-extensions#17695]
### Source information

Mangakakalot 1.4.8

### Source language

English 

### Steps to reproduce

1. Open mangakakalot
2. Open any manga
3. Go to any page after page 3

### Expected behavior

Pages should load 

### Actual behavior

Pages are not loading 

### Tachiyomi version

0.14.6

### Android version

Android 9

### Other details

Some of books will work but many are not working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have tried the troubleshooting guide.

**Comment by God-Slayer01** [comment]
Thanks. It worked
