### ISSUE TITLE
manga swat error

### ISSUE THREAD

**Issue by HVHJVHJ** [tachiyomiorg/tachiyomi-extensions#17703]
### Source information

manga swat 

### Source language

arabic

### Steps to reproduce

![Screenshot_20230828_004855_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/56452455/c3b56055-df5c-430e-be81-8432255d7115)
this is the error

### Expected behavior

it works? 

### Actual behavior

it supose to open the mangas

### Tachiyomi version

latest

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all the requested information correctly. In this state we can't even know if you have updated your extension. Even if it's the case, this is a site error which the site owners that needs to fix.

**Comment by HVHJVHJ** [comment]
i have updated to the latest it was working before i updated to the latest
extention update

**Comment by alessandrojean** [comment]
Latest is not a valid version number. Also what I said: this is a site error which the site owners that needs to fix.
