### ISSUE TITLE
LikeManga Error 529

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#17707]
### Source information

LikeManga 1.4.1

### Source language

English

### Steps to reproduce

1. Download "A way to protect the lovable you" chapter 105 , which doesn't even show page number but show HTTP error 529 in notification
2. View through app webview is fine
3. View through app to view image show HTTP error 529 

Help please

### Expected behavior

Can view and download chapter

### Actual behavior

show HTTP error 529 and unable to download

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce with the given steps. The HTTP error 529 means ''Site Overloaded", maybe the issue is intermittent.

Can you reproduce the issue yourself? -- clear cookies and chapter cache first.
