### ISSUE TITLE
Webnovel search engine fault

### ISSUE THREAD

**Issue by basharizwaan61** [tachiyomiorg/tachiyomi-extensions#17718]
### Source information

Web novel English

### Source language

English

### Steps to reproduce

Issues :
If I search for a novel in webnovel, it only searches in comic section and if search the same term in browser view it finds out the exact novel. Seems like the webnovel source link is fixed to comic section only. Please figure it out.

### Expected behavior

It should search in every section like novels, comic, Manga. 

### Actual behavior

It shows results from comic only

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by basharizwaan61** [comment]
> This isn't a novel reading app.

It can be, at least there must be a way, I just wanna read classroom of the elite light novel

**Comment by AntsyLich** [comment]
No intention to do so

**Comment by basharizwaan61** [comment]
> No intention to do so

Well, I found another source "novelcool". Thanks man, I got the novel by the way.
