### ISSUE TITLE
MangaFire no results found

### ISSUE THREAD

**Issue by BigBearBulrok** [tachiyomiorg/tachiyomi-extensions#17715]
### Source information

MangaFire 1.4.2

### Source language

English

### Steps to reproduce

1. Open MangaFire English source
2. Shows "no results found"

### Expected behavior

Shows the list of manga available on MangaFire 

### Actual behavior

Shows "no results found", not showing any manga at all
![MangaFire not fine](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/3d31efa1-9190-4707-8e93-f4a8e041baab)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

Webview loads the site as normal
![MangaFire fine](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/7329d88c-4ed9-4181-a8c5-a61b7bb01e10)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by seemslikeali** [comment]
Seems like they made adjustments to the website and now extension is broken
