### ISSUE TITLE
Asura scans new domain

### ISSUE THREAD

**Issue by NotBlankyu** [tachiyomiorg/tachiyomi-extensions#17724]
### Source information

Asura Scans 1.4.51

### Source language

English

### Source new URL

https://asuracomics.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by I-Am-C0der** [comment]
Looks like they finally moved to this new domain from the temporary domain after maintenance and stuffs. Hope there will be no more domain changes after this.
