### ISSUE TITLE
Mangame.org -> Mangareading.org

### ISSUE THREAD

**Issue by MikeZeDev** [tachiyomiorg/tachiyomi-extensions#17730]
### Source information

Mangame

### Source language

English

### Source new URL

Mangareading.org

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Both the old domain and new domain redirects to MangaEffect, which already exists.
