### ISSUE TITLE
Picacomic extensions must use VPN

### ISSUE THREAD

**Issue by wulei1997** [tachiyomiorg/tachiyomi-extensions#17734]
### Source information

picacomic 1.4.2

### Source language

zh

### Steps to reproduce

open the picacomis

### Expected behavior

the comic list

### Actual behavior

java.net.SocketTimeoutException:failed to connect to picaapi.picacomic.com/2001::6ca0:ace8(port 443) from /2408:84f2:c1:d6f1:4460:ecff:fe99:6767(port 41942) after 30000ms

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
if you need to use a vpn, then its not something we can control.
