### ISSUE TITLE
Liremangas

### ISSUE THREAD

**Issue by anjaragermai** [tachiyomiorg/tachiyomi-extensions#17736]
### Source name

Liremangas

### Source link

https://liremangas.com

### Source language

French

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by KirinRaikage** [comment]
It's not a French source.
Is there at list a manga with chapters in the website ?
Sounds like an empty website with just a list of themes as a placeholder and some manga entries set.
