### ISSUE TITLE
Mangaswat No chapters found issue 

### ISSUE THREAD

**Issue by AbdUlrahman097** [tachiyomiorg/tachiyomi-extensions#17748]
### Source information

MangaSwat 1.4.38

### Source language

Arabic

### Steps to reproduce

Open the extension
open any existing manga/manhwa
no chapters found

### Expected behavior

Find the chapters of any manga/manhwa as usual 

### Actual behavior

No chapters found for any manga/manhwa 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Tian-77** [comment]
The problem still exists beside the chapters are not opening @vetleledaal @alessandrojean
