### ISSUE TITLE
MangaClub: Chapters cannot be loaded when opening them

### ISSUE THREAD

**Issue by Rainarlyt** [tachiyomiorg/tachiyomi-extensions#17746]
### Source information

MangaClub 1.3.11

### Source language

Russian 

### Steps to reproduce

1. Зайти на сохраненную мангу
2. Выбрать главу.
3. Начать чтение (главы не грузятся с источника)
Ждал решения этой проблемы 4-6 месяцев.

### Expected behavior

Главы жолжны грузится

### Actual behavior

Главы не  загружаются

### Tachiyomi version

0.14.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
/edit-title "MangaClub: Chapters cannot be loaded when opening them"
