### ISSUE TITLE
Url change report

### ISSUE THREAD

**Issue by Byrdh** [tachiyomiorg/tachiyomi-extensions#17758]
### Source information

Shinigami 1.4.32

### Source language

Indonesia 

### Source new URL

Https:/shinigami.eu/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by izul150** [comment]
shinigami.ae is not .eu

**Comment by stevenyomi** [comment]
Duplicate of #17751
