### ISSUE TITLE
Shinigami ID

### ISSUE THREAD

**Issue by izul150** [tachiyomiorg/tachiyomi-extensions#17751]
### Source information

Shinigami 1.4.32

### Source language

Indonesian

### Source new URL

https://shinigami.ae

### Other details

please replace it quickly, thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Firman47** [comment]
P

**Comment by THELASTWIBUPLAY** [comment]
Waiting to be fixed..
