### ISSUE TITLE
Some manwha are  on the official website but not the app vesion 

### ISSUE THREAD

**Issue by Danieladanri8761** [tachiyomiorg/tachiyomi-extensions#17768]
### Source information

Aquamanga

### Source language

English 

### Steps to reproduce

Some manwha are on the official website but not the app vesion extension Aquamanga.

X Ash
Apocalypse mechanic 
On my way to kill god 

### Expected behavior

G

### Actual behavior

H

### Tachiyomi version

G

### Android version

G

### Other details

G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Fill in the fields next time properly
