### ISSUE TITLE
Sort by available chapters in Mangadex

### ISSUE THREAD

**Issue by Taursil** [tachiyomiorg/tachiyomi-extensions#17769]
### Source name

Mangadex

### Source language

English

### Describe your suggested feature

Introduce an option to sort manga search results by the number of available chapters. This would allow users to easily identify manga series based on their length.
Alongside the title or the cover of the manga in search results, display the total chapter count. This provides a quick reference point for users.

Use Case:
A user searching for a manga series to start might be looking for either:

   - A longer series to get invested in, or
   - A shorter series for a quick read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
MangaDex api doesn't provide sort by available chapters and the app doesn't know about chapter count until you open the title and load them
