### ISSUE TITLE
Aiyumanga domain changed

### ISSUE THREAD

**Issue by seba1107** [tachiyomiorg/tachiyomi-extensions#17767]
### Source information

AiYuManga 1.4.33

### Source language

Spanish

### Source new URL

https://www.aiyumanhua.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by edmxn** [comment]
Aún no hacen nada con esto?
