### ISSUE TITLE
Cloudrecess 

### ISSUE THREAD

**Issue by joyceedesu** [tachiyomiorg/tachiyomi-extensions#17771]
### Source name

cloudrecess

### Source link

https://cloudrecess.io/

### Source language

English

### Other details

18+/NSFW/smut especially for Yaoi fans

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by joyceedesu** [comment]
they update fast compared to other sites that I read so please consider this source, thank you so much

**Comment by strawberrysilk** [comment]
Any updates on when this source is going to be added?

**Comment by joyceedesu** [comment]
> Any updates on when this source is going to be added?
nothing :((

**Comment by joyceedesu** [comment]
tysm worth the wait🥹🩷

**Comment by strawberrysilk** [comment]
Omg YESSSSS this is amazing. Though there is a slight issue, longer comics
that have page 1 and 2. The list don't have page two's chapters included.
Like- the first chapter of "painter of the night" is chapter 38. Chapters
1-37 are on page two which aren't included in the tachiyomi list. Please
fix it. Thank you. 🌸💗

**Comment by alessandrojean** [comment]
Please report it by opening a separate bug report issue.

**Comment by joyceedesu** [comment]
Can you report the issue, I also experience the cloudflare issue since its
always loading and i can't open it even my tho i have an internet

**Comment by strawberrysilk** [comment]
I cannot open a separate issue because ghithub isn't letting me log in 😭

**Comment by joyceedesu** [comment]
me too, i tried last night but it didn't work for me 😔

**Comment by strawberrysilk** [comment]
Really hope it gets fixed though.

**Comment by alessandrojean** [comment]
We can't do anything about Cloudflare. Please refer to the troubleshooting guide linked in the acknowledgements section about it. Also issues aren't meant to be used as a chat. Please use the #support channel at our [Discord server](https://discord.gg/tachiyomi) if you need additional help instead.
