### ISSUE TITLE
Shinigami url change

### ISSUE THREAD

**Issue by ChikaTempest** [tachiyomiorg/tachiyomi-extensions#17788]
### Source information

Shinigami 1.4.32

### Source language

indonesia

### Source new URL

https://shinigami.ae/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by ChikaTempest** [comment]
still not fixed and update. don't close this yet

**Comment by ChikaTempest** [comment]
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/105035665/8e11145f-a3d4-4d71-8001-4e386ad17d49)

**Comment by arkon** [comment]
There's already an open request, you don't need to spam.
