### ISSUE TITLE
InazuManga: Change Theme, Name and Domain to YumeKomik.com

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#17810]
### Source information

Inazu Manga (ID) 1.4.31

### Source language

Indonesia 

### Source new URL

https://yumekomik.com

### Other details

![IMG_20230906_063046](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/d1c53abf-fdc6-4606-9b7e-2ba5f1b67c2d)

Translate :
"Sorry for the long wait, now InazuManga has changed its name to YumeKomik.com.

So from now on, keep visiting our website and don't forget to upvote"

### Theme

Migrate to MangaThemesia ~~previously Uses Madara~~ thanks to **vetleledaal** for correcting me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Also switched to MangaThemesia (previously Madara)
