### ISSUE TITLE
Mg komik

### ISSUE THREAD

**Issue by Joker2798** [tachiyomiorg/tachiyomi-extensions#17826]
### Source information

MgKomik 1.4.36

### Source language

Indonesia

### Source new URL

https://mgkomik.id/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closed by #17747.
