### ISSUE TITLE
Tenshi.id: short list of comics 

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi-extensions#17820]
### Source information

tenshi.id  1.4.28

### Source language

ID

### Steps to reproduce

Incomplete comics and updates 

### Expected behavior

There are a few popular comics, and the latest ones are just as few 
Usually much like the others

### Actual behavior

Like in the video 

### Tachiyomi version

Last

### Android version

Android 11

### Other details
![Screenshot_2023-09-07-08-05-17-75_5901a79de973a50c74cff4cbb6149856](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100791931/cb67fd73-b299-4216-a54a-7cb8a27b24a9)
![Screenshot_2023-09-07-08-05-21-68_5901a79de973a50c74cff4cbb6149856](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100791931/21cb3f50-246d-4ee5-a323-1de6144aebe9)
![Screenshot_2023-09-07-05-28-13-40_5901a79de973a50c74cff4cbb6149856](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100791931/c08de3cc-3bfb-4a96-a445-209a905d231c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill and provide all requested information correctly.

**Comment by mozzaru** [comment]
please open 
And check 
Thanks
