### ISSUE TITLE
Preview chapter marking itself unread and redownloading repeatedly 

### ISSUE THREAD

**Issue by Matakor** [tachiyomiorg/tachiyomi-extensions#17837]
### Source information

Asura Scans 1.4.52

### Source language

English

### Steps to reproduce

Difficult to reproduce, but happens once every few days. The specific series I see this happen with is Player Who Returned 10,000 Years Later from Asura. The series 'preview' chapter has gone untouched and not updated by the source since July 2022, but once or twice a week I suddenly see an unread chapter for the series and it is always that preview chapter. I delete this chapter, mark as read, and bookmark filter it out each time, and it still returns unread, unbookmarked, and is redownloaded.

### Expected behavior

A chapter that isn't updated for over a year should not be seen as a new chapter every week.

### Actual behavior

Stated above

### Tachiyomi version

App version: 0.14.6-6037

### Android version

Android 12

### Other details

I should note that I haven't seen this happen with other series, and I've got about 40 series from Asura in my library. Doesn't seem to happen with other extensions, but I think it could be possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Trinthakis** [comment]
I'm also affected by this bug. The chapter previews on the following two series keep on being marked unread and re-downloaded:

Player Who Returned 10,000 Years Later
Regressor Instruction Manual

**Comment by alessandrojean** [comment]
This happens because they change the URLs of the series and chapters frequently to mess up with apps like Tachi. If the URL changes, the app detects it as a new chapter by design, as it can be a reupload or some change in the chapter. Can't really do much on this case, we suggest using better source that doesn't have this bad behavior of changing URLs.
