### ISSUE TITLE
Bilibili Comics access "paid" free chapters through the desktop site or app

### ISSUE THREAD

**Issue by CaptPlasma** [tachiyomiorg/tachiyomi-extensions#17839]
### Source name

BILIBILI COMICS

### Source language

English

### Describe your suggested feature

Currently, the extension goes to the m.bilibilicomics.com site and that site requires users to download the app to view most chapters. However, going to the regular site (bilibilicomics.com) or downloading and reading through the app allow access to all chapters (at least for what I want to read, Ashes of Love).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We don't use the site. We use the api. And both of them use the same api.
