### ISSUE TITLE
KomikTo

### ISSUE THREAD

**Issue by Shrayuki** [tachiyomiorg/tachiyomi-extensions#17836]
### Source name

KomikTo

### Source link

https://komikto.com/

### Source language

Indonesian language

### Other details

> I see that this source does not or does not yet exist in ecstasy sources 

> [KomikTo](https://komikto.com/)`

> The source contains story content 18+

> There is a shortage in the genre category, more precisely, only a few genres are displayed 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by Riztard** [comment]
website "404 Not Found" at the moment
