### ISSUE TITLE
Cubari unused error notification

### ISSUE THREAD

**Issue by Conrmias** [tachiyomiorg/tachiyomi-extensions#17849]
### Source information

Cubari

### Source language

Multi

### Steps to reproduce

1.Type in command to get to a manga.
2.Add to library
3.Download.

### Expected behavior

Manga would download

### Actual behavior

Will not download and notification says unused instead of error code

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

![Screenshot_20230909-065516_(1)](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/119284115/da4e7a34-024f-4fff-866c-a9944981a5a5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed by dc237650eae30c09d5a85a202b4639db974839eb
