### ISSUE TITLE
Siyahmelek changed to grimelek.net

### ISSUE THREAD

**Issue by alpereyte** [tachiyomiorg/tachiyomi-extensions#17842]
### Source information

tr.siyahmelek 

### Source language

Turkish

### Source new URL

https://grimelek.net/

### Other details

The other site is closed, I would appreciate it if you update this site.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Duplicate of #17656
