### ISSUE TITLE
ares manga

### ISSUE THREAD

**Issue by weebos2** [tachiyomiorg/tachiyomi-extensions#17845]
### Source information

ARESmanga 1.4.28

### Source language

Arbic 

### Source new URL

https://aresnov.org/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by kayto16kit** [comment]
هل يمكن على الأقل فتح خيار تغيير رابط الموقع
