### ISSUE TITLE
Viz downloaded files goes missing

### ISSUE THREAD

**Issue by Srking91** [tachiyomiorg/tachiyomi-extensions#17853]
### Source information

Viz 1.4.19

### Source language

English

### Steps to reproduce

1) Sign into Viz with active premium account
2) download files
3) Viz logs you out after a period of time 
4) App sees only available downloads on the site vs what you actually have, resets read chapters

### Expected behavior

Able to view downloaded chapters 

### Actual behavior

They become unaccessable

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This happens because the URL changes and there's nothing we can do. Use the local source to read these.
