### ISSUE TITLE
Mode Scanlator: Moved to a custom CMS

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#17852]
### Source information

Mode Scanlator 1.4.32

### Source language

Português

### Steps to reproduce

domain changed to:https://modescanlator.com/
![Screenshot_20230909-013014799](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90201611/063e86a6-d3f2-4f29-a758-b949dafc7718)

### Expected behavior

should normally enter the scan

### Actual behavior

does not enter

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

apparently the two scans merged with Mode Scanlator and Peach scan to form one at the link: https://modescanlator.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They haven't changed their domain as the extension already uses this one. They changed their theme instead.

**Comment by alessandrojean** [comment]
Their site is now returning a lot of zip files instead of the actual images, and extensions can't handle downloading zip files and unzipping to show each individual image. The extension will be removed, migrate to better sources.

**Comment by ProTankerAlfa** [comment]
Im developer of this site (modescanlator), I recommend using the site directly, there are no abusive advertisements : )
