### ISSUE TITLE
Nhentai doesn't work

### ISSUE THREAD

**Issue by TomateAmargo** [tachiyomiorg/tachiyomi-extensions#17868]
### Source information

NHentai 1.4.39

### Source language

Multi

### Steps to reproduce

Whenever I try to open NHentai, be it on Multi or in English, it simply doesn't work, it says java.io.IOException: Falha ao contronar o Cloudflare, this has stayed like this for quite awhile, maybe some 3 or 4 months and I've tried to to solve this multiple times but without success, before this I would just open the extension and if needed, I would go to webview, do the CAPTCHA and be able to see the website like normal both in webview and in the app, nowadays that doesn't happen, the website just reloads into the same do the CAPTCHA again and again and again

### Expected behavior

The extension should open like every other without any problems

### Actual behavior

The extension doesn't open and instead shows java.io.IOException: Falha ao contronar o Cloudflare

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
