### ISSUE TITLE
Bakai: Cat and mouse game

### ISSUE THREAD

**Issue by Nerannnn** [tachiyomiorg/tachiyomi-extensions#17882]
### Source information

Bakai 1.4.4

### Source language

Portuguese 

### Steps to reproduce

- I open the extension
- Manga in the "Recent" part usually open
- At the bottom of the screen appears a message saying Error 404 and the rest of the library does not carry and can not be able to search manga

### Expected behavior

All the manga of the library carry and the possibility of searching for other manga

### Actual behavior

Half the library appears and only these manga can be opened and read followed by a message at the bottom of the screen by saying error 404, as well as not managing research.

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

This same error had already occurred before was fixed in the update of the extension but came back again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They changed the URLs again just after the extension update, so we're in a cat and mouse game and they're done on purpose. Migrate to better sources as it will be removed since it's not worth keep supporting it.

**Comment by Nerannnn** [comment]
Could you not remove the extension? Since it is still possible to read the manga both in the recent part as those who are already saved in my library

**Comment by alessandrojean** [comment]
There's no point in keeping a semi broken extension.
