### ISSUE TITLE
MangaRabic new URL

### ISSUE THREAD

**Issue by AhmadRamadansyria** [tachiyomiorg/tachiyomi-extensions#17880]
### Source information

MangaRabic

### Source language

Arabic 

### Source new URL

https://mangarabic.com

### Other details

This problem was suspended for a long time and tachiyomi doesn't even try to fix it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by AhmadRamadansyria** [comment]
The app didn't change the URL yet

**Comment by yemenihandsome** [comment]
> The app didn't change the URL yet

Yes, he changed the address

**Comment by AhmadRamadansyria** [comment]
Tachiyomi why won't you solve this problem or because it is an Arabic site so you don't intereste in it
