### ISSUE TITLE
Kai Scans

### ISSUE THREAD

**Issue by Jaj29** [tachiyomiorg/tachiyomi-extensions#17889]
### Source name

 Kai Scans

### Source link

https://kaiscans.com/

### Source language

English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme

**Comment by Jaj29** [comment]
May I ask what does that mean?

**Comment by vetleledaal** [comment]
It's a common theme used by several sites. Information intended for other contributors, i.e. the site can be added to MangaThemesiaGenerator.kt.

**Comment by Secozzi** [comment]
Closed by #19208
