### ISSUE TITLE
Remove 1st Kiss

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi-extensions#17897]
### Source name

1st Kiss

### Source language

English

### Source link

https://1stkissmanga.me

### Other details

It redirects to likemanga.io which was added in #17597

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
1stkiss is closed. They already gave notification weeks ago. Their new site is likemanga and has different template from before. Tachiyomi already release the likemanga extension

**Comment by pavzahr** [comment]
That sucks, thank you for closing this ticket down. Guess I'll migrate the rest of mine from that source, thx.
