### ISSUE TITLE
1st Kiss server is not 1st Kiss anymore, what happened? 

### ISSUE THREAD

**Issue by pavzahr** [tachiyomiorg/tachiyomi-extensions#17896]
### Source information

1st Kiss 1.4.4.1

### Source language

English

### Steps to reproduce

I did global search on certain manhwa titles for all sources/extensions I have but only 1Kiss is empty so I felt something is up as 1Kiss page on Tachiyomi is "no result", I went into 1Kiss extension source after it and turned out it's now Like Manga source, where is all 1Kiss server we are used to? Is it hacked again? It's second best after Mangadex. 

### Expected behavior

Try reading saved 1st Kiss comics on Tachiyomi, or global searching a title on 1st Kiss, it should have appeared. Pls try to look into 1st Kiss server on that extension please. 

### Actual behavior

Yes, empty pages on both saved 1st Kiss comics' episodes and also, nothing came out of 1st kiss results. 

### Tachiyomi version

1.6.6

### Android version

Android 7.0

### Other details

(uhh my latest Tachiyomi is actually 1.6.6 tho)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
#17897
