### ISSUE TITLE
MangaStarz : URL change report

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#17917]
### Source information

Manga Starz 1.4.35

### Source language

Arabic

### Source new URL

https://mangastarz.org

### Other details

No (https://mangalike.org) 
This is a link to last website

Picture from the site :
![Screenshot_٢٠٢٣٠٩١٢-١٧١٤٠٥](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/144265316/9321a608-1c7a-4ab5-b08b-8cc4345de4be)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by firstdarsh** [comment]
New link (https://mangastarz.org/)

**Comment by 1231971** [comment]
Is there any updates
