### ISSUE TITLE
request to remove the site link

### ISSUE THREAD

**Issue by Ashily25** [tachiyomiorg/tachiyomi-extensions#17929]
### Source link

"https://moondaisyscans.biz/"

### Other details

Hi, again. I am the admin of the site. I request you to remove my site link. Can you help me?

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by OncePunchedMan** [comment]
Who did you send the proof to?

**Comment by Ashily25** [comment]
> Who did you send the proof to?

I sent it to you on discord

**Comment by Ashily25** [comment]
Maintenance mode is turned off. Can you check again?

**Comment by OncePunchedMan** [comment]
Proof is valid
