### ISSUE TITLE
Doujindesu chapter not found

### ISSUE THREAD

**Issue by Lalaanda** [tachiyomiorg/tachiyomi-extensions#17923]
### Source information

Doujindesu 1.4.5

### Source language

Indonesian

### Steps to reproduce

1.open tachiyomi
2. Then select the extension
3. Search for the doujindesu source and click

### Expected behavior

please fix the doujindesu source

### Actual behavior

Chapter not found 
![Screenshot_20230912-215119](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/144820599/7534fafb-8e5d-46ca-aa81-603830194f6e)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
It works for me

Please refer to the **"Solving Cloudflare issues"** section and the three consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try **changing** the **User Agent** string, use **DOH / DNS Over HTTPS**, or change your **DNS** in your phone settings by following the link below, if you have done it but still no effect try to use **VPN**, **delete** the **Cookies**  and the **WebView Cache**, but this is a last measure, if it doesn't work, **migrate** to **other sources** or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

![Screenshot_2023-09-28-06-48-12-65_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/c4b7fae5-71fc-4301-95c6-bd3e53f97f92)

**Comment by TheKingTermux** [comment]
It works for me

Please refer to the **"Solving Cloudflare issues"** section and the three consecutive ones at the link below. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try **changing** the **User Agent** string, use **DOH / DNS Over HTTPS**, or change your **DNS** in your phone settings by following the link below, if you have done it but still no effect try to use **VPN**, **delete** the **Cookies**  and the **WebView Cache**, but this is a last measure, if it doesn't work, **migrate** to **other sources** or wait until they lower their protection.

https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

![Screenshot_2023-09-28-06-48-12-65_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/c4b7fae5-71fc-4301-95c6-bd3e53f97f92)
