### ISSUE TITLE
Another try for MangaRabic

### ISSUE THREAD

**Issue by AhmadRamadansyria** [tachiyomiorg/tachiyomi-extensions#17943]
### Source information

MangaRabic

### Source language

Arabic

### Source new URL

https://MangaRabic.con

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Domain doesn't exist, closing.

**Comment by AhmadRamadansyria** [comment]
I did it like that so they change it then I can enter the right one because they didn't solve it
