### ISSUE TITLE
Manga weebs source showing no page found, need a new update of extension

### ISSUE THREAD

**Issue by fitzz2894** [tachiyomiorg/tachiyomi-extensions#17952]
### Source information

Manga Weebs

### Source language

english

### Steps to reproduce

After an update also of (Manga Weebs) extension, there is an incoming new manga chapter but after clicking to see or read, it shows no page found, need a new update of it

### Expected behavior

click and read 

### Actual behavior

click and not found page

### Tachiyomi version

0.14.6

### Android version

Android version 7.0 NRD90M

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by huguesBouvier** [comment]
Same issue. Also 0.14.6 and android 11,
