### ISSUE TITLE
Delete a website

### ISSUE THREAD

**Issue by manganoon** [tachiyomiorg/tachiyomi-extensions#17950]
### Source link

https://manjanoon.com/

### Other details

control Board

![Screenshot_20230914_224140_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115876113/750fba61-7a33-4112-a128-8aaad1b68374)
![Screenshot_20230914_224150_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115876113/9f41e3ad-5501-4240-a610-0da2e7a3088a)

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Soitora** [comment]
I guess you could say that I got proof of "ownership"?

**Comment by arkon** [comment]
Hi, please add a `TXT` DNS record for my domain with the value `tachiyomi-verification` so we can verify you actually own the domain.

**Comment by manganoon** [comment]
> مرحبًا، يرجى إضافة `TXT`سجل DNS لنطاقك بالقيمة `tachiyomi-verification`حتى نتمكن من التحقق من ملكيتك الفعلية للنطاق.

I did it, you can now verify ownership

**Comment by arkon** [comment]
```
% dig -t txt manjanoon.com

; <<>> DiG 9.10.6 <<>> -t txt manjanoon.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45001
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;manjanoon.com.			IN	TXT

;; ANSWER SECTION:
manjanoon.com.		300	IN	TXT	"google-site-verification=wanHhoYNNRU5ppJgxlBnyEob09q39Et7k_To44_fHek"
manjanoon.com.		300	IN	TXT	"tachiyomi-verification"
manjanoon.com.		300	IN	TXT	"v=spf1 +a +mx +a:panel.flixscans.net -all"

;; Query time: 23 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Thu Sep 14 17:33:13 EDT 2023
;; MSG SIZE  rcvd: 212
```

Confirmed ownership.

That said, some other folks said your website is unusable with all of its ads and ad blocking prevention, which doesn't meet the requirements for removal.

**Comment by manganoon** [comment]
> ```
> % dig -t txt manjanoon.com
> 
> ; <<>> DiG 9.10.6 <<>> -t txt manjanoon.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45001
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;manjanoon.com.			IN	TXT
> 
> ;; ANSWER SECTION:
> manjanoon.com.		300	IN	TXT	"google-site-verification=wanHhoYNNRU5ppJgxlBnyEob09q39Et7k_To44_fHek"
> manjanoon.com.		300	IN	TXT	"tachiyomi-verification"
> manjanoon.com.		300	IN	TXT	"v=spf1 +a +mx +a:panel.flixscans.net -all"
> 
> ;; Query time: 23 msec
> ;; SERVER: 192.168.2.1#53(192.168.2.1)
> ;; WHEN: Thu Sep 14 17:33:13 EDT 2023
> ;; MSG SIZE  rcvd: 212
> ```
> 
> Confirmed ownership.
> 
> That said, some other folks said your website is unusable with all of its ads and ad blocking prevention, which doesn't meet the requirements for removal.

I apologize, but why are my ads annoying? They are not pop-up ads, but rather natural Google AdSense ads, which are the only source of support that keeps us going and working, and I think that some followers do not appreciate the effort made by the translators.

**Comment by arkon** [comment]
We'd be happy to reconsider if it was toned down from this:

![](https://media.discordapp.net/attachments/364330965444853761/1151973393101500457/wFnKakW.png)

**Comment by manganoon** [comment]
> We'd be happy to reconsider if it was toned down from this:
> 
> ![](https://camo.githubusercontent.com/b501ffb9521d208dae9aa56a16133da14c3a4a29b26ab072a8fb876916321635/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3336343333303936353434343835333736312f313135313937333339333130313530303435372f77466e4b616b572e706e67)

Well, sir, I will work on making the site work by adding an “ad blocker” so that some people can use the ad blocker, but sir, I know that I lose a lot of audience when you add my site to the application, and this does not help us at all, thank you.

**Comment by manganoon** [comment]
> We'd be happy to reconsider if it was toned down from this:
> 
> ![](https://camo.githubusercontent.com/b501ffb9521d208dae9aa56a16133da14c3a4a29b26ab072a8fb876916321635/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3336343333303936353434343835333736312f313135313937333339333130313530303435372f77466e4b616b572e706e67)

Could you delete it, sir, please? I'm not used to having to insist on my request.  But I do my best so that the effort of the team is not wasted. They are working very hard, so please remove it, as this does not help us at all..!

**Comment by AntsyLich** [comment]
When a page is opened on your site it is mostly covered with ads which is intrusive and annoying. I needed to close 4 ads before being able to navigate around. And there were more ads even after removing those. You also don't give the user the freedom to block said ads. Unless you make the ads non intrusive we won't be removing your site.

**Comment by manganoon** [comment]
> When a page is opened on your site it is mostly covered with ads which is intrusive and annoying. I needed to close 4 ads before being able to navigate around. And there were more ads even after removing those. You also don't give the user the freedom to block said ads. Unless you make the ads non intrusive we won't be removing your site.

Why should followers read for free? Why do they have priority over us, the translation team? We are the ones who work hard and work hard to provide them with the best translation and clean, high-quality images. What is the problem with watching some ads that contribute to the team’s continuation of translating manga? Don’t we deserve a little support?  ?!  You and I know very well how difficult this field is and requires effort to continue in it. We do not steal anyone’s translation, we do our work alone, so the advertisement section is important to us. I do not know why you insist on making sites lose their audience. If we were to steal anyone’s translation, you would have the right to upload it.  The website is in your application. Sir, you must understand this well. I am not asking much of you. I am only asking you to remove my website from your application, as it belongs to me and my team. Isn’t this a right I should demand!?

**Comment by scb261** [comment]
You don't care about your readers, why would we care about you? You could put a few ads just to pay for servers and maybe earn a bit, you could also put up a donation link. But instead you chose to put so many ads, that users can't even see the site content when opening the site. You yourself discourage your readers to read on the site.

**Comment by manganoon** [comment]
> You don't care about your readers, why would we care about you? You could put a few ads just to pay for servers and maybe earn a bit, you could also put up a donation link. But instead you chose to put so many ads, that users can't even see the site content when opening the site. You yourself discourage your readers to read on the site.

Sir, website visitors from the Arab world, ad views and clicks for Al Arab are very small compared to European countries, and I don’t just pay the server, I pay every translator, editor, and cleaner who works with us, so you have to understand, sir, why I do that, and I told you previously that I will grant the authority to view the site to whoever has it.  (Blocking ads) And this picture is from my advertising account. You can know the price per click and the return per thousand page views..
![Screenshot_20230915_110504](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115876113/5fedf678-12f4-4f2a-8d78-2d91ae1c3f0e)
