### ISSUE TITLE
Desu: new domain

### ISSUE THREAD

**Issue by andrey2s2** [tachiyomiorg/tachiyomi-extensions#17954]
### Source information

desu

### Source language

ru

### Source new URL

desu.win

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Wait for #17903
