### ISSUE TITLE
Ozul Shojo : (Source request)

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#17980]
### Source name

Ozul Shojo

### Source link

https://ozulshojo.com

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses MangaThemesia theme
```kt
SimpleDateFormat("MMMM dd, yyyy", Locale("ar"))
```

**Comment by yemenihandsome** [comment]
> Uses MangaThemesia theme
> 
> ```kotlin
> SimpleDateFormat("MMMM dd, yyyy", Locale("ar"))
> ```

I have opened a new problem that he created to me I wish to see its number #17981

**Comment by vetleledaal** [comment]
Redirects to https://kingofshojo.com/ , which was completed in #19021
