### ISSUE TITLE
Changed Domain: Golden Mangás

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#18002]
### Source information

Golden Mangás 1.4.20

### Source language

Português

### Steps to reproduce

even bypassing cloudflare in webview the extension doesn't work
![Screenshot_20230916-213211902](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90201611/a0145667-f7c2-4d71-8d80-ba01673ded19)

### Expected behavior

it should enter the scan normally

### Actual behavior

does not enter

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

the domain has been changed to: https://www.goldenmangas.top/
![Screenshot_20230916-213701931](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90201611/e7cb9142-407a-4938-8c17-601efbc0abc1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They haven't changed their domain and the extension is using this exact domain shown in your screenshot.

Please refer to the "Solving Cloudflare issues" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
