### ISSUE TITLE
Mangafire.to extension not working

### ISSUE THREAD

**Issue by saif78642** [tachiyomiorg/tachiyomi-extensions#18007]
### Source information

Mangafire 1.4.2

### Source language

English

### Steps to reproduce

Just update it

### Expected behavior

Let it be a working extension 

### Actual behavior

It should be working 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the requested information correctly next time. "Not working" is very vague, do specify any errors you're getting.

**Comment by grevorn** [comment]
is this close for good?

**Comment by Roy-deity** [comment]
How is not working very vague? Its genuinely not working for almost a month now, i don't why it keeps getting closed if it needs tl be fixing but if no-one is gonna try at least say something or give us an update.

**Comment by arkon** [comment]
Please refer to #17799 as an example of an issue with a decent amount of information provided.

**Comment by Roy-deity** [comment]
> Please refer to #17799 as an example of an issue with a decent amount of information provided.

Ok, I see
