### ISSUE TITLE
Golden mangás 

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#18015]
### Source information

Golden mangás 1.4.21

### Source language

Português pt-br

### Steps to reproduce

Entre na scan, e não carrega os mangás por falha de cloudflare 
Enter the scan, and the manga won't load due to cloudflare failure

### Expected behavior

Enter the scan and be able to read the manga 

### Actual behavior

Should upload the manga 

### Tachiyomi version

J2k 1.6.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
