### ISSUE TITLE
Golden Mangás: Changed their domain (again)

### ISSUE THREAD

**Issue by Ruanss2000** [tachiyomiorg/tachiyomi-extensions#18012]
### Source information

Golden Mangas 1.4.20

### Source language

Português(Br)

### Source new URL

Https://www.goldenmangas.top

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This domain just redirects to the one used by the extension currently, they haven't changed their domain.

**Comment by Ruanss2000** [comment]
> This domain just redirects to the one used by the extension currently, they haven't changed their domain.

A extensão está com o url GoldenManga.top, o novo url é Goldenmangas.top
Falta um "S" no final

**Comment by Ruanss2000** [comment]
Por isto não está funcionando mais

**Comment by alessandrojean** [comment]
Esse domínio com o S redireciona pro sem o S, que é o que a extensão usa.

**Comment by alessandrojean** [comment]
Irei reabrir porque o que está redirecionando é se usar sem o `www.`, já que eles configuraram errado.

**Comment by Retashe** [comment]
But when they manage to solve the url problem, it will automatically solve the problem cloudflare?

**Comment by alessandrojean** [comment]
Cloudflare is a totally different thing, it has no relation to this.
