### ISSUE TITLE
Gostaria de adicionar extensões 

### ISSUE THREAD

**Issue by Gustavohr123** [tachiyomiorg/tachiyomi-extensions#18018]
### Source name

Manga livre, leitor.net e neox 

### Source language

Português 

### Describe your suggested feature

Gostaria de manga livre ou leitor.net voltar pra tachiyomi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do use the source request form next time and fill one request per issue.

Please check if the sources you're suggesting weren't already removed before as well.
