### ISSUE TITLE
Request of a source of the site Ler Mangá 

### ISSUE THREAD

**Issue by pedrinsza** [tachiyomiorg/tachiyomi-extensions#18016]
### Source name

Ler Mangá 

### Source link

https://lermanga.org

### Source language

Brazilian Portuguese 

### Other details

There is NSFW material on the site.
Chapters update constantly.

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by pedrinsza** [comment]
nooooo please add this source I searched for it and I don't think it has any problems

**Comment by alessandrojean** [comment]
Someone else already requested it and there's an open issue. There's no need to have a duplicate.

You're told about it in the acknowledgements section, so please read and follow it when you're checking the boxes next time.

>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.
