### ISSUE TITLE
Extension GoldenMangas change url to GoldenMangas.top 

### ISSUE THREAD

**Issue by Ruanss2000** [tachiyomiorg/tachiyomi-extensions#18011]
### Source information

Golden Mangas 1.4.20

### Source language

Português(Br)

### Steps to reproduce

Url error, not corresponding the site, site is change to GoldenMangas.top 

### Expected behavior

Deveria abrir o site normalmente 

### Actual behavior

Em vez de abrir normalmente da erro de url

### Tachiyomi version

Last version

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This domain just redirects to the domain currently used by the extension.
