### ISSUE TITLE
Animated Glitched Scans URL changed

### ISSUE THREAD

**Issue by xavyc** [tachiyomiorg/tachiyomi-extensions#18025]
### Source information

Animated Glitched Scans 1.4.26

### Source language

English

### Source new URL

https://anigliscans.xyz/

### Other details

It's seem like that Animated Glitched scans changed their url to https://anigliscans.xyz/.

The old domain redirect to the new domain main page breaking all entries and chapters from the source.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ManiV97** [comment]
update Animated Glitched Scans domain #18066
