### ISSUE TITLE
asurescanstr.com domain change

### ISSUE THREAD

**Issue by By-PorfecTo** [tachiyomiorg/tachiyomi-extensions#18027]
### Source information

Asura scans 1.4.52

### Source language

Turkish

### Source new URL

https://armoniscans.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by By-PorfecTo** [comment]
asurascans.com changed its domain on the English-language site and its new domain changed to https://asuracomics.com/

**Comment by KaizennSama** [comment]
> asurascans.com changed its domain on the English-language site and its new domain changed to https://asuracomics.com/

Asuracomics Turkish source site became ArmoniScans

**Comment by KaizennSama** [comment]
You should look into this topic

**Comment by kyoyacchi** [comment]
> asurascans.com changed its domain on the English-language site and its new domain changed to [asuracomics.com](https://asuracomics.com/)

The English one and Turkish one has changed their domain.

Asura (EN) is https://asuratoon.com
And the Turkish one is https://armoniscans.com/
