### ISSUE TITLE
Desu was banned in Russia

### ISSUE THREAD

**Issue by XasyLame** [tachiyomiorg/tachiyomi-extensions#18026]
### Source information

Desu 1.4.23

### Source language

Russian

### Steps to reproduce

1. Opening Desu source
2. It doesn’t work

### Expected behavior

Opening this source provides all the mangas

### Actual behavior

It doesn’t work

### Tachiyomi version

0.14.6

### Android version

EMUI 12

### Other details

There’s actually a mirror for desu.me  —
desu.win which is available right now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
> Desu 1.4.23
> desu.win
![Screenshot_2023-09-18-23-28-45-36_5901a79de973a50c74cff4cbb6149856.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/35057681/71c4132b-a413-4ba0-bc0c-4aad4890feba)

![Screenshot_2023-09-18-23-28-52-37_c31b32364ce19ca8fcd150a417ecce58.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/35057681/43d6b00a-161a-46a2-94a9-edec70fcdbac)

**Comment by MikeZeDev** [comment]
May its no my place to answer but i think its not the job of tachiyomi to circumvent countries blocking. Its so time consuming.

Did you try the "DNS OVER HTTPS" option?  

If that doesnt work try a VPN. 🤷

**Comment by e-shl** [comment]
> May its no my place to answer but i think its not the job of tachiyomi to circumvent countries blocking. Its so time consuming.
> 
> Did you try the "DNS OVER HTTPS" option?  
> 
> If that doesnt work try a VPN. 🤷 

For convenience, when it is possible to change the domain and not use a VPN.
