### ISSUE TITLE
Golden mangás redirecting

### ISSUE THREAD

**Issue by Skyprak** [tachiyomiorg/tachiyomi-extensions#18038]
### Source information

Golden mangás 1.4.21

### Source language

Português (Brasil)

### Steps to reproduce

When entering a work and chapter from the aggregator it does not load and asks us to migrate to update the URL and when we try we cannot find the manga, even though the work is on the website, and when we enter the work's webview it shows the website's home page and not the manga.

![20230918_211913](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115963154/d38d9ac5-8283-4a05-ab0f-b6bed5dd6057)

![20230918_213316](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115963154/53b4582b-2dc9-42ef-8516-1a74da1c6e6b)

![20230918_211838](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115963154/a8b8fab3-d352-4f8b-b8ef-9a5b6e6567be)

### Expected behavior

opening of chapters and webview showing the manga page on the aggregator site

### Actual behavior

the chapters don't load, they ask for migration but don't find anything and the manga webview showing the website's home page

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They change their manga URLs constantly and there's nothing we can do about it.
