### ISSUE TITLE
mangaswat not working well

### ISSUE THREAD

**Issue by zrql** [tachiyomiorg/tachiyomi-extensions#18035]
### Source information

mangaswat 1.4.39

### Source language

arabic

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

not working at all

### Tachiyomi version

0.14.6

### Android version

emui 12

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all requested information. "Not working well" doesn't help with anything.
