### ISSUE TITLE
ShadowX

### ISSUE THREAD

**Issue by AbdoKhfagy** [tachiyomiorg/tachiyomi-extensions#18031]
### Source name

ShadowX

### Source link

https://shadowxmanga.com

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses Madara theme

**Comment by AbdoKhfagy** [comment]
So you can’t Add it because I use Madara Theme ???What about Mangalek or 3asq.org ???If it’s about the Child Theme “Madara MK” tell to find a solution.On 30 Sep 2023, at 3:28 PM, Vetle Ledaal ***@***.***> wrote:﻿
Uses Madara theme

**Comment by vetleledaal** [comment]
> So you can’t Add it because I use Madara Theme ???

Pretty much the opposite. It tends to be easier to add Madara sources since they are so similar to eachother.

**Comment by AbdoKhfagy** [comment]
Oh.. I get itBut when my website will appear as an extension on the app ?On 1 Oct 2023, at 8:01 PM, Vetle Ledaal ***@***.***> wrote:﻿

So you can’t Add it because I use Madara Theme ???

Pretty much the opposite. It tends to be easier to add Madara sources since they are so similar to eachother.

**Comment by vetleledaal** [comment]
> Oh.. I get itBut when my website will appear as an extension on the app ?

When someone have time and wants to work on it. There's no ETA.

**Comment by AbdoKhfagy** [comment]
Ok, thanks for the update.
I hope to get an update when it's published..

have a nice day

**Comment by vetleledaal** [comment]
Domain is parked
