### ISSUE TITLE
Extension crashed

### ISSUE THREAD

**Issue by Anothattha** [tachiyomiorg/tachiyomi-extensions#18043]
### Source information

Asura Scans

### Source language

English 

### Steps to reproduce

Reading manhwa:
Open extension
Open manhwa

### Expected behavior

Reading manhwa:
Opening manhwa, pages should load.

### Actual behavior

Reading manhwa:
When opening manhwa, it crashed and said HTTP error 404

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Migrate back to the new entry in Asura Scans again.

**Comment by Anothattha** [comment]
Is the new entry a new extension known as asura scans.us unoriginal?
Because if not asura scans even after updating to the latest version did
not work.
