### ISSUE TITLE
Golden Mangás: Changed their domain (again x2)

### ISSUE THREAD

**Issue by LucasRyuy** [tachiyomiorg/tachiyomi-extensions#18042]
### Source information

Golden mangás

### Source language

Português pt br

### Source new URL

https://goldenmanga.top/mangas?genero=Manhwa

### Other details

Pedindo para migrar
![Screenshot_20230918-222131_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145422272/e42cd5de-012f-410b-a38a-156353af56dc)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ruanss2000** [comment]
Acho estranho, que ao entrar na WebView primeiramente da um erro ou algo parecido, depois ele redireciona para o site normalmente, acho que isso pode estar causando algumas bugs, como cloudflare ou não atualizando a biblioteca dele
