### ISSUE TITLE
Support for imgchest (imgur alternative)

### ISSUE THREAD

**Issue by pseudotaken** [tachiyomiorg/tachiyomi-extensions#18057]
### Source name

imgchest

### Source link

https://imgchest.com

### Source language

English

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Way out of the scope of a manga reading app.

**Comment by curche** [comment]
fwiw, you can consider trying to request [Cubari](https://cubari.moe/) to support fetching images from that side, considering cubari already supports imgur and has a tachiyomi extension

how to contact or whether they'll add the feature, we do not know

**Comment by BrutuZ** [comment]
As for the last sentence: https://github.com/subject-f/cubarimoe
