### ISSUE TITLE
Covers on webtoons.com not showing properly

### ISSUE THREAD

**Issue by nobile01** [tachiyomiorg/tachiyomi-extensions#18054]
### Source information

Webtoons.com 1.4.40

### Source language

Multi

### Steps to reproduce

Force to refresh the series

### Expected behavior

To have a cover that actually shows the series' cover image

### Actual behavior

The cover is replaced by a banner with transparency in the middle, so the cover thumbnail is blank 

### Tachiyomi version

 0.14.6

### Android version

Android 13

### Other details

I'm guessing LINE Webtoons has updated their website, but now the cover is actually the banner, which always seems to be transparent in the middle, making all the thumbnails blank. 

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: TQ3A.230805.001.A1
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lord-ne** [comment]
I can still see the old cover on Webtoons in the corner of the website, so it may still be possible to make the extension retrieve it: 
![Screenshot_2023-09-20-23-12-45-840](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/34069872/23806ea7-0dfc-4c8c-b83c-16eaff8d30e3)

**Comment by SGaarden** [comment]
There does seem to be a thumbnail still on the site that is just the bottom right as @lord-ne showed. It is part of the background, but the thumbnail is 306x306.

Do note also that the new banner is only for Webtoons Originals, Webtoons Canvas seems to be unaffected.

**Comment by GeekinaCave** [comment]
in this [Webtoon ](https://www.webtoons.com/en/fantasy/i-was-the-final-boss/list?title_no=5170) for example the banner has this route in the webpage: 
https://webtoon-phinf.pstatic.net/20230310_286/1678397437524XOfBy_PNG/7IWastheFinalBoss_landingpage_desktop_fg.png but the thumbnail that we need to show has the route:
https://webtoon-phinf.pstatic.net/20230310_3/1678397413066QHyH1_JPEG/5IWastheFinalBoss_thumbnail_desktop.jpg
