### ISSUE TITLE
MangaSwat multi bugs

### ISSUE THREAD

**Issue by T3MYA11** [tachiyomiorg/tachiyomi-extensions#18050]
### Source information

MangaSwat 1.4.39

### Source language

Arabic 

### Steps to reproduce

first: after changing the url domain in the extension setting you can't update new chapters of any manga it just doesn't appear. 
second: there is a problems with showing latest manga and new add manga it just showing random mangas. 
third: and last bug is that the global search doesn't working you have to open the extension and search

### Expected behavior

first: it should showing the new chapters for the manga in the library
second: the latest button should showing the new chapters the same like the website. same thing for new add manga button
third: if i search for manga in global search and the extension had this manga is should appear 

### Actual behavior

first: there is problem with restricted access to the website because every now and then i have to reopen the WebView 
second: i think there is problem with the coding for latest button the same with new add manga
third: i think the global search problem is the same with restricted access to the website 

### Tachiyomi version

tachiyomij2k 1.6.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by T3MYA11** [comment]
now if i open the WebView of any manga in the library it takes me to the hom page

**Comment by T3MYA11** [comment]
![Uploading Screenshot_2023-09-22-05-12-30-483_eu.kanade.tachiyomi.j2k.jpg…]()

**Comment by MikeZeDev** [comment]
related #18083

**Comment by T3MYA11** [comment]
https://goldragon.me without the last (/) after.me fix it thanks

**Comment by Ammaralkaaki** [comment]
Not fixed yet as the new domain is https://goldragon.me/

**Comment by T3MYA11** [comment]
@Ammaralkaaki open the extension settings you will find option name (override baseUrl) click and put the url without the (/) after .me , now restart the app
also there was an update for the extension you need to do first

**Comment by Ammaralkaaki** [comment]
> @Ammaralkaaki open the extension settings you will find option name (override baseUrl) click and put the url without the (/) after .me , now restart the app also there was an update for the extension you need to do first

I did that unfortunately the manho and manga tiltes isn't directed  and only open the main web page.
