### ISSUE TITLE
biozinh doesn't work

### ISSUE THREAD

**Issue by sukuna0322** [tachiyomiorg/tachiyomi-extensions#18077]
### Source information

Biozimh.org 1.4.28

### Source language

Chinese

### Steps to reproduce

biozin extension does not work in the app, but in the webview it is normal.

### Expected behavior

open within the APP

### Actual behavior

open within the APP

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all requested information correctly and do provide any errors you're getting.
