### ISSUE TITLE
News releases of Golden Manga is broken

### ISSUE THREAD

**Issue by MansoBR** [tachiyomiorg/tachiyomi-extensions#18081]
### Source information

Golden Mangás 1.4.22

### Source language

Português

### Steps to reproduce

![Screenshot_20230921_082117_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145711541/5833e0d2-77a3-4edf-85e4-f2548345cb55)
![Screenshot_20230921_082054_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145711541/ad74c644-dc51-4c8a-8c7f-bd691c9eb91f)

### Expected behavior

This shoud show Theo releases

### Actual behavior

Don't show nothing

### Tachiyomi version

0.14.6

### Android version

11

### Other details

The other things work well. Just thia issue dont work. Theo block This.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Theuzin333** [comment]
> ### Fonte de informação
> Golden Mangás 1.4.22
> 
> ### Língua de origem
> Portugueses
> 
> ### Passos para reproduzir
> ![Screenshot_20230921_082117_Tachiyomi](https://user-images.githubusercontent.com/145711541/269726193-5833e0d2-77a3-4edf-85e4-f2548345cb55.jpg) ![Screenshot_20230921_082054_Tachiyomi](https://user-images.githubusercontent.com/145711541/269726201-ad74c644-dc51-4c8a-8c7f-bd691c9eb91f.jpg)
> 
> ### Comportamento esperado
> Este deve mostrar os lançamentos do Theo
> 
> ### Comportamento real
> Não mostres nada
> 
> ### Versão tachiyomi
> 0.14.6
> 
> ### Versão para Android
> 11
> 
> ### Outros detalhes
> As outras coisas funcionam bem. Apenas essa questão não funciona. Theo block Isto.
> 
> ### Agradecimentos
> * [x]  Eu procurei os problemas existentes e este é um novo ticket, **NÃO** duplicado ou relacionado a outro problema aberto ou fechado.
> * [x]  Escrevi um título curto, mas informativo.
> * [x]  Atualizei o aplicativo para a versão **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  Atualizei todas as extensões instaladas.
> * [x]  Eu tentei o [guia de solução de problemas](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  Se este é um problema com o aplicativo em si, eu deveria estar abrindo um problema no [repositório app](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  Preencha todas as informações solicitadas neste formulário.

I'm in the same problem as you.

**Comment by alessandrojean** [comment]
Closing as the source will be removed in a few days due to the cat and mouse game. Migrate to better sources.
