### ISSUE TITLE
Reader lock feature

### ISSUE THREAD

**Issue by candykelp** [tachiyomiorg/tachiyomi-extensions#18094]
### Describe why this should be added

A optional features on the reader which locks all other features other than tapzones so the user can solely focus on reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by candykelp** [comment]
Before i say anything heartful thanks to everyone who worked on tachiyomi for providing the best experience for reading manga on a screen. My only gripe with the application is the reader.As a person who spends most of my time in tachiyomi reading manga , there are some inconveniences that dents my experience such as misclicking the seekbar or accidentally zooming in.i think a lock feature can help create a immersive experience for many people.but it is but a minor issue rest assure i will never stop supporting this project

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

**Comment by candykelp** [comment]
sry my bad

**Comment by candykelp** [comment]
i'm still wet behind my ear
