### ISSUE TITLE
Golden mangás not working

### ISSUE THREAD

**Issue by ewertonns** [tachiyomiorg/tachiyomi-extensions#18098]
### Source information

Golden Mangás 1.4.22

### Source language

Portuguese

### Steps to reproduce

It is possible to read a chapter, but when updating the library an error occurs. "java.net.ProtocolException: Too many follow-up requests:21"

When accessing via "web view" you are redirected to the page "goldenmanga.top/erro.php" with the message access denied.

![golden manga 1](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/91988665/da1c243f-5cc4-40ca-ba04-efd84363ee61)
![golden manga](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/91988665/e030a298-c371-4cb0-a648-e0444ce2c121)

### Expected behavior

update the library

### Actual behavior

erro occurs

### Tachiyomi version

SY 1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as any new issues regarding this source will not be fixed since it will be removed by cat and mouse game. You should migrate to better sources at this time.
