### ISSUE TITLE
Manhua Plus no longer working

### ISSUE THREAD

**Issue by RazredgeBR** [tachiyomiorg/tachiyomi-extensions#18095]
### Source information

Manhua Plus 1.4.37

### Source language

English

### Steps to reproduce

The trying to load the source it gives a "No results found", same goes for searching.
Manhuas already in my list fail to load with the notification of "no pages found". And trying to refresh will result in "no chapters found".
Loading through "WebView" the page loads fine.
I've tried multiple different user agent strings, including desktop ones, all had the same result.

### Expected behavior

Should work, i.e. load chapters, pages, and be able to browse releases as well as search for specific manhuas.

### Actual behavior

Doesn't work. It doesn't load anything outside of WebView. No pages, no chapters, nothing.

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details

![Imagem do WhatsApp de 2023-09-22 à(s) 15 11 16](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/82561645/9dd0248c-e654-43d8-bb51-29211c140701)
![Imagem do WhatsApp de 2023-09-22 à(s) 15 11 17](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/82561645/3b17131a-cdd1-4509-bad2-779c8445645e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
There change site from .com to .org
![Screenshot_2023-09-23-03-10-35-52](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/79831076/b9cd7ab3-f632-4671-a3a6-a16388757763)

**Comment by conztanz045** [comment]
The extension broke because of redirect

**Comment by RazredgeBR** [comment]
Ah, I see. That would explain why WebView works, since it can handle redirect as opposed to the extension. Nonetheless, maybe this could be converted to a feature request to add the option of a fallback domain to .org when .com doesn't comply?

**Comment by xavyc** [comment]
> Ah, I see. That would explain why WebView works, since it can handle redirect as opposed to the extension. Nonetheless, maybe this could be converted to a feature request to add the option of a fallback domain to .org when .com doesn't comply?

Quite unlikely, as the .org domain doesn't even use the same theme as the .com domain.

In the .org domain they are currently using the liliana theme and image are loaded with ajax.

**Comment by I-Am-C0der** [comment]
I guess they will bring back the .com site once they resolve the issue as per their announcement in discord.

**Comment by I-Am-C0der** [comment]
Site issue is fixed and it is up and working now.

**Comment by xavyc** [comment]
Can confirm the extension is working now
