### ISSUE TITLE
Armoniscans

### ISSUE THREAD

**Issue by kaankapar** [tachiyomiorg/tachiyomi-extensions#18101]
### Source name

Armoniscans 

### Source link

https://armoniscans.com/

### Source language

Turkish

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by riship001** [comment]
i swap zksync eth to eth mainnet but fund is not receive my wallet 
i use symbiosis dex
txn id 0x50be87dc64e3b849ccdaa545cd42a22ce3d3800c491ca179b2067631e836d4c5
txn before 72 hours
