### ISSUE TITLE
Chapters in Pixiv series are in reverse order

### ISSUE THREAD

**Issue by DokterKaj** [tachiyomiorg/tachiyomi-extensions#18107]
### Source information

Pixiv

### Source language

All

### Steps to reproduce

1. Open any series in the Pixiv extension.
As an example, I'll use [this series](https://www.pixiv.net/user/52200937/series/107622), which you can find in the extension by searching up one of the names of its chapters, e.g. "The Last Festival".

### Expected behavior

Chapters should be listed in the correct order.
With the example, assuming chapters are sorted by chapter number in descending order, the top chapter should be numbered Chapter 12 and have the source title "Ch. 12 To The Wedding!", while the bottom chapter should be numbered Chapter 1 and have the source title "Ch. 1 The Last Festival".

### Actual behavior

Chapters are listed in reverse order starting from Chapter 0.
With the example, although chapters are sorted by chapter number in descending order, the top chapter is numbered Chapter 11 and has the source title "Ch. 1 The Last Festival", while the bottom chapter is numbered Chapter 0 and has the source title  "Ch. 12 To The Wedding!".

### Tachiyomi version

0.14.6

### Android version

EMUI 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Solitai7e** [comment]
Cannot reproduce.

[video.webm](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/60846439/dbbd0e8c-d05b-4f41-87a8-53188d6d62dd)

**Comment by DokterKaj** [comment]
> Cannot reproduce.

Are your sort settings set to descending by chapter number?

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/54882101/40b93d7e-11e9-4244-8b62-a0fec8c687f5

**Comment by Solitai7e** [comment]
Ok I did not know those settings were there I see what's going on now.
