### ISSUE TITLE
Changed Domain Golden Mangas(again)

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#18117]
### Source information

Golden Mangás 1.4.22

### Source language

Português

### Steps to reproduce

error bypassing cloudflare

### Expected behavior

should enter normally

### Actual behavior

error when entering

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

the link to enter is back in Golden Mangas back to: https://goldenmanga.top/

you need to remove the "www" from the link

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Just to clarify: we won't fix anything related to Golden as the extension will be removed soon. We recommend migrating to better sources instead.
