### ISSUE TITLE
Monarca Manga site closed

### ISSUE THREAD

**Issue by Omaeda** [tachiyomiorg/tachiyomi-extensions#18112]
### Source name

MonarcaMnga

### Source language

Spanish

### Source link

monarcamanga.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Its up ? 
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/10671518/7543279a-9174-4690-8008-410907f42fd4)
