### ISSUE TITLE
Mangalek: Changed their domain

### ISSUE THREAD

**Issue by hamdyahmed18** [tachiyomiorg/tachiyomi-extensions#18124]
### Source information

مانجا ليك 1.4.33

### Source language

Arabic

### Source new URL

https://mangaleku.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedosama12345** [comment]
hmm... this link too leads to the same site:
https://manga-lek.net/

**Comment by MikeZeDev** [comment]
People mentioned https://manga-lek.org/ too. what a mess .

**Comment by hamdyahmed18** [comment]
> People mentioned https://manga-lek.org/ too. what a mess .

The two links leads to the same sites but this (https://mangaleku.com/) is the Main link

**Comment by MikeZeDev** [comment]
I dont think so. Mangas on frontpage are differents, layout is different, no redirection. Its not the same site, those may be mirrors but how do you know which one is main?

**Comment by hamdyahmed18** [comment]
> I dont think so. Mangas on frontpage are differents, layout is different, no redirection. Its not the same site, those may be mirrors but how do you know which one is main? 
> 
> 

If you go to both Websites right now, you'll see that chapters on (https://mangaleku.com/) are being updated before those on (https://manga-lek.net/).

**Comment by BMask69** [comment]
Sorry for being out of line here to ask you to make this a priority
This is the main source for alot of Arab
At least the veterans of them leave the noobs aside
I waited a weak for the things that was a high priority in your list
And now iam asking to make this one 😅
And thanks for your hard work
