### ISSUE TITLE
Too many follow-up request

### ISSUE THREAD

**Issue by PeterPGS** [tachiyomiorg/tachiyomi-extensions#18121]
### Source information

Golden Mangás 1.4.22

### Source language

Portuguese 

### Steps to reproduce

Just update with mangas of that source

### Expected behavior

Update The library of mangas

### Actual behavior

java.net.ProtocolException: Too many follow-up requests: 21
  # Golden Mangás (PT-BR)

### Tachiyomi version

1.6.6 of TachiJ2K (last update)

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as any issues related to Golden won't be fixed as it will be removed by cat and mouse game. Migrate to better sources instead.
