### ISSUE TITLE
Website update issue

### ISSUE THREAD

**Issue by RiShin2132** [tachiyomiorg/tachiyomi-extensions#18131]
### Source name

Golden Mangá

### Source language

Portuguese (br)

### Describe your suggested feature

The source's website has a new security feature, which means that the manga in the app can be read but not updated.
 When trying to access the source the following message appears: java.net.ProtocolException: Too many follow-up requests: 21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as any Golden issue won't be fixed as it will be removed by cat and mouse game. Migrate to better sources instead.
