### ISSUE TITLE
Manhwatop unable to parse

### ISSUE THREAD

**Issue by QuintonDF** [tachiyomiorg/tachiyomi-extensions#18133]
### Source information

Manhwatop 1.4.33

### Source language

English

### Steps to reproduce

1. Try to read or browse on the source 

### Expected behavior

Manhwa loads up normally to read or to browse 

### Actual behavior

A error stating "javax.net.ssl.SSLExecption: unable to parse TLS packet header

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>A error stating "javax.net.ssl.SSLExecption: unable to parse TLS packet header

usually means your connection blocks the site, and fixed by something in the troubleshooting guide. please do what you acknowledge.
