### ISSUE TITLE
Yugenmangas and Sinensis Scan appears without pages

### ISSUE THREAD

**Issue by gatinhecomunista** [tachiyomiorg/tachiyomi-extensions#18143]
### Source information

Yugen Mangas - Português & Sinensis Scan - Português

### Source language

Português

### Steps to reproduce

When I open a chapter that has just been updated, whatever the work, it appears without pages, I can't open the chapter, it keeps giving me this error. But it is not a scan error, since the work is there with all the pages, it is from the app that this is coming. The chapters just don't open

### Expected behavior

When you click to read the chapter, the chapter opens and you can view the pages

### Actual behavior

Does not open the chapter and says it has no pages

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source, otherwise it keeps difficult to keep track on what have been addressed and what not.
