### ISSUE TITLE
manga lek domain name change

### ISSUE THREAD

**Issue by AhmedSamir899** [tachiyomiorg/tachiyomi-extensions#18154]
### Source information

مانجا ليك 1.4.33

### Source language

arabic

### Source new URL

https://manga-lek.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18124.
