### ISSUE TITLE
Asura scans changed its domain

### ISSUE THREAD

**Issue by ManiV97** [tachiyomiorg/tachiyomi-extensions#18153]
### Source information

all.asurascans 1.4.52

### Source language

English

### Source new URL

https://asuracomics.gg/

### Other details

Asura scans changed its domain from https://asuracomics.com/ to https://asuracomics.gg/
Please update the extension.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Zaperex** [comment]
Already fixed in https://github.com/tachiyomiorg/tachiyomi-extensions/pull/18150
