### ISSUE TITLE
Golden mangas dont work

### ISSUE THREAD

**Issue by jonhcobra** [tachiyomiorg/tachiyomi-extensions#18152]
### Source information

Golden mangas 1.4.22

### Source language

Pt-br

### Steps to reproduce

opening the golden mangas source, it keeps loading, and then the message "no results found" appears, when opening in web view it says "access not permitted".
![Screenshot_2023-09-25-15-56-16-471_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/131981755/a810a0c9-d359-41de-ab75-8f8f355983a9)

### Expected behavior

Open The source and show the list of mangas

### Actual behavior

Dont open

### Tachiyomi version

0.14.6 and 0.16.6-6064

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as any issue related to Golden won't be fixed as the extension will be removed by cat and mouse game. Migrate to better sources instead.

**Comment by jonhcobra** [comment]
Dont removed This extension,she back to work

**Comment by ewertonns** [comment]
Dont remove the extension. Its working now

**Comment by alessandrojean** [comment]
It will be removed anyway because they're explicitly targetting things to break the extension. Even if it works now it will soon start having errors again, it's a fact. Just migrate to better sources.
