### ISSUE TITLE
مانجا لينك

### ISSUE THREAD

**Issue by zrql** [tachiyomiorg/tachiyomi-extensions#18160]
### Source information

مانجا لينك 1.4.34

### Source language

Arabic 

### Source new URL

https://manga-like.net/mangalink/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18124
