### ISSUE TITLE
Manhwa18.cc: Images Are not Loading

### ISSUE THREAD

**Issue by Mohak-Singh** [tachiyomiorg/tachiyomi-extensions#18163]
### Source information

Manhwa18.cc 1.4.35

### Source language

Multi

### Steps to reproduce

I am not able to view any chapters from this source. It just Displays the message - "The image can't be loaded".

I am also not able to download any chapters as well.

### Expected behavior

It should just display the images and download the chapters.

### Actual behavior

No images get loaded, and no chapters get downloaded.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Can't reproduce this issue, for which manhwa it doesn't work ?

**Comment by Mohak-Singh** [comment]
It's not working for any of them.
This is the error. After this it doesn't even move
![photo_2023-09-26_16-36-09](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/126738368/4acce2d5-2087-404e-8e84-6bd15c634700)

**Comment by vetleledaal** [comment]
I also can't reproduce this issue, including for "Unlock Her Heart". I tried with both desktop and mobile user-agents. Maybe [clearing the cache/cookies/database](https://tachiyomi.org/docs/guides/troubleshooting/diagnosis#primary-diagnosis) would help?

**Comment by Mohak-Singh** [comment]
Wait! Its working now.
