### ISSUE TITLE
مانجا سبارك changed their url

### ISSUE THREAD

**Issue by zrql** [tachiyomiorg/tachiyomi-extensions#18169]
### Source information

mangaspark 1.4.34

### Source language

arabic

### Source new URL

https://mangaspark.org/net/

### Other details

HTTP error 404

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by iBloox** [comment]
Close this issue because it has a wrong domain or change the extension to the right domain which is "https://mangaspark.org/"

**Comment by abde928** [comment]
Change the source to 
https://mangaspark.org/
