### ISSUE TITLE
MangaSwat URL changed

### ISSUE THREAD

**Issue by firstdarsh** [tachiyomiorg/tachiyomi-extensions#18175]
### Source information

Manga Swat 1.4.39

### Source language

Arabic

### Source new URL

https://goldragon.me/

### Other details

The website has changed 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by salah2021ss** [comment]
@arkon error still exist

**Comment by GintokiMyk** [comment]
Mangaswat 404 error
