### ISSUE TITLE
Yugenmangas No Pages

### ISSUE THREAD

**Issue by Zer03021** [tachiyomiorg/tachiyomi-extensions#18176]
### Source information

YugenMangas 1.4.26

### Source language

Español

### Steps to reproduce

1. Open the Extensión
2. Select any Manhwa
3. try to read any chapter

### Expected behavior

chapter should be displayed

### Actual behavior

![Screenshot_2023-09-26-10-00-59-990_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/94061318/e47bac95-093d-42fc-8199-76a6f60474ac)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by VannevarB** [comment]
There was a change in the domain, from .net to .lat . There was no announcement of the reasons yet.
