### ISSUE TITLE
MangaSwat: no results found

### ISSUE THREAD

**Issue by AbdUlrahman097** [tachiyomiorg/tachiyomi-extensions#18183]
### Source information

ar.MangaSwat 1.4.39

### Source language

"Arabic"

### Steps to reproduce

1. Try to open the source
2. "No results found" will appear
3. If any chapters are be found, it Will not be opened.

### Expected behavior

The manhwa should show up and work

### Actual behavior

"no results found" shows up and the manhwas are not opening.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by salah2021ss** [comment]
I have the same issue but when i open viewbrowser it open google search not manga swat web, i think its url issue

**Comment by Seishirou101** [comment]
probably related to #18175

**Comment by AbdUlrahman097** [comment]
The problem still exists even after changing the domain
