### ISSUE TITLE
InariManga it's not working, webview is normal

### ISSUE THREAD

**Issue by Lanyxx** [tachiyomiorg/tachiyomi-extensions#18206]
### Source information

InariManga 1.4.32

### Source language

Spanish

### Steps to reproduce

1. Open the extension
2. Search for a title

![Screenshot_20230925_174150_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/87540723/220d5f62-bc4e-4a8b-900e-9f8af48ff566)

### Expected behavior

Works should appear when the extension is open.

### Actual behavior

The works do not appear in the app, only in the webview.

![Screenshot_20230925_174202_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/87540723/248683cc-d930-4804-9e74-465082b892a8)

### Tachiyomi version

1.7.1 (TachiJ2K)

### Android version

Android 13

### Other details

The page was down for a while due to maintenance, but it's back now. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
site was removed in #17978, so it will need to be added back on top of being fixed to work.
