### ISSUE TITLE
Asura Scans downloads get stuck at last page

### ISSUE THREAD

**Issue by touhidurrr** [tachiyomiorg/tachiyomi-extensions#18204]
### Source information

Asura Scans 1.4.56

### Source language

English

### Steps to reproduce

Download any chapter from any novel.

### Expected behavior

The chapter downloads completes without issues in most cases.

### Actual behavior

Every chapter from every novel gets stuck while downloading the last page and the download is never marked as completed.

### Tachiyomi version

Preview r6071, 0.14.6-6071 (standard, afb1ee220, 106, 2023-09-30T21:07Z)

### Android version

Android 11 (SDK 30)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Can't reproduce on like 50 or so chapters (that i read in the last 2 days)

**Comment by Jerrk** [comment]
i also have this issue.
![Screenshot_20231001_075408_TachiyomiJ2K.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/49324581/984cb42e-517f-40f8-bd3e-2402cff1eac6)

![Screenshot_20231001_075421_TachiyomiJ2K.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/49324581/26f22eed-c37a-44d1-9c91-4a2f3697bee3)

**Comment by AntsyLich** [comment]
Loads fine for me on that exact chapter.

![Screenshot_20231001-115720](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/59261191/66c3a348-403b-4540-a75a-55e91aed4eae)

**Comment by touhidurrr** [comment]
@AntsyLich,  try downloading new chapters.

**Comment by AntsyLich** [comment]
The 50 or so chapters that I read are new chapters.

**Comment by Jerrk** [comment]
could it have something to do with the last page having a redirect on it?

idk why that would make it show for some but not for others

**Comment by touhidurrr** [comment]
> could it have something to do with the last page having a redirect on it?
>
> idk why that would make it show for some but not for others though

I have a high speed internet and I tried with or without vpn. As you can see from the screenshots, the last page is downloaded. However, the download is still not being completed.

**Comment by touhidurrr** [comment]
**UPDATE:** Fixed after updating the app and extension version.

**Comment by Jerrk** [comment]
i completely missed what version you were using, im using [tachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K) which is currently on 1.7.1 and i am getting this issue.

ill probably open a different issue on the fork asking about this.

**Comment by touhidurrr** [comment]
@Jerrk I use the default tachiyomi version. I think the extension update might have fixed this for me. Maybe you should check your extension version and compare it with me?
My extension version is: **1.4.56**

**Comment by Jerrk** [comment]
Unfortunately i have that same extension version and the issue still persists

**Comment by touhidurrr** [comment]
> Unfortunately i have that same extension version and the issue still persists

Forgot to mention, but I also invalidated my download index. Maybe try that also.

**Comment by Jerrk** [comment]
Apperas to be fixed for me now as well.

i cleared most of the caches and updated to the 1.7.2 beta.
