### ISSUE TITLE
Comictoon

### ISSUE THREAD

**Issue by Wipwib** [tachiyomiorg/tachiyomi-extensions#18233]
### Source name

Comictoon

### Source language

Thai

### Source link

https://comictoonthaith-new.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by T3MYA11** [comment]
if you have a lot of dead sources to report, please go back and submit a single meta request
