### ISSUE TITLE
Manga starz

### ISSUE THREAD

**Issue by Jo12121** [tachiyomiorg/tachiyomi-extensions#18297]
### Source information
Manga Starz 1.4.36

### Source language

Arabic

### Source new URL

https://mangastarz.org/

### Other details

Didn't open the right site

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL is not updated yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Duplicate of #17917
