### ISSUE TITLE
Ozul Scans true url 

### ISSUE THREAD

**Issue by T3MYA11** [tachiyomiorg/tachiyomi-extensions#18299]
### Source information

ozulscans 1.4.27

### Source language

Arabic 

### Source new URL

https://ar-ozulscans.com/

### Other details

https://ozulscans.xyz/ is another website for the same team of "ozulscans" but it goes with the name (ozulshojo) they're different sites with different types of manga.
the right new one is https://ar-ozulscans.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Cainr01** [comment]
Ah when they fixed this bug tag me

**Comment by T3MYA11** [comment]
okay now the owner of the website changed the domain and the name of the website to ( https://kingofmanga.com) it works fine now , i don't know if you should change the extension name or not it's up to you , but every thing working fine right now

**Comment by T3MYA11** [comment]
update, the manga in my library is updated just fine but i can't search or open latest manga in extension, the WebView working fine
