### ISSUE TITLE
Jiangzaitoon: Changed their domain

### ISSUE THREAD

**Issue by Anokyai** [tachiyomiorg/tachiyomi-extensions#18293]
### Source information

Jiangzaitoon 1.4.33

### Source language

Turkish 

### Source new URL

https://jiangzaitoon.cc/

### Other details

![IMG_20231001_160043](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146554683/f3e99d15-c226-4398-877f-1e42b56aed2b)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
It'll be changed when someone feels like changing it

**Comment by erenoner** [comment]
neredeyse 1 ay oldu herhangi bir gelişme yok offff

**Comment by yaoihentanime** [comment]
Birileri artık birşey yapabilir mi?

**Comment by erenoner** [comment]
> Birileri artık birşey yapabilir mi? 

elimden gelse ben yapicamda hicbir bilgim yok kodlamayla ilgili

**Comment by yaoihentanime** [comment]
Açık kodlama olsa en azından biesy yapılır belki böyle alan adı değişimlerinde ama o da yok

**Comment by erenoner** [comment]
ayarlara domain değiştiğinde düzeltebilecegimiz bir sey eklenmesi mumkun bildiğim kadariyla bazi tachiyomi eklentilerinde mevcut bu konuyla ilgilenecek biri yok mudur

**Comment by yaoihentanime** [comment]
sonunda geri geldi
