### ISSUE TITLE
Azora not working properly 

### ISSUE THREAD

**Issue by Bakir-San** [tachiyomiorg/tachiyomi-extensions#18303]
### Source information

Azora 1.4.37

### Source language

Arabic 

### Steps to reproduce

Work normally on wep view
But when trying to open chapters in the app
Give me this error
![Screenshot_2023-10-01-22-06-20-374_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92395726/e58887e3-ad4e-4ed1-965e-88f94520e674)

### Expected behavior

Should open like always 

### Actual behavior

Give me this error
![Screenshot_2023-10-01-22-06-20-374_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92395726/ef4499c8-d527-4cee-aae6-11a71b079ffb)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Closing in favor of #19128
