### ISSUE TITLE
مانجا ليك لا يعمل HTTP error 404

### ISSUE THREAD

**Issue by Ahmad7sa** [tachiyomiorg/tachiyomi-extensions#18307]
### Source information

مانجا ليك 1.4.34

### Source language

Manga lek error 404

### Steps to reproduce

HTTP error 404
![Screenshot_٢٠٢٣١٠٠١-٢٣٣١١٨_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146676669/f6b26bac-88dd-47f9-978d-69824ae7dd57)

### Expected behavior

![٢٠٢٣١٠٠١_٢٣٣٣٣٥](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146676669/c37b221a-d31d-450b-80d8-efdf56a0ba97)

### Actual behavior

![Screenshot_٢٠٢٣١٠٠١-٢٣٣١١٨_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146676669/cb246120-1097-4a8e-9539-bd63ee8e6ba8)

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by iBloox** [comment]
The website changes the domain to 
https://manga-like.net/

**Comment by Seishirou101** [comment]
#18124
