### ISSUE TITLE
MangaToon (Limited)

### ISSUE THREAD

**Issue by KatoMegushua** [tachiyomiorg/tachiyomi-extensions#18310]
### Source information

MangaToon (Limited) 1.4.4

### Source language

Multi language

### Steps to reproduce

1 open a manhua
2 read the manhua
3 All the pages of all the manhuas are displayed with the logo of the extension.

### Expected behavior

1 install the extension
2 use the extension
3 Read all extension manhuas

### Actual behavior

1 install the extension
2 use the extension
3 No page of any manhua shows an image 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

This is what appears in all the extension titles

![Screenshot_20231001_161214_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/ef72d0ee-f532-4933-9d60-af747e4fdc53)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by christmovies** [comment]
Install- preview
