### ISSUE TITLE
Asura Scans Http error 404 issue

### ISSUE THREAD

**Issue by Kritti0** [tachiyomiorg/tachiyomi-extensions#18313]
### Source information

Asura Scans 1.4.56

### Source language

English, turkce

### Steps to reproduce

![Screenshot_2023-10-02-06-37-51-198_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146683908/8671c5f7-d6a1-43a2-85ed-5197bae9d0fe)
![Screenshot_2023-10-02-06-38-40-087_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146683908/7a171133-44b4-4cb6-a68c-9be44fbe99bf)

**_few of the books from asura scans are working but mos of them are always showing http error 404 I tried to see in the webview if the book is available in the website and then clear cookies still nothing changed and I tried to wait for new update still no change i tried reinstalling nope and it's one of my most favorite extensions _**

The main issue is that when I want to read it always show's http error 404

### Expected behavior

I don't know other than http error 404 everything is perfect actually 

### Actual behavior

Few of the books from asura scans are working but most of them are always showing http error 404 I tried to see in the webview if the book is available in the website and then clear cookies still nothing changed and I tried to wait for new update still no change i tried reinstalling nope and it's one of my most favorite extensions

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 13 (SDK 33) Android build ID: TKQ1.221114.001 test-keys Device brand: Redmi Device manufacturer: Xiaomi Device name: spes Device model: 2201117TI Device product name: spes_in

### Android version

Android 13

### Other details

Don't have any actually

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kritti0** [comment]
I'm sorry if it's not details are not enough I tried expressing everything I know if possible please solve this 😭😭

**Comment by daminokun** [comment]
Try migrating the title back to asurascan. That always fix the problem when it happen to me

**Comment by AntsyLich** [comment]
Enable permanent URL from extension settings
