### ISSUE TITLE
Mangadistrct suddenly timeout error 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#18329]
### Source information

Manga District 1.4.33

### Source language

English

### Steps to reproduce

Suddenly none of the saved manwha from mangadistrct doesn't work 

### Expected behavior

Usually opens regularly 

### Actual behavior

Suddenly none of chapter loads
![Screenshot_2023-10-03-00-21-27-45_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/8ccadb48-a194-402d-a7d3-9a70b6488eb6)
But works on web page 

### Tachiyomi version

R6071

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Check if you haven't seen a cached page in the browser, try searching for something in their site to check if it's not offline.

**Comment by Hawksaran** [comment]
Website works fine and in tachiyomi it was working fine before half and hour now only it doesn't load ....

> Check if you haven't seen a cached page in the browser, try searching for something in their site to check if it's not offline.

**Comment by alessandrojean** [comment]
Just checked, just try to search something directly in their site and nothing will load, so it's down.

Nothing we can do in this case, so closing. Wait until they fix it.
