### ISSUE TITLE
[Source Request] blkom Arabic 

### ISSUE THREAD

**Issue by ethi** [tachiyomiorg/tachiyomi-extensions#1832]
### Source Website
Website can be found at <https://manga.blkom.com/>.

**Comment by as280093** [comment]
Here is the icons: 
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3916455/ic_launcher.1.zip)

**Comment by yshalsager** [comment]
@ethi is this website still being updated? Seems like all popular manga are way outdated.
