### ISSUE TITLE
Mangamanhua source is down

### ISSUE THREAD

**Issue by vsavenok** [tachiyomiorg/tachiyomi-extensions#18335]
### Source name

MangaManhua

### Source language

English

### Source link

https://mangamanhua.online

### Other details

Starting 10/01/2023, Mangamanhua extension was returning 404 error. Upon going to the source website, the following error returned.
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/5033543/df3204f4-eb2e-4eb2-9610-51b5bcbffe56)
It might be permanent or they changed domain, it's hard to tell.

Thank you!

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The site now redirects to mangaonlineteam.com which is already available through the extension "Manga Online Team".

The MangaManhua extension can safely be removed.
