### ISSUE TITLE
Mangalek domain change

### ISSUE THREAD

**Issue by Bmswad1** [tachiyomiorg/tachiyomi-extensions#18336]
### Source information

مانجا ليك 1.4.33

### Source language

العربية

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Tachiyomi version

TachiyomiSY 1.9.3

### Android version

Android 12

### Other details

Mangalek domain changed to https://manga-lek.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as this isn't the right issue form to report this kind of issue and there's already open issues for it.
