### ISSUE TITLE
Sekaikomik change domain

### ISSUE THREAD

**Issue by PayLater666** [tachiyomiorg/tachiyomi-extensions#18338]
### Source information

Sekaikomik 1.4.36

### Source language

Indonesia

### Source new URL

https://sekaikomik.bio/

### Other details

Change domain

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by CrazyGamerIE** [comment]
It's already 1 month:''"'D
