### ISSUE TITLE
Changed Domain: Cerise Scan 

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#18344]
### Source information

Cerise 1.4.37

### Source language

Português

### Source new URL

https://cerisescan.com/

### Other details

 
![Screenshot_20231003-101212110](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90201611/b3028856-8114-4b3f-9578-7718997abbbd)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Clear the cover cache in the advanced settings and migrate any old entries in your library back to the same extension. They change the manga URLs constantly and there's nothing we can do about it besides suggesting using other sources that doesn't do this.
