### ISSUE TITLE
[Source Request] 嗶咔漫畫PicACG

### ISSUE THREAD

**Issue by 2333tql** [tachiyomiorg/tachiyomi-extensions#1834]
### Source Website
Website can be found at <https://www.picacomic.com/>.

### Other Details

**Comment by SnakeDoc83** [comment]
Is there manga on their website?  All I see are links to apps.

**Comment by lfkdsk** [comment]
@2333tql @SnakeDoc83

**Comment by as280093** [comment]
Here is the Icons: 
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3916430/ic_launcher.zip)

**Comment by lan23333** [comment]
any updates on this?
