### ISSUE TITLE
TAO SECT 

### ISSUE THREAD

**Issue by Mynameluis** [tachiyomiorg/tachiyomi-extensions#18356]
### Source information

Tao sect 1.4.19

### Source language

PT br

### Steps to reproduce

![Screenshot_20231003-194554](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145807935/e4ba09f8-96c7-4165-a373-b1e9189362ba)

### Expected behavior

![Screenshot_20231003-194843](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145807935/0b2aa968-e3be-4f8f-8a35-d99c5fbed964)

### Actual behavior

![Screenshot_20231003-194554](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145807935/5ee1f472-0e97-4ff0-914c-b4c8504574e0)

### Tachiyomi version

App version: 0.14.3-6151 (standard, 43e8dcd1f, 94, 2023-06-15T08:44Z) Android version: 10 (SDK 29) Android build ID: QPZS30.30-Q3-38-69-12 Device brand: motorola Device manufacturer: motorola Device name: guam Device model: moto e(7) plus Device product name: guam_retail

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The error already says what you need to do and it isn't something we can fix as they host stuff on Google Drive which has a daily viewing limit. It might be working on a browser because you likely is signed in in a Google account which helps into bypassing it.
