### ISSUE TITLE
MANGA Plus: `MissingFieldException`

### ISSUE THREAD

**Issue by aniforprez** [tachiyomiorg/tachiyomi-extensions#18358]
### Source information

MANGA Plus by SHUEISHA 1.4.44

### Source language

English

### Steps to reproduce

1. Try to fetch any title hosted on Manga Plus or browse titles on the site

### Expected behavior

Extension should fetch the new chapters for a title or give the list of titles when browsing them from the extension page

### Actual behavior

Fetching new chapters for a title shows a toast with `MissingFieldException` and trying to browse titles shows the error screen with the stacktrace.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

This seems to arise because there is no more `landscapeImageUrl` being sent on the list of titles being fetched from the API which it expects. Removing [this line](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusDto.kt#L127) might help sort it out but I'm not 100% sure 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DarkenedOrigins** [comment]
+1

My error output:

! Field 'landscapeImageUrl' is required for type with serial name 'eu.kanade.tachiyomi.extension.all.mangaplus.Title', but it was missing at path: $.success.titleDetailView.title at path: $.success.titleDetailView.title at path: $.success.titleDetailView.title at path: $.success.titleDetailView.title
  # MANGA Plus by SHUEISHA (EN)

**Comment by alessandrojean** [comment]
Just a warning for everyone who commented, stop doing `+1` to bump the issue as it won't help with anything.
