### ISSUE TITLE
Add drop/abandon option for a series

### ISSUE THREAD

**Issue by tgoel-dev** [tachiyomiorg/tachiyomi-extensions#18357]
### Describe why this should be added

I just want a feature that allows me to mark a series as "dropped/abandoned," but still stay within my library. The series could then not be updated during the routine updates. 
The option could be added to the menu at the top-right, alongside Migrate and Share. Remaining chapters could simply show a "--" to indicate that the series has been dropped, and not fully read.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.

Also, can just use a category for it and exclude from the global update in the settings.
