### ISSUE TITLE
Every time I open an extension I get error 429, where it won't let me use it or save any manga

### ISSUE THREAD

**Issue by Moroxo3** [tachiyomiorg/tachiyomi-extensions#18389]
### Source information

TMOHentai 1.4.7

### Source language

Español

### Steps to reproduce

1. I enter Tachiyomi 2. I go to the TMOHentai extension.  3.When I enter I get error 429 and no manga appears.  4. In the mangas saved by that extension it doesn't let me enter to see them either

### Expected behavior

It should let me enter the extension and be able to save sleeves correctly

### Actual behavior

It won't let me enter the TMOHentai extension or save mangas

### Tachiyomi version

0.14.6

### Android version

Huawei Y9 prime 2019

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
HTTP 429 means many requests are being done to the source. Try spreading your library into more sources to avoid using this one too much.
