### ISSUE TITLE
MyReading Manga

### ISSUE THREAD

**Issue by Nebulavargas** [tachiyomiorg/tachiyomi-extensions#18383]
### Source name

MyReading Manga

### Source language

Turkish 

### Source link

https://myreadingmanga.info/

### Other details

Source is down and website is closed. 

![IMG_20231005_133513](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146843923/35a8d53c-46a0-4085-ab9b-f4a0beac3351)

![IMG_20231005_133502](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146843923/8d22d368-8688-496f-a0fe-d6f7f21a2ec0)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
loads fine for me, considering this is your 2nd report, either you just couldn't connect to this site or your isp is blocking it.
