### ISSUE TITLE
nHentai.com (unorginal)

### ISSUE THREAD

**Issue by Nebulavargas** [tachiyomiorg/tachiyomi-extensions#18384]
### Source name

nHentai.com (unorginal) 

### Source language

Turkish 

### Source link

https://nhentai.com/home

### Other details

The Turkish source of this site has been closed.

![IMG_20231005_134040](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146843923/7da57d0b-0327-4b6a-808d-6305f2645a1f)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
loads fine for me, considering they're all the same url its probably just using a filter for turkish. you can ask on discord for more help.
