### ISSUE TITLE
Change title  of name of site of swat

### ISSUE THREAD

**Issue by Mahmoudpop800** [tachiyomiorg/tachiyomi-extensions#18386]
### Source information

https://goldragon.me/

### Source language

Arabic 

### Steps to reproduce

https://goldragon.me/.      Is new name of site
Old was  swat 
Change it

### Expected behavior

من أسبوع لم يفتح الموقع

### Actual behavior

يجب تغير معرف اسم الموقع 

### Tachiyomi version

0.14.6

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment]
هم ما غيروا اسم الموقع
فقط الدوماين

**Comment by Otakyora** [comment]
> هم ما غيروا اسم الموقع
> فقط الدوماين

صار هذا https://goldragon.me/

**Comment by curche** [comment]
The extension now uses the new domain. It also already includes an extension setting to change the domain manually by the user.

See #18175
