### ISSUE TITLE
Manga-Scan (FR) - Pages doesn't load

### ISSUE THREAD

**Issue by ElCacciatore** [tachiyomiorg/tachiyomi-extensions#18395]
### Source information

Manga-Scan (FR) 

### Source language

French

### Steps to reproduce

Load a manga
Open a chapter

### Expected behavior

Pages load and we can read

### Actual behavior

Pages doesn't load, we can't read on the app

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Ah website changed URL.
