### ISSUE TITLE
Asterisks in chapter names are removed when using the MangaDex extension

### ISSUE THREAD

**Issue by DokterKaj** [tachiyomiorg/tachiyomi-extensions#18407]
### Source information

MangaDex 1.4.188

### Source language

All

### Steps to reproduce

Open a series with a chapter that has asterisks in its name, e.g. [this one](https://mangadex.org/title/f4247b21-e8ff-46ae-9f92-fc04f6641188/aitsu-no-kanojo).

### Expected behavior

The chapter name should be displayed properly.

### Actual behavior

The asterisks in the chapter name are removed.

### Tachiyomi version

0.14.6

### Android version

EMUI 12

### Other details

![Screenshot_20231006_231810_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/54882101/da47704e-623c-42ac-a254-a629ab0d4043)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Funnily enough, there's a [chapter](https://mangadex.org/chapter/edb9793d-2748-44af-b5fa-18f141cadfbf) with just `*` as its title, and that shows up fine
