### ISSUE TITLE
Night scan http error open web view

### ISSUE THREAD

**Issue by 12vince12** [tachiyomiorg/tachiyomi-extensions#18416]
### Source information

1.4.28

### Source language

English

### Steps to reproduce

I troubleshoot it and diagnose the problem but the web view is fine but not the source itself

### Expected behavior

Expected to load the manga/manhwa's/manhua on the extension source but no problem on web view only the extension

### Actual behavior

No source but http error i tried the web view but it was okay there but the extension itself is broken

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

That is the issues

![Screenshot_2023-10-07-08-01-25-085](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145286161/d303dc69-8879-4ef3-843f-617e4a1bf9ce)
![Screenshot_2023-10-07-08-01-29-549](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145286161/492dad6e-d396-4df1-a26b-200b152e2485)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
its working for me. try troubleshoot
