### ISSUE TITLE
Falha ao contornar cloudflare

### ISSUE THREAD

**Issue by Luzphy** [tachiyomiorg/tachiyomi-extensions#18421]
### Source information

Golden Mangas

### Source language

Português Br

### Steps to reproduce

Falha ao contornar clouflare

### Expected behavior

Deveria voltar com uns dias 

### Actual behavior

Não voltou e ainda estar com problemas 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
