### ISSUE TITLE
Toonkor need to change default URL 

### ISSUE THREAD

**Issue by NeKoOuO** [tachiyomiorg/tachiyomi-extensions#18430]
### Source information

Toonkor 1.4.4

### Source language

Korean 

### Source new URL

https://toonkor296.com

### Other details

The default URL has no longer work anymore
Needs change thx 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
Toonkor always change their domain , there already option to change domain in extension setting, just put new link domain and restart the app 
 
![Screenshot_20231008-194121453](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/101858971/4e82dd94-09d1-42c0-ba71-68e754e70810)
![Screenshot_20231008-194134179](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/101858971/f259c3fd-36d3-4667-a816-676d0d1f1c17)
