### ISSUE TITLE
Shinigami error 429

### ISSUE THREAD

**Issue by pzmkr** [tachiyomiorg/tachiyomi-extensions#18435]
### Source information

Shinigami 1.4.33

### Source language

indonesia

### Steps to reproduce

1. i scanned for updates as usual
2. after finish scanning, the manhwa from shinigami extensions didn't update and those manhwa failed to update
3. try to check how to resolve and it said to raise a ticket so that a rate limit can be added to prevent ip bans in the future

### Expected behavior

manhwa should successfuly update

### Actual behavior

not updating error 429

### Tachiyomi version

0.14.6

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by pzmkr** [comment]
![Screenshot_20231008-162043_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/20937346/690352bc-f493-4c25-bf0b-bc7e25186255)

**Comment by izul150** [comment]
![Screenshot_2023-10-09-07-51-22-780_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115206805/e06d07d3-059e-4576-ba7a-3624f9483c09)

**Comment by BrutuZ** [comment]
You seem to have hit their Rate-Limit, just wait
![Too many Requests](http://http.cat/429)
