### ISSUE TITLE
Downloaded chapters vanish after a day

### ISSUE THREAD

**Issue by Quasar011** [tachiyomiorg/tachiyomi-extensions#18445]
### Source information

Bato.to 1.4.32

### Source language

English

### Steps to reproduce

I downloaded entire Lookism series from Webtoons extension and the next day I open it in my library, it displayed the download button next to the chapters so I downloaded the whole series again but the same thing happened again. It seemed to be the issue with source of Webtoons & Bato.to; both of these sources delete their chapters from the device overnight. What can I do to keep my chapters?

### Expected behavior

The downloaded chapters should remain in the device.

### Actual behavior

The "downloaded" chapters are shown as "not downloaded" in the app.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
view setting - downloads. turn off all on delete chapters section

**Comment by vetleledaal** [comment]
Won't fix - 51f35d8d755b798b7430e3ca42185861ce842ef6
