### ISSUE TITLE
Datgarscan

### ISSUE THREAD

**Issue by datcat1254** [tachiyomiorg/tachiyomi-extensions#18441]
### Source link

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14207

### Other details

My scan is having problems with few visits to the blog and I think this extension is a reason for it.
https://datgarscanlation.blogspot.com/

### Requirements

- [X] I've added a `TXT` DNS record for my domain with the value `tachiyomi-verification`
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by arkon** [comment]
The first requirement is not actually fulfilled:

```
% dig -t txt datgarscanlation.blogspot.com

; <<>> DiG 9.10.6 <<>> -t txt datgarscanlation.blogspot.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34586
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;datgarscanlation.blogspot.com.	IN	TXT

;; ANSWER SECTION:
datgarscanlation.blogspot.com. 300 IN	CNAME	blogspot.l.googleusercontent.com.

;; AUTHORITY SECTION:
l.googleusercontent.com. 60	IN	SOA	ns1.google.com. dns-admin.google.com. 571710424 900 900 1800 60

;; Query time: 34 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Sun Oct 08 17:59:52 EDT 2023
;; MSG SIZE  rcvd: 158
```

Although I'm not sure if you can even do it, given it's a Blogspot site. You'd need to add something on the website to allow us to verify that this is actually a request from someone who owns it/has access to it.

**Comment by datcat1254** [comment]
> The first requirement is not actually fulfilled:
> 
> ```
> % dig -t txt datgarscanlation.blogspot.com
> 
> ; <<>> DiG 9.10.6 <<>> -t txt datgarscanlation.blogspot.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34586
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;datgarscanlation.blogspot.com.	IN	TXT
> 
> ;; ANSWER SECTION:
> datgarscanlation.blogspot.com. 300 IN	CNAME	blogspot.l.googleusercontent.com.
> 
> ;; AUTHORITY SECTION:
> l.googleusercontent.com. 60	IN	SOA	ns1.google.com. dns-admin.google.com. 571710424 900 900 1800 60
> 
> ;; Query time: 34 msec
> ;; SERVER: 192.168.2.1#53(192.168.2.1)
> ;; WHEN: Sun Oct 08 17:59:52 EDT 2023
> ;; MSG SIZE  rcvd: 158
> ```
> 
> Although I'm not sure if you can even do it, given it's a Blogspot site. You'd need to add something on the website to allow us to verify that this is actually a request from someone who owns it/has access to it.



> En realidad, el primer requisito no se cumple:
> 
> ```
> % dig -t txt datgarscanlation.blogspot.com
> 
> ; <<>> DiG 9.10.6 <<>> -t txt datgarscanlation.blogspot.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34586
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;datgarscanlation.blogspot.com.	IN	TXT
> 
> ;; ANSWER SECTION:
> datgarscanlation.blogspot.com. 300 IN	CNAME	blogspot.l.googleusercontent.com.
> 
> ;; AUTHORITY SECTION:
> l.googleusercontent.com. 60	IN	SOA	ns1.google.com. dns-admin.google.com. 571710424 900 900 1800 60
> 
> ;; Query time: 34 msec
> ;; SERVER: 192.168.2.1#53(192.168.2.1)
> ;; WHEN: Sun Oct 08 17:59:52 EDT 2023
> ;; MSG SIZE  rcvd: 158
> ```
> 
> Aunque no estoy seguro de que puedas hacerlo, dado que es un sitio de Blogspot. Deberá agregar algo en el sitio web que nos permita verificar que en realidad se trata de una solicitud de alguien que lo posee o tiene acceso a él.

We added a section with the scan staff indicating that I am the owner and founder and it redirects to my Discord account
https://datgarscanlation.blogspot.com/p/staff.html

**Comment by datcat1254** [comment]
Are you satisfied with this verification or do you need something else to validate it?

**Comment by arkon** [comment]
Verified that Discord user ID 734835317084782635 is datcat07 and they were the person asking for removal.

Removal can proceed, assuming content isn't being aggregated from other places.
