### ISSUE TITLE
Mangaswat

### ISSUE THREAD

**Issue by GintokiMyk** [tachiyomiorg/tachiyomi-extensions#18440]
### Source information

Mangaswat 1.4.39

### Source language

Arabic

### Source new URL

https://goldragon.me/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by GintokiMyk** [comment]
It's been more than 2 weeks and the issue didn't fixed yet. That's why I opened this issue again.

**Comment by alessandrojean** [comment]
There's no ETA to any issue to be fixed. This is an open source and contributor driven project. Opening duplicate newer issues won't make it to be fixed more fast.
