### ISSUE TITLE
ElarcPage

### ISSUE THREAD

**Issue by AweRulez** [tachiyomiorg/tachiyomi-extensions#18446]
### Source information

ElarcPage 1.4.26

### Source language

English

### Source new URL

https://elarcreader.com/

### Other details

![Screenshot_2023-10-09-10-13-18-891_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/95154911/ec3346c8-7b4a-4711-a42a-df5a4f700be1)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
since they changed the name, maybe just create a new one and remove the "page"/older
