### ISSUE TITLE
Jinman Tiantang has been stuck on cloudflare page

### ISSUE THREAD

**Issue by supeep** [tachiyomiorg/tachiyomi-extensions#18466]
### Source information

Jinman Tiantang-1.4.38

### Source language

Chinese

### Steps to reproduce

1. Access the plugin in "Sources",or access the manga you have already add to library and click on webview
2. There is a high probability that it will keep loading.
3. Click on 'webview'
4. You will verify you are human again again and again

### Expected behavior

The page should just appear once, and then  it's the manga page

### Actual behavior

This page is just" verify you are human"

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
