### ISSUE TITLE
Please Add Magus Manga

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#18460]
### Source name

Magus Manga

### Source link

https://magusmanga.com/

### Source language

English 

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Either this is the same arabic website from before that now completely [citation needed] pivoted to english
Or someone grabbed the domain from the previous folks and now run their own website

Considering that the extension is still working, I presume its the former.
In any case, the extension could be updated to reflect the change in language.
