### ISSUE TITLE
ozulscansen معطل

### ISSUE THREAD

**Issue by Abdulrahman9009** [tachiyomiorg/tachiyomi-extensions#18470]
### Source name

ozulscansen

### Source language

العربية

### Source link

https://ozulscansen.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Abdulrahman9009** [comment]
ozulscansen معطل
 ولا يفتح وانما يفتح موقع اخر

**Comment by T3MYA11** [comment]
related to #18299

**Comment by vetleledaal** [comment]
There is no extension named ozulscansen or any extension using https://ozulscansen.com/. The site is also online. Make sure you use the correct issue template and fill it out accurately.

If an existing extension changed their domain, use "URL change report"
If this is a new site, use "Source request"
Search for duplicates before opening a new issue in any case.
