### ISSUE TITLE
TeamX URL Change

### ISSUE THREAD

**Issue by RavenAlive** [tachiyomiorg/tachiyomi-extensions#18479]
### Source information

Team X 1.4.14

### Source language

Arabic 

### Source new URL

https://team11x11.com/series

### Other details

Same thing as Ozul scans extension

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by T3MYA11** [comment]
team x working fine but the owner of the website changed the mangas name to Arabic words, so you need to re add the mangas manually
الموقع شغال عادي الدومين اتغير تلقائي بس اسامي المانجا اصبحت بالعربي أرجع ضيفها تاني للمكتبة .
