### ISSUE TITLE
Izakaya: HTTP error 401

### ISSUE THREAD

**Issue by Greed-2468** [tachiyomiorg/tachiyomi-extensions#18472]
### Source information

Izakaya 1.4.33

### Source language

Português (Brasil)

### Steps to reproduce

![Screenshot_2023-10-10-12-56-41-184_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92608858/f8fb6327-507f-424c-96d7-2348bd6ec639)
![Screenshot_2023-10-10-12-56-49-965_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92608858/a725a183-3404-4929-ab17-db19010bcb4f)

### Expected behavior

Aparecer os Manhwas 

### Actual behavior

Não aparece nada

### Tachiyomi version

0.14.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill out all information requested in English next time, not all contributors speaks Portuguese.

**Comment by alessandrojean** [comment]
Closing as these extensions will be removed.
