### ISSUE TITLE
Infinite loading of images

### ISSUE THREAD

**Issue by Thomas-unique** [tachiyomiorg/tachiyomi-extensions#18497]
### Source information

phenixscans 1.4.27

### Source language

French

### Steps to reproduce

Start the chapter 1 of northern blade on phenixscans
Infinite loading of the images 

### Expected behavior

Load the chapter's images

### Actual behavior

Infinite loading of images

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Works for me.  Maybe [clearing cache, cookies, database](https://tachiyomi.org/docs/guides/troubleshooting/diagnosis#primary-diagnosis) for PhenixScans could help ?

**Comment by KirinRaikage** [comment]
If you don't give some updates, I'll kindly ask to close the issue in the next few days, as it's most likely an isolated issue.

**Comment by Thomas-unique** [comment]
There's been an update, it works.

**Comment by KirinRaikage** [comment]
It worked also before the update. But glad that it was sorted out for you !
