### ISSUE TITLE
HTTP Error: 429 - Too Many Requests

### ISSUE THREAD

**Issue by Wyvernny** [tachiyomiorg/tachiyomi-extensions#18506]
### Source information

Shinigami 

### Source language

Indonesia 

### Steps to reproduce

![Screenshot_2023-10-12-17-47-55-94_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147713538/4a6b32b2-ba23-4e4b-82b3-f4c7b915e834)

![Screenshot_2023-10-12-17-47-51-36](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147713538/55403fac-3777-476f-8c8d-6855814ddaf6)

![Screenshot_2023-10-12-17-54-23-91_c37d74246d9c81aa0bb824b57eaf7062](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147713538/79b17266-df34-4868-9c3a-f4d848e40c10)

I didn't know it could happen like that, when I updated the latest chapter it didn't say "httpp error' 429" Likewise, I read the manhwa from shinigami like that, and I also checked that the shinigami extension contained "java.io.IOException: Gagal untuk menembus Cloudflare" Then I checked the extension and it turned out my IP was blocked from yesterday until now. please this problem can be fixed and I can also read manhwa from shinigami from the region Indonesia

### Expected behavior

This should be fixed quickly, because I want to read the manhwa from the shinigami extension, and also my IP please don't block it pls. I just want to read the manhwa from the manhwa extension, please fix it. Thank You 

### Actual behavior

I don't know, suddenly yesterday I read the manhwa from the shinigami extension but it got an error until now, and it says "http error' 429" and I checked the website of the shinigami extension and it turned out my IP was blocked.
![Screenshot_2023-10-12-17-47-51-36](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147713538/dc11214d-907c-4fc2-a2c2-b0884de82857)

![Screenshot_2023-10-12-18-00-15-54_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147713538/e721876c-ea7d-4f32-9d6a-be0b6b514304)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Please quickly fix the problem I told you about. I just want to read from the Shinigami extension. Thank You.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MeLoseAgain** [comment]
You can use another extension, until this is fixed

**Comment by TheKingTermux** [comment]
Why are you get blocked, even though I'm just fine?

![Screenshot_2023-10-14-07-29-32-72_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/8a60ccae-0458-4feb-8990-4631ced75e44)

![Screenshot_2023-10-14-07-28-03-20_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/c0f23fc0-94ad-47d7-bf6b-461b0d63b808)

**Comment by RoSiCyBeR** [comment]
> Why are you get blocked, even though I'm just fine? If you still get blocked, migrate to other source until it get fixed
> 
> ![Screenshot_2023-10-14-07-29-32-72_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/275093874-8a60ccae-0458-4feb-8990-4631ced75e44.jpg)
> 
> ![Screenshot_2023-10-14-07-28-03-20_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/275093875-c0f23fc0-94ad-47d7-bf6b-461b0d63b808.jpg)

What provider's do you use? I use CBN Telkom IP but it gets banned if I use Tachiyomi WebView. You can use a user agent but you can't download it😅

**Comment by RoSiCyBeR** [comment]
> > What provider's do you use? I use CBN Telkom IP but it gets banned if I use Tachiyomi WebView. You can use a user agent but you can't download it😅
> 
> I use a First Media one And use Random User Agent string that i found it online And it still works and fine for me For downloading the chapter it still works and fine But every time you close the Tachiyomi app, and you need to use the Shinigami Extension again, you need to require the Solving cloudflare through WebView first, and it Will works again

RandomUA? Or choose desktop/mobile?

**Comment by TheKingTermux** [comment]
> RandomUA? Or choose desktop/mobile? Or you have costume one?

I use dekstop one

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 YaBrowser/23.9.0.2253 Yowser/2.5 Safari/537.36
```

**Comment by RoSiCyBeR** [comment]
> > RandomUA? Or choose desktop/mobile? Or you have costume one?
> 
> I use dekstop one
> 
> ```
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 YaBrowser/23.9.0.2253 Yowser/2.5 Safari/537.36
> ```
> 
> Or you need a another UA ? You can [search it from here](https://www.whatismybrowser.com/guides/the-latest-user-agent/)

Ahh.... Tachiyomi's default user agent? I'm using it but it says bad browser or are you using DNS over http?

**Comment by TheKingTermux** [comment]
> Ahh.... Tachiyomi's default user agent? I'm using it but it says bad browser or are you using DNS over http? 
> I'm using desktop UA it's not working

That's not default, It's a custom one
And for DNS, i just use a [Cloudflare DNS](https://developers.cloudflare.com/1.1.1.1/setup/android/) on my phone settings and a router that i have, and i didn't use a DoH in my Tachiyomi App, just use a default one

**Comment by libran07** [comment]
> > Ahh.... Tachiyomi's default user agent? I'm using it but it says bad browser or are you using DNS over http?
> > I'm using desktop UA it's not working
> 
> That's not default, It's a custom one (or i can say i use a Yandex one :v) And for DNS, i just use a [Cloudflare DNS](https://developers.cloudflare.com/1.1.1.1/setup/android/) on my phone settings and a router that i have, and i didn't use a DoH in my Tachiyomi App, just use a default one
> 
> You think I'm lying ? Here little a video clip that i can access a Shinigami web using a WebView and read it from Tachiyomi app
> 
>  Record_2023-10-16-08-30-31_afd66b7916d19a60815f56273408b73e.mp4 
>  Record_2023-10-16-08-46-53_afd66b7916d19a60815f56273408b73e.mp4

yeah its work for you but not for me..

this stepbystep i used (from what you said/wrote)
- setting cloudflare DNS on my phone AND disabled DoH
- restart the app
- go to setting > advanced > on default user agent string i used user agen that you shared
- open shinigami extension setting > on random user-agent i chose Dekstop
- restart the app
- go to setting > advanced > refresh tracking metadata
- open shinigami extension > open in webview > not work or bad browser

i really dont know whats wrong or this not work because i used TachiyomiJ2K app

**Comment by TheKingTermux** [comment]
> i really dont know whats wrong or this not work because i used TachiyomiJ2K app

Nah you use J2K version, i just use a Tachiyomi Official App, maybe the J2K version doesn't match the settings I made. Try using the Official Tachiyomi app, and try using the settings I made to see if it works or not. If you can then enjoy reading again, if not, then wait until this problem is fixed and please migrate your reading to another source first

**Comment by libran07** [comment]
> Nah you use J2K version, i just use a Tachiyomi Official App, maybe the J2K version doesn't match the settings I made. Try using the [Official Tachiyomi app](https://github.com/tachiyomiorg/tachiyomi/releases/download/v0.14.6/tachiyomi-v0.14.6.apk), and try using the settings I made to see if it works or not. If you can then enjoy reading again, if not, then wait until this problem is fixed and please migrate your reading to another source first

I was thinking the same, I tried it in the J2K version because I already too enjoy reading there.
Maybe for now, I will migrate my reading to another source until this issue is fixed

> 
> Wait..... Did you change the User Agent string on Shinigami Extension Setting's? I just off it, and why you change to dekstop one? Just use a User Agent string on Tachiyomi Advanced Setting's not in the Extension Setting's

Oh, I might have misunderstood what you meant when you said 'desktop' when someone asked about dekstop or mobile.
Actually, after that. I also tried other options, 'mobile' and 'off,' but it still didn't work.

**Comment by RoSiCyBeR** [comment]
> > Nah you use J2K version, i just use a Tachiyomi Official App, maybe the J2K version doesn't match the settings I made. Try using the [Official Tachiyomi app](https://github.com/tachiyomiorg/tachiyomi/releases/download/v0.14.6/tachiyomi-v0.14.6.apk), and try using the settings I made to see if it works or not. If you can then enjoy reading again, if not, then wait until this problem is fixed and please migrate your reading to another source first
> 
> I was thinking the same, I tried it in the J2K version because I already too enjoy reading there. Maybe for now, I will migrate my reading to another source until this issue is fixed
> 
> > Wait..... Did you change the User Agent string on Shinigami Extension Setting's? I just off it, and why you change to dekstop one? Just use a User Agent string on Tachiyomi Advanced Setting's not in the Extension Setting's
> 
> Oh, I might have misunderstood what you meant when you said 'desktop' when someone asked about dekstop or mobile. Actually, after that. I also tried other options, 'mobile' and 'off,' but it still didn't work.

Try changing the user agent, maybe it will work  [Check another browser user agent](https://www.whatismybrowser.com/guides/the-latest-user-agent/).... Or Try using mine
 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/103.0.0.0`

**Comment by libran07** [comment]
> 
> Try changing the user agent, maybe it will work [Check another browser user agent](https://www.whatismybrowser.com/guides/the-latest-user-agent/).... Or Try using mine `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/103.0.0.0`

I have tried other user agent browsers and yours, but it still doesn't work. Thank you anyway.

**Comment by TheKingTermux** [comment]
> Try changing the user agent, maybe it will work  [Check another browser user agent](https://www.whatismybrowser.com/guides/the-latest-user-agent/).... Or Try using mine
>  `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/103.0.0.0`

Ohh did it works for you after **Updating the Extension**?

**Comment by RoSiCyBeR** [comment]
It worked fine after you give me  updated the repo, I haven't tried the previous version thx

**Comment by Mitia99** [comment]
> > 
> > Try changing the user agent, maybe it will work [Check another browser user agent](https://www.whatismybrowser.com/guides/the-latest-user-agent/).... Or Try using mine `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/103.0.0.0`
> 
> I have tried other user agent browsers and yours, but it still doesn't work. Thank you anyway.

It will work with original tachiyomi not J2K. I have a similar issue with an other extension. Don't know what's going with J2K unable to bypass Cloudflare.

**Comment by anarchysense** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/assets/94175604/98a295da-b857-4752-ac97-f6136ebab2f7

Still can't access the Shinigami website, it only displays the landing page.
