### ISSUE TITLE
Olympusscanlation

### ISSUE THREAD

**Issue by christmovies** [tachiyomiorg/tachiyomi-extensions#18501]
### Source name

olympus scanlation

### Source language

Spanish

### Describe your suggested feature

https://olympusv2.gg/seriesSorry, was this Tab on popular
![Screenshot_2023-10-11-22-10-38-145_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97629848/1e5718b6-2d14-4f8c-bdfe-c8b30d4a14a8)

https://olympusv2.gg/series
 
What I need is not that the popular mangas are shown, etc. but all of them,As in any other source (like as the "recents" tab), thanks for the recent tab, it's just what I needed

### Other details

Show all the comics uploaded to the website(https://olympusv2.gg/series(Where does it say series)) in the popular tab (tachiyomi popular)

Thanks For the support and your hard work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
What you're referring to isn't the popular manga, it's the entire library. Now you can access it through the filters.

**Comment by christmovies** [comment]
> What you're referring to isn't the popular manga, it's the entire library. Now you can access it through the filters.

Yes, thanks bro
