### ISSUE TITLE
Golden Mangás is Dead

### ISSUE THREAD

**Issue by Erick17x** [tachiyomiorg/tachiyomi-extensions#18518]
### Source name

Golden Mangás

### Source language

Portugues

### Source link

https://goldenmagas.top/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Pedro77h** [comment]
Did they abandon the project? or change the domain?

**Comment by Erick17x** [comment]
They announced on the website that they were closing the site. They thanked everyone for their support.

**Comment by alessandrojean** [comment]
Closing as we're waiting a little bit to confirm the facts before removing it.
