### ISSUE TITLE
Failed to connect to Nix Mangás

### ISSUE THREAD

**Issue by Erick17x** [tachiyomiorg/tachiyomi-extensions#18517]
### Source information

Nix Mangás 1.4.3

### Source language

Portuguese

### Steps to reproduce

1. Open app.
2. Browse -> Sources 
3. Search any manga 
4. Nix mangá error = " Failed to connect to api.nixmangas.com [...] "

### Expected behavior

1. Open app.
2. Browse -> Sources 
3. Search any manga
4. Find the manga i want

### Actual behavior

1. Open app.
2. Browse -> Sources 
3. Search any manga
4.  Dont find the manga i want

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Just open in WebView to check their site is down. Nothing we can do on our end.
