### ISSUE TITLE
Sushi-Scan: Image could not be loaded

### ISSUE THREAD

**Issue by kanidalo** [tachiyomiorg/tachiyomi-extensions#18520]
### Source information

Sushi-Scan 1.4.33

### Source language

French

### Steps to reproduce

Opening any manga fails and shows "image could not be loaded"

### Expected behavior

Displays the selected manga

### Actual behavior

Opening any manga fails and shows "image could not be loaded"

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AlCiavi** [comment]
Personally, everything was working great before the update 1.4.33. When starting Tachiyomi I just needed to overpass Cloudflare with WebView once and then everything worked. But now, I have the trouble of Cloudflare even if I overpass it with WebView. I don't have the "images could not load" as a issue showing. I don't know if that's useful to solve the problem. Thank you for your assistance

**Comment by KirinRaikage** [comment]
This should be handled once the pull request mentionned just above your comment is merged.
