### ISSUE TITLE
Domain change 

### ISSUE THREAD

**Issue by tttaima** [tachiyomiorg/tachiyomi-extensions#18528]
### Source information

مانجا لينك 

### Source language

Arabic 

### Source new URL

https://manga-like.net/mangalink/

### Other details

Can you solve the problem of changing the Mangalink domain?  He owns the same domain as Mangalek, and they also have many domains I can also provide you with all his domain names 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by aymanharrawi** [comment]
please update url to manga-like.net

**Comment by tttaima** [comment]
Mangalek will not work on Tashiyomi. It has a problem. Even after you
updated the domain, it did not work. Previously, it did not work. It only
worked, MangaLnk.
