### ISSUE TITLE
MangaSwat is not working 

### ISSUE THREAD

**Issue by Tian-77** [tachiyomiorg/tachiyomi-extensions#18521]
### Source information

ar.mangaswat 1.4.40

### Source language

"Arabic"

### Steps to reproduce

1. Open MangaSwat, "no result found" will show up because the url is an old one
2. Go to the source settings and use Override BaseUrl to change it to the new url which is " https://goldragon.me/ "
3. Restart the app and try to open MangaSwat again, it'll open the site but the manhwas will not working and u can't open any chapters

### Expected behavior

The url should be updated to the new one " https://goldragon.me/ "
Trying to change the url from the source settings makes the source not working 

### Actual behavior

Can't open any manhwa

### Tachiyomi version

1.9.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
You should use `https://goldragon.me` (without the last slash)

**Comment by Tian-77** [comment]
Thanks
