### ISSUE TITLE
Novelcool only download 1 image

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#18535]
### Source information

Novelcool 1.4.2

### Source language

English

### Steps to reproduce

1. Open novelcool manga and download chapter "Wotaku Girl And High School Boy" Chapter 1
2. View chapter in app
3. View chapter in webview

### Expected behavior

Novelcool download all image

### Actual behavior

Novelcool only download or view first image although in the webview there are more, for example in Wotaku Girl And High School Boy there are 5 image

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Closing in favor of #19094
