### ISSUE TITLE
Swatmanga  changed URL

### ISSUE THREAD

**Issue by Ammaralkaaki** [tachiyomiorg/tachiyomi-extensions#18538]
### Source information

Mangaswat1.4.41

### Source language

Arabic

### Source new URL

https://goldragon.me/

### Other details

This issue wasn't  fixed as this is the new url https://goldragon.me/.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Closing in favor of #18050
