### ISSUE TITLE
MangaToon (Limited) Language selection error

### ISSUE THREAD

**Issue by KatoMegushua** [tachiyomiorg/tachiyomi-extensions#18536]
### Source information

MangaToon (Limited) 1.4.5

### Source language

Spanish

### Steps to reproduce

1 search for the MangaToon extension (Limited)
2 install the extension
3 select the language (Spanish in this case)

### Expected behavior

1 select the language (Spanish in this case)

2 display the results of the extension in Spanish 

3 be able to read the titles with Spanish translation

### Actual behavior

1 select the language (Spanish in this case)

2 it does not show the results of the extension in Spanish, even when only that language is selected 

3 does not search for titles with Spanish translation 

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details

You can take as an example the title (Oye, no toques mi queso) that should be in the Spanish language section and you will see that it does not find results.

![Screenshot_20231013_124027_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/f0eccdc4-47b0-49d6-ae54-a3badac5c367)
![Screenshot_20231013_122648_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/9400bd9a-22be-4ec8-a2df-6450157a5f54)

When searching for the title in the web view if it finds it 

![Screenshot_20231013_122739_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/26042797-4f87-475f-9cea-7015124100d0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Como dice ahí, son resultados de una búsqueda por internet, es decir, ese enlace te envía a una página externa, por lo que no aparece en la extensión.

**Comment by KatoMegushua** [comment]
@bapeey Pues el dominio es el mismo no de allmanga, lo único que cambia es el lenguaje, de ser el caso pasaría lo mismos con la extensión de webtoon cuando se selecciona un lenguaje

**Comment by bapeey** [comment]
> Pues el dominio es el mismo no de allmanga

![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90949336/44029f05-3017-4fdd-8c28-125f5b6e61f7)

Si entras ahí te redirige a AllManga, puedes encontrarlo en Mangatoon con el nombre de "Oye, No Toques Mi Queso"

**Comment by KatoMegushua** [comment]
@bapeey pues ese era el problema que decía se que está en MangaToon pero al momento de buscarlo en la extensión de tachiyomi al parecer no lo encuentra

Y pues al revisar solo me muestra los resultados cuando el lenguaje seleccionado es inglés

![Screenshot_20231013_132813_Chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/45c15326-106d-4ea5-a50a-37e99f5de57d)

**Comment by bapeey** [comment]
Lo buscaste con ese nombre? A mi si me aparece

**Comment by KatoMegushua** [comment]
@bapeey en serio? pero como te digo no aparece intente en otro dispositivo y tampoco
![Screenshot_20231013_133727_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/8e151666-3490-4e41-ac83-253ba52d3b1d)

**Comment by bapeey** [comment]
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90949336/02d72a16-c85f-4ea0-a79f-f5c85eae88f6)

Ni siquiera asi?

De todas formas, puedes hacer una Source Request para TMOManga, que veo que tiene mas capítulos

**Comment by KatoMegushua** [comment]
Tienes alguna configuración? #
![Screenshot_20231013_134625_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/b4223d35-942f-460c-8715-2a2cdf9c0be7)

Pues en mangatoon está finalizado en tmo ya no lo siguieron por temas de licencia

**Comment by KatoMegushua** [comment]
@bapeey tienes alguna configuración u otra versión de tachiyomi? Yo utilizo la stable 0.14.6
![Screenshot_20231013_134625_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/7225a4b3-2cba-4438-aca9-490fc5d1d7c1)
