### ISSUE TITLE
Url shikigami 

### ISSUE THREAD

**Issue by Pecoriine** [tachiyomiorg/tachiyomi-extensions#18546]
### Source information

Shikigami 1.4.34

### Source language

Indonesian 

### Source new URL

https://shinigami.ae/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
[shinigami.ae](https://shinigami.ae/) showing other url instead
