### ISSUE TITLE
Magus manga

### ISSUE THREAD

**Issue by Elinosorry** [tachiyomiorg/tachiyomi-extensions#18541]
### Source name

Magus manga

### Source link

https://magusmanga.com

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Elinosorry** [comment]
I just checked the website again and there was no mistake 
The other request was under the arabic section but the website i mentioned is english

**Comment by curche** [comment]
Refer to https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18460#issuecomment-1754286084

**Comment by Elinosorry** [comment]
> Refer to [#18460 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18460#issuecomment-1754286084)

Thanks
