### ISSUE TITLE
Reopen F**ku cc ticket

### ISSUE THREAD

**Issue by Yzakrio** [tachiyomiorg/tachiyomi-extensions#18550]
### Source name

F**ku.cc

### Source link

https://fakku.cc

### Source language

English

### Other details

There was a source request for this in 2022 but the page got shut down and now is back up; the reply for that request was to use lanraragi. I don't really know how to set this up (and would rlly appreciate it if someone would link a detailed guide for this), but my guess is that it would be easier and a lot more practical for most of users to have a direct extension.

Thank you for reading

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Kantotero** [comment]
> Add Hentalk extension #18593
Please make a new extension & update fakku.cc ASAP

**Comment by vetleledaal** [comment]
Site only shows a router login page
