### ISSUE TITLE
Source Cannot be found

### ISSUE THREAD

**Issue by Luibarce** [tachiyomiorg/tachiyomi-extensions#18555]
### Source information

Mangairo, ManhaHub, MangaDex

### Source language

English 

### Steps to reproduce

The Extension cannot be found. but some of its manga is updating but i cannot found the source 

### Expected behavior

The Extension cannot be found. but some of its manga is updating but i cannot found the source 

### Actual behavior

The Extension cannot be found. but some of its manga is updating but i cannot found the source 

### Tachiyomi version

0.14.6

### Android version

Android 12.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Make sure you haven't disabled 18+ sources in the app settings.
