### ISSUE TITLE
Sushi-Scan : The image couldn't be loaded

### ISSUE THREAD

**Issue by AlCiavi** [tachiyomiorg/tachiyomi-extensions#18557]
### Source information

Sushi-Scan 1.4.34

### Source language

French

### Steps to reproduce

Once you've bypassed the Cloudflare with WebView, go to a manga on the list and click on an 'old' chapter (added in 2021 by Sushi-Scan, for example). Let's Alice in Borderland

### Expected behavior

Images should load normally, as they did on 1.4.32.

### Actual behavior

A very long loading time, then finally the text "the image couldn't be loaded" appears.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

This problem has occurred in the past. An update had solved the problem I believe. 
However, since update 1.4.33 and therefore also this update, this issue has returned. Thank you for solving this issue, Sushi-Scan is by far the best French source for reading manga. 
Thank you for your work.

PS : to double check the issue, try to load chapter 365 of Berserk, it works but volume 41 and all volumes don't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Hmmm I've tried to check for Berserk for example in WebView, the images themselves on some volumes on the source are broken, so it's perfecty normal in that case. I'll check if the same applies for Alice, but try to check if the images are not broken for the volumes in WebView first.

**Comment by KirinRaikage** [comment]
![Screenshot_2023-10-14-20-35-03-553_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/11159175/b8a24ecd-64ab-4082-a684-42a4fc2f2267)
Same can be applied for Alice, it seems :(

**Comment by AlCiavi** [comment]
The images are broken but only in WebView. In any other browser it works perfectly. Could this be an issue coming from Sushi-Scan ? I can't remember what solved the issue some time ago, but it's actually annoying. WebView problem ? Sushi-Scan issue ?

**Comment by KirinRaikage** [comment]
I would tend to say WebView issue.

**Comment by AlCiavi** [comment]
Do you think i need a new user agent ? Or maybe just wait for WebView to update or something ?

**Comment by KirinRaikage** [comment]
I'll try something on the code that may work, suggested by someone else. The volumes where we see the issue are using `http://` instead of `https://`

**Comment by AlCiavi** [comment]
I believe that was the issue before. When it occurred, i pointed it out in a previous issue here on Github. But now, all the images are in https://. Like this one : https://sushiscan.net/wp-content/uploads5/AliceinBorderlandTome9-001.jpg and Alice in Borderland doesn't work on WebView.
But I know less than you, so I guess I will just wait for someone to find the solution. Thank you for your time.

**Comment by KirinRaikage** [comment]
No, not really. Before, I think all images were loaded on the same page, now I had to make a code change to read JavaScript to load all the images (This solved the issue we had a few days ago but not completely, as you saw). Here, some images are still hardcoded in `http://`.

**Comment by AlCiavi** [comment]
Ok, that's where you lost me a bit lol. I trust you to find the solution. Once again, thank you for your time.

**Comment by KirinRaikage** [comment]
Good news, it will work.
