### ISSUE TITLE
Yugen Mangas - Is broken

### ISSUE THREAD

**Issue by gatinhecomunista** [tachiyomiorg/tachiyomi-extensions#18560]
### Source information

Yugen Mangas - Português

### Source language

Português

### Steps to reproduce

They invaded the website and deleted all the chapters. They are reuploading everything, but apparently their link broke on tachiyomi and keeps redirecting to their discord

### Expected behavior

get in there and be able to open the chapters

### Actual behavior

It keeps saying "HTTP ERROR 404" and when I try to log in via the web, it keeps going to discord

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their site is in maintenance and even on browser redirects to Discord. You need to wait for them to fix it first.
