### ISSUE TITLE
Fr-scan error 404

### ISSUE THREAD

**Issue by pixelroll** [tachiyomiorg/tachiyomi-extensions#18567]
### Source information

fr.frdashscan 1.4.33

### Source language

French

### Steps to reproduce

Try browsing the source

### Expected behavior

mangas should appear

### Actual behavior

Http error 404

### Tachiyomi version

0.14.6

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
From what I see, everything in the website itself is broken.
Manga list URL returns "Not found", for example:
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/11159175/f635e430-0f82-42ed-a7bf-29d7312484b8)

**Comment by KirinRaikage** [comment]
Ok, everything seems to be back but extension has been really slow. 
Probably due to the domain change from .cc to .com. 
I will create a PR to force the new domain.
