### ISSUE TITLE
problem with downloaded file names

### ISSUE THREAD

**Issue by aymanharrawi** [tachiyomiorg/tachiyomi-extensions#18572]
### Source information

ar.gmanga 1.4.12

### Source language

Arabic

### Steps to reproduce

the problem is with downloaded chapter names , when i open tachiyomi folder to get downloaded chapters I see that chapter names is named with chapter translators instead of chapter number and that is problem with chapters sorting and arranging please fix it

### Expected behavior

![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147435669/a7aa4c1c-c634-4a83-94ab-17be8c83f951)

### Actual behavior

![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147435669/cc6ed342-69b6-4d4b-ae0d-8cbefbfc652e)

### Tachiyomi version

0.14.6

### Android version

android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's intentional; sorting downloaded files isn't relevant for app usage.

**Comment by aymanharrawi** [comment]
ok, then can you update url for extention mangalink?  I posted this https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18571#issuecomment-1763397430  and bot just closed it as dublicated but this is mistake because the url is new

**Comment by arkon** [comment]
You don't need to create another issue if there's already one opened by somebody else. This is just spam.

**Comment by aymanharrawi** [comment]
if you ignoring his issue what should i do ?
