### ISSUE TITLE
Bug extension

### ISSUE THREAD

**Issue by Chellyph14** [tachiyomiorg/tachiyomi-extensions#18579]
### Source information

Cerise scan 1.4.38

### Source language

Português (Brasil)

### Steps to reproduce

First, when I go to add a manga to my library, it stops working, it doesn't receive updates, it keeps giving an error. Secondly, when I enter the extension it shows that the manga is not in my library but when I click to add, it shows that it is in my library.

### Expected behavior

What should happen is that when I add a manga, it is updated and it stays in my library.

### Actual behavior

It happened that every time I add a manga of this extension it stops receiving updates and says no it is not added to the library even though it already is.

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They change their manga URLs frequency and there's nothing we can do about it. Migrate from Cerise to Cerise periodically or just use better sources that doesn't do this.
