### ISSUE TITLE
HTTP error 404, 427

### ISSUE THREAD

**Issue by R1tzy** [tachiyomiorg/tachiyomi-extensions#18583]
### Source information

Golden Mangás 1.4.22, Izakaya 1.4.33,  Bakai1.4.3

### Source language

portuguese

### Steps to reproduce

1. access the source extension or do manga search
2. some fonts are giving this error

### Expected behavior

it should show manga search results for that extension source

### Actual behavior

does not show search results or source and gives error http

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Golden Mangas, Bakai show error Http 404
Izakaya show error Http 427

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Also please do open one issue per source next time, and do check if the sources you're having issues are not obsolete. We don't provide support to obsolete sources and you should just uninstall them.

**Comment by R1tzy** [comment]
@alessandrojean then add an extension like https://mangahosted.com/ or https://mangalivre.net/, an extension that several manga have. because if I have to add scan by scan to be able to read all the manga I follow, it becomes difficult

**Comment by BrutuZ** [comment]
@R1tzy They're both in the removed extensions list the bot linked: #7065 #8679
