### ISSUE TITLE
Manga swat url

### ISSUE THREAD

**Issue by Safsoff** [tachiyomiorg/tachiyomi-extensions#18586]
### Source information

MangaSwat 1.4.41

### Source language

Arabic 

### Source new URL

https://goldragon.me/

### Other details

The problem has been ther for like over a month and  still existed 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
The extension already uses the new domain. In addition, it also includes an extension setting to change the domain manually by the user.

See #18175
