### ISSUE TITLE
Web Shinigami from Indonesia 

### ISSUE THREAD

**Issue by Welmzs** [tachiyomiorg/tachiyomi-extensions#18590]
### Source information

Id.shinigami version 1.4.34

### Source language

Bahasa Indonesia

### Steps to reproduce

This website is experiencing problems. When opened it will just be stuck on the loading menu. Just see a circle spinning round and round. Of course it's not a connection problem.
![Screenshot_2023-10-17-05-06-32-180_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148159484/b94d1730-4f90-49f7-9564-72ae6a0c9a20)

### Expected behavior

Hopefully the website will be fixed quickly. And I can open the safe shinigami web

### Actual behavior

The shinigami web is having problems loading

### Tachiyomi version

0.14.6

### Android version

MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rewtio** [comment]
Shinigami currently raising their cloudflare level, you can see discussion in issue #18506

**Comment by curche** [comment]
Closing in favor of #18506

**Comment by TheKingTermux** [comment]
> Closing in favor of #18506 

Can you close the issue #18435?
They have the same issue as #18506
It locked, So i can't comment it
