### ISSUE TITLE
Source Crashing

### ISSUE THREAD

**Issue by selahchikah** [tachiyomiorg/tachiyomi-extensions#18609]
### Source information

E-Hentai 1.4.20

### Source language

English

### Steps to reproduce

1. Open TJ2K
2. Open "Browse" tab
3. Either open E-Hentai latest, or search and click results from E-Hentai
4. After a few seconds of loading, crash to home screen.

### Expected behavior

It should open the result/gallery of results from the website.

### Actual behavior

It crashed after a few seconds of loading.

### Tachiyomi version

1.7.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
not related to extension itself, wait for j2k update or try using the beta.
