### ISSUE TITLE
King Of Manga :(Source request)

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#18613]
### Source name

King Of Manga

### Source link

https://kingofmanga.com

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by YYSS15** [comment]
It's the new URL of Ozul scans ( ar.ozulscans 1.4.28 )

**Comment by abde928** [comment]
Add source 
https://kingofmanga.com/

**Comment by T3MYA11** [comment]
my issue closed so i will mention it here #18886

**Comment by Ammaralkaaki** [comment]
The url is it for ozulsans or kingofmanga
