### ISSUE TITLE
Mangarolls source change (.com to .net)

### ISSUE THREAD

**Issue by tommytaoli** [tachiyomiorg/tachiyomi-extensions#18625]
### Source information

MangaRolls 1.4.31

### Source language

English

### Source new URL

https://mangarolls.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by misen355** [comment]
https://gofile.io/d/1dESlz Changed the link in Android Studio, hopefully an official update comes soon!

**Comment by KirinRaikage** [comment]
Don't recommend to do stuff like that...
