### ISSUE TITLE
Scan attacks 

### ISSUE THREAD

**Issue by Henrique3616** [tachiyomiorg/tachiyomi-extensions#18620]
### Source information

Yugen mangoes, Golden mango, glorious scan.

### Source language

There is a hunt for scans and many are changing so as not to be taken down

### Source new URL

.

### Other details

It is not possible to read or download the chapters, many of them are giving http error 404, probably many other sources will have to be revised
/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source and do inform all the requested information such as their new URL, otherwise it keeps difficult to keep track on what have been addressed and what not.
