### ISSUE TITLE
Please fix arabic extensions 

### ISSUE THREAD

**Issue by iBloox** [tachiyomiorg/tachiyomi-extensions#18632]
### Source name

All arabic extensions 

### Source language

Arabic

### Describe your suggested feature

No one trying to fix arabic extensions
All the main source change their domain
And when someone changed the domain he changed it to a wrong one

### Other details

Please fix the arabic extensions like
Swatmanga
Team x
Mangalik
Mangalink
Mangaspark
Mangastar

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source next time and do check if there isn't already open issues about it to not open unnecessary duplicate issues.
