### ISSUE TITLE
Cosmic Scans doesn't find any pages

### ISSUE THREAD

**Issue by RazredgeBR** [tachiyomiorg/tachiyomi-extensions#18644]
### Source information

Cosmic Scans 1.4.28

### Source language

English

### Steps to reproduce

Try to open any chapters from Cosmic Scans (Tower of God, Lookism...), it will show "no pages found", but going to the site you can click the chapter and it loads.

### Expected behavior

Should load the pictures just as the browser.

### Actual behavior

Reports "no pages found" and nothing more.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hero-Kage** [comment]
Small addition from my side: Cosmic Scans changed their URL, so while the main site seems to be found without any issue any specific series URL does not work. The can be accessed in webview so most likely resolving the URL for a series does not work correctly for now

**Comment by nobile01** [comment]
Is this related to how we get No Pages Found when opening a chapter, but when we open Webview it loads an invite to their discord? Or should I open a new ticket?
