### ISSUE TITLE
Diskus Scan: Source removal request

### ISSUE THREAD

**Issue by MTKBlade** [tachiyomiorg/tachiyomi-extensions#18657]
### Source link

Https://diskusscan.com/

### Other details

Dear Tachiyomi Team,

I am writing to request the removal of the Diskus Scan extension from the Tachiyomi app. Our site, Diskus Scan, is currently listed as one of the sources in the Tachiyomi app, but I would like to kindly request its removal.

While I appreciate the Tachiyomi app and its mission to provide readers with a wide range of sources, I would like to manage access to our content exclusively through our site. Therefore, I would like to ask for the removal of Diskus Scan as a source within the Tachiyomi app.

I understand that this is part of your commitment to maintaining a diverse and open platform for manga readers, and I respect that. I hope you can honor my request to remove Diskus Scan as a source.

Thank you for your understanding and for the work you do in maintaining the Tachiyomi app.

Sincerely,
MTK Blade

### Requirements

- [X] I've added a `TXT` DNS record for my domain with the value `tachiyomi-verification`
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by arkon** [comment]
>  Site is not infested with user-hostile features (e.g., invasive or malicious ads)

Been a while since I've seen popup ads...

**Comment by MTKBlade** [comment]
@alessandrojean estarei ansioso pelos updates para derrubar novamente :3

**Comment by alessandrojean** [comment]
Imagine being so childish like this.
