### ISSUE TITLE
Mangagreat url change

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#18664]
### Source information

MangaGreat 1.4.35

### Source language

English

### Source new URL

https://mangagreat.org/

### Other details

![Screenshot_2023-10-22-13-35-12-73](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/79831076/cbddac75-9035-4d2e-a9b7-bb9b839423f6)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
Request re open #17587 is a wrong format (new source request not url change)

**Comment by alexphilip0019** [comment]
Can we get something like what's already done for hiperdex i.e override the base url so that no need to always update extension

**Comment by vetleledaal** [comment]
Domain is parked, couldn't find any new domain via Google.
