### ISSUE TITLE
Nitro Manga 

### ISSUE THREAD

**Issue by Hatashiki** [tachiyomiorg/tachiyomi-extensions#18663]
### Source information

Nitro scans and mangabaz 

### Source language

English 

### Source new URL

https://nitromanga.com/

### Other details

Nitro scans and mangabaz changed url

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Noir101** [comment]
update the extension 😑
