### ISSUE TITLE
Mangaswat 

### ISSUE THREAD

**Issue by 3lwoo** [tachiyomiorg/tachiyomi-extensions#18660]
### Source information

Mangaswat 1.4.41

### Source language

Arabic

### Steps to reproduce

1.open the source
2. Http error 404
3. Open webview
4. See google

### Expected behavior

Website should directly opened in webview and appear in source

### Actual behavior

Http errir 404

### Tachiyomi version

Tachiyomij2k 1.7.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kaaito0os** [comment]
The Source address is wrong when you click webview it will direct you to google search,
The address link for this site is https://goldragon.me/
And the title should be (Swat Manga).
I hope you fix it to the correct address

**Comment by Claudemirovsky** [comment]
Closed by #18752
