### ISSUE TITLE
Flame Scans site has shutdown

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi-extensions#18680]
### Source name

Flame Scans

### Source language

English

### Source link

https://flamescans.org/

### Other details

As of accessing this page on October 23, 2023 (GMT +8). A message appears when accessing in WebView (or even a regular web browser) due to site discontinuation.

(Though the app)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/c51adafa-dade-439d-bf78-fad9881b1870)
(Through a web browser)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/f8d35b20-a01b-426a-a468-d57457aa8243)

Note: This is applicable to any device that I used (Tachiyomi preview r6116 running under WSA with NextDNS as the DoH provider and Windows 11 with Microsoft Edge with Cloudflare as the DoH provider.)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by CedMIX-Productions** [comment]
I did changed the user agent here in the app to use the same as Microsoft Edge (in More -> Settings -> Advanced -> Default user-agent string)
User agent used: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61

Tachiyomi will fail with "Failed to bypass Cloudflare" but WebView says otherwise (video attached):

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/b0819caa-0c0a-470b-b43a-6200743cb80e

There's isn't any Cloudflare nag-screens on my experience (with the user-agent change applied).

**Comment by AriaDeAzure** [comment]
![Screenshot_2023-10-23-20-52-43-48_572064f74bd5f9fa804b05334aa4f912](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/104279446/7b36c36d-0116-4af5-bed6-2e6bc831da0d)

According to their Discord, they will be rebranding soon. I'm not sure if it's better to wait and rework the existing extension as soon as the rebranding is executed or if it's better to do a new extension from the ground up. It depends on a lot of factors. Probably it's best to wait and see (if all they change is the name/domain and keep everything else).

**Comment by luigiMinardi** [comment]
They're now at https://flamecomics.com/

**Comment by AriaDeAzure** [comment]
Just to let you know that Flame Scans officially changed domain to the link above. They were doing maintenance until just a couple of hours and the website is now available. From what I've understood, they are keeping things as they were and will take over everything (they also changed staff/). It should be safe to take care of this issue from now on.

**Comment by Dook42** [comment]
Idk how to do the thing but:

https://github.com/tachiyomiorg/tachiyomi-extensions/pull/18766
