### ISSUE TITLE
8Muses not working

### ISSUE THREAD

**Issue by Iambatman210** [tachiyomiorg/tachiyomi-extensions#18693]
### Source name

8Muses

### Source language

English

### Source link

https://comics.8muses.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
website is up form me

**Comment by vetleledaal** [comment]
> website is up form me

Same here.

@Iambatman210 if you're still having issues you should read through the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/), or hop onto [#support in Discord](https://discord.gg/tachiyomi). GitHub is not well suited for back and forth conversations.
