### ISSUE TITLE
Mangasusu: Changed their domain

### ISSUE THREAD

**Issue by kitsu2** [tachiyomiorg/tachiyomi-extensions#18698]
### Source information

Mangasusu 1.4.29

### Source language

Indonesia

### Steps to reproduce

1.Open the mangasusu extension
2.It does not feature comics

### Expected behavior

It should feature comics 

### Actual behavior

Does not display comics 

### Tachiyomi version

0.14.6

### Android version

11

### Other details

![Screenshot_2023_1024_221834](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/137640168/119fd2e4-0b13-43e3-ac09-7952da10a5a2)
Q
The display in webview looks normal 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kitsu2** [comment]
Hasn't this been fixed yet?

**Comment by Kiki88x** [comment]
Up! Domain changed to [mangasusuku.xyz](https://mangasusuku.xyz/)

Change the label from bug to new source.

**Comment by Kiki88x** [comment]
Just make new issue as "new source" so everyone can notice it.

**Comment by alessandrojean** [comment]
Don't open a new source request issue, this is not correct. This was already relabeled to a URL change issue.

**Comment by Kiki88x** [comment]
Oh sorry that's what I meant to... I forgot the label name lists. 😔

**Comment by niveanyctra** [comment]
Hasn't this been fixed yet?

**Comment by Kiki88x** [comment]
> Hasn't this been fixed yet?

Sadly nope until now.... Just be patient... Maybe next year. Cos i don't think anyone from dev see this, issue.
