### ISSUE TITLE
jinmantiantang can no longer be accessed from webview in the app

### ISSUE THREAD

**Issue by kayakibraco** [tachiyomiorg/tachiyomi-extensions#18704]
### Source information

jinmantiantang 1.4.38

### Source language

Chinese

### Steps to reproduce

1. browse -＞sources
2. open up the above-mentioned extension (jinmantiantang)
3. tap on "webview" button

### Expected behavior

it normally should open up a web page of the url where cloudflare verify you "as a human"

### Actual behavior

now the verification page will show for a split second before change to this new url that start of "blob:https...", then when you click on "open in brower", the following will show:
![Screenshot_2023-10-24-22-20-00-41_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/58750165/84b01e5f-7879-4068-b537-2b37f4384e53)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

the website work in actually Chrome app and other browser so I know it's not down. tried all source url in the extension settings but they all have the same issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CikaKure43** [comment]
I have the same thing happening on mangafreak and attempting to clear the cache in WebView on the blob page crashes the app.

**Comment by ouovouo** [comment]
[Tachiyomi v0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.7)
