### ISSUE TITLE
Manga-Scantrad issue

### ISSUE THREAD

**Issue by Eniiissay** [tachiyomiorg/tachiyomi-extensions#18700]
### Source information

Manga-scantrad 1.4.34

### Source language

French

### Steps to reproduce

1. Select any Manga/Webtoon/Manhwa 
2. Go in the Web view

### Expected behavior

Then you can browse on Manga-scantrad.

### Actual behavior

Instead you should have a black screen with no respons even if you use your own web browser.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

If you updating the library you got the cloudflare issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Not on Tachi's side.

**Comment by KirinRaikage** [comment]
This issue can be closed. Especially since the blob stuff has been solved. It's a classic Cloudflare issue.

**Comment by KirinRaikage** [comment]
Bumping to kindly close this as it technically still does work: 
![Screenshot_20231029_195930_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/11159175/8f06bf76-2f17-4f35-8bcd-0f3e7521dab3)
