### ISSUE TITLE
Timeline Comics

### ISSUE THREAD

**Issue by Zooldyck** [tachiyomiorg/tachiyomi-extensions#1871]
Source: https://timelinecomics.blogspot.com/?m=1
Language: Portuguese/Brazilian
Comic

**Comment by happywillow0** [comment]
Although the site looks like it has potential for a lot of things to read, each book is a link to Google Drive in a PDF format. 

Tachiyomi is unable to handle PDF comics as far as I am aware.

I would personally suggestion a book reader such as Moon reader to read PDFs that you download to your phone.

**Comment by alessandrojean** [comment]
Can be closed since the site doesn't even have a proper online reader, they just provide download links on Google Drive.
