### ISSUE TITLE
UltraLight Scans extension is not getting installed

### ISSUE THREAD

**Issue by mrpundir** [tachiyomiorg/tachiyomi-extensions#18718]
### Source information

UltraLight Scans 1.4.6

### Source language

English

### Steps to reproduce

UltraLight Scans extension is not getting installed
1- Not installing from within app itself
2- Not installing even if we download extension from Tachiyomi website and try it, getting error message: App not installed as package appears to be invalid

### Expected behavior

UltraLight Scans extension should get installed automatically from within app itself after clicking on Install

### Actual behavior

Within app, when we click on Install, it starts up package installer and then does nothing

### Tachiyomi version

Stable 0.14.7

### Android version

Android 13, MIUI Global 14.0.4

### Other details

![Screenshot_2023-10-26-00-26-55-992_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/46453835/a4569d95-ad05-48d8-9cef-0903117d3c43)
![Screenshot_2023-10-26-00-32-41-405_com google android packageinstaller](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/46453835/8ca7a744-92bf-41b9-9938-5e79708bc8d9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Not able to reproduce. Try installing the APK file with [SAI](https://github.com/Aefyr/SAI/releases/tag/4.5) or follow or guide about MIUI-related issues:

> Switch MIUI Optimizations under Developer Settings to OFF when installing extensions or updates to extensions. Alternatively, manually download updates from [here](https://tachiyomi.org/extensions/).

**Comment by mrpundir** [comment]
Hi @alessandrojean I followed your steps using SAI and got the following message:

A newer version of this package is already installed

INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 6 is older than current 17

See image/s attached

![Screenshot_2023-10-26-05-42-52-371_com.aefyr.sai.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/46453835/cf91b9a9-0818-45ea-ade9-63021dfe4ab3)

![Screenshot_2023-10-26-05-42-44-056_com.aefyr.sai.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/46453835/89a08d21-b6b7-4ff4-8144-dee66b2578b1)

**Comment by alessandrojean** [comment]
Ah, makes sense. The extension was likely not updated correctly when it (probably) changed themes.

**Comment by mrpundir** [comment]
I thoroughly looked up in my device and couldn't find any app or package installed by the name of Tachiyomi: UltraLight Scans

Even used third party apps like 'package manager' to list all packages on my device but there is no such package installed.

**Comment by mrpundir** [comment]
@alessandrojean any update please, also thanks for the help :)
