### ISSUE TITLE
Not passing captcha even in webview

### ISSUE THREAD

**Issue by PapaSpy69** [tachiyomiorg/tachiyomi-extensions#18722]
### Source information

ToonGod 1.4.36

### Source language

English

### Steps to reproduce

1. Opening the source
2. Keeps loading
3. Fails captcha in webview repeatedly 

### Expected behavior

The website should open

### Actual behavior

It doesn't open

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
