### ISSUE TITLE
Diskus Scan: HTTP error 403

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#18731]
### Source information

Diskus Scan 1.4.35

### Source language

Português

### Steps to reproduce

![Screenshot_20231025-230418632](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/90201611/59c69b34-d959-4ad5-a920-f641de5b678f)

### Expected behavior

should enter the scan normally

### Actual behavior

does not enter and appears HTTP error 403

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

the site works normally in web view but does not work in the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as they're doing it on purpose. Migrate to other extensions.
