### ISSUE TITLE
App freezes when attempting extension update/install 

### ISSUE THREAD

**Issue by CyberJman1** [tachiyomiorg/tachiyomi-extensions#18734]
### Source information

All of them. It's not a specific extension.

### Source language

N/A

### Steps to reproduce

1. Open app
2. Go to extension tab
3. Click update or install on new extension
4. Result: app freezes and phone states "app is not responding." Wait or close options given. Waiting does nothing. Stays frozen.

Tried clearing app cache, didn't fix...

### Expected behavior

When "update" or "install" is chosen, it should do the expected action.

### Actual behavior

App freezes. Have to force close.

### Tachiyomi version

0.14.6 and 0.14.7 both have the error.

### Android version

Android 14

### Other details

Pixel 7 phone 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
