### ISSUE TITLE
Cloudflare Issue

### ISSUE THREAD

**Issue by presifour** [tachiyomiorg/tachiyomi-extensions#18730]
### Source information

Shinigami 1.4.37

### Source language

Indonesia

### Steps to reproduce

In this extension you cannot download chapters, while in other extensions you can download chapters.

![Screenshot_20231026-082835](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/57415161/38790996-102a-4745-833a-87413654fad0)

### Expected behavior

Tolong diperbaiki

### Actual behavior

,.......

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DhimasArbi** [comment]
when try to solve cloudflare, It redirected like this
![Screenshot_2023-10-26-13-23-35-533_eu kanade tachiyomi debug](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/56208637/27979be9-95ae-40f1-82c1-5077b3025995)

**Comment by Rewtio** [comment]
Change your user agent then restart your app, it fixed it
