### ISSUE TITLE
Yomu Mangás: HTTP error 404

### ISSUE THREAD

**Issue by Nerannnn** [tachiyomiorg/tachiyomi-extensions#18757]
### Source information

Youmu mangás 1.4.3

### Source language

Portuguese 

### Steps to reproduce

When I open the extension a screen appears saying error 404

### Expected behavior

manga appear normally

### Actual behavior

 a screen appears saying error 404

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

I know that maybe this doesn't mean anything but if possible I would like the extension not to be removed it's already very difficult to find good fonts in Portuguese mainly because several sites are going down lately

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Will fix one more time but seems they're doing on purpose as they're selling VIP plans. Imagine actually paying for piracy...

**Comment by alessandrojean** [comment]
Not able to reproduce. Seems like it was a temporary issue.
