### ISSUE TITLE
Flame Scans moved website

### ISSUE THREAD

**Issue by morethanhater** [tachiyomiorg/tachiyomi-extensions#18759]
### Source information

Flame Scans 1.4.32

### Source language

English

### Source new URL

https://flamecomics.com/

### Other details

Flame Scans moved from flamescans.org to flamecomics.com
Need to update extension. 

Thanks in advance.
With love, morethanhater.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Noir101** [comment]
yes let's get it back🤝🏻
