### ISSUE TITLE
Cloudflare bypass

### ISSUE THREAD

**Issue by Mluffy02** [tachiyomiorg/tachiyomi-extensions#18758]
### Source information

Nhentai.net 1.4.39

### Source language

All

### Steps to reproduce

Will not bypass cloudflare protection even in web view.

### Expected behavior

Should bypass cloudflare automatically.

### Actual behavior

Keeps reloading after checking I am not robot box.

### Tachiyomi version

0.14.7

### Android version

Android 8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please check out https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare

**Comment by RambilE** [comment]
> Please check out https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare

He literally said that he tried the troubleshooting guide

**Comment by arkon** [comment]
I'd be a fool to believe everyone who fills in those checkboxes...

Regardless, the user agent change typically works but you'll need to experiment with them to find one that does work.

**Comment by Mluffy02** [comment]
Thank you for helping me regarding this problem, I tried the user agent change and it worked. Thank You again for your help.
