### ISSUE TITLE
Nhentai not opening in browser

### ISSUE THREAD

**Issue by Sakuta77** [tachiyomiorg/tachiyomi-extensions#18751]
### Source information

Nhentai 1.4.39

### Source language

English

### Steps to reproduce

First step - boot up app

Second step- open up any hentai using web view to pass cloudflare.

Issue here 

### Expected behavior

Cloudflare should load and ask me to hit the check box and then load straight to nhentai.

### Actual behavior

It tries to load cloudflare but the changes the url to say blop+website url
![Screenshot_20231027_084155_TachiyomiSY](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/142059861/052e71eb-05e7-4b46-b08c-8ef6f890757d)

### Tachiyomi version

App version: 1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
A fix for the blob issue was already submitted to the main app. Update your app if you haven't done yet or wait an update for your fork.
