### ISSUE TITLE
Manhwas.net error okhttp3 aún continua 

### ISSUE THREAD

**Issue by Marco-kun** [tachiyomiorg/tachiyomi-extensions#18762]
### Source information

Manhwas.net 1.4.10

### Source language

Español

### Steps to reproduce

1. Al abrir la extensión manhwas.net
2. Seleccionas un manhwa al azar
3. Debería aparecer los capítulos, pero no lo hacen apareciendo un error al respecto

### Expected behavior

Al abrir algún manhwa de la extensión, deberían aparecer los capítulos y que estén funcionales y no que marque error 

### Actual behavior

Al abrir la extensión aparecen los manhwas pero a la hora de seleccionarlos no aparecen los capítulos aparecieron el siguiente error
![Screenshot_2023-10-27-21-08-10-735_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/85567345/99231e94-f88c-456b-8bf9-eed084a00492)

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

Ya había enviado la misma solicitud anteriormente pero respecto al problema continuo igualmente 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Intenta borrar las cookies en los ajustes de la extensión

**Comment by necropower** [comment]
> Intenta borrar las cookies en los ajustes de la extensión

that worked for me!

**Comment by vetleledaal** [comment]
Can't reproduce the issue. Seems like the suggestion from @bapeey works for others so I'm closing this one.
