### ISSUE TITLE
Tachiyomi 

### ISSUE THREAD

**Issue by KashiSotaro2156** [tachiyomiorg/tachiyomi-extensions#18764]
### Source information

Toonily 

### Source language

English

### Steps to reproduce

I have been ban

### Expected behavior

This should fix that am ban

### Actual behavior

This happend on morning

### Tachiyomi version

0.14.7

### Android version

Poco M3

### Other details

Please unbanned me toonily I am just reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Closing in favor of #18760
