### ISSUE TITLE
Omega Scans: HTTP 400 in Browse

### ISSUE THREAD

**Issue by Grdsyt** [tachiyomiorg/tachiyomi-extensions#18761]
### Source information

Omega Scans 1.4.35

### Source language

English we are can only be be 

### Source new URL

https://omegascans.org/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
/edit-title "Omega Scans: HTTP 400 in Browse"
