### ISSUE TITLE
Can't read or download live, must open webview

### ISSUE THREAD

**Issue by HiSxY** [tachiyomiorg/tachiyomi-extensions#18768]
### Source information

Kiryuu 1.4.33

### Source language

Indonesia

### Steps to reproduce

cant read or download on tachi, must open in webview

### Expected behavior

fix

### Actual behavior

can fix it

### Tachiyomi version

0.14.7

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rewtio** [comment]
Kiryuu is working just fine, try clearing the cache & the database
#### * Don't worry, it won't delete your reading history

### Clear cache
`Settings` -> `Advanced` -> `Clear Cookies`
`Settings` -> `Advanced` -> `Clear Webview data`

### Clear Database
`Settings` -> `Advanced` -> `Clear database` -> `select "Kiryuu (ID)"` -> `press "Delete"`
