### ISSUE TITLE
Toonily (EN)- pages doesn't load

### ISSUE THREAD

**Issue by ElCacciatore** [tachiyomiorg/tachiyomi-extensions#18769]
### Source information

Toonily 1.4.42

### Source language

English 

### Steps to reproduce

Sélect manga, sélect Chapter, page doesn't load, webview blocked (maybe cloudflare) 

### Expected behavior

Read manga on page

### Actual behavior

Pages doesn't load

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ElCacciatore** [comment]
Webviewer works at the moment

**Comment by ElCacciatore** [comment]
You can delete my post, already à post on this problem there: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18760

**Comment by TheKingTermux** [comment]
Closing in favor of #18760

**Comment by MondoKuwabara** [comment]
I'm having this same issue with older uploads as well, so I don't know if it would still be considered a duplicate.
