### ISSUE TITLE
Infernal Void Scans Extension 'Broken'

### ISSUE THREAD

**Issue by NotPhoenic** [tachiyomiorg/tachiyomi-extensions#18778]
### Source information

Infernal Void Scans 1.4.32

### Source language

English

### Steps to reproduce

1. Open any chapter on the extension

### Expected behavior

Entire chapter loads

### Actual behavior

Only the first page loads and the rest fail to load, downloading also fails. Website works in web view.

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by semiya5** [comment]
Seems to be a new anti-scraping measure

**Comment by Riztard** [comment]
> Steps to reproduce 
> 1. Open any chapter on the extension

the image loaded just fine for me :/

**Comment by axu2** [comment]
Happens to me on Android 11 for specifically Lookism 472. Web view doesn't work either.

Opening in separate edge browser works fine though.

**Comment by semiya5** [comment]
Interestingly, fixed itself for me randomly. Idk what I did.

**Comment by arozaqf** [comment]
mine solved by migrating back to infernal void
