### ISSUE TITLE
Manhwaworld URL change 

### ISSUE THREAD

**Issue by tenkrat518** [tachiyomiorg/tachiyomi-extensions#18780]
### Source information

Mahwaworld 1.4.31

### Source language

English 

### Source new URL

https://aquascans.com/

### Other details

Old manga Is accesable but new one is not shown and library isnt updated when new manga Is added in webview of this source

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Chandanjk** [comment]
Observing same issue from past 10 days, please update the extension

**Comment by tenkrat518** [comment]
Yeah, I was waiting for someone to create a ticket but when no one did I decide to make my own. Ahh... So much was released And this one was my main source and now I can't read most of my manhwa :( 
(I know I can transfer my manga to another source but I dont wanna xd )

**Comment by tenkrat518** [comment]
Closing was my mistake

**Comment by Chandanjk** [comment]
Any update on this?

**Comment by vishnuodeyar** [comment]
Not yet, I guess we're gonna have to wait for a while
