### ISSUE TITLE
禁漫天堂cloudflare跳转错误

### ISSUE THREAD

**Issue by deadblue0910** [tachiyomiorg/tachiyomi-extensions#18788]
### Source information

Jinman Tiantang-1.4.38

### Source language

Chinese

### Steps to reproduce

点击WebView，始终会跳转到该页面
blob:https://18comic.vip/6fb7057c-d400-41cb-8d6f-abb5fab3ded2 
net::ERR_FILE_NOT_FOUND

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48860218/136d0a9d-ee9a-4062-aa57-151bbd15a95a

![Screenshot_20231029_131559_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48860218/76e36121-6950-46e1-ae07-67743ba75dc2)

### Expected behavior

应出现cloudflare确认是否真人页面，然后进入漫画页面

### Actual behavior

跳转到错误网页

### Tachiyomi version

1.9.3

### Android version

12

### Other details

App version: 1.9.3 (standard, d37463cf0, 57, 2023-10-01T21:27Z)
Preview build: 531
Android version: 12 (SDK 31)
Android build ID: DBY-W09 4.0.0.115(C00E113R3P5)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWDBY
Device model: DBY-W09
Device product name: DBY-W09
WebView user agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Safari/537.36

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SupKelelawar** [comment]
do you really updated your tachi for 0.14.7?

**Comment by arkon** [comment]
Looks like you're using TachiyomiSY. You'll need to wait for an app update that fixes this, or temporarily use a different version of the app (like the regular Tachiyomi v0.14.7).
