### ISSUE TITLE
Perf scans problem in library

### ISSUE THREAD

**Issue by pixelroll** [tachiyomiorg/tachiyomi-extensions#18793]
### Source information

PerfScan 1.4.18

### Source language

French

### Steps to reproduce

1. add a manga/webtoon to the library 
2. wait a while (1 day should be enough) 
3. Normally the page is now not found if accessed via the library, but the manga/webtoon is still on perf scan but it seems to have another one  address than the one added to the library.

### Expected behavior

The address of the manga/webtoon should remain findable since it is present on perf scan

### Actual behavior

address becomes unfound after a while

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Did you check if the address of the manga is the same? If it changes a lot you will have to migrate the entry from Perf Scan to Perf Scan.

**Comment by pixelroll** [comment]
> Did you check if the address of the manga is the same? If it changed you will have to migrate the entry from Perf Scan to Perf Scan. Tachiyomi can't track the URL changes of a manga which is in your library.

yes I migrate every time but I'm not going to do that every day... so I put the problem here.  This way, if the problem comes from the extension and not the site, it could be repaired.  If it comes from the site then the source is unusable and you might as well remove it.

**Comment by KirinRaikage** [comment]
Yeah. Like I told you there's nothing to do about it. This is a bad site behavior. If you're fine with that can you close the issue please ? Thanks
