### ISSUE TITLE
mangaStarz: can be removed 

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#18799]
### Source name

MangaStarz 1.4.35

### Source language

Arabic

### Source link

https://mangalike.org/

### Other details

No the link redirect to this website [New url 404](https://mangalike.org/) 

![Screenshot_2023-10-29-23-35-31-478_eu kanade tachiyomi-edit](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/61906880/70ce487c-de03-46e9-b9ac-69c23b3940de)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by yemenihandsome** [comment]
No, the site is still working, just change the link  
https://mangastarz.org
