### ISSUE TITLE
Group Removal

### ISSUE THREAD

**Issue by Hayatetan** [tachiyomiorg/tachiyomi-extensions#18807]
### Source link

https://remangas.net

### Other details

Hello guys, please don't laugh at my nick... I would like to ask you guys to take down a small TL Portuguese group of mine for now, remangas.net. Well, maybe my group will die in the next few months, so consider this a thing you guys would do anyway. But let's see, haha. I can prove my ownership at night on Discord: https://discord.gg/5hGbu6C  @hayatesann , or by posting a TL that you would like. I believe that my group follows all the rules since we stop immediately when a comic is licensed in our language, and we are not agregators either. If we were, we wouldn't be in this situation, haha!

### Requirements

- [X] I've added a `TXT` DNS record for my domain with the value `tachiyomi-verification`
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by alessandrojean** [comment]
> I can prove my ownership at night on Discord

Proof of ownership is done by the `TXT` DNS record as stated in the requirements.

> I've added a `TXT` DNS record for my domain with the value `tachiyomi-verification`

**Comment by alessandrojean** [comment]
Will be removed by #18845.

Note we don't have control over the user installs, so we can't force them to uninstall the extension and users that still have it will be able to keep using it for some time until the app still supports `v1.4` extensions, although we don't recommend users keeping obsolete extensions installed.

If you want to make sure these users won't be able to access your site through the obsolete extension, you will need to add some additional block checks on your side, and that we can't provide help with.
