### ISSUE TITLE
[OPex] Only works in Brazil

### ISSUE THREAD

**Issue by highlabs** [tachiyomiorg/tachiyomi-extensions#18808]
### Source information

OPex 1.4.6

### Source language

Portuguese Brazillian

### Steps to reproduce

1. Open and install OPex extension in Tachiyomi.
2. Try to load the One Piece chapters, will show a "Null Pointer Exception" error without any other details.
3. Click on WebView icon and try to read any chapter. The page will show the chapter name, but will not any images.

If you connect to a VPN in Brasil, it will fix the update and will show the chapter on the page.

You can reproduce this on PC too.

Connected from a Spain VPN (page: /manga-1096/)

```
<article class="manga">
   <header>
      <h1>Capítulo <strong>1096</strong></h1>
      <h2>Kumachi</h2>
   </header>
</article>
```

Connected from a Brasil VPN
```
<article class="manga">
    <a class="ler-mesmo" href="/mangas/leitor/1096/"><span>LER ONLINE</span></a>
    <header>
        <h1>Capítulo <strong>1096</strong></h1>
        <h2>Kumachi</h2>
    </header>
    <a class="capa" href="/mangas/leitor/1096/"><img src="/mangareader/mangas/1096/001_m.png" /></a>
    <div class="opcoes"><a href="/mangas/leitor/1096">Ler</a></div>
</article>

```

### Expected behavior

1. Open and install OPex extension in Tachiyomi.
2. Try to load the One Piece chapters. If fails will show an error explaining better that the manga is not available due to external restrictions.

### Actual behavior

1. Open and install OPex extension in Tachiyomi.
2. Try to load the One Piece chapters, will show a "Null Pointer Exception" error without any other details.
3. Click on WebView icon and try to read any chapter. The page will show the chapter name, but will not any images.

### Tachiyomi version

0.14.7

### Android version

Android / One UI 5.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I guess this is just how they designed the site. A lot of sites from the Brazilian scanlator scene are geolocked to try to prevent major DMCA issues.

Even if we van build the URL by the chapter number in the extension side, it's not guaranteed it will always work.

> Click on WebView icon and try to read any chapter. The page will show the chapter name, but will not any images.

The general rule is: if it doesn't work properly on WebView, it will not work on the extension. The only recommendation we can give in these cases is using a VPN or reading their content on other aggregators.
