### ISSUE TITLE
URL Change

### ISSUE THREAD

**Issue by Blacknova21** [tachiyomiorg/tachiyomi-extensions#18816]
### Source information

Nhentai 1.4.39

### Source language

English multi

### Source new URL

https://nhentai.to/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is just a copycat and the original one haven't changed its domain. If you want this to be added, open a Source request instead.
