### ISSUE TITLE
AsuraScans failing to connect

### ISSUE THREAD

**Issue by AhmedOsama96** [tachiyomiorg/tachiyomi-extensions#18814]
### Source information

asurascans

### Source language

https://asuratoon.com/

### Steps to reproduce

Example: 
I try to search for new titles
then the search happens
I check Asurascans and I find it not working 
+ 
when I update the library to check for new titles 
Asurascans always giving me an error

### Expected behavior

the extensions should be available to view in the application so I can view sources in it or migrate other sources to it.

### Actual behavior

it's giving me this message : 
java.net.SocketTimeoutException: failed to connect to asuratoon.com/104.21.62.214 (port 443) from / 192.168.1.5 (port 45186) after 10000ms

### Tachiyomi version

0.14.7

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is usually a connection issue. Try the troubleshooting guide in the acknowledgements section.

**Comment by AhmedOsama96** [comment]
Checked and it's online

**Comment by alessandrojean** [comment]
Try the troubleshooting guide then. Otherwise ask for support about this in our #support channel in [Discord](https://discord.gg/tachiyomi).
