### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Nerannnn** [tachiyomiorg/tachiyomi-extensions#18819]
### Source information

Mangás-chan 1.4.28

### Source language

Portuguese 

### Steps to reproduce

the webview page is buggy and this is somehow influencing the extension as sometimes a time out message appears

### Expected behavior

![Screenshot_20231030-234836](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/135178613/0efcb50b-21cf-4be1-be9d-0ecb81767bc7)

### Actual behavior

![Screenshot_20231030-233510](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/135178613/a7b62d42-1206-49aa-b421-0ccb9cd2f733)

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They're doing stuff on purpose to break the extension. Migrate to other sources.

**Comment by Nerannnn** [comment]
I don't think so because this problem happened right after I cleared the
cache of chapters and webview data

Em ter., 31 de out. de 2023 00:18, Alessandro Jean ***@***.***>
escreveu:

**Comment by Nerannnn** [comment]
Furthermore, the mangas are kind of reappearing, so I know this may not solve anything, but please don't remove this extension and if possible, update it as it wasn't long ago that I had to migrate several manga to this extension as many sites Brazilian manga books are disappearing and for the same reason there aren't many decent Portuguese extensions available either

**Comment by alessandrojean** [comment]
We don't offer long term support to sites that have this bad behavior so it will eventually be removed. Don't complain with us as we can't do anything about it, complain with the sites that do this instead.
