### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by BoladoCafe** [tachiyomiorg/tachiyomi-extensions#18820]
### Source information

Diskus Scan

### Source language

Português PT-BR

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They're breaking the extension on purpose. Use other sources. Also please do fill all the fields correctly next time. Filling all with a dot will not help into anything.
