### ISSUE TITLE
Add OzulScansEn

### ISSUE THREAD

**Issue by Maou20** [tachiyomiorg/tachiyomi-extensions#18833]
### Source name

OzulScansEn

### Source link

https://ozulscansen.com

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Maou20** [comment]
No

**Comment by AntsyLich** [comment]
it is

**Comment by Maou20** [comment]
I'm just asking to add this source as a single extension not as a multiple extension like this post #17981.
The arabic version of this website is not working anymore it just redirect you to a site called kingofmanga or something like that.

**Comment by alessandrojean** [comment]
As the bot said, someone else already opened a request for this site, so your issue is a duplicate and hence closed. Please don't insist.
