### ISSUE TITLE
SuryaScans domain change again

### ISSUE THREAD

**Issue by NotPhoenic** [tachiyomiorg/tachiyomi-extensions#18843]
### Source information

Surya Scans 1.4.28

### Source language

English

### Source new URL

https://suryacomics.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ArjixWasTaken** [comment]
Could this be made into a setting for the source?

Or are the manga links broken between sites?

**Comment by Azim** [comment]
Old site uploads single-page chapters saying "go to new site plz"

**Comment by thegreatdk** [comment]
Hi guys, is there any update on this?
