### ISSUE TITLE
Temple Scan: "Unable to extract series information" after website update

### ISSUE THREAD

**Issue by AriaDeAzure** [tachiyomiorg/tachiyomi-extensions#18857]
### Source information

Temple Scan 1.4.33

### Source language

English

### Steps to reproduce

If you try to check the series the scanlator is working on, the error immediately appears. As such, it also doesn't work during the update.

![Screenshot_20231103-202259_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/104279446/e40e0bfd-d56d-40b6-9378-795a863b1064)

After trying to update, an error appears saying "No chapter was found".

### Expected behavior

When you click on the extension to check the series the scanlator is working on, the information should appear. It also should work during the update.

### Actual behavior

It's not possible to use the extension as intended.

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

Temple Scan's website was just updated (I suspect they changed their theme, but not confirmed) and several things changed. The extension needs to reworked to work with the currently deployed updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Site now uses HeanCMS

**Comment by Faviur** [comment]
Is heancms an extension because i can't find it

**Comment by Faviur** [comment]
> Site now uses ### He**

> Site now uses HeanCMS

Is heancms an extension because i can't find it

**Comment by Faviur** [comment]
> Site now uses HeanCMS

Is heancms an extension because i can't find it

**Comment by AriaDeAzure** [comment]
> > Site now uses HeanCMS
> 
> Is heancms an extension because i can't find it

No, think of it like a template that the website uses. Knowing which one it is helps fixing or building a new extension.

**Comment by Faviur** [comment]
> > > Site now uses HeanCMS
> > 
> > 
> > Is heancms an extension because i can't find it
> 
> No, think of it like a template that the website uses. Knowing which one it is helps fixing or building a new extension.

Okay... The extension is working now after updating it
