### ISSUE TITLE
Sinensis - 404 error

### ISSUE THREAD

**Issue by gatinhecomunista** [tachiyomiorg/tachiyomi-extensions#18867]
### Source information

Sinensis Scan - Português

### Source language

Português

### Steps to reproduce

When trying to open the scan, it gives a 404 error. I can't read anything

### Expected behavior

That there is no error and we can read the works

### Actual behavior

It doesn't open, it gives an error and we can't read the works

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Their site seems to be having issues and it's down at the moment. Wait until they fix it.
