### ISSUE TITLE
YugenMangas: Error 404

### ISSUE THREAD

**Issue by seba1107** [tachiyomiorg/tachiyomi-extensions#18871]
### Source information

YugenMangas 1.4.27

### Source language

Spanish

### Steps to reproduce

1. Open YugenMangas's source

### Expected behavior

Mangas should be listed

### Actual behavior

Error 404.
WebView working correctly

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
Wait, that happens sometimes then it fixes itself and returns to normal

**Comment by seba1107** [comment]
> Wait, that happens sometimes then it fixes itself and returns to normal

That's right, it fixed itself
