### ISSUE TITLE
MANGA Plus: Mark extra chapters as `-1`

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/tachiyomi-extensions#18878]
### Source information

MangaPlus 1.4.49

### Source language

English/Multi

### Steps to reproduce

1. Go to title with a special chapter (containing numbers in the chapter name) available. 
2. They are marked as "ex" as of now. 

Screenshot taken from the title "Even If You Slit My Mouth"
![Screenshot_2023-11-07-12-46-20-11_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/23010526/4b92ee57-320e-4138-8d5a-c31f9c8f7f90)

### Expected behavior

The special chapters should not matter when searching for missing chapters. 

### Actual behavior

Due to ex chapters having numbers in the chapter title, the "missing chapters in list" is giving false information. 

### Tachiyomi version

App version: 0.14.7-6171

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
These are already beeing marked as `-1f` as they fall in the parsing. Likely an app issue, so report there.

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/f1c92f23d4356d31549cf6ad495ecf328c6cd710/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusDto.kt#L306
