### ISSUE TITLE
Ozulscans URL change 

### ISSUE THREAD

**Issue by firstdarsh** [tachiyomiorg/tachiyomi-extensions#18879]
### Source information

Ozulscans 1.4.28

### Source language

Arabic

### Source new URL

https://ozulscansen.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by firstdarsh** [comment]
There is an error because the problem is not a duplicate like number #17981

**Comment by alessandrojean** [comment]
There's no error, it's a duplicate still.
