### ISSUE TITLE
Baozimh.org Error: Null

### ISSUE THREAD

**Issue by Hakoyu** [tachiyomiorg/tachiyomi-extensions#18875]
### Source information

Baozimh.org 1.4.28

### Source language

Chinese

### Steps to reproduce

Null

### Expected behavior

Not error

### Actual behavior

Error: Null

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all requested information appropriately next time, otherwise it keeps difficult to any contributor to reproduce and fix your issues.
