### ISSUE TITLE
https://kingofmanga.com

### ISSUE THREAD

**Issue by Lordo12** [tachiyomiorg/tachiyomi-extensions#18888]
### Describe why this should be added

Burji Add Location https://kingofmanga.com/ To apply tachiyomi Please Because Manga Website ozulscans.com Has stopped and moved to https://kingofmanga.com/ and thank you

### Other details

https://kingofmanga.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please use the Source request form instead.
