### ISSUE TITLE
Update URL muslos no sekai

### ISSUE THREAD

**Issue by Simpyke** [tachiyomiorg/tachiyomi-extensions#18894]
### Source information

Muslos no sekai  1.4.7

### Source language

Spanish 

### Source new URL

https://mangasnosekai.com/?fbclid=IwAR3jCscVbGreBJTIz20Tj_Zxv-3kC4Gt9JkBeK6ANhDpWdNFKvmajHDEZx8

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by chimpandolfo159** [comment]
any update on this?

**Comment by Simpyke** [comment]
Ninguno la extencion sigue igual

**Comment by BrutuZ** [comment]
Not quite an update, but close enough: #18898

**Comment by Simpyke** [comment]
Vi que alguien pedía que se eliminará la extencion pero dentro de la página de facebook de la mismo scan reconocen saber que existe la extencion

**Comment by BrutuZ** [comment]
That's a given, can't ask to remove if you don't know it exists.

**Comment by Simpyke** [comment]
So it can't be updated at the moment

**Comment by Yura-ia** [comment]
Well, there was/is an extension of our web, that would be the web we made by blog (we closed it to make way for our new web, made from 0),  my point is, I would like this new web to have no extension or update.
![Captura](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/85031557/a00f80c0-0d12-4f81-8ec3-5cecbfe479db)

**Comment by JedeGM** [comment]
Es posible que la extensión "muslos no sekai" se actualize a "mangas no sekai" ya que cambiaron su dns, gracias

The "muslos no sekai" extension may be updated to "mangas no sekai" since they changed their dns, thanks
