### ISSUE TITLE
Emperor Scan 

### ISSUE THREAD

**Issue by Unknoweird** [tachiyomiorg/tachiyomi-extensions#18914]
### Source information

Emperor Scan 1.4.32

### Source language

Spanish 

### Steps to reproduce

1. Enter extension.
2. java IO exception. Fail in avoid Cloudflair

### Expected behavior

Enter and start searching 

### Actual behavior

Java IO exception. Fail to avoid Cloudflair

### Tachiyomi version

TachiJ2K 1.7.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
See the "Cloudflare" section in the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare)

**Comment by Unknoweird** [comment]
> See the "Cloudflare" section in the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare)

It's blocked of the page
