### ISSUE TITLE
247 manga changed to zinmanga 

### ISSUE THREAD

**Issue by LittleKnightG** [tachiyomiorg/tachiyomi-extensions#18928]
### Source information

247manga version 1.4.32

### Source language

English 

### Steps to reproduce

I just update it oh my mangas and one a day a came up with all of the manga I had into 247 manga as no chapter found then I want you and chat a was a different site name and then try download the manga anything

### Expected behavior

You should just update all of them with the chapters and let me download them

### Actual behavior

Sales no chapters found does in the download them the websites under different URL

### Tachiyomi version

0.14.7

### Android version

No sure 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Wrong template
