### ISSUE TITLE
Cant Access the Extentions

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#18938]
### Source information

Shinigami 1.4.38

### Source language

Indonesia

### Steps to reproduce

1. No too long loading
2. Can Access the extention

### Expected behavior

Can open the extention without too long loading 

### Actual behavior

Can read manga/manhwa normally

### Tachiyomi version

0.14.7

### Android version

Android 12

### Other details

![Screenshot_20231112-171915](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/81138524/893b18f2-2b00-4905-89a0-40dc4f224d84)
![Screenshot_20231112-171908](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/81138524/0b3647d7-6965-4093-871a-45caab39584c)

Too long loading and then i cant Access the extention, when i open without webview it should verify the security checklist but when i verify it always repeated over and over again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the [**"Solving Cloudflare issues"**](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare) section and the three consecutive ones. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try [**changing** the **User Agent** string](https://tachiyomi.org/docs/guides/troubleshooting/#changing-your-user-agent), use [**DOH / DNS Over HTTPS**](https://tachiyomi.org/docs/faq/settings#what-is-dns-over-https), or change your **DNS** in your phone settings, if you have done it but still no effect try to use **VPN**, [**delete** the **Cookies**  and the **WebView Data**](https://tachiyomi.org/docs/guides/troubleshooting/#clearing-cookies-and-webview-data), but this is a last measure, if it doesn't work, [**migrate** to **other sources**](https://tachiyomi.org/docs/guides/source-migration) or wait until they lower their protection.
