### ISSUE TITLE
Extension showing http error 429

### ISSUE THREAD

**Issue by Syed134678** [tachiyomiorg/tachiyomi-extensions#18939]
### Source information

999Hentai 1.4.4

### Source language

Multi

### Steps to reproduce

1. Tap on the Extension
2. It doesn't open and shows http error

### Expected behavior

It should run without issue

### Actual behavior

It shows http error 429

### Tachiyomi version

0.14.7

### Android version

Android 9

### Other details

![Screenshot_20231112-154334](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/150588921/bbcfd9ed-3df1-4d7a-8ebf-bdd9c54d4bde)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hada45** [comment]
The previous version of the extension are still working

**Comment by Syed134678** [comment]
> The previous version of the extension are still working

Is there a way yo get the previous version?

**Comment by CrepeTF** [comment]
No

**Comment by CrepeTF** [comment]
And HTTP error 429 is a rate limit error. It limited your access to it because you used it too much. Wait for them to reset you or use a vpn.

**Comment by Hada45** [comment]
> > The previous version of the extension are still working
> 
> Is there a way to get the previous version?

- You can ask someone that still has the older version of the extension to extract the apk from their phone, I'm search for it, let me know if you found it.
You also can search another older version extension on wayback machine, but unfortunately there no archive for this extension

**Comment by Hada45** [comment]
> And HTTP error 429 is a rate limit error. It limited your access to it because you used it too much. Wait for them to reset you or use a vpn.

So it only limit it on the tachiyomi app?, because i can still access it on the tachiyomi webview
