### ISSUE TITLE
Add mangaflix New source

### ISSUE THREAD

**Issue by BoladoCafe** [tachiyomiorg/tachiyomi-extensions#18972]
### Source name

Mangaflix

### Source link

https://mangaflix.net

### Source language

Português PT-BR 

### Other details

NSFW = no
New website
Site português

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Site seems to be broken, the details page doesn't even load.

**Comment by BoladoCafe** [comment]
For me, it's working normally.

https://mangaflix.net/browse

**Comment by alessandrojean** [comment]
Try opening any manga and you probably will get a Server error. It's clear it's unstable and broken.
