### ISSUE TITLE
Comick entries in the library displaying unread chapters, even there are not any of them

### ISSUE THREAD

**Issue by johndoe432** [tachiyomiorg/tachiyomi-extensions#18979]
### Source information

Comick 1.4.38

### Source language

English

### Steps to reproduce

1, Add any title to your library
2, Filter scanlator groups
3. Read all the chapters
4. Manga's card in the library will show unread chapter count (for some reason)

### Expected behavior

As all the chapters were read, no counter would be present until new chapters

### Actual behavior

Mentioned earlier

### Tachiyomi version

TachiyomiJ2K 1.7.3

### Android version

Anfroid 14

### Other details

This could be the fork's issue. However, this bug happens only while using the Comick extension, so I thought I should submit the issue here first.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Sounds like a fork issue, as you suspected. See Jays2Kings/tachiyomiJ2K#1627. Not sure why it only affects ComicK.
