### ISSUE TITLE
Hentai2Read inaccessible and a redirect

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi-extensions#18976]
### Source name

Hentai2Read

### Source language

English

### Source link

https://hentai2read.com

### Other details

The site is inaccessible due to a redirect to liquidnet abuse page (their hosting provider?).

1. Though extension:
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/945116f1-493a-4e5a-a584-29e73a1b6701)

2. Though Tachiyomi webview (Does not load):
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/2616f6f2-18a0-46ed-bc87-97ad50995abd)

3. Though a web browser:
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31158494/317e166b-355a-4e74-982e-8047d2ce8656)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Website is up, can be closed
