### ISSUE TITLE
Shinigami: Error 429 When Fetching Library

### ISSUE THREAD

**Issue by brianabdl** [tachiyomiorg/tachiyomi-extensions#19026]
### Source information

Shinigami 1.4.38

### Source language

Indonesia

### Steps to reproduce

1. Add at least 10 or more manga
2. Do global refresh update

### Expected behavior

The manga should be all normally refreshes without error

### Actual behavior

Some manga successfully update but some other is showing `Error 429`

### Tachiyomi version

0.14.7

### Android version

Android 12

### Other details

HTTP error 429
   Shinigami (ID)
    - The Tutorial Tower Of The Advanced Player
    - The World After The Fall
    - Tomb Raider King Side Story

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Maybe related to #18506

**Comment by Rewtio** [comment]
> just now I tried it but it working fine, maybe your internet connection problem

The additional details only show some of the error manga that had been flagged by the Shinigami due to rate limit,
Try adding 10+ mangas, then you can reproduce the bug again

**Comment by Rewtio** [comment]
> Maybe related to #18506

It's related and had been fixed, but it occur again so i though i opening another issue again

**Comment by TheKingTermux** [comment]
> It's related and had been fixed, but it occur again so i though i opening another issue again

Hhmm but i just fine reading on that extension, i actually reading [this Manhua](https://shinigami.sh/series/logging-10000-years-into-the-future/) Started at 10pm last night and just finished reading it, yeah it still need to resolve the Cloudflare, but after it i can start reading again (interval 1 hour / every 15 chap / every 30 chap and Soo on, after it need to resolve the Cloudflare again) and it works just fine
