### ISSUE TITLE
Http 404 error

### ISSUE THREAD

**Issue by Aceshaikh** [tachiyomiorg/tachiyomi-extensions#19028]
### Source information

Readers point 1.4.31

### Source language

English

### Steps to reproduce

Opening the source in tachiyiomi gives error 404

### Expected behavior

Website working

### Actual behavior

HTTP 404, check website in webview

### Tachiyomi version

TachiyomiSY Preview r532

### Android version

Android 13

### Other details

Lyra Scans has taken over this domain and rebranded it to quantum scans and changed the theme of the website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
There are two extensions pointing to the same domain (readers-point.space). You can migrate to 'Quantum Scans', it seems to work for me.

Keeping this issue open so the old extension can be removed
