### ISSUE TITLE
Implementation Mangapark v5x

### ISSUE THREAD

**Issue by Geired25** [tachiyomiorg/tachiyomi-extensions#19024]
### Source name

Mangapark v3

### Source language

English

### Describe your suggested feature

I request the upgrade of mangapark v3 to mangapark v5x because there are some Manga which are only on the newer version

### Other details

The other requests where closed by a bot without resolution and the other was open at February without a response

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Don't open duplicate requests. #15310
