### ISSUE TITLE
Access denied Error code 1020

### ISSUE THREAD

**Issue by ErarichXV** [tachiyomiorg/tachiyomi-extensions#19037]
### Source information

Hentai teca 1.4.32

### Source language

Português (Brasil)

### Steps to reproduce

Just access any manga already favorited with this extension and the chapters don't load and when I try to access the website through the app, the error appears that it was not possible to go through CloudFire.

### Expected behavior

The chapters should appear and it should also be possible to update all the manga linked to that extension.

### Actual behavior

The chapters do not load, updates regarding manga linked to that extension fail and it is also not possible to access the app via WebView

### Tachiyomi version

0.14.7

### Android version

Android 10

### Other details

! java.io.IOException: Falha ao contornar o Cloudflare
  # Hentai Teca (PT-BR)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We can't do anything about Cloudflare. Wait until they lower their protection or just use other sources.
