### ISSUE TITLE
禁漫天堂每日更新不显示

### ISSUE THREAD

**Issue by YuguangNevL** [tachiyomiorg/tachiyomi-extensions#19058]
### Source information

jinman tiantang 1.4.39

### Source language

chinese/中文

### Steps to reproduce

jinmantiantang 更新页 不显示
到具体漫画 下拉更新显示：NullPointerException:null

### Expected behavior

jinman tiantang 1.4.38 正常工作

### Actual behavior

jinman tiantang 1.4.39 更新了无法正常工作

### Tachiyomi version

0.14.7

### Android version

MIUI14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by in-out** [comment]
same here
