### ISSUE TITLE
Olympus Scanlation: Changed their domain

### ISSUE THREAD

**Issue by Scaredeadth** [tachiyomiorg/tachiyomi-extensions#19081]
### Source information

1.4.5

### Source language

Español

### Source new URL

https://olympusvisor.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Herciyuan** [comment]
I wanted to comment on the same thing
