### ISSUE TITLE
BR Mangás: Redirecting to external domains

### ISSUE THREAD

**Issue by CrazyBot666** [tachiyomiorg/tachiyomi-extensions#19086]
### Source information

Br Mangás 1.4.5

### Source language

Portuguese

### Steps to reproduce

1.Open Tachiyomi.
2.Choose manga from brmangas.

### Expected behavior

Manga should open normally

### Actual behavior

Manga didnt open.

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

Manga doesnt open, nor can i download them manually, no error appear, only a black blox without text

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
A user reported the chapters in their site are redirecting to external sites with the content. This makes things complex to handle as we can't also really trust the other arbitrary domains as being theirs. Other extensions that did these bad behaviors in the past got removed.

I will take a look but I already advice to migrate to better sources.
