### ISSUE TITLE
Novelcool doesn't detect any pages in most of the mangas

### ISSUE THREAD

**Issue by Motion0112** [tachiyomiorg/tachiyomi-extensions#19094]
### Source information

Novelcool 1.4.2

### Source language

English

### Steps to reproduce

1. Click on any of the charapters of an afected manga
2. Tries too load it
3. An error saying it didn't found any page is reported.

### Expected behavior

It should open the chapter normally, because you can read it in the web interface.

### Actual behavior

It says there are no pages.

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by deljhn** [comment]
when is this going to fix?
