### ISSUE TITLE
Yugenaangas error 400

### ISSUE THREAD

**Issue by Hayashi13q4** [tachiyomiorg/tachiyomi-extensions#19098]
### Source information

YugenMangas 1.4.29

### Source language

Español

### Steps to reproduce

![Screenshot_20231125_185723_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/109044821/61ec2d10-1635-4120-9139-aa32518b289e)

### Expected behavior

The series should be able to be updated without any problem

### Actual behavior

However, I get error 400 when entering the extension

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
Working. Es cuestión de esperar que después de horas vuelve a su normalidad.

**Comment by vetleledaal** [comment]
Seems like this was an issue with the site, I also can't reproduce the error.
