### ISSUE TITLE
Adding option

### ISSUE THREAD

**Issue by aymanharrawi** [tachiyomiorg/tachiyomi-extensions#19101]
### Source name

No sources 

### Source language

No language 

### Describe your suggested feature

can you add option to disable .nomedia files on downloaded chapters please?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Most people do not want manga pages in the default gallery app, [which is why the `.nomedia` files are created](https://github.com/tachiyomiorg/tachiyomi/issues/9390#issuecomment-1520643969).


 In any case, this is not something that can be changed from the extension side.
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

**Comment by aymanharrawi** [comment]
I understand, just suggesting to ad option to tachiyomi settings to choose if i want to add them or not, on next update,
