### ISSUE TITLE
Gekkou Scans: Changed their domain, CMS and requires login

### ISSUE THREAD

**Issue by Mynameluis** [tachiyomiorg/tachiyomi-extensions#19106]
### Source information

Gekkou Scan 1.4.31

### Source language

PT BR 

### Source new URL

https://gekkouscans.top/

### Other details

Precisa fazer login para ter acesso ao site

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please use the correct Source URL change report issue template next time.
