### ISSUE TITLE
To improve luscious

### ISSUE THREAD

**Issue by redahnnane** [tachiyomiorg/tachiyomi-extensions#19119]
### Source name

Luscious

### Source language

All

### Describe your suggested feature

Make many chapters into one chapter consisting of pages that will make the albums easier to watch 

### Other details

For example instead of 4657 chapter 
Make it 1 chapter with 4657 pages

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Iirc the extension already have that option, I think it's called "Merge Chapter"

**Comment by TheKingTermux** [comment]
> How can I active it ?

- Go to extensions tab 
- Look for the Luscious extension
- Select settings
- Select the language you use in that extension
- Enable "Merge Chapter" (the checkbox)

**Comment by redahnnane** [comment]
> > How can I active it ?
> 
> * Go to extensions tab
> * Look for the Luscious extension
> * Select settings
> * Select settings the language you use in that extension
> * Enable "Merge Chapter" (the checkbox one)
> * Restart your Tachiyomi app (you may not do this, but it is highly recommended)
> 
> Edit : I think this answer is enough to close this issue

Thank you
