### ISSUE TITLE
MangaRead.org: The image couldn't be loaded / can't download

### ISSUE THREAD

**Issue by Vygrnd** [tachiyomiorg/tachiyomi-extensions#19111]
### Source information

Mangaread.org

### Source language

English

### Steps to reproduce

1.global update
2.download chapter

### Expected behavior

Download complete

### Actual behavior

Downloads become error

### Tachiyomi version

0.14.7

### Android version

Galaxy a50

### Other details

![Screenshot_20231127-125446_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152138011/be9a0eb0-db40-40f8-ae68-3dfc398a95fd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Possibly related to tachiyomiorg/tachiyomi#10183

**Comment by vetleledaal** [comment]
/edit-title "MangaRead.org: The image couldn't be loaded / can't download"

**Comment by vetleledaal** [comment]
This is an issue that only occurs when using a mobile User-Agent. For now you can reset the User-Agent in the settings and restart Tachiyomi.

Desktop:
```html
<img id="image-0" src="https://www.mangaread.org/.../4.jpeg" class="wp-manga-chapter-img">
```

Mobile:
```html
<img id="image-0" data-cfsrc="https://www.mangaread.org/.../4.jpeg" class="wp-manga-chapter-img" style="display:none;visibility:hidden;">
<noscript><img id="image-0" src="https://www.mangaread.org/.../4.jpeg" class="wp-manga-chapter-img"></noscript>
```
