### ISSUE TITLE
Kaynak önceden çalışıyordu 3 aydır çalışmıyor sorun giderilirse çok iyi olur

### ISSUE THREAD

**Issue by Warlord7272** [tachiyomiorg/tachiyomi-extensions#19125]
### Source information

Webtoon Tr   sürüm: 1.4.32

### Source language

Türkçe

### Steps to reproduce

Kaynak önceden çalışıyordu 3 aydır çalışmıyor kaynağa girince hata veriyor lütfen bu sorun giderilsin

### Expected behavior

Magların açılması ve okuyabilmek

### Actual behavior

![Screenshot_2023-11-29-00-33-20-064_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152335943/f3300c19-7c05-414f-ada2-aab6430686f7)

### Tachiyomi version

0.14.7

### Android version

Benim telefonun android sürümü 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
