### ISSUE TITLE
Source offline

### ISSUE THREAD

**Issue by Kame62** [tachiyomiorg/tachiyomi-extensions#19126]
### Source name

Hentai teca

### Source language

Portuguese 

### Source link

https://hentaiteca.net/

### Other details

Extension down, but the site is active 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
