### ISSUE TITLE
Downloaded location not working on preview version 

### ISSUE THREAD

**Issue by Liking-Link** [tachiyomiorg/tachiyomi-extensions#19135]
### Source information

Preview r6237. App version: 0.14.7-6237 (standard, 27c4db752, 110, 2023-11-26T21:31Z)  WebView: Android System WebView 119.0.6045.67

### Source language

English 

### Steps to reproduce

1. After updating new version no download shows .
 2. I allowed rechecked storage location and permission, it's not working for preview version but works fine for stable version.
 3. Clicked on invalidate index , still not working.
![Screenshot_2023-11-29-19-14-25-71_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/117823692/34f30157-e738-4ea5-bed0-121249e5e1e3)
![Screenshot_2023-11-29-19-14-18-87_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/117823692/ac86558f-fb5f-481d-9083-09e4bf1fd9c3)

### Expected behavior

![Screenshot_2023-11-29-19-10-10-00_5734e8eb49b4234b62f913f831715b0f](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/117823692/1f363d9e-f0b8-4f0e-9021-ea16edbd1e25)
I use 2 different location for stable and preview version. Preview version application DOESN'T work both storage location.

### Actual behavior

Instead it shows library is empty. Let's get started.

### Tachiyomi version

0.14.7-6237

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
> - [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

I think you've already read this because you have already checked it, but why are you making this issue in the extension section?
