### ISSUE TITLE
Komikcast URL change

### ISSUE THREAD

**Issue by CharlieRivalno** [tachiyomiorg/tachiyomi-extensions#19139]
### Source information

komikcast 1.4.51

### Source language

Indonesia

### Source new URL

https://komikcast.lol

### Other details

Komikcast has change the url from:
https://komikcast.ch
To:
https://komikcast.lol

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by CharlieRivalno** [comment]
It's a mistake, cus i just make this issue. So it's not a duplicate

**Comment by bobbyrinaldy** [comment]
> It's a mistake, cus i just make this issue. So it's not a duplicate

the issue already reported, thats why its called duplicate. and i have also create a PR to close the issue
