### ISSUE TITLE
FR-Scan (FR) — Aucune page trouvée (No page found)

### ISSUE THREAD

**Issue by Newall-7** [tachiyomiorg/tachiyomi-extensions#19155]
### Source information

FR-Scan 1.4.35

### Source language

French 

### Steps to reproduce

1. Try to open or download a chapter of a manga/webtoon from the source.
2. The error "Aucune page trouvée" ("No page found") occur
3. No problem when browsing via WebView 

### Expected behavior

The chapter should open, or the download should begin.
There should be no difference in accessibility between WebView and in-app.

### Actual behavior

The chapter load in WebView, but the error "No page found" occur when trying to read/download.

### Tachiyomi version

Stable 0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Error 500 is not there anymore (Not on Tachiyomi side, error 5xx are errors that website owners should fix so if you see that kind of errors, nothing can be done except to wait) ; once I will have some free time I will start working on this No pages found issue.

**Comment by KirinRaikage** [comment]
From which manga for example ?

**Comment by Newall-7** [comment]
I'm on Tachiyomi Stable 0.14.7 / FR-Scan 1.4.37

So far I have tried to read/download:
- Infinite Mage
- Leveling with the Gods
- Kill the Hero
- Dr. Stone
- Dr. Stone Reboot: Byakuya **(Pages found here, has download)**
- My Daughter is the Final Boss
- Return of the 8th Class Magician
- SSS-Class Suicide Hunter
- F-Class Destiny Hunter
- Player From Today Onward
- Tales of Demons and Gods
- The Max Level Hero has Returned **(Pages found here, has download)**
- Talent-Swallowing Magician
- Return of the Frozen Player
- Taming-Master
- White Duke Pendragon
- The Great Mage Returns After 4000 Years
- Worn and Torn Newbie

Do not hesitate if you need any further information!

**Comment by KirinRaikage** [comment]
Can't reproduce unfortunately.
It works for me (Tried some manhwas on your list, manga) : maybe reinstall the extension itself ?

**Comment by pixelroll** [comment]
delete database solve the probleme for me

**Comment by Newall-7** [comment]
Even reinstalling the extension did nothing for me, and I do not know what to do next :/

**Comment by Newall-7** [comment]
Yes, I did

**Comment by pixelroll** [comment]
the bug is indeed not fixed.  It worked for a while after deleting the database but quickly became unusable again.

**Comment by KirinRaikage** [comment]
Still works for me, if it becomes broken for me I will reinvestigate
