### ISSUE TITLE
[Deletion Request] Delete Mangas no Sekai

### ISSUE THREAD

**Issue by Yura-ia** [tachiyomiorg/tachiyomi-extensions#19164]
### Source link

https://mangasnosekai.com/

### Other details

I come from the Scan creator of this website, and I would like you to remove my website from here. It was added without my permission, so I would like you to delete my website from here, thank you.

### Requirements

- [X] I've added a `TXT` DNS record for my domain with the value `tachiyomi-verification`
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by BrutuZ** [comment]
Why not stick with #18898 ?

**Comment by Seishirou101** [comment]
don't open duplicates, you need to do what vetleledaal said

**Comment by Yura-ia** [comment]
Yes, the problem is that they changed the name of "muslos no sekai" to "mangas no sekai" and updated the extension.
