### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dragonsballsuper** [tachiyomiorg/tachiyomi-extensions#19177]
### Source name

All

### Source language

All

### Describe your suggested feature

Add Override BaseUrl to all sources

### Other details

This feature is available on the Swatmanga source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is only useful on sources that changes the URLs constantly. Not worth adding it to every single extension.
