### ISSUE TITLE
Titles not showing up and saying no pages; also popular selection haven't change for 2 weeks and some stories aren't showing up and saying no pages 

### ISSUE THREAD

**Issue by Aureelion** [tachiyomiorg/tachiyomi-extensions#19189]
### Source information

"Myreadingmanga 1.4.47"

### Source language

English 

### Steps to reproduce

1. Open myreadingmanga
2. Popular selection doesn't change, and latest selection is missing some covers and pages
3. Clicked on one of the stories in latest; pages doesn't show / pages are missing

### Expected behavior

"This should happen, all of stories cover should come up, and stories should have pages in it"
![Screenshot_20231204-204923](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152873828/8284f5ae-8bc1-4930-b06c-9f21945035c6)
![Screenshot_20231204-204927](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152873828/1b085555-8466-49d5-9388-4e5f7c5d2cfe)

### Actual behavior

"This happened instead, no pictures and no pages"
![Screenshot_20231204-204939](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152873828/10016552-5224-4a1b-8a02-cc0d4b85332a)
![Screenshot_20231204-204935](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152873828/2697d547-141b-4f63-bf39-cf94efe32cbb)

### Tachiyomi version

"0.14.7"

### Android version

"Android 12"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nattadasu** [comment]
Dupe of #19165, resolved in #19202

However I'll try check "popular" (aka random manga) later. For now, the tab is falling back to oldest to newest manga from my observation.

**Comment by nattadasu** [comment]
Update about "popular"/random tab: it seems the problem happened on MRM end, not due to Tachiyomi. Unfixable until they fix the bug on the site themselves.

URL to test: https://myreadingmanga.info/search/?wpsolr_sort=sort_by_random

**Comment by Aureelion** [comment]
> Update about "popular"/random tab: it seems the problem happened on MRM end, not due to Tachiyomi. Unfixable until they fix the bug on the site themselves.
> 
> URL to test: https://myreadingmanga.info/search/?wpsolr_sort=sort_by_random

Regarding with this one on the website the popular/new selection works just fine it's just on the app that these problems are showing
