### ISSUE TITLE
Mangakakalot only loading 2 pages of chapter rest of pages are "the image couldnt be loaded retry"

### ISSUE THREAD

**Issue by spritefan** [tachiyomiorg/tachiyomi-extensions#19207]
### Source information

Mangakakalot 1.4.8

### Source language

English

### Steps to reproduce

1. go to latest in mangakakalot 
2. open any manga
3. open chapter
4. get "the image couldnt be loaded retry"

### Expected behavior

load the whole chapter when opening a chapter

### Actual behavior

when opening a chapter I get "the image couldnt be loaded retry". When I hit the retry button it does nothing. it works for other extension like mangahere and mangadex, just not mangakakalot

### Tachiyomi version

0/14/7

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17695#issuecomment-1697411190
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17695#issuecomment-1697449346
