### ISSUE TITLE
Shinigami Issue

### ISSUE THREAD

**Issue by Fauzy-Rahadian** [tachiyomiorg/tachiyomi-extensions#19217]
### Source information

Shinigami 1.4.38

### Source language

Indonesia

### Steps to reproduce

![Screenshot_20231207_111136](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/77951681/1d892b9a-9291-4bb5-899a-38ba97ce8b24)

### Expected behavior

can't open the shinigami ditachiyomi extension, and can only open it in webview pls fix this

### Actual behavior

![Screenshot_20231207_111157](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/77951681/44eca4a2-7444-458c-91fa-3e995aae59f5)

### Tachiyomi version

0.14.7

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please refer to the [**"Solving Cloudflare issues"**](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare) section and the three consecutive ones. Some sources intentionally have a higher Cloudflare protection to block apps like Tachiyomi. Try [**changing** the **User Agent** string](https://tachiyomi.org/docs/guides/troubleshooting/#changing-your-user-agent), use [**DOH / DNS Over HTTPS**](https://tachiyomi.org/docs/faq/settings#what-is-dns-over-https), or change your **DNS** in your phone settings, if you have done it but still no effect try to use **VPN**, [**delete** the **Cookies**  and the **WebView Data**](https://tachiyomi.org/docs/guides/troubleshooting/#clearing-cookies-and-webview-data), but this is a last measure, if it doesn't work, [**migrate** to **other sources**](https://tachiyomi.org/docs/guides/source-migration) or wait until they lower their protection.
