### ISSUE TITLE
Searching Mangá does not work on 'Ler Mangá'

### ISSUE THREAD

**Issue by TonicMaster** [tachiyomiorg/tachiyomi-extensions#19219]
### Source information

Ler Mangá 1.4.2

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Select the Ler Mangá source
2. Search any mangá

### Expected behavior

The searched mangá should appear

### Actual behavior

The searched mangá does not appear, it only appears if you search it on webview

### Tachiyomi version

0.14.7

### Android version

Android 13

### Other details

In webview, everything is working as it should. The mangá searched in webview appears normally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They don't have a search anymore, they're redirecting the users to a useless Google search. Nothing we can do if they don't have a proper search.
