### ISSUE TITLE
MyReadingManga unable to download

### ISSUE THREAD

**Issue by CactusTheGuy** [tachiyomiorg/tachiyomi-extensions#19221]
### Source information

MyReadingManga 1.4.48

### Source language

English

### Steps to reproduce

1. Enter a comic in MyReadingManga
2. Press download function
3. Wait a few seconds
4. Notification error show "Expected URL scheme 'http' or 'https' but no scheme was found for"

### Expected behavior

Able to download error free

### Actual behavior

Notification error show "Expected URL scheme 'http' or 'https' but no scheme was found for" after waiting a few seconds to download

### Tachiyomi version

0.14.7

### Android version

MIUI 14.0.8 Android 13

### Other details

![Screenshot_2023-12-07-21-14-54-844_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75614340/de6ba913-be4a-4a81-9c40-85eae5fe7dd4)
![Screenshot_2023-12-07-21-14-25-650_com android chrome](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75614340/c59513e0-5c71-4506-be05-8e139fd8281b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Billarin** [comment]
This is not because of the extension update, its been happening for a while on every new manga and doujin update in MRM. But reading it through google and webview is possible though. However, opening the manga or doujin through tachiyomi will give error and showing there is only 1 page and downloading will show the unexpected url scheme error.

**Comment by CactusTheGuy** [comment]
> opening the manga or doujin through tachiyomi will give error and showing there is only 1 page and downloading will show the unexpected url scheme error

The error of showing 1 page when opening throught tachiyomi is resolved in update 1.4.48 of MRM (which is updated 2 day ago at the time of sending this comment)

>downloading will show the unexpected url scheme error

This is not fixed with update 1.4.48 of MRM
