### ISSUE TITLE
Western comic trackers

### ISSUE THREAD

**Issue by Ripper2005** [tachiyomiorg/tachiyomi-extensions#19236]
### Source name

GrandComicDatabase , Leagueofcomicgeeks

### Source link

https://www.comics.org/  ,  https://leagueofcomicgeeks.com/

### Source language

English

### Other details

 Is it possible to add tracking APIs of some English comic trackers like Grand comic database(nonprofit) and Leagueofcomicgeeks ? becoz I use tachiyomi to read not just manga but other comics as well. This addition will be deeply appreciated. Thanks

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Neither of those have API access.
The first one is still very rudymentary but seems to have some kind of REST API *planned*, however [it's supposed to be read-only for the contents of the public database](https://github.com/GrandComicsDatabase/gcd-django/wiki/#rest-api-with-drf), no user profile.
The second one [stated that an API is not on their roadmap](https://leagueofcomicgeeks.uservoice.com/forums/213333-feature-requests/suggestions/6893699-api-access)

**Comment by Ripper2005** [comment]
> Neither of those have API access. The first one is still very rudymentary but seems to have some kind of REST API _planned_, however [it's supposed to be read-only for the contents of the public database](https://github.com/GrandComicsDatabase/gcd-django/wiki/#rest-api-with-drf), no user profile. The second one [stated that an API is not on their roadmap](https://leagueofcomicgeeks.uservoice.com/forums/213333-feature-requests/suggestions/6893699-api-access)

What about (https://comicvine.gamespot.com/) Comicvine ?, if its not gonna happen then fine. Thanks

**Comment by Ripper2005** [comment]
What about ComicVine ?(https://comicvine.gamespot.com/). If it's not gonna happen then fine. Thanks

**Comment by vetleledaal** [comment]
Wrong repo, this is app related. Also:
League of Comic Geeks tachiyomiorg/tachiyomi#1776
Comic Vine tachiyomiorg/tachiyomi#1125 , although they have an API now https://comicvine.gamespot.com/api/documentation
