### ISSUE TITLE
Yugen Mangas (Spanish): Images does not load

### ISSUE THREAD

**Issue by BastiVader** [tachiyomiorg/tachiyomi-extensions#19240]
### Source information

Yugenmangas 1.4.29

### Source language

Español

### Steps to reproduce

1. Entro a la fuente
2. Habro un manhwa 
3. Elijo un capítulo 
4. No carga la imagen (no está caída la pagina)

### Expected behavior

1. Entro a la fuente 
2. Habro un manhwa 
3. Elijo un capítulo 
4. Carga la imagen y leo 

### Actual behavior

No carga la imagen 

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Closing in favor of #19338
