### ISSUE TITLE
FR : manga-scan.me became mangascan.cc

### ISSUE THREAD

**Issue by AlCiavi** [tachiyomiorg/tachiyomi-extensions#19282]
### Source information

Manga-Scan 1.4.7

### Source language

French

### Source new URL

mangascan.cc

### Other details

A change of domain for what is currently the best French extension. Currently, images cannot be loaded into the application. Thank you very much.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Thanks for tracking, I didn't find out what was the new URL. Will work on it ASAP.
