### ISSUE TITLE
chapter cannot be opened

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#19287]
### Source information

DoujinDesu 1.4.5

### Source language

Indonesia

### Steps to reproduce

![Screenshot_2023-12-12-06-01-09-406_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/40079068/c5b5f477-f5f2-4183-aea3-c5102765fb97)

### Expected behavior

Mohon di perbaiki

### Actual behavior

Tidak bisa buka chapter 

### Tachiyomi version

TachiyomiSY 1.9.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Duplicate and the information in #19288 more detailed
