### ISSUE TITLE
Doujindesu: No pages found

### ISSUE THREAD

**Issue by Naruu76** [tachiyomiorg/tachiyomi-extensions#19288]
### Source information

Doujindesu 1.4.5

### Source language

Indonesian

### Steps to reproduce

1. Select one of the comics you want
2. Open the comic 
3. Select the desired chapter
4. When you open the chapter there is a statement that "No pages found"

### Expected behavior

Please fix the doujindesu extension because The chapter can't be opened

### Actual behavior

No pages found
![IMG_20231212_044304](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/116903678/08383224-e968-4417-85b3-b9ec600b177c)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ChikaTempest** [comment]
page not found 
![Uploading Screenshot_2023-12-13-21-49-05-653_eu.kanade.tachiyomi.sy-edit.jpg…]()

**Comment by Claymore9** [comment]
Halaman tidak ditemukan

**Comment by niveanyctra** [comment]
I don't think this has really been fixed, I still can't open the pages with error "No Pages Found"
