### ISSUE TITLE
Ex-Hentai Entries are not hidden

### ISSUE THREAD

**Issue by srcsvl** [tachiyomiorg/tachiyomi-extensions#19294]
### Source information

TachiyomiSY Added in

### Source language

English 

### Steps to reproduce

The manga entries I added in Ex-Hentai are not hidden or obfuscated in the browse

### Expected behavior

As with other extensions, I would like to dim or hide 

### Actual behavior

The manga I added to the library are also standing as if Ex-Hentai has not been added

### Tachiyomi version

Tachiyomisy prewiew R532

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Report to [TachiyomiSY ](https://github.com/jobobby04/TachiyomiSY/issues) instead. This repo is for the main app.
