### ISSUE TITLE
Sushi-scan : search function doesn't work 

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#19298]
### Source information

Sushi-scan 1.4.36

### Source language

French

### Steps to reproduce

1. Open the extension
2. Search for a manga
3. Extension shows you "No results found" regardless of it is there or not

### Expected behavior

The extension should show the manga that match the search

### Actual behavior

The extension shows "No results found" regardless of whether or not the actual site shows results if you search there
![Screenshot_20231213-103857](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/0beec73f-8861-41d6-9457-d865ec5cd402)
![Screenshot_20231213-103926](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51856879/1c9eac1a-d721-4d13-867a-1b0b9ba2cf29)

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Quite surprised that you're not "blocked" yet, I would have worked on it, but they have a strategy which blocks most French users from using Tachiyomi: 
![Screenshot_20231213_170115_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/11159175/e6743431-ed64-4b36-9d2a-90da98064c49)

It's been a few weeks now unfortunately...

**Comment by aboudiom59** [comment]
I use the base version of Webview that comes with my phone and did not update it

**Comment by KirinRaikage** [comment]
Report it in an issue then @kagehisa.

**Comment by KirinRaikage** [comment]
This is not what the update was supposed to fix.. It was supposed to fix search for those wirh the extension still working BEFORE the update
