### ISSUE TITLE
MangaLivre.info

### ISSUE THREAD

**Issue by LandonFZ** [tachiyomiorg/tachiyomi-extensions#19296]
### Source name

MangaLivre (Falso)

### Source link

https://mangalivre.info/

### Source language

Portuguese Brazilian

### Other details

18+/NSFW = YES.

I really believe it's Blogspot. And they just use name Mangá Livre unrelated to the original ML, but it's just my guess so I don't know and I didn't investigate. I'm very sorry for the inconvenience.

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Besides being a copycat, it's just a simple blog site.
