### ISSUE TITLE
Duplicate of #19288

### ISSUE THREAD

**Issue by NameLess1909** [tachiyomiorg/tachiyomi-extensions#19308]
Duplicate of #19288

_Originally posted by @arkon in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/19307#issuecomment-1855063511_
            How its duplicate? Im using tachiyomi az and still not fixed yet in tachiyomi az its still page list is empty doujindesu 1.4.5

**Comment by arkon** [comment]
You opened a duplicate issue about the same problem of a still open issue. Please do not create spam.
