### ISSUE TITLE
Ler manga

### ISSUE THREAD

**Issue by Mynameluis** [tachiyomiorg/tachiyomi-extensions#19305]
### Source name

Ler manga

### Source language

PT BR 

### Describe your suggested feature

Gostaria que fosse adicionado a função de procurar o manga pelo nome a fonte diz que o site não tem um buscador próprio mais no site se você coloca o nome da obra que você quer você acha a obg 

### Other details

![Screenshot_20231213-214532](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145807935/ee8eb6ec-7040-4329-97d0-93682e48f77e)

Se não for possível adicionar essa função 

Colocar pra poder migrar a obra pra essa extensão 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.###

**Comment by Mynameluis** [comment]
![Uploading Screenshot_20231213-215855.png…]()

**Comment by Mynameluis** [comment]
![Screenshot_20231213-215855](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145807935/c31351f3-ce35-4a50-baa7-73b09d8c588d)

**Comment by BrutuZ** [comment]
O site não tem busca **PRÓPRIA**, usam o Google que é inútil pro programa.
Busque no seu navegador e mande abrir no Tachiyomi

**Comment by alessandrojean** [comment]
Closing as Google do a lot of measures to prevent apps like Tachi to scrap their content as said by BrutuZ.
