### ISSUE TITLE
Mangakaklot search funktion is not working

### ISSUE THREAD

**Issue by kagehisa** [tachiyomiorg/tachiyomi-extensions#19311]
### Source information

Mangakakalot 1.4.8

### Source language

English

### Steps to reproduce

1. Open mangakakalot extension
2. Enter a manga title to search e.g. "Fuun Kara No Saikyou Otoko"
3. Extension shows "no search results found" despite it being available on the site

### Expected behavior

It should show the manga that matches the search.

### Actual behavior

The extension shows "No results found", while the actual site shows the wanted results if you search there.

### Tachiyomi version

0.14.7

### Android version

7.0 (No further updates for my tablet available)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Can't reproduce, search is working for me on the latest version of Mangakakalot. Can you try with other titles?
I couldn't find "Fuun Kara No Saikyou Otoko" on the website itself, by the way.
But could find search results for other manga.

**Comment by kagehisa** [comment]
Ok, I found the issue. My Bad! The title is only available in japanese not english. Therefore the search didn't work, since the extension was set to english only. Sorry!
