### ISSUE TITLE
Analysis of LerManga: Manga research

### ISSUE THREAD

**Issue by OverlordFire** [tachiyomiorg/tachiyomi-extensions#19337]
## Source information

LerMangá(1.4.3)

### Source language

Portugues(Brasil)

### Steps to reproduce

1-Open extension 
2-search mangas

### Expected behavior

appear the mangas

### Actual behavior

![Screenshots_2023-12-17-01-58-16](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/154038232/1a248b40-ef13-4f33-a1a2-aca8dce75ba7)

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

Verify that the extension's database is up-to-date with the latest information on available manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
The site literally doesn't have its own search, they outsource to Google, which can't be parsed.

You can search on your browser and open the manga on Tachiyomi
