### ISSUE TITLE
Extension already installed but not showing in the source list

### ISSUE THREAD

**Issue by Keykan345** [tachiyomiorg/tachiyomi-extensions#19346]
### Source information

Hentaivn

### Source language

Vietnamese

### Steps to reproduce

1. Already Installed in Tachiyomi J2K 1.7.1. Everything is fine with a little bit of lag.
2. Update to 1.7.3. The extension disappeared in the Source List.
3. Go to the Extensions list, it say the Source not installed.
4. Install again and notthing happen. What disappeared still disappear.

### Expected behavior

Extension show in the source list.
Can read manga from the extension that already add to library.

### Actual behavior

Can not found extension in the source list.
Manga that saved in library now unable to read.

### Tachiyomi version

1.7.3

### Android version

Andoird 14 - MIUI 14

### Other details

The extension work fine in tachiyomi older version
Test on another Xiaomi phone have same problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by guanda80** [comment]
Same here. But on Android 10.

**Comment by satohtakeru404** [comment]
It only happen with j2k. SY and base version still working fine. The extension has already installed, j2k just can't read it.
