### ISSUE TITLE
Mangás Chan com problema no Cloudflare

### ISSUE THREAD

**Issue by Gustavo5599** [tachiyomiorg/tachiyomi-extensions#19347]
### Source information

Mangás Chan 1.4.28

### Source language

Português do Brasil

### Steps to reproduce

Baixar a extensão com a última atualização e depois utilizar, porém tem Cloudflare

### Expected behavior

abrir na Webview para confirmar que não sou um robô e ter acesso aos mangás da extensão

### Actual behavior

Quando abro na Webview para confirmar que não sou robô acontece alguma falha e não funciona independente de quantas vezes eu tente

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

Nenhum detalhe e perdão por qualquer erro, é a primeira vez que uso o github e relato um problema aqui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gustavo5599** [comment]
Fechei o problema por engano

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.

**Comment by Gustavo5599** [comment]
Tentei usar outros "agentes de usuário" e o problema foi resolvido, obrigado pela atenção
