### ISSUE TITLE
Not able to read Manga Demon

### ISSUE THREAD

**Issue by Wesdes** [tachiyomiorg/tachiyomi-extensions#19359]
### Source information

Manga Demon

### Source language

English

### Steps to reproduce

1.Open Manga Demon latest
2. Pick any Manga or Manhwa
3. Chapter not showing 

### Expected behavior

Chapter should be listed 

### Actual behavior

Not displaying the chapter list

### Tachiyomi version

0.14.7

### Android version

Android 12

### Other details

Couldn't obtain an update for the latest chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DrProphet0** [comment]
Version 1.4.8 solved the issue, thanks.
