### ISSUE TITLE
Nexo Scans

### ISSUE THREAD

**Issue by Gustavo5599** [tachiyomiorg/tachiyomi-extensions#19351]
### Source name

Nexo Scans

### Source link

https://nexoscans.com/

### Source language

Português do Brasil

### Other details

Essa é a novo nome e dominio da antiga "Neox Scans", um dos motivos pelo qual peço essa fonte de volta é porque existe outro leitor de mangás chamado "kotatsu" que adicionou essa fonte meses atrás e sempre funcionou (talvez não esteja funcionando agora porque recentemente eles trocaram de domínio como mencionado antes), o outro motivo é porque eles tem os manhwas mais famosos traduzidos e nas extensões do brasil tem APENAS 2 FONTES que traz os manhwas deles atualizados ("Mangás Chan" e "Ler Mangás", e não é atoa que dizem que o tachiyomi está morto no brasil) e ainda sim muitos deles chegam atrasado, o que peço è que tentem trazer ela de volta e caso seja muito difícil de manter a fonte eu entendo se for abandonado, peço perdão por qualquer erro e obrigado pela atenção.

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If won't be added back as they clearly have all intentions to change a lot of stuff on purpose to block apps like Tachiyomi. Kotatsu extension aren't handled by us and likely has a way lower audience than Tachiyomi has, so they probably don't care about it. There's a lot of extensions that reupload their content and you can use them instead. We obviously don't control uploads of the sources so if they're slow, complain with them instead.
