### ISSUE TITLE
Sekte doujin tld change

### ISSUE THREAD

**Issue by Princess137** [tachiyomiorg/tachiyomi-extensions#19368]
### Source information

sekte doujin v1.4.31

### Source language

Indonesia

### Source new URL

https://sektedoujin.cc/

### Other details

sektedoujin.lol  -->  sektedoujin.cc

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by anjing1111** [comment]
Is there anyone who can change this domain extension?

**Comment by vetleledaal** [comment]
> Is there anyone who can change this domain extension?

There is an open PR #19350, you need to wait for it to be merged. There is no time estimate.

**Comment by TheKingTermux** [comment]
PR aleardy merged, this issue can be closed as completed now
