### ISSUE TITLE
The 'Ler Mangá"  search  not working, but the Mangás already added are still working 

### ISSUE THREAD

**Issue by HolyAether** [tachiyomiorg/tachiyomi-extensions#19365]
### Source information

Ler Manga 

### Source language

Português Brasil

### Steps to reproduce

When I try to search for a work to add, the extension says it doesn't have its own search, but when you go to the extension's website, it's usually there 

### Expected behavior

When I research works they should apa

### Actual behavior

But in reality this happens 
![Screenshot_20231219-143959](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/154362457/fd17609c-c44c-4940-be72-a69f0f36473d)

### Tachiyomi version

Stable 0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As the message says, it's self explanatory. The site doesn't have a proper search, they're using Google which prevents us from parsing their content. Nothing we can do, complain with them to they readd their own search.
