### ISSUE TITLE
mangapark v3 suddenly just disappeared, i had both mangapark and mp v3 now all my mangas in mpv3 have no affiliation 

### ISSUE THREAD

**Issue by cavejohnson7274** [tachiyomiorg/tachiyomi-extensions#19381]
### Source information

mangapark v3

### Source language

English 

### Steps to reproduce

1, search mangapark v3 in extension
2, see nothing

i also can't find the extension in my list of apps anymore

### Expected behavior

mangapark v3 should exist?

### Actual behavior

mp v3 doesn't exist

### Tachiyomi version

App version: 0.14.7 

### Android version

android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It was updated to MangaPark v5. You need to migrate all your entries to v5. This is expected.

**Comment by cavejohnson7274** [comment]
@alessandrojean I can't find v5 in github or tachi???

**Comment by alessandrojean** [comment]
It's named just MangaPark.

**Comment by PunMist3r** [comment]
I can't find a new mangapark in the extensions tab either. Is there any place I should look for it? Do I have to uninstall the current mangapark extension for it?
