### ISSUE TITLE
Bacakomik Extension close and change to new website 

### ISSUE THREAD

**Issue by WhoMeAnd** [tachiyomiorg/tachiyomi-extensions#19384]
### Source information

BacaKomik 1.4.7

### Source language

Indonesia 

### Source new URL

https://bacakomik.net/

### Other details

They couldn't fix the problem on the old website so they moved to a backup server

### Acknowledgements

- [x] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by WhoMeAnd** [comment]
Sorry I clicked wrong earlier

**Comment by TheKingTermux** [comment]
Uhh they just change the Url, the website didn't dead, closed or migration either

**Comment by WhoMeAnd** [comment]
> Uhh they just change the Url, the website didn't dead, closed or migration eithe

Can you update the link?

**Comment by TheKingTermux** [comment]
> Can you update the link? 

Unfortunately I can't right now, It will be updated if someone wants to work on it. There's no ETA
