### ISSUE TITLE
Picacomic extension make app crash

### ISSUE THREAD

**Issue by YangHgRi** [tachiyomiorg/tachiyomi-extensions#19393]
![](https://i.imgur.com/SYv0W0n.jpg)

extension version 1.4.2 & simp chinese

app crashed when i use about this extension

App version: 0.14.7 (standard, 178b00280, 113, 2023-12-20T11:13Z)
Android version: 13 (SDK 33; build TP1A.220624.014)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: xaga (xaga)
Device model: 22041216C
WebView: Android System WebView 119.0.6045.194

--------- beginning of main
12-22 14:10:16.050 13212 13423 E SQLiteLog: (284) automatic index on C(manga_id)
12-22 14:10:16.050 13212 13423 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-22 14:10:22.959 13212 13252 E libEGL  : pre_cache appList: ,,
12-22 14:12:52.727 13212 13212 E anade.tachiyomi: Invalid ID 0x00000000.
12-22 14:13:10.756 13212 13212 E anade.tachiyomi: Invalid ID 0x00000000.
12-22 14:13:22.727 13212 13212 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (16238) crash detected (code -1).
12-22 14:13:54.951 17634 17634 E i:error_handler: Not starting debugger since process cannot load the jdwp agent.
12-22 14:13:54.997 17652 17652 E anade.tachiyomi: Not starting debugger since process cannot load the jdwp agent.
12-22 14:13:55.049 17634 17678 E SQLiteLog: (283) recovered 197 frames from WAL file /data/data/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-22 14:13:55.054 17634 17688 E QT      : [QT]file does not exist
12-22 14:13:55.058 17634 17688 E QT      : [QT]file does not exist
12-22 14:13:55.093 17634 17634 E i:error_handler: Invalid ID 0x00000000.
12-22 14:13:55.240 17652 17714 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-22 14:13:55.310 17652 17736 E chromium: [1222/141355.309575:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
12-22 14:13:55.564 17634 17634 E FBI     : Can't load library: dlopen failed: library "libmagtsync.so" not found
12-22 14:13:55.586 17634 17681 E libMiGL : libmigl:This GPU version is note support Variable Shading Rate
12-22 14:13:55.588 17634 17681 E libEGL  : pre_cache appList: ,,

**Comment by alessandrojean** [comment]
Can you please recreate the issue by following the [Issue report](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new?assignees=&labels=Bug&projects=&template=01_report_issue.yml) form in the GitHub website instead, please?

Using the issues helps into organizing the information better.
