### ISSUE TITLE
Multiple pages

### ISSUE THREAD

**Issue by EvilCrow1210** [tachiyomiorg/tachiyomi-extensions#19406]
### Source information

BacaKomik 1.4.8

### Source language

Indonesia

### Steps to reproduce

1. Open BacaKomik (Indonesia)
2. Choose any comic

### Expected behavior

The comic should display the same 1 page

### Actual behavior

But now, every page will be repeated or duplicated

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by najahiiii** [comment]
![gambar](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/31695903/9e186f28-2935-4853-8478-e47ba66325b0)
this is the problem I think, because it takes every div tag it has img url on it
```
...
        document.select("div:has(>img[alt*=\"Chapter\"]) img").forEach { element ->
            val url = element.attr("onError").substringAfter("src='").substringBefore("';")
            i++
            if (url.isNotEmpty()) {
                pages.add(Page(i, "", url))
            }
        }
...
```
so, maybe selecting noscript tag or exclude it will fix the duplicated pages
