### ISSUE TITLE
Unknown eror MangaTale

### ISSUE THREAD

**Issue by ChikaTempest** [tachiyomiorg/tachiyomi-extensions#19401]
### Source information

MangaTale 1.4.28

### Source language

Indonesia

### Steps to reproduce

Can't load the manga. Can't download the manga.

### Expected behavior

Can view download the manga

### Actual behavior

![Screenshot_20231223_165412](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/105035665/9ff78e12-ff4b-4f39-b819-ed09e5af90ba)

### Tachiyomi version

0.14.7

### Android version

Android 12

### Other details

.
![Screenshot_20231223_165412](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/105035665/414cfad1-5a3f-4b48-b7aa-54df8839fa80)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
It's fine for me
![Screenshot_2023-12-23-21-00-49-89_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/d257dc39-a28f-4c93-929e-0c5e4519896a)

![Screenshot_2023-12-23-21-01-43-03_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/22676326-8c8b-4af7-9824-7b34e64aec36)

**Comment by Riztard** [comment]
works for me as well
