### ISSUE TITLE
Bacakomik change domain

### ISSUE THREAD

**Issue by Jeankirs** [tachiyomiorg/tachiyomi-extensions#19402]
### Source information

BacaKomik 1.4.7

### Source language

Indonesia

### Source new URL

https://bacakomik.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by najahiiii** [comment]
Patch already merged #19397

just wait for next update.
