### ISSUE TITLE
Accessing and Downloading old extensions

### ISSUE THREAD

**Issue by willhtang** [tachiyomiorg/tachiyomi-extensions#19414]
### Describe why this should be added

Is there a way to get ahold of older versions of extensions and/or extensions that are no longer being supported? Currently the visible APK commit history stops at July.

This will help people who are migrating to new devices and also allow people to default back to a previous working version.

For example, right now I am trying to migrate to a new device and many extensions of ongoing sources are marked as obsolete on the old device and cannot be found on the extensions list. However, that extension is still working fine on the old device, i.e. able to browse and download from the source site.

### Other details

I can't really mention any specific examples because the issue will get flagged by the bot. But I will drop some images to showcase this.
![Screenshot_20231224_234756](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/62323516/59e69811-1f12-4573-8fbc-83e1eebae1c1)
![Screenshot_20231224_234807](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/62323516/3c1e8bd7-f81c-4727-beb5-a41dc6fed580)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We don't offer support to obsolete extensions as the name suggests... they're obsolete. We recommend uninstalling and migrating to other extensions instead of insisting into using it as it always will cause eventual issues with the app such as crashes. Besides, newer app versions won't support them as well.
