### ISSUE TITLE
"bad base-64"is displayed in PicaComic

### ISSUE THREAD

**Issue by mavnp** [tachiyomiorg/tachiyomi-extensions#19434]
### Source information

PicaComic 1.4.3

### Source language

zh

### Steps to reproduce

1.更新picacomic
2.打开picacomic即复现

### Expected behavior

没更新之前可以正常加载

### Actual behavior

![Uploading Screenshot_20231227_005919_eu.kanade.tachiyomi.sy.jpg…]()

### Tachiyomi version

0.14.7

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MSandDX** [comment]
I encountered the same issue. After uninstalling the entire Tachiyomi, the problem was briefly resolved, but later it displayed 'bad base-64' again. I've also tried other methods without success, hoping for a prompt version update.

**Comment by ImQQiaoO** [comment]
Here is a temporary solution from the user's perspective:
Do not update this extension to version 1.4.3.
If you have already updated this extension to version 1.4.3, please uninstall it, and go to [tachiyomi-zh.picacomic-v1.4.2.apk](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/b6056f916d2cd2ca266a2d1cb3cb7da1b10e4125/apk/tachiyomi-zh.picacomic-v1.4.2.apk) to download and install the previous version.

**Comment by MSandDX** [comment]
> Here is a temporary solution from the user's perspective: Do not update this extension to version 1.4.3. If you have already updated this extension to version 1.4.3, please uninstall it, and go to [tachiyomi-zh.picacomic-v1.4.2.apk](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/b6056f916d2cd2ca266a2d1cb3cb7da1b10e4125/apk/tachiyomi-zh.picacomic-v1.4.2.apk) to download and install the previous version.

Thank you. I've identified the issue – all errors started after updating to version 1.4.3. I've considered reverting to the old version, but sadly, I can't find the download link for the previous version. You truly saved me; thanks again.

**Comment by alessandrojean** [comment]
Please don't download arbitrary APK files and also note we don't offer support to outdated versions.
