### ISSUE TITLE
COLAMANG漫画

### ISSUE THREAD

**Issue by paopaode4512** [tachiyomiorg/tachiyomi-extensions#19433]
### Source name

COLAMANG

### Source link

https://www.colamanga.com/

### Source language

中文-中文

### Other details

No response

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by 46772222** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md#too-difficult-to-maintain

**Comment by hauskx** [comment]
![IMG_0347](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/154932158/87406a5f-4c75-4133-8953-0758cdc7da2f)
 When I open it  it not work this the web

**Comment by paopaode4512** [comment]
The server has been restored to normal
![mmexport1703671768642](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/153882394/9663d629-c631-4c63-b597-2bef679b5c50)

**Comment by paopaode4512** [comment]
> ![IMG_0347](https://private-user-images.githubusercontent.com/154932158/292925097-87406a5f-4c75-4133-8953-0758cdc7da2f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTQwNTEsIm5iZiI6MTcwMzgxMzc1MSwicGF0aCI6Ii8xNTQ5MzIxNTgvMjkyOTI1MDk3LTg3NDA2YTVmLTRjNzUtNDEzMy04OTUzLTA3NThjZGM3ZGEyZi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDEzNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA0OGQwMmE2ZmUwMDIxMTI5OTg3M2UzYjk4ZDk0OTY3MTcyZGI0ZDE0NDkxNGNhMDVjMTk4OThlZGRmZDdjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RKAYLAV7kyuvlm3ZB8uzVP51pO_1ZB_CPHvUH75Rk4A) When I open it it not work this the web

The server has been restored to normal
![mmexport1703671768642](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/153882394/def26cc5-6cd1-4223-8d92-a0171ef3ab73)

**Comment by hauskx** [comment]
ok that’s great thanks so much

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月29日 01:36 |
| 收件人 | tachiyomiorg/tachiyomi-extensions ***@***.***> |
| 抄送人 | hauskx ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [tachiyomiorg/tachiyomi-extensions] COLAMANG漫画 (Issue #19433) |

When I open it it not work this the web

The server has been restored to normal
mmexport1703671768642.png (view on web)
