### ISSUE TITLE
MangaInUa : "No chapters found" while trying to update chapters

### ISSUE THREAD

**Issue by detth** [tachiyomiorg/tachiyomi-extensions#19436]
### Source information

MangaInUa 1.4.4

### Source language

Ukrainian

### Steps to reproduce

1. Open any title from this source
2. Try to update chapters
3. Message "No chapters found"

### Expected behavior

Title chapters should be updated

### Actual behavior

No new chapters and message "No chapters found"

### Tachiyomi version

0.14.7

### Android version

Android 13

### Other details

1. WebView works
2. Can read visible chapters in app 
3. While browsing in source, titles order in latest tab keep updates correctly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Articuno227** [comment]
same
