### ISSUE TITLE
Zero Scan: Extension can be removed

### ISSUE THREAD

**Issue by danroxha** [tachiyomiorg/tachiyomi-extensions#19435]
### Source name

ZeroScan

### Source language

Brazilian Portuguese

### Source link

https://zeroscan.com.br

## Sources
- ZeroScan - https://zeroscan.com.br
- VórtceScan - https://vortcescan.com.br
- TaberuMangás - https://taberu.org
- LadyEstelarScan - https://ladyestelarscan.com.br
- GekkouHentai - https://hentai.gekkouscans.com.br
- BananaCítrica - https://bananacitrica.com
- AkumanoTenshi - https://akumanotenshi.com

## Checking sources
```bash
#/usr/bin/env sh

sources="
- ZeroScan - https://zeroscan.com.br\n
- VórtceScan - https://vortcescan.com.br\n
- TaberuMangás - https://taberu.org\n
- LadyEstelarScan - https://ladyestelarscan.com.br\n
- GekkouHentai - https://hentai.gekkouscans.com.br\n
- BananaCítrica - https://bananacitrica.com\n
- AkumanoTenshi - https://akumanotenshi.com"


sources_file="/tmp/sources$RANDOM.txt"
responses="/tmp/responses$RANDOM.txt"

echo -e $sources > $sources_file
echo -en "" > $responses

TIMEOUT=60
clear

for url in $(awk 'BEGIN{FS="-"} {print $3}' $sources_file) 
  do
    curl --max-time $TIMEOUT --connect-timeout $TIMEOUT -s -o /dev/null -w "%{http_code}" $url \
    | echo -ne $(awk '{if($1 == 200) print "\033[32m"$1 ; else if ($1 >= 300 && $1 <= 403) print "\033[33m"$1 ; else print "\033[31m"$1}' ) - $url "\033[0m\n" \
    >> $responses &
  done

n_jobs=$(($(wc -l < <(jobs)) + 0))
while [ $n_jobs -gt 1 ]
  do 
    n_jobs=$(($(wc -l < <(jobs)) + 0))
    echo -ne "\033[0;0f===========================\nWaiting for $n_jobs process(es)\n===========================\n"
    cat $responses | tail -n 10
    sleep 1
    clear
  done
  

echo "Code| Domain"
sort -k1.3 -r $responses

case $1 in
  "-s"  | "-S" |"--save")  sort -k1.3 -r $responses > ./log.txt  ;;
esac

rm -f $responses $sources_file
```

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Wmestree** [comment]
O site zero foi fechado temporariamente por causa do dmca, eles estão aguardando um pouco o fim da caça ao scan no Brasil para voltar a ativar o site.
![20231226_151032](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/149016762/e7c9e9e0-81d1-4c3a-9468-8bacf6fcf4b1)

**Comment by alessandrojean** [comment]
Not worth keeping a dead site extension available. If they start a new website it can be readded later anyway.
