### ISSUE TITLE
COLAMANG漫画

### ISSUE THREAD

**Issue by paopaode4512** [tachiyomiorg/tachiyomi-extensions#19450]
### Source name

COLAMANG

### Source link

https://www.colamanga.com/

### Source language

Chinese-中文

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by junyaotan020517** [comment]
CoCo漫画被除掉了，因为他们把网页地址加密方法和加密钥匙一直改变。改来改去到我们修完一次他们已经不一样的加密算法。这给我们带了太的障碍，就决定除掉。回来的可能性很小。现在需要移民到别的网站去

**Comment by alessandrojean** [comment]
Please actually read and follow what you have acknowledged.

> I have checked that the extension is not on the removed sources list.
