### ISSUE TITLE
Manga.in.ua not returning chapters

### ISSUE THREAD

**Issue by MMorokk** [tachiyomiorg/tachiyomi-extensions#19453]
### Source information

Manga.in.ua

### Source language

Ukrainian

### Steps to reproduce

1. Install extension 
2. Click on manga cover

### Expected behavior

Shows list of chapters

### Actual behavior

Shows no chapters

### Tachiyomi version

1.14.7

### Android version

Android 13

### Other details

![Screenshot_2023-12-28-15-23-55-763_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51864605/e8328d7a-3456-4a7a-8612-13655b452329)

All manga showing no chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Oof, forgot to mark this issue as closed in #19459 
we live in a society
