### ISSUE TITLE
Mangabuddy and mangahere are down

### ISSUE THREAD

**Issue by Baymax325** [tachiyomiorg/tachiyomi-extensions#19451]
### Describe why this should be added

There is a problem with these 2 sites, I can't update them or view the extension, when I looked for the problem it said null.

![Screenshot_2023-12-28-22-30-34-94_8d485484d290ec17555e7acc83d01a83](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/130737137/a2697616-0fd1-4fc0-a927-44427eb3faaf)

### Other details

What is !null

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source, otherwise it keeps difficult to keep track on what have been addressed and what not.

Also note we can't do anything about Cloudflare, read and follow the troubleshooting guide on the acknowledgements section about it.
