### ISSUE TITLE
Happymh image loading issue

### ISSUE THREAD

**Issue by RadStorm04** [tachiyomiorg/tachiyomi-extensions#19457]
### Source information

Happymh 1.4.5

### Source language

中文

### Steps to reproduce

Open up comic from said source, won't load

### Expected behavior

Loading images normally

### Actual behavior

Unable to load images from source properly in app

### Tachiyomi version

J2K 1.7.3

### Android version

Android 14

### Other details

No kapacha blocking and can read normally in the webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sao-coding** [comment]
me too
