### ISSUE TITLE
Extension search issue

### ISSUE THREAD

**Issue by Ricard0466** [tachiyomiorg/tachiyomi-extensions#19464]
### Source information

Ler Mangá

### Source language

Portuguese(Brazilian)

### Steps to reproduce

1. Go to browse
2. Go to source
3. Select Lee Mangá extension
4. Browse a manga

### Expected behavior

Show the manga

### Actual behavior

It says the following "O site não possui busca própria."

### Tachiyomi version

0.14.7

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As the error says, they don't have a search, they're using Google, which the extension can't parse its contents. Use a better source that do have a proper search or wait until they implement one. There's nothing we can do and the extension is working as intended on what the site offers.
