### ISSUE TITLE
❗java.io.IOException❗

### ISSUE THREAD

**Issue by kapelabra** [tachiyomiorg/tachiyomi-extensions#19463]
### Source information

Shinigami

### Source language

Indonesia

### Steps to reproduce

I opened the Shinigami extension and buffering occurred and then the same opened the WebView section and asked to fill in the captcha to penetrate cloudflare 

### Expected behavior

After completing the captcha the WebView should open and the extension can be used 

### Actual behavior

but what happens is that you return to the captcha filling page repeatedly and when you return to the previous page the notification "java.io.IOException" appears. 

### Tachiyomi version

Tachiyomi Stable 0.14.7

### Android version

Andriod 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.

**Comment by Seishirou101** [comment]
> I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
