### ISSUE TITLE
Extension happymh(嗨皮漫画) cannot load in app but work on webview

### ISSUE THREAD

**Issue by HYChin** [tachiyomiorg/tachiyomi-extensions#19466]
### Source information

Happymh 1.4.5

### Source language

Chinese

### Steps to reproduce

1. Alr change the User Agent String last time its work
2. These two days open a comic 
3. Figure out the comic cannot load on app 
4. Show out Error HTTP 403 and cannot bypass cloudflare 
5. Have try fews User Agent String still cannot 

### Expected behavior

In should be able read the manga on app, now is showing these 2 error 

### Actual behavior

Correctly bypass cloudflare, fix the extension or fix app issue 

### Tachiyomi version

0.14.7

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HYChin** [comment]
But I have try all the Solving Cloudflare issues still not working at all

**Comment by TheKingTermux** [comment]
> But I have try all the Solving Cloudflare issues still not working at all

If it doesn't work, [**migrate** to **other sources**](https://tachiyomi.org/docs/guides/source-migration) or wait until they lower their protection.
