### ISSUE TITLE
Shinigami redirect to /semua-series

### ISSUE THREAD

**Issue by RoSiCyBeR** [tachiyomiorg/tachiyomi-extensions#19474]
### Source information

Shinigami 1.4.40

### Source language

Indonesia 

### Steps to reproduce

Open the extension from the source

### Expected behavior

The source says error code (404 check the webview) The website said they directed me to /all-series

### Actual behavior

![Screenshot_20231229-181714](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/34416860/1aa6111f-b906-4992-8b6c-59286f172bd5)
![Screenshot_20231229-181723](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/34416860/15ee9c64-327a-49c9-9724-5cd72cc827e2)

### Tachiyomi version

0.14.7

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by WEPOXS** [comment]
![Screenshot_20231229_215446_Tachiyomi.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146017577/a5f02b56-178d-4e22-9528-0ffc7d6c41ee)

Info terkini

**Comment by WEPOXS** [comment]
Ah ya btw pas verification cloudfire selalu ngulang ulang

**Comment by MeLoseAgain** [comment]
Wah wah parah 🤣
