### ISSUE TITLE
Ler Mangá: Search through WordPress API

### ISSUE THREAD

**Issue by edgardmessias** [tachiyomiorg/tachiyomi-extensions#19478]
### Source name

LerManga

### Source language

Portugueses

### Describe your suggested feature

The site [Ler Mangá](https://lermanga.org/) is based on Wordpress platform, and after some research, they have the **wp-json plugin** enabled, and because of that, we can implement a basic search on their content.

This is the analysis that a could find:
* The URL for seach is: `https://lermanga.org/wp-json/wp/v2/mangas?search=<term>`
* Search with only usefull fields: `https://lermanga.org/wp-json/wp/v2/mangas?search=tonikaku&_fields=title,link,slug`
* The image URL is: `https://img.lermanga.org/<first letter uppercased>/<slug>/capa.jpg`
* We can base the search on [Tao Sect](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/pt/taosect/src/eu/kanade/tachiyomi/extension/pt/taosect/TaoSect.kt) extension, because it uses wp-json format.
* All available API options: `https://lermanga.org/wp-json`

### Other details

Examples:
Request: `https://lermanga.org/wp-json/wp/v2/mangas?search=one%20piece&_fields=title,link,slug`
Response:
```json
[
  {
    "slug": "one-piece-colorido",
    "link": "https://lermanga.org/mangas/one-piece-colorido/",
    "title": {
      "rendered": "One Piece (Colorido)"
    }
  },
  {
    "slug": "one-piece",
    "link": "https://lermanga.org/mangas/one-piece/",
    "title": {
      "rendered": "One Piece"
    }
  }
]
```

Image: `https://img.lermanga.org/O/one-piece/capa.jpg`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Good finding! Will update the extension.
