### ISSUE TITLE
Chapters not found in Mangadex extension, but found in WebView

### ISSUE THREAD

**Issue by Lira-tron** [tachiyomiorg/tachiyomi-extensions#19481]
### Source information

Latest

### Source language

English, Español, Español (Latinoamerica)

### Steps to reproduce

1. Install MangaDex extension
2. in Mangadex extension settings, just select Español, Español(Latinoamerica)
3. search for one piece and select the first one
4. Open it and chapters will not be found (this is the problem)
5. In the one piece select WebView
6. It will take you to mangadex web ui, and the chapters in English, spanish, etc will be there 

By the way I use the mangadex app in ios and I can read them

### Expected behavior

1. Install MangaDex extension
2. in Mangadex extension settings, just select Español, Español(Latinoamerica)
3. search for one piece and select the first one
4. Open it and and see the chapters in english and spanish as I can see them if I go to WebView

### Actual behavior

1. Install MangaDex extension
2. in Mangadex extension settings, just select Español, Español(Latinoamerica)
3. search for one piece and select the first one
4. Open it and chapters will not be found (this is the problem)

### Tachiyomi version

0.14.7

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Those chapters aren't actually hosted on MangaDex, if you try clicking them on the website.
