### ISSUE TITLE
Alteração de URL de Gekkou Scan.

### ISSUE THREAD

**Issue by Dansayu55** [tachiyomiorg/tachiyomi-extensions#19482]
### Source information

Gekkou Scan.  versão 1.4.32

### Source language

Português-Br

### Source new URL

https://gekkouscans.top

### Other details

Recentemente os administradores do site https//gekkou.com.br mudaram URL do site para "https://gekkouscans.top".

Após uma breve pesquisa vi que esse erro ainda não foi relatado de forma correta aos administradores da plataforma.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The extension already uses this URL you reported. If you're having issues with it, try uninstalling the extension and then installing again.
