### ISSUE TITLE
集云 cola

### ISSUE THREAD

**Issue by SofiarDav** [tachiyomiorg/tachiyomi-extensions#19506]
### Source name

colamanga

### Source link

https://www.colamanga.com/

### Source language

Chinese

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by yigedajiaque** [comment]
这个网站把5秒盾撤了，但是他三天就会更改一次布局，和加密方式。所以维护成本极高。

**Comment by alessandrojean** [comment]
Please do actually read and follow what you have acknowledged...

> I have checked that the extension is not on the removed sources list.

**Comment by SofiarDav** [comment]
I got it,thks
