### ISSUE TITLE
Change the quality of chapters

### ISSUE THREAD

**Issue by Dragonbooster12az** [tachiyomiorg/tachiyomi-extensions#19508]
### Describe why this should be added

Adding the option to change the quality of chapters will allow the user of the application to save more chapters and consume less phone memory

### Other details

Example of this option is application:
Image Converter:
JPG PNG PDF

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is not possible because not all websites have this feature. And websites that do provides this usually already have an extension setting for it.
