### ISSUE TITLE
Bad browser!! (Shinigami)

### ISSUE THREAD

**Issue by WEPOXS** [tachiyomiorg/tachiyomi-extensions#19517]
### Source information

1.4.41

### Source language

Indonesia

### Steps to reproduce

Go to open in webview
![Screenshot_20240101_061319_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/146017577/947d49a7-bb79-4833-b711-14f250f5844b)

### Expected behavior

Can complete Cloudfire verification 

### Actual behavior

There should be a verification display but it just says bad browser 

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by WEPOXS** [comment]
I updated this to the latest version but what happened was as stated above

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
