### ISSUE TITLE
Picacomic: Bad JSON decoding

### ISSUE THREAD

**Issue by drelover** [tachiyomiorg/tachiyomi-extensions#19525]
### Source information

picacomic 1.4.4

### Source language

chinese

### Steps to reproduce

1.update picacomic1.4.4
2.open it
3.the same report like #19443

### Expected behavior

load page

### Actual behavior

"unterminated string at character (numbers) of ..."

### Tachiyomi version

0.14.7

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fumiama** [comment]
Well, maybe you should reopen this. Let's see if someone else could find it and fix it.

**Comment by fumiama** [comment]
The title should be more appropriate like `Bad non-ASCII character decoding of JSON`

**Comment by fumiama** [comment]
Thanks!

**Comment by Nemophilist-1** [comment]
{
  "code": 400,
  "error": "1001",
  "message": "the format of accept header is invalid"
}
