### ISSUE TITLE
Need new Extension 

### ISSUE THREAD

**Issue by diefordabi** [tachiyomiorg/tachiyomi-extensions#19523]
### Source name

Nyx Manga

### Source link

https://nyxmanga.com/

### Source language

Turkish

### Other details

we need this extension, A new site and share webtoons nd mangas. Please helpp 

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by diefordabi** [comment]
This is a different extension and a different site with the same name. Please check and deal again. Nyx Manga

**Comment by alessandrojean** [comment]
It is not. The linked issue is about the exact same site. There's no need to have duplicate open issues.

**Comment by diefordabi** [comment]
> O değil. Bağlantılı sorun tamamen aynı siteyle ilgili. Yinelenen açık sorunlara gerek yok.

If it is the same site, the problem has not been resolved for 8 months.
