### ISSUE TITLE
[Source Request] Mangadropout

### ISSUE THREAD

**Issue by arzyware** [tachiyomiorg/tachiyomi-extensions#1952]
### Source Website
Website can be found at [Mangadropout.net](https://mangadropout.net)

### Other Details

**Comment by as280093** [comment]
Here are the icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4023845/ic_launcher.17.zip)

**Comment by deardian20** [comment]
Still waiting mangadropout

**Comment by beteng-Q** [comment]
So, where the extension

**Comment by deardian20** [comment]
Mangadropout.net [indonesian]

**Comment by happywillow0** [comment]
Is the website region restricted? 

None of the links work for me and bring me to a random web page that isn't manga.

**Comment by deardian20** [comment]
May be website not restricted because when i use vpn singapore still work to open this website.
Link example : https://mangadropout.net/collection
https://mangadropout.net/

I hope this coment have a advantage for make extension.

**Comment by deardian20** [comment]
One of manhwa in mangadropout
https://www.mangadropout.net/collection/200122/rental-girls#yieldContent

**Comment by happywillow0** [comment]
Sorry. I don't think I'm able to get it to work. 
I can load up to: 
<img src="https://user-images.githubusercontent.com/45346080/74581216-f8620800-4f7a-11ea-836a-c6832a4ad977.png" height=500px>

But trying to open a chapter, I get:


<img src="https://user-images.githubusercontent.com/45346080/74581226-06178d80-4f7b-11ea-896d-194072b33c9b.png" height=500px>

**Comment by AriaMoradi** [comment]
The site might be dead for real now.
can anyone confirm?

**Comment by HaruSasaki** [comment]
> The site might be dead for real now.
> can anyone confirm?

Yes. It's announced in Mangadex. This picture said, the mangadropout has been officially closed.

![IMG_20201216_154425.jpg](https://user-images.githubusercontent.com/73406832/102325351-9ff20180-3fb5-11eb-9286-2aa08b2da4de.jpg)

**Comment by AriaMoradi** [comment]
Then this issue can be closed?

**Comment by AriaMoradi** [comment]
Then this issue can be closed?
