### ISSUE TITLE
RF Dragon Scan

### ISSUE THREAD

**Issue by Gustavo5599** [tachiyomiorg/tachiyomi-extensions#19520]
### Source name

RF Dragon Scan

### Source link

https://rfdragonscan.com/

### Source language

Português do Brasil

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Not possible as they download a lot of ZIP files locally in the browser and uncompress it to show the chapter images. The extensions structure doesn't support dealing with ZIP files. Read their content on some other aggregator website which reuploads it.
