### ISSUE TITLE
HTTP error 500 when opening and loading a manga in Mangahere 1.4.19

### ISSUE THREAD

**Issue by marlonv202** [tachiyomiorg/tachiyomi-extensions#19542]
### Source information

Mangahere 1.4.19

### Source language

English

### Steps to reproduce

1. Open Mangahere Latest in the application
2. Open the first Manga
3. Update manga chapters
4. Encounter error
5. Open webview and see page error 500 (basicly a 404 error)
6. Open the page/link in a web browser seperate from the app
7. Paste the link and change "www." into "m."

_e.g. 
not working link from the application: https://www.mangahere.cc/manga/rebirth/
working link adjusted: https://m.mangahere.cc/manga/rebirth/_

### Expected behavior

1. Open Mangahere Latest in the application
2. Open the first Manga
3. Update manga chapters
4. Manga chapters are updated, no error occurs

### Actual behavior

1. Open Mangahere Latest in the application
2. Open the first Manga
3. Update manga chapters
4. Encounter error

### Tachiyomi version

0.14.7 (10/25/23 18:11)

### Android version

Android 12

### Other details

Problem seemed to occur since 3rd of january 2023 UTC

It appears Mangahere did an update to their page, might be a mangehere issue.
I am not sure, but it appears mangahere might want to introduce a new webpage.
So a decision to support this or not should be taken into account

it does appear that change "www." with "m." makes the page viable again. (question is for how long)

not working link from the application: https://www.mangahere.cc/manga/rebirth/
working link adjusted: https://m.mangahere.cc/manga/rebirth/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Baymax325** [comment]
This is also happening to me

**Comment by morethanhater** [comment]
It's not a problem with tachiyomi or it's extension, but specifically mangahere's problem. First, we need to wait untill they fix it for their website, and later we'll know if any modifications to an existing extension should be done.

**Comment by marlonv202** [comment]
@morethanhater thx for the update, was expecting something, but least I could do was make a bug report to make sure it is on the radar :)

**Comment by masdabazz** [comment]
When I opened it up in webview, it said there's a new version. Maybe the change in source is what is messing with it

**Comment by marlonv202** [comment]
The problem seems to be fixed, I will be closing this issue.
