### ISSUE TITLE
Search. Pined or All

### ISSUE THREAD

**Issue by yarik21lobok** [tachiyomiorg/tachiyomi-extensions#19559]
### Source name

Search

### Source language

English

### Describe your suggested feature

After the update, the search automatically starts in pined mode, and it was easier for me to search among all sources. Now, every time I enter a title name, the program finds nothing, so I have to manually switch the search mode. I'm not saying it's wrong, but it changes the search experience a lot. It would be nice if you could add a toggle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
