### ISSUE TITLE
Bato.to v3x & Mangadex

### ISSUE THREAD

**Issue by ImpenetrableNoble** [tachiyomiorg/tachiyomi-extensions#19554]
### Source information

N/A

### Source language

English 

### Source new URL

https://bato.to/v3x  and  https://mangadex.org/

### Other details

Hey Tachiyomi Team, I've noticed some 
recent changes in the URLs of two popular manga websites since they became obsolete, Bato.to and Mangadex, which may require adjustments to Tachiyomi's website extensions.Bato.to has migrated to a new URL: https://bato.to/v3x and Mangadex can now be accessed at https://mangadex.org/

These changes have been confirmed through their respective Discord servers, where beta testers have received notifications about the updated URLs.

As a Tachiyomi user, I've encountered challenges with the existing extensions due to the changes in these platforms. Therefore, I believe it would be beneficial for Tachiyomi's website extensions to be updated accordingly, ensuring seamless access to manga content for users.

![Screenshot_20240105_164018](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/104534608/df94ae7b-3732-435f-9a56-db3fd0bce7c7)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
They've been removed

**Comment by tommai78101** [comment]
For anyone else who Googled to here, MangaDex and Bato.to are removed due to requests from copyright holder, Kakao Entertainment. 

https://github.com/tachiyomiorg/tachiyomi-extensions/commit/51f35d8d755b798b7430e3ca42185861ce842ef6

**Comment by ImpenetrableNoble** [comment]
@tommai78101 

I understand that the content was removed due to the outdated main website extension. The copyright holders decided to make their extension obsolete within the Tachiyomi application. Thank you for informing me; I'll contact Kakao Entertainment when I have time.
