### ISSUE TITLE
recent update to 1.5 changes to some extensions note only

### ISSUE THREAD

**Issue by seijinshi** [tachiyomiorg/tachiyomi-extensions#19557]
### Source information

mangadex batoto

### Source language

English 

### Steps to reproduce

install the 2 extensions and few others from 1.4.7
update to 1.5
open extension tab

### Expected behavior

extension shows normally like others

### Actual behavior

![inbound4032591787414472668](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/155842282/ace8f792-c40f-4205-91c6-d9538f8b1cbf)
the 2 extension now shows as obsolete despite still working fine 

### Tachiyomi version

0.15

### Android version

android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/51f35d8d755b798b7430e3ca42185861ce842ef6
