### ISSUE TITLE
Like manga

### ISSUE THREAD

**Issue by Elinosorry** [tachiyomiorg/tachiyomi-extensions#19558]
### Source information

LikeManga 1.4.3

### Source language

English

### Steps to reproduce

1. Open the extension
2. An error will appear

### Expected behavior

Updating an entry or entering the extension should be done with no issue

### Actual behavior

![Screenshot_20240106-222300_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147275253/4c949bd5-0114-4557-8897-47a003d63259)

### Tachiyomi version

0.15.0

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is an error with their HTTPS certificate. We can't do anything about it, you need to wait for them to fix it.
