### ISSUE TITLE
Whats up with the removal of the MangaDex extension?

### ISSUE THREAD

**Issue by hackgrid** [tachiyomiorg/tachiyomi-extensions#19553]
### Describe why this should be added

Whats up with 51f35d8 ?

Why has some korean company a copyright claim to the source code of these tachiyomi extensions?
Surely they have no copyright for that or all the manga chapters in all languages, maybe only for korean?
And this repository contains no content from them, so no reason that they should be allowed to DCMA that!

Is there another project which maintains these removed extensions?
Is there a way to manually install extensions for Tachiyomi from a zip/apk file?

MangaDex is the best source for manga and it would be a shame that this extension does not get maintained anymore... :-(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ourslfs** [comment]
not just mangadex, but batoto as well

**Comment by arkon** [comment]
We don't have resources to fight potential legal battles.

We retain a policy of goodwill for legitimate takedown requests, whether it be from copyright holders or scanlators acting in good faith.
