### ISSUE TITLE
Extension bato.to is no working 

### ISSUE THREAD

**Issue by WonHoney** [tachiyomiorg/tachiyomi-extensions#19578]
### Source information

Bato.to 1.4.32

### Source language

English

### Steps to reproduce

1.install the extention
2.enter extention and click on any series
3. try to read
4. Get an error "couldn't find script with image data".

### Expected behavior

Open de chapter 

### Actual behavior

No open chapter and show erro.

### Tachiyomi version

0.15.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Bato.to has been removed
