### ISSUE TITLE
XOXOCOMICS domain changed. Needs an update.

### ISSUE THREAD

**Issue by Rinhaka** [tachiyomiorg/tachiyomi-extensions#19571]
### Source information

XOXO Comics 1.4.4

### Source language

English

### Source new URL

https://xoxocomic.com/

### Other details

The XOXOComics domain has changed and the extension version 1.4.4 keeps loading the old domain. We need an updated extension for XOXOComics as the old domain seems to be for sale, hopefully nobody buys it before this is fixed, could be a security risk :/
Please, someone help out, it has been 5 months.

![Screenshot_20240105_220318_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/152467537/b0361755-14db-49ea-b259-8edeb5baea63)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Rinhaka** [comment]
Why is everyone being a fucking asshole about this issue!!! We have been asking for an update for months and it keeps getting closed. Wtf is wrong here?

**Comment by AntsyLich** [comment]
> We have been asking for an update for months and it keeps getting closed. Wtf is wrong here?

No one among the volunteers are interested in fixing the extensions

**Comment by arkon** [comment]
1. It's a bot.
2. There's an open issue for the same thing (#19388), don't create spam.
