### ISSUE TITLE
NewToki和bato.to能否继续运营？

### ISSUE THREAD

**Issue by FengTeLai** [tachiyomiorg/tachiyomi-extensions#19577]
### Source name

NewToki 1.4.29

### Source language

韩语(KO)/英语(EN)

### Describe your suggested feature

NewToki和bato.to被kakao版权了，但能否继续维护，更新发布交由我（第三方）来做，由我在其它平台发布APK？

### Other details

英文和韩语用户缺不了这两个网站，都想下载永久保存，求求了。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Yes. and many others are also maintaining a 3rd party repo
