### ISSUE TITLE
I can't read any chapters 

### ISSUE THREAD

**Issue by PotatoKop** [tachiyomiorg/tachiyomi-extensions#19589]
### Source information

With any source

### Source language

Any language 

### Steps to reproduce

I open the app
I tap on the chapter I want to read 
It won't open

### Expected behavior

It should open the chapter for me to read 

### Actual behavior

It says "couldn't find script with image data"

### Tachiyomi version

0.15.1

### Android version

Android 34

### Other details

As soon as I updated the app to the new version it won't let me open ANY chapters from any source, and it won't even let me download anything. Please, PLEASE help me fix this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This isn't from any source at all, it's Bato.to only, and we don't offer support to obsolete extensions.
