### ISSUE TITLE
Library is not Update new chapter 

### ISSUE THREAD

**Issue by RattandeepTriapthi** [tachiyomiorg/tachiyomi-extensions#19583]
### Source information

All Extensions- Hiperdex, Mango, Mangasee

### Source language

English 

### Steps to reproduce

1. I Installed new updated version On 7 Jan 2024
2. I didn't gave battery performance permission
3. After all this steps I try to refresh the manga I was reading but it didn't update new chapter and I tried to do global update and it didn't work so I did clear data and restore all my data but the issue is still there. I even reinstall the extension to buy I'm facing the same issue unable to get new chapters on update.

### Expected behavior

On update library it is not giving new chapter 

### Actual behavior

It should give me new chapters on all libraries 

### Tachiyomi version

0.15.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Too vague and also this:

> If this is an issue with the app itself, I should be opening an issue in the app repository.

**Comment by RattandeepTriapthi** [comment]
There is a change in issues now I'm able to update the library on single manga's but unable to do it globally update because my Hiperdex extension is getting failed to by pass the cloud
