### ISSUE TITLE
Mangadex and bato.to without korean

### ISSUE THREAD

**Issue by B10Reaper** [tachiyomiorg/tachiyomi-extensions#19587]
### Source name

Mangadex and bato.to

### Source link

Mangadex.org and bato.to

### Source language

English 

### Other details

It looks like the company making the complaint is Korean, it should be enough to remove Korean source language from them. There are series that only exist on these sources, enough so that it'd be better to go use a different app than to keep using tachiyomi.

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This won't work as eventually Japanese and other nationality publishers can also do the same thing. It won't be added back to the official repository.

**Comment by Xumiiii** [comment]
> This won't work as eventually Japanese and other nationality publishers can also do the same thing. It won't be added back to the official repository.

Hasn't that always been a possibility though ?

**Comment by alessandrojean** [comment]
Yes but it's desirable to be more cautious now.
