### ISSUE TITLE
Chapters didn't work

### ISSUE THREAD

**Issue by Ceron00** [tachiyomiorg/tachiyomi-extensions#19581]
### Source information

Mangaswat 1.4.42

### Source language

Arabic 

### Steps to reproduce

The bug with all chapters 

### Expected behavior

The expected behavior is when I open any chapter it works for me 

### Actual behavior

The actual behavior is when I open any chapter it doesn't work

### Tachiyomi version

0.15.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all fields correctly and do provide any errors you're getting next time.
