### ISSUE TITLE
更新后无法获取所有扩展列表

### ISSUE THREAD

**Issue by 2936747557** [tachiyomiorg/tachiyomi-extensions#19599]
### Source information

所有插件

### Source language

all

### Steps to reproduce

0.15.0之前的是可以直接获取所有扩展列表并更新的，但是升级到0.15.0后大陆网无法获取所有扩展列表了，需要VPN才可以刷新出来

### Expected behavior

应该是可以直接刷新出所有扩展的

### Actual behavior

显示无法获取扩展

### Tachiyomi version

0.15.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Using extension repos, you can add a mirror like `https://gcore.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/index.min.json`.
