### ISSUE TITLE
BATO. TO

### ISSUE THREAD

**Issue by fatmaarini** [tachiyomiorg/tachiyomi-extensions#19592]
### Source information

Batoto 1.4.131

### Source language

Semua 

### Steps to reproduce

The batoto web suddenly disappeared, is it true that it has been deleted?
If so, please return the batoto

### Expected behavior

I want batoto back 

### Actual behavior

The batoto web suddenly disappeared, is it true that it has been deleted?
If so, please return the batoto

### Tachiyomi version

0.15.1

### Android version

Android 9

### Other details

Why is batoto not in tachiyomi? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fatmaarini** [comment]
If so then then I have no point in downloading tachiyomi

**Comment by alessandrojean** [comment]
Feel free to use other apps if you want to insist into using this source.
