### ISSUE TITLE
One Piece Ex 

### ISSUE THREAD

**Issue by PODBENDLIU** [tachiyomiorg/tachiyomi-extensions#19602]
### Source information

One Piece Ex 1.4.6

### Source language

Português Br

### Steps to reproduce

![Screenshot_20240108-093520_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/155971436/f28754cf-e7b4-4893-8ee7-ea1c3b1f1b3e)

### Expected behavior

![Screenshot_20240108-093520_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/155971436/e29e866b-8a94-45a1-98f1-be81e9c7d441)
=expected

### Actual behavior

![Screenshot_20240108-093520_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/155971436/8e5bb767-2a94-4854-9321-4e7f5853c6a1)

### Tachiyomi version

0.15.0

### Android version

11

### Other details

![Screenshot_20240108-093520_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/155971436/b21485f1-d037-4500-be94-3ae96d1a8432)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill all requested fields correctly, just pasting the same screenshot on every single field doesn't help into anything.

**Comment by alessandrojean** [comment]
Again, please do fill a new issue correctly.
