### ISSUE TITLE
No carga capitulos de la fuente Yugenmangas (aparece "timeout")

### ISSUE THREAD

**Issue by BastiVader** [tachiyomiorg/tachiyomi-extensions#19606]
### Source information

Yugenmangas 1.4.29

### Source language

Español

### Steps to reproduce

- Entra a Tachiyomi 
- Entra a la fuente (yugenmangas)
- Entra a un manhwa 
- Espera a que cargue
- Se sale del manhwa y aparece "timeout" como aviso de Tachiyomi 

### Expected behavior

- Entrar a Tachiyomi
- Entrar a la fuente 
- Entrar al manhwa 
- Entrar al capítulo 
- Leerlo

### Actual behavior

- Entra a Tachiyomi 
- Entra a la fuente (yugenmangas)
- Entra a un manhwa 
- Espera a que cargue
- Se sale del manhwa y aparece "timeout" como aviso de Tachiyomi 

### Tachiyomi version

0.15.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Timeout means the site server didn't send the response in time. This isn't something we can fix.
