### ISSUE TITLE
Mangakakalot not working

### ISSUE THREAD

**Issue by masdabazz** [tachiyomiorg/tachiyomi-extensions#19611]
### Source information

Mangakakalot 1.4.8

### Source language

English

### Steps to reproduce

1) Go on any manga/manwha in library and reload, 
2) open up webview from the page

### Expected behavior

1) Should update or not show anything.
2) should go to mangakakalot page for manga/manwha in browser

### Actual behavior

1) HTTP 404, check website in webview
2) When I check the website in webview from the mangapage, it takes me to manganato and says there is no input file. However, when I go to webview through the extensions tab, it takes me to the correct place, mangakakalot.

I experimented some more and found that some mangas behave normally (update normally and take me to correct webview), these are the ones that do not work:

            - Mercenary Enrollment
            - Terminally-Ill Genius Dark Knight
            - My Little Brother is The Academy's Hotshot
            - Mato Seihei no Slave
            - An Old Man From the Countryside becomes a Swords Saint
            - Villains are Destined to DIe
            - I used to be a boss
            - The S-Classes that I Raised
            - A saintess who was adopted by the grand duke
            - Hand Jumper
            - I became the despised granddaughter of the Murim family
            - I became the Male lead's adopted daughter
            - My School Life pretending to be a worthless person
            - eminence in shadow
            - The Novel's Extra
            - And more

### Tachiyomi version

0.15.1

### Android version

Andriod 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They change the URL of their manga constantly and there's nothing we can do about it. Migrate from Mangakakalot to Mangakakalot to update your entries.
