### ISSUE TITLE
[Source Request] [Chinese] zero搬运网

### ISSUE THREAD

**Issue by jasonhpchu** [tachiyomiorg/tachiyomi-extensions#2079]
http://www.zerobyw4.com/

**Comment by Yusei-StarDust** [comment]
Now the url has switched [http://www.zerobywsaber.com](url)

Also, this site offer the image source analysis for another manga apk, maybe the code will be helpful:
[http://www.zerobywsaber.com/forum.php?mod=viewthread&tid=52940&extra=page%3D1](url)
`{"bookSourceGroup":"【付费不能看】","bookSourceName":"ZERO搬运网","bookSourceType":"漫画","bookSourceUrl":"http://www.zerobywsaber.com","enable":true,"httpUserAgent":"","lastUpdateTime":0,"loginUrl":"","loginUrlResult":"","ruleBookAuthor":"class.uk-margin-left.0@class.uk-label.0@text#作者:","ruleBookContent":":_R001_9D43EFDCD855834C71426DD21679ED8AAB3315CBCF76849EE48CD8E40A52E7E34AE0FF56F026C712A579EF38BE40660133FF413ED7CD6B091F75962687BA1545391558CCCFCD8CBDB8875D5B61D56BA674F53FD8AB982D5367DF518F5ED8BF83A7381578A78DBD7179AB3FE029EAAE8C6A10E22BD985DAFD1A7C1E54A4F9DC52","ruleBookKind":"class.uk-margin-left.0@class.cl.0@tag.a!0@text\u0026class.uk-margin-left.0@class.cl.0@tag.span.0@text","ruleBookLastChapter":"","ruleBookName":"class.uk-margin-left.0@tag.h3@text#(^.*?【.*?】).*$#$1","ruleBookUrlPattern":"","ruleChapterList":"class.muludiv","ruleChapterName":"tag.a.0@text","ruleChapterUrl":"","ruleChapterUrlNext":"","ruleContentUrl":"tag.a.0@href@header:{Cookie:\"__cfduid\u003ddfbf63039d629772dd8dbb18fe3b13c641555840275; kd5S_2132_saltkey\u003dmaGoKAVO; kd5S_2132_ulastactivity\u003df7d3a7gH6W3gmNgKeB%2Fll%2BUqqBYv9IsixL4GGXHLlXuGXLvkXByy; kd5S_2132_auth\u003dbdcbAfbJ7G06Ov%2B6GYT26rAVKUVpz%2B0vxlqRKaYT7rQmbcdcsyyOHX1I%2Bzb6Bz931s4D5xMaY2aqfvAvZv5RHel1OaA; kd5S_2132_tshuz_accountlogin\u003d470231; kd5S_2132_sid\u003dRKlQgk\"}","ruleContentUrlNext":"","ruleCoverUrl":"class.uk-width-medium.0@tag.img@src","ruleFindUrl":"上架::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026c\u003dindex\u0026a\u003dku\u0026odfie\u003daddtime\u0026order\u003dasc\u0026page\u003dsearchPage\n更新::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026c\u003dindex\u0026a\u003dku\u0026odfie\u003dedittime\u0026order\u003ddesc\u0026page\u003dsearchPage\n卖肉::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d1\u0026page\u003dsearchPage\n战斗::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d15\u0026page\u003dsearchPage\n日常::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d32\u0026page\u003dsearchPage\n后宫::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d6\u0026page\u003dsearchPage\n搞笑::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d13\u0026page\u003dsearchPage\n日常::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d28\u0026page\u003dsearchPage\n爱情::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d31\u0026page\u003dsearchPage\n冒险::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d22\u0026page\u003dsearchPage\n奇幻::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d23\u0026page\u003dsearchPage\n战斗::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d26\u0026page\u003dsearchPage\n体育::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d29\u0026page\u003dsearchPage\n机战::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d34\u0026page\u003dsearchPage\n职业::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026category_id\u003d35\u0026page\u003dsearchPage\n连载::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026jindu\u003d0\u0026page\u003dsearchPage\n完结::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026jindu\u003d1\u0026page\u003dsearchPage\n半生半熟::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026shuxing\u003d%E4%B8%80%E5%8D%8A%E4%B8%AD%E6%96%87%E4%B8%80%E5%8D%8A%E7%94%9F%E8%82%89\u0026page\u003dsearchPage\n全生肉::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026shuxing\u003d%E5%85%A8%E7%94%9F%E8%82%89\u0026page\u003dsearchPage\n全中文::http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dku\u0026shuxing\u003d%E5%85%A8%E4%B8%AD%E6%96%87\u0026page\u003dsearchPage","ruleIntroduce":"class.uk-margin-left.0@class.uk-alert@text","ruleSearchAuthor":"","ruleSearchCoverUrl":"tag.img@src","ruleSearchKind":"","ruleSearchLastChapter":"tag.p.0@text#^.*?【1-(\\d+\\D).*$#$1","ruleSearchList":"class.jameson_manhua@class.uk-card","ruleSearchName":"tag.p.0@text#(^.*?【.*?】).*$#$1","ruleSearchNoteUrl":"tag.a@href","ruleSearchUrl":"http://www.zerobywsaber.com/plugin.php?id\u003djameson_manhua\u0026a\u003dsearch\u0026c\u003dindex\u0026keyword\u003dsearchKey","serialNumber":142,"sourceRemark":"","weight":698}`

**Comment by anenasa** [comment]
Hello, I am working on this. It is almost finished, but I am looking for a way to login to read more chapters.

**Comment by Yusei-StarDust** [comment]
Now the website address switched to https://www.zerobywzio.com/

![Snipaste_2021-08-06_10-17-41](https://user-images.githubusercontent.com/26076608/128446323-81f38e4d-e71e-4b92-be30-7e5994f2270c.png)

![Snipaste_2021-08-06_10-20-52](https://user-images.githubusercontent.com/26076608/128446336-4ad3726a-76b3-4fd8-92ad-b1b3fa6f2c90.png)

I made a simple translation. Hope these images could help you.
