### ISSUE TITLE
[Source Request] [Italian] Zeurelscan

### ISSUE THREAD

**Issue by aslupo98** [tachiyomiorg/tachiyomi-extensions#2088]
### Source Website

http://zeurelscan.altervista.org/
https://reader.powermanga.org/

### Other Details

Are a very good italian subbers site... Others, like Mangaworld, steal chapters from these sites without write the source.
Please, save them from this stupid sites, and add these to make them known

If is possible add they, they'll be a perfect for our country.

**Comment by aslupo98** [comment]
And also MangaWorld and others don't have a very lot of chapters

**Comment by aslupo98** [comment]
Very thanks for the update for power manga... Now Is time for zeurelscan

**Comment by SnakeDoc83** [comment]
Looks like quite a few chapters from certain Zeurelscan manga are missing some or even all pages; don't see any updates the last couple months either.  You're sure it's worth it to you?

**Comment by aslupo98** [comment]
is a strage site... becouse you have to click the latest chapter and when you are in the web reader, you can select the other chapter

**Comment by salva0** [comment]
> ### Source Website
> http://zeurelscan.altervista.org/
> https://reader.powermanga.org/
> 
> ### Other Details
> Are a very good italian subbers site... Others, like Mangaworld, steal chapters from these sites without write the source.
> Please, save them from this stupid sites, and add these to make them known
> 
> If is possible add they, they'll be a perfect for our country.

powermanga c'è già

**Comment by aslupo98** [comment]
> 
> 
> > ### Source Website
> > http://zeurelscan.altervista.org/
> > https://reader.powermanga.org/
> > ### Other Details
> > Are a very good italian subbers site... Others, like Mangaworld, steal chapters from these sites without write the source.
> > Please, save them from this stupid sites, and add these to make them known
> > If is possible add they, they'll be a perfect for our country.
> 
> powermanga c'è già

E grazie al ca, l'hanno aggiunta dopo che gliel'ho chiesta XD

**Comment by ToroLoco94** [comment]
So ... I agree, in part, for mangaeden and mangaworld.  Mangadex are the same forums to publish the chapters.

  I use external sites because there is no list where you can read manga.  If the forums don't help make themselves known, I will always use external sites.  Mangalink is an excellent idea.  But for example boruto is absent.

**Comment by Genlon83** [comment]
Thank you by zeurelscan :) ps I reuploaded each chapter

**Comment by Genlon83** [comment]
> is a strage site... becouse you have to click the latest chapter and when you are in the web reader, you can select the other chapter

How do you think I could change it to do it better?

**Comment by happywillow0** [comment]
Account suspended - please close.

**Comment by scb261** [comment]
Looks like this is the new link https://www.zeurelscan.com/ (linked from their mangadex page)

**Comment by Genlon83** [comment]
I confirm, New site Is zeurelscan.com

Il dom 28 feb 2021, 02:59 scb261 <notifications@github.com> ha scritto:
