### ISSUE TITLE
[Source Request] Skyfall Scans

### ISSUE THREAD

**Issue by alexporth** [tachiyomiorg/tachiyomi-extensions#2276]
### Source Website
Website can be found at https://skyfallscans.ga/

### Other Details
English source

**Comment by as280093** [comment]
**ICONS:**
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4237127/ic_launcher.2.zip)

**Comment by joseph619** [comment]
Sources appears to be dead
