### ISSUE TITLE
[Bug] [indonesian] mangaku.in extension no result found

### ISSUE THREAD

**Issue by reihanakbar** [tachiyomiorg/tachiyomi-extensions#2530]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9

I can't acces mangaku extension, but it openend fine in web view.
Please fix this

![Screenshot_2020-03-28-06-04-58-163_eu kanade tachiyomi](https://user-images.githubusercontent.com/58359762/77807453-6fcaa180-70ba-11ea-8cc6-6bada70e1dfb.jpg)

**Comment by happywillow0** [comment]
I took a look and going down the list:
No results found can be fixed, 
some thumbnails can be fixed
Chapter list can be fixed

**However**, the pages for each chapter look to be encoded now so I'm not sure we can get the pages from the website anymore. This is not fixable at least by me. 

The entire site is very anti-poking around (has programs that make it hard to work with) so I would personally recommend using another site.
