### ISSUE TITLE
[Source request] Mangazone.cc

### ISSUE THREAD

**Issue by ANETAIII** [tachiyomiorg/tachiyomi-extensions#2622]
https://mangasum.com/
https://manga68.com/
https://manhuabox.net/
https://mangazone.cc/

**Comment by happywillow0** [comment]
Thanks for your suggestions. 
Each website should be opened in it's own issue to be proper.

This can be added to Manhua Plus whatever the actually theme is called:

- MangaSum

The following can be added to Madara:

- manga68.com
- manhuabox.net
- mangazone.cc

Someone will take a look at some point.

**Comment by ANETAIII** [comment]
Thanks, but what exactly should I do?

**Comment by ANETAIII** [comment]
How I add to madara?
How can I install manhua plus? I can't see manhua plus to install it why?

**Comment by arkon** [comment]
Wait for a developer to add them.

**Comment by CarlosEsco** [comment]
Manhua plus is in wp comics

**Comment by ANETAIII** [comment]
I am glad you add mangasum but some chapters are page list empty errors :(

**Comment by SnakeDoc83** [comment]
Which ones?

**Comment by happywillow0** [comment]
Manga68 and and Manhuabox will be added soon. 

I couldn't get Mangazone.cc working. It looks like Madara but it has some custom tweaks including a check to see if you really loaded the chapter page or not before allowing access to the images. (It is more advanced than just a referrer check as I am aware). Here is the code to start if anyone else wants to take a look:

```
class MangaZone : Madara("MangaZone", "https://mangazone.cc", "en") {
    override fun headersBuilder(): Headers.Builder = super.headersBuilder().add("Referer", baseUrl)
    override fun popularMangaRequest(page: Int): Request = GET("$baseUrl/views/$page/", headers)
    override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/latest/$page/", headers)
    override fun popularMangaSelector(): String = "div.c-tabs-item div.row"
}
```

**Comment by VeganCzech** [comment]
Is he going to add mangazone.cc? Thank you for the reply

**Comment by VeganCzech** [comment]
How will it be with the addition of support page mangazone.cc? The author of the extension wrote that there are problems and it's already from April. So you don't know what it looks like, please? I don't want to unnecessarily do a new topic and duplicate it.
How will it be with the addition of support page mangazone.cc? The author of the extension wrote that there are problems and it's already from April. So you don't know what it looks like, please? I don't want to unnecessarily do a new topic and duplicate it. Thank you for replying to my post. 
 Thank you for replying to my post

**Comment by SnakeDoc83** [comment]
The website has measures to deny scraping, it can't be added until they're
solved. From what I've seen, the main issue is with cookies.

**Comment by ANETAIII** [comment]
Is not solved mangazone problem? I really want download from it

**Comment by AriaMoradi** [comment]
http://mangazone.cc/ is dead. this can be closed.
