### ISSUE TITLE
[Feature Request] Mangakakalot: Add support for image server in extension setting

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi-extensions#2720]
Mangakakalot has two image servers, and for many users, one is faster than the other. It would be better if an option to choose image server was added to the extension.

**Comment by azeunkn0wn** [comment]
one of the server have broken manga chapters (missing and duplicated pages) and wrong chapters (chapter 1 is from a different manga). not sure which server is bad, maybe both of them have similar issues
