### ISSUE TITLE
[Source Request] MangaTigre

### ISSUE THREAD

**Issue by MerradOklom** [tachiyomiorg/tachiyomi-extensions#2821]
### Source Website
Website can be found at <https://www.mangatigre.com/>.

### Other Details
This is a Spanish source.
They seem to be using some kind of theme, but I couldn't figure out which.

**Comment by LeeanPR95** [comment]
Please add this extension. 
There is updated manga here ... 
They added a lot of extensions that don't compare to this one. Please...
