### ISSUE TITLE
[Bug] Readcomiconline : page list empty

### ISSUE THREAD

**Issue by Shabaaz22** [tachiyomiorg/tachiyomi-extensions#2874]
![20200502_132846](https://user-images.githubusercontent.com/64425974/80866705-17259000-8c88-11ea-9b07-d2aea102a267.jpg)
![Screenshot_20200502-133017_Tachiyomi](https://user-images.githubusercontent.com/64425974/80866715-20aef800-8c88-11ea-8ade-b0c55f0f850c.jpg)

### Device information
* Tachiyomi version:preview r2237
* Android version: 10

### Source information
* Source name: Readcomiconline
* Source extension version: 1.2.8

## Steps to reproduce
1. First Step
Opening any comics from the catalogue and clicking on any chapter will result in page list empty message. 
2.Second step
Opening Webview and clicking on any comics will automatically boot me out of the Webview into the catalogues page and the page list will still be empty. 

### Expected behavior
This should have happened 
Comic should have opened on Webviewer so I could input the captcha. 

### Actual behavior
This happens instead
Booted out from Webview before I can complete the captcha. 

### Other details
If i clear my chrome apps cookies and data first, then load up webviewer and then click the 3 dots and open up in a new browser I can then access the captcha in this new browser and complete it, this temporarily fixes the issue and allows me access the page list and downloading chapters, however the issue does still persist after a while. Downloading chapters may be the trigger for cloudflare error.

**Comment by scb261** [comment]
Fixed by #5659
