### ISSUE TITLE
[Source Request] The Ink Tank

### ISSUE THREAD

**Issue by NaeemBolchhi** [tachiyomiorg/tachiyomi-extensions#3118]
### Source Website
- Name: The Ink Tank
- Link: https://www.theinktank.co/5yearslater
- Language(s): English

### Other Details
Currently only has one fan comic with 9 chapters, but really popular among followers of Ben 10 and Danny Phantom, who know about the project.

**Comment by effcol** [comment]
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4616458/ic_launcher.zip)

Here's some icons from the website icon :)
