### ISSUE TITLE
[Source Request] EroCool

### ISSUE THREAD

**Issue by maxzeku** [tachiyomiorg/tachiyomi-extensions#3189]
### Source Website ### 

- Name: EroCool
- Link: https://erocool.net/
- Language(s): English

**Comment by Arekkusu1998** [comment]
I join the same request, adding one thing: if and when You add https://erocool.net/ to _Tachiyomi-Extensions_, please also comprehend all the other language options (**Japanese** and **Chinese**), in addition to **English**. Many manga / manhwa / manhua are only found raw.

Thank You very much.
