### ISSUE TITLE
Consulta sobre la extensión Toomics "Spanish" Latino

### ISSUE THREAD

**Issue by Credits125** [tachiyomiorg/tachiyomi-extensions#3196]
Una pregunta es posible agregar una cuenta para leer los capítulos VIP de toomics , tengo una cuenta persona VIP y me gustaría agregarla en tachiyomi y ver desde ahí para poder leer el contenido de adultos. Es que desde la web no me gusta quiero saber si es posible.

**Comment by leox233** [comment]
Prueba logeando en el webview

**Comment by alessandrojean** [comment]
Closing by the same reason of #7507.
