### ISSUE TITLE
[Bug] Mangahasu timeout

### ISSUE THREAD

**Issue by isaiahisaiahisaiah** [tachiyomiorg/tachiyomi-extensions#3200]
![Screenshot_20200517-114325_Tachiyomi](https://user-images.githubusercontent.com/65478075/82135416-32220380-9835-11ea-8c88-f7d1682f2db9.jpg)

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- I cleared all cache, cookies and datebase

**Comment by scb261** [comment]
I don't think this happens anymore, should be closed
