### ISSUE TITLE
ScanFR: Identify spoiler chapters and notify when they become true chapters

### ISSUE THREAD

**Issue by Matth7878** [tachiyomiorg/tachiyomi-extensions#3208]
### Why/User Benefit/User Problem
Some chapters are spoiler and not the actual chapters.
When the actual chapters are released their name is updated and do not contains anymore spoiler.

User should be notified about spoiler turning to true chapter. Right now he have to check regularly if true chapters have become available

### What/Requirements
Identify chapter with "spoiler" in their name.
Maybe make a setting for each manga so user can individually tune the feature by : 
- turning it off
- modifying the regex / filter to match for a chapter to be considered a spoiler (nice if in some language another word is used or to avoid false identification)

On library update when spoiler chapters have their name changed and are no longer considered spoiler report it as a new chapter. Or better tell user that x chapters are no longer spoiler.

Ideally propose to user to mark those chapters unread so if spoilers were read the true chapters won't be. This would make it nice for user displaying only  manga with unread chapters in library and/or are reading spoiler.

**Comment by o01210o** [comment]
Similar to https://github.com/inorichi/tachiyomi/issues/1925

**Comment by o01210o** [comment]
@CarlosEsco I think it should remains open since the solution to https://github.com/inorichi/tachiyomi/issues/1925 is specific to Japscan and doesn't apply to this one
