### ISSUE TITLE
[Bug] LIBRARY UPDATE  FAILED <Mangahub, mangafreak,mangafreak>

### ISSUE THREAD

**Issue by dondeepak** [tachiyomiorg/tachiyomi-extensions#3339]
Device information
App version: 0.9.2-2353 (standard, ac8f292, 45)
Android version: 9 (SDK 28)
Android build ID: PKQ1.181030.001 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1951
Device model: vivo 1951
Device product name: 1951

Update Failed for some manga.
Failed manga opens in webview can be read but every time selected manga failed to update

Above All Gods: No chapters found-mangahub(en)
Arifureta Shokugyou de Sekai Saikyou: No chapters found-mangafreak(en)
Armored Gull_ The Exoskeleton Frame: No chapters found-mangahub(en)
Battle Through The Heavens: No chapters found-mangahub(en)
Battle Through the Heavens_ Return of the Beasts: No chapters found-mangahub(en)
Black Clover: No chapters found-mangahub(en)
Boku no Hero Academia: No chapters found -mangahub(en)
Boku no Hero Academia: No chapters found-mangakakalot(en)
Boruto_ Naruto Next Generations: No chapters found-mangahub(en)
Chaotic Sword God: No chapters found-mangahub(en)
D.I.C.E: No chapters found-mangahub(en)
One Piece: No chapters found-mangahub(en)
Other details
Additional details and attachments.
![Screenshot_20200528_080627](https://user-images.githubusercontent.com/24863950/83092095-3f9f7f00-a0ba-11ea-9adc-80871afc6533.jpg)

**Comment by SnakeDoc83** [comment]
What happens when you go in to them in your library and refresh the info tab?

**Comment by dondeepak** [comment]
I am getting toast says no chapter found 
![Screenshot_20200529_075147](https://user-images.githubusercontent.com/24863950/83214070-58269c80-a181-11ea-99e3-b9842681e00c.jpg)

**Comment by SnakeDoc83** [comment]
Try searching for them on their respective sources (e.g. search for Above All Gods on Mangahub), do their covers look faded (like it's favorited) or not?

**Comment by dondeepak** [comment]
yes 
![Screenshot_20200529_143616~03](https://user-images.githubusercontent.com/24863950/83242529-34337d00-a1ba-11ea-992d-fdca1ba8f69b.jpg)
![Screenshot_20200529_143525~01](https://user-images.githubusercontent.com/24863950/83242552-3b5a8b00-a1ba-11ea-94d2-af3440add438.jpg)

![Screenshot_20200529_143503~01](https://user-images.githubusercontent.com/24863950/83242575-42819900-a1ba-11ea-996c-ac60ae583bfc.jpg)

**Comment by dondeepak** [comment]
Is anyway to fix this?

**Comment by scb261** [comment]
Mangahub - I tried some manga from the list, part of them works fine and part of them works fine after logging in.
Mangafreak - you gave only one example and it works fine for me.
Mangakakalot - the same, only one example and works fine for me.
Do you still have issues? Maybe try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).

**Comment by keinezeit8** [comment]
Does this problem still persist?

**Comment by CrepeTF** [comment]
I'll be closing this issue as it's all the way from May of last year, if anyone has any persisting issues reach out on the #support channel on Discord.
