### ISSUE TITLE
[Source Request] <BaraMangaOnline>

### ISSUE THREAD

**Issue by duckchomper** [tachiyomiorg/tachiyomi-extensions#3388]
### Source Website
- Name: BaraMangaOnline
- Link: https://baramangaonline.com
- Language(s): Arabic, Chinese, Danish, Dutch, English, Filipino, French Hebrew, Indonesian, Italian, Japanese, Korean, Norwegian, Portugese, Russian, Spanish, Vietnamese

### Other Info

Kinda focuses on bara manga, which is really hard to find on existing sources.

**Comment by wrestlerdude314** [comment]
bump!
