### ISSUE TITLE
[Enhancement] Tapastic Mature Comics

### ISSUE THREAD

**Issue by SneakyIntel** [tachiyomiorg/tachiyomi-extensions#3468]
### Source Website
- Name: Tapastic
- Link: https://m.tapas.io/mature
- Language(s): EN

### Other Details
Yes the tapastic extension is already available and you can log-in to download the chapters you bought but you are unable to view & download their Mature comics (only available on web browser/web view).

**Comment by emrexemre** [comment]
is that okay if i bump this up? we are still unable to view them
