### ISSUE TITLE
[Source Request] Loading Artist

### ISSUE THREAD

**Issue by keinezeit8** [tachiyomiorg/tachiyomi-extensions#3510]
### Source Website
- Name: Loading Artist
- Link: https://loadingartist.com
- Language(s): en

### Other Details
The text below each panel is not needed.

Latest panel can be found under https://loadingartist.com/latest

**Comment by roshavagarga** [comment]
Would also be interested in this one.

**Comment by keinezeit8** [comment]
I looked a bit into it and found that there is an RSS Feed available under 
[https://loadingartist.com/feed/](url)
and all comics are archived at [https://loadingartist.com/archives/?archive_year=2020](url) with the number being the years from 2011 to today

**Comment by roshavagarga** [comment]
Hopefully someone more knowledgeable in kotlin will have the time to give it a look over then :)

**Comment by roshavagarga** [comment]
Still want this :)

**Comment by roshavagarga** [comment]
@arkon Is it supposed to function the way it does? Opening the extensions shows each comic page as a separate thing to add, rather than combining all of them under 1 comic :)

**Comment by arkon** [comment]
Ask the person who wrote it, not me.

**Comment by roshavagarga** [comment]
My bad. @Arraiment - there seems to be an issue :)

**Comment by Arraiment** [comment]
> Opening the extensions shows each comic page as a separate thing

Erm yeah that's how I chose to implement it based on the data returned from the website.
Would you rather have comics split into archives by year?

**Comment by keinezeit8** [comment]
I would prefer to only have one comic (like XKCD) or comics split by year (like Cyanide & Happiness)

**Comment by Arraiment** [comment]
Ok I'll see if I can't split them up by year. But note that you won't be able to search for individual comics like on the website, and chapter dates _might_ screw up.

**Comment by roshavagarga** [comment]
Ideally everything should get shoved into 1 comic. As far as I remember, the page code for each page does use <time></time>?

**Comment by Arraiment** [comment]
> Yup, it does. The first comic has this as its posting date in source code: <time datetime=2011-01-04>January 4, 2011</time>

Ooh I did not notice that. Although I'll probably use the site's provided json to generate the chapter list now.

> Ideally everything should get shoved into 1 comic

If you prefer that then sure. It'll probably take longer to load the chapter list though.

**Comment by roshavagarga** [comment]
In that case, I guess yearly would be the better option, some extensions do take a while to load because of being shoved in the same place (xkcd is fast, but SMBC is sluggish).

**Comment by Arraiment** [comment]
I'll do a bit of testing, if it loads in less than ~3s I think I'll put them all in the same comic page.
