### ISSUE TITLE
[Source Request] Mangadeep

### ISSUE THREAD

**Issue by rro123** [tachiyomiorg/tachiyomi-extensions#3535]
Source Website
- Name: Mangadeep
- Link: www.mangadeep.com
- Language(s): English

**Comment by E3FxGaming** [comment]
I have reason to believe that mangadeep is just a deceiving mirror of www.tenmanga.com, which was requested in #3275.
Whoever is mirroring the website did a poor job though, e.g.
- a link on mangadeep to a Facebook homepage still points to the Facebook page of tenmanga
- the ajax/javascript on mangadeep is pretty broken, while it works still fine on tenmanga.

(This may change now that I've pointed it out, but the similarities between the two websites probably won't change.)

@rro123 Is there a special reason for you wanting this source? Does this website have something other websites don't have?

**Comment by rro123** [comment]
Among all mangareader sites that i follow up so far, i believe that
mangadeep is the one with the fastest update, at least in some manga such
as one piece. They post it at least a few hours (if not days) faster than
other sites. I haven't checked tenmanga yet, so i don't know whether it's
the same or not. Maybe i'll check them later.

The other reason is, in my country, many mangareader sites are blocked by
my ISP. Sites like mangafox, mangakakalot, and some others can't be
accessed. And so far, mangadeep is safe. I don't know about Tenmanga, but
if it's really the same as mangadeep, and it's not yet blocked by my ISP,
then i guess either of them is fine. Thanks for your attention to my
request.
