### ISSUE TITLE
[Source Request] Sankaku

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi-extensions#3557]
### Source Website
- Name: Sankaku
- Link 1: https://chan.sankakucomplex.com/
-Link 2:
https://beta.sankakucomplex.com/?tags=female
- Language(s): All

**Comment by vengiare** [comment]
Link for their books section:
beta.sankakucomplex.com/books

**Comment by Noname-noragami** [comment]
https://beta.sankakucomplex.com/books
And if you can please  show 20 image alias under the chapter by new to old by emty bơm ở something like this, or gallery, slide show
