### ISSUE TITLE
[Source Request] NyaHentai

### ISSUE THREAD

**Issue by shashank-p** [tachiyomiorg/tachiyomi-extensions#3568]
### Source Website
- Name: NyaHentai
- Link: https://nyahentai.com/
- Language(s): English

### Other Details
Website is similar to nhentai we can use nhentai files

**Comment by IhToN** [comment]
Added a custom extension to support NyaHentai (English version only)

https://github.com/IhToN/tachiyomi-extensions/commit/84c2afcc1529b4fd3c49d3622d2982cd34079a7d

Needs testing as for some reason my Tachiyomi instance in my phone was not recognizing the extension installation.
