### ISSUE TITLE
[Bug] <Hentaivn>: Main and latest page not loading

### ISSUE THREAD

**Issue by leoparker157** [tachiyomiorg/tachiyomi-extensions#3623]
### Device information
- Tachiyomi version: 1.0.7
- Android version: 8

### Source information
- Name: Hentaivn
- Extension version: 1.2.5
both main page and latest page don't load , it may work if you are using filter to search , I have tried to clear  cookies but it;s still not working
![image](https://user-images.githubusercontent.com/59758841/85892326-f22e4300-b81a-11ea-92b8-cf24c7e0b234.png)

**Comment by SnakeDoc83** [comment]
Probably related to https://github.com/inorichi/tachiyomi-extensions/issues/3033

What do you see when you open in webview?

**Comment by leoparker157** [comment]
> Probably related to #3033
> 
> What do you see when you open in webview?

Normal .

**Comment by SnakeDoc83** [comment]
No cloudflare or captcha before the site loads?

**Comment by leoparker157** [comment]
> Probably related to #3033
> 
> What do you see when you open in webview?

 i also have tried on another device such as Nox on PC , but still bug

**Comment by leoparker157** [comment]
> No cloudflare or captcha before the site loads?

no

**Comment by Sehai1** [comment]
Android 9 and have same issue

**Comment by Sehai1** [comment]
@leoparker157 does your extension work?

**Comment by scb261** [comment]
A user on discord and I had the same problem. Browse and Latest didn't work, but search in Browse did show manga. But when I taped on manga - it was giving error *No chapters found*.  Clearing cache/cookies/database helped, so anyone with this problem, try to do it in Advanced settings. But now there is new bug:

Covers won't load if you:
- open Browse without any search
- open Latest

Covers load if you:
- open a manga page from the previous list
- open Browse and search something

**Comment by scb261** [comment]
It looks like opening the source in WebView breaks the source and you need to clear cookies to fix it. But covers and pages won't load ii any case now
