### ISSUE TITLE
[Bug] Tapas: can't access locked chapters

### ISSUE THREAD

**Issue by Lightjohn** [tachiyomiorg/tachiyomi-extensions#3648]
It's partially a Bug, question, feature request so feel free to close it.

At first I have an issue on how to access locked chapters for Tapas.
It seems to be done by login trough web view, not sure where at first.

[**Bug part**]
After some time I found where to access webview from Tapas but when I hit login I don't see the login window as it would happen in normal browser.
I have the black overlay when I hit login but the login windows is not shown.

**First** I know webview is not part of Tachiyomi but a better way to login would be helpful I think.

[**Feature part**]
Could we have an extension preference where we can enter Username / Password and the extension will use it?

[**Question part**]
Can I unlock chapter tapas from Tachiyomi if I have enough credits?

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: Tapas
- Extension version: 1.2.10

## Steps to reproduce
1. Got to Browse -> Sources -> Tapas -> Browse -> Open in WebView
2. Tap login

### Expected behavior
I can login and Tapas will use this login

### Actual behavior
Login windows doesn't appear

**Comment by SnakeDoc83** [comment]
Pretty sure it worked before, but I think I see what you mean; their little login window closes before I can enter any credentials.
