### ISSUE TITLE
[Bug] CONTRIBUTION.MD: No way to debug extension is wrong

### ISSUE THREAD

**Issue by hapylestat** [tachiyomiorg/tachiyomi-extensions#3669]
### Device information
- Tachiyomi version: branch dev
- Android version: 9 (Pie)

### Other details
It is possible to debug tachiyomi extension step by step when running application in AVD. Everything you need is to run plugin as it was proposed in the doc "URL|a|-W -S -n eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.main.MainActivity -a eu.kanade.tachiyomi.SHOW_CATALOGUES" and then use "Attach Debugger to Android Process" with attaching to tachiyomi process. After this any function in the plugin could be debugged same as Evaluation could be used.

As tachiyomi main app were used compiled from the dev branch binary.

Could we point this in the documentation?

**Comment by arkon** [comment]
Please submit a PR.
