### ISSUE TITLE
[Bug] Nude-Moon.net : Does not work after login

### ISSUE THREAD

**Issue by iluha3w** [tachiyomiorg/tachiyomi-extensions#3708]
### Device information
- Tachiyomi version: stable 0.9.2
- Android version: 6

### Source information
- Name: Nude-Moon
- Extension version: 1.2.4

## Steps to reproduce
1. Open nude-moon.net in webviev 
2. Account login
3. Any manga from nude-moon.net does not open with the error "Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.data()'on a null object reference"

### Expected behavior
After logging in to the account get access to the entire manga

### Actual behavior
Any manga from the source does not open

### Other details
Without logging in, the extension works, but the part of the manga that is available only to registered users is not displayed

**Comment by SnakeDoc83** [comment]
They seem to work fine for me. Does "EroNinja" work for you while logged in?

**Comment by iluha3w** [comment]
> They seem to work fine for me. Does "EroNinja" work for you while logged in?

No.
I also tested on different devices with different versions of android, with vpn and without vpn.
If i open a chapter before logged - the chapter works after login, but only until the list of chapters is refresh

**Comment by iluha3w** [comment]
upd2: The problem appeared on the new account. Maybe when I opened the manga page through webview.
Try it
login: Tachicheck
pass: tachi123

**Comment by iluha3w** [comment]
upd2: I caught the source of the problem. After opening the manga in webviev, the default page display mode becomes "?row", the page structure changes and the extension does not find page links.
