### ISSUE TITLE
[Source Request] <manga raw>

### ISSUE THREAD

**Issue by GreyBLANK2000** [tachiyomiorg/tachiyomi-extensions#3754]
### Source Website
- Name: manga raw
- Link: https://www.manga-raw.club
- Language(s): korean/eng

### Other Details
it has most of the new and good webtoons raw and translated versions. most webtoon.
and its fast in updating. it's good if you wanna read the new chapter that hasn't been translated yet.
and many other good webtoons which are new and not started to translate and old good webtoons which are not translated.

Thank you for your hard working ♡

**Comment by ZEXERJK** [comment]
I strongly endorse this source! 👍
