### ISSUE TITLE
[Bug] MangaPark: No Results Error

### ISSUE THREAD

**Issue by KaoticOblivion** [tachiyomiorg/tachiyomi-extensions#3848]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: MangaPark
- Extension version: 1.2.16

## Steps to reproduce
1. Download MangaPark Extension
2. Try any (and all) Chapter List sources

### Expected behavior
I could view and download mangas from extension source

### Actual behavior
I get "No Results" on 'latest' and 'browse' tabs, cannot search for manga either. 

### Other details
Webview pulls up the site just fine. Not sure why nothing lets me view manga through this extension.

**Comment by SnakeDoc83** [comment]
Chapter list preference doesn't affect what manga you see when you browse a source, it effects the chapter list when you click in to a manga.

Do you get a cloudflare page when you open webview?

**Comment by KaoticOblivion** [comment]
Yes, I followed some of the troubleshooting that I found on the reddit after posting this. I'd gotten through the cloudflare and tried resetting cookies a couple times
