### ISSUE TITLE
Add Intent to open website urls for Isekaiscans

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi-extensions#3865]
I don't Know If I Request it to The Extension Or In the App... 
It is OK if You Add... That If you share a link like this... 

https://isekaiscan.com/manga/boku-no-heya-ga-dungeon-no-kyuukeijo-ni-natteshimatta-ken/

And Press it... Is there Posibility that... Can go Directly to the App....

Another request..... 

If I were to Share A Link From Google.. And Press Share... 

Can you Add the Tachiyomi App... In the Share Button of the Google So that It Can Go directly to the App...

**Comment by CarlosEsco** [comment]
renamed.  The share a link isnt going to be added though.  An intent to open in app like mangadex is potentially possible

**Comment by Efreak** [comment]
@ImPudding-tech install an app like [Open Link With](https://github.com/tasomaniac/OpenLinkWith) ([fdroid](https://f-droid.org/packages/com.tasomaniac.openwith.floss), [play store](https://play.google.com/store/apps/details?id=com.tasomaniac.openwith)); apps like this will allow opening a shared URL. I use this app alongside Neolinker and Intent Intercept to share opened links, open shared links, edit shared links (to remove URL parameters, etc).
