### ISSUE TITLE
[Source Request] Pink Litchi Scans

### ISSUE THREAD

**Issue by superiorthirst** [tachiyomiorg/tachiyomi-extensions#3921]
- Name: Pink Litchi Scans
- Link: https://pinklitchiscans.wordpress.com
- Language(s): English (En)

**Comment by CVIUS** [comment]
the last update on site is March 2019, dunno if it still worth keeping it here

**Comment by CVIUS** [comment]
> the last update on site is March 2019, dunno if it still worth keeping it here

definitely can be closed ^
