### ISSUE TITLE
[Feature Request] Henchan: Login via extension

### ISSUE THREAD

**Issue by D3xron** [tachiyomiorg/tachiyomi-extensions#3971]
### What feature should be added to this source?
On the Henchan resource, when I try to read a certain manga, I get an HTTP error 404, and no, it's not an error resource, the administration of the site, blocks the reading because it's forbidden content (sex with loli, etc.), and to access this manga you need to register on the site, and confirm your age. Can you make a login to this site via extension?

**Comment by SnakeDoc83** [comment]
Have you tried loggin in through webview?

**Comment by D3xron** [comment]
Yes, when I login into, it start works only on Webview, not into Tachiyomi
