### ISSUE TITLE
[Bug] Kumanga: Error 400

### ISSUE THREAD

**Issue by edgarMejia** [tachiyomiorg/tachiyomi-extensions#4108]
## Device information
- Tachiyomi version: Stable 0.10.4
- Android version: 10

## Source information
- Name: Kumanga
- Extension version: 1.2.5

## Steps to reproduce
1. Browse all mangas

### Expected behavior
Get list of all mangas

### Actual behavior
Error 400

## Other details
N/A

**Comment by wuniversales** [comment]
In my case this appears...
![image](https://user-images.githubusercontent.com/48658161/98298011-9c7e5a00-1fb5-11eb-8b6e-fdc733109212.png)
