### ISSUE TITLE
[Chinese] ac.qq.com

### ISSUE THREAD

**Issue by lilli34556** [tachiyomiorg/tachiyomi-extensions#412]
http://ac.qq.com/

Source of raw Chinese web-comics, contains comics that dmzj does not have.

**Comment by as280093** [comment]
Here the icon
[ic_launcher (1).zip](https://github.com/inorichi/tachiyomi-extensions/files/3615247/ic_launcher.1.zip)

**Comment by atomicink** [comment]
Please use https://m.ac.qq.com/
