### ISSUE TITLE
[Source Request] <python3 -m http.server>

### ISSUE THREAD

**Issue by gromenauer** [tachiyomiorg/tachiyomi-extensions#4130]
**PLEASE READ THIS**

## Source Website
- Name: My own PC data exported through python
- Link: http://192.168.0.10:8000 :wink: 
- Language(s): ALL

## Other Details

Scenario 1:
* In your PC create a directory, name it `manga`
* Inside the `manga` directory create one directory per manga using the manga name:
  * `manga/Ghost_in_the_shell`
  * `manga/Doraemon`
  * ...
* Add the correspondent manga files in every directory, named to be alphabetically ordered.
  * `manga/Ghost_in_the_shell/vol_001-0.cbz`
  * `manga/Ghost_in_the_shell/vol_002-0.cbz`
  * ...
* Inside the `manga` directory execute:
``` sh
python3 -m http.server
```
* Suppose your PC IP is 192.168.0.10
* Access from your tablet from your LAN to http://192.168.0.10:8000

Scenario 2:
* The same as Scenario 1 but using a script to populate the directories as [manga-py](https://github.com/manga-py/manga-py) to download manga not available in tachiyomi-extensions

Request:
* Add a source to access this manual-made local server

**Comment by pervertkirito** [comment]
use Komga or LANraragi extension for local

**Comment by gromenauer** [comment]
Thanks for the fast response @pervertkirito !

I'm using manga-py for download, and it relies in the directory structure to know what is downloaded.
Do Komga or LANraragi change the directory structure (moves or renames the files)?
