### ISSUE TITLE
[Source Request] MangaPlex

### ISSUE THREAD

**Issue by aSimpleGuy** [tachiyomiorg/tachiyomi-extensions#4226]
### Source Website

- Name: MangaPlex

- Link: https://mangaplex.com

- Language(s): English

**Comment by pakweebly** [comment]
Please make an extension for MangaPlex

**Comment by mcOz1** [comment]
Please.

**Comment by FourTOne5** [comment]
For future reference at the moment it is impossible to make a extension from this source since it is a blogger style website. I contacted the owner/developer and he said that he is working on making the site a proper comic hosting site.
