### ISSUE TITLE
[Source Request] Dream Scans

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#4263]
### Source Website

- Name: Dream Scans

- Link: https://dreamscans.com

- Language(s): English

**Comment by AbdullahM0hamed** [comment]
None of the chapters of any manga on that site load (or attempt to load) the pages of a chapter for me

**Comment by scb261** [comment]
The site still doesn't load any images and no one said it works for them, should be closed I think?
