### ISSUE TITLE
Hatsuki Manga

### ISSUE THREAD

**Issue by Hanshee375** [tachiyomiorg/tachiyomi-extensions#4282]
## Source Website
- Name: Hatsukimanga
- Link: https://www.hatsukimanga.com
- Language(s): Spanish

**Comment by davidtuning** [comment]
It has a growing library and some of the TMO scans are moving there. If anyone is willing to working on it, I will be grateful. 
Cheers!

**Comment by Asura0818** [comment]
Hola, no pudieron agregar la extensión de HatsukiManga?

**Comment by edmxn** [comment]
Hopefully and if they add it
