### ISSUE TITLE
[Meta] An end to multi-source extensions

### ISSUE THREAD

**Issue by SnakeDoc83** [tachiyomiorg/tachiyomi-extensions#4287]
Extensions like Madara that support multiple websites have had their time but that time is coming to an end. Going forward, extensions that contain multiple sources will be split in to single-source extensions that inherit shared code from a library. For end users this means that if they want to stay up to date they'll eventually need to uninstall their multi-source extension and install individual extensions for their sources as replacements. On the upside, eventually there won't be a need to search for extensions in multiple places or update every 3-4 days because someone found a new Madara site.

For developers: don't PR any new multi-source factory extensions.  Multi-lang factory extensions (one website with multiple languages) are fine and updates to _current_ multi-source extensions are also fine.  The general process for creating these new extensions is a bit more complicated than making a factory extension.  I've commented some of my code but as I convert more extensions I'm sure I'll have to make changes to the process; so for now it'd be pointless to go in to great detail about it.  The general concept is that there's a library (`themesources`) that will contain all the common code for what used to be multi-source factory extensions; individual extensions are generated from an executable script that creates boilerplate code and default icons for new sources which can then be modified.

Extension icons: As I convert extensions the new single-source extensions will continue to use the icons from their parent multi-source extension. It's possible to give each of them their own icons but I won't be spending time on that.  If you want to submit icons keep in mind they should have rounded corners.

**Comment by arkon** [comment]
See #5672
