### ISSUE TITLE
[Source Request] <One Piece Ex>

### ISSUE THREAD

**Issue by Bruszan** [tachiyomiorg/tachiyomi-extensions#4304]
## Source Website
- Name: One Piece Ex
- Link: https://onepieceex.net/mangas/
- Language(s): Brazilian Portuguese

## Other Details
It has a great quantity of One Piece content for brazilians, from cover stories to SBS.

**Comment by joseph619** [comment]
We don't add single series sources , see if you can find the scanlator or aggregator source.

**Comment by alessandrojean** [comment]
@joseph619 They have some spin-off mangas and an authorial manga too, isn't it worth trying to add as an extension?

**Comment by Bruszan** [comment]
I also thought this, Library of Ohara has a extension too and it's very similar.

**Comment by alessandrojean** [comment]
Well, I will try to make an extension later.

**Comment by joseph619** [comment]
@alessandrojean Still not worth it if it focuses on a single series only. Unless these spinoff can't be found in other aggregator sources.

**Comment by alessandrojean** [comment]
I think only the SBS can't be found in other sources, but I have seen the other spin-offs, so maybe it's not worth then.

**Comment by Bamaraj09** [comment]
If you can give a try to https://littlexgarden.com/ that would be cool. They had all One Piece chapter in colors. They also have Kingdom, Berserk and some others in colors too

**Comment by alessandrojean** [comment]
@joseph619 Since now we have some "*Read &lt;manga-name&gt; Online*" sources that are single-manga (even if they are a `multisrc`), is it okay to add this one, or it's better to close this and follow the "policy" of not adding single-manga sources?

**Comment by joseph619** [comment]
We should be following the policy yes, the Read XX was likely an exception due to being multi-src.

**Comment by alessandrojean** [comment]
It's better to close this issue then, since it won't be added.

**Comment by arkon** [comment]
@CarlosEsco can you reiterate what the new policy is?

**Comment by CarlosEsco** [comment]
Honestly I don't really care. Now that we have multi source split we have a million extensions anyways.

**Comment by alessandrojean** [comment]
If it's not a problem, I will create the extension then.
