### ISSUE TITLE
[Bug] Mangadex: Couldnt load image/decoded

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi-extensions#4306]
## Device information
- Tachiyomi version: 0.10.4 , j2k 1.0.8
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.96

## Steps to reproduce
1. Open mangadex
2. search [hungry cat kyuu chan](https://mangadex.org/title/49720/hungry-cat-kyuu-chan-fan-comic)
3. open [chapter 87.5](https://mangadex.org/chapter/1016735)

### Expected behavior
load all image

### Actual behavior
first image couldnt load

**Comment by arkon** [comment]
Closing this since it was likely just a bad MD@H node.
