### ISSUE TITLE
Separate Portuguese languages in the Extensions page

### ISSUE THREAD

**Issue by Bruszan** [tachiyomiorg/tachiyomi-extensions#4312]
## Why/User Benefit/User Problem

Because I was confused when I downloaded Portuguese extensions and haven't found them in the Sources section.
That happened because in the Sources section the "Portuguese (Brazil)" language was turned off, it was turned off because the "Portuguese" and "Portuguese (Brazil)" are unified as "Portuguese" in the Extensions section.

## What/Requirements

Although it has a solution, separating the language between "Portuguese" and "Portuguese(Brazil)" in the Extensions section would avoid confuse situations like this.

**Comment by arkon** [comment]
This may require moving things to a locale-specific subpackage (i.e. `pt-br` or `pt_br` instead of `pt`).

I don't quite remember off the top of my head if the repo build script would handle that properly, or if the app would either though.

**Comment by arkon** [comment]
I don't particularly mind if it gets punted since it doesn't really affect me personally.

**Comment by Soitora** [comment]
/edit-title "Separate Portuguese languages in the Extensions page"
