### ISSUE TITLE
[Bug] <ShounenJump+>: <not showing chapters>

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#4323]
## Source information
- Name: ShounenJump+ jp
- Extension version: latest

## Steps to reproduce
1. Open any manga

### Expected behavior
Seeing the free available chapters to read like the website

### Actual behavior
Only showing special chapters

**Comment by alessandrojean** [comment]
I will take a look on it.

**Comment by alessandrojean** [comment]
@sohilsayed I tested now and on the titles I viewed everything is working as expected: the free and special chapters are showing. Can you provide me some titles where this happens?

**Comment by scb261** [comment]
No response from the author and also works fine for me, maybe it just was some temporary problem. If it still happens - try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) first and then open new issue with examples.
