### ISSUE TITLE
[Source Request] Blind Ferret Ent.

### ISSUE THREAD

**Issue by roshavagarga** [tachiyomiorg/tachiyomi-extensions#4330]
## Source Website
- Name: Blind Ferret Entertainment is the company that owns the rights to all of the strips below, hence the naming pattern.
- Link: [Least I Could Do](https://leasticoulddo.com/archive), [Least I Could Do: Beginnings](https://leasticoulddo.com/archive), [Looking For Group](https://www.lfg.co/archives/), [Non-Playable Character](https://www.lfg.co/npc/archives/), [Tiny Dick Adventures](https://www.lfg.co/tda/archives/)
- Language(s): English

## Other Details
- The link to LICD and LICD: Beginnings is the same. Storylines 1 through infinity are for LICD, while the `Prologue. Beginnings` storyline contains all of the current and future strips for LICD: Beginnings.
- LFG, NPC and TDA are hosted on the same website/platform.

Note:
I know that typically these should be in two separate tickets, but all of them are owned by the same company and under 2 websites which probably use the same underlying system, so hopefully this is acceptable.

**Comment by Cernunnas** [comment]
I'd love that too!!
