### ISSUE TITLE
[Bug] <Hentai Nexus>: <Images couldn't load>

### ISSUE THREAD

**Issue by Feliciafoundsmiling** [tachiyomiorg/tachiyomi-extensions#4334]
---

## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: Hentai Nexus
- Extension version: 1.2.2

## Steps to reproduce
1. Search high and low
2. Open 

### Expected behavior
Images can load

### Actual behavior
Images couldn't load and keeps retrying

**Comment by scb261** [comment]
All pages of the mentioned title are loading fine for me, try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by vaginadesolator** [comment]
I believe HentaiNexus ext has been taken down as per request by site owners #3475.

Maybe this can be closed for now until things change @arkon.
