### ISSUE TITLE
NewToki - New Chapters - No pages found

### ISSUE THREAD

**Issue by Yun-ssi** [tachiyomiorg/tachiyomi-extensions#4345]
## Device information
- Tachiyomi version: r2682
- Android version: 7.0

## Source information
- Name: NewToki
- Extension version: 1.2.13

## Steps to reproduce
1. Browse -> Sources -> NewToki (Latest) -> Choose titles -> Choose latest release -> No pages found
2. Click Globe icon -> Check current URL/Domain -> https://manatoki102.net -> Browse -> Extensions -> Override URL to current domain -> Check latest titles -> No pages found

### Expected behavior
Latest titles should be accessible.

### Actual behavior
Doesn't load images.
No pages found message pops up.

## Other details
Previous chapters are available to read.
Cleared chapter cache/cookies. No changes.
Changed IP address with VPN client. No changes.
Releases prior to September are accessible.

**Comment by scb261** [comment]
The extension is already bumped several versions (1.2.19 now) and works fine for me:
- I used 95 for override for both NewToki and ManaToki (the link you gave is down)
- ManaToki doesn't implement Latest manga, but I still was able to find new chapters (there is another request for implementing Latest #5505)
- I checked latest chapters and chapters around 10th September on both NewToki and ManaToki

Considering that extension was updated several times and works fine for me - closing. If you still have some problems with it - try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) first, and then open new issue
