### ISSUE TITLE
[Bug] Mangalib.me: Incorrect retrieve of statuses

### ISSUE THREAD

**Issue by Makishima** [tachiyomiorg/tachiyomi-extensions#4353]
The site said that manga is completed
![изображение](https://user-images.githubusercontent.com/5548003/92994887-0f63db00-f507-11ea-8eed-ca5487a79695.png)
But extensions can't get it
![изображение](https://user-images.githubusercontent.com/5548003/92994922-40441000-f507-11ea-9eec-5a795bc59edf.png)

**Comment by Riztard** [comment]
same as #4903
