### ISSUE TITLE
ManaToki - Directs unrelated image on every manga

### ISSUE THREAD

**Issue by Yun-ssi** [tachiyomiorg/tachiyomi-extensions#4401]
## Device information
- Tachiyomi version: r2688
- Android version: 7.0

## Source information
- Name: ManaToki
- Extension version: 1.2.15

## Steps to reproduce
1. Browse -> Sources -> ManaToki -> Latest -> Select any manga -> Wait for chapters to load -> Open chapter -> Shows a single image of unrelated ecchi manga.
2. Browse -> Sources -> ManaToki -> Latest -> Globe -> Directs to https://manatoki77.net (Used 102 prior to this issue) -> Back -> Open chapter -> Shows an image of unrelated ecchi manga.

### Expected behavior
Expected to see updated chapter of specific manga

### Actual behavior
Uploads one page of unrelated ecchi manga. Ecchi manga is the same for any manga/chapter.

## Other details
Cleared cookies/chapter cache/datebase.
Changed VPN/public IP address.
Overrided URL to 102. No change. Goes back to https://manatoki77.net
Was able to read yesterday (9/18/20)

**Comment by scb261** [comment]
Works fine for me, are you still getting unrelated images? Can you give an example (what manga/chapter)?

**Comment by Yun-ssi** [comment]
Yeah, it's not an issue anymore.
It fixed itself 2-3 days after I posted a request.

Thank you.
