### ISSUE TITLE
[Source Request] <comic pixiv>

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#4412]
## Source Website
- Name: comic pixiv
- Link: https://comic.pixiv.net/ https://www.pixiv.net/manga
- Language(s): japanese

## Other Details
and if possible away to read normal manga works from the normal site https://www.pixiv.net/manga

**Comment by sohilsayed** [comment]
[PixivComics.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/5824712/PixivComics.zip)
java class file from http://redsquirrel87.altervista.org/doku.php/manga-downloader

**Comment by crse** [comment]
Wait, why this is even closed? There is no Pixiv Comic extension yet...

**Comment by sohilsayed** [comment]
Sorry by mistake
