### ISSUE TITLE
[Source Request] <Japanese sources group>

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#4414]
## Source Website
- Name: tonari young jump - sai zen sen - gangan online - seiga nico - urasunday - pocket shonenmagazine - sunday webry - kuragebunch
- Link: https://tonarinoyj.jp/ - https://sai-zen-sen.jp/comics/twi4/ -https://www.ganganonline.com/ - https://seiga.nicovideo.jp/ - https://urasunday.com/ - https://pocket.shonenmagazine.com/ - https://www.sunday-webry.com/ - https://kuragebunch.com/
- Language(s): japanese

## Other Details
A group of japanese oficcial sources beacuse there isnt a lot of oficcial sources in the app and there isnt that many japanese sources

**Comment by alessandrojean** [comment]
Some of these sources are already added as extensions. It would be better for the organization of the issues if you open an individual ticket for the websites you still want to be added.
