### ISSUE TITLE
Funbe

### ISSUE THREAD

**Issue by kuroBi99** [tachiyomiorg/tachiyomi-extensions#4422]
---

## Source Website
- Name: funbe
- Link: https://funbe.rest/%EB%AC%B4%EB%A3%8C%EC%9B%B9%ED%88%B0
- Language(s): korean

## Other Details
?

**Comment by Soitora** [comment]
Also exists under the `.works` TLD.

**Comment by alekc** [comment]
Botoh domains are down for me? Probably safe to close this one
