### ISSUE TITLE
[Bug] MangaFreak: Filter Bug

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi-extensions#4453]
The Filter In MangaFreak Have A Bug Because... It Wont Show The Genres... And Please Add More Filter Settings... 

![Screenshot_20200928_183249_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/65703094/94422111-2538f780-01b9-11eb-8767-0df8aa115213.jpg)

**Comment by scb261** [comment]
Duplicate of tachiyomiorg/tachiyomi#4455
