### ISSUE TITLE
[Source Request] <gekkou scan>

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#4458]
Source Website
- Name: gekkou scan
- Link: http://leitor.gekkouscans.com.br/
- Language(s): Portuguese Brazil

**Comment by alessandrojean** [comment]
I will take a look and try to make an extension.

**Comment by Douglasimav** [comment]
thank you very much

**Comment by gccamara** [comment]
> I will take a look and try to make an extension.

Hi, is there an estimate on when we might have this source? Thanks in advance! :)

**Comment by alessandrojean** [comment]
No ETA. But it will probably get added when MMRCMS turns into a multisrc.

**Comment by Douglasimav** [comment]
😍
