### ISSUE TITLE
[Source Request] <Ama Scan>

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#4473]
## Source Website
- Name: Ama Scan
- Link: https://amascan.com/
- Language(s): Portuguese Brazil

**Comment by alessandrojean** [comment]
I will try to add together with #4458, but it will take a while.

**Comment by Douglasimav** [comment]
no problem, thanks for the effort.

**Comment by Douglasimav** [comment]
sorry for the question outside the topic, is the neox scan page working for you? I opened the webview and waited several minutes but it doesn't load.

**Comment by alessandrojean** [comment]
Since MMRCMS got split now, I will work on this now.
