### ISSUE TITLE
[Bug] <Baca Manga>: <unable to get manga chapters. error: end of input at character 0 of>

### ISSUE THREAD

**Issue by nizarschecter** [tachiyomiorg/tachiyomi-extensions#4500]
## Device information
- Tachiyomi version: 0.8.5
- Android version: 4.4.2

## Source information
- Name: Baca Manga
- Extension version: 1.2.1

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

## Other details
:)

**Comment by Riztard** [comment]
should be closed, the old site already dead. and the ext now being used by another site with similar name
