### ISSUE TITLE
[Bug] <madara - mangazuki.online>: <no chapters found>

### ISSUE THREAD

**Issue by karlsefinn** [tachiyomiorg/tachiyomi-extensions#4535]
## Device information
- Tachiyomi version: stable 0.10.5
- Android version: 10

## Source information
- Name: Madara (mangazuki.online)
- Extension version: 0.1.2.139

## Steps to reproduce
1. opens manga catalog
2. clicks on chosen manga

### Expected behavior
the correct behavior criteria, all the chapters found, even the current ones

### Actual behavior
the "no chapters found" message appears

## Other details
i do know why this happens and the motive is that mangazuki.online has changed it, now the domain address is kissmanga.link, but apparently there are some people who dont know about it yet and i am here just for begging please can someone change the domain😭😭😭😭😭😭😭😭

**Comment by ArzuHrpt** [comment]
Thanks for the new domain name 😊 i had already opened an issue about it about 2 weeks ago, what didn't know was the change in domain name, even though it passed my mind, i hope change in domain name can fix it

**Comment by scb261** [comment]
Was supposed to be fixed by #5709, but it wasn't. The link used in the PR uses mangabox layout. I don't know which one is actually new domain
