### ISSUE TITLE
[Bug] NineHentai: doesn't download last chapter page.

### ISSUE THREAD

**Issue by VoraciousSergal** [tachiyomiorg/tachiyomi-extensions#4537]
## Device information
- Tachiyomi version: 1.0.9
- Android version: 8.1.0

## Source information
- Name: NineHentai
- Extension version: 1.2.7.

## Steps to reproduce
Download chapter, new or old.

### Expected behavior
Downloaded as usual

### Actual behavior
Last page refuses to download and the app starts downloading next chapter

## Other details
Sometimes more than 1 page doesn't download.

**Comment by scb261** [comment]
Whoever decides to fix it: ninehentai has last page broken for most of mangas, could be a measure against scraping. Probably should just check if the last page is available, and if it doesn't - remove it from pages list.
