### ISSUE TITLE
来漫画（laimanhua)

### ISSUE THREAD

**Issue by tsunaliew** [tachiyomiorg/tachiyomi-extensions#4542]
## Source Website
- Name: 来漫画（laimanhua)
- Link: https://www.laimanhua.com/
- Language(s): 中文 (Chinese)

**Comment by vetleledaal** [comment]
Domain has no A/AAAA record, redirected to www.laimanhua666.com on dec 9 2021, which returns 502 Bad Gateway -- which seems to be a recent issue
