### ISSUE TITLE
[Bug] <manga ae>: <didn't work>

### ISSUE THREAD

**Issue by abdo698** [tachiyomiorg/tachiyomi-extensions#4546]
---

## Device information
- Tachiyomi version: ?0.10.5
- Android version: ?9.0

## Source information
- Name: ?manga ae
- Extension version: ?1.2.7

## Steps to reproduce
1. First Step didn't work
2. Second Step didn't work

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by Riztard** [comment]
works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by scb261** [comment]
Also works fine for me. Can you tell what exactly doesn't work for you?

**Comment by scb261** [comment]
The source is working fine and no response from the author - the issue should be closed
