### ISSUE TITLE
[Source Request] <Novelcool>

### ISSUE THREAD

**Issue by yury-o** [tachiyomiorg/tachiyomi-extensions#4550]
## Source Website
- Name: Novelcool
- Link: novelcool.com
- Language(s): english, spanish, Portuguese, Italian, German, French, russian

**Comment by jobobby04** [comment]
Fully light novel website

**Comment by scb261** [comment]
There is manga as well, example: https://www.novelcool.com/novel/ONE-PIECE.html

**Comment by xCrashsystemx** [comment]
working on it right now everything is working for now execpt multilanguage(SourceFactory) and I must filter out light novels.

**Comment by FaTe-code** [comment]
Requesting source as well english alone is fine need it asap
