### ISSUE TITLE
[Bug] <MangaOwl>: <Failed to Bypass CloudFare>

### ISSUE THREAD

**Issue by vanessabluellie** [tachiyomiorg/tachiyomi-extensions#4552]
## Device information
- Tachiyomi version: 1.0.9
- Android version: 8.0.0

## Source information
- Name: MangaOwl
- Extension version: 1.2.7

## Steps to reproduce
1. First Step

When I manually refresh a manga for updates that is on this source mangaowl, this shows an error: "Failed to bypass Cloudfare, here is a screenshot as well:

![20201008_124109](https://user-images.githubusercontent.com/55352222/95407398-6a50ec80-0964-11eb-82ae-14d21da86496.jpg)

### Expected behavior
This should have happened:

It should usually just update the manga as usual.

### Actual behavior
This happens instead

It doesn't update and just shows the error.

## Other details

I think it stopped working 6 or so days ago... it's my favourite source. I hope it can be fixed, thank you very much!

**Comment by buzmeg** [comment]
I logged in specifically to post this bug, but somebody beat me to it.  Yay!

I can comment that even when viewing MangaOwl on Firefox, I get the "Cloudflare" screen refreshing 4,5,6 times until it finally settles in.  You can't just "Open the website, bypass Cloudflare once, and you're good."  And it will continue to do so at odd intervals while reading.

So, this bug is probably more complicated than it appears.

**Comment by scb261** [comment]
You need to open the site in **WebView** (**not** browser) and solve captcha there. If it doesn't work in regular browser like Firefox, then the app can't do it as well. It seems that MangaOwl started to use similar cloudflare to MangaHasu, that also has this issue for a while now.

**Comment by FujoshiEnthusiast** [comment]
I also have the same problem right now, i'm so frustrateeeeeed. MangaOwl is my favorite extension🤧

**Comment by FujoshiEnthusiast** [comment]
Hiiii!!!! i just found that you just really need to finish the captcha thing and then vóila! It's fixed!

(attached screenshot, earlier about an hour or two ago I refreshed for the library updates but none came out, yet when i'm done with the issue of bypass thing, it suddenly got this updates)

![Screenshot_20201008-234346](https://user-images.githubusercontent.com/53976983/95482021-428f7200-09c0-11eb-8604-8abeef3c488b.png)

**Comment by ArzuHrpt** [comment]
It isn't actually about captcha. I have the same issue. When i try it from mangaowl extension directly i can see mangas, when i try to open webview i have no problem,  especially if i go to browser.  But when i try to do same thing specifically with a manga, it gives me the same error. When i go to the webview of the manga capcha doesn't load, no matter how long i wait but when i try to open it in browser (specific manga) it loads without a problem.

**Comment by buzmeg** [comment]
Might want to revisit this as I think MangaOwl behavior has changed.  I'm seeing much better behavior from MangaOwl both in the WebView and with Firefox straight.  Suddenly, it isn't refreshing like 6 times in a row and I'm seeing far less "Complete this CAPTCHA" garbage.

**Comment by vanessabluellie** [comment]
I authored this thread a while ago. And it seems like the extension mangaowl now has stopped working completely. Will it be possible to fix it anytime soon? Thank you!

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/98330830-d68b4280-202d-11eb-8ce6-264a0267bdbc.png)

**Comment by afterdelight** [comment]
+1 please fix mangaowl as mangakakalot and other resources have crappy quality except for mangasee, but mangaowl has a rare manga which mangasee doesnt have.

**Comment by afterdelight** [comment]
hey i. managed to fix the error by solving web chapta through webview, cheers!

**Comment by vanessabluellie** [comment]
> hey i. managed to fix the error by solving web chapta through webview, cheers!

About that, we can't do the web captcha thing if we want to use the <mangaowl> extension source on the tachiyomi app. It's really difficult to even check what manga is on the source via the app now (for previously favourited manga, it's still okay, but otherwise, nothing appears...)

**Comment by afterdelight** [comment]
just be patient and wait for about one minute, ill will load a few times then show the chaptcha box. after some time you have to do the chaptcha thingy again though

**Comment by afterdelight** [comment]
or you can use mangalife or mangaparkas as temporary alternative sources

**Comment by buzmeg** [comment]
I suspect this has more to do with MangaOwl than anything.  Some days, the captcha pops quickly.  Some days, the captcha simply won't work at all.

**Comment by arkon** [comment]
Seems to work for some users. Make sure you're using the latest version of the app, extension, and WebView.
