### ISSUE TITLE
[Bug] Mangabat: url changed to https://m.mangabat.com/hp, chapters can still be read but downloads fail.

### ISSUE THREAD

**Issue by kendire** [tachiyomiorg/tachiyomi-extensions#4557]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 11

## Source information
- Name: mangabox
- Extension version: 1.2.24

## Steps to reproduce
1. Select a chapter
2. Click download button

### Expected behavior
Chapter downloads

### Actual behavior
Returns an error

## Other details
Can still click chapter to read it, it's only download that's broken. Probably because the old URL redirects to the new one.

**Comment by shashank-p** [comment]
can you check again there is no problem in reading or in downloading

**Comment by williamyiudae** [comment]
wait mangabat now is mangabox
also i have same problem
