### ISSUE TITLE
[Bug] MangaDods: Chapters Doesn't Get Updated

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#4559]
### Device information
Tachiyomi version: 0.10.5
Android version: 10

### Source information
Name:Madara (Mangadods)
Extension version: 1.2.148

### Steps To Reproduce

1. Go to Browse Section

2. Choose MangaDods

3. Choose any manga and try to update it

### Expected behavior

It should show new chapters

### Actual behavior

It shows no chapters found

### Other details

Tried the webview and found new chapters are available

**Comment by AbdullahM0hamed** [comment]
Unable to replicate, any specific manga that you've noted this behaviour on? And have you tried to clear cache/database?

**Comment by sam7028** [comment]
It doesn't update any manga,i have cleared cache/database still problem persists.
![Screenshot-476_eu kanade tachiyomi](https://user-images.githubusercontent.com/69104545/95545283-1e14b380-0a1b-11eb-9c9a-4d243363f680.jpg)
![Screenshot_eu kanade tachiyomi](https://user-images.githubusercontent.com/69104545/95545292-21a83a80-0a1b-11eb-95a0-567157128c10.jpg)

**Comment by AbdullahM0hamed** [comment]
Strange, it loads up to 44 for me:
![Screenshot_20201009-124707_TachiyomiJ2K](https://user-images.githubusercontent.com/25087116/95579600-da777500-0a2d-11eb-9080-f4ea0a2a72fa.jpg)

**Comment by Dragoon91786** [comment]
Have you attempted to uninstall and reinstall the extension, as well as removing the comic from your library, searching for it in sources, and then readding it/seeing if it loads up the current chapters?

Have you attempted to force update the app itself by downloading and installing in place the Tachiyomi app with the latest version?

**Comment by sam7028** [comment]
i have reinstalled the extension and i removed manga from library and re-added manga still it does not update.Mangadods is down now

**Comment by Sharkalone** [comment]
I'm currently facing the same issue with "The blade of Evolution-Walking Alone in the Dungeon". Using the browser to check the site show there is no pbm with it, but accessing the manga through the home page show they've ad a captcha. Can it be the source of the pbm?
