### ISSUE TITLE
[Source Request] Work Chronicles: Work Chronicles is a light hearted web comic featuring relatable and amusing tales from the modern day office.

### ISSUE THREAD

**Issue by Noriller** [tachiyomiorg/tachiyomi-extensions#4563]
Name: Work Chronicles

Short Description:
Work Chronicles is a light hearted web comic featuring relatable and amusing tales from the modern day office.

Link:
https://workchronicles.com/

Thank you.

**Comment by AbdullahM0hamed** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/4564#issuecomment-706327670
