### ISSUE TITLE
[Source Request] CommitStrip: The blog relating the daily life of web agency developers

### ISSUE THREAD

**Issue by Noriller** [tachiyomiorg/tachiyomi-extensions#4564]
Name:
CommitStrip

Small description:
The blog relating the daily life of web agency developers

Link:
https://www.commitstrip.com/

Thank you

**Comment by AbdullahM0hamed** [comment]
Should have the source request label instead of enhancement.

**Comment by kbhasi** [comment]
Add info:

*Languages: English and French
