### ISSUE TITLE
[Source Request] <mangajb>

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#4574]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this 

## Source Website
- Name: mangajb
- Link: https://mangajb.de/
- Language(s): english

## Other Details
18 + new manhwa

**Comment by scb261** [comment]
Duplicate of #4262

**Comment by fawadkhan121** [comment]
Closed  4262

**Comment by arkon** [comment]
Creating new issues to bump them doesn't do anything other than annoy almost 100 people who get emails, you know.

**Comment by fawadkhan121** [comment]
Any updates??

**Comment by fawadkhan121** [comment]
Please update thankyou

**Comment by fawadkhan121** [comment]
Manhwa and manga chapters have stopped updating
