### ISSUE TITLE
[Bug] Mangakatana: Search Features wont work on spaces

### ISSUE THREAD

**Issue by regakun** [tachiyomiorg/tachiyomi-extensions#4610]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 9

## Source information
- Name: Mangakatana
- Extension version: 1.2.3

### Step to Reproduce
1. Open Browse
2. Open Sources > Mangakatana
3. Search some title within spaces

### Expected behavior
It should be displaying the mangas according to the search

### Actual behavior
Displaying not found

### Other Details
its work on Webview/The Website, but not on the app

**Comment by AbdullahM0hamed** [comment]
Give a specific search: I just tried `Suki to` and that worked.

**Comment by scb261** [comment]
The problem isn't spaces. Example of search from #support - *Asahinagu*. I guess it's because the site opens manga page if it's the only found manga.

**Comment by AbdullahM0hamed** [comment]
Huh. Yeah, it seems that it'd better to perform the POST requests the site performs prior to the user hitting enter - as that doesn't behave like that if there is only 1 result

**Comment by regakun** [comment]
I was tried this title " Let's Buy the Land And Cultivate in Different World "
