### ISSUE TITLE
[Bug] <MangRock.es>: <The Quintessential Quintuplets Chapter 103 isn't working >

### ISSUE THREAD

**Issue by lelluk** [tachiyomiorg/tachiyomi-extensions#4649]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 9

## Source information
- Name: MangaRock.es
- Extension version: 1.2.1

## Steps to reproduce
1. Try to read The Quintessential Quintuplets Vol.12 Chapter 103
2. Try to dowload the same chapter
3. Open it in the webview

### Expected behavior
I should read the chapter in the app 
It should have downloaded the chapter to read offline 
I should read the chapter in the webview

### Actual behavior
The chapter isn't loading
The dowload doesn't finishing 
The webview is working well

**Comment by scb261** [comment]
I can't find the manga on the site, can you send link to it?

**Comment by Arraiment** [comment]
![20210822_171402](https://user-images.githubusercontent.com/76941874/130349555-0afdacee-3757-422b-b2c5-5acdfda0352a.jpg)
Appears to be working.

**Comment by scb261** [comment]
Also works for me and no response from the author, should be closed.

P.S. If anyone wants to test it but the search doesn't work, sort by rank and scroll a little bit. Idk why, but this title doesn't show up when searching with text, and it also happens in browser.
