### ISSUE TITLE
[Source Request] <Kuman>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#4662]
## Source Website
- Name: 酷漫屋
- Link: http://m.kuman55.com/
- Language(s): China

## Other Details
Best for Reading Manhua free.
![logo (1)](https://user-images.githubusercontent.com/67690617/96737982-10c6d400-13e0-11eb-8eca-229705368a35.png)

**Comment by scb261** [comment]
Duplicate of #4541
