### ISSUE TITLE
[Bug] hitomi.la: cannot load any pages, stuck on retry

### ISSUE THREAD

**Issue by bugreportanon** [tachiyomiorg/tachiyomi-extensions#4679]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: hitomi.la
- Extension version: 1.2.3

## Steps to reproduce
1. Add the english version of 
* Akuma To, Yume No Nai Otoko. | The Demon And The Dreamless Guy. 
* Ane Succubus - Sister Succubus
* My Dear Maid
* Neet Meets Princess
* Inma no Kyoudai 
* Akumakko Shoukan Program Aku Kore | Demoness Summoning Program Ch. 1-2
* [Mizone] Shokubutsu no Sodatekata - How to raise plants
* [Mizone] Shokubutsu no Sodatekata - How to raise plants ~After~
* A Foxy Childhood Friend
* Amazoness no Shima | The Amazon Island
* Ane wa Succubus de, Yobai o Suru. | My Succubus Sister Sneaks into my Room at Night.
* Arakune no Miko | The Arachne Miko
* Ayakashi no Omotenashi | A Monster's Hospitality
* B-Chiku (decensored)
* Bake Bare!
* Bakunyuu Sphinx to Itsumo no Riddle
* DeliHeal Devil | Delivery Health Devil

to the library
2. Attempt to read chapter
3. Entire chapter is stuck on "retry" screen with no pages loading

### Expected behavior
Pages should load and chapter is readable.

### Actual behavior
Entire chapter is stuck on "retry", pages refuses to load.

## Other details
I don't know what makes these manga different but the problem seems to be escalating to more manga on the site and now many have become unable to be read.

**Comment by MercerBoi** [comment]
Ah yes, I've experienced this quite frequently as well. I should also mention, everything works fine in the browser/webview though.

**Comment by Samy-darker** [comment]
Same happens to me its just work fine on website but the manga shows retry button

**Comment by montesat** [comment]
This is happening to me as well as described above.

**Comment by Erilson** [comment]
Issue still persists.
