### ISSUE TITLE
Black Heart Team

### ISSUE THREAD

**Issue by motsouzumaki** [tachiyomiorg/tachiyomi-extensions#4691]
## Source Website
- Name: Black heart team
- Link: https://blackh-team.com/
- Language(s): arabic

## Other Details
arabic manhua site

**Comment by iRahmaniMed** [comment]
Please, someone take care about adding this extension, we waited 8 months 🙏🙏🙏

**Comment by iRahmaniMed** [comment]
@CarlosEsco 🥺🙏🙏🙏

**Comment by dmswd** [comment]
Don't mention anyone
Someone who's interested will pick it up
