### ISSUE TITLE
[Source Request] <Chuixue>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#4709]
## Source Website
- Name: ChuiXue
- Link: https://m.chuixue5.com/
- Language(s): ZH

## Other Details
I've seen some sites with same logo and same homepage pattern but they're not the same so I hope you won't be confused.

**Comment by vetleledaal** [comment]
Domain is parked according to whois, redirects to ads
Issues with site since nov 28 2021 according to wayback machine
