### ISSUE TITLE
[Source Request] <Mangazuki co>

### ISSUE THREAD

**Issue by gospodinh** [tachiyomiorg/tachiyomi-extensions#4716]
## Source Website
- Name: Mangazuki
- Link: https://mangazuki.co/
- Language(s): English (EN)

**Comment by scb261** [comment]
Same layout as this one, probably needs to add just one line of code (I'm not planning to do it, just letting know to anyone who wants to do it)
https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L266
