### ISSUE TITLE
[Source Request] <MangaSaki>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#4757]
## Source Website
- Name: MangaSaki
- Link: https://www.mangasaki.com/
- Language(s): EN

## Other Details
uploads Manhwa

**Comment by tanuukii** [comment]
Anyone pls add this extension plsss

**Comment by CVIUS** [comment]
Looks like Mangasail scrape from this site. The chatango thing/ their chatbox is also present in Mangasail. But I'm not hundred percent sure about it. Just leaving it here.

**Comment by tanuukii** [comment]
Anyone please make an extension for MangaSaki

**Comment by tanuukii** [comment]
@alessandrojean Bro can you please add this too? they update really fast

**Comment by CrepeTF** [comment]
@alessandrojean Bro can you please add this too? they update really fast

**Comment by tanuukii** [comment]
Someone please add it🥺

**Comment by vetleledaal** [comment]
Same theme as Mangasail
