### ISSUE TITLE
[Bug] JapScan: Images not loading for some chapters

### ISSUE THREAD

**Issue by ronny1982** [tachiyomiorg/tachiyomi-extensions#4759]
## Device information
- Tachiyomi version: latest
- Android version: 9

## Source information
- Name: JapScan
- Extension version: latest

## Steps to reproduce
1. Try to read [Noblesse Ch. 543](https://www.japscan.se/lecture-en-ligne/noblesse/543/) on JapScan

### Expected behavior
Should show all images of the chapter

### Actual behavior
Shows a placeholder image on all pages

**Comment by ronny1982** [comment]
Cc @RaniSargees as main contributor for JapScan

**Comment by az4521** [comment]
aw wtf they added webtoon scrambling?

someone else fix this pl0x.

**Comment by scb261** [comment]
Closing in favor of #6166
