### ISSUE TITLE
[Source Request] <MF Read Online>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#4763]
## Source Website
- Name: MF Read Online
- Link: http://mangafreereadonline.com
- Language(s): EN

## Other Details
this site's logo is same as mangahub

**Comment by as280093** [comment]
https://mangahub.io theme based

**Comment by vetleledaal** [comment]
Did not add this site in #10735 as it uses a different way to load images
It loads the first 3 images unconditionally, then tries to load page 4-100 and hides the ones with errors
