### ISSUE TITLE
[Bug] <Mangadex>: Edited chapters not being uploaded.

### ISSUE THREAD

**Issue by asorel1942** [tachiyomiorg/tachiyomi-extensions#4769]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 9

## Source information
- Name: Mangadex
- Extension version: 1.2.97

## Steps to reproduce
1. Download a newly-released chapter on Mangadex to the app
2. Uploader of that chapter releases an edited version of same chapter
3. Attempt to refresh work in question to download updates

### Expected behavior
New version of chapter is downloaded.

### Actual behavior
New version of chapter is not downloaded.

## Other details
Have already attempted manually deleting saved chapters on device and downloading chapter again.

**Comment by scb261** [comment]
I don't think there is a way to detect edited version. Try to remove chapter, clear cache and re-download the chapter

**Comment by asorel1942** [comment]
> I don't think there is a way to detect edited version. Try to remove chapter, clear cache and re-download the chapter

That worked, thanks. Shame Mangadex doesn't provide a ping when chapters are edited; maybe the app could compare the cached chapters with the source chapter when manually refreshing?

**Comment by scb261** [comment]
I don't know if Mangadex provides some info about edited chapters. I was talking about the app, I don't think there is a way for extension to tell the app about new version.

Using your idea means downloading all pages again on each update just to compare them, and that won't be added.

**Comment by arkon** [comment]
This is an unfortunate edge case of having a cache. I'd say that the benefits of caching outweighs this rare scenario though, considering there is a workaround.
