### ISSUE TITLE
[Feature Request] <MangaDex>: <Personal "Follows" filter.>

### ISSUE THREAD

**Issue by Kzitold** [tachiyomiorg/tachiyomi-extensions#4783]
Add filters for personal follows. All, reading, completed, on hold, plan to read, dropped, re-reading.

**Comment by Seishirou101** [comment]
Filters are taken directly from mangadex afaik, I don't think mangadex has these filters when searching?

**Comment by Seishirou101** [comment]
As said before, filters are just what is given in the api, you can open a new issue if mangadex provides filters for personal follows
