### ISSUE TITLE
[Bug] JapScan : blank pages instead of actual page

### ISSUE THREAD

**Issue by SiliaL** [tachiyomiorg/tachiyomi-extensions#4792]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Japscan
- Extension version: 1.2.24

## Steps to reproduce
1. Download or read a manga
2. Witness blank pages every 10-20 pages

### Expected behavior
Pages should all be correctly loaded

### Actual behavior
Some pages loads totally blank and can't be reloaded unless we clear the cache and come back to it 

## When the cache is cleared the blank pages actually loads but there are some more a few pages further, it's really random, also it has happened both on my tablet and my phone which are respectively Samsung and Xiaomi

**Comment by Angelghost** [comment]
Same issues with reading Boruto... i will try to check why it not work and fix it.

**Comment by Angelghost** [comment]
@RaniSargees  and @az4521  i saw you have already work on japscan.... any idea on this issues also ? 
What i think it take to much time to load the page some time and so when the image is extract with the above it take a white page ....

`  val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        var canvas = Canvas(bitmap)
        webView!!.draw(canvas)`

**Comment by az4521** [comment]
the code I've written for scrambled webtoons could be applied to normal manga to fix this bug, but it crashes right now. I've opened a draft pr and asked for help fixing it. once that's done I'll be able to fix this easily. #4772

**Comment by AbdullahM0hamed** [comment]
Pages are an illusion

**Comment by Krylanc3lo** [comment]
Thank you @az4521 for the potential fix, let us know if we can help by testing it or anything else

**Comment by AbdullahM0hamed** [comment]
> plz help, this fix is 90% done it just crashes for some reason idk why.

You can help him by fixing his fix😭😭😭

**Comment by ehfromvinland** [comment]
same issue on samsung j3 2016, what am I should do ?

forgive my english : I'm french

**Comment by hysse-s** [comment]
Same issue. Any update about it ?

**Comment by scb261** [comment]
Closing in favor of #6166
