### ISSUE TITLE
[Bug] hitomi.la: Images lacking webp/avif use different subdomain suffix

### ISSUE THREAD

**Issue by einstein95** [tachiyomiorg/tachiyomi-extensions#4800]
Currently this line hardcodes the image subdomain suffix to `a`, however images which have `hasavif` and `haswebp` both set to `0` instead are on `b` subdomains.
https://github.com/inorichi/tachiyomi-extensions/blob/950e2a67ebeff2c151b513a18cc1a5a248a82f4e/src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt#L286

The hashes of each file (which supplies the other parts of the url) may provide this information, however it does not appear so at a cursory glance.

Examples:
https://hitomi.la/doujinshi/revenge-hypnosis-~-1-english-1770604.html page 18
https://hitomi.la/doujinshi/isekai-kita-no-de-mahou-o-sukebe-na-koto-ni-riyou-shiyou-to-omou-english-1317567.html all pages

**Comment by scb261** [comment]
Probably this is the reason of #4679

**Comment by einstein95** [comment]
> Probably this is the reason of #4679

I went through every manga listed in that issue and all use the `b` subdomain, so yes.
