### ISSUE TITLE
[Bug] MangaPark: Loading issues while browsing MangaPark

### ISSUE THREAD

**Issue by Jaykoerner** [tachiyomiorg/tachiyomi-extensions#4803]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: MangaPark
- Extension version: 1.2.17

## Steps to reproduce
1. Open MangaPark extension
2. Filter via any option other then all time views

### Expected behavior
Thumbnails load in a timely manner

### Actual behavior
Majority of the thumbnails timeout before loading

## Other details
This also pretains to the loading of metadata and other info when trying to view a specific title, the site in webview loads in a reasonable time frame for both and probably wouldn't cause a timeout if the app was loaded in the same speed as webview.

**Comment by Jaykoerner** [comment]
I would assume that one of two things are happening at the moment causing the issues

1) the user agent for tachiyomi is being looked for and slowed by MangaPark

Or

2) A site update has happened that changed stuff just enough to b slowing down the parser but still allow it to work

This is my opinion not sure if either are correct

**Comment by ShindouMihou** [comment]
While parsing MangaPark for my Discord Bot, I noticed a change in their thumbnails, here are the results I gathered.
`Thumb: //xcdn-mpcdn.mangapark.net/11558/2/300.jpg
Thumb: //xcdn-mpcdn.mangapark.net/9156/1/300.jpg
Thumb: https://xcdn-thumb.animemark.com/W300/ed/b9/edb905c44a1b3e39796307139932b68eede914d1_25485_200_314.jpg
Thumb: https://xcdn-thumb.animemark.com/W300/4a/e0/4ae0da9e7554980c8e43662a69370c43db4f9db1_29517_200_314.jpg`

As you can tell, some thumbnails contains "HTTPS" while some don't, I wonder if this can help debug the issue.

**Comment by Jaykoerner** [comment]
I can try to help no worrys, sorry for not responding, but i dont keep
track of my emails, i was expecting a reply in github, sorry..

**Comment by Jaykoerner** [comment]
Yeah for some reason your message doesn't show on GitHub weird...
