### ISSUE TITLE
[Feature Request] <Mangalib, Remanga, Desu, Allhentai, Mangahub, Mangaclub>: <opening links for Russian sources>

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi-extensions#4805]
## What feature should be added to this source?
Please add opening links for Russian sources. These sources are the most stable and popular.
Mangalib, Remanga, Desu, Allhentai, Mangahub, Mangaclub

**Comment by vetleledaal** [comment]
All these sources are in Tachiyomi:
Mangalib
Remanga
Desu
AllHentai
Mangahub
MangaClub

**Comment by alessandrojean** [comment]
He was asking for URL intent to be added, but I will close for the sake of organization.

Please open a new feature request for each source if you still want the URL intent to be added for them.
