### ISSUE TITLE
[Bug] <Japscan (FR) extension>: <Advertising added on top>

### ISSUE THREAD

**Issue by DigiDomL** [tachiyomiorg/tachiyomi-extensions#4811]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Japscan (FR)
- Extension version: 1.2.24

## Steps to reproduce
1. Click on any chapter of the japscan extension
2. See the ads inlaid on the manga

### Expected behavior
Manga without ads

### Actual behavior
Manga with ads

###Details
For the exemple is the "L" logo (Leclerc)

![Screenshot_2020-11-07-13-04-27-005_eu kanade tachiyomi](https://user-images.githubusercontent.com/74095980/98440840-6ba83d00-20fb-11eb-8d5d-6e5f55354125.jpg)

![Screenshot_2020-11-07-13-17-09-977_com android chrome](https://user-images.githubusercontent.com/74095980/98440866-95616400-20fb-11eb-97c8-d750cbfd3508.jpg)

**Comment by Angelghost** [comment]
I think this issue is link  #4792 ... some issues with the tool to get the page correctly.

**Comment by scb261** [comment]
Closing in favor of #6166
