### ISSUE TITLE
[Feature Request] MangaDex: use API v2 

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi-extensions#4812]
See https://mangadex.org/thread/351011

**Comment by arkon** [comment]
![](https://cdn.discordapp.com/attachments/569823838305648640/775496982071869440/unknown.png)

Should probably hold off on implementing this until it's an actual stable release of the API.

**Comment by ephemient** [comment]
Seems to be done by #5337.

Although I'm encountering HTTP status 429 responses with just a fraction of a library update now, while it worked just fine with plugin versions .97 and earlier. Is the plugin now making far more API calls, or is MD accounting them very differently? @CarlosEsco
