### ISSUE TITLE
[Nitpick] Hitomi.la: Strange Searching Method

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi-extensions#4816]
## What feature should be added to this source?

Searching for an artist must be done in lowercase letters, otherwise it results in a `it must not be null` error. This is strange, considering that the artist name on the source **website** is written normally (with uppercase letters used fittingly).

I would give screenshot examples, but that would've been NSFW, but basically, "John Smith" would have to be written as "john smith" for results to show up. Just an odd anomaly I thought I should report. Whether this is worth fixing or not is up to the devs.

Also worth mentioning is that Hitomi.la doesn't have a dedicated filter option, unlike nhentai, Tsumino, etc. for reasons I am unaware of. Adding one would simplify specialized searches, I think.

**Comment by Samy-darker** [comment]
Agree.
