### ISSUE TITLE
[Bug] Mangabox: Only loads first page. 

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi-extensions#4824]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Mangabox (Mangakakalot and others)
- Extension version: 1.2.24

## Steps to reproduce
1. Open any manga.

### Expected behavior
Loads every page. 

### Actual behavior
This happens instead
![Screenshot_20201109-010933](https://user-images.githubusercontent.com/49813589/98471580-45cc8680-2228-11eb-9fae-72f2b92986cd.jpg)

**Comment by scb261** [comment]
Works for me
1. Have you tried [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)?
2. What source/manga/chapter has this problem?

**Comment by scb261** [comment]
No response from the author, probably the same as #4337 - it was temporary issue on the site
