### ISSUE TITLE
[Bug] Emerald : Some bugs

### ISSUE THREAD

**Issue by borkwoof** [tachiyomiorg/tachiyomi-extensions#4836]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Emerald
- Extension version: 1.2.4

## Steps to reproduce
Problem 1
1. Open any titles in bato, for example The Justice of A Villainous Woman (http://bato.to/series/72466)
2. Click at first chapter, it can load in webview, but can't load in tachi app
3. Click at latest chapter, it can load in both webview and tachi app

Problem 2
1. Search any title in browse under bato source

### Expected behavior
Problem 1
- All images should load in tachi app

Problem 2
- Covers should be shown
- Each language only appears based on their language setting

### Actual behavior
Problem 1
- Image doesn't load (reply button refuses to load the images) in tachi app
- This problem happens sporadic/odd, means not all titles will get this result or in one chapter only some images doesn't load or it could happen at (relatively) new-upload-date chapters

Problem 2
- Some covers don't appear when browsing
- Other languages mix in another language setting

## Other details
- I have done troubleshoot, login at webview, clear cache/cookies (ofc I login again), close app and open it again. These don't work.

**Comment by Riztard** [comment]
for problem 2 -Covers should be shown
its always show all cover for me if i try use vpn

**Comment by jadoff630** [comment]
I noticed this too. A few days ago, chapters from a few years ago (things dated 2017 and maybe 2018) wouldn't load (the screen is black with blue retry text). Then there was an update for emerald the other day and those old chapters load, and chapters uploaded during the last week do as well, but things between the two dates don't (except for a few random exceptions that do)...

**Comment by AriaMoradi** [comment]
> I noticed this too. A few days ago, chapters from a few years ago (things dated 2017 and maybe 2018) wouldn't load (the screen is black with blue retry text). Then there was an update for emerald the other day and those old chapters load, and chapters uploaded during the last week do as well, but things between the two dates don't (except for a few random exceptions that do)...

provide links so we can test

**Comment by jadoff630** [comment]
> > I noticed this too. A few days ago, chapters from a few years ago (things dated 2017 and maybe 2018) wouldn't load (the screen is black with blue retry text). Then there was an update for emerald the other day and those old chapters load, and chapters uploaded during the last week do as well, but things between the two dates don't (except for a few random exceptions that do)...
> 
> provide links to those mangas so we can test

I saw that a lot of the manga that were having issues have been fixed, but here are a few more that still have this odd issue... 

- https://bato.to/series/10721. Chapter 1 gives the retry message (for some reason pages 4-7 load). Full chapter loads in webview. 
- https://bato.to/series/79942. Chapter 1 also doesn't load and gives retry message.

**Comment by jadoff630** [comment]
Also, in terms of problem 2 from the original post, I have seen that some manga have issues loading covers too, and they will show a broken image link. Sometimes if you open the manga it will make the image load (kindof randomly occurs so not sure how to give an example, currently this is one that it happens to that does not load even upon opening https://bato.to/series/79126). Also, the original post also mentioned that languages mix in. I only have English turned on in emerald settings, but it will show all the others. For instance, if I search for "A Villainess for a tyrant" the first result is the French one (has no chapters) and the second is the English... A related bug is that after those two results, it shows 18 partial matches to my search, and then continues to repeat all the results again and again.

**Comment by AriaMoradi** [comment]
> I saw that a lot of the manga that were having issues have been fixed, but here are a few more that still have this odd issue...
> 
> * https://bato.to/series/10721. Chapter 1 gives the retry message (for some reason pages 4-7 load). Full chapter loads in webview.
> * https://bato.to/series/79942. Chapter 1 also doesn't load and gives retry message.

both work for me, no errors

**Comment by AriaMoradi** [comment]
> Also, in terms of problem 2 from the original post, I have seen that some manga have issues loading covers too, and they will show a broken image link. Sometimes if you open the manga it will make the image load (kindof randomly occurs so not sure how to give an example, currently this is one that it happens to that does not load even upon opening https://bato.to/series/79126). Also, the original post also mentioned that languages mix in. I only have English turned on in emerald settings, but it will show all the others. For instance, if I search for "A Villainess for a tyrant" the first result is the French one (has no chapters) and the second is the English... A related bug is that after those two results, it shows 18 partial matches to my search, and then continues to repeat all the results again and again.

I think this is how the site works, they don't do search filter based on lang, and lang filter in latest and popular works internally with your account, noting we can do from tachi.(there might be some hidden functionality that I can't find...)

**Comment by jadoff630** [comment]
> > I saw that a lot of the manga that were having issues have been fixed, but here are a few more that still have this odd issue...
> > 
> > * https://bato.to/series/10721. Chapter 1 gives the retry message (for some reason pages 4-7 load). Full chapter loads in webview.
> > * https://bato.to/series/79942. Chapter 1 also doesn't load and gives retry message.
> 
> both work for me, no errors

Ignore me! I restarted my phone and tried again and they do work.

**Comment by jadoff630** [comment]
> > Also, in terms of problem 2 from the original post, I have seen that some manga have issues loading covers too, and they will show a broken image link. Sometimes if you open the manga it will make the image load (kindof randomly occurs so not sure how to give an example, currently this is one that it happens to that does not load even upon opening https://bato.to/series/79126). Also, the original post also mentioned that languages mix in. I only have English turned on in emerald settings, but it will show all the others. For instance, if I search for "A Villainess for a tyrant" the first result is the French one (has no chapters) and the second is the English... A related bug is that after those two results, it shows 18 partial matches to my search, and then continues to repeat all the results again and again.
> 
> I think this is how the site works, they don't do search filter based on lang, and lang filter in latest and popular works internally with your account, noting we can do from tachi.(there might be some hidden functionality that I can't find...)

That makes sense in terms of lang. filters... How about the endless loop of repeating results?

**Comment by AriaMoradi** [comment]
> That makes sense in terms of lang. filters... How about the endless loop of repeating results?

example?

**Comment by jadoff630** [comment]
Here is a screencast video showing the loop of results. 
https://vimeo.com/478642022

Also here is a screenshot of an example of broken image covers.
![Screenshot_20201112-141123_TachiyomiSY](https://user-images.githubusercontent.com/25085973/98991596-ad692700-24f1-11eb-832d-5cbfc77b15fa.jpg)

**Comment by Riztard** [comment]
do [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) it work fine for me, not even single broken cover image

**Comment by jadoff630** [comment]
> do [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) it work fine for me, not even single broken cover image
> *maybe More → Settings → Advanced Refresh → library manga covers too

Thanks! troubleshooting steps solved the cover issues! I think the only bug left from the the original bugs is the search issues with repeating results (see video link)

**Comment by Riztard** [comment]
@jadoff630 maybe create new issue instead of buried here and adding more

**Comment by jadoff630** [comment]
> @jadoff630 maybe create new issue instead of buried here and adding more

Will do!

**Comment by CarlosEsco** [comment]
closing as #5090  and #4882  seem to be the current issues
