### ISSUE TITLE
[Bug] <Zahard: <Chapter List Doesn't Load>

### ISSUE THREAD

**Issue by sshawnsamuell** [tachiyomiorg/tachiyomi-extensions#4845]
#657  Device information
- Tachiyomi version: 10.5
- Android version: 10 

## Source information
- Name: Zahard
- Extension version: 1.2.2

##  Details 
Updated to 1.2.2, series are all showing up, but chapters do not pull up. Gives error, "For Input String: Chapter ##" " (## being whatever the latest chapter for that series is)
![Screenshot_20201111-130526](https://user-images.githubusercontent.com/1341030/98853272-dbce0000-2426-11eb-98af-7809f0539a20.jpg)

**Comment by scb261** [comment]
Was fixed by #4850 and later moved to a factory extension due to site theme change #5089
