### ISSUE TITLE
[Bug] Emerald: Search results errors

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi-extensions#4882]
## Device information
- Tachiyomi version: Preview r306 (6e8ac9cc1)
- Android version: 10

## Source information
- Name: Emerald
- Extension version: 1.2.7

## Steps to reproduce
1. Open Bato.to 
2. Search for a title
- error seems to have occurred after updating to latest Emerald version which corrected #4872 where search results were duplicated in loop

### Expected behavior
Should show titles 

### Actual behavior
Either shows a full screen error message of no results found (screenshots 2-4) or shows some partial results (not including a title that is clearly in bato.to's library) and a popup at bottom of the screen saying no results found (screenshot 5)

## Other details
Screenshots: 

1. Browse screen for reference of titles that are indeed in bato.to's library
![bato browse](https://user-images.githubusercontent.com/25085973/99158437-66696600-2698-11eb-860d-17cfacb28a47.jpg)

2-4. Various full screen error messages for titles
![abe-kun](https://user-images.githubusercontent.com/25085973/99158441-6c5f4700-2698-11eb-9b8d-5dbe5a0933d5.jpg)
![positively yours](https://user-images.githubusercontent.com/25085973/99158442-6ec1a100-2698-11eb-8bb6-744b4e5ea75d.jpg)
![under the oak tree](https://user-images.githubusercontent.com/25085973/99158444-72552800-2698-11eb-9299-03ee2b0f8c93.jpg)

5 partial results error message missing title that is in browse screen
![abe-kun partial](https://user-images.githubusercontent.com/25085973/99158445-75e8af00-2698-11eb-9a1c-0ec2664b1084.jpg)

**Comment by vipzzx** [comment]
I am having the same issue. i have to physically look through lastest to add the ones i cant search
