### ISSUE TITLE
[Bug] <Error displaying manga status.>: <All manga in the MangaLib catalog has the status "Unknown".>

### ISSUE THREAD

**Issue by PythonLog** [tachiyomiorg/tachiyomi-extensions#4903]
## Device information
- Tachiyomi version: 0.10.5
- Android version:  8.1 (Oreo)

## Source information
- Name: MangaLib (Русский)
- Extension version: 1.2.23

I prefer to read the manga in the MangaLib catalog, however I ran into an exit status issue. Instead of "Completed" or "Ongoing" is written "Unknown status".

Я предпочитаю читать мангу в каталоге MangaLib, однако столкнулся с проблемой статуса выхода. Вместо "Выпускается" или "Выпущено" пишется "Неизвестно".

**Comment by Riztard** [comment]
should be closed

**Comment by Makishima** [comment]
Not resolved for some mangas

<details>
<summary>Screenshots</summary>

![photo_2021-01-18_16-37-19](https://user-images.githubusercontent.com/5548003/104922229-790b5e80-59ab-11eb-9861-261a78867cdc.jpg)
![photo_2021-01-18_16-37-23](https://user-images.githubusercontent.com/5548003/104922217-77da3180-59ab-11eb-8799-ec1acfb75182.jpg)
![photo_2021-01-18_16-37-22](https://user-images.githubusercontent.com/5548003/104922220-7872c800-59ab-11eb-9857-0d68be2484f2.jpg)
![photo_2021-01-18_16-37-21](https://user-images.githubusercontent.com/5548003/104922223-790b5e80-59ab-11eb-9636-df9628eeb825.jpg)


</details>
