### ISSUE TITLE
[Source Request] <Manga Mitsu>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#4939]
## Source Website
- Name: Manga Mitsu
- Link: https://mangamitsu.com/
- Language(s): EN

## Other Details
uploads manhua manhwa manga.

**Comment by CrepeTF** [comment]
Madara theme :Harold:

**Comment by CrepeTF** [comment]
I doubt we need another generic Madara source, and I also doubt this particular Madara aggregate source is any special
