### ISSUE TITLE
[Bug] Golden Mangás: cloudfare infinite loop

### ISSUE THREAD

**Issue by Sam-Oak** [tachiyomiorg/tachiyomi-extensions#4958]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 9 Pie

## Source information
- Name: Golden Mangás
- Extension version: 1.2.8

## Steps to reproduce
1. Open Golden Mangás in Browse

### Expected behavior
Show all manga from this source.

### Actual behavior
"java.lang.Exception: Falha ao contornar o Cloudfare". and when opening in webview, it gets stuck on the cloudfare screen

## Other details
![image](https://user-images.githubusercontent.com/62823895/100379612-eb874000-2ff3-11eb-949e-4871acb2c1b1.png)

**Comment by scb261** [comment]
Sources with the same problem #4552 #4804

**Comment by arkon** [comment]
Have you updated WebView too?

**Comment by joao917** [comment]
I'm going through the same thing in 3 extensions, I already opened it in the webview and it is in a loop

**Comment by Sam-Oak** [comment]
everything is updated. these days i saw some people in the tachiyomi discord with this same problem

**Comment by alessandrojean** [comment]
It's an issue with the site, I already tried to fix it but nothing can be done on the extension side.

I can only suggest waiting a while and see if the site fixes itself or migrate to another source.
