### ISSUE TITLE
[Bug] bato.to: You can only search once

### ISSUE THREAD

**Issue by DieSmilePN** [tachiyomiorg/tachiyomi-extensions#5015]
## Device information
* Tachiyomi version: v0.10.5 (standard, 2769e27a2, 51)
* Android version: 10 (SDK 29)

## Source information
* Source name: bato.to (Emerald)
* Source extension version: v1.2.7

## Issue/Request
Everything I search can only be searched **once**.
Im really not sure whats happening, ive tried uninstalling and install Emerald but still didn't fix it.
While you guys at it. Please fix the **Filter**. Its literally not working 

 
![Screenshot_20201204-222850_Tachiyomi](https://user-images.githubusercontent.com/68656846/101175627-5aae0580-3680-11eb-85dd-bb188cb49ba5.png)
![Screenshot_20201204-222905_Tachiyomi](https://user-images.githubusercontent.com/68656846/101175658-64376d80-3680-11eb-8859-c83a33c4a86b.png)
![Screenshot_20201204-222918_Tachiyomi](https://user-images.githubusercontent.com/68656846/101175677-6994b800-3680-11eb-9532-611bbff59c6f.png)
![Screenshot_20201204-222935_Tachiyomi](https://user-images.githubusercontent.com/68656846/101175866-acef2680-3680-11eb-8097-1413c6a3edd4.png)
![Screenshot_20201204-222945_Tachiyomi](https://user-images.githubusercontent.com/68656846/101175888-b4163480-3680-11eb-828b-84a9167ca27a.png)
![Screenshot_20201204-223000_Tachiyomi](https://user-images.githubusercontent.com/68656846/101176029-e162e280-3680-11eb-94de-7d47d7cfc6a2.png)
![Screenshot_20201204-223011_Tachiyomi](https://user-images.githubusercontent.com/68656846/101176059-ed4ea480-3680-11eb-8b9f-4fb1b4592914.png)
![Screenshot_20201204-223021_Tachiyomi](https://user-images.githubusercontent.com/68656846/101176062-f0499500-3680-11eb-88a1-24a7db367cbb.png)

**Comment by jadoff630** [comment]
I noticed that this was happening too, but I cleared cache and other troubleshooting steps and it fixed it

**Comment by DieSmilePN** [comment]
> I noticed that this was happening too, but I cleared cache and other troubleshooting steps and it fixed it

Not sure if only on my device this happen. But some other extensions work perfectly fine.

**Comment by DieSmilePN** [comment]
Heyyy I found out when I close the app, I can search the same title again. Yeah it fixed but it can only search **once** again, so it only work everytime I close the app to search. 

If someone have some clues whats going please let me know how to fix it.

**Comment by DieSmilePN** [comment]
Heyy I found out whenever I close the tachiyomi app I can search the same title again. Yeah it fixed it but it can only search **once** again, so I need to close the app whenever I need to search again.

If someone got a clue what's goin on here, please let me know to fix it.

**Comment by AbdullahM0hamed** [comment]
It's actually very confusing, looking at the response the app gets when the requist that returns "no results", the html both contains manga, and conforms to the structure  that is expected by the css selectors.

**Comment by CarlosEsco** [comment]
#4882 basically covers this
