### ISSUE TITLE
INKR

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi-extensions#5025]
---

## Source Website: INKR.com
- Name: INKR Comics
- Link: https://play.google.com/store/apps/details?id=com.inkr.comics
- Language(s): English prolly

## Other Details
has Yaoi guys, come on

**Comment by AriaMoradi** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3688

**Comment by CrepeTF** [comment]
Reopen this issue, they added on-website reading functionality

**Example:**
https://inkr.com/ik-title-412

<img width="1440" alt="Screenshot 2020-12-28 at 23 13 38" src="https://user-images.githubusercontent.com/70870719/103248384-549b0400-4962-11eb-8762-f9dcf072c785.png">

**Comment by CrepeTF** [comment]
It may be a preview, but technically you can read on-site

**Comment by CrepeTF** [comment]
Long live KINKR
