### ISSUE TITLE
[Bug] <Comic FX>: <Search Doesn't Work>

### ISSUE THREAD

**Issue by HaruSasaki** [tachiyomiorg/tachiyomi-extensions#5047]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 8.1

## Source information
- Name: Comic FX
- Extension version: 1.2.1

### Expected behavior
Shown result of search.

### Actual behavior
Nothing happens.

### Other details
https://youtu.be/SBnhZavBknw

**Comment by Riztard** [comment]
it can be done by using this link url to search, 
then select the value as manga title, 
and data as manga link by adding url in front of data value "https://comicfx.net/komik/the-nine-heaven-of-martial-art"
something like this maybe $baseurl/komik/$dataValue
![Clipboarder 2020 12 07-003](https://user-images.githubusercontent.com/16263232/101359102-63941680-38ce-11eb-85c6-5df19e4fe721.png)
but i dont know how LOL
