### ISSUE TITLE
[Bug] Emerald (Bato.to): Sometimes the pages don't load, it just shows retry. 

### ISSUE THREAD

**Issue by Xeiniac** [tachiyomiorg/tachiyomi-extensions#5090]
## Device information
- Tachiyomi version: TachiyomiSY Preview r313 (f1a6218a4)
- Android version: Android 8.1

## Source information
- Name: Emerald
- Extension version: 1.2.7

## Steps to reproduce
1. Open up a series, in this case it was Valentine Kiss (The english version) but it's happened to me for other series too
2. Open up a chapter, in this case it happened in the middle of chapter 42 but it also happened in chapter 37 and 36

### Expected behavior
Page loads without any issues

### Actual behavior
This happens instead
Page doesn't load and shows retry, after clicking retry it just shows it again
## Other details
It also happened to me on TachiyomiJ2K. 
I looked at the pages that didn't load in webview and they loaded perfectly fine, however they still didn't load on the app.

**Comment by AriaMoradi** [comment]
Can't reproduce this.
It must have been a network error or you are not on tgr latest version of the extention

**Comment by jadoff630** [comment]
I have had this happen. Going through troubleshooting steps (clear database, history, cache) and restarting the app clear it up.

**Comment by scb261** [comment]
There were various fixes and changes for bato.to since then (it now has separate extension that already has version 1.2.4) and it also works fine for me. If you still have problems with it - please open new issue
