### ISSUE TITLE
[Source Request] <Mangadig>

### ISSUE THREAD

**Issue by davidtuning** [tachiyomiorg/tachiyomi-extensions#5113]
It will be nice if this one can be add. 
## Source Website
- Name: Mangadig 
- Link: https://mangadig.com/
- Language(s): en

Thanks and happy holidays!

**Comment by HaruSasaki** [comment]
If look at the interface, i thought this website is using the same theme as CoCoManhua.

**Comment by davidtuning** [comment]
> If look at the interface, i thought this website is using the same theme as CoCoManhua.

So there's no hope for adding it to any addon?

**Comment by JustMe2277** [comment]
Hope these people will kind enough to see & recheck this again,  if it can be make as an  extension.

Thank you.

**Comment by hyoretsu** [comment]
Re-bumping this, some aggregator stole chapters from here and it seems I've finally found the only site that has all chapters of Boy in A Girl's High School. (If it really can't be added, just close the issue)

**Comment by alessandrojean** [comment]
Don't keep bumping issues. This is an open source project, it will get added when someone have time and wants to work on it, no ETA.

**Comment by hyoretsu** [comment]
It's just a matter of words. I was about to open a new issue to request this source, which'd then be closed in favor of this one, essentially bumping it. Nor was I hurrying for an ETA or something, but it was never disclosed if it's actually possible/"planned" or not, seeing how it's been open for 8 months.

**Comment by alessandrojean** [comment]
> but it was never disclosed if it's actually possible/"planned" or not

Clarifying this part, if the issue is still opened it means it's possible to add it as a source, but no one did it yet.
