### ISSUE TITLE
[Bug] <Tapas>: <Missing majority of chapters>

### ISSUE THREAD

**Issue by vanessabluellie** [tachiyomiorg/tachiyomi-extensions#5127]
## Device information
- Tachiyomi version: TachiJ2K 1.0.1p
- Android version: 8.0.0

## Source information
- Name: Tapas
- Extension version: 1.2.10

## Steps to reproduce
1. First Step
A lot of manga on this source Tapas can be read for free and don't need to be unlocked via Tapas ink. But on tachiyomi, every manga on the source in the app are missing! There's less than 10 chapters for essentially every manga. Could the extension be fixed and updated to contain every correct chapter please? Thanks so much! Love it. 

### Expected behavior
This should have happened
It should contain every chapter directly from the original Tapas app :D. 

### Actual behavior
This happens instead
Only less than 10 chapters appear for each manga in tapas extension on the tachij2k app.

## Other details
Hope that it can fixed at your earliest convenience! Thank you again!

**Comment by scb261** [comment]
Are you saying that free chapters are missing? Can you give example?

**Comment by alexporth** [comment]
This happens when you don't log into tapas through the web view. The locked chapters are not displayed in tachiyomi.
