### ISSUE TITLE
[Feature Request] <MangaKatana>: <Add Filter in Latest>

### ISSUE THREAD

**Issue by bungadrum** [tachiyomiorg/tachiyomi-extensions#5128]
## What feature should be added to this source?
Can you please add a Include/Exclude Filter in Latest on the site there is a option for Genre and Status, but on the source there is nothing at all. It is impossible to search anything by genre all you can do is type title of the Manga. If that isn't a option could you add a URL box you can adjust things on the site and just paste it in the Source. Maybe add a Save and Clear button so that you don't have to adjust it every time you open the source.

This is how it looks: like https://snipboard.io/MXwtIB.jpg  plz add if possible

**Comment by MercerBoi** [comment]
Bump.
