### ISSUE TITLE
[new extension] <nhentai.com>

### ISSUE THREAD

**Issue by QP-web** [tachiyomiorg/tachiyomi-extensions#5132]
## Source Website
- Name: nhentai.com
- Link: https://nhentai.com/en/comic/kizuitara-itsunomanika-kimobuta-otoko-no-ochinpo-ana-ni-tsukurikaerarete-ita-onnanoko-no-ohanashi-kedakaki-onna-ninja-no-matsuro-hen
- Language(s): N/A

## Other Details
?

**Comment by AriaMoradi** [comment]
This is the exact same codebase as https://readmanhwa.com/
We have another multi-source extension coming along...

**Comment by CrepeTF** [comment]
:meguu: why have a nhentai clone when you can use original

**Comment by QP-web** [comment]
It doesn't have any of the dojins from the artist I like (hinjyaku) neither of those sites do except this one

**Comment by QP-web** [comment]
What is this?????

**Comment by jobobby04** [comment]
It means progress on the extension, you dont really need to worry about it, the issue will be closed when the extension is added, so just wait for that

**Comment by QP-web** [comment]
Kk
