### ISSUE TITLE
Manga covers don't load - Union Mangás font

### ISSUE THREAD

**Issue by muriloepiphanio** [tachiyomiorg/tachiyomi-extensions#5142]
Some manga covers do not carry. Recently, the site of the Union Mangás source had part of its collection deleted. In this way, the Union Mangás source is experiencing slow loading problems.

**Comment by alessandrojean** [comment]
The extension acts like a fancy browser and just fetches the contents from the website. 

If the site itself is slow, there's nothing that can be done on the extension side.

A disclaimer from the Discord support channel:

> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

About the covers not loading, can you give some examples where this occurs? 

Did you check if they are not loading on the site too?

**Comment by scb261** [comment]
A lot of covers were missing for me too, but I fixed it with Brazil VPN. Some covers still were missing, but they were missing in WebView as well. Not an extension issue, closing
