### ISSUE TITLE
[Source Request] <Tkor>

### ISSUE THREAD

**Issue by vanessabluellie** [tachiyomiorg/tachiyomi-extensions#5150]
## Source Website
- Name: Tkor
- Link: https://tkor.fans/%EB%AC%B4%EB%A3%8C%EC%9B%B9%ED%88%B0
- Language(s): Korean

## Other Details
To protect the website, the proxy changes quite often. Its tkor.fans right now, but before it was tkor.asia. 
Hope this can be on Tachiyomi sometime soon! Love you all for the greatest app ahah~!

**Comment by Arekkusu1998** [comment]
**@vanessabluellie**, I downloaded Tachiyomi app yesterday on my Android Simulator «BlueStacks 4.2» and I enabled the Extensions in _English_, _Italian_ (my native language), _Japanese_ and _Korean_. At the end of the list, I find the ones in Korean that the developers have already entered: as you can see from the image below, 
Tookor is there.
![Immagine](https://user-images.githubusercontent.com/48092608/102641567-935bdd80-415c-11eb-9491-171174801b42.png)

**Comment by vanessabluellie** [comment]
Thank you very much @Arekkusu1998. For also mentioning that android simulator, it's amazing~! Issue closed :D
