### ISSUE TITLE
[Source Request] <Cocomanhua>

### ISSUE THREAD

**Issue by vanessabluellie** [tachiyomiorg/tachiyomi-extensions#5151]
## Source Website
- Name: Cocomanhua
- Link: https://www.cocomanhua.com/
- Language(s): Chinese

## Other Details
There's a lot of Chinese manhua on this website and I don't think it has cloudflare protection. I hope this website is considered since it has the biggest Chinese manhua collection! Thank you so so much~!!

**Comment by HaruSasaki** [comment]
I think this extension already exists. Extension name is CoCoManhua (OhManhua). If you can't find this extension, try to enable chinese in language filter.

**Comment by vanessabluellie** [comment]
Thank you so so so very much, HaruSasaki! I completely forgot about the language filter cos I've only had the English filter on default ㅠㅠ! I see it now so thanks again! 😊🙆✨

**Comment by Riztard** [comment]
then you can close this
