### ISSUE TITLE
[Source Request] <tappytoon>

### ISSUE THREAD

**Issue by Osama-Ezz** [tachiyomiorg/tachiyomi-extensions#5164]
It will be nice if this one can be added.

## Source Website
- Name: Tappytoon
- Link: https://www.tappytoon.com/en/
- Language(s): EN

**Comment by CarlosEsco** [comment]
read the description next time.

#1342

**Comment by Arekkusu1998** [comment]
And how is that supposed to help, sorry **@CarlosEsco**?
What should the zip folder do for us? It's written [here](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/4764) that they're for the source request, not for us.

**Comment by CarlosEsco** [comment]
From the description text see the bold part i just added  
- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application
  - In the multi-source spreadsheet: https://tachiyomi.org/extensions
  - By searching the GitHub repository for the extension and verify it does not appear in the code base
- **I have searched the existing GitHub issues and this extension does **NOT** have an open request**

**Comment by Arekkusu1998** [comment]
You're fully right, **@CarlosEsco**, but then it means request #1342 wasn't resolved, don't? 
TappyToon wasn't added to Extensions.

In any case, I also reiterated my request there with some important specification.

**Comment by arkon** [comment]
Making duplicate requests does not achieve anything.

**Comment by Arekkusu1998** [comment]
@arkon, please, read what I wrote in #1342: it's not a duplicate. I assure.

**Comment by arkon** [comment]
Are you arguing that a source request opened for the same website is in fact not a duplicate?

It's good that you added your input to the original issue. There's no use in creating more issues.

**Comment by Osama-Ezz** [comment]
> read the description next time.
> 
> #1342

    What can i do Other than that to help.

**Comment by AriaMoradi** [comment]
> What can i do Other than that to help.

Learn programming, make the extension yourself.
Or pay someone to do it for you.
