### ISSUE TITLE
[Source Request] <HomeStuck>

### ISSUE THREAD

**Issue by SeonTheCoder** [tachiyomiorg/tachiyomi-extensions#5166]
## Source Website
- Name: Home Stuck
- Link: https://www.homestuck.com/story
- Language(s): English

## Other Details
This webcomic's creator is Andrew Hussie, and the webcomic go from the year of 2009 to 2016.

**Comment by AriaMoradi** [comment]
This is a interactive comic. Not possible to make a extension for.
