### ISSUE TITLE
[Source Request] <[Korean] Toomics>

### ISSUE THREAD

**Issue by Arekkusu1998** [tachiyomiorg/tachiyomi-extensions#5167]
## Source Website
- Name: Toomics
- Link: https://www.toomics.com/
- Language(s): Korean

**Comment by arkon** [comment]
Are you saying that it doesn't show your paid chapters or you want it to bypass the payment requirement?

**Comment by Arekkusu1998** [comment]
Obviously to bypass the payment requirement: I don't have money to buy the chapters of a manhwa that interests me, so I was hoping for a solution. However I've read that what's **impossible**. Read here: tachiyomiorg/tachiyomi#4149.
