### ISSUE TITLE
[Enhancement] <Mangaowl>: <Version 1.2.8, Even after bypassing cloudfare, no Matter what you search in the browse section the results are always the same it's not the right one.>

### ISSUE THREAD

**Issue by Nyx-o12** [tachiyomiorg/tachiyomi-extensions#5168]
## Device information
- Tachiyomi version: 0.10.6
- Android version: 8.1.0

## Source information
- Name: Mangaowl
- Extension version: 1.2.8

## Steps to reproduce
1. Manually bypass cloudfare in mangaowl
2. Search a title in the browse section and scroll to mangaowl section 

### Expected behavior
The manga with matching title search should appear

### Actual behavior
The wrong mangas appear 

## Other details
The updates works but searching new titles doesn't because of the aforementioned issue #

**Comment by scb261** [comment]
Works right for me - the result is matching result in browser and different searches return different results. Can you check if the search you're trying returns different results in the WebView or a browser?

**Comment by Nyx-o12** [comment]
It works just fine both in my browsers and in the Webview. It doesn't work
however when I'm on tachiyomi's browse section. The Same mangas always
appear even though it's not what I  searched. The first two pictures are
from the browse section of tachiyomi, one only showing mangaowl. The other
two are from my chrome and Webview and they're fine.

**Comment by scb261** [comment]
I think the pictures weren't sent here when you replied via email, try to use github to send them

**Comment by Nyx-o12** [comment]
I wanted to send the photo on github when I reported the bug but I can't,
or I don't know how.

**Comment by Nyx-o12** [comment]
![Screenshot_20201218_112059](https://user-images.githubusercontent.com/76167283/102578204-9b078c00-4134-11eb-961d-268d43a3fa7d.jpg)

**Comment by Nyx-o12** [comment]
![Screenshot_20201218_112140](https://user-images.githubusercontent.com/76167283/102578236-ace92f00-4134-11eb-9d81-ab217047b096.jpg)

**Comment by Nyx-o12** [comment]
![Screenshot_20201218_112219](https://user-images.githubusercontent.com/76167283/102578265-be323b80-4134-11eb-9b09-97c159333358.jpg)

**Comment by Nyx-o12** [comment]
![Screenshot_20201218_112318](https://user-images.githubusercontent.com/76167283/102578301-cd18ee00-4134-11eb-943b-d76c8fa2bda8.jpg)

**Comment by Nyx-o12** [comment]
> I think the pictures weren't sent here when you replied via email, try to use github to send them

I successfully uploaded the photos.

**Comment by scb261** [comment]
If you press search, you'll get the same result as in Tachiyomi. But it looks like the list on your screenshots shows better results, so maybe the extension should take results from there. In this case it's more of enhancement than a bug.

**Comment by Nyx-o12** [comment]
So there is no way to fix it?

**Comment by scb261** [comment]
Edit the issue so it would be an enhancement instead of a bug, and wait until a dev will code it

**Comment by Nyx-o12** [comment]
I think it got deleted since I can't find it.

**Comment by scb261** [comment]
It wasn't deleted, click this link
![image](https://user-images.githubusercontent.com/65343233/102692978-ea76b680-421f-11eb-8710-4341c0812b80.png)

**Comment by Nyx-o12** [comment]
Where can I find The "Enhancement"? Is it in the issues too?

**Comment by scb261** [comment]
You can't change the label, just wait when one of maintainers will change it

**Comment by Nyx-o12** [comment]
So all I have to do is wait?
