### ISSUE TITLE
MIQ

### ISSUE THREAD

**Issue by alucardlucilfer** [tachiyomiorg/tachiyomi-extensions#5169]
## Source Website
- Name: MIQ Manga
- Link: https://www.m-iq.me/?m=1
- Language(s): Arabic

## Other Details
please add this site it has rare list of manga and thank you

**Comment by scb261** [comment]
There is no point in closing older issue (#4986) and opening a new one, just wait until someone will want to code it

**Comment by alucardlucilfer** [comment]
> There is no point in closing older issue (#4986) and opening a new one, just wait until someone will want to code it

I thought no one saw the post because it was a long time ago and no one responded

**Comment by CrepeTF** [comment]
Any source request will be made into a source when any dev that wants it makes it, there's absolutely no guarantee that it will be made into a source

**Comment by alucardlucilfer** [comment]
> Any source request will be made into a source when any dev that wants it makes it, there's absolutely no guarantee that it will be made into a source

Well thanks for making things clear

**Comment by vetleledaal** [comment]
Uses the theme Manga Sēbu v1.0, which would be new to Tachiyomi
