### ISSUE TITLE
[Feature Request] <nhentai>: <Support for blacklisted tags>

### ISSUE THREAD

**Issue by JasperNg** [tachiyomiorg/tachiyomi-extensions#5173]
## What feature should be added to this source?
Blacklisted tags tied to an account logged in should impact the search in the extension. The account can be logged in through webview

**Comment by arkon** [comment]
I'm pretty sure this is already the case?

**Comment by JasperNg** [comment]
I use TachiyomiSY and I asked Syer on discord. As far as I know, this is not added yet.

**Comment by JasperNg** [comment]
Unless it is different in TachiyomiSY

**Comment by arkon** [comment]
Seems to work fine in SY too.

**Comment by arkon** [comment]
Did you actually try it?

**Comment by JasperNg** [comment]
Yes, I just did. I blocked netorare but some doujins with netorare still pop up.

**Comment by arkon** [comment]
Did you verify that the website functions any differently?

**Comment by JasperNg** [comment]
Nevermind, I just logged in again and it works. Sorry for taking your time.
