### ISSUE TITLE
[Source Request] <ManhuaScan.com>

### ISSUE THREAD

**Issue by anshineta** [tachiyomiorg/tachiyomi-extensions#5174]
## Source Website
- Name: ManhuaScan.com
- Link: https://manhuascan.com/
- Language(s): English

## Other Details
?

**Comment by HaruSasaki** [comment]
It's already exists in FMReader extension.

**Comment by anshineta** [comment]
Thank you! And sorry I searched in the spreadsheet and in the app and it didnt come up.

**Comment by Arekkusu1998** [comment]
Thank you very much for the very useful information, @**HaruSasaki** : I was looking for same website too😃!
