### ISSUE TITLE
[Source Request] <Gudangkomik>

### ISSUE THREAD

**Issue by willyreza** [tachiyomiorg/tachiyomi-extensions#5178]
## Source Website
- Name: Gudangkomik
- Link: https://gudangkomik.com
- Language(s): Indonesian

## Other Details
👍👍👍

**Comment by kell20** [comment]
will this extension be added?

**Comment by Satriouz** [comment]
why did GudangKomik enter Toomics?

**Comment by TheKingTermux** [comment]
> why did GudangKomik enter Toomics?

The Bot is broken 😅

**Comment by TheKingTermux** [comment]
@willyreza buka source request lgi ya
