### ISSUE TITLE
[Source Request] <Mangacoro>

### ISSUE THREAD

**Issue by willyreza** [tachiyomiorg/tachiyomi-extensions#5179]
## Source Website
- Name: Mangacoro
- Link: https://mangacoro.com
- Language(s): Indonesian

## Other Details
👍👍👍

**Comment by Riztard** [comment]
i think its [bacakomik.co](bacakomik.co) clone

**Comment by willyreza** [comment]
> i think its [bacakomik.co](bacakomik.co) clone/use same database
> this one as well #5177

Ok👍

**Comment by Riztard** [comment]
gak di close juga gapapa, cuma ngasih tau kalo bisa make bacakomik juga

**Comment by willyreza** [comment]
> gak di close juga gapapa, cuma ngasih tau kalo bisa make bacakomik juga

Orang Indonesia om?🤭
