### ISSUE TITLE
[Source Request] <Manganime>

### ISSUE THREAD

**Issue by willyreza** [tachiyomiorg/tachiyomi-extensions#5183]
## Source Website
- Name: Manganime
- Link: http://manganime.my.id
- Language(s): Indonesian

## Other Details
👍👍👍

**Comment by antonycaporossi** [comment]
It seems to be the copied from Komikcast.
In the url logo you can also find the komikcast title tag ("Komikcast - Tempatnya Baca Komik Online Bahasa Indonesia")...
They have also the same content but Manganime has less function (filtering and ordering).

Please let me know if i'm wrong.

**Comment by willyreza** [comment]
Ok
