### ISSUE TITLE
[Source Request] <Gmanga>

### ISSUE THREAD

**Issue by Ar1hurT** [tachiyomiorg/tachiyomi-extensions#5189]
## Source Website
- Name: gmanga
- Link: https://gmanga.me/?utm_source=a2hs
- Language(s): arabic

## Other Details
the best arabic manga source

**Comment by arkon** [comment]
I guess you didn't try to search?

#117

**Comment by CrepeTF** [comment]
Already replied not your earlier request for this same source
#117
Don't request this source again.
