### ISSUE TITLE
[Bug] MangaWorld broken

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi-extensions#5190]
Unable to browse mangaworld

**Comment by antonycaporossi** [comment]
Hi, 2 weeks ago i rewrote mangaworld extensions.
You can find it in my repo
https://github.com/antonycaporossi/Tachiyomi-Mangaworld-Extension

It seems fully working (i use it almost everyday) so i'm gonna make a PR with it
