### ISSUE TITLE
[Bug] Keenspot Twokinds: Downloading folder structure broken

### ISSUE THREAD

**Issue by AMDHome** [tachiyomiorg/tachiyomi-extensions#5191]
## Device information
- Tachiyomi version:  v0.10.6
- Android version: 9

## Source information
- Name: Keenspot
- Extension version: v1.2.1

## Steps to reproduce
1. Open a comic and download the chapter
2. Go to the chapter download location using a file browser and look at the files.

### Expected behavior
In the Tachiyomi download folder, each extension should have one folder containing a folder for each comic/manga. Inside the comic/manga folder there should be more folders for chapters. 

### Actual behavior
The extension creates one folder per chapter in the downloads folder causing a huge mess.

## Other details
See Pictures for more information The three manga folders are individual sources.
![Screenshot_20201218-170103](https://user-images.githubusercontent.com/13590596/102676700-b0d87980-4153-11eb-85b5-d019c06f9ed1.png)

**Comment by AMDHome** [comment]
Great work on the extension, but could you take a look at this issue? @AriaMoradi  Thanks.

**Comment by AriaMoradi** [comment]
It's fine on my device. Probably a app bug.

**Comment by scb261** [comment]
Actually some systems don't support colons in names and it looks like author's system replacing it with `_`. The app can't find the folder and is trying to create new folder each time that results into those folders with numbers. The app replaces colon and some other characters in chapter names and a source shouldn't use one of those characters as name

https://github.com/tachiyomiorg/tachiyomi/blob/d4c9ab793f3966e1e3ae17b826daf9067adca98c/app/src/main/java/eu/kanade/tachiyomi/util/storage/DiskUtil.kt#L126
