### ISSUE TITLE
[Source Request] <SkyManga>

### ISSUE THREAD

**Issue by Theoden00** [tachiyomiorg/tachiyomi-extensions#5199]
---

## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: SkyManga from madara extension
- Extension version: ?

### Expected behavior
This should have happened
Skymanga should be apart of Madara but no longer exists on this extension. Normal skymanga website works

**Comment by fawadkhan121** [comment]
Please add it back

**Comment by AriaMoradi** [comment]
I was added again in #5184
this can be closed.
