### ISSUE TITLE
[Source Request] Travis Translations

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#5200]
## Source Website
- Name: Travis Translations
- Link: https://travistranslations.com/
- Language(s): English

## Other Details
?

**Comment by Riztard** [comment]
i think it use wp mangastream theme from easTheme

**Comment by FlammFR** [comment]
+1

**Comment by curche** [comment]
From the looks of it, this looks to be a Light Novel translations and not a Manga site. Kindly confirm

**Comment by jopejoe1** [comment]
Can't find any Manga on their site, tried all the ones mentioned on their [Manga-updates page](https://www.mangaupdates.com/groups.html?id=13380)

**Comment by curche** [comment]
Closing as no Manga is found on the source. LNs cannot be read using Tachiyomi anyways
