### ISSUE TITLE
[Bug] <Mangakawaii>: dont load correctly all data

### ISSUE THREAD

**Issue by sikiang** [tachiyomiorg/tachiyomi-extensions#5205]
## Device information
* Tachiyomi version: Preview r2903
* Android version: 9
* Device: Samsung Galaxy Tab 3

## Source information
* Source name: mangakawaii
* Source extension version: 1.2.11

## Steps to reproduce
1 Install mangakawaii extension 
2 reload data for this extension

## Issue/Request
This source does not load correctly manga information and chapter information

On attachement you can see missing name of manga on beliw of picture, and all chapter are not see by this extension (one picture on application and another on integrated browser for the dame chapter

I have try on my phone with last production version and its the same
I have try also to remove all data and its the same 

## Other details
Additional details and attachments.

When the chapter is availaible on the app no problem for download or for read chapter

![Screenshot_20201126-073121_Tachiyomi](https://user-images.githubusercontent.com/49972601/102700315-a4841780-424c-11eb-8b2d-eb2570196114.jpg)
![Screenshot_20201126-073045_Tachiyomi](https://user-images.githubusercontent.com/49972601/102700316-a5b54480-424c-11eb-9020-a2d28d450597.jpg)
![Screenshot_20201126-073019_Tachiyomi](https://user-images.githubusercontent.com/49972601/102700317-a5b54480-424c-11eb-9721-06102e39fee5.jpg)

**Comment by OncePunchedMan** [comment]
I've fixed the extension. Pls check if it's working as intended

**Comment by sikiang** [comment]
Thanks for this update.

It's not good for me.
I have flush cache, refresh library and all metadata.

For the library it's just hit (image 1 and 2) so he miss so many books.

And i have try for recent chapter and for the first Aquaman the name, description, are good but chapter does not load. (image 3)

![Screenshot_20210105-122440_Tachiyomi](https://user-images.githubusercontent.com/49972601/103640879-151b7b80-4f51-11eb-8b0d-84a64f1252fd.jpg)


![Screenshot_20210105-122136_Tachiyomi](https://user-images.githubusercontent.com/49972601/103640699-c968d200-4f50-11eb-9031-a0161cf0f984.jpg)

![Screenshot_20210105-122148_Tachiyomi](https://user-images.githubusercontent.com/49972601/103640715-d1c10d00-4f50-11eb-9d3a-4aa3184bb388.jpg)

**Comment by OncePunchedMan** [comment]
the site seems to have removed the manga you want to read. can't find it on the site.

**Comment by sikiang** [comment]
They have rename it as aquaman but now it's empty

But it's not just whith this manga 

I have see if the sender of chapter is not izayoi the chapter is not view by tachiyomi 

![Screenshot_20210106-014248_Tachiyomi.jpg](https://user-images.githubusercontent.com/49972601/103715608-5d728200-4fc1-11eb-8aff-d478b89cc328.jpg)

![Screenshot_20210106-014205_Chrome.jpg](https://user-images.githubusercontent.com/49972601/103715617-6400f980-4fc1-11eb-9c49-da51ed4715c1.jpg)

**Comment by OncePunchedMan** [comment]
it says, aquaman is licensed. so no luck

as for the missing chapters: i'll take a look

**Comment by sikiang** [comment]
Thanks for update, all manga on my library are now correctly updated.

![Screenshot_20210106-080813_Tachiyomi](https://user-images.githubusercontent.com/49972601/103755821-bcaab380-500e-11eb-99ed-e79fb8570778.jpg)


Just the global library from Mangakawaii doesn't work properly. this only displays some popular manga and not the complete library available on the site

![Capture d’écran 2021-01-06 105959](https://user-images.githubusercontent.com/49972601/103755733-94bb5000-500e-11eb-81c3-e24f19f4c7f8.png)
