### ISSUE TITLE
[Bug] <Madara>: <Missing sources after update>

### ISSUE THREAD

**Issue by Kuuhaku0130** [tachiyomiorg/tachiyomi-extensions#5210]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: Madara 
- Extension version: 1.2.160

## Steps to reproduce
1. After updating to latest madara extension version 
2. Skymanga source is missing.

### Expected behavior
After updating extension, skymanga should still be available. 
### Actual behavior
Skymanga extension and mangas missing completely. Extension cannot be found.

**Comment by Vesnyx** [comment]
Should be added back in #1218.

**Comment by Vesnyx** [comment]
Should be added back in #5128.

**Comment by Vesnyx** [comment]
Should be added back here: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/5218.
