### ISSUE TITLE
[Source Request] < newtoki91.com > KR

### ISSUE THREAD

**Issue by zaydendavis69** [tachiyomiorg/tachiyomi-extensions#5221]
https://newtoki91.com/
- Name: NewToki91
- Link: https://newtoki91.com/
- Language(s): KR

## Other Details
Was previously using newtoki but no longer works. Request to add/update from newtoki to newtoki91. Thanks!

**Comment by CrepeTF** [comment]
Already exists, edit the URL in the extension's settings

**Comment by zaydendavis69** [comment]
Thanks! Didn't know you could do that.
