### ISSUE TITLE
[Bug] <Tritinia Scans>: <getting an http error in madara extension>

### ISSUE THREAD

**Issue by Subtilizer28** [tachiyomiorg/tachiyomi-extensions#5222]
## Device information
- Tachiyomi version: 1.0.10 J2K
- Android version: 10

## Source information
- Name: Madara -> Tritinia Scans
- Extension version: 1.2.161

## Steps to reproduce
1. Install Madara Extension
2. Open Tritinia Scans in it

### Expected behavior
Shows Manhwas

### Actual behavior
Gives **HTTP error 404: Check website in WebView**

## Other details
The Source works fine in webview

**Comment by Vesnyx** [comment]
Yeah, they changed their reader to what appears to be a GitHub pages blog with static images, which I don't think we'll be supporting. They upload on MangaDex so probably your best bet to switch over. 

URL: https://tritiniaman.ga/

**Comment by Subtilizer28** [comment]
Oh I see. Thanks for the resp!!
