### ISSUE TITLE
[Source Request] <CopyToon>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#5224]
## Source Website
- Name: CopyToon
- Link: https://copytoon121.com/
- Language(s): KR

## Other Details
Uploads raw manhwa

**Comment by vetleledaal** [comment]
Domain expired 2021-12-14T20:01:38Z according to whois

**Comment by Seishirou101** [comment]
You can open a new issue if the site ever comes back.
