### ISSUE TITLE
[Source Request] <HoHoToon>

### ISSUE THREAD

**Issue by dingdonng22** [tachiyomiorg/tachiyomi-extensions#5226]
## Source Website
- Name: HohoToon
- Link: https://hohotoon21.com/
- Language(s): KR

## Other Details
uploads raw manhwa.

**Comment by vetleledaal** [comment]
Site redirects to some ads
Parked since at least 2022-02-02T22:14:54Z according to whois, site was probably not available since at least dec 3 2021 according to wayback machine

**Comment by Seishirou101** [comment]
You can open a new issue if the site ever comes back.
