### ISSUE TITLE
[Source Request] <Party Network>

### ISSUE THREAD

**Issue by Subtilizer28** [tachiyomiorg/tachiyomi-extensions#5227]
## Source Website
- Name: Party Network
- Link: https://mangadex.org/group/12467/party-scans
- Language(s): EN

## Other Details
They Don't Have an website but here is their scans group. I submitted this cuz mangadex takes too long to upload new chapters.....

**Comment by shashank-p** [comment]
And where do they upload chapter before mangadex if they don't have website

**Comment by Subtilizer28** [comment]
Lol me being really dumb. But it is bit delaying when I refresh on tachiyomi. BTW it would be great if it had a separate source.

**Comment by arkon** [comment]
Use the MangaDex source, we won't so anything special for all of the scanlators on there
