### ISSUE TITLE
[Bug] <漫畫堆manhuadui>: <change site to m.90mh.com>

### ISSUE THREAD

**Issue by smarttommyau** [tachiyomiorg/tachiyomi-extensions#5228]
This extension has moved to new website so that the extension will give error "failed to connect to m.manhuadai.com/61.111.129.189 (port 443) from /192.168.0.119 (port 57800) after 30000ms". The new website is m.90mh.com.Please update the extension, thank you.

**Comment by sunbeams001** [comment]
Official news? Seems both m.90mh.com and www.90mh.com have different page structure from the original one.

**Comment by smarttommyau** [comment]
thanks I think I have been bislead by some online post. 😅
