### ISSUE TITLE
[Bug] <Mangapark>: <most cover did not show up>

### ISSUE THREAD

**Issue by tunabruhh** [tachiyomiorg/tachiyomi-extensions#5230]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 8.1.0

## Source information
- Name: Mangapark
- Extension version: 1.2.17

## Steps to reproduce
1. Delete app cache
2. Open Tachiyomi

### Expected behavior
All cover should load

### Actual behavior
Most cover did not show up

## Other details
Only way to make the cover show is to click every single manga that doesn't have its cover load to make it appear.

**Comment by antonycaporossi** [comment]
I'm not able to replicate the issue.
Everything is working fine for me.

Did you have this problem in a specific page (keywork search or filtering)?

**Comment by tunabruhh** [comment]
No it's not specific.
