### ISSUE TITLE
[Feature Request] manga dex: bookmark feature for filters

### ISSUE THREAD

**Issue by RedCrafterLP** [tachiyomiorg/tachiyomi-extensions#5242]
I regularly check for new content uploaded under a certain combination of filter. I find it pretty annoying to always have to dial in my filter. So I thought it would be a good idea being able to save filter settings to find new content faster. It would be nice if you could consider my idea. Thanks for this great app.

**Comment by scb261** [comment]
It should be done on the app side, not an extension. Maybe just add your idea to https://github.com/tachiyomiorg/tachiyomi/issues/779

**Comment by RedCrafterLP** [comment]
got it. Thanks for your reply ;-)
