### ISSUE TITLE
[Bug] <Scantrad [FR]>: <403 Forbidden>

### ISSUE THREAD

**Issue by Zealest** [tachiyomiorg/tachiyomi-extensions#5243]
## Device information
- Tachiyomi version: Preview r2909
- Android version: 10

## Source information
- Name: Scantrad
- Extension version: 1.2.6

## Steps to reproduce
Simply open the extension

### Actual behavior
An error should appear + opening it in webview displays the same error :|
also, Scantrad website is working fine on any web browser.

### Additionnal infos

Scantrad.fr changed to Scantrad.net, so it needs an update! Thanks to @king07-0 for pointing this out.

**Comment by yfreezer** [comment]
i have the same problem

**Comment by choco-latin** [comment]
Similar problem, I get a "HTTP error 403"

**Comment by W4tte0** [comment]
Me too, "HTTP error 403" and when I use WebView it shows "Forbidden"

**Comment by king07-0** [comment]
Scantrad.fr change to scantrad.net, so the extension have to be updated

**Comment by Zealest** [comment]
> Scantrad.fr change to scantrad.net, so the extension have to be updated

updated my post
thank you I didn't notice the domain has actually changed.

**Comment by Zealest** [comment]
it's still not working :(
![Screenshot_20201225-223311](https://user-images.githubusercontent.com/62892019/103142308-819cac00-4701-11eb-8497-f1f902ed4f05.jpg)
![Screenshot_20201225-223325](https://user-images.githubusercontent.com/62892019/103142310-84979c80-4701-11eb-8542-fe4aca6e2b1f.jpg)

**Comment by CrepeTF** [comment]
can confirm ^
reopen the issue

**Comment by W4tte0** [comment]
Is there any advancements in the issue ?

**Comment by W4tte0** [comment]
Cause the update didn't worked (I use J2K) and I don't see any cases opened about this issue.

**Comment by arkon** [comment]
@W4tte0 You're commenting on an open issue. I'm not sure if there's anybody actively working on it, as we generally have very few people actually contributing.

**Comment by Zealest** [comment]
yup, it would be cool if it could be fixed

**Comment by W4tte0** [comment]
Okay thanks

**Comment by clarencecastillo** [comment]
PR #5267 is up, should fix this issue.

![image](https://user-images.githubusercontent.com/5035728/103183570-3398cb80-48ee-11eb-937f-aa2507b7fe2f.png)

**Comment by choco-latin** [comment]
I confirm the update fixed the issue. Thanks!

**Comment by Zealest** [comment]
THANKS!

**Comment by choco-latin** [comment]
The extension is not working again, unfortunately.  This issue should be reopened.

**Comment by Zealest** [comment]
I spoke with a Scantrad admin, he said they will continue to block Tachiyomi and consider the app equal to a site like Japscan, if the developers are motivated enough and manage to bypass their blocking methods it would be so fkin great :)
Just to discourage them, we're just people who want to read :)

**Comment by CarlosEsco** [comment]
ask them if they would consider allowing if we add a harsh rate limiting?

**Comment by Zealest** [comment]
> ask them if they would consider allowing if we add a harsh rate limiting?

they absolutely want us to read on their site, and that's understandable. anyway i'll ask them

**Comment by Zealest** [comment]
admin hasn't replied yet.
wondering if he doesn't know what it is or he ignores me on purpose
