### ISSUE TITLE
[Feature Request] <NeoxLeitor>

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#5244]
## Source Website
- Name: NeoxLeitor
- Link: https://neoxleitor.com/
- Language(s): portuguese Brazil

## Other Details
 neox scanlator website exclusive for solo leveling at the moment

**Comment by alessandrojean** [comment]
Normally single series sources doesn't get added.

I will keep taking a look, when they have more series, it can be added to Madara.

Meanwhile, you can use an aggregator source.

**Comment by Douglasimav** [comment]
ok
