### ISSUE TITLE
[Bug] <NeoxScanlator>: The domain has changed

### ISSUE THREAD

**Issue by matheuswr89** [tachiyomiorg/tachiyomi-extensions#5251]
## Device information
- Tachiyomi version: 0.10.6
- Android version: 10

## Source information
- Name: NeoxScanlator
- Extension version: Madara 1.2.161

### Expected behavior
Updates were expected to appear in the domain that is configured in the extension, but this is not the case

## Other details
The domain changed from https://neoxscans.net/ to https://neoxscans.com/

**Comment by matheuswr89** [comment]
@alessandrojean se puder dar uma olhadinha ai

**Comment by alessandrojean** [comment]
Eu vou atualizar assim que eu tiver um tempinho.

Aproveitando, não precisa ficar me marcando toda vez, eu tô sempre olhando as *issues* de tempos em tempos ^^'
