### ISSUE TITLE
[Bug] MangaFast: Page not loading

### ISSUE THREAD

**Issue by FaTe-code** [tachiyomiorg/tachiyomi-extensions#5257]
## Device information
- Tachiyomi version: J2K 1.0.10
- Android version: 9

## Source information
- Name: MangaFast
- Extension version: MangaFast

### Expected behavior
Page loading like usual

### Actual behavior
Timeouts on first try then it opens the reader but shows try again but it doesn't load.

## Other details
Webview works tat got no prob.

**Comment by Riztard** [comment]
work just fine for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by scb261** [comment]
Also works fine for me. I suppose the author just encountered manga that has broken pages (while checking the source and fixing thumbnails #5997 I encountered few manga like this). If there actually is a chapter that works on the site but not in the app - please open new issue and specify what manga and chapter exactly doesn't load
