### ISSUE TITLE
[Bug] <Remanga extension error>: <java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $>

### ISSUE THREAD

**Issue by WiNE-iNEFF** [tachiyomiorg/tachiyomi-extensions#5264]
Today 27.12.2020 extension Remanga (Russian) doesn't work with error:
`java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`

![Screenshot_2020-12-27-17-46-52-965_com android htmlviewer](https://user-images.githubusercontent.com/41611046/103173618-2b4c7c00-486d-11eb-88d3-973392a8aead.jpg)

This error i was get when restore backup.
Before this error appeared, the application crashed when connected to the Internet. Everything was fine without internet access

## Device information
- Tachiyomi version: r2909 
- Android version: Xiaomi Redmi 5a (8.1.0)

## Source information
- Name: Remanga
- Extension version: 1.2.9

**Comment by scb261** [comment]
Looks like they are blocking Tachiyomi, works fine in browser
![image](https://user-images.githubusercontent.com/65343233/103181989-1513df80-48b0-11eb-8a1b-b696804d86d8.png)

**Comment by WiNE-iNEFF** [comment]
> Похоже, они блокируют Тачиёми, в браузере работает нормально
> ![образ](https://user-images.githubusercontent.com/65343233/103181989-1513df80-48b0-11eb-8a1b-b696804d86d8.png)

Doesn't this mean that this extension is no longer functional and can be removed?

**Comment by Nonamow** [comment]
> Doesn't this mean that this extension is no longer functional and can be removed?

It is a very-very-very bad idea. I hope, that dev. can fix this extension.
