### ISSUE TITLE
earlymanga extension doesnot work!!

### ISSUE THREAD

**Issue by Jubin-saud** [tachiyomiorg/tachiyomi-extensions#5265]
**earlymanga.xyz** is a great manga/manhua website with fast updates. it was recently(i saw it recently added into the **madara(multiple source)** extension.. ) , but it doesn't work every time i try to open it, it shows **" http error 404 "..**

**Comment by Riztard** [comment]
they seems no longer use madara theme

**Comment by CarlosEsco** [comment]
@Jubin-saud that is the reason the issue is still open..  you are welcome to do the work yourself if you are impatient
