### ISSUE TITLE
[mangalek.com] <mangalek>

### ISSUE THREAD

**Issue by anastrafalgar** [tachiyomiorg/tachiyomi-extensions#5271]
---

## Source Website
- Name: ? mangalek
- Link: ? mangalek.com
- Language(s): ? Arabic

## Other Details
? This is one of the biggest manhwa and manga library, so hop you add it !!

**Comment by scb261** [comment]
Read acknowledgment section before removing it. It already exists, search [the spreadsheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) or github next time.
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/63b264137558618d814615b474fa5480b8ad0913/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L879
