### ISSUE TITLE
[mangaswat.com] <mangaswat>

### ISSUE THREAD

**Issue by anastrafalgar** [tachiyomiorg/tachiyomi-extensions#5272]
---

## Source Website
- Name: ? mangaswat
- Link: ? mangaswat.com
- Language(s): ? Arabic

## Other Details
? This website is one of the biggest manhwa and manga library, so hope you add it

**Comment by scb261** [comment]
Read acknowledgment section before removing it. It already exists, search [the spreadsheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) or github next time.
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/b8ef36992883daaef3b325b9b2509fea48c891da/src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt#L551
