### ISSUE TITLE
<NHentai>: chapter don't load

### ISSUE THREAD

**Issue by lolo298** [tachiyomiorg/tachiyomi-extensions#5273]
## Device information
* Tachiyomi version: stable 0.10.7
* Android version: 7
* Device: samsung galaxy s6

## Source information
* Source name: NHentai
* Source extension version: 1.2.28

## Steps to reproduce
1. install NHentai extension
2. open this extension

## Issue/Request
The source don't load anything
when it's open, it just shows the message connection reset

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
Works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems)

**Comment by arkon** [comment]
Your country or household is likely blocking it.
