### ISSUE TITLE
[Bug] Mangakakalot: Slow loading af

### ISSUE THREAD

**Issue by RedstoneStrikers** [tachiyomiorg/tachiyomi-extensions#5276]
## Device information
- Tachiyomi version: Latest
- Android version: 9

## Source information
- Name: Mangabox (mangakakalot etc)
- Extension version: Latest

## Steps to reproduce
1. Load Any Pages in the Source
2. It doesn't load but in webview, it loads instantly

### Expected behavior
tachiyomi loads at same speed in webview

### Actual behavior
It loads slowly (like super slowly)

**Comment by Riztard** [comment]
i try 4 sources and load fast for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by CrepeTF** [comment]
This issue is pretty old and there have been many updates to the extension since.
