### ISSUE TITLE
comicabc.com

### ISSUE THREAD

**Issue by arso7** [tachiyomiorg/tachiyomi-extensions#5279]
## Source Website
- Name: 8comic
- Link: 8comic.com
- Language(s): zh

## Other Details
Other link to the website : https://www.comicbus.com
App link : https://www.comicbus.com/app/

**Comment by as280093** [comment]
**ICONS:** [8comic.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/5769543/8comic.zip)

**Comment by vetleledaal** [comment]
New URL: https://www.comicabc.com
