### ISSUE TITLE
[Bug] Emerald : bato.to - Catalog and Chapters aren't loading in app, works in webview

### ISSUE THREAD

**Issue by zyrif** [tachiyomiorg/tachiyomi-extensions#5282]
## Device information
- Tachiyomi version: 0.10.7-2921 (standard, eaccfdde, 54)
- Android version: 10 (SDK 29)

## Source information
- Name: Emerald
- Extension version: 1.2.7

## Steps to reproduce
- Go to catalog
and/or
- Try to open any chapter of any series already in the library

### Expected
- Catalog should show entries. 
- Chapters should open normally

### Actual behavior
- Catalog and search both shows no results found
- Attempting to open a chapter shows "Value document.domain of type java.lang.String cannot be converted to JSONObject"

## Other details
Webview seems to be working fine.

**Comment by zyrif** [comment]
I really hope it's salvagable, can't say I'm looking to doing another migration.

**Comment by CarlosEsco** [comment]
#5090
#4882

**Comment by zyrif** [comment]
@CarlosEsco Hi, I ended up solving this after uninstalling and reinstalling the extension. What was weird is that it wasn't working even in a fresh SY installation. The extension needed to be uninstalled and reinstalled in each fork individually. I think it'd help if this particular issue/solution was be added to the faq page (right now it just says to clear cache, history, db and enable doh)

**Comment by CarlosEsco** [comment]
That isn't the case though and sounds likes a phone specific issue
