### ISSUE TITLE
[Bug] RawLH: Not Loading Manga List after change to LoveHug.net

### ISSUE THREAD

**Issue by Donnie-B** [tachiyomiorg/tachiyomi-extensions#5293]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: FMReader
- Extension version: 1.2.23

## Steps to reproduce
1. Open Latest for RawLH, got blank list
2. Open RawLH, got message "No results found"
3. Open web view, web page successfully opened

### Expected behavior
Should be able to list the latest manga list when opening the latest, or all manga list when opening the RawLH.

### Actual behavior
Either get blank list, or "No result found"

**Comment by Riztard** [comment]
yeah they use new/different theme
