### ISSUE TITLE
[Bug] MangaSee : Bleach chapters no loading 

### ISSUE THREAD

**Issue by matecl** [tachiyomiorg/tachiyomi-extensions#5295]
---

## Device information
- Tachiyomi version: 0.10.7
- Android version: 9.1

## Source information
- Name: Bleach
- Extension version: Mangasee

### Actual behavior
The chapters of bleach from the 113 until the end doesn't load up, and appear as "HTTP error 520". When I load other extensions it works just fine.

**Comment by joseph619** [comment]
Open in webview to check if it's working on site, whether it's working on other extensions is irrelevant to the issue.

**Comment by matecl** [comment]
Seemed like the page was down, tried to load some other mangas and we're down too. Now it seems to work fine, so it was just wait.
