### ISSUE TITLE
[Bug] <azora>: <chapters does not load correctly>

### ISSUE THREAD

**Issue by dmswd** [tachiyomiorg/tachiyomi-extensions#5297]
## Device information
- Tachiyomi version:r3085
- Android version: 10

## Source information
- Name: azora
- Extension version: 1.2.1

## Steps to reproduce
1. Open the app
2. Open azora
3. Open a chapter from the most recent mangas
### Expected behavior
A full chapter should appear

### Actual behavior
Only a small image from the end of chapter appears in the reader

## Other details
Works fine in the browser
![Screenshot_20210102-121849_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/103455502-61b74a80-4cf6-11eb-8377-b157d2dfcb06.jpg)![Screenshot_20210102-122030_Samsung Internet.jpg](https://user-images.githubusercontent.com/66433732/103455503-63810e00-4cf6-11eb-8eb4-85a093586c0c.jpg)![Screenshot_20210102-122142_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/103455506-65e36800-4cf6-11eb-88d5-a5adf2f69425.jpg)![Screenshot_20210102-122234_Samsung Internet.jpg](https://user-images.githubusercontent.com/66433732/103455508-67149500-4cf6-11eb-98bd-981323975959.jpg)

**Comment by Riztard** [comment]
the image seems split vertically as well. need to stitch the image to fix it

**Comment by scb261** [comment]
Seems to work fine for me. Can you clear chapter cache and see if it still happens with fixed URL in 1.2.2?

**Comment by dmswd** [comment]
It seems that there are about ten chapters in the whole site that don't work correctly 
So I think it isn't worthwhile for anyone to try to fix it
