### ISSUE TITLE
[Source Request] manhuascan

### ISSUE THREAD

**Issue by red86fritz** [tachiyomiorg/tachiyomi-extensions#5307]
## Source Website
- Name: manhuascan
- Link: manhuascan.com
- Language(s): english

 Thanks in advance

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues?q=is%3Aissue+manhuascan

**Comment by red86fritz** [comment]
Oh yey, i found it! Thank you so much
