### ISSUE TITLE
[Bug] <COCO Manhua>: <decryption error>

### ISSUE THREAD

**Issue by EricFoodTab** [tachiyomiorg/tachiyomi-extensions#5310]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 9

## Source information
- Name: COCO manhua
- Extension version: 1.2.6

## Steps to reproduce
1. when i want to read the manhua

### Expected behavior
It will normally load into the manhua

### Actual behavior
it says decryption failed when i try to read the manhua

## Other details
![Screenshot_2021-01-04-18-26-50-263_eu kanade tachiyomi](https://user-images.githubusercontent.com/70044043/103534045-1ef99c00-4ec9-11eb-9e42-e2529134725e.jpg)

**Comment by lmk1988** [comment]
As usual, pre-release apk is located here

https://github.com/lmk1988/tachiyomi-extensions/releases
