### ISSUE TITLE
[Bug] <Mangahasu>: <For input string: "img-current">

### ISSUE THREAD

**Issue by TheFourthEspada** [tachiyomiorg/tachiyomi-extensions#5313]
## Device information
- Tachiyomi version: r2959
- Android version: 10

## Source information
- Name: Mangahasu
- Extension version: 1.2.9

## Steps to reproduce
1. Tap any manga from Mangahasu source
2. Tap any non downloaded (if any) chapter from chosen manga

### Expected behavior
Tachiyomi should load pages(images)

### Actual behavior
Tachiyomi goes back to chapter list and displays, "For input string: "img-current""

## Other details
![Screenshot_20210104-113131_Tachiyomi](https://user-images.githubusercontent.com/76968890/103571835-70316d80-4e80-11eb-8dce-cadb1ecb6b01.jpg)

**Comment by scb261** [comment]
Works fine for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems)

**Comment by TheFourthEspada** [comment]
It works now. I believe it was clearing cache, cookies and database that made it work. Reinstalling and DNS over HTTPS did nothing.
