### ISSUE TITLE
[Source Request] <The DC Corps>

### ISSUE THREAD

**Issue by ahmed03waleed** [tachiyomiorg/tachiyomi-extensions#5317]
## Source Website
- Name: The DC Corps
- Link: https://www.thedccorps.info/search/label/%D8%A7%D9%84%D9%83%D9%88%D9%85%D9%8A%D9%83%D8%B3%20%D8%A7%D9%84%D9%85%D8%AA%D8%B1%D8%AC%D9%85%D8%A9?max-results=10&m=1
- Language(s): Arabic

**Comment by shipoxx** [comment]
A note about this request and why it should be closed: 
• All links are external, meaning there is no way (hard) to display content/images. 
• This is a blog that specializes in comics and writing articles, not a comic translation site 
• No addition has been made to the mentioned site for more than a year.
