### ISSUE TITLE
[Source Request] <earlymanga.xyz>

### ISSUE THREAD

**Issue by Jubin-saud** [tachiyomiorg/tachiyomi-extensions#5320]
## Source Website-https://earlymanga.xyz
- Name: earlymanga
- Link: [https://earlymanga.xyz](url)
- Language(s): English

## Other Details
this extension exists in the **madara extension** as a sub extension, but its **only in name it does not work** in madara....
so I request to add a separate extension for it, as it is a good website for fast updates...

**Comment by scb261** [comment]
Duplicate of #5265
