### ISSUE TITLE
[Bug] Nekopost : not loading manga

### ISSUE THREAD

**Issue by sokixcem** [tachiyomiorg/tachiyomi-extensions#5321]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 9

## Source information
- Name: Nekopost
- Extension version: 1.2.3

## Steps to reproduce
1. Delete extension and instail again
2. Delete app and instail again

### Expected behavior
it is return to normal use.

### Actual behavior
Can't load manga it say "www.nekopost.net/ﬁle_server/collecthon/008000/7386/7386dtl.json"

![Screenshot_20210107-235414528](https://user-images.githubusercontent.com/65889238/103920361-cbdf4d80-5143-11eb-86df-0ea7134048a9.jpg)

**Comment by scb261** [comment]
I tried to look into it and there are 2 things that I just leave here in case it'll help someone who knows how to fix it:
1. File server is now fs.nekopost.net
2. File server now has some weird cloudflare protection that I couldn't quite figure out and let alone code it in the extension. They return 520 for direct links to files (e.g. pages or covers) even when the site is actually fine. I'm not sure what exactly triggers it, but if you open the same file from the site itself (i.e. open site, find manga and open chapter from there) then the file loads fine. And after doing it in a browser it will also work in the app but only for the same file, so I guess ip is also considered. And yes, I tried overriding client with `network.cloudflareClient` but it didn't help.
