### ISSUE TITLE
[Bug] AsuraScans: Chapters are behind

### ISSUE THREAD

**Issue by psychopomp9** [tachiyomiorg/tachiyomi-extensions#5333]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 9

## Source information
- Name: AsuraScans (WP mangaStream)
- Extension version: 1.2.44

### Expected behavior
New chapter should load

### Actual behavior
New chapters aren't loading

## Other details
There might be some issue while fetching new chapter from site.

**Comment by CarlosEsco** [comment]
if you go into one of the manga and swipe refresh, is there an error?

**Comment by psychopomp9** [comment]
No, sorry for the trouble, they aren't linking new chapters to their index i think, that's why

**Comment by CrepeTF** [comment]
Asura scans group knows about problem but dunno why they haven't fixed it yet.

Anyway website issue, someone close this
