### ISSUE TITLE
[Bug] MangaDex: ID lookup failing

### ISSUE THREAD

**Issue by Mutank** [tachiyomiorg/tachiyomi-extensions#5338]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: MangaDex
- Extension version: 1.2.98

## Steps to reproduce
1. In Sources, enter the MangaDex source
2. (Might not actually be necessary) Open webview and ensure you are logged in to MangaDex to enable search
3. Search for "id:<some_known_manga_id>" (e.g. "id:48045")

### Expected behavior
Search results should return only one entry. (In the above example, "Sousou no Frieren")

### Actual behavior
Error message: 'manga' is not found

**Comment by Riztard** [comment]
work for me :/

**Comment by Mutank** [comment]
Searching just the number still doesn't work for me. Also, opening external mangadex.org links in the MangaDex extension searches for "id:number", not just "number", so there would still be unexpected behavior.

**Comment by Riztard** [comment]
> Searching just the number still doesn't work for me.

try update ext again?

**Comment by Mutank** [comment]
Yes, still broken on 1.2.99, latest extension version

**Comment by giosann** [comment]
It's also broken for me. For both manual search and link opener.
The error is
'manga' is not found
![Screenshot_20210107-112550_Tachiyomi](https://user-images.githubusercontent.com/10052873/103881799-38723200-50db-11eb-8fef-13ae7162188d.png)



App version: 0.10.7-2991 (standard, 7192b264, 54)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.T865XXU4BTK2
Device brand: samsung
Device manufacturer: samsung
Device name: gts6l
Device model: SM-T865
Device product name: gts6leea

Mangadex 1.2.99
