### ISSUE TITLE
[Bug] Mangadex: Blocked groups not blocked

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi-extensions#5341]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.99

## Steps to reproduce
1. Log in to Mangadex
2. Block a group (like Snipe4U)
3. View a manga with chapters from that group (like A Wife Who Heals With Tights)

### Expected behavior
No chapters visible from the blocked group.

### Actual behavior
All chapters visible from the blocked group.

**Comment by CarlosEsco** [comment]
was a mangadex issue and not tachi

**Comment by BraveDude8** [comment]
For posterity; mangadex.org/API requests were correctly handling group blocks, API.mangadex.org requests were not. MD issue.

**Comment by arkon** [comment]
Keeping this open until MangaDex fixes their issues.

**Comment by BraveDude8** [comment]
Same API issue is also causing edited chapters to break, devs are working on fixing it. API cache isn't being properly cleared.

**Comment by arkon** [comment]
Some API issues were supposedly fixed. Is this still happening, @kiriya-aoi ?

**Comment by scb261** [comment]
Quote from BraveDude8 on Discord:
> group blocks are still broken but I think everything else is fine

I just tried and yes, blocked groups are still shown

**Comment by KaoticOblivion** [comment]
Just updating that blocked groups are still shown.

**Comment by kiriya-aoi** [comment]
Per this update, it's now functioning as expected. https://mangadex.org/thread/351011/9/#post_4292536
