### ISSUE TITLE
[Bug] <Manhwamanga.net>: <Search function not working>

### ISSUE THREAD

**Issue by xhugo92** [tachiyomiorg/tachiyomi-extensions#5350]
## Device information
- Tachiyomi version: Stable 0.10.7
- Android version: QPI30.73-33

## Source information
- Name: ManhwaManga.net
- Extension version: 1.2.2

## Steps to reproduce
1.  Install the source
2. Try to search any title

### Expected behavior
* The title searched shows 

### Actual behavior
* I get the http error 404

## Other details
* I already checked in web view and the site is working properly
* I can read and download the titles in the source

**Comment by OncePunchedMan** [comment]
working for me. try troubleshooting: https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis

**Comment by xhugo92** [comment]
Still not working after the troubleshooting. I will try to upload a video of the problem

**Comment by xhugo92** [comment]
Here is the video. Sorry for the trouble
https://drive.google.com/file/d/14EzAqo_7lxUI0vkbrWHlqv0uDOH7Gwri/view?usp=sharing
