### ISSUE TITLE
[Bug] Mangadex : Duplicates still showing up after blocking

### ISSUE THREAD

**Issue by NerouDesign** [tachiyomiorg/tachiyomi-extensions#5352]
## Device information
- Tachiyomi version: 10.7
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.100

## Steps to reproduce.2.
1. Go to Mangadex/library 
2. Click on any manga which has 2 scanlator groups

### Expected behavior
If blocked one, only the other group should show up

### Actual behavior
Can see both groups (in this case SSSS).

## Other details
I have even blocked the user which uploads the chapters.

**Comment by arkon** [comment]
#5341

**Comment by arkon** [comment]
@BraveDude8 Has this not been fixed on MangaDex's side yet?

**Comment by NerouDesign** [comment]
So we have to wait for md to fix it then.
