### ISSUE TITLE
[Bug] <Mangadex>: <Not Filtering Blocked Groups>

### ISSUE THREAD

**Issue by KaoticOblivion** [tachiyomiorg/tachiyomi-extensions#5354]
## Device information
- Tachiyomi version: App version: 0.10.7 (standard, c87ba62, 53)
Android version: 10 (SDK 29)

## Source information
- Name: Mangadex
- Extension version: 1.2.100
## Steps to reproduce
1. Have a blocked upload group on your mangadex account
2. Open a manga with recently added chapters they contributed
3. Their chapters no longer filtered out of Tachiyomi manga list

### Expected behavior
Expected that the blocked group would continue to not show up in the Manga's chapter list at all

### Actual behavior
The group's uploads are showing up in only Tachiyomi leading to inflated new chapter numbers for things that have not updated by the group's I'd actually want to read by

## Other details
Group shows up in Tachiyomi
![Screenshot_20210108-065043_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/8932192/104013317-4ed1c980-517f-11eb-8b57-9197a06acaa6.jpg)

Shown filtered out in Mangadex (opened in webview)
![Screenshot_20210108-065056_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/8932192/104013438-7032b580-517f-11eb-9a6b-04dafb3e96aa.jpg)

**Comment by OncePunchedMan** [comment]
#5341
