### ISSUE TITLE
[Bug] All FMReader sources: extra empty last chapter

### ISSUE THREAD

**Issue by AriaMoradi** [tachiyomiorg/tachiyomi-extensions#5358]
## Device information
- Tachiyomi version: stable
- Android version: 10

## Source information
- Name: Any FMReader (i.e. HeroScan, ManhuaScan)
- Extension version: 1.2.25

## Steps to reproduce
1. open any manga and look at the chapter list

### Expected behavior
All chapters should work

### Actual behavior
As described in the title, one extra empty chapter is added at the end.

**Comment by scb261** [comment]
It's not all sources, only some of them.
With empty chapter: ManhuaScan, ManhwaSmut, HeroScan
W/o empty chapter: Manhwa18, Manhwa18.net, LHTranslation
18LHPlus - down

**Comment by OncePunchedMan** [comment]
override fun chapterListSelector() = "div#list-chapters p, table.table tr, .list-chapters a"

".list-chapters a" is causing issues for some sites
