### ISSUE TITLE
[Bug] Mangadex: new chapters not loading

### ISSUE THREAD

**Issue by simo9466** [tachiyomiorg/tachiyomi-extensions#5361]
## Device information
- Tachiyomi version: 0.10.7 stable
- Android version: 7

## Source information
- Name: MangaDex
- Extension version: 1.2.100

## Steps to reproduce
1. Open a newly updated chapter (manga must be in library)

### Expected behavior
When opening a newly updated chapter (manga must be in library) the chapter loads normally.

### Actual behavior
When opening a newly updated chapter (manga must be in library) every page goes immediately to "Retry" and is stuck there.

**Comment by scb261** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5341#issuecomment-756815613

**Comment by Void2258** [comment]
I am also experiencing this since the update. It only effects the newest chapters. Not sure if that is due to upload time (after the update) or something about being the newest in particular. I added a few new ones to the library and every single chapter downloaded fine for these but the most recent. Every single on has this exact error on the most recent but no where else.

**Comment by indivisible** [comment]
Seems like only v2 api is broken on edited chapters, so reverting to the old one could fix the issue for now. The site uses that too, so them calling it deprecated is a bit misleading

**Comment by Void2258** [comment]
Most users don't know how to do that so you should patch to rest it until the new API actually works.

**Comment by indivisible** [comment]
Well I'm not a tachi dev, but I just tested that reinstalling the 97 version fixes the issue (after a chapter cache wipe), though it's not exactly user friendly

**Comment by Aedyrn** [comment]
Just tested some chapters that weren't loading yesterday after clearing cache and they're working now it seems. Make sure to clear cache as they wouldn't load without it clearing it.

**Comment by Z-WolF** [comment]
Yesterday some updates didn't download. Today all updates were downloaded. It looks like whatever issue was in mangadex side, is fixed now.

**Comment by CarlosEsco** [comment]
Mangadex fixed their api server. Also backing out was not an option because they're were removing the old end point
