### ISSUE TITLE
[Bug] Remanga: Viewing chapter error

### ISSUE THREAD

**Issue by dDmioko** [tachiyomiorg/tachiyomi-extensions#5365]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: Remanga
- Extension version: 1.2.11

## Steps to reproduce
1. Find manga "Strongest son-in-law"
2. Download chapter
3. Open downloaded chapter

### Expected behavior
View chapter

### Actual behavior
Throwing an exception "Pages not found"

## Other details
Manga link: https://api.remanga.org/api/titles/strongest-soninlaw/?from=search/
This error I only found in this particular manga.
I found out that the extension of the loaded pages is bin, not the extension of the image. Changing the extension to jpg solves the viewing issue.

**Comment by scb261** [comment]
What chapter? I tried chapter 25 and it's fine

**Comment by dDmioko** [comment]
All of this. About a month ago it worked for me too. I'll try to reinstall app

**Comment by dDmioko** [comment]
It downloads fine to internal storage. But the error occurs with the SDcard. Only for this manga bin extension does not change

**Comment by scb261** [comment]
Can't reproduce. Try deleting a chapter, clearing chapter cache in advanced settings, and re-downloading the chapter

**Comment by dDmioko** [comment]
It doesn't help. Thank you for advice

**Comment by dDmioko** [comment]
This issue has been solved
