### ISSUE TITLE
[Feature Request] Manhuagui: Add option to enable Traditional Chinese mode

### ISSUE THREAD

**Issue by null-von-sushi** [tachiyomiorg/tachiyomi-extensions#5366]
## What feature should be added to this source?

Please add an option to use the traditional version of the website instead of the simplified version. All the mangas I've tried are available in traditional already (though there might be some which originate from china which could be in simplified), however the description and chapter names are in simplified currently.

It would be nice if there was an option to use the tw.manhuagui.com domain instead. Thank you.

**Comment by sunbeams001** [comment]
Isn't it already implemented in the setting page?

**Comment by null-von-sushi** [comment]
Sorry, you are right. When I checked I might have accidentally tapped on manhuaDui instead of manhuaGui, so I thought that there are no settings 😅
