### ISSUE TITLE
[Bug] Mangadex: HTTP error 429 can't load any chapter

### ISSUE THREAD

**Issue by jdanielchg** [tachiyomiorg/tachiyomi-extensions#5373]
## Device information
- Tachiyomi version: stable 0.10.7
- Android version: android 10

## Source information
- Name: Mangadex
- Extension version: 1.2.100

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Should load chapters

### Actual behavior
Doesn't load the chapters and it says HTTP error 429.

## Other details
I can see the newest updates and all that, the only problem is that the chapters don't load.

**Comment by arkon** [comment]
This is an issue on MangaDex's side, but we'll keep this open so others don't open more issues.

There's nothing (good) that we can do from Tachiyomi's side to fix this.

**Comment by ldutra** [comment]
Do you have any idea of what’s happening in MangaDex, so perhaps we can pester them about it?

**Comment by indivisible** [comment]
Why is tachiyomi beta-testing the new api? Wouldn't it make sense to roll back, let MD dogfood it for themselves, and then re-enable it here once they have it working in their own web reader for 3 days?

**Comment by arkon** [comment]
Tachiyomi is a major source of traffic burden on their servers. We're in a catch 22 situation where if we don't migrate, their existing servers will experience more unavailability.

They've been fixing issues though. It's mostly down to caching issues now.

**Comment by ldutra** [comment]
So I understand they have a new API Tachiyomi must use, but it is unstable as of now?

**Comment by arkon** [comment]
That would be the simplest way of putting it, yes.

**Comment by CarlosEsco** [comment]
They made a change about an hour ago.  Once it's working again, if you get 429 again please open a new ticket

**Comment by ldutra** [comment]
Still failing here.

**Comment by CarlosEsco** [comment]
@ldutra you had 0 issues in last 2 hours and now are getting 429s or you still have 429s from earlier.  If it's the latter you have to wait til you are temp unbanned.

**Comment by ldutra** [comment]
Sorry, how that works?  Just wait two more hours from now?

Half an hour ago I tested a different device which I had not used for a few days and sure enough it gave me a 429.  Or is my account that must be unbanned?  How do I check it?

**Comment by CarlosEsco** [comment]
Wait til you are not getting 429s.  Just wait til tomorrow.  If you still aren't understanding join discord and ask there
