### ISSUE TITLE
[Bug] <lovehug.net>: <cant find owner contact info>

### ISSUE THREAD

**Issue by piyarad27** [tachiyomiorg/tachiyomi-extensions#5374]
All of device pc, tablet, iphone, android phone(not using tachiyomi app).
when I try to see the contact info (email address) of the site, the page would just go to the top of the home page. which in the old site the email address would place at the bottom of the page for everyone to see for easy contact to the site owner but now I cant seem to find where to contact the site owner.
p.s I was wondering if I face the site problem in lovehug site should I contact the site owner or contact here in this github

**Comment by OncePunchedMan** [comment]
We are not responsible for any site changes. pls try to contact them as we can't and won't do anything about this.
