### ISSUE TITLE
[Source Request] <Mangaku> and <HentaiManhwa>

### ISSUE THREAD

**Issue by farhanpurdi** [tachiyomiorg/tachiyomi-extensions#5380]
## Upadate Source Website
- Name: Mangaku
- Link: https://mangaku.pro/
- Language(s): Indonesia

## Source Website
- Name: Manhwa Hentai
- Link: https://manhwahentai.me/
- Language(s): English

**Comment by scb261** [comment]
Mangaku: exists with older domain, but there are other problems #2530
Manhwa Hentai: exists in a multi-source extension, check [the spreadsheet](https://tachiyomi.org/extensions-spreadsheet)

For future - open one issue per source
