### ISSUE TITLE
[Bug] <MangaDex>: Titles which are completed no longer show up as such in library after recent update

### ISSUE THREAD

**Issue by Puddintame349** [tachiyomiorg/tachiyomi-extensions#5382]
-Tachiyomi: v10.7 (Stable)
-Android 10

-MangaDex v1.2.100

After the recent extension update, all of the titles from MangaDex which are or were completed previous to the recent extension updates have suddenly disappeared when filtering for completed titles in the library. This, of course, includes when a title has had its final chapter uploaded, which is marked as such on the site. However, this has seemingly been messed up with the recent extension updates to MangaDex.

Tried reinstalling the extension to no avail, as well as clearing the cache for Tachiyomi.

**Comment by Puddintame349** [comment]
P.S. At the moment, I don't seem to be getting HTTP errors when trying to read the titles, just a lable problem

**Comment by Puddintame349** [comment]
P.P.S
I tried totally uninstalling Tachiyomi. After a backup restore, the problem persists.

**Comment by arkon** [comment]
The status isn't correctly set. Reinstalling the app won't make any difference until the extension is updated to address that.

**Comment by Puddintame349** [comment]
> The status isn't correctly set. Reinstalling the app won't make any difference until the extension is updated to address that.

Understood. Thought not, but I also I'd rule it out for certain.

**Comment by CarlosEsco** [comment]
This should be resolved with the https://github.com/tachiyomiorg/tachiyomi-extensions/pull/5456  can you verify @Puddintame349

**Comment by Puddintame349** [comment]
> This should be resolved with the #5456 can you verify @Puddintame349

Thanks. I had meant to, but kept forgetting. It is now solved
