### ISSUE TITLE
[Bug] <Komikcast>: <can't access the list of manga>

### ISSUE THREAD

**Issue by JustX1105** [tachiyomiorg/tachiyomi-extensions#5385]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 5

## Source information
- Name: Komikcast (Indonesia)
- Extension version: 1.2.4

## Steps to reproduce
1. Just open the explorer
2. ...

### Expected behavior
Show the manga list

### Actual behavior
Extension doesn't show the list of manga. It Show java.lang.Exception:Gagal untuk menembus Cloudflare

## Other details
----

**Comment by scb261** [comment]
Open in WebView to bypass Cloudflare https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-a-captcha

**Comment by Riztard** [comment]
sama itu juga, pake komikCast yang ada di "wp MangaStream" aja, soalnya kemungkinan bakal kehapus yang ekstensi sendiri, kalo rusak juga paling yang dibenerin yang di "wp MangaStream" doang

**Comment by scb261** [comment]
Should be closed
