### ISSUE TITLE
[Bug] <himera fansub>: <download error>

### ISSUE THREAD

**Issue by shadoupasu** [tachiyomiorg/tachiyomi-extensions#5387]
## Device information
- Tachiyomi version: 10.7
- Android version: 8.0.0

## Source information
- Name: himera fansub
- Extension version: 1.2.166

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Opened or download chapter

### Actual behavior
Not Opened or download chapter

**Comment by scb261** [comment]
Works for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). If won't help - specify what manga and chapter has the issue.

P.S. You should always update your extension before reporting it

**Comment by scb261** [comment]
No steps to reproduce and no answer from the author for a month
