### ISSUE TITLE
Do you know how to contact lovehug?

### ISSUE THREAD

**Issue by piyarad27** [tachiyomiorg/tachiyomi-extensions#5388]
We are not responsible for any site changes. pls try to contact them as we can't and won't do anything about this.

_Originally posted by @OncePunchedMan in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5374#issuecomment-757705445_

Is what i get in the reply but I can seem to find the way to contact the site owner so please tell me if you know how

**Comment by CarlosEsco** [comment]
Stop opening issues, we are not affiliated with sites we don't know their contact info
