### ISSUE TITLE
Mangadraft

### ISSUE THREAD

**Issue by Zealest** [tachiyomiorg/tachiyomi-extensions#5390]
## Source Website
- Name: Mangadraft
- Link: https://www.mangadraft.com/
- Language(s): French

## Details
Free platform for publishing manga/bd/webtoon/lightnovel, primarly intended for amateurs.
It is a good source for discovering all kinds of writings and illustrations.

**Comment by as280093** [comment]
ICONS: [MangaDraft.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/5829648/MangaDraft.zip)
