### ISSUE TITLE
[Bug] <Kumanga (ES)>: <Not loading list of mangas>

### ISSUE THREAD

**Issue by arqeli** [tachiyomiorg/tachiyomi-extensions#5406]
## Device information
- Tachiyomi version: stable 0.10.7
- Android version: 7.1.1

## Source information
- Name: Kumanga (ES)
- Extension version: 1.2.5

## Steps to reproduce
1. Open the extension

### Expected behavior
Load list of mangas

### Actual behavior
Not load any manga

## Other details
![Screenshot_20210113-185230~01](https://user-images.githubusercontent.com/77376228/104531380-aafb7a00-55d3-11eb-8a09-b12bca0a0b24.png)

**Comment by scb261** [comment]
Looks like they're blocking tachi. Translated from webview:
> We have detected a possible unsafe action so we have blocked your access to the page.
