### ISSUE TITLE
[Feature Request] Komga: use the library feature

### ISSUE THREAD

**Issue by lbesnard** [tachiyomiorg/tachiyomi-extensions#5410]
## What feature should be added to this source?

Komga server offers the possibility to have multiple libraries. However, under the tachiyomi app, all the libraries seemed to be merged into a single one, which makes it harder to:

1) search for comics under a specific library
2) scroll individually through libraries

I tend to create libraries per comics style (manga, comics, BD(french comics)) as well as languages my comics are in.

@gotson

**Comment by gotson** [comment]
You can already filter by library in the Tachiyomi extension for Komga.

![Screenshot_20210114-134624](https://user-images.githubusercontent.com/2139133/104550022-ec8d3300-566e-11eb-9db9-45dc09319043.jpg)

**Comment by lbesnard** [comment]
ah damn! thanks a lot. I completely missed this feature!
