### ISSUE TITLE
[Bug] Failed updates MangaLib

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi-extensions#5415]
Unsuccessful library manga updates 
Very frequent updates and site errors within the app 
content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_update_errors.txt
It's a reference to a mistake
---

## Device information
* Tachiyomi version: 10.7
* Android version: 9
* Device: Honor 9 lite

## Steps to reproduce
1. Open the app
2. Check out the manga update

### Expected behavior
This should happen.

### Actual behavior
![Screenshot_20210114_150055_com android chrome](https://user-images.githubusercontent.com/71752683/104588410-5f031080-5679-11eb-95ab-033f902c2059.jpg)

This happened instead.

## Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Transferred this to extensions because this seems to be a mangalib issue

**Comment by MM001-r** [comment]
What can I do?

**Comment by MM001-r** [comment]
Where are the extensions?

**Comment by CarlosEsco** [comment]
you opened the issue on the wrong respository (which is why i moved it to https://github.com/tachiyomiorg/tachiyomi-extensions)
Wait until one of the russian contributors responds or fixes the issue

**Comment by VlasovRoman** [comment]
There is many problems with this website last time.

**Comment by Kugumin** [comment]
It seem to be like API changes from their side. Waiting for the fix. 

Didn't see and made issue too #5426

**Comment by CarlosEsco** [comment]
@Kugumin post that ticket info here

**Comment by Kugumin** [comment]
Getting this when trying to update any manga from Mangalib
![Screenshot_2021-01-15-09-17-23-171_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/42800753/104823473-ef487d80-5852-11eb-85e9-5bd9d66841e0.jpg)

**Comment by arkon** [comment]
Addressed by #5460
