### ISSUE TITLE
[Source Request] <Blacktoon>

### ISSUE THREAD

**Issue by akmalmeaw** [tachiyomiorg/tachiyomi-extensions#5417]
**PLEASE READ THIS**

I wanted this korean extention named Blacktoon. I'ts a good extention. Please do it as fast as you can
---

## Source Website
- Name: blacktoon
- Link:https://blacktoon97.com
-  Language(s):korean

**Comment by vetleledaal** [comment]
Site redirects to some ads
Parked since at least 2022-02-08 according to whois, site was probably not available since at least nov 28 2021 according to wayback machine

**Comment by Seishirou101** [comment]
You can open a new issue if the site ever comes back.
