### ISSUE TITLE
[Bug] <Bulu Manga>: <Lee Doona! chapter 65-67 won't load after the latest update>

### ISSUE THREAD

**Issue by amarufi** [tachiyomiorg/tachiyomi-extensions#5429]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 9

## Source information
- Name: Bulu Manga
- Extension version: 1.2.4

## Steps to reproduce
1. Open the app
2. Open zBulu extension
3. Open Bulu Manga source
4. Search manhwa Lee Doona!

### Expected behavior
All chapter should appear because this morning I received notification that my last issue of this has been fixed.

### Actual behavior
Chapter 65-67 won't load on app, only chapter 64 and 68 that load successfully.

## Other details
Retry notification appears when I click chapter 65-67.
![Screenshot_20210115-071554_Tachiyomi.jpg](https://user-images.githubusercontent.com/77256895/104735127-cdc49480-5773-11eb-92d3-f636ec7415a6.jpg)![Screenshot_20210115-071610_Tachiyomi.jpg](https://user-images.githubusercontent.com/77256895/104735141-d1f0b200-5773-11eb-83ea-5706b6991121.jpg)![Screenshot_20210115-071641_Tachiyomi.jpg](https://user-images.githubusercontent.com/77256895/104735148-d6b56600-5773-11eb-9be3-dbb96ddb9ee9.jpg)

**Comment by Riztard** [comment]
working for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by amarufi** [comment]
> working for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

It works! Thank you, sir
