### ISSUE TITLE
[Bug] <Webtoons>: <Cannot parse date for the spanish version>

### ISSUE THREAD

**Issue by arqeli** [tachiyomiorg/tachiyomi-extensions#5433]
## Device information
- Tachiyomi version: stable 0.10.7
- Android version: 7.1.1

## Source information
- Name: Webtoons (ES)
- Extension version: 1.2.24

## Steps to reproduce
1. First Step: Browse comic from Webtoons.com (Spanish) 
2. Second Step: Select any comic

### Expected behavior
The comic page will open, and the chapter list will be displayed.

### Actual behavior
An error "Unparsable date " will appear, and Tachiyomi will fail to get the comic's chapter list. An example of the date format is "27-sep-2020"
## Other details
![Screenshot_20210114-130404~01](https://user-images.githubusercontent.com/77376228/104761663-d9d73480-5728-11eb-9679-c695bfd3eaff.png)

**Comment by Riztard** [comment]
i think someone try to fix it before, i guess he didnt build/check if it actually fix the issue :/
wait for someone to fix it

**Comment by arqeli** [comment]
@Riztard Thank you! I will wait 😊

**Comment by arqeli** [comment]
THANK YOU! ☺️💕
