### ISSUE TITLE
[Bug] <Bug extension>: <Ninemanga>

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi-extensions#5438]
Ninemanga extension crashed in app

**Comment by Deserada** [comment]
![Screenshot_20210116-034919](https://user-images.githubusercontent.com/49881846/104794039-d6d25780-57ad-11eb-9eef-e1a2f9aeb63f.jpg)

Its saying something like this when trying to open any manga ep

**Comment by arkon** [comment]
Closing in favour of #5439, which has more information from the template.
