### ISSUE TITLE
[Bug] <Webtoon>: <Chapter numbers are 1 off for webtoon with Prologue, messing up tracking too>

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#5450]
## Device information
- Tachiyomi version: v0.10.6
- Android version: 10

## Source information
- Name: Webtoon
- Extension version: ?

## Steps to reproduce
1. Look for webtoon with Chapter 0 or Prologue 
2. EX: unOrdinary (has Prologue)
3. True Beauty (has Chapter 0)
4. Omniscient Reader (is marked as Chapter 0 and Prologue) 
2. (Not all webtoons have Chapter 0/Prologue)

### Expected behavior
Webtoons with Chapter 0 or Prologue should start off as Chapter 0, not as Chapter 1. 

After reading Chapter 1 or Prologue, tracking should not be marked as read chapter 1.

### Actual behavior
Webtoons with Chapter 0 or Prologue should be started as chapter 0 so the numbers are not off. Tracking also uses Tachiyomi's numbering of chapters

**Comment by vipzzx** [comment]
[]()![Screenshot_20210116-033429_Tachiyomi.jpg](https://user-images.githubusercontent.com/59638889/104807280-d20ca400-57ab-11eb-9d3b-497b872db79c.jpg)![Screenshot_20210116-033433_Tachiyomi.jpg](https://user-images.githubusercontent.com/59638889/104807282-d3d66780-57ab-11eb-8fc4-5f767dcd0beb.jpg)

**Comment by vipzzx** [comment]
![Screenshot_20210116-033553_Tachiyomi.jpg](https://user-images.githubusercontent.com/59638889/104807299-fd8f8e80-57ab-11eb-8a42-6ffabb9e49a2.jpg)

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/104807523-34988b00-5812-11eb-8ae6-f9fec690d2de.png)
it is chapter 1

**Comment by vipzzx** [comment]
but shouldnt it be matching the episode and not the chapter?

**Comment by vipzzx** [comment]
its rather in consistent because if it is another source that has Chapter 0 or a Prologue it does not mark it as Ch.1 
Ex. National School Prince is a Girl in S2Manga extension. Ch 0 is marked as Ch 0 and does not mess up the tracking either

**Comment by Arraiment** [comment]
The extension displays chapter titles by appending "Ch. #" to the end of the chapter title displayed on the webtoons site. I would think its meant to allow users to see the exact numerical order of the chapter list, regardless of what fancy titles the chapters have. Would you prefer if only the chapter title was shown without the "Ch. #"?

> Ch 0 is marked as Ch 0 and does not mess up the tracking either

As for tracking I'm not sure if it would be sensible to mark chapter 0 as 0 chapters in the tracker. You have read one chapter after all, just that the title of the chapter happens to be "Chapter 0"
