### ISSUE TITLE
[Source Request] <Rawdevart & MangaRaw>

### ISSUE THREAD

**Issue by skyususkhhko** [tachiyomiorg/tachiyomi-extensions#5451]
## Source Website
- Name: Rawdevart & MangaRaw
- Link: https://rawdevart.com/ - https://www.manga-raw.club/
- Language(s): All

## Other Details
-

**Comment by Riztard** [comment]
raw devart aready added 
mangaraw uplicate of #3754

**Comment by skyususkhhko** [comment]
> raw devart aready added
> mangaraw uplicate of #3754

can you add it?(manga-raw.club)
