### ISSUE TITLE
[Bug] <NineManga>: <Cuando entro a la extensión de NineManga e intento cargar un manga me aparece vacío, y me arroja un error "Unable to Resolve Host 'es.ninemanga.comhttps' no address associated with Host name">

### ISSUE THREAD

**Issue by kurozakii** [tachiyomiorg/tachiyomi-extensions#5454]
## Device information
- Tachiyomi version: v0.10.7
- Android version: 7.1.1

## Source information
- Name: NineManga
- Extension version: 1.2.12

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by scb261** [comment]
Duplicate of #5439
