### ISSUE TITLE
[Bug] <ninemanga(EN)>: <can't open or download>

### ISSUE THREAD

**Issue by thegreatdk** [tachiyomiorg/tachiyomi-extensions#5455]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: ninemanga (EN)
- Extension version: 1.2.12

## Steps to reproduce
1. Open app
2. open / download manga from ninemanga(the one I used is using english)
3. error message will come out

### Expected behavior
Can read manga normally

### Actual behavior
Error message will come out, the error is too long, if anybody know where the log file is please tell me that will be helpful, I will copy the message, but I provide the screenshot when it happrns

## other
![Screenshot_20210116-203200_Tachiyomi](https://user-images.githubusercontent.com/47343103/104813155-f747f380-5839-11eb-8c38-1ff03a9b744a.jpg)

**Comment by scb261** [comment]
Duplicate of #5439

**Comment by thegreatdk** [comment]
@scb261 i'm sorry if im wrong, is it really the same error? The error message are different, and i can open via web perfectly fine, once again im sorry if im wrong

**Comment by scb261** [comment]
The reason is probably the same, just the app using some cached/saved data and thus returns different error. Wait for update and see if it's still happening. Or maybe @Riztard could check if the error happens in his PR.

**Comment by thegreatdk** [comment]
Ok will wait for the update then, thank you. @Riztard if you could, please also help to check this one, i would be grateful, thank you

**Comment by Riztard** [comment]
if its chapter 14 of that manga, can download it just fine

**Comment by thegreatdk** [comment]
Ok after updating now it works, thank you all
