### ISSUE TITLE
[Feature Request] Madara: Non Manga filter

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#5459]
## What feature should be added to this source?
A detection mechanism that detect if a result is not a manga and then removes it from the search result in the case that it is not a manga. 
Some sources like Astral Libary have both mangas and novels and the novels are turning up in the search results together.

**Comment by alessandrojean** [comment]
Good to mention Madara itself doesn't have a type filter in the search, and does not put the type in the classes when using search. Although it is possible to filter in popular and latest (like it's done currently), these novels/video entries will always appears on search results.

**Comment by FourTOne5** [comment]
Wasn't this implemented?

**Comment by alessandrojean** [comment]
Yes, didn't even know back then there was an issue about it, so I didn't link it in the PR. Closing 👍🏻.
