### ISSUE TITLE
[Meta] <Export of the Tachiyomi list And sorting out the research >

### ISSUE THREAD

**Issue by MChaman** [tachiyomiorg/tachiyomi-extensions#5461]
Good morning,
I use tachiyomi regularly and I would like to address two points that can be improve. The impossibility of exporting my entire list on a platform such as myanimelist, with over 1000 manga in my list I can not reread them all individually for it to sync with my account. I searched if this was possible but I found nothing, hoping not to have missed it! :) 
The second is having to sort my search every time I open an extension like mangadex. If my search sort could be back up it would be more comfortable. 
Here, thank you for reading me, hoping that my post serves something
Have a nice day. 

##  Why/Project's Benefit/Existing Problem

More comfortable for the user. 

## Other Details 
I love your work.

**Comment by scb261** [comment]
First of all, wrong repo, see https://github.com/tachiyomiorg/tachiyomi . Also you should open separate issues for separate feature requests. But still:
1. There is no way for the app to know corresponding tracking entries without manual setup, thus there is no way to implement exporting to a tracking service without manually linking each manga to the right entry. And manual setup already saves it to your account.
2. Save search and filters already requested in the right repository https://github.com/tachiyomiorg/tachiyomi/issues/779 https://github.com/tachiyomiorg/tachiyomi/issues/1484
