### ISSUE TITLE
[Bug] <FoolSlide - GTO The Great Site>: <player and domain changed>

### ISSUE THREAD

**Issue by sbarrusa** [tachiyomiorg/tachiyomi-extensions#5472]
## Source information
- Name: FoolSlide - GTO The Great Site

### Expected behavior
it should also show the new chapters

### Actual behavior
it only shows chapters released until January 4, 2021

## Other details
the site changed players and went from FoolSlide to a MangaDex-like player.
domain changed from https://www.gtothegreatsite.net/reader/ to https://reader.gtothegreatsite.net/comics

**Comment by alessandrojean** [comment]
Fixed by #8734.
