### ISSUE TITLE
TuMangaOnline: Http Error 429

### ISSUE THREAD

**Issue by J-VF** [tachiyomiorg/tachiyomi-extensions#5479]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: TuMangaOnline (Spanish)
- Extension version: 1.2.29

## Steps to reproduce
One of the forms to reproduce the bug is:
1. Search a Manga With 600 Chapters or more (Bleach for example)
2. Download all Chapters

### Expected behavior
All Chapter Should be Download

### Actual behavior
Http error 429

## Other details
Sorry for my English, I speak spanish

**Comment by OncePunchedMan** [comment]
error 429 means "too many requests"
download your manga in steps of like 10-20 chapters each time and let it finish downloading before starting another download

translated with DEEPL:
el error 429 significa "demasiadas solicitudes"
descarga tu manga en pasos de 10-20 capítulos cada vez y deja que termine de descargarse antes de empezar otra descarga

**Comment by arkon** [comment]
Should look into the rate limiting in the extension to try to avoid spamming the site.

**Comment by J-VF** [comment]
> error 429 means "too many requests"
> download your manga in steps of like 10-20 chapters each time and let it finish downloading before starting another download
> 
> translated with DEEPL:
> el error 429 significa "demasiadas solicitudes"
> descarga tu manga en pasos de 10-20 capítulos cada vez y deja que termine de descargarse antes de empezar otra descarga

It's not only that, when I update the library, it doesn't update all the manga.
