### ISSUE TITLE
[Bug] Komga: can't display publisher's name

### ISSUE THREAD

**Issue by raining1123** [tachiyomiorg/tachiyomi-extensions#5481]
whatever how I modify Publisher/Editors/Writers/Pencillers/Inkers... in Komga , it only display "Unknown author" in the source page.
the same as th Language.
![Screenshot_20210119_102304](https://user-images.githubusercontent.com/17892238/104980006-92121f00-5a40-11eb-914a-ee019440fe41.jpg)

**Comment by gotson** [comment]
It's not a bug, it's not implemented, that's all.

**Comment by gotson** [comment]
I think the language is coming from the source, not the manga itself, no?
