### ISSUE TITLE
[Bug] ManaToki: Latest/search function down

### ISSUE THREAD

**Issue by Yun-ssi** [tachiyomiorg/tachiyomi-extensions#5505]
## Device information
- Tachiyomi version:  stable 0.10.7
- Android version: 7

## Source information
- Name: Manatoki
- Extension version: 1.2.19

## Steps to reproduce
1. Clicked on Manatoki extension to see Latest/Search.  Page told me, "No results found." 
2. Opened in WebView. URL redirects to manatoki94.net (currently set to manatoki102.net). Changed to 94/reset app. Same results. 

### Expected behavior
Expected the Latest/Search to show lists of manga without having to Open in WebView
Changing URL usually brings up Latest/Search

### Actual behavior
Latest/Search don't work anymore.

## Other details
Accessing/updating manga still works if the user has them on favorite. This works for 94 and 102. 
Feature was working, until today on Jan 21, 2021.

**Comment by DitFranXX** [comment]
It's working on my side. Please check the extension settings. ManaToki's Latest is opt-in feature since it has bit problem within.

**Comment by scb261** [comment]
Both search and latest are working for me. As said above, Latest can be enabled in extension settings as experimental feature, so do expect issues with it (though I don't have any). You could try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis) if you have issues with searching.
