### ISSUE TITLE
[Feature Request] <Desu, Remanga...>: <redirect from api>

### ISSUE THREAD

**Issue by e-shl** [tachiyomiorg/tachiyomi-extensions#5511]
This is not really a suggestion, but I would like to know how to redirect from api to a page with manga?
For these sources 
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt

**Comment by mlneko** [comment]
![image](https://user-images.githubusercontent.com/70600003/105464774-b8cb9200-5c9a-11eb-88ac-6bd1929e102c.png)
![image](https://user-images.githubusercontent.com/70600003/105464784-bcf7af80-5c9a-11eb-8f9a-214286247ce1.png)
сам задал - сам ответил))
по котлину не шарю, так бы кинул готовое
получаешь из json-а выделенный dir и подставляешь в формате https://remanga.org/manga/{dir}

**Comment by mlneko** [comment]
с desu.me ещё проще:
![image](https://user-images.githubusercontent.com/70600003/105465783-0bf21480-5c9c-11eb-9f93-3c00cb1ae21a.png)

**Comment by OncePunchedMan** [comment]
you want the source not to use the apis?

you'd have to change the urls and some other functions. basically you could just copy from another source and set the html tags and urls and so on correctly

**Comment by e-shl** [comment]
@OncePunchedMan, no, I want the api to be used, but open the manga page via webview or share

**Comment by OncePunchedMan** [comment]
i see

**Comment by arkon** [comment]
You can refer to how MangaPlus does it: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/b32647e7023b8bc13063f68bacf58edb01c1b5ea/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt#L188-L195
