### ISSUE TITLE
[Bug] Mangadex: Latest/Browse are very slow

### ISSUE THREAD

**Issue by TheUnlocked** [tachiyomiorg/tachiyomi-extensions#5513]
## Device information
- Tachiyomi version: r3013
- Android version: 9

## Source information
- Name: Mangadex
- Extension version: 1.2.102

## Steps to reproduce
1. View Browse or Latest

### Expected behavior
Loads quickly, so that it is easy to browse.

### Actual behavior
Thumbnails take a very long time to load and hold back loading additional pages of manga.

## Other details
Loading these pages works perfectly fine on webview. This is almost certainly a result of #5507; Neko seems to be experiencing the same issue. From a quick glance at the code it seems like thumbnails are being rate limited, but I'm somewhat skeptical that Mangadex actually counts thumbnail downloads against the rate limits (some tests on my local machine find no issue with trying to download 100 thumbnails in one second).

It could also be something else causing the issue, but regardless it seems likely to be a bug that can be resolved.

**Comment by OncePunchedMan** [comment]
we changed the rate limiting so it wouldn't throw a lot of 429s. we are aware that it slows down dex, but we won't get so many 429s

**Comment by TheUnlocked** [comment]
Created https://github.com/TheUnlocked/tachiyomi-extensions/tree/mangadex-remove-thumbnail-rate-limits to try out excluding thumbnails from the rate limits. It performs much faster and looking at logcat I don't see any 429s even when scrolling extremely quickly (though I could also be looking in the wrong place). Unless there's some other issue with this that someone can think of and I'm not seeing, I'll PR.
