### ISSUE TITLE
[Bug] <Mangakawaii [FR]>: <No page found on any manga>

### ISSUE THREAD

**Issue by Zealest** [tachiyomiorg/tachiyomi-extensions#5518]
## Device information
- Tachiyomi version: r3013
- Android version: 10

## Source information
- Name: Mangakawaii
- Extension version: 1.2.13

### Actual behavior
I tested with 3 different manga and I had the same error for all 3. The chapters are displayed correctly but when you open any of them an error shows up "No page found".

*I don't know what could cause that, maybe that's because the site is updating regularly or its blocking Tachiyomi (?).*

`Last issue related to Mangakawaii` #5284

**Comment by Moineuh** [comment]
I have the same issue. Webview is working well. All troubleshooting tests have been done on my side.

**Comment by Zealest** [comment]
thanks!!
