### ISSUE TITLE
[Bug] Mangahere: chapters show only 5 pages instead the comlete version

### ISSUE THREAD

**Issue by mrey666** [tachiyomiorg/tachiyomi-extensions#5531]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 9

## Source information
- Name: Mangahere
- Extension version: 1.2.15 English

## Steps to reproduce
1. Open a new chapter. For example Martial Peak 918
2. It's only 5 pages long instead of the full chapter.
3. This issue has happed to me in other new chapter too but never hapoened before.

### Expected behavior
The chapter has all the pages it should.

### Actual behavior
The chapters has 5 pages (exactly, every time) instead of the full chapter.

**Comment by Seishirou101** [comment]
It's the same thing on the website.
Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
![Screenshot_20210123-174930703 (1)](https://user-images.githubusercontent.com/57241064/105617387-6924bd80-5da3-11eb-83fd-3edb98285b3f.jpg)
