### ISSUE TITLE
[Bug] <copymanga extension>: <crash to desktop when loading>

### ISSUE THREAD

**Issue by star2056** [tachiyomiorg/tachiyomi-extensions#5544]
## Device information
- Tachiyomi version: stae 0.10.7
- Android version: 6.0

## Source information
- Name: copymanga 插件
- Extension version: 1.2.4

## Steps to reproduce
1. First Step 点击浏览，点击图源
2. Second Step 点进漫画等待载入完毕

### Expected behavior
漫画信息本应被完整载入完毕

### Actual behavior
应用程序跳出，回到手机桌面

## Other details
none

**Comment by sunbeams001** [comment]
Please provide crash logs. Extension can't cause App crash, generally.
FYI
https://github.com/tachiyomiorg/tachiyomi/issues/4326#issuecomment-764791148

**Comment by star2056** [comment]
> Please provide crash logs. Extension can't cause App crash, generally.
> FYI
> [tachiyomiorg/tachiyomi#4326 (comment)](https://github.com/tachiyomiorg/tachiyomi/issues/4326#issuecomment-764791148)

Log uploaded.
https://pastebin.ubuntu.com/p/wxCXDGHhqM/
If you need original txt please tell me I'll send via netdisk.

**Comment by sunbeams001** [comment]
@star2056 Got it, gonna fix it soon.

**Comment by star2056** [comment]
@sunbeams001 thanks.
