### ISSUE TITLE
nHentai browse in WebView open in tachiyomi: when browsing in webview allow a button to switch tachiyomi view for url of current manga

### ISSUE THREAD

**Issue by MatteCrystal** [tachiyomiorg/tachiyomi-extensions#5545]
nHentai browsing in tachiyomi can be a bit limiting. I often find myself browsing in webview, finding a manga I like, copying it's name then fully exiting out of webview and manually searching the name in tachiyomi app in order to favorite it. 

not only is this a lengthy and annoying process but It also causes you to lose your place in the webview meaning if you were on page 5 of some specific search and there were 2 manga u were interested in you would have to enter webview again, search the tags, and navigate to page 5 again.

It would be better if the browser was just a normal webpage that could be opened and closed at any time and retain it's last position on the website, as well as back button functionally. While at the same time having a dedicated button to open the current manga the webpage is on in the tachiyomi app.

**Comment by arkon** [comment]
WebView isn't really meant to be that fully featured and is more so a tool to let users solve CAPTCHAs and such. You should just use a separate browser.

**Comment by MatteCrystal** [comment]
It shouldn't really be an "advanced feature" In the app you can click to view the manga in webview which just points the browser to a url. Why not vis versa?

**Comment by scb261** [comment]
It's hard (if not impossible) to implement. If you think that some filter or sorting is missing - you can request it to make browsing in the app less limiting
