### ISSUE TITLE
[Source Request] <Novel Mania>

### ISSUE THREAD

**Issue by Bee-Hachi** [tachiyomiorg/tachiyomi-extensions#5551]
## Source website
- Name: Novel Mania
- Link: https://novelmania.com.br/
- Language(s): Português Brasileiro (Brazilian Portuguese)

## Other details 
Sinto falta de uma extensão de novels em português :/

**Comment by Riztard** [comment]
i dont see any manga, so...

Will Tachiyomi ever support Light Novels?
No, Tachiyomi is designed as an image parser, not a text parser, so there will never be any support for Light Novels.
