### ISSUE TITLE
[Bug] <Mangadex>: <Blocked groups showing up>

### ISSUE THREAD

**Issue by kmqx** [tachiyomiorg/tachiyomi-extensions#5555]
## Device information
- Tachiyomi version: stable 0.10.7
- Android version: 10

## Source information
- Name: Mangadex
- Extension version:  1.2.103

## Steps to reproduce
1. Clear Cookies/ Clear Database
2. Relogin to mangadex from webview

### Expected behavior
The blocked groups should have been filtered

### Actual behavior
The blocked groups are not filtered

**Comment by scb261** [comment]
If you blocked them recently, then it's probably mangadex api server cache issue, nothing can be done on the extension side

**Comment by CarlosEsco** [comment]
See above
