### ISSUE TITLE
[Bug] <FoolSlide>: <Phoenix scans site change>

### ISSUE THREAD

**Issue by Satorou** [tachiyomiorg/tachiyomi-extensions#5561]
The site of the phoenix scans (Italian team) has changed its domain and consequently on FoolSlide they are not seen the chapters... I hope it can be solved, thanks a lot!

**Comment by scb261** [comment]
I guess https://www.phoenixscans.com/ is the new site?

**Comment by Satorou** [comment]
Yes it is that!
