### ISSUE TITLE
[Source Request] <TruyenTranh8>

### ISSUE THREAD

**Issue by huynhthang9697** [tachiyomiorg/tachiyomi-extensions#5575]
## Source website
- Name: TruyenTranh8
- Link: mangaxy.com
- Language(s): Vietnamese

## Other details
It has continuation of manga not found in other sources.

**Comment by hotboymrt** [comment]
@scb261 But i didn't find it on tachiyomi

**Comment by scb261** [comment]
@hotboymrt because no-one added it yet, and it's unknown when someone will
