### ISSUE TITLE
[Bug] <ngomik>: <no results found>

### ISSUE THREAD

**Issue by nancysavchenkoo** [tachiyomiorg/tachiyomi-extensions#5576]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10

## Source information
- Name: ngomik
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

## Other details
Extension bahasa indonesia

**Comment by Riztard** [comment]
kenapa bambang, gue bisa aja search. jelasi / kasi contoh

**Comment by nancysavchenkoo** [comment]
> kenapa bambang, gue bisa aja search. jelasi / kasi contoh

Ngga muncul bro daftar manganya, cuman keluar tulisan = no results found

**Comment by Riztard** [comment]
kau nge search apa? kalo browse/latest bisa aja di punya aing
coba [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)
