### ISSUE TITLE
[Source Request] <two sources>

### ISSUE THREAD

**Issue by shadoupasu** [tachiyomiorg/tachiyomi-extensions#5587]
## Source website
- Name: mangawow and mangagecesi
- Link: www.mangawow.net , www.mangagecesi.com
- Language(s): tr

## Other details
Can you send me these resources after adding them?
because site owners want it removed
I want to add it myself but don't know how to code
emperorsama61@gmail.com

**Comment by CarlosEsco** [comment]
nobody is making the extension and then sending them to you.  You also shouldnt just post your email address on a public forum...
