### ISSUE TITLE
[Bug] <nHentai.com(unoriginal)>: <http error  manga>

### ISSUE THREAD

**Issue by bellpeppr** [tachiyomiorg/tachiyomi-extensions#5595]
![Screenshot_20210130-193316_Tachiyomi](https://user-images.githubusercontent.com/78259219/106355331-1bbfc780-6332-11eb-84e7-b8488f2cd9d4.jpg)
Extension name: nHentai.com (unoriginal)
Problem: All manga shows "http error"
Example: this manga (https://nhentai.com/zh/comic/nise-my-exciting-high-school-debut-lets-join-the-manga-club) will be redirected to this (https://nhentai.com/en/webtoon/nise-my-exciting-high-school-debut-lets-join-the-manga-club?nsfw=false) in the app. The page doesnt exist.

**Comment by scb261** [comment]
Does it still happen if you log in via WebView?

**Comment by bellpeppr** [comment]
> Does it still happen if you log in via WebView?

That screen shot is the web view
