### ISSUE TITLE
[Bug] Tapas: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by Trobador** [tachiyomiorg/tachiyomi-extensions#5600]
## Device information:
App version: 0.10.7-3045 (standard, 8a668ba7, 54)
Android version: 10 (SDK 29)
Android build ID: QKQ1.200512.002 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: surya
Device model: M2007J20CG
Device product name: surya_eea

## Source information
- Name: Tapas (English)
- Extension version: 1.2.10

## Steps to reproduce
1. Have the Tapas extension installed and one or more Tapas comics in your library
2. Update chapters

### Expected behavior
The Tapas comics' chapter lists should be updated

### Actual behavior
Tachiyomi fails to update the Tapas comics' chapter lists; error log says "Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive"

## Other details
Other sources update properly; reinstalling the extension did not help

EDIT: nothing to add, just want to give thanks to the maintainers and contributors for their work on the app

**Comment by ardittristan** [comment]
Tapas search also doesn't seem to function for me

**Comment by Arraiment** [comment]
Hey so I'm working on an update for this extension, @Trobador do you still encounter this issue? If so which comic specifically?

**Comment by Trobador** [comment]
> Hey so I'm working on an update for this extension, @Trobador do you still encounter this issue? If so which comic specifically?

Nope, no longer happening. Tapas comics now seem to updare just fine.

**Comment by curche** [comment]
Closing since the issue doesn't happen anymore
