### ISSUE TITLE
[Bug] Viz Shonen Jump: Moriarty the patriot not downloading

### ISSUE THREAD

**Issue by Cwavs** [tachiyomiorg/tachiyomi-extensions#5602]
## Device information
- Tachiyomi version: J2K 1.0.10
- Android version: 10

## Source information
- Name: Viz Shonen Jump
- Extension version: 1.2.5

## Steps to reproduce
1. Open Moriarty the patriot
2. Download any volume 2 chapter

### Expected behavior
Chapter is unlocked with Shonen Jump subscription if it isn't already and downloaded.

### Actual behavior
Unlocks and starts downloading, hangs on the last page and then errors.

## Other details
I get an error when opening the manga in the app or refreshing that says "Attempt to invoke virtual method 'java.lang.String.org.jsoup.nodes.Element.text()' on a null object ref" (the error was cut off by the pop up it was in)

As far as I can tell this is specific to Moriarty the patriot, I tried a few other chapters and series and I didn't get the same error.

**Comment by alessandrojean** [comment]
Probably will be fixed by #5604.

I can't really test if it fixes the chapter error because I am not a VIZ subscriber, but it probably will.

If after the update you still face this, open a new issue please.
