### ISSUE TITLE
[Bug] <Toonily / skymanga (madara).>: <Error message.>

### ISSUE THREAD

**Issue by yamato44** [tachiyomiorg/tachiyomi-extensions#5605]
## Device information
* Tachiyomi version: 0.10.7.
* Android version: 5.
* Device: samsung.

## Source information
* Source name: Toonily / skymanga (madara).
* Source extension version: 1.2.176

## Steps to reproduce
1. Open toonily or skymanga .
2. Error message.

## Issue/Request
when i open toonily or skymanga it load for a few moments and gives this message ( java.lang. Expection: Failed to bypass cloudflare ).

## Other details
Other sources update properly.

**Comment by scb261** [comment]
Open webview to bypass cloudflare https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-the-cloudflare-issue

**Comment by yamato44** [comment]
but i want to download chapters

**Comment by yamato44** [comment]
> Open webview to bypass cloudflare https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-the-cloudflare-issue

the problem is still appearing even if i did what you said
![Screenshot_2021-01-31-18-22-50](https://user-images.githubusercontent.com/77173618/106392728-681f0c00-63f3-11eb-9ac9-090cde4d609a.png)

![Screenshot_2021-01-31-18-22-02](https://user-images.githubusercontent.com/77173618/106392736-73723780-63f3-11eb-842d-2128d4b1f71b.png)
original view
![Screenshot_2021-01-31-18-22-20](https://user-images.githubusercontent.com/77173618/106392742-8d137f00-63f3-11eb-98bf-6596793f530c.png)

![Screenshot_2021-01-31-18-25-46](https://user-images.githubusercontent.com/77173618/106392756-9c92c800-63f3-11eb-891b-16e90d30482f.png)
original view
![Screenshot_2021-01-31-18-27-05](https://user-images.githubusercontent.com/77173618/106392771-b03e2e80-63f3-11eb-9568-9c904afcb09a.png)

**Comment by scb261** [comment]
try to open a chapter in webview and then return to the app and try again

**Comment by yamato44** [comment]
thank you it works fine now and sorry for disturbing you

**Comment by Kazuma64** [comment]
> thank you it works fine now and sorry for disturbing you

dude same problem here how do you fix toonily? im having this issue for a week.
