### ISSUE TITLE
HBrowse: Fix locked galleries access with hidden cookie

### ISSUE THREAD

**Issue by jollld** [tachiyomiorg/tachiyomi-extensions#5606]
In the www.hbrowse.com source, there are galleries that cannot be accessed without a certain cookie from the site 

![Screenshot_20210131-164857044](https://user-images.githubusercontent.com/72407660/106392563-4ec59200-63ea-11eb-889e-9cf6e07c0c8d.jpg)

This image appears inside the chapter or the site.
Normally to fix this you must visit this link:
https://hbrowse.com/cookiemonster

And "solve the riddle" so the site gives you the required cookie
The required sequence is like this:

![Uploading Screenshot_20210131-173621105.jpg…]()

Heart:Home
Cookie:Heart
Home:cookie

The problem is, inside the app there is no way to retrieve the cookie through normal means, I believe, webview does not work as I cannot change it's url and there is no link to https://hbrowse.com/cookiemonster 
in the site, has this url is a plain in view "secret"

So I'd like to request something to be done to accurately retrieve this cookie!
Thank you very much.

**Comment by hlaxkar** [comment]
Can someone solve this issue please?

**Comment by Palloxin** [comment]
To watch the images you have to open it in the browser and click on the image of the lock.
I checked the first 20 mangas that the app shows and 8 of them were locked

**Comment by Palloxin** [comment]
Here is how the lock criteria of th site. if the chapter of the manga has less than 20 pages the site will not lock it. if the chapter has 20 or more pages the chapter will be locked. If a chapter of a manga has for example 100 pages you can watch it on the site clicking on the image as i already wrote, but you have to click again on that "lock image" every 20 pages read.

**Comment by Palloxin** [comment]
seems that the site locks only mangas that include at least one of these "Types": Bestiality, Lolicon, Shotacon
as i already said, to watch these manga you have to open the browser and click on the lock image to unlock the next 20 pages of that chapter, and it i so for every 20 pages.

**Comment by Soitora** [comment]
/edit-title "HBrowse: Fix locked galleries access with hidden cookie"
