### ISSUE TITLE
[Bug] TCBScans Extension: Chapters not refreshing with new pages

### ISSUE THREAD

**Issue by phracture** [tachiyomiorg/tachiyomi-extensions#5608]
## Device information
- Tachiyomi version: Stable 0.10.7
- Android version: 9

## Source information
- Name: TCB Scans
- Extension version: 1.2.1

## Steps to reproduce
1. Browse, select One Piece (the only manga released by them)
2. Pull down on chapter list to refresh (doesn't help, but thought it would)
3. Select recent chapter to view
3. Try to read pages

### Expected behavior
Latest pages from chapter will be displayed

### Actual behavior
Page from first release of chapter is displayed, even though website has updated the pages for the chapter. 

## Other details
Starting with chapter 1000, TCP started posting the chapter page 2 days before the actual release with a single page chapter stating "keep calm and wait for new chapter". Then when the chapter is actually released, they remove this page and post the actual pages. Tachiyomi seems to just cache the original release and never update with the new pages. If I click WebView and click the new chapter, I can see the new pages in the WebView.

**Comment by scb261** [comment]
You can clear chapter cache for now, but leave the issue opened - those chapters should be filtered

**Comment by phracture** [comment]
Thanks for the tip, didn't realize that option existed in Settings>Advanced. Definitely helps as a temporary fix when needed.
