### ISSUE TITLE
[bug] mangadex stopped working (they disabled the legacy reader)

### ISSUE THREAD

**Issue by ptoump** [tachiyomiorg/tachiyomi-extensions#5609]
---

## Device information
* Tachiyomi version: latest Dev
* Android version: 10
* Device: ?samsung galaxy s7+

## Source information
* Source name: mangadex
* Source extension version: 1.2.103

## Steps to reproduce
1. Go to any manga
2.Refresh  or load chapter

## Issue/Request
Http 500 error

**Comment by scb261** [comment]
don't bother opening new issue - the reader is unrelated to the issue, mangadex api servers are down for maintenance

**Comment by ptoump** [comment]
Ah! OK, makes sense... correlation is not causation. 😅
