### ISSUE TITLE
[Bug] readcomiconline:source doesn’t work natively (only web view)

### ISSUE THREAD

**Issue by ash10r** [tachiyomiorg/tachiyomi-extensions#5612]
## Device information
- Tachiyomi version: PREVIEW r3063
- Android version: 10

## Source information
- Name: readcomiconline
- Extension version: 1.2.8

## Steps to reproduce
Note: reproducible on my phone, both on current version and preview 3045 (one plus 5)but not with support staff
Edit : confirmed also happened to scb261.
1)Readcomiconline source clicked -> browse list does not load
2)web view attempted-> loads
3) Readcomiconline source reclicked -> browse still does not load

### Expected behavior
Readcomiconline should have loaded initially or after troubleshooting 

### Actual behaviour 
Source is only functional in web view

## Other details
1)List of Troubleshooting attempted: clear chapter /app cache, clear database, clear cookies, multiple VPN, DNS over HTTPS, Reinstallation.
2)note , before reinstalling: existing chapters would load , however error on refreshing any comic in library : “Attempt to invoke virtual method ‘org.jsoup.select.Elements org.jsoup.nodes.Element.select(Java.lang.String)’ on a null object reference”
 3) note, after reinstalling: error log during restore: “Attempt to invoke virtual method ‘org.jsoup.select.Elements org.jsoup.nodes.Element.select(Java.lang.String)’ on a null object reference” -> for 5 comics , how ever there were more than 5 comics in backup. Existing library of readcomiconline source was hence lost

**Comment by Riztard** [comment]
it load for me :/
try again

**Comment by ash10r** [comment]
I know. For some reason it seems to be specific to me :( . That’s why I waited for yesterday’s update. But after 2 builds it’s still there even after all troubleshoot; that’s the only reason I filed bug.

**Comment by ash10r** [comment]
Relevant information: I just moved from preview to stable with same backup file and extension apk. It works fine. Doesn’t seem to be a source or ISP issue.

I know it’s not reproducable, so it’s hard to test but I just thought this is useful info for the devs.

**Comment by scb261** [comment]
Can confirm - it only works in stable 0.10.7 for me, but not in preview r3063 (*No results found* in browse)

**Comment by Riztard** [comment]
work for me in prev r3045 and r3063 :/

**Comment by ash10r** [comment]
> Can confirm - it only works in stable 0.10.7 for me, but not in preview r3063 (_No results found_ in browse)

Update: as of stable 0.10.8 readcomiconline is dead on both apps now. I have NO app now :( scb261 (or any other Dev) could you also confirm? Since you were able to reproduce last time.

**Comment by scb261** [comment]
Yeah, doesn't work on both r3078 and 0.10.8 for me

**Comment by arkon** [comment]
We send a more realistic user agent string now, which apparently doesn't work for this site for some reason. The extension should be updated to use the old one (`Mozilla/5.0 (Windows NT 6.3; WOW64)`), which seems to work.

**Comment by Riztard** [comment]
why it works for me then :/

**Comment by arkon** [comment]
Not sure. The user agent is based on WebView's now.

**Comment by ash10r** [comment]
Ok let me preface this my saying I’m not a Dev/coder and apologise for this whole comment in advance(just the guy that reported the bug n trying to help) but I have a phone that updates webview regularly via play store. Riztard by any chance do you have a phone that only updates webview with system updates annually ?

also arkon do you mean the extension update is out, or now you know the issue and will be out eventually? (I didn’t mean that to be rude/ demanding I just wasn’t sure if I misunderstood that it’s out and now I have another issue 😅)

**Comment by arkon** [comment]
I generally don't maintain extensions, but if someone is willing to try it, they can update the extension with a different user-agent string to try to fix it.

**Comment by Riztard** [comment]
not sure what you ask, but i update my webview few weeks ago
