### ISSUE TITLE
[Bug] <Toonily>: <failed to bypass cloudflare - every single time>

### ISSUE THREAD

**Issue by werdoe** [tachiyomiorg/tachiyomi-extensions#5613]
---

## Device information
- Tachiyomi version: 1.10.7
- Android version: Android 10 MIUI 12

## Source information
- Name: Toonily / Madara
- Extension version: 1.2.176

## Steps to reproduce
1. Update Library
2. Check error notification
3. Manually open the manga/manhwa and view in webview
4. Pass the cloudflare
5. Repeat step 1

### Expected behavior
Should bypass cloudflare and update without problem

### Actual behavior
Error message keeps showing up in the notification that it was not able to bypass cloudflare when trying to update the manga. Tried multiple times to manually open in webview and reupdate the library, same error.

## Other details
I already tried reinstalling the extension (madara) still same issue.

**Comment by Kazuma64** [comment]
having this problem for weeks. T.T

**Comment by fam007e** [comment]
Web view works fine with bypass of cloudfare check but I can't browse via the app's extension browse or latest feature.

**Comment by EfronC** [comment]
For whoever is having this problem, go to the Playstore and update Webview. The problem doesn't seems to be actually the way it retrieves the data to show it, i noted it because it started launching the error of Cloudflare, i used the Webview to bypass it, but when it loaded the page it was as if it didn't load the CSS, and when i got out of the Webview the extension kept without working, opening the web on a tab actually worked fine. I ended up updating Webview, returned to the extension, opened on Webview to bypass Cloudflare, and saw that now it rendered correctly, then got out, clicked retry, and then it worked normally.

Not sure why it fails because of this, but this seemed to be the problem, it also happens with other extensions with this same problem, like Hiperdex.

**Comment by fam007e** [comment]
> For whoever is having this problem, go to the Playstore and update Webview. The problem doesn't seems to be actually the way it retrieves the data to show it, i noted it because it started launching the error of Cloudflare, i used the Webview to bypass it, but when it loaded the page it was as if it didn't load the CSS, and when i got out of the Webview the extension kept without working, opening the web on a tab actually worked fine. I ended up updating Webview, returned to the extension, opened on Webview to bypass Cloudflare, and saw that now it rendered correctly, then got out, clicked retry, and then it worked normally.
> 
> Not sure why it fails because of this, but this seemed to be the problem, it also happens with other extensions with this same problem, like Hiperdex.

But the problem still persists even after updating Web-view app from playstore. The Web-view does its job of cloudfare verification but returning to browse option of toonily extension causes timeout. Is it really going to be beginning of the end for Toonily. ...  😣

**Comment by EfronC** [comment]
> > For whoever is having this problem, go to the Playstore and update Webview. The problem doesn't seems to be actually the way it retrieves the data to show it, i noted it because it started launching the error of Cloudflare, i used the Webview to bypass it, but when it loaded the page it was as if it didn't load the CSS, and when i got out of the Webview the extension kept without working, opening the web on a tab actually worked fine. I ended up updating Webview, returned to the extension, opened on Webview to bypass Cloudflare, and saw that now it rendered correctly, then got out, clicked retry, and then it worked normally.
> > Not sure why it fails because of this, but this seemed to be the problem, it also happens with other extensions with this same problem, like Hiperdex.
> 
> But the problem still persists even after updating Web-view app from playstore. The Web-view does its job of cloudfare verification but returning to browse option of toonily extension causes timeout. Is it really going to be beginning of the end for Toonily. ... 😣

Seems like that would be a different issue, this topic was about the failed bypass cloudflare, but in your case seems like the update to webview has solved that, but the timeout might be a different one, if i'm not misunderstanding your case.

**Comment by hyoretsu** [comment]
Still happening, so annoying when we can't even bypass it using WebView

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
