### ISSUE TITLE
[Source Request] <Doujindesu>

### ISSUE THREAD

**Issue by dimbaii** [tachiyomiorg/tachiyomi-extensions#5615]
## Source website
- Name: **Doujindesu**
- Link: www.doujindesu.site / www.doujindesu.info
- Language(s): Indonesia

## Other details
This is one of Indonesian web translators for manga, manhwa, etc

**Comment by scb261** [comment]
doujindesu.info - duplicate of #5470
doujindesu.site - looks like it has different content, but I'm not sure

**Comment by dimbaii** [comment]
@scb261 
There's a different web, doujindesu.info especially for read online
doujindesu.site can able to download and read online
So I give '/' on it

**Comment by dimbaii** [comment]
> doujindesu.info - duplicate of #5470
> doujindesu.site - looks like it has different content, but I'm not sure

**Comment by yoshino36** [comment]
We Need This Extensions ASAP

**Comment by curche** [comment]
Both sites now point to the same site doujindesu.info which makes it a duplicate to #5470
