### ISSUE TITLE
[Bug] <Viz Shonen Jump>: <Moriarty the patriot not downloading>

### ISSUE THREAD

**Issue by Cwavs** [tachiyomiorg/tachiyomi-extensions#5622]
## Device information
- Tachiyomi version: J2K 1.0.10
- Android version: 10

## Source information
- Name: Viz Shonen Jump
- Extension version: 1.2.6

## Steps to reproduce
1. Open Moriarty the patriot
2. Download any volume 2 chapter

### Expected behavior
Chapter is unlocked with Shonen Jump subscription if it isn't already and downloaded.

### Actual behavior
Unlocks and starts downloading, hangs on the last page and then errors.

## Other details
The same as #5602, the pull request by @alessandrojean unfortunately didn't fix the downloading issue but it did fix the missing cover and error that popped up.

As far as I can tell this is specific to Moriarty the patriot, I tried a few other chapters and series and I didn't get the same error.

**Comment by scb261** [comment]
Tried removing `<chaptername>_tmp` folder with a file manager and clearing chapter cache in advanced settings?

**Comment by Cwavs** [comment]
> Tried removing `<chaptername>_tmp` folder with a file manager and clearing chapter cache in advanced settings?

There wasn't any folders to remove, cleared the chapter cache but that doesn't seem to have fixed the issue.

**Comment by alessandrojean** [comment]
It's something related to the last image in the chapter that I don't know what it is. Since you are a subscriber, can you post here a screenshot of the last two pages of any chapter with error on the website (preferencially on desktop)?

@TheUnlocked maybe you can help me fix this?

**Comment by Cwavs** [comment]
The last two pages of the chapters are recommendations for other series and an ad for the volume:

![vr1C8KQO 1](https://user-images.githubusercontent.com/16854045/106612131-b1d93500-6560-11eb-8576-0bd90714f7b5.png)
![JPaDynhJ 1](https://user-images.githubusercontent.com/16854045/106612179-bc93ca00-6560-11eb-9fef-36ec054d0eb6.png)
I checked some chapters of Dr. Stone with some volumes and they had the same two things for their last pages.

I did check the last two pages that were not the adverts and they seemed to bugged in some way, I've attached a screen recording because I can't really describe what its doing, but it looks like an issue on Viz's end?

https://user-images.githubusercontent.com/16854045/106612959-9589c800-6561-11eb-8ee3-6d9a2e2f21cd.mp4

As for testing on stable I haven't I'll go and do that now

**Comment by Cwavs** [comment]
Just tested on stable, same issue.

**Comment by alessandrojean** [comment]
Yep, definitely a problem on VIZ's end, since the last images doesn't show on the website too. There's nothing that can be done to fix on the extension side for now.

I can only recommend you to read those chapters without downloading.

**Comment by Cwavs** [comment]
Ok, so should I close this for now?

**Comment by alessandrojean** [comment]
I think so.

Probably when VIZ add the next volumes, they will fix this problem on their side.

**Comment by snintendog** [comment]
Would like to add This happens on odd VIZ chapter JOJO part 4 ch113 does this as well but the rest are 100% fine Tachi loads these ads as a black or blank page in its reader the rest of the CHP is in the TMP folders is there a way of manually telling Tachi to ignore this last page and rename the tmp folder to a chapter folder  and is complete as a work around?
