### ISSUE TITLE
[Bug] The downloads gets stuck at the last page and shows an error message

### ISSUE THREAD

**Issue by LandChit** [tachiyomiorg/tachiyomi-extensions#5625]
## Device information
* Tachiyomi version: 10.7
* Android version: 9
* Device: OppoF9 pro

## Steps to reproduce
1. Open a Manga
2. Download all

### Expected behavior
It should Download completely

### Actual behavior
It gets stuck for example 13/14

## Other details
By going to the files app while the app is fully closed and removing _tmp in the folder name fixes the broken chapter it doesn't happen all the time though

**Comment by LandChit** [comment]
It happened to 
NineManga
Mangahub
I dont know if it occurred in other sources I haven't tried them yet

**Comment by LandChit** [comment]
> Looks like source or internet issue

Its probably not an internet issue i have a stable internet connection

**Comment by LandChit** [comment]
> What source is this occurring on?

It happened to 
NineManga
Mangahub
I dont know if it occurred in other sources I haven't tried them yet

**Comment by scb261** [comment]
I just tried to download from both sources - worked fine for me. It probably was temporary issue with source or internet

**Comment by LandChit** [comment]
> I just tried to download from both sources - worked fine for me. It probably was temporary issue with source or internet



> I just tried to download from both sources - worked fine for me. It probably was temporary issue with source or internet

It doesn't happen all the time it happens every 7 or more chapters in my device

**Comment by scb261** [comment]
Tbh it still looks like a problem on your side. You tried only two sources and both have this issue for you. And since it always happens on the last page, I think it's probably your phone preventing the app from renaming chapter folder. Try following and tell what are results:
- try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)
- try more sources
- try using default download location (don't forget to restart the app after changing it)

**Comment by scb261** [comment]
@LandChit did you try recommendations above?

**Comment by LandChit** [comment]
> @LandChit did you try recommendations above?

Actually i didnt it was the temporary folder name that is causing the problem

The download is done but it cant change the folder name so it cant be recognized as fully downloaded

This issue doesn't happen anymore tho
