### ISSUE TITLE
MangaDex: recent updates not shown in app

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi-extensions#5627]
**PLEASE READ THIS**

## Device information
- Tachiyomi version: 0.10.7
- Android version: 7.1.2 (LineageOS 14.1)

## Source information
- Name: MangaDex
- Extension version: 1.2.103

## Steps to reproduce
1. Go to browse -> sources -> "latest" in the MangaDex source
2. open a manga in my library that hasn't auto-updated yet
3. pull down to refresh the chapter list
4. check in the web view if there are newer chapters not present in tachiyomi's list

### Expected behavior
New chapters visible in the web view should show up in tachiyomi

### Actual behavior
**For very recently updated manga**, new chapters don't show up in tachiyomi even if I manually refresh the view of the manga. After a while these same manga update fine.

## Other details
I could not find a pattern for this, it seems to apply to any manga in my library. My guess would be there's an issue with the code that hides chapters that have not yet been released (but appear in mangadex as "will be released in n days").

**Comment by CarlosEsco** [comment]
Known issue with MangaDex's api server, the cache is not updating correctly. They have been working on a fix for the past few weeks.  Nothing we can do at this time

**Comment by NightA** [comment]
Reference: https://mangadex.org/thread/351011/10/#post_4523247

**Comment by arkon** [comment]
Closing in favour of #5780, where we'll edit the post with better info.
