### ISSUE TITLE
A few of the extensions ive download are now no where to be found in my extensions list and appear as a string of numbers in the migrate tab and where it was sopposed to be when you click on a manga, i cannot read the mangas that were from the extensions, when i click on the chapters it says source not found.

### ISSUE THREAD

**Issue by Dank-Circle** [tachiyomiorg/tachiyomi-extensions#5629]
## Device information
- Tachiyomi version: stable 0.10.7
- Android version: Android 10 one ui 2.5

## Source information
- Name: mangadex and possibly 2 others that I don't know the names of.
- Extension version: can't find

### Actual behavior: me not being able to read the manga

**Comment by CarlosEsco** [comment]
Did you uninstall the extensions either in app, or through your android app settings?

**Comment by Riztard** [comment]
maybe the source got removed

**Comment by arkon** [comment]
It's one of these:
- they were uninstalled
- you updated an extension but the source was removed from it
- you hid NSFW sources
