### ISSUE TITLE
[Source Request] Imgur

### ISSUE THREAD

**Issue by Dangelman** [tachiyomiorg/tachiyomi-extensions#5631]
## Source website
- Name: Imgur
- Link: https://imgur.com
- Language(s): /

## Other details
Not an extension to browse Imgur, but to import Imgur albums from a link, similar to Local Sources.

A lot of scalation teams post their chapters there due to limitations (eg. Mangadex DMCA). The Imgur app is pretty bad for reading manga, and the websites that repost the chapters take 1-2 days from the scanlation teams' release.
Miscellany comics are also often posted on Imgur.

Example of galleries that it would import: https://imgur.com/a/AIRPpma https://imgur.com/a/knH0d https://imgur.com/a/6FOHO

**Comment by CarlosEsco** [comment]
I'm trying to understand how this would even work.
There would be no discovery, no "manga", the best it could is it would have a generic "manga"  that when you click a link adds that link as a chapter?  It sounds pretty horrible to be honest.  Why wouldnt you use a different 3rd party app to either read, or to download make the manga a local entry.  

There is no deep linking directly to a chapter so i just dont see how this would even work well.

**Comment by arkon** [comment]
This is definitely one of the weird ones but you can have browse do nothing and have search/intents handle links or IDs to get an album as a single chapter manga.

**Comment by Dangelman** [comment]
What a suggest is more like a "import from link" feature, similar to "Local Sources".

I think it would come pretty handy, as the alternatives would be to either having to download the imgur album and move it to the Local sources folder or wait 2 days for a third-party source to reupload the work of the Scanlation team.

**Comment by CarlosEsco** [comment]
Its still is a very weird workflow.  You have to basically know where to find the imgur albums of the manga you want so you can read it in the app.  Whats next a tumblr reader?

**Comment by Dangelman** [comment]
> Its still is a very weird workflow. You have to basically know where to find the imgur albums of the manga you want so you can read it in the app. Whats next a tumblr reader?

It's not hard if you follow the Scanlation team. For example, I one of the teams I follow is [r/OnePunchMan](https://reddit.com/r/OnePunchMan/) (on both Reddit and Discord), and they release they translation within 24h from the Japanese raw. They use Imgur as the English translation got a takedown on MangaDex.

**Comment by CarlosEsco** [comment]
Yea but its one of the few extensions thats non intuitive, and maybe the only one that creates dummy manga.  
The closest extensions that are ones that you host your own manga server, but even then if you google their name it has steps on how to setup.  This relies on people to know specific scanlators host on imgur, follow them, then open when they do post a new chapter.  

If you saved them to your library you would have no information on what this dummy manga was or what it contained.

**Comment by Dangelman** [comment]
Don't you need to create a json file to add those info to local manga too? Maybe add a _Help_ button, like in _Local Sources_, to help inexperienced users.

Also imgur is pretty much the only alternative beside the mainstream manga websites for Scanlators.

**Comment by CarlosEsco** [comment]
It would make way more sense in your use case to download them on your computer and use komga and the komga extension.  Unless you only ever want to read one offs and never keep the chapters on your device.

**Comment by CarlosEsco** [comment]
with a quick search there is even an easy downloader that might work.
https://dschep.github.io/imgur-album-downloader/#/

**Comment by Seishirou101** [comment]
imgur often deletes the manga uploaded too iirc, so you're better off downloading it in all cases if you can't read it right away. if you don't want to do what carlos suggested with komga, you can also setup a sync with your local folder on your android and one on your computer and download to that folder and have it sync up for local to read too.

**Comment by celestialporcupine** [comment]
For deeplinking imgur albums I use imgurviewer.
https://play.google.com/store/apps/details?id=com.ensoft.imgurviewer

If tachi is essential, I suggest using the source guya.moe to proxy imgur links. Here are the example links op used:
https://guya.moe/proxy/imgur/AIRPpma/1/1/
https://guya.moe/proxy/imgur/knH0d/
https://guya.moe/proxy/imgur/6FOHO/1/1/

**Comment by Dangelman** [comment]
> If tachi is essential, I suggest using the source guya.moe to proxy imgur links. Here are the example links op used:
> https://guya.moe/proxy/imgur/AIRPpma/1/1/
> https://guya.moe/proxy/imgur/knH0d/
> https://guya.moe/proxy/imgur/6FOHO/1/1/

I don't think the Guya extension supports proxy imgur links (?)

**Comment by celestialporcupine** [comment]
You are right. The Guya extension does not, but the website does. I was hinting at a possible implementation.

**Comment by Seishirou101** [comment]
#6090 addressed this. you can use the proxy now by searching like the pr specifies

**Comment by arkon** [comment]
Could potentially add a URL intent handler, but should probably check with the Guya folks on whether they'd want the additional traffic that could incur.

**Comment by Dangelman** [comment]
> Could potentially add a URL intent handler, but should probably check with the Guya folks on whether they'd want the additional traffic that could incur.

An URL handler or a open-in-app sharing function  would indeed be convenient. The proxy is working fine.

**Comment by CrepeTF** [comment]
Shouldn't this be solved now with Cubari
