### ISSUE TITLE
[Bug] <BestManhua>: No Pages Found

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#5632]
### Device Information

Tachiyomi Version: 0.10.7
Android Version: Android 10 

### Source Information

Name: BestManhua / Madara
Extension version: 1.2.177

### Steps to Reproduce

1. Open BestManhua 

2. Select any manga

3. Select any chapter

### Expected Behaviour
Able to Read Manga

### Actual Behaviour
No Pages Found

### Other Details
Webview Works Fine

**Comment by Hades68** [comment]
This bug show up again
