### ISSUE TITLE
[Source Request] <Ava's Demon>

### ISSUE THREAD

**Issue by Vinerak** [tachiyomiorg/tachiyomi-extensions#5635]
## Source website
- Name: Ava's Demon
- Link: https://www.avasdemon.com/chapters.php
- Language(s): English

**Comment by anin1354** [comment]
Ava's demon is already available through the webtoons.com extension.

**Comment by Lightsockie** [comment]
The version on webtoons is very behind the source. Actually just came to this repo myself to potentially make a source request of my own because webtoons is on about page ~2188, but the source is up to 2611

**Comment by scb261** [comment]
We usually don't do sites with one manga, especially when it's available on different extension, but I guess it's fine in this case? It's original and way ahead of webtoons.com.
