### ISSUE TITLE
[Source Request] readonepiece

### ISSUE THREAD

**Issue by idioticchris** [tachiyomiorg/tachiyomi-extensions#5637]
## Source website
- Name: readonepiece
- Link: https://ww8.readonepiece.com
- Language(s): English

## Other details
this website offers both the ORIGINAL AND COLORED version of one piece, i know mangadex also have colored version of it but the number of colored version of one piece on mangadex isn't enough so please🙏🙏🙏 add this website. It'd be really really appreciated  THANKS! :D

**Comment by joseph619** [comment]
Single source websites will not be added unless it's from a scanlator. Find an aggregator which has coloured One Piece.

**Comment by scb261** [comment]
See above.

**Comment by CarlosEsco** [comment]
Are they one's doing the coloring?  Or just hosting colored manga from somewhere else

**Comment by scb261** [comment]
> Officially coloured by Shueisha, the publishers behind One Piece

https://ww8.readonepiece.com/manga/one-piece-digital-colored-comics/

**Comment by idioticchris** [comment]
Oh i see... Thanks for your time guys!
