### ISSUE TITLE
[Bug] Reaper Scans: HTTP error 404

### ISSUE THREAD

**Issue by Subtilizer28** [tachiyomiorg/tachiyomi-extensions#5642]
# Device information
- Tachiyomi version: J2K 1.0.10
- Android version: 10

## Source information
- Name: Reaper Scans (Genkan Extension)
- Extension version: 1.2.25

## Steps to reproduce
1. Open any manga and you will get the error in reaper scans. 

### Expected behavior
Refreshes the manga and shows the new chapters

### Actual behavior
Gives HTTP error 404

**Comment by scb261** [comment]
It looks like they have changed links to some manga. Can you search again the same manga in the source and check if it works?

**Comment by Subtilizer28** [comment]
Ah yeah I did search for same manga but it's the same for all. Here u go. The 1st link is from tachiyomi and the 2nd one from official

https://reaperscans.com/comics/266224-second-life-of-a-gangster
https://reaperscans.com/comics/68096-second-life-of-a-gangster

They changed the ID's

**Comment by scb261** [comment]
Yeah, that's can't be actually fixed, you would need to manually migrate manga from Reaper Scans to Reaper Scans to update url

**Comment by Subtilizer28** [comment]
Oh I see. Sorry for that. Thanks!!
