### ISSUE TITLE
[Bug] <Mangakawaii>: <Pages doesn't load>

### ISSUE THREAD

**Issue by Zealest** [tachiyomiorg/tachiyomi-extensions#5643]
## Device information
- Tachiyomi version: r3063
- Android version: 10

## Source information
- Name: Mangakawaii
- Extension version: 1.2.15

### Actual behavior
Number of pages are shown, but if doesn't load.
It shows this error when I want to download a chapter (I can't expand the notification)

![Screenshot_20210205-193207](https://user-images.githubusercontent.com/62892019/107074317-dd6e5080-67e8-11eb-86c1-ccf48593a368.jpg)

**Comment by Zealest** [comment]
many thanks @Riztard

**Comment by Zealest** [comment]
is it normal if there isn't any update available ? (1.2.15 -> 1.2.16)

**Comment by arkon** [comment]
You need to wait for it to build/deploy.
