### ISSUE TITLE
[Source Request] <SoftKomik>

### ISSUE THREAD

**Issue by AikuSubaru** [tachiyomiorg/tachiyomi-extensions#5645]
## Source website
- Name: SoftKomik
- Link: https://softkomik.site/
- Language(s): Indonesian (ID)

## Other details

**Comment by Riztard** [comment]
change url to softkomik.com

**Comment by vetleledaal** [comment]
Geo blocked to Indonesia. Unknown theme, pulls data from https://mongo.animeyusha.com/ (https://animeyusha.com/ does not have any geo blocking)
