### ISSUE TITLE
[Bug] Mangasee: http 403 error

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#5651]
## Device information
- Tachiyomi version: App version: 0.10.8
-Android version: 11 (SDK 30)

## Source information
- Name: Mangasee
- Extension version: 1.2.16

## Steps to reproduce
Open Manga from mangasee Extension 
Already Tried on few titles shown same problem  Tales of Demons and Gods/Martial Peak/ Overgeared

### Expected behavior
Images should be loaded

### Actual behavior
Shows error Error 403

## Other details
Working fine in web view but not in App

![Screenshot_20210206-221209_Tachiyomi](https://user-images.githubusercontent.com/36104528/107124690-6a89d600-68cb-11eb-87f2-c7ce2c5f7f5e.jpg)
![Screenshot_20210206-221245_Tachiyomi](https://user-images.githubusercontent.com/36104528/107124694-6e1d5d00-68cb-11eb-885a-50657e3d02cc.jpg)

Issue still persist even after opening in webview

**Comment by xmalbertox** [comment]
Same thing here on TachiyomiJ2K
It was working ok, the problem started after the extension update earlier today

**Comment by Ali-Elsherif** [comment]
Same problem here!

**Comment by Riztard** [comment]
now it works, source issue

**Comment by Samk19** [comment]
Thankyou

**Comment by kai000bubbles** [comment]
It's happening again but now I can't even access the manga
