### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by Luizzhh** [tachiyomiorg/tachiyomi-extensions#5652]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

## Source information
- Name: MangaSee
- Extension version: 1.2.16

## Steps to reproduce
1. Try to load a chapter of any manga from the MangaSee source.

### Expected behavior
The image of the first unread page of that chapter should load.

### Actual behavior
The chapter won't load, instead a HTTP error 404 message apears.

## Other details
The source was working perfectly fine before installing the latest extension update.
The source page loads fine using the webview.

**Comment by Seishirou101** [comment]
thanks for making the report, but you don't have to make another one since this one is closed. #5651 was created before yours so that one can be used
