### ISSUE TITLE
[Bug] BlogTruyen: Cannot load content

### ISSUE THREAD

**Issue by lightspect** [tachiyomiorg/tachiyomi-extensions#5653]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10
- Device: Oneplus 5T

## Source information
- Name: BlogTruyen 
- Extension version: 1.2.8

## Steps to reproduce
1. Open the app
2. Go to the Browse section
3. Choose BlogTruyen in the Sources tab

### Expected behavior
See the list of manga available on the site

### Actual behavior
App showed No result found

## Other details
Tried clearing cookies and cached but result still the same. WebView worked fine

**Comment by scb261** [comment]
Can't reproduce. Does it still happen to you? Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).

**Comment by lightspect** [comment]
Seem like the issue has been fixed. Maybe there was a update on the site or extension and now it worked correctly. I think this issue can be closed
