### ISSUE TITLE
[Bug] EarlyManga: timeout

### ISSUE THREAD

**Issue by keinezeit8** [tachiyomiorg/tachiyomi-extensions#5655]
## Device information
- Tachiyomi version: J2K 1.0.10
- Android version: 11

## Source information
- Name: EarlyManga
- Extension version: 1.2.2

## Steps to reproduce
1. Install EarlyManga
2. Open EarlyManga

### Expected behavior
Some Mangas should appear

### Actual behavior
`timeout error`

## Other details
When clicking "Open in WebView" the error message `You need to access the site through the browser` appears.
When opening in the browser it works. I even tried making an account and logging in, but it doesn't change anything.

**Comment by CarlosEsco** [comment]
A new version was released.  Reopen if still an issue

**Comment by keinezeit8** [comment]
Updated to
EarlyManga 1.2.3
Behaviour hasn't changed.

**Comment by scb261** [comment]
Can you check if it happens on main app 0.10.8? https://tachiyomi.org/download/

**Comment by keinezeit8** [comment]
I tried 0.10.8 and it works

**Comment by scb261** [comment]
Changing user agent doesn't seem to fix it, probably should be fixed on J2K side
