### ISSUE TITLE
[Bug] NewToki: Chapters marked as "웹툰미리보기" returns an error when trying to read

### ISSUE THREAD

**Issue by juleast** [tachiyomiorg/tachiyomi-extensions#5657]
## Device information
- Tachiyomi version: 0.10.8-3085
- Android version: 10 SDK 29

## Source information
- Name: NewToki
- Extension version: 1.2.19

## Steps to reproduce
1. Pick a manhwa (For me, the specific ones that I had problems with were the titles "스터디그룹" and "튜토리얼 탑의 고인물". From what I've seen tho, "갓 오브 하이스쿨" didn't give the same error)
2. From the tachiyomi app, try to read chapters that are marked as "웹툰미리보기".

### Expected behavior
The reader should have loaded the chapter images

### Actual behavior
Reader closed and returned an error message

## Other details
Screenshot of error message:
![Screenshot_20210206-170033~2](https://user-images.githubusercontent.com/44688633/107131079-a1e38d00-68a1-11eb-91da-c41b19b12b12.jpg)

**Comment by DitFranXX** [comment]
What I trying to figure out is, If URL has `[` or `]`, `SChapter.setUrlWithoutDomain` is failed to extract domain.
This seems issue with Tachiyomi itself, or more over it's library issue so. (Which means *not extension bug*)

Plus, It only applied the chapter that start with `[`, Like `[뉴토끼]`. Which it has `[뉴토끼]` in the url.

**Comment by DitFranXX** [comment]
#5935 will fix it temporary. Note that source doesn't follow the uri standard (which caused this issue).
