### ISSUE TITLE
[Bug] <Bacakomik>: <saat memilih chapter pada komik untuk dibaca selalu muncul tulisan "Halaman tidak ditemukan," padahal saat membuka app dan webnya terlihat aman>

### ISSUE THREAD

**Issue by alapereni** [tachiyomiorg/tachiyomi-extensions#5664]

**Comment by alapereni** [comment]
### Device information:
App version: 0.10.8 (standard, 45a19d1, 55)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.J730GDXSCCTH1
Device brand: samsung
Device manufacturer: samsung
Device name: j7y17lte
Device model: SM-J730G
Device product name: j7y17ltedx

### Source information

- Name: Bacakomik (Bahasa Indonesia)

- Extension version: 1.2.2

### Steps to reproduce

1. Pilih dan bukalah salah satu manga yang ada di ekstensi bersangkutan
2. Kemudian pencet salah satu chapter

### Expected behavior
Tidak ada lagi "Halaman tidak ditemukan," inilah yang menyebabkan ekstensi bersangkutan tidak dapat dipakai dalam artian tidak bisa baca manga di ekstensi tersebut. Semoga masalah tersebut bisa diperbaiki sehingga ekstensi bisa digunakan.

### Actual behavior
saat memilih chapter pada komik untuk dibaca selalu muncul tulisan "Halaman tidak ditemukan,"

**Comment by scb261** [comment]
All chapters I've tried have broken images in a browser, so it's not an extension issue. Contact site owner and ask them to fix it. If there actually are chapters that load in a browser but not in the app - please open new issue and specify what manga and chapters have this problem.

**Comment by Riztard** [comment]
it is broken
