### ISSUE TITLE
[Feature Request] all sources: reason for obsolition when a source is made obsoloete

### ISSUE THREAD

**Issue by GreatestFool** [tachiyomiorg/tachiyomi-extensions#5670]
I feel this should be added because there is no easy way to find _why_ certain sources have been made obsolete. I checked today because Genkan and Mangabox, which contain many sources, were made obsolete.

I don't know the true extent of how many sources they covered or where they were moved, so it would be _really_ nice to be able to simply click on them and have the reason for why they are made obsolete be in a description field like there is a preference field. In general, I think they should have a description field regardless, simply so that sources that cover multiples can say which they cover.

Having a description field like this is also nice when making them obsolete in the sense of telling the end user of which extensions can be used as an alternative.

**Comment by arkon** [comment]
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/2420
