### ISSUE TITLE
MangaBox obsolete but where did it move?

### ISSUE THREAD

**Issue by phonixor** [tachiyomiorg/tachiyomi-extensions#5671]
Not sure this is the right place for this.
But couldn't find the answer on google yet.

I see in commit
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/700ec615a632c7673686867a2cd5157667892dfe
that the MangaBox extension moved to the multisrc dir

but in app i only see it as OBSOLETE, how do i get the multisrc extension version? what is the migration path?

thanks in advance!

additional info:
I just updated main app to 0.10.8
MangaBox version 1.2.24 (OBSOLETE)

**Comment by scb261** [comment]
It was split into separate extensions. Search extension for the source you've used (e.g. search `kakalot` in the **Extensions** tab) and install it. Uninstall obsolete. Restart the app.

@arkon, maybe create meta issue and pin it? Or edit #4287?

**Comment by phonixor** [comment]
thanks for the quick response! and cool the app is smart enough so that i don't have to migrate :)

but i think a better upgrade path was to install(/suggest to install) the replacement apps, instead of just saying (OBSOLETE)

**Comment by Emperornero** [comment]
After uninstalling Mangabox I'm unable to use 4 different sources.

Can someone link me to the latest working version of the Mangabox extension?  Regardless of it being obsolete, it still worked.

Can't access Mangabat, Mangakakalots, Mangakakalots (unofficial), or MangaDex anymore after uninstalling it, and can't migrate the manga I was reading from the broken sources.
