### ISSUE TITLE
[Meta] Splitting multi-source extensions and OBSOLETE extensions

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi-extensions#5672]
We are in the process of splitting multi-source extensions into separate extensions for each source. You will see OBSOLETE mark beside those extensions.

<details>
<summary>List of extensions that have been already split.</summary>

- Genkan
- MangaBox
- ComiCake
- Madara
- EroMuse
- WP MangaReader
- MangAdventure
- Paprika
- WP-Comics
- FMReader
- FoolSlide
- WP MangaStream
- MangaMainac (you will need to migrate to a separate extension if you used MangaMainac)
- Luscious
- zBulu
- Webtoons
- mangásPROJECT
- NyaHentai
- My Manga Reader CMS

</details>

What do you do? You'll need to uninstall obsolete extensions and install separate extensions for sources that you're using. Follow the guide bellow to do it:

<details>
<summary>How to move to a new extension that was separated?</summary>

1. Open the **Extensions** tab and see what extension is marked as OBSOLETE. In this example it's **MangaBox**.
![01](https://user-images.githubusercontent.com/65343233/107156746-dc742500-6988-11eb-86c5-20a0c16e73b5.png)
1. Go to the **Migrate** tab and write down sources that you're using from this extension. You can identify them by icon that is the same as the extension icon. In this example it's **Mangakakalot** and **Manganelo**.
![02](https://user-images.githubusercontent.com/65343233/107156886-94093700-6989-11eb-9d3f-fca70b2cb284.png)
1. Go back to the **Extensions** tab, open the obsolete extension and remove it.
![03](https://user-images.githubusercontent.com/65343233/107156930-d6327880-6989-11eb-8a44-1421764f5d74.png)
1. In the **Extensions** tab find the extensions for sources that you wrote down before and install them. In this example it's **Mangakakalot** and **Manganelo**.
![04](https://user-images.githubusercontent.com/65343233/107156989-36c1b580-698a-11eb-8b6d-6fc977149b21.png)
![05](https://user-images.githubusercontent.com/65343233/107156992-37f2e280-698a-11eb-98c9-7dfcf6a77ccd.png)
1. At this point everything should work fine. If you are seeing numbers instead of a source name - force close the app.

</details>

<details>
<summary>What to do if I can't find new source in the Sources tab and only see numbers on manga and migration screens?</summary>

1. If the extension isn't on the list above and was removed for different reason (see #3475), then there is nothing you can do. If it is in the list above, follow to the next step.
1. Make sure you have installed right new extension. You can check id number in this list https://pastebin.com/raw/QX2scdRT .
1. Force close the app.

</details>

<details>
<summary>Do I need to migrate and what will happen to my downloads?</summary>

No, you don't need to migrate. Old and corresponding new sources have the same id internally, so manga that you have already added to your library will work fine. That means that downloads also will be kept and you don't need to redownload chapters. Just follow the guide above to uninstall obsolete and install new extensions.

</details>

Known issues:
- [upstream] **Reaper Scans** shows error 404. This has nothing to do with splitting **Genkan** extension, **Reaper Scans** changed manga URLs. You need to manually migrate each manga with this error from **Reaper Scans** to **Reaper Scans**.
- [fixed] ~~**Hatigarm Scans** from **Genkan** shows numbers instead of the source name even after following the guide above. This issue is known and developers are working on it.~~ **Hatigarm Scans** was fixed. If you see 863874713491229667, update **Hatigarm Scans** extension to 1.2.2 version. If you already migrated and see 1568996025316330857, migrate again from **Hatigarm Scans** to **Hatigarm Scans**.
- [fixed] **Mangazuki.online**, **Hunter Fansub**, **Ichirin No Hana Yuri**, **Just For Fun**, **KlikManga**, **Kombatch** and **Void Scans** extensions cannot be installed. This issue was fixed, try to install them again.
- [fixed] **MangaBox** sources (**Mangakakalot, Manganelo, Mangabat, Mangakakalots (unoriginal), Mangairo**) don't show manga list in Browse for some users. Fixed, should work fine now.
- [fixed] **WebNovel.com** doesn't appear on the list of extensions after separating another source with similar name (**WebNovel**). Fixed, remove and reinstall both extensions and restart the app afterwards.
- [note] **Manhwa18.net Raw** is now part of **Manhwa18.net** extension.
- [fixed] **ManhwaSmut** isn't recognized by the app after installing. Fixed, remove and reinstall the extension.
- [note] **Manwha Club** was renamed to **Manhwa.club**. To keep you downloads from this source open download folder with a file manager and rename `Manwha Club (EN)` folder to `Manhwa.club (EN)`. Restart the app afterwards.

**Comment by kuroko14** [comment]
Any reason to split the extensions?

**Comment by arkon** [comment]
Read #4287.

**Comment by vengiare** [comment]
> Any reason to split the extensions?

So that extension search is 5000% more useful and we don't have to refer people to a spreadsheet (https://tachiyomi.org/extensions-spreadsheet) for certain sources.

**Comment by melink14** [comment]
FYI for others, migrating to the separated sources will mean you lose your downloaded chapters and will need to re-download.

**Comment by scb261** [comment]
No, it will not. And you don't need to migrate (excluding Reaper Scans and Hatigarm Scans). Use support channel on Discord to get help https://discord.gg/tachiyomi

**Comment by melink14** [comment]
You're right, I went through all the steps of the post first include some like which needed to be migrated and others which just need the new extension installed and didn't make the connection that the normal split sources were fine.

**Comment by Bexa2** [comment]
I deleted all multisource obsolete extensions but forgot to write down what source I was using on each.
Is there any way to see "orphaned Manga" in my library to know what mangas don't have the extension installed?

**Comment by CarlosEsco** [comment]
@Bexa2 join the discord channel and ask in support

**Comment by hyoretsu** [comment]
Iskultrip Scans leads to a "Social Potatoes" site now, so I guess they dropped scanlation.

**Comment by CarlosEsco** [comment]
closing as everything is split iirc
