### ISSUE TITLE
Mangafreak: conflicted extension with Guya

### ISSUE THREAD

**Issue by Ceonci** [tachiyomiorg/tachiyomi-extensions#5675]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

## Source information
- Name: Mangafreak, Guya
- Extension version: 1.2.2, 1.2.13

## Steps to reproduce
1. Installed only mangafreak extension
2. Install Guya extension, restart the app

### Expected behavior
Chapter load normally in webview

### Actual behavior
The unread chapters did not load and the amount of pages becomes double the actual amount in webview

**Comment by arkon** [comment]
Not entirely sure why, but this was a side effect of some changes in the main app around how we pretend to be a normal browser. It should be fixed in the next release.
