### ISSUE TITLE
[Bug] <azora>: <when installingthe source it doesn't appear in the list of downloaded extensions>

### ISSUE THREAD

**Issue by Bm12347** [tachiyomiorg/tachiyomi-extensions#5677]
## Device information
App version: 0.10.8-3085 (standard, d84b5e8b, 55)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BTK3
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx
## Source information
- Name: azora
- Extension version: 1.2.1

## Steps to reproduce
Try installing it
### Expected behavior
Should appear in downloaded extensions list

### Actual behavior
It doesn't even though I checked that it is downloaded

## Other details
I also tried the stable version
![Screenshot_20210208-010519_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/107162428-adbb7600-69ab-11eb-91db-cc1edc9da6c9.jpg)

**Comment by arkon** [comment]
Try reinstalling it in ~30 minutes. You may need to manually uninstall the old Azora extension from the apps list in Android settings first.
