### ISSUE TITLE
[Bug] <Mangadex>: <Doesn't update>

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#5683]
## Device information
Android 10

Tachiyomi r3085

## Source information
Mangadex 1.2.103

## Steps to reproduce
Update any manga

### Expected behavior
New chapters

### Actual behavior
No new chapters in app, but on webview i see it

I already wipe cache and clean cookies

![Screenshot_2021-02-08-08-18-33-564_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/107178927-48d14180-69e6-11eb-9989-095b2b3ebb56.jpg)![Screenshot_2021-02-08-08-18-43-615_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/107178931-4a9b0500-69e6-11eb-9d63-e1cd3221a926.jpg)

**Comment by Seishirou101** [comment]
Refer to #5627

**Comment by Akazotik** [comment]
Neko tachi works properly![Screenshot_2021-02-11-15-20-43-384_tachiyomi.mangadex.jpg](https://user-images.githubusercontent.com/39062952/107635986-0aa17f80-6c7d-11eb-9fea-f84702ad2946.jpg)
![Screenshot_2021-02-11-15-20-57-334_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/107635993-0d9c7000-6c7d-11eb-9e0f-a7a6d773bf2b.jpg)

**Comment by scb261** [comment]
Read https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5666#issuecomment-774665668
