### ISSUE TITLE
[Source Request] <Manhwaid>

### ISSUE THREAD

**Issue by gospodinh** [tachiyomiorg/tachiyomi-extensions#5702]
## Source website
- Name: Manhwa ID
- Link: https://www.manhwaid.com/
- Language(s): Indonesia (ID)

**Comment by SokKeras** [comment]
lu ngapain request web sepi, percuma uploadnya dikit mending web gede

**Comment by scb261** [comment]
The site doesn't have online reader, only download links. Use local instead https://tachiyomi.org/help/guides/reading-local-manga/
