### ISSUE TITLE
[Bug] Arang Scans: not pulling any chapter info

### ISSUE THREAD

**Issue by catoAvg** [tachiyomiorg/tachiyomi-extensions#5712]
## Device information
- Tachiyomi version: 0=10.8
- Android version: 11/ OneUI 3.1

## Source information
- Name: Arang Scans
- Extension version: 1.2.1

## Steps to reproduce
1. Open Arang Scans thru extension using the normal or latest view
2. Tap on any manga and wait for the error message
3. Open the manga in webview and see that there are chapters

### Expected behavior
Chapter list should have come up

### Actual behavior
"No chapters found"

**Comment by AriaMoradi** [comment]
Regression of #5477
