### ISSUE TITLE
[Invalid Sources] List of sources that might be broken

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/tachiyomi-extensions#5714]
I opened all websites in the Spreadsheet (Multi-src), these are the websites that had issues:

### Opens sketchy websites:

Source | Website
-- | --
HanaScan (Raw QQ) | http://rawqq.com
Midnight Haven | http://midnighthaven.shounen-ai.net
Storm in Heaven | http://storm-in-heaven.net
Miracle Scans | http://miraclescans.com

### Domain pending renewal

Source | Website
-- | --
Tsubaki No Scan | https://tsubakinoscan.com
MangaZuki.xyz | http://mangazuki.xyz

### Domain parked

Source | Website
-- | --
Manga18 Fun | https://manga18.fun
Raider Scans | https://raiderscans.com
WeScans | https://wescans.xyz
Komik Go | https://komikgo.com
KingzManga | http://kingzmanga.com

### Host misconfiguration

Source | Website
-- | --
مانجا عرب اون لاين | https://mangaarabonline.com
Einherjar Scan | https://einherjarscans.space
MangaCultivator | https://mangacultivator.com
NTS Void Scans | https://ntsvoidscans.com
Prime Manga | https://primemanga.com
DoujinYosh | https://doujinyosh.work
Mangatensei | http://www.mangatensei.com
Matakomik | https://matakomik.com
Fallen World Reader | https://faworeader.altervista.org
The Phoenix Scans | http://www.phantomreader.com
مانجا اولاو | https://olaoe.giize.com

### ERR_CERT_AUTHORITY_INVALID

Source | Website
-- | --
Nikushima | https://azbivo.webd.pro

### DNS_PROBE_FINISHED_NXDOMAIN

Source | Website
-- | --
MangazukiClubJP | https://mangazuki.club
MangazukiClubKO | https://mangazuki.club
Just For Fun | https://just-for-fun.ru
TurkceManga | https://turkecemanga.com
NoxSubs | https://noxsubs.com
KomikIndo | https://www.komikindo.web.id
18LHPlus | https://18lhplus.com
ATM-Subs | https://atm-subs.fr
Nazarick Scans | https://nazarickscans.com

### ERR_CONNECTION_TIMED_OUT

Source | Website
-- | --
Ajia no Scantrad | https://ajianoscantrad.fr

### Suspended by hosting provider

Source | Website
-- | --
KomikRu | https://komikru.com

### Might have database errors

Source | Website
-- | --
KaisarKomik | https://kaisarkomik.com

### Product activation error

Source | Website
-- | --
Mangakyo | https://mangakyo.me

### Error 521: Web server is down

Source | Website
-- | --
FR Scan | https://frscan.me
MangaShiro | https://mangashiro.co

### Error 526: Invalid SSL Certificate
Source | Website
-- | --
ToonPoint | https://toonpoint.com

### Error 404: Not found

Source | Website
-- | --
AlianzaMarcial | https://alianzamarcial.xyz
Spooky Scanlations | https://spookyscanlations.xyz
MangazukiOnline | https://www.mangazuki.online

### Error 403: Forbidden

Source | Website
-- | --
Baixar Hentai | https://leitura.baixarhentai.net

### Not loading

Source | Website
-- | --
ZManga | https://zmanga.org

### Might be shutting down

Source | Website
-- | --
StageComics | https://stagecomics.com

### Website requires login

Source | Website
-- | --
MMScans | https://mm-scans.com

**Comment by staudond** [comment]
Other sources that doesn't work

**They shut down**
source | website
 --- |---
One Time Scans | https://otscans.com/ 

**Redirects to another website**
source | website
 --- |---
Helvetica Scans | https://helveticascans.com

**Comment by scb261** [comment]
Just checked them all after 2 weeks and here are some notes:

https://azbivo.webd.pro - works only with HTTP
https://noxsubs.com - DNS is fixed now
https://kaisarkomik.com - works fine, they probably fixed the database error
https://mangashiro.co - it's not 521 (down) but 1020 (access denied) for me, so I'm not sure about this one
https://mm-scans.com - works fine for me without login
