### ISSUE TITLE
[Bug] <manganelo/mangabat>: <don't load>>

### ISSUE THREAD

**Issue by GamaG27** [tachiyomiorg/tachiyomi-extensions#5719]
## Device information: Huawei Psmart 2018
App version: 0.10.8-3095 (standard, 9f9f9872, 55)
Android version: 9 (SDK 28)
Android build ID: FIG-LX1 9.1.0.216(C432E22R1P5)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWFIG-H
Device model: FIG-LX1
Device product name: FIG-LX1

## Source information
- Name: manganelo/mangabat
- Extension version: latest (I believe is 0.1 as is the first realise since the split of mangabox) 

## Steps to reproduce
1. Find Manganelo/mangabat in 
2. Click the source 

### Expected behavior
Manganelo/mangabat would load
### Actual behavior
Manganelo/mangabat doesn't load
"No se han encontrado resultados" 
(don't the message in English) 

## Other details
Even though you cant access the source 
The web view still works and if you already had a favorited Manga from manganelo/mangabat still works and update

**Comment by scb261** [comment]
Works for me. Did you remove the old mangabox extension and restarted the app? If not - try it. Also try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)

**Comment by GamaG27** [comment]
I removed the mangabox installed the new manganelo/mangabat
Reboot the app
Troubleshoot
And re-installed manganel/mangabat

**Comment by scb261** [comment]
Hm, two more users reported this problem on discord. Wait for someone to look into it, ig

**Comment by AriaMoradi** [comment]
Maybe their host returns 5xx errors time to time?
I primarily use these two besides bato.to but never experienced loading issues

**Comment by Blaze9676** [comment]
Yeah bro like the all of it shows cloud fare access is denied

**Comment by AriaMoradi** [comment]
> Yeah bro like the all of it shows cloud fare access is denied

It's a cloudflare issue, your IP has been blocked, this is not a Tachiyomi issue.

**Comment by MahaVailo13** [comment]
There is a work around if someone wants to replace manganelo.com with .tv

Anyone willing to do a work around with that?

**Comment by vietpride218** [comment]
I'm unable to look anything up in browse for Mangakalot. Even looking up a simple term like "hero" or "tales" returns no results. 
I am able to look it up if I go into webview in Mangakalot, but that doesn't help too much in trying to find and add stuff to my library.

App version: 0.10.9-3130 (standard, d4c9ab79, 56)
Android version: 10 (SDK 29)
Android build ID: QPMS30.80-63-6-8-5
Device brand: motorola
Device manufacturer: motorola
Device name: sofia
Device model: moto g power
Device product name: sofia_retail

This has, however, been an issue through multiple Tachiyomi preview updates. 
![Screenshot_20210228-123144](https://user-images.githubusercontent.com/79806535/109429655-78121780-79c2-11eb-8533-821c7ac8c36e.png)
![Screenshot_20210228-123159](https://user-images.githubusercontent.com/79806535/109429658-7d6f6200-79c2-11eb-9e81-d8662a6991a1.png)

**Comment by AriaMoradi** [comment]
I've been using manganelo for the past two days and sometimes their server either crashes and doesn't respond or parts of their site become slow and/or stop loading, but usually after 10-15 minutes it comes back. Maybe reportees where using the site then?

**Comment by vietpride218** [comment]
> I've been using manganelo for the past two days and sometimes their server either crashes and doesn't respond or parts of their site become slow and/or stop loading, but usually after 10-15 minutes it comes back. Maybe the reportees where using the site then?
> 
> @vietpride218 please try at various times and see if the issue persists.

Yeah, no luck.

**Comment by CarlosEsco** [comment]
New version with url changes was released
