### ISSUE TITLE
[Bug] Madara: Comicsvalley Isn't working now. It supposed to work like in Version 1.2.178

### ISSUE THREAD

**Issue by rickninja765** [tachiyomiorg/tachiyomi-extensions#5722]
Device information
- Tachiyomi version: 0.10.8
- Android version: 10

Source information
- Name: Madara
- Extension version: 1.2.180

Steps to reproduce
1. First Step : Open Any Comicsvalley Comic
2. Second Step : It will eventually not open cause its revoked i guess.

Expected behavior
It Should open any comics belongs to Comicsvalley.

Actual behavior
But Now Its not opening Can you add it back.

Other details
    The Site Info : Comicsvalley.com

**Comment by scb261** [comment]
It was separated, install the new extension. Read #5672 for more info

**Comment by rickninja765** [comment]
Thanks I installed it.
But i have one question. If Anything happens to site or any possible failure in extension. We have to individually report for that extension?

**Comment by scb261** [comment]
Yes, just open issue and fill in template
