### ISSUE TITLE
[Bug] Mangadex: New chapters are not showing despite the extension working fine other than that

### ISSUE THREAD

**Issue by Umairuem** [tachiyomiorg/tachiyomi-extensions#5724]
## Device information
- Tachiyomi version: j2k 1.0.10
- Android version: 7

## Source information
- Name: Mangadex
- Extension version: 1.2.103

## Steps to reproduce
1. Open a manga that has received a new update on website in previous 1-2 days
2. Pull down to update the entry

### Expected behavior
The new chapters show up

### Actual behavior
It remains as it was before despite being the new chapters present in website

## Other details
So, I think there's already an open issue for this bug https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5627#issue-799508323
But still, it has been bugging me about how important this issue is and it's not being updated despite this problem occurring for a week now. I'm sorry if my issue is related to the one I mentioned, but please try to work on this soon. There are many manga that are getting updated on the website while this issue is continuously there and those can't be read in the app.
And the thing is, all other things are working perfectly fine for this extension, old chapters are loading totally fine. The only problem is that it's not updating the new chapters. So I want to ask how many time can it take to solve? This issue has been persistent ever since Mangadex's website update a few days ago. Please try to solve this one asap if you can.
Again sorry for submitting this issue again, but I just wanted to get your attention towards this bug for one of the most used extension in case no one is working on it yet haha.

**Comment by scb261** [comment]
The problem is on MD side, nothing we can do. The issue that you linked has more info about it. Opening duplicate to "get your attention towards this bug" only annoys people who gets email notifications about this.
