### ISSUE TITLE
[Bug] Martial Scans Source 404

### ISSUE THREAD

**Issue by alexporth** [tachiyomiorg/tachiyomi-extensions#5728]
## Device information
* Tachiyomi version: 0.10.8 (standard, 45a19d1, 55)
* Android version: 10 (SDK 29)
* Device: ONEPLUS A5010 (OnePlus5T)

## Source information
* Source name: Madara (multiple sources)
* Source extension version: 1.2.180

## Steps to reproduce
1. Enter the Martial Scans sources under sources
2. Get a 404 error.
3. Check the webview, sometimes this will show the website and other times it will give you a message that Google thinks you are a bit. The second will appear if, after 20 seconds, the website has not.

## Issue/Request
I think that tachiyomi is being treated as a bot, when the website is not accessed in webview.

**Comment by Riztard** [comment]
look like they dont use madara anymore

**Comment by FlammFR** [comment]
+1
