### ISSUE TITLE
[Bug] <Aloalivn>: <no page>

### ISSUE THREAD

**Issue by Warcrors** [tachiyomiorg/tachiyomi-extensions#5732]
---

## Device information
- Tachiyomi version: preview r337
- Android version: 10

## Source information
- Name: Aloalivn
- Extension version: 1.2.1

## Steps to reproduce
1. Go to the ext
2. Open a chapter of the series 

### Expected behavior
A page to appear

### Actual behavior
No pages

## Other details
None

**Comment by Riztard** [comment]
work for me, give an example or try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)

**Comment by tyme2tb** [comment]
Having the same issue. Webview works perfect. Just in the app when trying to view a chapter I get no page found message. I tried numerous mangas and non worked.

**Comment by Zextokar** [comment]
I am with the same problem, there is no way to fix it, I do not speak English so I have to use the translator

**Comment by tyme2tb** [comment]
Looks like the new extension update 1.2.2 that was just released fixes this

**Comment by Riztard** [comment]
> Looks like the new extension update 1.2.2 that was just released fixes this

it only add genres :/
