### ISSUE TITLE
[Bug] <Hentaifox>: Thumbnail Loading Issue.

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi-extensions#5733]
## Device information
- Tachiyomi version: 0.10.8.
- Android version: 10.
- Device: Motorola One Fusion Plus.

## Source information
- Name: Hentaifox.
- Extension version: 1.2.2.

## Steps to reproduce
1. Browse the source.

### Expected behavior
All thumbnails/covers should load as you keep browsing.

### Actual behavior
Thumbnails/covers do not load.

## Other details
Only once you tap on a specific entry does the cover for that entry load. Returning to the catalogue only shows that entry being loaded while the rest are blank.

**Comment by scb261** [comment]
Works on r3095, but not on 0.10.8. Probably should just wait for the next app release

**Comment by pherryo13** [comment]
sad,

**Comment by scb261** [comment]
Now it works on stable as well (0.10.9)
