### ISSUE TITLE
[Bug] MangaSee: Chapters not updating upon manual refresh 

### ISSUE THREAD

**Issue by jgjsjdh** [tachiyomiorg/tachiyomi-extensions#5737]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

## Source information
- Name: MangaSee
- Extension version: 1.2.16

## Details

MangaSee often first uploads fan translations for the latest chapters. A week later, they replace it with Official translations. 

I can see that the new Official translation chapter was re-uploaded on the MangaSee website. But when I go into the app and perform a manual refresh, it still only displays the old fan translations.

For example, chapter 138 of Solo Leveling is still showing the old translations after a manual refresh: https://i.imgur.com/GQlHZD0.jpg , even though the newer/official translations have already been uploaded on their website: https://i.imgur.com/8SdKwT4.png

**Comment by scb261** [comment]
Remove downloaded chapter and clear chapter cache in advanced settings
