### ISSUE TITLE
[Bug] Can't read downloaded after reinstalling an accidentally-uninstalled extension

### ISSUE THREAD

**Issue by iamcrucial** [tachiyomiorg/tachiyomi-extensions#5741]
## Device information
- Tachiyomi version: 1.0.10
- Android version: 10

## Source information
- Name: NHentai
- Extension version: 1.2.28

## Steps to reproduce
1. Download chapters.
2. Accidentally uninstalled an extension because I wanted to uninstall a certain one but uninstalled others.
3. Reinstall the extensions to try and read again the chapters since it wants the extension installed before reading.
4. There is a "downloaded" badge but I can't read my downloaded chapter.
5. Checked the Downloads link on J2K if its correct. It is correct.
6. Checked the Downloads folder on my device and the chapters are still there.
7. Checked the original Tachiyomi and I can read the downloaded chapter there but not in J2K.

### Expected behavior
Since I can read it on Tachiyomi, it should be fine also with J2K since I reinstalled the extensions.

### Actual behavior
Can't read all the downloaded chapters of reinstalled extensions.

## Other details
No "downloaded" chapter and I can't read it, I have to redownload the chapter.

The download path is custom since I migrated to J2K.
![Screenshot_20210210-085846](https://user-images.githubusercontent.com/78633099/107449805-32122280-6b7f-11eb-9b5c-b37b7892ed07.jpg)

Download folder on my device.
![Screenshot_20210210-085645](https://user-images.githubusercontent.com/78633099/107449831-39d1c700-6b7f-11eb-8b7b-e327119e7939.jpg)

There is "downloaded" chapter in Tachiyomi and I can read it.

**Comment by arkon** [comment]
Please don't post NSFW content.

**Comment by arkon** [comment]
This also sounds like it should go in the J2K GitHub repo's issues.
