### ISSUE TITLE
[Meta] <Refresh Button or option>

### ISSUE THREAD

**Issue by bungadrum** [tachiyomiorg/tachiyomi-extensions#5742]
Can you add a refresh button or option with swiping down in Latest, whenever you load a random source most of the times the Thumbnail images won't load for example like MPark RawLH. To fix this you have to open every Manga one by one and refresh it from there. When you do this the thumbnail img will appear, but it's time consuming to do it every time.

**Comment by scb261** [comment]
Refreshing - just reopen Latest. If you need more hard refresh - clear database in advanced settings. Next time use https://github.com/tachiyomiorg/tachiyomi/issues for suggesting app features.

Mangapark - #4803.
RawLH - works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).
Next time use bug report in this repo for source issues (but troubleshoot and search opened issue before reporting).
