### ISSUE TITLE
[Bug] Mangadex: 404 error on special characters

### ISSUE THREAD

**Issue by Maerteje** [tachiyomiorg/tachiyomi-extensions#5746]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

## Source information
- Name: MangaDex
- Extension version: 1.2.103

## Steps to reproduce
1. Search for a manga containing a ' character (e.g. "The demon lord's Love Life isn't going well", "I'll Become the Tyrant's Tutor")
2. Select the manga cover from the search result to go into its details
3. No information is retrieved and a toast notification returns a HTTP error 404 (see screenshot below)
![image](https://user-images.githubusercontent.com/39061526/107529550-43792000-6bbb-11eb-838f-4c6431704805.png)

### Expected behavior
The manga is retrieved as usual as well as its chapters, description, etc.

### Actual behavior
The manga details are not retrieved, only a 404 error is returned.

## Other details
It's probably to the encoding of the single-quote character, I haven't tried with any other special characters.

**Comment by Seishirou101** [comment]
no, its related to #5627.

**Comment by Maerteje** [comment]
I don't believe it's related. By selecting "The villainess is a marionette" (first manga in Mangadex > latest) which has chapters in webview and none in tachiyomi, the description is retrieved and the toast only says "No chapters were found". Not the 404 error and no description issue.

**Comment by Seishirou101** [comment]
completely related. 
https://mangadex.org/title/61649/the-demon-lord-s-love-life-isn-t-going-well 
https://api.mangadex.org/v2/manga/61649

**Comment by scb261** [comment]
See above, the api returns 404 by manga id, so it's indeed api server issue
