### ISSUE TITLE
[Bug] <void scans>: <can't download>

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#5748]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

## Source information
- Name: void scans
- Extension version: 1.2.1

## Steps to reproduce
1. Search for void scans
2. Download it

### Expected behavior
Should be downloaded

### Actual behavior
Doesnt download

**Comment by scb261** [comment]
The extension can be downloaded and installed, but the app doesn't detect it

**Comment by arkon** [comment]
The package or class name is probably wrong.

@Riztard
