### ISSUE TITLE
Tumangaonline **Spanish extension** Have problems

### ISSUE THREAD

**Issue by Sessho0** [tachiyomiorg/tachiyomi-extensions#5755]
I have problems with The spanish extension of Tachiyomi **Tumangaonline/TMO** In all the mangas comes out a black screen and "retry" message, i have 2 days with this problem.
![b57d072e-333f-4e4a-a285-28179fdcb5c8](https://user-images.githubusercontent.com/78880519/107572447-b0dc7f00-6bc2-11eb-8a1d-b2bd142f7b12.jpg)

## Device information
* Tachiyomi version: stable 0.10.7
* Android version: ? 10.0.0
* Device: ? Huawei Y9 PRIME

**Comment by J-VF** [comment]
Creí que solo me pasaba a mí

**Comment by monarca-kim** [comment]
Lo mismo me pasa a mi, alguna solución?

**Comment by J-VF** [comment]
> Lo mismo me pasa a mi, alguna solución?

Parece que se arregló hoy (por lo menos a mí sí me funciona ahora), lo que pasa es que la página renovó/cambió un certificado y yo supongo que tenían que renovar ese certificado en la extensión y por eso la falla

**Comment by edgarMejia** [comment]
Este era un problema con los certificados de la páginad TMO

This issue can be close, the problem is fixed by TMO.
