### ISSUE TITLE
[Bug] <Mangapark>: <No Thumbnails>

### ISSUE THREAD

**Issue by schimits221** [tachiyomiorg/tachiyomi-extensions#5759]
## Device information
- Tachiyomi version: App version: 0.10.8 (standard, 45a19d1, 55)
- Android version: 8.0.0 (SDK 26)
- Android build ID: R16NW.G935FXXS8ETCB
- Device brand: samsung
- Device manufacturer: samsung
- Device name: hero2lte
- Device model: SM-G935F
- Device product name: hero2ltexx

## Source information
- Name: Mangapark
- Extension version: 1.2.17

## Steps to reproduce
1. Open Tachiyomi
2. Tap on Mangapark to browse (not the latest one)

### Expected behavior
Thumbnails should appear above the list on manga's title

### Actual behavior
Only readed/tapped manga that shows its thumbnail

## Other details
Connections are good
![SmartSelect_20210211-053108_Tachiyomi](https://user-images.githubusercontent.com/42657530/107581254-61ca3480-6c2a-11eb-8a8f-65d6dd95d003.jpg)

**Comment by scb261** [comment]
Works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)

**Comment by schimits221** [comment]
> Works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)

Ah, yes. Somehow after restarted it works perfectly, so im guessing its the dns (cloudflare) checked in my settings, sorry.
