### ISSUE TITLE
[Bug] <Mangahere>: <Source web is inaccessible>

### ISSUE THREAD

**Issue by hmmokay** [tachiyomiorg/tachiyomi-extensions#5762]
## Device information
- Tachiyomi version: 0.10.8
- Android version: Android 10

## Source information
- Name: Mangahere
- Extension version: 1.2.15

## Steps to reproduce
1. Go to Browse
2. Choose Sources
3. Select Mangahere

### Expected behavior
It should have shown all manga list that available from the site, including all manga that was added in Library.

### Actual behavior
It produces Connection Timeout. Tried via Web-View also produces the same issue. Tested via VPN and browser, website also unreachable

## Other details
Mangahere.cc website seems down currently as it's inaccessible from Extension, Web-view and Browser. It also produce issue that all manga that has been added to library from Mangahere is not showing when searching via Browse then choose Search, while it showing when searching from Library then select Search. All downloaded chapters from the source that was downloaded prior this issue also missing from Library, while the manga itself is still in the library.

**Comment by arkon** [comment]
As you mentioned yourself, the website is down.
