### ISSUE TITLE
[Source Request] Webnovel.live is missing

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#5763]
After the extension split, webnovel.live is gone. Please reup it agan

**Comment by scb261** [comment]
It's still there and named `WebNovel` just as it was named before

**Comment by samanta-widjaja** [comment]
That's webnovel.com not webnovel.live. before there are webnovel and webnovel.live

**Comment by samanta-widjaja** [comment]
Please reopen this

**Comment by arkon** [comment]
You're wrong, but this does bring up the issue that the Madara version shadows the non-Madara version, which is now missing.

**Comment by Seishirou101** [comment]
what scb said is correct... did you even open it? 
![421-879-max](https://user-images.githubusercontent.com/57241064/107601266-1f9af600-6c1e-11eb-88b7-b90ff9b918f1.png)
