### ISSUE TITLE
[Bug] Readmanhwa: No results found when NSFW is toggled

### ISSUE THREAD

**Issue by LandChit** [tachiyomiorg/tachiyomi-extensions#5765]
## Device information
- Tachiyomi version: 10.8
- Android version: 10

## Source information
- Name: ReadManhwa
- Extension version: 1.2.7

## Steps to reproduce
1.Open the extension

### Expected behavior
It should show everything even the NSFW

### Actual behavior
Shows No results Found

## Other details
By turning off the NSFW flag it works fine

**Comment by ugivibbu** [comment]
I also have this problem,I hope you fix it 
It is a good source
