### ISSUE TITLE
[ChangeURLMagakakalot]MangaKakalot:MangakakalotDOWN

### ISSUE THREAD

**Issue by kasuma0** [tachiyomiorg/tachiyomi-extensions#5766]
Hi.
MangaKakalot is down and there is a new URL for MangaKakalot.  it is https://ww.mangakakalot.tv

**Comment by Seishirou101** [comment]
unless the original mangakakalot redirects to this domain, or you have an official statement of the switch, you can assume its just a copycat... you can make a source request for it if you'd like.

**Comment by kasuma0** [comment]
Nevermind. mangakakalot has revived
