### ISSUE TITLE
[Bug] Webnovel.com: No Manga found

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#5768]
## Device information
- Tachiyomi version: TachiyomiSy r337
- Android version: 10

## Source information
- Name: Webnovel.com
- Extension version: 1.2.2

## Steps to reproduce
1. open The source
2. and try anything 
### Expected behavior
Manga should appear

### Actual behavior
returns "No results found"

## Other details
check web-view its working and shows the right site webnovel.com
![Screenshot_20210211-192542_TachiyomiSY](https://user-images.githubusercontent.com/34899572/107607845-4cf19f00-6c32-11eb-92f5-229eac006484.jpg)

**Comment by Riztard** [comment]
i think this related to #5767

**Comment by jopejoe1** [comment]
Needs to be reopened as it did not fix the Webnovel.com extension still no manga visible any where in the extension
![Screenshot_20210212-022852_TachiyomiSY](https://user-images.githubusercontent.com/34899572/107642825-3f8fef80-6cda-11eb-87c2-c5e94c9358d2.jpg)

**Comment by arkon** [comment]
Works fine for me, go through [the troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting-problems/).

**Comment by jopejoe1** [comment]
Okay did a bit of trying around and found that my app is trying to load the mobile version of the website but the extension seems to be written with desktop version in mind.
