### ISSUE TITLE
[Bug] <NANI? Scans>: <creates new folder every time you download a new chapter from source>

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#5771]
---

## Device information
- Tachiyomi version: J2K 1.0.10
- Android version: Android Q (10.0)

## Source information
- Name: NANI? Scans
- Extension version: 1.2.5

## Steps to reproduce
1. Download a chapter from source
2. Check if downloaded chapter can be viewed without internet connection
3. Check files where folder download is

### Expected behavior
Downloaded chapter can be read after downloading and no new folders are creates.

### Actual behavior
The downloaded chapter cant be viewed on app, and a new NANI? Scans folder is created on files

**Comment by CrepeTF** [comment]
Sounds similar to Manga Plus problem where the first folder name isn't properly names, so it keeps trying to make a proper folder, but because the folder name is the same (nigh for capitalization) it keeps creating duplicate folders.

Delete all the NANI Scans folders and download again.

**Comment by scb261** [comment]
Did removing the source folder and redownloading help? How does it look in a file manager? I think it's probably the same issue as #5191 and question mark should be removed from the source name.

**Comment by scb261** [comment]
This is actually a fork issue - Tachiyomi already sanitizes source names in downloads. It's possible to change source name, but I think it should be fixed on the fork side.
| Tachiyomi r3783 | J2K v1.2.1 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/65343233/132947163-0963d66d-13e9-4e37-87b2-b854b4eba70a.png) | ![image](https://user-images.githubusercontent.com/65343233/132947148-b2727fdf-f360-4b52-a3bf-c058c56456ae.png) |
