### ISSUE TITLE
[Feature Request] Toonily.com:Icon

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#5777]
## What feature should be added to this source?
Just an icon for the toonily.com source![Icon_Toonily.jpg](https://user-images.githubusercontent.com/56766778/107625507-b4bcdf80-6c5c-11eb-8bfc-8cc6887eb016.jpg)

**Comment by Mitia99** [comment]
Here is the website icon on browser![Screenshot_20210211_132920.jpg](https://user-images.githubusercontent.com/56766778/107625646-e635ab00-6c5c-11eb-9d98-585bf62ad7a0.jpg)

**Comment by CrepeTF** [comment]
@as280093 do your thing :whip:

**Comment by as280093** [comment]
Okie
