### ISSUE TITLE
[Bug]  Hentaivn: The extension can't search manga

### ISSUE THREAD

**Issue by Sehai1** [tachiyomiorg/tachiyomi-extensions#5781]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

## Source information
- Name: Hentaivn
- Extension version: 1.2.6

### Expected behavior
Search in the extension can find manga

### Actual behavior
The extension can't search manga although webview can
![Screenshot_2021-02-11-20-29-13-397_eu kanade tachiyomi](https://user-images.githubusercontent.com/64726925/107647326-9f23d600-6cad-11eb-8a4f-d4e0491e505e.jpg)

**Comment by scb261** [comment]
I fixed it and will PR soon, can you translate "Log in via `WebView` to enable search" to Vietnamese? Don't change the `WebView` part.

**Comment by Sehai1** [comment]
> I fixed it and will PR soon, can you translate "Log in via `WebView` to enable search" to Vietnamese? Don't change the `WebView` part.

"Log in via `WebView` to enable search" in Vietnamese is "Đăng nhập qua `WebView` để kích hoạt tìm kiếm"
Btw i login webview, search doesn't work :(

**Comment by Sehai1** [comment]
What do u mean? U fixed search in the extension or webview?

**Comment by scb261** [comment]
I fixed the search, but you need to log in via WebView for it to work. Wait until maintainers will merge it and update the extension after this

**Comment by Sehai1** [comment]
> I fixed the search in the extension, but you need to log in via WebView for it to work. Wait until maintainers will merge it and update the extension after this

I login via webview then the extension didn't work :'(
