### ISSUE TITLE
Mangakakalot Chapter Pictures

### ISSUE THREAD

**Issue by SebasTianzer** [tachiyomiorg/tachiyomi-extensions#5785]
Uhmm I can't see the pictures of latest chapters in mangakakalot... How to fix??? Oh same in manganelo

**Comment by CarlosEsco** [comment]
#5750

**Comment by SebasTianzer** [comment]
Hello do u have a fix for missing thumbnails in mangakakalot?

**Comment by CarlosEsco** [comment]
go on the discord channel read the rules and status updates and ask on support.
