### ISSUE TITLE
[Bug] Leitor.net: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by maz1no** [tachiyomiorg/tachiyomi-extensions#5787]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 8.1.0

## Source information
- Name: Leitor.net (mangásPROJECT)
- Extension version: 1.2.16

## Steps to reproduce
1. Trying to Download at app/view a chapter at Tachiyomi browser
2. Failed to bypass Cloudflare

## Other details
Totally fine running at 3rd party browser. Error persists when I try to use the Tachiyomi browser. 

Also have some mangas with "restricted images" like "The God of Highschool" and "Tower of God (Season 2)" but I don't know if you guys can do something about it.

**Comment by alessandrojean** [comment]
This is an issue related to the WebView, where for some reason it keeps in an infinite cycle at the Cloudflare page. It's a known problem, and it happens in some other sources. There's nothing that can be done on the extension side to fix this for now.


I can suggest you to be persistent and try to resolve the captcha at the WebView (sometimes it works), or migrate the mangas in your library to another source.


About the restricted images, I will see if I can reproduce and submit a fix.

**Comment by maz1no** [comment]
Thank you!
