### ISSUE TITLE
[Source Request] Manga Susu

### ISSUE THREAD

**Issue by k9uu** [tachiyomiorg/tachiyomi-extensions#5789]
## Source website
- Name: Manga Susu
- Link: https://m.mangasusu.co/
- Language(s): Indonesia

**Comment by Seishirou101** [comment]
Does this site still exist? it is down for me when I try to access it.

**Comment by Seishirou101** [comment]
closing due to lack of response, the site is still down for me and shows down on a down service checker. Please open a new issue with the correct website if one exists if you still want it.
