### ISSUE TITLE
[Bug] erro na extençao do tsuki mangas

### ISSUE THREAD

**Issue by GODDEATH1** [tachiyomiorg/tachiyomi-extensions#5802]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 7.1.2

## Source information
- Name: tsuki mangas
- Extension version: 1.2.8

## Steps to reproduce
Ao tentar abir a extençao ela não carrega e da o erro http 404
![Capture+_2021-02-12-09-14-11](https://user-images.githubusercontent.com/74791666/107770456-2a39b600-6d18-11eb-849f-90854727708c.png)

**Comment by CrepeTF** [comment]
#5794
