### ISSUE TITLE
[Bug] <Tsuki Mangas>: Chapters do not appear

### ISSUE THREAD

**Issue by matheuswr89** [tachiyomiorg/tachiyomi-extensions#5807]
## Device information
- Tachiyomi version:  0.10.7
- Android version: 9

## Source information
- Name: Tsuki Mangas
- Extension version: 1.2.9

## Steps to reproduce
1. Choose a manga from the source

### Expected behavior
Chapters are expected to appear

### Actual behavior
As you can see in the Image below, the chapters do not return and a message appears.
![Screenshot_20210212-154303](https://user-images.githubusercontent.com/44068234/107809839-80275180-6d4a-11eb-8fb8-f1b7480d33c6.png)

**Comment by alessandrojean** [comment]
I will take a look.
