### ISSUE TITLE
[Source Request] Mangasusu

### ISSUE THREAD

**Issue by SokKeras** [tachiyomiorg/tachiyomi-extensions#5813]
## Source website
- Name: Mangasusu
- Link: https://mangasusu.world
- Language(s): Indonesia

**Comment by web-apply** [comment]
mangasusu.world is a safe website about "MangaSusu - Read Manga and Manhwa Home" in chapter category. The server is running at 104.31.87.34 ip address and [mangasusu](https://login.page/mangasusu.me) there is a secure connection certificate between the website and the visitor.

**Comment by keinezeit8** [comment]
redirects to https://mangasusu.biz/

**Comment by vetleledaal** [comment]
old domain is parked, new domain is down since 11 dec 2021 http://web.archive.org/web/2021*/http://mangasusu.biz/

**Comment by Seishirou101** [comment]
You can reopen if it ever comes back up.
