### ISSUE TITLE
[Bug] TMOHentai: the imagen chapter do not load

### ISSUE THREAD

**Issue by AlexPuyol95** [tachiyomiorg/tachiyomi-extensions#5816]
## Device information
- Tachiyomi version: 10.8
- Android version: 10

## Source information
- Name: TMOHentai
- Extension version: 1.2.4

## Steps to reproduce
1. Open the extension
2. Open a chapter
3. Try to read a chapter

### Expected behavior
Be able to read a chapter

### Actual behavior
the chapter imagens never load

**Comment by alexfo0** [comment]
Device information
Tachiyomi version: 10.8
Android version: 10
Source information
Name: TMOHentai
Extension version: 1.2.4
Steps to reproduce
Open the extension
Open a chapter
Try to read a chapter
Expected behavior
Be able to read a chapter

Actual behavior
the chapter imagens never load

**Comment by liondarlieds** [comment]
Me pasa lo mismo

**Comment by AlexPuyol95** [comment]
Gente no se que paso pero ahora Tmohentai está funcionando, vayan y verifiquen

**Comment by scb261** [comment]
As the author said above, it works now
