### ISSUE TITLE
[Bug] <ManhwaSmut>: <unable to install>

### ISSUE THREAD

**Issue by dragneel152** [tachiyomiorg/tachiyomi-extensions#5823]
## Device information
- Tachiyomi version: v.8.6.3-AZ
- Android version: 10

## Source information
- Name: ManhwaSmut
- Extension version: 1.2.1

## Steps to reproduce
1. First Step - Go to the extentions tab and click install on the ManhwaSmut extension.
2. Second Step

### Expected behavior 
what should have happened is that the extension should be installed and should be shown and listed in the source tab

### Actual behavior
what happens instead is that after you install it does show that the extension is installed but when you check your source page it's not present/available there, and if you once again check go and check the extension tab the ManhwaSmut extension is again showed as an extension you have yet to install.

**Comment by arkon** [comment]
Wrong subpackage: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/3bc1aa5e3bc510ed845be0df9790fbf09f039f7c/multisrc/overrides/fmreader/manhwasmut/src/ManhwaSmut.kt#L1

@AriaMoradi
