### ISSUE TITLE
[Bug] Manhuagui: SSL handshake timed out in the App but Webview Works Fine

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi-extensions#5829]
## Device information
- Tachiyomi version: TachiJ2K 1.0.10
- Android version: 10

## Source information
- Name: ManHuaGui
- Extension version: 1.2.7

## Steps to reproduce
1. Open Manhuagui's recent update page or index page
2. Wait loading and met `SSL handshake timed out` error as last.
3. Open Manhuagui website in Webview mode, the site can load without any problem.
4. Checking any limited-level manga, works fine.

### Expected behavior
App can load Manhuagui's manga list normally.

### Actual behavior
`SSL handshake timed out` error

## Other details
By searching `Manhuagui.kt` file, I had already add `manhuagui.com` and `hamreus.com` into the proxy list, demand software access them with JP ip.
Since I can access the site and manga in Webview mode, I think it may not be connectivity problem. 
Where might gone wrong?

**Comment by scb261** [comment]
Works for me. Check **Chain validation failed** in the common errors. Also try going through diagnosis https://tachiyomi.org/help/guides/troubleshooting-problems

**Comment by scb261** [comment]
Did you try what I said above? Does it still happen to you?

**Comment by LenKiMo** [comment]
Sorry for reply late.
Clear cookies doesn't help. I had tried open Manhuagui in Webview mode and login as user, everything goes fine inside webview, but when come back it still report same error.

**Comment by scb261** [comment]
So you only tried clearing cookies and going to WebView? There is more in `Chain validation failed` and `Diagnosis` sections. Can you also screenshot the error, there may be some useful information in it.

**Comment by LenKiMo** [comment]
DNS over HTTPS is open from start, and Clear Database and Clear Cache doesn't help too.

I am alwasys connect via proxy, since Webview page is accessible, I think it could not be a part of problem.

![image.png](https://i.loli.net/2021/03/02/glErvPwpuJVS4tQ.png)

**Comment by scb261** [comment]
Well, it's working for me, so it's probably something on your side. Looking at your comment it still feels like you didn't try everything in the guide, make sure you actually tried everything from it. 

Maybe your proxy only affects Tachiyomi but not WebView app. Did you try disabling proxy? Using different proxy? Using VPN instead of proxy?

**Comment by LenKiMo** [comment]
All of steps list on `Diagnosis`, Clear Cache, Clear Cookies, Clear Database, DNS over HTTPS has been done, and did not take any effects.

My proxy is work as VPN, and filtered by domain, so if it works for Webview, it also should works for any other App. That's why I confused.

**Comment by LenKiMo** [comment]
This problem is solved by TachiJ2K 1.0.11 update. Thanks for your concerned.
