### ISSUE TITLE
[Bug] hitomi.la: pages don't load for select manga

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#5830]
## Device information
- Tachiyomi version: 10.9
- Android version: 10

## Source information
- Name: hitomi.la
- Extension version: 1.2.5

## Steps to reproduce
1. Attempt to read;
* Boku no Otona Shokugyo-taiken | My Adult Work Experience Ch. 6
* Boku no Otona Shokugyou Taiken | My Adult Work Experience Ch. 4
* Mon Cafe yori Ai o Komete | With Love, the Monster Cafe (page 17)
2. All pages are stuck on "retry" instead of loading.

### Expected behavior
Pages should load normally and be readable.

### Actual behavior
Pages stuck on retry.

## Other details
I have run into this issue on a few other manga on hitomi.la however I forgot the titles, these are the ones I added to my library.

**Comment by MercerBoi** [comment]
Facing this exact same issue for pretty much most of the manga from this source.

**Comment by naimyuri** [comment]
yeah this need a fix, pretty much all of the manga from this source have this bug
