### ISSUE TITLE
[Source Request] <Tempest Fansub>

### ISSUE THREAD

**Issue by YukiHimeTempest** [tachiyomiorg/tachiyomi-extensions#5834]
## Source website
- Name: Tempest Fansub
- Link: https://manga.tempestfansub.com
- Language(s): Turkish (Türkçe)

**Comment by Riztard** [comment]
Tempest Fansub/Tempest Manga?
the site title and discord is Tempest Manga 🤔

**Comment by YukiHimeTempest** [comment]
> Tempest Fansub/Tempest Manga?
> the site title and discord is Tempest Manga 🤔

Yeah. I mean Tempest Manga
