### ISSUE TITLE
[Bug] Scantrad: 403 Error

### ISSUE THREAD

**Issue by vic-blt** [tachiyomiorg/tachiyomi-extensions#5850]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Scantrad [FR]
- Extension version: 1.2.12

## Steps to reproduce
1. Install Scantrad extension
2. Go to **Browse** tab
3. Open Scantrad source

### Expected behavior
It should list mangas available on Scantrad website

### Actual behavior
There's a 403 HTTP error

### Related issues
#5243, #5560, #5322

**Comment by OncePunchedMan** [comment]
they are actively blocking tachi and we tried fixing scantrad by adding this useragent

**Comment by vic-blt** [comment]
I know, I've read the issues regarding the situation with Scantrad's admins.
But currently, the headers have to be removed in order to get rid of the 403 HTTP error and be able to fetch Scantrad URLs.
Maybe it's the setting of the referer which causes the 403 HTTP error.
Could you test with the setting of the user-agent header only ?

**Comment by vic-blt** [comment]
Well that was quick, tachiyomi is blocked again.
