### ISSUE TITLE
[Source Request] <AnimaRegia Scantrad>

### ISSUE THREAD

**Issue by luscarvalho** [tachiyomiorg/tachiyomi-extensions#5854]
- Name: AnimaRegia
- Link: https://animaregia.net/
- Language(s): Portuguese(Br)

**Comment by alessandrojean** [comment]
Already exists in My Manga Reader CMS extension.

**Comment by luscarvalho** [comment]
> Already exists in My Manga Reader CMS extension.

Thanks, I didn't know you were together.
