### ISSUE TITLE
[Bug] hentaivn, hentainexus: extension can't bypass the cloudflare.

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi-extensions#5860]
Hentaivn, hentainexus extension can't bypass the cloudflare. But the webview still ok.

**Comment by scb261** [comment]
We don't support HentaiNexus
As for HentaiVN - maybe try to read a chapter in WebView or do some other actions that trigger cloudflare

**Comment by Noname-noragami** [comment]
I have use app with socks5

**Comment by Noname-noragami** [comment]
So the source taichi can't pass it
