### ISSUE TITLE
[Source Request] <Mangahua>

### ISSUE THREAD

**Issue by FlammFR** [tachiyomiorg/tachiyomi-extensions#5873]
## Source website
- Name: Mangahua
- Link: https://www.mangahua.net/
- Language(s): English

**Comment by CrepeTF** [comment]
Not to be confused with **manhuaga.com** which exists

**Comment by vetleledaal** [comment]
Site has been down for a month. Additionally, Wayback Machine indicates the site has been having issues since December 2021.
