### ISSUE TITLE
[Bug] Dragonball-Multiverse: messy language codes and names

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#5877]
## Device information
- Tachiyomi version: TachuyomiSY r339
- Android version: 10

## Source information
- Name: Dragon Ball Multiverse
- Extension version: 1.2.1

## Steps to reproduce
1. Go to Language selection
2. See language codes

### Expected behavior
Should show language name written out for all languages 

### Actual behavior
Shows a mix between languages names written out, language codes and strange combinations in between and wrong languages 

## Other details
List of Languages:
Language -> Displays as -> should Display as
/ stands for or
- [x] English -> English -> English
- [x] French -> Français -> Français
- [ ]  Japanese -> Jp -> 日本語
- [ ] Chinese -> Cn -> 中文
- [x] Spanish -> Español -> Español
- [x] Italian -> Italiano -> Italiano
- [x] Portuguese -> Português -> Português
- [x] German -> Deutsch -> Deutsch
- [x] Polish -> Polski -> Polski
- [x] Dutch -> Nederlands -> Nederlands
- [ ] Turkish -> Displayed as Türkçe (Türkiye) -> Türkçe
- [x]  Portuguese (Brazil) -> Português (Brasil) -> Português / Português (Brasil)
- [ ] Hungarian -> Magyar (Magyarország) -> Magyar
- [ ] Galician -> Gaeilge (an Spáinn) -> Galego
- [ ] Catalan -> Ct (CT) -> Català
- [ ] Norwegian -> Norsk (Norge) -> Norsk
- [ ] Russian -> Русский (Россия) -> Русский
- [ ] Romanian -> Română (România) -> Română
- [ ] Basque -> Euskara (Mendebaldeko Sahara) - > Euskara
- [ ] Lithuanian -> Lietuvių (Lietuva) -> Lietuvių
- [ ] Croatian -> Hrvatski (Hrvatska) -> Hrvatski
- [ ] Korean -> Kanuri (South Korea) -> 한국어
- [ ] Finnish -> Suomi (Suomi) -> Suomi
- [ ] Hebrew -> עברית (HE) -> עברית
- [ ] Bulgarian -> Български (България) -> Български
- [ ] Swedish -> Svenska (Sverige) -> Svenska
- [ ] Greek -> Gr (Greece) -> ελληνικά
- [?]  Spanish (Latino) -> Español (Colombia) -> Español / ???
- [ ] Arabic ->  -> العربية
- [ ] Filipino -> Tagalog (PI) -> Filipino
- [ ] Latin -> Latin (Laos) - Latin
- [ ] Danish ->Dansk (Danmark) -> Dansk
- [ ] Corsican -> Corsican (France) -> Corsu
- [ ] Breton -> Brezhoneg (Frañs) -> Brezhoneg
- [ ] Venetian -> Xx (Venezuela) -> Vèneto
- [ ] French -> Français (Panama) -> Français -> Note: This is a parody version.

**Comment by CarlosEsco** [comment]
Did you verify its the same in the main Tachiyomi?

**Comment by jopejoe1** [comment]
Yes Also tested in Tachiyomi Preview r3121

**Comment by scb261** [comment]
Thanks for the list, it was really useful
