### ISSUE TITLE
[Source Request] ReadComicManga

### ISSUE THREAD

**Issue by ric0369** [tachiyomiorg/tachiyomi-extensions#5880]
## Source website
- Name: ReadComicManga
- Link: https://readcomicmanga.com/
- Language(s): English (EN)

**Comment by vetleledaal** [comment]
Requires a $3.9/month subscription to access chapters. Partial implementation https://gist.github.com/vetleledaal/cf7cc1d0ef743eb6bf9c63027deba4f6
