### ISSUE TITLE
[Bug] Manga Raw: Not showing up after WP MangaStream's split, ID conflict

### ISSUE THREAD

**Issue by crisalis2** [tachiyomiorg/tachiyomi-extensions#5881]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Manga Raw

##
The WP MangaStream extension included a Manga Raw (mangaraw.org) source. Then it was splitted, but there isn't a new corresponding Manga Raw extension showing up in the app itself or in https://tachiyomi.org/extensions/ . 

Note that there is an unrelated extension called MangaRaw (manga1001.com and manga1000.com), not based on WP MangaStream. 

In fact, after a quick glance at WP MangaStream's split commit I think the problem is probably that WP MangaStream's Manga Raw (mangaraw.org) gets assigned to eu.kanade.tachiyomi.extension.ja.mangaraw, but that ID was already being used by the other MangaRaw (manga1001.com and manga1000.com).

@Riztard

**Comment by Riztard** [comment]
@crisalis2 is the source id this one? 6223520752496636410

**Comment by crisalis2** [comment]
> @crisalis2 is the source id this one? 6223520752496636410
> related issue #5767

Sorry, how do I check that? For some reason I happened to see a document with that kind of ids a while ago, but I can't find it now...

**Comment by Riztard** [comment]
it should show number instead of source name in your manga

**Comment by crisalis2** [comment]
Yes, 6223520752496636410.
