### ISSUE TITLE
[Meta] TCB Scans duplicated

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#5896]
##  Why/Project's Benefit/Existing Problem
Explain why this should be added

TCB Scans has its own extension but is also part of the sites that are included in the MangaMainac extension.
## Other Details

**Comment by CrepeTF** [comment]
No we're trying to split the multisource extensions, not make them bigger

**Comment by jopejoe1** [comment]
I know, sorry for not being clear enough what i meant is that TCB scans currently exists 2 time's in the repo once as a separate extension and once in the MangaMainac extension.

**Comment by CrepeTF** [comment]
Fair 'nuf

**Comment by scb261** [comment]
Should we just remove separate one and force users to migrate to multi-source extension? Or maybe wait for splitting and do it then?

**Comment by CarlosEsco** [comment]
@Riztard are you planning splitting more of the multisource ext?

**Comment by Riztard** [comment]
nah, all my source is splitted LOL
