### ISSUE TITLE
[Source Request] mangakakalot.com

### ISSUE THREAD

**Issue by Koxmo** [tachiyomiorg/tachiyomi-extensions#5897]
Source request

Name: mangakakalot
Link: https://mangakakalot.com/
Language(s): French (français, FR)

Thanks you

**Comment by CrepeTF** [comment]
Already exists, just remember to enable French language in source and extensions filters

**Comment by RealKC** [comment]
It's actually a SingleLang for english source, but I'm not sure how you get the website to become french anyway

**Comment by scb261** [comment]
@Koxmo can you give link to French version?

**Comment by Koxmo** [comment]
hello, I'm really sorry, google translation misled me, the page being in French I believed that the manga I was looking for too, I took your time, sorry sorry ...

**Comment by scb261** [comment]
Closing since English version already exists
