### ISSUE TITLE
[chapter not loading] <Sen Manga>: <chapters not refreshing>>

### ISSUE THREAD

**Issue by Anifan2021** [tachiyomiorg/tachiyomi-extensions#5905]
---

## Device information
- Tachiyomi version: 10.9
- Android version: ?

## Source information
- Name: ?
- Extension version: Sen manga

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened
Chapters should refresh and web view should work
### Actual behavior
Describe what happens instead
Chapters are not refreshed and web viewer not working

**Comment by happywillow0** [comment]
Hi @Anifan2021 
Sen Manga recently got updated as the webpage may have changed a bit. Have you tried again yet? 
I'm not sure how much the website has changed recently. You can try to use the Migrate function from Sen Manga to Sen Manga to refresh the link to the website for the manga.

**Comment by Anifan2021** [comment]
Thanks issue resolved after installing update of extension
