### ISSUE TITLE
[Bug] <Mangadex>: <i can't download chapters>

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#5907]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 5.1.1

## Source information
- Name: mangadex
- Extension version: 1.2.10

## Steps to reproduce
1. I can find new chapter on mangadex extension 
2.  I try download this chapter

### Expected behavior
Chapters download normally

### Actual behavior
I only can see how many there are pages, but when I try download or read this chapter in app I see a messenge "try again". Olders chapters are download normally.

## Other details
I have this problem on nox emulator but everything working on my phone. Other extension are working normally.

**Comment by scb261** [comment]
Do you have data saver enabled on emulator? Try to disable it (Browse > Extensions > Mangadex > gear button > Data saver) and clear chapter cache (Settings > Advanced > Clear chapter cache).

Did you try the same chapter on your phone and emulator?

**Comment by mcOz1** [comment]
> Do you have data saver enabled on emulator? Try to disable it (Browse > Extensions > Mangadex > gear button > Data saver) and clear chapter cache (Settings > Advanced > Clear chapter cache).
> 
> Did you try the same chapter on your phone and emulator?

Thank you!!!! I did what you tell me and it work!
