### ISSUE TITLE
[Bug] Mangakawaii: Chapter "ghost" appeared in each series

### ISSUE THREAD

**Issue by RGFRv2** [tachiyomiorg/tachiyomi-extensions#5910]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 11

## Source information
- Name: Mangakawaii 
- Extension version: 1.2.21

## Steps to reproduce
1. Go to Mangakawaii and take a series at random & Look at a series you have in your library.
2. It displays a new last chapter available without any information.

### Expected behavior
It should display just the last available chapter 1st but this is not the case.

### Actual behavior
Since the update, there is a ghost chapter without any information in all series.
on the site it displays 39 chapters but on the application it displays 40 chapters (## Other details)

## Other details
(In app)
![Screenshot_20210218-092835_Tachiyomi](https://user-images.githubusercontent.com/38694732/108330420-dde5ee80-71cd-11eb-805f-4a771aa46329.png)
(On the site)
![Screenshot_20210218-094648_Tachiyomi](https://user-images.githubusercontent.com/38694732/108330752-4634d000-71ce-11eb-968d-e585dc2ccb9e.png)

Show

**Comment by Riztard** [comment]
not happening to me, try refresh manga by drag down?

**Comment by RGFRv2** [comment]
Already tried

https://user-images.githubusercontent.com/38694732/108339752-1a1e4c80-71d8-11eb-98d8-8f1a0cdaff21.mp4

**Comment by sikiang** [comment]
Same problem for me and now i cannot download chapter

**Comment by happywillow0** [comment]
I was working on this extension trying to fix something else. 

Is this issue still happening? I haven't come across this issue with a ghost chapter yet in my testing.

**Comment by RGFRv2** [comment]
> I was working on this extension trying to fix something else.
> 
> Is this issue still happening? I haven't come across this issue with a ghost chapter yet in my testing.

No it's good the ghost page problem doesn't exist anymore.
