### ISSUE TITLE
[Bug] <Dream Manga>: <updated failed>

### ISSUE THREAD

**Issue by FlammFR** [tachiyomiorg/tachiyomi-extensions#5915]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 9

## Source information
- Name: Dream Manga
- Extension version: 1.2.1

## Steps to reproduce
1. Update manga from Dream Manga

### Expected behavior
Chapters update

### Actual behavior
Update failed

**Comment by scb261** [comment]
Looks like they have issues with certificate
> This server couldn't prove that it's **dreammanga.com**; its security certificate is from **shortener.secureserver.net**.

**Comment by scb261** [comment]
The old link https://dreammanga.com redirects to their new domain https://en.ruyamanga.com , the extension should be changed accordingly
