### ISSUE TITLE
[Meta] <Add the abilty to create filter presets when searching in extensions>

### ISSUE THREAD

**Issue by ManyMangaAreMangos** [tachiyomiorg/tachiyomi-extensions#5920]
Hi. When looking for new manga, I often use a filter search in the extensions I use. In most cases, I often look for a certain kind of thing in particular, so this means checking certain genre boxes, and x-ing a lot of others in order to exclude them.

I 'd like to humbly offer the idea of being able to make your own presets, which, when enabled, includes and excludes the genres which you've slected for that preset. Personally, I'd find this very useful, and I think some others would, too. Not a biggie, but a nice convenience

**Comment by curche** [comment]
As I understand, duplicate/related to https://github.com/tachiyomiorg/tachiyomi/issues/1484
