### ISSUE TITLE
[Bug] <MangáLivre (mangásPROJECT)>: <pages don't load for select manga>

### ISSUE THREAD

**Issue by zumba-lon** [tachiyomiorg/tachiyomi-extensions#5923]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 8

## Source information
- Name: MangáLivre (mangásPROJECT)
- Extension version: 1.2.17

## Steps to reproduce
1. All pages are stuck on "retry" instead of loading.

### Expected behavior
Pages should load normally and be readable.

## Other details

the chapter imagens never load

**Comment by scb261** [comment]
> pages don't load for select manga

what manga and chapter?

**Comment by zumba-lon** [comment]
Virtually all of mangas

**Comment by layon-ru** [comment]
> > pages don't load for select manga
> 
> what manga and chapter?

It is not possible to load the content or update the chapters

**Comment by alessandrojean** [comment]
Not happening to me in the mangas I tested. Can you provide me a manga and chapter as an example where this occurs?

Have you tried to open a chapter or a manga in the WebView and try to complete the captcha?

Maybe it was a temporary problem with the site, or specific with the manga you are trying to read (and if it's the case, there's nothing that can be done on the extension side).

If it's still happening to you, try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting-problems/).

**Comment by zumba-lon** [comment]
what happens, when I search for a manga it keeps loading infinitely, only after I reset the tachiyomi it opens or sometimes the chapter and the cover of the manga does not appear.

**Comment by alessandrojean** [comment]
Probably is related to the rate limiting, I will try to increase it a little bit.
