### ISSUE TITLE
HTTP error 400 - Hikari Scan

### ISSUE THREAD

**Issue by thanosluyang** [tachiyomiorg/tachiyomi-extensions#5925]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 7

## Source information
* Source name: Hikari Scan
* Source extension version: 1.2.1

## Steps to reproduce
1. Click on the extension or latest.

## Issue/Request
It gives an error saying to access the website, which is normal.

## Other details
After maintenance on the site the extension stopped working.

**Comment by Riztard** [comment]
look like they change their theme from madara to mangastream

**Comment by thanosluyang** [comment]
it seems they are using mangareader theme now
