### ISSUE TITLE
Locked chapter value/filter

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#5927]
##  Why/Project's Benefit/Existing Problem

A value that can be set in SChapter that indicated if a chapter is a locked/premium chapter.
This could than be implemented in tachiyomi as a filter option to hide locked chapters from the chapter list.

## Other Details
Would require implementation by both tachiyomi app and extensions.

**Comment by hyoretsu** [comment]
Seeing how there's already a way to identify locked chapters (só they can load the lock icon) this might only be needed on Tachiyomi's part
