### ISSUE TITLE
[Bug] <Mangalib>: <manga don't refresh>

### ISSUE THREAD

**Issue by Kongs23** [tachiyomiorg/tachiyomi-extensions#5933]
## Device information
- Tachiyomi version: Stable 1.5.0 (standard, 0413d50, 13)
- Android version: 10

## Source information
- Name: Mangalib
- Extension version: 1.2.33

## Steps to reproduce
1. Add boruto to library
2. Try updating chapters

### Expected behavior
Chapters are updated

### Actual behavior
These two errors at the same time
![Screenshot_20210220_170359_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/51830566/108596475-c27e0d80-739e-11eb-871d-e4d1d36533c2.jpg)
![Screenshot_20210220_170400_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/51830566/108596480-c90c8500-739e-11eb-829d-821606b4c01c.jpg)

**Comment by scb261** [comment]
https://mangalib.me/boruto (link from the search) redirects to the main page. Maybe it requires login or was removed. And I don't see any message about logging in, so we can't parse it to display correct error to the user. You can try logging in via WebView to see if it fixes the issue.

Not sure if the issue should be closed, or should the extension check the redirect and show an error about redirecting.

**Comment by Kongs23** [comment]
Logging in via WebView helped!!
