### ISSUE TITLE
[Bug] Manhwa.club: the extension is very slow in the app compared to the site (browser)

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#5936]
## Device information
- Tachiyomi version: 10.9
- Android version: 8

## Source information
- Name: Manhwa.club
- Extension version: 1.2.3

## Steps to reproduce
1. Try to download/view the chapters of the manhwa named "sikinen" and compare the load speed in-app and on the site (browser)

### Expected behavior
the pages should be downloaded/viewed as fast as the site (browser), always

### Actual behavior
sometimes the download/view of the paages is really slower(in-app) compared to the site (browser)

## Other details
seems manhwa.club puts tachiyomi readers in low priority or something (but not always)

**Comment by scb261** [comment]
Loads pretty fast to me. Does it happen after you download bunch of chapters? I wouldn't be surprised if they are throttling your requests when you do this, nothing can be done on the extension side in this case. You can also try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis), maybe it will help.
