### ISSUE TITLE
[Meta] Mangairo url

### ISSUE THREAD

**Issue by runboy93** [tachiyomiorg/tachiyomi-extensions#5938]
Link to Mangairo is not "https://m.mangairo.com", it should be "https://h.mangairo.com/" instead.

Extension v 1.2.1 currently.

Unlike Mangabat, Mangairo does redirect correctly even with older URL, but still there seem to be slight delay, compared to correct URL (tested web browser version)

**Comment by scb261** [comment]
Was changed in #6115
