### ISSUE TITLE
Mangahasu HTTP error 400

### ISSUE THREAD

**Issue by andrea11564** [tachiyomiorg/tachiyomi-extensions#5940]
Updated yesterday to the current version 0.10.9
All manga from Mangahasu do not works anymore. 
Had the same issue before and after the update.

**Comment by scb261** [comment]
Works for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). Give an example (what manga and chapter).

**Comment by andrea11564** [comment]
Tried everything in the guide but nothing happened.
Now randomly works fine. I do not know why and how!
Thanks a lot anyway!
