### ISSUE TITLE
[Bug] MangaRaw: Some chapters not loading

### ISSUE THREAD

**Issue by SkillGG** [tachiyomiorg/tachiyomi-extensions#5941]
## Device information
- Tachiyomi version: both 0.10.9 (freshly installed) and SY r339
- Android version: 9 PPR1.180610.011

## Source information
- Name: MangaRaw
- Extension version: 1.2.1

## Steps to reproduce
1. Open oldest chapters in one of those manga in Manga1000 or Manga1001 source:
- 塩対応の佐藤さんが俺にだけ甘い＠comic (Raw – Free) [chap 1-6]
- かぐや様は告らせたい～天才たちの恋愛頭脳戦～ (Raw – Free) [chap 1-13]
- ひとりぼっちの異世界攻略 (Raw – Free) [chap 1-22]
- よふかしのうた 漫画 (Raw – Free) [chap 1-29]

### Expected behavior
After opening the chapter pages should load and be viewed with Tachiyomi reader.

### Actual behavior
After opening the chapter, all pages show button "retry", that doesn't do anything.
You have to go to the WebView where you can read the chapter.

## Other details
Button "WebView" in the reader redirects to the manga page, not the chapter page, which can be the cause of this bug, as it doesn't have the right page to load images from.

**Comment by crassd** [comment]
Same exact issue here! Only the most recent chapter seems to work?
