### ISSUE TITLE
[Bug] <TuMangaOnline>: <Does not show some mangas>

### ISSUE THREAD

**Issue by YuiitsunoYoake** [tachiyomiorg/tachiyomi-extensions#5956]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 9

## Source information
- Name: TuMangaOnline (Spanish)
- Extension version: 1.2.29

## Steps to reproduce
1. Search some mnaga seinen, erotic or other demographic 
2. When trying to read it, no image appears

### Expected behavior
Should see the images of the searched chapter

### Actual behavior
When viewing the chapter does not load and appears "retry"

## Other details
I speak spanish, sorry if don't understand what I'm trying to say

**Comment by scb261** [comment]
Works fine for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). What manga and chapter?

**Comment by YuiitsunoYoake** [comment]
I tried it with Aki-Sora, because it is one of the first Seinen genre that appeared to me and no chapter is seen.
I also tried some Manhwa looking for Seinen or Erotic and they don't look either

**Comment by scb261** [comment]
I tried first and latest chapters for both examples and it works fine on my end. Did you try troubleshoot guide I sent above?

**Comment by KenDxD** [comment]
Try backup then clear data the app (tachiyomi) in the settings. Just restore it after.

**Comment by YuiitsunoYoake** [comment]
It's fixed, I tried it with several mangas and it works for me
