### ISSUE TITLE
[Source Request] <mytoon>

### ISSUE THREAD

**Issue by nancysavchenkoo** [tachiyomiorg/tachiyomi-extensions#5958]
## Source website
- Name: mytoon
- Link: https://mytoon.net/
- Language(s): english

**Comment by happywillow0** [comment]
Looks like the site uses Zbulu

Should this be added to "all" or should this be converted to a multisrc?

**Comment by Seishirou101** [comment]
It looks like https://heaventoon.com which is already in the zbulu currently, gets redirected to https://mytoon.net now, so we may need to update it.
