### ISSUE TITLE
[Bug] <Mangakakalot.tv>

### ISSUE THREAD

**Issue by KenDxD** [tachiyomiorg/tachiyomi-extensions#5959]
## Source website
- Name: Mangakakalot.tv
- Link: https://ww.mangakakalot.tv/
- Language(s): English

## Other details
Either update the old extension to new.

**Comment by Bm12347** [comment]
It exists
Close the issue

**Comment by Riztard** [comment]
> Either update the old extension to new

im not sure if its the same, the content more like mirroring from manganelo and the .com seems update faster

**Comment by KenDxD** [comment]
But there's a bug the shows cloudflare. And in the extension there's no update  but on the website there is.

**Comment by KenDxD** [comment]
There is no latest update on the extension of kakalot.com.

**Comment by KenDxD** [comment]
Ohhh I just found out a fix. Backup then clear data the app and just restore. Back to normal
