### ISSUE TITLE
[Bug] Gecenin Lordu and NoxSubs - Changed Theme

### ISSUE THREAD

**Issue by Agayev033** [tachiyomiorg/tachiyomi-extensions#5962]
## Device information
- Tachiyomi version: Up-to-date
- Android version: 9

## Source information
- Name: Gecenin Lordu - Madara and NoxSubs - MyMangaReaderCMS
- Extension version: Gecenin Lordu 1.2.1 and NoxSubs 1.2.54

## Steps to reproduce
They changed site theme. So this extensions not working anymore

**Comment by scb261** [comment]
Please open separate issues for each source, so they could be closed separately when someone fixes one of them
