### ISSUE TITLE
[Bug] <Mangasee>: <the title is not displayed correctly>

### ISSUE THREAD

**Issue by WeiDe2512** [tachiyomiorg/tachiyomi-extensions#5963]
## Device information
- Tachiyomi version: stable 0.10.9
- Android version: 11

## Source information
- Name: mangasee
- Extension version: 1.2.16

## Steps to reproduce
1. search a manga for example (Hazure Skill "Kage ga Usui" o Motsu Guild Shokuin ga) or (A Stepmother's Märchen)
2. you will see that the title is not correct displayed

### Expected behaviour
when I view the manga the title should be the same as the webpage

### Actual behaviour
when I search for the manga's that I gave as example the titles are displayed as 
Hazure Skill &#34Kage ga Usui&#34 o Motsu Guild Shokuin ga
A Stepmother's MaÌˆrchen

**Comment by happywillow0** [comment]
How important is this issue to you? 
The extension pulls from the database and special character issue only appears 2 times that I can find (`Myuu & I` and `Hazure Skill "Kage ga Usui" o Motsu Guild Shokuin ga`). 

The second issue with the `ä` works on my phone (Pixel 3 Android 11). 
Could it be something with your phone / language / font? Does it happen with any other extension?

**Comment by WeiDe2512** [comment]
The problem is not that major it is just annoying.
I do not have a similar problem on my phone or with the other extension.
I have a samsung s10e and the other extension that I use is Mangahub.
