### ISSUE TITLE
[Bug] NoxSubs - Changed site theme

### ISSUE THREAD

**Issue by Agayev033** [tachiyomiorg/tachiyomi-extensions#5966]
## Device information
- Tachiyomi version: Up-to-date
- Android version: 9

## Source information
- Name: NoxSubs - MyMangaReaderCMS
- Extension version: 1.2.54

## Steps to reproduce
They are using new theme. So this extension is not working anymore.

**Comment by happywillow0** [comment]
I think I moved the site correctly to the new code. 

@Agayev033 
You will have to install the new NoxSubs extension and you may have to migrate your saved mangas over to the new extension. If you don't have any other MyMangaReaderCMS sites, you can remove that one. 

This issue can be closed.
