### ISSUE TITLE
[Bug] mangadex - download error

### ISSUE THREAD

**Issue by vongdong** [tachiyomiorg/tachiyomi-extensions#5970]
Over these last 2 days, a couple of chapters got a download error. Message is 'Not a JSON object: null'

Can read in app and webview though. 

Using TachiyomiSY preview 339

**Comment by scb261** [comment]
Is it the same in main Tachiyomi? What manga and chapter?

**Comment by vongdong** [comment]
I don't know, I only us sy preview.

Latest was Yuugai Shitei Doukyuusei chapter 36

**Comment by scb261** [comment]
Works fine for me in both apps. Try disabling data saver (Browse > Extensions > MangaDex > gear icon > Data Saver). Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).

**Comment by vongdong** [comment]
Yeah, works fine now. I'll screenshot it if it happens again.

**Comment by vongdong** [comment]
> Works fine for me in both apps. Try disabling data saver (Browse > Extensions > MangaDex > gear icon > Data Saver). Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).

Data saver is disabled in the extension

The story of an otaku and gyaru falling in love.
![Screenshot_20210225-040104_TachiyomiSY](https://user-images.githubusercontent.com/60080780/109037021-598bf200-771e-11eb-959f-c2bdb7da1948.jpg)

**Comment by scb261** [comment]
From md announcements
> api.mangadex.org is kind of failing 50% of requests right now :meguuu2: good luck to anyone using it, will fix eventually hopefully maybe

Works fine for me though, try troubleshoot guide I linked above
