### ISSUE TITLE
[Bug] Hiperdex: Cloudflare Error Despite No Captcha.

### ISSUE THREAD

**Issue by Fmoment1** [tachiyomiorg/tachiyomi-extensions#5971]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Hiperdex.
- Extension version: 1.2.1

## Steps to reproduce
1. Access Hiperdex from the app.

### Expected behavior
The contents appear and are readable.

### Actual behavior
Keep getting `java.lang.Exception: Failed to bypass Cloudflare` error.

## Other details
Opening in webview offers no captcha, and everything is functioning from the web.

Android System Webview is up-to-date as well.

**Comment by scb261** [comment]
Works fine for me. Where exactly are you getting the error? Try to do the same thing in WebView (e.g. if you're getting it when opening a chapter in the app, then open a chapter in WebView). Also try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).

**Comment by MercerBoi** [comment]
I'm getting this error anytime I try to access the site in any way, whether it's just reading a chapter or simply tapping on the source from the list. I made this issue after going through troubleshooting, (hence why I mentioned there being no captcha).

**Comment by kikuKeii** [comment]
I have the same problem. Even though I had done the troubleshooting, it still failed to bypass Cloudflare. So the solution is I use an extension whose content is similar to an inaccessible extension.

**Comment by DanAl27** [comment]
Same problem too, no captcha there.
