### ISSUE TITLE
[Bug] <ComicKiba>: <no pages found>

### ISSUE THREAD

**Issue by tyme2tb** [tachiyomiorg/tachiyomi-extensions#5973]
## Device information
- Tachiyomi version: 0.10.9-3128
- Android version: 9

## Source information
- Name: ComicKiba
- Extension version: 1.2.1

## Steps to reproduce
1. Try to view chapter of manga (I tried "Cultivator Against Hero Society") 
2. Get the no pages found message

### Expected behavior
Should be able to read chapter 

### Actual behavior
No pages found

**Comment by scb261** [comment]
Works fine for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). What chapter?

**Comment by Riztard** [comment]
> Works fine for me

same

**Comment by tyme2tb** [comment]
I just tried a few and apparently it is not all Mangas on the site. I had issues with the 2 below, but I and I did follow all troubleshooting. 
King of Spirit Beast
Cultivator Against Hero Society

**Comment by scb261** [comment]
First and latest chapters for both examples work fine for me. Can you also tell what chapter has this problem?

**Comment by tyme2tb** [comment]
I have tried the most recent and a handful of the ones in the middle for both and get the no pages message. Webview works fine for both.

**Comment by scb261** [comment]
Get logcat and send it here, maybe there will be something about your issue https://play.google.com/store/apps/details?id=com.dp.logcatapp

**Comment by tyme2tb** [comment]
I will just say screw it and hope someday it works. Since I am not installing some random app to try and figure it out. Hasn't worked since at least 2/21 so I won't hold out hope.

**Comment by scb261** [comment]
Works for others and the author doesn't want to send logs, closing. If anyone else actually has the same problem, please open new issue with attached logcat, so devs could look into it
