### ISSUE TITLE
[Source Request] <Leercomicsonline>

### ISSUE THREAD

**Issue by lolomimi21** [tachiyomiorg/tachiyomi-extensions#5976]
## Source website
- Name: Leercomicsonline
- Link: https://leercomicsonline.com/
- Language(s): spanish

## Other details

We need more extensions for read comics in Spanish, there is only manga! Please, you do a great job

**Comment by happywillow0** [comment]
The Comics are hosted and embeded onto the site via a different service called Issuu.com.
The site as I can see is incompatible with Tachiyomi.
