### ISSUE TITLE
Can't read isekai.scans

### ISSUE THREAD

**Issue by Shana198** [tachiyomiorg/tachiyomi-extensions#5980]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 11
* Device: realme 3 pro

## Source information
* Source name: isekaiscans
* Source extension version: 1.2.2

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
All comic can't read it's said

## Other details
Additional details and attachments. Java.lang failed to bypass

**Comment by scb261** [comment]
Follow this to solve Cloudflare https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-the-cloudflare-issue

But IsekaiScan is under maintenance right now, so any issues with it is on their side right now.

**Comment by TanielianVB** [comment]
I'm afraid. It's been 2 days already...
I Found https://isekaiscanmanga.com/ Is it a copy site?
