### ISSUE TITLE
[Bug] <Mangá Host>: <http error 403  >

### ISSUE THREAD

**Issue by desenvolvedor2021** [tachiyomiorg/tachiyomi-extensions#5984]
---

## Device information
- Tachiyomi version: v0.10.9
- Android version: 8.1.0 (SDK 27)
Device model: Moto G (5S)

## Source information
- Name: Mangá Host 
- Extension version: 1.2.17

## Steps to reproduce
1. http error 403.
2. The manga doesn't load or update when you go to read the chapters.

### Expected behavior
Describe what should have happened

The Host manga extension should work normally due to a network failure that displays a warning about [http error 403] even though the source of the Host manga identifies that it is without internet I do not know if it is another problem that is preventing the source of the manga Host. 

### Actual behavior
describes what happened

What is happening is that the network is not working normally even with internet and most all the manga do not load because of this failure.

## Other details

Failure print.

![Screenshot_20210224-210710.png](https://user-images.githubusercontent.com/79285956/109087853-a2bf5000-76e4-11eb-8b15-8cc457ca38c4.png)

And another detail when I want to read a manga whenever I press a chapter it doesn't load, there is an error warning 403 of http.

**Comment by desenvolvedor2021** [comment]
Acabei de ver também esse problema acho que o link do site do mangá Host interrompeu.

![Screenshot_20210224-212946.png](https://user-images.githubusercontent.com/79285956/109089375-7e18a780-76e7-11eb-9e6a-9b99c8f043c0.png)

**Comment by alessandrojean** [comment]
I will take a look and try to fix it.

**Comment by desenvolvedor2021** [comment]
I don't know it seems that I have been blocked in several fraud processes even.And more I have tried to change the ID of my device, the security of the site is very high, there is no point in changing anything except contacting the site owner.

**Comment by desenvolvedor2021** [comment]
I will send a print of the problem that is occurring in all sites related to the host manga ![Screenshot_20210225-092429.png](https://user-images.githubusercontent.com/79285956/109159904-886c8d00-774b-11eb-9f85-fd0e7c49edb8.png)

**Comment by CarlosEsco** [comment]
@alessandrojean  can you add a harsh rate limiting if you fix it.  So people don't get ip banned

**Comment by alessandrojean** [comment]
@CarlosEsco I already added in the last update I submitted, 3 requests in the interval of 1 second. Should I change it to 1 per second?

**Comment by CarlosEsco** [comment]
@alessandrojean yea make it 1 a second, since they are actively ip banning people.
