### ISSUE TITLE
[Source Request] <Isekaiscan manga>

### ISSUE THREAD

**Issue by Beji-kun** [tachiyomiorg/tachiyomi-extensions#5987]
## Source website
- Name: Isekaiscan manga
- Link: https://isekaiscanmanga.com/
- Language(s): English

**Comment by scb261** [comment]
Looks like a rip-off, it even has template text in `About us` and `Contact us` sections. If someone actually adds it, should add `unoriginal` or something to the source name

**Comment by happywillow0** [comment]
Added via #5998. 
Can be closed, thank you.
