### ISSUE TITLE
[Meta] <Make a custom titles order>

### ISSUE THREAD

**Issue by lolomimi21** [tachiyomiorg/tachiyomi-extensions#5990]
---

##  Why/Project's Benefit/Existing Problem
Explain why this should be added

The app's library allows us to organize the titles alphabetically and in order of publication. It would be great if it also allows us to change the order of the titles according to our preference.  This can be used (for example) to create reading orders with Marvel and DC comics

## Other Details

Please!! :(

**Comment by scb261** [comment]
This should be requested in the app repo https://github.com/tachiyomiorg/tachiyomi/issues
