### ISSUE TITLE
[Bug] Hentai2Read: Getting Timeouts Despite Website Working Properly.

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi-extensions#6002]
## Device information
- Tachiyomi version: 0.10.9.
- Android version: 10.

## Source information
- Name: Hentai2Read.
- Extension version: 1.2.11.

## Steps to reproduce
1. Browse the source.
2. Get the error.

### Expected behavior
The app should show website contents, and allow browsing and reading as usual.

### Actual behavior
Loads for about half a minute and then gives a timeout. This happens twice and **then** it works.

## Other details
Webview works properly. Website works properly. No issues there. My network connection is also stable.

**Comment by scb261** [comment]
Loaded fast for me. Did it happen once or happens regularly? Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis).

**Comment by MercerBoi** [comment]
I wouldn't say it's regular, but rather quite frequent. It's not happening now though. I'll follow troubleshoot the next time it happens, but the thing is, it shouldn't happen at all, right? Considering the website working properly and all.
