### ISSUE TITLE
[Bug] mangadex : chapter donot open in contrast open on official website

### ISSUE THREAD

**Issue by ben1000000000** [tachiyomiorg/tachiyomi-extensions#6012]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10  lineage_tissot-userdebug 10 QQ3A.200805.001

## Source information[Maiden in-law on Mangadex](https://mangadex.org/chapter/1224704/1) 
- Name: Mangadex
- Extension version: Version 1.2.103

## Steps to reproduce
1. Search id:50533 (maiden in-law)
2. Try opening any chapters
3. Now open https://mangadex.org/chapter/1224704/1 (se manga on official Mangadex website, opens every chapter fine)

### Expected behavior
Chapter of this particular manga do not open now, but i have read this on same Mangadex extension on tachiyomi

### Actual behavior
Chapter opens and are downloadables

## Other details
#

**Comment by OncePunchedMan** [comment]
they are being ddos'd and api still has issues

**Comment by scb261** [comment]
I'll leave one issue opened until they fix it

**Comment by conztanz045** [comment]
now any manga are not showing the latest chapter 

![Screenshot_2021-03-01-19-52-05](https://user-images.githubusercontent.com/79831076/109493716-ce478f00-7a84-11eb-92e8-7cd0060cf601.png)

![Uploading Screenshot_2021-03-01-19-52-45.png…]()

**Comment by Ponso07** [comment]
Not showing or download any manga in mangadex

**Comment by RusticKey** [comment]
We can only wait until the DDoS stops or that they have mitigated the attacks.

**Comment by scb261** [comment]
Closing in favor of #5780
