### ISSUE TITLE
[Bug] Mangadex sometimes stop working: When reading from the Mangadex extension it would stop working telling me to retry but it would not actually load and instantly go back to retry even though the webreader is working fine.

### ISSUE THREAD

**Issue by TainiuKu** [tachiyomiorg/tachiyomi-extensions#6021]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 9

## Source information
- Name: Mangdex
- Extension version: 1.2.103

## Steps to reproduce
1. Read through any random Mangadex series 
2. Continue reading until the pages stop loading
3. Try to reload 

### Expected behavior
It should slowly load the current and subsequent pages

### Actual behavior
It would instantly stop loading and would bring back the retry button

## Other details
-The only way to fix this (sometimes) is to clear chapter cache and cookies but it is not consistent
- Randomly it would be able to load again and work normally (sometimes after 30 min, sometimes after an entire day)
- I thought it might have something to do with the Mangadex website itself but that is not the case as the manga itself is still accessible in webview.
- Happens in the previous versions as well but more frequently recently

**Comment by JPetsis** [comment]
The same is happening to me! Also yesterday for some time I would receive error 502 all the time. I wonder if all this has to do with the new mangadex api..

**Comment by CarlosEsco** [comment]
In the future you should check their subreddit, or discord channel.

https://www.reddit.com/r/mangadex/comments/lv9d4c/psa_were_still_being_ddosed/
