### ISSUE TITLE
[Source Request] - French - Mangas-Origines

### ISSUE THREAD

**Issue by pixelroll** [tachiyomiorg/tachiyomi-extensions#6027]
Source Website

    Name: Mangas-Origines

    Link: https://mangas-origines.fr/

    Language(s): French

Other Details :

    This is the website of a small French team, which translates the least advanced webtoons in France.
    For example  The Beginning After The End 
    In short, all webtoons available on this site get a very fast and high quality translation.
    Thanks

**Comment by Mitia99** [comment]
@as280093 An icon please ^^.Thanks
