### ISSUE TITLE
[Bug] <manhuadui>: <chain validation failed>

### ISSUE THREAD

**Issue by smarttommyau** [tachiyomiorg/tachiyomi-extensions#6029]
Whenever I want to read or refresh chapter in manhuadui, it will pop up a toast says chain validation failed.I have checked the website and it still work normal.

**Comment by scb261** [comment]
Their certificate is expired and your browser should at least notify you about invalid certificate. Wait until they renew it

**Comment by scb261** [comment]
They fixed their certificate and the extension works fine now
