### ISSUE TITLE
KomikIndo

### ISSUE THREAD

**Issue by farhanpurdi** [tachiyomiorg/tachiyomi-extensions#6031]
## Source website
- Name: KomikIndo
- Link: https://komikindo.id/
- Language(s): ID

**Comment by HaruSasaki** [comment]
That's different website…? A website that is down is komikindo.web.id not komikindo.id

**Comment by Riztard** [comment]
> That's different website…? A website that is down is komikindo.web.id not komikindo.id

he just replying to someone

**Comment by HaruSasaki** [comment]
> > That's different website…? A website that is down is komikindo.web.id not komikindo.id
> 
> he just replying to someone

Oh sorry my bad, i did'nt notice (TT)
