### ISSUE TITLE
[Bug] <Manhua ES>: <don't work>

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#6037]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 5.1.1

## Source information
- Name: manhua ES
- Extension version: 1.2.1

## Steps to reproduce
1. First Step -Open extension Manhua ES
2. Second Step

### Expected behavior
Extension show manhuas normally

### Actual behavior
I see inscription "No results found ".

## Other details
I see this on my nox emulator and on my phone. Browser open this website normally.

**Comment by Riztard** [comment]
seems like now they use madara
