### ISSUE TITLE
[Source Request] <ReadComicsOnline>

### ISSUE THREAD

**Issue by lolomimi21** [tachiyomiorg/tachiyomi-extensions#6045]
## Source website
- Name: Readcomicsonline
- Link: Readcomicsonline.ru
- Language(s): English

## Other details

It would be great to have more extensions for comics, since compared to manga, there are too few.  Don't confuse this source with ReadComicOnline, which is already on Tachiyomi.  Readcomicsonline.ru is different.

Please! •^•

**Comment by scb261** [comment]
It's in `My Manga Reader CMS` extension
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/9014f85f7736b4d2be159b77a98122016c499030/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L238
