### ISSUE TITLE
[Bug] <Mangakawaii>: <HTTP Error 403>

### ISSUE THREAD

**Issue by meliodasd** [tachiyomiorg/tachiyomi-extensions#6046]
## Device information
- Tachiyomi version: latest 
- Android version: latest 

## Source information
- Name: Mangakawaii 
- Extension version: latest 

## Steps to reproduce
1. Click on manga 
2. Click on chapter 

Can't read or download any chapters.

**Comment by Riztard** [comment]
work for me after use VPN
