### ISSUE TITLE
[Bug] <Komga>: Libraries not available in Filter

### ISSUE THREAD

**Issue by valdearg** [tachiyomiorg/tachiyomi-extensions#6047]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 11

## Source information
- Name: Komga
- Extension version: 1.2.21

## Steps to reproduce
In Sources > Komga > Filter, the Libraries option does not expand to list Komga libraries. Other filter options such as Status. Genres, Publishers do show.

### Expected behaviour
Should show a list of available Komga libraries. 

View within Komga:
![image](https://user-images.githubusercontent.com/2789033/108628434-dd11be80-7452-11eb-9829-e255f7972527.png)

In Tachiyomi, the Libraries doesn't load anything.
![Screenshot_20210221-144145_Tachiyomi](https://user-images.githubusercontent.com/2789033/108628454-016d9b00-7453-11eb-9abe-5dbdcf4fc7cb.jpg)

Tagging @gotson

**Comment by gotson** [comment]
When you click `Reset` at the top of the filter panel, does it fixes the problem?

**Comment by gotson** [comment]
What's your Komga server version?

**Comment by valdearg** [comment]
Tried the Reset button, no change there. 

I'm running the latest Komga version as of last night, v0.77.1-master

**Comment by gotson** [comment]
@valdearg can you try extension version `1.2.22` and report if that works ? If not, can you dump crash logs (from advanced settings) and post here?

**Comment by valdearg** [comment]
Just tried by unfortunately no change. I've dumped the logs, looks like there are a few errors on:

```
03-08 09:24:23.864 19744 19744 E extension.all.komga: error while loading genres for filters
03-08 09:24:23.864 19744 19744 E extension.all.komga: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
```

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6100286/tachiyomi_crash_logs.txt)

**Comment by gotson** [comment]
Can you share what's the url configured for the extension (masking domain name if needed)?

**Comment by valdearg** [comment]
Yeah, the URL I'm using is: https://komga.neko.network

**Comment by valdearg** [comment]
Don't suppose you got anywhere with this?

**Comment by gotson** [comment]
Could you check the http traces on server side when doing that request?

It's accessible with an admin account at `/actuator/httptrace`.

**Comment by valdearg** [comment]
Nothing absolutely obvious, it does a request for the https://komga.neko.network/api/v1/series?page=0

But nothing much happens.

**Comment by gotson** [comment]
You should see a trace to /api/v1/libraries when the filter loads when you start tachiyomi.

**Comment by valdearg** [comment]
Ah OK so I've completely closed tachiyomi and re-opened it and I can see the requests you mentioned:

https://komga.neko.network/api/v1/publishers
https://komga.neko.network/api/v1/genres
https://komga.neko.network/api/v1/authors
https://komga.neko.network/api/v1/libraries
https://komga.neko.network/api/v1/tags
https://komga.neko.network/api/v1/collections?unpaged=true

```
[
  {
    id: "61933",
    name: "DC Comics",
    root: "/home/valdearg/nextcloud_data/valdearg/files/Comics/DC Comics",
    importComicInfoBook: true,
    importComicInfoSeries: true,
    importComicInfoCollection: true,
    importComicInfoReadList: true,
    importEpubBook: true,
    importEpubSeries: true,
    importLocalArtwork: true,
    importBarcodeIsbn: true,
    scanForceModifiedTime: false,
    scanDeep: false
  },
  {
    id: "0270Z54P9MC42",
    name: "Independents & Misc",
    root: "/home/valdearg/nextcloud_data/valdearg/files/Comics/Independents & Misc",
    importComicInfoBook: true,
    importComicInfoSeries: true,
    importComicInfoCollection: true,
    importComicInfoReadList: true,
    importEpubBook: true,
    importEpubSeries: true,
    importLocalArtwork: true,
    importBarcodeIsbn: true,
    scanForceModifiedTime: false,
    scanDeep: false
  },
  {
    id: "124367",
    name: "Manga",
    root: "/home/valdearg/nextcloud_data/valdearg/files/Manga",
    importComicInfoBook: true,
    importComicInfoSeries: true,
    importComicInfoCollection: true,
    importComicInfoReadList: true,
    importEpubBook: true,
    importEpubSeries: true,
    importLocalArtwork: true,
    importBarcodeIsbn: true,
    scanForceModifiedTime: false,
    scanDeep: false
  },
  {
    id: "89877",
    name: "Marvel",
    root: "/home/valdearg/nextcloud_data/valdearg/files/Comics/Marvel",
    importComicInfoBook: true,
    importComicInfoSeries: true,
    importComicInfoCollection: true,
    importComicInfoReadList: true,
    importEpubBook: true,
    importEpubSeries: true,
    importLocalArtwork: true,
    importBarcodeIsbn: true,
    scanForceModifiedTime: false,
    scanDeep: false
  }
]
```

**Comment by gotson** [comment]
Could you post the full httptrace for the libraries request?

**Comment by valdearg** [comment]
```
{
  timestamp: "2021-03-30T11:43:39.665912Z",
  principal: null,
  session: null,
  request: {
  method: "GET",
  uri: "https://komga.neko.network/api/v1/libraries",
  headers: {
  sec-fetch-mode: [
  "navigate"
  ],
  referer: [
  "https://komga.neko.network//actuator/httptrace"
  ],
  if-none-match: [
  ""0552151b4f233f28c45935f74d2bd7ebe""
  ],
  sec-fetch-site: [
  "same-origin"
  ],
  accept-language: [
  "en-GB,en;q=0.9,en-US;q=0.8,es;q=0.7"
  ],
  sec-fetch-user: [
  "?1"
  ],
  accept: [
  "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
  ],
  sec-ch-ua: [
  ""Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99""
  ],
  sec-ch-ua-mobile: [
  "?0"
  ],
  x-forwarded-server: [
  "komga.neko.network"
  ],
  host: [
  "komga.neko.network"
  ],
  upgrade-insecure-requests: [
  "1"
  ],
  connection: [
  "Keep-Alive"
  ],
  accept-encoding: [
  "gzip, deflate, br"
  ],
  user-agent: [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
  ],
  sec-fetch-dest: [
  "document"
  ]
  },
  remoteAddress: null
  },
  response: {
  status: 304,
  headers: {
  Cache-Control: [
  "max-age=0, must-revalidate, no-transform, private"
  ],
  ETag: [
  ""0552151b4f233f28c45935f74d2bd7ebe""
  ],
  Vary: [
  "Origin",
  "Access-Control-Request-Method",
  "Access-Control-Request-Headers"
  ]
  }
  },
  timeTaken: 66
},
```

**Comment by gotson** [comment]
The server is fine and replies with a `200`. Do you have recent exported crash logs from Tachiyomi ? I changed the way it logs in the last version to remove some noise.

**Comment by valdearg** [comment]
I've closed and re-opened the app, went to Browse > Komga > Filter, then tried to expand Libraries, nothing showed up. Tried hitting the reset button, no change.

I've dumped the crash logs but not getting anything there.

[tachiyomi_crash_logs (1).txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6235637/tachiyomi_crash_logs.1.txt)

**Comment by plumber-craic** [comment]
+1 getting this issue with komga 1.2.31. With a single library it worked (I could see my library and a checkbox), but once I had more than one I was unable to filter by library (tapping arrow does nothing).

**Comment by gotson** [comment]
> +1 getting this issue with komga 1.2.31. With a single library it worked (I could see my library and a checkbox), but once I had more than one I was unable to filter by library (tapping arrow does nothing).

Can you go through the same steps as suggested above, ie checking the httptrace endpoint to make sure the server answers with a 200, then provide crash logs?

**Comment by plumber-craic** [comment]
I'm not seeing any calls to v1/libraries in the trace. It looks like the client isn't doing anything when the filter button is being pressed. I'm opening Tachiyomi, clicking Browse, Komga, Filter then Libraries. I try both the arrow and the text label; the button doesn't respond in any way. 

There are two calls to that endpoint when tachiyomi starts, a 200:
`		{
			"timestamp": "2021-10-03T08:41:14.303747Z",
			"principal": null,
			"session": null,
			"request": {
				"method": "GET",
				"uri": "http://192.168.1.250:8089/api/v1/libraries",
				"headers": {
					"host": [
						"192.168.1.250:8089"
					],
					"connection": [
						"Keep-Alive"
					],
					"cache-control": [
						"max-age=600"
					],
					"accept-encoding": [
						"gzip"
					],
					"user-agent": [
						"TachiyomiKomga/1.2.31"
					]
				},
				"remoteAddress": null
			},
			"response": {
				"status": 200,
				"headers": {
					"X-Frame-Options": [
						"DENY"
					],
					"Keep-Alive": [
						"timeout=60"
					],
					"Cache-Control": [
						"max-age=0, must-revalidate, no-transform, private"
					],
					"ETag": [
						"\"0b87bdb71eec0a8a94d70dd47c8756fcc\""
					],
					"X-Content-Type-Options": [
						"nosniff"
					],
					"Connection": [
						"keep-alive"
					],
					"Vary": [
						"Origin",
						"Access-Control-Request-Method",
						"Access-Control-Request-Headers"
					],
					"X-XSS-Protection": [
						"1; mode=block"
					],
					"Content-Length": [
						"1403"
					],
					"Date": [
						"Sun, 03 Oct 2021 08:41:14 GMT"
					],
					"Content-Type": [
						"application/json"
					]
				}
			},
			"timeTaken": 197
		}`

and a 304

`				{
			"timestamp": "2021-10-03T08:39:29.624961Z",
			"principal": null,
			"session": null,
			"request": {
				"method": "GET",
				"uri": "http://192.168.1.250:8089/api/v1/libraries",
				"headers": {
					"referer": [
						"http://192.168.1.250:8089/startup?redirect=%2Fdashboard"
					],
					"if-none-match": [
						"\"0b87bdb71eec0a8a94d70dd47c8756fcc\""
					],
					"accept-language": [
						"en-GB,en;q=0.5"
					],
					"host": [
						"192.168.1.250:8089"
					],
					"x-requested-with": [
						"XMLHttpRequest"
					],
					"connection": [
						"keep-alive"
					],
					"accept-encoding": [
						"gzip, deflate"
					],
					"user-agent": [
						"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"
					],
					"accept": [
						"application/json, text/plain, */*"
					]
				},
				"remoteAddress": null
			},
			"response": {
				"status": 304,
				"headers": {
					"Cache-Control": [
						"max-age=0, must-revalidate, no-transform, private"
					],
					"ETag": [
						"\"0b87bdb71eec0a8a94d70dd47c8756fcc\""
					],
					"Vary": [
						"Origin",
						"Access-Control-Request-Method",
						"Access-Control-Request-Headers"
					]
				}
			},
			"timeTaken": 0
		}`

Similarly, when pushing the Collections (#9330) button I don't think the client is sending anything when I'm at the filter screen. During load I can see a single request to collections that looks ok, but nothing shows up in trace when i hit the button:
`		{
			"timestamp": "2021-10-03T08:41:14.305137Z",
			"principal": null,
			"session": null,
			"request": {
				"method": "GET",
				"uri": "http://192.168.1.250:8089/api/v1/collections?unpaged=true",
				"headers": {
					"host": [
						"192.168.1.250:8089"
					],
					"connection": [
						"Keep-Alive"
					],
					"cache-control": [
						"max-age=600"
					],
					"accept-encoding": [
						"gzip"
					],
					"user-agent": [
						"TachiyomiKomga/1.2.31"
					]
				},
				"remoteAddress": null
			},
			"response": {
				"status": 200,
				"headers": {
					"X-Frame-Options": [
						"DENY"
					],
					"Keep-Alive": [
						"timeout=60"
					],
					"Cache-Control": [
						"max-age=0, must-revalidate, no-transform, private"
					],
					"ETag": [
						"\"03226cbca7ef47d60e90ac44a502bcc87\""
					],
					"X-Content-Type-Options": [
						"nosniff"
					],
					"Connection": [
						"keep-alive"
					],
					"Vary": [
						"Origin",
						"Access-Control-Request-Method",
						"Access-Control-Request-Headers"
					],
					"X-XSS-Protection": [
						"1; mode=block"
					],
					"Content-Length": [
						"4897"
					],
					"Date": [
						"Sun, 03 Oct 2021 08:41:14 GMT"
					],
					"Content-Type": [
						"application/json"
					]
				}
			},
			"timeTaken": 204
		}
		`

**Comment by gotson** [comment]
The calls to get the filters value are only done on application startup. You would need to force kill tachiyomi and start it again to see it.

**Comment by gotson** [comment]
Could you check the crash logs of tachiyomi and post it here?

**Comment by gotson** [comment]
> I'm not seeing any calls to v1/libraries in the trace. It looks like the client isn't doing anything when the filter button is being pressed. I'm opening Tachiyomi, clicking Browse, Komga, Filter then Libraries. I try both the arrow and the text label; the button doesn't respond in any way.
> 
> There are two calls to that endpoint when tachiyomi starts, a 200: ` { "timestamp": "2021-10-03T08:41:14.303747Z", "principal": null, "session": null, "request": { "method": "GET", "uri": "http://192.168.1.250:8089/api/v1/libraries", "headers": { "host": [ "192.168.1.250:8089" ], "connection": [ "Keep-Alive" ], "cache-control": [ "max-age=600" ], "accept-encoding": [ "gzip" ], "user-agent": [ "TachiyomiKomga/1.2.31" ] }, "remoteAddress": null }, "response": { "status": 200, "headers": { "X-Frame-Options": [ "DENY" ], "Keep-Alive": [ "timeout=60" ], "Cache-Control": [ "max-age=0, must-revalidate, no-transform, private" ], "ETag": [ "\"0b87bdb71eec0a8a94d70dd47c8756fcc\"" ], "X-Content-Type-Options": [ "nosniff" ], "Connection": [ "keep-alive" ], "Vary": [ "Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers" ], "X-XSS-Protection": [ "1; mode=block" ], "Content-Length": [ "1403" ], "Date": [ "Sun, 03 Oct 2021 08:41:14 GMT" ], "Content-Type": [ "application/json" ] } }, "timeTaken": 197 }`
> 
> and a 304
> 
> ` { "timestamp": "2021-10-03T08:39:29.624961Z", "principal": null, "session": null, "request": { "method": "GET", "uri": "http://192.168.1.250:8089/api/v1/libraries", "headers": { "referer": [ "http://192.168.1.250:8089/startup?redirect=%2Fdashboard" ], "if-none-match": [ "\"0b87bdb71eec0a8a94d70dd47c8756fcc\"" ], "accept-language": [ "en-GB,en;q=0.5" ], "host": [ "192.168.1.250:8089" ], "x-requested-with": [ "XMLHttpRequest" ], "connection": [ "keep-alive" ], "accept-encoding": [ "gzip, deflate" ], "user-agent": [ "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0" ], "accept": [ "application/json, text/plain, */*" ] }, "remoteAddress": null }, "response": { "status": 304, "headers": { "Cache-Control": [ "max-age=0, must-revalidate, no-transform, private" ], "ETag": [ "\"0b87bdb71eec0a8a94d70dd47c8756fcc\"" ], "Vary": [ "Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers" ] } }, "timeTaken": 0 }`

The first call (200) is from tachiyomi, thus looks fine. The second one if not, see the user agent. 304 is also fine, the cache kicks in and returns a not changed.

The Tachiyomi logs could help us, nothing wrong on server side.

**Comment by plumber-craic** [comment]
Where is the log file saved? I can open it on the device but can't see it when I browse to the eu.kanade.tachiyomi folder

**Comment by gotson** [comment]
I might need to add some logs here : https://github.com/tachiyomiorg/tachiyomi-extensions/blob/78f627dfa0ab7acf1d1430f4be43a755e282002e/src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt#L433

**Comment by gotson** [comment]
Looks like this is fixed, we can probably close this one.
