### ISSUE TITLE
[Bug] <Webnovel.com>: <Https error 404>

### ISSUE THREAD

**Issue by LazyAndBeyond** [tachiyomiorg/tachiyomi-extensions#6056]
---

## Device information
- Tachiyomi version: 1.0.10
- Android version: 10

## Source information
- Name: Webnovel.com
- Extension version: 1.2.2

## Steps to reproduce
1. First Step check any webnovel
2. Second Step you get the error

### Expected behavior
Describe what should have happened 
You get the chapters

### Actual behavior
Describe what happens instead
It doesn't show any chapters instead shows https error 404
## Other details
Already singed in in webveiw and tried the chapter there and they all worked fine

**Comment by hyoretsu** [comment]
Also happens with So Pure, So Flirtatious

**Comment by Riztard** [comment]
seems like they change something back, so it works now, but now there is a pages issue
