### ISSUE TITLE
[Meta] Language dialects improvement

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#6063]
##  Why/Project's Benefit/Existing Problem
Currently there are 2 different ways that extensions are adding dialects:
1. using language codes with sub values like `pt-BR`, used by sites like MangaDex
2. using language codes with out subs like `pt` and just adding the sub values to the title, used by sites like Webtoons

**Comment by arkon** [comment]
What's the proposal?

**Comment by jopejoe1** [comment]
Changing from having 2 different ways to only having one.

**Comment by CarlosEsco** [comment]
one way makes it less accurate..
