### ISSUE TITLE
[Source Request] <JuinJutsuTeam>

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi-extensions#6064]
# Forum: juinjutsuteam.forumcommunity.net
# Reader: juinjutsureader.ovh
- Name: JuinJutsuTeam
- Link: juinjutsureader.ovh
- Language(s): Italian

**Comment by scb261** [comment]
They previously requested removal of their source #2958 and it looks like it's a scanlator site.
