### ISSUE TITLE
[Feature Request] ManhwaManga: Use current date instead of '0' for new chapters

### ISSUE THREAD

**Issue by RickSaysMeh** [tachiyomiorg/tachiyomi-extensions#6067]
## What feature should be added to this source?
Currently, this source sets the date of all new chapters to '0'. I presume this is due to the site itself not providing upload dates. Not having a date associated with new chapters causes the title to remain in its current position in the library when sorting via Latest chapter and keeps the title from appearing on the Updates screen.

If possible, it would be beneficial to provide some sort of date so that the titles actually appear. Using the current date at the time of the update scan instead of '0' should resolve this.

**Comment by scb261** [comment]
Extensions just fetch chapter list, storing and comparing with the old list is done on the app side, so extension can't detect new chapters. As the author of #6327 said, they will open an issue about sorting based on fetch date in the correct repository.
