### ISSUE TITLE
[Bug] ComicKiba: No Pages Found

### ISSUE THREAD

**Issue by askolds11** [tachiyomiorg/tachiyomi-extensions#6068]
## Device information
- Tachiyomi version: 0.10.9
- Android version: Android 11 (MIUI 12)

## Source information
- Name: ComicKiba
- Extension version: 1.2.1

## Steps to reproduce
1. Open a manga chapter (In my case List of Villains, happens on some other manga too)
2. Get the error "No Pages Found"

### Expected behavior
Opened the chapter

### Actual behavior
I get the error "No Pages Found"

## Other details
It works in WebView.
Probably the same issue as #5973

Hope I made the log correctly, I used the adb logcat.
[tachi.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6086065/tachi.txt)

**Comment by scb261** [comment]
Maybe I missed something but here are two logs that caught my attention:
- I'm not sure what this one means and it happens to many extensions, so probably not the issue, mentioned it just in case.
```
03-04 21:10:49.477  2018  3783 D DexManager: Oops, can't get pkgUseInfo with /data/app/~~WfgN4ZhUGx_DKrA-VCDftw==/eu.kanade.tachiyomi.extension.all.mangadex-fVBkUFG4w7Hp_CPpRE_-7w==/base.apk, skip dexopt on it.
03-04 21:10:49.756  2018  3783 D DexManager: Oops, can't get pkgUseInfo with /data/app/~~b1cZ0gHUZTshl5516P-VEw==/eu.kanade.tachiyomi.extension.en.comickiba-UZWR4qXI2xZl8RgV9dnA6Q==/base.apk, skip dexopt on it.
03-04 21:10:50.009  2018  3783 D DexManager: Oops, can't get pkgUseInfo with /data/app/~~LV0KLAehWVwsp6acjpJJBg==/eu.kanade.tachiyomi.extension.en.edelgardescans-vDNr3vdM4wyjF8T6oekb9Q==/base.apk, skip dexopt on it.
```
- Looks like the second one is the issue. I would suggest checking the chapter in Webview, but you already did it, so I don't know why it happens. Maybe someone else could look at it.
```
03-04 21:11:16.253 22529 22889 W anade.tachiyom: Long monitor contention with owner OkHttp https://comickiba.com/... (22700) at okhttp3.Response eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(okhttp3.Interceptor$Chain)(CloudflareInterceptor.kt:61) waiters=0 in okhttp3.Response eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(okhttp3.Interceptor$Chain) for 674ms
```

To get more details: what chapter exactly doesn't work? Do examples from #5973 (`King of Spirit Beast` and `Cultivator Against Hero Society`) work for you?

I also suggest trying [troubleshoot guide](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). Especially updating WebView and clearing cache/cookies, but you still should try everything in the guide.

**Comment by askolds11** [comment]
None of the chapters work for all 3 manga: `List of Villains`, `King of Spirit Beast` and `Cultivator Against Hero Society`.
WebView is the latest version (88.0.4324.181)
Clearing cache, cookies, database and DNS over HTTPS didn't fix it either (Probably should've mentioned I did these before, but just in case, did it again and didn't work)

Trying other manga from ComicKiba, `Super School Doctor`, `Campus master` don't work either (all chapters), the first one I found working was 'Emperor LingTian', and all of the chapters worked.

Also tried on mobile data instead of Wi-Fi, but didn't change anything.

**Comment by Riztard** [comment]
> None of the chapters work for all 3 manga: List of Villains, King of Spirit Beast and Cultivator Against Hero Society.

> Trying other manga from ComicKiba, Super School Doctor, Campus master don't work either (all chapters), the first one I found working was Emperor LingTian, and all of the chapters worked.

hmm all of this work for me

**Comment by askolds11** [comment]
Everything works as of version 1.2.2.
Do I close the issue?

**Comment by Arraiment** [comment]
This issue can be closed.
