### ISSUE TITLE
[Bug] <Mangadex>: <no new chapters>

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#6071]
---

## Device information
- Tachiyomi version: r3130
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.104

## Steps to reproduce
1. Update manga

### Expected behavior
New chapters in app

### Actual behavior
No new chapters in app

## Other details
After update extension 1.2.103->1.2.104, i don't have 502 error on updating manga, but new chaters still don't show in app.![Screenshot_2021-03-05-09-40-58-226_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/110077323-f5f56a80-7d96-11eb-8e68-d1ba931b3a17.jpg)![Screenshot_2021-03-05-09-41-07-888_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/110077326-f68e0100-7d96-11eb-9490-9b927de0125f.jpg)

**Comment by Riztard** [comment]
refer to #5780
