### ISSUE TITLE
[Feature Request] Can bookmark for specific a page

### ISSUE THREAD

**Issue by fedder404** [tachiyomiorg/tachiyomi-extensions#6072]
Everytime I read, there is sometimes that i want to bookmark a page because it's either i like the phrase in it or I'm confused on it.When i'm confused with it i will read it again after finding some clues on the proceeding chapters but when only the chapter was bookmarked, i sometimes forgot what page it was. I also think there other several reason for this issue to be implemented but those reasons i mentioned above is what i currently experience that can be use as reason for implementing this issue.

**Comment by CrepeTF** [comment]
Wrong repo,
Pokies already requested here:
https://github.com/tachiyomiorg/tachiyomi/issues/565

**Comment by fedder404** [comment]
Sorry, I'm new to this community and can i ask what is repo? Thank you.

**Comment by Riztard** [comment]
repository
