### ISSUE TITLE
[Bug] Komga: Crash on newly setup tablet & tachiyomi

### ISSUE THREAD

**Issue by Vodes** [tachiyomiorg/tachiyomi-extensions#6074]
## Device information
- Tachiyomi version: 0.10.9 (also happens on latest SY and J2k)
- Android version: 10 (Lenovo Tab p11)

## Source information
- Name: Komga
- Extension version: 1.2.21

## Steps to reproduce
This is just me guessing, but you need a completely new tachiyomi setup, no leftover data or anything.
[Video of whats happening](https://vodes.pw/i/Alex/AaZCurt7tMifjm4.mp4)

## Other details
@gotson knows about this, but cant explain it either.

As you can also see in the video. Other extensions work fine.
Komga with the same server, app version and android version even works on my phone for some reason.
Attached is the crash log
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6092081/tachiyomi_crash_logs.txt)

**Comment by gotson** [comment]
@Vodes can you try extension `1.2.22` and let me know if that works ? If you still have an error, can you report on what error, and also post the dump of the crash logs (from advanced settings) ?

**Comment by Vodes** [comment]
Seems to work fine now and I think I know what the issue was. It seems I had a typo in the login data and after I updated the extension it said 401. Maybe the last version didn't handle that the way it was supposed to?

**Comment by gotson** [comment]
> Seems to work fine now and I think I know what the issue was. It seems I had a typo in the login data and after I updated the extension it said 401. Maybe the last version didn't handle that the way it was supposed to?

nah, the error was some null reference exception, so something not handled. Are all the filters loaded OK ?

**Comment by Vodes** [comment]
As far as I can see they are

**Comment by gotson** [comment]
Good, i think you can close the issue then!
