### ISSUE TITLE
Add information on when a new extension was added

### ISSUE THREAD

**Issue by AzamSaja** [tachiyomiorg/tachiyomi-extensions#6079]
'Date added' or 'new' tag on extension so we know which is 'new' source extension

---

Some developer might working hard to add new source extension, but we don't know which one (I mean there is a lot source extension)

And I, one of people that excited to try and explore new source extension.

Or you can add 'new' tag to new add extension for past 7 days or 3 days.

**Comment by Soitora** [comment]
/edit-title "Add information on when a new extension was added"

**Comment by arkon** [comment]
README/CHANGELOG files can be added now within modules and are linked from the app.
