### ISSUE TITLE
[Source Request] <Flame Scans>

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#6083]
---

## Source website
- Name: Flame Scans
- Link: flamescans.org
- Language(s): English

## Other details
This is the new URL for Flame Scans

**Comment by scb261** [comment]
It's the same URL that is used now and the extension works fine
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/244ea0b9b418fe1baeb759f164885cb510b3b22b/multisrc/overrides/wpmangastream/flamescans/src/FlameScans.kt#L8
