### ISSUE TITLE
[Bug] <IMHentai>: <Expired domain>

### ISSUE THREAD

**Issue by kenokarsi2000** [tachiyomiorg/tachiyomi-extensions#6086]
## Device information
- Tachiyomi version: 10.9
- Android version: 7.1.2

## Source information
- Name: ?
- Extension version: ?

## Steps to reproduce
1. First Step - Install IMHentai extension
2. Second Step - Enter into this extension and choose manga

### Expected behavior
Should see manga lists after entering into this extension

### Actual behavior
Only showing "imhentai.com: NXDOMAIN" without showing manga lists

## Other details
IMHentai website recently changed its domain.So,web address is changed From   "https://imhentai.com"   Into  "https://imhentai.xxx".For these reason,Tachiyomi extension that used previous domain address is no longer working now.

**Comment by arkon** [comment]
#6069
