### ISSUE TITLE
[Source Request] <Anime GDR Club>

### ISSUE THREAD

**Issue by AlexMini2517** [tachiyomiorg/tachiyomi-extensions#6088]
## Source website - agcscanlation.it
- Name: Anime GDR Club
- Link: animegdrclub.forumfree.it - agcscanlation.it
- Language(s): Italian

## Other details
Forum:
![Screenshot_3](https://user-images.githubusercontent.com/76444133/110256529-b34fb000-7f99-11eb-986f-ef15f416ff68.jpg)

Reader:
![Screenshot_4](https://user-images.githubusercontent.com/76444133/110256531-b5b20a00-7f99-11eb-8ad8-798bbf0ddcd2.jpg)

**Comment by AlexMiniReal** [comment]
someone?

**Comment by CrepeTF** [comment]
Someone will make an extension for it when someone wants to

**Comment by AlexMiniReal** [comment]
Please guys MangaDex is down and i really need this extension :(

**Comment by AlexMiniReal** [comment]
Anyone?

**Comment by CrepeTF** [comment]
> Someone will make an extension for it when someone wants to

**Comment by annabenefiel90** [comment]
:insert noeta emoji:
