### ISSUE TITLE
[Feature Request] <Hitomi.la>: <sort by popularity>

### ISSUE THREAD

**Issue by Hybridcre** [tachiyomiorg/tachiyomi-extensions#6095]
## What feature should be added to this source?
Sort by popularity feature should be added.
Explain why this should be added
With the help of this feature we can search popular tags now it's only shows recent.

**Comment by CrepeTF** [comment]
The filters and sorts are a reflection of the filters and sorts on the websites (check through webview)

If a website doesn't a popularity sort it won't be in Tachiyomi

**Comment by Hybridcre** [comment]
> The filters and sorts are a reflection of the filters and sorts on the websites (check through webview)
> 
> If a website doesn't have a popularity sort it won't be in Tachiyomi

In the webview it show through popularity.
After checking on WebView I made this request.

**Comment by scb261** [comment]
`hitomi.la/tag/popular/[tag]-[lang].html` if someone wants to add it. This will search only by this one tag, and the search query will be ignored when this filter is on
