### ISSUE TITLE
[Bug] MangaPark: Image not loaded (retry button showing) 

### ISSUE THREAD

**Issue by arrianda** [tachiyomiorg/tachiyomi-extensions#6098]
### Device information
Tachiyomi version: 0.10.9
Android version: 10

### Source information
Name: MangaPark
Extension version: 1.2.17

### Steps to reproduce
1. Read a chapter from MangaPark
2. Close/Switch app halfway when the page is on loading
3. Back to the chapter whenever the Tachiyomi restarted or not

Expected behavior
The page/image which not loaded will be loading again to full page/image

Actual behavior
I got error with retry button within very short loading delay for entire next page on that chapter. Still normal for next chapter though. Still the same error whether I press retry or check it for another day.

Other details
The download will be stuck if you download the chapter that have the error.

**Comment by scb261** [comment]
MangaPark gives temporary image URLs that work only for 10 minutes. I don't think it can be fixed on extension side. For current chapter - clear chapter cache. For future chapters - download chapters before reading

**Comment by arrianda** [comment]
I see. Thanks for the info. I hope it can be fixed, at least maybe automatic clear chapter cache for mangapark.
