### ISSUE TITLE
[Bug] <Mangasee>: <Sudden timeouts when reading using mangasee>

### ISSUE THREAD

**Issue by LordSquiggles** [tachiyomiorg/tachiyomi-extensions#6107]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Mangasee
- Extension version: 1.2.16

## Steps to reproduce
1. Read a few chapters of un-downloaded manga

### Expected behavior
Pages and the extension should load properly

### Actual behavior
After reading a few chapters of any manga using Mangasee, pages will at random suddenly fail to load and when going to the actual extension to view manga, a loading icon will show followed by a timeout error.

## Other details
The issue only seems to affect the Mangasee extension as other extensions are still viewable when this occurs. The error also seems to be isolated to my phone since when I try viewing the Mangasee extension on another phone it loads properly while my  phone's extension does not. The error takes a few minutes to resolve itself before being able to use the extension again wherein the process repeats itself after reading more chapters.

**Comment by arkon** [comment]
Closing in favour of #6136
