### ISSUE TITLE
[English] Lezhin

### ISSUE THREAD

**Issue by metroid112** [tachiyomiorg/tachiyomi-extensions#611]
(https://www.lezhin.com/en)

Lezhin is a webtoon platform with some dubious monetization system (And no respect for creators) but sadly it holds monopoly of certains webtoons that are not available anywhere on the web except their site.

The big issue with bringing this to Tachiyomi is to make sure that you are only able to see the free chapters in their catalogue (They lock like half of the available chapters to free users, which are usually unlocked)

**Comment by joseph619** [comment]
Lezhin is a licensed site, creating extension might risk copyrights. Lezhin is extremely aggressive in this regard.

**Comment by as280093** [comment]
here the icons
[Lezhin.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614808/Lezhin.zip)
