### ISSUE TITLE
[Bug] Reset Scans : Extension Broken

### ISSUE THREAD

**Issue by Subtilizer28** [tachiyomiorg/tachiyomi-extensions#6110]
## Device information
- Tachiyomi version: 1.0.10 J2K
- Android version: 10

## Source information
- Name: Reset Scans
- Extension version: 1.2.2

## Steps to reproduce
1. OPEN THE EXTENSION IN BROWSE TAB

### Expected behavior
Should have shown all the manga available in that Source

### Actual behavior
Gives the Error HTTP Error 500

**Comment by scb261** [comment]
5xx are server errors and the screenshot above confirms it
