### ISSUE TITLE
[Source Request] <mangaku.pro>

### ISSUE THREAD

**Issue by 1kriver** [tachiyomiorg/tachiyomi-extensions#6117]
[Mangaku](https://mangaku.pro/) 
![Uploading Screenshot_20210310-083403_Brave.jpg…]()
---
## Source website
- Name: Mangaku
- Link: https://mangaku.pro/
- Language(s): Indonesia

**Comment by scb261** [comment]
There is already mangaku with old URL that redirects to the URL you gave, but since it wasn't fixed back then, I guess just changing URL in the extension isn't enough #3697 #2530
