### ISSUE TITLE
[Bug] Mangasee : Mangas not in my library doesn't load

### ISSUE THREAD

**Issue by Aorm122** [tachiyomiorg/tachiyomi-extensions#6127]
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.9)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

---

## Device information
- Tachiyomi version: Preview r3136 
- Android version: 6

## Source information
- Name: Mangasee
- Extension version: 1.2.16

## Steps to reproduce
1. Open Mangasee extension
2. Open any manga that is not on my library

### Expected behavior
Covers and chapters should load

### Actual behavior
Covers and chapters don't load

## Other details
Mangasee on my phone works fine but it doesn't load on my tablet

**Comment by CrepeTF** [comment]
Wait for this fix to get merged and pushed
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/6134
