### ISSUE TITLE
[Bug] <Mangakawaii>: <Can't read manga or download them>

### ISSUE THREAD

**Issue by meliodasd** [tachiyomiorg/tachiyomi-extensions#6132]
## Device information
- Tachiyomi version: App version: 0.10.9 (standard, f590378, 56)
Android version: 10 (SDK 29)
Android build ID: AC2003_14_210204
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: Nord
Device model: AC2003
Device product name: Nord_EEA
- Android version: Android 10

## Source information
- Name: Mangakawaii 
- Extension version: 1.2.22

## Steps to reproduce
1. Click on manga 
2. Click on chapter 

### Expected behavior
Read the manga or download it 

### Actual behavior
The download does not take place 
Can't read the chapter 

## Other details
Thank you for your work

**Comment by Seishirou101** [comment]
why did you create another one? it's probably related to your other issue #6046

**Comment by meliodasd** [comment]
Yes probably 
My bad
