### ISSUE TITLE
MangaLife/MangaSee is overloaded and blocking Tachiyomi right now. Wait for unblock.

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi-extensions#6136]
## Device information
- Tachiyomi version: Preview r3002
- Android version: 10

## Source information
- Name: mangasee
- Extension version: 1.2.17

## Steps to reproduce
1. Try to download Survival Story of a Sword King in a Fantasy World (Erroring at least on ch66~80)

### Expected behavior
You should receive a notification containing an error `Invalid URL host: "jQuery(document).ready(function`

### Actual behavior
It should simply download the chapter.

**Comment by hyoretsu** [comment]
Might be related to #6107, it shows a Retry button when reading undownloaded chapters.

**Comment by EZarnosky** [comment]
This issue is still not resolved by the latest version 1.2.18. It worked OK for qp minutes, then fails.
