### ISSUE TITLE
[Bug] MangaDex: Error 451 on manga id 44387 when signed in on webview

### ISSUE THREAD

**Issue by EisbarGFX** [tachiyomiorg/tachiyomi-extensions#6141]
---

## Device information
- Tachiyomi version: v0.10.9
- Android version:  10

## Source information
- Name: Mangadex 
- Extension version: 1.2.105

## Steps to reproduce
1. Open mangadex entry https://mangadex.org/manga/44387/ (only manga i am experiencing this on.)
2. Read most recent chapter

### Expected behavior
Read chapter as is normal with other titles

### Actual behavior
Receive Error 451: Log in to view manga

## Other details
Only happens on chapter 81 of the linked manga. Any other chapter from that manga and any other manga in my list (that I have tested) do not give an error and read as normal.

**Comment by scb261** [comment]
Try to open the chapter in a browser - it's the issue on MangaDex side, report it to them
