### ISSUE TITLE
Cant find source

### ISSUE THREAD

**Issue by luizfz** [tachiyomiorg/tachiyomi-extensions#6143]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Galaxy A20

## Source information
* Source name: hentai cafe, hentai nexus
* Source extension version: ?

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
?

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
They were removed from extensions since those sites stopped working
> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
