### ISSUE TITLE
[Bug] <IMHentai>: <Viewing and Downloading error>

### ISSUE THREAD

**Issue by kenokarsi2000** [tachiyomiorg/tachiyomi-extensions#6146]
## Device information
- Tachiyomi version: 10.9
- Android version: 7.1.2

## Source information
- Name: IMHentai
- Extension version: 1.2.2

## Steps to reproduce
1. First Step - Enter IMHentai and view images from the first 3 Artist CGs
2. Second Step - Try downloading those Artist CGs

### Expected behavior
All Artist CGs shold be able to view and download

### Actual behavior
Most of the images from Artist CGs show "Retry" repeatedly and cannot be able to view and download

## Other details
Manga,Doujinshi and Other categories Except Western Cannot be viewed

**Comment by Rux02** [comment]
Imhentai extension is not displaying the contents since the start of August, pls if you can't fix pls delete I'm hentai
