### ISSUE TITLE
[Bug] MangaMutiny: Synching chapter number to tracker

### ISSUE THREAD

**Issue by ric0369** [tachiyomiorg/tachiyomi-extensions#6149]
## Device information
- Tachiyomi version: TachiyomiSy Preview r342
- Android version: 10

## Source information
- Name: MangaMutiny
- Extension version: 1.2.5

## Steps to reproduce
1. Find a manga with the volume number in the chapter name (e.g. Kumo Desu ga, Nani ka? Vol  7 chapter 31)
2. Finish the chapter.

### Expected behavior
Chapter number synched to tracker is 31

### Actual behavior
Chapter number synched to tracker is 7

## Other details
Sorting the chapter list by chapter number sorts by the volume number instead of the chapter number.

**Comment by Seishirou101** [comment]
should be fixed by #6159
