### ISSUE TITLE
[Bug] All Sources: won't download or update

### ISSUE THREAD

**Issue by KingZaraki** [tachiyomiorg/tachiyomi-extensions#6151]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 11

## Source information
- Name: mangasee and all sources
- Extension version: 1.2.16 for mangasee

### Expected behavior
I tried to install the new update for mangasee and install other extensions and it usually works.

However extensions would not install or update. I tried to uninstall some of them and install them again but now I can't even install them.

**Comment by scb261** [comment]
Try to install from [the site](https://tachiyomi.org/extensions). If still doesn't work, try to install them with [SAI](https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=en_US).

P.S. MangaSee isn't working right now because site owner is blocking Tachiyomi.

**Comment by alessandrojean** [comment]
Closing as it sounds to be a temporary connection issue.
