### ISSUE TITLE
[Bug] Mangasee: Problem downloading chapters

### ISSUE THREAD

**Issue by JLosh94** [tachiyomiorg/tachiyomi-extensions#6153]
Android Stylo 5
- Tachiyomi version:  0.10.9
- Android version: 9

## Source information
- Name: Mangasee
- Extension version: 1.2.19

## Steps to reproduce
1. Attempted to download chapter

### Expected behavior
Download chapters from the Mangasee Extension

### Actual behavior
Download fails.  Notification display states that Mangasee is overloaded and blocking Tachiyomi rights.

## Other details
Only seeing this issue with Mangasee.  No issues with other extensions.

**Comment by arkon** [comment]
#6136
