### ISSUE TITLE
[Bug] <Mangasee>: <Page loading (retry) error>

### ISSUE THREAD

**Issue by shiva9425g** [tachiyomiorg/tachiyomi-extensions#6155]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 8.1.0

## Source information
- Name: Mangasee
- Extension version: 1.2.19

## Steps to reproduce
1. Try loading page of any manga from "Mangasee"

### Expected behavior
Page should load

### Actual behavior
"Retry" error

## Other details
-My connection is fine and i can open the manga on webpage mode and on browser 
-other extensions are working fine
-It started happening after recent extension update (11 march)
![Screenshot_20210312-100751_Tachiyomi](https://user-images.githubusercontent.com/52504814/110892880-e2a84900-831a-11eb-9a0e-707826bfac2e.jpg)

**Comment by Riztard** [comment]
#6136
