### ISSUE TITLE
[Bug] Leviatan Scans: Changed theme to Madara

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi-extensions#6162]
## Device information
- Tachiyomi version: SY Comics r342.2
- Android version: 10

## Source information
- Name: Leviatan Scans
- Extension version: 1.2.2

## Other details
They changed theme to Madara

![Screenshot_20210312-121605.jpg](https://user-images.githubusercontent.com/70870719/110939275-10968900-832d-11eb-95ab-6c865734462a.jpg)

**Comment by OncePunchedMan** [comment]
a user in their discord said, it's temporary. not worth fixing if it will be back to "old" in a few day/weeks. no ETA

**Comment by Samk19** [comment]
Saw this on kenmei discord server

From kenmei developer

![image](https://user-images.githubusercontent.com/36104528/111834296-65339880-8919-11eb-96cf-356b9f66bdde.jpeg)
