### ISSUE TITLE
Json document was not fully  consumed (manga Life)

### ISSUE THREAD

**Issue by timwatkins57** [tachiyomiorg/tachiyomi-extensions#6163]
![Screenshot_20210312-165609_Tachiyomi](https://user-images.githubusercontent.com/12775407/110972398-de4c5200-8353-11eb-927e-bedb888e168c.jpg)

**Comment by charissepante** [comment]
Same issues with mangalife. All updated. Deleted data and reinstalled app

**Comment by timwatkins57** [comment]
> Same issues with mangalife. All updated. Deleted data and reinstalled app

Hopefully it will be resolved soon!

**Comment by timwatkins57** [comment]
Wait, how did you delete data?

**Comment by CrepeTF** [comment]
The MangaSee and MangaLife extensions have been intentionally made to not work by MangaSee and MangaLife's site administration.

We don't know if or when Mangasee/MangaLife will unblock us. Don't ask us about it. And definitely don't bother Mangasee/MangaLife site owner, it will only further agitate them. Migrate to a difference source.

**Comment by CarlosEsco** [comment]
#6153

**Comment by charissepante** [comment]
> Wait, how did you delete data?

On settings > storage.

I see. It was intentionally blocked. I understand. Thank you.
