### ISSUE TITLE
Toonily timeout in extension browse 

### ISSUE THREAD

**Issue by fam007e** [tachiyomiorg/tachiyomi-extensions#6164]
## Device information
- Tachiyomi version: 8.6.3-AZ
- Android version: 5.1 (Samsung J2)

## Source information
- Name: Toonily 
- Extension version: 1.2.3

## Steps to reproduce
Opening the extension via "browse" or "latest" feature.

### Expected behaviour
Browse the manhwa

### Actual behavior
Timeout is shown 

## Other details
After cloudfare check via web-view option, retry into browse in Toonily shows timeout (even though it works in "web-view" option of the extension).

**Comment by scb261** [comment]
Duplicate of #5613

**Comment by fam007e** [comment]
Web view works fine with bypass of cloudfare check but I can't browse via the app's extension browse or latest feature.

**Comment by scb261** [comment]
It still timeouts because of Cloudflare protection
