### ISSUE TITLE
[Bug] Lynx Scans : Hidden mangas cannot be searched

### ISSUE THREAD

**Issue by SaruDesu** [tachiyomiorg/tachiyomi-extensions#6167]
## Device information
- Tachiyomi version: 0.10.9-3136 (standard, 48e7cbd7, 56)
- Android version: 6.0.1 (SDK 23)

## Source information
- Name: LynxScans
- Extension version: 1.2.1

## Details
~~The extension can't find mangas that are not in the new release page in the website.~~
There are hidden mangas accessible only by searching it. These mangas doesn't appear on any page of the website but only by searching. 
Examples of manga not fetched:
The God of Death
First God of War

## Suggested solution
~~The comic page should be fetched. 
lynxscans.com/comics.~~
I retract my suggested solution as apparently the cause is due to the mangas not listed on any pages but only after searching it.

But it may be fixed if the in-app search feature  corresponds to the genkan search engine instaed of just searching fetched manga from lists or pages

**Comment by scb261** [comment]
I'm not sure what is the problem. The extension already uses `lynxscans.com/comics` for browse and `lynxscans.com/latest` for latest. And search also works fine for me. Can you give steps to reproduce and describe what is the problem exactly?

**Comment by CarlosEsco** [comment]
Pretty sure they are clicking latest and not the source name.
