### ISSUE TITLE
[Bug] <Aloalivn>: <No pages found>

### ISSUE THREAD

**Issue by mrehanabbasi** [tachiyomiorg/tachiyomi-extensions#6171]
## Device information
- Tachiyomi version: Preview r3136
- Android version: 10

## Source information
- Name: Aloalivn
- Extension version: 1.2.2

## Steps to reproduce
1. Open any manga/manhua from the Aloalivn source.
2. Try to download any chapter.

### Expected behavior
The chapter should be downloaded without any issue.

### Actual behavior
It shows the "No pages found" error notification.

## Other details
The pages show up in webview.

**Comment by scb261** [comment]
Works for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis). Give specific example what manga/chapter has the problem.

**Comment by mrehanabbasi** [comment]
I've tried troubleshoot but it's not working. None of the chapters for any manga/manhua are opening.

**Comment by scb261** [comment]
Yeah, can reproduce now with "Divine Hero's Skyfall System"
