### ISSUE TITLE
[Bug] <Super Hentais>: <Not a JSON a object: null>  

### ISSUE THREAD

**Issue by 2wlsousa** [tachiyomiorg/tachiyomi-extensions#6174]
## Device information
- Tachiyomi version: 10.9
- Android version: 9.0

## Source information
- Name: SuperHentais
- Extension version: 1.2.6

## Steps to reproduce
1. Enter the extension

### Expected behavior
Extension should open without any error

### Actual behavior
When you enter the extension this error appears Not a JSON a object: null

**Comment by alessandrojean** [comment]
I will take a look.
