### ISSUE TITLE
[Bug] Sleeping Knight Scans: Cert error, Changed to Madara

### ISSUE THREAD

**Issue by TigerUppercut** [tachiyomiorg/tachiyomi-extensions#6178]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Sleeping Knight Scans
- Extension version: 1.2.1

## Steps to reproduce
Viewing and updating manga from Source

### Expected behavior
Display manga and update chapters.

### Actual behavior
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

## Other details
Website changed to Madara

**Comment by OncePunchedMan** [comment]
a user in their discord said, it's temporary. not worth fixing if it will be back to "old" in a few day/weeks. no ETA
