### ISSUE TITLE
[Bug] Bato.to [EN]: next loading page is in looped (Retry) whenever i switch to other app or after cellphone's standby mode

### ISSUE THREAD

**Issue by pisola93** [tachiyomiorg/tachiyomi-extensions#6182]
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: 11

## Source information
- Name: Bato.to [EN]
- Extension version: 1.2.4

## Steps to reproduce
1. Reading any manga from this source (Bato.to [EN]) normally
2. Either switch to the other app / close the phone to the standby mode
3. Opening the tachiyomi app again by clicking the app or just after opening the phone from standby mode
4. Next loading page from the manga is always showing the (Retry) button

### Expected behavior
The manga is loading succesfully to open up another next pages

### Actual behavior
Instead of loading succesfully, it always shows Retry and when i clicked it, showing loading circle just half of a second, and then return to Retry notification again

## Other details
I can fix the bug by deleting the cache from the Advanced Setting in the Tachiyomi app, but it sucks that whenever i switched to the other app or in standby mode, the Retry is always returning
![Screenshot_20210315-184204_Tachiyomi](https://user-images.githubusercontent.com/80683402/111143538-d80edd80-85c0-11eb-9a73-842ac8b1eb9d.jpg)

**Comment by scb261** [comment]
Bato.to gives temporary links to images, that work only for 10 minutes. I suggest to download before reading. Similar issue with mangapark #6098.

**Comment by pisola93** [comment]
> Bato.to gives temporary links to images, that work only for 10 minutes. I suggest to download before reading. Similar issue with mangapark #6098.

Oooh, so that's what's going on! I honestly thought that bato.to extension is kinda buggy, but it seems that bato.to took this kinda route to avoid "previous" issue
