### ISSUE TITLE
[Bug] Martial scans>: <error 404>

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#6195]
## Device information
- Tachiyomi version: 0.10.9
- Android version:  5.1.1

## Source information
- Name: Martial Scans
- Extension version: 1.2.1

## Steps to reproduce
1. First Step open extensions
2. Second Step 

### Expected behavior
open normally

### Actual behavior
error 404 show up

**Comment by scb261** [comment]
Duplicate of #5728
