### ISSUE TITLE
[Bug] Madara: Sub-extension Neox Scanlator not returning Mangas and Manwhas as before

### ISSUE THREAD

**Issue by AlyssonVitor500** [tachiyomiorg/tachiyomi-extensions#6211]
## Device information
- Tachiyomi version: v0.10.9 (newest version)
- Android version: 9

## Source information
- Name: Madara
- Extension version: v1.2.176 (newest version)

## Steps to reproduce
1. Download sub extension of Madara (Brazil) Neox Scanlator
2. Click on Neox Scanlator

### Expected behavior
Opens a page with Mangas and Manwhas from Neox Scans

### Actual behavior
Returns the message: Http error 400: Verify the website on webview

## Other details
The website is working normally

**Comment by scb261** [comment]
Madara was split into separate extensions, read #5672
