### ISSUE TITLE
[Bug] Komikcast: No chapters found

### ISSUE THREAD

**Issue by Hannaichi** [tachiyomiorg/tachiyomi-extensions#6212]
---

## Device information
- Tachiyomi version: 0.10.9
- Android version: 8

## Source information
- Name: Komikcast
- Extension version: 1.2.4

## Steps to reproduce
1. Update Library

### Expected behavior
Library updated

### Actual behavior
No chapters found

## Other details
![image](https://user-images.githubusercontent.com/79848320/111671047-1a4b4f80-884b-11eb-81df-b01f8633dc04.png)

**Comment by fuad04** [comment]
![Uploading 20210319_094409.png…]()

**Comment by fuad04** [comment]
![Uploading 20210319_094409.png…]()

**Comment by fuad04** [comment]
![Uploading 20210319_094409.png…]()

**Comment by Riztard** [comment]
need to fix the "chapter list" maybe with regex which i dont know much
maybe someone? 
#6216

**Comment by Riztard** [comment]
nvm seems like i did it, maybe im just tired

**Comment by Riztard** [comment]
nvm seems like i did it, maybe im just tired
