### ISSUE TITLE
[Bug] <Flame Scans>: No Results Found

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#6213]
### Device information

 Tachiyomi version: 0.10.9
 Android version: 10

### Source information

  Name: Flame Scans
  Extension version: 1.2.2

### Steps To Reproduce

- Browse Flame Scans

### Expected behavior

should show manga

### Actual behavior

No Results Found

### Other details

Webview works fine

**Comment by Riztard** [comment]
the site is broken too, cant see any manga in here
but can still search, so only search is broken for now

**Comment by Riztard** [comment]
nvm it just they change list manga but their button still unchanged
