### ISSUE TITLE
[Bug] <TritiniaScans> Images not loading 

### ISSUE THREAD

**Issue by tblader** [tachiyomiorg/tachiyomi-extensions#6214]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: 8

## Source information
* Source name: TritiniaScans 
* Source extension version: 1.2.1

## Steps to reproduce
Go to _Lord of Money_ or _Movies are Real_ and open the latest chapter

## Issue/Request
"The image couldn't be loaded" 

## Other details
Works fine in WebView

**Comment by CrepeTF** [comment]
Images are in the SVG format

**Comment by scb261** [comment]
Looks like they use JPG now and it works fine. Can you confirm if it works for you? Remove downloads for this manga and clear chapter cache in settings to be sure.
