### ISSUE TITLE
[Bug] problem

### ISSUE THREAD

**Issue by fuad04** [tachiyomiorg/tachiyomi-extensions#6221]
## Device information
- Tachiyomi version: v 0.10.9
- Android version: 6

## Source information
- Name: Komikcast
- Extension version: v1.2.5

## Steps to reproduce
1. Install komikcast
2. Unnistall komikcast
### Expected behavior
Describe what should have happened
since then some extensions do not appear in the source
![IMG-20210320-WA0000](https://user-images.githubusercontent.com/80931279/111853251-c2950d00-894c-11eb-8a06-0c8d43566321.jpg)

**Comment by Riztard** [comment]
wat, try this https://tachiyomi.org/help/guides/troubleshooting/#diagnosis

**Comment by Zidan8376** [comment]
![Screenshot_2021-03-20-15-43-30-29_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/81010981/111864403-3e19ad00-8993-11eb-94d6-5e6170151a5d.jpg)

Why is the image from the "Komikcast" extension blurry?  whereas in other extensions it is not blurry

**Comment by Riztard** [comment]
what manga, did you check the site?

**Comment by Zidan8376** [comment]
From extension Komik Cast

**Comment by Zidan8376** [comment]
All manga in extensions Komik Cast

**Comment by Riztard** [comment]
> All manga in extensions Komik Cast

looks good for me, have you tried troubleshoot?

**Comment by Riztard** [comment]
fixed by reinstall *in discord

**Comment by Zidan8376** [comment]
Yeah thank you its fix my problem, anyway user in discord is me 🙂
