### ISSUE TITLE
[Source Request] <ManhwaID>

### ISSUE THREAD

**Issue by endrare** [tachiyomiorg/tachiyomi-extensions#6223]
## Source website
- Name: ManhwaID
- Link: https://manhwaid.co
- Language(s): Indonesia

**Comment by uzumakhiadi** [comment]
Fast

**Comment by AMVengeance** [comment]
> ## Source website
> * Name: ManhwaID
> * Link: https://manhwaid.co
> * Language(s): Indonesia

plz make it

**Comment by arkon** [comment]
New URL: #10097
