### ISSUE TITLE
[Bug] <Japscan>: Some chapter won't download, or open with online reading

### ISSUE THREAD

**Issue by hyminix** [tachiyomiorg/tachiyomi-extensions#6234]
## Device information
- Tachiyomi version: preview r3159 and latest stable release
- Android version: 11

## Source information
- Name: Japscan
- Extension version: 1.2.25

## Steps to reproduce
1. Try to download a chapter (Ex: solo leveling 144, Versatile Mage 515)
2. Try to open the same chapter with online reading

### Expected behavior
Chapter is downloaded or opened from online reading

### Actual behavior
With online reading, endless loading appears, without error
For the download, no page number is displayed and the download does not start

## Other details
For the same source, other series can be downloaded without problem, but for a few days some chapter of some series no longer works

**Comment by CarlosEsco** [comment]
#6166
