### ISSUE TITLE
[Bug] Hentai2Read: Faulty URL Intent.

### ISSUE THREAD

**Issue by Fmoment1** [tachiyomiorg/tachiyomi-extensions#6239]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Hentai2Read
- Extension version: 1.2.12

## Steps to reproduce
1. Tap on any Hentai2Read link.

### Expected behavior
The entry opens in-app.

### Actual behavior
The app does open, but it keeps loading indefinitely - with exceptions (discussed below).

## Other details
I had reported this exact same thing two months ago (#5495), and it was supposedly fixed, but I don't see any difference. I'll repeat:

>I've noticed that if the link is for an entry that's **already in my library**, or if the entry was **opened in-app before** (*cached?*) then it works as intended. 

>However, if the entry is completely new for the app, it results in indefinite loading.

To further simplify, the way the links are written, if there's an entry called "A Very Good Day" (just an example), the link will be like `https://hentai2read.com/a_very_good_day/`. If I had opened this entry in the app before, either just to see the details or for reading, any future instance of tapping on that link will yield a successful url intent operation. If I had not, then it'll result in indefinite loading. The extension seems to identify the entry when the underscores are removed, (so just like a normal in-app search) very strangely.

I'm also having unusual `timeout` difficulties with this extension which is also strange considering my network is fine and everything else works fine for me. But that's a different issue. Anyway, hope this clears things up.

**Comment by scb261** [comment]
Odd, it works for me. Your link gives `No results found` since it doesn't exist even in browser, but other links work fine for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis). Since you're saying that you have good internet and timeouts, I suggest to try VPN in the first place.

**Comment by MercerBoi** [comment]
My link doesn't give any results because it's an imaginary link used for example. I suppose this is a problem specific to me. Not sure about the intricacies of this issue since the source does work without VPN, it just stumbles a bit before working.
