### ISSUE TITLE
[Source Request] <SekaiKomik>

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#6241]
## Source website
- Name: SekaiKomik
- Link: https://www.sekaikomik.net/
- Language(s): Indonesian

## Other details
I have searched the existing GitHub issues and this extension does **NOT** have an open request

**Comment by Riztard** [comment]
yang bug report bambang, yang ini https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new?assignees=&labels=bug&template=source_bug.md&title=%5BBug%5D+%3CSource+Name%3E%3A+%3Cshort+description%3E

**Comment by scb261** [comment]
Closing, since it's a bug reported in #6242, not a new site
