### ISSUE TITLE
Set reading mode per source

### ISSUE THREAD

**Issue by pompedus** [tachiyomiorg/tachiyomi-extensions#6250]
## Device information
* Tachiyomi version: App version: 0.10.9 (standard, f590378, 56)
* Android version: 11 (SDK 30)
* Device: OnePlus 7T Pro

## Request
There should be an option of setting reading mode per source. For example if there is a source with only webtoons, you could set reading mode to webtoon, while another source could use right to left for example

**Comment by scb261** [comment]
Duplicate of tachiyomiorg/tachiyomi#4649
