### ISSUE TITLE
[Source Request] Nyahentai( 喵绅士中文站)

### ISSUE THREAD

**Issue by NaughtDZ** [tachiyomiorg/tachiyomi-extensions#6256]
## Source website
- Name: 喵绅士（nyahentai）
- Link: http://zh.nyahentai.fun/
- Language(s): Chinese

## Other details
this website can be reading without vpn in China(english ver need vpn),pls add

**Comment by scb261** [comment]
For easier searching for duplicates and for making extension without unnecessary redirects - zh.nyahentai.fun redirects to zh.ddhentai.com
