### ISSUE TITLE
Tachiyomi crashes when opened.

### ISSUE THREAD

**Issue by Nubosity** [tachiyomiorg/tachiyomi-extensions#6257]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device:  Samsung Galaxy A20S

## Steps to reproduce
1. Just opening the app

## Issue/Request
Tachiyomi continuously crashes when opened.

**Comment by Riztard** [comment]
1. if the app is closed when "Just opening the app" then not extension issue
2. next time go to discord support maybe it will solved faster
3. try this https://9to5google.com/2021/03/22/android-apps-crashing-webview/
if still not work go to discord support or report to tachiyomiorg/tachiyomi not here
