### ISSUE TITLE
CocoManhwa (OneManga) 502 error

### ISSUE THREAD

**Issue by KusanagiRyu** [tachiyomiorg/tachiyomi-extensions#6260]
---

## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Huawei Mate20

## Source information
* Source name: CoCoManhwa (OneManga) 
* Source extension version: 1.2.7

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
Error 502
Tried reading any of manhwa from extension, received error 502 instead. Tried reinstalled pre-release, still get error. Tried installing the official release, still get error. 

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
You mean `CoCoManhua (OhManhua)`? It works fine for me. 5xx errors are server side errors, probably the site was down when you tried it. Can you confirm if it works for you now?

**Comment by KusanagiRyu** [comment]
It work now. Webview of the site was working while trying to read it thru the app gives error 502 that day.
