### ISSUE TITLE
[Bug] <komik cast - wp manga stream>: <no result found>

### ISSUE THREAD

**Issue by nancysavchenkoo** [tachiyomiorg/tachiyomi-extensions#6274]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 8.0

## Source information
- Name: komik cast - wp manga stream
- Extension version: 1.2.27

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

## Other details
Bahasa indonesia

**Comment by scb261** [comment]
You need to use the new extension #5672

**Comment by CrepeTF** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4524#issuecomment-782876645

**Comment by CrepeTF** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5672
