### ISSUE TITLE
Mangawindow has no extension

### ISSUE THREAD

**Issue by volkayno** [tachiyomiorg/tachiyomi-extensions#6282]
After splitting sources which is a nice move btw I wasnt able to find Mangawindow any longer

---

## Device information
* Tachiyomi version: 0.10.9
* Android version: 6
* Device: Samsung s7 edge

## Source information
* Source name: Mangawindow
* Source extension version: Emerald

## Steps to reproduce
1. Remove Emerald
2. Second install Bato.to and Mangawindow

## Issue/Request
Extention for Mangawindoe

## Other details
Additional details and attachments.

**Comment by Riztard** [comment]
isnt mangawindow is dead?

**Comment by volkayno** [comment]
Mangawindow is indeed dead thanks for informing me
