### ISSUE TITLE
[Bug] Mangasee : Can't read downloaded chapter

### ISSUE THREAD

**Issue by Poncow5** [tachiyomiorg/tachiyomi-extensions#6284]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 5

## Source information
- Name: mangasee
- Extension version: 1.2.21

## Steps to reproduce
1. Downloading manga from mangasee
2. Try to read downloaded chapter

### Expected behavior
The chapter should be downloaded and able to be opened offline in tachiyomi reader

### Actual behavior
The chapter got downloaded but cannot be read in tachi reader

## Other details
Every time downloading a chapter from mangasee it's create a new folder named mangasee (1), (2) and so on.

**Comment by scb261** [comment]
Remove folders `MangaSee (EN) (1)`, rename `Mangasee (EN)` to `MangaSee (EN)`, and force close the app. I think I'll leave this one open for now so other users will see it.

**Comment by haffizhissham** [comment]
Do we need to wait for extension update from mangasee? or there are a way to circumvent this issue?
apart from manually renaming folders downloaded

![image](https://user-images.githubusercontent.com/38602279/120057359-05721000-c075-11eb-95ed-879f50cdb302.png)
![image](https://user-images.githubusercontent.com/38602279/120057391-466a2480-c075-11eb-91fe-f56fa3146603.png)

**Comment by loocool2** [comment]
@haffizhissham Follow the instructions in the comment above. Please read.

**Comment by haffizhissham** [comment]
> @haffizhissham Follow the instructions in the comment above. Please read.

noted. thanks for your help and the inconvenience cause.
Missed the capital when read comment above.
