### ISSUE TITLE
<copymanga extension> unable to pull information from source

### ISSUE THREAD

**Issue by kayakibraco** [tachiyomiorg/tachiyomi-extensions#6299]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Red Magic 5s

## Source information
* Source name: copymanga
* Source extension version: 1.2.5

## Issue/Request
The website is up and all, but unable to grab thumbnail, image, etc.

## Other details
It was working fine about 3-5 days ago
Have force stop the app and uninstall & reinstall extension but didnt fix it

**Comment by isNijikawa** [comment]
same, report “     code": 210, "message": "\u8acb\u53bb\u5b98\u7db2\u4e0b\u8f09\u6700\u65b0APP\u4f7f\u7528!", "results": null    ”from build in webview, website working normally in browser.

**Comment by SORclown** [comment]
using windows visit the site is ok, but when phone open the site in other browser，it will redirect to download app

**Comment by CarlosEsco** [comment]
possibly resolved in just merged version
