### ISSUE TITLE
[Bug] Mangapill : The date of when the chapters were uploaded is not visible

### ISSUE THREAD

**Issue by ShahbazKhan97** [tachiyomiorg/tachiyomi-extensions#6302]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 11

## Source information
- Name: MangaPill
- Extension version: 1.2.1

## Steps to reproduce
1. Open Mangapill 
2. Open any manga to read from

### Expected behavior
Should have the date when the chapter was uploaded visible

### Actual behavior
Date of chapters' upload not visible
![Screenshot_20210327-122017](https://user-images.githubusercontent.com/47472035/112712793-8dae2a80-8ef7-11eb-9864-fb6a3cf2a47a.jpg)

**Comment by scb261** [comment]
Are there dates for chapters on the site?

**Comment by ShahbazKhan97** [comment]
> Are there dates for chapters on the site?

Oh wait, it isn't. Makes sense. You can close this report. I will go and talk to mangapill then
