### ISSUE TITLE
[Bug] <Disaster Scans>: <Chapter doesn't load gives error 403 even though the wesite is fine and working/>

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi-extensions#6304]
## Device information
- Tachiyomi version: v0.10.9 (Stable)
- Android version: 6.0

## Source information
- Name: Disaster Scan
- Extension version: v1.2.1(Latest)

## Steps to reproduce
1. Select any chapter of a manga from the source Disaster Scans.

### Expected behavior
Chapter should load with images.

### Actual behavior
Chapter tries to load for a second and then gives error 403.

Video - https://youtube.com/shorts/mOWoNP-77Eg

## Other details
Manga updates as usual. Problem only occurs when trying to read a chapter. Nothing wrong even in webview

**Comment by scb261** [comment]
Works for me. Do chapters actually load in webview? Can you give an example of manga and chapter with the problem?

**Comment by CrepeTF** [comment]
Works fine for me, you could've been IP banned from the source, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis)

**Comment by FourTOne5** [comment]
> 
> 
> Works fine for me, you could've been IP banned from the source, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis)

Well I don't think I'm IP banned. When I open it on WebView the site loads as usual.

**Comment by FourTOne5** [comment]
I updated the report with a video.

**Comment by Riztard** [comment]
did you try troubleshoot?

**Comment by FourTOne5** [comment]
> did you try troubleshoot?

Yup. Even freshly installed Tachiyomi and the Disaster Scan extension on Android 10 but the result is still same.

**Comment by Riztard** [comment]
vpn too?
