### ISSUE TITLE
[Source Request] <readmha>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#6309]
## Source website
- Name: remha
- Link: https://ww6.readmha.com/
- Language(s): English

**Comment by scb261** [comment]
Similar to mangamainac, they have separate site for each manga (e.g. #6308 and [many other sites](https://ww3.readopm.com/read-manga/)), could be added as a multisrc.

**Comment by FireNation323** [comment]
> Similar to mangamainac, they have separate site for each manga (e.g. #6308 and [many other sites](https://ww3.readopm.com/read-manga/)), could be added as a multisrc.

That would be perfect because they actually update faster than mangapill

**Comment by jopejoe1** [comment]
Yeah no idear what to call the multisrc extension for these group of websites. Do they have an official collective name or some thing?
