### ISSUE TITLE
[Bug] <Darkyu Realm>: <Error 404>

### ISSUE THREAD

**Issue by thanosluyang** [tachiyomiorg/tachiyomi-extensions#6310]
## Device information
- Tachiyomi version: 0.10.9

## Source information
- Name: Darkyu Realm
- Extension version: 1.2.1

## Steps to reproduce
1. Click on extension or latest

### Expected behavior
Access manga list.

### Actual behavior
Message asking to check webview (HTTP error 404).

## Other details
The page loads normally in webview.

**Comment by alessandrojean** [comment]
Already solved by #7106.
