### ISSUE TITLE
[Bug] <Mangahere>: <Not Handling Chapters after #1000>

### ISSUE THREAD

**Issue by Klunst** [tachiyomiorg/tachiyomi-extensions#6312]
## Device information
- Tachiyomi version: preview r3172 / stable 0.10.7
- Android version: 10

## Source information
- Name: Mangahere
- Extension version: 1.2.15

## Steps to reproduce
1. Load chapter of Martial Peak 999
2. Try to go to 'ext chapter

### Expected behavior
Normally, chapter should show up in the list to the last one (around 1050).

### Actual behavior
Chapter after 999 are not shown. Both on preview and stable version. When I try to go from chapter 999 to 1000 (Webtoon View), it indicates that this is the last chapter. But I can access it from the "new chapters" if I click on chapter 1000, and chapter transition will work until chapter 1009. After Chapter 1009, it will go back to chapter 101. Same behavior at Chapter 1019, the next chapter shown will be chapter 102. And so on. This behavior occur with Martial peak, but not Hajime No Ippo for example, which also have more than 1000 chapters.

Thank you for reading.

**Comment by scb261** [comment]
That's just how the site sorts chapters, you can check it in WebView. You can sort chapter list `By chapter number`.
![image](https://user-images.githubusercontent.com/65343233/112738482-0353de00-8f6c-11eb-985e-8d02ed30be33.png)
