### ISSUE TITLE
[Bug] <xCaliBR Scans>: <Endless chapter load>

### ISSUE THREAD

**Issue by FrixBOX** [tachiyomiorg/tachiyomi-extensions#6316]
## Device information
- Tachiyomi version: 0.10.9
- TachiyomiSY version:r347
- Android version: 7

## Source information
- Name: xCaliBR Scans
- Extension version: 1.2.2

## Steps to reproduce
1. Select Manhua
2. Open or download chapter

### Expected behavior
open or download chapter without issue

### Actual behavior
when opening chapter it's stuck at loading chapter without error code.
when downloading chapter it's show error expected url scheme 'http' or 'https' but no colon- (can't read the rest of the error)

**Comment by Samk19** [comment]
Facing same issue

**Comment by FrixBOX** [comment]
Maybe caused by yesterday maintenance
