### ISSUE TITLE
[Feature Request] <IsekaiScan>: <Use actual date of update for new chapters or allow for sort by recent updates>

### ISSUE THREAD

**Issue by K3end0** [tachiyomiorg/tachiyomi-extensions#6327]
IsekaiScan marks chapters as being released [x seconds ago] for multiple days after its actual update release. This means that for users that filter library by "latest chapter", which relies on the date of update sources provide, the top of the library will be filled with manga from this source marked as having released more recently than it actually was. 

For example, a manga from IsekaiScan that had a chapter release on the 24th will, if the manga is refreshed, now be marked as having its recent chapter release on today's date and pushed again to the top of the library. This will happen whenever the manga is refreshed.

Replacing the source-given date of release listed with the actual date of update would resolve this issue for this source, or preferably adding a feature to allow users to sort their library by the actual most recent updates instead of the latest date prescribed to a chaper would resolve similar date issues that may arise in other sources as well

**Comment by scb261** [comment]
> Replacing the source-given date of release listed with the actual date of update would resolve this issue for this source

From where the extension would take the actual date?

> adding a feature to allow users to sort their library by the actual most recent updates instead of the latest date prescribed to a chaper

This isn't something that is done within an extension. You can request on tachi github to use fetch date instead of upload date.

**Comment by K3end0** [comment]
> From where the extension would take the actual date?

Just so i don't continue to double-post, for both this and #6328 maybe it could use the date on a user's own device of when the update was fetched to set the 'actual' upload date?

> This isn't something that is done within an extension. You can request on tachi github to use fetch date instead of upload date.

Will do. Date issues appears to be a reccuring problem in general (#6067) but a sort by fetch date would completely avoid them.

**Comment by scb261** [comment]
That's not how extensions work - they can't access fetch date or upload date from previous fetch. Closing, since it's a site issue.
