### ISSUE TITLE
[Feature Request] <Mangahub>: <Use actual date of update for new chapters or allow for sort by recent updates>

### ISSUE THREAD

**Issue by K3end0** [tachiyomiorg/tachiyomi-extensions#6328]
Mangahub marks the date of its chapters a day or two behind the actual date of its update. This means that for users that filter library by "latest chapter", which relies on the date of update sources provide, the recently updated manga from Mangahub do not appear where they should in the library and instead appear lower down in the library. 

Replacing the source-given date of release listed with the actual date of update would resolve this issue for this source, or preferably adding a feature to allow users to sort their library by the actual most recent updates instead of the latest date prescribed to a chaper would resolve similar date issues that may arise in other sources as well

(this issue is similar to IsekaiScan, hence my very similar postings.)

**Comment by scb261** [comment]
The same as https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6327#issuecomment-808986796 , from where the extension would take the actual date?

**Comment by scb261** [comment]
Same as #6327 - site issue, closing.
