### ISSUE TITLE
[Bug] <HentaiHand>: <Login through WebView to read locked content & Manga without language tag>

### ISSUE THREAD

**Issue by SrofW** [tachiyomiorg/tachiyomi-extensions#6329]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: HentaiHand
- Extension version: 1.2.1

## Steps to reproduce
1. Log in to the HentaiHand account using WebView to access locked content.
2. Trying to read this content in the application after logging shows error 401.

### Expected behavior
I guess that after logging in with the account, the locked content should be readable.

### Actual behavior
Error 401, I can read it through Webview but not in the app.

## Other details
I tried deleting cookies, logging out, creating a new account using WebView and reinstalling the extension but it didn't solve the problem.
I also noticed that there are many wholesome manga that don't have a language tag in the web and these manga cannot be found by the app.

**Comment by scb261** [comment]
Can you give an example?

**Comment by SrofW** [comment]
Almost all manga tagged as Premium has no language tag, but I chose this one that has English tag for demonstration

![1](https://user-images.githubusercontent.com/59592921/112774053-03042300-8ffe-11eb-81da-69b499b633c1.jpg)
Already logged, it can be read in WebView.

![2](https://user-images.githubusercontent.com/59592921/112774320-f2a07800-8ffe-11eb-8e85-4382c96e2723.jpg)
Trying to read it in the app gives this error


![3](https://user-images.githubusercontent.com/59592921/112774456-588cff80-8fff-11eb-9693-28ac7f061160.jpg)
![4](https://user-images.githubusercontent.com/59592921/112774458-5d51b380-8fff-11eb-91e0-67a2fa980c0a.jpg)

The one tagged as premium does not have a language tag in the Details part, but the other one does


![5](https://user-images.githubusercontent.com/59592921/112774679-fe406e80-8fff-11eb-9581-4aa6d218a69c.jpg)
![6](https://user-images.githubusercontent.com/59592921/112774687-04364f80-9000-11eb-9eb1-fa4aebc5b36d.jpg)

No results found when searching in the app but there are results in WebView.
