### ISSUE TITLE
[Feature Request] Mangasee and manga4life, add Type as genre tag 

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi-extensions#6332]
Hi, in mangasee and manga4life extension, please add Type as genre in manga description, and if possible in filter. Solo leveling is a manhwa on mangasee/manga4life website but it not show as such on tachiyomi

https://mangasee123.com/search/?type=Manhwa 

https://manga4life.com/search/?type=Manhwa

![Capture](https://user-images.githubusercontent.com/81538887/112773918-e9ff7000-9005-11eb-9eee-4c23828820de.JPG)

**Comment by Riztard** [comment]
added in #6382
