### ISSUE TITLE
[Bug] <MangaFast>: Manga & Chapters Not Showing

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#6338]
### Device information
Tachiyomi version: 0.10.9

### Source information
Name: MangaFast
Extension version: 1.2.6

### Steps To Reproduce

- Browse MangaFast Source

### Expected behavior

- Should Show Manga

### Actual Behavior
![IMG_20210329_125437](https://user-images.githubusercontent.com/69104545/112801766-e7952880-908e-11eb-9305-d4b4fb1c061c.jpg)
![IMG_20210329_130201](https://user-images.githubusercontent.com/69104545/112801841-02679d00-908f-11eb-9935-7cdfd7cb6cca.jpg)

### Other Details

The page loads normally in webview

**Comment by mcOz1** [comment]
I have the same problem.
