### ISSUE TITLE
Mango add ignore DNS over HTTPS

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi-extensions#6340]
see solution here #6335

**Comment by hkalexling** [comment]
Hi, I will look into this. Btw is there a way for me to get notified when there's an issue related to Mango? I am the creator of Mango (but not the extension), and I already missed a few important issues here.

**Comment by CarlosEsco** [comment]
I don't think there is a way,  I'll try to remember to ping you if i see a mango issue opened

**Comment by hkalexling** [comment]
Sweet! Thanks you :)
