### ISSUE TITLE
[Source Request] <Void Scans>

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#6342]
## Source website
- Name: Void Scans
- Link: voidscans.net
- Language(s): English

## Other details
Void Scans changed their domain extension from .com to .net

**Comment by Riztard** [comment]
they now use lanraragi for their website, so you can just instal lanraragi and just input host name in the setting

**Comment by Banhammer151** [comment]
It doesn't anymore
