### ISSUE TITLE
[Bug] Mangakawaii: Error http or https

### ISSUE THREAD

**Issue by moi15moi** [tachiyomiorg/tachiyomi-extensions#6360]
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: 10

## Source information
- Name: Mangakawaii
- Extension version: 1.2.25

## Steps to reproduce
1. Try download [this chapter](https://www.mangakawaii.com/manga/GodofMartialArts/124.2/1). Chapter 124.2 of God of Martial Arts

### Expected behavior
Should download the chapter.

### Actual behavior
I received the error: **Expected URL sheme 'http' or 'https' but no colon (I can't see the rest of the error message)**
## Other details
Thank you very much

**Comment by papjul** [comment]
I can't even get to the chapter page, you probably have them in cache.

@Riztard I saw a lot of commits from you on this extension, I thought that I would let you know. I did some research and chapter pages are now loaded from another XMLHttpRequest, but I didn't know how to pass down the URL from mangaDetails regexp "/arrilot/load-widget" parsing to the chapterListRequest. If you want to work on it, please do them on top of #6371 which fixes some cover issues and does some clean up, to avoid conflicts.

**Comment by Riztard** [comment]
> @Riztard I saw a lot of commits from you on this extension, I thought that I would let you know. I did some research and chapter pages are now loaded from another XMLHttpRequest, but I didn't know how to pass down the URL from mangaDetails regexp "/arrilot/load-widget" parsing to the chapterListRequest. If you want to work on it, please do them on top of #6371 which fixes some cover issues and does some clean up, to avoid conflicts. Nevermind, it got merged quickly.

that sounds complicated, im too dumb for that. 
![image](https://user-images.githubusercontent.com/16263232/113177527-d2c7b900-9277-11eb-91d2-64300f3f2020.png)
maybe someone else can fix it

**Comment by moi15moi** [comment]
> I can't even get to the chapter page, you probably have them in cache.
> 
> @Riztard I saw a lot of commits from you on this extension, I thought that I would let you know. I did some research and chapter pages are now loaded from another XMLHttpRequest, but I didn't know how to pass down the URL from mangaDetails regexp "/arrilot/load-widget" parsing to the chapterListRequest. If you want to work on it, please do them on top of #6371 which fixes some cover issues and does some clean up, to avoid conflicts. Nevermind, it got merged quickly.

No, I can access the chapter via my navigator.

**Comment by moi15moi** [comment]
There is a new update, but the problem is still here..

**Comment by papjul** [comment]
Yes, it's #6371, I mentioned it earlier

**Comment by Riztard** [comment]
this will be closed if the problem is solved

**Comment by moi15moi** [comment]
> #6461 will fix chapter list being empty on some specific manga.
> It will not solve this issue.
> 
> Edit: Nevermind, found what was the issue, it will be fixed in next version.

I have updated to the 1.2.27, but I still have a problem.
I don't have the same error as before (_Expected URL sheme 'http' or 'https' but no colon (I can't see the rest of the error message_).

Now, it just don't download the lasted page and the download stop without any error.
![image](https://user-images.githubusercontent.com/80980684/113950214-cb0b9580-97de-11eb-9abf-7522b862acec.png)

**Comment by papjul** [comment]
Next version is 28.

On version 27, you need to skip the first page.
