### ISSUE TITLE
[Bug] xkcd: detection of non image

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#6370]
## Device information
- Tachiyomi version: r349
- Android version: 10

## Source information
- Name: xkcd
- Extension version: 1.2.8

## Steps to reproduce
1. Try opening one of these chapters 1350, 1416, 1608, 1663

### Expected behavior
Load image

### Actual behavior
Infinity loading

## Other details
In these chapter there exist no image as thy interactive content and should be filtered out or be replaced with a placeholder image that indicate that to see this content you need to visit the website

**Comment by curche** [comment]
The extension code actually checks for "div#comic img" attribute which is missing in the above examples
But each one has a different attribute replacing it
 
<details>
<summary>1663</summary>

```
<div id="comic">
<script src="https://linden.xkcd.com/linden.js" data-endpoint="https://linden.xkcd.com/" data-image-endpoint="/1663/art/" data-title="Relax.">
</script>
</div>
```
</details>

<details>
<summary>1608</summary>

```
<div id="comic">

<div id="explore"></div>
<style>
@font-face {
  font-family: 'xkcd-Regular';
  src: url('/fonts/xkcd-Regular.eot?') format('eot'), url('/fonts/xkcd-Regular.otf') format('opentype');
}

#explore {
  position: relative;
  width: 740px;
  height: 700px;
  border: 2px solid black;
  font-family: xkcd-Regular;
  margin: 0 auto;
}

#explore:focus {
  box-shadow: 0 0 30px 3px #96a8c8;
}
 
</style>
<script src="/1608/tigl.min.js"></script>
<script>
helloWorld(function(path) {
  return '/1608/' + path
})
</script>
</div>
```
</details>

<details>
<summary>1416</summary>

```
<div id="comic">

<iframe frameborder="0" scrolling="0" style="display: block; margin: 0 auto; border: none; overflow: hidden" width="600" height="600" src="//imgs.xkcd.com/turtledown/frame.html" id="comic-frame"></iframe>

</div>
```
</details>

<details>
<summary>1350</summary>

```
<div id="comic">

<script src="/s/b66ed7.js"></script>
<script src="/1350/bernardo.min.js"></script>
<script type="text/javascript">
Bernardo.comic({el: $('#comic')})
</script>
</div>
```
</details>

Interestingly, this is different in the most recent interactive comic (April Fools 2021) 
So it works fine
<details>
<summary>2445</summary>

```
<div id="comic">
<img src="//imgs.xkcd.com/comics/checkbox.gif" title="Check check check ... chhecck chhecck chhecck ... check check check" alt="Checkbox" srcset="//imgs.xkcd.com/comics/checkbox_2x.gif 2x" style="image-orientation:none" >
<script src="comic.js"></script>
<script></script>
</div>
```
</details>
