### ISSUE TITLE
[Bug] Mangalib: HTTP 403

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#6376]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10 (MIUI 12)

## Source information
- Name: Mangalib
- Extension version: 1.2.34

## Steps to reproduce
1. Open Mangalib in Browse tab

### Expected behavior
List of mangas is displayed

### Actual behavior
HTTP error 403 is displayed
![Screenshot_2021-03-31-23-14-41-333_eu kanade tachiyomi](https://user-images.githubusercontent.com/34866475/113205797-59c86180-9277-11eb-8b45-00c9676d7a44.jpg)

## Other details
Works fine in the WebView

**Comment by VlasovRoman** [comment]
Manga from mangalib don't update too.

**Comment by e-shl** [comment]
It cloudflare blocked

**Comment by LilitMoon** [comment]
Это будет на время или же теперь MangaLib полностью заблокирован?

**Comment by LilitMoon** [comment]
> It cloudflare blocked

How much will it be blocked?

**Comment by e-shl** [comment]
> How much will it be blocked?

Until mangalib gives up blocking bots or someone comes up with a workaround.

**Comment by MM001-r** [comment]
When will this problem be solved?

**Comment by VlasovRoman** [comment]
> When will this problem be solved?

Nobody knows

**Comment by Sennetsu** [comment]
When asked why the application does not work, the administration of mangalub replied that their site works, and they do not care about any applications. So figure it out for yourself
![iYF__txoQQw](https://user-images.githubusercontent.com/81966326/113571817-bb921e00-961f-11eb-9a1d-5ef9ab6809f0.jpg)

**Comment by e-shl** [comment]
Обсуждение приложения(в том числе и проблемы Mangalib):
https://4pda.ru/forum/index.php?showtopic=805780 Также телеграмм: @Tachiyomi_RUS

**Comment by e-shl** [comment]
mangalib removed bot blocking
