### ISSUE TITLE
[Source Request] <genkan>

### ISSUE THREAD

**Issue by abdallahbassim** [tachiyomiorg/tachiyomi-extensions#6377]
- Name: genkan
- Link: https://genkan.io
- Language(s): English

## Other details
It is trying to be next MangaDex

**Comment by Samk19** [comment]
Is this source added ? Cannot find it in spreadsheets of Tachiyomi extensions

**Comment by CarlosEsco** [comment]
The ticket is open, which means it's not

**Comment by Samk19** [comment]
Any update on this source ?

**Comment by CrepeTF** [comment]
Sources will be developed when someone is willing to make it, there's no schedule or of the sort.

**Comment by Samk19** [comment]
Oh ok thankyou for the info

Its a good one specially as an alternative to mangadex 

As we have no idea when will mangadex v5 be released 😭
