### ISSUE TITLE
[Bug] <Leviatan Scans>: <Unable to resolve host>

### ISSUE THREAD

**Issue by Archund** [tachiyomiorg/tachiyomi-extensions#6380]
---

## Device information
- Tachiyomi version: J2K 1.0.11
- Android version: 8.1.0

## Source information
- Name: Leviatan Scans
- Extension version: 1.2.5

## Steps to reproduce
1. Attempt to open a chapter

### Expected behavior
Chapter loads

### Actual behavior
Toast appears saying 'Unable to resolve host "leviatanscans.comhttps": No address associated with hostname'

## Other details
Works fine in Webview. New chapter updates are shown. Only opening a chapter shows problems. I have tried several mangas, both old and new chapters fail to load with the same toast.

Sample
![Sample Manga](https://cdn.discordapp.com/attachments/827109081407160320/827109217781022740/Screenshot_20210401-030630_TachiyomiJ2K.png)
Toast
![Toast](https://cdn.discordapp.com/attachments/827109081407160320/827109217491877888/Screenshot_20210401-030638_TachiyomiJ2K.png)
Working Webview
![Working Webview](https://cdn.discordapp.com/attachments/827109081407160320/827109217189363732/Screenshot_20210401-030708_TachiyomiJ2K.png)

**Comment by Riztard** [comment]
work for me, have you tried troubleshooting?

**Comment by Archund** [comment]
I had tried everything in troubleshooting. Decided to also try uninstalling and reinstalling the extension and that fixed it. 
In hindsight, I remember this happened with another extension, but since it got an update soon after I forgot about it. I think it might just be my phone :/

This probably isn't the place, but uninstalling and reinstalling extensions should be added to troubleshooting
