### ISSUE TITLE
[Bug] Dynasty-Chapters: HTTP Error 500

### ISSUE THREAD

**Issue by Last-Stardust** [tachiyomiorg/tachiyomi-extensions#6383]
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: Android 10 (MIUI 12.0.3)

## Source information
- Name: Dynasty-Chapters (Dynasty)
- Extension version: 1.2.12

## Steps to reproduce
1. Install 'Dynasty' Extension
2. Launch 'Dynasty-Chapters' from Sources

### Expected behavior
Page would load Chapter library.

### Actual behavior
Page displays HTTP Error 500: Check the website in WebView.

## Other details
The issue is affects only Dynasty-Chapters. Dynasty-Series/Issues/Doujins/Anthologies all load fine and are not affected.
The page also loads properly in WebView. 
Manga already added to library under the Dynasty-Chapters extension also load properly.

**Comment by powermad80** [comment]
Appears to be problem with the source itself, Dynasty-Scans admin acknowledges that the search function is broken site-wide. This explains why webview and other aspects of their plugins are still working.

**Comment by MemoriVR** [comment]
Should be solved already. Please check it and close the issue
