### ISSUE TITLE
(TMO) la pagina se queda congelada mientras carga

### ISSUE THREAD

**Issue by BlackLewis-cyber** [tachiyomiorg/tachiyomi-extensions#6392]
## Device information
- Tachiyomi version: 0.10.9.apk
- Android version: android 10

## Source information
- Name: TMO
- Extension version: 1.2.33

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened: que el manga no se quede cargando luego de haberse cargado las primeras 3 o 4 paginas

### Actual behavior
Describe what happens instead: Ocurre que abro la aplicación y funciona a la perfección, intento abrir un manga de cualquier otra fuente que no sea TMO y estas corren sin problemas.
es solo que cuando abro uno de la fuente TMO, estos cargan tan solo las primeras 3 paginas y luego se quedan cargando, independientemente de que la calidad del internet sea bastante buena. Además de que se puede quedar horas cargando y no lo hace.

## Other details: al principio pensaba que eran problemas de internet, el cual no era el caso, ya que, cambie a los diversos routers de mi casa y hasta intente usar mis datos moviles. también la desinstale para probar, borre el cache y la cookies un par de veces en menos de 4 días, cosa que tampoco funciono.
finalmente contacte con el grupo de soporte de discord por ayuda, en donde me dijeron que creara este informe para obtener una ayuda aun más profundizada

**Comment by vetleledaal** [comment]
I'm unable to reproduce the issue as described, I immediately get the first 10 pages and the remaining pages trickle in as per the default rate limits. Rate limits were changed in #6114 , which might have fixed this issue.

You can also change the rate limit under the extension settings
![a](https://user-images.githubusercontent.com/13540478/147884839-4e415543-0f80-435d-9b24-751c64bcbeb0.png)

**Comment by vetleledaal** [comment]
Since no reproducible steps have been provided, I'm closing this issue.
