### ISSUE TITLE
[Bug] webtoons.com: nothing being loaded from extension

### ISSUE THREAD

**Issue by tiktak24** [tachiyomiorg/tachiyomi-extensions#6394]
## Device information
- Tachiyomi version: j2k fork 1.0.11
- Android version: 10 miui 12.0.3

## Source information
- Name: webtoons.com
- Extension version: 1.2.25

## Steps to reproduce
1. Browsing the source doesn't load anything

**Comment by CrepeTF** [comment]
On my end at least, using a VPN works. However webview still works with or without vpn

**Comment by tiktak24** [comment]
Vpning to the states worked but in UK either by VPN, data or normal WiFi it doesn't load

**Comment by CrepeTF** [comment]
VPN from UK to UK works on my end

**Comment by keinezeit8** [comment]
I tried it as well. Doesn't work without VPN and VPN to US. 
Tried clearing cookies.
Opening in webview allows to enter birthdate, but extension still doesn't work.
