### ISSUE TITLE
[Source Request] Void Scans

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#6398]
### Source website
Name: Void Scans
Link: voidscans.net
Language(s): English

### Other details

- Void Scans changed their domain from .com to .net

- they dont use lanraragi

**Comment by Seishirou101** [comment]
work in progress it seems lol 
![2560-1390-max](https://user-images.githubusercontent.com/57241064/113431729-b50b6880-93cb-11eb-9466-696142f1a67d.png)

**Comment by Riztard** [comment]
harold moment
