### ISSUE TITLE
Chapters without date not appearing in updates tab

### ISSUE THREAD

**Issue by LNP8095** [tachiyomiorg/tachiyomi-extensions#6409]
## Device information
- Tachiyomi version: J2K 1.0.11
- Android version: 10

## Source information
- Name: Bato.to
- Extension version: 1.2.5

## Steps to reproduce
Update Library or Refresh Manga

### Expected behavior
New chapters should appear in Updates Tab

### Actual behavior
New chapters don't appear

## Other details
In bato.to source chapters don't have a date of when they were added. This causes new chapters to not appear in Updates tab

**Comment by vipzzx** [comment]
for me the new chapters are appearing but the dates are missing on my batoto mangas too

**Comment by Enduserprocess** [comment]
Issue also prevelant on v0.10.09 - multiple series are not showing any date or time, which is causing them to not be listed on the updates page, but will show on the push notifications if updated. Suspect that it is a site issue?

**Comment by LNP8095** [comment]
Don't think so. Bato shows proper date of upload

**Comment by jadoff630** [comment]
for some reason the lack of dates does not keep the titles from showing up in updates (I use SY). I wonder if bato.to changed the code for their date system and that is why it no longer shows?

**Comment by vipzzx** [comment]
So in the case with SY when you sort by latest chapter they will appear on the bottom of the category but does show in update tab.  

In j2k it shows in the proper order in the library when sorted by upload date but doesn't show in the update tab. 

I don't know how it is on vanilla tachiyomi since I don't use that one.
