### ISSUE TITLE
[Bug] Flame Scans: Extension Broken

### ISSUE THREAD

**Issue by Subtilizer28** [tachiyomiorg/tachiyomi-extensions#6416]
## Device information
- Tachiyomi version: 1.0.11 J2K 
- Android version: 10

## Source information
- Name: Flame Scans
- Extension version: 1.2.4

## Steps to reproduce
1. Open the Extension and choose any manga/manhwa which is ongoing
2. You can see the chaps are uploaded twice and chaps of other series are also included in that. 

### Expected behavior
Chap should be shown once in its respective page

### Actual behavior
Chaps are being displayed twice and different series chaps are being shown in that page. 

## Other details
I did check in WebView and the website seems perfect.
U can see :- 
Eg. Kill the villainess manhwa in the extension

**Comment by Riztard** [comment]
i think it only happen to j2k 🤔

<table>
<tr>
	<td>J2K
	<td>Stable
	<td>Preview
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/828519762035343400/Screenshot_2021-04-05-13-40-54-890_eu.kanade.tachiyomi.j2k.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/828519762404311040/Screenshot_2021-04-05-13-40-50-548_eu.kanade.tachiyomi.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/828519761591140393/Screenshot_2021-04-05-13-41-12-447_eu.kanade.tachiyomi.debug.jpg">
</table>

**Comment by Riztard** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues/714
