### ISSUE TITLE
[Bug] Webtoons: Cannot fetch new chapters 

### ISSUE THREAD

**Issue by mlilyd** [tachiyomiorg/tachiyomi-extensions#6417]
Refreshing the library does not pull new chapters. I knew that some series I follow updates on Sunday, but I didn't get any update notification from Tachiyomi. I tried manually refreshing my library for new chapters, as well as manually refreshing just that one series, but no new chapters. I checked Webtoons's website, and indeed a new chapter was uploaded, so the problem must be with Tachiyomi.

This applies for both English and Indonesian source, but I haven't checked for other languages.

**Comment by mlilyd** [comment]
Ah, it seems that the entire extension is broken? I can't browse Webtoons through Tachiyomo either

**Comment by curche** [comment]
possible duplicate of #6394

**Comment by EstebanOD** [comment]
Same problem with English and French extension, the chapters can't be reached and the images of each WEBTOON disappeared and can't be downloaded back.

**Comment by keinezeit8** [comment]
there was an update to the extension.
does it still happen?

**Comment by EstebanOD** [comment]
Hello, thank you for the answer.
Fortunately no, it doesn't, I updated my library, the covers came back and
it updated the WebToons' chapters.
