### ISSUE TITLE
[Bug] PMSCans: downloading manga giving fake chapter

### ISSUE THREAD

**Issue by D47290C1** [tachiyomiorg/tachiyomi-extensions#6420]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: PMScans
- Extension version: 1.2.2

## Steps to reproduce
1. Download Leveling Up, by Only Eating!
2. Read

[downloaded by tachi](https://cdn.discordapp.com/attachments/752382408292040825/828479714246262834/Screenshot_2021-04-05-11-02-20-318_eu.kanade.tachiyomi.jpg)
[from the web](https://cdn.discordapp.com/attachments/752382408292040825/828482377319710720/Screenshot_2021-04-05-11-13-01-814_eu.kanade.tachiyomi.jpg)

**Comment by codingotaku** [comment]
https://reader.pmscans.com seems to have the correct chapters.

**Comment by Riztard** [comment]
> [reader.pmscans.com](https://reader.pmscans.com) seems to have the correct chapters.

is that their new website or what? 
if not, will make new ext for that one

**Comment by AeonLucid** [comment]
@Riztard your PR fixed the issue for chapter 57, the one mentioned in this issue. However in the next chapter 58 the resolution is very low for the pages after the first one. On the website it appears normal.

**Comment by Riztard** [comment]
> @Riztard your PR fixed the issue for chapter 57, the one mentioned in this issue. However in the next chapter 58 the resolution is very low for the pages after the first one. On the website it appears normal.

make new issue
