### ISSUE TITLE
[Bug] Mangalib.me Error 403

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi-extensions#6428]
Mangalib hasn't been working for more than 6 days! Are you going to decide?
Device information
Tachiyomi version: 0.10.9
Android version: 9
Device: honor 9 lite
Steps to reproduce
Just update the manga list
Expected behavior
Long-awaited manga update

Actual behavior
No update and IS REPORTED 403

Other details

**Comment by Seishirou101** [comment]
duplicate of #6376
