### ISSUE TITLE
[Feature Request] Mangahasu, add Type as genre tag

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi-extensions#6440]
similar to #6332 , please add Type as genre tag in manga description, and if possible in filter. Solo leveling is a manhwa on Mangahasu  website but it not show as such on tachiyomi

![screenshot_20210406-050544_sam](https://user-images.githubusercontent.com/81538887/113687079-f46cda00-9695-11eb-81c2-5e17d66d019e.jpg)

**Comment by OncePunchedMan** [comment]
There is a filter for type already
![Screenshot_20210406_235012](https://user-images.githubusercontent.com/64155117/113782650-d7d2af80-9732-11eb-91af-01b3e13dba45.png)
