### ISSUE TITLE
[Bug] <LireScan>: <HTTP 404 everytime>

### ISSUE THREAD

**Issue by Ghrydon** [tachiyomiorg/tachiyomi-extensions#6445]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 8.1.0

## Source information
- Name: Lirescan
- Extension version: 1.2.1

## Steps to reproduce
1. Go to Browse
2. Under "Source" search for "LireScan" and select it

### Expected behavior
When following the previous steps, a list of manga should appear instead of the error message

### Actual behavior
The following message appear when you follow the previous step
![image](https://user-images.githubusercontent.com/82056623/113765982-3b51e280-971d-11eb-8a2d-efef484cae89.png)

## Other details
The following actions have been carried out however the phenomenon still occurs:
- Clear Cache
- Clear Cookie
- Clear Database
- DNS over HTTPS

When using the "Web view" on the source, the website is displayed correctly
![image](https://user-images.githubusercontent.com/82056623/113766630-ee224080-971d-11eb-9ffb-969d8654c5e8.png)

**Comment by CrepeTF** [comment]
Closing in favour of #7366 due to more info
