### ISSUE TITLE
[Source Request] Tonari

### ISSUE THREAD

**Issue by ric0369** [tachiyomiorg/tachiyomi-extensions#6448]
## Source website
- Name: Tonari
- Link: https://tonari.tk/
- Language(s): English (EN)

**Comment by curche** [comment]
FYI: The site uses [Mango](https://github.com/hkalexling/Mango) which already has an extension
However, it doesn't really help since the ext requires a username and password

**Comment by curche** [comment]
Update:
the website can now be opened using Mango extension with the following extension parameters -
|Parameter | Value |
|--|--|
| Address | https://tonari.tk |
| Username | default |
| Password | default |

note that while the extension loads the website fine, not all manga work properly (parse error in webview, chapter sort error etc)
nonetheless, this particular request can be closed.
