### ISSUE TITLE
[Source Request] <dbsmanga>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#6449]
## Source website
- Name: dbsmanga
- Link: https://ww6.dbsmanga.com/
- Language(s): English

**Comment by FireNation323** [comment]
I have like 7 more of these readmanga websites can I just put the links here or do I have to make a request for each one of them?

**Comment by CarlosEsco** [comment]
Just put them all here.
@jopejoe1  if you get time can you add them all after @FireNation323  lists them

**Comment by FireNation323** [comment]
> Just put them all here.
> @jopejoe1  if you get time can you add them all after @FireNation323  lists them

https://ww2.readkingdom.com/
https://ww3.readdrstone.com/
https://readberserk.com/
https://ww7.readnaruto.com/
https://ww1.readvinlandsaga.com/
https://ww8.readonepiece.com/
https://ww6.readhaikyuu.com/
https://ww4.readfairytail.com/manga/edens-zero/

**Comment by jopejoe1** [comment]
> Just put them all here.
> @jopejoe1 if you get time can you add them all after @FireNation323 lists them

Yeah, sure gone add them when I have time for it.
