### ISSUE TITLE
[Feature Request] Mangasee: Change search method as it currently does not work.

### ISSUE THREAD

**Issue by Jirb** [tachiyomiorg/tachiyomi-extensions#6457]
I was unable to search in Mangasee so I opened the webapp and found that their quick search feature does not seem to work at the moment which led me to the assumption that tachiyomi uses that feature for it's search function.

Their detailed search feature, which you can reach on their webpage by clicking the magnifying glass icon near the top, however does seem to work so I would like to suggest changing it so tachiyomi uses "title" portion of their detailed search.

**Comment by Seishirou101** [comment]
can't reproduce your issue, the search works inside the app and also on their website. Try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis)
![1543-1259-max](https://user-images.githubusercontent.com/57241064/113863062-b9070400-9798-11eb-94d6-09e1358b5a2f.png)

**Comment by Jirb** [comment]
It works for me as well. Must have been a temporary issue on mangasee and they fixed it.
