### ISSUE TITLE
[Bug] <Mangaworld>: <Latest: only new added>

### ISSUE THREAD

**Issue by Hazyfade** [tachiyomiorg/tachiyomi-extensions#6483]
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: 9

## Source information
- Name: Mangaworld
- Extension version: 1.2.3

## Steps to reproduce
1. Browse
2. Mangaworld latest

### Expected behavior
There should appear the latest updates titles

### Actual behavior
Instead appear only the latest added titles

## Other details
If you go on WebView mode, you can see on the homepage the latest updated manga, while on Tachiyomi only the new added titles

**Comment by as280093** [comment]
request close
as it just Domain Change requested in #6534
