### ISSUE TITLE
[Bug] MangaSee: Cannot load download manga from sdcard

### ISSUE THREAD

**Issue by CaptainHalflife** [tachiyomiorg/tachiyomi-extensions#6485]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 8.1.0

## Source information
- Name: MangaSee
- Extension version: 1.2.22

## Steps to reproduce
1. Set download location to sdcard.
2. Download a chapter.
3. Open the chapter.

### Expected behavior
The chapter open and load correctly.

### Actual behavior
Tachiyomi behave as if the chapter is not downloaded but show it as downloaded.

## Other details
After downloading several chapters i saw that in my file manager.
![Screenshot_20210409-202905_ES File Explorer Pro](https://user-images.githubusercontent.com/65003109/114214906-fb396c80-9975-11eb-9b1b-bb0cd42e2047.jpg)
Each folders contain only 1 chapter and after some chapters are downloaded the next downloads fail.

This does not occur when download location is set to internal.

It was working fine before the recent updates i don't know which one exactly.

**Comment by arkon** [comment]
You'll need to rename the first one (without the suffixed number) to have the proper capitalization. If you're having issues doing that, rename it to something else first. You can then copy the other folders' contents into it.

**Comment by CaptainHalflife** [comment]
I see thx.
