### ISSUE TITLE
[Bug] Mangas Origines: Missing status(ongoing/completed...)

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#6492]
## Device information
- Tachiyomi version: TachiJ2K 1.0.11
- Android version: 10

## Source information
- Name: Mangas Origines
- Extension version: 1.2.3

## Steps to reproduce
1. Browse Mangas Origines
2. Select a random manga

### Expected behavior
Status(ongoing/completed...) should be displayed

### Actual behavior
Missing status

## Other details
![Mangas Origines_Missing status.jpg](https://user-images.githubusercontent.com/56766778/114269540-646dbe00-9a10-11eb-94c3-c179b3131ba2.jpg)
![Screenshot_20210410_173939_edit_38884866961253.jpg](https://user-images.githubusercontent.com/56766778/114273719-eadfcb00-9a23-11eb-93d4-fc0cb2d936af.jpg)

**Comment by Mitia99** [comment]
@as280093 An icon will be good when it will be fixed :))

**Comment by as280093** [comment]
@Mitia99  ICON 
->[CLICK ME](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6289976/Mangas.Orgines.ICON.zip)

**Comment by papjul** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt#L353-L354

Easy fix if someone wants to do it:
* add "En cours" to ONGOING
* add "Terminé" to COMPLETED
