### ISSUE TITLE
[Source Request] <Read Manga>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#6499]
## Source website
- Name: blackclovermanga
              readheroacademia
              readonepunchman
              onepiecechapters
- Link: https://w1.blackclovermanga2.com/
           https://w23.readheroacademia.com/
           https://w17.readonepunchman.net/
           https://onepiecechapters.com/
         
         
- Language(s): English

**Comment by arkon** [comment]
Whatever happened to our policy of not accepting sites that are just "aggregator" sites of just 1 series?

**Comment by CrepeTF** [comment]
I concur

**Comment by CarlosEsco** [comment]
These are a multisrc which is why I was letting them get added

**Comment by Umairuem** [comment]
https://onepiecechapters.com/ already has its extension as "TCB Scans".

**Comment by FireNation323** [comment]
> https://onepiecechapters.com/ already has its extension as "TCB Scans". 

Oh

**Comment by FireNation323** [comment]
> https://onepiecechapters.com/ already has its extension as "TCB Scans". 

Yes, but tcb scans puts out the next chapter before it's actually out and says bookmark us and the chapter becomes cached and you don't get a notification for when the actual chapter releases, so I thought this would be better

**Comment by jopejoe1** [comment]
All of them are already extensions in the mangamainac multisrc. 
 #6368
