### ISSUE TITLE
[not working] nhentai: nhentai is not working in Russia

### ISSUE THREAD

**Issue by SielPhantomhaiv** [tachiyomiorg/tachiyomi-extensions#6501]
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: 10

## Source information
- Name: NHentai
- Extension version: 1.2.28

## Steps to reproduce
1. (If you not in Russia) Use VPN
2. Open manga in this extension

### Expected behavior
Normal opening this manga site

### Actual behavior
Error "SSL handshake aborted...Connection reset by peer"

## Other details
In Russia, "nhentai.net" is not working. The only working domain - "nhentai.to"

**Comment by CrepeTF** [comment]
Try using a VPN?

**Comment by SielPhantomhaiv** [comment]
Yes, it's working with VPN, but I want to use this extension without VPN

**Comment by nobara88** [comment]
> Yes, it's working with VPN, but I want to use this extension without VPN

Try DNS over HTTPS. More > setting > advance >  DNS over  HTTPS (Cloudflare) 
Restart the app.

**Comment by SielPhantomhaiv** [comment]
It is not working

**Comment by CarlosEsco** [comment]
Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

The above also holds for sites blocked in countries
