### ISSUE TITLE
[Bug]  Isekaiscans: Recently updated manga do not show at the top of the list. 

### ISSUE THREAD

**Issue by fightmesun** [tachiyomiorg/tachiyomi-extensions#6506]
## Device information
- Tachiyomi version: 1.0.11
- Android version: 11

## Source information
- Name: Isekaiscans 
- Extension version: 1.2.4

## Steps to reproduce
1. Select manga to be sorted by the latest chapter update

### Expected behavior
Mangas that have recently been updated should show up at the top of the list/grid

### Actual behavior
Mangas are ordered in a bizzare manner where 9 or so mangas rotate order. Selecting the first manga and refresh it's page will cause it's last chapter upload time to change to "0 minutes ago"

### Other details
Many of the updated mangas have pages that are out of order but this issues appears on the actual site as well so I suspect it has more to doing with the uploader then the Extension

**Comment by Seishirou101** [comment]
If the issue appears on the actual site then there is nothing to be done since we're showing you exactly what the website shows... If the issue happens again and it doesn't match the website you can open a new issue
