### ISSUE TITLE
Mangalife and mangasee previously download manga not displaying 

### ISSUE THREAD

**Issue by oge2k** [tachiyomiorg/tachiyomi-extensions#6509]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 7
* Device: Vernee thor E

## Source information
* Source name: mangalife and mangasee
* Source extension version: 1.2.18 and 1.2.18

## Issue/Request
Update of extension causes downloaded manga while being displayed on the download badge to not open when trying to read the download manga

## Other Description 
The extension download folder is changed to MangaLife (EN)  and MangaSee (EN) by the support i got from discord

And the previous version of them both worked fine so why do working parts get changed to manke them not work properly

**Comment by CarlosEsco** [comment]
You already have the solution to your problem from discord.
