### ISSUE TITLE
[Bug] MangaSee: Chapter image blurry, but when checking the website it's clean

### ISSUE THREAD

**Issue by Pentillum** [tachiyomiorg/tachiyomi-extensions#6512]
## Device information
- Tachiyomi version: Preview r3250
- Android version: 9

## Source information
- Name: MangaSee
- Extension version: 1.2.22

## Steps to reproduce
1. Open manga (Leveling up, by Only Eating!)
2. Select chapter 58 (latestchapter as of writing)
3. Compare to website version

### Expected behavior
Images should be clean and readable

### Actual behavior
Images are very blurry, and text can't be read

## Other details
Images attached

Tachi screen shot
![Screenshot_20210412-191047_Tachiyomi](https://user-images.githubusercontent.com/59666465/114390687-28318d80-9bc9-11eb-95d8-1cb54f5f2bb8.jpg)

Official website screen shot
![Screenshot_20210412-194236_Brave](https://user-images.githubusercontent.com/59666465/114390185-8316b500-9bc8-11eb-90f6-59faec208ffe.jpg)

**Comment by CrepeTF** [comment]
Issue is likely to do with PMScans website messing with aggregators.

**Comment by Riztard** [comment]
i think its because the image is a gif

**Comment by CrepeTF** [comment]
> i think its because the image is a gif

Actually they're using both a mix of gif and PNG, and the pngs are still pixelated

**Comment by CrepeTF** [comment]
Or not, the pngs are GIFs too
