### ISSUE TITLE
[Bug] <ReadComicOnline>: <Search not working on app>

### ISSUE THREAD

**Issue by Tarant00** [tachiyomiorg/tachiyomi-extensions#6515]
## Device information
- Tachiyomi version: Stable 0.19.9
- Android version: T380DXU4CUA2/T380XAR4CUA2/

## Source information
- Name: ReadComicOnline
- Extension version: ReadComicOnline

## Steps to reproduce
1. First Step
Try to search anything in this extension
2. Second Step
Fail

### Expected behavior
Search engine on app working perfectly.

### Actual behavior
Search engone not working on app, even though it works on webview and in other sources.

## Other details
I can read the comics in this source and use the webview just fine, but the search engine in the app isn't working.

**Comment by jfcaraujo** [comment]
Like I said in the other issue, I think I found the reason
The domain changed from readcomiconline.to to .li (redirects if you try to use the .to)
Search probably doesn't work because if you try to use the .to it's probably resetting something in the redirect

**Comment by Tarant00** [comment]
> Like I said in the other issue, I think I found the reason
> The domain changed from readcomiconline.to to .li (redirects if you try to use the .to)
> Search probably doesn't work because if you try to use the .to it's probably resetting something in the redirect

Entendi, de boa então. Muito obrigado!

**Comment by jfcaraujo** [comment]
Fixed this in the pull request, it was just changing the domain
