### ISSUE TITLE
[Bug] ReadComicOnline: Search Not working

### ISSUE THREAD

**Issue by jfcaraujo** [tachiyomiorg/tachiyomi-extensions#6516]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 9

## Source information
- Name: ReadComicOnline
- Extension version: 1.2.9

## Steps to reproduce
1. Open Source
2. Search a title

### Expected behavior
Search should show results

### Actual behavior
No results found 

## Other details
On webview works, top mangas/home page and latest page works, reading/updating added mangas works, tried all the troubleshooting (Clear Cache, Clear Cookies, Clear Database, DNS over HTTPS) and still not working

**Comment by jfcaraujo** [comment]
I think I found the reason
The domain changed from readcomiconline.to to .li
search doesn't work because if you try to use the .to it's sending you back to main page

**Comment by CrepeTF** [comment]
#6515
