### ISSUE TITLE
[Bug] PMScans: resolution is very low(or GIF on text) for the pages after the credit page

### ISSUE THREAD

**Issue by D47290C1** [tachiyomiorg/tachiyomi-extensions#6523]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 10

## Source information
- Name: PMScans
- Extension version: 1.2.3

## Steps to reproduce
1. Download Leveling Up, by Only Eating!
2. Read

(already tried refresh library manga covers)

[sample ](https://cdn.discordapp.com/attachments/349436576037732355/831147043677405205/Screenshot_20210412_204103.jpg)

**Comment by D47290C1** [comment]
looks like only happend to lattest chapter. in time frame. lattest chapter of good of cooking (2021-04-08 on tachi)  if you download now look good.

**Comment by CrepeTF** [comment]
Links to the short discussion in #6512

**Comment by CrepeTF** [comment]
They're doing some weird thing where the GIFs constantly go back and forth between 2 different frames really quickly.

**Comment by ravel10** [comment]
It seems that on browser, there is no loop and only the 2nd frame is displayed (the correct one).

**Comment by D47290C1** [comment]
now its only downloading the credit page
