### ISSUE TITLE
[Bug] <Myreadingmanga>: <Myreadingmanga extension isn't working and says error 403 while it was working like a month ago>

### ISSUE THREAD

**Issue by Zach-Kid** [tachiyomiorg/tachiyomi-extensions#6528]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 11

### Expected behavior
To work fine as the other extensions and shows Mangas. ### ### 

### Actual behavior
Doesn't show any Manga of any sorts and just says error 403

**Comment by OncePunchedMan** [comment]
they protected the site. open the website. let cloudflare pass and then go back to app, refresh.
this is the solution

**Comment by psredijk** [comment]
> they protected the site. open the website. let cloudflare pass and then go back to app, refresh.
> this is the solution

i've tried that but it stil doesnt work, it keeps closing the app itself
