### ISSUE TITLE
[Meta] <Add another sorting for chapters that are not downloaded>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#6533]
##  Why/Project's Benefit/Existing Problem
Explain why this should be added
Some sources have missing chapters so when I download the chapters that are available I have to manually scroll through hundreds of chapters to see the chapters that are not downloaded so I can download them on another another source 

## Other Details
Just makes life easier

**Comment by arkon** [comment]
I assume you're the guy from Discord. This belongs in https://github.com/Jays2Kings/tachiyomiJ2K

**Comment by FireNation323** [comment]
> I assume you're the guy from Discord. This belongs in https://github.com/Jays2Kings/tachiyomiJ2K

Oh mb
