### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by giuliobz** [tachiyomiorg/tachiyomi-extensions#6546]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 10

## Source information
- Name: mangaword (italian)
- Extension version: mangaword: 1.2.4

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Read manga and open the mangaword library

### Actual behavior
Can't open manga chapter and mangaword library

# Other details
When I try to update manga chapter there Is this message:

'Attempt ti invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference'

This appen on a Mangaword (ita extension) manga. When i open mangaword i can't see the catalog, but if i open the web version It works.

I update the extension and the application.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6534
