### ISSUE TITLE
[Bug] MangaYabu!: "No results found"

### ISSUE THREAD

**Issue by Sam-Oak** [tachiyomiorg/tachiyomi-extensions#6550]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 9

## Source information
- Name: MangaYabu!
- Extension version: 1.2.6

## Steps to reproduce
1. Go to Browse
2. click on "MangaYabu!" source

### Expected behavior
Show all manga from this source.

### Actual behavior
Shows a message saying "No results found".

**Comment by alessandrojean** [comment]
Should be fixed by #6549.
