### ISSUE TITLE
[Bug] <Mangaworld>

### ISSUE THREAD

**Issue by edofl3da** [tachiyomiorg/tachiyomi-extensions#6554]
## Xiaomi Mi A1
- Tachiyomi version: latest
- Android version: latest

## Source information
- Name: Mangaworld
- Extension version: latest

## Steps to reproduce
1. Install extension Mangaworld
2. Open extension and read a manga

### Expected behavior
You can read manga

### Actual behavior
There are no chapters and there are only 10 manga

**Comment by as280093** [comment]
request to close 
#6534
