### ISSUE TITLE
[Bug] mangaworld: no update

### ISSUE THREAD

**Issue by xr4z13l** [tachiyomiorg/tachiyomi-extensions#6555]
## Device information
- Tachiyomi version: latest
- Android version: 9

## Source information
- Name: mangaworld
- Extension version: latest

## Steps to reproduce
1. First Step
when I update the manga I get a Java error and then the warning of no new chapter

2. Second Step
opening the webview always opens the manga world home page and not the manga page

In the telegram group they advised that they had changed domain from .com to .io

The Java error:
![Screenshot_20210414-205310](https://user-images.githubusercontent.com/20503894/114821241-8b394500-9dc0-11eb-9a7a-9b2508b9ebe6.jpg)

**Comment by as280093** [comment]
Request to close 
#6534
