### ISSUE TITLE
crash <webtoon>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi-extensions#6556]
when reading a manhwa with a longspread and a reading option with webtoons the app crashes and your phone freeze for a few second tried opening that chapter again but it still crashes but if you just use the default reading option it doesnt crash but makes the manhwa blured and sometimes unreadable

**Comment by CrepeTF** [comment]
Sounds like [this issue](https://github.com/tachiyomiorg/tachiyomi/issues/1908) on the app repo so I'll be closing this in favour of that.
