### ISSUE TITLE
Komik Moe

### ISSUE THREAD

**Issue by Joker2798** [tachiyomiorg/tachiyomi-extensions#6558]
---

## Source website
- Name : Komik Moe
- Link : https://komikmoe.my.id/
- Language : Indonesia

## Other details
I have searched for the extension but can't find it.
Please add the extension with the source above
Upload Manga, Manhwa, Manhua, Doujin

**Comment by alekc** [comment]
Domain name is not reachable. @alessandrojean close?

**Comment by alessandrojean** [comment]
@alekc No need to ping me every message for closing the issues, we have a channel on Discord where we can see all comments done on the repositories, so if I didn't see your comment, someone else will see and close the issue :+1:
