### ISSUE TITLE
VoyceMe

### ISSUE THREAD

**Issue by xampl3** [tachiyomiorg/tachiyomi-extensions#6560]
## Source website
- Name: VoyceMe
- Link: https://voyce.me/
- Language(s): English

## Other details
Uploads original Novels/Manga/Comics/original stories

**Comment by Bappamaiti** [comment]
Will it going to be added soon?

**Comment by alessandrojean** [comment]
Don't ask for ETA. It will get added when someone have time and wants to work on it.

**Comment by Slowxzy** [comment]
I was about to ask for it

**Comment by AlexMiniReal** [comment]
Me too, still waiting for someone with a good heart to code the extension...

**Comment by alessandrojean** [comment]
I am currently working on it, but no ETA.
