### ISSUE TITLE
[SourceRequest] HastaTeam: Italian source for manga

### ISSUE THREAD

**Issue by edofl3da** [tachiyomiorg/tachiyomi-extensions#6561]
## Source website
- Name: HastaTeam
- Link: https://hastateam.com/forum/index.php
- Language(s): Italian
Please add this source because in One of the best for Italian readers

**Comment by jopejoe1** [comment]
FoolSlide

**Comment by LucaLKS** [comment]
They also have an online reader if it can help
https://ddt.hastareader.com/slide/directory/

**Comment by Ripper346** [comment]
Look at #3359 and https://github.com/tachiyomiorg/tachiyomi-extensions/pull/115

**Comment by Ripper346** [comment]
As this is closed I would like to remind also that we don't want to be part of the project with all our domain and subdomains, such as hastateam.com and hastareader.com. I don't know if #1179 is planned or implemented

**Comment by CrepeTF** [comment]
ye no issues, but if any of your domains get an extension just reach out on the discord or something to get it removed
