### ISSUE TITLE
[Bug] (IT) mangaworld : chapters don't show up

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#6568]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 8

## Source information
- Name: Mangaworld
- Extension version: 1.2.3

## Steps to reproduce
1.Choose and then open a random manga woth the extension

### Expected behavior
Chapters should show up without an error message

### Actual behavior
Chapters don't show up

## Other details
![Screenshot_20210415-201107](https://user-images.githubusercontent.com/75091899/114918702-ad19e280-9e27-11eb-92a7-5e3428525a52.jpg)

**Comment by curche** [comment]
known issue
duplicate #6534
