### ISSUE TITLE
[Bug] (IT) mangaworld: manga cover preview isn't downloader

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#6574]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 8

## Source information
- Name: Mangaworld
- Extension version: 1.2.4

## Steps to reproduce
1. Search a random manga

### Expected behavior
the manga should download the cover preview

### Actual behavior
the manga don't download the cover preview unless i tap on the specific manga (only here the app will download the cover of the manga)

## Other details
![Screenshot_20210416-090205](https://user-images.githubusercontent.com/75091899/114985374-0539fe80-9e93-11eb-961c-ff0a2ec52142.jpg)

**Comment by OncePunchedMan** [comment]
they do for me. try the troubleshoot guide: https://tachiyomi.org/help/guides/troubleshooting/#diagnosis
