### ISSUE TITLE
[Source Request] <manga>

### ISSUE THREAD

**Issue by hanxin1997** [tachiyomiorg/tachiyomi-extensions#6578]
## Source website
- Name: 熟练漫画
- Link: https://www.manga2020.com/
- Language(s): Traditional Chinese

## Other details
The structure can refer to the copymanga  in the Chinese source

**Comment by hotmanga** [comment]
这个叫 熱辣漫畫，不叫 熟练漫画 。该站点皆为版权合作的付费漫画，希望 Tachiyomi 不要进行任何程度的盗链行为。谢谢。

**Comment by zhongfly** [comment]
> 这个叫 熱辣漫畫，不叫 熟练漫画 。该站点皆为版权合作的付费漫画，希望 Tachiyomi 不要进行任何程度的盗链行为。谢谢。

这是你和BiliBili版权合作的收费漫画吗？https://www.manga2020.com/comic/nizaonanlema/chapter/64d0bb5a-1863-11ec-b710-024352452ce0
