### ISSUE TITLE
[Bug] <MyReadingManga>: <The extension hasn't been working about 2 weeks ago already>

### ISSUE THREAD

**Issue by psredijk** [tachiyomiorg/tachiyomi-extensions#6581]
--

## Device information
- Tachiyomi version: 0.10.10
- Android version: 5.1

## Source information
- Name: MyReadingManga
- Extension version: 1.2.41

## Steps to reproduce
1. Open the source
2. Open the webview

### Expected behavior
Open the source and work fine, showing mangas

### Actual behavior
When I open the source it just says 'HTTP error 403' 

## Other details
I tried solving the cloudflare a few times but when I complete the capchta the app suddenly close itself

**Comment by CVIUS** [comment]
can be closed since #6690 has better information
