### ISSUE TITLE
[Bug] xCaliBR Scans: Not working properly

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#6582]
## Device information

-App version: 0.10.10 (standard, 0dc4862, 57)
-Android version: 11 (SDK 30)

## Source information
- Name: xCaliBR Scans
- Extension version: v1.2.5

## Steps to reproduce
1. Open any title (tested with My Disciples Are All Immortals)
2. Select a chapter and open 
3. Chapters keeps on loading
4. Also try to download the chapter using download button
5. Download doesn't start

-Network was working fine as i am able to read and download titles from other sources
-Also webview of xcalibrscan is working fine

### Expected behavior
Able to view the chapter images
And chapters are downloading 

### Actual behavior
Chapters keeps on loading forever

Also download doesn't start 

![Screenshot_20210417-062237_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/115097004-5dc9d400-9f45-11eb-9e28-027c2740e40a.jpg)
![Screenshot_20210417-061836_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/115096878-c82e4480-9f44-11eb-808e-0c96fb981820.jpg)

**Comment by FaTe-code** [comment]
I'm also having this prob.

**Comment by Riztard** [comment]
work for me, try troubleshoot

**Comment by Samk19** [comment]
Still not working 
Tried troubleshoot,  reinstall source, also tried on the other version (j2k) same issue 

No vpn use 
Tried with cloudfare option on and off
Tested my network its working fine

**Comment by Riztard** [comment]
nvm maybe its a cache(dont remember read this manga) or something
same for me
