### ISSUE TITLE
[Bug] MangaOwl: Missing Blue Filter Button

### ISSUE THREAD

**Issue by nbhmhdysf** [tachiyomiorg/tachiyomi-extensions#6590]
## Device information
- Tachiyomi version: 10.10
- Android version: 11

## Source information
- Name: MangaOwl
- Extension version: English 1.2.9

## Steps to reproduce
1. First Step : On Android device accessing Tachiyomi app, I have installed MangaOwl extensions.
2. Second Step : Upon browsing the manga on MangaOwl extension, I've noticed there is no blue filter button on bottom right where it should be in other extensions.

### Expected behavior
Describe what should have happened
Other extensions have this blue filter button on the bottom right panel

### Actual behavior
Describe what happens instead
However MangaOwl seems to missing that blue filter button

## Other details
Pictures below are what exactly i meant:

1. MangaOwl without the blue filter button
![Screenshot_20210417-215857_Tachiyomi](https://user-images.githubusercontent.com/82715372/115116473-336f2980-9fcc-11eb-80f2-4ceab70d882a.jpg)

2. Other extensions with blue filter button
![Screenshot_20210417-220938_Tachiyomi](https://user-images.githubusercontent.com/82715372/115116478-3d912800-9fcc-11eb-973a-5a80859662e1.jpg)

**Comment by CVIUS** [comment]
can be closed as per #8087 
I didn't notice this because it was labeled as a bug
