### ISSUE TITLE
[Bug] Mangá Host (BR) : Doesn't update manga library

### ISSUE THREAD

**Issue by johnnylord1** [tachiyomiorg/tachiyomi-extensions#6592]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 9

## Source information
* Source name: Mangá Host
* Source extension version: 1.2.23

## Issue/Request
After the last update, the extension doesn't update manga library anymore.

## Other details
If you try to read any manga of the source, appears an error message : The site is blocking the tachiyomi. Migrate to another source if the problem persists.

**Comment by alessandrojean** [comment]
Read #6537. It's recommended to do as the error suggests and migrate the titles in your library to another source, since there's nothing that can be done on the extension side at the moment.
