### ISSUE TITLE
[Source Request]<mangallama>

### ISSUE THREAD

**Issue by abdallahbassim** [tachiyomiorg/tachiyomi-extensions#6599]
## Source website
- Name: mangallama
- Link: https://mangallama.com
- Language(s): EN

**Comment by keinezeit8** [comment]
Duplicate of #3572

Maybe that also should be closed, because back then someone asked it not to be implemented.
But I don't know if they ever followed through

**Comment by abdallahbassim** [comment]
Did he follow through is he the owner of the site if he didn't can you open it

**Comment by keinezeit8** [comment]
the original is still open
but this is a duplicate, that's why its closed

**Comment by abdallahbassim** [comment]
Ok thank u
