### ISSUE TITLE
[Meta] manhwa18 duplicate extension

### ISSUE THREAD

**Issue by keinezeit8** [tachiyomiorg/tachiyomi-extensions#6608]
##  Why/Project's Benefit/Existing Problem
Currently there exist two extensions Manhwa18 and Manhwa18.net
They access [manhwa18.com](https://manhwa18.com/) and [manhwa18.net](https://manhwa18.net/) respectively.
Both seem to provide exactly the same content. Also manhwa18.**net** has manhwa18.**com** written in the top left.

Maybe one of them should be removed.

## Other Details
manhwa.net is in _all_ while manhwa.com is in _en_

**Comment by joseph619** [comment]
Manhwa18 focuses on raws more than .net, and is also used as a backup for each other (same as Mangasee and Mangalife). Both can stay as they are.
