### ISSUE TITLE
[Bug] Mango shows last page of entry first.

### ISSUE THREAD

**Issue by Didact** [tachiyomiorg/tachiyomi-extensions#6613]
According to the  [docs](https://github.com/hkalexling/Mango/blob/8829d2e237889d0ec232a92a485b3ef4086ecaa0/src/routes/api.cr#L75) (can't find a public version of the rendered API, sorry), Mango page indices are 1-based, and asking for page 0 apparently gives you the last item in the chapter.

Should just be a quick update here to fix:
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/defa03d68d9b7b7a25140951e73df878d7fe46dc/src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt#L165

**Comment by hkalexling** [comment]
I think this can be closed as it's fixed in #7227
