### ISSUE TITLE
[Enhancement] MangaKatana: Show Alternate Names, Add Punctuation in Author(s) Field

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi-extensions#6617]
## What feature should be added to this source?
Title is pretty self-explanatory. The extension at the moment doesn't show alternate names, but accurate results still show up if searched using an alternate one. Maybe it could be displayed in the description itself, like how the Hentai2Read extension does it.

There's also no comma to separate the author and the artist in the extension, but this is not the case in the website. Just a small QoL feature. Example given below.

![Screenshot_20210419-141401](https://user-images.githubusercontent.com/28984045/115208065-d1bcd580-a119-11eb-86c8-5bfe8ac3c338.png)
![Screenshot_20210419-141431](https://user-images.githubusercontent.com/28984045/115208078-d41f2f80-a119-11eb-9cf6-354e96c27b80.png)

**Comment by FlaminSarge** [comment]
Where would you suggest alt names go? At the top/bottom of the description section?

Also, for the author list, something like #7841 will probably work here, will take a look. Slowly getting through sources that do this.

**Comment by MercerBoi** [comment]
> Where would you suggest alt names go? At the top/bottom of the description section?

Top of the description section sounds nice, and thanks getting to this issue!

**Comment by FlaminSarge** [comment]
@MercerBoi I stuck it at the bottom of the description, as a lot of other sources do the same

**Comment by MercerBoi** [comment]
> @MercerBoi I stuck it at the bottom of the description, as a lot of other sources do the same

No problem, thank you.
