### ISSUE TITLE
[Source Request] <Coolmic, manga18.info, manga.club, doujins.me>

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi-extensions#6618]
## Source website
- Name: Coolmic
- Link: https://coolmic.me/
- Language(s): English

## Other details
It's kinda hard to add this extensions since it's apps based.

## Source website
- Name: manga18.info
- Link: https://manga18.info/index.html
- Language(s): English

## Other details
It's different site with manhwa18 and manhwa18.net

## Source website
- Name: manga.club
- Link: https://www.manga.club/
- Language(s): English

## Other details
Like Kakaopage

## Source website
- Name: doujins.me
- Link: https://doujins.me/
- Language(s): English

## Other details
Common site like other site

**Comment by joseph619** [comment]
Don't make multiple requests in one post, also check which sources have been requested already.

**Comment by arkon** [comment]
Please make individual issues if applicable.

**Comment by HapyEnding** [comment]
Sorry, didnt  know that
