### ISSUE TITLE
[Bug] <Union Mangás>: <Not Found>

### ISSUE THREAD

**Issue by MarcosSouza2004** [tachiyomiorg/tachiyomi-extensions#6622]
## Device information
- Tachiyomi version: 0.10.11
- Android version: 11

## Source information
- Name: Union Mangás
- Extension version: 1.2.20

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Connect and read mangas

### Actual behavior
"Not found" 
![image](https://user-images.githubusercontent.com/76596575/115285035-ca022e80-a123-11eb-9fc1-d73c3f9157e3.png)

**Comment by alessandrojean** [comment]
I'm fixing this now.

**Comment by MarcosSouza2004** [comment]
> I'm fixing this now.

you are awesome
