### ISSUE TITLE
[Source Request] Coolmic.me

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi-extensions#6630]
## Source website
- Name: Coolmic.me
- Link: https://coolmic.me/
- Language(s): EN

## Other details
It's like mangatoon and kakaopage. You need pay to read manga.

**Comment by Riztard** [comment]
how do you read manga from this site with browser? 🤔

**Comment by HapyEnding** [comment]
> how do you read manga from this site with browser? 🤔

i have no idea, it's only from android maybe. Kinda like man manga or mangatoon.

**Comment by paulo27ms** [comment]
They have some free chapters available: https://coolmic.me/episodes/12919
Only available on mobile?

**Comment by HapyEnding** [comment]
> They have some free chapters available: https://coolmic.me/episodes/12919
> Only available on mobile?

**Comment by HapyEnding** [comment]
> They have some free chapters available: https://coolmic.me/episodes/12919
> Only available on mobile?

Only mobile
