### ISSUE TITLE
[Bug] <Rainofsnow>: <doesn't load more then 6 images >

### ISSUE THREAD

**Issue by riyan1215** [tachiyomiorg/tachiyomi-extensions#6631]
## Device information
- Tachiyomi version: tachij2k 1.0.15
- Android version: 11

## Source information
- Name: rain of snow
- Extension version: 1.2.5

## Steps to reproduce
1. First Step: open any manga 
2. Second Step: only shows 6 images

### Expected behavior
Describe what should have happened
loads all the images
### Actual behavior
Describe what happens instead
only loads 6 images

**Comment by tyme2tb** [comment]
Noticed the same issue. When I Checked webview, to see more pages you have to click a button now, so I think that may be the issue.

**Comment by Th3-822** [comment]
A tip for making it easier to fix, send a big negative number as "offset" and it will reply with all the pages
