### ISSUE TITLE
[Bug] Scantrad (fr) : HTTP error 403

### ISSUE THREAD

**Issue by bapcrespin** [tachiyomiorg/tachiyomi-extensions#6633]
## Device information
- Tachiyomi version: 0.10.11
- Android version: 11

## Source information
- Name: Scantrad
- Extension version: 1.2.16

## Steps to reproduce
1. Go to explore
2. Menu sources
3. Tap on the Scantrad source name

### Expected behavior
Have a view of the available scan in the website.

### Actual behavior
![Screenshot_20210420-122849](https://user-images.githubusercontent.com/15652297/115381770-2f155d00-a1d4-11eb-9be0-158f52c00a7b.jpg)

## Other details

**Comment by CrepeTF** [comment]
FYI Scantrad actively blocks tachiyomi

**Comment by bapcrespin** [comment]
I see so no workaround possible I guess. Thanks for the answer !

**Comment by CrepeTF** [comment]
It's not there's no workaround, but that if the extension were to be fixed, it would be a short matter of time before it would be blocked again
