### ISSUE TITLE
[Bug] <members.luscious>: <no tags and decs>

### ISSUE THREAD

**Issue by Warcrors** [tachiyomiorg/tachiyomi-extensions#6643]
---

## Device information
- TachiyomiSY version: preview r357
- Android version: 10.0

## Source information
- Name: members.luscious
- Extension version: 1.2.2

## Steps to reproduce
1. Go to any doujin on the ext

### Expected behavior
Has description and tags

### Actual behavior

No description and tags

**Comment by arkon** [comment]
I fixed #6642, so closing this

**Comment by Warcrors** [comment]
Thank you
