### ISSUE TITLE
Lily Manga not chapters not found

### ISSUE THREAD

**Issue by MinecraftEnthusiast** [tachiyomiorg/tachiyomi-extensions#6648]
## Device information
* Tachiyomi version:  0.10.9
* Android version: 10
* Device: Realme 6

## Source information
* Source name: Lily Manga
* Source extension version: 1.2.3

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
? I just downloaded lily manga and all manga's say that chapter is not found? Is Lily Manga down or is this on my device's problem or is there an issue with my app?

## Other details
Additional details and attachments.

**Comment by joseph619** [comment]
Update your app, latest version is 0.10.11

**Comment by MinecraftEnthusiast** [comment]
Just updated it, it still says no chapter found

**Comment by jaeheemarupok** [comment]
It's also not working for me. I'm using Oppo A3s.

**Comment by ShadesOfRay** [comment]
I tested it on both my phone and an emulator. You have to open a manga in webview first. After that the extension should work correctly.

**Comment by MinecraftEnthusiast** [comment]
IT WORKED THANKSSS
