### ISSUE TITLE
[Bug] CopyManga: maybe I find the reason of load manga images slowly

### ISSUE THREAD

**Issue by zhongfly** [tachiyomiorg/tachiyomi-extensions#6649]
## Device information
- Tachiyomi version: 0.10.11
- Android version: 10

## Source information
- Name: CopyManga
- Extension version: 1.2.8

## Steps to reproduce
read any chapter of manga using copymanga source

### Expected behavior
Can watch manga smoothly

### Actual behavior
loading manga images very slowly

## Other details
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6584
Because the website have 2 kinds of domain name for its image.
When you visit copymanga on mobile phone,it will ask you "請選擇加速線路" and you can choose "大陆用户线路" or "港台及海外线路".Then it will store your choose as "region",the value "0" means "港台及海外线路" and the value "1" means "大陆用户线路".
When you request chapter image with header "region:0",the website will give you image url with "https://mirror2.mangafunc.fun/……"or"https://mirror.mangafunc.fun/……",loading image fast with proxy but slow with direct .When the request's header is "region:1",the website will give you image url with "https://mirror277.mangafunc.fun/……" or "https://mirror77.mangafunc.fun/……" ,loading images slow with proxy.
@sunbeams001

**Comment by zhongfly** [comment]
拷贝漫画的资源有以下子域名
alicdn2.mangafunc.fun 阿里cdn，放js文件
图片用，国内cdn，国内加载速度快：
mirror277.mangafunc.fun
mirror77.mangafunc.fun
图片用，国外cdn，境外速度快：
mirror2.mangafunc.fun
mirror.mangafunc.fun
未启用：
mirrorvip.mangafunc.fun

**Comment by sunbeams001** [comment]
I simply parse result from PC web page, and the image hosts are mirror77 and mirror277 in my network (whether use proxy can not affect it).
If the PC page has an option to choose different CDN hosts, I can add it.
