### ISSUE TITLE
[Bug] Wonderland: I can't get into the manga via WebView, but when I go to the Wonderland website, the manga enters

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#6654]
## Device information
- Tachiyomi version: 0.10.11
- Android version: 8.1.0

## Source information
- Name: Wonderland
- Extension version: 1.2.3

## Steps to reproduce
1. Go to explore
2. Menu sources
3. Tap on the Wonderland source name

### Expected behavior
See the manga available at Scan

### Actual behavior
![Screenshot_20210421-110815_Tachiyomi](https://user-images.githubusercontent.com/82852543/115567712-ef14af80-a291-11eb-9473-ce98f18cadf0.jpg)

![Screenshot_20210421-110557_Tachiyomi](https://user-images.githubusercontent.com/82852543/115567532-bbd22080-a291-11eb-848f-098f11028558.jpg)

![Screenshot_20210421-110633_Tachiyomi](https://user-images.githubusercontent.com/82852543/115567574-c8ef0f80-a291-11eb-8d52-031e348d3ecf.jpg)

## Other details
But when I enter the Scan site, Manga comes in

![Screenshot_20210421-111248_Tachiyomi](https://user-images.githubusercontent.com/82852543/115568640-e1135e80-a292-11eb-9b5c-ac9bd94b239e.jpg)

![Screenshot_20210421-111417_Tachiyomi](https://user-images.githubusercontent.com/82852543/115568717-f25c6b00-a292-11eb-9180-cba9658fdfc9.jpg)

**Comment by Kaylenna** [comment]
I can't get into the manga via WebView, but when I go to the Wonderland website, the manga enters

**Comment by Kaylenna** [comment]
I tried to resolve it through the Help Center, but it didn't work

**Comment by alessandrojean** [comment]
I will take a look.

**Comment by Kaylenna** [comment]
Thank you, now the manga has entered
