### ISSUE TITLE
[Bug] <Mangafreak><It shows cloudflare error even after clearing it>

### ISSUE THREAD

**Issue by ArzuHrpt** [tachiyomiorg/tachiyomi-extensions#6655]
App version: 0.10.11-3306 (standard, 0eb8d7d0, 58)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.N960FXXS8FUB1
Device brand: samsung
Device manufacturer: samsung
Device name: crownlte
Device model: SM-N960F
Device product name: crownltexx

## Source information
- Name: Mangafreak
- Extension version: 1.2.2

## Steps to reproduce
1. Show the updated manga when regular update comes
2. Show the manga covers and chapters on search

### Expected behavior
1.When manga update happens, updated manga to be shown without problem
2.Should be able to see the cover and chapters of manga when I search

### Actual behavior
1.When update happens it always gives the 'failed to bypass cloudflare' error.
2. I can't see the chapters of manga i searched

## Other details
Extension works fine when i try to browse it from the tab. I can see manga covers, chapters. I can read them too. I did pass cloudflare in case it would still cause a problem, both from web view and browser. However, it still gives this error on updates and when I try to check a manga i found from search.

**Comment by okaywhatfine** [comment]
Same here.
At first it popped up "Cannot bypass Cloudfare."

Then i did the troubleshoot guide for that but in the end it didn't work but gave me a new error titled "Stream was Reset: INTERNAL_ERROR".


Then at rare times it shows "Cannot bypass Cloudfare Cloudfare" again.


It's a LOOOP it's like I'm a hamster stuck in a loop at this point.

My device:

Android 10
Realme 5
Latest Update

Tachiyomi Info:

App: Tachiyomi
Fork? No

Extension info: (Problem)

Name: MangaFreak
Problem: Filtering pops up "Cannot bypass Cloudfare" or "Stream was reset: INTERNAL_ERROR" when using
When did the problem show itself? When i first installed Mangafreak aka Jun 4
