### ISSUE TITLE
[Bug] <Sekte doujin>: < Extension appears broken - unable to load website Error 404  >

### ISSUE THREAD

**Issue by Okaklaaaa** [tachiyomiorg/tachiyomi-extensions#6657]
## Device information
- Tachiyomi version: 0.10.7
- Android version: 7.1.1

## Source information
- Name: sekte doujin
- Extension version: 1.2.3

## Steps to reproduce
1. First Step - Have the extension installed then open it by clicking on it
2. Second Step - try opening the extension by using the "latest" button

### Expected behavior
Title picture icons should load like all other extensions, and we should be able to pick and choose a title to read.
### Actual behavior
Message appears on the screen "Http error 404" Check website in webview" If refreshed the messaged can be replaced with "no results found"
## Other details
Actual website is live and running when checked in webview. Have not encountered cloudflare from the few titles I looked while in webview.

**Comment by arkon** [comment]
Supersede by #9172
