### ISSUE TITLE
[Bug] <MG Komik>: <error 400>

### ISSUE THREAD

**Issue by gospodinh** [tachiyomiorg/tachiyomi-extensions#6658]
## Device information
- Tachiyomi version: 0.10.11
- Android version: 10

## Source information
- Name: MG Komik
- Extension version: 1.2.3

## Steps to reproduce
1. Browse all mangas

### Expected behavior
Get list of all mangas

### Actual behavior
Error 400

**Comment by Riztard** [comment]
its working, maybe previously they change to another theme  then back to madara theme
