### ISSUE TITLE
[Source Request] <Leviathan porn manhwa>

### ISSUE THREAD

**Issue by catoAvg** [tachiyomiorg/tachiyomi-extensions#6660]
## Source website
- Name: Leviathan Scans X
- Link: https://xxx.leviatanscans.com/
- Language(s): English

## Other details
They've created a hentai website that's separate from their main site, so the current Leviathan extension can't access it.

**Comment by as280093** [comment]
**Icon:**
[XLevi.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6357345/XLevi.zip)
