### ISSUE TITLE
[Bug] Cubari: Chapters are in wrong order

### ISSUE THREAD

**Issue by mnabid** [tachiyomiorg/tachiyomi-extensions#6662]
## Device information
- Tachiyomi version: 0.10.11
- Android version: 8.1.0

## Source information
- Name: Cubari
- Extension version: 1.2.2

## Steps to reproduce
1. Open [`cubari:gist/OPM`](https://cubari.moe/read/gist/OPM/) in Tachiyomi
2. Sort chapters by source

### Expected behavior
Chapters should be ordered numerically according to the [source](https://cubari.moe/read/gist/OPM/) **(1, 2, 3, ..., 99, 100, 101, ...)**

### Actual behavior
Chapters are in wrong order **(1, 10, 100, 101, ..., 119, 12, 120, 121, ...)**

## Screenshots
| https://cubari.moe/read/gist/OPM/ | Tachiyomi |
| - | - |
| ![Screenshot 1](https://user-images.githubusercontent.com/62117272/115628689-d7393c00-a322-11eb-8687-76ae294da38c.png) | ![Screenshot 2](https://user-images.githubusercontent.com/62117272/115628910-2f703e00-a323-11eb-92c6-a36a625d9654.png) |

**Comment by Seishirou101** [comment]
you're opening https://gist.githubusercontent.com/funkyhippo/1d40bd5dae11e03a6af20e5a9a030d81/raw/? which is showing exactly like in tachi.

**Comment by MarcosSouza2004** [comment]
i'm with the same problem, but if you change the settings to this:
![image](https://user-images.githubusercontent.com/76596575/115708536-84717b80-a346-11eb-97b5-da1036effc90.png)
The bug dont happend, no the ideal, but is a temporary opition
