### ISSUE TITLE
[Enhancement] Cubari: Show update time of chapters

### ISSUE THREAD

**Issue by mnabid** [tachiyomiorg/tachiyomi-extensions#6663]
## What feature should be added to this source?
**cubari.moe** shows the **"Last Updated"** time of the chapters. (e.g.: https://cubari.moe/read/gist/OPM/)
This should be shown in Tachiyomi too.

| cubari.moe | Tachiyomi |
| --------------- | -------------- |
| ![cubari.moe](https://user-images.githubusercontent.com/62117272/115634753-0a33fd80-a32c-11eb-87b0-9ad059c4b9f0.png) | ![Tachiyomi](https://user-images.githubusercontent.com/62117272/115628910-2f703e00-a323-11eb-92c6-a36a625d9654.png) |

**Comment by mnabid** [comment]
fixed with a77f704

**Comment by RedShangarf** [comment]
Sorry for asking this but,  how can i update the date of last chapters (Last Updated)? I don't know about these things, i just followed steps on the internet. I always use this "last_updated": "1617506008" so always show an old and same date. Please help me (https://cubari.moe/read/gist/J367J/)

**Comment by lord-ne** [comment]
Confirmed still present in version 1.2.5 of the extension

**Comment by eNV25** [comment]
> Sorry for asking this but, how can i update the date of last chapters (Last Updated)? I don't know about these things, i just followed steps on the internet. I always use this "last_updated": "1617506008" so always show an old and same date. Please help me (https://cubari.moe/read/gist/J367J/)

"last_updated" is a Unix timestamp. In Linux/Unix use `date +%s` to get the current timestamp. On windows you'll have to use a website like https://www.unixtimestamp.com/.

**Comment by RedShangarf** [comment]
> > Sorry for asking this but, how can i update the date of last chapters (Last Updated)? I don't know about these things, i just followed steps on the internet. I always use this "last_updated": "1617506008" so always show an old and same date. Please help me (https://cubari.moe/read/gist/J367J/)
> 
> "last_updated" is a Unix timestamp. In Linux/Unix use `date +%s` to get the current timestamp. On windows you'll have to use a website like https://www.unixtimestamp.com/.

Wow, it works! You're amazing!! Very thanks!!

**Comment by lord-ne** [comment]
The reason why this is not implemented is because the extension is using the Cubari API (`cubari.moe/read/api/<source>/series/<series name>`), which does not show return upload dates. Thus the extension would need to make an entirely separate GET request to the main chapters page (`cubari.moe/read/<source>/<series name>`) and try to match up the upload dates there to the chapter/volume numbers from the API. The simplest solution would be for Cubari to just add the dates to the API, but I can't find their Discord or a Github repository or anything where I can suggest it.

**Comment by jay061996** [comment]
> I can't find their Discord or a Github repository or anything where I can suggest it.

[Cubari Discord](https://discord.gg/SavdUC45MS)
While it's not the Cubari reader, here is the [Github](https://github.com/appu1232/cubari-proxy) for their [Cubari Proxy](https://proxy.cubari.moe)

**Comment by lord-ne** [comment]
I asked on the Discord and the Cubari team says they'll add it. I think the Tachiyomi extension will work with the dates as soon as they're added to the API, since it's already set up to process dates if available (since they already exist for some Cubari sources)

**Comment by funkyhippo** [comment]
This issue should be fixed.

**Comment by mnabid** [comment]
Yup, it's fixed now.
