### ISSUE TITLE
[Source Request] <Asiancrew Fansub>

### ISSUE THREAD

**Issue by davidtuning** [tachiyomiorg/tachiyomi-extensions#6667]
## Source website
- Name: Asiancrew Fansub
- Link: https://asiacrewfansub.com/
- Language(s): Spanish

## Other details

I believe it uses WP Stream, maybe I'm wrong.

Thanks as always!

**Comment by davidtuning** [comment]
Nvrm, looks like is Eastmanga theme.

**Comment by loocool2** [comment]
Site seems to be down now

**Comment by vetleledaal** [comment]
Domain is parked
