### ISSUE TITLE
Ehentai image limit exceeded

### ISSUE THREAD

**Issue by audi4444player** [tachiyomiorg/tachiyomi-extensions#6668]
Hello, Both my app and extension are latest, but my android version is 5 unfortunately, so that might be the issue.
I'm having an issue where it's downloading the chapters as the limit exceeded files,  however it doesn't seem to reset, I'm logged in now in the Web view to try to solve it (but I don't know if tachiyomi acknowledges that, once logged it  I shouldn't reach my limit) but either way there should be no issue now as it's been a few days since going over the  guest limit. I tried to clear chapter cashe, re add to my library, Mark as unread and obviously re download but it hasn't fixed it. It's there a solution? Thank you

**Comment by audi4444player** [comment]
I finally figured out how to flash my tablet up to android 7, the issue still persists. It even happens on things not in my library already,  as stated the Web view works fine. To be clear all images of any manga on eh are downloaded as 509 bandwidth exceeded files.

**Comment by joseph619** [comment]
This is not an extension issue, you got temp banned by Ehentai for exceeding daily limit.

**Comment by audi4444player** [comment]
oh, I see, thank you so much for the info, do you know if there is there a way to see how long it's banned for? and after that time will tachiyomi download with my account limit that's logged in in the web view ? or will it happen again if I'm not careful? I have the maximum limit for my account.
