### ISSUE TITLE
[Bug] <Mangaworld>: <does not update manga>

### ISSUE THREAD

**Issue by Satorou** [tachiyomiorg/tachiyomi-extensions#6671]
hi, I wanted to report that the Mangaworld extension (https://www.mangaworld.io/) does not work. 
![IMG_20210423_022805_485](https://user-images.githubusercontent.com/68879270/115800755-8afe0280-a3db-11eb-8433-b7ffbef17f72.jpg)

**Comment by OncePunchedMan** [comment]
working fine for me. try https://tachiyomi.org/help/guides/troubleshooting/#diagnosis
