### ISSUE TITLE
[bug] komiku (ID) unable open image

### ISSUE THREAD

**Issue by hostkit** [tachiyomiorg/tachiyomi-extensions#6674]
## Device information
* Tachiyomi version: r3312 and last stable release
* Android version: 9
* Device: redmi note 5a

## Source information
* Source name: komiku (id)
* Source extension version: 1.2.11

## Steps to reproduce
1. Open manga martial peak
2. Open chapter always retry not showing image

**Comment by Kyrieze** [comment]
I do have report as well, all the image from different title do the same, I have a lot from this source and yeah I can confirm that all of the aren't accessible

**Comment by Kyrieze** [comment]
@Riztard I hope you check this out, thanks in advance!

**Comment by Riztard** [comment]
#6711
