### ISSUE TITLE
[Bug] <mangaswat>: <site protected open webview>

### ISSUE THREAD

**Issue by dmswd** [tachiyomiorg/tachiyomi-extensions#6678]
## Device information
 App version: 1.6.1 (standard, be1e7f28e, 15)
Preview build: 357
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx
## Source information
- Name: mangaswat
- Extension version: 1.2.4

## Steps to reproduce
1. Just open the source

### Expected behavior
Manga should appear

### Actual behavior
Nothing appears

## Other details
Works fine in webview
Also tried in the preview
Some time ago in order for the site to work i had to open the webview

**Comment by Aqid-Frost** [comment]
Manga swat has been currently having site modifications. they might have changed something related to the process of pulling mangas using tachiyomi.
So, manga swat extension might need to be updated so that it can function under the new circumstances.

**Comment by Aqid-Frost** [comment]
@AbdullahM0hamed can you please do anything that might help, or we lost swat for good

**Comment by dmswd** [comment]
The site is up again and working
I'm closing this

**Comment by CarlosEsco** [comment]
@dmswd  is it not working?

**Comment by dmswd** [comment]
Yes
It's not working

**Comment by Aqid-Frost** [comment]
Its  broken again

**Comment by FrostAlev** [comment]
21 days, still no solution!
