### ISSUE TITLE
[Source Request] <bilibilicomics>

### ISSUE THREAD

**Issue by abdallahbassim** [tachiyomiorg/tachiyomi-extensions#6686]
## Source website
- Name: bilibilicomics
- Link: www.bilibilicomics.com
- Language(s): EN

**Comment by Samk19** [comment]
+1 for support of this source request

**Comment by mrehanabbasi** [comment]
I'd request it as well that it be added.

**Comment by Silvermane06** [comment]
I'd also love for this to be added.

**Comment by alessandrojean** [comment]
I will try to make an extension for it.

**Comment by abdallahbassim** [comment]
There something wrong in extensions only shows 4 manhwa
![Uploading Screenshot_2021-05-21-16-07-59-951_eu.kanade.tachiyomi.jpg…]()

**Comment by alessandrojean** [comment]
The browse screen only shows the featured titles, it's intentional. You can search for what you want though.

**Comment by abdallahbassim** [comment]
Ok thank u for the trouble
