### ISSUE TITLE
[Failed to connect with githubuser] <tachiyomi.org>: <only the installed extensions are showing up not all the extentions available in extensions tab>

### ISSUE THREAD

**Issue by killuazol47** [tachiyomiorg/tachiyomi-extensions#6697]
## Device information
- Tachiyomi version: 0.10.11 (standard, 0eb8d7d, 58)
- Android version: 10 (SDK 29)

## Source information
- Name: -
- Extension version: -

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
When We open extensions tab we see Installed extensions and extentions that we can download

### Actual behaviour
In extensions tab only the installed extensions are showing not all the available extensions.

## Other details
Im also attaching the screenshot of error showing after i refresh the extensions tab.
![Screenshot_20210424-232453__01](https://user-images.githubusercontent.com/83135673/115968856-6e86d500-a557-11eb-86ae-bfac1be834bb.jpg)

**Comment by arkon** [comment]
We can't really fix your connection issues. Did you try a different network or a VPN?

**Comment by killuazol47** [comment]
> We can't really fix your connection issues. Did you try a different network or a VPN?

Well my internet connection is damn gud . And i dont any have problem with it somewhere else. Fortunately I tried vpn and it worked.. Still make sure there are no server problems or anything because my friends was also having the same issues . We belong to India.

**Comment by arkon** [comment]
Are you expecting me to fix your connection to GitHub?
