### ISSUE TITLE
[Source Request] <manga.club>

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi-extensions#6700]
Name: manga.club
Url: https://manga18.club/
Lang: en,korean

**Comment by jopejoe1** [comment]
Duplicate of #5253

**Comment by jopejoe1** [comment]
Or just mislabelled

**Comment by alexphilip0019** [comment]
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5253
