### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by Jir0u** [tachiyomiorg/tachiyomi-extensions#6702]
Nome: Tsuki Mangás
![Screenshot_20210425-113216_Tachiyomi](https://user-images.githubusercontent.com/83174135/115998280-e9cea200-a5bc-11eb-8be3-fcd2f23a7c16.jpg)

**Comment by alessandrojean** [comment]
Deve ser corrigido na próxima atualização. Por favor, na próxima vez, preencha todo o template da Issue corretamente.
