### ISSUE TITLE
Bug: Tsuki Mangás

### ISSUE THREAD

**Issue by Jir0u** [tachiyomiorg/tachiyomi-extensions#6705]
## Device information
- Tachiyomi version: App version: 0.10.11
- Android version: 9

## Source information
- Name: Tsuki Mangás
- Extension version: 1.2.13

Não dá pra entrar na extensão
![Screenshot_20210425-113216_Tachiyomi](https://user-images.githubusercontent.com/83174135/115998663-b9880300-a5be-11eb-8ae0-9108f9d0b3db.jpg)

**Comment by alessandrojean** [comment]
Already fixed by #6703.
