### ISSUE TITLE
[Source Request] <Galicia Comic>

### ISSUE THREAD

**Issue by JackRestart** [tachiyomiorg/tachiyomi-extensions#6709]
## Source website
- Name: Galicia Comic
- Link: https://galiciacomics2.blogspot.com/
- Language(s): Spanish

## Other details

Seeing as there isn't any Spanish western extension yet, and leercomicsonline #5976 won't work because of issu, could this work? It has a lot of indie graphic novels that I haven't been able to find anywhere else. Thank you for your work!

**Comment by alessandrojean** [comment]
Blogger website without a proper structure and a title details page.
