### ISSUE TITLE
[Bug] <Sekte Doujin>: <bisa menampilkan komiknya tapi tidak bisa di baca ataupun di download>

### ISSUE THREAD

**Issue by Mugenjin07** [tachiyomiorg/tachiyomi-extensions#6710]
## Device information
- Tachiyomi version: 10.11
- Android version: 10

## Source information
- Name: Sekte Doujin
- Extension version: 1.2.4

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by curche** [comment]
Google Translated title:
> can display the comics but cannot be read or downloaded

sekte extension had an update since they changed website themes recently (as per #6706)
try migrating from that source to the same source

you can also ask for support at the #support channel by joining the Discord Server

**Comment by ramenclouds** [comment]
> Google Translated title:
> > can display the comics but cannot be read or downloaded
> 
> sekte extension had an update since they changed website themes recently (as per #6706)
> try migrating from that source to the same source
> 
> you can also ask for support at the #support channel by joining the Discord Server

Can you teach me how to migrate the source? I've trying to uninst then install the extensions again but the problem is still there. I'm sorry but I don't really understand how this works...

**Comment by curche** [comment]
Since this extension changed links recently, you can try to migrate your manga from old version of sekte to latest one [linked here](https://tachiyomi.org/extensions/#id.sektedoujin) 

You can refer to a detailed guide on performing Migration at https://tachiyomi.org/help/guides/source-migration/
