### ISSUE TITLE
[Feature Request] <Gs nation>: 
<Gs nation is a french scantrad team, their website has the same WordPress as the flame scan, they often translate the new big manhwa
https://gs-nation.fr/>

### ISSUE THREAD

**Issue by NedBtww** [tachiyomiorg/tachiyomi-extensions#6716]
## What feature should be added to this source?
The same feature as the flame scan

Explain why this should be added

Because it has become the best French scantrad team (only in the manhwa sector)

**Comment by keinezeit8** [comment]
I think this should be a source request.

---------------------------------------
Also a [link](https://gs-nation.fr/) to click.
