### ISSUE TITLE
[Bug] <MangaPark>: <The mangas in the extension dindt shows>

### ISSUE THREAD

**Issue by plsouza12** [tachiyomiorg/tachiyomi-extensions#6721]
## Device information
- Tachiyomi version: **0.10.11**
- Android version: **Galaxy Note9**

## Source information
- Name: **Mangapark**
- Extension version: **1.2.18**

## Steps to reproduce
**Open the extension to see the mangas**
### Expected behavior
**See the mangas**

### Actual behavior
**Shows the messages"No results found"**

## Other details
    If you try to read a manga from your library works fine and in the webview shows this:  
![Screenshot_20210426-200728_Tachiyomi.jpg](https://user-images.githubusercontent.com/64226623/116162988-402b0600-a6cd-11eb-8e38-3ec351be7e30.jpg)

![Screenshot_20210426-200650_Tachiyomi.jpg](https://user-images.githubusercontent.com/64226623/116162994-44efba00-a6cd-11eb-922d-655f40483206.jpg)

**Comment by Jaykoerner** [comment]
seems they have updated the site, temp measure to use the url https://v2.mangapark.net to get the old results will work atm, the scarper need to be redone from scratch

**Comment by Jaykoerner** [comment]
submitted change to extension, but it has not been tested, I assume this will(temporarily fix the extension)

**Comment by Jaykoerner** [comment]
verified my proposed fix works, and built debug app, here https://drive.google.com/file/d/1WgFQozqgR764vg5ZfeLqVOTBojqqi7ow/view?usp=sharinghttps://drive.google.com/file/d/1WgFQozqgR764vg5ZfeLqVOTBojqqi7ow/view?usp=sharing 

use at own risk, i built and trust this app but am not asking you to,
To use uninstall mainline extension, install from unknown sources, and trust in app

**Comment by Jaykoerner** [comment]
Just to note the issue is not fully fixed, should a new issue be posted since this is only falling back to the legacy server? If so is feature request or bug appropriate?

**Comment by CarlosEsco** [comment]
Request a feature to update to new version

**Comment by Jaykoerner** [comment]
Will do, thanks
