### ISSUE TITLE
[Tachiyomi SY Crashes] <The Flash (2016)>: <Tachiyomi Sy takes me to the opening screen whenever I click on settings while reading the mentioned comic>

### ISSUE THREAD

**Issue by GoldMight948** [tachiyomiorg/tachiyomi-extensions#6723]
## Device information
- Tachiyomi version: Stable 1.6.1 (SY) 
- Android version: 8.10

## Source information
- Name: ReadComicOnline
- Extension version: 1.2.10

## Steps to reproduce
1. Open The Flash (2016)
2. Click on settings 

### Expected behavior
The settings tab should've opened

### Actual behavior
After I click on the settings icon, instead of opening the tab it takes me to the opening screen of sy

## Other details
It's only happening with this comic, in this source

**Comment by CarlosEsco** [comment]
Does the crash happen on the main Tachiyomi?

**Comment by GoldMight948** [comment]
> Does the crash happen on the main Tachiyomi?

No
