### ISSUE TITLE
[Source Request] Freetime Scanlator

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#6728]
- Name: Freetime Scanlator
- Link: https://www.ftmangas.top/home
- Language(s): Portuguese

**Comment by alessandrojean** [comment]
I will take a look into it.

**Comment by Kaylenna** [comment]
Ok ^^, thanks

**Comment by alessandrojean** [comment]
I took a look now into the site source code, and they use random generated CSS classes (that probably change every time they upload a new manga or chapter and rebuild the site), so this will make the creation of an extension almost impossible.

The same case of #6640 applies then:

> You probably can read their releases in some aggregator source that already have their own extension.

**Comment by Kaylenna** [comment]
Got it, thanks for trying 😁
