### ISSUE TITLE
[Feature Request] <Manga Diyarı>: <URL Change>

### ISSUE THREAD

**Issue by onursedef** [tachiyomiorg/tachiyomi-extensions#6731]
## What feature should be added to this source?
Explain why this should be added

Change url of Manga Diyarı. If you click the current link on tachiyomi you'll see a vm login page 'cause the owner of web site change their url to manga-diyari.com . Website still uses same theme and same extensions so you'll just change url.

**Comment by jopejoe1** [comment]
Was already done by #6447
