### ISSUE TITLE
[Bug] <ManhuaScans>: <Page didn't found>

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#6733]
---

## Device information
- Tachiyomi version: r3328
- Android version: 10

## Source information
- Name: ManhuaScans
- Extension version: 1.2.3

## Steps to reproduce
1. Open any manga (f.e. FFF-Class Trashero)
2. Open any chapter (f.e. 85)

### Expected behavior
Open chapter

### Actual behavior
I see this: page didn't found

## Other details
-![Screenshot_2021-04-28-07-45-32-116_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/116347892-bf1b5e00-a7f5-11eb-802c-89e96457045c.jpg)

**Comment by Shiyuue** [comment]
Had the same issue.

**Comment by rururubie** [comment]
Same problem 🥲

**Comment by Akazotik** [comment]
For now i see this

![Screenshot_2021-04-28-10-12-46-183_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/116362055-525e8e80-a80a-11eb-9d29-47a0b1a3bab5.jpg)

**Comment by yasnil03** [comment]
Is it now fix the manhuascan?

**Comment by nzoba** [comment]
It's waiting for the approval of a maintainer.
If a developer approves the fix, the issue will be closed and a new update will be available for the extension in Tachiyomi.
