### ISSUE TITLE
[Bug] <Isekaiscan>: <not showing the latest manga,manhua and manhwa>

### ISSUE THREAD

**Issue by PolgP** [tachiyomiorg/tachiyomi-extensions#6735]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: Isekaiscan.com
- Extension version: 1.2.5

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
it should have show the updated books like for  april 28,2020

### Actual behavior
it is still stuck at books that updated b a week ago

## Other details
when i open webview in app it shows the correct books

**Comment by Riztard** [comment]
i dont really understand wdym, should fill Steps to reproduce
you can add screenshot as well if needed/easier to explain

**Comment by matheuswr89** [comment]
Here on my phone it's working perfectly
