### ISSUE TITLE
[Bug] Webtoon.xyz : can't browse, cause of cloudflare bypass

### ISSUE THREAD

**Issue by Kyrieze** [tachiyomiorg/tachiyomi-extensions#6738]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.1

## Source information
- Name: WebtoonXYZ
- Extension version: 1.2.3

## Steps to reproduce
1. First Step 
Trying to browse the source

### Expected behavior
Shows list of titles 

### Actual behavior
Shows error can't bypass Cloudflare

## Other details
I've tried to clean the cache, and cookies from settings, I've tried change DNS through HTTPS to cloudflare and Google, still got no result, I got nothing on the library from that source

I'll get the screenshot below
![Screenshot_2021-04-28-16-08-54-61](https://user-images.githubusercontent.com/74162654/116379683-75566600-a83d-11eb-86bf-8afe694eefa0.png)
It's shows nothing on webview, but
![Screenshot_2021-04-28-16-20-05-05](https://user-images.githubusercontent.com/74162654/116379930-b2225d00-a83d-11eb-8382-0150338d95a7.png)
After I clicked the menu and click open in browser it's displaying the website
![Screenshot_2021-04-28-16-08-46-85](https://user-images.githubusercontent.com/74162654/116380067-d1b98580-a83d-11eb-9a61-9e359c5658b8.png)

**Comment by The-Doof** [comment]
I have experienced a similar issue. Webtoonxyz does not show any content and I'm stuck on the cloud flare DDoS protection page. 


![Screenshot_2022-07-10-04-13-58-032_eu kanade tachiyomi](https://user-images.githubusercontent.com/104657004/178129930-875db97a-4bbf-42cd-ba1b-ba9505b01bb1.jpg)
![Screenshot_2022-07-10-04-13-47-822_eu kanade tachiyomi](https://user-images.githubusercontent.com/104657004/178129932-1502ba7a-f5bc-4b0b-8938-d5f4d5b02755.jpg)

**Comment by onmyouji** [comment]
It is a known issue, here's the status update from their official discord:

![2022-07-10_143207](https://user-images.githubusercontent.com/8424198/178135585-8c447254-9ef2-40ec-a643-0332fa3e7bd8.png)

**Comment by onmyouji** [comment]
I can now browse webtoon.xyz using tachiyomi (you have to open it in webview/browser first to bypass the cloudflare).

Either they have lowered their cloudflare protection level or [this latest extension update](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/31a8bb30781b3b1d93cfb285e0466fde242615b7) solves the issue.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
