### ISSUE TITLE
[Bug] <ManhuaScan>: <Pages wont load correctly>

### ISSUE THREAD

**Issue by SleepyCap** [tachiyomiorg/tachiyomi-extensions#6744]
---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: ManhuaScan
- Extension version: 1.2.4

## Steps to reproduce
1. Open any manga

### Expected behavior
I should see normal manga pages

### Actual behavior
Instead it's just a loading gif with a chibi

![Shh, You'll Wake up the Child - Shh, You'll Wake up the Child Chap 6 - 1](https://user-images.githubusercontent.com/83361536/116436958-ea647400-a81a-11eb-9f74-c0fd5e0f9025.gif)

Also, when I go in we view the pages load up fine.

**Comment by nzoba** [comment]
It's working for me with the version 1.2.4.
Try cleaning your chapter cache, it may be because the chapter pages were loaded before the fix of 1.2.4

If it still doesn't work, give me an example of manga/chapter

**Comment by rururubie** [comment]
> It's working for me with the version 1.2.4.
> Try clearing your chapter cache (in Tachiyomi settings), it may be because the chapter pages were loaded before the fix of 1.2.4
> 
> If it still doesn't work, give me an example of manga/chapter

I tried it but it only shows gray lines and skip all the pages
![Uploading Screenshot_2021_0430_091047.gif…]()

**Comment by leoteesh** [comment]
Hi, sorry if this was the wrong place to post but is anyone having problems with the images not loading again?
![Screenshot_20210430-090214_Tachiyomi](https://user-images.githubusercontent.com/21075197/116666079-7220be80-a992-11eb-861b-16798a30a744.jpg)

Many thanks

**Comment by rururubie** [comment]
> Hi, sorry if this was the wrong place to post but is anyone having problems with the images not loading again?
> ![Screenshot_20210430-090214_Tachiyomi](https://user-images.githubusercontent.com/21075197/116666079-7220be80-a992-11eb-861b-16798a30a744.jpg)
> 
> Many thanks

Me too 😭

**Comment by nzoba** [comment]
It's quite strange, it works perfectly fine for me with `1.2.4`. Maybe try reinstalling the extension ?

Does it do it for all the manga/chapters or any in particular ?

**Comment by leoteesh** [comment]
It does it on all chapters on manhuascan

**Comment by leoteesh** [comment]
Yes having same problem with heroscans and manhwasmut. 
I have tried reinstalling and clearing cache , it worked for a bit then it stopped again with the same problem

**Comment by nzoba** [comment]
So I'll need a bit more information to find where the problem come from.

Can someone do this on a computer with a browser (Chrome, Firefox...) :
- Go to `view-source:https://manhuascan.com/read-the-beginning-after-the-end-chapter-103.html` (don't forget the view-source)
- Paste here some of the content of the line 461, it should look like this
```
</center></br><img class='lazyload chapter-img' src='/lazy_loading.gif' data-srcset='https://qq3.mhscdnv6.club/images/2021/05/01/7dd8be35294667e86.jpg' data-aload='https://qq3.mhscdnv6.club/images/2021/05/01/7dd8be35294667e86.jpg' data-sizes='auto' alt='The Beginning After The End Chapter 103 - ManhuaScan.Com'></br><img class='lazyload chapter-img' src='/lazy_loading.gif' data-srcset='https://qq3.mhscdnv6.club/images/2021/05/01/85f44b636d5cc518c.jpg' data-aload='https://qq3.mhscdnv6.club/images/2021/05/01/85f44b636d5cc518c.jpg' data-sizes='auto' alt='The Beginning After The End Chapter 103 - ManhuaScan.Com'>
```
And give me some information like : 
- Which fork are you using? (E.g: Tachiyomi, TachiyomiJ2K...)
- What numerical version of the app are you on? (E.g: 0.10.11)
- Which device are you using? (E.g: Pixel 5)
- Which Android version are you on? (E.g: Android 11)
- Which country are you from?

**Comment by OncePunchedMan** [comment]
also try using DNS over HTTPS or a VPN

**Comment by chlo-ui** [comment]
I can read with manhua scan but only in webview and not on tachiyomi for a few days, when I want to read a chapter that I have not finished it puts me "no chapter find" I have roof Try and I notice that the problem comes from manhuascan only

**Comment by CrepeTF** [comment]
> I can read with manhua scan but only in webview and not on tachiyomi for a few days, when I want to read a chapter that I have not finished it puts me "no chapter find" I have roof Try and I notice that the problem comes from manhuascan only 

#7011

**Comment by athea08** [comment]
> > Hi, sorry if this was the wrong place to post but is anyone having problems with the images not loading again?
> > ![Screenshot_20210430-090214_Tachiyomi](https://user-images.githubusercontent.com/21075197/116666079-7220be80-a992-11eb-861b-16798a30a744.jpg)
> > Many thanks
> 
> Me too 😭

Me too 😭. Manhuascan is the best extension ever
