### ISSUE TITLE
[Bug] <Luscious>: <Some Doujin/Manga doesn't loads>

### ISSUE THREAD

**Issue by dzambazov** [tachiyomiorg/tachiyomi-extensions#6749]
---

## Device information:Samsung Tab A (2020)
- Tachiyomi version: 0.10.11
- Android version: 10

## Source information
- Name: Luscious 
- Extension version: 1.2.6

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
I expect that this doujin loads on tachiyomi
https://www.luscious.net/graphql/nobatch/?operationName=AlbumGet&query=query%20AlbumGet%28%24id%3A%20ID%21%29%20%7B%0A%20%20%20%20album%20%7B%0A%20%20%20%20%20%20%20%20get%28id%3A%20%24id%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Album%20%7B%20...AlbumStandard%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20MutationError%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20errors%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20code%20message%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0Afragment%20AlbumStandard%20on%20Album%20%7B%0A%20%20%20%20__typename%20id%20title%20labels%20description%20created%20modified%20like_status%20number_of_favorites%20number_of_dislikes%20rating%20moderation_status%20marked_for_deletion%20marked_for_processing%20number_of_pictures%20number_of_animated_pictures%20number_of_duplicates%20slug%20is_manga%20url%20download_url%20permissions%20cover%20%7B%20width%20height%20size%20url%20%7D%20created_by%20%7B%20id%20url%20name%20display_name%20user_title%20avatar%20%7B%20url%20size%20%7D%20%7D%20content%20%7B%20id%20title%20url%20%7D%20language%20%7B%20id%20title%20url%20%7D%20tags%20%7B%20category%20text%20url%20count%20%7D%20genres%20%7B%20id%20title%20slug%20url%20%7D%20audiences%20%7B%20id%20title%20url%20url%20%7D%20last_viewed_picture%20%7B%20id%20position%20url%20%7D%20is_featured%20featured_date%20featured_by%20%7B%20id%20url%20name%20display_name%20user_title%20avatar%20%7B%20url%20size%20%7D%20%7D%0A%7D&variables=%7B%22id%22%3A%22402325%22%7D 

### Actual behavior
But it doesn't loads and it only loads on webview

**Comment by arkon** [comment]
Please don't post NSFW images on GitHub.

**Comment by dzambazov** [comment]
> Please don't post NSFW images on GitHub.

Sorry

**Comment by jopejoe1** [comment]
Try changing the image resolution in the Luscious extension settings screen to a different resolution.

**Comment by dzambazov** [comment]
> Try changing the image resolution in the Luscious extension settings screen to a different resolution.

Thanks it loads now
