### ISSUE TITLE
[Bug] Manga Plus problem

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#6751]
## Device information
* Tachiyomi version: SY Preview r360
* Android version: 11
* Device: Galaxy S10

## Source information
* Source name: Manga Plus by Shuiesha
* Source extension version: 1.2.17

## Steps to reproduce
1. Add a series to library
2. Try to check series for updates
Or 
1. Open source to browse

## Issue/Request
Update checking the series or trying to browse gives error:

kotlinx.serialization.protobuf.ProtoBuf$Default cannot be cast to kotlinx.serialization.BinaryFormat

## Other details
Additional details and attachments.

**Comment by alessandrojean** [comment]
I'll try to reproduce in the emulator and see if I can fix.

**Comment by alessandrojean** [comment]
I tested now with my physical device (that is also on Android 11) and it loaded fine on both Stable and Preview. Probably it is related to the fork you are using, but I will test on the emulator anyway.

**Comment by semiya5** [comment]
Just installed and opened Base Stable and it works correctly

**Comment by joseph619** [comment]
Close the ticket and let the dev of respective fork know on Discord

**Comment by semiya5** [comment]
Will do
