### ISSUE TITLE
[Bug] <Tritinia Scans>: <No Pages but shows in Webview>

### ISSUE THREAD

**Issue by JasonLement** [tachiyomiorg/tachiyomi-extensions#6755]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 8.1.0

## Source information
- Name: Tritinia Scans
- Extension version: 1.2.4

## Steps to reproduce
1. Go to chapter
2. image not loading

### Expected behavior
Show Pages

### Actual behavior
Doesn't show pages

## Other details
Troubleshooting does not work

**Comment by Riztard** [comment]
work for me, what manga what chapter?

**Comment by FourTOne5** [comment]
So it seems like Tritinia added a "Anti scraping" measurement. Where if you don't directly visit the site for the first 24H of chapter release you will not get the chapter data rather the image below under a different class (Thus no page error.)

![image](https://user-images.githubusercontent.com/59261191/116565683-e6724800-a927-11eb-8e7b-beca197d86f3.png)

**Comment by CarlosEsco** [comment]
Probably want to check the timestamp on parsing the chapter list and if its < 24h dont return that chapter.  So the app just sees it as no update

**Comment by Riztard** [comment]
> So it seems like Tritinia added a "Anti scraping" measurement. Where if you don't directly visit the site for the first 24H of chapter release you will not get the chapter data rather the image below under a different class (Thus no page error.)


where did you get that?
seems not happen to all manga?

**Comment by FourTOne5** [comment]
> > So it seems like Tritinia added a "Anti scraping" measurement. Where if you don't directly visit the site for the first 24H of chapter release you will not get the chapter data rather the image below under a different class (Thus no page error.)
> 
> where/how did you get that?
> seems not happen to all manga?

It was happening until a hour or so ago. Maybe they were trying out something for Anti Scraping.

**Comment by Riztard** [comment]
they are not using it, at least for manga i read there
