### ISSUE TITLE
[Source Request] <readberserk.com>

### ISSUE THREAD

**Issue by obito767** [tachiyomiorg/tachiyomi-extensions#6756]
## Source website
- Name: Readberserk.com
- Link: Readberserk.com
- Language(s): English

**Comment by keinezeit8** [comment]
possibly factory source with MangaCatalog #6399

**Comment by obito767** [comment]
Not on app


-------- Original message --------
From: keinezeit8 ***@***.***>
Date: 29/04/2021 17:58 (GMT+00:00)
To: tachiyomiorg/tachiyomi-extensions ***@***.***>
Cc: obito767 ***@***.***>, Author ***@***.***>
Subject: Re: [tachiyomiorg/tachiyomi-extensions] [Source Request] <readberserk.com> (#6756)


possibly factory source with MangaCatalog #6399<https://github.com/tachiyomiorg/tachiyomi-extensions/pull/6399>

**Comment by keinezeit8** [comment]
I know. But a factory source is a source that could be written more easily as it does not need to be dritten from scratch.

**Comment by obito767** [comment]
Sorry idk what you're talking about but can you put the website?


-------- Original message --------
From: keinezeit8 ***@***.***>
Date: 01/05/2021 05:51 (GMT+00:00)
To: tachiyomiorg/tachiyomi-extensions ***@***.***>
Cc: obito767 ***@***.***>, Author ***@***.***>
Subject: Re: [tachiyomiorg/tachiyomi-extensions] [Source Request] <readberserk.com> (#6756)


I know. But a factory source is a source that could be written more easily as it does not need to be dritten from scratch.
