### ISSUE TITLE
[Source Request] <Manhwa18.cc>

### ISSUE THREAD

**Issue by Jinotu** [tachiyomiorg/tachiyomi-extensions#6759]
- Name: Manhwa18
- Link: https://manhwa18.cc/
- Language(s): English

Just found some translations on this website that others don't. 
And while I am at it. Can you please fix this extension?
![Screenshot_20210429-120653_Tachiyomi](https://user-images.githubusercontent.com/77118844/116584609-878bdf00-a8e5-11eb-991e-88fc3bf2f5fe.png)
Website looks similar to the one I am requesting, but this one doesn't work and not only this one some others too, but can't remember their names. Website works properly though.
![Screenshot_20210429-121327_Tachiyomi](https://user-images.githubusercontent.com/77118844/116584886-d0dc2e80-a8e5-11eb-8fa6-94b2c9ba26b7.png)
Oh, and there are this ad pop ups above, if possible please remove those too. Thanks.

**Comment by Kyrieze** [comment]
It's already available that Manhwa18.net was the extension name

**Comment by Jinotu** [comment]
> It's already available that Manhwa18.net was the extension name

But this one is different. It's not .com, or .net, or .org but .cc.
