### ISSUE TITLE
[Feature Request] VIZ Shonen Jump: Add Shonen Jump member login

### ISSUE THREAD

**Issue by GusNa** [tachiyomiorg/tachiyomi-extensions#6771]
## Add optional Shonen Jump member login, in a similar way to the login in the Madokami extension, but optional.
If this feature is added, users who are also Shonen Jump members, paying monthly to access full series in the Shonen Jump digital vault will be able to read these series in full using Tachiyomi, and not just the first and last three chapters.

**Comment by spoutn1k** [comment]
So that was the method I used to access all chapters but the latest update (1.2.7) broke the feature. I am connected in the webview but now refreshing does not list all chapters anymore.

**Comment by alessandrojean** [comment]
@spoutn1k Uhh, sorry if I broke that. I will check what have broke this, because it's not supposed to.

**Comment by spoutn1k** [comment]
@alessandrojean No worries. If you want me to test stuff, please let me know, as I have the membership.

**Comment by alessandrojean** [comment]
Sure, I will ping you when I open the new PR to fix it.

**Comment by spoutn1k** [comment]
If that helps, I closed my phone, did something else, and came back to it. Now the list is back, but trying to download a chapter fails with an notification stating: `'err' is not found`.

**Comment by alessandrojean** [comment]
I will take a look in this too, thanks for reporting.

**Comment by alessandrojean** [comment]
@spoutn1k probably #6774 will fix your issue now.

It should show the locked chapters when you are logged in after a refresh and should load them fine.

If you have some new error or wrong behavior after the update, just let me know.

Sorry for breaking this functionality, and thanks for the information.

**Comment by spoutn1k** [comment]
It works great ! Thanks for the quick action.
