### ISSUE TITLE
[Bug] VIZ: Missing first pages of chapters

### ISSUE THREAD

**Issue by spoutn1k** [tachiyomiorg/tachiyomi-extensions#6772]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version:10

## Source information
- Name: VIZ Shonen Jump
- Extension version: 1.2.6

## Steps to reproduce
1. Download One-Piece chapter 1011 (Or any chapter with a double page spread at the beginning)

### Actual behavior
Read the chapter and see the spread missing a page. The downloaded files on the device start at `002.png` for every chapter.

**Comment by alessandrojean** [comment]
That's weird. I will take a look into it.

**Comment by alessandrojean** [comment]
So, there's no way to check if it is a blank page at start or not. I guess them it's better to always show the blank page in the chapters that have it, since in some ones it can be part of the first double-page spread. I will submit a PR to fix this.
