### ISSUE TITLE
Como puedo quitar el ratelimit?

### ISSUE THREAD

**Issue by iChitose02** [tachiyomiorg/tachiyomi-extensions#6776]
Es un poco molesto esto, la verdad me gustaria desactivarlo ya que limita mucho la experiencia de lectura y demora demasiado las cargas de las paginas

![Screenshot_20210430-221849](https://user-images.githubusercontent.com/83202828/116769505-52c17a00-aa02-11eb-9932-d1e8c05c950b.png)

![Screenshot_20210430-221909](https://user-images.githubusercontent.com/83202828/116769507-56550100-aa02-11eb-84dc-35ebcce751e6.png)

**Comment by OncePunchedMan** [comment]
rate limits exists to not get you ip banned by the source. waiting is a small price to pay
