### ISSUE TITLE
[Bug] gekkouscan>: <chapters>

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#6786]
---

## Device information
App version: 0.10.12-3346 (standard, cb203ef0, 60)
Android version: 11 (SDK 30)
Android build ID: RQ2A.210405.005
Device brand: POCO
Device manufacturer: Xiaomi
Device name: surya
Device model: M2007J20CG
Device product name: surya_global

## Source information
- Name: gekkouscan
- Extension version:  1.2.3

## Steps to reproduce
1. open any manga

### Expected behavior
when opening the manga the chapters should appear.

### Actual behavior
No chapters

**Comment by alessandrojean** [comment]
Uh, they use custom CSS classes in the chapters. I will update it.
