### ISSUE TITLE
[Bug] <Tao Sect>: <cover>

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#6791]
-

## Device information
App version: 0.10.12-3346 (standard, cb203ef0, 60)
Android version: 11 (SDK 30)
Android build ID: RQ2A.210405.005
Device brand: POCO
Device manufacturer: Xiaomi
Device name: surya
Device model: M2007J20CG
Device product name: surya_global

## Source information
- Name: ?
- Tao Sect
- Extension version:  1.2.2

## Steps to reproduce
1. open any manga

### Expected behavior
when selecting the manga, the cover should be loaded.

### Actual behavior
any selected manga does not load the cover.
![Screenshot_20210502-111114_Tachiyomi~2](https://user-images.githubusercontent.com/72045485/116816172-412dbe80-ab37-11eb-9e26-e6eee26e5665.png)

**Comment by alessandrojean** [comment]
I will take a look into it.
