### ISSUE TITLE
[Source Request] Lemon Juice Scan

### ISSUE THREAD

**Issue by danrleylfd** [tachiyomiorg/tachiyomi-extensions#6810]
## Source website
- Name: Lemon Juice Scan
- Link: https://lemonjuicescan.com
- Language(s): PT-BR

## Others Details

- Yaoi Source

**Comment by alessandrojean** [comment]
Seems to use Madara, I will add it.

**Comment by danrleylfd** [comment]
Thank you 👏👏👏
