### ISSUE TITLE
[Meta] <Ability to have custom sound notification, per category>

### ISSUE THREAD

**Issue by Rodark** [tachiyomiorg/tachiyomi-extensions#6811]
##  Why/Project's Benefit/Existing Problem
It improves customization, makes it a fun experience for the user adding their own sound notifications, is immediately informed which of their categories have a manga update
## Other Details
My idea is this. I personally have 4 categories on the app. Currently it allows me to have a checking for downloads sound and a chapter found sound.
Id love to have the ability to have a custom notification sound per category. So, DC has an update? My Batman sound effect, Marvel has an update? Iron Man effect. Manga has an update? insert x anime notification sound.

**Comment by Seishirou101** [comment]
wrong repo, this isn't done at the extension level. You need to make an issue on the main repo

**Comment by Rodark** [comment]
> wrong repo, this isn't done at the extension level. You need to make an issue on the main repo

ah i did not realize! thanks for the info ill post it there
