### ISSUE TITLE
[Bug] Failed to download some pictures of dmzj.com

### ISSUE THREAD

**Issue by Gokou-Ruri** [tachiyomiorg/tachiyomi-extensions#6813]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 11
* Device: Redmi k20 pro

## Source information
- Name: dmzj ( eu.kanade.tachiyomi.extension.zh.dmzj )
- Extension version: 1.2.16

### Actual behavior
https://m.dmzj1.com/info/48519.html
This comic on the end of Chapter 15, there are two pictures download failed.

**Comment by Oldwangtouchtouchdoge** [comment]
确认能复现问题，不过看起来是动漫之家那边的故障，作为客户端我们这边大概没法处理。
日志：
`2021-05-30 13:38:52.157 9945-10453/eu.kanade.tachiyomi.debug I/okhttp.OkHttpClient: <-- 404 https://images.dmzj1.com/k/%E7%A7%91%E5%AD%A6%E5%AD%98%E5%9C%A8%E7%9A%84%E4%BA%BA%E5%A4%96%E5%A8%98%E8%A7%82%E5%AF%9F%E6%97%A5%E8%AE%B0/15%E8%AF%9D_1588770056/25x.jpg (146ms)`

![图片](https://user-images.githubusercontent.com/18094567/120093456-01b1bc80-c14d-11eb-830f-5f7b0c32c98c.png)

`2021-05-30 13:39:04.187 9945-10453/eu.kanade.tachiyomi.debug I/okhttp.OkHttpClient: <-- 404 https://images.dmzj1.com/k/%E7%A7%91%E5%AD%A6%E5%AD%98%E5%9C%A8%E7%9A%84%E4%BA%BA%E5%A4%96%E5%A8%98%E8%A7%82%E5%AF%9F%E6%97%A5%E8%AE%B0/15%E8%AF%9D_1588770056/%E4%BD%9C%E5%93%81%E9%A1%B50 (237ms)`

![图片](https://user-images.githubusercontent.com/18094567/120093512-5f460900-c14d-11eb-8327-4767e253e752.png)
