### ISSUE TITLE
[Feature Request] <Comic Star>: <New site>

### ISSUE THREAD

**Issue by FlammFR** [tachiyomiorg/tachiyomi-extensions#6817]
## What feature should be added to this source?
Old site : https://comicstar.org/
New site : https://comicrush.org/

**Comment by jopejoe1** [comment]
> New site : https://comicrush.org/

Seems to have only one Manga with no Chapters in it.

**Comment by keinezeit8** [comment]
> New site : https://comicrush.org/

For me its just a "Coming Soon!" wordpress page.

**Comment by jopejoe1** [comment]
> New site : https://comicrush.org/
Has manga with chapters now also uses Madara

**Comment by Riztard** [comment]
maybe just add new one, since it changes the name as well
