### ISSUE TITLE
[Bug] <Leviatan Scans>: <HTTP error 404 on reload and reading>

### ISSUE THREAD

**Issue by Markus40** [tachiyomiorg/tachiyomi-extensions#6830]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.1

## Source information
- Name: Leviatan Scans
- Extension version: 1.2.6

## Steps to reproduce
Reload Manga, try to read a chapter or open Webview in your library (saved from before about a week ago)

### Actual behavior
HTTP error 404

## Other details
The Manga still exist on the website but the URL seems to have changed (from "leviatanscans.com/lcomic/manga/" to "leviatanscans.com/comicss/manga/").
If I go directly to the extension or save new Manga to the library it works correctly. Only the old Manga in the library have problems.

**Comment by Seishirou101** [comment]
Migrate your old library entries back into leviathan scans.  There's nothing to do if they change the url

**Comment by Markus40** [comment]
I already migrated but other users that don't have update error messages enabled may not realize that the source does not work. Would it require changes to the main app to change the library URL from an extension?

**Comment by Seishirou101** [comment]
You already said that the extension works. There is nothing that can be done. They just have to migrate themselves because they changed the url.
