### ISSUE TITLE
[Bug] <Bato.to>: Cannot find specific manhwa from other language translation

### ISSUE THREAD

**Issue by clairesnow** [tachiyomiorg/tachiyomi-extensions#6839]
---

## Device information
- Tachiyomi version: stable 0.10.12
- Android version: 10

## Source information
- Name: bato.to
- Extension version: 1.2.8

## Steps to reproduce
1. Open Bato.to extension
2. type manhwa n3n3k
3. result not found
4. trying webview
5. search n3n3k
6. can found in webview

### Expected behavior
When i try to search Indonesian translated manhwa using their unique name, the manhwa suppose to appear in tachiyomi app 

### Actual behavior
When i try to search the manhwa name n3n3k ch4rlott3 (manhwa unique name in Indonesian), search failed. I try to open webview and search and it appear using same manhwa name. Actually it worked before but i'm not sure why now cannot search because i already save some indonesian manhwa and i try search again 

## Other details
I will post the picture for your reference

1st picture = The manhwa that i already put in my library back then i try search using unique name also
2nd picture = i try to search on 6th May 2021 cannot find
3rd picture = Search in webview and appear

![1](https://user-images.githubusercontent.com/83724663/117189147-0d3cec80-ae08-11eb-8768-2f9fb4273d68.jpg)
![2](https://user-images.githubusercontent.com/83724663/117189165-1332cd80-ae08-11eb-9bbf-aebad0cdcb7d.jpg)
![3](https://user-images.githubusercontent.com/83724663/117189171-1463fa80-ae08-11eb-83ff-a8c41c885007.jpg)

Thank you!

**Comment by jopejoe1** [comment]
You can't find it because you are searching on the English version and not the Indonesian.

**Comment by clairesnow** [comment]
I actually already try to filter indonesian (ID) from the filter function and only few manhwa come out like 15. I also try disable all in extensions language except indonesia also cannot. 

Would you mind to inform how search in indonesian one? If not using filter function

Thank you.

**Comment by jopejoe1** [comment]
> I actually already try to filter indonesian (ID) from the filter function and only few manhwa come out like 15. 

That filter function is for from where the manga is and not in what language it is.

> I also try disable all in extensions language except indonesia also cannot.

Did you disable all source languages other than Indonesia and that Indonesia is enabled

> Would you mind to inform how search in indonesian one? If not using filter function

If you did what I asked above check if it says Indonesia under the source in the source list, if it does not then you are using the wrong language. If it does than try searching again.

![Browse 1](https://user-images.githubusercontent.com/34899572/117240091-313e1380-ae84-11eb-977f-00c5941c1a47.png)

**Comment by clairesnow** [comment]
!!

Omg I didn't realize that. 

Thank you very much for the support

I apologize for the inconvenience ♥️
