### ISSUE TITLE
q[Bug] <luscious >: <it stopped working after the 1.2.7 update>

### ISSUE THREAD

**Issue by Agi0m** [tachiyomiorg/tachiyomi-extensions#6840]
---

## Device information
- Tachiyomi version: 0.10.12
- Android version: 6.0.1

## Source information
- Name: luscious 
- Extension version: 1.2.7

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened
The extension should have opened 
### Actual behavior
Describe what happens instead
The app crashes immediately 
## Other details
none

**Comment by arkon** [comment]
Likely only an issue on Android < 8.0 because of the use of newer `java.util` APIs.
