### ISSUE TITLE
[Bug] MangaDex: "newChapterListJson["results"] must not be null" error

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi-extensions#6846]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: MangaDex
- Extension version: 1.2.106

## Steps to reproduce
1. Attempt to open or migrate "Wonder Cat Kyuu-chan"

### Expected behavior
It loads.

### Actual behavior
Error: `newChapterListJson["results"] must not be null`

**Comment by Flat** [comment]
Same error for Otome Danshi ni Koisuru Otome

**Comment by matheuswr89** [comment]
The mangadex team launched v5 API just now and probably changed a few things.
The URL API documentation: https://api.mangadex.org/docs.html

**Comment by CarlosEsco** [comment]
@matheuswr89  this is already using the new api
