### ISSUE TITLE
Standardised sub-language codes

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#6849]
##  Why/Project's Benefit/Existing Problem
Currently, there are 3 different language codes for Chinese Simple and Traditional each. For a total of 7 language codes just for Chinese alone, 6 of them with only one extension in it.
There are also 2 Lang codes for Portuguese Brazilian.

## Other Details
Some of it is just that some extension use different capitalization for the language codes than other extension resulting in multiple language categories in tachiyomi.

The majority uses full caps sub language codes.

**Comment by CarlosEsco** [comment]
Would be nice to put it as a constant in the extensions lib so people are setting to the constant variable rather then hard coding

**Comment by alessandrojean** [comment]
> There are also 2 Lang codes for Portuguese Brazilian.

I will work on this and submit a PR later to fix this part and replace all the usages of `pt-br` to `pt-BR`.

**Comment by jopejoe1** [comment]
@CarlosEsco 
Should be reopened as only fixes the Portuguese Brazilian language.

**Comment by CarlosEsco** [comment]
didn't realize he did fixes # lol

**Comment by matheuswr89** [comment]
In Mangadex extension too necessary replace `pt-br` to `pt-BR`

**Comment by alessandrojean** [comment]
@matheuswr89 As said above, it's replaced in CarlosEsco/tachiyomi-extensions#526, that's why I didn't change this part on my PR.

**Comment by alessandrojean** [comment]
Fixed by #10562.
