### ISSUE TITLE
[Bug] <Gmanga>: <chapters don't appear>

### ISSUE THREAD

**Issue by JxDirash** [tachiyomiorg/tachiyomi-extensions#6852]
In GMANGA extension, the whole chapters of all manga are not shown with a massage that says "index:8 , size:7" (chick the attached pic plz), but when we try webview the chapters do appear. 

![Screenshot_20210506-043127_Tachiyomi](https://user-images.githubusercontent.com/83741170/117234582-f01b1480-ae2d-11eb-9087-6777821490da.jpg)

**Comment by hakudansho** [comment]
⏳⏳
