### ISSUE TITLE
[Bug] DMZJ: Marked Unnumbered Chapters as Unread Repeatly

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi-extensions#6858]
## Device information
- Tachiyomi version: TachiJ2K 1.0.16
- Android version: 10

## Source information
- Name: DMZJ
- Extension version: 1.2.16

## Steps to reproduce
1. Adding manga which using specific title but not number.
2. Mark some chapters as read.
3. Update the library.

### Expected behavior
Chapters which already read still marked as read.

### Actual behavior
Some of chapters re-marked as unread.

## Other details
Some of manga chapters in DMZJ would named with a specific name, and does not have a certain chapter number. This chapter would have chapter number `-1` when you share the manga. For example:  `Helltaker推特短篇集: 第 -1 章, 第 4 页`.

This kind of chapters would re-unread randomly after update the library. Some chapters like `15.5` `12.1` would may re-marked as unread too. It's hard to reproduce and hard to figure which would be affected and which would not in next time library update.

I am only using TachiJ2K, so I can't confirm if it appears in upstream version. And since it only appears in DMZJ, so I pull it as a extension problem.

**Comment by LenKiMo** [comment]
Here is an example about how app remarked the chapters:

![DMZJ Bug Example](https://i.loli.net/2021/05/06/pkl5eOnVQXbNxwu.jpg)

The chapters using number as its name would still read, but chapters do not has an chapter number but using a specific name would re-marked to unread.

**Comment by Oldwangtouchtouchdoge** [comment]
确认可以复现这个问题。
这个问题的原因有两个：
1、tachiyomi使用url地址作为key来区分章节，而现版本（1.2.16）的动漫之家插件由于会通过多个API地址获取章节列表，因此每次刷新时章节的url地址可能出现变化，导致tachiyomi认为获取到的是一个全新的章节。https://github.com/tachiyomiorg/tachiyomi-extensions/blob/6822315dfd054e4a3e1738760c925d483de7bf88/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L268-L324
2、tachiyomi对此有一套补偿机制，大致为：如果联网获取到的新章节列表中，某一个章节的**章节号码**，与本地数据库里的旧章节列表中的某一个章节的号码相等，那么会自动把新章节列表中的这个章节设为已读，然后新列表替换旧列表存入数据库。也就是说，可以通过章节号码把新旧章节列表里的章节关联起来，继承阅读记录。但是，现版本（1.2.16）的动漫之家插件是通过从章节标题中提取第一串数字作为章节号码，而标题中不含数字的章节的号码都会设置为初始值-1，这种情况下上述的补偿机制就无法工作。
https://github.com/tachiyomiorg/tachiyomi/blob/034506f56b96b7f01c2d27021236e55f0542c559/app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt#L104-L132

### 基于上述2个原因，如果章节的url网址因刷新而出现变化，而且这个章节的号码又是初始值-1，tachiyomi就无法认出来这个章节有没有阅读过了，因此会标记为未读。

我正在着手编写新版本，加入的应对措施为：章节的url地址将只填入不变的漫画ID和章节ID，发起连接时根据需要再拼接完整的网址。
该措施启用后的第一次更新书架/更新章节列表依然会出现不含数字的章节标记为未读的情况，之后章节url网址稳定不变，应该就能解决了。
