### ISSUE TITLE
[Bug] Mangadex: Not a JSON Object: null

### ISSUE THREAD

**Issue by Vverg** [tachiyomiorg/tachiyomi-extensions#6862]
---

## Device information
- Tachiyomi version: Preview r3346 
- Android version: 11

## Source information
- Name: Mangadex
- Extension version: 107

## Steps to reproduce
1. Pick a random manga, pick something with enough chapters.
2. Download all chapters.
3. Notice that eventually the download stops, sometimes with the error 'Not a JSON Object: null'.
4. Pause and continue the download queue doesnt solve the issue, I have the remove everything and download again.

### Expected behavior
That it downloads chapters without issues.

### Actual behavior
Stops downloading, make the queue get stuck where I can only fix the issue by removing everything in the queue.
Also getting a error sometimes as mentioned above.

**Comment by CarlosEsco** [comment]
Can you provide a sample manga?

**Comment by Vverg** [comment]
One example would be: Gokukoku no Brynhildr

Though the chapter skipping (the red explanation mark) and getting stuck does happen with every title I download. If I download a title my group does "Bijutsubu Girl", that one has mostly 1 page chapters you will notice the chapter skipping faster.

**Comment by Riztard** [comment]
does it happen to specific chapter or random?

**Comment by Vverg** [comment]
It seems randomly, since I can download the chapter eventually after I delete the queue and readd it. 
However the error 'Not a JSON Object: Null' i only noticed so far with this title.

However, the queue getting stuck seems to happen with every issue that causes a chapter not to be downloaded. Since I also get this issue with random 502/504 error codes. So that might be a bug of Tachiyomi itself instead of the extension.

**Comment by shadowvalentine** [comment]
I've had this problem as well, with "Mushoku no Eiyuu" chapter 14, and "12 Beasts" chapter 20 and 23. Removing those chapters and re-adding it fixed the problem for the "12 Beasts" chapters, but not the "Mushoku no Eiyuu" chapter; it now appears to be completely skipping it (I've tried moving it to top, and pausing and re-starting the download).  When my downloads all complete, I'll attempt it again alone. 

Trying to open the chapter directly shows that it has 25 pages (about right for this manga) but each page cannot load; could it be malformed somehow on Mangadex's end?

**Comment by shadowvalentine** [comment]
Hi, still having this problem on Mangadex exxtension ver 108 with the same manga and chapter, Mushoku no Eiyuu chapter 14. Same error, "Not a JSON Object: null".

**Comment by CarlosEsco** [comment]
> Hi, still having this problem on Mangadex exxtension ver 108 with the same manga and chapter, Mushoku no Eiyuu chapter 14. Same error, "Not a JSON Object: null".

Can you remove the manga from you library, clear chapter cache and db in advanced settings. Then readd the manga.

**Comment by shadowvalentine** [comment]
Thanks Carlos, no luck though. Same error on chapter 14. Redownloading the rest now.
