### ISSUE TITLE
[Source Request] <Lapkzone>

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#6867]
- Name: Lapkzone
- Link: https://lapkzone.com/
- Language(s): Português (Brasil)

- 18+ site.

**Comment by alessandrojean** [comment]
The site is just a WordPress blog with images in the posts and doesn't follow some pattern (like having a manga details page) neither has a proper online reader. It's kinda hard to create an extension when the sites do not follow a pattern in the pages.

For now, alternatively, you can use some other existing extensions that have the same content.

**Comment by Militinix** [comment]
> The site is just a WordPress blog with images in the posts and doesn't follow some pattern (like having a manga details page) neither has a proper online reader. It's kinda hard to create an extension when the sites do not follow a pattern in the pages.
> 
> For now, alternatively, you can use some other existing extensions that have the same content.
> 
> I can take a look later, but I don't promise anything.

Well, if it's too much trouble, you don't need to make an extension of this site, but I would like you to focus on the Super Hentais extension, which is currently the best 18+ site in the Português (Brasil).

Site for you to know which "extension" I am talking about > https://www.superhentais.com/

**Comment by alessandrojean** [comment]
> but I would like you to focus on the Super Hentais extension

Check #3475 in the "Too Difficult to maintain" section.

*Super Hentais* and *Super Mangás* got removed because the site owners didn't want the extension and kept changing things in the site to break the extension. It's unlikely that it will be added again. The best alternative is you use another source.

**Comment by Militinix** [comment]
> _Super Hentais_ and _Super Mangás_ got removed because the site owners didn't want the extension and kept changing things in the site to break the extension.

Meee, I didn't know that the owners were that annoying, then I will even try to talk to them, but it will probably come to nothing. Anything I let you know.

**Comment by alessandrojean** [comment]
> then I will even try to talk to them

I don't think that talking to them will change something, they were very clear at the source code (check #6348).

**Comment by alessandrojean** [comment]
> The site is just a WordPress blog with images in the posts and doesn't follow some pattern (like having a manga details page) neither has a proper online reader.

Closing this because as said before, the site is not a proper online reader, it's just a blog with images attached to the posts.
