### ISSUE TITLE
[Bug] <tcb scans>: <can't display manga in extension>

### ISSUE THREAD

**Issue by Ali-dono** [tachiyomiorg/tachiyomi-extensions#6869]
## Device information
- Tachiyomi version: stable 0.10.12
- Android version: 11

## Source information
- Name: TCB scans
- Extension version: 1.2.3

### Expected behavior
Should have shown the manga in their list which is one piece

### Actual behavior
Nothing in the extension but the webview works fine

**Comment by ilmastr0** [comment]
They updated their website, doesn't work for me either

**Comment by rickninja765** [comment]
Yeah it's still broken.

**Comment by FireNation323** [comment]
It's still broken

**Comment by FireNation323** [comment]
It's still broken

**Comment by Oridjinn1980** [comment]
Still broken, same issue! Web view is fine, but in the app it doesn't show any manga. Would really like to use it since its the "original" source for several series.
