### ISSUE TITLE
[Source Request] <One Piece Ex>

### ISSUE THREAD

**Issue by Resadi** [tachiyomiorg/tachiyomi-extensions#6872]
## Source website
- Name: One Piece Ex
- Link: onepieceex.net
- Language(s): Portuguese

**Comment by alessandrojean** [comment]
Duplicate of #4304.

**Comment by Resadi** [comment]
> Duplicate of #4304.

não vai poder adicionar essa fonte?

**Comment by alessandrojean** [comment]
Leia os comentários no Issue referenciado. Ele ainda está aberto, então pode ser adicionado um dia, mas ainda está no caso de fontes com apenas um mangá, que geralmente não são adicionadas (com algumas raras exceções).

Por enquanto você consegue ler os releases da OPEx em vários outros sites agregadores e em fontes de sites oficiais que tem extensões já.
