### ISSUE TITLE
[Bug] <ReadComicsOnline>: <can't read comics from the extension>

### ISSUE THREAD

**Issue by cowboydroptop** [tachiyomiorg/tachiyomi-extensions#6874]
## Device information
- Tachiyomi version: 0.10.12
- Android version: Samsung

## Source information
- Name: ReadComicsOnline
- Extension version: 1.2.10

## Steps to reproduce
1. First Step: Clicked on other comic books to try to read from them besides the one I tried to read. All can't be opened
2. Second Step: Checked my extension for updates, there weren't any.

### Expected behavior
When I tap on an issue of a comic it should open and let me read the issue

### Actual behavior
When I tap on the issue it doesn't open, making it unable to read the issue from the app and I have to use the web version

## Other details
Web version of the extension works

**Comment by alekc** [comment]
using the latest versions, it works fine. Given the age we can close this one.
