### ISSUE TITLE
Gmanga extension doesn't work

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi-extensions#6875]
## Device information
- Tachiyomi version: latest
- Android version: 10

## Source information
- Name: gmanga
- Extension version: latest

## Steps to reproduce
I open a manga in gmanga or update it

### Expected behavior
It should open or to update

### Actual behavior
A black box appears in the middle of the screen (look at the photo)

## Other details
![Screenshot_2021-05-07-01-34-14-23_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/75262438/117380692-97558580-aeda-11eb-9176-0510fa529973.jpg)

**Comment by iRahmaniMed** [comment]
I have the same problem with this extension

**Comment by hakudansho** [comment]
So, are we getting any solution here or what?🤦🏻

**Comment by CarlosEsco** [comment]
#6852
