### ISSUE TITLE
[Bug] Mangadex v5: Searching for a particular manga returns 403

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi-extensions#6880]
## Device information
- Tachiyomi version: 0.10.12, Sy r362
- Android version: 10 (Lineage OS)

## Source information
- Name: Mangadex
- Extension version: 1.2.107

## Steps to reproduce
1. Open up Browse
2. Search for the manga `Getsuyoubi no Tawawa (Twitter Webcomic) (Fan Colored)`

### Expected behavior
show manga results

### Actual behavior
HTTP error 403: Check website in Webview 

## Other details
The manga itself works fine and can be opened if I search just for Tawawa and find it. Just the exact manga title seems to break search

**Comment by Riztard** [comment]
isnt it dex issue?

**Comment by Korbeil** [comment]
> isnt it dex issue?

It is an MD issue, we found why, working on a fix.

**Comment by curche** [comment]
closing since it will be resolved at Dex
