### ISSUE TITLE
[Feature Request] MangaDex: Add an option to only use MD@H nodes that use port 443 (the official SSL/TLS port)

### ISSUE THREAD

**Issue by fourquestionmarksokay** [tachiyomiorg/tachiyomi-extensions#6881]
*Note to some people: this issue contains links to [the MangaDex Discord server](https://discord.gg/mangadex), which is inaccessible unless you have joined that server.*

## Summary
MangaDex uses volunteer nodes to serve images, which in some cases is problematic in some networks (notably enterprise and school networks) since they heavily filter the internet connection and does not allow any outbound connection except to standard HTTP and HTTP/SSL ports (which is 80 and 443 respectively). In MDv3 and MD API v2 [it's toggled by user's settings](https://discord.com/channels/403905762268545024/719013234065276998/840186248702459904) but in MDv5 the responsibility [is moved to the serving frontend or application](https://discord.com/channels/403905762268545024/719013234065276998/840181501290348615), which is [triggered by putting up a `ssl=true` URL query](https://api.mangadex.org/docs.html#operation/get-at-home-server-chapterId). Essentially, this feature request asks for a port-restricted toggle similar to that of a data-saver toggle.

## The MD@H structure
To keep the traffic manageable and to improve performance in regions where MD has historically not served optimally, they have launched MD@H in early 2020. This is accomplished by either using [the official client](https://gitlab.com/mangadex-pub/mangadex_at_home) (which is easy to run) or an advanced user may opt to run a custom system [following a common specification](https://gitlab.com/mangadex-pub/mangadex_at_home/-/wikis/Formal-Specification-for-Custom-Clients). Some nodes can't use the official SSL/TLS port because
- [the system they're running doesn't allow them to do this](https://gitlab.com/mangadex-pub/mangadex_at_home/-/wikis/Frequently-Asked-Questions#i-am-getting-the-error-javanetsocketexception-permission-denied)
- the node was on a residential network
  - which UPNP doesn't allow automatic inbound connections to port 443
  - [which some ISPs don't allow webhosting](https://discord.com/channels/403905762268545024/719013234065276998/840181157844484166)
  - which some ISPs block port 443
- other technical issues or reasons
  - difficulty of doing SNI ([server name indication](https://en.wikipedia.org/wiki/Server_Name_Indication)) routing ([MD@H discussion](https://discord.com/channels/403905762268545024/719013234065276998/840180770252652546))
  - [for the LOLs](https://discord.com/channels/403905762268545024/719013234065276998/840180407478779904)

## Why non-standard ports are a problem for users
In most residential networks, these problems are nearly non-existent: if a firewall is in place, it only blocks certain well-known ports (like [the special port 0](https://www.grc.com/port_0.htm) and ports 137-139 and 445 [which is used by Microsoft SMB](https://en.wikipedia.org/wiki/Server_Message_Block), which has serious security bugs). In enterprise and school networks, things are different. To minimize evasion (whether due to genuine concerns of exfiltration of trade secrets and other proprietary assets to fears of being a high-value target of phishing and other dangerous attacks to blocking and logging "illicit things"), they typically do the following:
- [use DNS filtering](https://www.michaelhorowitz.com/DNS.and.Routers.March.2018.php)
- block all ports except for standard web browsing (which is 80 and 443)
- [intercept HTTPS requests](https://blog.cloudflare.com/monsters-in-the-middleboxes/)

This obviously prevented users on these networks to access MangaDex, which to them seemingly at random.

## How MDv3 (and MD APIv2) solved this
In MDv3 and API users, logged out users were only given a subset of all available nodes which only uses the standard port 443. [For logged-in users, there is a toggle to opt-out of the default for them, which was all MD nodes regardless of operating port.](https://discord.com/channels/403905762268545024/719013234065276998/840186248702459904) This ensured that users in restrictive networks can access MangaDex unless a block specifically issued to MangaDex was issued.

## How MDv5 (and MD APIv5) solved this
The API expects [the frontend is expected to either detect non-standard port blocking or giving the user an option to switch to it](https://discord.com/channels/403905762268545024/719013234065276998/840181501290348615). On the frontend, if the conditions were right or the user has asked for it [the frontend must place a `ssl=true` URL query to signal this change](https://api.mangadex.org/docs.html#operation/get-at-home-server-chapterId) (Update: yes, it's a confusing name! All MD@H nodes uses HTTPS with TLS (the successor to SSL), just in different ports). This means that the burden is shifted from MangaDex into the frontends.

**Comment by CarlosEsco** [comment]
Thanks for the extra info @Riztard  more to add to your PR

**Comment by Riztard** [comment]
youre expecting too much from me, im still figuring out how things work 
![image](https://user-images.githubusercontent.com/16263232/117447995-5d32c500-af68-11eb-9fe4-74501feb661a.png)
