### ISSUE TITLE
[Source Request] <Ykza Fanscans>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#6884]
## Source website
- Name: Ykza Fanscans
- Link: https://w24.readheroacademia.com/
- Language(s): English

**Comment by jopejoe1** [comment]
Exist already under the name of `Read Boku No Hero Academia Manga Online`

**Comment by FireNation323** [comment]
> Exist already under the name of `Read Boku No Hero Academia Manga Online`

oh my bad I didn't know
