### ISSUE TITLE
[Bug] <TuMangaOnline>: <HTTP ERROR 403>

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi-extensions#6888]
## Device information
- Tachiyomi version: 1.0.16 (J2K)
- Android version: Samsung, 7.0.1

## Source information
- Name: TuMangaOnline (Spanish)
- Extension version: 1.2.33

## Steps to reproduce
1. Open in extension

### Expected behavior
Sleeves appear normally without error

### Actual behavior
"HTTP error 403" appears.

## Other details
In WebView opens normally. Attached images of what happens.
- https://i.imgur.com/BHkc3pi.png
- https://i.imgur.com/yxDHV1G.png

**Comment by TheTeso** [comment]
Creí que era el único xddd

**Comment by Noctamb** [comment]
> Creí que era el único xddd

Yo tambien tengo ese problema

**Comment by srambro** [comment]
Eso es porque a TMO no le gusta que usen apps externas para acceder a su web, así que un bot te banea la IP por unas horas. Vuelve a revisar dentro de un rato, o en un día si es necesario. Este mismo problema lo converse con ellos en su discord y eso fue lo que me dijeron.

**Comment by ripinsertname** [comment]
Y que pasa si llevo así varios días? :c no hay servidores tan buenos como los de tmo

**Comment by KasukeLp23** [comment]
@ripinsertname usa su gemelo que vendría a ser Lector Manga, o a su vez Ninemanga.

Con TMO mi problema es que no aparece los mangas en la sección explorar, pero si se me actualizan los de mi librería asi que no tengo mucho inconveniente.

**Comment by Skygio** [comment]
Algunos mangas también tiran ese error al actualizar los capítulos

**Comment by KasukeLp23** [comment]
@Skygio es por el bot de TMO al requerir varias respuestas. Por eso mismo en la configuración de la extensión te lo dice para evitar aquello o a su vez que no ocurra muy a menudo.

**Comment by Skygio** [comment]
@KasukeLp23 pero ese error es el **HTTP ERROR 429** y cuando se actualizan manualmente algunos mangas lanzan tambien el error **HTTP ERROR 403 ** al igual que al querer explorar y ver los recientes en la extencion

**Comment by edgarMejia** [comment]
Casi siempre esto es por muchas solicitudes al server, en la mayoria de casos se soluciona abriendo el webview y completando el recapcha.
