### ISSUE TITLE
[Source Request] <A Pair Of 2+>

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi-extensions#6892]
## https://pairof2.com/
- Name: A Pair Of 2+
- Link: https://pairof2.com/
- Language(s): English

## Other details
Their important releases: Dandadan, That Time I Got Reincarnated As A Slime.

**Comment by Riztard** [comment]
mangareader theme

**Comment by AlexMiniReal** [comment]
what does that mean?

**Comment by Riztard** [comment]
its for someone who will add the extension
