### ISSUE TITLE
[Bug] <sektedoujin>: <tidak dapat dibaca>

### ISSUE THREAD

**Issue by riyanm21** [tachiyomiorg/tachiyomi-extensions#6897]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 8

## Source information
- Name: sektedoujin
- Extension version: 1.2.4

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

## Other details
[](https://ibb.co/Y49fNNm)

**Comment by riyanm21** [comment]
https://i.ibb.co/hx52ggb/Screenshot-2021-05-08-17-17-37-833-eu-kanade-tachiyomi.jpg

**Comment by SanzXD** [comment]
Yeah same issue here on a10
