### ISSUE TITLE
[Feature Request] <hentaimimi>: <add search field on Filter menu>

### ISSUE THREAD

**Issue by annabenefiel90** [tachiyomiorg/tachiyomi-extensions#6899]
Currently this extension doesn't have a search field option, which require us to scroll and looking through the tags, artist.. one by one when filtering out.
Adding this feature would be useful cause one would just typing the tags that they want instead of scrolling one by one.

**Comment by CarlosEsco** [comment]
They don't offer search by tag on their website.. so it's not something we can add to the filter

**Comment by CarlosEsco** [comment]
Actually look it does and it already has the option so I don't know what you are asking for
