### ISSUE TITLE
[Source Request] <Pusu Pusu>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#6906]
## Source website
- Name: Pusu pusu scans
- Link: https://pusupususcans.wordpress.com/
- Language(s): English

**Comment by h-hyuuga** [comment]
Either your link is wrong, or wordpress shut them down in the last 30 minutes

**Comment by FireNation323** [comment]
> Either your link is wrong, or wordpress shut them down

Yea they said on Twitter that their website got taken out
