### ISSUE TITLE
[Source Request] <Get Comics>

### ISSUE THREAD

**Issue by Resadi** [tachiyomiorg/tachiyomi-extensions#6912]
---

## Source website
- Name: Get Comics
- Link: https://getcomics.info/
- Language(s): English

**Comment by alessandrojean** [comment]
Their online reader link in the posts points to `readcomicsonline.ru`, which already have an extension.

You can alternatively download their content and read through the [local source](https://tachiyomi.org/help/guides/local-manga/).
