### ISSUE TITLE
[Bug] Genkan.io: Tachiyomi crashes when trying to open genkan

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi-extensions#6925]
## Device information
- Tachiyomi version: SY r364
- Android version: 10

## Source information
- Name: genkan.io
- Extension version: 1.2.2

## Steps to reproduce
1. After update to the extension (#6919) 
2. Select Genkan.io to browse extension 

### Expected behavior
Should show titles in source 

### Actual behavior
Crashes Tachiyomi.

**Comment by CarlosEsco** [comment]
Just verified this is a bug with Sy.  So open an issue there
