### ISSUE TITLE
[Meta] <MangaDex> Automatically migrate library to UUIDs

### ISSUE THREAD

**Issue by gondolyr** [tachiyomiorg/tachiyomi-extensions#6931]
##  Why/Project's Benefit/Existing Problem

Currently the [MangaDex extension](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt) is throwing an error when attempting to load pages with the legacy numerical IDs ([MangaDex.kt#L182](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt#L182)).

It would be much more convenient for users if the [legacy ID mapping endpoint](https://api.mangadex.org/docs.html#operation/post-legacy-mapping) were used and automatically updated the entry in Techiyomi on behalf of the user.

I have two issues with the current approach:

1. I have greater than 350 favorited manga and having to migrate each one-at-a-time would place a significant burden on me.
2. The search functionality with MangaDex's API seems to be inaccurate the times I've used the migration feature of Tachiyomi using the updated MangaDex extension (1.2.109 at the time of filing this issue). When I go to migrate from MangaDex to MangaDex as I'm instructed, I'm often unable to find the same manga entry in the results.

## Other Details

None that I can think of.

**Comment by loocool2** [comment]
Don't think this will happen, however one of the contributors made a app that migrates MangaDex manga to UUIDs with the MangaDex given mappings. Should be ~100% accurate. 

https://github.com/ivaniskandar/tachiyomi-mangadex-migrator/releases/latest

**Comment by CarlosEsco** [comment]
Automigrate is not possible due to how things are saved in db and what can or can not be edited.

See loos answer for alternatives.
