### ISSUE TITLE
[Bug] <Fudido Scanlator>: Webview not working

### ISSUE THREAD

**Issue by dfantonio** [tachiyomiorg/tachiyomi-extensions#6933]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: Fudido Scanlator
- Extension version: 1.2.3

## Steps to reproduce
1. Open extensions page
2. Click on Fudido Scanlator
3. Open on the webview icon

### Expected behavior
The webview should open the scan website

### Actual behavior
The webview is opening a gif

## Other details
I don't know if it is related or not, but when I try to search for "class suicide hunter" or just "class" or "suicide" the search shows 0 results, even thought when I search using the scan's website I find the [manga](https://fudidoscan.com/manga/sss-class-suicide-hunter/)

I asked for the creation of this source a few days ago (#6845) , but just now I found this bug

**Comment by dfantonio** [comment]
Thanks for the quick response.

E um salve, pq acabei de ver q tu tbm é brasileiro hsuahusuahsuh

**Comment by alessandrojean** [comment]
This issue can be closed now, as it's not a problem with the extension.
