### ISSUE TITLE
[Bug] GMANGA: Invalid index 8 size is 7

### ISSUE THREAD

**Issue by M7mdTl3t** [tachiyomiorg/tachiyomi-extensions#6941]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 6.0.1

## Source information
- Name: GMANGA
- Extension version: 1.2.4

## Steps to reproduce
1. Open gmanga source
2. Open any manga page

### Expected behavior
Under the manga page there should be the chapters that are uploaded on gmanga.me

### Actual behavior
There are no chapters showing on the manga page and no matter how many times I refresh the the manga page I get the error "invalid index 8 size is 7

## Other notes
I'm using tachiyomiSY but I tried to uninstall it and try tachiyomi and tachiyomiJ2K but I'm facing the Same issue 
 I've been using that extension a lot so I have some manga in my Library so i noticed that i can read the chapters that already shown before I get that error without any issues
Also when open the manga page in webview I shows the chapters but when I get back nothing change

**Comment by CrepeTF** [comment]
#6852

**Comment by saidsahra15** [comment]
Me to
