### ISSUE TITLE
[Bug] Shinzoo Scan: No load manga list

### ISSUE THREAD

**Issue by danrleylfd** [tachiyomiorg/tachiyomi-extensions#6949]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.2

## Source information
- Name: Shinzoo Scan
- Extension version: 1.2.5

## Steps to reproduce
1. Tap shinzoo source
2. Tap Reload

Actual behavior
![Screenshot_2021-05-10-08-42-56.png](https://user-images.githubusercontent.com/61889582/117654674-76a45e80-b16c-11eb-9928-38346156ea6c.png)
![Screenshot_2021-05-10-08-43-01.png](https://user-images.githubusercontent.com/61889582/117654686-7b691280-b16c-11eb-9107-34e70ffcd25a.png)

## Other details
pt-BR

**Comment by alessandrojean** [comment]
This looks like a site error related to their HTTPS certificate, maybe it expired.

**Comment by alessandrojean** [comment]
Yep, I checked here, and it's a problem on their side, and there isn't a way to fix in the extension because using only HTTP redirects to HTTPS which is broken currently. You can wait until they fix this or migrate to another source.

**Comment by alessandrojean** [comment]
This can be closed since it's a problem with the site and not with the extension.
