### ISSUE TITLE
Please delete this issue.

### ISSUE THREAD

**Issue by josephbekedamguidewire** [tachiyomiorg/tachiyomi-extensions#6953]
Please delete this issue, I used the wrong github account.

**Comment by jobobby04** [comment]
TachiyomiEH is deprecated, use one of the continuation forks such as SY or AZ

**Comment by loocool2** [comment]
Known issue. TachiyomiEH has been deprecated and unmaintained for over 2 years now. These extensions depend on things not found in TachiyomiEH anymore

**Comment by jobobby04** [comment]
https://github.com/ivaniskandar/tachiyomi-mangadex-migrator/releases/latest

**Comment by josephbekedamguidewire** [comment]
Thank you. Do you mind deleting this issue? I posted it under the wrong github account.
