### ISSUE TITLE
[Source Request] Some Vietnamese site

### ISSUE THREAD

**Issue by gonz1324** [tachiyomiorg/tachiyomi-extensions#6973]
## Cứu truyện
![image](https://user-images.githubusercontent.com/63002225/117851895-f8050980-b2b0-11eb-8a6d-239a01363f79.png)
### Link: cuutruyen.net
- Usually translate dropped manga
## Vlogtruyen
![image](https://user-images.githubusercontent.com/63002225/117852474-8da09900-b2b1-11eb-8081-81080f5b01a0.png)
### Link: vlogtruyen.com
- Have manga, a lot of webtoons, manhwa and manhua
## TruyenTranh8
![image](https://user-images.githubusercontent.com/63002225/117854790-056fc300-b2b4-11eb-867d-73c8cd59b0fb.png)
### Link: truyentranhtam.com
- Have some nice 18+ manhwa
## TruyenVN
![image](https://user-images.githubusercontent.com/63002225/117855618-da39a380-b2b4-11eb-86e0-7c2716f22631.png)
### Link: truyenvn.com
- Have a lot of mature manga/manhwa

**Comment by CarlosEsco** [comment]
1 request per a ticket, make sure a request doesnt already exist
