### ISSUE TITLE
[Source Request] Vlogtruyen

### ISSUE THREAD

**Issue by gonz1324** [tachiyomiorg/tachiyomi-extensions#6975]
![image](https://user-images.githubusercontent.com/63002225/117852474-8da09900-b2b1-11eb-8081-81080f5b01a0.png)
### Link: vlogtruyen.com
- Language: Vietnamese
- Have manga, a lot of webtoons, manhwa and manhua

**Comment by jopejoe1** [comment]
Domain Parked
