### ISSUE TITLE
[Bug] <Gmanga>: <It doesn't appear chapters>

### ISSUE THREAD

**Issue by iRahmaniMed** [tachiyomiorg/tachiyomi-extensions#6980]
Device information
- Tachiyomi version: 0.10.12
- Android version: 10

Source information
- Name: Gmanga
- Extension version: 1.2.4

**Comment by iRahmaniMed** [comment]
I searched and I found three persons wrote about that, I spend 6 days without solution So I thought that if I pressed you, you might solve the problem

**Comment by CarlosEsco** [comment]
This is a free and open source repository and welcomes any contributions.   Feel free to fix it and open a pull request
