### ISSUE TITLE
[Bug] <NEOX>: <NÃO ABRE>

### ISSUE THREAD

**Issue by Zedrike** [tachiyomiorg/tachiyomi-extensions#6990]
Neox não tá abrindo pois aparentemente há alguma palhaçada da parte deles denovo :( teu trabalho é muito foda amigo q criou esse app. Vc merece o mundo parabéns ❤️.

**Comment by alessandrojean** [comment]
Eles mudaram a URL por acaso? Posso dar uma olhada.

Eu não criei o app, sou apenas um dos colaboradores. Por favor, preencha o template da Issue correta e completamente na próxima vez.

**Comment by alessandrojean** [comment]
Testei agora e está funcionando normalmente, provavelmente pode ser algum problema com a sua conexão ou o seu provedor de acesso. Tente realizar todos os procedimentos de [solução de problemas](https://tachiyomi.org/help/guides/troubleshooting/), e caso ele não se resolva, peça ajuda no canal #support no Discord.

**Comment by alessandrojean** [comment]
This issue can be closed as the source it's working fine and it's probably a connection issue from the user.

**Comment by Douglasimav** [comment]
> This issue can be closed as the source is working fine and it's probably a connection issue from the user.

it seems that neox changed the url of the manga, solo leveling is giving error 404

**Comment by alessandrojean** [comment]
@Douglasimav You can migrate from Neox to Neox to update the manga URL to the new one. Nothing the extension can do to fix if they keep changing the manga URL.
