### ISSUE TITLE
[Bug] Ae: Gmanaga: Empty chapters list

### ISSUE THREAD

**Issue by yshalsager** [tachiyomiorg/tachiyomi-extensions#6991]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11.0

## Source information
- Name: Gmanga
- Extension version: 1.2.4

## Steps to reproduce
1. Open any manga from Gmanga

### Expected behavior
Chapters should be there.

### Actual behavior
Chapters list is empty, an error toast appears "Index 8, Size 7" or an empty toast.

## Other details
I have tried to check gmanaga response, it seems that their API response data has changed.
Here's an example of what the latest response looks like:
https://0bin.net/paste/1PLbhqh4#-gGRNtwmNv0YnEjZqspOSjxcFT9ld42fCzHm+EHh0MT

@clarencecastillo You may want to check out this.

**Comment by arkon** [comment]
#6852

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues?q=is%3Aissue+is%3Aopen+gmanga

**Comment by yshalsager** [comment]
> [https://github.com/tachiyomiorg/tachiyomi-extensions/issues?q=is%3Aissue+is%3Aopen+gmanga](https://github.com/tachiyomiorg/tachiyomi-extensions/issues?q=is%3Aissue+is%3Aopen+gmanga+sort%3Aupdated-desc)

I did search before I create one nothing appeared. This is weird, anyways thanks and sorry for the duplicate one :D
