### ISSUE TITLE
[Bug] GMANGA: Chpaters sort not correct

### ISSUE THREAD

**Issue by AyEdAlH** [tachiyomiorg/tachiyomi-extensions#6993]
## Device information
- Tachiyomi version: 0.10.12-3354 (standard, 47c120e5, 60)
- Android version: 10

## Source information
- Name: GMANGA
- Extension version: 1.2.5

## Steps to reproduce
1. Join any manga/manhua
2. Look at the chapters order (by source)

### Expected behavior
the sort by source should be like the website, by volumes and chapters numbers

### Actual behavior
Randomly and not sorted well, i have to sort it manually for some reason.

**Comment by hakudansho** [comment]
![Screenshot_2021-05-12-20-48-33-56_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/75262438/118029285-4de6b980-b364-11eb-8930-a91683b7b1f9.jpg)
@ @

**Comment by hakudansho** [comment]
The order of chapters has changed 🤦🏻🤦🏻

**Comment by hakudansho** [comment]
Another falut that despite i have already downloaded all the chapters they won't open inside 
![Uploading IMG_20210513_030112.jpg…]()

**Comment by hakudansho** [comment]
![Uploading IMG_20210513_030112.jpg…]()

**Comment by hakudansho** [comment]
![IMG_20210513_030112](https://user-images.githubusercontent.com/75262438/118062884-40e3bd80-b398-11eb-98af-250e0f8dfefc.jpg)

**Comment by AyEdAlH** [comment]
no i'm not facing that issue
