### ISSUE TITLE
[Bug] <Inmanga (Spanish)>: <inmanga does not load any chapter of any manga in the library>

### ISSUE THREAD

**Issue by FedeeMartinez** [tachiyomiorg/tachiyomi-extensions#6997]
---

## Device information
- Tachiyomi version: TachiJ2K 1.0.17
- Android version: 9

## Source information
- Name: Inmanga
- Extension version: 1.2.1

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
when entering a chapter it should load the content as it did before

### Actual behavior
when I enter a chapter of any manga that I have saved from the Inmanga extension, only the option "retry" appears, while with the rest of the sleeves of different extensions, the same does not happen to me

## Other details
This did not happen to me with an update, it was without installing something previously, when entering the web the manga load correctly but not in the app

**Comment by TuTrolloLove** [comment]
I have this problem too.

Android version: 10
Tachiyomi version: TachiyomiJ2K 1.0.17 and Tachiyomi0.10.12 (i tried with both)

I will add that in my case i can't see any manga and i can't download either

**Comment by ComplexCodegit** [comment]
Same problem..

Tachiyomi version: 0.10.12
Android version: 7.1.1

Clarify that this problem in my case is not associated with any type of update, it just stopped working from one moment to another.

**Comment by AngelGlz99** [comment]
I have the same problem

Suddenly it stopped loading the manga, I thought that with an update it would be fixed but the problem continues.

Tachiyomi version: 0.11.1
Android version: 10 QPA1A.190711.020
