### ISSUE TITLE
Manhuwascans "no pages found" error

### ISSUE THREAD

**Issue by SleepyCap** [tachiyomiorg/tachiyomi-extensions#7005]
## Device information
* Tachiyomi version: v0.10.12
* Android version: 
* Device: Amazon fire

## Source information
* Source name: Manhuwascans
* Source extension version: 1.2.4

## Steps to reproduce
1. Open any chapter
2. Wait

## Issue/Request
Whenever I try to open any chapter, all I get is the "no pages found" error. Opening it in Web mode is fine,

**Comment by yasnil03** [comment]
same error with me. No pages found

**Comment by rururubie** [comment]
I think we need to wait to fix it by the moderator 🥲

**Comment by arkon** [comment]
#7011

**Comment by ronniejovelo** [comment]
Heroscan too, maybe theres some issues btwn tachiyomi and the server of manwhua whatever...
