### ISSUE TITLE
[Bug] <mangadex>: <http error 410>

### ISSUE THREAD

**Issue by itiswhatitseems** [tachiyomiorg/tachiyomi-extensions#7014]
## Device information
- Tachiyomi version: 1.5.0
-  Android version: 10

## Source information
- Name: mangadex
- Extension version: latest

## Steps to reproduce
1. First Step opening mangadex extenstion
2. Second Step getting http error 410

### Expected behavior
Describe what should have happened should have opened up

### Actual behavior
Describe what happens instead getting the error on the bottom

**Comment by plW0lf** [comment]
Unable to reproduce on latest (1.2.111) version of extension. More information needed.

**Comment by CarlosEsco** [comment]
gonna close.  in the future actually put the extension version nubmer two and what you were doing
