### ISSUE TITLE
[Bug] <NineHentai>: <http error 405>

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#7016]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: NineHentai
- Extension version: 1.2.9

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Manga should show

### Actual behavior
![Screenshot_20210514-005400_Tachiyomi.jpg](https://user-images.githubusercontent.com/59638889/118223410-3a644d00-b44f-11eb-989f-581308f1698e.jpg)

**Comment by plW0lf** [comment]
The cause is change in html address (from 9hentai.ru to www1.9hentai.ru)
