### ISSUE TITLE
[Bug] <Manhuascan>: <Chapters won't open and download>

### ISSUE THREAD

**Issue by lol10011996** [tachiyomiorg/tachiyomi-extensions#7018]
---

## Device information
- Tachiyomi version: 0.10.12
- Android version: 8.1.0

## Source information
- Name: Manhuascan
- Extension version: 1.2.4

## Steps to reproduce
1. Open/download any manga

### Expected behavior
The chapters will load and can read normally

### Actual behavior
The chapters are not loading/won't open. Can't also download any chapters

**Comment by Seishirou101** [comment]
please search before posting. probably related to #7011
