### ISSUE TITLE
[Bug] <Heroscans>: <cant read manga from this extension>

### ISSUE THREAD

**Issue by waterlover6969** [tachiyomiorg/tachiyomi-extensions#7023]
## Device information
- Tachiyomi version: v 0.10.12
- Android version: v 10

## Source information
- Name: Heroscans
- Extension version: v 1.2.3

## Steps to reproduce
1. Open the extension 
2. Click and open a manga

### Expected behavior
I should have been able to read the manga

### Actual behavior
It said "no pages found"

## Other details
Started happening yesterday

**Comment by CrepeTF** [comment]
#7013
