### ISSUE TITLE
[Bug] Mangakawaii: No pages found

### ISSUE THREAD

**Issue by Psykomat** [tachiyomiorg/tachiyomi-extensions#7030]
## Device information
- Tachiyomi version: 0.10.12(standard, 6aff438, 59)

- Android version: 10 (sdk 29) 

## Source information
- Name: Mangakawaii
- Extension version: 1.2.30

## Steps to reproduce
1. Click on a chapter

### Expected behavior
Load and Read some scan

### Actual behavior
No pages found error

**Comment by papjul** [comment]
It's probably because they changed their url from .com to .net
