### ISSUE TITLE
[Bug] <Manhuascan>: i can't read any manga from this source

### ISSUE THREAD

**Issue by Blacklist97** [tachiyomiorg/tachiyomi-extensions#7031]
## Device information
- Tachiyomi version: 1.0.17
- Android version: 10

## Source information
- Name: manhuascan
- Extension version: 1.2.4

## Steps to reproduce
1. Open the source
2. Select the manga and read it 

### Expected behavior
You should be able to read the chapters without problem

### Actual behavior
I can't read any manga, because when I open the chapters it tells me "no pages found"

## Other details
I tried go to the webview and everything works on the site
i also tried to download the source again but nothing has changed

**Comment by loocool2** [comment]
Duplicate of #7011

**Comment by Blacklist97** [comment]
> Duplicate of #7011
Oh thanks!
I guess we'll have to wait for the moderator to fix it

**Comment by athea08** [comment]
I hope that they can fix it . manhuascan is the best extension
