### ISSUE TITLE
Tachiyomi- extension * Manhuascan * doesn't work intachiyomi app Even the website is fine 

### ISSUE THREAD

**Issue by athea08** [tachiyomiorg/tachiyomi-extensions#7034]
![2A0F5C18-A90A-47B7-9D5E-DD965B7049D1](https://user-images.githubusercontent.com/84158024/118195506-30ffc400-b400-11eb-9b15-b281aff2c39a.jpeg)

Similar issue. Web preview is fine and the updates, do update. However, when resuming reading, “No Pages Found”.

_Originally posted by @smanunciacion in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7011#issuecomment-840872758_

**Comment by loocool2** [comment]
#7011

**Comment by ronniejovelo** [comment]
![Screenshot_20210515_005110](https://user-images.githubusercontent.com/84239882/118368554-0fa40100-b5d5-11eb-928e-5a8e87cfe147.jpg)
Same issue here

**Comment by athea08** [comment]
> ![Screenshot_20210515_005110](https://user-images.githubusercontent.com/84239882/118368554-0fa40100-b5d5-11eb-928e-5a8e87cfe147.jpg)
> Same issue here
 Yes, Hope they can fix it! Manhuascan is the best extension ever

**Comment by athea08** [comment]
Yes, hope they can fix it! Manhuascan is best extension ever

**Comment by rururubie** [comment]
Hope they can fix it tomorrow,😅
