### ISSUE TITLE
[Source Request] tusmangasonline

### ISSUE THREAD

**Issue by FelipeG99** [tachiyomiorg/tachiyomi-extensions#7037]
- Name: tusmangasonline
- Link: http://tusmangasonline.com/
- Language(s): Spanish, Español

Other details:
I have noticed that it has much more updated sleeves than the extensions that currently exist.
He notado que tiene mangas mucho mas actualizados que las extenciones que hay actualmente
![Captura](https://user-images.githubusercontent.com/84248887/118377068-41937400-b591-11eb-9419-9c9aaa9eac88.PNG)

**Comment by vetleledaal** [comment]
Redirects to https://tumangaonline.online/ , which is also the same as in #8314
