### ISSUE TITLE
[Bug] <tumangaonlien>: <http error 403>

### ISSUE THREAD

**Issue by slendcraft** [tachiyomiorg/tachiyomi-extensions#7044]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 6

## Source information
- Name: tumangaonline
- Extension version: tumangaonline

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Load the tumangaonline extension

### Actual behavior
Http error 403

## Other details
N-I alrady waited like 2 days but it dosent load

**Comment by alessandrojean** [comment]
Seems to be a duplicate of #6888.
