### ISSUE TITLE
[Bug] <Kiryuu>: <change domain>

### ISSUE THREAD

**Issue by Ayanokouji-kun** [tachiyomiorg/tachiyomi-extensions#7053]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.1

## Source information
- Name: Kiryuu
- Extension version: 1.2.4

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Kiryuu change domain from kiryuu.co to kiryuu.id

### Actual behavior
Change source kiryuu from domain kiryuu.co to kiryuu.id

## Other details

**Comment by Riztard** [comment]
duplicate of #6989
