### ISSUE TITLE
[Bug] ManhuaScan: Error Bad Decrypt

### ISSUE THREAD

**Issue by allishona** [tachiyomiorg/tachiyomi-extensions#7054]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 11

## Source information
- Name: ManhuaScan
- Extension version: 1.2.6 

## Steps to reproduce
1. Click on Resume
2. Open/Resume Chapter

### Expected behavior
It should open and/or resume the manga/manhua.

### Actual behavior
Forced closed. Showing Error. Open SSL
Internal_Bad Decrypt.

## Other details
[Screenshot_20210516-230304_Tachiyomi](https://user-images.githubusercontent.com/84158024/118440234-3416e080-b69c-11eb-90f6-71860ead0e7c.jpg)

**Comment by allishona** [comment]
![Screenshot_20210516-230304_Tachiyomi](https://user-images.githubusercontent.com/84158024/118440728-f49cc400-b69c-11eb-934e-89d32d4d74b6.jpg)

**Comment by rururubie** [comment]
What does it mean???

**Comment by akey2096** [comment]
same problem, manga won't download

**Comment by lol10011996** [comment]
it was resolved then the same issue occured again. Can't open/download any chapters

**Comment by SleepyCap** [comment]
Yep, same issue here.

**Comment by arkon** [comment]
Reminder that "+1" style comments are considered spam and non-productive.
