### ISSUE TITLE
[Bug] Heroscan: Error Bad Decrypt 

### ISSUE THREAD

**Issue by synticalx** [tachiyomiorg/tachiyomi-extensions#7055]
## Device information
- Tachiyomi version: v0.10.12
- Android version: 11

## Source information
- Name: HeroScan
- Extension version: 1.2.5

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Page to load and appear.

### Actual behavior
Page force closed, with a tag stated, error: 1e000065: Cipher functions: OPENS SL_internal:BAD_DECRYPT 

## Other details
![Screenshot_20210517-141155_Tachiyomi](https://user-images.githubusercontent.com/84307394/118441486-d7f3a100-b71b-11eb-8fa4-ee44960bc47a.jpg)

**Comment by athea08** [comment]
Same issue here 😌
But yesterday it's fixed and again I need to wait to fix it😭
