### ISSUE TITLE
[Feature Request] <Tsuki Mangás>: <Add more filter options>

### ISSUE THREAD

**Issue by MarcosSouza2004** [tachiyomiorg/tachiyomi-extensions#7056]
## What feature should be added to this source?
Add the others filters to the extension: 
![image](https://user-images.githubusercontent.com/76596575/118466754-888c8100-b6d9-11eb-97c6-fd80f40afb1f.png)
The ones with the red "X"

**Comment by alessandrojean** [comment]
This seems to be new, I will take a look later.
