### ISSUE TITLE
[Bug] <Komiku>: <Took a long time to load image>

### ISSUE THREAD

**Issue by Ayanokouji-kun** [tachiyomiorg/tachiyomi-extensions#7060]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 7.1.1

## Source information
- Name: Komiku
- Extension version: 1.2.12

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
It doesn't take long time for images to load

### Actual behavior
It doesn't take long time for images to load

## Other details
all manga/hwa/hua from extension Komiku it took a long time to load the image, even though my connection is stable

- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/

**Comment by Riztard** [comment]
you mean infinity loading? or does it even load?
