### ISSUE TITLE
[Feature Request] add icon for some extension

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi-extensions#7080]
skymanga, mangazuki.me, manhwahentai.me, manytoon, milftoon, porncomix please add icon for these thnx

**Comment by joseph619** [comment]
@as280093

**Comment by as280093** [comment]
[porncomix.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511445/porncomixio.zip)
[milftoon.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511446/milftoon.zip)
[ManyToon.me.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511447/ManyToon.me.zip)
[ManyToon.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511448/ManyToon.zip)
[ManhwaHentai.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511449/ManhwaHentai.zip)
[MangaZuki.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511450/MangaZuki.zip)
[SkyManga.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6511451/SkyManga.zip)
@joseph619
