### ISSUE TITLE
[Source Request] <tales of demons and gods> <question more than it is source request>

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi-extensions#7082]
## Source website
- Name: Tales of Demons and Gods
- Link: https://taleofdemonsandgods.com/
- Language(s): English

## Other details

This website only has 2 manga, and I don't believe it follows any of the previously created generators/sources (i.e. madara/factory source, for example), so I do believe it' be pointless to request a source for just two manga that can be found on other extensions. 

If you can do it, that'd be great though.

The main question: Is there any easy way to simply download/find the sources that it links to through the website so that the manga can be downloaded? I.e. If the embed links to google drive, is there a way to get that information and then download it?

**Comment by CrepeTF** [comment]
You'd be correct, the single entry sources were added since they used a website template, this made it easy to add them.

There's no such advantage for this site.

**Comment by loocool2** [comment]
Closed due to being a single manga site not based on any factory source
