### ISSUE TITLE
[Bug] ManhuaScan: displaying HTTP error 500

### ISSUE THREAD

**Issue by ladysoftlighting** [tachiyomiorg/tachiyomi-extensions#7088]
## Device information
- Tachiyomi version: 0.10.12 
- Android version: 11 (SDK 30)

## Source information
- Name: ManhuaScan
- Extension version: 1.2.7

## Steps to reproduce
1. Open book in library
2. Open chapter in book

### Expected behavior
Chapter should load and display 

### Actual behavior
Chapter pages do not load. "HTTP error 500" displays on screen 

## Other details
![Screenshot_20210519-031419_Tachiyomi](https://user-images.githubusercontent.com/84220100/118771856-0626cd00-b851-11eb-8f6a-83ffe6acaec0.jpg)

**Comment by ladysoftlighting** [comment]
Update: it is displaying a different error message now. Screenshot linked 
![Screenshot_20210519-032606_Tachiyomi](https://user-images.githubusercontent.com/84220100/118772687-05db0180-b852-11eb-94ad-ec72fe4262e8.jpg)

**Comment by bone-d** [comment]
Had the latest issue too 
![Screenshot_20210519_172539_eu kanade tachiyomi](https://user-images.githubusercontent.com/84444998/118789899-d1a22800-b8c7-11eb-99b6-3a4d34da7c7c.jpg)

**Comment by allishona** [comment]
![Screenshot_20210519-024932_Tachiyomi](https://user-images.githubusercontent.com/84158024/118792966-002eed00-b84d-11eb-9467-7672dd692e9e.jpg)
