### ISSUE TITLE
Nhentai Failed to Connect [Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by Drakoney** [tachiyomiorg/tachiyomi-extensions#7089]
---
## Device information
- Tachiyomi version: App version: 0.10.12 (standard, 6aff438, 59)
- Android version: 5.1.1 (SDK 22)

## Source information
- Name: Nhentai
- Extension version: 1.2.28
![Screenshot_2021-05-19-15-32-34](https://user-images.githubusercontent.com/84439474/118774424-67ce5200-b8b8-11eb-9313-57ea27505d7d.png)

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by loocool2** [comment]
If you're in the Phillipines, PLDT is currently blocking nhentai, which has nothing to do with us. You can try enabling DNS over HTTPS, but if that doesn't work, you'll need to use a VPN

**Comment by Drakoney** [comment]
How to enable DNS over HTTPS? @loocool2

**Comment by loocool2** [comment]
More  →  Settings  → Advanced

**Comment by Drakoney** [comment]
Thanks for the help bro
