### ISSUE TITLE
[Bug] <Jinmantiantang>: <Error 429 when updating library>

### ISSUE THREAD

**Issue by XeroxV** [tachiyomiorg/tachiyomi-extensions#7090]
## Device information
- Tachiyomi version: Stable 1.6.2
- Android version: 11

## Source information
- Name: Jinmantiantang （禁漫天堂）
- Extension version: 1.2.11

## Steps to reproduce
1. Update the manga from this source

### Expected behavior
Chapters should be updated

### Actual behavior
Error 429

**Comment by CarlosEsco** [comment]
Sounds like this source needs rate limiting added to it
