### ISSUE TITLE
[Bug] <Manhuascan>: <display error>

### ISSUE THREAD

**Issue by athea08** [tachiyomiorg/tachiyomi-extensions#7095]
Device information

Tachiyomi version: 0.10.12
Android version: 11 (SDK 30)

Source information

Name: ManhuaScan
Extension version: 1.2.7

Steps to reproduce

•Open book in library
•Open chapter in book

Expected behavior
Chapter should load and display

Actual behavior
Chapter pages do not load. "gson.stream. MalformedJsonEx caption: use JsonReader setlineint(true) to accept Malformed JSON at line 1 column 64
![Screenshot_2021-05-19-21-01-48-12_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/84239349/118819667-22c21400-b8e8-11eb-8d66-f29908a9a372.jpg)

**Comment by arkon** [comment]
#7088
