### ISSUE TITLE
[Bug] <darkyue realm>: <error 404n>

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#7102]
App version: 0.10.12-3368 (standard, 09c07faa, 60)
Android version: 11 (SDK 30)
Android build ID: RQ2A.210405.005
Device brand: POCO
Device manufacturer: Xiaomi
Device name: surya
Device model: M2007J20CG
Device product name: surya_global

## Source information
- Name: darkyu realm 
- Extension version:  1.2.5

## Steps to reproduce
1. open the extension

### Expected behavior
load the manga

### Actual behavior
error 404

**Comment by alessandrojean** [comment]
Sounds like the source changed the manga URL, did you try to migrate the manga from the source back to the source to update the URL and check if is working after that?

**Comment by Douglasimav** [comment]
> Parece que a fonte mudou a URL do mangá. Você tentou migrar o mangá da fonte de volta para a fonte para atualizar a URL e verificar se está funcionando depois disso?

in this case it's not a problem in the manga url, the site changed the url

**Comment by alessandrojean** [comment]
It looks like they added a path to the URL, I will add it to the extension.

**Comment by alessandrojean** [comment]
I submitted a fix. When the update is available, and you've installed it, you will still need to migrate your entries in your library back to the source to update the URL, though.
