### ISSUE TITLE
[Bug] HeroScan: forced closed problem

### ISSUE THREAD

**Issue by synticalx** [tachiyomiorg/tachiyomi-extensions#7107]
## Device information
- Tachiyomi version: v0.10.12 
- Android version: 11

## Source information
- Name: HeroScan 
- Extension version: 1.2.6 

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
The page would load

### Actual behavior
Page forced closed, with an box stating "com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON
at line 1 column 97 path $"

## Other details
Only HeroScan seems to have this issue for me. NineManga works fine.
![Screenshot_20210519-224113_Tachiyomi](https://user-images.githubusercontent.com/84307394/118864561-aee93100-b912-11eb-8a30-255d35c9416a.jpg)

**Comment by CrepeTF** [comment]
They are actively blocking the Tachiyomi extension. 

The extension will be deleted, migrate to another source.

Same issue with Manhuascan and Manhwahot too

**Comment by SaeranC** [comment]
> They are actively blocking the Tachiyomi extension.
> 
> The extension will be deleted, migrate to another source.
> 
> Same issue with Manhuascan and Manhwahot too

Is it really?
