### ISSUE TITLE
[Feature Request] ManhuaScan: Changes to genres list

### ISSUE THREAD

**Issue by INSANEMODE** [tachiyomiorg/tachiyomi-extensions#7111]
## What feature should be added to this source?
additions, removals, and spelling corrections of genres in the filter menu.

---
genres that don't exist:
18+
Anime
Live Action

genres that are misspelled:
Shojou Ai (should be renamed to Shoujo Ai)

genres that need to be added:
4-Koma
Isekai
Yuri
Cooking
Lolicon
Medical
Music
Webtoon

---
Explain why this should be added

For a search experience that is closer to what you can do on the website.

**Comment by paulo27ms** [comment]
Extension is broken and likely won't be fixed. So seems a bit pointless to fix this.

**Comment by INSANEMODE** [comment]
Ah, I just saw the issue. That's unfortunate.

**Comment by bone-d** [comment]
> Extension is broken and likely won't be fixed. So seems a bit pointless to fix this.

Aw damn, it was one of the best extensions I ever used.

**Comment by AlexXmira** [comment]
Is manhuascan will be fix soon???
It's been 4 days and all my manga's are from manhuascan

**Comment by SaeranC** [comment]
Theres A Comment on issued for heroscan (same extension as manhuascan) that they were forcefully not to associate with tachiyomi so the manhuascan extension might get deleted better to migrate it to other extension

**Comment by theronnie602** [comment]
Anyone got any good recommendations for alternatives to manhuascan? Seeing as it's probably going to go down
