### ISSUE TITLE
[Bug] Gmanga: Download Failed

### ISSUE THREAD

**Issue by motsouzumaki** [tachiyomiorg/tachiyomi-extensions#7113]
---

## Device information
App version: 0.10.12-3368 (standard, 09c07faa, 60)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.M105FDDS4CTL2
Device brand: samsung
Device manufacturer: samsung
Device name: m10lte
Device model: SM-M105F
Device product name: m10ltedd

## Source information
- Name: Gmanga
- Extension version: 1.2.5

## Steps to reproduce
1. Choose any manga
2. Read or download any chapter

### Expected behavior
I can read or download normally

### Actual behavior
Loading remains pending and does not progress + read failure

## Other details
(The problem appears especially in the latest added chapters)
![Screenshot_20210520-063022_Tachiyomi](https://user-images.githubusercontent.com/68796249/118931744-d0f4aa80-b936-11eb-9383-a7ddee189f75.jpg)
![Screenshot_20210520-064036_Tachiyomi](https://user-images.githubusercontent.com/68796249/118931748-d225d780-b936-11eb-99a3-d119b7eebe2b.jpg)

**Comment by shipoxx** [comment]
#6992
Issue has been solved.
