### ISSUE TITLE
[Source Request] <Mangago>

### ISSUE THREAD

**Issue by SaeranC** [tachiyomiorg/tachiyomi-extensions#7114]
---

## Source website
- Name: Mangago
- Link: Mangago.me
- Language(s): english

## Other details
Mangago is one of the best to read a manga it updates everyday and it has a lot of manga theres that you couldn't see in any other manga sites

**Comment by SaeranC** [comment]
> Most of the manga in Manhuascan are pulled from Mangago.me.

Yeah but manhuascan is always down also theres some missing chapters

**Comment by allishona** [comment]
> > Most of the manga in Manhuascan are pulled from Mangago.me.
> 
> Yeah but manhuascan is always down also theres some missing chapters

Lol, I'm agreeing with you about adding this extension. I'm saying that manhuascan is getting their manga from mangago.me

Just to add details about why they should add this extension. Because it is the source of manhuascan anyway. XD

**Comment by Akazotik** [comment]
> > > Most of the manga in Manhuascan are pulled from Mangago.me.
> > 
> > Yeah but manhuascan is always down also theres some missing chapters
> 
> Lol, I'm agreeing with you about adding this extension. I'm saying that manhuascan is getting their manga from mangago.me
> 
> Just to add details about why they should add this extension. Because it is the source of manhuascan anyway. XD

-![Screenshot_2021-05-20-11-18-23-615_com.github.android.jpg](https://user-images.githubusercontent.com/39062952/118944318-217efe80-b95d-11eb-9214-9def6a76bef2.jpg)

So they won't add mangago.

**Comment by loocool2** [comment]
ManhuaScan's been giving us a lot of issues so we'll likely end up removing manhuascan as well

**Comment by Akazotik** [comment]
> ManhuaScan's been giving us a lot of issues so we'll likely end up removing manhuascan as well

So what about this extention. Or you won't add it like it said in previous issue?

**Comment by loocool2** [comment]
Yes, this source won't be added. The issue is that it scrambles the images in multiple different ways we can't account for, and that changes frequently.

**Comment by loocool2** [comment]
We try our best but extensions and developers have their limitations

**Comment by SaeranC** [comment]
> We try our best but extensions and developers have their limitations

How about the new mangadex the mangadex.tv?
