### ISSUE TITLE
[Source Request] Vietnamese Source - Nettruyentop

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#7121]
## Source website
- Name: Nettruyentop
- Link: http://www.nettruyentop.com/
- Language(s): Vietnamese

**Comment by Huynh12345678** [comment]
Cái source này có rồi mà?

**Comment by buinguyenhoangtho** [comment]
> Cái source này có rồi mà?

Source cũ không còn sử dụng được bác ơi. Đổi sang url khác rồi.

**Comment by Huynh12345678** [comment]
> > Cái source này có rồi mà?
> 
> Source cũ không còn sử dụng được bác ơi. Đổi sang url khác rồi.

cái nhattruyen, truyenchon, nettruyen là 1 , giống nhau hết thôi

**Comment by DejaSentj** [comment]
tình hình là 2 hôm nay không dùng được nhattruyen các bác có thể kiểm tra dùm ko?

**Comment by long21wt** [comment]
> tình hình là 2 hôm nay không dùng được nhattruyen các bác có thể kiểm tra dùm ko?
Mình confirm là không dùng được nhattruyen nettruyen cũng như truyenchon lỗi 403
Cách fix là đổi url khi send request ở trong các file liên quan đến các extension này

**Comment by Makro297** [comment]
extension NetTruyen hình như vẫn bị lỗi 403 chưa fix thì phải ?

**Comment by vetleledaal** [comment]
Appears to use WPComics, but latest and search needs some work
