### ISSUE TITLE
[Bug] JMana: 404 Error

### ISSUE THREAD

**Issue by jcha1600** [tachiyomiorg/tachiyomi-extensions#7127]
---

## Device information
- Tachiyomi version: v8.6.4-AZ
- Android version: 9(One UI 1.0)

## Source information
- Name: JMana
- Extension version: 1.2.11

## Steps to reproduce
1. Go to [Sources].
2. Scroll down to [한국어] and tap [JMana].

### Expected behavior
List of mangas should appear

### Actual behavior
HTTP error 404: Check website in WebView

**Comment by Seishirou101** [comment]
did you match the number?
> Some Korean sources use numbered domains (e.g. newtoki55.com) that change every 7-10 days. Use extension settings to change that source's domain to the current number.

**Comment by jcha1600** [comment]
Upon closer inspection, I noticed that the default BaseURL was set to 003.jmana2.net but that URL was down and the working URL is jmana1.net. But I still get it to work in app(works fine on WebView)
