### ISSUE TITLE
[Bug] <Manhua Scan>: <malformedJsonException>

### ISSUE THREAD

**Issue by Arthur-Leywin** [tachiyomiorg/tachiyomi-extensions#7131]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: Manhuascan
- Extension version: 1.2.7

## Steps to reproduce
1. Choose any manga
2. Read/download any chapter

### Expected behavior
Able to access Manhuascan extension

### Actual behavior
A pop-up came out which disallowed me to read any chapter in the extension.
![Screenshot_2021-05-20-09-36-23-094_eu kanade tachiyomi](https://user-images.githubusercontent.com/84531965/119018765-08af3100-b9cf-11eb-8a1e-59627e3495ed.jpg)

## Other details
I have uninstall and reinstall the extension, but same thing still persists.

**Comment by alessandrojean** [comment]
This extension will be removed soon, read #7129.

**Comment by Arthur-Leywin** [comment]
Aww man, is there any other extensions as good as manhuascan i can read at? 😭

**Comment by alessandrojean** [comment]
No recommendations. Test some and check what works best for you.

**Comment by Arthur-Leywin** [comment]
Noted with thanks!
