### ISSUE TITLE
[Source Request] <ComicK>

### ISSUE THREAD

**Issue by ShahbazKhan97** [tachiyomiorg/tachiyomi-extensions#7144]
## Source website
- Name: ComicK
- Link: ComicK.fun
- Language(s):  English but has many other languages.

## Other details

A great website with good UI and huge library.
![Screenshot_20210521-083112](https://user-images.githubusercontent.com/47472035/119075727-ec32e900-ba0e-11eb-9860-17b8e4acbd0b.jpg)

**Comment by CrepeTF** [comment]
#5680

**Comment by ShahbazKhan97** [comment]
> #5680

It already has many manga which mangadex doesn't or can't host, like Mashle and Jujutsu Kaisen.

**Comment by CarlosEsco** [comment]
we don't keep duplicate issues open
