### ISSUE TITLE
[Feature Request] <Dragon Translation>: <Erase of the App>

### ISSUE THREAD

**Issue by AltairMaster0** [tachiyomiorg/tachiyomi-extensions#7145]
good, I would like to ask you to remove the extension of DragonTranslation of Tachiyomi, because they take away the already very few visits we have to buy raw and to continue with our work, please I ask it with urgency and importance, because if not we can not continue with our work and we would harm us and much more the readers who follow us, thank you very much for your attention, I attach the image that we are dragonTranslation and I reiterate that all the projects we have on the web are supported by the visits that come to the page, we are not collecting pages or anything like that, which if you wish we can demonstrate all the heads of the respective scans that are on our page.

https://prnt.sc/137ctw8

and as I said before if you want more proof I can contact all the heads of the scans that are in our page to demonstrate that we are alliance and we all support each other in the visits,

PS: I reiterate we are not collecting page we only have our own projects worked on the page.

**Comment by vinsmokesanj** [comment]
please remove Dragon Translation from Tachiyomi

**Comment by AnhelAlcivar** [comment]
Bueno vengo a pedir que hagan el favor de eliminar la extención de Dragon Translatión de Tachiyomi 
La razón del porque la esta comentando AltairMaster0

**Comment by EmersonG7** [comment]
Buenas noches pedirles de favor que eliminen Dragon Translation de Tachiyomi ya que afecta las visitas a la pagina original por favor

**Comment by Cazadorjk** [comment]
Porfavor eliminé la extensión de dragon translation de tachiyomi ya que con esos mangas me hago la paja.

**Comment by OdysseyScan** [comment]
Please remove the extension from our colleagues from "Dragon Translation", for the reasons already mentioned, this is a lack for those who stay up translating projects.

**Comment by ji871** [comment]
Please remove the dragon translation of app please

**Comment by dmswd** [comment]
Wait until a dev responds
And please stop spamming

**Comment by Br4y4n-Pro** [comment]
please remove the dragon scalation extension 

Buenas noches pedirles de favor que eliminen Dragon Translation de Tachiyomi ya que afecta las visitas y con ello compra material para traducir,

**Comment by IFreddyTM** [comment]
I came here just to say "REMOVE DRAGON TRANSLATION EXTENSION FROM TACHIYOMI".  
PD: There's no good night for u guys. 😒

**Comment by SapitoXD** [comment]
Haber vengo a ser claro osea la extensión de la pagiana de Dragon esta opacando la pagina oficial es decir que si no tienen vistas en su web se daria de baja me entendes 
O se lo digo resumido la extencion de Drangon Translation esta molestando a la comunidad ok ....zzzzzzzz

**Comment by necromata738** [comment]
Buenas noches vengo aquí para comentar que quiten dragon translation de tachiyomi por las razones ya mencionadas anteriormente

**Comment by onefullblazt** [comment]
please delete extension dragon translation

**Comment by Byjhos** [comment]
please remove Dragon Translation from Tachiyomi

**Comment by Blackcanonn** [comment]
Por favor eliminen la extensión ya que dragon es el mejor scan que Conozco eliminen la de tachiyomi

**Comment by GitBot69** [comment]
Hello, very good, I have come to ask you to cancel the extension of dragon translations, one does not pay to see different projects and your only way to subscribe is from the visits of the page.  I eat it the fan boys of timochi xD

**Comment by GitBot69** [comment]
hola, muy buenas, vengo a pedir que den de baja la extensión de dragon Translations, uno ni paga para ver distintos proyectos y su única manera de subsixtir es desde las visitas de la pagina.  me la comen los fan boys de timochi

**Comment by Lukes-69** [comment]
Hola, me uno al pedido de que quiten la extension o lo que sea de dragón translation, a nosotros nos perjudica al momento de tener visitas, nos esforzamos mucho en traer los proyectos lo más rápido posible justo para que la gente lo disfrute en la página, ver como bajan las visitas, nos desmotiva, dragón puede quedarse sin comer por no tener visitas.

**Comment by Xstren** [comment]
Please remove the extension from our colleagues from "Dragon Translation" please

**Comment by Yisussgod** [comment]
Buenas noches, se le pide de manera amable e prudente que si nos puede aser el favor de que remueva la extencion del scan dragon traslation. 
Se le agradeseria.

**Comment by jpisco-gif** [comment]
Please remove Dragon Translation from Tachiyomi, doing this does not help the new scans to emerge

**Comment by R8drig8** [comment]
Me cree una cuenta solo para solicitar que quiten la extensión de dragon translation, ya que como dice, hay menor cantidad de visitas a la página y no queremos que desaparezca, así que por favor, ayuden a esta bella página.

**Comment by jackson13261** [comment]
Buenas estoy aqui para perdiles q eliminen la extención de dragón translation  ya q como mencionaron afecta mucha al scan de dragón asi que por favor eliminen la extension de dragón translation.

**Comment by Xstren** [comment]
Por favor eliminen la extensión de Dragón translation que si no nos quedamos sin caps

**Comment by Alexiscastilloshadow** [comment]
Vengo a pedirles en esta ocasión que eliminen Dragon Translation de Tachiyomi, la razón es que afecta las visitas a la página original y por ende no remunerado el trabajo que elaboran.                                                                        
Gracias por su atención, esperando que así cumpla las demandas aquí puestas.

**Comment by Realppp** [comment]
Pls remove among us virus from tachiyomi

**Comment by elma-tagatos20** [comment]
Eliminate Dragon Translation from tachiyomi please

**Comment by juanigu** [comment]
Please remove Dragon translation from tachiyomi.
since it affects the visits of the original page.

**Comment by DaRwIn347** [comment]
Por favor eliminen la extención de Dragon Translatión de Tachiyomi, esta robando contenido y le quitas visitas a la pagina real.

**Comment by CarlosEsco** [comment]
I have removed your ad ridden site.  Though we cant control those who have already downloaded and are using it, or those that choose to share it other wise.  

https://easyupload.io/1sae0t

**Comment by Mnu008** [comment]
Buenas noches pedirles de favor que eliminen Dragon Translation de Tachiyomi ya que afecta las visitas a la pagina original por favor
