### ISSUE TITLE
[Bug] MangaOwl: Shows Index: 0, Size: 0 in fetch logs.

### ISSUE THREAD

**Issue by Dark4Codrutz** [tachiyomiorg/tachiyomi-extensions#7149]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: MangaOwl
- Extension version: 1.2.9

## Steps to reproduce
1. First Step
Set-up background sync with show update errors enabled.
2. Second Step
Wait for background sync

### Expected behavior
No error notification in the fetch log for this type.

### Actual behavior
When sync happens manga from MangaOwl reports "Index: 0, Size: 0" as an error even though there is nothing to fetch (no new chapters) and notification arrises to user.

### Other
The error also shows up while manually refreshing the chapter page for said manga.
I have two manga from MangaOwl:
[Drifters](https://mangaowls.com/single/1427/drifters)  : The error is not presented (neither for manual nor auto sync)
[Mushoku Tensei](https://mangaowls.com/single/1113/mushoku-tensei-isekai-ittara-honki-dasu)  : error shows up

**Comment by CVIUS** [comment]
can be closed as per #8417
