### ISSUE TITLE
[Bug] <Luscious>: <chapter display>

### ISSUE THREAD

**Issue by Golisopod88** [tachiyomiorg/tachiyomi-extensions#7152]
## Device information
- Tachiyomi version: preview r3368
- Android version: MI 12.0.4

## Source information
- Name: Luscious
- Extension version: 1.2.11

## Steps to reproduce
1. Open any manga

### Expected behavior
Every image should have been in a same chapter

### Actual behavior
Instead every image is presented like a chapter

**Comment by jopejoe1** [comment]
This is on purpose as some manga get new pages regularly and users can get updates when these  are added. If you prefer a single chapter per manga you can enable merged chapter in the Luscious settings screen.
