### ISSUE TITLE
[Bug] <Mangas.pw(Mangas.in)>: <Error in manga chapters>

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi-extensions#7154]
## Device information
- Tachiyomi version: 1.0.17 (J2K)
- Android version: SAMSUNG, 7.0.1

## Source information
- Name: Mangas.pw(Mangas.in)
- Extension version: 1.2.3

## Steps to reproduce
1. Open extension section
2. Open sleeve (any)

### Expected behavior
Shows all the chapters to be shown in the sleeves without any error.

### Actual behavior
Only one chapter of all the sleeves is shown, and without having to do with them (changed chapters)

## Other details
- The extension is Spanish language
- Bug Images:
https://i.imgur.com/ZYApRVO.jpg
https://i.imgur.com/3v3KC3E.jpg
https://i.imgur.com/ovtSW1T.jpg

**Comment by KasukeLp23** [comment]
Webview: https://i.imgur.com/qXTPeGY.jpg

**Comment by yony1325** [comment]
Me pasa lo mismo ...ya desinstale y re instale y pasa lo mismo ..me sale solo un cap en cada manga

**Comment by KasukeLp23** [comment]
HELP!!
