### ISSUE TITLE
[Bug] <Japscan>: <not working >

### ISSUE THREAD

**Issue by Diego10pedro** [tachiyomiorg/tachiyomi-extensions#7161]
## Device information
- Tachiyomi version: 0.10.12 
- Android version: 10

## Source information
- Name: japscan 
- Extension version: 1.2.27

## Steps to reproduce
1. Trying to read or download a chapter 
2. Infinite loading

**Comment by h-hyuuga** [comment]
Duplicate of #6166 ?

**Comment by Diego10pedro** [comment]
No, I think is différent. All chapters and webtoons don't work. And there are no ads.
