### ISSUE TITLE
[Bug] <WeComics>: <jsonObject["data"] must not be null>

### ISSUE THREAD

**Issue by ThatOneIndian** [tachiyomiorg/tachiyomi-extensions#7162]
## Device information
- Tachiyomi version: J2k v1.0.17
- Android version: 11

## Source information
- Name: WeComics
- Extension version: 1.2.1

## Steps to reproduce
1. go to Adventurer in the Netherworld
2. go to latest chapter

### Expected behavior
Describe what should have happened
opening up the actual chapter
### Actual behavior
Describe what happens instead
return error = jsonObject["data"] must not be null
## Other details
only happens to manhua that requires using website payments of coins or shells. Only free manhua work on extension

**Comment by FourTOne5** [comment]
Well obviously only free ones will work. So it's not a bug.

**Comment by ThatOneIndian** [comment]
look man i was just told to make this ticket so i went and did it not much
to say other than that
