### ISSUE TITLE
[Source Request] Any plan to add mangapark v3?

### ISSUE THREAD

**Issue by crest1993** [tachiyomiorg/tachiyomi-extensions#7164]
The source in mangapark v3 is more neatly organized not like in v2 when the source is mashed from fox duck rock (it's a mess).

## Source website
- Name: Mangapark v3
- Link: https://mangapark.net
- Language(s): English

**Comment by Seishirou101** [comment]
duplicate of #6726

**Comment by Seishirou101** [comment]
Duplicate of #6726
