### ISSUE TITLE
[Bug] <mangalek>: <fetching chapters causes app to crash>

### ISSUE THREAD

**Issue by FrostAlev** [tachiyomiorg/tachiyomi-extensions#7165]
## Device information
- Tachiyomi version: TachiyomiSY 1.6.2, based on Tachiyomi stable 0.10.12
- Android version: 8.1.0

## Source information
- Name: tachiyomi-ar.mangalek
- Extension version: 1.2.4

## Steps to reproduce
1. Open any manga's page.
2. Open or download any chapter.

### Expected behavior
Chapter loads and display images.

### Actual behavior
1. Keeps loading for a couple of seconds.
2. App crashes.

## Other details
- That error didn't happen before updating the extension to the 1.2.4 version.
- if a chapter of a manga from this source was queuing in the download list crashes happen even if I'm trying to download from another source and sorting it's chapters first.
- I have tried using the official tachiyomi app version 0.10.12 and I had the same issue.
- using the older version (1.2.1) causes no crashes.

**Comment by matheuswr89** [comment]
This error started after the update of choosing the Host where the image will be provided.
This PR mentioned is #6841 
in addition to the source mentioned in this PR, there are more sources with the same problem

**Comment by FrostAlev** [comment]
I have tried every single server of the, yet crashes still occur.
So I had to go back to the stable 1.2.1 version

**Comment by alessandrojean** [comment]
Closing this since the new preference added that was causing the crash was reverted.
