### ISSUE TITLE
[Bug] <ComicKiba>: <Pages spilt and not in order>

### ISSUE THREAD

**Issue by SoloLeveller1** [tachiyomiorg/tachiyomi-extensions#7166]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: ComicKiba (EN)
- Extension version: 1.2.4

## Steps to reproduce
1. Open "Cultivator Against Hero society"
2. Open chapter 87

### Expected behavior
In webtoon mode, read comfortably by scrolling down

### Actual behavior
Pages split 
2nd half of page is found at later pages and chapter doesn't make sense

## Other details
Only occuring on chapter 87

**Comment by mcOz1** [comment]
I have the some problem

**Comment by tyme2tb** [comment]
Seeing it also. Interestingly it just started happening with manhuaus (Reborn 80,000 Years) also.

**Comment by cyvax** [comment]
comickiba is doing the same as manhuaus.
This means that the page is literally split into two.

**Comment by tyme2tb** [comment]
Got some other bad splitting issues with the below manga:
The Strongest Death System
