### ISSUE TITLE
[Bug] [JapanRead]: Captcha added before getting the chapters / error code 1020

### ISSUE THREAD

**Issue by oktapodia** [tachiyomiorg/tachiyomi-extensions#7173]
---

## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: JapanRead
- Extension version: 7

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

Extension working again

### Actual behavior
Describe what happens instead

Trying to download any chapter on the website with `pageListParse`, you will see by using the webview that there is a ReCaptcha page added before getting the chapter.

I did try to add the following but this does not work (I'm clearly not a java dev), any ideas how to fix it?

```kotlin
    val chapterIdElement = document.select("meta[data-chapter-id]")

    val responseCaptchaDocument: Document
    if (!chapterIdElement.hasAttr("data-chapter-id")) {
        responseCaptchaDocument = hasCaptchaForm.first().submit().execute().parse()
    } else {
        responseCaptchaDocument = document
    }
```

**Comment by nzoba** [comment]
You can solve the captcha with the webview and then everything will work again in Tachiyomi for all the chapters (you may need to do that once in a while)

**Comment by Adam935** [comment]
> You can solve the captcha with the webview and then everything will work again in Tachiyomi for all the chapters (you may need to do that once in a while)

I try it but that still not working do you think you can fix it ?

**Comment by oktapodia** [comment]
Thank you for your answer @nzoba it works for few days.

Now it looks like cloudflare is blocking tachiyomi to get the chapter pages even with resolving the captcha from the webview (error 1020)

**Comment by Crazyom** [comment]
There’s still no one to fix this?
It's the most active french source currently

**Comment by CarlosEsco** [comment]
> There’s still no one to fix this?
> It's the most active french source currently

This is an open source project. Feel free to pr the fix yourself

**Comment by Crazyom** [comment]
> > There’s still no one to fix this?
> > It's the most active french source currently
> 
> This is an open source project. Feel free to pr the fix yourself

I have no coding skills, which is why I help translate the application.
That’s why I up this problem that which seems to have fallen into oblivion, you're free to decide if you trie to fix that or not.

**Comment by CarlosEsco** [comment]
> > > There’s still no one to fix this?
> > > It's the most active french source currently
> > 
> > This is an open source project. Feel free to pr the fix yourself
> 
> I have no coding skills, which is why I help translate the application.
> That’s why I up this problem that which seems to have fallen into oblivion, you're free to decide if you trie to fix that or not.
 
Learn to code, or wait for a french developer who wants to fix it.  Upping does nothing.
