### ISSUE TITLE
[Bug] Mangadex: Language filters not working

### ISSUE THREAD

**Issue by Hendiadyoin1** [tachiyomiorg/tachiyomi-extensions#7179]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.113

## Steps to reproduce
1. Have a mangadex chapter
2. Manually reload chapters

### Expected behavior
Only show chapters in the designated language

### Actual behavior
All chapters, in all languages are shown

## Other details
Saw in:
* Kumo desu ga, Nani ka?
* Tensei shittara slime Datta ken
* And all other manga ported from the old mangadex extension

**Comment by loocool2** [comment]
Known issue, fix coming soon
