### ISSUE TITLE
[Source Request] <Yaoi Manga>

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#7184]
## Source website
- Name: Yaoi Manga
- Link: https://yaoi.mobi/
- Language(s): English

## Other details
The name says it all xD

**Comment by loocool2** [comment]
Also looks like madara...

**Comment by CVIUS** [comment]
Hope u guys add my requests cuz manhuascan got removed T_T anyways wish u goodluck, gb and stay safe everyone

**Comment by murasakibara2002** [comment]
I hope this will add as new extension ☺️ until now I can't believe that ManhuaScan got removed. I hope it will back >.<

**Comment by hedge12** [comment]
This would be really helpful for the BL community!  🎉
