### ISSUE TITLE
[Bug] Mangaworld

### ISSUE THREAD

**Issue by edofl3da** [tachiyomiorg/tachiyomi-extensions#7185]
## Device information
* Tachiyomi version: Latest
* Android version: Latest
* Device: Xiaomi Mi A1

## Source information
* Source name: Mangaworld
* Source extension version: latest

## Steps to reproduce
1. Install Mangaworld
2. Enter extension

## Issue
The app doesn't connect to the website. So i can't read my manga or search something on the extension

**Comment by OncePunchedMan** [comment]
working for me. try troubleshooting https://tachiyomi.org/help/guides/troubleshooting/#diagnosis

**Comment by CrepeTF** [comment]
Saying latest provides no credible information, please state the numerical version information.
