### ISSUE TITLE
[Bug] <mangadex>: <shows all scans from each languageavailable>

### ISSUE THREAD

**Issue by dmswd** [tachiyomiorg/tachiyomi-extensions#7186]
## Device information
- App version: 1.6.2 (standard, ab0f5d107, 17)
Preview build: 371
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx
## Source information
- Name: mangadex
- Extension version: 1.2.114

Something heppend to mangadex as it's now displaying all scans from all languages

**Comment by arkon** [comment]
This is a SY-specific issue due to its delegation. He's working on fixing it.
