### ISSUE TITLE
Some downloaded chapters don't appear

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi-extensions#7200]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: gmanga
- Extension version: 1.2.5

## Steps to reproduce
I have already downloaded all the chapters included in a specific manga

### Expected behavior
They all shoud appear and open when i click on them

### Actual behavior
Some of the "already downloaded" chapters need to be downloaded again

## Other details
The downloaded chapters appear in the date file in phone storage (see the photos for further details)
![IMG_20210524_095953](https://user-images.githubusercontent.com/75262438/119316180-f0613f80-bc76-11eb-8d7c-a3216db82d24.jpg)
![IMG_20210524_095712](https://user-images.githubusercontent.com/75262438/119316187-f1926c80-bc76-11eb-8fa9-527040307121.jpg)

**Comment by arkon** [comment]
Those scanlators are clearly different.

**Comment by hakudansho** [comment]
So i just have to download them again and the problem is solved or what?

**Comment by arkon** [comment]
You could also rename the folders to have the different scanlators' names (the part before the underscore) if you don't care that they don't actually match up.

**Comment by hakudansho** [comment]
It worked as you said, thanks a lot 🥰
