### ISSUE TITLE
[Chapters not loading] <Comick.fun>: <I try reading any comic in this extension, but the chapters doesn't load. The webview is working fine, so the problem is with the app version SY>

### ISSUE THREAD

**Issue by BriggsWall** [tachiyomiorg/tachiyomi-extensions#7207]
## Device information
- Tachiyomi version: App version: 1.5.0 (standard, 0413d50, 13)
Preview build: 0
- Android version: 10

## Source information
- Name: Comick.fun
- Extension version: 1.2.1

## Steps to reproduce
1. Open the comic in the source
2. Appear a message and the chapters doesn't load

### Expected behavior
When opening a comic, I should be able to see the chapters and read

### Actual behavior
A message appeared and I couldn't see the chapters

## Other details
I checked the webview, it's working fine,I can see the chapters from there, but when I open in Tachiyomi it's not working
![Screenshot_20210524-103121](https://user-images.githubusercontent.com/83545586/119367702-379ffe00-bc80-11eb-9cbe-3783ee4dbaaf.png)

**Comment by curche** [comment]
Wrong Repo. You have to report it at https://github.com/jobobby04/TachiyomiSY/issues

Before reporting, do update your app to the latest version, which is v1.6.2, and check if the issue persists there as well

**Comment by BriggsWall** [comment]
Thanks, I already opened in the right one
