### ISSUE TITLE
[Bug] <JapanRead>: <JSON error>

### ISSUE THREAD

**Issue by Cypral** [tachiyomiorg/tachiyomi-extensions#7214]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 10

## Source information
- Name: JapanRead
- Extension version: 1.2.7

## Steps to reproduce
1. Open or download any chapter

### Expected behavior
Should open or download the chapter

### Actual behavior
Getting this error 
![IMG_20210525_022324.jpg](https://user-images.githubusercontent.com/19366824/119422530-99547c80-bd01-11eb-8211-a7c8e7e89299.jpg)

## Other details
It's like that for like 3 or 4 days, for every manga on this source. However it still manage to update and detect if there's new chapters

**Comment by arkon** [comment]
Closing in favour of #7173
