### ISSUE TITLE
[Bug] <mangas.pw>: <is crashed show the same chapter in all manga please view it>

### ISSUE THREAD

**Issue by saodxd** [tachiyomiorg/tachiyomi-extensions#7216]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: mangaspw
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by saodxd** [comment]
Por favor revisa

**Comment by Kempachi15** [comment]
Me pasa lo mismo todos los cap fueron cambiados por un hentai

**Comment by DTecheira** [comment]
Duplicated of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7154
