### ISSUE TITLE
[Bug] <Toonily>: <App crash on chapter read or download>

### ISSUE THREAD

**Issue by Ayushk222** [tachiyomiorg/tachiyomi-extensions#7217]
## Device information
- Tachiyomi version: TachiyomiJ2K 1.0.17
- Android version: 10

## Source information
- Name: Toonily
- Extension version: 1.2.6

## Steps to reproduce
It'd be hard to reproduce because I think my country is one of the few that have banned Toonily from being accessed unless you turn on VPN. But if you can get past that then 

- Pick any series from Toonily and read a chapter without turning the VPN on.

### Expected behavior
The app shouldn't crash and instead show toast "Failed to bypass Cloudflare ..."

### Actual behavior
App crashes when trying to read or download Toonily chapters without turning VPN on.

## Other details
Yesterday, when I accessed any Toonily chapter from the TachiyomiJ2K app, my phone restarted a few times. I would dump crash logs here if they had anything in them. The file was empty it's size was 0B.
I have already posted this as a comment in an already opened issue for the TachiyomiJ2K fork as it might be an issue there.

**Comment by hyoretsu** [comment]
Also happening on Hell's Harem, most of the time I used to get the Cloudflare error. Accessing from Brazil.

**Comment by alessandrojean** [comment]
There was an update recently in all Madara extensions that fixed the crash when reading a chapter.

Does this crash still happens after the update?

**Comment by Ayushk222** [comment]
@alessandrojean I just checked and it no longer happens. Thanks to whoever fixed it! I'll close this issue now.
