### ISSUE TITLE
[Bug] <Webtoons.com>: <webtoon not marked as in library because URL changed >

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#7223]
## Device information
- Tachiyomi version: j2k 1.0.17
- Android version: 10

## Source information
- Name: Webtoons.com
- Extension version: 1.2.29

## Steps to reproduce
1. Need to already have webtoons.com webtoon in library
2. Search webtoon name in extension
3. It will not be marked as "in library"

### Expected behavior
Be marked as in library 

### Actual behavior
Not marked as in library

**Comment by CarlosEsco** [comment]
If the url changed, there is nothing to be done.  Did you try sharing manga from both instances and see if they changed anything

**Comment by vipzzx** [comment]
Not too sure. That's what jay said. 
![Screenshot_20210525-135330_Discord.jpg](https://user-images.githubusercontent.com/59638889/119545247-9b015d00-bd60-11eb-8dd7-001d19e8f3f5.jpg)

**Comment by CarlosEsco** [comment]
click the share button and send the link here 
do it for both of them

**Comment by vipzzx** [comment]
One example

One form my library: https://www.webtoons.com/episodeList?titleNo=2009

One from searching in webtoons.com extension:
https://www.webtoons.com/en/fantasy/your-throne/list?title_no=2009

**Comment by CarlosEsco** [comment]
It looks like they changed the URL and the library one is redirecting to the new one. Think you're going to have to migrate from webtoon to webtoon

**Comment by vipzzx** [comment]
I did that already and it's still the same.

**Comment by herdax** [comment]
![Screenshot_2021-05-27-23-18-55-85_79aa9bf7c61e266c5f841e42245e214b](https://user-images.githubusercontent.com/12084129/119863400-b5476080-bf43-11eb-81c8-a838ceec6f09.jpg)
![Screenshot_2021-05-27-23-19-14-25_79aa9bf7c61e266c5f841e42245e214b](https://user-images.githubusercontent.com/12084129/119863406-b7112400-bf43-11eb-9220-91a0abae19e2.jpg)

it's affect webtoon indonesia too, and filter is not working

**Comment by scb261** [comment]
Duplicate of #7024

**Comment by CarlosEsco** [comment]
From #7024
> Apparently the extension returns the same manga with different URLs:
```
Browse/Latest
https://www.webtoons.com/en/romance/subzero/list?title_no=1468

Search
https://www.webtoons.com/episodeList?titleNo=1468
redirects to
https://www.webtoons.com/en/romance/subzero/list?title_no=1468
```
>Converting browse link to search link would mean forcing unnecessary redirect. Converting search link to browse link would require extra network call for each found manga since we don't have enough info for it. I think it's better to leave the extension as is, but it's up to maintainers.
>

**Comment by uap4** [comment]
I have a similar problem with **readmanga.live** and **mintmanga.live**. Although it is connected not with a change in the scheme, but with the change of titles to localized, but also some ID are gradually added. Thanks to redirects nothing breaks, but also the divergence of library with the source catalog.

For a workaround, I propose to add a switch in extension settings, with which you can turn off redirects. Then updates will be interrupted with errors and such can be sorted and run migration.

It would be better if URL was updated in same way as the rest of metadata.
