### ISSUE TITLE
[Bug] <comiclatest>: <getting a 521 error in trying to get a list while "latest" works>

### ISSUE THREAD

**Issue by Sualem** [tachiyomiorg/tachiyomi-extensions#7231]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10 patch level 03/2021

## Source information
- Name: comiclatest
- Extension version: 1.2.2

## Steps to reproduce
1. go to source, press on comiclatest. i get an error 521, it works on webview.
2. if i press on "latest", i have access to the latest comics available.

### Expected behavior
have a view of all the comics, not only the latest ones, and being able to search.

### Actual behavior
HTTP error 521, going into webview and refresh does not change the situation

## Other details
thanks for the great work. i really appreciate.

**Comment by OncePunchedMan** [comment]
they are redirecting to readcomicsonline. guess they're down or stopped existing
