### ISSUE TITLE
[Bug] Lilymanga: Can't Load Chapter

### ISSUE THREAD

**Issue by vcyzteen** [tachiyomiorg/tachiyomi-extensions#7233]
## Device information
- Tachiyomi version: 0.12.0
- Android version: 10

## Source information
- Name: lilymanga
- Extension version: 1.2.9

## Steps to reproduce
1. Click Manga & Refresh
2. Chapter not found

### Expected behavior
Load and Read some scan

### Actual behavior
Chapter not found. I try reinstall extension again but not work. And chage DNS. But same and if im use browser all fine

**Comment by Arraiment** [comment]
Have you tried opening webview before trying to view the manga?

**Comment by vcyzteen** [comment]
> Have you tried opening webview before trying to view the manga?

Yeah Before Version 1.2.11 its not work. And now after there is a new extension update version 1.2.11. And i just now update and its work. So this is can be closed with open webview first. Thanks for the update 👍🏻
