### ISSUE TITLE
[Bug] <Komik Cast>: <Blank Manga Cover>

### ISSUE THREAD

**Issue by Ayanokouji-kun** [tachiyomiorg/tachiyomi-extensions#7235]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 7.1.1

## Source information
- Name: Komik Cast
- Extension version: 1.2.8

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
After I update this extension to the latest version, all manga cover from this extension becomes blank

### Actual behavior
Can admin fix this

## Other details
- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/

**Comment by CrepeTF** [comment]
#6955
