### ISSUE TITLE
[Bug] TruyenTranhLH : HTTP error 404

### ISSUE THREAD

**Issue by gonz1324** [tachiyomiorg/tachiyomi-extensions#7237]
## Device information
- Tachiyomi version: Preview r3354(47c120e5)
- Android version: 9
- Extension version: TruyenTranhLH ver 1.2.8

![Capture+_2021-05-27-00-50-00.png](https://user-images.githubusercontent.com/63002225/119707582-81a60100-be85-11eb-8fb2-9348fe5b5dcb.png)
Cause they have changed manga url structure , so all bookmarked manga in library can't work now.
Old url structure: truyentranhlh.net/truyen/manga-name
New url structure: truyentranhlh.net/truyen-tranh/manga-name

Please update the extension

**Comment by OncePunchedMan** [comment]
working for me. try troubleshooting https://tachiyomi.org/help/guides/troubleshooting/#diagnosis

**Comment by gonz1324** [comment]
New manga in extension still work normal. But all old bookmarked manga before they changed the link can't work

**Comment by gonz1324** [comment]
> working for me. try troubleshooting https://tachiyomi.org/help/guides/troubleshooting/#diagnosis

New manga in extension still work normal. But all old bookmarked manga before they changed the link can't work

**Comment by Aeternyx** [comment]
@gonz1324 why not migrate?

**Comment by gonz1324** [comment]
> @gonz1324 why not migrate? if the comic isn't there, naturally it should 404

I tried changed the link and it worked. This bug used to happened 1 year ago.
And no one want to migrate some hundred bookmarked one-by-one
