### ISSUE TITLE
El contenido no corresponde a la página o al manga.

### ISSUE THREAD

**Issue by kurozakii** [tachiyomiorg/tachiyomi-extensions#7240]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 7
* Device: Moto E4 plus

## Source information
* Source name: Mangas.pw
* Source extension version: 1.2.3

## Steps to reproduce
1. Entrar a la extensión
2. Ingresar á cualquier manga, cargará un capítulo de algún Doujin.
3. Si seleccionamos cualquier otro manga saldrá el mismo capítulo del Doujin.

**Comment by DaviidC** [comment]
Duplicate of #7154

Porfavor busca antes de abrir un issue nuevo.

PD: mangas.in no quieren que la gente use tachiyomi en su sitio, por eso (imagino) detectan el User-Agent de tachiyomi y envían datos falsos a la aplicación.
Es decir que lo rompen a propósito. 

Así que elige, o usas otra extensión o usas manga.in solo en el navegador y te comes los anuncios (si es que los hay, yo uso adblock así que ni idea, si no los hay no entendería la necesidad de bloquear tachiyomi) .
