### ISSUE TITLE
[Bug] <Komikcast>: <Image Cover>

### ISSUE THREAD

**Issue by adisptr13** [tachiyomiorg/tachiyomi-extensions#7248]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: Komikcast
- Extension version: 1.2.8

## Steps to reproduce
1. Click the latest
2. Image cover didn't load a.k.a image crash

### Expected behavior
Image cover on some manga/manhwa didn't load properly  

### Actual behavior
Image cover not found

## Other details

![Screenshot_20210527-163807_Tachiyomi](https://user-images.githubusercontent.com/84905600/119804370-7a750680-bf0a-11eb-9d09-bb29c1fb51b4.jpg)

**Comment by CrepeTF** [comment]
#6955

**Comment by Riztard** [comment]
i think those are different issue but whatever lol 0.8.5
