### ISSUE TITLE
[Bug] manga-raw.club: error when opening a manga & no chapters shown

### ISSUE THREAD

**Issue by ZEXERJK** [tachiyomiorg/tachiyomi-extensions#7253]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: [manga-raw.club](https://www.manga-raw.club/)
- Extension version: 1.2.1

## Steps to reproduce
1. open the extension in sources
2. go to any manga
3. problem appears as soon as one's opens the manga 

### Expected behavior
1. open the extension in sources
2. go to any manga
3. manga info displays as usual with chapters listed below

### Actual behavior
1. error appears on the bottom of the page
2. no chapters shown, only general info
3. also, the information about the summary is not taken from the summery section, but the one above that has other information already displayed at the top after the name
4. manga status not showing (ex: ongoing etc.)

## Other details
The error varies depending on the viewed manga since it displays the date of the last chapter.
Screenshot of the error:
![manga-raw club error](https://user-images.githubusercontent.com/48049633/119849971-667ed400-bf0d-11eb-8e7f-afd27d4e8ae6.jpg)

**Comment by NMBLM** [comment]
Can you tell me which manga caused this?

**Comment by ZEXERJK** [comment]
It's a very strange issue, I was going to make a screen recording of the issue and changed the language of the app to English(UK) to show you the issue, but the problem just solved itself, for test’s sake I changed the language of the app to another different from English(UK) and the one I normally use(my mother language) and the problem resurfaced, so at this point I think that there might be something interfering with the language one chooses for the app and the extension date format or website language.

**Comment by ZEXERJK** [comment]
I tested a few languages and the only ones that give no problems are English(UK) and English(USA).
I also tested different kinds of date format and different languages but that seems not to be the issue, at this point is something related with the language of the app I think.

**Comment by NMBLM** [comment]
I have changed so that when reading the date it will always assume that it is in english and I have also changed the part related to the description to not include that extra will create the update request

**Comment by ZEXERJK** [comment]
Thank you very much! 👍🏻 
If it's not a bother could you look also at the status section? It doesn't show the status of the manga (ongoing/completed/hiatus etc.), thank you again :)
