### ISSUE TITLE
[Bug] <SamuraiScan>: <HTTP error 404>


### ISSUE THREAD

**Issue by Hanshee375** [tachiyomiorg/tachiyomi-extensions#7258]
## Device information 
- Tachiyomi version: 0.10.12 
- Android version: 8.1.0  

## Source information 
- Name: SamuraiScan  
- Extension version: 1.2.5  

### Expected behavior
The page theme was changed so the extension stopped working.

### Actual behavior
When I try to enter the extension I get a 404 error message and only the web view works.

![Screenshot_20210527-171241.jpg](https://user-images.githubusercontent.com/70455757/119904453-076e8e80-bf10-11eb-8531-88bd19d12c08.jpg)
![Screenshot_20210527-171317.jpg](https://user-images.githubusercontent.com/70455757/119904461-0d646f80-bf10-11eb-9b70-894a2e9c4cca.jpg)

**Comment by Riztard** [comment]
its working, maybe they change back their theme
