### ISSUE TITLE
[Source Request] Twitter

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#7263]
## Source website
- Name: Twitter
- Link: Twitter.com
- Language(s): All

## Other details
I think a good way of doing it would be to have each user be a "comic" and each tweet be a chapter, since each tweet can have four images. Personally I think it would be fine to just ignore all the tweets without images, but for those that are only text, maybe do it like the xkcd extension did for the hover text?

I genuinely think this would be a better way to browse Twitter.

**Comment by loocool2** [comment]
what the fuck

**Comment by AwesomeQuest** [comment]
Twitter sucks right now if you only want to browse specific creators. What with all the bloat, retweets, likes, topics, it all just gets in the way.
Thus I think it would be better to have all the bullshit stipped away and browse Twitter like I do all my other comics.

**Comment by az4521** [comment]
I think you'd be interested in the email extension
#5294

**Comment by CarlosEsco** [comment]
no
