### ISSUE TITLE
[Bug] <Mangahasu>: <Not loading>

### ISSUE THREAD

**Issue by Sakurahime08** [tachiyomiorg/tachiyomi-extensions#7264]
## Device information
- Tachiyomi version: latest
- Android version: 10

## Source information
- Name: Mangahasu
- Extension version: latest

## Steps to reproduce
1. Mangahasu not loading.  
2. Does not open in Webview - webpage not available; net::ERR_CONNECTION_REFUSED
3. Also does not open in "Open in Browser" button
4. Mangahasu open on the actual browser apps, though. 

### Expected behavior
Open normally. 

### Actual behavior
Failed to connect

## Other details
There was an Android Webview update earlier today and I installed that. Not sure if it affects this.

**Comment by CrepeTF** [comment]
Mangahasu is down
