### ISSUE TITLE
[Bug] <Komik Cast>: <Missing Cover>

### ISSUE THREAD

**Issue by archainur** [tachiyomiorg/tachiyomi-extensions#7265]
## Device information
- Tachiyomi version: Tachiyomi J2K 1.0.17
- Android version: 10

## Source information
- Name: Komik Cast
- Extension version: 1.2.8

## Steps to reproduce
1. First Step : Browse Komik Cast
2. Second Step : No cover

### Expected behavior
Describe what should have happened
Comic with cover

### Actual behavior
Describe what happens instead
Missing Comic Cover

**Comment by CrepeTF** [comment]
#6955
