### ISSUE TITLE
[BUG] <MangaHasu> : <Failed to connect to /77.73.69.61:443>

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi-extensions#7269]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: Samsung Galaxy Note 9

## Source information
* Source name: Mangahasu
* Source extension version: 1.2.10

## Steps to reproduce
1. Open extension sources/any app from the source.

## Issue/Request
Issue: Tachiyomi fails to connect to Mangahasu servers.

## Other details
![Screenshot_20210529-000053_Tachiyomi](https://user-images.githubusercontent.com/49813589/120012688-69172180-c012-11eb-873d-626484a699d1.jpg)

**Comment by CrepeTF** [comment]
Mangahasu is down

**Comment by leoteesh** [comment]
Hi not sure if I can comment on this and apologies of I couldn't.
Mangahasu seems to be working fine on a normal website however not sure why not working on the webview

![Screenshot_20210529-080124_Firefox](https://user-images.githubusercontent.com/21075197/120061917-5b37bf80-c057-11eb-8913-e82ce2ca9e4b.jpg)
