### ISSUE TITLE
[Bug] <manganato>: <library don't match from manganello>

### ISSUE THREAD

**Issue by mono0000** [tachiyomiorg/tachiyomi-extensions#7272]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 9

## Source information
- Name: manganato(manganelo)
- Extension version: 1.2.3

## Steps to reproduce
1. Added manga from manganelo extension
2. manganelo extension -> manganato
3. In same extension manga unadded
4. Manga still in library from same extension
5. Add manga to library in extension
6. Double manga in library from same extension(newly added manga un-readed read manga)

## Expected behavior
One same manga in library from same extension, remember readed chapter (manganelo -> manganato)

### Actual behavior
Double manga in library from same extension, newly added manga don't have readed chapter

## Other details
After manganelo change to manganato, in extension manga added to library don't show yet still in library, when manga in extension readded, in library doubled manga as if from different extension

**Comment by CrepeTF** [comment]
That's not a bug, just migrate your shit from nelo to nato.
