### ISSUE TITLE
[Source Request] <jpmtl.com>

### ISSUE THREAD

**Issue by amarufi** [tachiyomiorg/tachiyomi-extensions#7274]
## Source website
- Name: jpmtl.com
- Link: https://jpmtl.com
- Language(s): English

## Other details
This site has the most update  manhwa that I read recently (Boy of death). This site can provide machine translation method to our favorite manhwa. Please make it to be an extension for Tachiyomi. Thx before

![Screenshot_20210529-073222_Chrome](https://user-images.githubusercontent.com/77256895/120052591-3c81fa80-c050-11eb-8cba-ad86d45bfd5a.jpg)
![Screenshot_20210529-073240_Chrome](https://user-images.githubusercontent.com/77256895/120052596-3e4bbe00-c050-11eb-8840-db1bb35409b4.jpg)

**Comment by CrepeTF** [comment]
#5796
