### ISSUE TITLE
[Bug] MangaSee: Extension's Multiple Downloaded Folder. MangaSee (1), (2), (3), n

### ISSUE THREAD

**Issue by haffizhissham** [tachiyomiorg/tachiyomi-extensions#7275]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version:  11 RKQ1.200826.002

## Source information
- Name: MangaSee
- Extension version: 1.2.23

## Steps to reproduce
1. Download manga from MangaSee
2. View file manager to see extension's redundancy folders created as in pictures below

### Expected behavior
Other extensions' only have one folder for each extension 

### Actual behavior
1. Tachiyomi created multiple folders of MangaSee. MangaSee (1), (2), (3), (4), and so on
2. Folder created per chapter download. if download 10 chapters of any manga, it will created 10 folder of MangaSee
3.  Cant read manga(s) downloaded
4. Only can read after transferring all chapters downloaded in MangaSee (n) to main MangaSee (EN) folder and restart the app

## Other details
- Downloaded manga cant read as well. like this thread ( [https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6284](url) )
![image](https://user-images.githubusercontent.com/38602279/120057677-921dcd80-c077-11eb-8030-34554731681d.png)

- Picture from before and after downloaded new manga from MangaSee's extension
BEFORE :
![image](https://user-images.githubusercontent.com/38602279/120057659-731f3b80-c077-11eb-9cdc-99b99cf37dbb.png)
AFTER : 
![image](https://user-images.githubusercontent.com/38602279/120057662-7c100d00-c077-11eb-9bf1-c10b8f49cfa3.png)

**Comment by loocool2** [comment]
Not a bug. MangaSee was renamed from Mangasee to MangaSee, and so you need to rename your mangasee folder to MangaSee as well.

**Comment by haffizhissham** [comment]
> Not a bug. MangaSee was renamed from Mangasee to MangaSee. You need to rename the Mangasee (EN) folder to MangaSee (EN) and then force stop the app

noted. thanks for your help and the inconvenience cause.
Missed the capital when read thread #6284
