### ISSUE TITLE
[Bug] Manganelo: Library bug after update

### ISSUE THREAD

**Issue by ImMapple** [tachiyomiorg/tachiyomi-extensions#7277]
## Device information
- Tachiyomi version: 0.10.2
- Android version: 8.1.0

## Source information
- Name: Manganato (was manganelo. updated)
- Extension version: 1.2.3

## Steps to reproduce
1. Have old manganelo before update to manganato
2. Update to manganato
3. Open a manga from library and refresh

### Expected behavior
Refreshed and if there is new chapter  it will show up

### Actual behavior
No chapters found

## Other details
Cant open the webview after the update

**Comment by arkon** [comment]
#7278

Do not open duplicate issues.
