### ISSUE TITLE
[Bug] <Manganelo>: <Library bug after update>

### ISSUE THREAD

**Issue by ImMapple** [tachiyomiorg/tachiyomi-extensions#7280]
## Device information
- Tachiyomi version: 0.10.2
- Android version: 8.1.0

## Source information
- Name: Manganato (was manganelo. updated)
- Extension version: 1.2.3

## Steps to reproduce
1. Have old manganelo before update to manganato
2. Update to manganato
3. Open a manga from library and refresh

### Expected behavior
Refreshed and if there is new chapter it will show up

### Actual behavior
"no chapter found"

## Other details
Cant open the webview after the update

**Comment by loocool2** [comment]
This isn't a bug. MangaNelo changed its site URLs to MangaNato. You must migrate to MangaNato to continue reading manga from that source.

If you have any downloads, you must rename the MangaNelo folder to MangaNato, and all chapters in the folders must be renamed from manganelo.com to readmanganato.com.

**Comment by Riztard** [comment]
and maybe use `Text To Speech` if you cant read or blind
