### ISSUE TITLE
[Bug] some genres are missing in some source filters

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi-extensions#7288]
## Device information
- Tachiyomi version: j2k 1.0.7
- Android version: 11

## Source information
- Name: they are many like this but I choose a random one and it was "manytoons"
- Extension version: 1.2.6

## Steps to reproduce
1. Open source
2. Open filter and choose genres

### Expected behavior
all genres should be there

### Actual behavior
Some are extra and some aren't there, I counted in the source that there are only 48 tags but in the filter there were exactly 59,some tags were missing like smut and some weren't even in the original source like cars

## Other details
Can you check every source for the filter tags and fix them, there are many sources like this but I just picked one as an example

**Comment by CarlosEsco** [comment]
If genres are missing that is an extension issue not an app issue open an issuer per a source that has this issue https://github.com/tachiyomiorg/tachiyomi-extensions/
