### ISSUE TITLE
Mangazure

### ISSUE THREAD

**Issue by hanshiro6l6** [tachiyomiorg/tachiyomi-extensions#7293]
## Source website
- Name:mangazure
- Link:https://www.mangazure.com/
- Language(s): Turkish

**Comment by velvetcrowee** [comment]
pls add mangazure is great

**Comment by velvetcrowee** [comment]
What is the latest status of the topic 3 months ago? will it be added please add

**Comment by Riztard** [comment]
this is an open-source project, anyone can try to add it and whenever they want
