### ISSUE TITLE
[Bug] <Komik Cast>: <Can't load image>

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#7296]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 7.1.1

## Source information
- Name: Komik Cast
- Extension version: 1.2.9

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
I cant load image all manga in Komik Cast after update to the latest version...I've click "retry" many times but I still can't load image

### Actual behavior
Can admin fix it until it can load the image

## Other details
- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/

**Comment by Chan220** [comment]
looks okay when i opened it. Updating new manga, and their thumbnails. But when i read it theres no images or pages shown and only reload button is there.

I tried to uninstall the extension and reinstalling but still not working :(
