### ISSUE TITLE
[Bug] <Mangahasu>: <Failed to connect to /77.73.69.61:443>

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi-extensions#7299]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10
- Device: Samsung Galaxy Note 9

## Source information
- Name: Mangahasu
- Extension version: 1.2.10

## Steps to reproduce
1. Open extension sources/any manga from the source.

### Expected behavior
Should be able to connect to Mangahasu

### Actual behavior
Doesn't connect to Mangahasu

## Other details
Mangahasu extension lost its connectivity ever since the site became "not secure". It can be fixed by simply changing the baseUrl from "https://mangahasu.se" to "http://mangahasu.se" or just simply "mangahasu.se" so it could still connect to the server, regardless of whether it's secured or not.

**Comment by makroop** [comment]
I am having the same issue

**Comment by keyjeyelpi** [comment]
Well, the solution is simple, as I've looked at the source code and have already given the answer. It's an easy fix and I'd do it myself, but unfortunately, my knowledge in building apps such as these is minimal.

**Comment by JermanyWilhelm** [comment]
How to update mangahasu base url in the app?

**Comment by keyjeyelpi** [comment]
> How to update mangahasu base url in the app?

You're gonna have to rebuild it. We've got no choice until someone updates the extension.

**Comment by JermanyWilhelm** [comment]
> > How to update mangahasu base url in the app?
> 
> You're gonna have to rebuild it. We've got no choice until someone updates the extension.

Ahhhh ok ok I'm just gonna wait for the update for the extension
Thanks mate
