### ISSUE TITLE
[Feature Request] Mangadex: Sort by Scores or Sort by Total Views

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi-extensions#7302]
It would be really good if we had better sorting options for mangadex since it's pretty much back up on tachiyomi. 
The current sorting mechanism is a little confusing and usually doesn't yield good results. If a few more options like 
Sort by:
1. Score
2. Views
3. Trending this week
If these were added, it would become easier to find new manga that many people seem to enjoy. 
Thank you.

**Comment by CarlosEsco** [comment]
Literally none of these are offered by their api

**Comment by rsmyst** [comment]
> Literally none of these are offered by their api

Oh I thought the functionality could be added on tachiyomi's side of extensions. nvm if it's impossible. maybe later. thanks.

**Comment by CarlosEsco** [comment]
Yep as things get added to the api, if they are feasible we will add.
