### ISSUE TITLE
[Komiku.id] <Komiku>

### ISSUE THREAD

**Issue by Pecoriine** [tachiyomiorg/tachiyomi-extensions#7305]
## Source website
- Name:Komiku
- Link:Komiku.id
- Language(s): Indonesia

## Other details
This is the website logo
![A3V8wiquaTTpAAAAAElFTkSuQmCC](https://user-images.githubusercontent.com/85052642/120095691-7a1a7c80-c151-11eb-9c30-2324acee118c.png)

**Comment by Seishirou101** [comment]
it already exists.

**Comment by Seishirou101** [comment]
Duplicate of #2244
