### ISSUE TITLE
[Bug] <Sekte Komik>: <Can't Load Image after update to the latest version>

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#7311]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 7.1.1

## Source information
- Name: Sekte Komik
- Extension version: 1.2.5

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
I cant load image all manga in Komik Cast after update to the latest version...I've click "retry" many times but I still can't load image

### Actual behavior
Can admin fix it until it can load the image

## Other details
- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/

**Comment by loocool2** [comment]
There hasn't been a extension update that fixes any issues since your last issue. 1.2.10 is the latest version anyhow
