### ISSUE TITLE
[Source Request] <MangaPlus.org>

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#7316]
## Source website
- Name: MangaPlus.org
- Link: mangaplus.org
- Language(s): English

**Comment by Alexluther5** [comment]
I was wondering when will you guys add this source 
or explain if why you can't add this
Give an answer please.

**Comment by alessandrojean** [comment]
It will gets added when it gets added, there's no ETA for any extension to be added.
