### ISSUE TITLE
[Bug] <mangakakalot>: <Some manga have different chapter dates>

### ISSUE THREAD

**Issue by XeroxV** [tachiyomiorg/tachiyomi-extensions#7318]
---

## Device information
- Tachiyomi version: 1.0.17
- Android version: 11

## Source information
- Name: mangakakalot.com
- Extension version: 1.2.4

## Steps to reproduce
1. Check manga like Awkward Senpai

### Expected behavior
Date uploaded should show

### Actual behavior
Date uploaded is missing

**Comment by CrepeTF** [comment]
Can't reproduce, make sure you've migrated from Mangakakalot back to itself after updating the extension.

**Comment by somebody1234** [comment]
having the same issue, oddly enough. migrated to itself, still no cigar

**Comment by CrepeTF** [comment]
They've seem to have 2 different date formats for manga which are hosted on Nato and Kakalot.

Kakalot formatted dates succeed bit Nato ones do not.
