### ISSUE TITLE
[Bug] <Komikcast>: <won't load any images or pages>

### ISSUE THREAD

**Issue by Chan220** [tachiyomiorg/tachiyomi-extensions#7319]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 8.0.0

## Source information
- Name: Komikcast
- Extension version: 1.2.9

## Steps to reproduce
1. Open any manga

### Expected behavior
I should see normal manga pages

### Actual behavior
looks okay when i opened it. Updating new manga, and their thumbnails. But when i read it theres no images or pages shown and only reload button is there.

I tried to uninstall the extension and reinstalling but still not working :(

**Comment by arkon** [comment]
Why are you still spamming issues?!
