### ISSUE TITLE
[Bug] <Sekte Komik>: <Image Cant Load>

### ISSUE THREAD

**Issue by Ayanokouji-kun** [tachiyomiorg/tachiyomi-extensions#7320]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 7.1.1

## Source information
- Name: Sekte Komik
- Extension version: 1.2.5

## Steps to reproduce
1. Image from all manga/hwa/Hua didn't load

### Expected behavior
When I want to read manga from this extension, Image was always retry

### Actual behavior
After an update to 1.2.9 the image cover was fixed, but can't read the manhwa/manga the image was always retry

## Other details
![Screenshot_2021-05-30-22-57-38-38](https://user-images.githubusercontent.com/83941364/120111110-d05fdd80-c19a-11eb-9d01-aea50cd0fdc3.png)

**Comment by Riztard** [comment]
#7301
