### ISSUE TITLE
[source request] < knightnoscanlation >

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi-extensions#7321]
## Source website
- Name: knightnoscanlation
- Link: https://knightnoscanlation.com/
- Language(s): Spanish (ES)

**Comment by Clouddark75** [comment]
This one was asked for removed from their owners before. Ensure to check the previous ticket before posting.

**Comment by loocool2** [comment]
Bot should've closed it, but it was missing from the list. Anyways, closed.
