### ISSUE TITLE
[Feature Request] manganato: change downloaded file format

### ISSUE THREAD

**Issue by arozaqf** [tachiyomiorg/tachiyomi-extensions#7331]
The current file will be having long filename including website name plus chapter number. My suggestion would be filename with only chapter name. So in case website change we will only need to rename top most folder not every single chapter name. To future proof this source. Thank you

**Comment by Seishirou101** [comment]
mangabox sources for whatever reason uses their website as the scanlator name for most (some?) of their manga. If they change the url or the chapter list, downloads would be broken regardless so only having chapter name would be meaningless (cause they can change that too if they wanted) as its to prevent sources that have multiple scanlators for the same chapter from messing up downloading.

**Comment by arozaqf** [comment]
> mangabox sources for whatever reason uses their website as the scanlator name for most (some?) of their manga. If they change the url or the chapter list, downloads would be broken regardless so only having chapter name would be meaningless (cause they can change that too if they wanted) as its to prevent sources that have multiple scanlators for the same chapter from messing up downloading.

I am focusing on local side how downloaded file saved
