### ISSUE TITLE
[Meta] <Diffrent color outline option for bookmarks>

### ISSUE THREAD

**Issue by bungadrum** [tachiyomiorg/tachiyomi-extensions#7339]
##  Why/Project's Benefit/Existing Problem
When you bookmark something can you add the option for it to have a specific color outline. If you have a lot of bookmarks it would make it easier to organize content. For example if you are currently reading something the outline color around the thumbnail img or cover when you open a manga would be green. If you are considering reading later the color outline would be blue. And if you finished reading, but don't wan't to remove from bookmarks libary it would be red color outline by the users choice. If that's not a option maybe a small circle, square or badge icon colors on cover or thumbnail image as alternative similar to what Twitter has for VIP's, but not just blue.

## Other Details
We already have a label option in chapters that gives us a blue color which is usefull if you have a lot of sources or a lot of chapters it makes it easier to find where you left off or if you have a favorite, but if you have a lot of bookmarks and can't mark nothing it could be harder to organize. Diffrent color outlines or icons would be a great option can you plz add them just 2 or 3 colors for reading, considering and finished if possible.

**Comment by alessandrojean** [comment]
Issue opened in the wrong repo, you need to request this in the [app repository](https://github.com/tachiyomiorg/tachiyomi).
