### ISSUE TITLE
Universo Comics

### ISSUE THREAD

**Issue by luizxpyyy** [tachiyomiorg/tachiyomi-extensions#7340]
## Source website
- Name: Universo Comics
- Link: https://universocomics.xyz/
- Language(s): Português

**Comment by alessandrojean** [comment]
This site does not have an online reader, it just links to Google Drive, an extension can't be made for sites like this.

---
Este site não possui um leitor online, ele somente redireciona para o visualizador do Google Drive. Não há como criar uma extensão para sites assim.

**Comment by luizxpyyy** [comment]
ok
