### ISSUE TITLE
Galáxia Dos Quadrinhos

### ISSUE THREAD

**Issue by luizxpyyy** [tachiyomiorg/tachiyomi-extensions#7347]
---

## Source website
- Name: Galáxia Dos Quadrinhos
- Link: https://www.galaxiadosquadrinhos.com.br
- Language(s): Português

**Comment by alessandrojean** [comment]
The site is just a blog hosted on Blogger and does not have a proper online reader system and neither a title listing page. An extension can't be made for sites like this.

---

O site é somente um blog criado no Blogger e não possui um sistema de leitor online adequado e nem uma página de listagem de títulos. Não há como criar uma extensão para sites assim.
