### ISSUE TITLE
[Bug] <TCB Scans>: <the website has updated its UI, but the extension hasn't been updated yet>

### ISSUE THREAD

**Issue by Umairuem** [tachiyomiorg/tachiyomi-extensions#7348]
## Device information
- Tachiyomi version: j2k 1.0.17
- Android version: Android 7

## Source information
- Name: TCB Scans
- Extension version: 1.2.3

## Steps to reproduce
1. Open the extension

### Expected behavior
The extension should load and update the manga available on the site; http://tcbscans.com/

### Actual behavior
"No results found"

## Other details
This extension just need an update because the translation team updated their website UI. Extension is still working on the previous UI, so it doesn't load the site.

**Comment by CrepeTF** [comment]
#6869
