### ISSUE TITLE
[Bug] MANGA Plus by SHUEISHA: App crashes after choosing chapter to read or resume

### ISSUE THREAD

**Issue by quetsalkoatl** [tachiyomiorg/tachiyomi-extensions#7355]
## Device information
- Tachiyomi version: 0.11.0
- Android version: 10

## Source information
- Name: MANGA Plus by SHUEISHA
- Extension version: 1.2.18

## Steps to reproduce
1. Choose any Shueisha manga to read (library or browse)
2. Tap on chapter to read or resume reading
3. Tachiyomi crashes

### Expected behavior
App should not crash

### Actual behavior
App crashes, displays home screen

## Other details
This happens since updating to Tachiyomi v0.11.0, it worked before. Maybe an issue with the new version, but all other sources I tested work fine.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/commit/62db4bb09d09d38eb1193adbb8c96162010b810d

**Comment by quetsalkoatl** [comment]
Very quick fix. Thanks!
