### ISSUE TITLE
Senpai Ediciones

### ISSUE THREAD

**Issue by Realppp** [tachiyomiorg/tachiyomi-extensions#7359]
## Source website
- Name:Senpai endiciones
- Link: http://senpaiediciones.com/
- Language(s): spanish

Guilt trip I been

**Comment by Realppp** [comment]
Also my other extension mangamiso

**Comment by vetleledaal** [comment]
Uses WPMangaReader

**Comment by vetleledaal** [comment]
you don't need to close the issue, WPMangaReader is just the theme it uses. Someone still needs to implement it
