### ISSUE TITLE
[Bug] <Mangas.pw>: <missing chapters>

### ISSUE THREAD

**Issue by bhs642** [tachiyomiorg/tachiyomi-extensions#7360]
## Device information
-Tachiyomi version: 0.10.12-3458
-Android version: 10 (SDK 29)

## Source information
- Name: mangas.pw
- Extension version: 1.2.3

## Steps to reproduce
1. Open Tachiyomi
2. Select Browse
3. Select Extensions
4. Go to the spanish section
5. Install manga.pw
6. Now go to the sources
7. Open Mangas.pw
8. Select any series

### Expected behavior
Show all chapters released

### Actual behavior
Show only one released chapter or Out of date list of chapters

**Comment by CrepeTF** [comment]
#7154
