### ISSUE TITLE
[Bug] LilyManga doesn't return any search results

### ISSUE THREAD

**Issue by Malkierian** [tachiyomiorg/tachiyomi-extensions#7363]
## Device information
- Tachiyomi version: 0.11.1
- Android version: ?

## Source information
- Name: LilyManga
- Extension version: 1.2.5

## Steps to reproduce
1. Search literally anything you know exists on LM (like https://lilymanga.com/ys/watashi-ga-koibito-ni-nareru-wake-naijan-muri-muri-muri-janakatta/ ). Neither the English nor the Romaji names work (the English name worked on Madara before I finally uninstalled it to install the separated version)

### Expected behavior
Show the manga in the list

### Actual behavior
Instant "no results"

**Comment by Arraiment** [comment]
Have you tried opening and closing webview before searching?

**Comment by Malkierian** [comment]
At the time, I had, and it didn't make a difference.  Just checked now, it's working fine in both overall search and specifically on LilyManga's browse search.
