### ISSUE TITLE
error when wanting to read Mangadoor chapters

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#7374]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: Mangadoor
- Extension version: 1.2.3

### Expected behavior
Description:
When entering a chapter of a manga corresponding to mangadoor, I see a retry and it does not load the vignettes even though my internet is stable I need help Load a popress or retry and nothing helps please

![Screenshot_20210601_184732_eu kanade tachiyomi](https://user-images.githubusercontent.com/85204374/120408322-69663400-c314-11eb-957c-d7cb648cf134.jpg)

**Comment by Elcrack14** [comment]
Cuándo lo arreglan yo tengo el mismo error
