### ISSUE TITLE
[Bug] <DMZJ>: <Chapters that are not part of the serialized series are not displayed>

### ISSUE THREAD

**Issue by zhongfly** [tachiyomiorg/tachiyomi-extensions#7382]
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 10

## Source information
- Name: dmzj
- Extension version: 1.2.17

## Steps to reproduce
1. 用软件打开动漫之家源 具有多个系列的漫画，例如《与FPS游戏的好友现实中见面了》
2. 软件中未显示“其他系列”的“全一话”这个章节

### Expected behavior
显示所有章节

### Actual behavior
只显示排列最前系列的章节

## Other details
《与FPS游戏的好友现实中见面了》全部章节如下图：
![Screenshot_20210602165621](https://user-images.githubusercontent.com/11155705/120450976-8dcd1980-c3c3-11eb-9219-871082a43d4e.jpg)
dmzj插件的章节显示如下图
![Screenshot_20210602165651](https://user-images.githubusercontent.com/11155705/120451044-a2a9ad00-c3c3-11eb-8656-bc972dda840c.jpg)
可以发现缺少了“全一话”章节
更为明显的是《啾的报恩》
![Screenshot_20210602165946](https://user-images.githubusercontent.com/11155705/120451377-ef8d8380-c3c3-11eb-8ff9-0ed296c78817.jpg)

**Comment by Oldwangtouchtouchdoge** [comment]
已确认并修复，是我测试的时候没测到有多个章节系列的漫画🤣

**Comment by Oldwangtouchtouchdoge** [comment]
不过我注意到 api.dmzj.com/dynamic/comicinfo 返回的json数据是只包含一个章节系列的，现在这个api是作为备选，首选是可以获得所有章节系列的v4api。

**Comment by zhongfly** [comment]
> 不过我注意到 api.dmzj.com/dynamic/comicinfo 返回的json数据是只包含一个章节系列的，现在这个api是作为备选，首选是可以获得所有章节系列的v4api。

可以理解，也就只能这样了，毕竟是api的限制
