### ISSUE TITLE
[Bug] <Manga18 Fx>: <HTTP eror 404: Check Website in WebView still doesn't work after opening in WebView>

### ISSUE THREAD

**Issue by AbsolutePepega** [tachiyomiorg/tachiyomi-extensions#7386]
## Device information
- Tachiyomi version:  Stable 0.11.1
- Android version: 11

## Source information
- Name: Manga18 Fx
- Extension version: 1.2.5

## Steps to reproduce
1.  Open in WebView
2.  Still asking me to check in WebView
### Expected behavior
Describe what should have happened

Manga/Manhwa should show up the list on the site.

### Actual behavior
Describe what happens instead
The extension has an error that cannot access and asked  to check in webview to see if it is running fine, it runs fine but when I get back to tachiyomi it still has the error.

**Comment by somebody1234** [comment]
it's no longer using madara, will probably need a custom extension now

**Comment by Incognito546** [comment]
Update: 24 Sept. 2021
Same issue, error404 but webview ok.
Tachi ver. 0.12.2
Ext. Name: Manga18fx.com
Ext Ver. 1.2.12
Added steps:
1. Tried VPN, still the same problem.

Phone: android 9
