### ISSUE TITLE
[Bug] <AsuraScans >: <can't download or view chapters >

### ISSUE THREAD

**Issue by SingiuStefan** [tachiyomiorg/tachiyomi-extensions#7388]
---

## Device information huawei p 40 lite 
- Tachiyomi version: 0.11.1
- Android version: 10

## Source information
- Name: AsuraScans 
- Extension version: 1 2.5

## Steps to reproduce
1. Enter extension 
2. Press any manhua 

### Actual behavior
Shows error 500,
![Screenshot_20210602_192416_eu kanade tachiyomi](https://user-images.githubusercontent.com/69900628/120520116-1952a480-c3dc-11eb-88c6-23f308a2b944.jpg)
![Screenshot_20210602_193654_eu kanade tachiyomi](https://user-images.githubusercontent.com/69900628/120520125-1c4d9500-c3dc-11eb-9edc-1754d687dcb4.jpg)
![Screenshot_20210602_193853_eu kanade tachiyomi](https://user-images.githubusercontent.com/69900628/120520146-1fe11c00-c3dc-11eb-848f-7297b61f3dde.jpg)

**Comment by somebody1234** [comment]
can't reproduce

**Comment by CrepeTF** [comment]
Preceded by #7395
