### ISSUE TITLE
[Bug] <Asura Scans>: <Only getting credits pages>

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#7395]
## Device information
- Tachiyomi version: 0.11.1
- Android version: Android 11

## Source information
- Name: Asura Scans
- Extension version: 1.2.5

## Steps to reproduce
1. Open Solo Leveling or Constellation
2. View latest chapter, 154 or 28 respectively

### Expected behavior
Series should have about 8-10 pages available

### Actual behavior
Only recievinf credits pages

## Other details
None

**Comment by somebody1234** [comment]
working fine for me

**Comment by somebody1234** [comment]
looks like they're hosted on imgur for some reason
