### ISSUE TITLE
[Bug] DMZJ: Making some wrong requests.

### ISSUE THREAD

**Issue by PussAzuki** [tachiyomiorg/tachiyomi-extensions#7396]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: DMZJ
- Extension version: 1.2.18

## Steps to reproduce
1. 点开[最近更新]
2. 点开【和喜欢游戏的朋友各种轶事】
3. 点击任意章节，会提示 没有找到页面 ，使用httpcanary抓包发现请求到了 [链接A](https://m.dmzj1.com/chapinfo/https://m.dmzj.com/chapinfo/46372/116015.html.html)和 [链接B](https://api.m.dmzj1.com/comic/chapter/https://m.dmzj.com/chapinfo/46372/116015.html.html)

### Expected behavior
应该像其他漫画一样正确的请求

### Actual behavior
请求到了错误的地址，于是没法查看漫画

## Other details
暂无

**Comment by LenKiMo** [comment]
无法在 TachiJ2K 1.0.17 + DMZJ 1.2.18 上复现此问题。

![photo_2021-06-03_10-32-23.jpg](https://i.loli.net/2021/06/03/qQgSPvBRyxLOh94.jpg)

1.2.17-18 版本更新了 API 与请求方式，如果更新扩展后无法阅读，可以尝试在章节页面刷新要求扩展重新获取漫画信息来刷新章节链接。

**Comment by Oldwangtouchtouchdoge** [comment]
从1.2.17版开始变更了章节URL的存储格式和拼接逻辑，但由于tachiyomi本地缓存的章节URL还没有更新为新格式，所以你会看到URL拼接成了奇怪的样子🤣。
从1.2.16或以前的版本更新到1.2.17或以上时，需要手动下拉刷新漫画信息或者全局获取新章节，把本地缓存的章节URL覆盖为新格式，不过在此过程中会出现章节标题不含数字或者章节号码重复的章节被再次标记为未读（请参考 #6858 中的说明），但章节URL更新为新格式后应该就不会再出现这种情况了。另建议等待1.2.19版上线，17和18版有点小问题。

**Comment by PussAzuki** [comment]
我是从16版本更新到18版本的，看到不能看的时候以为是本体不够新，然后，就有了这个issue

**Comment by MiyouQ** [comment]
更完发现隐藏漫画都无法观看了

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> 更完发现隐藏漫画都无法观看了

方便提供具体看不了的漫画名称或者地址吗？我来看看是不是插件的问题。

**Comment by LenKiMo** [comment]
> > 更完发现隐藏漫画都无法观看了
> 
> 方便提供具体看不了的漫画名称或者地址吗？我来看看是不是插件的问题。

《朋友的妹妹只喜欢烦我》
https://m.dmzj1.com/info/51443.html
更新到 19 后，手动刷新章节列表，再打开任意一话，返回空 toast，无法打开。

**Comment by MiyouQ** [comment]
> > 更完发现隐藏漫画都无法观看了
> 
> 方便提供具体看不了的漫画名称或者地址吗？我来看看是不是插件的问题。

试着把本体从0.10更新到最新0.11版本正常了 是我自己的锅( ;´д`)
不过发现最近刚隐藏的<简单易懂的SCP>章节列表缺损严重 不知道是获取问题还是dmzj删章节了

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> > > 更完发现隐藏漫画都无法观看了
> > 
> > 
> > 方便提供具体看不了的漫画名称或者地址吗？我来看看是不是插件的问题。
> 
> 试着把本体从0.10更新到最新0.11版本正常了 是我自己的锅( ;´д`)
> 不过发现最近刚隐藏的<简单易懂的SCP>章节列表缺损严重 不知道是获取问题还是dmzj删章节了

scp这个看起来是网站那边删了，v4api获取不到章节，v1api只能获取一点点，就是你在软件里面看到的那些。

**Comment by pkszzcq** [comment]
请问一下，我Tachiyomi version: 0.11.1

**Comment by MiyouQ** [comment]
试了下
《玛吉纳泰拉》应该是删掉了 百度都搜不出来
《作为恶女活下去的理由》这个能搜到啊
《英雄战争Lovelock》这个没隐藏 不过确实tc上搜不出来

**Comment by MiyouQ** [comment]
> > 方便提供具体看不了的漫画名称或者地址吗？我来看看是不是插件的问题。
> 
> 请问一下，我好几个版本的dmzj插件，很多漫画都没法搜索到，不清楚是哪里的问题。目前更新到了最新。我在雷电模拟器里也可以复现。
> 例如：《玛吉纳泰拉》、《作为恶女活下去的理由》、《英雄战争Lovelock》
> Tachiyomi version: 0.11.1
> Extension version: 1.2.19
> Android version: 11

试了下
《玛吉纳泰拉》应该是删掉了 百度都搜不出来
《作为恶女活下去的理由》这个能搜到啊
《英雄战争Lovelock》这个没隐藏 不过确实tc上搜不出来

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> > > 方便提供具体看不了的漫画名称或者地址吗？我来看看是不是插件的问题。
> > 
> > 
> > 请问一下，我好几个版本的dmzj插件，很多漫画都没法搜索到，不清楚是哪里的问题。目前更新到了最新。我在雷电模拟器里也可以复现。
> > 例如：《玛吉纳泰拉》、《作为恶女活下去的理由》、《英雄战争Lovelock》
> > Tachiyomi version: 0.11.1
> > Extension version: 1.2.19
> > Android version: 11
> 
> 试了下
> 《玛吉纳泰拉》应该是删掉了 百度都搜不出来
> 《作为恶女活下去的理由》这个能搜到啊
> 《英雄战争Lovelock》这个没隐藏 不过确实tc上搜不出来

插件内用的是旧版的搜索api，我在dmzj官网三个都能搜到，后面我改一下搜索逻辑。

**Comment by PussAzuki** [comment]
现在动漫之家是换了API还是什么情况?
插件这边没法使用了唉

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> 现在动漫之家是换了API还是什么情况?
> 插件这边没法使用了唉
> 插件是 1.2.19

dmzj的api网址有变化，已经有大佬改了，等待1.2.20版上线就行。

**Comment by zhongfly** [comment]
问题已解决，可以关闭。

Problem solved, can be closed @alessandrojean
