### ISSUE TITLE
[Source Request] <QuegnaTT>

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi-extensions#7405]
## Source website - pignaquegna.altervista.org
- Name: QuegnaTT
- Link:
Forum: qtt.forumcommunity.net
Reader: pignaquegna.altervista.org
- Language(s): Italian

## Other details
It's the exact same layout as the italian PhoenixScans Extension. Here are some examples:
https://www.phoenixscans.com/reader/series/domestic-na-kanojo/
http://pignaquegna.altervista.org/

**Comment by AlexMiniReal** [comment]
Thanks a lot somebody1234! Where can I download the extension?

**Comment by Riztard** [comment]
you wait

**Comment by AlexMiniReal** [comment]
ok!
