### ISSUE TITLE
[Source Request] <bilingualmanga.con>

### ISSUE THREAD

**Issue by DaCat1337** [tachiyomiorg/tachiyomi-extensions#7411]
## Source website
- Name: Bilingualmanga 
- Link: https://bilingualmanga.com/ 
- Language(s): Japanese

## Other details
Site for learning Japanese with manga, it can switch between Japanese and English so I'm not sure how feasible it is to make it into a source but yeah.

**Comment by alessandrojean** [comment]
Unfortunately, it's not possible to create an extension for this website because the text is separated from the images.
