### ISSUE TITLE
LegionAsia

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7420]
## Source website
- Name: LegionAsia
- Link: https://legionasia.com
- Language(s): Spanish (ES)

**Comment by Riztard** [comment]
hmm website theme easttheme similar to mangastream

**Comment by NarellaproA1** [comment]
@alessandrojean @loocool2 @SamB @dev @ChrisJAllan 
Please can do it has many flight sleeves and also contain updates of several existing sleeves so I ask you please to elaborate it to

**Comment by Suiren5** [comment]
Please we need legionasia
