### ISSUE TITLE
[Bug] Tsuki Mangás: Cloudflare error 1020 / error 403

### ISSUE THREAD

**Issue by geennalis** [tachiyomiorg/tachiyomi-extensions#7421]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9.0

## Source information
- Name: Tsuki Mangás
- Extension version: 1.2.16

## Steps to reproduce
1. Read manga on Tsuki Mangás web view: error 1020
2. Read manga in tachiyomi app : error 403

### Expected behavior
Expected to update the display page with the latest site listing.

### Actual behavior
Returns error in web view (1020) and in application view (403)

## Other details
![Screenshot_20210603-131703](https://user-images.githubusercontent.com/42114221/120685565-5b302900-c476-11eb-9c3f-805c59acd0cd.png)
![Screenshot_20210603-131713](https://user-images.githubusercontent.com/42114221/120685585-5f5c4680-c476-11eb-9108-5b3c75b7ae4a.png)

**Comment by alessandrojean** [comment]
O funcionamento da extensão está desabilitado temporariamente por conta dos responsáveis pelo site estarem realizando algumas manutenções nos servidores.

**Comment by geennalis** [comment]
Nem tinha me tocado que eles estavam fazendo manutenção. Obrigado.
