### ISSUE TITLE
[Bug] <Remanga (RU)>: <Says to authorize>

### ISSUE THREAD

**Issue by coffinforgrowth** [tachiyomiorg/tachiyomi-extensions#7423]
When I try to load manga on this source, that is age restricted by source, it says in description of manga to authorize in webview but even I authorize it keeps asking me to authorize and doesn't show chapters! Could Russian contributor that works on this source fix this?

**Comment by e-shl** [comment]
Какая манга? И как авторизировались?

> Translate:
What manga?  And how authorize?

Обсуждение приложения на русском:
https://4pda.to/forum/index.php?showtopic=805780 
Также телеграмм: [@Tachiyomi_RUS](https://t.me/Tachiyomi_RUS)

> Translate:
Discussion of the application in Russian:
https://4pda.to/forum/index.php?showtopic=805780
Also telegram: [@Tachiyomi_RUS](https://t.me/Tachiyomi_RUS)
