### ISSUE TITLE
[Feature Request] All Sources : Open links in app

### ISSUE THREAD

**Issue by danrleylfd** [tachiyomiorg/tachiyomi-extensions#7425]
## What feature should be added to this source?

- [ ] Open all extension sites with the app.

Explain why this should be added

- [ ] Because this is a feature that is already available in some extensions and it would be nice if it worked in all others.

**Comment by alessandrojean** [comment]
It's kinda hard to add to all existing sources, since some of them have differences in how the website works, and it would also be a lot of work, since we have more than 600 sources.

It's better that you open an issue requesting this feature only for the sources you want it.
