### ISSUE TITLE
[Bug] <SamuraiScan>: <HTTP error 404>

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi-extensions#7427]
## Device information
- Tachiyomi version: 0.11.1 
- Android version: 9.1.0 

## Source information
- Name: SamuraiScan 
- Extension version: 1.2.5 

## Steps to reproduce
![119904453-076e8e80-bf10-11eb-8531-88bd19d12c08.jpg](https://user-images.githubusercontent.com/78783435/120694410-c6c2c800-c46f-11eb-93ac-8d761f708c1f.jpg)

![119904461-0d646f80-bf10-11eb-9b70-894a2e9c4cca.jpg](https://user-images.githubusercontent.com/78783435/120694436-cde9d600-c46f-11eb-9907-c48c0b90bc68.jpg)
### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by somebody1234** [comment]
seems like it may be using mmrcms now

**Comment by Clouddark75** [comment]
And it's a new version of it. It will need some rework to get it working.

**Comment by aSimpleGuy** [comment]
Duplicate #7258
