### ISSUE TITLE
[Bug] <Nude-Moon>: <Covers don't load automatically>

### ISSUE THREAD

**Issue by BaeronGreg** [tachiyomiorg/tachiyomi-extensions#7428]
---

## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: Nude-Moon
- Extension version: 1.2.7

## Steps to reproduce
1. Open source 
2. After opening the source, you can see that the covers are not loaded 

### Expected behavior
Covers are loaded when the source is opened

### Actual behavior
Covers are not loaded automatically. But when you open some manga, the cover is loaded to it, that is, to see other covers, you need to open each manga in turn

**Comment by somebody1234** [comment]
you need to be logged in to view covers, however that functionality hasn't been added yet. for anyone interested, you need to
`POST` to https://nude-moon.net/setuser.php with the following body: `user_name=<username>&user_pass=<password>&remember_me=y&login=+Sign+in` and saving the `fusion_user` cookie

**Comment by BaeronGreg** [comment]
i'm logged in with web view. but that's not the problem. look here. Previously, covers were loaded automatically. now that the cover would appear, you need to go into the manga itself and only then the cover will be loaded. I show in the screenshots.
![photo_2021-06-04_19-20-00](https://user-images.githubusercontent.com/59482186/120833115-1685ba00-c56a-11eb-9d66-bf330b3448e9.jpg)
![photo_2021-06-04_19-20-00 (3)](https://user-images.githubusercontent.com/59482186/120833187-2b624d80-c56a-11eb-9cfe-dace01041d48.jpg)
![photo_2021-06-04_19-20-01 (2)](https://user-images.githubusercontent.com/59482186/120833204-2f8e6b00-c56a-11eb-9476-ae29b8e4c62b.jpg)

**Comment by somebody1234** [comment]
ah, of course, webview. i might see if i can fix that then, busy for now, i'll see if i have time later today

**Comment by BaeronGreg** [comment]
> ah, of course, webview. i might see if i can fix that then, busy for now, i'll see if i have time later today

Hi.  The problem has been hanging for a long time, can you fix it?

**Comment by Oleksandrigo** [comment]
Same problem. Is it possible to add authorization?
