### ISSUE TITLE
[Bug] <Ichirin no Hana Yuri>: <Cloudflare erro 1020 / erro 403>

### ISSUE THREAD

**Issue by Tomo-kun** [tachiyomiorg/tachiyomi-extensions#7435]
## Device information
- Tachiyomi version: SY dev build r380
- Android version: 11 

## Source information
- Name: Ichirin no Hana Yuri
- Extension version: 1.2.6

## Steps to reproduce
1. Read manga on ichirin no Hana Yuri web view: error 1020
2. Read manga in tachiyomi app : error 403

### Expected behavior
Expected to update the display page with the latest site listing.

### Actual behavior
Returns error in web view (1020) and in application view (403)

## Other details
![Screenshot_20210603-185145_TachiyomiSY](https://user-images.githubusercontent.com/54520491/120718116-2389a700-c49f-11eb-99ad-95129d87334d.jpg)

![Screenshot_20210603-185242_TachiyomiSY](https://user-images.githubusercontent.com/54520491/120718124-26849780-c49f-11eb-89dc-c92f68279d47.jpg)

**Comment by alessandrojean** [comment]
Looks like they are trying to block the extension, I will try to bypass once.
