### ISSUE TITLE
[Bug] <Japanread>: <only showing last chapter + getting error 404 on it>

### ISSUE THREAD

**Issue by Cypral** [tachiyomiorg/tachiyomi-extensions#7438]
## Device information
- Tachiyomi version: stable v0.11.1
- Android version: 10 

## Source information
- Name: Japanread
- Extension version: 1.2.7

## Steps to reproduce
1. Go on any serie from the extension

### Expected behavior
Should show all chapters

### Actual behavior
It only show the last chapter of each serie with sort of a "generic" name

## Other details
see examples below, but it's the same for any serie (last screen is from explorer section)
![Screenshot_2021-06-04-02-06-24-581_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/19366824/120727090-f1496b00-c4d9-11eb-92ba-c13048fcc65d.jpg)![Screenshot_2021-06-04-02-06-31-974_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/19366824/120727096-f3132e80-c4d9-11eb-9999-93db26e626ef.jpg)![Screenshot_2021-06-04-02-06-36-932_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/19366824/120727098-f3abc500-c4d9-11eb-8c58-7a0523ac964e.jpg)![Screenshot_2021-06-04-02-08-26-866_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/19366824/120727099-f4dcf200-c4d9-11eb-8107-f0384bc85e08.jpg)

**Comment by Clouddark75** [comment]
They changed some strings from the chapter list page using rgex for the chapters and imgs.
