### ISSUE TITLE
[Bug] <sekaikomik>: <eror 403 >

### ISSUE THREAD

**Issue by Mugenjin07** [tachiyomiorg/tachiyomi-extensions#7439]
**PLEASE READ THIS**

## Device information
- Tachiyomi version: 0.11.1
- Android version: 10

## Source information
- Name: sekai komik
- Extension version: 1.2.12

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

## Other details
Ketika di buka eror 403 dan jika menggunakan webview cloudflare eror 1020

**Comment by h-hyuuga** [comment]
Duplicate of #7457
