### ISSUE TITLE
[Invalid Sources] List of sources that might be down

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#7448]
Continuation of #5714

Source | Website | Reason
------------ | ------------- | -------------
AniMangaEs | https://animangaes.com/ | Expired
Aloalivn | https://aloalivn.com/ | Connection timed out - 522
Tohomh123 | https://www.tohomh123.com/ | Unable to connect
Bread Factory | https://www.breadfactory.site/ | No A/AAAA/CNAME records
Café com Yaoi | http://cafecomyaoi.com.br/ | Password Protected
Cutie Pie | https://cutiepie.mo/ | No A/AAAA/CNAME records
Comic Star | https://comicstar.org | Blank Page
~~Manganelo.link~~ | ~~https://manganelo.link~~ | ~~Connection timed out~~
MangaRoma | https://mangaroma.com | Expired
Manga Turf | https://mangaturf.com | Connection timed out
Manhuas World | https://manhuasworld.com | SSL_ERROR_RX_RECORD_TOO_LONG
Ookamii Manga | https://manga.ookamii.xyz/ | Blank Page
SocialWeebs | https://socialweebs.in/ | No Content
SoloScanlation | https://soloscanlation.site | Forbidden - 403
TheTopComic | https://thetopcomic.com | Expired
Mundo Wuxia | https://mundowuxia.com | Page Not Found
Yokai Jump | https://yokaijump.fr | Site not installed
Mangareceh | https://mangareceh.id | Connection timed out
MangaYosh | https://mangayosh.xyz | Redirects to Porn site
Shinzoo Scan | https://shinzooscan.xyz | No A/AAAA/CNAME records

**Comment by alessandrojean** [comment]
Banana Mecânica is region locked, I can access just fine, can remove from the list.

**Comment by mcOz1** [comment]
Many sources have cut pages. For example: ManhuaUS, manga1st.

**Comment by jopejoe1** [comment]
> Many sources have cut pages. For example: ManhuaUS, manga1st.

Create a new Issue for that.

**Comment by arkon** [comment]
Closing since it's been a while. Sources can be removed ad-hoc if they seem to be dead.
