### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by RickCypher** [tachiyomiorg/tachiyomi-extensions#7467]
**Device information**
Tachiyomi version: 0.10.12
Android version: 10

**Source information**
Name: Tsuki Mangás
Extension version: 1.2.16

**Problem:**
HTTP Error 403 and Error 1020 in webview

**Comment by alessandrojean** [comment]
Duplicate of #7421.

Por favor, leia minha resposta neste outro issue.

**Comment by RickCypher** [comment]
Nem tinha reparado, obrigado!
