### ISSUE TITLE
[Bug] <Myreadingmanga>: <won't open, app also crashes when trying to view authors other works for all sources>

### ISSUE THREAD

**Issue by jordamuk** [tachiyomiorg/tachiyomi-extensions#7471]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9.0

## Source information
- Name: Myreadingmanga
- Extension version: 1.2.41

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Im able to read chapters from myreadingmanga and view authors works from any source

### Actual behavior
Im not able to read chapters from my reading manga and trying to view author works from any source crashes the app

content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt
Edit: found the logs

--------- beginning of system
--------- beginning of main
06-04 22:18:51.532 26973 26973 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
06-04 22:18:52.395 26973 27018 E SQLiteLog: (284) automatic index on C(manga_id)
06-04 22:18:52.395 26973 27018 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 9 (SDK 28)
Android build ID: 00WW_5_15K
Device brand: Nokia
Device manufacturer: HMD Global
Device name: NB1
Device model: TA-1012
Device product name: TA-1012_00WW

------ beginning of system
--------- beginning of main
06-04 22:19:55.852 27352 27403 E SQLiteLog: (284) automatic index on C(manga_id)
06-04 22:19:55.852 27352 27403 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 9 (SDK 28)
Android build ID: 00WW_5_15K
Device brand: Nokia
Device manufacturer: HMD Global
Device name: NB1
Device model: TA-1012
Device product name: TA-1012_00WW

**Comment by alessandrojean** [comment]
You didn't provide the app version (latest is **not** a valid response), and neither the extension version.

Also, you didn't attach any contents of the log.

**Comment by jordamuk** [comment]
> You didn't provide the app version (latest is **not** a valid response), and neither the extension version.
> 
> Also, you didn't attach any contents of the log.

Ive updated the post
