### ISSUE TITLE
[Bug] <manhuaUS, manga1st>: <pages are cut>

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#7472]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 7.1.2

## Source information
- Name: manhuaUS, manga1st ...
- Extension version: 1.2.7, 1.2.5

## Steps to reproduce
1. open latest chapter 

### Expected behavior
open normally

### Actual behavior
pages are cut

**Comment by Clouddark75** [comment]
Be more precise (witch titles, episodes, etc). I tested some and didn't face cut pages at all.

**Comment by tyme2tb** [comment]
Having the issue with the one below, it appears to be just newest chapter, and not sure about any others:
Reborn 80,000 Years chapter 210

**Comment by conztanz045** [comment]
Some scanlator are starting using half pic to improve the quality on pic on there works just hope it will not affect the image arrangements on the app

**Comment by conztanz045** [comment]
Here a sample:

![Uploading Screenshot_2021-06-06-13-48-32-41_afd66b7916d19a60815f56273408b73e.jpg…]()

**Comment by Clouddark75** [comment]
> Having the issue with the one below, it appears to be just newest chapter, and not sure about any others:
> Reborn 80,000 Years chapter 210

Mate, ManhuaUS and a lot of others pages do this "Soon™" anticipation for the next chapter. Has nothing to do with Tachi. That's why I asked which problems did have the person that did create the ticket. MANGA1ST don't have that, at least as far I know, just tested a couple Manhua/Manwha.

**Comment by Clouddark75** [comment]
> Here a sample:
> 
> ![Screenshot_2021-06-06-13-48-32-41_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/79831076/120914129-8ca33180-c6ce-11eb-9042-3704cced914d.jpg)
> 
> But i think scanlator will fix it in time

That's cool, but those sources don't provide non-wecomics, some websites that have Japanese mangas do indeed uses a scrambling system for their releases. But this isn't not the case. 

OP need to be more precise with what's going on for him. But thanks for sharing your thoughts!

**Comment by mcOz1** [comment]
Ok. Thank for help.
