### ISSUE TITLE
[Bug] <Extension Tsuki Mangás>: <HTTP error 403>

### ISSUE THREAD

**Issue by muriloepiphanio** [tachiyomiorg/tachiyomi-extensions#7473]
Sorry, but I saw this on Twitter today: 
🔥 #TsukiMangás won't be available as they're under server maintenance
⚠️ The source of #TsukiMangás in Tachiyomi's app will be turned off, while the website's Staff evaluates the status of the servers

Could it be that you can't perform a new font update, because the site was in fact under maintenance that day, but on the same day they fixed the servers and it was back up and running again.

**Comment by alessandrojean** [comment]
Duplicate of #7421.

Por favor, leia meu comentário nesta issue.

> O funcionamento da extensão está desabilitado temporariamente por conta dos responsáveis pelo site estarem realizando algumas manutenções nos servidores. Nada que possamos fazer na extensão para arrumar isto, você deve esperar com que eles reabilitem a permissão de uso da extensão.

A permissão de acesso da extensão ao site foi desabilitada enquanto eles estão fazendo algumas manutenções internas nos servidores, por conta da grande demanda de requisições de usuários do Tachiyomi. Nada que possamos fazer no momento, você deve esperar essa situação ser resolvida, e não há uma previsão para tal.
