### ISSUE TITLE
[Bug] <TuMangaOnline>: <Chapters images are cut in pieces>

### ISSUE THREAD

**Issue by SymonXD** [tachiyomiorg/tachiyomi-extensions#7485]
## Device information
- Tachiyomi version: stable is v0.11.1
- Android version: 9 PKQ1.190319.001

## Source information
- Name: TuMangaOnline
- Extension version: 1.2.34

## Steps to reproduce
1. Select a manwha from TuMangaOnline source
2. Download chapters of the selected manwha 

### Expected behavior
When downloading manwha, the amount of images should be around 20 large ones.  

### Actual behavior
The chapters images are being cut in pieces turning into around 100 images per chapter.

**Comment by loocool2** [comment]
Chapters being cut by the source isn't our problem, we don't control if the chapters are cut more or less.
