### ISSUE TITLE
Asura Scans: Stuck Downloads

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#7486]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: Asura Scans
- Extension version: 1.2.7

## Steps to reproduce
1. Pick a series
2. Download a chapter

### Expected behavior
Chapter should download and be removed

### Actual behavior
Chapter downloads all pages, sits at 100%, gives no error notification, and stays as a _tmp folder

## Other details
Resuming/restarting download does nothing

**Comment by tyme2tb** [comment]
Having the same issue

**Comment by vipzzx** [comment]
same for me

**Comment by Alexluther5** [comment]
Up

**Comment by Ahsan40** [comment]
This extension counts one image extra (if ch has 5 image it shows 6). When is stucks, just go to the Tachiyomi download folder and copy the last image and paste also rename it accordingly (if last image name **05.jpg**, rename new copied image as **06.jpg**) and that will fix the issue.

But the problem is we have to do this for every chapter. It's too much hassle. Just hope that we get an issue fix update soon.

**Comment by conztanz045** [comment]
Up

**Comment by diyanmaykill** [comment]
It's trying to download the extra page that says that the chapter was stolen from AsuraScan's site. It shows up when reading chapters online using the app. It does not show up when reading from their site directly.

**Comment by hyoretsu** [comment]
Still nothing?

**Comment by 8227846265** [comment]
For me, Asura Scan downloads doesn't get completed.

**Comment by hyoretsu** [comment]
Still stuck.

**Comment by lord-ne** [comment]
It might be possible to make the extension always ignore the "stolen" image, which should fix the issue

**Comment by Th3-822** [comment]
> It might be possible to make the extension always ignore the "stolen" image, which should fix the issue. I'll take a look at it in the morning

iirc the extension itself ignores the img, but pageListParse() loads the image from another list at the page and adds it to the list too, so you may have to override that instead of pageSelector and just return the document.select line with the selector
