### ISSUE TITLE
MangaTales

### ISSUE THREAD

**Issue by zeredouni** [tachiyomiorg/tachiyomi-extensions#7488]
Name: MangaTales
Link: https://mangatales.com/
Language(s): Arabic

/
/
/
/
/
/
/

**you can use this**  

`  <It's the same >
`
[/src/ar/gmanga](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/ar/gmanga)

**Comment by Clouddark75** [comment]
Gmanga reader theme.
