### ISSUE TITLE
[Bug] <Sekte Komik>: <All manga not updated>

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#7495]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.1

## Source information
- Name: Sekte Komik
- Extension version: 1.2.8

## Steps to reproduce
1. All manga not updated

### Expected behavior
All manga in this extension not updated

### Actual behavior
All manga in this extension not updated even though in website all manga still updated... I have tried troubleshooting guide but it still cant work

**Comment by Riztard** [comment]
wdym not updated? any example or screenshoot?

**Comment by ellodandra** [comment]
> wdym not updated? any example or screenshoot?

![Screenshot_2021-06-06-11-06-22-98](https://user-images.githubusercontent.com/81138524/120912183-5d34fa80-c6b7-11eb-8292-1ab6762ece55.png)
![Screenshot_2021-06-06-11-05-49-30](https://user-images.githubusercontent.com/81138524/120912184-5efebe00-c6b7-11eb-8877-f5c58138f208.png)

Example : in app tachiyomi manhua Magic Emperor not update chap 199 but in website already update chap 199

**Comment by Riztard** [comment]
it doesnt updated in the manga page either https://sektekomik.com/manga/magic-emperor/
so maybe they have cache issue or intentional
