### ISSUE TITLE
[Bug] DMZJ: Extension Will Pull Other Series Update and Re-marked them as Unread Randomly

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi-extensions#7503]
## Device information
- Tachiyomi version: TachiJ2K 1.0.17
- Android version: 10

## Source information
- Name: DMZJ
- Extension version: 1.2.19

## Steps to reproduce
1. 添加任意带有“其他系列”或“单行本”“Online 版”的漫画
2. 全部设为已读，或将属于“其他系列”的部分设为已读
3. 手动更新一次，或等待自动更新

### Expected behavior
被设为已读的部分不会再重新标记为未读

### Actual behavior
伴随手动刷新或自动更新，带有“其他系列”内容的漫画会被随机标记为未读

## Other details
- 对于更新后第一次手动刷新的漫画，无论其是否带有“其他系列”，更新后若涉及链接变化，即使未读状态被保留，也会被收录最近更新列表。（这并不一定是扩展的问题）
- 大部分“其他系列”被重新标记为“未读”状态的，均非手动刷新，而是在自动更新过程中随机发生的，目前尚未观察到规律
- 部分漫画存在重复拉取，在自动更新中“其他系列”内容被反复标记为未读状态的情况。目前还尚未截到图。

**Comment by arkon** [comment]
Is this the same as #7396?

**Comment by LenKiMo** [comment]
> Is this the same as #7396?

Probably not. This issue is intend to report problem that some chapters re-marked to Unread. #7396 is about wrong URL.

**Comment by LenKiMo** [comment]
这是一个扩展拉取“其他系列”旧更新的案例：

![photo_2021-06-06_22-42-16.jpg](https://i.loli.net/2021/06/06/X4qWvDj3AIOrFZ6.jpg)
![photo_2021-06-06_22-42-17.jpg](https://i.loli.net/2021/06/06/fSRMYyo2FkpzJtl.jpg)
![photo_2021-06-06_22-42-14.jpg](https://i.loli.net/2021/06/06/dkJwa8qOhQReSoX.jpg)

举例来说，《唐山葬》自 2017 年以来便再无更新，其他系列的更新时间在 2015 至 2017 年期间。但是却在用户没有发起更新或阅读的情况下，被自动拉取了更新，并将其他系列设为未读。
其它部分同样展示了在用户未主动发起请求的情况下，部分漫画被自动拉取更新且恢复未读状态的情况。

**Comment by LenKiMo** [comment]
重复拉取更新一例：

《沙々々P站图合集》的“其他系列”被重复拉取，在昨天被拉取更新一次，用户手动设置为已读状态后，今天再次拉取，且重新设为未读状态。

![photo_2021-06-07_20-36-05.jpg](https://i.loli.net/2021/06/07/6uPdHOiYmvtrMaE.jpg)

**Comment by Oldwangtouchtouchdoge** [comment]
> 对于更新后第一次手动刷新的漫画，无论其是否带有“其他系列”，更新后若涉及链接变化，即使未读状态被保留，也会被收录最近更新列表。（这并不一定是扩展的问题）

这个是会的，tachiyomi通过章节url来区分章节，dmzj插件的1.2.17~1.2.19版更新后dmzj漫画的所有章节url都会改变（存储格式变了），只要章节url不存在于本地缓存数据库中，那么这个章节就会被作为“新”章节存入数据库，因此所有刷新到的章节似乎都会被列入“最近更新”列表。这其中的一部分章节可以通过tachiyomi的章节号码识别功能继承已读状态。但dmzj插件中提取章节号码的逻辑是默认逻辑，具体是提取出章节标题中的第一串数字（能识别小数点，并提取小数，章节号码就是用小数保存的），而一旦章节号码有重复，那tachiyomi只能继承其中一个章节的已读状态。

比较理想的解决办法是章节号码也使用`漫画ID章节ID` 的格式保存，但现在我不太敢调整章节号码的逻辑，因为对一些刚从1.2.16版本升级上来的用户来说，一旦章节url和章节号码的格式同时被更改，那么用户可能丢失这篇漫画的所有已读记录。后面我打算在插件设置里面加一个开关来启动这个解决办法。

> 大部分“其他系列”被重新标记为“未读”状态的，均非手动刷新，而是在自动更新过程中随机发生的，目前尚未观察到规律

“全局书架更新”功能也会获取章节列表，而且该功能根据你的设置可能是定时自动运行的。

> 部分漫画存在重复拉取，在自动更新中“其他系列”内容被反复标记为未读状态的情况。目前还尚未截到图。

我认为可能还是章节号码的重复问题，从v4api获取到的标题中含有章节系列的名字，而“连载：5话”和“其他：5话”就会出现章节号码重复的问题了。但按说已读变未读情况只会出现一次，第二次刷新的时候章节url已经固定存为`漫画ID章节ID` 的格式了，这两个值应该是不会变的（如果真的变了那好像就没啥办法解决了的🤣）。目前我暂未观察到更新一次章节列表后手动已读，再更新还会变回未读的情况。

**Comment by LenKiMo** [comment]
目前面临的问题是两个：

1. 全局更新书架时，有随机作品会被拉取“其他系列”的更新
目前观察不出规律。

2. 部分作品存在重复拉取的问题
诸如《沙々々P站图合集》《唐山葬》《非正常镇守府》《彼女的季节》等作品在我的客户端上已经出现三次重复拉取更新的情况，全都发生在书架自动拉取更新的过程中。

问题一倒也并不算特别影响，这是在这几个版本升级过程中必须经历的链接结构更新。但问题二的重复拉取问题比较影响使用，因为这会在最近更新列表里引入大量更新记录，从而干扰更新列表。

另外我使用的是 TachiJ2K 而非本家，不清楚这是否可能会导致问题。

**Comment by LenKiMo** [comment]
需要留意的是，大量被重复拉取更新的《彼女的季节》，其他系列没有**章节号码**。是否可能是因为无法获取章节号码，从而导致未读状态被重复拉起？

**Comment by Oldwangtouchtouchdoge** [comment]
你可以考虑安装一个debug版的原版tachiyomi（debug版包含测试环境，可以通过adb读取日志、查看数据库文件。[link](https://github.com/tachiyomiorg/tachiyomi-preview/releases)），导入现在j2k的书架，看看能不能复现这个情况。
