### ISSUE TITLE
[Bug] Asura Scans: credits only chapters

### ISSUE THREAD

**Issue by Halosheeps** [tachiyomiorg/tachiyomi-extensions#7504]
## Device information
- Tachiyomi version: Stable 0.11.1
- Android version: 11

## Source information
- Name: Asura Scans
- Extension version: 1.2.7

## Steps to reproduce
1. Go to Asura Scans extenstion
2. Open _Capitalist Monster Hunter_.

### Expected behavior
The full chapter should have opened.

### Actual behavior
A single page with only the scanlator's credits is present, claiming the user should visit their site to view the chapter because it is stolen.

## Other details
Using webview you can view the whole chapters without issue. The "stolen content" credits page is present on all of the manwha read through the app, but this one does not allow the user to read any of the chapters through Tachiyomi.

**Comment by CrepeTF** [comment]
It's a novel
