### ISSUE TITLE
[Bug] <Japanread>: <No chapter found>

### ISSUE THREAD

**Issue by Ferreoly** [tachiyomiorg/tachiyomi-extensions#7506]
## Device information
- Tachiyomi version: v 0.11.1
- Android version: 9

## Source information
- Name: Japanread
- Extension version: 1.2.7

## Steps to reproduce
1. Go to the Explorer
2. Click on Sources
2. Click on the Source Japanread
3. No pictures are displayed
4. Click on a Manga (No pictures displayed)
5. No chapter found
### Expected behavior
When i click on the source Japanread, i should see the mangas with their pictures and when i click on a manga i should see the chapters.
### Actual behavior
When i click on the source Japanread, the manga names appear but there are no pictures and when i click on a manga after charging, it displays the message no chapter found.
## Other details
Nothing else

**Comment by xavimaa** [comment]
1.2.8 does not solve the problem

**Comment by arkon** [comment]
Duplicate of #7173
