### ISSUE TITLE
[Feature Request] <Toomics>: <allow vip members to read vip chapters>

### ISSUE THREAD

**Issue by Ferreoly** [tachiyomiorg/tachiyomi-extensions#7507]
## Allow vip members to read and download the vip chapters after connection.
It will help those you haven't a very good connection to read offline.

**Comment by alessandrojean** [comment]
This would probably go against their access terms described on the website and cause bans to the accounts.

![image](https://user-images.githubusercontent.com/14254807/120941319-52e72080-c6f8-11eb-9093-3f168414a8ae.png)

If you have a membership, it's better that you use their website or the official app to read.

**Comment by Ferreoly** [comment]
Ok thanks for the information
