### ISSUE TITLE
[Bug] <Mangadex>: <503 in vebview>

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#7513]
---

## Device information
- Tachiyomi version: r3497
- Android version: 11

## Source information
- Name: mangadex
- Extension version: 1.2.117

## Steps to reproduce
1. open vebview

### Expected behavior
Show new frontend of site

### Actual behavior
503 error

## Other details
![Screenshot_2021-06-07-07-27-28-287_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/120959274-0cc6a700-c762-11eb-95de-529026e7e17c.jpg)
![Screenshot_2021-06-07-07-27-38-756_com.opera.browser.jpg](https://user-images.githubusercontent.com/39062952/120959284-105a2e00-c762-11eb-8121-8f9d496b511c.jpg)

**Comment by Seishirou101** [comment]
should be fixed by #7540
