### ISSUE TITLE
[Bug] <Mangabat>: Downloaded chapters from updates stop being detected

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi-extensions#7523]
App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A725FXXU2AUE1
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

## Source information
- Name: Mangabat
- Extension version: 1.2.6

## Steps to reproduce
1. Save manga to library
2. Make app download updates automatically
3. Wait for manga to update and download chapter
4. Wait again

### Expected behavior
Downloaded chapter should remain readable 

### Actual behavior
Downloaded chapter is no longer accessable from the app. Chapter shows as not downloaded but comic downloaded badge shows that one comic is downloaded. 

## Other details
When you look at the folders where the chapter is stored, all unreadable chapters have are named "read.mangabat (1).com" as opposed to "read.mangabat.com". 

I think this happens because the manga is being updated again after the chapter is added since it only seems to happen to recent chapters.

**Comment by Seishirou101** [comment]
Does this still happen to you? I'm unable to reproduce this, usually when it appends a (1) is because it can't access the folder anymore and thinks it doesn't exist and then tries to create another folder, or the folder exists but the case of the folder is incorrect so it creates another.

**Comment by AwesomeQuest** [comment]
> Does this still happen to you? I'm unable to reproduce this, usually when it appends a (1) is because it can't access the folder anymore and thinks it doesn't exist and then tries to create another folder, or the folder exists but the case of the folder is incorrect so it creates another.

I just checked and it seems to have stopped. However, two manga have unreadable chapters that I hadn't noticed, [Dog Nigga](https://m.mangabat.com/read-nb391820) and [Nidoume No Jinsei Wo Isekai De](https://read.mangabat.com/read-ez36022). All the unreadable folders have the same last modified date, for Dog Nigga it's 2021-06-26 and for Nidoume No Jinsei Wo Isekai De it's 2021-10-04.
