### ISSUE TITLE
[Bug] TBS Scans: Extension Broken

### ISSUE THREAD

**Issue by IBentu** [tachiyomiorg/tachiyomi-extensions#7534]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: TBS Scans
- Extension version: 1.2.3

## Steps to reproduce
Open the Source

### Expected behavior
 The source only contained the One Piece scanlations

### Actual behavior
Shows the "no results found" page

## Other details
TBS Scans added more manga to their site, which I assume was the reason the extension broke

**Comment by Riztard** [comment]
tbs scans?

**Comment by IBentu** [comment]
![Screenshot_20210608-133110__01](https://user-images.githubusercontent.com/26677555/121170624-22b99200-c85e-11eb-82cf-2d5554b22b78.jpg)

**Comment by IBentu** [comment]
Sorry, didn't realize I had a typo, will close issue since it's a duplicate
