### ISSUE TITLE
[Bug] <MangaPark v3>: <Unexpected JSON error and search function broken>

### ISSUE THREAD

**Issue by SilentSparrow02** [tachiyomiorg/tachiyomi-extensions#7538]
---

## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: MangaPark v3
- Extension version: 1.2.4

## Steps to reproduce
1. Open the Source
2. Select on any manga from the ones that appear

### Expected behavior
Manga will open, showing a list of chapters

### Actual behavior
An "Unexpected JSON token" error message is displayed, with no chapters. 
![image](https://user-images.githubusercontent.com/59610509/121121811-ee35de00-c83d-11eb-9270-f1f2550d8709.png)
Screenshot link: (https://i.imgur.com/rQUhxHs.png)
## Other details
Error occurs for all manga. **Search function for the source is also not working**, showing a "closed" message instead. 
![image](https://user-images.githubusercontent.com/59610509/121122013-4cfb5780-c83e-11eb-9229-e3b036f2c0db.png)
Screenshot link: (https://i.imgur.com/26YOEFI.png)

**Comment by alessandrojean** [comment]
Probably will be fixed by #7536.

**Comment by SilentSparrow02** [comment]
All right, thanks

**Comment by SilentSparrow02** [comment]
Problem wasn't fixed by #7536, unfortunately. Closing this and making new issue for version 1.2.5

**Comment by SilentSparrow02** [comment]
Problem wasn't fixed by #7536, unfortunately. Closing this and making new issue for version 1.2.5
