### ISSUE TITLE
[Bug] <samurái scan>: <Error constante 404 >

### ISSUE THREAD

**Issue by Marco-kun** [tachiyomiorg/tachiyomi-extensions#7544]
Cada vez que intento iniciar la fuente samurái scan marca el error 404 lo mismo pasa cuando lo inicio webview en un manga de esa fuente pero cuando inició webview en la misma fuente si funciona 
![e1f0ea54-36c1-4ca4-884a-a82d22dc5452](https://user-images.githubusercontent.com/85567345/121204619-00ffe100-c845-11eb-991c-be858026aeaf.jpg)
![cdf3b783-db75-461c-9d40-c47a6b58ef84](https://user-images.githubusercontent.com/85567345/121204623-01987780-c845-11eb-83a2-3fa1ac3215d8.jpg)
![fa9908fa-e820-4445-a23a-aa013f5d3d17](https://user-images.githubusercontent.com/85567345/121204624-01987780-c845-11eb-8610-bb67662574bd.jpg)

**Comment by Clouddark75** [comment]
Han cambiado de tema y por eso no funciona en Tachi. Por ahora ese tema no es compatible. Así que por ahora migra tus mangas a otras fuentes. 

Te recomiendo que para la próxima revises que no haya un reporte del mismo y abras tus ticket ls en inglés. 

Duplicate of #7258
