### ISSUE TITLE
[Source Request] <Mangaforfree.net>

### ISSUE THREAD

**Issue by Incognito546** [tachiyomiorg/tachiyomi-extensions#7548]
## Source website
- Name: Mangaforfree
- Link: https://mangaforfree.net/
- Language(s): Multi - language, mostly English and Korean

## Other details
Request to add this site to the extensions please.

**Comment by jopejoe1** [comment]
Madara

**Comment by Incognito546** [comment]
Madara has been removed/obsolete.

**Comment by loocool2** [comment]
he's leaving a note for whoever's going to add it that it uses the madara wordpress layout to make it easy for them. Madara was split into a bunch of extensions, we're still using it in other ways
