### ISSUE TITLE
[Bug] <dmzj>: <Failed resolution of: Lkotlinx/serialization/internal/PluginExceptionsKt;>

### ISSUE THREAD

**Issue by isNijikawa** [tachiyomiorg/tachiyomi-extensions#7551]
## Device information
- Tachiyomi version: v-8.6.4-AZ (TachiyomiAZ)

- Android version: 10

## Source information
- Name: dmzj
- Extension version: 1.2.19

## Steps to reproduce
1. First Step 
Go get a TachiyomiAZ then install dmzj extension.
2. Second Step
Using dmzj update some of manga with recently updated source api like Goblin slayer.

### Expected behavior
Describe what should have happened
Normally update manga list.

### Actual behavior
Describe what happens instead

Unable to update manga chapter list, messge me <Failed resolution of: Lkotlinx/serialization/internal/PluginExceptionsKt;>

## Other details
Now open manga in webview will notice me "因版权、国家法规等原因，此漫画暂不提供观看，敬请谅解。".
This won't happen during dmzj version like 1.2.16.
ALSO the extension will make tachiyomiSY/elder versions tachitomi crash.

**Comment by arkon** [comment]
You'll need to ask for TachiyomiAZ to be updated.

We don't support old versions of Tachiyomi.
