### ISSUE TITLE
[Bug] <Kuaikanmanhua>: Can not login Kuaikanmanhua to download and view chapter which was paid

### ISSUE THREAD

**Issue by Rosabis** [tachiyomiorg/tachiyomi-extensions#7556]
---

## Device information
* Tachiyomi version: 0.11.1
* Android version: 9
* Device: Xiaomi MI2

## Steps to reproduce
1. Open the extension
2. Login an account

### Expected behavior
Can view paid chapter through my account

### Actual behavior
Can not watch these chapter which I am paid

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by openube** [comment]
How do you login to the account? I tried login to the account from the webview, but the cookies did not transfer over to the view list. The lock to the purchased chapter remains, unable to login and view.

**Comment by Rosabis** [comment]
> How do you login to the account? I tried login to the account from the webview, but the cookies did not transfer over to the view list. The lock to the purchased chapter remains, unable to login and view.

This also happened to me,so I hope there is a solutipn to solve it.

**Comment by openube** [comment]
Judging from the code [here](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/zh/kuaikanmanhua/src/eu/kanade/tachiyomi/extension/zh/kuaikanmanhua), there is no function to support account login and etc. Perhaps you should turn this into a source request?
