### ISSUE TITLE
[Bug] Mangadex: New extensions fixes all broken statuses except for Completed and Cancelled

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi-extensions#7557]
## Device information
- Tachiyomi version: r3497
- Android version: 9.0

## Source information
- Name: Mangadex
- Extension version: 1.2.118

## Steps to reproduce
1. Go to any completed or canceled manga, as verified via the actual site
2. Refresh

### Expected behavior
Status should update from "Unknown" to either "Completed" or "Cancelled"

### Actual behavior
Status remains unknown

## Other details
There is this comment in MangaDexHelper.kt:
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/49c930d622c6e6c835720da014b82e34924fade0/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt#L78
But I don't really get it. Why can't you just get the status that Mangadex says the series is and use that?

**Comment by Seishirou101** [comment]
that's publication status iirc, and most people don't actually care for that, before it went down, they used the "END" on a chapter to indicate it was done in a particular language and we would check for that but that may be removed now and what its alluding to. I'm not sure about abandoned though.

**Comment by CarlosEsco** [comment]
If we used complete or cancelled from dex then it would break the setting of don't update complete manga in the app, because those statuses relate to publication not scanlation.
