### ISSUE TITLE
[Bug] Mangadex: bbcode regex fails to remove [hr]

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi-extensions#7558]
## Device information
- Tachiyomi version: r3497
- Android version: 9.0

## Source information
- Name: Mangadex
- Extension version: 1.2.118

## Steps to reproduce
1. Go to a manga with an [hr] in the description field, such as Pashiri na Boku to Koisuru Banchou-san
2. Refresh

### Expected behavior
[hr] should be removed

### Actual behavior
It is not

## Other details
N/A

**Comment by Seishirou101** [comment]
not sure if this will be fixed on our side as its not actually suppose to be there and will be fixed by mangadex from what I understand. From their server,

> Title pages
>Yes, descriptions have wacky BBCode, this is getting replaced with Markdown and individual languages are being split out into their own, localised description fields.
>The primary title displayed is currently using the first alternate title listed, which is frequently in the wrong language.

**Comment by CarlosEsco** [comment]
Yea no plans to fix this as descriptions are gonna change once edits are live
