### ISSUE TITLE
[Source Request] <Anitation Arts>

### ISSUE THREAD

**Issue by FlammFR** [tachiyomiorg/tachiyomi-extensions#7567]
## Source website
- Name: Anitation Arts
- Link: https://anitationarts.blogspot.com/
- Language(s): English

**Comment by Clouddark75** [comment]
The website is only available for people with invitations only, hence it will needs an Google account login. 

I believe this can be closed because of the odds and requirements.

**Comment by loocool2** [comment]
It looks like they have a patreon that you can buy into to access the chapters. So someone who wants to add this extension would need a membership.

**Comment by Dreqion** [comment]
The website has been changed for the group

**Comment by CVIUS** [comment]
> The website has been changed for the group

ita https://anitationarts.org ryt? I already added it #8042 so ig this can be closed

**Comment by Dreqion** [comment]
> > The website has been changed for the group
> 
> ita https://anitationarts.org ryt? I already added it #8042 so ig this can be closed

okay
