### ISSUE TITLE
Include theme identifier for multi-source extensions

### ISSUE THREAD

**Issue by ghus3rz** [tachiyomiorg/tachiyomi-extensions#7571]
## What feature should be added to this source?
Hi team
First of all, I definitely appreciate all the works have done in developing and maintaining the applications and its various extensions.
I am opening this request to find out if it's possible to include source theme identifier for the extensions that are part of the multi source extensions, maybe as part of title?
Or I don't mind if it cannot be there but instead in another suitable place.
After the split, which I also appreciate , I can still identify some of these extensions and their main theme if they still use default icons but not when the icons has already been customized  
So in this case if I see multiple extension marked for update. I can  at least have rough idea if it looks like the main multi source code being updated if it affected a large number of extensions from same multi source theme.

Sample of what I would love to see:  
Extension Name (Madara)

I did try searching if there was a previous request but couldn't really find if there was any specific to this. So sorry if this has been discussed before. Thanks again and hopefully there can be a positive feedback on this request.

**Comment by dmswd** [comment]
Then how about creating an extension for each theme
Like foolslide customizable 
And the user writes the source website in it

**Comment by h-hyuuga** [comment]
While not particular convenient, the app already does provide a way to identify themes for multi source extensions: going to the changelog for an extension will bring you to the commit history of the theme (in the  case of multi source extensions)

![](https://i.imgur.com/AcLrN5S.png)

**Comment by Soitora** [comment]
/edit-title "Include theme identifier for multi-source extensions"

**Comment by arkon** [comment]
Not sure why you'd want this.
