### ISSUE TITLE
[Bug] nhentai : titles/names are kinda buggy

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi-extensions#7573]
## Device information
- Tachiyomi version: 1.0.17
- Android version: 11

## Source information
- Name: nhentai
- Extension version: 1.2.28

## Steps to reproduce
1. Add a manga from nhentai to your library
2. Go to source settings and change the title from long to short or vise versa
3. Update your library/category

### Expected behavior
The name should change to the new long/short title

### Actual behavior
The name remains the same

## Other details
The only way to change it is to open the manga directly in your library or the source itself (doesn't matter) and update it manually which is so inconvenient especially if you have a lot of them, so can you please look into it and fix it

**Comment by alessandrojean** [comment]
This is the intended behavior in this case because of app limitations in how the settings and the extensions work at the moment.

Some changes in the app itself would probably need to be done to allow this.
