### ISSUE TITLE
[Bug] <nhentai>: the other language option in the source is wrong

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi-extensions#7577]
## Device information
- Tachiyomi version: 1.0.17
- Android version: 11

## Source information
- Name: nhentai
- Extension version: 1.2.28

## Steps to reproduce
1. Open source option and open the "other" language
2.go down in browse to the other category and open nhentai

### Expected behavior
Since they are only three languages in nhentai and in the source settings there are three plus the "other" Language, then that means that other language is the manga without language, like they remove the text bubble and it is only the drawings, almost no text

### Actual behavior
The other language extension is just all languages together, including the ones with only the drawings

## Other details
I have a request, can you make the other language to be like no English Chinese Japanese since they are the only three languages there, like make it in the search bar be like (-english -Chinese -Japanese) but of course hidden
And another request if you don't mind
Can you add an all language option to the extension, just like the current other language extension, it will have all the languages plus the no language ones, just like a normal webview version

**Comment by alessandrojean** [comment]
Nhentai extension already have fixed that by changing the `other` language to `all` in the latest version. If you still want a new source that excludes the three languages, open a new issue.
