### ISSUE TITLE
[Bug] <Mangas.pw>: <The list of chapters does not appear>

### ISSUE THREAD

**Issue by Heavyarms04** [tachiyomiorg/tachiyomi-extensions#7583]
## Device information
- Tachiyomi version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
- Android version: 10

## Source information
- Name: Mangas.pw
- Extension version: 1.2.3

## Steps to reproduce
1. Enter any manga that is listed in the extension 

### Expected behavior
It should show all the chapters of the manga

### Actual behavior
Only shows 1 chapter of the manga but this does not correspond to the manga

**Comment by CrepeTF** [comment]
#7154
