### ISSUE TITLE
[Source Request] <Monarca fansub>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7586]
## Source website
- Name: Monarca Fansub
- Link: https://monarcafansub.blogspot.com
- Language(s): Spanish (Es)

**Comment by Clouddark75** [comment]
Site with a couple of shorter ad links. Not worth the effort and time.

**Comment by alessandrojean** [comment]
Closing since blogger websites also doesn't contain a proper online reader.
