### ISSUE TITLE
[Bug] MangaDex: Wrong chapter orders

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi-extensions#7599]
## Device information
- Tachiyomi version: SY r383
- Android version: 10

## Source information
- Name: MangaDex
- Extension version: 1.2.118

## Steps to reproduce
1. Open a MangaDex title from your library (doesn't happen for every MangaDex title)
2. Chapters are out of order (See example below. Also occurs often for titles that have a mixture of chapters with and without volume numbers included)
3. Syncing the title does not fix it. Clearing database, cache, etc does not help

### Expected behavior
Chapters should be in order?

### Actual behavior
Chapters in your library from before API relaunched (titles have been migrated from the old to the new IDs - I did not use the migrator app, but just did the migration by hand) have their chapters all out of order. 
- Deleting the title from your library, clearing database cache etc, and then re-adding the title fixes the issue - but that is quite burdensome depending on the size of your library.

## Other details
Example image of out of order chapters: 
![2021-6-10_19-15-31](https://user-images.githubusercontent.com/25085973/121613149-7fb17580-ca21-11eb-81f9-94620038b114.JPEG)

**Comment by CarlosEsco** [comment]
This is an issue with the main app itself.  The db doesn't update source order if the chapters don't change. Which is why removing then clearing db fixes.

**Comment by CarlosEsco** [comment]
Open a ticket on the main repo
