### ISSUE TITLE
[Bug] <tohomh123>: Is not usable

### ISSUE THREAD

**Issue by Rosabis** [tachiyomiorg/tachiyomi-extensions#7600]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: tohomh123
- Extension version: 1.2.2

## Steps to reproduce
1. First Step open this extension
2. Second Step search something

### Expected behavior
Describe what should have happened
1.When you open this extension,it will show manga
2.Show manga which you have searched

### Actual behavior
Nothing but timeout

**Comment by jopejoe1** [comment]
The site seems to be down

**Comment by Rosabis** [comment]
> The site seems to be down

I don't think so,change url to m.tuhao456.com,you will get a result
