### ISSUE TITLE
[Bug] <manhuadui>: Is not usable

### ISSUE THREAD

**Issue by Rosabis** [tachiyomiorg/tachiyomi-extensions#7601]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: manhuadui
- Extension version: 1.2.2

## Steps to reproduce
1. First Step open this extension
2. Second Step search something

### Expected behavior
Describe what should have happened
1.When you open this extension,it will show manga
2.Show manga which you have searched

### Actual behavior
Nothing but errors

**Comment by OncePunchedMan** [comment]
their certificate is expired

**Comment by anenasa** [comment]
Searching works for me, but loading images in chapters is not working. I can open a pull request.
