### ISSUE TITLE
[Source Request] <Mangaka3rb> 

### ISSUE THREAD

**Issue by Abodee90** [tachiyomiorg/tachiyomi-extensions#7605]
---

## Source website
- Name: Mangaka3rb
- Link: https://mangaka3rb.com/
- Language(s): arabic

**Comment by Riztard** [comment]
madara theme

**Comment by Abodee90** [comment]
> madara theme

what

**Comment by alessandrojean** [comment]
He is just saying to however one that pick up this website to add that it uses an existing extension template.
