### ISSUE TITLE
Mangahere not loading chapters. 

### ISSUE THREAD

**Issue by Uelques** [tachiyomiorg/tachiyomi-extensions#7616]
Source information
- Name: Mangahere
- Extension version: 1.2.15

Steps to reproduce
1. Try to load any manga from this source.

Expected behavior
Should load the chapter. 

Actual behavior
Doesn't load anything. 

Other details
It has been a weak since I can't seem to load any pages from mangahere. The site is working OK but when I open the chapters on the app it loads indefinitely.

**Comment by conztanz045** [comment]
Its working on me

**Comment by Riztard** [comment]
working for me as well, try troubleshoot
if still not working, go to discord support
