### ISSUE TITLE
[Bug] <Samurái Scan>: <Error 404 al abrir la extension>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7619]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: Samurái Scan
- Extension version: 1.2.7

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Que se muestren el catálogo de mangas que tiene 

### Actual behavior
Aparece error 404 y no se ve ningún manga 

## Other details
Al abrirlo en la webiew aparece normal y en la extensión aparece 404 abrir en webiew

**Comment by Clouddark75** [comment]
Han cambiado de tema y por eso no funciona en Tachi. Y por esa razón ese tema no es compatible. Así que por ahora migra tus mangas a otras fuentes.

Y te recomiendo que para la próxima revises que no haya un reporte del mismo y abras tus tickets en inglés. 

Duplicate of #7258 and #7427
