### ISSUE TITLE
Deliscan

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#7624]
## Source website
- Name: Deliscan
- Link: https://deliscan.xyz
- Language(s): French

**Comment by h-hyuuga** [comment]
Factory Source: Madara

**Comment by pixelroll** [comment]
I was going to make the request

**Comment by Mitia99** [comment]
@Riztard Factory source label ?

**Comment by Soitora** [comment]
Site domain has expired.

**Comment by Riztard** [comment]
> Site domain has expired.

work for me, maybe regional thing

**Comment by Mitia99** [comment]
@Riztard According to the site admins,domain is really down(You can recheck).For now,I'll close this request then
