### ISSUE TITLE
[Bug] <Flame scan, Lhtranslation,Nonames>: <Connection reset>

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#7626]
## Device information
- Tachiyomi version: 10.11
- Android version: 9

## Source information
- Name: Flame scan, Lhtranslation,Nonames
- Extension version: latest

## Steps to reproduce
1. First Step - refresh library

### Expected behavior
No error

### Actual behavior
Saying connection reset

## Other details
The extension is usable but i need to open the site on webview so i can open the extension

**Comment by conztanz045** [comment]
![Screenshot_2021-06-12-16-55-38-61](https://user-images.githubusercontent.com/79831076/121771259-e90bc280-cba0-11eb-9e0f-4d2124da1d08.jpg)

**Comment by Matakor** [comment]
I am also getting an "error 1020" when attempting to access with webview, may have something to do with it.

**Comment by conztanz045** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7743#issue-925315661

**Comment by CarlosEsco** [comment]
Don't open issues for multiple sources in one issue, as for flame scan they purposely block at times for traffic issues. I've talked to the guy and have no reason to believe it will be permanent
