### ISSUE TITLE
[Bug] <Hentaimimi>: <Downloading Issue,No registered instance or factory for type class kotlinx.serialization.json.json >

### ISSUE THREAD

**Issue by denveroh** [tachiyomiorg/tachiyomi-extensions#7627]
## Device information
- TachiyomiAZ version: v.8.6.4-AZ
- Android version: 11

## Source information
- Name: Hentaimimi
- Extension version: 1.2.5

## Steps to reproduce
1.Browse Hentaimimi extension & add doujins to the library 
2. Select all added doujins in the library 
3. Press download all
4.Read offline 
### Expected behaviour
Should have downloaded with no issues.

### Actual behaviour
Gave error message of: No registered instance or factory for type class kotlinx.serialization.json.json

## Other details
Can't read undownloaded doujins due to the same issue.
Webview works fine

Was working fine with the older extension but after I updated the extension to 1.2.5 it couldn't download.
Other downloaded Doujins take longer to refresh than last time. Using SD card with 512GB to store the downloads.
Can still read downloaded doujins. Thumbnails some of them fail to load.
Have over 2000+ Doujins added.

**Comment by arisudesu** [comment]
Probably the issue is with TachiyomiAZ, not the extension. I could reproduce it with other extension using kotlinx.serialization.json - NaniScans on TachiAZ. However it doesn't repro in both extensions on TachiyomiJ2K and original Tachiyomi.

**Comment by arkon** [comment]
Yes, you'll need to ask for TachiyomiAZ to be updated to work with newer extensions.
