### ISSUE TITLE
[Bug] <mangadex>: <random feature>

### ISSUE THREAD

**Issue by dmswd** [tachiyomiorg/tachiyomi-extensions#7628]
## Device information
App version: 1.7.0 (standard, d5638c620, 19, 2021-06-10T21:24Z)
Preview build: 383
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A315FXXU1CUD4
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Source information
- Name: mangadex
- Extension version: 1.2.119

## Steps to reproduce
1. Open the filter sheet
2. Press the random option

### Expected behavior
A manga should Appear

### Actual behavior
It says no results found

## Other details
Noticed that when using this feature
The ID appears in the search field missing the id:
If I add id: before the manga id it works

**Comment by joseph619** [comment]
Random manga is a SY/Neko feature afaik, so you should open a ticket on SY fork repo
