### ISSUE TITLE
[Bug] <MangaDex>: when sorting with number of followers gives blank cover with text

### ISSUE THREAD

**Issue by ahmedalnouby132** [tachiyomiorg/tachiyomi-extensions#7630]
## Device information
- Tachiyomi version: Stable 0.11.1
- Android version: 10

## Source information
- Name: MangaDex 
- Extension version: 1.2.119

## Steps to reproduce
1. Sort with respect to no of followers
2. scroll a bit.

### Expected behavior
the cover of the manga will show up like normally with other sort options.

### Actual behavior
just gives me a blank cover with text "update your application to get covers"

## Other details
to get the cover you must enter the details page and wait for it to load 
then return to the normal sort page and the normal cover will be in its place

/sorry for bad English/

**Comment by CarlosEsco** [comment]
clear your cover cache, and db in advanced settings.
