### ISSUE TITLE
[Bug] <Lynx Scans>: <Invalid Sourcr URL>

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#7632]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: Lynx Scans
- Extension version: 1.2.2

## Steps to reproduce
1. Browse extension for Tomb Raider King
2. Try to read our download chapter 197-201 (198 works) 

### Expected behavior
Chapter should load or download

### Actual behavior
Shows retry. Downloading gives error of Invalid Host URL

**Comment by IRawXI** [comment]
I noticed that the download of the same chapters failed, and from release day I remember a error message about 'too many connections'.

Anyways, it looks like the first two images of the mentioned chapters aren't loading. I was just able to read the rest just fine.
