### ISSUE TITLE
[Bug]Manga mx:When searching for a certain manga, it does not appear that it has the manga in question and if you enter the extension error #419 appears, but if you enter ma extension itself ai appears the search.

### ISSUE THREAD

**Issue by pito-ui** [tachiyomiorg/tachiyomi-extensions#7634]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 8.1.0

## Source information
- Name: mangaMX
- Extension version: 1.2.10
## Steps to reproduce
1. First Step        en el momento de buscar un manga pulsando explorar no aparece el manga en cuestion, y si entro de la extension, me aparece el mensaje error #419.
2. Second Step
pero si entro en laa fuente directamente y luego busco el manga aparece
### Expected behavior
Describe what should have happened
## steps to reproduce
 1.  When searching for a manga by pressing explore, the manga in question does not appear, and if I enter the extension, I get the error message #419.
 2.  Second step
 But if I go into laa fuente directly and then look for the manga appears
 In the end, she was able to see her face.
 Describe what should have happened
 ### actual behavior
 Describe what happens instead
 And what appears is that the selected manga doesn't appear, just by entering the source directly.
### Actual behavior
Describe what happens instead     
y lo que aparece es que no aparece el manga seleccionado, solo al entrar a la fuente directamente.

**Comment by edgarMejia** [comment]
What is the name of the Manga?

**Comment by pito-ui** [comment]
Mamga.MX

**Comment by edgarMejia** [comment]
Me referia a la serie que te da ese error
