### ISSUE TITLE
[Bug] Mangadex: Covers don't load with error, "update application to view cover"

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi-extensions#7635]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 10

## Source information
- Name: mangadex
- Extension version: 1.2.119

## Steps to reproduce
1. Use mangadex

### Expected behavior
Covers load properly at full quality.

### Actual behavior
Just loads an image saying update application to view covers.

**Comment by jobobby04** [comment]
Clear the database and refresh library covers in Settings → Advanced, restart the app afterwards.

**Comment by rsmyst** [comment]
Ok thanks that seemed to have worked
