### ISSUE TITLE
[meta] fix? or an option to disable the slide bar that appears while scrolling

### ISSUE THREAD

**Issue by areyance** [tachiyomiorg/tachiyomi-extensions#7640]
---

## so currently the slide bar that appears when u scroll more often than not do more harm than good

im unsure if this is becauae im running the app on the Arabic language (which also  affects for example how i can sweep between categories ,as it defaults to the english left to right navigation
so me sqeeping right makes me go to the category on the left etc ) 

it currently snaps to my finger movement when im scrolling across the screen
this is very detremnital for long series when im trying to scan for a specific chapter and suddwnly find myself elsewhere becquse it snapped to my finger while flicking through

i can provide a video of what im expriencing with finger pointers to where i was clicking/scrolling if that helps

**Comment by CrepeTF** [comment]
Wrong repo, see https://github.com/tachiyomiorg/tachiyomi/issues
