### ISSUE TITLE
[Bug] <Bilibili comincs>: <only shows featured webtoons>

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#7646]
## Device information
- Tachiyomi version: j2k 1.0.17
- Android version: 10

## Source information
- Name: Bilibili Comics
- Extension version: 1.2.3

## Steps to reproduce
1. Select Bilibili Comics

### Expected behavior
Show recently updated and other webtoons

### Actual behavior
Only shows featured webtoons on home page

## Other details
idk if this extension is still a work in process

**Comment by FourTOne5** [comment]
1. Bilibili comics doesn't have a latest sort so no Latest
2. Featured aka popular only gives 6 so can't do anything there.

Possible fix for 2 is showing all comics popular or not.

**Comment by alessandrojean** [comment]
Yeah, this is website fault and we can't really do much about it in the extension, so closing.
