### ISSUE TITLE
[Bug] <Saikai Scan>: <update on the website>

### ISSUE THREAD

**Issue by Tomo-kun** [tachiyomiorg/tachiyomi-extensions#7649]
## Device information
- Tachiyomi version: SY 1.7.0
- Android version: 11

## Source information
- Name: Saikai Scan
- Extension version: 1.2.5

## Steps to reproduce
1. Open extension
2. See nothing

## Other details
the site had a major update, generating error when trying to access the extension.

I think that's the reason

**Comment by alessandrojean** [comment]
Yeah, it's most likely it. I will take a look.
