### ISSUE TITLE
[https://www.mangatigre.com/] <mangatigre>

### ISSUE THREAD

**Issue by kael544** [tachiyomiorg/tachiyomi-extensions#7650]
## Source website
- Name: Mangatigre
- Link: https://www.mangatigre.com/
- Language(s): Spanish

## Other details

Is a website that is regular in update and that personally the manga that I don't found or that is out of date I found here.

For example: The Gamer, is a webtoon that in Tachiyomi extension I only have 338 chapters, while in this site I found all chapters to the last chapter published and traduced.

Sorry for my bad English.

En español: es un sitio que siempre es regular con las subidas y que personalmente el manga que no encuentro o que estan desactualizados los encuentro allí.

Ejemplo The Gamer, en los sitios de tachiyomi está en español hasta el 338, mientras que allí están hasta el último número actualizado

**Comment by Seishirou101** [comment]
Duplicate of #2821
