### ISSUE TITLE
[Source Request] <Helvetica Scans>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#7661]
## Source website
- Name: Helvetica scans
- Link: https://helveticascans.com/
- Language(s): English

**Comment by loocool2** [comment]
MangAdventure

**Comment by FireNation323** [comment]
> MangAdventure

?

**Comment by loocool2** [comment]
That's the site template it's built on

**Comment by datreesezcup** [comment]
I'm not sure if a new extension is even needed: it would appear that Helvetica Scans is an exact mirror of Assorted Scans.
Take a look: the sites look to be identical:
- https://assortedscans.com/
- https://helveticascans.com

And: the site title in the tab for Helvetica Scans says: "Home · Assorted Scans"

So as of now, I believe the currently existing "Assorted Scans" extension will work for this source.
(Unless I'm missing something: I have not had time to check if everything is identical between the two sites)

**Comment by ObserverOfTime** [comment]
Helvetica does indeed point to Assorted Scans and the extension already works.
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/516dfdbd364ff933cf788c226bccaeb0f84a698b/multisrc/overrides/mangadventure/assortedscans/AndroidManifest.xml#L18
