### ISSUE TITLE
[Feature Request] <Hipercool>: <Add Filters>

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#7666]
## What feature should be added to this source?
Portuguese Br source

The site have tags for the manga, but the extension dont have the filter selector

**Comment by alessandrojean** [comment]
The [tags page](https://hiper.cool/tags) on the website is broken, so it is not possible to get them to build the filter options.

You can already search by tags by typing it in the normal search too.
