### ISSUE TITLE
[Bug] bato.to: "blocking comic genres" in page options is not respected by extension

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi-extensions#7677]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 7.1.2

## Source information
- Name: bato.to
- Extension version: 1.2.12

## Steps to reproduce
1. browse content with the extension
2. open in web view
3. log in if not logged in
4. go to options (gear wheel in upper-right corner)
5. select tags (genres) in "Blocking Comic Genres" section
6. exit web view, browse content again

### Expected behavior
Whatever tags are selected should not appear in the listing of comics

### Actual behavior
listing of comics is unchanged

## Other details
What I'm attempting to do works for mangadex (well, worked before mangadex went down). If this can't be made to work, I would like to have some way to exclude specific tags from comics listings in general

**Comment by 8227846265** [comment]
I also have the same issue. I see lots of irrelevant genre that I don't want to read on the Latest page of Bato.to extension.

Would be better if the genres can be excluded on the Latest page.

**Comment by vetleledaal** [comment]
Per the settings page those options only block the genres from the home page. The Bato.to extension fetches from the browse section, which has the same behaviour as the website -- ignoring the setting.

Using the home page instead isn't really an option, as there's no pagination or filtering there.

You can check that the pages do not respect this option here:
https://bato.to/browse?langs=en&sort=views_w&page=1 (popular)
https://bato.to/browse?langs=en&sort=update&page=1 (latest)

Given that all the tags are shown you might be able to filter those out in the client, but I'm not sure if that should be done.

**Comment by asdkant** [comment]
I think a reasonable solution would be to be able to save preset queries for browsing any given particular source.

So I could have a button to browse the latest of what I'm interested, which would show what I'd otherwise would get by browsing, then opening the filters to exclude tags/genres and sort by latest.

**Comment by vetleledaal** [comment]
Since the extension can't really modify how the site itself works, I'm closing this issue. [Saving filter data is a feature in the fork TachiyomiSY](https://tachiyomi.org/forks/), but you can also [make an issue in the main repo](https://github.com/tachiyomiorg/tachiyomi), if one doesn't already exist.
