### ISSUE TITLE
[Bug] Hiperdex: The extension doesn't work at all

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#7680]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 8

## Source information
- Name: Hiperdex
- Extension version: 1.2.8

## Steps to reproduce
1. Try to enter in the extension to look for mangas

### Expected behavior
Should load mangas

### Actual behavior
Nothing is loaded and the app says "HTTP error 400: check the website in WebView"

## Other details
in WebView the site works just fine

**Comment by Clouddark75** [comment]
The website change its url to hiperdex2.com

**Comment by GSantos23** [comment]
It is probably that the only change needed is to update the url in:

[https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/overrides/madara/hiperdex/src/Hiperdex.kt](url)

`class Hiperdex : Madara("Hiperdex", "https://hiperdex.com", "en")`

to

`class Hiperdex : Madara("Hiperdex", "https://hiperdex2.com", "en")`

As @Clouddark75 mentions.
