### ISSUE TITLE
[Bug] <Manga crab>: <no muestra los mangas>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7688]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: Manga crab
- Extension version: 1.2.7

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Que se muestren todos los mangas que están disponibles

### Actual behavior
Aparece un error largo y no se muestra nada 

###otros detalles:
En la webiew si habré normal

**Comment by Clouddark75** [comment]
Están cambiando de host porque la página no aguanta más. Seguro por el uso masivo de Tachiyomi. Puede que tarden una semana o un mes para traer una nueva página. Y por favor te lo pido, escribe tus tickets en inglés si quieres ayuda.

The source is moving from hosting.

**Comment by Clouddark75** [comment]
The source has move successfully. This ticket can be close.
