### ISSUE TITLE
[Bug] <viz extension>: <no longer working on my ereader>

### ISSUE THREAD

**Issue by Absentelement** [tachiyomiorg/tachiyomi-extensions#7689]
---

## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: viz
- Extension version: 1.2.11

## Steps to reproduce
1. First Step try to use viz extension on my ereader instead of my phone
2. Second Step viz no longer loads manga on ereader like it did yesterday and still does on my phone

### Expected behavior
it should load manga 

### Actual behavior
says retry on every page

## Other details
works fine on my phone so the extensions not down but as of today no longer works on my ereader I've been reading the viz extension through for several months. All of my other extensions work on my ereader still. I have tried everything on the troubleshooting page.

**Comment by alessandrojean** [comment]
Not able to reproduce, the chapter images are loading fine for me.

Did you try to check if this happens on the Preview version too?
