### ISSUE TITLE
[Bug] Scantrad Union (French) : Double pages 

### ISSUE THREAD

**Issue by Sayyth** [tachiyomiorg/tachiyomi-extensions#7694]
## Device information
- Tachiyomi version: v0.11.1
- Android version: 11

## Source information
- Name: Scantrad Union
- Extension version: 1.2.1

The webtoon manhua on the app for this source have double pages and when you go on the website there is only one page. 

Tachiyomi : 

![Screenshot_2021-06-17-04-35-02-197_eu kanade tachiyomi](https://user-images.githubusercontent.com/86033900/122323978-4c427f80-cf28-11eb-857d-c4cd18ff49b7.jpg)

Website:

![Screenshot_2021-06-17-04-38-37-410_eu kanade tachiyomi](https://user-images.githubusercontent.com/86033900/122323979-4d73ac80-cf28-11eb-84fb-cae07efa7d1f.jpg)

**Comment by Mursaat** [comment]
I've had the problem on other webtoon for a few days.
I'll try to see if I can fix it.
