### ISSUE TITLE
[Bug] <MG Komik>: <the link not fixed>

### ISSUE THREAD

**Issue by ZekkenID** [tachiyomiorg/tachiyomi-extensions#7695]
---

## Device information
- Tachiyomi version: 0.11.1
- Android version: 10

## Source information
- Name: MG Komik
- Extension version: 1.2.8

Reason
Domain transfer from mgkomik.my.id to mgkomik.com
In web view domain site mgkomik.my.id in extension chapter cant be load

**Comment by ZekkenID** [comment]
https://www.udrop.com/5DRO/Screenshot_2021-06-17-13-02-13-633_eu.kanade.tachiyomi.jpg

**Comment by kiriya-aoi** [comment]
Related: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7116
Not sure why you closed it before it was fixed.

**Comment by ZekkenID** [comment]
I thought it was fixed right then, sorry
