### ISSUE TITLE
[Bug] MangaDex: Json Parsing Error

### ISSUE THREAD

**Issue by h-hyuuga** [tachiyomiorg/tachiyomi-extensions#7697]
## Device information
- Tachiyomi version: j2k 1.0.17
- Android version: Android 11

## Source information
- Name: MangaDex
- Extension version: 1.2.120

## Steps to reproduce
1. Open Up [Berserk](https://mangadex.org/title/801513ba-a712-498c-8f57-cae55b38cc92) 
2. Pull Down to refresh Chapter List/Manga Details

### Expected behavior

Manga details should refresh

### Actual behavior

Shows Json Parsing exception (from kotlinx.serialization)

## Other details

I would dump logs, but the exception gets caught and displayed by a toast

![Screenshot_20210617-023211.png](https://user-images.githubusercontent.com/83582211/122344287-a1749600-cf14-11eb-90b8-b8354e874a40.png)

**Comment by animusfracto** [comment]
Looks like this is the same issue as #7678.  You should still be able to update the chapter list by either updating the category that this manga is under or by the periodic update

**Comment by animusfracto** [comment]
@h-hyuuga update your mangadex extension and please close this issue if it's fixed

**Comment by h-hyuuga** [comment]
Closed by #7709
