### ISSUE TITLE
[Bug] Hiperdex: HTTP error 400: check the website in WebView

### ISSUE THREAD

**Issue by BulaLoaf** [tachiyomiorg/tachiyomi-extensions#7703]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: Hiperdex
- Extension version: 1.2.9

## Steps to reproduce
1. Try to enter in the extension to look for mangas

### Expected behavior
Mangas should load correctly

### Actual behavior
HTTP error 400: check the website

## Other details
In bug report #7680, the url was changed to "https://hiperdex2.com", but in #7696, the source was changed back to "https://hiperdex.com". I believe the url in Hiperdex extension needs to be changed back to "https://hiperdex com".

**Comment by Clouddark75** [comment]
It's working fine on my end (tested with different devices). Make sure you bypass throughout Cloudflare on WebView.

**Comment by Clouddark75** [comment]
And make sure you update the extension. The url was changed to hiperdex2.com on that commit.

**Comment by brazor421** [comment]
> And make sure you update the extension. The url was changed to hiperdex2.com on that commit.
Well, apparently, they have changed it back to hiperdex.com. Coz when open in webview i can clearly see "hiperdex.com", and yesterday it was "hiperdex2.com". That's why extension don't work now. I have 1.2.9 version of the extension.

**Comment by Clouddark75** [comment]
You sure about that? It's still hiperdex2.com here. Just try different browsers and devices, its the same url. Same behavior on Tachi, working just fine here. Either you could have some old cache/cookies (or they're having some cache problems with the host and Cloudflare).
Try to clean your cookies and cache.

**Comment by Clouddark75** [comment]
> Well, apparently, they have changed it back to hiperdex.com. Coz when open in webview i can clearly see "hiperdex.com", and yesterday it was "hiperdex2.com". That's why extension don't work now. I have 1.2.9 version of the extension.
> A small clarification: when I bypass cloudflare in webview, adress is hiperdex2.com, but after returning in app, I get error 400, and when I open webview again, the adress is hiperdex.com.

Nvrm, the problem is the 'new' apk store on github.com, it didn't got the URL updated, I guess it failed to compile the new code and it's still uses the 'hiperdex.com' old url instead of the new one 'hiperdex2.com'. That's why you can't see the mangas. My bad I did compile mine, because it takes a couple of hours to get update on Github repository.

**Comment by loocool2** [comment]
If you could create a PR with the changed URL that'd be helpful

**Comment by jferdous70** [comment]
this not fix, ext still broken
