### ISSUE TITLE
[bug] Mangamx search is broken

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#7716]
tachiyomi version: stable 0.11.1
android version: 11

log from tachiyomi: element class kotlinx.serialization.json.Jsonobject is not a jsonarray.
this message is retrieve any time you make a search

**Comment by CrepeTF** [comment]
What happens when you enter webview?

**Comment by Mtkmanjaro** [comment]
@CrepeTF  web view is working well, after the search falied and use web view mode is used take you to the home page of mangamx
