### ISSUE TITLE
Manhwa18.cc: Search and filter not working

### ISSUE THREAD

**Issue by Lunafreya37** [tachiyomiorg/tachiyomi-extensions#7726]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: Manhwa18.cc
- Extension version: 1.2.7

## Steps to reproduce
1. Open Manhwa18.cc extension.
2. Search title and/or filter content.

### Expected behavior
Display search results and/or filtered content.

### Actual behavior
Getting No Result Found

## Other details
I tried the web view and it's working on the web view. Also occur at global search and migrate option

**Comment by curche** [comment]
/edit-title "Manhwa18.cc: Search and filter not working"

**Comment by metroid112** [comment]
Can confirm search isn't working
