### ISSUE TITLE
[Bug] <1st Kiss>: <No date for updated chapters>

### ISSUE THREAD

**Issue by Thonioi** [tachiyomiorg/tachiyomi-extensions#7731]
## Device information
- Tachiyomi version: 0.11.1
- Android version: Android 10 QP1A

## Source information
- Name: 1st Kiss
- Extension version: 1.2.10

## Steps to reproduce
1. Basic trouble shooting done
2. Uninstall/install of app

### Expected behavior
Describe what should have happened
New manga chapters to be displayed on update section

### Actual behavior
Describe what happens instead
New manga chapters to be displayed on update section

## Other details
New manga chapters was not displayed on update section due to no date was added from source

**Comment by jopejoe1** [comment]
That was fixed in the last update and now works fine for me.
