### ISSUE TITLE
Dmzj: Make API endpoints configurable

### ISSUE THREAD

**Issue by erinacio** [tachiyomiorg/tachiyomi-extensions#7733]
## What feature should be added to this source?

Dmzj has multiple endpoints for a specific API. For example, the v4api have at least 3 usable endpoints:

- https://nnv4api.dmzj.com
- https://nnv4api.dmzj1.com (Yes, it's alive again)
- https://nnv4api.muwai.com (According to https://github.com/tachiyomiorg/tachiyomi-extensions/pull/7712#issuecomment-863785354)

There may be even more api endpoints in the future. Some endpoints may be temporarily down in a specific duration (like the dmzj1.com endpoint). Some APIs may behave differently under different endpoints (e.g. some manga can be fetched with dmzj1.com endpoint of v4api, but not dmzj.com, for now). It may be meaningful to make api endpoints configurable to mitigate issues that can be simply fixed by changing api endpoint, before the extension is updated.

-----

简单来说就是最近 dmzj 的 api 地址变动好像变得很频繁，然后 api 地址更改的 PR 合并还要等 review 通过、扩展更新以后才能生效，很慢。考虑到类似问题单纯换个地址就解决了，我寻思这样的话不如直接把每个用到的 api 的地址都做成可配置项，哪个地址好用就手动改成哪个地址，也不用苦等扩展更新了。插件仍然可以在之后更新、把默认值改成确定可用的地址。

**Comment by zhongfly** [comment]
waiting for you to do this……
今天动漫之家的加载又十分地慢了，看来v4 api地址又有问题，还不如直接失败回落到v1
@Oldwangtouchtouchdoge

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> waiting for you to do this……
> 今天动漫之家的加载又十分地慢了，看来v4 api地址又有问题，还不如直接失败回落到v1
> @Oldwangtouchtouchdoge

我最近疯狂加班，可能要过一阵子了😂

**Comment by erinacio** [comment]
> waiting for you to do this……
> 今天动漫之家的加载又十分地慢了，看来v4 api地址又有问题，还不如直接失败回落到v1
> @Oldwangtouchtouchdoge

😂我其实根本不会 Kotlin，我平时都是写 C++ 和 Go 的。三年前写过一点 Java 8 不过大部分都忘光了。得先抽空入个 Kotlin 的门才行。

**Comment by erinacio** [comment]
另外我其实自己在用全部切到 muwai.com 的 debug 版自编译插件，好像速度还行，可以当一个临时的解决方案顶过这一阵子。

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> > waiting for you to do this……
> > 今天动漫之家的加载又十分地慢了，看来v4 api地址又有问题，还不如直接失败回落到v1
> > @Oldwangtouchtouchdoge
> 
> 😂我其实根本不会 Kotlin，我平时都是写 C++ 和 Go 的。三年前写过一点 Java 8 不过大部分都忘光了。得先抽空入个 Kotlin 的门才行。如果需要我这边做什么的话。

巧了，我也没有系统学过kotlin的，靠大学教的一点java加上读读其他插件的代码就直接干了😉 如果有空闲欢迎来添砖加瓦哦。

**Comment by zhongfly** [comment]
> 另外我其实自己在用全部切到 muwai.com 的 debug 版自编译插件，好像速度还行，可以当一个临时的解决方案顶过这一阵子。

所有API都可以直接改成muwai吗？打算先改域名，把现在扛过去

**Comment by erinacio** [comment]
> > 另外我其实自己在用全部切到 muwai.com 的 debug 版自编译插件，好像速度还行，可以当一个临时的解决方案顶过这一阵子。
> 
> 所有API都可以直接改成muwai吗？打算先改域名，把现在扛过去

我只改了所有的 class 级别的 val 字段，没有改最后一个 replace dmzj1.com with dmzj.com。我没有仔细测试过每个 api 下的行为（工作上的事情太多没时间测），我自己用到的场景里目前还没怎么碰到问题。

**Comment by zhongfly** [comment]
> > 所有API都可以直接改成muwai吗？打算先改域名，把现在扛过去
> 
> 我只改了所有的 class 级别的 val 字段，没有改最后一个 replace dmzj1.com with dmzj.com。我没有仔细测试过每个 api 下的行为（工作上的事情太多没时间测），我自己用到的场景里目前还没怎么碰到问题。

我把有把握的改了吧，nnv3 nnv4 images我都确定是官方正在用的

**Comment by zhongfly** [comment]
由于api地址已经稳定，目前看来已不再需要此功能

At present, the api endpoints have been stabilized, and this function is no longer required.
