### ISSUE TITLE
[Bug] <Manhuas.net>: <Updated chapter not loaded to update list>

### ISSUE THREAD

**Issue by JustMe2277** [tachiyomiorg/tachiyomi-extensions#7739]
## Device information
- Tachiyomi version: SY Preview r384
- Android version: 8.1.0

## Source information
- Name: Manhuas.net
- Extension version: 1.28

## Steps to reproduce
1. Update manga (as same as auto update manga)
2. Check the drawer (quick setting), All Manhuas.nets' new chapters list in notification drawer

### Expected behavior
There should be get in app's updates list too, not just in notification.

### Actual behavior
After library update finish, in notification it show Manhuas.net had some chapter updates.

But in the app's updates list, there's no chapter updates from Manhuas.net.

Still, it show there are new chapters, in manga library. 

## Other details
It happened just on Manhuas.net extension, not on any other extension i use. 

![Long_ScreenShot_20210619_044409](https://user-images.githubusercontent.com/78903683/122619186-0d443380-d0ba-11eb-8ca0-60e8116ac452.jpg)
![Long_ScreenShot_20210619_044458](https://user-images.githubusercontent.com/78903683/122619189-0f0df700-d0ba-11eb-95fd-c17110bc196e.jpg)
![Long_ScreenShot_20210619_044418](https://user-images.githubusercontent.com/78903683/122619191-103f2400-d0ba-11eb-854f-a34c53ff23f8.jpg)

**Comment by CrepeTF** [comment]
The chapters probably just don't appear to have chapter dates, same has happened to a few other extensions
