### ISSUE TITLE
[Bug] DMZJ: Character `~` May Cause Searching Problem

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi-extensions#7745]
## Device information
- Tachiyomi version: TachiJ2K 1.0.17
- Android version: 10

## Source information
- Name: DMZJ
- Extension version: 1.2.20

## Steps to reproduce
1. Searching any keyword, with an character `~`（Half Width）

### Expected behavior
Searching can return results without problem.

### Actual behavior
Searching failed with error message `End of input at character 0 of`

## Other details
The full width `～` will not cause this problem.

**Comment by zhongfly** [comment]
网站自身问题，你在动漫之家中搜索还有标点的漫画，一样无结果
