### ISSUE TITLE
Manganelo: Restore backup error

### ISSUE THREAD

**Issue by CoffeeMuggo** [tachiyomiorg/tachiyomi-extensions#7758]
## Device information
- Tachiyomi version: 11.1
- Android version: 11

## Source information
- Name: Manganelo
- Extension version: ???

## Steps to reproduce
1. Create Backup from old Phone (Android 8) to my new one (Android 11)
2. Load the Backup in my Android 11. Did not downloaded any Manga Chapters

### Expected behavior
All of my backup chapters are on my new one. 

### Actual behavior
Most of the Errors came from Manganelo sources

## Other details
Renamed it to manganelo to readmanganato, nothing happens

**Comment by Clouddark75** [comment]
The source is Manganelo.link? If so, that source was removed because is dead. Migrate your mangas from that source to another one, make a new backup and then restore it. Or either you can do search then again on your new device.

**Comment by curche** [comment]
Most points are related to sources like Manganelo/Manganato in https://github.com/tachiyomiorg/tachiyomi/issues/4616

Make sure to create backups in proto.gz. Dont use .json backups
proto.gz backup can restore manga even if the source changed links or is removed. 
And then you can migrate them to another source after restore

**Comment by Seishirou101** [comment]
Closing due to lack of response, please do what curche suggested. If you still have issues, you can try and get help in the discord server in #support.
