### ISSUE TITLE
[Bug] <manytoon>: <downloaded chaptees keep getting deleted from that source>

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi-extensions#7762]
## Device information
- Tachiyomi version: 1.0.17
- Android version: 11

## Source information
- Name: manytoon
- Extension version: 1.2.8

## Steps to reproduce
1. Download any chapter from manytoon
2. Wait for a while(I don't know the conditions,like is it after a few days it gets deleted or maybe after refreshing the category,I don't know, but I think if a manga gets updated, all downloaded chapters from all the mangas from manytoon gets deleted) 

### Expected behavior
The chapter should still be there downloaded

### Actual behavior
It gets deleted even though you didn't even read it

## Other details
Look at the steps

**Comment by Clouddark75** [comment]
I believe you should make this ticket on TachiyomiJ2K. It has some extra features that aren't available on Tachi. 
The only thing I can think of is to check if you have automatic removal enable on TachiyomiJ2K

**Comment by medoria0** [comment]
> I believe you should make this ticket on TachiyomiJ2K. It has some extra features that aren't available on Tachi.
> The only thing I can think of is to check if you have automatic removal enable on TachiyomiJ2K

Nah it is disabled

**Comment by arkon** [comment]
Did you check if the files are still present on your device, and not just in Tachiyomi?
