### ISSUE TITLE
[Bug] <MangaIn>: <No aparece ningún capítulo el único que aparece manda a un hentai>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7764]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 9

## Source information
- Name: Mangas.pw(MangaIn)
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Que aparezcan los capítulos de los mangas 

### Actual behavior
Por cada manga aparece un capítulo el cual manda a un hentai al abrirlo 

## Other details
Hace un mes estaba bien la extensión

**Comment by edgarMejia** [comment]
Te refieres a InMaga? no encuentro ninguna extension llamada "MangaIn".

**Comment by KasukeLp23** [comment]
Ya reportado

**Comment by Clouddark75** [comment]
Porque lo han hecho a propósito. No es la primera vez que lo hacen, van unas cuantas veces ya. Yo pienso que lo más recomendable sería remover la fuente. Ellos no quieren aplicaciones como Tachi o Haruneko usando su página. 

Y OP, te lo pido, deja de crear nuevos tickets duplicados cuando ya han sido reportados. Espera a que alguien con el tiempo lo revise y repare.
