### ISSUE TITLE
[Bug] <Flame Scans>: <HTTP Error 403>

### ISSUE THREAD

**Issue by TsukinoDesu** [tachiyomiorg/tachiyomi-extensions#7766]
## Device information
- Tachiyomi version: 11.1
- Android version: 10

## Source information
- Name: Flame Scans 
- Extension version: 1.2.11

## Steps to reproduce
1. Open Source

### Expected behavior
Show the list of Manga's.

### Actual behavior
HTTP Error 403: Check Website in WebView

## Other details
Opening Source in WebView ends up with the Website Stuck on Cloudflare DDoS Protection

**Comment by conztanz045** [comment]
cant bypass cloudflare having same error

**Comment by CVIUS** [comment]
![Screenshot_20210620-162748.png](https://user-images.githubusercontent.com/84634607/122667313-c69f2800-d1e4-11eb-9994-41208ff57691.png)![Screenshot_20210620-162754.png](https://user-images.githubusercontent.com/84634607/122667315-cb63dc00-d1e4-11eb-8bdf-dcc8af1c152a.png) it works for me

**Comment by conztanz045** [comment]
It fix now

**Comment by TsukinoDesu** [comment]
Fixed now.
