### ISSUE TITLE
[Source Request] <Sad Scans>

### ISSUE THREAD

**Issue by hanshiro6l6** [tachiyomiorg/tachiyomi-extensions#7778]
## Source website
- Name: sadscans
- Link: https://sadscans.com/
- Language(s): Turkish

**Comment by loocool2** [comment]
Do not repost issues

**Comment by CrepeTF** [comment]
Remaking issues doesn't do anything, stop recreating new issues to 'bump' source requests.

Wait for someone who feels like they want to make the source to come along and pick up the issue.
