### ISSUE TITLE
Manga-Fénix: Rate limit needed

### ISSUE THREAD

**Issue by Clouddark75** [tachiyomiorg/tachiyomi-extensions#7779]
## What feature should be added to this source?
They have to migrate many times now because of the heavy use of the site, it's probably they will ask for the source to be removed. So in order to have a less impact on the website. I recommend put a discrete limited for the scan of mangas and chapters loads from the website.

**Comment by Soitora** [comment]
Is this for **Fênix Scanlator** or for **Manga Fenix** ?

**Comment by Clouddark75** [comment]
Manga-Fénix.
