### ISSUE TITLE
[Bug] Flame Scans : Cloudflare bypass not working (inf loop)

### ISSUE THREAD

**Issue by krakerz** [tachiyomiorg/tachiyomi-extensions#7781]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 10

## Source information
- Name: Flame Scans
- Extension version: 1.2.11

## Steps to reproduce
1. Install the plugins
2. if by chance you get 403 error or no page, try opening the webview (random manga is fine in most case)
3. infinite redirect cloudflare

### Expected behavior
cloudflare bypassed normally even in webview

### Actual behavior
infinite loop @ cloudflare

## Other details

also, Manhwahentai.me (1.2.8) has same issue, tho this one can be fixed temporary by opening @ webview once, and after cloudflare bypassed, it's worked normally again (tho the auto update might not working, since it seems it's got cloudflare again)

**Comment by Clouddark75** [comment]
Clean your cookies and cache (make sure you have the best/last version of Webview installed). 
They're still using a basic version of Cloudflare, so  everything does load fine here with differents devices.

**Comment by krakerz** [comment]
already tried the cookies and cache clear from the app (either from vanilla tachiyomi / tachiyomiSY)
already checked the playstore as well for the webview update (no update tho)
still got the issue sadly ._.

**Comment by krakerz** [comment]
here i attach the vid record for it
https://drive.google.com/file/d/1kE9o52Tght2_BvQV5vxeB39Ag4kkdaIr/view?usp=drivesdk

**Comment by Clouddark75** [comment]
Do you have the same infinite loop with Chrome or another browser on your device?
The problem with Cloudflare is that anything can break their DDoS shield. If you have a dynamic IP try to restart your device. It could be that your IP got flagged. The other thing you can do is wait until it gets fixed by itself.

**Comment by krakerz** [comment]
> Do you have the same infinite loop with Chrome or another browser on your device?
> The problem with Cloudflare is that anything can break their DDoS shield. If you have a dynamic IP try to restart your device. It could be that your IP got flagged. The other thing you can do is wait until it gets fixed by itself.

only within tachiyomi, when i'm using opera mobile, it's working as intended, sadly my IP is static right now so... RIP for me if my IP is blacklisted (inside the tachiyomi tho)
![Screenshot_2021-06-21-14-56-09-95_4641ebc0df1485bf6b47ebd018b5ee76](https://user-images.githubusercontent.com/8030983/122727243-088da400-d2a1-11eb-9aa3-360387d65745.jpg)

**Comment by loocool2** [comment]
Flamescans is blocking Tachiyomi at peak times since they're having issues with site load crashing the site

**Comment by krakerz** [comment]
> Flamescans is blocking Tachiyomi at peak times since they're having issues with site load crashing the site

RIP then ;_; might need to migrate them to agregate ones then ._.

**Comment by Clouddark75** [comment]
Yah, no wonder. Too many requests by people is a problem. I have no problem to access the website with Tachi, tho'. I don't use the source but, it a shame when people abuse from it.

**Comment by JustMe2277** [comment]
If you can open that with Opera, but can't open  with Chrome, then you'll need VPN to bypass it, since Opera use VPN at data save mode.

**Comment by krakerz** [comment]
> If you can open that with Opera, but can't open with Chrome, then you'll need VPN to bypass it, since Opera use VPN at data save mode.

nah, i already turn off that too, since i know it's _probably due vpn_
already turn off ad block, data save, vpn etc, still same.
if you're curious with the IP, my ip is static for my whole network (PC, Phone, Server, etc) which is even i open it @ PC or other, it's working fine as intended, only tachiyomi have the problem, maybe due the Browser Agent sent to the flamescan is using tachiyomi for example, and they block it.

**Comment by Dragoon91786** [comment]
Yeah, having the same issues. I updated WebView and tried beta and dev. All resulted with infinite loop.

I even attempted running DNS66 off F-Droid and that was a no-go. Cloudflare DNS via HTTPS didn't help either. I cleared the cache likewise.

Is there some way that we can help throttle the extension by working in tandem with the flamescans dev like has been happening with the dev team for MangaDex?

Also, anyone got any ideas on when the site's Tachiyomi block goes down? Like, can they give us a window at the very least or have the app programmed with additional refresh delays for updates?

I'll need to put flamescans in a separate category that doesn't update automatically so it doesn't break the server.

**Comment by Dragoon91786** [comment]
Anyhow, thanks for tye help, everyone! :3

**Comment by Dragoon91786** [comment]
> > If you can open that with Opera, but can't open with Chrome, then you'll need VPN to bypass it, since Opera use VPN at data save mode.
> 
> nah, i already turn off that too, since i know it's _probably due vpn_
> already turn off ad block, data save, vpn etc, still same.
> if you're curious with the IP, my ip is static for my whole network (PC, Phone, Server, etc) which is even i open it @ PC or other, it's working fine as intended, only tachiyomi have the problem, maybe due the Browser Agent sent to the flamescan is using tachiyomi for example, and they block it.

Possibly. Though, they might instead be specifically blocking WebView vs full browsers.

Anyone able to load up WebView in a separate app that can debug/compare, like an app that is a front for WebView as Chrome is it's own thing? [WebView, I'm guessing is built off of Chromium/no proprietary.]

BTW, anyone know if WebView permits JavaScript? Wondering if that could be an issue too.

**Comment by CarlosEsco** [comment]
They are blocking the UA its that simple, either wait out when they decide to block or migrate.

**Comment by CarlosEsco** [comment]
locking due to topics going offtopic from original issue
