### ISSUE TITLE
[Bug] <MangaFast>: HTTP Error 404: Check website in webview

### ISSUE THREAD

**Issue by aSimpleGuy** [tachiyomiorg/tachiyomi-extensions#7786]
### Device information

Tachiyomi version: 0.11.1

Android version: 10

### Source information

Name: MangaFast
Extension version: 1.2.10

### Steps to reproduce

- Browse MangaFast Source
- Scroll down

### Expected behavior

- Should Show available manga

### Actual behavior

- HTTP Error 404: Check website in Webview

### Other details

- Search Not Working

**Comment by MikeZeDev** [comment]
Apparently update changed something on their website and you cant search properly. On my browser i cant list manga at all , by genre or not, nor search them. Unless they have an API and Tachi is using it (which i doubt) i think there is nothing to do until MF fixes that.

**Comment by scb261** [comment]
Should be fixed by #8638
