### ISSUE TITLE
[Bug] <Astral Library>: No Results Found

### ISSUE THREAD

**Issue by aSimpleGuy** [tachiyomiorg/tachiyomi-extensions#7787]
### Device information

Tachiyomi version: 0.11.1

Android version: 10

### Source information

Name: Astral Library
Extension version: 1.2.9

### Steps to reproduce

- Browse Astral Library Source

### Expected behavior

Should Show available manga

### Actual behaviour

- No results found

**Comment by Clouddark75** [comment]
The actual 11 mangas that aren't from Bilibili are visible. Clean your cookies and cache.

**Comment by Riztard** [comment]
it shows available manga for me
