### ISSUE TITLE
Allow extensions to utilize the CatalogueSource provider

### ISSUE THREAD

**Issue by dkanada** [tachiyomiorg/tachiyomi-extensions#7788]
##  Why

I'd like to implement a new extension but the service only provides files as CBZ and other archive formats. Thought it might be possible to override CatalogueSource instead of HttpSource but I don't see a single example within this repository. I'm guessing there are issues with my idea but I'd like to get some confirmation before I start.

## Other Details

The source I'd like to add is Jellyfin, which currently doesn't provide books by their individual pages. Since the LocalSource in the main app seems to support CBZ and related formats with CatalogueSource, I was hoping it might be possible to use here as well.

**Comment by Soitora** [comment]
/edit-title "Allow extensions to utilize the CatalogueSource provider"
