### ISSUE TITLE
[Bug] <ComicKiba>: <Chapters not updated>

### ISSUE THREAD

**Issue by JustMe2277** [tachiyomiorg/tachiyomi-extensions#7789]
## Device information
- Tachiyomi version: Preview r384
- Android version: 8.1.0

## Source information
- Name: ComicKiba
- Extension version: 1.2.8 

## Steps to reproduce
1. Do library global update
2. Check manga chapters from ComicKiba both in library & webview.

### Expected behavior 
Chapters should be updated in Library manga, show as same as in webview.

### Actual behavior
Manga in library not updated, still same chapters as before library update.

## Other details
Not just one manga, but all manga from ComicKiba are like that. 
Doing manual update in manga page do work well btw. 

![Long_ScreenShot_20210621_191404](https://user-images.githubusercontent.com/78903683/122764999-3f2be480-d2ca-11eb-9dc4-38c46f851111.jpg)
![Long_ScreenShot_20210621_191454](https://user-images.githubusercontent.com/78903683/122765015-4226d500-d2ca-11eb-90e4-4bbb7e06282b.jpg)

**Comment by Clouddark75** [comment]
It did take me time to find a Manga that got updated. No problem on my end. Global update works just fine.
Try to migrate then back to ComicKiba or remove them and add it back. Maybe your library got bugged.
If you have many Mangas it can get glitchy.
