### ISSUE TITLE
Manhwahentai.me: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi-extensions#7790]
## Device information
- Tachiyomi version: 1.0.17
- Android version: 11

## Source information
- Name: manwahentai.me
- Extension version: 1.2.8

## Steps to reproduce
1. Open source
2. That's it, you can try downloading many stuff from there to further test it out and see how annoying and inconvenient the problem is

### Expected behavior
It should open and downloaded normally, open it I'm web view from some time to time for it to work and that's it

### Actual behavior
It keeps saying failed to bypass cloudflare but when I open it in web view, most of the time there isn't that loading screen, it opens normal and fast too, it is annoying cuz when I am downloading stuff it keep failing, I try to open it in webview to fix it but there isn't a problem/loading screen to begin with, I can go directly to the site and can read chapters normally and fast too

## Other details
It is so annoying but the site is good so please try to fix it

**Comment by Clouddark75** [comment]
Nothing can be done with Cloudflare protection of the site increase the level. You will need either to keep using it as you do and wait to gets fixed by itself or migrate to another source. So yah, in the worst case scenario they're blocking Tachi.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
