### ISSUE TITLE
[Bug] <GoldenMangás>: <Cloudflare Loop>

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#7791]
## Device information
- Tachiyomi version: 0.11.1 (Preview Too)
- Android version: 11

## Source information
- Name: Golden Mangás
- Extension version: 1.2.10

## Steps to reproduce
1. First Step: Open Extension

### Expected behavior
Open as usual

### Actual behavior
Stucked in cloudflare loop

**Comment by alessandrojean** [comment]
> Some sources may have sophisticated Cloudflare protection, that results in infinite loading in WebView when trying to bypass it. If you're facing this issue, try the following steps:
> 1. Open the source in WebView, tap on the three dots and choose Open in browser, then bypass Cloudflare through the browser.
> 2. Back out of the browser and WebView.
> 3. Open the source in WebView again and try to bypass Cloudflare now.
> 
> **If it still doesn't work, you should migrate to a different source, since it's unknown when and if it will be fixed.**

With that said, I already done the only fix possible before, so there isn't much to do now. It's better to migrate or wait for the source fix itself.
