### ISSUE TITLE
Manga.ae: Pages not found

### ISSUE THREAD

**Issue by Ahmedashraf15** [tachiyomiorg/tachiyomi-extensions#7796]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 6

## Source information
- Name: Manga.ae
- Extension version: 1.2.7

## Steps to reproduce
1. Open the extension
2. Choose any available manga

### Expected behavior
It should normally open

### Actual behavior
When you click on any chapter it shows"pages not found"

## Other details
no thing else

**Comment by iRahmaniMed** [comment]
I have the same problem

**Comment by shipoxx** [comment]
Bcs the site is down

**Comment by shipoxx** [comment]
Here

**Comment by iRahmaniMed** [comment]
The website link must be changed from (https://mngaar.com/) to (https://manga.ae/) in the extension because the first link isn't the official one but the second
