### ISSUE TITLE
Manga-TR: Pages not found

### ISSUE THREAD

**Issue by 6tsugumohanshiro9** [tachiyomiorg/tachiyomi-extensions#7800]
Device information

Tachiyomi version: 0.11.1

Android version: 8.1.0

Source information

Name: Manga-TR

Extension version: 1.2.4

Steps to reproduce

Open the extension

Choose any available manga

Expected behavior

It should normally open

Actual behavior

When you click on any chapter it shows"pages not found"

Other details

no thing else

**Comment by kyoyacchi** [comment]
I have the same problem as well.

**Comment by neppn** [comment]
same
