### ISSUE TITLE
Comick.fun: kotlinx.serialization.json.JsonNull

### ISSUE THREAD

**Issue by Kiriao** [tachiyomiorg/tachiyomi-extensions#7808]
## Device information
- Tachiyomi version: 0.11.1
- Android version: Verisoin 9

## Source information
- Name: Comick.fun
- Extension version: 1.2.4

## Steps to reproduce
Reinstall the extenstion but nothing change

### Expected behavior
It should be able to update the manga chapter as in comick website has updated.

### Actual behavior
When i try to refresh the manga it gave me "kotlinx.serialization.json.JsonNull cannot be cast to kotlinx.serialization.json.JsonLiteral"

## Other details
On the comick.fun "Komi-san wa Komyushou Desu." is updated to chapter 311 but in the Tachiyomi comick extentsion getting error but some of my comick manga is still able to update.

![image](https://user-images.githubusercontent.com/48480973/122864458-43eaaa00-d357-11eb-9195-5dde3d88a3cf.png)

**Comment by FourTOne5** [comment]
I also found the same thing occuring for Shingeki no Kyojin and Please Go Home, Akutsu-san!

**Comment by Soitora** [comment]
/edit-title "Comick.fun: kotlinx.serialization.json.JsonNull"
