### ISSUE TITLE
[Bug] bato.to: "failed to bypass cloudflare" error but web view loads fine

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi-extensions#7820]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 7.1.2

## Source information
- Name: bato.to
- Extension version: 1.2.13

## Steps to reproduce
1. open either latest or regular browse for source "bato.to"
2. wait for it to load, it fails, open web view.

### Expected behavior
List of mangas should load

### Actual behavior
List of mangas doesn't load. I tried clearing cookies, it doesn't work.

> ![image](https://user-images.githubusercontent.com/3915542/122992156-31cf3280-d37c-11eb-86a0-03b2af459fe8.png)

Tachiyomi's help mentiones a load loop, but that's not the issue since the web view loads.

## Other details
The other sources I regularly use are MangaDex, LHTranslations and Mangasushi. Mangasushi seems to be down (informed by CloudFlare), the other too load fine (I know that MangaDex uses CloudFlare).

**Comment by loocool2** [comment]
batoto has raised their Cloudflare protection level possibly due to a DDoS attack, expect to not be able to use the site or the site to be extremely slow during this time.
