### ISSUE TITLE
[Bug] xCaliBR Scans: Can't download/read MGA in-app

### ISSUE THREAD

**Issue by Mikestrike** [tachiyomiorg/tachiyomi-extensions#7821]
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: xCaliBR Scans
- Extension version: 1.2.8

## Steps to reproduce
1. Open Martial God Asura
2. Try to download/read any chapter

### Expected behavior
The chapter should load in it's pages or download

### Actual behavior
Each chapter is only one page long (or fails to load any pages) and constantly tries loading. When attempting to download, it fails to do so with the message: Expected URL scheme 'http' or 'https' but no colon was found.

## Other details
I did have an issue in the WebView once and solved the captcha, but it still didn't fix the issue.

**Comment by Clouddark75** [comment]
They're really blocking Tachi. I recommend you to migrate to another source. Tachi can't access to the chapter images because they're blocking any intent of reading outside of the website.

**Comment by Mikestrike** [comment]
> They're really blocking Tachi. I recommend you to migrate to another source. Tachi can't access to the chapter images because they're blocking any intent of reading outside of the website.

Wow that's really surprising actually. Shame too since they seem to have the best translation I've seen so far.

**Comment by Clouddark75** [comment]
> > They're really blocking Tachi. I recommend you to migrate to another source. Tachi can't access to the chapter images because they're blocking any intent of reading outside of the website.
> 
> Wow that's really surprising actually. Shame too since they seem to have the best translation I've seen so far.

Indeed. Their website couldn't keep up with the requests and used to be down and slow, same with Flamescans. I guess they got tired of it. Some times upgrading the host isn't not the answer. But yah, their Cloudflare setup is pretty aggressive.
