### ISSUE TITLE
[Source Request] <Moon Witch In Love>

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#7827]
## Source website
- Name: Moon Witch In Love
- Link: https://moonwitchinlove.com/
- Language(s): Portuguese

**Comment by Clouddark75** [comment]
Madara theme.

**Comment by alessandrojean** [comment]
I will add it later.

**Comment by Kaylenna** [comment]
Okay thank you ^^
