### ISSUE TITLE
WNACG: The search results will only show the latest 20 manga

### ISSUE THREAD

**Issue by XeroxV** [tachiyomiorg/tachiyomi-extensions#7828]
## Device information
- Tachiyomi version: SY Stable 1.6.2
- Android version: 11

## Source information
- Name: WNACG
- Extension version: 1.2.5

## Steps to reproduce
1. Search for any manga

### Expected behavior
All the manga should appear

### Actual behavior
It will only show the latest 20 manga

**Comment by Clouddark75** [comment]
No problem whatsoever here. Did you try to clear your cookies and cache/data? I did have to download SY, but it was the lastest. But that, no problem with the base version or YS and TachiyomiJ2K, as well tested on different devices.

**Comment by XeroxV** [comment]
Yeap, tried that as well. But it seems like it's only showing the first page when you're searching for something.

**Comment by XeroxV** [comment]
@Clouddark75  Can you show me a screenshot of your search results?

**Comment by Soitora** [comment]
/edit-title "WNACG: The search results will only show the latest 20 manga"

**Comment by nigelinux** [comment]
I confirm I have the same problem. However, for me it seems the search results are the **oldest** (not latest) mangas matching the search queries, so it always stays the same for the same keyword even though I'm sure there are newer manga matching the keywords. I tried with both Tachiyomi (my default) and TachiyomiJ2K (newly installed just to see if it helps) but had the same results.
