### ISSUE TITLE
XafelReader

### ISSUE THREAD

**Issue by AlexMini2517** [tachiyomiorg/tachiyomi-extensions#7835]
## xafelreader.it
- Name: XafelReader
- Link: xafelreader.it
- Language(s): Italian (Italiano)

## Other details
I think the layout is similar to others, so it's maybe easier to do the extension. Thanks in advance to whoever does this extension.

![Screenshot_9](https://user-images.githubusercontent.com/76444133/123146126-d70e0780-d45d-11eb-89f0-eddf1c81dd06.jpg)

**Comment by Clouddark75** [comment]
WPMangaStream theme.

**Comment by AlexMiniReal** [comment]
Why do you remove the Source Request on the title? Isn't it necessary?

**Comment by jobobby04** [comment]
We are in the process of changing the way issues are formatted
