### ISSUE TITLE
[Source Request] <HentaiLib> New extension for app

### ISSUE THREAD

**Issue by wwhoamii** [tachiyomiorg/tachiyomi-extensions#7839]
## Source website
- Name: hentailib
- Link: hentailib.me
- Language(s): Russia (Russian)

## Other details
Hi, the site which name a mangalib.me have another source with hentai manga which name hentailib.me respectively, can you add it for extensions, i think it's gonna be great idea because it's not much extensions in app which have great list of hentai manga, hope for cooperation. Thank for assistance!

**Comment by CrepeTF** [comment]
#3973
