### ISSUE TITLE
Manga TX

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#7851]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manga Tx

### Source link

https://manga-tx.com/

### Language

Arabic?

### Other details

Redirected from https://mangaarabteam.com
Madara

**Comment by Seishirou101** [comment]
this already exists, but may be broken #6498 currently. Or is that what your request is wanting?

**Comment by arkon** [comment]
Whoops, they're not the same.

**Comment by jopejoe1** [comment]
I'm just going through extension that don't have custom icons and if there is an issue with one of them i report it. If its not already reported.
