### ISSUE TITLE
MangaPark v3: Filter not working

### ISSUE THREAD

**Issue by Khr4sh** [tachiyomiorg/tachiyomi-extensions#7855]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

android 11

### Source information

MangaPark v3 1.2.6

### Steps to reproduce

open the sourse from browse 
i click filter 
i click any genre 
i click filter 

### Expected behavior

should give all manga in that genre 

### Actual behavior

it's gives ( no result found )

### Other details

i tried all genre it's the same 
i open it in browser inside the app and i can search in any genre 
![photo_2021-06-25_05-28-21](https://user-images.githubusercontent.com/86451421/123360653-5a228100-d576-11eb-97dd-c3bee76ef5a3.jpg)
![photo_2021-06-25_05-29-00](https://user-images.githubusercontent.com/86451421/123360661-5b53ae00-d576-11eb-8374-4d0c6f575651.jpg)

some tages are hedding like smut and hentai in the app 
but when i enter the browser i can see them all 
my setting i change it so that i can see all type of manga  +18  and others

**Comment by FourTOne5** [comment]
They seem to use different div class for genre search and normal search.
