### ISSUE TITLE
Acggd

### ISSUE THREAD

**Issue by voltes2** [tachiyomiorg/tachiyomi-extensions#7859]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

http://www.acggd.com/

### Source link

http://www.acggd.com/

### Language

chinese

### Other details

this site has unique chinese manga not seen other site

**Comment by Riztard** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/8f38f3fb28fd15a8b837a74a185292338216a67f

**Comment by stevenyomi** [comment]
This is a duplicate of #11820 which was added in #12270.
