### ISSUE TITLE
Manhua'nelo

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#7862]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manhua'nelo

### Source link

https://manhuanelo.com

### Language

English

**Comment by vetleledaal** [comment]
Doesn't appear to be online. It's down at the time of this comment and on December 17, 2021 according to https://web.archive.org/web/20211217103340/http://manhuanelo.com/
