### ISSUE TITLE
MangaZukiNew.online

### ISSUE THREAD

**Issue by ArzuHrpt** [tachiyomiorg/tachiyomi-extensions#7879]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Mangazukinew.online

### Source link

http://mangazukinew.online/

### Language

English 

### Other details

It is the new page the old link sent me when i tried to check a manga from mangazuki.online extension. I had checked the other useable mangazuki extensions and they don't lead the user to this page I am requesting now. Please consider adding this extension. Thank you.

**Comment by jopejoe1** [comment]
Mangabox
