### ISSUE TITLE
edoujin.net

### ISSUE THREAD

**Issue by FrixBOX** [tachiyomiorg/tachiyomi-extensions#7884]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

edoujin.net

### Source link

https://edoujin.net

### Language

English

### Other details
i think it's use wpmangastream
_No response_

**Comment by Clouddark75** [comment]
WP MangaStream.
