### ISSUE TITLE
Mangahasu: no pages found

### ISSUE THREAD

**Issue by leoteesh** [tachiyomiorg/tachiyomi-extensions#7888]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

android 11

### Source information

mangahasu 1.2.12

### Steps to reproduce

Search manga, select chapter to read, open chapter

### Expected behavior

It should open normally

### Actual behavior

Get no page found message

### Other details

It is working fine on the webpage.
Could you please help?

**Comment by kowboj1231** [comment]
The same problem

**Comment by kowboj1231** [comment]
Maybe just wait for Expansion update

**Comment by Riztard** [comment]
work for me, give better steps to reproduce

**Comment by Clouddark75** [comment]
Worked as intended here too. Witch title do you guys have problems with it?

**Comment by leoteesh** [comment]
Hi all 
It is now working for me!
Thanks so much for your time!
