### ISSUE TITLE
Portuguese Extensions: The portuguese extensions don't appear on the sources page

### ISSUE THREAD

**Issue by Gallindel** [tachiyomiorg/tachiyomi-extensions#7896]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

All the portuguese extensions

### Steps to reproduce

1. Download any portuguese extension
2. If I go to the sources page the extension don't appear

### Expected behavior

Normally the portuguese extensions just appear on the sources page, like the other language extensions (The English and Spanish are working well, but the portuguese isn't)

### Actual behavior

The extension aren't showing, so I can't read or search any portuguese manga

### Other details

I tested the English and the Spanish extensions and they are working well

**Comment by alessandrojean** [comment]
You have to enable the Portuguese (Brasil) language on the filter. You can find them at the topbar in the Browse part.
