### ISSUE TITLE
Flame Scans: Split Pages Vertically

### ISSUE THREAD

**Issue by JasonLement** [tachiyomiorg/tachiyomi-extensions#7897]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

8.1.0

### Source information

Flame Scans 1.2.11

### Steps to reproduce

1. Open Flame Scans
2. Open any chapter that was updated on or after 6/27/21, namely Omniscient Reader's Viewpoint, Chapter 61
3. Observe that the pages are split vertically 

### Expected behavior

A normal webtoon should appear as it was in webview.

### Actual behavior

The Pages are split horizontally only showing 50% of the image per page. 

### Other details

![image](https://user-images.githubusercontent.com/80947599/123533488-29357e00-d727-11eb-9c7b-ad046dada222.png)
![image](https://user-images.githubusercontent.com/80947599/123533498-33577c80-d727-11eb-8e86-7da175a6139a.png)
![image](https://user-images.githubusercontent.com/80947599/123533511-3bafb780-d727-11eb-9c04-22cae1623a8b.png)

**Comment by Oridjinn1980** [comment]
Happens for me as well! The second half of the images are the next image over, but that doesn't really help if youre reading it as a webtoon.

**Comment by Kyuuhachi** [comment]
Most or all pages before the change are represented as
```html
<p><img loading="lazy" src="https://flamescans.org/eternalflame/2021/06/ORV61-001.jpg" alt="" width="800" height="10300" class="aligncenter size-full wp-image-30802" /></p>
```
but after the change, most pages (not including title and credits pages) are instead
```html
<div class="composed_figure">
<img loading="lazy" src="https://flamescans.org/eternalflame/2021/07/ORV62-02.jpg" alt="" width="400" height="9545" class="aligncenter size-full wp-image-31477" /><br />
<img loading="lazy" src="https://flamescans.org/eternalflame/2021/07/ORV62-03.jpg" alt="" width="400" height="9545" class="aligncenter size-full wp-image-31478" />
</div>
```

Tachiyomi doesn't support this kind of image manipulation AFAIK, so to work around this would require either:
* modifying the core,
* having the source download all images, merge them, and return the to the core as data: urls (which would be huge and would prevent lazy loading),
* or possibly finding/building a web service that takes two images and concatenates them (I doubt there exists a free one with sufficient capacity).

**Comment by alessandrojean** [comment]
That can be solved with an OkHttp interceptor.
