### ISSUE TITLE
NhatTruyen and NetTruyen: Connection closed

### ISSUE THREAD

**Issue by QuangTKD** [tachiyomiorg/tachiyomi-extensions#7898]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Nettruyen Version 1.2.2

### Steps to reproduce

1. Browse
2. Click on extension NetTruyen ( version 1.2.2, Vietnamese)

### Expected behavior

manga loads normally

### Actual behavior

Nothing show up, it showed like this:
[https://imgur.com/a/Yng6n4D](url)

### Other details

Tried to open in WebView, it's show website dead
[https://imgur.com/a/Kxu6xXq](url)

**Comment by aSimpleGuy** [comment]
NhatTruyen redirects to http://nhattruyentranh.com
NetTruyen redirects to http://www.nettruyentop.com

**Comment by long21wt** [comment]
The issue is still there. This ticket should be reopened till a new pull request.
