### ISSUE TITLE
Webtoon.XYZ: New updates don't show up the "Updates" tab

### ISSUE THREAD

**Issue by naturemarth** [tachiyomiorg/tachiyomi-extensions#7909]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

WebtoonXYZ 1.2.9

### Steps to reproduce

1. Go to the "Updates" tab
2. Look for new updates

### Expected behavior

New updates show, but the notification will show that there are new chapters

### Actual behavior

No new updates will show, but the notification will show that there are new chapters

### Other details

I think this problem is caused due to the fact that these new chapters don't have a date attached to them.

**Comment by Seishirou101** [comment]
You're correct, and there is nothing that can be done from the extension side. You can refer to [this issue](https://github.com/tachiyomiorg/tachiyomi/issues/4938) on the main repo about it.
