### ISSUE TITLE
the return of the best

### ISSUE THREAD

**Issue by npkiler** [tachiyomiorg/tachiyomi-extensions#7913]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

mangá host

### Source link

https://mangahost4.com/

### Language

português

### Other details

I would like you to return to the manga host extension , you are saying that it is obsolete , but it still works and very well , among all the extensions in Portuguese it has always been the best

**Comment by alessandrojean** [comment]
Leia o #7065 também. Ela não vai voltar.
