### ISSUE TITLE
Hitomi.la: Certain titles cause Tachiyomi to crash when searching 2.0

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#7916]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3537

### Android version

A11

### Source information

Hitomi.la 1.2.8

### Steps to reproduce

1.Try search some manga in global search with Hitomi.la extension enabled 
Ex: Yahari Ore no Seishun Love Comedy wa Machigatteiru
2. Press enter and wait to the search ends

### Expected behavior

Finishing the search and be able to browse in results

### Actual behavior

Crash and close the app during the search or when the blue progress bar disappear

### Other details

1. If i search by "Yahari Ore no Seishun" the things runs as expeted, for this reason i suppose that's related to the size of the titles
2. In 0.11.1 (Stable) all works as expect
3. https://github.com/tachiyomiorg/tachiyomi/issues/5474 all start here
4. https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7224 probably this bug returned in preview

**Comment by alessandrojean** [comment]
Closing as the extension was removed (refer to #11613).
