### ISSUE TITLE
DMZJ: Can not Get Manga Cover in List Page

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi-extensions#7917]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] #7918
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

TachiJ2K 1.0.17

### Android version

Android 10

### Source information

DMZJ 1.2.24

### Steps to reproduce

Open manga list page likes Last Update page

### Expected behavior

All manga cover can be loaded.

### Actual behavior

The covers which is not in database, which means it need to pull from website, are failed to load.

### Other details

The cover can load when you open Manga Chapters page, after that, it will display normally in Manga List Page.
Based on this, I might guess the API to get cover is difference from List Page and Chapters Page.
Some of covers can be displayed after upgrade, just because they already saved in database.
This problem once opened in #7698 , but disappear shortly, this time it still occurs for several version.

简言之，在漫画列表中漫画封面将加载失败，需要进入到漫画章节页面才会正常加载出来。加载成功一次后，漫画封面即可正常在任何页面加载。
估计是漫画列表页面和漫画章节页面分别使用了不同的 API 或不同的域名，导致了漫画列表页面获取封面失败。
该问题曾经提报了 #7698 ，但当时很快就恢复了，便取消了 issue。现在该情况已经连续数个版本持续出现，且只出现在 DMZJ 中，故重新提报。

**Comment by LenKiMo** [comment]
Example:

![photo_2021-06-29_09-19-01](https://user-images.githubusercontent.com/10625080/123722797-a560ca80-d8bb-11eb-991e-c739d1cc63be.jpg)

**Comment by erinacio** [comment]
非常微妙，我在同一份代码编译的 Tachiyomi 本体的 release 版里复现了，但是 debug 版里却不能复现。

做了一下三清操作（清除章节缓存，清除 cookie，从数据库中清除未收藏的章节）好像以后好了，也很微妙。可能关键点在于从数据库中清除没有被收藏的漫画。可能还需要手动全量刷新一次收藏漫画的封面。

**Comment by LenKiMo** [comment]
清除应用数据并恢复备份后，该问题暂时得到解决。但清除数据总不能算是个好方法，所以我个人暂时判断保持此 issue 开放。

**Comment by erinacio** [comment]
> 清除应用数据并恢复备份后，该问题暂时得到解决。但清除数据总不能算是个好方法，所以我个人暂时判断保持此 issue 开放。

只清除没有被收藏的漫画也不行么，如果这也不行的话，理论上是 Tachiyomi 本体的问题了，建议去本体的 issue 区提。插件只能给本体提供数据，但是是由本体选择以前的缓存数据还是新数据的。

**Comment by LenKiMo** [comment]
因为直接清了应用数据，所以不清楚只清未收藏漫画的行不行。如果接下来还出现这个情况的话再去本体报 issue 吧。

**Comment by zhongfly** [comment]
我看了下，的确有问题，图片限制了跨域（`Referrer Policy: strict-origin-when-cross-origin`），请求不带refer的话就会403。

**Comment by zhongfly** [comment]
在目前版本上无法复现，问题应该已经解决，应该关闭此issue

It cannot be reproduced on the current version, the problem should be solved. @alessandrojean
