### ISSUE TITLE
svscomics

### ISSUE THREAD

**Issue by Nikustick** [tachiyomiorg/tachiyomi-extensions#7919]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

svscomics

### Source link

https://svscomics.com/

### Language

English

**Comment by h-hyuuga** [comment]
NSFW

**Comment by CrepeTF** [comment]
They seem to host their files on external download sites like Uploaded or keep2share. So you would have to download the files and unzip them. Not to mention from what I see some of the download options have captchas and wait times.
