### ISSUE TITLE
RavenManga

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7920]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

"RavenManga" 

### Source link

https://ravenmanga.xyz

### Language

Spanish

### Other details

Thank you for your work.

**Comment by Elcrack1412** [comment]
Creenla por favor es demasiado buena

**Comment by edmxn** [comment]
Hopefully and if they add it, that website is great

**Comment by Lenoyr** [comment]
_The hope is the last thing you lose_
