### ISSUE TITLE
MyReadingManga: Can't read manga HTTP error 403 but works in webview

### ISSUE THREAD

**Issue by TheFourthEspada** [tachiyomiorg/tachiyomi-extensions#7923]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3537

### Android version

Android 11

### Source information

MyReadingManga v1.2.41

### Steps to reproduce

1. Open source MyReadingManga or saved manga from MyReadingManga
2. Source display HTTP error 403: Check website in WebView or HTTP error 403 for saved manga
![Screenshot_20210629-194810_Tachiyomi](https://user-images.githubusercontent.com/76968890/123896949-65c7cc00-d917-11eb-9bcf-e5bb1df89b47.jpg)
3. Open source in WebView
![Screenshot_20210629-194822_Tachiyomi](https://user-images.githubusercontent.com/76968890/123897059-a889a400-d917-11eb-8fd3-f486d78bb9d6.jpg)
4*. Exit WebView, retry source but still displays HTTP error 403: Check website in WebView

### Expected behavior

If source displays HTTP error 403, open it in WebView wait for Cloudflare, exit WebView, hit retry and source will load

### Actual behavior

If source displays HTTP error 403, open it in WebView, fully loads website [Cloudflare doesn't come up], exit WebView and hit retry but still displays HTTP error 403

### Other details

I've already cleared cookies, database, and chapter cache
I've also cleared cache for Android System WebView and Chrome to see if Cloudflare will come up, it didn't
My IP can't be banned because then I wouldn't be able to access the site at all
I was running a previous preview version that worked for three days then today it didn't. So I updated Tachiyomi to r3537 to see if it would fix it, it didn't.

**Comment by Sleepyysophieee** [comment]
Hi, finding a similar issue here just wondering if you are on a Samsung device as for right now  myreadingmanga is still working on my xiaomi. Thought that it might have been the android system webview bug causing my issue but managed to resolve that and its still not working to no avail. Tried trouble shooting and opening in Webview on both chrome and Samsung Internet but the in app view is still not working.

**Comment by TheFourthEspada** [comment]
Yes I am using Samsung S10 Plus

**Comment by Sleepyysophieee** [comment]
I thought that might have been the case, but today by some sort of karma it stopped working on my xiaomi too. I have only around 40 different manga in my library from myreadingmanga on my xiaomi device compared to several hundred on my Samsung so I don't think its a question of source quantity in the library. Which is in a slightly different area of the troubleshooting guide.

**Comment by McPoops** [comment]
I don't know if this information is useful but this extension works for me if I set my VPN to a server outside North America.  I have no idea why that is though.

**Comment by TheFourthEspada** [comment]
I don't know all I know is I've cleared cookies multiple times to try to get the Cloudflare thing to show up but it doesn't
