### ISSUE TITLE
hell-scan

### ISSUE THREAD

**Issue by Dekkii0** [tachiyomiorg/tachiyomi-extensions#7925]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Hell scan

### Source link

https://hell-scan.eu

### Language

French

**Comment by Clouddark75** [comment]
Madara theme.

**Comment by shipoxx** [comment]
Website doesn't work probably

![IMG_20220131_214113.jpg](https://user-images.githubusercontent.com/61906880/151869831-28def2c1-52d4-41b9-8114-53c8caa38cc6.jpg)

**Comment by alekc** [comment]
@alessandrojean it's still behind the paywall, close?
