### ISSUE TITLE
Geass Scan

### ISSUE THREAD

**Issue by Jir0u** [tachiyomiorg/tachiyomi-extensions#7929]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Geass Scan 1.2.7

### Steps to reproduce

the source is giving error "HTTP error 400"

### Expected behavior

The mangas were supposed to appear

### Actual behavior

It is showing an error

### Other details

![Screenshot_20210630-195941_Tachiyomi](https://user-images.githubusercontent.com/83174135/124042883-35983000-d9e0-11eb-9bec-9d4e935667e5.jpg)

**Comment by alessandrojean** [comment]
They changed the base theme from Madara to WpMangaStream.

**Comment by alessandrojean** [comment]
I submitted a fix on #7932. When it got merged, you will need to uninstall the current extension, install the new one, and migrate your library entries from Geass Scan to Geass Scanlator.
