### ISSUE TITLE
Ace Scans:400 error

### ISSUE THREAD

**Issue by yorozuyaginchan** [tachiyomiorg/tachiyomi-extensions#7933]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

10

### Source information

Ace Scans - 1.2.7

### Steps to reproduce

Ace Scans throws a 400 error and no manga loads up. The webview works fine. 

### Expected behavior

Manga list should be showing up for Ace Scans. 

### Actual behavior

400 error showing up

**Comment by CVIUS** [comment]
they're using wpmangareader now

**Comment by conztanz045** [comment]
Same here

**Comment by conztanz045** [comment]
@CVIUS  what is that?

**Comment by CVIUS** [comment]
> @CVIUS what is that?

wordpress theme :3
