### ISSUE TITLE
manga crab 

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi-extensions#7939]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1 

### Android version

Android 10

### Source information

Manga crab 1.2.7

### Steps to reproduce

Http error 400
![Screenshot_20210701_114123_eu kanade tachiyomi](https://user-images.githubusercontent.com/78783435/124161267-d0395300-da62-11eb-91d0-e584289a45a2.jpg)

### Expected behavior

. 

### Actual behavior

. 

### Other details

Actualizaron el sitio web

![Screenshot_20210701_114531_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/78783435/124162154-cf54f100-da63-11eb-96fb-88ad638ea2f3.jpg)

**Comment by Clouddark75** [comment]
This can be close, the source is using madara again.
