### ISSUE TITLE
Request to add Comick

### ISSUE THREAD

**Issue by RespectfulManga** [tachiyomiorg/tachiyomi-extensions#7943]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Comick

### Source link

https://comick.fun/

### Language

English

**Comment by alessandrojean** [comment]
It already exists. Please do search in the list of extensions before opening a new issue.

**Comment by Riztard** [comment]
and read the Acknowledgements
