### ISSUE TITLE
Gmanga 

### ISSUE THREAD

**Issue by JxDirash** [tachiyomiorg/tachiyomi-extensions#7948]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

.

### Android version

.

### Source information

.

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

This extension is not working!
![Screenshot_20210702-171159_Tachiyomi](https://user-images.githubusercontent.com/83741170/124328164-cb26f180-db91-11eb-955d-ed006d7cbdcf.jpg)

### Other details

.

**Comment by arkon** [comment]
Create another issue with the requested information filled in. Also, specify whether the WebView works or not.
