### ISSUE TITLE
Gmanga error 503

### ISSUE THREAD

**Issue by HeavenShadow** [tachiyomiorg/tachiyomi-extensions#7952]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

10

### Source information

Gmanga 1.2.5

### Steps to reproduce

Open extension 

### Expected behavior

Show manga list

### Actual behavior

![Screenshot_20210703-044742_Tachiyomi](https://user-images.githubusercontent.com/13036407/124342213-456b6c00-dbba-11eb-989c-5ff7959c4a06.jpg)

### Other details

webView keep showing this

![Screenshot_20210703-044713_Tachiyomi](https://user-images.githubusercontent.com/13036407/124342238-65029480-dbba-11eb-9d01-54c24d2e0852.jpg)

**Comment by arkon** [comment]
Closing in favour of #7957
