### ISSUE TITLE
GMANGA: Cloudflare doesn't allow me access to the website in the WebView

### ISSUE THREAD

**Issue by iRahmaniMed** [tachiyomiorg/tachiyomi-extensions#7957]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

GMANGA 1.2.5

### Steps to reproduce

1.Entering to the extension
2.An error appears tell me to check the website in WebView
3.Opening the WebView

### Expected behavior

The Cloudflare allows me to access then i use Tachi normally

### Actual behavior

The Cloudflare doesn't allow me to access no matter how long i wait

### Other details

- When I open the website in Chrome the Cloudflare allows me normally to access.
- I try to open another extension has the Cloudflare protection with the WebView (ManyToon) and it gives me the access normally
- Cloudflare protection is activated in the website only at night, so the extension works normally In the daytime

**Comment by nabiliSdS** [comment]
I have the same problem here,  and I tried a lot of things but didn't work

**Comment by CrepeTF** [comment]
closing in favour of #8114
