### ISSUE TITLE
Manga Door: No carga las páginas 

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7958]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 9

### Source information

Manga Door 1.2.4

### Steps to reproduce

Entro a un capitulo pero no carga las páginas aparece reintentar y nada 

### Expected behavior

Que carguen las páginas respectivas de cada capítulo

### Actual behavior

No carga y aparece reintentar 

### Other details

![Screenshot_20210703_080813_eu kanade tachiyomi](https://user-images.githubusercontent.com/85296132/124355386-70fc4f80-dbd6-11eb-9f64-dab9e4381fa2.jpg)

![Screenshot_20210703_080905_eu kanade tachiyomi](https://user-images.githubusercontent.com/85296132/124355389-78bbf400-dbd6-11eb-8e1a-be0fe356e90e.jpg)

![Screenshot_20210703_080912_eu kanade tachiyomi](https://user-images.githubusercontent.com/85296132/124355397-82455c00-dbd6-11eb-8011-60b835ef5940.jpg)

**Comment by CrepeTF** [comment]
#7374
