### ISSUE TITLE
MangaPark v3: Failed to load pages

### ISSUE THREAD

**Issue by randw0** [tachiyomiorg/tachiyomi-extensions#7963]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3521

### Android version

Android 12

### Source information

Mangapark v3 1.2.7

### Steps to reproduce

Open Chainsaw Man Chapter 7 (title url https://mangapark.net/comic/74763/chainsaw-man)

### Expected behavior

Chapter images load

### Actual behavior

Chapter doesn't load, shows following error 
![Screenshot_20210703-215318_Tachiyomi](https://user-images.githubusercontent.com/54715630/124370105-fe2cbc00-dc49-11eb-94d7-9b193a2d14e1.png)

### Other details

Not sure if this affects other titles/chapters, haven't found anything in the, admittedly small, titles i sampled

**Comment by FourTOne5** [comment]
![Screenshot_2021-07-04-09-14-54-60](https://user-images.githubusercontent.com/59261191/124371927-54304c80-dca8-11eb-8fc2-8d6b3d14d8a2.jpg)

I don't think this needs other explanation.

**Comment by randw0** [comment]
You're right, stupid of me not to check that.

However, I would expect a more user-friendly error message in this case (I think no pages found is used for this situation, but not entirely sure?), instead of the Unexpected Token error message
