### ISSUE TITLE
Mangas.pw (mangas.in): only shows one chapter and it's hen**

### ISSUE THREAD

**Issue by Natillax** [tachiyomiorg/tachiyomi-extensions#7970]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

MIUI 12

### Source information

Mangas.pw 1.2.4

### Steps to reproduce

1. First step: Look for a manga in mangas.pw
2. Second step: Choose one manga.
3. Third step: If there are more than one chapter, reload, and then it will only appear one chapter and it will be hent***.

### Expected behavior

This should happen:
1. First step: Look for a manga in mangas.pw
2. Second step: Choose one manga.
3. Third step: There are a lot of chapters. You can reload and they are still there. You can read them.

### Actual behavior

This happens instead:
1. First step: Look for a manga in mangas.pw
2. Second step: Choose one manga.
3. Third step: If there are more than one chapter, reload, and then it will only appear one chapter and it will be hent***.

### Other details

The update to fix this extension only worked one day...
Could you fix this as soon as possible, please? Is the only good Spanish extension that you have.

**Comment by loocool2** [comment]
Update your extension

**Comment by DTecheira** [comment]
Check open PRs first https://github.com/tachiyomiorg/tachiyomi-extensions/pull/7966

If the solution worked one day, clearly they don't want to be scraped

**Comment by Elcrack14** [comment]
Arreglen ese problema por favor manga.pw es uno de los mejores

**Comment by Clouddark75** [comment]
It was what I say the other weeks. They're checking the Tachi extension code. I once again recommend to remove the source, they don't want their page here.

**Comment by Clouddark75** [comment]
> Arreglen ese problema por favor manga.pw es uno de los mejores

Nada que hacer amigo, ellos lo hace intencionalmente, no quieren su página en la aplicación. Busquen otra fuente.

**Comment by KasukeLp23** [comment]
Lo más recomendable es que migren a otra fuente que si funcione, ya que los de mangas.in no quieren que su página esté en la aplicación, y aunque se arregle de nuevo va a pasar lo mismo una y otra vez.

**Comment by Elcrack1412** [comment]
> > Arreglen ese problema por favor manga.pw es uno de los mejores
> 
> Nada que hacer amigo, ellos lo hace intencionalmente, no quieren su página en la aplicación. Busquen otra fuente.

@Clouddark75 entonces es un problema que manga.pw siga en tachi ya que siempre seguirá con ese error pueden poner otra extensión como hatsuki manga que es parecido el contenido

**Comment by KasukeLp23** [comment]
@Elcrack1412  JAJAJA como vas a comparar Mangas.pw (con mas de 1000 mangas en su página y que se actualizan mucho mas rápido que las demás) con HatsukiManga? (que solo tiene +10 y que solo es de manhwas/donghuas). Hay iguales a Mangas.pw la cual una seria la de KuManga, pero igual da error.

Aunque no se si sea necesario el eliminar la extensión de Tachiyomi, porque igual se puede leer en webview de cada titulo y, si sirve para los mangas que tienen solamente un capitulo.

**Comment by Elcrack1412** [comment]
Es injusto las páginas web más piensan en ellas que en sus usuarios y por eso no deja que podemos tener distintas alternativas ya que en su página es muy lento los capítulos comparado con tachi gracias creadores de tachi por su gran contribución

**Comment by Elcrack1412** [comment]
> su

Bro yo no hablo so de esa hay muchas mas que también tienen mangas y no solo de podría incluir hatsuki manga si no otros como legionAsia RabenManga otakuteka mangalandia hay por lo menos hubiera una cantidad cómoda ya que manga.pw no se puede

**Comment by JhulShock** [comment]
Tengo el mismo problema. Solo me carga 1 capítulo aleatorio
![2](https://user-images.githubusercontent.com/21696690/131945717-55a994dd-f83e-4979-8f43-32b424faafe3.jpeg)
