### ISSUE TITLE
Sekte Doujin: Pages looping and Chapters not found

### ISSUE THREAD

**Issue by Chan220** [tachiyomiorg/tachiyomi-extensions#7982]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1.

### Android version

Android 8.0.0

### Source information

Sekte Doujin 1.2.9

### Steps to reproduce

1. Open Source
2.  Pages Looping
3.  Chapter not found

### Expected behavior

Show update everyday and pages not looping

### Actual behavior

Pages always looping not showing update & Chapter not found

**Comment by Soitora** [comment]
/edit-title "Sekte Doujin: Pages looping and Chapters not found"
