### ISSUE TITLE
NekoBreaker: need update the url

### ISSUE THREAD

**Issue by Tomo-kun** [tachiyomiorg/tachiyomi-extensions#7986]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

SY Preview - 389

### Android version

A11

### Source information

Nekobreaker

### Steps to reproduce

Open the extension

### Expected behavior

appear something

### Actual behavior

Nothing appears

### Other details

they changed their address

The new site: https://nekobreakerscan.com/

**Comment by alessandrojean** [comment]
It seems that the extension was accidentally removed when Madara got split into multiple extensions. I will add it back.

If you're still using the old Madara, you need to uninstall it and install the separate extensions for the sources you use.
