### ISSUE TITLE
Danke fürs lesen: Links are broken 

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#7991]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Tachiyomi SY Preview r390

### Android version

Android 10

### Source information

Danke fürs Lesen

### Steps to reproduce

Open any manga from this source
See description of the manga
You will find the links of the author's social media platforms.
If you try to click on them, they won't redirect you anywhere.

### Expected behavior

Links should redirect you to the author's social media.

### Actual behavior

They don't redirect you anywhere

### Other details

Everything works as intended in the webview.
![IMG_20210706_101211](https://user-images.githubusercontent.com/86711105/124543336-b45af600-de42-11eb-83f5-093a835f1aa3.jpg)

Here is the image of the issue

**Comment by Poggies01** [comment]
O

**Comment by CrepeTF** [comment]
I mean technically it's not a bug, you're not meant to be able to open links in the Synopsis, nor was it a feature in the past

**Comment by Poggies01** [comment]
> I mean technically it's not a bug, you're not meant to be able to open links in the Synopsis, nor was it a feature in the past

Ohhhhhh
