### ISSUE TITLE
Manga Weebs: Fail to display pages

### ISSUE THREAD

**Issue by tancysam** [tachiyomiorg/tachiyomi-extensions#7993]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

 0.11.1 

### Android version

Android 11

### Source information

Manga Weebs 1.2.9  

### Steps to reproduce

1. Open Manga Weebs source
2. Tap on any manga
3. Tap on any chapter
4. **Issue**: Pages of Manga does not load; Only a "retry" button appears 

![Screenshot of problem](https://user-images.githubusercontent.com/80210931/124545521-c8f7b800-de5b-11eb-9794-2bee0ae269d8.png)

### Expected behavior

The pages and images of the manga should be displayed. 

### Actual behavior

The images and pages of the manga does not appear; Only a "retry" button appears 

### Other details

Pages open successfully in Webview. 
Manga cover successfully appears
Manga chapter successfully appears
Manga tags successfully appears

**Comment by Clouddark75** [comment]
They changed some of the of the tags for the images, so, you will need to wait for someone to fixed it.
