### ISSUE TITLE
olympus scanlation

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi-extensions#8000]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

olympus scanlation

### Source link

https://olympusscanlation.com/

### Language

Spanish (ES)

**Comment by Elcrack1412** [comment]
Esta ya esta disponible es martial manga

**Comment by Clouddark75** [comment]
I believe this can be close, the site just changed their URL, I believe this one is more suitable feature #8000, but both are the same, so one of them can be closed.

**Comment by arkon** [comment]
@Clouddark75 You linked this issue?

**Comment by Clouddark75** [comment]
Sorry #8019.
