### ISSUE TITLE
Mihentai: Pages doesn't load

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8003]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Source information

mihentai 1.2.7

### Steps to reproduce

open tachiyomi, install mihentai ext, open mihentai ext, click on any manga, read any chapter

### Expected behavior

pages should load

### Actual behavior

pages doesn't load, it exit and a toast will pop out without any text in it.

**Comment by FrixBOX** [comment]
and it's also have page loop problem, filter doesn't work and finished manga is marked as unknown status.
