### ISSUE TITLE
Hyakuro: Error 404

### ISSUE THREAD

**Issue by Cwavs** [tachiyomiorg/tachiyomi-extensions#8005]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

Hyakuro 1.2.2

### Steps to reproduce

1. Open source as browse or latest

### Expected behavior

When you open the source, you should get a list of available manga

### Actual behavior

You get an Error 404 despite the source seemingly being up in webview.

**Comment by Clouddark75** [comment]
The extension has a "/" (it should be "https://hyakuro.com/reader" only and not "https://hyakuro.com/reader/") at the end of the URL and Tachi most of the time fails to works with it.
The funny thing's that the theme generator is write down right. So my knowledge of why the final extension has it, isn't enough in this case (probably something went wrong during the compilation process). 

What I can recommend for the time being. Is to install the Foolslide Customizable extension and use the URL of the site on it "https://hyakuro.com/reader" (without the quote marks, of course).
You will be able to read until it gets fixed.

**Comment by ObserverOfTime** [comment]
Should be fixed by #8301.
