### ISSUE TITLE
MangaLazy

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8007]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

MangaLazy

### Source link

https://mangalazy.com

### Language

English

### Other details

this'll be the last time I request this (sorry for adding & then removing it tho) they've done something on the site where you'll need to click a button to view/read the manga, which is beyond my knowledge :V 

- icon -> [mangalazy.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6784157/mangalazy.zip)
- uses madara

**Comment by vetleledaal** [comment]
This site implements something similar to #9733, without the redirects. The `decode_images` API also includes `img_index`
