### ISSUE TITLE
Olympus Scanlation / Martial Manga: Cambio de página 

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8019]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Olympus scanlation(Martial manga) a cambiado de página lo cual hace que ya no se pueda leer en martialmanga.com ahora su web se encuentra alojada en https://olympusscanlation.com/ actualizarlo por favor

**Comment by Elcrack1412** [comment]
It

**Comment by arkon** [comment]
@Elcrack1412 Stop bumping and creating duplicate issues. I'll block you from the organization if you keep doing it.

**Comment by NarellaproA1** [comment]
@arkon @loocool2 @alessandrojean @null-dev
Please update it is one of the best sources I beg you
