### ISSUE TITLE
MangaOwl: No pages found

### ISSUE THREAD

**Issue by tenxii** [tachiyomiorg/tachiyomi-extensions#8023]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 8

### Source information

MangaOwl 1.2.13

### Steps to reproduce

1. Opened a story under the said extension.
2. Clicked a chapter and "No pages found" error message shows up.

### Expected behavior

Pages should be able to load just fine.

### Actual behavior

An error message "No pages found" shows up.

### Other details

![Screenshot_20210708-231227_Tachiyomi](https://user-images.githubusercontent.com/87138122/124946979-0b7ae980-e042-11eb-9509-c81470d9b566.jpg)

The site is working fine on webview.

**Comment by Clouddark75** [comment]
Try to clean your cookies. Its probably Cloudflare is limiting your access to the page. The site works just fine on my side with different devices with that same title and others.

**Comment by tenxii** [comment]
> Try to clean your cookies. Its probably Cloudflare is limiting your access to the page. The site works just fine on my side with different devices with that same title and others.

I did and it worked! Thank you!
