### ISSUE TITLE
Mangayeh

### ISSUE THREAD

**Issue by muhammad932** [tachiyomiorg/tachiyomi-extensions#8025]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

mangayeh

### Source link

https://mangayeh.com/

### Language

English

### Other details

most unavailable chapter in certain sites in here.

**Comment by CVIUS** [comment]
redirects to https://mangarok.mobi/ after enabling dark mode🤔

**Comment by muhammad932** [comment]
> redirects to https://mangarok.mobi/ after enabling dark mode🤔

yeah, that's the issue when i'm using them
i see they using two (2) different server to manage darm mode and light mode.
but the main is mangayeh dot com

**Comment by Realppp** [comment]
> > redirects to https://mangarok.mobi/ after enabling dark mode🤔
> 
> yeah, that's the issue when i'm using them
> i see they using two (2) different server to manage darm mode and light mode.
> but the main is mangayeh dot com

Yep I also wished this can be added

**Comment by Realppp** [comment]
> > redirects to https://mangarok.mobi/ after enabling dark mode🤔
> 
> yeah, that's the issue when i'm using them
> i see they using two (2) different server to manage darm mode and light mode.
> but the main is mangayeh dot com

If u close this issue I might be able to make a new one

**Comment by muhammad932** [comment]
> If u close this issue I might be able to make a new one

ok done.
thank you for your help.
