### ISSUE TITLE
Manganato: can't read chapters downloaded back when it was Manganelo

### ISSUE THREAD

**Issue by Mrnofish** [tachiyomiorg/tachiyomi-extensions#8026]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.10.12

### Android version

Android 5.1

### Source information

Manganato 1.2.5

### Steps to reproduce

1. Open a manga that was downloaded by Tachiyomi back when the Extension / Site were still called Manganelo
2. Verify that the chapters that are available locally all show the down arrow/download icon instead.

### Expected behavior

Chapters should show as downloaded since they are available locally

### Actual behavior

All downloaded chapters show a down arrow / download icon.

### Other details

1. The manga appears to have been migrated automatically and otherwise correctly .
2. I tried migrating manually to no avail
3. I am not sure whether this is an Extension or app problem.
4. I am on the latest version available to me, 0.11.1 shows as incompatible with an Android 6 minimum requirement.

**Comment by alessandrojean** [comment]
You need to rename the folder with the old name to the new name the sources uses now. You will also need to rename every chapter folder because the beginning of it contains the old URL, for that you can use a file manager with bulk renaming feature.
