### ISSUE TITLE
LetItGo Scans: HTTP ERROR 404

### ISSUE THREAD

**Issue by ric0369** [tachiyomiorg/tachiyomi-extensions#8027]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

J2K 1.1.0

### Android version

Android 11

### Source information

LetItGo Scans 1.2.1

### Steps to reproduce

1. Try to browse the extension

### Expected behavior

The app should display the available manga in the site.

### Actual behavior

"HTTP error 404: Check website in webview" is displayed.
https://i.imgur.com/tFk4xKL.jpg

### Other details

Lastest is broken as well.

Webview works.
https://i.imgur.com/46bOZHk.jpg

**Comment by ObserverOfTime** [comment]
Should be fixed by #8301.
