### ISSUE TITLE
LilyManga: no manhuas/mangas work, no chapters found

### ISSUE THREAD

**Issue by ZoomTheSloth** [tachiyomiorg/tachiyomi-extensions#8030]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

10

### Source information

Lily Manga 1.2.7

### Steps to reproduce

Go to browse -> sources -> Lily Manga
Open Lily Manga
Search for any manga/manhua
OR
Open any of the manhuas/mangas that appear

### Expected behavior

When searching, it should return with the manhua/manga
When opening them from the source, chapters should appear

### Actual behavior

When searching nothing returns, says "No results found"
When opening any of the manhuas/mangas that appear, "No chapters found"

**Comment by Clouddark75** [comment]
They have some tags changes for the chapters.

**Comment by Riztard** [comment]
i believe its working
try troubleshoot if still not

**Comment by ZoomTheSloth** [comment]
It started working as of a few weeks ago, I forgot to close the ticket sorry. Sent from Mail for Windows From: Riztard LanthornSent: Sunday, 14 November 2021 14:40To: tachiyomiorg/tachiyomi-extensionsCc: ZoomTheSloth; AuthorSubject: Re: [tachiyomiorg/tachiyomi-extensions] LilyManga: no manhuas/mangas work, no chapters found (#8030) i believe its working for metry troubleshoot if still not—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
