### ISSUE TITLE
MangaSee : Create new source folder for every chapter

### ISSUE THREAD

**Issue by PhilippBleimund** [tachiyomiorg/tachiyomi-extensions#8032]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

7.1.1

### Source information

MangaSee 1.2.24

### Steps to reproduce

1. Start download of Manga chapter
2. After it finished it shows a competed download
3. Restart tachiyomi
4. It isn't downloaded anymore
5. Go to file explorer and look up the tachiyomi download folder

### Expected behavior

Tachiyomi should create a manga folder in the already existing source folder.

Directory tree:

TachiyomiMangas
├──MangaSee (EN)
        ├──Dragonball
                ├──chapter 0
                ├──chapter 1

### Actual behavior

Problem:
Tachiyomi creates for every chapter a new MangaSee folder. Therefore it can't read it's contends because android(or tachiyomi) appends a number to the folder name.

Directory tree:

TachiyomiMangas
├──MangaSee (EN)
        ├──Dragonball
                ├──chapter 0
├──MangaSee (EN) (1)
        ├──Dragonball
                ├──chapter 1

### Other details

![Capture+_2021-07-09-10-36-52](https://user-images.githubusercontent.com/77382879/125083072-3ad43980-e0c8-11eb-9af4-772715505d72.png)

**Comment by arkon** [comment]
See #6284
