### ISSUE TITLE
Mangadex: manga not showing name

### ISSUE THREAD

**Issue by ZEXERJK** [tachiyomiorg/tachiyomi-extensions#8036]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

Android 11

### Source information

Mangadex 1.2.122

### Steps to reproduce

1. Open Mangadex source (not latest)
2. Some manga don't display the title but only the cover even though they have a tittle like other manga when you open them in webview

### Expected behavior

1. Open Mangadex source (not latest)
2. Manga display as they should be with titles and all the informations

### Actual behavior

[Mangadex title URL brought as example](https://mangadex.org/title/8fef2dc5-fd32-4d62-9cb3-4a39275e0ef5) 
![Screenshot_20210709-232919_Tachiyomi](https://user-images.githubusercontent.com/48049633/125138126-5eba6e00-e10e-11eb-9efa-9df66ba19f6e.jpg)
![Screenshot_20210709-231742_Tachiyomi](https://user-images.githubusercontent.com/48049633/125138134-6417b880-e10e-11eb-8d7f-46eb71bdc1e8.jpg)

### Other details

I cleared cache/cookies of both tachiyomi and webview if that helps with anything.

**Comment by CarlosEsco** [comment]
This is because it doesn't have a "en" title in the main titles.  Gonna leave this open for a little bit to see if they correct their data or if changes.  I was told romanji wasn't gonna be considered "jp"...

**Comment by paulo27ms** [comment]
@CarlosEsco title{} shouldn't have more than 1 title anyway, even if it's jp or kr or whatever, I think we can just use it regardless of classification because there might always be mistakes when filling the manga info on MangaDex's side and having to report those constantly would be a pain.

**Comment by CarlosEsco** [comment]
> @CarlosEsco title{} shouldn't have more than 1 title anyway, even if it's jp or kr or whatever, I think we can just use it regardless of classification because there might always be mistakes when filling the manga info on MangaDex's side and having to report those constantly would be a pain.
> If it somehow gets 2 titles we could use priority of en>jp>others.

There is no guarantee it's just one.  There is talks of having the primary of each language in title

**Comment by paulo27ms** [comment]
And we'd always just use the one based on the language setting? That's never gonna work because there's very rarely gonna be a manga that has all the titles for each language.
If it's planned to be multiple then we can go on a priority basis.

**Comment by CarlosEsco** [comment]
Realistically. The romanji key would exist. And that would be the fall back. But yea I wish it was just one title so we could always match the dex front end
