### ISSUE TITLE
Remove Nartag

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi-extensions#8038]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

proof of ownership provided on discord

**Comment by Clouddark75** [comment]
Is TraduccionesNartag (extension: Traduciones Amistosas), right?

**Comment by CarlosEsco** [comment]
@CVIUS could you do this next time you update madara

**Comment by CVIUS** [comment]
> @CVIUS could you do this next time you update madara

aight, np👌
