### ISSUE TITLE
Neox Scanlator: The source changed their link and the app doesn't load new chapters 

### ISSUE THREAD

**Issue by thiago8rocha** [tachiyomiorg/tachiyomi-extensions#8039]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

Neox Scanlator 1.2.12

### Steps to reproduce

1. Open the app
2. Click on the Browser tab
3. Click on Latest on the source
4. There's the issue 
5. Click on the Open Webview icon
6. There's the issue

### Expected behavior

The source should shown the new chapters releases and open the correct website on webview 

### Actual behavior

The source doesn't shown the new chapters and shows the following message:
error  HTTP 400: Check website in Webview
When opened in webview the website shows the old link, missing some recent releases as I show in the attached screenshots

### Other details

Old source link: https://neoxscans.net/
New source link: https://neoxscans.com/
![New_website](https://user-images.githubusercontent.com/81594678/125151526-2706f280-e11d-11eb-841d-4b3078a91dc7.jpg)
![Old_website](https://user-images.githubusercontent.com/81594678/125151527-28381f80-e11d-11eb-9431-9c64e6a987b8.jpg)

**Comment by alessandrojean** [comment]
Oh man, they do really like to change the URL. I will update it later.

**Comment by RichardCle** [comment]
I was looking to report this problem, even better that you have already seen.
