### ISSUE TITLE
Certain Comics in Mangadex show as no available chapters when in reality, it is available on the website 

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi-extensions#8040]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

MangaDex 1.2.123

### Steps to reproduce

**This does not happen for all manga. Only certain ones.**
1. Choose a bugged manga. For example: Her summon. Chapters available on website but not on extension
2.  Wait for it to load up fully

### Expected behavior

1. chapters should appear including the latest ones

### Actual behavior

1. gives a toast saying no chapters

**Comment by FourTOne5** [comment]
This is happening because the chapter you are seeing in site are probably dummy chapters.

### In case of Her Summon
English Only (Dummy Chapter):
![image](https://user-images.githubusercontent.com/59261191/125163396-c45e3700-e1ae-11eb-8412-a87210a9be85.png)

Turkish Only (Actual Chapter):
![image](https://user-images.githubusercontent.com/59261191/125163511-42224280-e1af-11eb-8ed3-cb662b42d6b9.png)

**Comment by ZEXERJK** [comment]
Those are just drop-down tabs that have the last translated chapters as the title, manga DEX decided that for every new chapter translated in any language they create a "specific chapter group" for every language, meaning that the chapter that you see is a collection of the same chapter, just sorted by language. And if you select a language where that chapter was not translated into then you will have an "empty" drop-down group.
![ex1](https://user-images.githubusercontent.com/48049633/125167128-46defa80-e19f-11eb-91d3-4d0b1417e850.png)
![ex2](https://user-images.githubusercontent.com/48049633/125167146-5c542480-e19f-11eb-8b70-e76d7b5c73c4.png)
