### ISSUE TITLE
MangaDex and Mangafreak: Cannot install the extension update for both MangaDex v1.2.121 and Mangafreak v1.2.2

### ISSUE THREAD

**Issue by billybale** [tachiyomiorg/tachiyomi-extensions#8045]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

J2K 1.1.0

### Android version

Android 10

### Source information

MangaDex 1.2.121 & Mangafreak 1.2.2

### Steps to reproduce

1. Go to extension tab
2. Tap update
3. Continue download the update
4. After finish download, pop up "can't install the update"

### Expected behavior

The update should continue install

### Actual behavior

Update can't be installed

### Other details

Occur on both MangaDex 1.2.121 and Mangafreak 1.2.2

**Comment by arkon** [comment]
This is a J2K-specific issue, not an extension one. You need to disable MIUI Optimization.
