### ISSUE TITLE
Hitomi.la : #4679 repeating again after almost a month

### ISSUE THREAD

**Issue by billybale** [tachiyomiorg/tachiyomi-extensions#8046]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

J2K 1.1.0

### Android version

Android 10

### Source information

Hitomi.la 1.2.8

### Steps to reproduce

1. Open the "latest" tab on Hitomi.la extension
2. Trying to read any manga
3. Pages cannot load and stuck at retry
4. Try to download the chapter but also failed to do so

### Expected behavior

All page loaded successfully and can be downloaded

### Actual behavior

Page do not load and can't be downloaded

### Other details

Page is loaded successfully at webview.

**Comment by Freedomstrik** [comment]
Have the same problem

**Comment by Freedomstrik** [comment]
I have the same problem

**Comment by YuiWelp** [comment]
Can confirm, but some of the pages load for some reason (eg. every 2-5 pages there is one that actually loads)

**Comment by alextbaez** [comment]
I'm having the same problem
