### ISSUE TITLE
Can't Use An Extension

### ISSUE THREAD

**Issue by MiyukiHinata** [tachiyomiorg/tachiyomi-extensions#8051]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

8.1.0

### Source information

Hitomi.la 1.2.8

### Steps to reproduce

1. Saved a doujin from the extension into the library.
2. Open the saved doujin from library.

### Expected behavior

When i saved a doujin into the library, i can just read it back without any problem

### Actual behavior

The saved doujin won't load and instead just keeps buffering while showing the retry text everytime i tried to read. Some of the doujins will display the cover only while most of the others just won't load.

### Other details

I've tried to resolve the problem by troubleshooting, reinstalling and asking discord but all comes to dead end. The problem started two days ago and before this happen, everything is just fine

**Comment by zayin02** [comment]
Known issue #8046
