### ISSUE TITLE
Manga00

### ISSUE THREAD

**Issue by hightproject** [tachiyomiorg/tachiyomi-extensions#8052]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manga00

### Source link

manga00.com

### Language

Thai

**Comment by Clouddark75** [comment]
WP MangaStream custom theme, or either a WP EastManga version, probably (?

**Comment by hightproject** [comment]
THEME : THAI

**Comment by Clouddark75** [comment]
> THEME : THAI

Woah, easy young padawan. Thai is the language of the page. What I mentioned is the "reader theme" they're using on that website, friend.
