### ISSUE TITLE
E-Hentai: enforced language

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8055]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

A11

### Source information

Ehentai 1.2.14

### Steps to reproduce

1. enable enforced language 
2. go to latest page

### Expected behavior

just show the content related to the selected language 

### Actual behavior

show the most recents post ignoring the language

**Comment by Clouddark75** [comment]
Hmm. It works just fine for me with English. Can you be more specific with language you're having problems?

**Comment by SrW0nka** [comment]
> Hmm. It works just fine for me with English. Can you be more specific with language you're having problems?

Portuguese

**Comment by Clouddark75** [comment]
> > Hmm. It works just fine for me with English. Can you be more specific with language you're having problems?
> 
> Portuguese, but English have the same problem (node: its in "latest")

Yah, on "latest" as you mentioned. I didn't have problems at all. It works as intended if you have the language enforcement enabled for the extension language of preference for English, so it did load only "English" content for me. Now for Portuguese, I see it simply ignored the config and just displayed "Japanese" content only. Same with "Spanish" and others, it just display "Japanese" content.

**Comment by SrW0nka** [comment]
> > > Hmm. It works just fine for me with English. Can you be more specific with language you're having problems?
> > 
> > 
> > Portuguese, but English have the same problem (node: its in "latest")
> 
> Yah, on "latest" as you mentioned. I didn't have problems at all. It works as intended if you have the language enforcement enabled for the extension language of preference (witch is English in my case), so it did load only "English" content for me. Now for Portuguese, I see it simply ignored the config and just displayed "Japanese" content only. Same with "Spanish" and others, it just display "Japanese" content.

oh true, i dont enable enforced in English...anyway thanks for confirm the bug, lets wait to be fixed
