### ISSUE TITLE
MangaDex: Open chapter links in Tachiyomi

### ISSUE THREAD

**Issue by lord-ne** [tachiyomiorg/tachiyomi-extensions#8066]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

MangaDex chapter links (e.g. https://mangadex.org/chapter/2859b3ad-974a-4ffd-9217-efd367f05890/1) should open in Tachiyomi (via URL intent/"deep links"). _(EDIT: To clarify, the chapter links should open the series page in Tachiyomi, since opening chapter pages isn't possible)_. Currently only series links (e.g. https://mangadex.org/title/4479de8f-811f-4f07-8d02-68dd4caa4af0) will open in the app.

### Other details

I beleive that this feature was present before the MangaDex redesign. Related to #8015 (closed).

**Comment by paulo27ms** [comment]
Pretty sure chapters never worked like this, it was only for manga.

**Comment by CarlosEsco** [comment]
Deep linking of chapters for any source has never been a thing in the main application and probably won't be because it requires main app code changes before an extension can support it

**Comment by lord-ne** [comment]
My intent was that chapter links would open the series page (currently they just don't open with Tachiyomi). Can you reopen?

**Comment by CarlosEsco** [comment]
You didn't specify that at all in the post.

**Comment by lord-ne** [comment]
I didn't specify because I never even thought of the idea of opening individual chapters in Tachiyomi, since I already knew it wasn't possible. I apologize.
