### ISSUE TITLE
Mangadex: wrong chapters order

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#8068]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3583

### Android version

Android 11

### Source information

Mangadex 1.2.123

### Steps to reproduce

1. Update manga
2. Sort chapters by source
3. New chappters will be in bottom of all chapters

### Expected behavior

1. New chapters are first in order

### Actual behavior

2. New chapters are last 
![Screenshot_2021-07-12-09-50-32-248_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/39062952/125243492-da770f00-e2f6-11eb-923f-e2cda4e59e71.jpg)
![Screenshot_2021-07-12-09-51-29-356_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/39062952/125243493-da770f00-e2f6-11eb-979c-a4566787ac46.jpg)
![Screenshot_2021-07-12-09-53-05-563_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/39062952/125243591-f8dd0a80-e2f6-11eb-8bca-b2acfe35c7e4.jpg)

### Other details

I tried sort by number of chapters, but it brokes some manga from other extensions.

**Comment by CarlosEsco** [comment]
have you you tried swipe refreshing the chapters?

**Comment by arkon** [comment]
This should already be fixed for Jahy-sama. Some entries still have the wrong order from MD because of missing volume numbers on their end.
