### ISSUE TITLE
Multporn: it just doesn't work

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#8069]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.3

### Android version

android 8

### Source information

Multporn 1.2.2

### Steps to reproduce

try to search in the extension.

### Expected behavior

it should show the comics

### Actual behavior

It shows nothing.
![IMG_20211012_161355](https://user-images.githubusercontent.com/75091899/136975070-cbe133d1-56db-41fc-baf9-f28bc9e19715.jpg)

### Other details

I saved a comic in my library before multporn break and it still works, i can read the chapters and update it normally.

**Comment by Palloxin** [comment]
6 months..

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
