### ISSUE TITLE
Japanread.cc : We can't read chapters on this extension

### ISSUE THREAD

**Issue by Dekkii0** [tachiyomiorg/tachiyomi-extensions#8081]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Japanread 1.2.8

### Steps to reproduce

1.Click on japanread
2.Click on a serie
3.Click on a chapter
4.Can't read the chapter

### Expected behavior

We should read 

### Actual behavior

We can't read

### Other details

Series posters are not displayed

**Comment by Adam935** [comment]
**You got this too ?**

![1626651857608](https://user-images.githubusercontent.com/50600860/126085823-8c445e07-1253-4a18-a8a0-16bb40094141.jpg)

**Comment by Dekkii0** [comment]
no i can't just read
the poster's black too 
it's say that they found no page

**Comment by Adam935** [comment]
> it's say that they found no page

Strange what was the manga where you have they found no page?

**Comment by Dekkii0** [comment]
every manga

**Comment by Zwoider8** [comment]
Here to say that french readers would be really grateful to see this issue fixed as this is one of the best sources for our language.

If this can help i get this issue when trying to read a chapter, the chapters list, manga description and everything loads perfectly, except the manga cover and the actual chapters when u tap on them. I get this on all the mangas of that source.
![20210822_073445](https://user-images.githubusercontent.com/89331500/130343755-7a3958b4-88ec-441f-8d57-d1d545a10194.jpg)

**Comment by arkon** [comment]
Duplicate of #7173
