### ISSUE TITLE
Reaper Scans: changed theme to MADARA

### ISSUE THREAD

**Issue by ZEXERJK** [tachiyomiorg/tachiyomi-extensions#8082]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Reaper Scans

### Source link

https://reaperscans.com/homepage/

### Language

English 

### Other details

Reaper Scans changed the theme of the website to madara.

**Comment by Silvermane06** [comment]
Just adding these pictures for reference from their discord, it may or may not help.
![useful_info_reaperscans_1](https://user-images.githubusercontent.com/79814066/125376210-286c3100-e350-11eb-898b-b40dfc3551b9.PNG)
![useful_info_reaperscans_3](https://user-images.githubusercontent.com/79814066/125376212-2904c780-e350-11eb-8022-513dfa6fc6b4.PNG)
![useful_info_reaperscans_2](https://user-images.githubusercontent.com/79814066/125376214-299d5e00-e350-11eb-8da8-b02a6fdc17a5.PNG)

**Comment by Silvermane06** [comment]
Also i doubt this has any effect on tachiyomi since it just uses calls rather than going to the home page itself, but the home page seems to be broken atm, which they fixed by using the link above.

**Comment by arkon** [comment]
Already addressed by #8083. Open another issue if there's new problems.
