### ISSUE TITLE
Reaper Scans: http error 404, migrating search broken

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi-extensions#8094]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stavle 0.11.1

### Android version

Android 11 One UI 3.1

### Source information

Reaper Scans 1.2.7

### Steps to reproduce

1. Update Manga
2. Fails to update and produces http error 404. However webview works.
3. Migrate manga.
4. Fails to show up under reaper scans with *no results found* showing up instead.

### Expected behavior

Manga should show up and you should be able to migrate the manga back to reaper scans.

### Actual behavior

Instead, you get no results found.

### Other details

Only reason I tried to migrate in the first place was the fact there was an http error 404 even though webview works fine. I can't migrate however, becomes it seems like the search isn't working properly. 
I also tried this with multiple diff manga/webtoon/manhuas

Edit: restarting the app causes source id to display as a #, so weview option is n/a.

**Comment by SaruDesu** [comment]
Due to maintenance on Reaper's side. Issue needs to be closed.

**Comment by loocool2** [comment]
Yep, confirmed that it's a issue on Reaper's end. Their main site page is a empty apache webpage lol
