### ISSUE TITLE
LectorManga: Missing scanlators at chapter list

### ISSUE THREAD

**Issue by SamirM15** [tachiyomiorg/tachiyomi-extensions#8105]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

10

### Source information

LectorManga 1.2.16

### Steps to reproduce

When I open the application and enter the manga the names of the scans that translate it should appear but now only the upload dates of the chapters appear but not the name of the scans.

### Expected behavior

The names of the scans should appear

### Actual behavior

The names of the scans do not appear

### Other details

When I enter the web view the names of the scans do appear, so maybe the source changed.

**Comment by alessandrojean** [comment]
/edit-title "LectorManga: Missing scanlators at chapter list"
