### ISSUE TITLE
E-Hentai: introducing Chapters

### ISSUE THREAD

**Issue by Firehawk0815** [tachiyomiorg/tachiyomi-extensions#8108]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The E-Hentai Extension doesn't feature Chapters at the moment. This causes the issue that neither the single downloaded chapter gets updated (unless you delete it and redownload) nor does the user receive a notification as new pages get added.

Is there a possibility to define every page as its own chapter like for example on the Lemonfont Extension?

**Comment by CrepeTF** [comment]
no.

**Comment by loocool2** [comment]
No

**Comment by jobobby04** [comment]
:eyes:

**Comment by CrepeTF** [comment]
> 👀

no.

**Comment by Firehawk0815** [comment]
K guess not then

**Comment by Firehawk0815** [comment]
Then the E-Hentai Extension stays useless for anything that's ongoing

**Comment by jobobby04** [comment]
:eyes:
~~Look at the forks page on the Tachi website~~
