### ISSUE TITLE
Mangaku.cc

### ISSUE THREAD

**Issue by Ikiw090** [tachiyomiorg/tachiyomi-extensions#8113]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Not Scans

### Source link

https://mangaku.cc

### Language

Indonesia

### Other details

Please enter https://mangaku.cc into tachiyomi because the web for me is very good and cool. if Tachiyomi's side adds it I'm very grateful to you!

**Comment by HaruSasaki** [comment]
This site is redirect from mangaku.in, then see #2530
