### ISSUE TITLE
GMANGA: HTTP Error 503

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi-extensions#8114]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

10

### Source information

Gmanga(latest)

### Steps to reproduce

I Refresh gmanga
Or i open gmanga in web view 

### Expected behavior

The manga list shoud be updated

### Actual behavior

An error message appears only with manga in the gmanga extension 
And when i open it in web view (check the attached photo), but if i opened gmanga from chrime the site runs normally 
![Screenshot_2021-07-14-18-26-45-92](https://user-images.githubusercontent.com/75262438/125658112-ae6e587b-9700-4860-8974-158ce4a2899d.jpg)

### Other details

![Screenshot_2021-07-14-18-15-22-72_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/75262438/125657351-2afc3c7c-30c9-4f4e-bdf7-6c05d2759ad2.jpg)

**Comment by loocool2** [comment]
Not much information you're giving us. What error are you running into? Change the title to be more descriptive as well please

**Comment by hakudansho** [comment]
When i refresh any manga (Error 503) message appears

**Comment by CarlosEsco** [comment]
#8061

**Comment by CarlosEsco** [comment]
actually keeping this one since it has better info

**Comment by ahmedgamal17** [comment]
I found that gmanga changes the site to https://gmanga.org/ and the extension is for https://gmanga.me

**Comment by hakudansho** [comment]
So is there a solution or not?🥺

**Comment by iRahmaniMed** [comment]
For more details #7957

**Comment by hakudansho** [comment]
Gmanga is working naturally as of today, don't know what happened and i don't know if it will keep working, So should i close the issue or what?

**Comment by iRahmaniMed** [comment]
Cloudflare protection is activated on the website only at night, so the extension works normally in the daytime, but at night I always face this issue.
