### ISSUE TITLE
Sekte Doujin: Chapters do not load

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8122]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Sekte Doujin v1.2.9

### Steps to reproduce

https://user-images.githubusercontent.com/40079068/125761068-70050870-9415-42ce-a8fc-83002428e657.mp4

### Expected behavior

Extension Error

### Actual behavior

Extension Error

### Other details

_https://sektedoujin.club/_

**Comment by alessandrojean** [comment]
/edit-title "Sekte Doujin: Chapters do not load"

**Comment by arkon** [comment]
Supersede by #9172
