### ISSUE TITLE
Tsuki Mangás: Content not loading

### ISSUE THREAD

**Issue by Messaih** [tachiyomiorg/tachiyomi-extensions#8131]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

Talves trocando o link da tsuki talvez ajude, ou tirando o suporte de login dela

**Comment by alessandrojean** [comment]
Por favor, não abra Issues duplicados.

A permissão de acesso da extensão foi desabilitada temporariamente pelos responsáveis do site. Nada que possamos fazer para contornar isto no momento. Você deve esperar com que eles reabilitem a permissão ou deve migrar para outra fonte caso não queira esperar.

Importante mencionar que não há uma previsão para quando e se a permissão será reativada.

**Comment by alessandrojean** [comment]
Actually, gonna let this one open to try to prevent new duplicates.

**Comment by alessandrojean** [comment]
A permissão de acesso da extensão foi reabilitada pelos responsáveis do site, mas pode ser que você ainda enfrente algum erro ao tentar utilizar a extensão. Para corrigi-lo, você deve limpar os cookies do aplicativo, indo em **Mais → Configurações → Avançado → Limpar os cookies**. Após isso, você deverá conseguir acessar normalmente.
