### ISSUE TITLE
Tsuki mangás bugado

### ISSUE THREAD

**Issue by Messaih** [tachiyomiorg/tachiyomi-extensions#8133]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 6

### Source information

Tsuki mangás 1.2.21

### Steps to reproduce

O suporte de login nao funciona e esta bugando a extensão 

### Expected behavior

O site esta funcionando porem o login nao

### Actual behavior

Em vez de entrar no site certo ele entra em um site bugado

**Comment by alessandrojean** [comment]
Por favor, faça igual a sessão de Acknowledgements diz e pesquise por Issues antes de abrir duplicados.

A permissão de acesso da extensão foi desabilitada temporariamente pelos responsáveis do site. Nada que possamos fazer para contornar isto no momento. Você deve esperar com que eles reabilitem a permissão ou deve migrar para outra fonte caso não queira esperar.

Importante mencionar que não há uma previsão para quando e se a permissão será reativada.

**Comment by Messaih** [comment]
A unica scan br boa e nao concertarao

**Comment by alessandrojean** [comment]
Em nenhum momento eu mencionei que ela não será arrumada e/ou que estamos fazendo isso propositalmente.

Dependemos dos responsáveis do site liberarem o uso da extensão para ela continuar funcionando, não temos o que fazer, isso é responsabilidade total deles neste momento. Em resumo, peça e reclame com eles sobre isso, e não conosco.

Caso não queira esperar, use outra fonte.
