### ISSUE TITLE
MangaDex: Not all latest chapters are shown in app

### ISSUE THREAD

**Issue by StefanosM** [tachiyomiorg/tachiyomi-extensions#8134]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.0

### Android version

Android 7.0 Nougat

### Device

Redmi Note 4

### Steps to reproduce

https://user-images.githubusercontent.com/19763745/125879521-b8915992-b233-48b4-bbe7-49e4ec2732ef.mp4

### Expected behavior

New chapters uploaded to MangaDex should appear in the "Latest" section of the in-app extension.

### Actual behavior

The "Latest" section lags behind several hours and also does not feature all the recent uploads even within that timeframe.

### Other details

I looked for duplicate issues but didn't find any (which I was very surprised by) so if there is something obvious I am missing, I apologize in advance.

**Comment by CarlosEsco** [comment]
@paulo27ms good catch on me missing the limit[]

**Comment by StefanosM** [comment]
@CarlosEsco Yeah I realized it too late, sorry
