### ISSUE TITLE
Mangacrow

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8138]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Mangacrow

### Source link

https://mangacrow.com/index.php

### Language

English

**Comment by Soitora** [comment]
Low quality aggregator that requests money for doing work they themselves don't do.

**Comment by CarlosEsco** [comment]
Doesn't mean we can't add it

**Comment by vetleledaal** [comment]
Uses same theme as Raw-Manga
