### ISSUE TITLE
ReadHentai

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8140]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ReadHentai

### Source link

https://readhent.ai/

### Language

English

**Comment by vetleledaal** [comment]
Domain redirects to Yandex, and has been since at least December 14, 2021. It's probably dead
