### ISSUE TITLE
Add Extension Indonesia

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8142]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Please add extension 🙏

Website :
manhwaid.co
manhwaland.me
wib.my.id
komikvip.com

**Comment by Soitora** [comment]
This is not the correct way to request extensions.

**Comment by uzumakhiadi** [comment]
> This is not the correct way to request extensions.

how to request it?

**Comment by Soitora** [comment]
You request source through "Source request", not "Feature request". Try reading next time
![image](https://user-images.githubusercontent.com/10836780/126035317-945ddbe0-b212-4f2f-825e-0dd9e83b4564.png)

**Comment by uzumakhiadi** [comment]
> You request source through "Source request", not "Feature request". Try reading next time

Ohh ok thanks
