### ISSUE TITLE
Add Extension ManhwaID

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8144]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ManhwaID

### Source link

https://manhwaid.co/

### Language

Indonesia

### Other details

Comic 18+
![Screenshot_2021-07-17-19-30-10-377_org mozilla fenix](https://user-images.githubusercontent.com/40079068/126035463-21cb3699-6562-45ed-bfe0-9b95aa289d6e.jpg)

**Comment by CrepeTF** [comment]
#6223
