### ISSUE TITLE
Doujinpoi

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8149]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Doujinpoi

### Source link

https://doujinpoi.club/

### Language

Indonesia

**Comment by vetleledaal** [comment]
Uses WPMangaStream or WPMangaReader

**Comment by ZekkenID** [comment]
extension already exists under the name sektedoujin

**Comment by uzumakhiadi** [comment]
> Uses WPMangaStream or WPMangaReader

how?

**Comment by ZekkenID** [comment]
@uzumakhiadi 
![IMG_20220510_134037](https://user-images.githubusercontent.com/23666289/167543989-2165c76e-6f87-4a84-97c3-c0ca7e1e08c1.jpg)
Udah ada mangkanya ditutup
