### ISSUE TITLE
Add Extension Doujindesu

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8150]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Doujindesu

### Source link

https://doujindesu.info/

### Language

Indonesia

**Comment by CarlosEsco** [comment]
Please don't post nsfw screenshots.  Can you go back through your other tickets and remove them

**Comment by CrepeTF** [comment]
#5470
