### ISSUE TITLE
Add Extension ManhwaID

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8154]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ManhwaID

### Source link

https://manhwaid.co/

### Language

Indonesia

### Other details

![Screenshot_2021-07-17-20-31-34-752_org mozilla fenix](https://user-images.githubusercontent.com/40079068/126036973-2d404955-d0e3-4c93-aa75-8c6da21e9239.jpg)

**Comment by CrepeTF** [comment]
#6223, I closed them because they're a duplicate issue, actually read and press what I reply and stop remaking these issues, I will close them

**Comment by uzumakhiadi** [comment]
> #6223, I closed them because they're a duplicate issue, actually read and press what I reply and stop remaking these issues, I will close them

Ohh ok
