### ISSUE TITLE
Extensions not working, android 4.4

### ISSUE THREAD

**Issue by Ice-wallow** [tachiyomiorg/tachiyomi-extensions#8164]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.8.5

### Android version

Android 4.4

### Source information

Every source

### Steps to reproduce

Android 4.4
Try installing extensions

### Expected behavior

Should work

### Actual behavior

Doesn't

### Other details

The extensions don't work on android 4.4, and upon decompiling mangakalot, I found that the min. supported version was android 5. This has upset me to a great deal, as I have been using Tachiyomi since its infancy, and have never found an app that can compare. If anyone can help I'd be grateful.
Thanks

**Comment by Seishirou101** [comment]
[That change](https://github.com/tachiyomiorg/tachiyomi/issues/4885) was done months ago. Your only options are upgrading your rom, or getting a new phone as you're out of luck.
