### ISSUE TITLE
MangaOwl: Chapters do not load

### ISSUE THREAD

**Issue by mverika** [tachiyomiorg/tachiyomi-extensions#8165]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Source information

MangaOwl 1.2.16

### Steps to reproduce

1. Open Tachiyomi
2. Click on MangaOwl extension
3. Click on any manga
4. Click on a chapter

### Expected behavior

Chapter loads

### Actual behavior

![image_2021-07-18_165436](https://user-images.githubusercontent.com/70913994/126061539-80aca4f4-93a9-45b8-847d-b30719014974.png)

**Comment by Clouddark75** [comment]
Works just fine here. Can you be more specific with which manga you are having problems with?
Anyways, make sure you can bypass Cloudflare. And as reinforcement be sure of clear your cookies and cache on Tachi.

**Comment by mverika** [comment]
It happened to all mangas from MangaOwl, but now it works fine. Thanks

**Comment by CVIUS** [comment]
This can be closed.
