### ISSUE TITLE
Auto scrolling for mobile.

### ISSUE THREAD

**Issue by Chaotickeyblade** [tachiyomiorg/tachiyomi-extensions#8166]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

For viewing images in the app it would be great if there was an auto scrolling feature with different scrolling speeds instead of having to use the volume up and down buttons just make it automatic.

**Comment by curche** [comment]
Wrong repo. Kindly make sure you to read the Acknowledgements next time:
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues).

That said, Duplicate of tachiyomiorg/tachiyomi#2093
