### ISSUE TITLE
Nhentai broken 

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#8167]
the issue is pretty simple they changed their domain, old domain is https://Nhentai.net and new one is https://nhentai.to, just need to update the extension with the new domain

**Comment by Soitora** [comment]
No lol, what are you on about?

**Comment by BraveDude8** [comment]
.to is an impersonator site that's been around for a couple of years. Odds are your ISP is blocking .net, because it's still online. You'll need a VPN.

**Comment by Mtkmanjaro** [comment]
@BraveDude8  i can access to .net without problems for example taringa.net, is just nhentai.net is just dead for me I don't know why maybe they blocked this domain to my region but my ips provider has nothing to do since i can access to others .net sites

**Comment by arkon** [comment]
>i can access to .net without problems for example taringa.net

...that's not how the Internet works.

If you want to request a _new_ extension for a _different_ website, submit a request with the proper form.

**Comment by Mtkmanjaro** [comment]
@arkon  i never said I want a new extension for a new website i just give a example, so stop speculating mate.

**Comment by arkon** [comment]
I'm going to give you the benefit of the doubt that you're just wildly misunderstanding every response here.

If you're requesting a new extension for nhentai.to (which again, is not the same thing as nhentai.net, create a source request with the correct form).
