### ISSUE TITLE
Cubari: Manga title is encoded

### ISSUE THREAD

**Issue by RunningDroid** [tachiyomiorg/tachiyomi-extensions#8170]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)

### Android version

8.0.0

### Source information

Cubari 1.2.9

### Steps to reproduce

1. Install the Cubari extension
2. Search Cubari for cubari:gist/JYPEl
3. Tap add to library
4. Navigate to the library
5. View the manga
6. Migrate the manga (use cubari:gist/JYPEl as the search term)

### Expected behavior

The search, library, & migration search screens should present the title of this manga as `The Witch's Dealings with a Boy`.

### Actual behavior

The search and library screens present the title as `The Witch&#x27;s Dealings with a Boy`, and the migration search screen presents the title as `The Witch's Dealings with a Boy`

### Other details

I'm assuming this is a bug in the Cubari source extension because I haven't seen this behavior with other sources but I could be wrong.

**Comment by E3FxGaming** [comment]
I can't reproduce this problem. First tried it with a newer app version on Android 11, then with 0.11.1 on Android 11 and since that didn't let me recreate the problem either I set up a fresh Android 8 Virtual Device with Tachiyomi 0.11.1 - still couldn't reproduce the problem.

Could you tell us a little more about your system settings? (Is the system language English or a different language?,  ...)

**Comment by RunningDroid** [comment]
It sounds like I might just have a local problem then, I'm gonna see what happens if I "migrate" to the correct rendering.

My system language is set to American English.

**Comment by RunningDroid** [comment]
Migrating to the correctly rendered title (from the same source) appears to have fixed the issue, should I close this?

**Comment by alessandrojean** [comment]
> Migrating to the correctly rendered title (from the same source) appears to have fixed the issue, should I close this?

If you're not facing the problem, and it was fixed, it can be closed.
