### ISSUE TITLE
Tsuki Mangás: Distinguish between manga and novels

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi-extensions#8171]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Disguising manga and novel because in tsuki they have the same name

**Comment by loocool2** [comment]
/edit-title "Tsuki Mangás: Distinguish between manga and novels"

**Comment by loocool2** [comment]
Issue description should probably be something like "Tsuki-Mangas puts both novels and manga in the catalog, making it necessary to filter out any novels from the library to prevent duplicates and conflicting entries"
