### ISSUE TITLE
Japanread (FR) : We can't read chapters "Json error code 1020"

### ISSUE THREAD

**Issue by Adam935** [tachiyomiorg/tachiyomi-extensions#8173]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

preview r393

### Android version

android 10

### Source information

Japanread version 1.2.8

### Steps to reproduce

1.Click on japanread
2.Click on a manga or orther 
3.Click on a chapter

### Expected behavior

This should work ( show manga pages)

### Actual behavior

Actualy we have *This*
![IMG_20210815_181136](https://user-images.githubusercontent.com/50600860/129648940-47d80c3e-39bb-4653-ab68-c2ee83506cb4.jpg)

### Other details

**I did a search I found this [https://community.cloudflare.com/t/community-tip-fixing-error-1020-access-denied/66439](url) but I don't know how to fix the problem hope you can help.
Also strangely when you use the WebView it works but as soon as you use the application it stops working.**

**Comment by Zwoider8** [comment]
Here to say that french readers would be really grateful to see this issue fixed as this is one of the best sources for our language.

**Comment by moi15moi** [comment]
Is there any news about this problem?

**Comment by arkon** [comment]
Duplicate of #7173
