### ISSUE TITLE
Mangahasu - Unexpected JSON token at offset 0

### ISSUE THREAD

**Issue by RSTZZZ** [tachiyomiorg/tachiyomi-extensions#8177]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10.1

### Source information

Mangahasu 1.2.12

### Steps to reproduce

1. Download / View any chapter from Mangahasu.

### Expected behavior

Manga would be downloaded.

### Actual behavior

Error: Unexpected JSON token at offset 0: Can't begin reading element, ...

**Comment by JermanyWilhelm** [comment]
Same issue, but I think they will fix it later and get the updated version later on

**Comment by cievee** [comment]
Same issue as mine I was about to make a entry good thing this guy did it first i hope the devs see this

**Comment by SilentSparrow02** [comment]
I'm not getting Unexpected JSON but only a "No pages found" error.
Also would like to add, Mangahasu recently upgraded to HTTPS but Tachi is still loading the HTTP site for me.

**Comment by Drimakus** [comment]
Same problem and still not fixed :(

**Comment by JermanyWilhelm** [comment]
Thanks for the update of mangahasu but the unexpected JSON token at offset 0 is still there when downloading.new chapters, but as of now it can view new chapters in mangahasu

**Comment by Drimakus** [comment]
Try to delete chapter in download queue and add download again. It helped me

**Comment by JermanyWilhelm** [comment]
> Try to delete chapter in download queue and add download again. It helped me

Oh thank you it works 😊
