### ISSUE TITLE
Mangadex: content rating filter works incorrectly with explicit content

### ISSUE THREAD

**Issue by Syntribos** [tachiyomiorg/tachiyomi-extensions#8179]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

O.11.1

### Android version

Android 11

### Source information

MangaDex 1.2.125

### Steps to reproduce

1. Browse MangaDex
2. Open MangaDex filter
3. Ensure all 4 "content rating" options are checked
4. Search for a pornographic manga
5. See no results

Alternative:
1. Go to MangaDex settings
2. Enable pornographic content being shown by default
3. Perform a global search for a pornographic manga
4. See no results

### Expected behavior

Pornographic results are returned if the pornographic content rating checkbox is checked

### Actual behavior

If all 4 content rating checkboxes are checked, no pornographic results are returned

### Other details

Unchecking "suggestive" but leaving safe/erotica/pornographic checked will return pornographic results.

Changing "included tags mode" to "Or" rather than the default "And" will also return the correct results.

This is mostly just annoying because it means global search doesn't work correctly. It's easy to get around when actually inside the MangaDex extension.

**Comment by Syntribos** [comment]
Also just realized that adding any other non-content tag bypasses this. For example:
1. Check safe, suggestive and pornographic
2. Search for hololive: 6 results
3. Also check "completed": 11 results

**Comment by CarlosEsco** [comment]
#5417

The app itself poorly supports default filters.  What happens is the initial filters are loaded, but for subsequent searches the app sees the defaults filters as unchanged

**Comment by Syntribos** [comment]
I think you misunderstood my issue and then linked an irrelevant ticket.

I don't believe this has anything to do with default filters and subsequent searches, based on its reproducibility (unless I'm misunderstanding your explanation). This behaviour is reproducible backwards and forwards, and _only_ affects how the "suggestive" content filter interacts with the explicit filters.

Can you provide a better explanation on why you think this is the case?

**Comment by CarlosEsco** [comment]
In your first scenario, what was your defaults set at?  Was it all 4?

**Comment by CarlosEsco** [comment]
This is what the default bug is
All 4 defaulted
![Screenshot_20210719-112024_Tachiyomi.jpg](https://user-images.githubusercontent.com/2092019/126184670-2a23d836-6347-4d9c-a607-1d1928ef1f6f.jpg)

Only 3 defaulted and the 4th clicked in the filter fab
![Screenshot_20210719-111931_Tachiyomi.jpg](https://user-images.githubusercontent.com/2092019/126184733-853d878d-d994-4e13-a984-78b763ef39d4.jpg)

**Comment by Syntribos** [comment]
My mistake. I've gone through a couple other scenarios as well as looking through the extension code and you're correct.

Not sure why you linked #5417 though

**Comment by CarlosEsco** [comment]
As for global search. That seems to be a bug in the app also. I assume it's not passing the filter list when searching globally, and mangadex defaults all searches without content types in the url to everything but pornographic

**Comment by CarlosEsco** [comment]
> 
> 
> My mistake. I've gone through a couple other scenarios as well as looking through the extension code and you're correct.
> 
> Not sure why you linked #5417 though
> 
> Edit: Ah 5417 in the tachiyomi repo. Should've specified.

Oh that's github being github.  I copied the url and i guess it shortened it :smile:

**Comment by Syntribos** [comment]
Sweet, thanks for the insight!
