### ISSUE TITLE
Mangafreak: Cannot update titles, get "no chapters" notification

### ISSUE THREAD

**Issue by brazor421** [tachiyomiorg/tachiyomi-extensions#8182]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3598

### Android version

Android 10

### Source information

Mangafreak 1.2.3

### Steps to reproduce

1. Open manga title in app
2. Bypass Cloudflare if neccessary
3. Try to update chapters
4. Get "no chapters" notification

### Expected behavior

After successful update you can see new chapters (if there are any)

### Actual behavior

Instead of new chapters, you get "no chapters" notification.

### Other details

Using webview you can assure that manga titles you're reading have actually been updated. But updating these titles in app, you get "no chapters" notification.

**Comment by Clouddark75** [comment]
MangaFreak is using a heavy version of Cloudflare, you will need to open the source on Tachi before updating your Mangas each time. Is either to wait for them to lower it, or migrate to another source. You should be able to read and update your Mangas after bypassing Cloudflare on Tachi Webview.

**Comment by brazor421** [comment]
> MangaFreak is using a heavy version of Cloudflare
Yeah, I know. The thing is, extension worked perfectly fine until yesterday. As I wrote in steps to reproduce: bypass Cloudflare if neccessary. I know how to use mangafreak ext. On webview I can see all new added chapters of titles I read, but when I try to update titles in app, I get "no chapters" notification. And new chapters don't display in app.

**Comment by Clouddark75** [comment]
Witch title you're having that issue? Because I tried a couple and they got updated just fine. Try to clean your cookies and cache from Tachi.

**Comment by brazor421** [comment]
>Try to clean your cookies and cache from Tachi.

I did it before posting the issue. Well, I have that problem with all titles, not only those in my library. For example, title "The undefeatable swordsman". It's in my library, and in app it displays 73 chapters. But on mangafreak there are 74 chapters. When I try to update in app, I get "no chapters" notification. For those not in my library, when I open them in app, I don't see any chapters, just blank space, and get the same notification.

**Comment by zayin02** [comment]
I can confirm, I have the same issue with "no chapters" after bypassing the Cloudflare in webview.

**Comment by Clouddark75** [comment]
I simply can't reproduce the problem. It works/update just fine for me (all the chapters are there, and global updates works as intended after bypassing Cloudflare), I try it with different devices, I even install on a virtual machine.

**Comment by brazor421** [comment]
Well, I don't know what to say. I tried reinstalling extension, tried on another ISP, mobile network, also did steps in troubleshooting (clear cookies, data, cache, etc.) and still get "no chapters".

**Comment by zayin02** [comment]
![Screenshot_20210720-174141_Tachiyomi](https://user-images.githubusercontent.com/76571965/126354228-0ae514e4-01f1-4976-be64-4821a96810ca.jpg)

**Comment by Clouddark75** [comment]
You did two update recently Tachi preview? I downloaded and yup, effectively it doesn't show the any chapter. So it's a problem of the recent preview builds. For now install the stable build.

**Comment by zayin02** [comment]
Yep, I'm using preview r3606

**Comment by brazor421** [comment]
>You two did update recently Tachi preview?

Yeah, I'm currently using preview version. Ok, thx for clarification!

**Comment by Clouddark75** [comment]
No problem. Last working build was Tachi preview r3583. If you two needed a feature from recent preview build, you safely can install that one. 
They seen to have update something referred to chapters updates and stuff with build r3598. 
@arkon, can you take a look at that? Tachi stop fetching chapter since that build.

**Comment by phanirithvij** [comment]
@arkon just reminding. Can you please take a look at this issue.

**Comment by arkon** [comment]
jsoup was updated in that release. Someone should check if the selectors in the extension are still returning valid data.

**Comment by phanirithvij** [comment]
This permanently broke mangafreak.

**Comment by Lickitahm** [comment]
The same thing is happening to me (sorry for opening a new ticket), but this time I'm using stable version 0.12.1 and I have the same issue. Should I downloaded the latest preview or do I wait for a fix?

**Comment by arkon** [comment]
The extension needs to be fixed.
