### ISSUE TITLE
xCaliBR Scans: Java.lang Exception: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Sachinptl20** [tachiyomiorg/tachiyomi-extensions#8183]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

xCaliBR Scans 1.2.9

### Steps to reproduce

xCaliBR Scans is protected by Cloudflare so i followed troubleshooting guides
1. As instructed I opened the source in web view to bypass Cloudflare verification.
2. Then as mentioned in there to Press "X" after bypassing Cloudflare bot verification.
3. Then after clicking on chapters they won't load.
![Screenshot_2021-07-19-19-29-49-781_eu kanade tachiyomi](https://user-images.githubusercontent.com/87658209/126179378-4f5bbe35-9cf3-4a83-914b-7202260b77ef.jpg)

### Expected behavior

After the verification chapters were supposed to load as per steps in troubleshooting guides.

### Actual behavior

Any comic from the source don't load any chapters at all.

**Comment by Clouddark75** [comment]
XCaliBR is well known for their heavy Cloudflare protection level, I recommend you to migrate another source. Because they're doing it intentionally.

**Comment by Clouddark75** [comment]
I believe this can be close. Just the usual heavy Cloudflare protection.
