### ISSUE TITLE
Sinensis

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#8185]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Sinensis

### Source link

https://sinensisscan.com/

### Language

Portuguese

**Comment by Clouddark75** [comment]
Madara theme.

**Comment by alessandrojean** [comment]
I will add it later.

**Comment by Kaylenna** [comment]
Thanks ^^

**Comment by alessandrojean** [comment]
Will be added by #8186.

I can't really get their date formatting pattern since all chapters seems to be uploaded in the past few days, so in the future if the extension stop showing the chapter dates, open a new issue about it.

**Comment by Kaylenna** [comment]
Okay I will and thanks for trying ^^
