### ISSUE TITLE
Dream Union Scan

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#8187]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Dream Union Scan

### Source link

https://www.dreamunionscan.com/

### Language

Portuguese

### Other details

You need an account to log in and it doesn't seem to be mandatory to enter a mobile number

**Comment by alessandrojean** [comment]
Uses Madara. I managed to create an account with a temporary email, will check if it works with an extension.

**Comment by Kaylenna** [comment]
Okay ^^, thanks

**Comment by alessandrojean** [comment]
Will be added by #8188.

When it's available, you will need to log in through WebView in order to use the source.

**Comment by Kaylenna** [comment]
Yes, thank you ^♡^
