### ISSUE TITLE
Comick.fun some chapters do not load and also cant download

### ISSUE THREAD

**Issue by DeltaKiloOne** [tachiyomiorg/tachiyomi-extensions#8192]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

Comick.fun 1.2.5

### Steps to reproduce

1. Open comick.fun
2. Search oyasumi punpun
3. Open oyasumi punpun 
4. Open chapter 1 

### Expected behavior

Should show me the manga 

### Actual behavior

After opening the chapters its says retry but still doesn't show me the manga

### Other details

This is what it actually shows 
![Screenshot_20210720-093751_TachiyomiJ2K](https://user-images.githubusercontent.com/87071129/126260498-bbb6d860-cb53-4d08-b03b-903602aa2816.jpg)

**Comment by Riztard** [comment]
it work now, maybe issue on comick side

**Comment by zayin02** [comment]
On the discord server they stated that they doing image migration, could be that

**Comment by Riztard** [comment]
wait no, image for this manga ch 1 apparently hosted on mangadex maybe some issue from dex before

**Comment by DeltaKiloOne** [comment]
Actually the issue was resolved when ver. 1.2.6 was released sorry for not closing the issue. Will make sure this doesn't happen again.
