### ISSUE TITLE
Mangasee extention fix

### ISSUE THREAD

**Issue by Haruu14** [tachiyomiorg/tachiyomi-extensions#8193]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Latest

### Android version

Android 11

### Source information

Mangasee 1.2.24

### Steps to reproduce

We need mangasee to be fix becuase once you download  a chapter it will make new folder that the chapter will be keep their and once you download again it will make new folder again(mangasee (eng)(1)-(10000) and you need to cut or paste the chapters to main mangasee mangasee(eng) director so i wish this can be resolve

### Expected behavior

The chapter should be keep in the same folder so that their will be jo error

### Actual behavior

Please make it

### Other details

We need mangasee to be fix becuase once you download  a chapter it will make new folder that the chapter will be keep their and once you download again it will make new folder again(mangasee (eng)(1)-(10000) and you need to cut or paste the chapters to main mangasee mangasee(eng) director so i wish this can be resolve

**Comment by arkon** [comment]
#6284
