### ISSUE TITLE
Webtoons.com: Extension doesn't support m.webtoons.com URLs

### ISSUE THREAD

**Issue by SuperSonicHub1** [tachiyomiorg/tachiyomi-extensions#8210]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Webtoons.com 1.2.31

### Steps to reproduce

1. Open `https://m.webtoons.com/en/fantasy/anti-monster-force/list?title_no=2970` or `https://m.webtoons.com/en/fantasy/anti-monster-force/episode-3/viewer?title_no=2970&episode_no=3` with Tachiyomi.

### Expected behavior

Search menu should open, show series "Anti-Monser Force" under Webtoons.com. Works with `https://www.webtoons.com/en/fantasy/anti-monster-force/list?title_no=2970` and `https://www.webtoons.com/en/fantasy/anti-monster-force/episode-3/viewer?title_no=2970&episode_no=3`.

### Actual behavior

Get "No results found" under Webtoons.com.

### Other details

Looking at the [URLActivity](url-activity) for this extension, I can't see why mobile Webtoons URLs don't pass the test. Replacing the subdomain `m` with `www` is the only thing that's required for search to work again. Oddly enough, it seems that having no subdomain also causes the same issue, but I could only see this being important if someone's typing out a link by hand.

[url-activity]: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/6d144464c7d19ba78c71be6d56afefb077d19043/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsUrlActivity.kt

**Comment by RunningDroid** [comment]
I can confirm this bug also occurs with Tachiyomi version: 0.12.1 (standard, 85791a9, 67, 2021-08-06T21:36Z), Android version: 8.0.0 (SDK 26), and Webtoons 1.2.31

**Comment by SuperSonicHub1** [comment]
Any updates on this? It's been a few months now.

**Comment by alessandrojean** [comment]
> Any updates on this? It's been a few months now.

This is an open source project, people submit fixes when they want and when they have time for it. There's no ETA for an open issue to be fixed.

**Comment by SuperSonicHub1** [comment]
@alessandrojean Am aware of this; maintain my own projects after all.

**Comment by SuperSonicHub1** [comment]
I fixed this through allowing Tachiyomi to open Webtooms URLs in settings. It for some reason wasn't automatically enabled.
