### ISSUE TITLE
Fleur Blanche

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#8211]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Fleur Blanche

### Source link

https://fleurscan.com/

### Language

Portuguese

### Other details

You need an account to login, I think it is not mandatory to enter a mobile number

**Comment by alessandrojean** [comment]
I will take a look later.

**Comment by Kaylenna** [comment]
Okay ^^, thank you

**Comment by alessandrojean** [comment]
Mobile number is required. Can you provide me some screenshots of how the website is when logged in?

If it uses Madara I should be able to add it without needing to create an account.

**Comment by Kaylenna** [comment]
![Screenshot_20210721-164005_Chrome](https://user-images.githubusercontent.com/82852543/126549746-9b6543e4-d187-4f86-967f-e38a460af949.jpg)

**Comment by alessandrojean** [comment]
Yup, it uses Madara. I will work on it.

Also, what's the date format they use? You can check it in a manga page in the chapter list.

**Comment by Kaylenna** [comment]
This is how the dates are 07/10/2021

**Comment by Kaylenna** [comment]
The site has a lot of content +18

**Comment by alessandrojean** [comment]
I will mark it as NSFW :+1:

**Comment by Kaylenna** [comment]
Okay ^^
