### ISSUE TITLE
Kanzenin

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8215]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Kanzenin

### Source link

https://kanzenin.xyz/

### Language

Indonesia

### Other details

Comic 18+

**Comment by Clouddark75** [comment]
WP MangaStream theme.

**Comment by uzumakhiadi** [comment]
> WP MangaStream theme. 

sorry, I don't understand
How to?

**Comment by loocool2** [comment]
it's a note that makes it easier for us to remember things, you don't need to worry about it
