### ISSUE TITLE
MangaOwl: Missing some manga in results

### ISSUE THREAD

**Issue by ntslmfao** [tachiyomiorg/tachiyomi-extensions#8218]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I think it would be nice if the mangas listed more in the app just like in the web source

### Other details

For example what I suggest from above is when I opened source MangaOwl with wuxia tags it's only show around 36 mangas but in the web it's more than that so I would appreciate if you listed the manga more in the app, thank you

**Comment by alessandrojean** [comment]
/edit-title "MangaOwl: Missing some manga in results"

**Comment by CVIUS** [comment]
#8151 is related to this issue
