### ISSUE TITLE
Asura Scans: Can't load the chapters in appview 

### ISSUE THREAD

**Issue by NeverGoneXD** [tachiyomiorg/tachiyomi-extensions#8219]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

10

### Source information

Asura Scans 1.2.11

### Steps to reproduce

Can browse the available series on the extension but can't read them

### Expected behavior

Should be able to load the chapters

### Actual behavior

Isn't loading the chapters

### Other details

The webview is working just fine but for some reason can't load the chapters in appview, it says ERROR. It also shows the page numbers. Calling it CHAPTER DOESN'T LOADS might cause a confusion so, rather let's call it THE PAGE DOESN'T LOADS

**Comment by LephantisG** [comment]
I'm having the same exact problem on Android 11

**Comment by elhertz** [comment]
Can replicate on Android 10

**Comment by Matakor** [comment]
I'm having this issue on Android 10 as well. Also note that nothing will download from asura either, it just times out or errors. WebView sees it working normally and loads fine otherwise, but app does not.

**Comment by SilF88** [comment]
Got the same exact problem on android 10

**Comment by CarlosEsco** [comment]
This should be resolved
