### ISSUE TITLE
Leviatan Scans: "invalid int: ..." error (no Bilibili)

### ISSUE THREAD

**Issue by Sharkalone** [tachiyomiorg/tachiyomi-extensions#8221]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 6.0

### Source information

Leviatan Scans v1.2.12

### Steps to reproduce

1. Open "Talent Copycat" series page (Leviatan Scans, not a Bilibili) or try to refresh it
2. See the error : Invalid int : "01 - My ability to copy has awakened?" (name of chapter 01)

### Expected behavior

Display the 3 chapters allready released

### Actual behavior

No chapters in the list with "0 chapter" displayed on the head

![Screenshot_2021-07-22-11-12-21](https://user-images.githubusercontent.com/3669600/126616232-4547c1db-7ed3-4bc7-bd86-d5f15b1ad14c.png)

### Other details

With french language configuration, there is "1 chapitre" displayed on the head while "0 Chapter" in english. It should be "0 chapitre" instead.

**Comment by mohdats** [comment]
I have the same problem

**Comment by Izunyaaan** [comment]
Also seen in https://leviatanscans.com/m/manga/im-a-martial-art-villainess-but-im-the-strongest/ happenes because chapter 50 has "season finale" in the chapter name rather than just 50
