### ISSUE TITLE
mangaalarab.com

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#8226]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

 Manga Alarab

### Source link

https://mangaalarab.com

### Language

Aerobic

### Other details

Please, please, please, add this source for app tachiyomi-extensions

**Comment by CarlosEsco** [comment]
Why did you close the issues and open again?  are you trying to get banned?

**Comment by hani1998** [comment]
@CarlosEsco Previous cases closed because you told me the same name

**Comment by CarlosEsco** [comment]
@hani1998 you can edit the titles, and i had already done it for all your tickets

**Comment by hani1998** [comment]
@CarlosEsco I hope you'll excuse me because it's the first time I've used a resource request that I didn't know the terms

**Comment by hani1998** [comment]
@CarlosEsco I sincerely apologize for making you tired of me
