### ISSUE TITLE
hizomanga.com

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#8227]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

hizomanga

### Source link

http://hizomamga.com

### Language

Aerobic

### Other details

Please, please, please, add this source for app tachiyomi-extensions

**Comment by yemenihandsome** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a title with source name.
> * [x]  I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
> * [x]  I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
> * [x]  I will fill out all of the requested information in this form.
> 
> ### Source name
> Hizo Manga
> 
> ### Source link
> http://hizomanga.com
> 
> ### Language
> Aerobic
> 
> ### Other details
> Please, please, please, add this source for app tachiyomi-extensions

**Comment by Clouddark75** [comment]
It's this website even alive? It seen down.

**Comment by Clouddark75** [comment]
Well, the URL is written incorrectly. 
It's https://hizomanga.com/
