### ISSUE TITLE
https://mangaarbteam.com

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#8230]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

 Manga arbteam

### Source link

https://mangaarbteam.com

### Language

Aerobic

### Other details

The old addon for Manga Arab Team This link to the new site has expired

**Comment by hani1998** [comment]
@CarlosEsco The old site of Manga Arab Team has stopped this is the address of the new site

**Comment by CarlosEsco** [comment]
Why do you ping me on every issue?

**Comment by hani1998** [comment]
I apologize to you, I send you every case so that if you find mistakes, let me know about them

**Comment by hani1998** [comment]
@CarlosEsco I'm sorry
