### ISSUE TITLE
Mangahasu: No pages found error while opening any chapter

### ISSUE THREAD

**Issue by Kanwar12** [tachiyomiorg/tachiyomi-extensions#8232]
![Screenshot_20210725_165651](https://user-images.githubusercontent.com/87832080/126897421-b658d6c0-eca0-44a3-bbdf-59ded2f2c003.jpg)
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Mangahasu 1.2.12

### Steps to reproduce

1. Open a manga
2. Open any chapter

### Expected behavior

Chapter should load.

### Actual behavior

'No pages found' error everytime on opening any chapter.

**Comment by emlautarom1** [comment]
I also happen to get the same error. I'm also running Android 11. Does anyone have the same issue with a different OS version?
