### ISSUE TITLE
MangaTR: Chapter images do not load

### ISSUE THREAD

**Issue by Agayev033** [tachiyomiorg/tachiyomi-extensions#8233]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

MangaTR 1.2.5

### Steps to reproduce

1. Choose a manga
2. Open a chapter

### Expected behavior

Loaded Chapter Pages

### Actual behavior

Chapter pages not working. Just says "Retry"

**Comment by alessandrojean** [comment]
/edit-title "MangaTR: Chapter images do not load"

**Comment by matmakif** [comment]
I have same problem.

My solution:
1. Choose a manga
2. Open in WebView
3. Open 1st chapter last chapter one by one
4. Close WebView
5. Download all chapters.
