### ISSUE TITLE
manga.ae

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#8236]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

manga.ae 1.2.7

### Steps to reproduce

When I open a chapter I get an error, No Pages

### Expected behavior

The pages should open without any problem

### Actual behavior

No pages when reading

**Comment by CarlosEsco** [comment]
Thank you for checking the boxes but not actually doing what they ask.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7796
