### ISSUE TITLE
hentaiseason

### ISSUE THREAD

**Issue by Militinix** [tachiyomiorg/tachiyomi-extensions#8242]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Hentai Season

### Source link

hentaiseason.com

### Language

Português (Brasil)

### Other details

Site 18+.

**Comment by alessandrojean** [comment]
What's the difference between this and #8241? Looks like it's the same website or a mirror of each other.

**Comment by Militinix** [comment]
> What's the difference between this and #8241? Looks like it's the same website or a mirror of each other.

They are partners, that's why they are similar, but the difference is that there is a lot of content in one that there is not in the other, but because they are partners there is some content that is the same as each other.

Now, if you want to merge the two sites, it would be good in.

While our last conversation about superhentai, the site died so forget it for now. #6867
