### ISSUE TITLE
MangaDex: Extension not showing up despite installing.

### ISSUE THREAD

**Issue by dhimanAdhikari** [tachiyomiorg/tachiyomi-extensions#8251]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3606

### Android version

Android 11 (LineageOS 18.1)

### Source information

MangaDex v1.2.126

### Steps to reproduce

1. Install/update MangaDex

### Expected behavior

It should show up under Sources and I should be able to browse manga.

### Actual behavior

It doesn't show up under Sources and when I check Extensions again, it has Install button. Installing it does nothing but repeat. The Apps and Notifications in System Settings does show the APK to be installed.

### Other details
Other extensions don't seem to have this problem.
I'm not exactly sure whether to open this issue under extensions or tachiyomi so sorry about that.

**Comment by CarlosEsco** [comment]
Make sure you show R18 sources, and you have the Languages it supports enabled.

**Comment by dhimanAdhikari** [comment]
But I can't even access the extension options.
Extension installs > "Installed" > tap on it > starts installing again instead of going to extension options.

**Comment by CarlosEsco** [comment]
Can you ask in the discord support channel. They can help you out better then here

**Comment by dhimanAdhikari** [comment]
> Make sure you show R18 sources, and you have the Languages it supports enabled.

Disabled R18 Sources was the issue but I had lost myself trying to install the extension and didn't realise it meant app settings rather than extension settings. My bad and thank you!
