### ISSUE TITLE
MangaOwl: Missing chapters

### ISSUE THREAD

**Issue by mamamohuju** [tachiyomiorg/tachiyomi-extensions#8255]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

android 11

### Source information

MangaOwl 1.2.16

### Steps to reproduce

1. There are lacking chapters in the app, and if you look at the website of mangaowl there are more chapters.
2. Some mangas cant be found in the app

### Expected behavior

It is expected that the mangaowl in the app is updated with the chapters

### Actual behavior

lack of chapters and manga

**Comment by Clouddark75** [comment]
Mate, be more specific when you create a ticket. Witch titles you're having problems with and name the ones you can't see on the App. We aren't fortunate tellers.
