### ISSUE TITLE
[Source Request][English] YaoiArmy

### ISSUE THREAD

**Issue by Mystique0414** [tachiyomiorg/tachiyomi-extensions#826]
https://theyaoiarmy.com/webcomics/

I would like yo ask for a request for this site, I discover this first on NHentai then suddenly I doesn't have a update yet and I search it on other source too ("btw the webtoon was I'm talking about is 'Reversal' 'Stalking' and many more under 'YaoiArmy'") but it don't have well I search it on the webtoon site they have but the webtoon source it does not have 😢 So I'm making this request 😅😻

**Comment by as280093** [comment]
Here the icons
[YaoiArmy.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614432/YaoiArmy.zip)
