### ISSUE TITLE
Manga18fx: Results does not load when using URL intent

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi-extensions#8275]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 9

### Source information

Manga18fx 1.2.8

### Steps to reproduce

1. Open Browser(Firefox)
2. Go somewhere in manga18fx.com
3. Click open in app
4. Done.

### Expected behavior

Should be showing manga info

### Actual behavior

Loads for a very long time.

**Comment by alessandrojean** [comment]
/edit-title "Manga18fx: Results does not load when using URL intent"

**Comment by AriaMoradi** [comment]
fixed in #13118
