### ISSUE TITLE
MangaFast: Missing chapter names, images and search results

### ISSUE THREAD

**Issue by Hy4rkan** [tachiyomiorg/tachiyomi-extensions#8277]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

TachiyomiJ2K 1.2.1

### Android version

Android 11

### Source information

MangaFast 1.2.12

### Steps to reproduce

1. Open MangaFast extension
2. Try to navigate it or open a Manga

### Expected behavior

It should load all the content available, chapters, summary and cover. 

### Actual behavior

Instead it is a blank, nothing seems to load (see images).

![Screenshot_20210726-000919__01](https://user-images.githubusercontent.com/68969938/126942419-8f8d050d-bf3a-4972-8352-fa5f5b2f0910.jpg)
![Screenshot_20210726-002213](https://user-images.githubusercontent.com/68969938/126942423-23b007c4-c604-4423-8176-12fdd4853620.jpg)

### Other details

WebView "sort of" works; the website seems to have some pretty aggressive redirecting ads that I believe are getting in the way.

**Comment by alessandrojean** [comment]
/edit-title "MangaFast: Missing chapter names, images and search results"

**Comment by FourTOne5** [comment]
Can you share a MangaFast manga url from Tachi. I need to check if manga url format has changed.

**Comment by Hy4rkan** [comment]
> Can you share a MangaFast manga url from Tachi. I need to check if manga url format has changed.

This one comes up as 
https://mangafast.net/read/versatile-mage

And when reading a chapter as
https://mangafast.net/versatile-mage-chapter-724
