### ISSUE TITLE
Catmanga showing new ch in webview but not in app

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#8284]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.2.1

### Android version

Android 10

### Source information

Catmanga

### Steps to reproduce

Go to catmanga> click on Fire Force

 You will see 275 chapters

### Expected behavior

You should see 276 chapters like in Webview

### Actual behavior

Only seeing 275 chapters

**Comment by ivaniskandar** [comment]
The extension gets the data from the home page, That means if it doesn't show up there then it will not show up in the app. If it's a new chapter, wait for a few hours.

**Comment by FireNation323** [comment]
> The extension gets the data from the home page, That means if it doesn't show up there then it will not show up in the app. If it's a new chapter, wait for a few hours.

If that's the case why don't they make it from the chapter list almost every extension does that already

**Comment by ivaniskandar** [comment]
Yes, _almost_. The extension used to do just that and still had the same issue on some new chapters, there's no fix for this without adding unnecessary load on their site so just wait patiently or read directly on the site.

**Comment by alessandrojean** [comment]
Did the chapter appear after some hours in the extension? If so, the issue can be closed.

**Comment by ivaniskandar** [comment]
Yes, the said missing chapter is now showing up in the extension.
