### ISSUE TITLE
Jinmantiantang: Chapter images are scrambled

### ISSUE THREAD

**Issue by lbwstco** [tachiyomiorg/tachiyomi-extensions#8293]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3631

### Android version

Android 11

### Source information

1.2.13

### Steps to reproduce

Open Jinmantiantang Extension
Select a Manga to read

### Expected behavior

Manga should open with no issues.

### Actual behavior

Images have been scrambled and display incorrectly, unable to read.

### Other details

My test chapter id is 269003. It seems the website change the scramble algorithm.

**Comment by lbwstco** [comment]
https://18comic.vip/templates/frontend/airav/js/jquery.photo-0.4.js?v=20210726
It seems the new scramble function has been obfuscated.

**Comment by ZingerZY** [comment]
Cracking it will consume a lot of time, but some people specialize in cracking work, but it costs money

**Comment by ZingerZY** [comment]
> https://18comic.vip/templates/frontend/airav/js/jquery.photo-0.4.js?v=20210726
> It seems the new scramble function has been obfuscated.

Cracking it will consume a lot of time, but some people specialize in cracking work, but it costs money, I don’t have money

**Comment by calion-m** [comment]
I have done it. However my local repository is messy, can someone help merge it?
```kotlin
import java.math.BigInteger
import java.security.MessageDigest
private fun getRows(aid: Int, imgIndex: String): Int {
    fun md5(input: String): String {
        val md = MessageDigest.getInstance("MD5")
        return BigInteger(1, md.digest(input.toByteArray())).toString(16).padStart(32, '0')
    }

    return if (aid >= 268850) {
        2 * (md5(aid.toString() + imgIndex).last().toInt() % 10) + 2
    } else {
        10
    }
}
```
### usage
```kotlin
val aid = url.substring(url.indexOf("photos/") + 7, url.lastIndexOf("/")).toInt()
val imgIndex: String = url.substringAfterLast("/").substringBefore(".")
decodeImage(it, getRows(aid, imgIndex)) // let rows = getNum(aid, imgIndex)
```

### where does it come from?
type `scramble_image` in devtools.console and it shows the source code
