### ISSUE TITLE
Madara : Handle Manga and Chapters from BilibiliComics

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi-extensions#8299]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Well many scanlator are being affiliated with BC and showing there manga on their site (And most of the site are using madara) many are serving chapter from BC which when clicked redirects them to BC site. Handle them and give a toast saying to use the BC extension.

### Other details

Leviathan Scan, Immortal Updates, Twilight Scans are some of many case.

**Comment by alessandrojean** [comment]
I think it would be better to just filter then and hide it, just like the MD extension does with MangaPlus chapters.

**Comment by Riztard** [comment]
done by this? #9877
