### ISSUE TITLE
Tag search in Hitomi doesn't url-encode colons

### ISSUE THREAD

**Issue by einstein95** [tachiyomiorg/tachiyomi-extensions#8308]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

preview r3631

### Android version

Android 10

### Source information

Hitomi.la 1.2.9

### Steps to reproduce

1. Search for a tag name that contains `:`, e.g. `female:ahegao`
2. The search returns 404.

However,
1. Search for the same tag but with the `:` url-encoded (`%3A`)
2. The search shows results. 

### Expected behavior

The search with `:` returns results.

### Actual behavior

The search returns 404.

**Comment by Arraiment** [comment]
I can verify that this bug exists, but the extension probably intends for you to use the category dropdown above to choose the tag category,  instead of writing the entire query in the keyword field. The text in the keyword field is never url-encoded by design, hence the bug.
