### ISSUE TITLE
Arc-Relight: Deeplink doesn't work like expected

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi-extensions#8310]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3631, Sy Preview r400

### Android version

Android 11 (LOS)

### Source information

Arc-Relight, English, 1.2.3

### Steps to reproduce

1. Install Arc-Relight extension, if you haven't already
2. Enable Arc-Relight in Browse>Sources, if you haven't already
3. Now head over to Arc-Relight's website and open any one of the manga. For this example, I chose https://www.arc-relight.com/reader/twitter-4-koma/
4. Now try to open the link in the app. If you use Firefox (or Iceraven or similar) use the Open in App option and choose Tachiyomi: Arc-Relight (like below)

### Expected behavior

Deeplink works and opens the manga in the app

![Screenshot_20210730-001657_Android_System_arc](https://user-images.githubusercontent.com/72807749/127549214-c3077d8d-1717-4a67-bd6e-2ad6d50060fd.png)

### Actual behavior

Nothing happens.
Once I realised the app doesn't open, I tried Step 4 again only to get this error 

![Screenshot_20210730-001024_Tachiyomi_arc](https://user-images.githubusercontent.com/72807749/127549197-d0a5d6b8-ce8b-4bac-b418-91d3c1f1cea4.png)

### Other details

Was trying out some multisrc extensions with Deeplink and observed this

**Comment by ObserverOfTime** [comment]
This in an obscure issue and I do know *what* causes it but I don't know *why*.
Nevertheless, I have fixed it and will submit a pull request within the weekend.
