### ISSUE TITLE
HzManga 

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8311]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Hz Manga

### Source link

https://hzmangas.com/

### Language

Spanish (Es)

**Comment by Clouddark75** [comment]
The source has an extension already, but they aren't using that page anymore so it's just the basic madara template with no real chapters on it. 
This ticket can be closed.
