### ISSUE TITLE
MangaSpark   :(   Failed to bypass Cloudfare

### ISSUE THREAD

**Issue by zeredouni** [tachiyomiorg/tachiyomi-extensions#8323]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7.2

### Source information

MangaSpark v1.2.8

### Steps to reproduce

1. Choose a manga
2. Open a chapter
3. Image can't be load

### Expected behavior

The image should be loaded

### Actual behavior

Image can't be loaded
It showes Fail to bypass CloudFlare

### Other details

I've tried to clean the cache, and cookies from settings, I've tried change DNS through HTTPS to cloudflare and Google, still got no result.

**Comment by kiriya-aoi** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-the-cloudflare-issue

**Comment by zeredouni** [comment]
I used "WebView" , but it still doesn't work.
also ( MangaLionz v1.2.7  /  Manga Starz v1.2.8  / مانجا لينك v1.2.9  /  مانجا ليك v1.2.8 )
Have the same problem
