### ISSUE TITLE
MangaOwl: No pages found

### ISSUE THREAD

**Issue by eviosl** [tachiyomiorg/tachiyomi-extensions#8324]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

MangaOwl 1.2.18

### Steps to reproduce

1. Choose manga to open
2. Open a chapter
3.  Shows "no pages found"

### Expected behavior

Pages from the chapter should be loaded

### Actual behavior

Pages can't be loaded and shows "no pages found". It showed the same thing to all of the manhwas I opened
![Screenshot_2021-07-30-21-44-00-249_eu kanade tachiyomi](https://user-images.githubusercontent.com/88173176/127663080-4132b42c-91d1-4a80-ab6d-9cfcfb1a2772.jpg)
![Screenshot_2021-07-30-21-54-20-287_eu kanade tachiyomi](https://user-images.githubusercontent.com/88173176/127663603-203a7577-c036-4761-a94a-2b0117e2479d.jpg)
![Screenshot_2021-07-30-21-54-36-926_eu kanade tachiyomi](https://user-images.githubusercontent.com/88173176/127663609-b4b7094e-c797-4ca9-8c70-b66507da3f81.jpg)

**Comment by Clouddark75** [comment]
It works just fine here. Make sure you can bypass Cloudflare. Clean your cookies and cache.

**Comment by eviosl** [comment]
It's now working fine. Thank you so much..
