### ISSUE TITLE
Scan-Manga: Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by o01210o** [tachiyomiorg/tachiyomi-extensions#8326]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Source information

Scan-Manga 1.2.5

### Steps to reproduce

1. Choose a manga
2. Open a chapter

### Expected behavior

Chapter is displaying

### Actual behavior

Nothing happen

**Comment by lecomteb27** [comment]
I was just about to open a ticket to report the Scan-Manga problem. Thanks for doing it!

**Comment by Minoflaz** [comment]
Thanks for the ticket ! Same issue here.

**Comment by lecomteb27** [comment]
As a result, it is impossible to read the latest webtoons, mangas, etc. I'm at the end of my life people :)

**Comment by alessandrojean** [comment]
/edit-title "Scan-Manga: Expected URL scheme 'http' or 'https' but no colon was found"

**Comment by RGFRv2** [comment]
When you switch to Webview you are redirected to this link whose page does not load: https://www.scan-manga.com/403.html
![Screenshot_20210804-004358_Tachiyomi](https://user-images.githubusercontent.com/38694732/128095923-2676daae-7137-4f9e-a893-9ff048e65c9e.png)

**Comment by lecomteb27** [comment]
After doing a test on personal services.  Scan Manga has blocked Tachiyomi and especially his IP address.  I told ScanManga why x was blocked

**Comment by RGFRv2** [comment]
Is there a solution for that?

(On est d'accord que la version WEB est vraiment pas ouf du tout...)

**Comment by lecomteb27** [comment]
> Is there a solution for that?
> 
> (On est d'accord que la version WEB est vraiment pas ouf du tout...)

Tiens, voici nos échanges.
La personne, elle insulte les développeurs 👎 

![screencapture-twitter-messages-224733937-2554077367-2021-08-08-10_30_44](https://user-images.githubusercontent.com/33637996/128626118-b641c3c9-d1fb-4ef8-b7cd-0c0d18e47a7d.png)

Enfin bon, je cherche une nouvelle source sur Tachiyomi, lui en a rien à foutre des lecteurs 👍

**Comment by RGFRv2** [comment]
Y aurait pas un moyen de contourner ça ? Car ils doivent bien se baser sur quelque chose afin de bloquer Tachiyomi.

**Comment by lecomteb27** [comment]
Non, comme il bloque l'adresse IP de l'appli Tachiyomi, il n'y a aucun espoir.
Surtout que la personne qui gère le site est connecté sur le Discord, donc au courant de tout ce qui se passe.
Mais comme il n'aime pas les développeurs, il n'est pas encore intervenu sur cette discussion, étrangement :D

**Comment by soadienne65** [comment]
C'est vraiment dommage ,déjà que japanread (les mêmes teams de traducteurs) ne fonctionne pas non plus du coup on peux plus suivre les scans. Et franchement en France pour moi il n'y a que ses deux là.. c'est dommage tachiyomi nous permet de suivre les sortis des quelles sont mises à jour ..

**Comment by nauno40** [comment]
> Y aurait pas un moyen de contourner ça ? Car ils doivent bien se baser sur quelque chose afin de bloquer Tachiyomi.

Je me demande si l'on pourrait pas faire une API qui irait scrapper le site pour faire intermédiaire ... Et sous docker afin de pouvoir le re-déployer extrêmement rapidement si JMRelou décide de re-bloquer l'adresse IP

**Comment by o01210o** [comment]
Vivement que MangaPlus arrive en français.

**Comment by lecomteb27** [comment]
> Vivement que MangaPlus arrive en français.

Si MangaPlus arrive, ce sera un complément à Webtoons.com :)
J'ai hâte de lire des titres sur MangaPlus également 👍

**Comment by Adam935** [comment]
> C'est vraiment dommage ,déjà que japanread (les mêmes teams de traducteurs) ne fonctionne pas non plus du coup on peux plus suivre les scans. Et franchement en France pour moi il n'y a que ses deux là.. c'est dommage tachiyomi nous permet de suivre les sortis des quelles sont mises à jour ..

Ah donc c'est le même problème sur Japanread ça sert a rien d'attendre ? 
Perso j'ai tout le temps ça comme message.
Si c'est le cas je trouve ça triste fondamentalement je comprends ce que dit le créateur de scan-manga mais dans les faits il est y a les premier et dernière pages avec le nom des temps + discord (que j'ai très souvent rejoins pour conversé et suivre leur actualité Dommage.
![IMG_20210815_181136](https://user-images.githubusercontent.com/50600860/129500443-c83f6fc9-aa05-44b3-83d6-034374807a6c.jpg)

**Comment by RGFRv2** [comment]
> > Y aurait pas un moyen de contourner ça ? Car ils doivent bien se baser sur quelque chose afin de bloquer Tachiyomi.
> 
> Je me demande si l'on pourrait pas faire une API qui irait scrapper le site pour faire intermédiaire ... Et sous docker afin de pouvoir le re-déployer extrêmement rapidement si JMRelou décide de re-bloquer l'adresse IP

Et comment ça se mettrait en place ?
