### ISSUE TITLE
Infinite Retry

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#8328]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7.1.1

### Source information

West Manga 1.2.9

### Steps to reproduce

1. Fix infinite retry

### Expected behavior

Infinite retry when I opened manga in this extension

### Actual behavior

Infinite retry for all manga in this extension. I have tried troubleshoot guide but it couldn't help 

### Other details

![Screenshot_2021-07-30-23-17-49-06](https://user-images.githubusercontent.com/81138524/127682367-42a9194a-a30d-4e84-b018-c57e11ed5c3c.png)

**Comment by alessandrojean** [comment]
> West Manga 1.2.9

Update the extension.
