### ISSUE TITLE
Leviatan Scans cannot search or migrate to new url

### ISSUE THREAD

**Issue by Jerrk** [tachiyomiorg/tachiyomi-extensions#8330]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.2.1

### Android version

Android 9

### Source information

Leviatan Scans 1.2.12

### Steps to reproduce

Browse the extension.
Search for anything.
See error.

Try to migrate any manga to Leviatan Scans
no alternatives will be found, assmuing its the same search error as above.

### Expected behavior

you should be able to search manga.
you should be able to migrate manga.

### Actual behavior

throws an error and does not let you update an old URL.

### Other details

Every so often the manga from leviatan scans will throw 404 errors and i have to migrate them again and again back to leviatan scans again. Is this the intended behaviout or what?
I'm assuming the folks at leviatan scans are changing the URLs themselves so it breaks the connection through tachi or something.

**Comment by CrepeTF** [comment]
Not an issue on our end, the search is broken on their site. There is nothing we can do about that.

**Comment by Sharkalone** [comment]
> Every so often the manga from leviatan scans will throw 404 errors and i have to migrate them again and again back to leviatan scans again. Is this the intended behaviout or what?
> I'm assuming the folks at leviatan scans are changing the URLs themselves so it breaks the connection through tachi or something.

Nop, it's to avoid DCMA
