### ISSUE TITLE
Bug Manga Cover

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#8332]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7.1.1

### Source information

Komikcast 1.2.16

### Steps to reproduce

1. Bug cover for all manga

### Expected behavior

I cant see cover for all manga 

### Actual behavior

I cant see cover for all manga in this extension and I have tried troubleshoot guide but it shouldnt help

### Other details

![Screenshot_2021-07-31-08-44-04-52](https://user-images.githubusercontent.com/81138524/127725105-82fe128e-2656-4f3c-9eb1-601708827457.png)

**Comment by Nirawatpuechpian** [comment]
@thailand
