### ISSUE TITLE
[Bug] CoCoManhua (OhManhua): Not loading pages

### ISSUE THREAD

**Issue by BBoyJ** [tachiyomiorg/tachiyomi-extensions#8335]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

CoCoManhua (OhManhua) Version: 1.2.7

### Steps to reproduce

Open any chapter from source

### Expected behavior

Should be able to load pages

### Actual behavior

Blank page with retry button.

![Tachiyomi_CocoManhua_Bug](https://user-images.githubusercontent.com/44795313/127737673-22531d12-22c3-4854-b198-764f9ff1b8d5.jpg)

**Comment by EricFoodTab** [comment]
Even the covers won't load as well, checked it in webview and it has no problems at all

**Comment by Khaos116** [comment]
@EricFoodTab
request header add param:
referer:https://www.cocomanhua.com

**Comment by Khaos116** [comment]
like this

**Comment by KusanagiRyu** [comment]
> @EricFoodTab
> request header add param:
> referer:https://www.cocomanhua.com

What you mean?

**Comment by Khaos116** [comment]
> > @EricFoodTab
> > request header add param:
> > referer:https://www.cocomanhua.com
> 
> What you mean?

need add request param

**Comment by KusanagiRyu** [comment]
Still not working?

**Comment by Radio028** [comment]
> Still not working? 

The newer version extension still not available yet. So it is still working yet.

**Comment by Khaos116** [comment]
1.2.8 is available 
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/8358/commits/ddb0b3a5d671707fdc4ef43ea411f04818f3c072

**Comment by Khaos116** [comment]
临时使用，但是签名非官方
Temporary use, but unofficial signature
https://raw.githubusercontent.com/Khaos116/ABase/master/tachiyomi-zh.onemanhua-v1.2.8-release.apk

**Comment by Radio028** [comment]
Tested v1.2.8, it is working now. Thanks a lot.

**Comment by KusanagiRyu** [comment]
Thanks
