### ISSUE TITLE
Hiperdex issue

### ISSUE THREAD

**Issue by Tttccc2** [tachiyomiorg/tachiyomi-extensions#8337]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

10.9

### Android version

Android 5.1

### Source information

Hiperdex 1.2.11

### Steps to reproduce

Should be able to update and read

### Expected behavior

Should be able to read and update but 

### Actual behavior

show Java Lang failed to bypass cloudflare

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-the-cloudflare-issue
