### ISSUE TITLE
Bilibili Comics: Crashes on deeplink.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi-extensions#8343]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3644

### Android version

Android 6

### Source information

Bilibili Comics 1.2.5

### Steps to reproduce

Open a Bilibili Comics manga url with extension.

### Expected behavior

Manga Appear in App

### Actual behavior

It Crashes.

**Comment by alessandrojean** [comment]
I will try take a look into it.

**Comment by FourTOne5** [comment]
> I will try to take a look into it.

Since You'll be looking into it can you also add Popular, Update, Search like in-app.

## Request
Path: `/twirp/comic.v1.Comic/${if (query.isBlank) "ClassPage"  else "Search" }?device=pc&platform=web` (Blank query breaks the genre search)
Type: `POST`
Body: `{
            "area_id":  -1,
            "is_finish": STATUS,
            "is_free": 1,
            "order": SORT,
            "page_num": $page,
            "page_size": 9,
            "style_id": Genre,
            "key_word": $query
}`

## Status
Type: `Int`
ChoiceType: `Single`
Choice: `
        All: -1,
        Ongoing: 0,
        Completed: 1`

## Sort
Type: `Int`
ChoiceType: `Single`
Choice: `
        Popular: 0
        Update: 1`

## Genre
Type: `Int`
ChoiceType: `Single`
Choice: ` All: -1, Romance: 13, Teen: 20, BL: 3, Fantasy: 11, Mystery: 17, Harem: 15, Suspense: 41, Comedy: 14, Historical: 12, Eastern: 30, GL: 16, Action: 19, Adventure: 22, Slice of Life: 21, Horror: 23`

**Comment by alessandrojean** [comment]
Sure.
