### ISSUE TITLE
Toomics插件 问题

### ISSUE THREAD

**Issue by 64944646** [tachiyomiorg/tachiyomi-extensions#8348]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Toomics1.2.6

### Steps to reproduce

第一步
进去观看漫画
只显示
原来用谷歌游览器看过的章节的
不显示，没有观看的章节

### Expected behavior

应该有多少章节显示多少章节

### Actual behavior

只显示用谷歌游览器看过的
![Uploading IMG_20210801_165527.jpg…]()

### Other details

![IMG_20210801_165535](https://user-images.githubusercontent.com/88269344/127765561-b5613e70-72ae-4a54-a340-eb25eedc5056.jpg)
![IMG_20210801_165535](https://user-images.githubusercontent.com/88269344/127765570-b664e0ba-0aba-462d-9da2-ed5e8d631fb5.jpg)
![IMG_20210801_165527](https://user-images.githubusercontent.com/88269344/127765572-b82aae65-4dde-472d-a25f-f1418707b6bf.jpg)

**Comment by alessandrojean** [comment]
The extension only shows the free chapters (in the screenshot you provided, it's only the first six of the list). This is the intended behavior to avoid copyright issues and bypassing that would most likely go against their ToS.
