### ISSUE TITLE
Manhuaren插件问题

### ISSUE THREAD

**Issue by 64944646** [tachiyomiorg/tachiyomi-extensions#8349]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android11

### Source information

Manhuaren 1.2.7

### Steps to reproduce

第一步
打开Manhuaren
第二步
进去输入账号
可惜进不去

### Expected behavior

应该进去

### Actual behavior

进不去

### Other details

![IMG_20210801_171138](https://user-images.githubusercontent.com/88269344/127765727-595196ac-9ff6-4f3f-ac8c-558315f83c3c.jpg)
![IMG_20210801_171111](https://user-images.githubusercontent.com/88269344/127765729-69fed4a7-afc7-487b-a974-f3939e9da055.jpg)

**Comment by zhongfly** [comment]
本来就不支持登录账号
