### ISSUE TITLE
Asura Scans TR

### ISSUE THREAD

**Issue by Beliaruin** [tachiyomiorg/tachiyomi-extensions#8354]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Asura Scans TR

### Source link

https://tr.asurascans.com

### Language

Turkish

### Other details

Mangastein turned into Asura Scans TR so please add it. (All rights of Mangastein bought by Asura Scans)

**Comment by velvetcrowee** [comment]
pls add

**Comment by kadiranul** [comment]
Pls add

**Comment by AegroNN** [comment]
pls add asura scans tr.  we are waiting <3

**Comment by velvetcrowee** [comment]
yeah bruh we are waiting <3<3
