### ISSUE TITLE
Manga Weebs logo displaying instead of the page

### ISSUE THREAD

**Issue by aSimpleGuy** [tachiyomiorg/tachiyomi-extensions#8364]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Source information

Manga Weebs 1.2.11

### Steps to reproduce

1.Open Manga Weebs source
2.Tap on manga
3.Tap on  chapter

### Expected behavior

Image of manga should be shown instead of logo

### Actual behavior

![Screenshot_2021-08-02-11-05-13-731_eu kanade tachiyomi](https://user-images.githubusercontent.com/69104545/127809386-321ac2a0-1259-4114-b590-d24f5ab6336c.jpg)

### Other details

Not every manga has this issue

**Comment by Arraiment** [comment]
If possible, could you provide some examples of specific manga where this happens?

**Comment by aSimpleGuy** [comment]
Fixed in 0.12.1
