### ISSUE TITLE
MangaPark v3: Icon is bigger than usual.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi-extensions#8366]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

N/A

### Android version

N/A

### Source information

MangaPark v3

### Steps to reproduce

Check MPv3 icon from source.

### Expected behavior

Similar Icon to other source.

### Actual behavior

Not similar

![IMG_20210802_153927_131](https://user-images.githubusercontent.com/59261191/127840318-1710c272-1d4d-4d2f-a951-7b5163d27e9b.jpg)

### Other details

Also maybe change the logo with a better one?

**Comment by CVIUS** [comment]
wdyt?
![ic_launcher](https://user-images.githubusercontent.com/84634607/127846568-15d2c706-eb0b-4e92-989f-5cbe78ec3f57.png)

**Comment by FourTOne5** [comment]
> wdyt?
> ![ic_launcher](https://user-images.githubusercontent.com/84634607/127846568-15d2c706-eb0b-4e92-989f-5cbe78ec3f57.png)

Maybe add "v3" other than that looks good.
