### ISSUE TITLE
Manga Starz - page not found & cloudflare

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#8367]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

6

### Source information

manga Starz 1.2.8

### Steps to reproduce

- When i click to read he took to much time to show me "page not found" 
- In the download when i want to download tachi show me " failed cloudflare..."
 
But when i click on the WebView works fine and the still same problem... Over and over!

Link: https://mangastarz.com/

### Expected behavior

Should work fine and download/show the chapter after the preview.

### Actual behavior

Even after the preview... Still show me "cloudflare" problem and "page not found".

### Other details

![IMG_20210720_160318_897](https://user-images.githubusercontent.com/61906880/127848508-e1862591-f215-40f2-96db-2952144624b2.jpg)

This  when i click on preview

![IMG_20210720_160259_959](https://user-images.githubusercontent.com/61906880/127848592-7a3fb932-91bf-4bbf-ace2-cccca43d87bd.jpg)

And this problem happened over and over.

**Comment by shipoxx** [comment]
It's work fine now!

**Comment by shipoxx** [comment]
Problem back again I'm so confused

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).

**Comment by shipoxx** [comment]
> Refer to the troubleshooting guide (also detailed in #3475).

It's not about cloudfare they don't have one. If u have really good connection source work fine but if not extension show you "failed to bypass cloudflare Protection" 🤔
