### ISSUE TITLE
مانجا ليك - page not found & failed cloudflare

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#8369]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Mangalek

### Android version

Android 6

### Source information

1.2.8 مانجا ليك

### Steps to reproduce

1. I've been trying to read/download chapter from this source but "page not found" when i try to read, and "failed cloudflare..." In download.
2. I updated my WebView and click on it and all the troubleshooting guide but nothing.

### Expected behavior

√ work fine

### Actual behavior

× page not found
× failed cloudflare... can't download or read.

### Other details

Preview solution

![IMG_20210802_120444_624](https://user-images.githubusercontent.com/61906880/127852170-3e7b12b6-b968-45ee-a27e-a37bb1b0311d.jpg)

When i close the preview/brows

![IMG_20210802_120459_576](https://user-images.githubusercontent.com/61906880/127852106-87c6db83-72fb-473d-97b4-b1055b3ea94d.jpg)

Link : https://mangalek.com/

**Comment by alessandrojean** [comment]
If you're not able to use even after WebView method, nothing much can be done, just wait to see if the website lower the protection or migrate to another source.

**Comment by CHAOSX0** [comment]
fuck🙃 so there's no way to make it work?

**Comment by CHAOSX0** [comment]
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.
> 
> ### Tachiyomi version
> Mangalek
> 
> ### Android version
> Android 6
> 
> ### Source information
> 1.2.8 مانجا ليك
> 
> ### Steps to reproduce
> 1. I've been trying to read/download chapter from this source but "page not found" when i try to read, and "failed cloudflare..." In download.
> 2. I updated my WebView and click on it and all the troubleshooting guide but nothing.
> 
> ### Expected behavior
> √ work fine
> 
> ### Actual behavior
> × page not found
> × failed cloudflare... can't download or read.
> 
> ### Other details
> Preview solution
> 
> ![IMG_20210802_120444_624](https://user-images.githubusercontent.com/61906880/127852170-3e7b12b6-b968-45ee-a27e-a37bb1b0311d.jpg)
> 
> When i close the preview/brows
> 
> ![IMG_20210802_120459_576](https://user-images.githubusercontent.com/61906880/127852106-87c6db83-72fb-473d-97b4-b1055b3ea94d.jpg)
> 
> Link : https://mangalek.com/

same problem

**Comment by shipoxx** [comment]
An update about this:

When i click on ' latest' it's work fine, and i can explore the manga, but also i cant download or view manga on regular way

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
