### ISSUE TITLE
MangaSpark - failed to bypass cloudflare

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#8370]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

6

### Source information

MangaSpark 1.2.8

### Steps to reproduce

1. Updated my WebView
2. View to pass cloudflare but not working

### Expected behavior

It should work after the WebView..

### Actual behavior

Page not found
Failed to bypass cloudflare

### Other details

After i view ..

![IMG_20210802_121636_222](https://user-images.githubusercontent.com/61906880/127853445-f57c58f8-ac02-402c-be08-92c68443ad60.jpg)

When i close WebView

![IMG_20210802_121620_349](https://user-images.githubusercontent.com/61906880/127853531-3148b92d-2050-4a46-8ed5-dfd59da53939.jpg)

**Comment by alessandrojean** [comment]
If you're not able to use even after WebView method, nothing much can be done, just wait to see if the website lower the protection or migrate to another source.

**Comment by shipoxx** [comment]
You don't to copy and paste same response.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
