### ISSUE TITLE
Mangalionz - failed to bypass cloudflare

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#8371]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

6

### Source information

Mangalionz 1.2.7

### Steps to reproduce

1. Itry WebView.. no result

### Expected behavior

Work fine

### Actual behavior

![IMG_20210802_121620_349](https://user-images.githubusercontent.com/61906880/127853842-639fcd75-0ebe-4b0b-8115-50a63736dae4.jpg)

![IMG_20210802_121636_222](https://user-images.githubusercontent.com/61906880/127853871-93d614e8-2b56-473d-aa7e-1eb3bcf5cd53.jpg)

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-the-cloudflare-issue

**Comment by shipoxx** [comment]
> https://tachiyomi.org/help/guides/troubleshooting/#solving-the-cloudflare-issue
> 
> If you're not able to use even after WebView method, nothing much can be done, just wait to see if the website lower the protection or migrate to another source.

Nah i didn't work

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
