### ISSUE TITLE
Manga content in Bakkin source doesn't match with title

### ISSUE THREAD

**Issue by maggotb** [tachiyomiorg/tachiyomi-extensions#8380]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

7.1.1

### Source information

Bakkin

### Steps to reproduce

Go to Bakkin source

Open any manga

Open any chapter

### Expected behavior

The content should match with the title

### Actual behavior

The content is the Yuru Yuri manga

### Other details

It happens with all the mangas in the source

**Comment by ObserverOfTime** [comment]
This seems to happen because chapter URLs aren't always unique. I'll see if I can fix it tomorrow.
