### ISSUE TITLE
Erro GeassScanlator: For Input String: "agosto"

### ISSUE THREAD

**Issue by yToddyn** [tachiyomiorg/tachiyomi-extensions#8382]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Geass Scanlator 1.2.10

### Steps to reproduce

![Screenshot_20210803-132406_Tachiyomi](https://user-images.githubusercontent.com/85813659/128053091-0bff5c87-542d-4144-998c-1884d32e6aa9.jpg)

### Expected behavior

Era para acontecer isso 
![Screenshot_20210803-133743_Tachiyomi](https://user-images.githubusercontent.com/85813659/128053235-40fb4ad8-cd7e-45f6-86b5-ee3cfcf66590.jpg)

### Actual behavior

Aconteceu o problema For Input String: "Agosto", ao atualizar o mangá. Ao invés de aparecer um novo capítulo ao atualizar o mangá.

**Comment by alessandrojean** [comment]
Thanks for providing examples. I will take a look later.
