### ISSUE TITLE
MangaYabu: Manga covers are not loading

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi-extensions#8385]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3644

### Android version

Android 11

### Source information

MangaYabu! v1.2.9

### Steps to reproduce

1. Open the browse section from the extension.

### Expected behavior

Manga covers should load.

### Actual behavior

Manga covers are not loading.

### Other details

I will fix it later, this issue is just to remember me about it and to avoid duplicates.

Reported by a user in #support on Discord.

**Comment by Keikunbr** [comment]
This bug isn't solved because I've many mangas in my library from source MangaYabu and they still without covers.
I tried clean the cache but this not solved the issue,

**Comment by alessandrojean** [comment]
Some cover images are having loading problems, mainly because of their server, nothing that can be done about that on the extension.

**Comment by Keikunbr** [comment]
> 
> 
> Some cover images are having loading problems, mainly because of their server, nothing that can be done about that on the extension. They manage to load on WebView or Browser because it follows the redirect requests, but extension have a limit.

Thanks for feedback.
