### ISSUE TITLE
ManhuaZ

### ISSUE THREAD

**Issue by FaTe-code** [tachiyomiorg/tachiyomi-extensions#8386]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ManhuaZ

### Source link

https://manhuaz.net/

### Language

English

**Comment by Clouddark75** [comment]
The source used ZBulu theme, but now changed to Dark theme (witch I have seen just a couple sources using it, I guess it should be multisrc).

**Comment by CVIUS** [comment]
Also, #8652 is using the same theme. 

> I guess it should be multisrc.

👍

**Comment by vetleledaal** [comment]
> The source used ZBulu theme, but now changed to Dark theme (witch I have seen just a couple sources using it, I guess it should be multisrc).

Is Dark a different theme? Looks like it has a lot in common with FMReader

**Comment by skysonfire** [comment]
I really can't wait to see this, they're making some great moves lately.
