### ISSUE TITLE
Myhentaigallery author search not working.

### ISSUE THREAD

**Issue by stnm12brX2** [tachiyomiorg/tachiyomi-extensions#8389]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

At the moment, it is impossible sort for an author's work through the myhentaigallery extension. The myhentaigallery site has 2 search boxes, one labeled tags and one labeled titles.  Author search (after pressing the author's name on a comic screen) defaults to using title bar to look up the author. This does not work as (for some reason) the author is considered a tag and must use the tag bar.

This poses an issue to tachiyomi's global search as there is no differentiator between author and title. I suggest just changing the tag selector in the filter menu into a text box (as seen on various extensions, notably on multporn.net) and making the link that is the author's name in the manga menu screen use the tag bar not the title bar (verified by using web view btw). I recommend not changing the default behavior of the global search as that would be very messy as well as require a change in the app which I think is unecessary for a small bug like this.

I have fully updated tachiyomi and the extension. Thank you for reading and your hard work.

**Comment by stnm12brX2** [comment]
I put feature request, not bug........ Sorry for being stupid. Idk how to change the label.....

**Comment by CVIUS** [comment]
label needs to be changed here

**Comment by stnm12brX2** [comment]
I tried to but I couldn't figure it out when I edited the post.
