### ISSUE TITLE
access permission From the deactivated extension tsuki manga

### ISSUE THREAD

**Issue by BrNote** [tachiyomiorg/tachiyomi-extensions#8395]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

LG k9

### Source information

Tsuki mangas

### Steps to reproduce

Dando problemas de acesso ao entrar na fonte 
Giving access problems when entering the source
![Screenshot_2021-08-04-08-37-02](https://user-images.githubusercontent.com/88436178/128174321-dbe36148-76a8-406c-9a00-4394797ab44e.png)

### Expected behavior

O certo seria entrar normalmente
The right thing would be to enter normally

### Actual behavior

It happened that there was an error and the sleeves aren't carrying either 
Aconteceu que houve um erro e as mangas também não estão carregando

### Other details

![Screenshot_2021-08-04-08-37-02](https://user-images.githubusercontent.com/88436178/128174701-6e501d03-e1a5-4d5e-9219-e5e878e5385e.png)

**Comment by arkon** [comment]
Did you read the message on the screen?
