### ISSUE TITLE
Hentairead won't show genres even after pressing reset

### ISSUE THREAD

**Issue by FrixBOX** [tachiyomiorg/tachiyomi-extensions#8396]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

7.0

### Source information

Hentairead 1.2.9

### Steps to reproduce

1.Open Source
2.Press the filter button
3. and press reset button

### Expected behavior

show genres list that was previously hidden

### Actual behavior

only show press reset to attempt to fetch genres warning no matter how many times i press reset button

**Comment by CVIUS** [comment]
> Genres may not work for all sources
Its written above the genre list

**Comment by FrixBOX** [comment]
> 
> 
> `Genres may not work for all sources`
> Its written above the genre list

So it's never gonna work ?

**Comment by CVIUS** [comment]
sadly, no. they are using tags and not genres. tachiyomi ext (madara multisrc to be specific, the website theme) currently do not fetch tags.

**Comment by CVIUS** [comment]
also, they only have 4 genres :3
here -> https://hentairead.com/genre-index/

**Comment by FrixBOX** [comment]
would it be possible to make the tags searchable?

**Comment by CVIUS** [comment]
> would it be possible to make the tags searchable?

open a feature request issue
