### ISSUE TITLE
Tsuki Manga: Dando problemas de acesso ao entrar na fonte

### ISSUE THREAD

**Issue by BrNote** [tachiyomiorg/tachiyomi-extensions#8400]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7.1.2

### Source information

Tsuki mangas 1.2.24

### Steps to reproduce

![Uploading Screenshot_2021-08-04-08-37-02.png…]()

### Expected behavior

Entra na fonte e carregar os mangás

### Actual behavior

Deu acesso de extensão desativado

**Comment by alessandrojean** [comment]
Leia o erro. Não temos controle sob isso se os responsáveis do site decidem desativar o acesso da extensão. Pergunte e peça a eles para reabilitar.
