### ISSUE TITLE
manhwas.men

### ISSUE THREAD

**Issue by vetp** [tachiyomiorg/tachiyomi-extensions#8404]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [x] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manhwas.men

### Source link

https://manhwas.men/

### Language

Inglês, Espanhol, Raw coreano

### Other details

Site de raw de manhwas hentai

**Comment by alessandrojean** [comment]
> I have checked that the extension does not already exist on the website extensions list or the app.

Already exists as "Manhwas Men".
