### ISSUE TITLE
Comick.fun: chapter pages issue

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi-extensions#8405]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1, r3644

### Android version

A10

### Source information

1.2.6

### Steps to reproduce

1. browse comick.fun
2. search `tensei inja wa hokusoemu`
3. open chapter 6

### Expected behavior

load chapter page

### Actual behavior

immediately failed to load

### Other details

other chapter work just fine
can load in webview

**Comment by Arraiment** [comment]
It appears to be a problem with comick.fun's api. The image links they've provided are invalid.
[This](https://comick.fun/api/get_chapter?hid=lVLX1) is the endpoint causing problems.

**Comment by Riztard** [comment]
> EDIT: They fixed the issue, chapter should load fine now.

stil doesnt work, 
i thought this was duplicate issue but maybe that fix only for #8192
