### ISSUE TITLE
Silence Scan

### ISSUE THREAD

**Issue by Douglasimav** [tachiyomiorg/tachiyomi-extensions#8408]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

SilenceScan 1.2.12 

### Steps to reproduce

open the extension

### Expected behavior

load the mangas

### Actual behavior

 unable to  parse  TLS  packet header 

### Other details

domain changed to https://silencescan.com.br/

**Comment by alessandrojean** [comment]
I will update it later.

**Comment by alessandrojean** [comment]
The PR #8412 will fix it, but you will have to migrate your library entries from the source with numbers to Silence in order to update the URLs to the new ones.
