### ISSUE TITLE
Mangaowl: Not working and No pages found

### ISSUE THREAD

**Issue by sabbyby** [tachiyomiorg/tachiyomi-extensions#8411]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

App version: 0.11.1

### Android version

Android 8

### Source information

Mangaowl

### Steps to reproduce

![Screenshot_20210806-013940](https://user-images.githubusercontent.com/88506198/128396165-a816b621-4743-4824-b8b3-bbaf575cbdef.jpg)

1. Open the app. Refresh. 
2. When you open a manga/manhwa/manhua in library it says no pages found. 
3. Tried opening it in Web view, still it is not working. 

### Expected behavior

Open the pages and works perfectly

### Actual behavior

No pages found. Even when open in web view, still not working. No chapters opened in the specific source.

**Comment by Arraiment** [comment]
The extension works fine for me. Can you provide the specific manga where you encountered this issue? Also check if you are using the latest version of the extension.

**Comment by sabbyby** [comment]
> The extension works fine for me. Can you provide the specific manga where you encountered this issue? Also check if you are using the latest version of the extension.

Just now, the extension works fine now. Maybe they just had a maintenance overnight. Tnx.
