### ISSUE TITLE
<Tsuki Mangás> HTTP error 429: Check websit in WebView

### ISSUE THREAD

**Issue by zootakuxy** [tachiyomiorg/tachiyomi-extensions#8438]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

TsukiManga

### Steps to reproduce

1. Entrar na aba de navegação
2. Abrir a fonte de Tsuki Mangás

### Expected behavior

Deveria mostar a lista das obras disponivel na tsuki mangás

### Actual behavior

HTTP error 429: Check websit in WebView

### Other details

![photo_2021-08-07_12-48-44](https://user-images.githubusercontent.com/17088320/128600664-9efbb301-663c-4914-8046-ae2302221e9c.jpg)

No WebView funciona normalmente

![photo_2021-08-07_12-58-28](https://user-images.githubusercontent.com/17088320/128600965-27289757-c588-4e68-a8d9-2bc54694c33c.jpg)

**Comment by zootakuxy** [comment]
Ops, esqueci de informar, mas no WebView está funcionando sem problemas.

**Comment by alessandrojean** [comment]
Eles estão bloqueando a extensão e não temos controle sob isso. Recomendamos migrar para outra fonte ou usar o site ou app próprio deles.
