### ISSUE TITLE
arabshentai

### ISSUE THREAD

**Issue by Ghilas951** [tachiyomiorg/tachiyomi-extensions#8452]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

arabshentai

### Source link

https://arabshentai.com/manga

### Language

Arabic

### Other details

![Capture+_2021-08-07-19-51-56](https://user-images.githubusercontent.com/87284048/128611007-bfe889de-0287-4e87-88f7-29959226a66c.png)

**Comment by shipoxx** [comment]
يا رجل لم اكن أعلم أن هناك مواقع هنتاي عربية هذا غريب!

**Comment by CHAOSX0** [comment]
> يا رجل لم اكن أعلم أن هناك مواقع هنتاي عربية هذا غريب!

yeah that is weird af

**Comment by alessandrojean** [comment]
Duplicate of #6189

**Comment by arkon** [comment]
@Ghilas951 Do not post NSFW content on GitHub.
