### ISSUE TITLE
MangaOwl - failed to bypass cloudflare 

### ISSUE THREAD

**Issue by recmsan** [tachiyomiorg/tachiyomi-extensions#8456]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 1.6.2

### Android version

Android 5.1

### Source information

MangaOwl 1.2.19

### Steps to reproduce

1. Open WebView feature
2. View to pass cloudflare not working

### Expected behavior

It should work after opening WebView

### Actual behavior

Page not found
Failed to bypass cloudflare

**Comment by recmsan** [comment]
![IMG_20210808_130736](https://user-images.githubusercontent.com/84307775/128624098-e406a636-3a08-4e9e-92cf-aef40dd38aa7.jpg)
![IMG_20210808_130742](https://user-images.githubusercontent.com/84307775/128624104-bf875109-09db-4fa9-b5a9-fcbbc8fbbbaa.jpg)

**Comment by tanuukii** [comment]
OMG same! I can't read any manga because of cloudflare😭😭

**Comment by sabbyby** [comment]
I thought i was the only one haha. These days, mangaowl doesn't work properly.

**Comment by akmalmeaw** [comment]
Yeah. Its happen to me too. What happen??? I am scared. Its remind me to manhuascan that also have problem also then at last the extension got deleted....please save mangaowl. I dont know any manga extension as good as mangaowl after manhuascan gone😭😭😭

**Comment by arkon** [comment]
MangaOwl is dead.
