### ISSUE TITLE
Foolslide Customizable bug

### ISSUE THREAD

**Issue by HondaTooru97** [tachiyomiorg/tachiyomi-extensions#8458]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

The phoenix scans

### Steps to reproduce

/

### Expected behavior

/

### Actual behavior

/

### Other details

in their extension no manga is shown, not even the latest additions

**Comment by Riztard** [comment]
@HondaTooru97 what is `The phoenix scans` website url?

**Comment by HondaTooru97** [comment]
> @HondaTooru97 what is `The phoenix scans` website url?

This https://www.phoenixscans.com/

**Comment by Riztard** [comment]
that website is not using Foolslide theme. ofc it wont work

**Comment by HondaTooru97** [comment]
> that website is not using Foolslide theme. ofc it wont work

So it won't work anymore?😭😭

**Comment by Riztard** [comment]
if they no longer use foolslide website theme it wont work

**Comment by HondaTooru97** [comment]
> if they no longer use foolslide website theme it wont work

and if so, would it be possible to add it between extensions in another way? Like how it was an external application to foolslide?

**Comment by alessandrojean** [comment]
It should be available as a new ext by #7196.

**Comment by HondaTooru97** [comment]
> It should be available as a new ext by #7196.
pizzareader is there already in the extensions?

**Comment by alessandrojean** [comment]
You should be able to install the individual extension of Phoenix Scans.

![SmartSelect_20210808-212026_Tachiyomi](https://user-images.githubusercontent.com/14254807/128650137-b9924bd5-c627-4520-9580-68682ebe9ad1.jpg)

**Comment by HondaTooru97** [comment]
> You should be able to install the individual extension of Phoenix Scans.
> 
> ![SmartSelect_20210808-212026_Tachiyomi](https://user-images.githubusercontent.com/14254807/128650137-b9924bd5-c627-4520-9580-68682ebe9ad1.jpg)

yes, but it doesn't work
![Uploading Screenshot_20210809-022541_Tachiyomi.jpg…]()

**Comment by FedericoHeichou** [comment]
> > You should be able to install the individual extension of Phoenix Scans.
> > ![SmartSelect_20210808-212026_Tachiyomi](https://user-images.githubusercontent.com/14254807/128650137-b9924bd5-c627-4520-9580-68682ebe9ad1.jpg)
> 
> yes, but it doesn't work
> 
> ![Screenshot_20210809-022541_Tachiyomi](https://user-images.githubusercontent.com/87310799/128650364-dce35edf-9986-424a-bf61-71b5da580f37.jpg)

I'm the author, it works, try to clear the cache

**Comment by HondaTooru97** [comment]
> > > You should be able to install the individual extension of Phoenix Scans.
> > > ![SmartSelect_20210808-212026_Tachiyomi](https://user-images.githubusercontent.com/14254807/128650137-b9924bd5-c627-4520-9580-68682ebe9ad1.jpg)
> > 
> > 
> > yes, but it doesn't work
> > ![Screenshot_20210809-022541_Tachiyomi](https://user-images.githubusercontent.com/87310799/128650364-dce35edf-9986-424a-bf61-71b5da580f37.jpg)
> 
> I'm the author, it works, try to clear the cache

IT WORKS, THANK YOU SO MUCH!
