### ISSUE TITLE
LilyManga - Pages not Found

### ISSUE THREAD

**Issue by Rixman254** [tachiyomiorg/tachiyomi-extensions#8459]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Source information

LilyManga 1.2.8

### Steps to reproduce

1. Load source
2. Open Webview
3. Download

### Expected behavior

Load Manga Pages

### Actual behavior

Error: Page not found (Even after launching Webview)

**Comment by Arraiment** [comment]
On which manga are you experiencing this problem specifically?

**Comment by Riztard** [comment]
its working, probably they change something and change it back. or something else
