### ISSUE TITLE
Bakkin source : some chapters don't open

### ISSUE THREAD

**Issue by maggotb** [tachiyomiorg/tachiyomi-extensions#8462]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

7.1.1

### Source information

Bakkin

### Steps to reproduce

Go to Bakkin source

Open "Oomuro-ke!" manga, open any chapter

### Expected behavior

It should open the chapter

### Actual behavior

Chapters don't open, an error says "collection contains no element matching the predicate"

### Other details

It happens only in the Oomuro-ke, Yuyushiki, and Touzainanboku mangas

**Comment by ObserverOfTime** [comment]
They all work for me. :thinking:

**Comment by curche** [comment]
Works fine at my end as well. Closing as it cannot be reproduced and there's been no response. 

Please do go through [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) once again.
If you still get this issue, create a new ticket
