### ISSUE TITLE
I install Toonily extension (many times) and it doesn't appear 

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi-extensions#8471]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

10

### Source information

Toonily 1.2.12

### Steps to reproduce

I install toonily

### Expected behavior

To be installed and to open naturally

### Actual behavior

It appears that the extension isn't installed

### Other details

Sometimes it get installed and behave naturally but after some (hours) the issue appears again
****See the attached photos for further explanation****
![IMG_20210808_183515](https://user-images.githubusercontent.com/75262438/128639051-bae6506a-400d-4e60-acfe-ec36397bf733.jpg)
![IMG_20210808_183527](https://user-images.githubusercontent.com/75262438/128639054-0c884712-6e9c-430b-a51d-aac7841f2ef9.jpg)
![IMG_20210808_183538](https://user-images.githubusercontent.com/75262438/128639056-1ef5c537-b890-40e1-a689-8c05c8f03b23.jpg)

**Comment by arkon** [comment]
You probably need to enable NSFW sources.

**Comment by hakudansho** [comment]
I did

**Comment by hakudansho** [comment]
> You probably need to enable NSFW sources.

You were right thanks.🙏❤️
