### ISSUE TITLE
Hitomi.la extension wont load any pages

### ISSUE THREAD

**Issue by KEMOHUNZ** [tachiyomiorg/tachiyomi-extensions#8472]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.12.1

### Android version

Android 9

### Source information

Hitomi.la 1.2.9

### Steps to reproduce

1. Open the latest tab on Hitomi extension
2. Try to read anything
3. Pages won't load and keep asking for retry

### Expected behavior

Pages load successfully 

### Actual behavior

Pages won't load and keep asking for retry

### Other details

Another finds is that some older manga (older than 2018) are working like what it's intended. All the newer manga have this problem. This problem also occure like 2 months after i used the extension back in 2020, and never getting fixed.

Titles that can load (example): 
Seigi no Netori Ch. 1-3 (2014)
Takamiya-kun no Hanayome Shugyou (2014)
Haha no hi to Musume no hi | Mother’s Day and Daughter’s Day (2015)
Tonari no Sumire-san | My Neighbor Sumire-san (2016)
Seifuku no Oku no Kimochi Ii Toko (2017)

**Comment by Arraiment** [comment]
It works fine for me. Which source language are you using?

**Comment by KEMOHUNZ** [comment]
English

**Comment by Militinix** [comment]
> It works fine for me. Which source language are you using?

This is happening in the older Mangas, the recent ones don't have this problem.

**Comment by Arraiment** [comment]
Any specific examples? Although I can't seem to reproduce @KEMOHUNZ's issue.

**Comment by Militinix** [comment]
If you click on the Hitomi extension, the first manga on the list has this problem, name Lucky Dosukebe! Kouhen page 16 or if you prefer check an example of @KEMOHUNZ's, manga Seigi no Netori Ch. 1-3 page 62.

**Comment by Arraiment** [comment]
Yeah there appears to be an issue building the page urls. I'll see if I can fix it when I have the time.

**Comment by alessandrojean** [comment]
Should be fixed by #8554. If you are still facing this after the extension update, please open a new issue.
