### ISSUE TITLE
Meus Manga

### ISSUE THREAD

**Issue by gutolimeira** [tachiyomiorg/tachiyomi-extensions#8473]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Meus Mangas

### Source link

https://meusmangas.net

### Language

Brazilian Portuguese

**Comment by alessandrojean** [comment]
Use the same theme of MangaTube.

**Comment by gutolimeira** [comment]
Yes, but MangaTube doesn't have any chapters in many mangas

**Comment by alessandrojean** [comment]
That was just an observation for the code...

**Comment by gutolimeira** [comment]
Ok, sorry.
