### ISSUE TITLE
Error in Phoenix Fansub, message - For Input String: "agosto"

### ISSUE THREAD

**Issue by SuperP91** [tachiyomiorg/tachiyomi-extensions#8479]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

 0.12.1

### Android version

Android 10

### Source information

Phoenix Fansub 1.2.9

### Steps to reproduce

![image](https://user-images.githubusercontent.com/8459200/128648194-4cbb7d81-ee29-4c81-8e08-3ad0e9b4e800.png)

### Expected behavior

The new chapters should be updated without any message error.

### Actual behavior

I see in the commit history that WPMangaStream was alredy updated to address an issue very similar in GS (#8415). It seems that the behavior is the same in this case, searching for new chapters the date parser seems to return this error.

**Comment by alessandrojean** [comment]
Can you try to reinstall the extension and see if you're still getting this error?

**Comment by SuperP91** [comment]
After reinstalling worked perfectly. Thank you!
