### ISSUE TITLE
Manhwa Club

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi-extensions#8481]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manhwa Club

### Source link

https://manhwa.club/

### Language

English

### Other details

Manhwa Club is back, and seems to be using same theme as ReadManhwa (possible new factory extension?).

@CVIUS Since you removed Manhwa Club from Madara earlier, might want to take a look at this

**Comment by CVIUS** [comment]
If I only have enough knowledge to do so, but no. Let's patiently wait for someone to take it over. I decided to remove it because the site isn't up for months(?)

**Comment by vetleledaal** [comment]
Uses same theme as ReadManhwa
