### ISSUE TITLE
ReadManhwa: Change theme into multisrc

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8482]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

#8481 https://manhwa.club changed their website theme that obviously looks like https://readmanhwa.com which already exist in the extension list. I do not know what theme they are using, so this require further investigation.

**Comment by Chan220** [comment]
isn't manhwa.club the extension no longer available?

**Comment by jopejoe1** [comment]
https://nhentai.com is also using that theme.
