### ISSUE TITLE
Madara: Ability to fetch tags

### ISSUE THREAD

**Issue by cvius** [tachiyomiorg/tachiyomi-extensions#8483]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Some madara sources have tags and madara factory currently do not support fetching tags. It may not work for some sources too.

https://manganine.com/manga-tag/topmanhua/
https://manhwaworld.com/manga-tag/online/
https://manhwafull.com/manga-tag/s2manga/

**Comment by Riztard** [comment]
should be able to be done like `ProjectFilter` in WPMangaStream

**Comment by SolarAquarion** [comment]
I'm getting this issue with HentaiRead.  If this feature was implemented it would make things more enjoyable when trying to use HentaiRead.
