### ISSUE TITLE
MyReadingManga forbidding access

### ISSUE THREAD

**Issue by PHandlerC** [tachiyomiorg/tachiyomi-extensions#8484]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 8.1.0

### Source information

MyReadingManga 1.2.41

### Steps to reproduce

1. Open extension

### Expected behavior

Extension should work as normally, showing available manga in the website.

### Actual behavior

HTTP error 403 when opening the extension. Cookies and cache from WebView and Chrome were cleaned and the IP can still access the website normally, but the app is unable to connect. Complete clean and uninstalling the app still gives the same result.

### Other details

Extension stopped working after a 2 day slow time in the website. Although Cloudflare protection is used, the app can't connect, but the website in any mobile browser is functioning normally.

**Comment by CrepeTF** [comment]
#7923
