### ISSUE TITLE
beemanga

### ISSUE THREAD

**Issue by cimon-bkr** [tachiyomiorg/tachiyomi-extensions#8487]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

beemanga

### Source link

https://ww1.beemanga.com

### Language

english

### Other details

beemanga has the latest and spoiled webtoon chapters

**Comment by CVIUS** [comment]
Zbulu theme

**Comment by cimon-bkr** [comment]
> Zbulu theme

yes ! is it an issue ?

**Comment by Riztard** [comment]
> yes ! is it an issue ?

nope, its just a note for developer
