### ISSUE TITLE
MangaPlus Russian language support

### ISSUE THREAD

**Issue by Iliansic** [tachiyomiorg/tachiyomi-extensions#8500]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Recently MangaPlus added official Russian translations to it's catalog. Could you please add it to extension?

**Comment by alessandrojean** [comment]
I will add it 👍🏻
