### ISSUE TITLE
RawLH/WeLoveManga: Title does not sync with the content

### ISSUE THREAD

**Issue by Donnie-B** [tachiyomiorg/tachiyomi-extensions#8501]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Source information

WeLoveManga 1.2.6

### Steps to reproduce

1. Open Latest list entry in WeLoveManga
2. Open manga Kage no Jitsuryokusha ni Naritakute!
3. When refreshing chapter, the thumbnail and description turns into Shinka no Mi - Shiranaiuchi ni Kachigumi Jinsei, but the title remains the same.

### Expected behavior

The manga title and content should match

### Actual behavior

Some manga title has different content compared to the title

### Other details

Different people might have issue with different title but the same case.
I suspect it's because of the site migration, so the ID on the new site and the one already stored inside the tachiyomi got conflicted, but I don't understand how to sync it back.

**Comment by Arraiment** [comment]
Refer to the "Clear Cache" section [here](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis) and try the first 3 options. See if that helps. You might want to perform a backup beforehand.

**Comment by laggerspecialist** [comment]
Have the same issue. Clearing cache did nothing. Searching from the extension will give the correct manga but incorrect title. If you sync/refresh manga in your library, the title will stay but the cover and chapters will change. The chapters will be what the cover shows. In Version 1.2.7 migration worked. But if you migrated in the previous version. If you migrated in the previos version, your chapters will be correct but the title is wrong. If you migrate again in 1.2.7, the chapters will follow the changed title and lost your previous manga. Those migrated might want to double check their library

**Comment by Donnie-B** [comment]
I fixed it not by using Clear Cache, but Clear Database.
For the series I don't follow, this fixed the problem, but for the followed series, I need to re-migrated all titles one-by-one. If only there is a way to mass migrate title.
Though I did this on version 1.2.6
Not sure what changes is done for 1.2.7

**Comment by laggerspecialist** [comment]
Thanks. I just found it as well by clearing database. And yeah, need to re migrate everything one by one.

**Comment by Arraiment** [comment]
> I fixed it not by using Clear Cache, but Clear Database.

> Thanks. I just found it as well by clearing database

Nice.


> If only there is a way to mass migrate title.

Unfortunately not in Tachiyomi itself but some of the forks do have such a feature.

Do update if you run into any other issues with the extension.
