### ISSUE TITLE
Add Team1x1 Request

### ISSUE THREAD

**Issue by Satomar** [tachiyomiorg/tachiyomi-extensions#8504]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Team1x1

### Source link

https://team1x1.com/

### Language

Arabic

### Other details

This site is considered the best Arabic manhua translator

**Comment by loocool2** [comment]
الموقع لن يتم اعادته بسبب أن صاحب الموقع طلب ذلك، وسياسية تطبيق الجديدة تحترم الفراق التي تترجم اعمال كنوع من الدعم.

TeamX will not be added back as the Scanlator team has requested it to be removed. Read #3475 for more information

**Comment by Satomar** [comment]
Thanks

عَ ـبُـ‘ـُوٌډ ٻوُڪيَ
