### ISSUE TITLE
Please, add Russian Manga Plus

### ISSUE THREAD

**Issue by panchenko9b** [tachiyomiorg/tachiyomi-extensions#8518]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manga Plus Russia

### Source link

https://mangaplus.shueisha.co.jp/manga_list/all

### Language

Russian

### Other details

Last Monday Manga Plus launched its Russian catalog. Currently it has 6 series. Please, add extension for them like we has for Spanish and other non-English languages.

**Comment by curche** [comment]
> I have checked that the extension does not already exist on the website extensions list or the app.

Should have already been added by https://github.com/tachiyomiorg/tachiyomi-extensions/pull/8513
