### ISSUE TITLE
Manga's in the Manga-TR resource does not open 

### ISSUE THREAD

**Issue by Uzlet** [tachiyomiorg/tachiyomi-extensions#8520]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

I want the Manga-TR resource to work like any other resource . I want to read while inside the application without going to the source's site. For example, I ran into this issue in the Berserk, Vagabond and The Beginning After the End mangas. In the application, the chapters seem to be unable to load, but the manga opens normally on the application's site. Please fix this issue

**Comment by Redbot19** [comment]
berserk ve vagabond manga tr den kaldırıldı site baktığında da bölümşerin olmadığını göre bilirsin ingilizce yazmaya üşendim

**Comment by Uzlet** [comment]
Berserk kaldırılmış ama vagabond manga tr de duruyor oradan okuyabiliyorum

**Comment by Redbot19** [comment]
yep vagabond okunuyor ben geçenlerde okuyum bittirdiydim

**Comment by Redbot19** [comment]
bir kontrol etmek için grip baktımda evet bazı sayfalar yüklenmiyor

**Comment by kyoyacchi** [comment]
Bazı sayfaları okuyabilirken, bazı sayfalarda yeniden dene diyor.

**Comment by kyoyacchi** [comment]
Any updates about this?

**Comment by Uzlet** [comment]
Nope it still the same

30 Eyl 2021 Per 20:51 tarihinde KYOYA ***@***.***> şunu yazdı:

**Comment by alessandrojean** [comment]
> Any updates about this?

It will get fixed when someone has free time and wants to work on it, no ETA.
