### ISSUE TITLE
Qvfamma

### ISSUE THREAD

**Issue by Dayron15atn** [tachiyomiorg/tachiyomi-extensions#8525]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Qwfamma

### Source link

https://qvfammaonline.blogspot.com/

### Language

Español

**Comment by alessandrojean** [comment]
Blogger website without a proper structure. All the manga listings are images, so it isn't even possible to get the titles.
