### ISSUE TITLE
Tencent Comics (ac.qq.com): Add lock icon for paywalled chapters

### ISSUE THREAD

**Issue by XeroxV** [tachiyomiorg/tachiyomi-extensions#8534]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Add lock icon for paywalled chapter

### Other details

Take Kuaikan as an example, if the chapter is paywalled, there will be a lock icon beside it.

**Comment by Soitora** [comment]
/edit-title "Tencent Comics (ac.qq.com): Add lock icon for paywalled chapters"
