### ISSUE TITLE
Unable to bypass extension

### ISSUE THREAD

**Issue by miss1433** [tachiyomiorg/tachiyomi-extensions#8537]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

21.1

### Android version

Android 11

### Source information

IsekaiScan. Com

### Steps to reproduce

Since the extension is working alright before. 
It should start of by clicking the manga and then showing the chapters but it didn't happened for almost a week now

### Expected behavior

It should be the same to other manga extension

### Actual behavior

This is what happened.. 
![Screenshot_2021-08-12-23-25-40-862_eu kanade tachiyomi](https://user-images.githubusercontent.com/28482555/129225233-bb1fd8f5-2477-4294-8cb2-a8818f0c5675.jpg)

### Other details

None

**Comment by CVIUS** [comment]
Isekaiscan is currently in maintenance mode atm, there's nothing we can do to the extension. Wait for it to be up or migrate. Can be closed.
