### ISSUE TITLE
Previsão para desbloqueio da extensão tsuki mangas

### ISSUE THREAD

**Issue by BrNote** [tachiyomiorg/tachiyomi-extensions#8546]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 7.1.2

### Source information

Tsuki mangas 1.2.27

### Steps to reproduce

![Screenshot_2021-08-13-11-02-14](https://user-images.githubusercontent.com/88436178/129369305-ce9826cb-9214-4fea-8da2-e0b7339818e6.png)

### Expected behavior

Abrir a fontw

### Actual behavior

![Screenshot_2021-08-13-11-02-14](https://user-images.githubusercontent.com/88436178/129369458-f007dc9f-0e36-4087-a4f1-46f524515f68.png)

**Comment by alessandrojean** [comment]
Sem previsão. Use o site ou o app próprio deles cado queira continuar lendo o conteúdo deles. Recomendamos migrar para outra fonte.
