### ISSUE TITLE
Bato.to: HTML entities not parsed in titles

### ISSUE THREAD

**Issue by indivisible** [tachiyomiorg/tachiyomi-extensions#8549]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

Bato.to 1.2.13

### Steps to reproduce

1. Open Browse > Sources > bato.to
1. Search for `I"S`
2. See multiple garbled titles ("`I&quot;S`")

### Expected behavior

Properly parsed entities in titles (eg `I&quot;S` => `I"S`)

### Actual behavior

Unparsed entities appear in titles (`&quot;`, `&#39;`, etc)

### Other details

This happens with other entities too (for example `&#39;`) in some titles

**Comment by Arraiment** [comment]
![20210814_171611](https://user-images.githubusercontent.com/76941874/129441197-2ec0acb1-70bf-4c05-a1f7-ebe6cebb797a.jpg)
Looks fine to me

**Comment by indivisible** [comment]
> Looks fine to me

![Screenshot_20210814-212053_Tachiyomi](https://user-images.githubusercontent.com/937641/129458485-d9fcced5-4b2b-4e5c-a1c1-45a9e6e1a3a3.jpg)
Might be locale related. My phone is on hu-HU

**Comment by Soitora** [comment]
/edit-title "Bato.to: HTML entities not parsed in titles"
