### ISSUE TITLE
Toonkor: URL changed

### ISSUE THREAD

**Issue by retsieem** [tachiyomiorg/tachiyomi-extensions#8551]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ToonKor

### Source link

https://tkor.dog/

### Language

Korean

### Other details

Everytime I load or download it always give a timeout. The new address is https://tkor.dog/

**Comment by happywillow0** [comment]
Fixed by #8585
