### ISSUE TITLE
TCB Scans: Remember currentTimeMillis like in CatManga

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8557]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

add currentTimeMillis when a manga was first fetch so that update will notify like in CatManga

### Other details

I cannot take a look for it anymore cus I personally don't have enough time, classes will start soon too. Cya! xD

**Comment by Soitora** [comment]
/edit-title "TCB Scans: Remember currentTimeMillis like in CatManga"
