### ISSUE TITLE
MangaOwl: Search is buggy

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi-extensions#8559]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

10

### Source information

Mangaowl 1.2.21

### Steps to reproduce

Search love me dramatically

### Expected behavior

Result should show

### Actual behavior

Other manga appears

### Other details

But when I search Bj alex, it works. That's why its buggy. 😅

**Comment by Arraiment** [comment]
Just to clarify, did you change any of the filters before searching or did you just use text search?

**Comment by tanuukii** [comment]
> Just to clarify, did you change any of the filters before searching or did you just use text search?

I just use text search and I did not change any of the filters.

**Comment by Arraiment** [comment]
Yeah the reason its buggy is related to [this](https://github.com/tachiyomiorg/tachiyomi/issues/5584) issue with the main app. Until, that's fixed it will remain buggy. As a temporary workaround you can try setting minimum chapters to 0 to see accurate results.

**Comment by tanuukii** [comment]
> Yeah the reason its buggy is related to [this](https://github.com/tachiyomiorg/tachiyomi/issues/5584) issue with the main app. Until, that's fixed it will remain buggy. As a temporary workaround you can try setting minimum chapters to 0 to see accurate results.

Oh, okay. Thank you!

**Comment by tanuukii** [comment]
I will close it now because it is now working on latest preview (r3691). TYSM♥️
