### ISSUE TITLE
[FlameScans] Each chapter update creates a duplicate

### ISSUE THREAD

**Issue by antikovt** [tachiyomiorg/tachiyomi-extensions#8565]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

TachiyomiJ2K 1.2.1

### Android version

Android 11, OneUI 3.1

### Source information

Flame Scans 1.2.16

### Steps to reproduce

Happens each time a new chapter of a manga comes out.

### Expected behavior

The library updates automatically, there's a new chapter in the manga.

### Actual behavior

The library doesn't update automatically and trying to update the manga manually gives an "HTTP error 404" toast. To get the new chapter, one should go into the extension and re-add the manga, upon which it becomes a duplicate. The old copy can be deleted.

### Other details

Screenshots in order of appearance. Notice that on the second screenshot, the manga (updated duplicate) is not tagged as "in library". Solo Leveling is not the only title it happens to, just an example.
![Screenshot_20210814-002646_TachiyomiJ2K](https://user-images.githubusercontent.com/76940779/129460101-58883286-3385-4654-94e1-c42166ae7be5.png)
![Screenshot_20210814-002502_TachiyomiJ2K](https://user-images.githubusercontent.com/76940779/129460104-a259f248-ff71-4ffa-b941-cf8f8f730c75.png)
![Screenshot_20210814-002543_TachiyomiJ2K](https://user-images.githubusercontent.com/76940779/129460105-a17cbbb5-888a-45bf-8899-d1b73bf4c9b7.png)

**Comment by antikovt** [comment]
FlameScans is not in the known issues tab though, I checked that before posting

**Comment by loocool2** [comment]
The extension is gone from the repo. It's been removed by request. There will be no fixes to it.
