### ISSUE TITLE
MangaAlarab: date of chapters doesn't appear in its exact place

### ISSUE THREAD

**Issue by iRahmaniMed** [tachiyomiorg/tachiyomi-extensions#8574]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

MangaAlarab 1.2.3

### Steps to reproduce

1. Enter the extension
2. Chose manga and enter it

### Expected behavior

The date appears under the chapter name
![Screenshot_2021-08-15-12-22-30-028_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/80282534/129476797-b42a277c-9c91-4f15-addd-1fbbb47c6f73.jpg)

### Actual behavior

The date appears in the same line with the name of the chapter
![Screenshot_2021-08-15-12-07-07-992_eu kanade tachiyomi](https://user-images.githubusercontent.com/80282534/129476703-cc3f1ec6-1daf-48c9-8f01-0f44701a5f26.jpg)

**Comment by iRahmaniMed** [comment]
@ahmedgamal17

**Comment by ahmedgamal17** [comment]
There is already PR to fix this but it's not merged yet

**Comment by iRahmaniMed** [comment]
Oh, I didn't see it
