### ISSUE TITLE
Feature Request: Hidden or Secure Catagories

### ISSUE THREAD

**Issue by Vercingetorix321** [tachiyomiorg/tachiyomi-extensions#8575]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

For privacy there should be a way to create a hidden category that does not appear on the top scroll bar of the app. Alternatively, or in addition to this, it would great to be able to secure individual categories with a passcode.  Such a passcode should be able to be made different from your device passcode. I have other people who use my phone and use tachiyomi on my phone so the existing security features will not keep prying eyes from anything I would want keep private. I hate asking for features for an already great app that is offered for free but I am sure many people would enjoy this feature. Thank you for your consideration.

**Comment by arkon** [comment]
Wrong repo and already rejected.

**Comment by Vercingetorix321** [comment]
Hi, you move very fast. Sorry I posted in the wrong place. Do you mean the feature request itself was rejected? I searched in as many places as I could find to see if this was already requested but could find nothing about it. Is there a reason for the rejection?

**Comment by curche** [comment]
See the issue at the correct repo
https://github.com/tachiyomiorg/tachiyomi/issues/1508
