### ISSUE TITLE
Manga Land Arabic: No chapters found

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#8576]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

"Manga Land Arabic 1.12.10"

### Steps to reproduce

1- Enter the Extension
 2- Open the manga
 3- There are no chapters

### Expected behavior

You should see the chapters

### Actual behavior

There are no chapters

### Other details

After I updated the plugin, this problem appeared
![Screenshot_20210817-052346](https://user-images.githubusercontent.com/87826849/129654051-f464e5cd-dbdb-4a22-8bed-865fec0fd0c8.png)
![Screenshot_20210817-052409](https://user-images.githubusercontent.com/87826849/129654086-8f3a7f13-b97b-4567-947e-25326d775eda.png)

**Comment by ahmedgamal17** [comment]
Does the website work on WebView

**Comment by yemenihandsome** [comment]
@ahmedgamal17 yes the site is working

**Comment by yemenihandsome** [comment]
It was working yesterday before the update to the source

**Comment by yemenihandsome** [comment]
![Uploading Screenshot_20210815-184250.png…]()

**Comment by ahmedgamal17** [comment]
but it doesn't load  with me
![Screenshot from 2021-08-15 18-13-38](https://user-images.githubusercontent.com/25945926/129485086-6857f2f8-fdab-42ce-b37a-590dda51d61c.png)

**Comment by yemenihandsome** [comment]
![Uploading Screenshot_20210816-085633.png…]()

**Comment by yemenihandsome** [comment]
![Screenshot_20210816-085633](https://user-images.githubusercontent.com/87826849/129518488-75849fc6-a246-4618-bbff-5e03756a0950.png)

**Comment by yemenihandsome** [comment]
@ahmedgamal17 See that the site is working for me

**Comment by alessandrojean** [comment]
/edit-title "Manga Land Arabic: No chapters found"
