### ISSUE TITLE
IsekaiScan.com : Chapters not showing up 

### ISSUE THREAD

**Issue by KattelAnts** [tachiyomiorg/tachiyomi-extensions#8577]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

IsekaiScan.com 1.2.11

### Steps to reproduce

1. Enter the Extension
2. Choose a manga

### Expected behavior

All chapters show up and images in WebView show up.
![Screenshot_20210816-000305](https://user-images.githubusercontent.com/88095499/129492929-c8209456-066b-4013-a667-6bf1186b209d.jpg)
![Screenshot_20210816-000209](https://user-images.githubusercontent.com/88095499/129492939-4a82b0ce-4e4a-48c2-9767-18c515dfac4a.jpg)

### Actual behavior

No chapters found in app and images in WebView don't show up.
![Screenshot_20210815-235917](https://user-images.githubusercontent.com/88095499/129492952-6a64704d-2826-4df1-9f7d-bbc7984ed1f5.jpg)
![Screenshot_20210816-000009](https://user-images.githubusercontent.com/88095499/129492960-cd03df68-2c59-464b-b7af-250b029a2460.jpg)

**Comment by Love-Chaos** [comment]
same problem, Isekaiscan had a update so probably need some code update

**Comment by morcefaster** [comment]
Working on this right now.
