### ISSUE TITLE
Arthur Scan: No chapters found

### ISSUE THREAD

**Issue by yToddyn** [tachiyomiorg/tachiyomi-extensions#8579]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

Arthur Scan - 1.2.11

### Steps to reproduce

when the manga is updated, it should appear the new chapters of the given manga

### Expected behavior

![Screenshot_20210815-211832_Tachiyomi](https://user-images.githubusercontent.com/85813659/129497092-24024e10-6a53-4874-89cc-39de955ba7e4.jpg)

### Actual behavior

![Screenshot_20210815-210649_Tachiyomi](https://user-images.githubusercontent.com/85813659/129497080-aa000116-e8e3-4518-87f8-9a3be3278a9f.jpg)

**Comment by alessandrojean** [comment]
I will take a look later.

**Comment by CecilioASDS** [comment]
> I will take a look later.

Amigo se puder da uma olhada na extensão da Tao Sect também ficaria muito agradecido esta dando no address associated with hostname e tem mangas com os capítulos faltando
