### ISSUE TITLE
Dynasty Reader: URL intent not working

### ISSUE THREAD

**Issue by RossSmyth** [tachiyomiorg/tachiyomi-extensions#8581]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

v1.2.1 J2K

### Android version

Android 11

### Source information

Dynasty v1.2.14

### Steps to reproduce

1. Open Dynasty Reader series link via Tachiyomi intent
2. Wait for series to load in search

### Expected behavior

Series should load and open

### Actual behavior

Just loads as long as I let it sit (a few minutes was longest I let it sit)

### Other details

- I am able to search manually for series 
- Intents for chapters work

**Comment by curche** [comment]
The [Dynasty extension](https://tachiyomi.org/extensions/#en.dynasty) has 5 sources viz Anthologies, Chapters, Doujins, Issues, Series. Ideally, one of those should match your link. Can you provide an example link(s)?

**Comment by RossSmyth** [comment]
I have tried several series in the past and they wouldn't load. Though trying it right now does work and load. But this has happened in the past, and has not just been a one time occurrence. My guess is something on dynasty's side? It's hard to say. Best I can do is take a screen video of it next time it happens.

 To be clear searching manually by the title's name has always worked fine. But when opening dynasty links with Tachiyomi it doesn't always work when it searches for "manga:series:<title>". The other Dynasty extensions would recognize and display "No results found" but the Dynasty Series extension would just sit and load for as long as I let it sit.

**Comment by alessandrojean** [comment]
/edit-title "Dynasty Reader: URL intent not working"
