### ISSUE TITLE
Manhwa18.me

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#8583]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manhwa18.me

### Source link

https://manhwa18.me/

### Language

English 

### Other details

18+ manhwa

**Comment by Arraiment** [comment]
Extensions for manhwa18.org, manhwa18.app, manhwa18.net, manhwa18.cc, manhwa18.com all already exist. I dunno if adding what appears to be another mirror is necessary.

**Comment by fawadkhan121** [comment]
The first 2 extensions aren't working

**Comment by Arraiment** [comment]
I'll have a look at the existing ones when I have time.
