### ISSUE TITLE
ISSUE WITH THE ISEKAISCAN EXTENSION.IT SHOWS "NO CHAPTERS FOUND" WHEN YOU UPDATE.

### ISSUE THREAD

**Issue by GAAROS** [tachiyomiorg/tachiyomi-extensions#8586]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

ANDROID 11

### Source information

isekaiscan.com

### Steps to reproduce

First step: Open any manga on isekaiscan extension in the updated list.
Second step: Try to refresh the chapter list of the above manga you selected.

### Expected behavior

The thing that should happen is that it should get updated and new unread manga should be shown at top.

### Actual behavior

This happens instead: It will show "NO CHAPTERS FOUND" error.

**Comment by loocool2** [comment]
#8577
