### ISSUE TITLE
WeComics: Not able to read the paid chapters when signed in

### ISSUE THREAD

**Issue by yimeji** [tachiyomiorg/tachiyomi-extensions#8592]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

11

### Source information

WeComics

### Steps to reproduce

1. Choose a series
2. Login to account via web
3. download chapter

### Expected behavior

Should download normally as the free chapter able to do so.

### Actual behavior

Will receive error "currently not available, login through web if purchased..."

### Other details

The web view via Tachiyomi doesn't work properly problem with view/zoom/scale.

**Comment by alessandrojean** [comment]
> The web view via Tachiyomi doesn't work properly problem with view/zoom/scale.

Try to check if there's an update available to the WebView or try with other WebView implementation.

**Comment by alessandrojean** [comment]
/edit-title "WeComics: Not able to read the paid chapters when signed in"

**Comment by jopejoe1** [comment]
Pretty sure WeComics was removed in #9695
