### ISSUE TITLE
Setsu scans: blank chapter list

### ISSUE THREAD

**Issue by Eastral** [tachiyomiorg/tachiyomi-extensions#8595]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

8.1.0

### Source information

1.2.10

### Steps to reproduce

![Screenshot_20210817_071349](https://user-images.githubusercontent.com/86764747/129642296-2a7557ed-b17f-42e3-90b3-92fb3ba7ffec.jpg)

### Expected behavior

The manga title should have been listed beside cover

### Actual behavior

Blank title manga list, only shows cover

### Other details

The manga with blank title also gives error in webview.

**Comment by FourTOne5** [comment]
Duplicate(?) of #8299

**Comment by Riztard** [comment]
its working now, maybe there is some update that filter bilibili
