### ISSUE TITLE
Isekaiscan update

### ISSUE THREAD

**Issue by thetechgeekko** [tachiyomiorg/tachiyomi-extensions#8596]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Isekaiscan

### Source link

https://isekaiscan.com/

### Language

English

### Other details

For a week or 2 the site was down.
Yesterday it came up . And there are updates in website but those can't be seen in tachiyomi with the latest updated extension.
I hope it could be fixed.
Thank you.

**Comment by loocool2** [comment]
#8577
