### ISSUE TITLE
Graphite Comics

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi-extensions#8598]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Graphite Comics

### Source link

https://graphitecomics.com/

### Language

English

### Other details

Replacement for INKR, but an actual decent one with big library

**Comment by alessandrojean** [comment]
I will try to work on it.
