### ISSUE TITLE
MangaTigre

### ISSUE THREAD

**Issue by LeeanPR95** [tachiyomiorg/tachiyomi-extensions#8608]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

MangaTigre

### Source link

https://www.mangatigre.com

### Language

Spanish

### Other details

Hello, I suggest adding MangaTigre as a source, since there is very up to date manga on this website.

It can be a very good alternative to sources like TuMangaOnline or MangaMX.

The website also has detailed information on each manga, such as: original name, alternative titles, demographics and content, genres, authors and artists, and so on.

It also has, of course, a section for recent manga chapters, and search filters.

I hope you consider adding the source, since I consider in my opinion, a very good alternative.

Sorry for my bad English.

**Comment by xcr44sh** [comment]
it is really a good option, I hope they can have the extension soon, as it would be a good choice of variety as in the other languages.

**Comment by LeeanPR95** [comment]
Thanks for your good vibes, the truth is right now I'm learning programming at a very basic level. I hope I can learn a lot so I can contribute to this project soon.
