### ISSUE TITLE
Myreadingmanga works in WebView but not on Tachiyomi

### ISSUE THREAD

**Issue by skybloodx0824** [tachiyomiorg/tachiyomi-extensions#8620]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

App version: 0.12.1

### Android version

Android 11

### Source information

Myreadingmanga 1 .2.42

### Steps to reproduce

I just updated the new version of the myreadingmanga update
![Screenshot_2021-08-18-16-57-23-065_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/129869504-5eba9fbf-ed12-44b0-848a-4229ae2b40ff.jpg)

I need to go through cloudflare verification 
![Screenshot_2021-08-18-16-37-04-159_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/129869871-8fd71503-2a95-4277-b60b-1f4ba062161c.jpg)

I already passed the clouflare verification and lead me to WebView.
![Screenshot_2021-08-18-16-53-24-253_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/129869637-b51ead7b-2130-473b-9843-df97141b8789.jpg)

When I went back to Tachiyomi app, it doesn't load.
![Screenshot_2021-08-18-16-53-30-678_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/129869729-23e736d2-4d2b-4850-adb2-8eda42618aa7.jpg)

### Expected behavior

Usually after the update we need to open it up on WebView in order to make it works on Tachiyomi app.

### Actual behavior

After the new update I can't access myreadingmanga through tachiyomi but it works perfectly fine in the WebView.

**Comment by mountfox** [comment]
@skybloodx0824 Could you please clear app cache of Tachiyomi and try again? If it still does not work, try to reinstall the MyReadingManga 1.2.42 and see if the issue is really caused by the udpate.

<img src="https://user-images.githubusercontent.com/88900671/129920326-fe68d031-40df-4c50-b71a-7c7147353563.png" width=300>

**Comment by skybloodx0824** [comment]
Yeah, I've done all of that and it's still the same. I still can't access myreadingmanga through tachiyomi app. It works fine on the WebView.

**Comment by mountfox** [comment]
@skybloodx0824 Did you try to install the 1.2.41?

**Comment by CVIUS** [comment]
Use VPN and connect to US server, it'll work.

**Comment by skybloodx0824** [comment]
@mountfox I installed the 1.2.42. Can you teach me how to install the 1.2.41? Sorry since I'm still new with this.

**Comment by skybloodx0824** [comment]
@CVIUS sadly I don't use a VPN. I think I need to get one if I can't fix this issue. Thanks for your suggestion. 😊

**Comment by skybloodx0824** [comment]
@mountfox I did it. I downloaded the 1.2.41 extension and it's working now.
![Screenshot_2021-08-18-23-20-14-938_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/129925328-05e362c4-d1a9-417d-81aa-42de5d0a863b.jpg)

![Screenshot_2021-08-18-23-20-28-773_eu kanade tachiyomi](https://user-images.githubusercontent.com/84511836/129925345-bd754055-4704-453f-b6c8-753c233d627e.jpg)

And yes the problem is caused by the new update.
Thank you for helping me 😊.

**Comment by mountfox** [comment]
@skybloodx0824 How long does it take to finish loading the website in the webview without cache? It could be that your loading takes more than 10s can cause the Cloudflare bypass to timeout. In this case, using a VPN may help.

**Comment by skybloodx0824** [comment]
@mountfox it doesn't take more than 10s to load. Well just to safe I'll get the VPN soon. Seriously thank you for helping me. But I think there's a lot of people who have the same problem as me after the 1.2.42 update. Will the moderater fix it?

**Comment by remex24** [comment]
Do you have any idea where i can download a prevvious version of version 1.2.41 i can't seem to find it

**Comment by CarlosEsco** [comment]
new release should fix
