### ISSUE TITLE
App crashes when I save a chapter image

### ISSUE THREAD

**Issue by Jeffersonrsds** [tachiyomiorg/tachiyomi-extensions#8633]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

8.1.0

### Source information

J7 Pro

### Steps to reproduce

1-open a manhwa 2-open any chapter 3-save any page

### Expected behavior

save pages and the APP doesn't close by itself.

### Actual behavior

The APP closes by itself when saving a page.

### Other details

this happened in the old version of the APP

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
