### ISSUE TITLE
Implement Category Security/Locking

### ISSUE THREAD

**Issue by 2Exists** [tachiyomiorg/tachiyomi-extensions#8634]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Individual categories will be locked or secured so that accidents are to be avoided. Since the application has +18 sources together with safe sources, this feature might be usable and important especially when reading safe contents outside.

### Other details

Biometrics or pattern licking might suffice for this kind of feature. Thank you very much

**Comment by alessandrojean** [comment]
> If this is an issue with the app itself, I should be opening an issue in the app repository.
