### ISSUE TITLE
Golden Manga

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8639]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Golden Manga

### Source link

https://golden-manga.com

### Language

Arabic

### Other details

I hope to be added to Tachiyomi-extensions

**Comment by shipoxx** [comment]
We used to have this source but i can't find him now!

Ex: #3625

**Comment by shipoxx** [comment]
The source has been removed

#4298 (not sure)
@alessandrojean can you confirm this?

**Comment by alessandrojean** [comment]
It was temporarily removed because they changed the theme of the website and the extension was broken because of it. Wait until someone adds it again.

**Comment by hani1998** [comment]
why ?

**Comment by alessandrojean** [comment]
Read the comment, it explains why.

**Comment by shipoxx** [comment]
> It was temporarily removed because they changed the theme of the website and the extension was broken because of it. Wait until someone adds it again.
> 
> And that issue you mentioned is another source, not this one, it just share the same name.

The first one or the second one?

Ik there's another one but different name in Spanish ig

**Comment by hani1998** [comment]
OK

**Comment by Semq245** [comment]
من زمان المشكلة ليش للحين ماتغير اللينك ؟

**Comment by HusamAljaafari** [comment]
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a title with source name.
> - [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
> - [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
> - [X] I will fill out all of the requested information in this form.
> 
> ### Source name
> 
> Golden Manga
> 
> ### Source link
> 
> https://golden-manga.com
> 
> ### Language
> 
> Arabic
> 
> ### Other details
> 
> I hope to be added to Tachiyomi-extensions
