### ISSUE TITLE
Resurrection Scan

### ISSUE THREAD

**Issue by Jeffersonrsds** [tachiyomiorg/tachiyomi-extensions#8644]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Resurrection Scan

### Source link

https://www.rescan.top/?m=1

### Language

Portuguese

**Comment by alessandrojean** [comment]
Blogger website without a strict pattern in the HTML, an extension can't be made for sites like this.
