### ISSUE TITLE
"No Chapters Found" in Immortal Updates

### ISSUE THREAD

**Issue by SoloLeveller1** [tachiyomiorg/tachiyomi-extensions#8648]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

Immortal Updates 1.2.10

### Steps to reproduce

1. Browse through Immortal Updates source.
2. Click on any manga.

### Expected behavior

Manga loads up and you can see the chapters.

### Actual behavior

Says no chapters found. Even though there are chapters which show up in webview.

### Other details

Manga which I have already read(even if only some chapters) show up and can read from tachi itself without any issues.

**Comment by Arraiment** [comment]
Should be fixed by #8660
