### ISSUE TITLE
isekaiscan: HTTP error 403

### ISSUE THREAD

**Issue by GAAROS** [tachiyomiorg/tachiyomi-extensions#8651]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

isekaiscan 1.2.13

### Steps to reproduce

step 1: Go to the latest section of it.

### Expected behavior

EDIT: it should show the latest manga's updated list.

### Actual behavior
EDIT: Now it is showing the 403 error and when I am opening it in the webview there is no captcha to be cleared to fix it.

**Comment by Pedrolina** [comment]
Cara tá acontecendo a mesma coisa cmg e eu n sei o q fazer Man

**Comment by alessandrojean** [comment]
> Cara tá acontecendo a mesma coisa cmg e eu n sei o q fazer

@Pedrolina do not comment off-topic stuff not related to this particular issue. If you need help, reach us through #support channel in [Tachiyomi's Discord server](https://discord.gg/tachiyomi). You can also ask for help in Portuguese there.

**Comment by CrepeTF** [comment]
The issue seemed to be temporary and has fixed itself
