### ISSUE TITLE
Mangakakalot: chapter images do not load

### ISSUE THREAD

**Issue by Rickmelmo** [tachiyomiorg/tachiyomi-extensions#8654]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Source information

Mangakakalot 1.2.7

### Steps to reproduce

Select a chapter in source(Ex:The weakest occupation ch 24) Read through pages. From page 3 and on try to retry loading the pages. 

### Expected behavior

It should load the page 

### Actual behavior

It doesn't load the page, and retry reappears.

**Comment by alessandrojean** [comment]
/edit-title "Mangakakalot: chapter images do not load"

**Comment by curche** [comment]
Loads fine at my end. This is usually due to an unstable internet connection. Try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) steps to fix it.
