### ISSUE TITLE
Manga Library

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi-extensions#8661]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manga Library

### Source link

https://mangalibrary.net/

### Language

English

**Comment by happywillow0** [comment]
Reminder: Madara
`useNewChapterEndpoint = true`

**Comment by happywillow0** [comment]
This site is being stupid. Not only did they move the "admin" section to `mangamin`
but the site is throwing an error 500 on the details page causing an exception in the app even though it gives you the right page.
