### ISSUE TITLE
Tao Sect: Unable to resolve host

### ISSUE THREAD

**Issue by thanosluyang** [tachiyomiorg/tachiyomi-extensions#8663]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

7

### Source information

Tao Sect 1.2.5

### Steps to reproduce

1. Click on any manga.
2. Choose a chapter.
3. Shows the message "Unable to resolve host".

### Expected behavior

The chapter load.

### Actual behavior

The chapter does not load and the error message appears.

**Comment by alessandrojean** [comment]
/edit-title "Tao Sect: Unable to resolve host"
