### ISSUE TITLE
Mangahere: Site update

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi-extensions#8664]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Mangahere updated site http://newm.mangahere.cc/

### Other details

Also, search is buggy. Please update the extension. Thank you❤️

**Comment by Arraiment** [comment]
The old site at [https://www.mangahere.cc/](https://www.mangahere.cc/) appears to be working fine though. Also can you elaborate on how the search is buggy?

**Comment by tanuukii** [comment]
> Also can you elaborate on how the search is buggy?

For example, I search Blue lock, it shows no result found in the extension. But when I try to search on the site, it is present, and more results are showing. If I search One piece, other manga shows.
