### ISSUE TITLE
Tapas - paywall chapters give error "no pages found" 

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi-extensions#8686]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

SY Preview r402

### Android version

12

### Source information

Tapas 1.2.12

### Steps to reproduce

1. find a tapas title with paywall chapters
2. log in to tapas account in webview
3. purchase a chapter in webview 
3. try to read the purchased chapter in Tachiyomi 

### Expected behavior

the chapter would be readable through Tachiyomi

### Actual behavior

Given the error "no pages found"

**Comment by AlexMiniReal** [comment]
That also happens to me. I buy chapters on the Tapas app, then go to Tachiyomi, refresh the Manhwa and the chapter still has the locked emoji. This bug appeared after the last update of the extension.
