### ISSUE TITLE
manga livre obsolete (mangasPROJECT) fix

### ISSUE THREAD

**Issue by MrJ0se** [tachiyomiorg/tachiyomi-extensions#8695]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

11

### Source information

Mánga Livre (mangasPROJECT) 1.2.10

### Steps to reproduce

1. access no cached chapter of mangaProject/ mangalivre

### Expected behavior

load chapter

### Actual behavior

do not load images

### Other details

obsoleted recently, i believe because no chapter is loading images (due to new chapter token generation method).

to help active developers to solve it, i debugged the site and found that they are using a new method to get the token that is usually used to get image link list: `.../{chapter_id}?token={*token*}`

### in order to get the new token, you need these paramethers:
- id_release: chapter id from current chapter HTML link;
- token: pick token from link parameter of reader.min.js (in current chapter html):
		`... src="/mangazord_lib/js/reader.min.js?id=cca469e8708363be0934&token=5c029ccaeee5b80e1d53f6b32d0f36198fe4e2e8&i ...`
		(`5c029ccaeee5b80e1d53f6b32d0f36198fe4e2e8`)
- "obfuscator_key": from Reader constructor call in current HTML
		`... new Reader(chapters, number, isVertical, "b13ef880146fd869e42c17039b46edb7ad1c19bf"); ...`
		(`b13ef880146fd869e42c17039b46edb7ad1c19bf`)

### use the algorithm in the obfuscated js reader.min.js:
```
function(e, t, i) {
	var o = Math.max(i % n("MmsG")(), 1)//another obfuscated function that return 7
	  , a = t.match(/.{1,5}/gi);
	t = (t = a.slice(o).concat(a.slice(0, o)).join("")).split("");
	var s = e.split("").reverse()
	  , c = e.split("").sort(function() {
		return Math.random() - .5
	})
	  , u = e.split("").sort(function() {
		return Math.random() - .5
	});
	return e.split("").reduce(function(e, n, r) {
		return e + u[r] + n + s[r] + t[r] + c[r]
	}, "").match(new RegExp(".{1," + Math.max(i % 11, 1) + "}","gi")).map(function(e) {
		return r(Math.max(i % 7, 1)) + e
	}).join("")
}
```

reverse engineered version:

```
function obfuscate_token(token, obfuscator_key, id_release/*current chapter id*/) {
	var o = Math.max(
		id_release % 7,
		1
	);
	var a = obfuscator_key.match(/.{1,5}/gi);

	obfuscator_key = (obfuscator_key = a.slice(o).concat(a.slice(0, o)).join("")).split("");

	var s = token.split("").reverse();
	var c = token.split("").sort(() => Math.random() - 0.5);
	var u = token.split("").sort(() => Math.random() - 0.5);

	return token.split("")
		.reduce(
			function(acumulator, currentValue, index) {
				return acumulator + u[index] + currentValue + s[index] + obfuscator_key[index] + c[index]
			},
			""
		).match(
			new RegExp(
				".{1," + Math.max(id_release % 11, 1) + "}","gi"
			)
		).map(function(e) {
			return r(Math.max(id_release % 7, 1)) + e
		}).join("")
}
```

Hope this helps, thanks for attention.

**Comment by alessandrojean** [comment]
I have reversed engineer the code too, but it has a lot of things that they can easily change in the algorithm to break the extension again as soon the update is available. Besides that, they clearly said they want their users to read in their website instead of third party apps, it's a cat and mouse game situation, and we do not keep extensions like that.
