### ISSUE TITLE
Mangadoom: Error appears

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8701]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

10

### Source information

Mangadoom 1.2.3

### Steps to reproduce

Open any manga

### Expected behavior

No error should appear

### Actual behavior

This appears.
![Screenshot_20210821-183452_Tachiyomi](https://user-images.githubusercontent.com/87689027/130319167-49c12fc3-5d91-48b6-9a84-bf744e0d59ae.jpg)

**Comment by CVIUS** [comment]
To someone who will take this, consider #8276
