### ISSUE TITLE
qingman5 (kuman55)

### ISSUE THREAD

**Issue by heartlog** [tachiyomiorg/tachiyomi-extensions#8719]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

kuman55

### Source link

http://qingman5.com/

### Language

Chinese

### Other details

Add this manga source please ,
It gives quick raw of manga after released quickly.
Good source for Chinese manhwa.

**Comment by stevenyomi** [comment]
This site (http://www.kumw5.com/) has oudated, inaccessible chapters and broken images, thus not worth making an extension. You may want to close this issue.
