### ISSUE TITLE
2 Extensions Broken. Setsu and Tritinia

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#8720]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

Setsu Scans (1.2.11), Tritinia Scans (1.2.11)

### Steps to reproduce

Add series to library
Get error

### Expected behavior

Should update series

### Actual behavior

Gives error

### Other details

http://imgur.com/a/fqIZyVV

Attached error result from library update ^

**Comment by alessandrojean** [comment]
Related to the view count reporting system, I will take a look :+1:
