### ISSUE TITLE
1st Kiss Manhua Thumbnails do not Load

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi-extensions#8726]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Source information

1st Kiss Manhua 1.2.5

### Steps to reproduce

1. Open extension catalog
2. Scroll
3. Thumbnails don't load

### Expected behavior

Thumbnails all load

### Actual behavior

Thumbnails don't load

### Other details

Clearing the database and refreshing library covers in Settings > Advanced and restarting doesn't help.

**Comment by Clouddark75** [comment]
Yah, some Madara sources extensions simply just don't load the covers at all now.

**Comment by Riztard** [comment]
its working now
