### ISSUE TITLE
myreadingmangaa error

### ISSUE THREAD

**Issue by D1o2c3** [tachiyomiorg/tachiyomi-extensions#8729]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

myreadingmanga 1.2.42

### Steps to reproduce

403 error unfixed even after webview is properly initiated and is no problem running.

### Expected behavior

403 error should be solved after opening the site in webview and the more advance where you click the three dots on the upper corner of the screen during webview to open the site in another webview. After exiting webview and refreshing the source then the mangas will show.

### Actual behavior

The webview works properly however, after exiting webview and refreshing the source/extention it does not load into normal but instead stays on 403 error. This had been happening since the last update of the extention.

**Comment by akmalmeaw** [comment]
Its true, i also downgrade myreadingmanga to 1.2.41 version. Its still working, maybe 1.2.42 have a problem. Jusr waiting for the next version. But for temporary, you should downgrade it, install the 1.2.41 version....

**Comment by CarlosEsco** [comment]
new release should fix
