### ISSUE TITLE
TruyenVN

### ISSUE THREAD

**Issue by QuangHien3010** [tachiyomiorg/tachiyomi-extensions#8731]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

TruyenVN

### Source link

https://truyenvn.com/

### Language

Vietnamese

### Other details

It is source for manhwa vietsub

**Comment by vetleledaal** [comment]
Uses FMReader

**Comment by NeoHp94** [comment]
Source change to : https://truyenvn.vip/
