### ISSUE TITLE
[Meta] Remove Mundo Mangá-kun

### ISSUE THREAD

**Issue by Stykalash** [tachiyomiorg/tachiyomi-extensions#8739]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

Hello, good morning/evening/night!
I'm Mundo Mangá-kun's scanlator owner and would like to ask you to remove our scan from your extension/application

Proof Of Ownership:
![image](https://user-images.githubusercontent.com/23347707/130356714-0c5305b0-9612-452a-a84a-a557e7ead9a3.png)

**Comment by Stykalash** [comment]
![image](https://user-images.githubusercontent.com/23347707/130356974-01988146-dc87-4c79-a026-a34089021c07.png)

**Comment by arkon** [comment]
#8741
