### ISSUE TITLE
Remove Mundo Mangá-kun extension

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi-extensions#8741]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

Proof of ownership was provided in Discord and they only host their own stuff.

**Comment by arkon** [comment]
cf. #8739
