### ISSUE TITLE
Dragonking

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8742]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Dragon King Scan 

### Source link

https://dragonkingscan.blogspot.com/

### Language

Spanish

**Comment by Clouddark75** [comment]
Blogspot sites hardly gets an extension, and the library is all over the place, so it won't worth the work making one, at least right now.

**Comment by Crallpro** [comment]
@Clouddark7 Sorry for the inconvenience but you can create an extension for Niadd as it contains many good manga please

**Comment by alessandrojean** [comment]
Closing, since it's a blogger site, and it doesn't have a proper structure.
