### ISSUE TITLE
Niadd

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8743]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Niadd

### Source link

https://www.niadd.com/

### Language

Spanish (Es) 

### Other details

It has a lot of manga that rivals TMO and NineManga and also translates the fastest manga and has a simple and simple theme, and I would appreciate it if you would do it please.

**Comment by jopejoe1** [comment]
Also has English, Italian, Russian, Portuguese, German and French content

**Comment by jopejoe1** [comment]
Looks like they have some self-hosted chapters and some externally hosted chapters
