### ISSUE TITLE
Pijamalı Koi

### ISSUE THREAD

**Issue by bcykn** [tachiyomiorg/tachiyomi-extensions#8745]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Pijamalı Koi

### Source link

https://pijamalikoi.com/m

### Language

Türkçe

### Other details

WPMangaStream

_No response_

**Comment by Clouddark75** [comment]
CMS theme.

**Comment by vetleledaal** [comment]
New URL: https://pijamalikoi.com/m/
Appears to use WPMangaStream or WPMangaReader
