### ISSUE TITLE
Adicionem o Mangá livre de novo!!!! :(

### ISSUE THREAD

**Issue by IGRISS16** [tachiyomiorg/tachiyomi-extensions#8746]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Mangá livre 

### Source link

https://www.google.com/url?sa=t&source=web&rct=j&url=https://mangalivre.net/&ved=2ahUKEwjepZr878TyAhV7rZUCHVtTBKwQFnoECAoQAg&usg=AOvVaw3mRK9uqTOdpBx_8K8qyOGS

### Language

Português 

### Other details

A fonte mangá livre foi removida do app tachiyomi!! Ela é  minha principal fonte de mangas, e pelo que eu pesquisei da maioria dos brasileiros!! Coloquem de volta por favor!!!

**Comment by alessandrojean** [comment]
Leia o #3475.

Ela não vai ser adicionada de volta porque os donos do site estão fazendo modificações constantes para quebrar a extensão e já deixaram bem claro que querem que as pessoas leiam somente no site deles. Migre para outras fontes e bola pra frente.

**Comment by joaojsrbr** [comment]
Eu tenho mais de 200 manga na extensão deles, recomenda eu migrar pra qual extensão?

**Comment by alessandrojean** [comment]
Nós não recomendamos nenhuma fonte. Isto se deve pelo motivo da base de usuários do Tachiyomi ser enorme e o ato de recomendar fontes só fez com que os sites fechassem no passado. Isto também levou fontes a bloquearem o Tachiyomi ou quebrar intencionalmente o funcionamento das extensões, pedindo para serem removidas do Tachiyomi, enchendo nossos repositórios de spam, ou ficando lentas e mais lentas até pararem de funcionar devido ao intenso tráfego com muitos usuários acessando.

Dito isto, instale algumas e teste para achar as que funcionam melhor para você. Recomendações só deixam a situação atual pior.
