### ISSUE TITLE
Manga-scantrad: No chapters found

### ISSUE THREAD

**Issue by Dekkii0** [tachiyomiorg/tachiyomi-extensions#8750]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Source information

Manga-scantrad 1.2.12

### Steps to reproduce

1.library update
2.Manga scantrad don't update

### Expected behavior

It should update

### Actual behavior

It don't

**Comment by alessandrojean** [comment]
To anyone who address the issue: it looks like they updated the Madara version and the variable to use the new chapter endpoint needs to be set to true.
