### ISSUE TITLE
Pedido para extensão 

### ISSUE THREAD

**Issue by Joao245909** [tachiyomiorg/tachiyomi-extensions#8751]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Mundo mangá kun

### Source link

https://mundomangakun.com.br/

### Language

Português brazil

**Comment by alessandrojean** [comment]
Leia o #3475. Esta extensão foi removida a pedido do scanlator e não será adicionada de volta.

Por favor, na próxima vez, preencha o nome do site no campo título ao invés de colocar "Pedido para extensão".
