### ISSUE TITLE
Cervo Scanlator - Rate Limiting

### ISSUE THREAD

**Issue by Getauscht** [tachiyomiorg/tachiyomi-extensions#8760]
### Describe why this should be added

**Hi I would like to request the removal of the rate limiting from my ''Cervo Scanlator' extension". As I spoke with developer Alessandro at Discord, I use external services for image delivery, and if necessary I have other servers of my own for image delivery and CDN, so removing this would not affect performance on any of the site and servers.
And I also talked to him about keeping Rate Limiting only at the domain level of the site, but it would still not be interesting because I have a Loabalacing. So, in summary, maintaining a usage rate cap is not interesting because it would affect the load for the user and the servers would still have 2-3 percent CPU usage. Making these practically unusable and no reason to keep them!

Getäuscht,
Owner of Cervo Scanlator**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Will be closed by #8764.

If you need the rate limit to get added back in the future, open a new issue :+1:.
