### ISSUE TITLE
Disaster Scans: not able to download chapters

### ISSUE THREAD

**Issue by Nathan-j-hardee** [tachiyomiorg/tachiyomi-extensions#8767]
### Source information

disaster scans 1.2.12

### Steps to reproduce

1. install disaster scans
2. add "martial peak" to library
3. download chapter 1177 (theres many others where it will not download anything at all ex. ch612)

### Expected behavior

downloads all 16 pages

### Actual behavior

downloads 10 then errors out. 

### Tachiyomi version

0.12.1

### Android version

Android 11

### Other details

this has been replicated across 3 different devices. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Silvermane06** [comment]
This is still an issue, except it seems to happen on myltiple chapters scatrered throughout, not only on martial peak, but also on other mangas as well from this extension. 

I have tested downloading the chapters via hakuneko, and it seems to download them fine, and viewing through webview with this extension will also let you read said chapters. It's only an issue with downloading via this extension specifically on said chapters.

**Comment by tyme2tb** [comment]
I have seen this before also. Although just starting yesterday I get timeouts just trying to check for updates from this extension, even though webview looks fine.
