### ISSUE TITLE
Webnovel.live http error 500....but webview working fine

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#8770]
### Source information

Webnovel (.live) 1.2.14

### Steps to reproduce

Install webnovel extensions 
View any manga chapter from webnovel source 

### Expected behavior

Images displayed

### Actual behavior

Http error 500

### Tachiyomi version

0.12.1

### Android version

ANDROID 11

### Other details

Cannot download also

Webview working fine.....so website is working fine

Tested on titles: Become the Castellan in Another World Comics and The Cultivator From The Future Comics

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Zatania** [comment]
I tested this using the steps you used with the same version. And all seems to work fine. Have you tried checking if it's your internet connection that is causing the problem? Sometimes with this kind of errors, it's the internet connection that is having some kind of weird connection with the site's server.

[image](https://imgur.com/a/O40M9SZ)

**Comment by Samk19** [comment]
Not working 
Can access the website with the webview option in tachiyomi so the internet connection and the site seems to work fine.

Let me try to remove cache and clear database and check....as this issue appeared after updating the extension

**Comment by Samk19** [comment]
OK so now it's working fine after clearing cache , cookie and database 
Then restaring the device
