### ISSUE TITLE
ManhuaZonghe

### ISSUE THREAD

**Issue by fufukioka** [tachiyomiorg/tachiyomi-extensions#8774]
### Source name

ManhuaZonghe

### Source link

https://manhuazonghe.com/

### Language

English and Chinese

### Other details

Has lots of manhua and manhwa, both translated to english and in raw 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
Madara theme.

**Comment by alekc** [comment]
Latest & Most popular not paginating properly (the selector is fine), most likely due to a structure of the site?

**Comment by kasperskier** [comment]
> We have removed all Chinese translation content. You can read manhwa, manhua the English translations.

So this becomes a single English source. @alessandrojean
