### ISSUE TITLE
Hitomi should have more languages

### ISSUE THREAD

**Issue by Nikolai0w0** [tachiyomiorg/tachiyomi-extensions#8776]
### Describe your suggested feature

It should have more languages like japanese korean and more. It only has english and spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
All the available languages that the site has are already supported by the extension. You can seen then on the extension configuration, select the language you're interested on, and enable those you have chosen in Tachi filter near the search button.
