### ISSUE TITLE
Gekkou Scans

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#8794]
### Source information

Gekkou Scans 1.2.6

### Steps to reproduce

Abrir a extensão Gekkou 
Falha:HTTP error 404
Open Gekkou extension
Erro HTTP 404

### Expected behavior

Abrir e aparecer os mangás dela
Open and display the mangas of the Open and show her mangas

### Actual behavior

Abrir e aparecer o Erro HTTP 404
Open and show HTTP Error 404

### Tachiyomi version

0.12.1

### Android version

Android 11

### Other details

O site está funcionando perfeitamente, e a scan falou que não tem nenhum envolvimento com o erroThe site is working perfectly, and the scan said it has no involvement with the error The site is working perfectly, and the scan said it has no involvement with the error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
O site deles está com alguns problemas de carregamento e as imagens não carregam via `https`, somente via `http`.

Estou esperando que eles arrumem esse problema para atualizar a extensão, pois não é seguro ficar usando `http`.

Leia o #8678.
