### ISSUE TITLE
LHTranslation from fmreader to madara

### ISSUE THREAD

**Issue by SaruDesu** [tachiyomiorg/tachiyomi-extensions#8795]
### Describe why this should be added

LHTranslation.net changed theme from fmreader to madara.
![image](https://user-images.githubusercontent.com/51081028/130541175-7f541c84-3f35-4cad-a0c7-0bf4e709969c.png)

### Other details

Details from gochyu.com
![image](https://user-images.githubusercontent.com/51081028/130541257-42f34b71-d10c-4f70-a10e-ddb224d069c6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Their change is temporary. So #8727 will be more appropriate
