### ISSUE TITLE
Mangasushi: No chapters found

### ISSUE THREAD

**Issue by SaruDesu** [tachiyomiorg/tachiyomi-extensions#8796]
### Source information

Mangasushi 1.2.12

### Steps to reproduce

Go to mangasushi source. Open any manga. 

### Expected behavior

Should list all available chapters. 

### Actual behavior

Shows "No chapters found" toast. 
![Screenshot_20210824-094113_Aniyomi](https://user-images.githubusercontent.com/51081028/130542700-1e8c5a12-73ba-49f5-a6e0-554260c208e1.png)

### Tachiyomi version

0.12.1

### Android version

Android 11

### Other details

Even if chapters are not found, list of available manga as well as their respective thumbnail loads. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Arraiment** [comment]
Now uses new xhrChapterRequest, might also need to open webview before loading manga details.
