### ISSUE TITLE
Leviatan Scans throws no chapters found

### ISSUE THREAD

**Issue by yorozuyaginchan** [tachiyomiorg/tachiyomi-extensions#8797]
### Source information

Leviatan Scans - 1.2.17

### Steps to reproduce

Open any manga in Leviatan scans extension and refresh. It shows no chapters found. 

### Expected behavior

Chapters should show in the extension. 

### Actual behavior

Getting message "No chapters found" and no chapters are shown. 

### Tachiyomi version

0.12.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Arraiment** [comment]
They now use the new xhrChaptersRequest
