### ISSUE TITLE
Some extensions don't work

### ISSUE THREAD

**Issue by Dome2005** [tachiyomiorg/tachiyomi-extensions#8804]
### Source information

TuMangaOnline 1.2.34 and LectorManga 1.2.17

### Steps to reproduce

1. I try to read a manga
2. The chapter don't charge
3. Always appear a button to retry

### Expected behavior

It should charge the chapters as usually.

### Actual behavior

Actually it always appear a retry button and I tried everythin to fix it but i think it's not only my problem. Also Lectormanga was working right until today ):

### Tachiyomi version

0.12.1

### Android version

8.0.0

### Other details

I already tried all the advices to fix my problem but nothing worked

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Volcanianis** [comment]
I have the same problem, i thought it was because I was using an older version of tachiyomi (0.10) so i upgraded to the newest one but the problem is still happening, as you said Lectormanga was working fine until today and Tumangaonline has been broken since Sunday, I think this is because both sites went into maintenance recently and maybe something changed in their code, let's hope someone is able to fix this, because this two extensions are by far the best ones in terms of number of serieses available in Spanish :(

**Comment by SoraSpace769** [comment]
I also have the same problem. TuMangaOnline and LectorManga stopped working. Last night the latter was working just fine :(. I have the 0.12.1 version of the app.

**Comment by paulo27ms** [comment]
Check if TuMangaOnline works now. If LectorManga still doesn't, open another issue for it.

**Comment by abhijeetChawla** [comment]
LectorManga still doesn't work

**Comment by SoraSpace769** [comment]
> Check if TuMangaOnline works now. If LectorManga still doesn't, open another issue for it.

I tested some mangas and TuMangaOnline now works for me, but LectorManga still doesn't work for the same mangas tested early.

In case do you need, I tested Steel Ball Run and Chuuko demo Koi ha Shitai.

**Comment by Volcanianis** [comment]
> Check if TuMangaOnline works now. If LectorManga still doesn't, open another issue for it.
Yeah Tumangaonline seem to be working properly again, I tested with Chainsaw man, Dorohedoro, Bakemonogatari, Berserk, Blame! and Dimension W. Lectormanga on the other hand is still broken so i suppose it's better to create another thread.

**Comment by Volcanianis** [comment]
> Check if TuMangaOnline works now. If LectorManga still doesn't, open another issue for it.



Yeah Tumangaonline seem to be working properly again, I tested with Chainsaw man, Dorohedoro, Bakemonogatari, Berserk, Blame! and Dimension W. Lectormanga on the other hand is still broken so i suppose it's better to create another thread.

**Comment by CarlosEsco** [comment]
open a different ticket for lector, and next time 1 source per ticket
