### ISSUE TITLE
TuMangaOnline isn't showing the images in the chapters

### ISSUE THREAD

**Issue by Kaydnn** [tachiyomiorg/tachiyomi-extensions#8820]
### Source information

 TuMangaOnline 1.2.34

### Steps to reproduce

Just seach a manga, open a charapter and the images doesn't load.

### Expected behavior

Load the images of any manga, manhwa, etc.

### Actual behavior

Doesn't load the images of any manga, manhwa, etc.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

I asked a friend and happends the same to him.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
#8804
