### ISSUE TITLE
Add light novel support 

### ISSUE THREAD

**Issue by royal78** [tachiyomiorg/tachiyomi-extensions#8825]
### Describe your suggested feature

Add Light novel source then we can read light novel . 

### Other details

🆕🎉🎊

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://tachiyomi.org/help/faq/#can-tachiyomi-read-light-novels

**Comment by arkon** [comment]
No?
