### ISSUE TITLE
Error 404 Gekkou Scans

### ISSUE THREAD

**Issue by 2wlsousa** [tachiyomiorg/tachiyomi-extensions#8827]
### Source information

Gekkou Scans  1.2.6

### Steps to reproduce

1 Open the extension

### Expected behavior

Work Fine

### Actual behavior

Http Error 404

### Tachiyomi version

12.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read #8794.
