### ISSUE TITLE
Broken MyReadingManga chapters

### ISSUE THREAD

**Issue by PHandlerC** [tachiyomiorg/tachiyomi-extensions#8830]
### Source information

MyReadingManga 1.2.43

### Steps to reproduce

1. Open MyReadingManga extension
2. Select chapter from mangas.

### Expected behavior

Chapter pages are shown to the user

### Actual behavior

"Error cat" gif from MyReadingManga is shown instead of the actual pages.

### Tachiyomi version

Stable 0.12.1

### Android version

Android 8.1.0

### Other details

This problems seems random, but much more frequent ever since the 403 access errors from 1.2.42, as I had downgraded to 1.2.41 and never encountered these errors, until i updated to 1.2.43. Some manga start showing the gif at random pages, and subsequent chapters only display the gif. When you choose another manga, they work absolutely fine, but the one that errored stays like that, even after clearing the cache and cookies. Today's example stopped working at page 17, and all other chapters displayed the same.
![Screenshot_20210825-051057](https://user-images.githubusercontent.com/8846339/130756230-011352ce-af88-4417-b4f6-c08e5bbd1cab.png)
![Screenshot_20210825-051104](https://user-images.githubusercontent.com/8846339/130756352-b62ffdce-6517-46ed-9820-58bc9fe58c8d.png)
![Screenshot_20210825-051114](https://user-images.githubusercontent.com/8846339/130756366-8a5d116f-954e-4c5e-9db1-d2458610197d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by akmalmeaw** [comment]
Same here... its totally bug
