### ISSUE TITLE
I can't download from TuMangaOnline

### ISSUE THREAD

**Issue by Byakko92** [tachiyomiorg/tachiyomi-extensions#8832]
### Source information

TuMangaOnline 1.2.34

### Steps to reproduce

Add to queue a chapter of the site

### Expected behavior

Start the download

### Actual behavior

I see the number complete of pages of the chapter but never starts the download

### Tachiyomi version

Stable v0.12.1

### Android version

Android 11

### Other details

It does not load me online in the app, work in the webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Check after https://github.com/tachiyomiorg/tachiyomi-extensions/pull/8831 is merged.

**Comment by abhijeetChawla** [comment]
It's resolved
