### ISSUE TITLE
Kissmanga.in: Thumbnails are not loading after opening a manga

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi-extensions#8835]
### Source information

Kissmanga.in 1.2.13

### Steps to reproduce

Open any manga from the extension.

### Expected behavior

Thumbnail should load.

### Actual behavior

Thumbnails are not loading. 

### Tachiyomi version

0.12.1

### Android version

10

### Other details

Thumbnails are loading if manga is not opened from the extension. But after opening a manga, thumbnails are not loading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tanuukii** [comment]
+ Troubleshooting doesn't help.

**Comment by topazrn** [comment]
It works now. Thanks!
