### ISSUE TITLE
Manhuarock.net

### ISSUE THREAD

**Issue by haruki-takeshi** [tachiyomiorg/tachiyomi-extensions#8856]
### Source name

manhuarock

### Source link

https://manhuarock.net

### Language

Vietnamese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses FMReader

**Comment by haruki-takeshi** [comment]
> Uses FMReader

I can't find on extension group.

**Comment by haruki-takeshi** [comment]
I can't find extension yet.

**Comment by vetleledaal** [comment]
FMReader is just the theme it uses. Someone still needs to implement it
