### ISSUE TITLE
Mangas.in

### ISSUE THREAD

**Issue by Ginto-sama** [tachiyomiorg/tachiyomi-extensions#8863]
### Source name

Mangas.in

### Source link

https://mangas.in/

### Language

Español

### Other details

En esta fuente se puede encontrar diversidad de manwhas, los cuales están más avanzados en términos de capitulos que en otras páginas, tales como; "TMO", "Lectores de manga",  "dragontranslation" etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
The extension is already available, but the site don't want it to get fixed, they keep breaking it with a couple hours after the fix. So it's the cat and mouse game...

This ticket can be closed.

**Comment by curche** [comment]
> So it's the cat and mouse game

@Clouddark75 considering removing the extension so as to avoid further issues which won't be resolved anyways
