### ISSUE TITLE
Hentaifox : Chapter images do not load 

### ISSUE THREAD

**Issue by Okaklaaaa** [tachiyomiorg/tachiyomi-extensions#8870]
### Source information

Hentaifox 1.2.2

### Steps to reproduce

1. Choose a manga
2. Open a chapter

### Expected behavior

Loaded Chapter Pages

### Actual behavior

Chapter pages not working. Just says "Retry"

### Tachiyomi version

0.11.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hullmat998** [comment]
Came to see if a ticket had been opened yet.  I noticed that titles can be viewed on the website directly just fine when you click "open in WebView" just with typical amount of pop-up and redirect ads.
