### ISSUE TITLE
Mangadex : Alternative Name

### ISSUE THREAD

**Issue by myth-riel** [tachiyomiorg/tachiyomi-extensions#8872]
### Describe your suggested feature

![image](https://user-images.githubusercontent.com/12084129/131131113-b5a4be75-4097-4d6c-b6ae-6bde1f9462a0.png)
Please add this feature to this extension. Thank you for the hard work 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FlaminSarge** [comment]
(I believe MD has mostly standardized their name usage and will be opening a PR for this when I can instead of a new issue).
