### ISSUE TITLE
MangaStein Extension doesn't work

### ISSUE THREAD

**Issue by himuraaa** [tachiyomiorg/tachiyomi-extensions#8874]
### Source information

MangaStein 1.2.12

### Steps to reproduce

Search MangaStein
Open it and wait
it won't Open

### Expected behavior

The Manga's would have load up 

### Actual behavior

Error message "no results found" 

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

If you try to open the Webview it opens but after 5 seconds url turns to tr.asurascans.com, and the Mangastein.com url doesnt exist more, the new url is tr.asurascans.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by himuraaa** [comment]
> #8354

how is this gonna help me @kiriya-aoi

**Comment by paulo27ms** [comment]
Unfortunately not being able to read is terminal.
