### ISSUE TITLE
MangaDex: Chapters Uploaded by Comikey return No Pages found

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi-extensions#8877]
### Source information

1.2.129

### Steps to reproduce

Find a manga with a Comikey chapter
Open it

### Expected behavior

The chapter should be able to be opened, or if it's a redirect to another site, the chapter should be hidden

### Actual behavior

The chapter returns no pages found

### Tachiyomi version

0.12.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Ignore chapters with "data":[],"dataSaver":[] meaning it has no pages.
There are chapters with externalUrl but they still have pages in the API that the app can use so that's not the best thing to check.
