### ISSUE TITLE
Mangalivre [PT-BR]

### ISSUE THREAD

**Issue by noraky** [tachiyomiorg/tachiyomi-extensions#8879]
### Source information

Mangalivre extension isn't working

### Steps to reproduce

1.Install "mangalivre" extension
2.Select a manga and a chapter
3.A failure occurs.

### Expected behavior

The chapter should work normally.

### Actual behavior

But the app insists on failing in any chapter.

### Tachiyomi version

0.12.1

### Android version

Android 8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> As extensões Mangá Livre e Leitor.net foram removidas por conta dos responsáveis do site estarem fazendo modificações intencionais para quebrar o funcionamento das extensões. Migre os mangás destas fontes em sua biblioteca para outras extensões caso queira continuar lendo.
