### ISSUE TITLE
Make TCB scans pull chapters from the home page like catmanga

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#8885]
### Describe why this should be added

they have caching issues so if they upload a new chapter it will not be seen in tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Arraiment** [comment]
The newest version of the tcbscans ext uses your system's current time to set new chapter dates every time the chapter list updates, so tachiyomi should already update you if a new chapter is released. Is this feature not working for you?

**Comment by FireNation323** [comment]
> The newest version of the tcbscans ext uses your system's current time to set new chapter dates every time the chapter list updates, so tachiyomi should already update you if a new chapter is released. Is this feature not working for you?

Sorry if I was clear enough. There was a jjk chapter that came out and it wasn't appearing in Tachiyomi because it wasn't in the chapter list on the website, but it was on the home page as a latest release, so I think it's better if it pulls chapters from the home page.

**Comment by Seishirou101** [comment]
As with your conversation in #8284. There are issues either way, just wait for the chapter to appear in the chapter list.
