### ISSUE TITLE
Mangasail: Only few manga show in Latest

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi-extensions#8891]
### Source information

Mangasail 1.2.2

### Steps to reproduce

Install the Mangasail extension and click Latest

### Expected behavior

More manga will appear that can be seen on site.

### Actual behavior

Only few manga appear. I think the next button is not recognize.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

Please also add filters that can be found here 
https://www.mangasail.co/tagclouds/chunk/1 TYSM♥️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tanuukii** [comment]
This is also happening when searching. If I search "after", there should be more manga to appear like from the site.

**Comment by Arraiment** [comment]
The extension displays latest manga from the front page at [https://www.mangasail.co](https://www.mangasail.co). While there are more manga provided in [https://www.mangasail.co/latest_list](https://www.mangasail.co/latest_list), they link directly to the chapters, so it would be difficult to scrape compared to the shorter list currently used.

**Comment by Arraiment** [comment]
I'll still add filters though.
