### ISSUE TITLE
Azora Manga website update

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#8899]
### Source name

Azora Manga

### Source link

https://azoraworld.com

### Language

Aerobic

### Other details

I hope to update as soon as possible 🥺

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
The site is under updates wait until the updates are finished

**Comment by hani1998** [comment]
يسلموا اخي احمد جمال

**Comment by hani1998** [comment]
ok thanks 🌹
