### ISSUE TITLE
Mangayaro

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#8907]
### Source name

Mangayaro

### Source link

https://mangayaro.com/

### Language

Indonesia

### Other details

![image](https://user-images.githubusercontent.com/40079068/131436703-6ec2bf85-dd01-4803-98a8-1db91792fc6b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
WP MangaReader theme.

**Comment by hostkit** [comment]
Any update?
