### ISSUE TITLE
MangaBuddy

### ISSUE THREAD

**Issue by Jvlier** [tachiyomiorg/tachiyomi-extensions#8908]
### Source name

MangaBuddy

### Source link

https://mangabuddy.com/

### Language

English

### Other details

![IMG_20210831_084635](https://user-images.githubusercontent.com/84441821/131463857-4bcba1da-7b43-457f-82ca-1f0b5c056afb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by joyceedesu** [comment]
Thank tou for requesting it🙏❤️

**Comment by Arekkusu1998** [comment]
Thank you for requesting it from me too🙏❤️

**Comment by rafalohaki** [comment]
does it use any theme from multisrc?

**Comment by vetleledaal** [comment]
Doesn't look like it's using an existing theme, but you should include MangaMad if you make one #9010

**Comment by rafalohaki** [comment]
here, i tried but couldnt figure out api requests
api: https://mangabuddy.com/api/manga/search?
files (images and template to edit) 
src/en/mangabuddy: https://drive.google.com/drive/folders/11vqmZ0h2-eu3pEgBxPd6B5HrWaHh_Lhx?usp=sharing
