### ISSUE TITLE
Mangadex doesn't show Spanish (Latin america) results when searching manga

### ISSUE THREAD

**Issue by lranixonl** [tachiyomiorg/tachiyomi-extensions#8911]
### Source information

1.2.130

### Steps to reproduce

1. Go to browse
2. Search any manga

### Expected behavior

It should search in all the languajes enabled

### Actual behavior

It search in Spanish (Spain) and English but no in Spanish (Latin america).
![photo_2021-08-31_12-28-44](https://user-images.githubusercontent.com/18472171/131531444-14cd14f0-2035-4932-9643-c476177de867.jpg)

### Tachiyomi version

1.12.1

### Android version

Android 11 (LineageOS 18.1)

### Other details

Spanish (Latin america) is enabled in MangaDex extension settings
![photo_2021-08-31_12-30-14](https://user-images.githubusercontent.com/18472171/131531673-17172190-0263-4b0c-93c6-bf7543464dcf.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Seems fine to me
![Screenshot_20210831-114303_Tachiyomi.jpg](https://user-images.githubusercontent.com/2092019/131533815-a064b3ce-319e-4292-8a1c-c8970cd6c826.jpg)

**Comment by lranixonl** [comment]
For me it doesn't show

![photo_2021-08-31_13-05-26](https://user-images.githubusercontent.com/18472171/131537515-edab9b2d-9660-414f-8c24-d19f59387f5d.jpg)
![photo_2021-08-31_13-05-28](https://user-images.githubusercontent.com/18472171/131537519-bc30a142-b00e-45f9-af11-d3cb547bcef4.jpg)

This is the config, but i don't think that there is a problem here

![photo_2021-08-31_13-05-41](https://user-images.githubusercontent.com/18472171/131538016-c5742aa2-71b0-4721-8022-5fbda9c235c8.jpg)


Also disabled all the other languages from all the extensions excep for Spanish Latinamerica in MangaDex and doesn't show it

![photo_2021-08-31_13-05-44](https://user-images.githubusercontent.com/18472171/131537923-34631b5d-1a98-498c-822a-04d27c710577.jpg)

**Comment by CarlosEsco** [comment]
In that last screen shot. Can you click the languages at top and make sure latin american Spanish in enabled

**Comment by lranixonl** [comment]
> In that last screen shot. Can you click the languages at top and make sure latin american Spanish in enabled

Oh, that was, sorry for the problems.
