### ISSUE TITLE
Manhwa Time

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#8912]
### Source name

Manhwa Time

### Source link

https://manhwatime.com

### Language

Aerobic

### Other details

Wonderful wonderful wonderful site I hope you add as soon as possible 😘

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
Madara theme.

**Comment by hani1998** [comment]
Why Madara theme

**Comment by Clouddark75** [comment]
> Why Madara theme?

Is the theme reader that the site uses. You can see it as an note for the person who may work on the source. So don't worry.

**Comment by hani1998** [comment]
شكراً لك اخي
thanks brother
