### ISSUE TITLE
Reaper Scans Obsolete

### ISSUE THREAD

**Issue by mrehanabbasi** [tachiyomiorg/tachiyomi-extensions#8916]
### Source information

Reaper Scans 1.2.12

### Steps to reproduce

1. Go to Browse.
2. Go to Extensions tab.

### Expected behavior

Reaper Scans extension should behave normally.

### Actual behavior

There is obsolete written on the extension.
![Screenshot_20210901-062453_Tachiyomi](https://user-images.githubusercontent.com/19202888/131597103-5af0b971-74f5-4330-b50f-d152a40df20c.jpg)

Moreover, it has a new version which only supports Portuguese website and not the English one.
Both extensions refer to different websites.
1.2.12 refers to [reaperscans.com](https://reaperscans.com) 
1.2.13 refers to [reaperscans.com.br](https://reaperscans.com.br) 

### Tachiyomi version

Preview r3756

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It has both.

**Comment by mrehanabbasi** [comment]
But it does not show up for me in Sources under English or All.

**Comment by alessandrojean** [comment]
You need to uninstall the old one with only English and install the new one under the all section. An app restart could help too.

**Comment by mrehanabbasi** [comment]
I even restarted my phone but it still isn't showing. And yes, I did uninstall the old one.
