### ISSUE TITLE
Manga18Fx: HTTP error 404

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#8918]
### Source information

Manga18Fx 1.2.12

### Steps to reproduce

browse using manga10fx extension or use search,  showing error 404 but is working fine in web view

### Expected behavior

should show error 404

### Actual behavior

should show manga

### Tachiyomi version

0.12.1

### Android version

Android 7 and android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Flwk** [comment]
Hello

I see that the extension isn't working and that there is no news

Do someone know if it can be fixed ?

Thank you very much for all of your work ☺️ !

**Comment by DioSensei** [comment]
Same issue

**Comment by Flwk** [comment]
Hello

Any news ? 

Thanks

**Comment by alessandrojean** [comment]
No ETA. It will get fixed when/if someone wants to work on it.

**Comment by z8512** [comment]
Please someone work on it 🤗

**Comment by AriaMoradi** [comment]
fixed in #13118
