### ISSUE TITLE
CommitStrip: newest manga (2021) is broken

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi-extensions#8923]
### Source information

CommitStrip 1.2.2

### Steps to reproduce

1. Install [CommitStrip](https://tachiyomi.org/extensions/#all.commitstrip). Use either `en` or `fr`
2. From Browse, open `Commit Strip (2021)`
3. Wait for it to load

### Expected behavior

Loads the chapter list and view webcomics released in 2021

### Actual behavior

![Screenshot_20210901-170039_Tachiyomi_why](https://user-images.githubusercontent.com/72807749/131664289-541f2eb9-3d65-407f-ac50-92e866c9c193.png)

### Tachiyomi version

0.12.1

### Android version

Android 11 (LOS)

### Other details

Attempted a fix that would have been added in #8922 but didn't work
Basically happens because of the following:
```kotlin
override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> {
        // create a new call to parse the no of pages in the site
        // example responseString - Page 1 of 11
        val responseString = client.newCall(GET("${manga.url}", headers)).execute().run {
            asJsoup().select(".wp-pagenavi .pages").first().text()
        }
        // use regex to get the last number (i.e. 11 above)
        val pages = Regex("\\d+").findAll(responseString).last().value.toInt()
        return (1..pages).map {
            val response = chapterListRequest(manga, it)
            chapterListParse(response)
        }.let { Observable.just(it.flatten()) }
    }
```

on a quick look, [CommitStrip (2021)](https://www.commitstrip.com/en/2021/) doesn't have any pages so the selector fails and cannot proceed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
I didn't test it but this should work.

```kotlin
override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> {
    // create a new call to parse the no of pages in the site
    val pages = client.newCall(GET("${manga.url}", headers)).execute().run {
        asJsoup().select(".wp-pagenavi .page").last()?.text()?.toInt() ?: 1
    }
    return Observable.just(
        (1..pages).flatMap {
            chapterListParse(chapterListRequest(manga, it))
        }
    )
}
```

**Comment by curche** [comment]
Oh Thanks, but that doesn't always work I think. For example, using it on [2014](https://www.commitstrip.com/en/2014/), the last element is 10, while the total pages is 11

I was able to fix the ext by an elvis operator, close to what you suggested (altho when I did tried that before Android Studio was complaining :thinking: ; probably something dumb from my side). It works fine now :success:
