### ISSUE TITLE
CopyManga extension not working

### ISSUE THREAD

**Issue by Hezj** [tachiyomiorg/tachiyomi-extensions#8934]
### Source information

CopyManga 1.2.11

### Steps to reproduce

Refresh the gallery, browse or read chapters from CopyManga source

### Expected behavior

Works normally.

### Actual behavior

Only search function works. When opening any chapter I get "page not found" toast and when refreshing it's "Attempt to invoke ….Element.attr(java.lang.String) on a null object".
I've tried changing my IP, clearing cookies and clearing data/reinstall but nothing helped. Though WebView works properly.

### Tachiyomi version

Stable 0.12.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Punizione** [comment]
The website changed that:

1. chapter list encrypted string from 

> _comic/{manga_path_word}_ 

were move to a new endpoint, and this endpoint do not return _updateTime_ now

> _comicdetail/{manga_path_word}/chapters_ 

2. manga pages image encrypt data and key from manga-page change: 
`val disposableData = document.select("div.disposableData").first().attr("disposable")`
`val disposablePass = document.select("div.disposablePass").first().attr("disposable")`
change to
`val disposableData = document.select("div.disData").first().attr("contentKey")`
`val disposablePass = document.select("div.disPass").first().attr("contentKey")`

I'm not good at kotlin so please help to fix this.

**Comment by SnowArk** [comment]
I've already fixed this issue. The website update the way get the chapter list and the namespace of encrypted data and key in the image detail page. PR created and wait for approval!
