### ISSUE TITLE
1st kiss: HTTP Error 400 in Browse

### ISSUE THREAD

**Issue by Tearz1** [tachiyomiorg/tachiyomi-extensions#8939]
### Source information

1stkiss 1.2.16

### Steps to reproduce

![Screenshot_20210902-222418_Tachiyomi](https://user-images.githubusercontent.com/89990511/131866935-049ddb0b-1088-4f26-a60f-4b745ff14ef8.jpg)

### Expected behavior

Opened normally and showed the mangas.

### Actual behavior

Http 400 error is being shown

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

Http 400 error cant be seen from any other help provider

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Search works fine and manga and chapter load fine too
Browse is broken

**Comment by curche** [comment]
/edit-title 1st kiss: HTTP Error 400 in Browse

**Comment by curche** [comment]
/edit-title "1st kiss: HTTP Error 400 in Browse"

**Comment by shinzi14** [comment]
The extension is showing HTTPS 400 error but I still can read the manhwas from the 1st kiss but the covers turn black:(

**Comment by ptoump** [comment]
1stkissmanga changed domain name. From .com to .io 
Along with that change there may give been other changes too.

**Comment by akshar2324** [comment]
> Search works fine and manga and chapter load fine too
> Browse is broken

hello i am new here i am having same problem did you find solution??

**Comment by akshar2324** [comment]
did anyone find solution my all manga are ni this extension so please hurry 😭

**Comment by akshar2324** [comment]
how to use solution. will tachiyomi provide update for it??

**Comment by akshar2324** [comment]
thanks thank you very much tachiyomi is best i love it and issue is solved very quickly 🙏🙏🙏

**Comment by shinzi14** [comment]
THANK YOU FOR FIXING IT SO QUICKLY!👏👏🙏
