### ISSUE TITLE
Gekkou Scans: Changed the site theme back to MMRCMS

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi-extensions#8941]
### Source information

Gekkou Scans 1.2.11

### Steps to reproduce

Entrar na extensão Gekkou Scans

### Expected behavior

Entrar e aparecer os mangás

### Actual behavior

Entrar e não aparecer nada

### Tachiyomi version

0.12.1

### Android version

Android 11

### Other details

Provavelmente está ocorrendo esse erro porque a Gekkou arrumaram o site deles para o normal, e no Tachiyomi voltou a não funcionar

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Gekkou Scans: Changed the site theme back to MMRCMS"

**Comment by Retashe** [comment]
😔
