### ISSUE TITLE
cover missing

### ISSUE THREAD

**Issue by anothernewone** [tachiyomiorg/tachiyomi-extensions#8942]
### Source information

Manganato, 1st Kiss, Manhua Plus, 

### Steps to reproduce

![WhatsApp Image 2021-09-03 at 09 28 02](https://user-images.githubusercontent.com/84385137/131936855-59d6c755-693c-4d7f-b6c6-67e8e5ca7230.jpeg)
- My library does not show cover for any manhwa, manhua from 1st Kiss, Manganato and Manhua Plus extension.
- updating still works just the cover is not shown.

### Expected behavior

The cover should be shown when I open the app, but it show blank cover.

### Actual behavior

- Blank cover were shown instead of the comic actual cover.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
1 source problem per ticket, please.
