### ISSUE TITLE
MangaDex Extension Search Broken

### ISSUE THREAD

**Issue by DishankJ** [tachiyomiorg/tachiyomi-extensions#8945]
### Source information

MangaDex 1.2.130

### Steps to reproduce

1. Search a manga in the MD source
2. You can see irrelevant results appear on any title you search

### Expected behavior

Titles similar to the search term should appear

### Actual behavior

Irrelevant or random titles appear on search instead

### Tachiyomi version

0.12.1-3756

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
This is more related to MangaDex API and we have zero control over it.

**Comment by BraveDude8** [comment]
Posting for historical reference; search is now unfucked.
