### ISSUE TITLE
Genkan: No results found when opening via URL Intent

### ISSUE THREAD

**Issue by caramrlkiw** [tachiyomiorg/tachiyomi-extensions#8953]
### Source information

Genkan 1.2.3

### Steps to reproduce

usually i just click links from update notification and open it with tachiyomi
![IMG_20210903_230735](https://user-images.githubusercontent.com/90056628/132035870-a88b9b73-2b5b-4e6f-927d-cf96f023adf4.jpg)

### Expected behavior

showing the series

### Actual behavior

not showing the series
![IMG_20210903_230745](https://user-images.githubusercontent.com/90056628/132035913-ee2af6b6-04d8-4dd5-a9c5-be1341efbdb8.jpg)

### Tachiyomi version

0.12.1

### Android version

android 10

### Other details

i tried to search manually too and still the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Genkan: No results found when opening via URL Intent"

**Comment by caramrlkiw** [comment]
> /edit-title "Genkan: No results found when opening via URL Intent"

strangely it only for 18+ books, sfw books are fine

**Comment by stevenyomi** [comment]
Removed in #15016.
