### ISSUE TITLE
Komiku.id removal request

### ISSUE THREAD

**Issue by kontakid** [tachiyomiorg/tachiyomi-extensions#8971]
### Describe why this should be added

hallo, i'm the owner from komiku.id, i want to request for remove the extension for komiku.id website, because we already have the official app for the website, thanks for your attention.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
Gave me proof of ownership in Discord DMs.

**Comment by arkon** [comment]
Removal requests only apply for scanlator sites that don't re-host other groups' contents. Please let us know if that isn't actually the case.
