### ISSUE TITLE
Argos Scan: Changed URL

### ISSUE THREAD

**Issue by yToddyn** [tachiyomiorg/tachiyomi-extensions#8976]
### Source information

Argos scan - 1.2.14

### Steps to reproduce

Argos Scan changed its domain and made a new website with the domain: https://megamanga.com.br/

 So I would like you to remove the Argos Scan extension and create the new MegaManga flame

### Expected behavior

Change Argos Scan Extension to Mega Manga

### Actual behavior

New Argos website

### Tachiyomi version

0.12.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing since the website still exists and it should be a Source Request issue since it's a different website.
