### ISSUE TITLE
Mangas.in

### ISSUE THREAD

**Issue by Dairon15** [tachiyomiorg/tachiyomi-extensions#8978]
### Source name

Mangas.in

### Source link

https://mangas.in

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
it already exists. it's listed under its other name

**Comment by Clouddark75** [comment]
The extension is already available but it will get removed from Tachi. Stop making new ticket from previous ones. 

This ticket can be closed.
