### ISSUE TITLE
No funciona bien mangas.pw

### ISSUE THREAD

**Issue by Sagenav0** [tachiyomiorg/tachiyomi-extensions#8984]
### Source information

Mangas.pw 1.2.4

### Steps to reproduce

Quiero entrar a leer y no aparecen los capítulos del manga o otros, aparece algo que no esta relacionado con lo que quiero leer

### Expected behavior

Que aparescan los capítulos del manga, manhua etc

### Actual behavior

Aparece solo un capitulo que no es del manga

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

El unico capítulo que aparece es solo un capitulo de un hentai en vez de los capítulos del manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Crallpro** [comment]
@Sagenav0 este problema es frecuente la extensión manga.pw a quedado obsoleta ya que siempre que lo arreglan se vuelve a romper es un problema que no se va a poder solucionar

**Comment by Urulokke** [comment]
Y ya hicieron lo de este comentario? https://github.com/tachiyomiorg/tachiyomi-extensions/commit/1882705bd4067397dc568b553f8c55925e5461d0#diff-6ccdfd91fce7cb7ed4c98808d05223cef4e30ada45623f1bb2f5b0833a17f2b3

**Comment by alessandrojean** [comment]
Duplicate of #7970
