### ISSUE TITLE
Read One Piece Manga Online: Ad in the middle of the chapter

### ISSUE THREAD

**Issue by iam-Ameena** [tachiyomiorg/tachiyomi-extensions#8988]
### Source information

Read One Piece Manga Online Version 1.2.2

### Steps to reproduce

1. Open Read One Piece Manga Online Source/Extension
2. Open One Piece colored manga
3. Open any chapters
4. Scroll down, you should see an ad as manga page,

### Expected behavior

There should be no ad,

### Actual behavior

There's ad in manga as a manga page

### Tachiyomi version

TachiyomiJ2K version 1.2.1

### Android version

Android 11

### Other details

The ad is specifically mentioned as an ad in the website and not as an manga page, it's the same ad on every chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Read One Piece Manga Online: Ad in the middle of the chapter"
