### ISSUE TITLE
Read Adult: All but 3 most recent chapters show No Pages Found

### ISSUE THREAD

**Issue by OmfgItsJesus** [tachiyomiorg/tachiyomi-extensions#8989]
### Source information

Read Adult 1.2.11

### Steps to reproduce

Manga Cover Load and description but when you go to load chapters its not found  mostly 99.90% say "No pages found" only ones that load are like the last 3 most recent chapters not orders ones.

### Expected behavior

All chapters should load fine when u click to open it instead it saying no pages found.

### Actual behavior

Manga Cover Load and description but when you go to load chapters its not found  mostly 99.90% say "No pages found" only ones that load are like the last 3 most recent chapters not orders ones.

### Tachiyomi version

TachiyomiSY Preview r405 

### Android version

Android 10

### Other details

Already been like this for a month thought it was just me but seems it is not on extension side the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
/edit-title "Read Adult: All but 3 most recent chapters show No Pages Found"
