### ISSUE TITLE
MangaDex: add setting to load first cover instead of last

### ISSUE THREAD

**Issue by qgustavor** [tachiyomiorg/tachiyomi-extensions#8992]
### Describe your suggested feature

MangaDex hosts multiple covers for each manga, [like this](https://mangadex.org/title/65263bf9-4f87-4513-b72f-ad6436b3911c/wotaku-ni-koi-wa-muzukashii?tab=art). The API that handles this [is documented here](https://api.mangadex.org/docs.html#operation/get-cover).

By adding a setting that allows loading the first cover it avoid the issue of someone starting some manga gets spoiled when the latest cover includes some plot point that's introduced later in the manga (as some simple examples, some characters marrying or the resolution of some love triangle).

### Other details

[One of the latest changes](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/8268/files) to the MangaDex extension added a quality setting, which was a +48 -8 lines change. I imagine adding a setting to load the first cover would have similar complexity in terms of implementing the interface, in the other hand the API interactions would be more complex as currently covers are loaded by using manga relationships, which, [as the documentation states](https://api.mangadex.org/docs.html#section/Static-data/Relationship-types), only returns the primary cover (by default, the last one).

I don't know Kotlin, but I think that loading an additional endpoint, the `/cover` endpoint, adds an additional complexity that could be avoided, even considering that it accepts batches of up to 100 manga. One way to make it simpler would be a `first_cover_art` relationship, which I already suggested to MangaDex staff (still awaiting a response). If this relationship gets implemented by MangaDex in their API implementing this the cover setting would be quite easier as the setting would only change which relationship would be requested.

As I'm a J2K user I changed covers using its custom covers feature to point to the first cover (automatically, crating a backup, editing and importing it back). Because it works on the backup file it only changes manga already added, even so I found that it was a good change so I can start manga that I already planned without the cover revealing future plot points.

I don't know if there are other people that would like this feature. If you think this idea is too complex or if it would be useful just for too few people I'm fine if it's rejected. I know that developing an open-source project is not easy and this repository already have a lot of open issues. I can try implementing it myself in a fork by using the existing code and the changes from the the pull request above as reference in case this feature gets well accepted but gets delayed because contributors need to work on more important issues.

By the way, all points marked below because it's required, but I use TachiJ2K 1.2.1, MangaDex extension 1.2.130. The application should not be an issue as the extension is expected to work in the same way in the fork.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Not adding a setting that hits the cover end point to load the first cover.  It will just make everything way slower.   When you browse on the manga list you are adding 20+ more api calls to get all the covers.  If you remember correctly a few months ago how slow loading covers was. That is why. It was before they had the includes.  If dex adds a first cover option in includes feel free to open a new ticket.

**Comment by qgustavor** [comment]
As I mentioned you can batch queries, so there is no need for "20+ more api calls", just use batches. That being said I know batching stuff is complicated to implement.

Seems this suggestion got accepted as long it can easily implemented without requiring additional requests. I will wait for Mangadex staff response and, if they implement it, I will open other issue (or is it better to leave another comment on this one?).
