### ISSUE TITLE
Unparseable date in Webtoon 

### ISSUE THREAD

**Issue by LNP8095** [tachiyomiorg/tachiyomi-extensions#9000]
### Source information

Webtoons.com 1.2.31

### Steps to reproduce

Update library or manually refresh a webtoon; try to view a webtoon's info

### Expected behavior

Webtoon should update/should show chapters if not in library

### Actual behavior

Webtoons in library don't update, with Unparseable date: ""  error. Webtoons not in library don't show chapters

### Tachiyomi version

J2k 1.2.1

### Android version

Android 10

### Other details

![Screenshot_20210907_135659_com android chrome](https://user-images.githubusercontent.com/81875709/132340643-f106c057-1561-4fb8-9b3d-3b130f2303ef.jpg)
![Screenshot_20210907_135651_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/81875709/132340651-72e1ecbd-757e-4b2f-9fd5-c5d2e3a4b01a.jpg)

First screenshot is about webtoons in library with the update error; second is for the webtoons not in library 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raineedust** [comment]
Haha what a coincidence, I was also trying to open "Unholy Blood".

**Comment by Edge-0** [comment]
Seems to be happening to any of them, just try to load any you have never seen before
