### ISSUE TITLE
MangaOn

### ISSUE THREAD

**Issue by Kirito-Senpai9** [tachiyomiorg/tachiyomi-extensions#9008]
### Source name

Manga Online

### Source link

https://mangaon.site/

### Language

Português

### Other details

O saite MangaOn ou manga online é um dos mais visitados saites de mangá em Português pt-br também possui uma grande variedade de mangás e novel é uma ótima opção para ser uma fonte para o Tachiyome.

MangaOn site or online manga is one of the most visited manga sites in Portuguese pt-br it also has a wide variety of manga and novel is a great option to be a source for Tachiyome. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read #8765. The site is broken, and the chapters are not showing. 

An extension can't be made for broken sites.
