### ISSUE TITLE
Mangakakalot.tv

### ISSUE THREAD

**Issue by ImperialRandal** [tachiyomiorg/tachiyomi-extensions#9009]
### Source name

Mangakakalot ( probably not official one )

### Source link

https://ww.mangakakalot.tv/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
what's the difference between this and the original one? and there is already an unofficial version too
