### ISSUE TITLE
Mangasee stuck in webview 

### ISSUE THREAD

**Issue by fam007e** [tachiyomiorg/tachiyomi-extensions#9015]
### Source information

Mangasee v1.2.26

### Steps to reproduce

Opening the mangasee extension shows open in webview instruction. 

### Expected behavior

The site will open in webview after cloudfare verification. And starting inside app extension browse module will start working. 

### Actual behavior

It gets stuck in webview cloudfare verification and keeps loading. Doesn't open the site in webview. 

### Tachiyomi version

Tachiyomi v8.6.5-AZ

### Android version

Android 5.1.1

### Other details

I have the latest Webview app installed from Google Play Store.
I have tried both enabling and disabling the experimental feature of Captcha verification in webview.
In chrome the site opens without any problem. Only webview from inside tachiyomi app is causing the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
What's your webview version exactly?

**Comment by fam007e** [comment]
> What's your webview version exactly?

v93.0.4577.62

**Comment by Seishirou101** [comment]
don't think that's related to mangasee. probably something that has to do with az if its out of date. you can ask in the channel or on his github
