### ISSUE TITLE
jmana loads random pages

### ISSUE THREAD

**Issue by handy-cap** [tachiyomiorg/tachiyomi-extensions#9023]
### Source information

JMana 1.2.12

### Steps to reproduce

1. open any manga from manga list (for example: 하야테처럼!)
2. open any chapter from chapter list(chapter 1)
3. check its pages

### Expected behavior

only pages from the chosen chapter of the chosen manga should appear
(right number of pages in total for 하야테처럼 ch.1 is 32)

### Actual behavior

sometimes random pages from different manga are found in random locations of the chapter
all pages from original chapter are still present
(page count is higher than 32 in this case)

### Tachiyomi version

0.12.1

### Android version

Android 11 

### Other details

opening and closing any chapter a few times, you can observe the page count changing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
fixed in latest release
