### ISSUE TITLE
Jinmantiantang Data source error

### ISSUE THREAD

**Issue by ShiliangMi** [tachiyomiorg/tachiyomi-extensions#9025]
### Source information

Jinmantiantang 1.2.15

### Steps to reproduce

1.Click on the comic data source and enter
2.Waiting for refresh

### Expected behavior

Refresh and display the comic list normally

### Actual behavior

1.Unable to refresh and display comic list
2.The page returns the error message "Restricted Access!" when using the Web link

### Tachiyomi version

0.12.1

### Android version

Android 11

### Other details

I try to open it in Chorme directly using the data source link and return the same error message

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by in-out** [comment]
try to use proxy except japan

**Comment by ShiliangMi** [comment]
> 尝试使用日本以外的代理

Okay

**Comment by alessandrojean** [comment]
Is the issue solved?

**Comment by ShiliangMi** [comment]
> 问题解决了吗？

已经解决了，我这边的代理临时更换了线路造成的，确实是代理地区的问题
