### ISSUE TITLE
Mangadex lastest only showing Bilibili Comics

### ISSUE THREAD

**Issue by Candiam** [tachiyomiorg/tachiyomi-extensions#9029]
### Source information

Mangadex 1.2.131

### Steps to reproduce

1. go to sources
2. Select "Latest" on Mangadex 

### Expected behavior

it should show all the latest chapters added in MD

### Actual behavior

Only list chapters added from Bilibili Comics Group

### Tachiyomi version

0.12.1

### Android version

10

### Other details

If i go to the mangadex extensions setting and check "Japanese" or "Korean" when i go to the latest i dont get any results.
If i open MD on web view i can see every chapter added
I already uninstalled the extensions, clear cache/cockies
![Latest](https://user-images.githubusercontent.com/13791985/132931671-904c3ca1-f1bb-49d3-8246-bced39e9623a.jpg)

![Webview](https://user-images.githubusercontent.com/13791985/132931674-bae7465a-939d-4f83-9817-c26a8aecc3df.jpg)

![Settings](https://user-images.githubusercontent.com/13791985/132931687-cb00d149-5b61-45f7-a628-aeacd0d40916.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Neko014** [comment]
I thought i was the only one, if you toggle only japanese or korean origins the latest list shows up blank it only show up  Chinese comics for some reason

**Comment by loocool2** [comment]
This is because BilliBilli is absolutely spamming uploads so the entire latest page is empty, changing the request to filter when you request manga in latest instead of filtering after you get the results will fix it
