### ISSUE TITLE
about nyahentai plugins

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#9031]
### Describe your suggested feature

nyahentai, nyahentai.club,nyahentai.co,nyahentai
.fun nyahentai.me...all of nyahentai series plugins are just different domain names of the same website, why not integrate all the plugins into one like MangaRaw?It's weird.

### Other details

![Screenshot_2021-09-11-12-00-21-876_eu kanade tachiyomi](https://user-images.githubusercontent.com/46775615/132935630-bf23306f-1f2a-4f5a-a50b-8a58450b36c6.jpg)
![Screenshot_2021-09-11-12-02-58-948_eu kanade tachiyomi](https://user-images.githubusercontent.com/46775615/132935699-f3ad3677-df2c-47cd-b6b6-40b7263afd13.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Multisource extensions got split a while ago, so now an extension of a theme have only one source inside it to be easier to people find the extension.
