### ISSUE TITLE
MangaSee: HTTP Error 403

### ISSUE THREAD

**Issue by VanMeyer** [tachiyomiorg/tachiyomi-extensions#9042]
### Source information

MangaSee

### Steps to reproduce

1. Casually reading some mangas
2. Few chapters later, error 403 came
3. Went ahead and followed instructions to fix
4. Took some time 
5. Managed to get fixed
6. Few minutes later, the error came again

### Expected behavior

1. Casually reading some mangas
2. Few chapters later, error 403 came
3. Went ahead and followed instructions to fix
4. Took some time 
5. Managed to get fixed
6. Should be smoothly reading 

### Actual behavior

1. Casually reading some mangas
2. Few chapters later, error 403 came
3. Went ahead and followed instructions to fix
4. Took some time 
5. Managed to get fixed
6. Few minutes later, the error came again
7. Thus, I repeatedly go to browser mode every time the error occurs

### Tachiyomi version

0.12.1

### Android version

MIUI Global 12.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
are you getting the issue often still? Mangasee has the option to block us during high congestion time which is usually what http 403 means with nepnep sources.

**Comment by Seishirou101** [comment]
closing as no answer from op
