### ISSUE TITLE
Fuente

### ISSUE THREAD

**Issue by MoiDRT** [tachiyomiorg/tachiyomi-extensions#9051]
### Source name

Mangas.in

### Source link

https://mangas.in/

### Language

Español

### Other details

En esta fuente se encuentran muchos mangas no disponibles en las demás fuentes de la aplicación.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
It's already available as "Mangas.pw" on the extension, but it will get removed from Tachi, the owners don't want the site here. So stop requesting it when you have already searched for previous tickets.

This can be closed.
