### ISSUE TITLE
[tachidesk] "onlineFetch=True" cause timeout

### ISSUE THREAD

**Issue by hasanpasha** [tachiyomiorg/tachiyomi-extensions#9052]
### Source information

tachidesk

### Steps to reproduce

open any manga and it doesn't load the chapters and show timeout error

How To Solve:
The problem solved when I set "onlineFetch=False".. Maybe you can add an option to turn on and off it 

### Expected behavior

It should load the chapters 

### Actual behavior

Show timeout error

### Tachiyomi version

0.12.1

### Android version

android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaMoradi** [comment]
This is a Tachidesk related issue, open another issue at https://github.com/Suwayomi/Tachidesk-Server/issues/new/choose
