### ISSUE TITLE
Mangapark v3: HTTP ERROR 404

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi-extensions#9054]
### Source information

Mangapark v3 1.2.8

### Steps to reproduce

Just browse on the extension and select any manga you want.

### Expected behavior

It should load fine without any error, and chapters should be there too.

### Actual behavior

HTTP ERROR 404

### Tachiyomi version

r3799

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vncrack** [comment]
Webview is fine but reload chapter for new updates in app get HTTP ERROR 404

**Comment by kevin01523** [comment]
Yeah 404 not found for chapter list i guess maybe they changed the class or js etc

**Comment by FourTOne5** [comment]
The chapter endpoint was changed. I'll open a PR soon.
