### ISSUE TITLE
Error 403-Lector Manga/Tumangaonline

### ISSUE THREAD

**Issue by GoblinReader** [tachiyomiorg/tachiyomi-extensions#9056]
### Source information

TMO: 1.2.36    Lector Manga:  1.2.21

### Steps to reproduce

Example: 
1.the cap of the two extensions cannot be downloaded 
2.Webview and Captcha do not work 
3.the chapters are not updated, etc.

### Expected behavior

normal operation of the app

### Actual behavior

problems mentioned above

### Tachiyomi version

Tachiyomi version: 0.12.1 

### Android version

android:  10QP1A.190711.020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
The extensions are working as it should. Please, check yourself if you have problems with your connection, and try to clean your cookies and cache.

**Comment by KasukeLp23** [comment]
Both extensions working correctly, without any news

**Comment by GoblinReader** [comment]
Don't problem,thanks.

**Comment by Clouddark75** [comment]
> Don't problem,thanks.

Are they working for you?

**Comment by alessandrojean** [comment]
Closing since it appears to be solved.

Next time please open 1 ticket per source.
