### ISSUE TITLE
Mangadex update fail

### ISSUE THREAD

**Issue by satyricon-hu** [tachiyomiorg/tachiyomi-extensions#9059]
### Source information

Mangadex 

### Steps to reproduce

Update library 

### Expected behavior

Should update

### Actual behavior

! Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.extension.all.mangadex.dto.ChapterListDto', but it was missing
  # MangaDex (EN)
- manga list omitted 

### Tachiyomi version

App version: 0.12.1 (standard, 85791a9, 67, 2021-08-06T21:36Z) 

### Android version

Android version: 11 (SDK 30) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  I have updated all installed extensions.
Make sure you're running the latest MangaDex ext as this was fixed in newest update. You can get it from here as well: https://tachiyomi.org/extensions/#all.mangadex
