### ISSUE TITLE
Comikey: HTTP Error 403/Cloudflare

### ISSUE THREAD

**Issue by Canlethan** [tachiyomiorg/tachiyomi-extensions#9075]
### Source information

Comikey

### Steps to reproduce

Trying to read any chapter with the comikey extension gives back a 403 error. Webview works. 

### Expected behavior

Being able to read and download the chapter. 

### Actual behavior

Http error 403

### Tachiyomi version

0.12.2

### Android version

Android 10

### Other details

@lord-ne who wrote the extension. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GizmoTheGreen** [comment]
Got 403 on comikey too. Can't update chapters or read any chapters. WebView works fine and I'm logged in as well when i check it.

**Comment by alessandrojean** [comment]
They added Cloudflare protection to the website. Nothing much you can do besides waiting for them to lower the protection or migrating to other source.

**Comment by Alveel** [comment]
How does that work exactly? It works perfectly fine in Tachi's WebView, but in the reader I get an instant 403 every time. I never see anything Cloudflare related, like you sometimes see on other websites.

I only just got into some Comikey series, so it's sad to see this happening :(

**Comment by lord-ne** [comment]
They're blocking access to their website if you don't have JavaScript enabled (and an HTTP GET request does not run JavaScript). They're even blocking the API, which seems to defeat the purpose of an API if you ask me.

It probably is possible to bypass this within Tachiyomi, I assume that's what the `cloudflareClient` is for, but I don't know how to do it.

**Comment by alessandrojean** [comment]
> I assume that's what the `cloudflareClient` is for

This client only have an additional interceptor that tries to resolve the challenge Cloudflare provides in order to access the website, but it's outdated at the moment, and it does not work with the majority of sites.

If JavaScript is the check they're doing, it's probably by a cookie, `localStorage`, or they're checking the `X-Requested-With` header that JavaScript sets to `XMLHttpRequest` in AJAX.

A workaround would be using an WebView interceptor to do the requests.

**Comment by edgehub-cloud** [comment]
Would it getting a fix anytime soon?

**Comment by CrepeTF** [comment]
No ETA

Someone who wants to fix it will fix it, you'll just have to wait.
