### ISSUE TITLE
HentaiLib

### ISSUE THREAD

**Issue by zhoozhich** [tachiyomiorg/tachiyomi-extensions#9076]
### Source name

HentaiLib

### Source link

https://hentailib.me/

### Language

russian

### Other details

I have seen closed sources this source, but it is not in the list of extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by venom963** [comment]
> I have seen closed sources this source, but it is not in the list of extensions

I support, the topic is relevant
