### ISSUE TITLE
(MangaDex) Include latest chapters released on "Sort"

### ISSUE THREAD

**Issue by GauzeHades** [tachiyomiorg/tachiyomi-extensions#9079]
### Describe your suggested feature

I'd like to have a filter that sorts the manga by the latest chapters released for the language we have chose on MangaDex. I like to discover new séries by seeing if they are having releases or are basically dropped by scanlators groups.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
#9043 Adds this if I'm understanding correctly

**Comment by GauzeHades** [comment]
I do think you are right. Didn't found this when a looked for it. Thanks!

**Comment by CarlosEsco** [comment]
FYI their api doesnt support specific language when you sort.  So its going to sort by whatever language was uploaded.
