### ISSUE TITLE
"No pages found" bug - Cubari

### ISSUE THREAD

**Issue by Dangelman** [tachiyomiorg/tachiyomi-extensions#9084]
### Source information

Cubari 1.2.9

### Steps to reproduce

1. Add a Cubari manga to the library
2. Open a chapter (downloaded or not)

### Expected behavior

All available chapters from the Cubari manga website should be able to be opened in the reader too

### Actual behavior

Random chapters cannot be opened in the reader, whether they are downloaded or not.
Sometimes the chapters that cannot be opened change. More in Other Details.

Things I've tried: deleting chapters, re-adding the manga to the library, reinstalling the extension, clearing the database/cookies.

### Tachiyomi version

0.12.2

### Android version

Android 10

### Other details

One Punch Man manga: https://cubari.moe/read/gist/OPM/
Recording of the issue (beware of manga spoilers): https://i.imgur.com/ogYg2ND.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
can you show screenshot of the folder of the chapters in file manager that give no pages found

**Comment by Dangelman** [comment]
![Capture+_2021-09-16-14-29-47](https://user-images.githubusercontent.com/26676154/133612939-e9882c32-3f1d-4f6b-8f67-fc47f89de732.png)
I've now deleted and downloaded the chapters again, the reader seems to open them properly now.
What could have caused this?

**Comment by alessandrojean** [comment]
Google Drive has a view limit, so probably the chapter reached it and when this happens it presents a normal page instead of the proper image.

Closing this now.
