### ISSUE TITLE
[Source Request] Chrysanthemum Garden

### ISSUE THREAD

**Issue by vanessabluellie** [tachiyomiorg/tachiyomi-extensions#9086]
### Source name

Chrysanthemum Garden

### Source link

https://chrysanthemumgarden.com/

### Language

English

### Other details

This is a website for Web Novels. Although I'm uncertain if tachiyomi supports only words and not images in the app, please please consider this source! They're really quite big and offer many novels!! Thank you!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> Will Tachiyomi ever support Light Novels?
> No, Tachiyomi is designed as an image parser, not a text parser, so there will never be any support for Light Novels.
