### ISSUE TITLE
[Source Request] Novel Updates

### ISSUE THREAD

**Issue by vanessabluellie** [tachiyomiorg/tachiyomi-extensions#9087]
### Source name

Novel Updates

### Source link

https://www.novelupdates.com/

### Language

English

### Other details

This is absolutely the biggest website for Web Novels, Danmei Novels of all genres. Although I'm uncertain if tachiyomi supports only words and not images in the app, please please consider this source! They're really extremely big and offer the biggest collection of novels from all over!! Hope to see it on tachiyomi too!! Thank you!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
tachiyomi doesnt support novel
