### ISSUE TITLE
Sleepy translations: No chapters found

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi-extensions#9091]
### Source information

Sleepy translations 1.2.12

### Steps to reproduce

1. Open any entry from the sleepy translations extension
2. Refresh

### Expected behavior

Chapter list should show up

### Actual behavior

Chapter list does not show up

### Tachiyomi version

0.12.2-3812

### Android version

Android 11

### Other details

The website works from webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KaoticOblivion** [comment]
I haven't seen any guidelines on seconding/endorsing an issue so sorry if you prefer no comments but I also have this issue and I'm on Tachiyomi version 0.12.3 and extension version 1.2.12

**Comment by curche** [comment]
Fixed by https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9948
If you are still facing issues, make sure to try [Troubleshooting steps](https://tachiyomi.org/help/guides/troubleshooting/) or ask for help at the #support channel in [Discord server](discord.gg/tachiyomi).
