### ISSUE TITLE
Mangadex extension: No chapters found

### ISSUE THREAD

**Issue by DerSocken** [tachiyomiorg/tachiyomi-extensions#9094]
### Source information

MangaDex 1.2.137

### Steps to reproduce

1. Install MangaDex extension
2. Open any Manga
3. No chapter found error

### Expected behavior

Chapters are shown in the app, since they are available on the website

### Actual behavior

No chapters found error in most cases (screenshots)
The only case any chapters (only the german ones) show up that I have found is in the first 2 screenshots

### Tachiyomi version

1.3.1

### Android version

Android 11, MIUI 12.5.3

### Other details

![Screenshot_2021-09-17-02-07-12-363_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/39536883/133704068-a1954b3d-fffa-4e1c-87fa-3dfaccfecddf.jpg)
![Screenshot_2021-09-17-02-07-30-038_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/39536883/133704073-4f7cb70e-6741-4d80-8833-bc83fd9d9e37.jpg)

![Screenshot_2021-09-17-02-07-58-430_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/39536883/133704078-62397ad1-142d-495b-8dd7-274962e11d28.jpg)
![IMG_20210917_020902](https://user-images.githubusercontent.com/39536883/133704081-86cf561c-f6e6-4228-88e4-cad0a070f4d9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The last example you provided don't have any chapter in German on the site, so it will not show under the German Mangadex inside the app. If you want to read the chapters in English, you need to browse through the Mangadex under English section in the app.
