### ISSUE TITLE
您好，請停止解析 CopyManga 並下架 tachiyomi-extensions 裡 copymanga 代碼

### ISSUE THREAD

**Issue by hotmanga** [tachiyomiorg/tachiyomi-extensions#9096]
### Source information

CopyManga.kt

### Steps to reproduce

您好，尊敬的 Tachiyomi 開發者。

我們無意中發現了 Tachiyomi 這款開源產品，覺得十分的優秀。裡面的代碼結構和編寫方式讓我們由衷的喜歡和羨慕。

但目前我們在閱讀源代碼時遭遇到一些情況，經受 CopyManga 的委託，特來與您方協商一下。

經過閱讀代碼我們發現，在您程序代碼 CopyManga.kt 中發現正在解析 CopyManga 的頁面和API接口，如

- /comics
- /api/v3/search/comic
- /comic/$comicPathWord/chapter/${chapter.getString("id")}
- /comic/${obj.getString("path_word")}

希望 Tachiyomi 方可以下架該功能並刪除這些代碼。講這些代碼共享開源出來之後，給 CopyManga 帶來了大量的工作阻礙。

我們發現 Tachiyomi 是有一款優秀的產品，有著十分廣泛的用戶，故大量用戶在頻繁訪問 CopyManga 時，也給服務器帶來了不小的影響。

我們十分喜歡和欣賞 Tachiyomi 這款產品，但還是希望您方可以下架該功能。

再次感謝。

### Expected behavior

希望可以下架該功能。

### Actual behavior

希望可以下架該功能。

### Tachiyomi version

Tachiyomi 0.12.2

### Android version

Tachiyomi 0.12.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It doesn't look like the website is for a scanlator nor an official one.

We'll add some aggressive rate limiting to help alleviate pressure.

**Comment by whghjyh** [comment]
> 它看起来不像网站是扫描器或官方的。
> 
> 我们将增加一些激进的利率限制，以帮助缓解压力。



> It doesn't look like the website is for a scanlator nor an official one.
> 
> We'll add some aggressive rate limiting to help alleviate pressure.

These websites are all built by collecting translation groups or official content.In fact, there are many such websites in China just like those in English.

**Comment by sunze1016** [comment]
> 看起来该网站既不是扫描仪也不是官方网站。
> 
> 我们将添加一些激进的速率限制以帮助减轻压力。

Will the plug-in of this website be updated in the future? A large number of users rely on this plug-in very much.
