### ISSUE TITLE
MangaReader

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi-extensions#9112]
### Source name

MangaReader

### Source link

https://mangareader.to/home

### Language

English

### Other details

Doesn't seem to use WordPress at all
Doesn't seem to be a mirror of the other mangareader sites
~~There doesn't seem to be a dedicated Latest updates page or a typical "browse" page, but there is a A-Z page~~ lol there is I just didn't look hard enough

They scramble the pages they serve
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
maybe
Latest: https://mangareader.to/latest-updated
Browse: https://mangareader.to/most-viewed

**Comment by objestik** [comment]
Has it been added yet?

**Comment by rayn000** [comment]
Why ⭐mangareader.to⭐ extension not added yet, even with so many requests? Is it because they couldn't reach out to the website owner or couldn't get the license.

**Comment by FourTOne5** [comment]
> Why ⭐mangareader.to⭐ extension not added yet, even with so many requests? Is it because they couldn't reach out to the website owner or couldn't get the license.

Every extension is made voluntarily by contributors by reverse engineering the site. We don't contact the site owner or get a license. For mangareader.to it's tricky to implement so no one bothered to add it when there is a shit ton of alternative extension already available.

**Comment by ObserverOfTime** [comment]
See #9325. If you guys want it so much, help me figure out their algorithm.

**Comment by rayn000** [comment]
> See #9325. If you guys want it so much, help me figure out their algorithm.

I wanted to know why it wasn't added yet. Since @FourTOne5 said that it a tricky one. I'm not going argue about. Also I'm not a developer.
