### ISSUE TITLE
CopyManga: Error Missing Argument

### ISSUE THREAD

**Issue by sunze1016** [tachiyomiorg/tachiyomi-extensions#9114]
### Source information

CopyManga 1.2.14

### Steps to reproduce

Can't open

### Expected behavior

Can't open

### Actual behavior

Can't open

### Tachiyomi version

0.12.2

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by History-exe** [comment]
Maybe this is the time to give up copymanga, let it become the past. I am tired to see hundreds of manga update failed. Copymanga has notice this extension, they will change the rule of web very often.
