### ISSUE TITLE
WNACG

### ISSUE THREAD

**Issue by tatular** [tachiyomiorg/tachiyomi-extensions#9115]
### Describe your suggested feature

Update extension.

### Other details

Please update extension for wnacg. Some of the mangas in the web are not searchable using Tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the issue report form instead.
