### ISSUE TITLE
Remove Ascient empire scan extension

### ISSUE THREAD

**Issue by llpro11** [tachiyomiorg/tachiyomi-extensions#9116]
### Describe why this should be added

Mucho gusto quería recomendar que se elimine la extensión ascient empire scan la cual es una extensión en español debido a que es obsoleta los creadores de la web la han cerrado hace meses así que esperara que se elimine para que no haya inconveniente con los nuevos usuarios 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the source request form instead.
