### ISSUE TITLE
GoldenMangás fails to bypass cloudflare

### ISSUE THREAD

**Issue by MomonSam** [tachiyomiorg/tachiyomi-extensions#9118]
### Source information

Golden Mangás 1.2.12

### Steps to reproduce

The extension does not load as it gives error 403 or fails to bypass cloudflare.

### Expected behavior

The extension does not load as it gives error 403 or fails to bypass cloudflare.

### Actual behavior

The extension does not load as it gives error 403 or fails to bypass cloudflare.

### Tachiyomi version

0.12.2

### Android version

Android 7.1

### Other details

The extension does not load as it gives error 403 or fails to bypass cloudflare.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They intensified their Cloudflare protection and there's nothing we can do in the extension to fix it. Wait for them lower the protection or migrate to other sources if you don't want to wait.
