### ISSUE TITLE
Mangahub

### ISSUE THREAD

**Issue by Psycho00001** [tachiyomiorg/tachiyomi-extensions#9119]
### Source information

Mangahub 1.2.9

### Steps to reproduce

1. Searching for manga
2. Reading a manga
3. Library cant be updated
4. Http error 520

### Expected behavior

Reading and searching a manga the contents should loaded
Updating my library will let me see new update

### Actual behavior

Cant load
Http error 520 

### Tachiyomi version

0.12.2

### Android version

Asus m1 max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
From the Discord server:

> MangaHub is currently facing issues. We dont know when or if it will be back. Wait patiently or use a different source.
