### ISSUE TITLE
Graze Scans: HTTP Error 400

### ISSUE THREAD

**Issue by DerSocken** [tachiyomiorg/tachiyomi-extensions#9122]
### Source information

Graze Scans 1.2.12

### Steps to reproduce

1. Open the Graze Scans source

### Expected behavior

Shows their manga

### Actual behavior

HTTP Error 400 

### Tachiyomi version

1.3.1

### Android version

Android 11

### Other details

Error:
![Screenshot_2021-09-18-20-58-09-425_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/39536883/133905776-571a34bc-7ce2-4326-9cf9-b3255e746a54.jpg)

Website:
![Screenshot_2021-09-18-20-58-22-147_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/39536883/133905777-f9dd9a3b-79dc-40b0-b25c-58ad6b4ca9aa.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate of #9037
