### ISSUE TITLE
GMANGA : No chapters Found

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#9125]
### Source information

"GMANGA 1.2.6"

### Steps to reproduce

1- Open GMANGA-EXTENSION
2- Open Manga

### Expected behavior

Manga chapters should appear

### Actual behavior

The manga chapters did not open, it was showing an error

### Tachiyomi version

0.12.2

### Android version

Android 10

### Other details

This is a picture of the problem

![Screenshot_20210919-064420](https://user-images.githubusercontent.com/89131255/133914921-b0f8d2b2-76e4-4430-9025-81b91f8ee044.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
It shows "503 error"
