### ISSUE TITLE
MangaparkV3: Chapters not showing

### ISSUE THREAD

**Issue by vncrack** [tachiyomiorg/tachiyomi-extensions#9129]
### Source information

"MangaParkV3 1.2.9"

### Steps to reproduce

1. Open a manga in app
2. Reload for new chapter update

### Expected behavior

"The manga updates new chapters"

### Actual behavior

"For input string:..."
![Screenshot_20210919-122114_Tachiyomi](https://user-images.githubusercontent.com/78357927/133916458-9df153de-43a1-44af-9d99-491b8fc82728.jpeg)

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

Webview works normally

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
MP Dev is rapidly changing site code so I'll suggest to wait until it's in a stable phase (basically wait for #9069 to be merged)
