### ISSUE TITLE
MangaOwl: Add server preference

### ISSUE THREAD

**Issue by Yaoiislife** [tachiyomiorg/tachiyomi-extensions#9138]
### Describe your suggested feature

Good Day/Afternoon/Evening

Hello,

I just wanted to add a feature on those extensions. Websites have their own server's like for example. Mangaowl, they have server's which is server 1 3 and 5 (depends on every Manga/Manhwa/Manhua) you can choose either of those server in case server's 1 chapter doesn't load, has missing chapter or image's missing. You can switch to another server, since the other server, doesn't load, doesn't have missing chapter or image's is not missing. 

Here is the screenshot with the highlighted part. 
3 screenshots that has different server's. I really do hope that it will be added since of the server's has broken chapters or images. So that, we can switch to another server to download or to read. 
![Screenshot_20210920_020128](https://user-images.githubusercontent.com/90814673/133937967-e22f4936-8131-4f9f-b011-6fb3cbbf1252.jpg)
![Screenshot_20210920_020137](https://user-images.githubusercontent.com/90814673/133937971-405f1b15-e483-46b3-813c-683911f8a0f7.jpg)
![Screenshot_20210920_020151](https://user-images.githubusercontent.com/90814673/133937974-60427b50-0112-46ed-b219-6e8655f0e675.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
MangaOwl is dead.
