### ISSUE TITLE
Can't update manga through library

### ISSUE THREAD

**Issue by Redlorna** [tachiyomiorg/tachiyomi-extensions#9139]
### Source information

Wakamics 1.2.11

### Steps to reproduce

I tired updating library and it shows "UPDATE FAILED" ,so I refresed it and viewed it in webpage and I can see it through there but when updating through library I can't. 

### Expected behavior

Normally it would update but now it shows error. 

### Actual behavior

When updating through library, it won't update (specially wakamics) and shows error, but individually when updated I have no issue with viewing. 

### Tachiyomi version

App version: 0.12.2 

### Android version

11

### Other details

![Screenshot_2021_0919_235905](https://user-images.githubusercontent.com/91028051/133938651-6450cd83-25e3-4bb6-b47c-659cdeeec460.jpg)
This is how it shows ☝ , 
![Screenshot_20210919_235913](https://user-images.githubusercontent.com/91028051/133938658-edad2684-70c9-4f1b-98ba-4cc2cb1eaad1.jpg)
When I click "show error" It sents me this☝

And this is one I can show that the source has no issues👇
![Screenshot_20210920_000121](https://user-images.githubusercontent.com/91028051/133938703-77a9f0e8-0bc1-47b5-868b-656f7ac8d30f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You have to show what error you're getting. The update errors screenshot you provided don't have anything.

If you're still facing this problem, try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) first, and if it still persists, open a new issue and fill out all inputs appropriately.
