### ISSUE TITLE
Nhentai blank page chapter blank errors

### ISSUE THREAD

**Issue by BTheBlood** [tachiyomiorg/tachiyomi-extensions#9140]
### Source information

Nhentai 1.2.29

### Steps to reproduce

1.open any doujin 
2.all blank
![Screenshot_20210920-044925](https://user-images.githubusercontent.com/91033720/133944378-ae317e56-5a5c-44e5-80d2-c78f2eab4519.png)

![Screenshot_20210920-044929](https://user-images.githubusercontent.com/91033720/133944380-85d33ff3-69e0-4e83-840f-ab80f516e7af.png)

![Screenshot_20210920-044933](https://user-images.githubusercontent.com/91033720/133944381-faf7859d-b9e8-4b37-a585-c383fc7f6a42.png)

### Expected behavior

Can read normal like e henta.

### Actual behavior

Blank

### Tachiyomi version

8.4.5.eh

### Android version

Android 6.0.1 sumsung galaxy j2 prime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Don't use Tachiyomi EH, it's deprecated. Use Stable with the Nhentai extension or use some updated fork that has this source built-in.
