### ISSUE TITLE
Hiperdex: No chapters found

### ISSUE THREAD

**Issue by Astrokinng** [tachiyomiorg/tachiyomi-extensions#9142]
### Source information

Hiperdex 1.2.15

### Steps to reproduce

1. Normal update the library
2. The hiperdex Extension shows not chapter found

### Expected behavior

There should be chapter in the particular manhwa

### Actual behavior

There are no chapter available for any comic or manhwa if u view thorough the specified instructions

### Tachiyomi version

App version: 0.12.2-3826 

### Android version

Android 11

### Other details

![Screenshot_20210920-062138](https://user-images.githubusercontent.com/89287848/133948764-403af909-8da2-49f5-a3d2-2e078308dd35.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by REDFLAME123** [comment]
Having the same problem with toonly
