### ISSUE TITLE
Error en la fuente Martial Manga y pedir su retiro

### ISSUE THREAD

**Issue by Marco-kun** [tachiyomiorg/tachiyomi-extensions#9144]
### Source information

Martial Manga

### Steps to reproduce

1. Retirar la fuente Martial Manga ya que dejó de funcionar y su URL dejo de existir ya que se cambió a uno nuevo el cual es https://olympusscanlation.com/
2. Una vez retirada la fuente (Martial Manga) de ser posible agregar la nueva fuente que antes era Martial Manga pero se convirtió en https://olympusscanlation.com/ 

### Expected behavior

1. Que la fuente se hubiera eliminado y cambiado por la actual ya que dejó su funcionamiento una vez cambiado su URL por https://olympusscanlation.com/ 

### Actual behavior

Una vez ingresada a la fuente marca un error y al ingresar por Webview continúa con un error en la página web

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

![Screenshot_2021-09-19-22-23-13-829_eu kanade tachiyomi](https://user-images.githubusercontent.com/85567345/133951131-fd4264de-1ecc-4beb-b04d-ac43859ad03d.jpg)
![Screenshot_2021-09-19-22-23-04-971_eu kanade tachiyomi](https://user-images.githubusercontent.com/85567345/133951133-a7dc2f4c-f07b-4d37-85b4-be7382376ef9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate of #8019
