### ISSUE TITLE
CarToonMad

### ISSUE THREAD

**Issue by jwstaceyOvO** [tachiyomiorg/tachiyomi-extensions#9145]
### Source name

CarToonMad

### Source link

https://www.cartoonmad.com/

### Language

Chinese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by whghjyh** [comment]
If you need Chinese manga websites, I think I may know a lot.But I'm not familiar with github, so I don't know how to submit it.

**Comment by jwstaceyOvO** [comment]
@whghjyh I usually use copymanga extension, but it has some problems in last several months. And it seems that the webmaster of copymanga don't like the copymanga extension in tachiyomi, I have to migrate my manga resource, so I'd like to see more Chinese extensions.

**Comment by whghjyh** [comment]
> If you need Chinese manga websites, I think I may know a lot.But I'm not familiar with github, so I don't know how to submit it.

    Me，too.Are you Chinese?We are also troubled by copymanga. Obviously, chinese extensions are scarce.xD
