### ISSUE TITLE
Tachidesk: JSON error

### ISSUE THREAD

**Issue by smarttommyau** [tachiyomiorg/tachiyomi-extensions#9148]
### Source information

tachidesk 1.2.3

### Steps to reproduce

1. open the tachidesk extension

### Expected behavior

it's should show the library

### Actual behavior

it show error message

### Tachiyomi version

0.12.2

### Android version

10

### Other details

![Screenshot_20210920_165647_eu kanade tachiyomi](https://user-images.githubusercontent.com/75346987/133978196-4e2d80f2-f11b-48c3-8e21-fca360fe3599.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
The Tachidesk extension now requires Tachidesk 0.5.0 and over. I believe you are running a version of Tachidesk under 0.5.0

**Comment by smarttommyau** [comment]
oh maybe i forgot to update
