### ISSUE TITLE
Bilibili Manga(Chinese)

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#9150]
### Source name

哔哩哔哩漫画

### Source link

https://manga.bilibili.com/

### Language

Chinese

### Other details

China's second largest digital comics site.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/search?q=bilibili

**Comment by CarlosEsco** [comment]
The check boxes are not just for show

**Comment by alessandrojean** [comment]
He is requesting the Chinese Bilibili website. 

The existing Bilibili extension have only the contents from the English website.

**Comment by CarlosEsco** [comment]
my mistake

**Comment by ZerOri** [comment]
3 months passed😥

**Comment by FourTOne5** [comment]
It'll be added when someone adds it.
