### ISSUE TITLE
Toonily Extension Issue

### ISSUE THREAD

**Issue by Allied-R** [tachiyomiorg/tachiyomi-extensions#9152]
### Source name

Toonily

### Source link

https://toonily.com/

### Language

English

### Other details

When trying to refresh to update manga chapters it gives a No chapters found but when I click web view it shows on the site that the chapters are there and when clicking on a chapter it loads fine just not in my library.  I've tried both extensions the one from the main extension and the obsolete Madera extension.  I've tried uninstalling it and reinstalling and the issue persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the Issue report form instead.
