### ISSUE TITLE
Set MangaDex default sort option to "Relevant manga"

### ISSUE THREAD

**Issue by Signum21** [tachiyomiorg/tachiyomi-extensions#9159]
### Describe your suggested feature

You can see just by searching popular manga like Naruto or Akira that "Number of follows" doesn't work, there's no way I'm gonna believe that all those manga before Naruto have more follower than it lol.
I don't know how "Relevant manga" works but the results order makes a lot more sense. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
You can change the sort when you search. Having relevant default makes no sense when you click into browse for first time cause what is it relevant too?
