### ISSUE TITLE
Hentaivn source cannot be searched and search in tag

### ISSUE THREAD

**Issue by trantinvan21087** [tachiyomiorg/tachiyomi-extensions#9164]
### Source information

Hentaivn

### Steps to reproduce

Search in HentaiVn source
or
Search globally

### Expected behavior

If search normally, then Hentaivn source will return something.

### Actual behavior

If search in Hentaivn Source, Hentaivn will say you need to open webview to search it.
If search globally, Hentaivn say it found nothing.

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Does it say something like this?
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/4c5f86ed6b946cd0f71daa5dc20d9ae29bce7861/src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt#L134

The intention was to say [Log in via WebView to enable search](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5781#issuecomment-777622255). If you think it's not clear enough, you can suggest a better translation.
