### ISSUE TITLE
Nhentai extension not find manga that still in nhentai.net

### ISSUE THREAD

**Issue by reygrey666** [tachiyomiorg/tachiyomi-extensions#9182]
### Source information

NHentai 1.2.29

### Steps to reproduce

1. Search based on particular title or tags section
2. No result found

### Expected behavior

It should find the manga that already uploaded on nhentai.net

### Actual behavior

It not found any manga

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MatchaSoba** [comment]
Cannot reproduce issue on extension version **1.3.34**, can you verify if this is still occurring on your end?

**Comment by curche** [comment]
Closing since there's been no response. If you face this issue again, feel free to open a new issue
