### ISSUE TITLE
Madaradex 18+ issue

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi-extensions#9183]
### Source information

Madaradex v1.2.11

### Steps to reproduce

1. Open madaradex from source
2. Select any 18+ manga
3. Open or download any chapter of that manga
Issue here:- Keeps getting "retry" while opening or download fails

### Expected behavior

The images of manga should be parsed or downloaded.

### Actual behavior

If try to open, shows "retry"
if try to download, download pauses automatically and doesn't even start.

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#9449
