### ISSUE TITLE
Earlymanga uses 2 websites causing failed to resolve domain

### ISSUE THREAD

**Issue by Sighyu** [tachiyomiorg/tachiyomi-extensions#9188]
### Source information

Earlymanga 1.2.16

### Steps to reproduce

1. Open earlymanga extension
2. Click random manga

### Expected behavior

Should load chapters of said manga

### Actual behavior

Error failed to resolve domain

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

When open in webview you get the following 

The web page at https://earlymanga.orghttps//earlymangarelease.com/manga/second-life-ranker could not be loaded because:
net::ERR_NAME_NOT_RESOLVED

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tanuukii** [comment]
@FourTOne5 Can you fix this? 😅 TYSM❤️

**Comment by FourTOne5** [comment]
> @FourTOne5 Can you fix this? 😅 TYSM❤️

Both site now redirects to https://earlym.org/ which is using MDv3 like theme. The extension will need a complete rewrite. I'll look into if I have time.
