### ISSUE TITLE
remove mangasusu

### ISSUE THREAD

**Issue by fajri411** [tachiyomiorg/tachiyomi-extensions#9192]
### Source name

mangasusu

### Source link

mangasusu.co.in

### Language

indonesia

### Other details

bro can you delete mangasusu.co.in from the tachiyomi app?
because I experienced a drastic decrease in visitors so I was on the verge of closing my website
or leave my ad on the tachiyomi application so that I can continue to earn income
this application makes me bankrupt because of the decrease in visitors

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
You need contact a mod from the Tachiyomi discord server and prove them that you own the site and it'll be removed.

**Comment by fajri411** [comment]
link discord bro, give me

**Comment by CarlosEsco** [comment]
it's on the main github page
