### ISSUE TITLE
Japscan.ws (Manga Extension)

### ISSUE THREAD

**Issue by Showzur** [tachiyomiorg/tachiyomi-extensions#9195]
### Source name

Japscan.ws

### Source link

https://www.japscan.ws/

### Language

French

### Other details

I checked if the extension existed on the application and there is an extension called japscan, but this one is a different site, so I added it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nzoba** [comment]
The japscan extension is exactly the same site/url, not a different one
