### ISSUE TITLE
CopyManga: BAD_ENCRYPT

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi-extensions#9197]
### Source information

CopyManga 1.2.16

### Steps to reproduce

1. Open any manga.
2. Slide down to refresh the chapter list.

### Expected behavior

Chapter list could be refresh without any problem.

### Actual behavior

`error: 1e000065: Cipher functions: OPENSSL_internal: BAD_DECRYPT`
Also happen in reading any chapters.

### Tachiyomi version

TachiJ2K 1.3.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AlphaAnother** [comment]
same error.
with android 11, tachiyomi 0.12.2, CopyManga 1.2.16.

**Comment by jwstaceyOvO** [comment]
I think maybe we should give up it and try something else, it will be easier for both users and contributors.
