### ISSUE TITLE
Custom Color Theme

### ISSUE THREAD

**Issue by Fernsehen** [tachiyomiorg/tachiyomi-extensions#9198]
### Describe your suggested feature

I think it would be a nice addition to let you customize colors inside the app instead of only choosing between presets, simple options like changing background color or most importantly change accent color.

Even letting you save your presets and sharing them like custom themes could be a good approach, but if that's too ambitious, just the functionality of changing colors easily in-app is more than enough. 

If that is still too much, having a strong yellow theme would be awesome. Thanks for reading!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
wrong repo and this is already requested
