### ISSUE TITLE
TuttoAnimeManga - No Chapters found, changed layout

### ISSUE THREAD

**Issue by sbarrusa** [tachiyomiorg/tachiyomi-extensions#9200]
### Source information

tuttoanimemanga 1.2.3

### Steps to reproduce

1. Open any entry from the sleepy translations extension
2. Refresh

### Expected behavior

Chapter list should show up

### Actual behavior

Chapter list does not show up

### Tachiyomi version

0.12.2-3812

### Android version

11

### Other details

Since two weeks the layout is in the same style as tachiyomi-it.gto-v1.2.4, which works perfectly on tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sbarrusa** [comment]
The layout is now in the same style as gto extension, is there no way to solve it?

**Comment by alessandrojean** [comment]
Wait until someone have free time and want to work on it, no ETA.

**Comment by sbarrusa** [comment]
sorry, it was not my intention, I was trying to give as much information as possible to be able to solve easily.
