### ISSUE TITLE
Please adding LINE Webtoon ID to ID Manhwa Extension

### ISSUE THREAD

**Issue by blackborn94** [tachiyomiorg/tachiyomi-extensions#9201]
### Source name

Webtoon ID

### Source link

https://m.webtoons.com/id/

### Language

INDONESIAN

### Other details

Please adding LINE Webtoon ID to ID Manhwa Extension. I suggest to adding this to extension because the current LINE Webtoon is just for LINE Webtoon manhwa that serialized in english. I cant search or choose any indonesian LINE webtoon there. Please i hope you consider my only wish. Thanks 🙏

ps : sorry if my english is bad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Webtoons extension already supports ID

![Screenshot_20210924-010949](https://user-images.githubusercontent.com/59261191/134569236-fa29ecef-8023-4c26-b0de-a7d97ae01c06.png)

**Comment by blackborn94** [comment]
> Webtoons extension already supports ID
> 
> ![Screenshot_20210924-010949](https://user-images.githubusercontent.com/59261191/134569236-fa29ecef-8023-4c26-b0de-a7d97ae01c06.png)

I have setting my webtoons extension like that, i changeit to Bahasa Indonesia but the results is i still cant find any indonesian line webtoon there. 😭

Or is my steps wrongs ?

**Comment by alessandrojean** [comment]
Check if the webtoon you're searching isn't present in the Webtoon Translations extension.

Maybe it is not an official translation.
