### ISSUE TITLE
Toonily: No Chapters Found

### ISSUE THREAD

**Issue by BreadGenie** [tachiyomiorg/tachiyomi-extensions#9208]
### Source information

Toonily 1.2.16

### Steps to reproduce

1. Open any Manhwa in Toonily
2. Refresh if viewed before

### Expected behavior

Chapters should be displayed as usual

### Actual behavior

No chapters found message is returned

### Tachiyomi version

0.12.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by brazor421** [comment]
Yep, I have the same issue.

**Comment by ibrahimturna1** [comment]
Same issue here

**Comment by Akazotik** [comment]
Same issue here

**Comment by abhijeetChawla** [comment]
Someone can close this Issue, it's working.

**Comment by BreadGenie** [comment]
Yep, It seems to be working fine now. Weird.
