### ISSUE TITLE
Error in the extension of MangaTeca.

### ISSUE THREAD

**Issue by BruninhoDark** [tachiyomiorg/tachiyomi-extensions#9212]
### Source information

MangaTeca 1.2.14

### Steps to reproduce

The manga do not carry in the extension.

### Expected behavior

The works should appear within the extension.

### Actual behavior

![Screenshot_20210924-081622](https://user-images.githubusercontent.com/89276508/134666553-558f4993-c08c-4736-a96d-f1e96f301ce2.png)

### Tachiyomi version

V1.3.1

### Android version

Android 9

### Other details

Extension does not carry the works, thus not appearing the mangas. 
![Screenshot_20210924-081622](https://user-images.githubusercontent.com/89276508/134666801-458279dd-f861-4d06-b5e0-0d8384036950.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They intensified the Cloudflare protection, nothing we can do to fix it. Wait for them lower the protection or migrate to other sources if you don't want to wait.
