### ISSUE TITLE
Mangadex: missing chapters

### ISSUE THREAD

**Issue by fieldhouse** [tachiyomiorg/tachiyomi-extensions#9215]
### Source information

Mangadex 1.2.138

### Steps to reproduce

Browse or add Idol Manager in Another World (that's the one I've checked on multiple devices)

Extension shows Chapters 28.1 and 29.2 as latest but in web view 28.2 and 29.1 both exist and Chapters up through 37.2 show as available (published to mangadex 6 days ago). 

### Expected behavior

Plugin chapter listing should match web site

### Actual behavior

Chapters are missing and show incorrect published date

### Tachiyomi version

TachiyomiJ2K 1.3.1 and tachiyomi 0.12.2

### Android version

Android 9 and 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Those are all bilibili uploads, use the bilibili extension to view them as they are official releases
