### ISSUE TITLE
Nhattruyen domain change

### ISSUE THREAD

**Issue by trantinvan21087** [tachiyomiorg/tachiyomi-extensions#9219]
### Source information

Nhattruyen

### Steps to reproduce

current Nhattruyen cannot be searched or viewed through webview 
Nhattruyen domain change to http://nhattruyenvip.com

### Expected behavior

Nhattruyen can be searched and accessed

### Actual behavior

Nhattruyen on webview isn't available , on tachiyomi cant search or migrate.

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Closed by #10770
