### ISSUE TITLE
ru.{readmanga , mintmanga} - There is no description at all in the description Manga

### ISSUE THREAD

**Issue by uap4** [tachiyomiorg/tachiyomi-extensions#9224]
### Source information

ru.readmanga 1.2.31 , ru.mintmanga 1.2.32

### Steps to reproduce

Обновить метаданные манги.  
Update Manga Metadata.  

### Expected behavior

В описании будет актуальное  описание.  
The description will contain an up-to-date description.

### Actual behavior

В описании совсем нет описания, а только рейтинг, голоса и альтернативые названия.  
There is no description at all in the description, only rating, votes and alternative names.

### Tachiyomi version

SY 1.7.0

### Android version

Android 8.1.0 (SDK 27) LineageOS 15.1

### Other details

Даже если описание было, то теперь оно пропадает после обновления метаданных.  
Even if there was a description, now it disappears after updating the metadata.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
@uap4 пиши лучше на [форум ](https://4pda.to/forum/index.php?showtopic=805780)или в телеграм [@Tachiyomi_RUS](https://t.me/Tachiyomi_RUS)
