### ISSUE TITLE
copymanga search "No results found"

### ISSUE THREAD

**Issue by MiyouQ** [tachiyomiorg/tachiyomi-extensions#9225]
### Source information

copymanga 1.2.18

### Steps to reproduce

1.browse->copymanga->search
2.any word
for example "lv2"

### Expected behavior

return search results
"從Lv2開始開掛的原勇者候補悠閑的異世界生活"

### Actual behavior

No results found

### Tachiyomi version

0.12.2

### Android version

android 10

### Other details

web search normal

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
try 1.2.19

**Comment by MiyouQ** [comment]
> try 1.2.19

the bug fixed

thank you
