### ISSUE TITLE
Doesnt show pages of webtoon on Tachiyomi

### ISSUE THREAD

**Issue by CuppieKoffie** [tachiyomiorg/tachiyomi-extensions#9227]
### Source information

LeviatanScans 1.2.18

### Steps to reproduce

1. Open "Don’t Get Me Wrong, I’m The Real Victim!"
2. Open a chapter

### Expected behavior

The chapter pages show up like on the webview

### Actual behavior

Only one page is there and it's not the webtoon
![Screenshot_20210925-084838_Tachiyomi](https://user-images.githubusercontent.com/91376271/134772252-f0ae127c-01e5-4eb0-8cbc-220ef1fc4d83.jpg)
![Screenshot_20210925-084848_Tachiyomi](https://user-images.githubusercontent.com/91376271/134772257-38100e55-d95b-4f86-af27-bd6c1c91d126.jpg)
![Screenshot_20210925-085045_Chrome](https://user-images.githubusercontent.com/91376271/134772261-632600cc-2c7d-43cb-9896-2b47f0184468.jpg)

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Those manga are from Bilibili Comics (check url in 3rd image) which their affiliate site put on their webpage (like Leviathan Scans, Twilight Scans) migrate to the Bilibili Comics extension for those manga and read from there.
