### ISSUE TITLE
YugenMangas HTTP 404

### ISSUE THREAD

**Issue by Asura0818** [tachiyomiorg/tachiyomi-extensions#9229]
### Source information

YugenMangas 1.2.11

### Steps to reproduce

1. Entrar a la fuente "YugenMangas"

### Expected behavior

Debería suceder que se muestren los Mangas de la esa fuente

### Actual behavior

Lo que sucedio en su lugar es que al abrir la fuente aparece el "Error 404"

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

La fuente "YugenMangas" cambio el diseño de su pagina, lo que ha provocado que al entrar a la extensión "YugenMangas" se produzca el "Error 404" por lo tanto, seria necesario actualizar la fuente para que coincida con el nuevo diseño de la Pagina Web

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Asura0818** [comment]
Aquí pueden usar la misma extensión de "Dragontranslation 1.2.14" esa página usa la misma plantilla web que "YugenMangas"

**Comment by KasukeLp23** [comment]
Migrarlo a Madara

**Comment by Seishirou101** [comment]
There was a recent update to the extension, can you see if the issue was fixed?

**Comment by Asura0818** [comment]
> There was a recent update to the extension, can you see if the issue was fixed?

Si, ya se soluciono el problema, muchas gracias. ☺
