### ISSUE TITLE
MangaJar: all chapter numbers set to 0

### ISSUE THREAD

**Issue by cronjobsasha** [tachiyomiorg/tachiyomi-extensions#9231]
### Steps to reproduce

1.  Track with either MAL on Anilist
2. Make sure "Update progress on Reading" is selected
3.  Add Berserk/Solo Levelling/My Perfect Girlfriend or any manga to the library
4. Make sure it's tracked
5. Read any new chapter 

### Expected behavior

- Expected chapter update automatically in MAL/Anilist
- Instead have to manually open the tracker from the app and update it.

### Actual behavior

* No update on MAL or Anilist - have to manually use the tracking chapter to update it.

### Tachiyomi version

0.12.2

### Android version

11

### Device

Samsung Ultra 21

### Other details

- All this used to work and not sure why it stopped working
- Tried to isolate problem with various things
- Switched from Anilist to MAL
- Re-installed app
- Re-install extensions
- Migrated manga from one tracker to another
- Cleared cookies
- Tried various random manga
- No matter what I do it never gets updated automatically
- Updating manually via app works so this is not a connection issue and I verified update chapter progress is selected.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Gotta parse this stuff 
![IMG_20210925_202534](https://user-images.githubusercontent.com/13546823/134783972-5298dc6a-4fc9-49f2-a55c-cf71d4d29310.jpg)
