### ISSUE TITLE
Mangapark v3: For input string: "Comic"

### ISSUE THREAD

**Issue by randw0** [tachiyomiorg/tachiyomi-extensions#9240]
### Source information

MangaPark v3 1.2.10

### Steps to reproduce

Open any manga

### Expected behavior

Gets a list of chapters

### Actual behavior

Immediatly fails with For Input String: "Comic". It fails fast enough that I suspect its not even making a request

### Tachiyomi version

0.12.2-3833

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by chandukiran13** [comment]
Exactly same behaviour for me as well the details given are the same too
