### ISSUE TITLE
MangaPark v3: The chapter contents are deleted

### ISSUE THREAD

**Issue by randw0** [tachiyomiorg/tachiyomi-extensions#9251]
### Source information

MangaPark v3 1.2.11

### Steps to reproduce

Open any manga
Start reading

### Expected behavior

Manga pages load

### Actual behavior

Gwt an error saying chapter contents are deleted. Checking the website shows that the chapter content exists

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

@FourTOne5 mentioning you as detailed in your last PR

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
I'll take a look
