### ISSUE TITLE
[Source Request] [French] Manga Plus by SHUEISHA

### ISSUE THREAD

**Issue by ThePlayse** [tachiyomiorg/tachiyomi-extensions#9252]
### Source name

Manga Plus by SHUEISHA FR

### Source link

https://mangaplus.shueisha.co.jp/updates

### Language

French

### Other details

Manga plus by SHUEISHA has just announced the release of the French version today in 8 mangas

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Will be closed by #9245.
