### ISSUE TITLE
CatManga: not working

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#9256]
### Source information

CatManga 1.2.4

### Steps to reproduce

Browse the extension.

### Expected behavior

It should work.

### Actual behavior

Not working.

### Tachiyomi version

0.12.2

### Android version

11

### Other details

The site has been updated to version 3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dyl-M** [comment]
To add more information than "it should work / not working":

Reading chapters with CatManga as source still works, however it is now impossible to navigate through extension's menu and to update series associated with CatManga.

**Comment by lasersPew** [comment]
This was the shot from Tachiyomi app. It just shows no error message.
![Screenshot_20210928-042015_Tachiyomi](https://user-images.githubusercontent.com/87552756/134979345-5b5acbe4-9a31-4501-892a-c49c0f710dd9.jpg)

Here's the list of the manga update's error message:

![Screenshot_20210928-041118_MiXplorer](https://user-images.githubusercontent.com/87552756/134979440-9c518bd6-defb-4353-8d96-dec07b40e843.jpg)

Here's the message for updates on my own series. The series in my library from catmanga is:

-  A Couple of Cuckoos
-  A Rare Marriage: How to Grill Our Love
- A Saint Joined My Party!
- Ase to Sekken
- Boy's Abyss
- Dog and Scum
- Doujima-kun Won't Be Disturbed
- Fire Force
- Getsuyoubi no Tawawa
- Goddess Café Terrace
- Gokushufudou: The Way of the House Husband
- Hanazono Twins
- I Don't Know if It's LOVE or MAGIC!
- I Shaved. Then I Brought a High School Girl Home.
- Kanojo mo Kanojo
- Kanojo, Hitomishirimasu
- Kanojo, Okarishimasu
- Kanojo, Okarishimasu - The Official Anthology
- Komi-san wa Komyushou Desu
- Matchmaking of the Amagami Household
- My Charms Are Wasted On Kuroiwa Medaka
- Ranger Reject
- Sakurai-san Wants to Be Noticed
- Senpai ga Uzai Kouhai no Hanashi
- Sono Bisque Doll wa Koi wo Suru
- Tonikaku Kawaii

Note: When I open series in my library and updated it, it shows "Unknown Error"

**Comment by krisu5** [comment]
Extension is broken because of 3.0 update. https://catmanga.org/about/updates

Possibly fixed with #9263, wait that or another PR to be merged.
