### ISSUE TITLE
Bato.to manga show "no description" 

### ISSUE THREAD

**Issue by LNP8095** [tachiyomiorg/tachiyomi-extensions#9261]
### Source information

Bato.to 1.2.14

### Steps to reproduce

View a manga's information

### Expected behavior

Description should appear

### Actual behavior

Just shows "no description" 

### Tachiyomi version

J2k 1.3.1

### Android version

Android 10

### Other details

![Screenshot_20210927_180036_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/81875709/134943887-803a1ea1-55eb-4c75-bbc5-49a08fcd2ca7.jpg)
![Screenshot_20210927_175208_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/81875709/134943900-5b92de28-9f82-4042-90fb-7cad18c25d82.jpg)

As per screenshot, every single title on batoto source show no description.
My guess is this is caused by the "show remaining x%", which is a new thing for the description on the site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vipzzx** [comment]
Also having the same issue
