### ISSUE TITLE
Year is showing 1970 for all manga in Manga Weebs

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#9267]
### Source information

Manga Weebs 1.2.16

### Steps to reproduce

1. Select Manga Weebs in sources
2. Select any manga
3. Year will be 1970

### Expected behavior

show the correct year

### Actual behavior

shows only 1970

### Tachiyomi version

j2k 1.3.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The website doesn't provide the year in all the dates, so the extension can't really guess it.
