### ISSUE TITLE
1stkissmanga.io maybe a fake aggregator for 1stkissmanga.love

### ISSUE THREAD

**Issue by molitar** [tachiyomiorg/tachiyomi-extensions#9268]
### Source information

1st Kiss 1.2.17

### Steps to reproduce

Many of the martial art manhwa I am following was missing on 1stkissmanga.io so I did a bit of more searching and found the URL 1stkissmanga.love and I was able to find all the latest releases including the manhwa that was missing that I had migrated.

It appears the .io maybe a fake aggregate and taking longer to populate from the 1stkissmanga.love.

### Expected behavior

Manhwa's should not be missing that are dated in the last day or two.

### Actual behavior

manhwa's were missing on .io but located on .love with uploads dated today.

### Tachiyomi version

Preview r408

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We're not responsible for outdated manga or missing chapters, complain with the websites instead.

**Comment by Clouddark75** [comment]
"io" It's their new domain (they have like fourth or so domain). There isn't much to say, isn't the first time 1stkiss does this. On their website, they move Mangas from "1stkiss Manga" to "1stkiss Manhua", simply migrate to the manhua one, there should be what you want.

**Comment by molitar** [comment]
I was told in Discord to report it here.. The believe is the .love is the true site and the other is a fake aggregator site that someone has put up and is imitating the .love site.

**Comment by paulo27ms** [comment]
You opened an issue for missing chapters instead of opening one for a new source/replace the other one, that's why this was closed.

**Comment by molitar** [comment]
Understand but actually it was missing entire manga's.. did a search and over like 18 was missing.  I see redirect goes to .io but really appears the primary site is .love and it was getting updated first.  We'll see how the syncing of there two sites actually go not sure why they did not just use both URLS for same site but they are definitely seperate.
