### ISSUE TITLE
MangaDex language selection wrong

### ISSUE THREAD

**Issue by steveacab** [tachiyomiorg/tachiyomi-extensions#9269]
### Source information

MangaDex 1.2.139

### Steps to reproduce

Install
Check the language 
Not showing the selected language

### Expected behavior

Italian phone here. After installing the extension go in options and select the preferred language. Deselect all the others. Still stuck with Italian instead of the selected English version.

### Actual behavior

In the options I checked only English translation, but still stick with Italian. I tried to remove and reinstall, clean the cache, download from GitHub but nothing change. 
In the options now I have only English, but still see only Italian translations. 

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by steveacab** [comment]
Additional info

![Screenshot_20210928-132131](https://user-images.githubusercontent.com/4009959/135077576-40e79636-942e-461c-a3e7-fe43012a90b4.jpg)
![Screenshot_20210928-132142](https://user-images.githubusercontent.com/4009959/135077582-7c992677-8b74-48c0-b43d-10b2d4fad70b.jpg)
![Screenshot_20210928-132146](https://user-images.githubusercontent.com/4009959/135077588-ccdb1b3f-629e-4b36-8e07-bce78be4dbc4.jpg)

**Comment by Seishirou101** [comment]
you have to use the mangadex en extension. Your screenshot shows you're still using the IT ext. It should be somewhere in your english source list, or you filtered it out and you need to unfilter it

**Comment by steveacab** [comment]
Those screenshot are made after i removed and reinstalled the extension.
I checked only English and still i have only Italian no matter what I do. If you want I can make a video too

**Comment by Seishirou101** [comment]
you should go on discord and get support.

**Comment by steveacab** [comment]
I think that's a bug. It show in Italian even after i remove it and reinstall.

**Comment by arkon** [comment]
Enable English in the Sources menu properly.
