### ISSUE TITLE
Komik Cast: No pages found

### ISSUE THREAD

**Issue by arispati** [tachiyomiorg/tachiyomi-extensions#9275]
### Source information

Komik Cast 1.2.19

### Steps to reproduce

1. Open/tap the Komik Cast Source
2. search: Class ga Isekai Shoukan sareta Naka Ore dake Nokotta n desu ga
3. select chapter 12

### Expected behavior

Show images of the chapter

### Actual behavior

"No pages found" toast shown

### Tachiyomi version

0.12.2

### Android version

Android 10

### Other details

I've tried on the original website and didn't find any issue with the chapter

![photo_2021-09-29 10 49 35](https://user-images.githubusercontent.com/13604647/135201228-46a596a0-3bd1-47d4-8fcb-7f93b97c2207.jpeg)

![Screen Shot 2021-09-29 at 10 49 19](https://user-images.githubusercontent.com/13604647/135201533-83783782-d754-4c7b-a08d-3c040bddf516.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Chan220** [comment]
punya gw bisa kok

**Comment by Chan220** [comment]
itu memang dari komiknya udah mati linknya

**Comment by Chan220** [comment]
coba pake ekstensi yg lain spt komiku / kiryuu

**Comment by arispati** [comment]
> punyaku bisa kok.

@Chan220 saya coba lagi masih belum bisa pada chapter 12 (pada komik cast di tachiyomi), tapi saya coba buka di webnya langsung tidak ada masalah, chapter 12 bisa dibuka.

sepertinya ada masalah saat scrapping data url list chapternya, mau saya debug sendiri masih bingung, belum ada pengelaman di kotlin 😢 

karena chapter lainnya tidak ada masalah, hanya pada chapter 12 aja, jadi saya buat issue bug ini.

**Comment by Chan220** [comment]
> > punyaku bisa kok.
> 
> @Chan220 saya coba lagi masih belum bisa pada chapter 12 (pada komik cast di tachiyomi), tapi saya coba buka di webnya langsung tidak ada masalah, chapter 12 bisa dibuka.
> 
> sepertinya ada masalah saat scrapping data url list chapternya, mau saya debug sendiri masih bingung, belum ada pengelaman di kotlin 😢
> 
> karena chapter lainnya tidak ada masalah, hanya pada chapter 12 aja, jadi saya buat issue bug ini.

aku juga pengen bisa edit" ekstensi karena masih banyak ekstensi bhs.indo yg minta diupdate spt sekaikomik tapi apa daya ,aku gak tau cara ngeditnya...

**Comment by Riztard** [comment]
> aku juga pengen bisa edit" ekstensi karena masih banyak ekstensi bhs.indo yg minta diupdate spt sekaikomik tapi apa daya ,aku gak tau cara ngeditnya...

bisa cek ini, awal2 bisa coba yang simpel2 dulu aing juga gitu
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md

cuma 1 chapter yang gabisa jadi males benerin wkwk

**Comment by arispati** [comment]
> > aku juga pengen bisa edit" ekstensi karena masih banyak ekstensi bhs.indo yg minta diupdate spt sekaikomik tapi apa daya ,aku gak tau cara ngeditnya...
> 
> bisa cek ini, awal2 bisa coba yang simpel2 dulu aing juga gitu https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md
> 
> cuma 1 chapter yang gabisa jadi males benerin wkwk

oke @Riztard saya coba baca dulu, selama ini bikin mobile app pakai react native soalnya,  jadi masih bingung di kotlin dan java di android 🤣

**Comment by Chan220** [comment]
![b0ea3055-afbf-414c-9b61-6278b250eadd](https://user-images.githubusercontent.com/81818094/137435133-1dd7a41d-e535-4b1c-bfd4-df158a0c87cb.jpg)


> > > aku juga pengen bisa edit" ekstensi karena masih banyak ekstensi bhs.indo yg minta diupdate spt sekaikomik tapi apa daya ,aku gak tau cara ngeditnya...
> > 
> > 
> > bisa cek ini, awal2 bisa coba yang simpel2 dulu aing juga gitu https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md
> > cuma 1 chapter yang gabisa jadi males benerin wkwk
> 
> bener banget cuma 1 chapter doang males banget buat fixing wkowokkowkow
