### ISSUE TITLE
NineManga error

### ISSUE THREAD

**Issue by FireCheck** [tachiyomiorg/tachiyomi-extensions#9276]
### Source information

NineManga 1.12.5

### Steps to reproduce

1. Open NineMangaFR or NineMangaEN
2. Open Webview

### Expected behavior

It should open fr.ninemanga.com or en.ninemanga.com

### Actual behavior

But instead it shows "no result found" and it redirects to www.gardenmanager.com and i don't know why.
![Screenshot_20210929-140554_Tachiyomi](https://user-images.githubusercontent.com/84283461/135269909-5938342b-48b0-4459-b3c2-733fd346944a.jpg)
![Screenshot_20210929-140603_Tachiyomi](https://user-images.githubusercontent.com/84283461/135269913-95e50bea-9cf8-43fd-b198-f097fc7cc66d.jpg)
![Screenshot_20210929-140612_Tachiyomi](https://user-images.githubusercontent.com/84283461/135269914-f5cbc81f-6bab-4300-9793-811bfe3e40f9.jpg)

### Tachiyomi version

0.12.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
from https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475
> Known issues
> NineManga won't load / gardening site in webview: Clear your cookies

to be precise, More > Settings > Advanced > Clear cookies
