### ISSUE TITLE
Migrate Comick API to https://api.comick.fun

### ISSUE THREAD

**Issue by meotimdihia** [tachiyomiorg/tachiyomi-extensions#9278]
### Describe your suggested feature

Please migrate Comick API to https://api.comic.fun
This is the docs: https://api.comick.fun/docs
It is the same as the old API with changes: 
- query `tachiyomi=true` is required instead of the header
- `coverURL` param was change to `cover_url`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by h-hyuuga** [comment]
Adding `tachiyomi=1` returns a 500 response to otherwise functional queries

https://api.comick.fun/search?page=1&limit=100&q=

https://api.comick.fun/search?page=1&limit=100&q=&tachiyomi=1

**Comment by meotimdihia** [comment]
Sorry, I  have updated again. You need to add params `tachiyomi=true`.
https://api.comick.fun/search?page=1&limit=100&q=&tachiyomi=true

**Comment by h-hyuuga** [comment]
Every single cover_url points to https://comick.fun/static/failed_to_load.png

**Comment by meotimdihia** [comment]
Hi, I have fixed the URL:  https://api.comick.fun/search?page=1&limit=100&q=&tachiyomi=true

> coverURL hasn't consistently been renamed across the API: https://api.comick.fun/comic/solo-leveling has "coverURL" instead of "cover_url"
Currently, cover_url  will be for the param tachiyomi only. Comick backend doesn't have this convention 😀.

Yes, the API URL format was changed and I removed unnecessary nested data for the response. 
About the `/chapter/{hid}` API. I added attribute width and height in case anyone needs them. 😀

Thanks for point out the problem.

**Comment by h-hyuuga** [comment]
I'm not sure if this is intentional, but omitting the `q` parameter for `/search` causes all of the `cover_url`s to be https://comick.fun/static/failed_to_load.png

* https://api.comick.fun/search?page=1&limit=100&tachiyomi=true
* https://api.comick.fun/search?page=1&limit=100&tachiyomi=true&q=

**Comment by h-hyuuga** [comment]
Not sure if this is intentional, but omitting the `q` parameter from `/search` will make all `cover_url`s "https://comick.fun/static/failed_to_load.png"

* https://api.comick.fun/search?page=1&limit=100&tachiyomi=true
* https://api.comick.fun/search?page=1&limit=100&tachiyomi=true&q=

**Comment by h-hyuuga** [comment]
In `/search`

* The `t` parameter is undocumented, and `https://comick.fun` seems to send queries without `t=true` for autocomplete but then adds `t=true` when the actual query is sent. Which are we expected to use?
* A couple parameters will cause the request to fail if they are sent with no value, instead of falling back on some default. This isn't guaranteed to be a complete list: `demographic`, `time`
  * **Succeeds** https://api.comick.fun/search?q=solo&page=1&limit=100&t=true&tachiyomi=true
  * **Succeeds** https://api.comick.fun/search?q=solo&page=1&limit=100&t=true&tachiyomi=true&genres=
  * **Fails** https://api.comick.fun/search?q=solo&page=1&limit=100&t=true&tachiyomi=true&demographic=
  * **Fails** https://api.comick.fun/search?q=solo&page=1&limit=100&t=true&tachiyomi=true&time=

**Comment by meotimdihia** [comment]
- Query `t=true` will include alt titles. It is for show only, the result is the same.
- I am working on an empty string on array params. It is a new problem from yesterday. I will reply to the thread if I can't solve it. 😀

**Comment by meotimdihia** [comment]
@h-hyuuga It looks like we have to remove parameters that have an empty string.
It looks like I can't find out how to solve the problem with the framework that I am using.

**Comment by h-hyuuga** [comment]
> @h-hyuuga It looks like we have to remove parameters that have an empty string. I can't find out how to solve the problem with the framework that I am using.

This isn't a blocking issue; I figured that it might be fixable since some array parameters do accept the empty string but others don't. So long as the limitations are properly documented, it should be fine.

**Comment by h-hyuuga** [comment]
It may also be useful to document that most of the other parameters are ignored when the `q` is non-empty

**Comment by meotimdihia** [comment]
I have fixed the problem. 😀

**Comment by meotimdihia** [comment]
@h-hyuuga I replaced the field `country_code` with `lang` in chapters. 
https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/localization#locale-codes
It is the same as Mangadex but I fixed `es-la` to `es-419` because Mangadex returned the wrong code is `es-la`

**Comment by h-hyuuga** [comment]
> @h-hyuuga I replaced the field `country_code` with `lang` in chapters. https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/localization#locale-codes It is the same as Mangadex but I fixed `es-la` to `es-419` because Mangadex returned the wrong code is `es-la`

added to the PR
