### ISSUE TITLE
About hitomi.la and other multilingual sites  

### ISSUE THREAD

**Issue by AIR-HH** [tachiyomiorg/tachiyomi-extensions#9281]
### Describe your suggested feature

Hitomi. la is not shown in all, and there is no way to use all searches。

### Other details

![Screenshot_20210930_091658_eu kanade tachiyomi](https://user-images.githubusercontent.com/30023208/135370221-91187a80-8790-40d2-97e3-15be5f9c189d.jpg)
![Screenshot_20210930_091722_eu kanade tachiyomi](https://user-images.githubusercontent.com/30023208/135370220-8c652768-52ab-4b13-84b7-cc6e2180a242.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Are you sure it's not disabled on the extension settings?

**Comment by curche** [comment]
iirc Hitomi.la has an OTHER language option (named as, aptly, "hitomi.la unfiltered"). Might be worth a try:
1. go to extension settings, and enable OTHER
2. go to Browse > Extension, use the filter button at top, and enable OTHER lang
3. you should see a "hitomi.la unfiltered" source and try searching in that 

Relevant issue https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9436

**Comment by alessandrojean** [comment]
Closing as the extension was removed (refer to #11613).
