### ISSUE TITLE
ManhuaUS - No chapter found

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#9283]
### Source information

ManhuUS 1.2.13

### Steps to reproduce

Open any manga in the extension

### Expected behavior

Should work just fine

### Actual behavior

Giving No chapter found

### Tachiyomi version

0.12.2

### Android version

Android 10

### Other details

![Screenshot_2021-09-30-14-47-09-02_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/79831076/135407203-c5ff01d8-10f8-420e-aacd-f43201678242.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GhostLone93** [comment]
I join to problem, same thing is happening on my device Redmi note 9, android 10. Extension Mangaus 1.2.13
