### ISSUE TITLE
Mangaworld don t open all the chapters

### ISSUE THREAD

**Issue by Mattzero94** [tachiyomiorg/tachiyomi-extensions#9287]
### Source information

Mangaworld 1.2.4

### Steps to reproduce

when I try to open a chapter of any series, it gives me the error no page found.

### Expected behavior

I cant read all series

### Actual behavior

the site is online and working correctly but not via the app

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing in favour of #9291.
