### ISSUE TITLE
Mangaworld: Changed domain

### ISSUE THREAD

**Issue by AleTeen92** [tachiyomiorg/tachiyomi-extensions#9291]
### Source information

mangaworld.in

### Steps to reproduce

To change the domain from https://www.mangaworld.io to https://www.mangaworld.in

### Expected behavior

To work

### Actual behavior

Doesn't work

### Tachiyomi version

Last

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
alright, it is bad reported so i will write mine here

Steps to reproduce
open the extension, choose a manga opening it (just clicking on it)

Expected behavior
it should show the chapters

Actual behavior
it doesn't show the chapters with with message 
![IMG_20210930_205300](https://user-images.githubusercontent.com/75091899/135514594-19c0cc7a-caaa-4343-8d27-d32ad1b66072.jpg)

Tachiyomi version
0.12.2
Last
Android version

8
Other details

No response

**Comment by evaltin** [comment]
Mangaworld.io changed domain to mangaworld.in
Need help

**Comment by alessandrojean** [comment]
Wait for an extension update.

**Comment by SmashBanana** [comment]
Sorry but I don't know if this [https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9294](url) actions was accepted or not, if not i going to fix it

**Comment by Dadohnk** [comment]
> 
> 
> Sorry but I don't know if this #9294 was accepted or not, if not i going to fix it

dont think so, the guy closed it without testing

**Comment by alessandrojean** [comment]
@SmashBanana if you're going to submit a fix, please follow the CONTRIBUTING.md guide and test the modifications by compiling the extension and running in a emulator or physical device through Android Studio.

**Comment by alessandrojean** [comment]
No problem, you can edit the open PR if needed.
