### ISSUE TITLE
Migration issue 

### ISSUE THREAD

**Issue by DeltaBeam** [tachiyomiorg/tachiyomi-extensions#9305]
### Source information

Manganato 

### Steps to reproduce

There's a problem with the migration process in Tachiyomi.. Usually when you try and migration your manga from one extension to another it takes you back to the migration process, but now it takes you to the manga which you migrated and when you press back button its exit you from the migration,,, now i cant even migrate my 1500 collection as fast as it was used to be, it takes me almost more than double the time and effort to migrate, any solutions?"

### Expected behavior

when you try and migration your manga from one extension to another it takes you back to the migration process

### Actual behavior

it takes you to the manga which you migrated and when you press back button its exit you from the migration

### Tachiyomi version

0.12.2

### Android version

Android 10

### Other details

I was having this issue since like three months ago when one updated came 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This is an app issue, search in the app repo if an issue about this already exist and open a new one if it's not the case.

> If this is an issue with the app itself, I should be opening an issue in the app repository.
