### ISSUE TITLE
[West Manga] image problem

### ISSUE THREAD

**Issue by julptk** [tachiyomiorg/tachiyomi-extensions#9308]
### Steps to reproduce

1. open manga
2. click chapter
3. image not loaded

### Expected behavior

should be open

### Actual behavior

not loaded image mid quality and low

### Crash logs

App version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_PhoneApp version: 0.12.2 (standard, 3eec207, 68, 2021-09-13T19:16Z)
Android version: 6.0.1 (SDK 23)
Android build ID: MMB29M.WW_Phone-13.0.7.19-20160919
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X009D_2
Device model: ASUS_X009DA
Device product name: WW_Phone

### Tachiyomi version

0.12.2

### Android version

Android 6.0

### Device

Asus X009DA 

### Other details

![Screenshot_20211001-120542](https://user-images.githubusercontent.com/56266781/135576803-edf6652a-6058-4fb4-bf9d-16f8950d7abc.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me, be more specific with the steps to repoduce

**Comment by ZekkenID** [comment]
Do you have check manga on webview?
