### ISSUE TITLE
Voyce.me: Broken browse and search

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#9317]
### Source information

Voyce.me 1.2.1

### Steps to reproduce

1. Install the Voyce.me extension
2.1. Browse the extension
2.2. Use the search

### Expected behavior

2.1. Manga and manhwa should show up
2.2. Results should show up

### Actual behavior

2.1 & 2.2. Both are showing this
![Screenshot_20211002-140747_Tachiyomi](https://user-images.githubusercontent.com/84634607/135705656-30ccc6b4-9130-4388-8cf9-31bb6eb4516a.png)

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

Manhwa from the said extension that is in library is readable. No errors. Latest is working too (but covers are loading infinitely, or is it just my connection?)

Edit: Yea, prolly its just my slow connection ಠ︵ಠ

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Latest time I checked their server was having problems, so we need to wait for them to fix it first.

**Comment by alessandrojean** [comment]
Their GraphQL API is still broken, so the only thing we can do is wait for them to fix it.

![image](https://user-images.githubusercontent.com/14254807/135773990-5ceb3345-805d-4240-9b85-fec65bde54c7.png)

Even the requests done in their website are getting errors.

**Comment by alessandrojean** [comment]
Closing since search is working normally now.
