### ISSUE TITLE
AllPornComic: HTTP error 403/Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by mish20011** [tachiyomiorg/tachiyomi-extensions#9318]
### Source information

AllPornComic 1.2.11

### Steps to reproduce

1. Download chapter
2. Refresh Manga 
3. Turn off DNS for app

### Expected behavior

AllPornComic in browser works properly and loads chapters

### Actual behavior

But is http error when viewed in app and also has cloudflare that loops when used webview

### Tachiyomi version

TachiyomiSY 1.7.0

### Android version

Android 6.0

### Other details

https://i.imgur.com/qdu3jhY.png

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hyoretsu** [comment]
@alessandrojean This issue is talking about HTTP error 403, but ALSO about Cloudlare issue ON TACHIYOMI'S WEBVIEW. I get the issue on Tachiyomi, WebView works 100% fine including reading the manga I'm trying to download.

**Comment by alessandrojean** [comment]
@hyoretsu HTTP 403 is also one of the effects of Cloudflare, so it's the same issue. No need at all to have duplicate issues about the same thing.

**Comment by arkon** [comment]
Refer to the troubleshooting guide (also detailed in #3475).
