### ISSUE TITLE
Leviatan Scans: Change ’ apostrophe to ' apostrophe when migration searching 

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi-extensions#9322]
### Describe your suggested feature

 Results are fine when you global search (tap on the series title), but fails when searching through migration as the search is looking for the other (straight) apostrophe mark.

**Solution**
When migrating, switch the apostrophe mark from **apostrophe ’ (U+2019)** to **apostrophe '  (U+0027)**.

https://media.discordapp.net/attachments/566585518171881493/893807064294490112/21-10-02-11-28-51.mp4

### Other details

FYI: Fuck language
′ - Prime
’ - Apostrophe
' - Apostrophe
` - Backtick

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
While video is from SY, the issue persists in Main as well

**Comment by ObserverOfTime** [comment]
Actually, U+2019 is a quotation mark.

**Comment by setzke** [comment]
This exists with Flame Scans as well, so possibly others. I recorded a video showcasing the issue, if needed.

Steps:
1. Open a Flame Scans item that gets a 404 error when updating and has an apostrophe. 
2. Pull down to refresh to make sure; should say 404 at the bottom.
3. Click the 3 dots in the top right, then Migrate
4. Click Flame Scans since we only care about that right now, wait for list to load. Your comic shouldn't be there.
5. Click the name you're searching at the top. Correct the apostrophe, and allow it to search again.
6. Your comic will show. Migrate it. Next time you update it will be not 404.

**Comment by CrepeTF** [comment]
> This exists with Flame Scans as well, so possibly others. I recorded a video showcasing the issue, if needed.
> 
> Steps:
> 1. Open a Flame Scans item that gets a 404 error when updating and has an apostrophe. 
> 2. Pull down to refresh to make sure; should say 404 at the bottom.
> 3. Click the 3 dots in the top right, then Migrate
> 4. Click Flame Scans since we only care about that right now, wait for list to load. Your comic shouldn't be there.
> 5. Click the name you're searching at the top. Correct the apostrophe, and allow it to search again.
> 6. Your comic will show. Migrate it. Next time you update it will be not 404.

I mean sure, but the Flame Scans extension has been removed. It will not receive any fix.

**Comment by setzke** [comment]
> > This exists with Flame Scans as well, so possibly others. I recorded a video showcasing the issue, if needed.
> > Steps:
> > 
> > 1. Open a Flame Scans item that gets a 404 error when updating and has an apostrophe.
> > 2. Pull down to refresh to make sure; should say 404 at the bottom.
> > 3. Click the 3 dots in the top right, then Migrate
> > 4. Click Flame Scans since we only care about that right now, wait for list to load. Your comic shouldn't be there.
> > 5. Click the name you're searching at the top. Correct the apostrophe, and allow it to search again.
> > 6. Your comic will show. Migrate it. Next time you update it will be not 404.
> 
> I mean sure, but the Flame Scans extension has been removed. It will not receive any fix.

I forgot about that! I have seen it with others too. If it comes up with another one, I'll do a new video. :)
