### ISSUE TITLE
Mangaworld: Chapters and covers do not load

### ISSUE THREAD

**Issue by ed0fl3da** [tachiyomiorg/tachiyomi-extensions#9323]
### Source information

Mangaworld

### Steps to reproduce

Open Mangaworld
Select a manga
Open a chapter

### Expected behavior

You can read manga

### Actual behavior

Covers don't load
Chapters don't load

### Tachiyomi version

0.12.2

### Android version

Latest

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
/edit-title "Mangaworld: Chapters and covers do not load"

**Comment by loocool2** [comment]
Cannot reproduce as of March 15th 2022
