### ISSUE TITLE
MangaYabu: No pages found

### ISSUE THREAD

**Issue by Tdragoni** [tachiyomiorg/tachiyomi-extensions#9324]
### Source information

MangaYabu! 1.2.12

### Steps to reproduce

1.Open a title
2.click on a chapter
3. get error message. 

### Expected behavior

A chapter should open for Reading

### Actual behavior

No page found

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

Tested titles:
My hero academia
Vinland Saga
Kingdom
Black Clover

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Retashe** [comment]
MangaYabu vai parar de funcionar no Tachiyomi?

**Comment by alessandrojean** [comment]
O MangaYabu! está realizando modificações intencionais no site deles com o intuito de quebrar o funcionamento da extensão. Recomendamos migrar para outras fontes, pois a extensão muito provavelmente será removida em breve.

Não temos controle sobre isso, reclame com eles.
