### ISSUE TITLE
"Escuse me, This is my room" Chapters not showing in the app

### ISSUE THREAD

**Issue by Rinvay06** [tachiyomiorg/tachiyomi-extensions#9329]
### Source information

BeeManga

### Steps to reproduce

1. Open BeeManga
2. Search Up "Excuse me, this is my room"
3. Open the manwa 

### Expected behavior

Chapters should appear normal like in Toonily

### Actual behavior

Chapters did not appear, only this blank thing
![Uploading Screenshot_20211003_011528.jpg…]()

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MrChuw** [comment]
Title should change for all manga are without chapters working.

**Comment by stevenyomi** [comment]
Closing in favor of #15842
