### ISSUE TITLE
Kavita

### ISSUE THREAD

**Issue by edgehub-cloud** [tachiyomiorg/tachiyomi-extensions#9332]
### Source name

Kavita

### Source link

https://kavitareader.com/

### Language

English

### Other details

The api is still being built upon. (Swagger ui) 
https://wiki.kavitareader.com/en/guides/plugins-and-3rd-party-scripts
Needs to be hosted first. if u need more requirements u can ask dev Joe at their [Discord ](https://discord.gg/hy73F2Dk). Thanks
https://api.kavitareader.com/
 Alternative approach, scrap kavita if api isn't enough. Yea I know mad. But the authentication panel won't change nor the sending protocol so #8768 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by edgehub-cloud** [comment]
Swagger hosted but still need to be locally run
https://api.kavitareader.com/

**Comment by ThePromidius** [comment]
This is extension is being developed.

I though it'd be good to mention it here.

**Comment by edgehub-cloud** [comment]
Thanks for letting me and everyone know
