### ISSUE TITLE
[Bug] Komga extension wrong region label

### ISSUE THREAD

**Issue by Sakusuke** [tachiyomiorg/tachiyomi-extensions#9335]
### Source information

Komga 1.2.31

### Steps to reproduce

1. install komga extension from "all" type extensions

### Expected behavior

1. komga should show up in "all" type extensions

### Actual behavior

1. The extension shows up as "English" in installed extensions
2. The sources don't show up if "English" extensions are turned off

### Tachiyomi version

0.12.2

### Android version

android 10

### Other details

The extension shows up in "all" (すべて for me) when first selecting and installing it, but after install it's labeled as "English". I've asked the komga dev why it isn't in "all", he answered thusly:
"It is all, probably tachiyomi does a default, but ask on their discord".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The package is `all`, but the lang is set to `en` in https://github.com/tachiyomiorg/tachiyomi-extensions/blob/78f627dfa0ab7acf1d1430f4be43a755e282002e/src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt#L353

I haven't seen any extension where the language is set to `all`. I think `all` only applies to extensions with source factory that can generate multiple extensions in different language. I don't know all the insides of tachiyomi though.

@arkon is there an `all` language category for extensions (instantiated, not factories)? Is the request of OP doable?

**Comment by jobobby04** [comment]
There are multiple actually, such as LANraragi, Genkan.io, and a bunch of others. You can see them all here https://github.com/tachiyomiorg/tachiyomi-extensions/blob/repo/index.json

**Comment by gotson** [comment]
> There are multiple actually, such as LANraragi, Genkan.io, and a bunch of others. You can see them all here https://github.com/tachiyomiorg/tachiyomi-extensions/blob/repo/index.json

Thanks, that should be a simple fix then!

**Comment by kiriya-aoi** [comment]
Worth noting that when this change is made it will break downloads. Still worth doing, but should be paired with an announcement to rename any existing Komga download folders in `Tachiyomi\downloads\` from `Komga (EN)` to `Komga (All)`.

**Comment by gotson** [comment]
I think it may also break binding, the ID contains the language if I am correct.

**Comment by jobobby04** [comment]
Ya, it would just be `override val id` to the current id

**Comment by gotson** [comment]
Would it make sense to allow the language to be configured in the extension settings? That way you could say source 1 is en, source 2 is all, source 3 is jp.

**Comment by gotson** [comment]
> Ya, it would just be `override val id` to the current id

The `id` contains the version of the extension, i'm not sure we need to override the id in the extension to keep the language. I'll do some tests, see if it breaks anything.

**Comment by gotson** [comment]
> > Ya, it would just be `override val id` to the current id
> 
> The `id` contains the version of the extension, i'm not sure we need to override the id in the extension to keep the language. I'll do some tests, see if it breaks anything.

my bad, it contains the `versionId`, which is set to 1 and not overriden.
