### ISSUE TITLE
Komga Extension - Collections Not Appearing As A Filter

### ISSUE THREAD

**Issue by heisarzola** [tachiyomiorg/tachiyomi-extensions#9347]
### Source information

Komga 1.2.31

### Steps to reproduce

The collection dropdown (a custom filter) always appears empty, the only option being "None", while all other filters update normally. 

Seems pretty consistent on all devices for me, just by trying to use the dropdown, so it's likely something to do with the collection names or something of that nature, something on the Komga setup side being the point.

Hard to give a step by step of how my Komga collections are setup to reproduce this, as it would take a long time to redo it, but I more a less explain what I have below.

### Expected behavior

For the filter dropdown to be populated with the combined collections list.

### Actual behavior

The dropdown is empty.

### Tachiyomi version

0.12.2 (Latest Stable)

### Android version

9

### Other details

I'm not sure when did it started happening, but I was only ever able to see the dropdown items once, while I was still making the komga libraries, it changed to None ever since. Tried removing all special characters on all collections (keeping it to a-zA-Z), tried only having a single library, tried adding and removing books, all these alongside the standard reboot device, force close tachi, delete cache, even a different device as described before, etc. 

Every time I made these changes, I checked the rest of the filters (tags, libraries, etc.), and those did update properly each time, as a combined lists of all items in all libraries. The only thing I haven't tried was to redo the komga libraries, but seems overkill and too time consuming for just a test. 

The only "abnormal" thing I can remember that happened at some point, was that I moved all the items of a collection to another directory, after a new scan the old collection got scrapped for now having 0 items, so I had to remake it.

Each item in the entire library is either cbz or zip files, and each item is in at least one collection, each item is readable (none are corrupted), and everything should total around 50 collections to name an equal amount of series (some have special characters like ☆, but as stated above, removing these was already tried).

I tried looking at the log files when I clean installed tachiyomi + komga extension on a different device, it didn't show anything abnormal, just the regular logins, book fetches, and the like. Same for when the filters were provided to the new device after waiting a bit, so no relevant logs were found.

@gotson 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Probably similar to #6047, I'll add more logs

**Comment by plumber-craic** [comment]
Here are some logs showing an exception for collections: https://pastebin.com/c9Eumn1p 

My Libraries filter works now, but the collections filter does not. Yesterday was the opposite behaviour.

**Comment by gotson** [comment]
> though that is not an available option in the Filters (would be nice to have an author option).

It is, but it's dynamically built, so you don't see it because of the exception.

---

It seems to be a problem of doing some work in the wrong thread, with an Android exception: `android.os.NetworkOnMainThreadException` `android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)`

My Android knowledge is limited, I have no idea how to fix that.

**Comment by gotson** [comment]
I don't know much how the various schedulers work in Android, but i was thinking you could try changing:

```
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
```

for

```
.subscribeOn(Schedulers.newThread())
.observeOn(Schedulers.newThread())
```

Given you are tinkering with the extension already for your other PR, you could test if that fixes it. It works on my end, but I don't know if there could be other side effects.

**Comment by plumber-craic** [comment]
I haven't done any android dev before, don't think it's my PR. But if you have a signed compiled binary with these changed lines I'd be happy to test and resubmit logs.

**Comment by gotson** [comment]
> Same result on the latest version https://pastebin.com/pkJ5qsaM

The change was merged 1h after your comment, so that's probably not the latest version.

**Comment by plumber-craic** [comment]
1.2.34 works! Thank you very much @gotson

**Comment by curche** [comment]
Closing since its resolved. You can reopen if it still doesn't work
