### ISSUE TITLE
Isekai Scan still broken 

### ISSUE THREAD

**Issue by Astrokinng** [tachiyomiorg/tachiyomi-extensions#9351]
### Source information

Isekai Scan 1.2.15

### Steps to reproduce

1. update the library 
2. Isekai Scan Doesn't update .. failed to bypass clouflare

### Expected behavior

It should get updated normally 

### Actual behavior

Nothing happens 
Tried webview 
Vpn 
Nothing works 

### Tachiyomi version

App version: 0.12.2-3844 

### Android version

Android 11

### Other details

![Screenshot_20211003-195625](https://user-images.githubusercontent.com/89287848/135758439-ef83fadf-d056-4ba3-bb49-f81f33669d29.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Camo260** [comment]
Isekaiscans itself has actually been under maintenance for a while, have to wait till they back up or change to another source. If webview and using another web browser doesn't load anything then the issue is probably website side rather than extension.
