### ISSUE TITLE
Wakamics fails to find any chapters

### ISSUE THREAD

**Issue by QuantumSoundings** [tachiyomiorg/tachiyomi-extensions#9355]
### Source information

Wakamics 1.2.11

### Steps to reproduce

Attempt to view any series using the extension and see that it fails to load the chapters. Look in the webview to see there are actually chapters.

### Expected behavior

Chapters are found.

### Actual behavior

No chapters are found.

### Tachiyomi version

r3844

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Should be fixed #9948 as it looks to work for me
If you are still facing issues, make sure to try [Troubleshooting steps ](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) or ask for help at the #support channel in the Discord server.
