### ISSUE TITLE
Mangakik - no chapters, webview shows broken images, external browsers fine

### ISSUE THREAD

**Issue by Camo260** [tachiyomiorg/tachiyomi-extensions#9357]
### Source information

Mangakik 1.2.11

### Steps to reproduce

1. Open Mangakik source search or latest
2. Open Manhwa eg. "Reverse Villain"
3. 0 chapters
4. Refresh
5. Still 0 chapters found
6. Enter webview
7. Select latest chapter (currently 82)
8. All chapter images broken
9. Use external browser (chrome and firefox)
10. Select latest chapter (currently 82)
11. Chapter images load fine on mangakik

### Expected behavior

Should be able to view and read chapters in search and library in Tachiyomi for Mangakik source

### Actual behavior

Unable to see or read any chapters in Tachiyomi for Mangakik source

### Tachiyomi version

J2K v1.3.2 and 0.12.2

### Android version

Android 11 (One UI 3.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me, probably fixed by madara chapter list in the past
