### ISSUE TITLE
Display problem with manwhatop extension

### ISSUE THREAD

**Issue by Zimsa19** [tachiyomiorg/tachiyomi-extensions#9358]
### Source information

Manhwatop 1..2.12

### Steps to reproduce

There is an issue of retry error when I was trying to read any comic within the extension

### Expected behavior

The comic should not jave any retry error and all comic is readable

### Actual behavior

However the comic become unreadable and there is an retry error for all of comics

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Closing due to lack of response, please do what curche suggested and if the issue persists come onto discord and ask for help in #support
