### ISSUE TITLE
[Source Request] Comic Walker

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi-extensions#9359]
### Source name

Comic Walker

### Source link

https://comic-walker.com/

### Language

Japanese

### Other details

I know that this has been asked multiple times but hear me out.

Why I am so persistent on this extension:

1. **Because you made extensions for MangaPlus by Shueisha, Magazine Pocket, Tonari no Young Jump and Shounen Jump+ which is OFFICIAL SOURCES**.
2. You can just add a dialog that says "By clicking ok and installing this extension, I acknowledge that I fully read the terms and conditions of said source". This is also solution for #2157
3. Just Do It!

Note: You can just add it to Tachiyomi app itself, not on the website.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Yes, we have done extensions for these sites you mentioned, but the publishers and owners doesn't have a high history of sending a lot of DMCA complaints, like Kadokawa does directly or indirectly by using other companies.

**Comment by ObserverOfTime** [comment]
Even if we were to disregard the risk of a DMCA complaint, their images are DRM protected which would make implementing an extension rather difficult.
