### ISSUE TITLE
[Japscan] Some pictures are scrambled while some are not

### ISSUE THREAD

**Issue by MikeZeDev** [tachiyomiorg/tachiyomi-extensions#9374]
### Source information

Japscan 1.2.29

### Steps to reproduce

I downloaded "Aime ton prochain" from the app.

### Expected behavior

Picture shouldnt be scrambled..

### Actual behavior

All chapters from 1 to 61 have scrambled pictures. Chapters 62 to 74 seems to be fine

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

I downloaded using 0.12.2 then i saw on the bug form there is a 0.12.3. Not sure it'l fix anything since its extension related but i'll give it a try. I know Japscan is annoying, i expected something like that from them. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kiwizpatate** [comment]
Thx. Haven't found this topic. A lot of late chapter from the French extension are scrambled

**Comment by MikeZeDev** [comment]
I can reproduce the problem with "Ah my Goddess " too.  Chapters 297 to the last are scrambled.

**Comment by az4521** [comment]
lol

**Comment by CrepeTF** [comment]
lol

**Comment by LockBlock-dev** [comment]
Any news on this?

**Comment by MikeZeDev** [comment]
As of now, i dont see puzzles anymore on Japscan
