### ISSUE TITLE
MangaNyaa

### ISSUE THREAD

**Issue by pcmaamcp** [tachiyomiorg/tachiyomi-extensions#9379]
### Source name

MangaNyaa

### Source link

https://manganyaa.com/

### Language

Portuguese (Brazil), English and Spanish

### Other details

There are 3 different languages available on the site, but I am most interested in Portuguese (Brazil).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The website is hosting the data in a GitHub repository. It's a matter of time until someone (like Comeso) send a DMCA complaint, and it gets removed. It's not worth to make an extension in this case.
