### ISSUE TITLE
Manhua ES chapters cut off

### ISSUE THREAD

**Issue by SaintFrancis01** [tachiyomiorg/tachiyomi-extensions#9402]
### Source information

Manhua ES 1.2.16

### Steps to reproduce

1. Open Manhua ES Comic - example: Cultivator In The City
2. Open Chapter - example: Ch. 10
3.  Last Half of chapter is cutoff, no error messages or "unable to load - retry" messages.
4. Next chapter starts normally but is also cutoff
End

Same behavior for downloaded and not downloaded chapters

### Expected behavior

Full chapters to load or download

### Actual behavior

Half of chapters are cut off, not even showing an error message as if the app doesn't know there is more to load. 

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11

### Other details

Reading the chapter on the website loads the chapters normally, there are no errors or breaks in the chapters on the website. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
From what i can they have 4 different chapter types on the site:

- Normal chapters [example](https://manhuaes.com/manga/cultivators-in-the-city/chapter-11/) working
- 2 pages chapters [example](https://manhuaes.com/manga/cultivators-in-the-city/chapter-10/) only one page gets loaded
- Broken Chapters with no content [example](https://manhuaes.com/manga/i-can-snatch-999-types-of-abilities/chapter-8/) Gives error message `No pages found`
- Not yet released chapters [example](https://manhuaes.com/manga/an-emperor-persistently-pursuits-the-twelfth-wife/chapter-37/) Are filtered out
