### ISSUE TITLE
اضافة مانجا لايت مون

### ISSUE THREAD

**Issue by rashedawonho** [tachiyomiorg/tachiyomi-extensions#9417]
### Source name

Manga Light Moon

### Source link

https://mangalightmoon.blogspot.com/?m=1

### Language

Arabic

### Other details

المدونة للشوجو مانجا

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
We don't add blogspot sites

**Comment by Riztard** [comment]
*update: nvm their chapter open imgur link :v
