### ISSUE TITLE
Some luscious pages are just marked as "conpleted" on screen

### ISSUE THREAD

**Issue by drakosoldier298** [tachiyomiorg/tachiyomi-extensions#9422]
### Source information

Luscious. 1.2.14 

### Steps to reproduce

1. Open any luscious manga
2. 2.try to read it.

### Expected behavior

Every page is the manga

### Actual behavior

Every other page has contnent of "finished x" "next x"
![Screenshot_20211010-094549](https://user-images.githubusercontent.com/30358222/136700884-f9ed14ee-a0b2-4add-bf5b-14704a22a1da.png)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
That is intended behavior due to Luscious adding new pages to Albums regularly.

There are 2 ways to remove this:

1. Enable Merge Chapter options in the Luscious extension settings
2. Turn of Always show chapter transition in Reader settings
