### ISSUE TITLE
CatManga isn't opening Kanojo Okarishimasu Chapter 208

### ISSUE THREAD

**Issue by Dannoob** [tachiyomiorg/tachiyomi-extensions#9431]
### Source information

CatManga 1.2.5

### Steps to reproduce

1. search for Kanojo Okarishimasu
2. add to library
3. open latest chapter in this case it's chapter 208

### Expected behavior

it should open normally like other manga does

### Actual behavior

but instead it opens for few miliseconds and exits the manga while displaying a blank pop-up message

### Tachiyomi version

tachiyomi J2K v1.3.2

### Android version

Android 11.

### Other details

https://media.discordapp.net/attachments/349436576037732355/897114781398478858/screen-20211011-212818.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheUnlocked** [comment]
I talked to the folks at Black Cat Scanlations and it seems like this is a caching issue on their end. Hopefully it should resolve itself in the near future, but there shouldn't be any action needed by the extension.
