### ISSUE TITLE
Change nHentai, and Hitomi.la Other sources to All

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi-extensions#9436]
### Describe your suggested feature

...since we're using All category for sources now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
"Other" in EH maps to `language:other` so it shouldn't be changed.
