### ISSUE TITLE
Mundo hentai

### ISSUE THREAD

**Issue by Joao245909** [tachiyomiorg/tachiyomi-extensions#9441]
### Source name

Mundo hentai

### Source link

https://mundohentaioficial.com/

### Language

Português brazil

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Wrongly removed by #7361.

**Comment by alessandrojean** [comment]
Don't close it, it was just a comment to keep control of things and help it to get added back.

**Comment by alessandrojean** [comment]
Readded by #9554.
