### ISSUE TITLE
Mangakalot - Manganato 

### ISSUE THREAD

**Issue by Ghostpretzel13** [tachiyomiorg/tachiyomi-extensions#9443]
### Source information

Mangakalot

### Steps to reproduce

When choosing manga from mangakalot it has either the word mangakalot or readmanganato beneath the chapter title or number.

### Expected behavior

This would cause no problem as it would load the pages and be readable.

### Actual behavior

Instead once a manga is subtitled readmanganato it will go no further than the 2nd page and refuse to load anything afterwards. while the mangakalot subtitled manga can be read completely.

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

I have no clue as to if this issue is with the extension or the site host but when any manga that would not load was opened in webview it for the most part had loaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
works fine for me, did you try clearing your cache like the troubleshooting guide said?

**Comment by Ghostpretzel13** [comment]
have tried but still the same thing every manganato and mangakalot with the readmanganato chapters all refuse to load after page 2

**Comment by Seishirou101** [comment]
can you read from webview on manganato's site? usually clearing the cache fixes this issue. How are you clearing the cache? what version number of the extension are you using?

**Comment by Ghostpretzel13** [comment]
reading on webview works and clearing the cache did not work in the tachiyomi settings and in phone settings with the mangakakalot ext at 1.2.8 and Manganato ext at 1.2.7 it did not happen like this before so i don't know what is different

**Comment by zerakori** [comment]
Its happening again in version 1.3.8 for mangakakalot and 1.3.7 for manganato

**Comment by zerakori** [comment]
Uninstalled them, cleared the cache, then reinstalled them but the problem remains the same

**Comment by Saberfanboy** [comment]
Hi, has this issue ever been fixed?
I'm having the same problems with manganato for quite a while now

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
