### ISSUE TITLE
Golden Mangás HTTP error 403

### ISSUE THREAD

**Issue by KonSmile** [tachiyomiorg/tachiyomi-extensions#9448]
### Source information

Golden Mangás 1.2.13

### Steps to reproduce

the extension and the mangas won't work when I press them

### Expected behavior

the expected behaviour is it letting me in

### Actual behavior

HTTP ERROR 403

### Tachiyomi version

0.12.3

### Android version

Android 7.1.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's a Cloudflare error and there's nothing we can do to fix it. Wait for them to lower the protection or migrate to better sources.
