### ISSUE TITLE
Vanitas

### ISSUE THREAD

**Issue by rashedawonho** [tachiyomiorg/tachiyomi-extensions#9452]
### Source name

Vanitas

### Source link

https://www.vaniitasclub.com/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Doesn't appear to be a manga site any more?

**Comment by shipoxx** [comment]
Website is Dead even the new domain is Dead tho (empty)

So this request close.

**Comment by curche** [comment]
Can make another request when new one comes up, if at all
