### ISSUE TITLE
AR FlameScans: Chapter images split

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#9455]
### Source information

AR FalmeScens 1.2.11

### Steps to reproduce

1- Open Tachiyomi-extensions AR FalmeScens
2-Open Manga
3- Open Chapters

### Expected behavior

The full class photo display should appear

### Actual behavior

View the pictures of the chapter divided into the last chapters

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

These are images from within the application source
![Screenshot_20211012-191733](https://user-images.githubusercontent.com/87826849/136994737-d63acf00-6bb4-4268-8188-172cc76449d4.png)
.
![Screenshot_20211012-191739](https://user-images.githubusercontent.com/87826849/136994833-727cf8c4-4c9f-44ff-b8f5-1aff1cbdafba.png)
![Screenshot_20211012-191744](https://user-images.githubusercontent.com/87826849/136994873-8dc02227-63d4-46b0-b0be-1741bbca6d86.png)

This is a presentation of the class from within the site, the image appears in full and is not divided in width
![Screenshot_20211012-191838](https://user-images.githubusercontent.com/87826849/136995243-c949370a-fa2d-4e94-a875-602f6687351a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Wasn't AR Flame Scans also supposed to be removed?

**Comment by ahmedgamal17** [comment]
الموقع نفسه بيغير روابط المانجا الموجودة فكده بتضطر أن انت تضيف المانجا من تاني

**Comment by hani1998** [comment]
شكراً ياغالي واشتي اسالكم golden time معد يرجع المصدر

**Comment by shipoxx** [comment]
> شكراً ياغالي واشتي اسالكم golden time معد يرجع المصدر 
> 

تم ازالته عن طريق الخطأ وهناك طلب لاعادته 
يعتمد الامر ان كان هناك شخص متفرغ.

**Comment by shipoxx** [comment]
> الموقع نفسه بيغير روابط المانجا الموجودة فكده بتضطر أن انت تضيف المانجا من تاني

اذن هناك اي معنى من فتح موضوع جديد حوله لاني حاولت اصلاحه بدون جدوى
