### ISSUE TITLE
Manhwas Men: Can't view or download chapters

### ISSUE THREAD

**Issue by Fakhr456** [tachiyomiorg/tachiyomi-extensions#9458]
### Source information

Manhwas Men

### Steps to reproduce

First I installed Manhwas Men. 
Then I searched the manhwa I needed to download. 
Issue is chapters dont download, they can't even be viewed. 

### Expected behavior

Normally the chapters start downloading, and if they don't I use vpn which does the trick. 

### Actual behavior

The chapters don't download, after a certain time I can see the error icon that the chapter hasn't downloaded. 

### Tachiyomi version

0.12.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fawadkhan121** [comment]
When downloading keep the app ON don't put it in background i thinks this should do the trick

**Comment by Fakhr456** [comment]
Sorry for the delayed response. The issue wasn't with the extension but with the site itself, some chapters were broken, that's why they weren't downloading.
