### ISSUE TITLE
Favorited titles under MangaFast Extension Crash Tachiyomi to Android home screen

### ISSUE THREAD

**Issue by applepuppy** [tachiyomiorg/tachiyomi-extensions#9466]
### Source information

MangaFast ID# 6140599306147980654, v1.2.13

### Steps to reproduce

Repro 1
======
Open Library
Scroll down until a thumbnail associated with one of my 50+ MangaFast favorites loads
Tachiyomi closes without an error message taking me back to the Android home screen

Repro 2
======
Open Browse
Select Migrate
Select MangaFast (52)
A white screen loads with MangaFast in the upper left hand corner, but no thumbnails load and then the app crashes to Android home screen without an error message within the span of about a second

### Expected behavior

I should be able to open any "favorited" title under MangaFast without it crashing the browse menu.
I should be able to open extensions -> migrate and open MangaFast without it creashing the migrate menu 

### Actual behavior

The moment I attempt to view a thumbnail associated with a MangaFast within the browser or migrate a title off of MangaFast it crashes Tachiyomi to the Android home menu and I have to re-start the Tachiyomi app.

### Tachiyomi version

0.12.3 (10/4/21 2:35PM) Stable

### Android version

Andorid 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Closing since issue resolved itself.
