### ISSUE TITLE
Mangafoxfun

### ISSUE THREAD

**Issue by dtantono** [tachiyomiorg/tachiyomi-extensions#9467]
### Source name

Mangafoxfun

### Source link

https://mangafox.fun/updates//

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
different source i believe

**Comment by vetleledaal** [comment]
Related issue #10205 (and possibly #4763)

Same theme:
https://mangahub.io
https://mangaonline.fun
https://mangatoday.fun
https://manga.town
https://mangahere.onl
https://mangakakalot.fun
https://mangafox.fun
https://mangapanda.onl
(they all say "©mangahub.io group")

There is an extension made for mangahub.io in #1593, but it should probably be made into a factory.
