### ISSUE TITLE
MangaToon (Limited) 1.2.2 Error

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#9472]
### Source information

MangaToon 1.2.2

### Steps to reproduce

All chapters in Mangatoon are not found and Cover is black after opening Manga

### Expected behavior

Hopefully it can be fixed

### Actual behavior

All chapters in Mangatoon are not found and Cover is black after opening Manga

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

Extension : MangaToon (Limited) 1.2.2
Problem: All manga cannot be loaded with empty aliases and blackened covers in all languages
Screenshot : https://the.tokisakimitsuha.workers.dev/0:/MangaToon%20Error.zip

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rspreet92** [comment]
I suggest use of h5.mangatoon.mobi instead of the desktop site mangatoon.mobi
The h5 version also support login and coin/token use.

**Comment by FourTOne5** [comment]
> I suggest use of https://h5.mangatoon.mobi instead of the desktop site mangatoon.mobi The h5 version also support login and coin/token use.

it gets the chapter from an API call which needs a signature to authenticate the calls which I tried hard but couldn't find any references to.
