### ISSUE TITLE
Add Madara Customizations

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi-extensions#9474]
### Source name

N/A

### Source link

N/A

### Language

N/A

### Other details

1. Needs option for custom date format
2. Option to toggle between old and new chapter endpoint.
3. Extension needs to have more than one customizable source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
I think this can be closed already?

**Comment by Riztard** [comment]
> I think this can be closed already?

why? was it alredy added?

**Comment by stevenyomi** [comment]
> Needs option for custom date format

Already there.

> Option to toggle between old and new chapter endpoint.

There is one.

> Extension needs to have more than one customizable source.

Don't really understand this one.

**Comment by stevenyomi** [comment]
Or, is the option an "editable preference"?

**Comment by Riztard** [comment]
> I'm asking for "FoolSlide Customizable" like source for Madara -_-

**Comment by stevenyomi** [comment]
> > I'm asking for "FoolSlide Customizable" like source for Madara -_-

I have no idea what is "FoolSlide Customizable".

**Comment by curche** [comment]
> > I'm asking for "FoolSlide Customizable" like source for Madara -_-
> 
> I have no idea what is "FoolSlide Customizable".

https://tachiyomi.org/extensions/#all.foolslidecustomizable

basically, if your website is an un-altered foolslide theme, then it shud work with the extension

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
