### ISSUE TITLE
Source Hentaifox broken

### ISSUE THREAD

**Issue by Etherious108** [tachiyomiorg/tachiyomi-extensions#9484]
### Source information

Hentaifox English 1.2.3

### Steps to reproduce

If you open a chapter no pages load. But it opens in webview

You can't download as well
![IMG_20211015_151441](https://user-images.githubusercontent.com/91865941/137468864-a5200cf6-81eb-4e03-94a4-906587303d95.jpg)

### Expected behavior

Pages should load

### Actual behavior

It doesn't load. It comes as "retry"

### Tachiyomi version

Stable 0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Silvermane06** [comment]
I'm having the same problem, can't download anything, it'll just eventually timeout.

**Comment by Clouddark75** [comment]
This can be closed. The source changed the tags back, so the extension has been working for awhile now.
