### ISSUE TITLE
MangaSee: Manga covers not updating

### ISSUE THREAD

**Issue by Whisperx17** [tachiyomiorg/tachiyomi-extensions#9486]
### Source information

Mangasee 1.2.26

### Steps to reproduce

Advanced > Refresh library manga covers
Issue: none of the manga covers get refreshed (Mangasee extension)
N.B: I haven't noticed the same issue with other extensions

### Expected behavior

During global library updates or when directly refreshing library manga covers, it usually updates to match with what's on the host site if there's a new manga cover. 

### Actual behavior

Nothing happens. Sometimes the manga cover goes black for a few seconds, but when it comes back, it remains unchanged. 

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Updating metadata with library updates should do the same as the advanced option.
It just seems like covers don't actually get updated. I'm not sure how Tachiyomi decides if a cover is updated (it's certainly not redownloading covers every single time) but I'm guessing it just looks at the URL which is always the same for MangaSee covers.
Deleting the manga and searching for it shows the new cover just fine.
For me this is more of an app issue (if one isn't already opened for this) but there's no real good solution as the only way to tell the difference is to redownload the covers every time and compare and that's not happening (but perhaps the advanced option to update covers could include redownloading everything too).

**Comment by OkaforDonald** [comment]
> Updating metadata with library updates should do the same as the advanced option. It just seems like covers don't actually get updated. I'm not sure how Tachiyomi decides if a cover is updated (it's certainly not redownloading covers every single time) but I'm guessing it just looks at the URL which is always the same for MangaSee covers. Deleting the manga and searching for it shows the new cover just fine. For me this is more of an app issue (if one isn't already opened for this) but there's no real good solution as the only way to tell the difference is to redownload the covers every time and compare and that's not happening (but perhaps the advanced option to update covers could include redownloading everything too).



> Updating metadata with library updates should do the same as the advanced option. It just seems like covers don't actually get updated. I'm not sure how Tachiyomi decides if a cover is updated (it's certainly not redownloading covers every single time) but I'm guessing it just looks at the URL which is always the same for MangaSee covers. Deleting the manga and searching for it shows the new cover just fine. For me this is more of an app issue (if one isn't already opened for this) but there's no real good solution as the only way to tell the difference is to redownload the covers every time and compare and that's not happening (but perhaps the advanced option to update covers could include redownloading everything too).
