### ISSUE TITLE
Pedido de fonte Reaper Scan (BR)

### ISSUE THREAD

**Issue by Greed-2468** [tachiyomiorg/tachiyomi-extensions#9494]
### Source name

Reaper Scans

### Source link

https://reaperscans.com.br/

### Language

Português br

### Other details

É uma Scan com base na Reaper Scans em inglês, só que feita por brasileiros é recente mas muito promissora, espero que possam fazer uma extensão pra ela. Please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Already exists under the Reaper Scans extension.
