### ISSUE TITLE
[1st kiss manhua] cannot download and read any chapters

### ISSUE THREAD

**Issue by RenzRayark** [tachiyomiorg/tachiyomi-extensions#9509]
### Source information

1st Kiss Manhua 1.2.13

### Steps to reproduce

For reading:
     1. Click any comic
     2. Click any chapter
     3. Wait for images/chapter to load

For downloading:
     1. Click any chapter
     2. Click download

### Expected behavior

-Images/pages should load

-downloading chapters should start then finish

### Actual behavior

For reading- only shows "retry"
![Screenshot_20211017-133019](https://user-images.githubusercontent.com/92661551/137613832-6db41051-70e6-4d19-9078-73c86b6d43fc.jpg)

For downloading- download starts but the progress bar doesn't move
![Screenshot_20211017-134506](https://user-images.githubusercontent.com/92661551/137613828-a43d7c30-167a-4d73-a57c-a4c197ace47b.jpg)

### Tachiyomi version

0.12.3

### Android version

ASUS_X018D

### Other details

-all other extensions work fine(except 1st kiss because HTTP error 403 is still there)

-Androd 7

-cloudfare is up to date

-i checked webiew. The site is not down and comics are still available
![Screenshot_20211017-133657](https://user-images.githubusercontent.com/92661551/137613875-1c56cf3e-3a0b-4547-a14d-1fc4b000bebb.jpg)

-App has dump crash log:
--------- beginning of main
10-17 13:10:45.750 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056c
10-17 13:10:45.756 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:10:45.756 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:10:45.756 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:10:45.756 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:10:46.033 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:10:46.034 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:10:46.034 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:10:46.034 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:10:47.239 30016 30088 E SQLiteLog: (284) automatic index on C(manga_id)
10-17 13:10:47.239 30016 30088 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-17 13:22:28.142 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056c
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056c
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:22:28.143 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056c
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056c
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.144 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:22:28.192 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056c
10-17 13:22:28.194 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.194 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.194 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.194 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
10-17 13:22:28.368 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101056d
10-17 13:22:28.368 30016 30016 E ResourceType: Style contains key with bad entry: 0x0101058c
10-17 13:22:28.368 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010604
10-17 13:22:28.368 30016 30016 E ResourceType: Style contains key with bad entry: 0x01010605
App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 7.0 (SDK 24)
Android build ID: WW_Phone-14.02.1803.52-20180318
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X018_4
Device model: ASUS_X018D
Device product name: WW_X018

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArzuHrpt** [comment]
Mine is Android 10 and I'm also having the same problem, while tracking the updates it gives an error. When I try to open it in web view or in browser it works just fine but on app it doesn't update manga, can't read anything nor i can browse in extension tab on 1st kiss

**Comment by rzmeu** [comment]
Also have this problem, but there are times when it works and when not. If no one is investigating this, I cat take a look

**Comment by P08Rahul** [comment]
I am having same issue It works sometime but most of the time it show failed to bypass cloudflare. When I open it in webview it works fine and I have tried all the troubleshoot. I am using tachiyomi j2k latest version all the extension is up-to-date and my android version is 11.
![Screenshot_2021-10-18-10-11-42-293_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/76175244/137670559-ea3338a5-3bb4-4678-b741-909a004608c0.jpg)
![Uploading Screenshot_2021-10-18-10-14-54-532_eu.kanade.tachiyomi.j2k.jpg…]()

**Comment by payback111** [comment]
Some manhua if you can't read in 1st kiss manhua you can read in 1st kiss and what is strange is that if you read one chapter at 1kiss it fix that one chapter at 1st kiss manhua.

**Comment by abdulashfaq** [comment]
Iam also facing same using but iam tachiyami preview app latest version .

The Bug is regarding 1st kiss manhua is gives me updates but i can't read those 

And every extension is up to date

**Comment by Waseem-Almoliky** [comment]
You can use
Mangafixfull
Or
Isekaiscans
Until they kill the bug
