### ISSUE TITLE
[Graze Scans] Extension will not read or download manga. Errors in description.

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi-extensions#9510]
### Source information

Graze Scans [English 1.2.13]

### Steps to reproduce

1. Download any chapter of a series, or all at once.

OR

2. Open a chapter to read.

### Expected behavior

1. The chapter should download.
2. The chapter should open

### Actual behavior

Problem 1:
Instead of downloading the chapter, tachiyomi sends an error notification of "_**Expected URL scheme 'http' or 'https:' but no colon was fo...**_".
I can't post the full notification because it gets cut off in the noti area after that, and clicking on the noti just opens the tachiyomi app.

Problem 2:
If you actually read the manga, you get an error message of '_**"unable to resolve host "grazescans.comhttps" : No address associated with hostname."**_'

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11 [One UI 3.1]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
graze scans is gone
