### ISSUE TITLE
Fonte fora do ar

### ISSUE THREAD

**Issue by KikuLindu** [tachiyomiorg/tachiyomi-extensions#9514]
### Source information

Golden mangás

### Steps to reproduce

Ero 404

### Expected behavior

Carregar os mangás

### Actual behavior

Não carrega nada

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Eles aumentaram a proteção do Cloudflare e não há nada que possamos fazer na extensão para contornar isso. Aguarde com que eles diminuam a proteção ou use outras fontes.

Por favor preencha o formulário com mais detalhes e **em inglês** na próxima vez.
