### ISSUE TITLE
comick.fun says sequence is empty for some chapters 

### ISSUE THREAD

**Issue by DeltaKiloOne** [tachiyomiorg/tachiyomi-extensions#9516]
### Source information

Comick.fun v1.2.7

### Steps to reproduce

1. Search a manga eg. Grand blue
2. Open chapter 51 or 52 or 53 (works on the site)
3. Says sequence is empty

### Expected behavior

Should show me or allow me to download chapter 51 52 or 53

### Actual behavior

Says sequence is empty and down now allow me to download or read the manga chapters 
![Screenshot_20211017-215649_TachiyomiJ2K](https://user-images.githubusercontent.com/87071129/137636470-cd46644c-423d-405e-a194-7d71b7f9b8a6.png)

### Tachiyomi version

v1.4.2 Tachiyomi J2K and also in original tachiyomi v0.12.3

### Android version

Android 11 One UI 3.1

### Other details

The actual behavior can't open the reader too
![Screenshot_20211017-215649_TachiyomiJ2K](https://user-images.githubusercontent.com/87071129/137636608-ce8d700c-641b-43d6-a8b9-da7abda63c0d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by h-hyuuga** [comment]
Reproduced, is an issue with the Comick.fun API


---

@meotimdihia in `/chapter/{hid}` not every object in the `chapter.images` list provides a `url`

e.g: https://api.comick.fun/chapter/RXEYO?tachiyomi=true (Grand Blue 51)

* `chapter.images[39]` provides a `w` and `h` but no `url`.

**Comment by meotimdihia** [comment]
@h-hyuuga I have fixed this problem. Thanks for the report 😀
