### ISSUE TITLE
request for new Brazil Portuguese extensions

### ISSUE THREAD

**Issue by Jokvfijcf** [tachiyomiorg/tachiyomi-extensions#9517]
### Describe your suggested feature

I'd like you to add a few scans and websites to Tachiyomi, please:
Alone scanlator
Tsuki manga (website)
War queen scan
Witches academy scan
Br. Niad.(website)
Bubble tea scan
Sumire scan
Scarlet scan
If you could add these scan and websites, I'd appreciate it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill out the source request form and 1 source per ticket.
