### ISSUE TITLE
1st kiss extension can't bypass cloudflare

### ISSUE THREAD

**Issue by Estiak69** [tachiyomiorg/tachiyomi-extensions#9530]
### Source information

1st Kiss 1.2.17

### Steps to reproduce

Fix

### Expected behavior

I
![Uploading Screenshot_2021-10-18-16-52-18-897_eu.kanade.tachiyomi.debug.jpg…]()

### Actual behavior

![Screenshot_2021-10-18-16-51-49-660_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/88083213/137717695-37d2e435-bd30-46fb-b510-001e6dcd8ff1.jpg)

### Tachiyomi version

App version: 0.12.3-3903 

### Android version

Android 10

### Other details

Some time it bypass cloudflare but maximum time it doesn't bypass even if i open it in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9377
