### ISSUE TITLE
Scans Raw error

### ISSUE THREAD

**Issue by johnnylord1** [tachiyomiorg/tachiyomi-extensions#9542]
### Source information

Scans Raw 1.2.12

### Steps to reproduce

Refresh library

### Expected behavior

Refresh without any problems

### Actual behavior

Unable to resolve host "scansraw.com": No address associated with hostname

### Tachiyomi version

1.4.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me, try troubleshoot
