### ISSUE TITLE
Hentaidexy: No chapters found

### ISSUE THREAD

**Issue by Ixayoi** [tachiyomiorg/tachiyomi-extensions#9563]
### Source information

Hentaidexy v. 1.2.12

### Steps to reproduce

Chapters are there but it won't load up the recent release ones(won't update at all). 
Site is perfectly working without issue and so is the pathway towards the source.

### Expected behavior

New chapters are found and updated whenever the user decides to update it.

### Actual behavior

New chapters aren't found.

### Tachiyomi version

Stable v. 0.12.3

### Android version

Android v. 10

### Other details

![20211020_120753](https://user-images.githubusercontent.com/92878388/138134432-49849b45-017e-433b-a398-3404a0bb86ff.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Fixed by https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9948
If you are still facing issues, make sure to try [Troubleshooting steps](https://tachiyomi.org/help/guides/troubleshooting/) or ask for help at the #support channel in [Discord server](discord.gg/tachiyomi).
