### ISSUE TITLE
Uptdate failed

### ISSUE THREAD

**Issue by Ivirawr** [tachiyomiorg/tachiyomi-extensions#9564]
### Source information

Manganato

### Steps to reproduce

Uptdate library

### Expected behavior

New chapters

### Actual behavior

12 uptdates failed due to timeout, http error 520 and http error 500

### Tachiyomi version

1.4.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Timeout and 5xx errors are server side issues and there's nothing to be done in the extension to fix it. You need to wait until the website fix itself.
