### ISSUE TITLE
The extention TuttoAnimeManga don't work

### ISSUE THREAD

**Issue by HondaTooru97** [tachiyomiorg/tachiyomi-extensions#9574]
### Source information

TuttoAnimeManga

### Steps to reproduce

When I try to refresh the page this happens: 
![image](https://user-images.githubusercontent.com/87310799/138269089-30a905ed-89ee-4afc-b8a9-f608842766ad.png)

### Expected behavior

bug

### Actual behavior

bug

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HondaTooru97** [comment]
Hi, by any chance is there any news?

**Comment by alessandrojean** [comment]
No ETA. It will get fixed when someone have time and wants to work on it.
