### ISSUE TITLE
[IsekaiScans] Can't read or download manga, webview works.

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi-extensions#9578]
### Source information

IsekaiScan.com [English, 1.2.15]

### Steps to reproduce

1. Download or read any chapter from Max Level Returner

### Expected behavior

1. The manga should download/read.

### Actual behavior

1. You get a "No chapters found" error.

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11 [One UI 3.1]

### Other details

Webview works when viewing every single chapter, and wverything can be read inside webview, but it seems the extension/techiyomi can't find the same images.

I haven't tried this yet with other manga though, can update later and check.

Edit: some oyher manga have the same problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Since it can be fixed through library updates and clearing database I'll close this
