### ISSUE TITLE
Mangaowl search not finding manga immediately

### ISSUE THREAD

**Issue by RocGoddess** [tachiyomiorg/tachiyomi-extensions#9586]
### Source information

Mangaowl 1.2.22

### Steps to reproduce

Search for a manga on the global search and choose mangaowl

### Expected behavior

Manga should be first result on mangaowl.

### Actual behavior

It just shows an array of manga. I have to click on filter and click description to allow it to search in all fields.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Is there a way for sources to remember my search preferences and apply them for future use?

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by steffenbugenhagen** [comment]
I can confirm the problem.
The SortFilter seems not to be set correctly here as soon as only "Manga Title" and "Authors" is selected. Maybe because it is the default search?

**Comment by CVIUS** [comment]
again,
> already fixed by https://github.com/tachiyomiorg/tachiyomi/commit/9aa676333c1e9263138ae0fe55a9152dca33f867

update your app. this issue can be closed.
