### ISSUE TITLE
YAP24H

### ISSUE THREAD

**Issue by GasaiYunoV2** [tachiyomiorg/tachiyomi-extensions#9590]
### Source name

YAP24H

### Source link

https://yup24h.com/pt_br/

### Language

portuguese

### Other details

Yaoiiii

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Site is down (or changed their domain). Open a new issue if it starts to work again or if they changed the URL.
