### ISSUE TITLE
Mangahot

### ISSUE THREAD

**Issue by LPIP-Throwaway** [tachiyomiorg/tachiyomi-extensions#9604]
### Source name

mangahot

### Source link

https://mangahot.jp/

### Language

Japanese, 3 English

### Other details

Has an app in Japanese and can be read on the website 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment]
There exist and api at `api.mangahot.jp` which neko and TachiyomiSY's mangadex delegation make use of
