### ISSUE TITLE
Extension Not Loading Any Chapters

### ISSUE THREAD

**Issue by MataGoala** [tachiyomiorg/tachiyomi-extensions#9606]
### Source information

PornComix

### Steps to reproduce

1. Open extension
2.press new 
3. Comix Loading
4. Press on selected Comic
5. app open Comic
6. Comic failure - no Chapter Found

### Expected behavior

So when you open an comic it should load the chapters and you could see them throu the app

### Actual behavior

Every comic you open there is No Chapter even thou the webview is working

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Please fix this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#9538
