### ISSUE TITLE
GMANGA: Make url customizable

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi-extensions#9608]
### Describe your suggested feature

The site address link must be added in order to compress the site that sometimes occurs

  An example is a source (MangaLink)
![Screenshot_20211024-193222](https://user-images.githubusercontent.com/90999286/138603867-6370688f-9ec4-4570-a1dc-706252018bca.png)
![Screenshot_20211024-193226](https://user-images.githubusercontent.com/90999286/138603870-777f9f5e-37e9-47b3-bc79-916e52e8f3c0.png)

### Other details

Additional and backup site address

https://gmanga.org

and

https://gmanga.me

and 

https://gmanga.io

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
It's different websites?

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
