### ISSUE TITLE
Manhuas.net "No Chapters Found"

### ISSUE THREAD

**Issue by HyperFate** [tachiyomiorg/tachiyomi-extensions#9613]
### Source information

Manhuas.net 1.2.13

### Steps to reproduce

Whenever a new manga loaded the message "No chapter found" displayed with black list of chapters.

### Expected behavior

Show chapters of comic

### Actual behavior

"No chapter found" message displayed.

### Tachiyomi version

0.12.13

### Android version

Android 11

### Other details

Same issue as Wakamics extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
work for me try troubleshoot
