### ISSUE TITLE
Hiperdex "No Chapters Found"

### ISSUE THREAD

**Issue by REDAKUN** [tachiyomiorg/tachiyomi-extensions#9621]
### Source information

Hiperdex 1.2.16

### Steps to reproduce

Whenever a new manga loaded the message "No chapter found" displayed with black list of chapters.

### Expected behavior

Show chapters of manga / manhwa

### Actual behavior

"No chapter found" message displayed.

### Tachiyomi version

0.12.3

### Android version

android 10

### Other details

Same issue in a lot of extension .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Should be fixed #9948
If you are still facing issues, make sure to try [Troubleshooting steps](https://tachiyomi.org/help/guides/troubleshooting/) or ask for help at the #support channel in Discord server.
