### ISSUE TITLE
Anubis scans

### ISSUE THREAD

**Issue by shadoupasu** [tachiyomiorg/tachiyomi-extensions#9647]
### Source name

Anubis scans

### Source link

https://anubisscans.com/

### Language

Turkish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Kaeinzhu** [comment]
As the management of Günahkar Manga, we changed the name and our name was Anubis Scans.  As a result of this name change, we do not want and will not want the content on our own site to be placed on tachiyomi or any other application without our permission.  Please do not apply on behalf of us, the management team of Anubis Scans!

**Comment by shipoxx** [comment]
> As the management of Günahkar Manga, we changed the name and our name was Anubis Scans. As a result of this name change, we do not want and will not want the content on our own site to be placed on tachiyomi or any other application without our permission. Also, I contacted the tachiyomi official on discord and requested that our site be removed.  Thank you very much for helping me with this. 
> 
> Request for removal of old site's: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9060 
> 
> Please do not apply on behalf of us, the management team of Anubis Scans!


 if you have sent a team and prove that you are the owner of a site This should be closed 

@CarlosEsco

**Comment by shipoxx** [comment]
> > As the management of Günahkar Manga, we changed the name and our name was Anubis Scans. As a result of this name change, we do not want and will not want the content on our own site to be placed on tachiyomi or any other application without our permission. Also, I contacted the tachiyomi official on discord and requested that our site be removed.  Thank you very much for helping me with this. 
> > 
> > Request for removal of old site's: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9060 
> > 
> > Please do not apply on behalf of us, the management team of Anubis Scans!
> 
> 
>  if you have sent a team and prove that you are the owner of a site This request should be closed 
> @CarlosEsco
