### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#9655]
### Source information

https://mangaarabteam.com/

### Steps to reproduce

![2021](https://user-images.githubusercontent.com/93197738/139297919-c28370ff-67c0-4d79-80f2-3d9aa1cee589.jpg)

this is the problem ....

### Expected behavior

this shouldn't happen as it was working then this crash happen...

### Actual behavior

this happen instead

### Tachiyomi version

0.12.3

### Android version

Andriod 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
Same things happened month ago
It might be temporary idk

#8747

Can you edit the title.

**Comment by Seishirou101** [comment]
possible issue when source was named that, but there is a source/updated to use https://mangaarbteam.com now. You can make a new issue if the issue still persists.
