### ISSUE TITLE
Missing chapter of Manga 

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#9656]
### Source information

Shqqaa Manga 1.2.2

### Steps to reproduce

On opening the Manhwa / manga only 100 chapter from last are visible and others chapter from starting are missing.

### Expected behavior

All chapters should be visible.

### Actual behavior

![2](https://user-images.githubusercontent.com/93197738/139300850-ae3a801d-15e5-426d-b67c-8e8542e5f787.jpg)

### Tachiyomi version

12.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
This source hasn't been updated more than 10 months 

So it's kinda dead now, look for another source now 


Ps: This is the source that I mentioned to you a while ago, and you told me that you should judge whether he is dead or not @loocool2  can you close this, thank you.
