### ISSUE TITLE
Tappytoon.com - You are not authorised to view this.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi-extensions#9665]
### Source information

Tappytoon 1.2.2

### Steps to reproduce

Open any title in the tappytoon extension .
Open one of the free chapters or one which you have unlocked.

### Expected behavior

The chapter loads fine.

### Actual behavior

The chapter show you are not authorised to view this when you try to open or download a chapter.

### Tachiyomi version

0.12.3-3903 

### Android version

Android 11

### Other details

The chapter opens fine in webview.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Did you log in through the webview and restart the app afterwards?

**Comment by THElegend5** [comment]
Yeah didn't have this problem till today , even chapters without the lock are showing access denied.

**Comment by ObserverOfTime** [comment]
Looks like they're blocking the app's user agent on that endpoint. I can fix it tomorrow.

**Comment by THElegend5** [comment]
K thanks.

**Comment by THElegend5** [comment]
@ObserverOfTime btw is there any eta.

**Comment by ObserverOfTime** [comment]
As soon as someone merges it.

**Comment by THElegend5** [comment]
Oh ok thanks.
