### ISSUE TITLE
Mangasee Source error

### ISSUE THREAD

**Issue by vripside** [tachiyomiorg/tachiyomi-extensions#9667]
### Source information

Mangasee 1.2.26

### Steps to reproduce

1. Open tachiyomi
2. Open manga "The magical revolution of the reincarnated princess and the genius young lady" with the mangasee extension
3. Open latest chapter (11.1/11.2)

### Expected behavior

It should open normally in reader

### Actual behavior

Got this error instead
![Screenshot_20211030-004135_Tachiyomi](https://user-images.githubusercontent.com/93415982/139518401-b7325aec-009e-44ff-9ada-ba975e770499.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vripside** [comment]
I got these error too when updating all my mangas in my library ... but only with some of the mangas
![Screenshot_20211031-100646_Chrome](https://user-images.githubusercontent.com/93415982/139566328-955cab37-7834-41a9-bd2f-db961ffdb8b9.jpg)
![Screenshot_20211031-010836_Discord](https://user-images.githubusercontent.com/93415982/139566333-aefbed49-6d75-4d1d-bb47-345706976307.jpg)
![Screenshot_20211030-100000_Chrome](https://user-images.githubusercontent.com/93415982/139566334-be0d119e-5e47-40eb-a153-20077bc5ffe9.jpg)
![Screenshot_20211030-010737_Chrome](https://user-images.githubusercontent.com/93415982/139566336-755ab04c-0ab9-4047-bd63-af32b46b913e.jpg)

**Comment by paulo27ms** [comment]
The site and extension are working.
Go to discord if you need help troubleshooting.

**Comment by vripside** [comment]
Yes I already have gone to the discord and they said to put it in github

**Comment by arkon** [comment]
Closing in favour of #9982 since that title is more easily searchable.
