### ISSUE TITLE
Unable to scroll back up on specific webtoon chapter

### ISSUE THREAD

**Issue by rohrsben** [tachiyomiorg/tachiyomi-extensions#9669]
### Source information

Webtoons.com 1.2.32

### Steps to reproduce

1. Navigate to the webtoon Lore Olympus
2. Open chapter "Episode 17 Ch. 19" by any means (eg clicking it in chapter list, scrolling down to it from ch 18)
3. Make sure reading mode is set to "webtoon"
4. Attempt to scroll up into "Q&A Ch. 18"

### Expected behavior

You should be able to scroll all the way into the chapter

### Actual behavior

After one image (the final in Q&A) scrolling completely stops, and you are unable to scroll up any further

### Tachiyomi version

1.4.3

### Android version

Android 10

### Other details

This is occurring on TachiyomiJ2K, not the regular tachi app. In their issue page though, it said to report extension-specific bugs here. Seeing as I have never noticed this issue anywhere else -- be it chapter, manga, or extension -- I figured this was the better place. 

I think I attached a video of this happening, but it's not showing up on the preview, so I'm not sure if it worked. Apologies if it didn't. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is an app issue not an extension issue
