### ISSUE TITLE
MangaPill: No Chapter Found

### ISSUE THREAD

**Issue by game5413** [tachiyomiorg/tachiyomi-extensions#9675]
### Source information

MangaPill 1.2.5

### Steps to reproduce

At Library menu, pull from top / click updating library button.

### Expected behavior

Show new chapters of manga.

### Actual behavior

"No chapter found" message displayed.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Log file when updating list manga on library.

[tachiyomi_update_errors.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/7447437/tachiyomi_update_errors.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ringosham** [comment]
MangaPill seems to have gone through a whole UI update.
The extension need to be rewritten with the right css selectors
