### ISSUE TITLE
Extention is not listed in sources tab & Extention names are numbers in migration tab.

### ISSUE THREAD

**Issue by clarychristionc** [tachiyomiorg/tachiyomi-extensions#9683]
### Source information

"Bato.to 1.2.15", "Comick.fun 1.2.8"

### Steps to reproduce

1. Download the Application from https://tachiyomi.org/download .
2. Install bato.to, comick.fun, asura scans, webtoons.com and mangakakalot extentions.
3. Restore backup.
4. Update all the categories.
5. Manually replace manga that has errors.
6. Exit application.
7. Open Application.

### Expected behavior

Extention names are to be listed in sources and migration tabs.

### Actual behavior

1. In sources tab extention is not present.
2. In migration tab extention names are in numbers  

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details
- Migrate tab
![Screenshot_2021-10-31-11-43-39-54](https://user-images.githubusercontent.com/47944263/139571695-682195b3-e23d-432a-856a-bd72dd5636a6.jpg)
- Source tab
![Screenshot_2021-10-31-12-21-42-02](https://user-images.githubusercontent.com/47944263/139571960-e77d56b8-c65b-45c3-bf03-55c42248837d.jpg)
- Installed Extentions
![Screenshot_2021-10-31-12-22-39-19](https://user-images.githubusercontent.com/47944263/139571983-1da220b1-e960-41e5-bbeb-dfedbe422fa7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Turn on 18+

**Comment by clarychristionc** [comment]
It Worked, Thanks !
🤝

**Comment by clarychristionc** [comment]
It Worked, Thanks !
🤝
