### ISSUE TITLE
MangaRaw: Missing author in manga details screen

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#9690]
### Source information

MangaRaw 1.2.3

### Steps to reproduce

Author name is not displayed.

### Expected behavior

none

### Actual behavior

The original website shows the author’s name, but the extensions shows an unknown author, hope to fix it.
![image](https://user-images.githubusercontent.com/46775615/139623196-308bf582-45b4-46d4-ba36-b8ae0648009e.png)

### Tachiyomi version

0.12.3

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
This is outdated and can be closed. The original site is long gone.
