### ISSUE TITLE
[Manga Plus by SHUEISHA] changing langage not working

### ISSUE THREAD

**Issue by Cissoubaka** [tachiyomiorg/tachiyomi-extensions#9694]
### Source information

Manga Plus 1.2.25

### Steps to reproduce

Launching the extension without changing the langage, then change to french, and the extension stay in english

### Expected behavior

Changing the langage change the langage

### Actual behavior

No change for the langage are effective

### Tachiyomi version

0.12.3

### Android version

fire HD 8 2020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Where exactly are you expecting the language to change? In the extension settings...?

The source language only change the contents of the mangas, it's working as expected.

If you want to read the French content, you have to enable and access the Manga Plus under the *Français* section
