### ISSUE TITLE
Argos Scans: Login is required on the website

### ISSUE THREAD

**Issue by matheuswr89** [tachiyomiorg/tachiyomi-extensions#9703]
### Source information

Argos Scans 1.2.16

### Steps to reproduce

1. Open the app and locate the Argos Scans extension and click on it.

### Expected behavior

Expected of loading the mangas correctly

### Actual behavior

The mangas not loading.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

The site changed the way to access manga. Previously a token system was implemented, but now it has implemented a login system to access manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Already reported. We are waiting for them to stop changing their website constantly.

They changed it two times already after the extension was fixed.

**Comment by alessandrojean** [comment]
/edit-title "Argos Scans: Login is required on the website"
