### ISSUE TITLE
QiXiManhua : Domain Change

### ISSUE THREAD

**Issue by EricFoodTab** [tachiyomiorg/tachiyomi-extensions#9718]
### Source information

QiXiMnahua 1.2.3

### Steps to reproduce

1. Read a manhua from the latest section and try to access webview

### Expected behavior

manhua would be able to load like normal

### Actual behavior

it shows 404 error on tachiyomi and when try to access webview and it redirected me to a new website

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

new domain : m.mhxqiu.com   (漫画星球）

you can still access all manhua via their homepage and read it on webview but when you try to access their manhua in tachiyomi, it shows 404 error and it redirects you to a new website when try to access a manhua via webview from tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
After comparing url in tachiyomi and webview, I found url in tachiyomi lacks a trailing slash, so we get http 404. Fixing the url should make it work.
