### ISSUE TITLE
[REQUEST FOR ADD] [French] Mangas origines

### ISSUE THREAD

**Issue by Scorvic** [tachiyomiorg/tachiyomi-extensions#9719]
### Source name

Mangas origines

### Source link

https://mangas-origines.fr/

### Language

French

### Other details

Hello, I wanted to propose this site because it is among one of my best sites that is regularly updated and offers manga and Webtoons that are increasingly rare on many French sites, please take my request into consideration, thank you! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  I have checked that the extension does not already exist on the website [extensions](https://tachiyomi.org/extensions/) list or the app.

https://tachiyomi.org/extensions/#fr.mangasorigines

**Comment by Scorvic** [comment]
@curche thank you very much for the addition I just installed it and found it among the French extensions.
