### ISSUE TITLE
Scan-Manga: HTTP error 500

### ISSUE THREAD

**Issue by Scorvic** [tachiyomiorg/tachiyomi-extensions#9720]
### Source information

Scan-Manga 1.2.5

### Steps to reproduce

Try searching for a manga or webtoon from 

Explorer then source precisely on the Scan-Manga extension 
![Screenshot_20211102-065007](https://user-images.githubusercontent.com/93567405/139793427-0f843e8e-d104-4288-852d-77925fdf1d11.png)

then 
Go to the Webview and open in the browser. 
![Screenshot_20211102-064839](https://user-images.githubusercontent.com/93567405/139794858-6b097e45-70e3-4e72-bbc6-fb2eb8a89eff.png)
![Screenshot_20211102-063419](https://user-images.githubusercontent.com/93567405/139794884-03df8756-acaf-4e18-bb64-371a0c91266f.png)

### Expected behavior

The manga site would be able to load as usual.
![Screenshot_20211102-063419](https://user-images.githubusercontent.com/93567405/139793990-ca2e6d00-3ea4-473b-84a0-d15597556ab9.png)

### Actual behavior

It displays an error 500 on tachiyomi and when I try to access the web view and it redirects me to the site and it remains freeze so without any change of the site, then when I go to the open option in the browser at this time the site loads and is displayed but with a slightly different URL,  so we would deduce at a glance that the domain of the site has been modified. 

### Tachiyomi version

Tachiyomi 0.12.3

### Android version

Android 8.1

### Other details

Hello, I hope you will correct because this site is essential for manga and Webtoons, it is also one of the best sites among the best in France, it would be really important for us because it is always up to date on the wide catalog of manga and Webtoons available. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TomPitel** [comment]
Hi, I think this is an issue for a while and it's due to the owner of the website which blocks Tachiyomi IP. I think the source should be reported as obsolete. See issue #8326

**Comment by CarlosEsco** [comment]
They can't block tachiyomi ip because there is no tachiyomi ip

**Comment by TomPitel** [comment]
I'm just translating the French discussions on the other issue. Not sure how they blocked the requests then but result is that the extension is down for 6 months and nobody seems to have a way to fix that.

**Comment by gcoadour** [comment]
Has anyone tried to change the address?
If not, I'll do some tests on my own

**Comment by vetleledaal** [comment]
Can't get images to load on the site at all. The 500 issue is caused by the User-Agent, it can be changed as such:
```diff
diff --git a/src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt b/src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
index af61a8ed9..3dc5620ce 100644
--- a/src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
+++ b/src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
@@ -22,6 +22,7 @@ import org.jsoup.nodes.Element
 import org.jsoup.parser.Parser
 import rx.Observable
 import uy.kohesive.injekt.injectLazy
+import kotlin.math.absoluteValue
 import kotlin.random.Random

 class ScanManga : ParsedHttpSource() {
@@ -47,12 +48,16 @@ class ScanManga : ParsedHttpSource() {

     private val json: Json by injectLazy()

-    override fun headersBuilder(): Headers.Builder = super.headersBuilder()
+    // from Madara
+    private val userAgentRandomizer = " ${Random.nextInt().absoluteValue}"
+
+    override fun headersBuilder(): Headers.Builder = Headers.Builder()
         .add("Accept-Language", "fr-FR")
+        .add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/78.0$userAgentRandomizer")

     // Popular
     override fun popularMangaRequest(page: Int): Request {
-        return GET("$baseUrl/Tout-le-TOP.html", headers)
+        return GET("$baseUrl/TOP-Manga-Webtoon-3.html", headers)
     }

     override fun popularMangaSelector() = "div.image_manga a[href]"
```
