### ISSUE TITLE
mangastarz

### ISSUE THREAD

**Issue by satyogi** [tachiyomiorg/tachiyomi-extensions#9730]
### Source name

mangastarz

### Source link

https://mangastarz.com/

### Language

arabic

### Other details

the arabic website in app are old website and the new manga dont work this website is the best website in arabic manga 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
الموقع موجود منذ مدة طويلة.
![IMG_20211105_002641.jpg](https://user-images.githubusercontent.com/61906880/140433930-28204fc7-be42-45dd-8747-0e2fcb392c7c.jpg)
