### ISSUE TITLE
Some manga titled as "unknown"

### ISSUE THREAD

**Issue by vagabondshrimp** [tachiyomiorg/tachiyomi-extensions#9732]
### Source information

Mangadex

### Steps to reproduce

1. Add manga from source
2. Manga added to library

### Expected behavior

Shows manga with correct title and description

### Actual behavior

Manga title and description are both "unknown".
![20211104_171029](https://user-images.githubusercontent.com/74079735/140296487-c4b4875c-4442-4152-b91c-07aced84b995.jpg)
![20211104_171016](https://user-images.githubusercontent.com/74079735/140296508-aeb1d04b-f055-4b16-a0d8-46b976ded52d.jpg)

In webview:
![20211104_171119](https://user-images.githubusercontent.com/74079735/140296624-ba6fda1a-14e4-4bec-a64e-1473400d8311.jpg)
![20211104_171106](https://user-images.githubusercontent.com/74079735/140296644-23a35371-a21c-470d-8927-1a24ea2b7a6f.jpg)

### Tachiyomi version

preview r3931

### Android version

android 10

### Other details

Manga urls:
https://mangadex.org/title/a5cdfc61-43b0-4f87-b387-01e0949e2449
https://mangadex.org/title/ad5e875e-abaa-4fa3-ab75-b93a172ed35c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Works fine at my end. The Mangadex extension had an update recently which should have fixed this
Make sure you're on the latest version (1.2.143 as of writing)
https://tachiyomi.org/extensions/#all.mangadex

(That or Mangadex fixed the bad data themselves)

**Comment by vagabondshrimp** [comment]
Thanks for the response. Looks like it's from mangadex's side because I've installed/uninstalled the extension a bunch of times and it's still not fixed.

**Comment by curche** [comment]
Probably got cached in the app. Can try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) 
Specifically:
- Remove the manga with unknown titles from your library, if you have any
- Then go and clear database at More > Settings > Advanced > Clear Database

See if that fixes it

**Comment by vagabondshrimp** [comment]
Ok that fixes it...
It's weird tho, I definitely did troubleshoot before I submit a ticket, maybe because I didn't remove the manga from library??? Anyway, thank you!

**Comment by Riztard** [comment]
> Ok that fixes it... It's weird tho, I definitely did troubleshoot before submitting a ticket, maybe because I didn't remove the manga from library??? Anyway, thank you!

yea manga in library cant change title
