### ISSUE TITLE
1st kiss extension doesn't work 

### ISSUE THREAD

**Issue by DeltaBeam** [tachiyomiorg/tachiyomi-extensions#9734]
### Source information

1st kiss 1.2.17

### Steps to reproduce

The extension doesn't work

### Expected behavior

It should work

### Actual behavior

Its doesn't work

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

Http error: 403 check website in web view 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
> ` I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue`
