### ISSUE TITLE
Request for update of ShinobiScans source

### ISSUE THREAD

**Issue by Harukumaru** [tachiyomiorg/tachiyomi-extensions#9736]
### Source information

ShinobiScans 1.2.11

### Steps to reproduce

1) Browse source ShinobiScans
2) Open any manga/manhwa from the source
3) issue here: it says no chapter found (even though on their website you can read it)

### Expected behavior

It should show chapter and you should be able to read or downlaod them

### Actual behavior

A toast notification appears saying no chapter found

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

The server of their website was down for a couple of months because of a network issue with the ISP or something like that.
Now it's back and working again but on tachiyomi the issue still persist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This was fixed in #9948
