### ISSUE TITLE
ToonGod : Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by tobyzulka** [tachiyomiorg/tachiyomi-extensions#9738]
### Source information

ToonGod 1.2.13

### Steps to reproduce

1. Go to navigation Browse
2. Browse or latest source ToonGod

### Expected behavior

Successful show manga list

### Actual behavior

- In Fragment List : Failed to bypass Cloudflare
- In WebView : Error 1020

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11 - MIUI Global 12.5.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fawadkhan121** [comment]
Please someone fix this

**Comment by alessandrojean** [comment]
There's nothing that can be done on the extension side to fix Cloudflare issues. You have to wait until the website lower their protection or migrate to other sources. Also, 1020 error means your IP is banned.

**Comment by alessandrojean** [comment]
> Then is there a way to fix this problem?

You don't, like I said...

Use other sources or wait until the site owners lower the Cloudflare protection (very unlikely to happen).

**Comment by vetleledaal** [comment]
ToonGod is blocking requests containing the header `X-Requested-With: com.android.browser`. It doesn't appear to be an IP ban, but rather a firewall rule set up in Cloudflare.

**Comment by vetleledaal** [comment]
Fixed by https://github.com/tachiyomiorg/tachiyomi/commit/996f770935de78e6b0f4dfa13996c59f0f3dbac4
