### ISSUE TITLE
WeLoveManga : No result found

### ISSUE THREAD

**Issue by tobyzulka** [tachiyomiorg/tachiyomi-extensions#9739]
### Source information

WeLoveManga 1.2.8

### Steps to reproduce

1. Go to navigation Browse
2. Browse or latest source WeLoveManga 

### Expected behavior

Successful show manga list

### Actual behavior

- in Fragment List : No result found
- In WebView : Successful 

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11 - MIUI Global 12.5.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 12345axc** [comment]
Also happening on Android 12.
Tachiyomi version: Stable 0.12.3

----
Probably related to #9282.
