### ISSUE TITLE
no picture

### ISSUE THREAD

**Issue by enryu12** [tachiyomiorg/tachiyomi-extensions#9740]
### Source information

kiryuu 1.2.14

### Steps to reproduce

![Screenshot_20211105_104133](https://user-images.githubusercontent.com/93758312/140470851-e3b5c692-3a61-4e4d-9a21-7159003e3f4c.jpg)

### Expected behavior

pls solve this problem as fast as you can do it

### Actual behavior

i hope this problem not happen again

### Tachiyomi version

0.12.3

### Android version

8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
punyaku keload aja
ngasih info aja ga jelas

**Comment by enryu12** [comment]
Wkwkkw  gak keluar gambar nya di webview ok je

**Comment by Riztard** [comment]
> Wkwkkw gak keluar gambar nya di webview ok je

masalah sourcenya berarti kalo di webview juga gabisa

**Comment by enryu12** [comment]
Di webview ada gambar dekat app tachiyomi ni takde ,reload pun x boleh jugak

**Comment by Riztard** [comment]
isi yang jelas tuh `Steps to reproduce` nya

**Comment by enryu12** [comment]
Contohnya macam mana

**Comment by Riztard** [comment]
> Contohnya macam mana
 
1. masuk wc
2. buka celana
3. boker
