### ISSUE TITLE
kuaikanmanhua Chapter detection is invalid

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#9742]
### Source information

kuaikanmanhua 1.2.6

### Steps to reproduce

The previous version V1.2.5 is still normal, but it becomes invalid after the update.

### Expected behavior

none

### Actual behavior

none

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by leebvcc** [comment]
update kuaikanmanhua v1.2.6
Reloading 
Unexpected JSON token at offset 3: Expected quotation mark '"', but had 'd' instead
JSON input: [{id:aS,title:a$,cover_image_url:.....

read chapter
Unexpected JSON token at offset 6: Expected quotation mark '"', but had 'h' instead
JSON input: [{width:a,height:b,url:a_},{width:a,.....
