### ISSUE TITLE
Mangadex: missing chapters

### ISSUE THREAD

**Issue by junpet** [tachiyomiorg/tachiyomi-extensions#9743]
### Source information

MangaDex 1.2.143

### Steps to reproduce

Browse or add Fairy Tail: 100 Years Quest.

Extension shows chapter 88 as latest, but in web view chapters up through 94 show as available. Uploaders and group are the same.

### Expected behavior

Plugin chapter listing should match web site.

### Actual behavior

Chapters are missing.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
What language are you using?

**Comment by junpet** [comment]
English. I tried one week ago with the same result, refresh didn't helped. I tried multiple times today as well and now magically the missing chapters are appeared... Sorry for opening ticket.
