### ISSUE TITLE
Sushi-Scan

### ISSUE THREAD

**Issue by younesnoui336** [tachiyomiorg/tachiyomi-extensions#9744]
### Source name

Sushi-Scan

### Source link

https://sushi-scan.su

### Language

French

### Other details

Hi everyone, 
I want to request this source on Tachiyomi please: it's one of the best among those available in France. There are numerous manga by volume, which can be pretty convenient for reading and downloading manga.
Thanks to the person who will take the trouble to take care of it! 👍 💯 🥇 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
Pouvez-vous remplacer le titre par le nom de la proposition que vous avez demandée?

- suchi scan

**Comment by younesnoui336** [comment]
> Pouvez-vous remplacer le titre par le nom de la proposition que vous avez demandée?
> 
> * suchi scan

C'est fait ✅

**Comment by vetleledaal** [comment]
Appears to use WPMangaStream or WPMangaReader

**Comment by FlammFR** [comment]
🙏🙏
