### ISSUE TITLE
KlikManga : Domain Change

### ISSUE THREAD

**Issue by willyreza** [tachiyomiorg/tachiyomi-extensions#9755]
### Source information

KlikManga 1.2.12 (Indonesian)

### Steps to reproduce

1. Go to Tab Explore
2. To Tab Source
3. To Extension (KilkManga)

### Expected behavior

Normal

### Actual behavior

HTTP error 400 when try access source

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Old domain   --->https://klikmanga.com
New domain --->https://klikmanga.id

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by willyreza** [comment]
P

**Comment by willyreza** [comment]
![Screenshot_20211121-152010_Tachiyomi](https://user-images.githubusercontent.com/3974476/142754965-771c67d3-f853-44fa-a350-edb36946dbfb.jpg)

Image cannot be loaded😔

**Comment by willyreza** [comment]
![Screenshot_20211121-152306_Tachiyomi](https://user-images.githubusercontent.com/3974476/142755022-de0a00ba-5544-46d3-b6ac-4cfd3cbc642e.jpg)

Image cannot be loaded😔

**Comment by ZekkenID** [comment]
![Screenshot_2021-11-21-20-34-58-568_eu kanade tachiyomi](https://user-images.githubusercontent.com/23666289/142760182-7ffbe006-8818-43ea-9a26-71427276c34b.jpg)

@willyreza its fine in my extension
