### ISSUE TITLE
Cant update comics

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#9757]
### Source information

Sekte Komik 1.2.15

### Steps to reproduce

1. Update all comics

### Expected behavior

Cant updates comics

### Actual behavior

I cant updates all comics in this extension

### Tachiyomi version

0.12.3

### Android version

Android 7.1.1

### Other details

I tried to reinstall extension but it cant work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #11318
