### ISSUE TITLE
MangaDex source sort wrong when changed to latest chapter uploaded

### ISSUE THREAD

**Issue by Crasben** [tachiyomiorg/tachiyomi-extensions#9762]
### Source information

MangaDex 1.2.143

### Steps to reproduce

1. Install the source
2. Browse the mangas on the source
3. Change the filter to sort it by Chapter uploaded at
4. Check on a few of the first mangas if it appears in the latest chapters in the MangaDex page

### Expected behavior

It should show manga with the latest chapters uploaded when asked to sort by Chapter uploaded at.
![image](https://user-images.githubusercontent.com/38433553/140703305-94c8d8b9-5d10-458e-99de-887d68d89b9b.png)

### Actual behavior

Shows the mangas that are popula
![](https://cdn.discordapp.com/attachments/892167923702063176/907174899989225472/Screenshot_20211108-084801_Tachiyomi.jpg)
r.

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

It happens too in the Neko app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Unless the api changed it's working as designed.  The manga list  endpoint sorts by latest chapter irregardless of the language.
