### ISSUE TITLE
KastyScans

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#9768]
### Source name

KastyScans

### Source link

https://kastyscans.com.br/

### Language

Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The site uses Google Firebase to host their data, and it doesn't seen to have a direct API or something else that the extension can use to retrieve the information, unfortunately.

**Comment by Kaylenna** [comment]
Alright thank you ^^
