### ISSUE TITLE
Manhwa18 is broken (Error 404)

### ISSUE THREAD

**Issue by conztanz045** [tachiyomiorg/tachiyomi-extensions#9770]
### Source information

Manhwa18 1.2.6

### Steps to reproduce

Open manhwa18 extension

### Expected behavior

Works just fine

### Actual behavior

Getting error 404

### Tachiyomi version

0.12.2

### Android version

9

### Other details

![Screenshot_2021-11-09-14-04-05-59_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/79831076/140871318-8083ad32-831c-41e0-adf0-86201d13a734.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fawadkhan121** [comment]
It's a website issue and not the app

**Comment by smowtenshi** [comment]
The issue I have with Manhwa18.net is a failure with bypassing Cloudflare. I guess it's solely website's fault too?

```
! java.lang.Exception: Failed to bypass Cloudflare # Manhwa18.net (EN) - A Pervert's Daily Life
```

**Comment by fawadkhan121** [comment]
Chack now its working now

**Comment by conztanz045** [comment]
> Chack now its working now

No its not
