### ISSUE TITLE
Kiryuu : Image not loading & blank cover

### ISSUE THREAD

**Issue by herdax** [tachiyomiorg/tachiyomi-extensions#9773]
### Source information

Kiryuu : 1.2.14

### Steps to reproduce

1. Browse any manga eg: https://kiryuu.id/manga/the-heavenly-demon-destroys-the-lich-kings-murim/ 
2. Open chapter 

### Expected behavior

1. Cover become blank after manual update
2. Image not loading

### Actual behavior

Image should be loading and cover show up

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![Screenshot_2021-11-09-14-52-33-75_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/12084129/140884378-441e5664-5e1b-43db-9c49-18d5e13d7b00.jpg)
![Screenshot_2021-11-09-14-52-29-57_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/12084129/140884387-0acfe4f4-dbdc-4297-a619-a48f138c734f.jpg)
![Screenshot_2021-11-09-14-45-08-65_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/12084129/140884366-bc648f5e-786f-4517-8313-628a7bca5fc7.jpg)
![Screenshot_2021-11-09-14-45-26-56_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/12084129/140884372-845a5f70-9f57-481e-a828-cef9b5045d27.jpg) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
bikin satu problem satu tiket/issue
sama puanyaku cover sama komiknya bisa, coba troubleshoot
