### ISSUE TITLE
Welovemanga is broken

### ISSUE THREAD

**Issue by Yuumi012** [tachiyomiorg/tachiyomi-extensions#9774]
### Source information

Welovemanga 1.2.8

### Steps to reproduce

1. Open
2. Click something
3. Cant see any chapter

### Expected behavior

Works just fine

### Actual behavior

No showing any chapters

### Tachiyomi version

0.12.3

### Android version

Android 9

### Other details

![Screenshot_20211109-183436_Tachiyomi](https://user-images.githubusercontent.com/86627447/140917129-21a90d10-0add-436e-ae89-92a4239825b7.jpg)
![Screenshot_20211109-183419_Tachiyomi](https://user-images.githubusercontent.com/86627447/140917140-e480fc64-fd34-4cec-a289-a3a0a34d80eb.jpg)
![Screenshot_20211109-183433_Tachiyomi](https://user-images.githubusercontent.com/86627447/140917142-c8b0f450-2b05-4c81-99f4-a06d62d850d3.jpg)
![Screenshot_20211109-183416_Tachiyomi](https://user-images.githubusercontent.com/86627447/140917144-30eb50dc-2c1e-4452-9ff6-ea200246f80a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#9739
