### ISSUE TITLE
Dragontranslation is broken

### ISSUE THREAD

**Issue by LergRz** [tachiyomiorg/tachiyomi-extensions#9775]
### Source information

Dragontranslation 1.2.13

### Steps to reproduce

the extension doesn't load the covers

### Expected behavior

works fine and show covers

### Actual behavior

doesn't load, black screen

### Tachiyomi version

0.12.3

### Android version

android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
Extension removed for some time.

**Comment by arkon** [comment]
Reopening since the extension still exists.

**Comment by KasukeLp23** [comment]
@arkon Will they fix it?
