### ISSUE TITLE
New extension for Manhwas pls

### ISSUE THREAD

**Issue by LordoftheChaos** [tachiyomiorg/tachiyomi-extensions#9778]
### Source name

Manhwasmen

### Source link

https://manhwas.net/es

### Language

Spanish

### Other details

It is a collection page of manhwas and I would like to have it in tachiyomi to be able to keep up to date with the manhwas that I follow

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#5347
