### ISSUE TITLE
M-IQ 

### ISSUE THREAD

**Issue by AbdullahAl-Taie** [tachiyomiorg/tachiyomi-extensions#9780]
### Source name

M-IQ

### Source link

https://www.m-iq.me/?m=1

### Language

Arabic

### Other details

That's one of the best arabic manga sides.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#5169

> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
