### ISSUE TITLE
Sekaikomik block by cloudflare

### ISSUE THREAD

**Issue by Megumi-chon** [tachiyomiorg/tachiyomi-extensions#9790]
### Source information

Sekaikomik. 1.2.19

### Steps to reproduce

![Screenshot_20211111-074104](https://user-images.githubusercontent.com/94088435/141216213-9f4eb2cd-4353-42cf-9d02-3b8b12388663.png)

### Expected behavior

Block by cloudflare

### Actual behavior

Bug

### Tachiyomi version

0.12.3

### Android version

10

### Other details

Block by cloudflare

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The IP block is a website issue, and it's out of our control.
