### ISSUE TITLE
Lelscan-VF not working anymore

### ISSUE THREAD

**Issue by Floflo10** [tachiyomiorg/tachiyomi-extensions#9795]
### Source information

Lelscan-VF 1.2.4

### Steps to reproduce

From the explorer :
1. Tap on Lelscan-VF extention in the source tab
2. Wait for the manga list to load

### Expected behavior

We should view a list of all manga available on the site.

### Actual behavior

All the manga have black cover, no chapter and the same description which is list of recent manga.

![Screenshot_20211111-132947](https://user-images.githubusercontent.com/16256168/141298906-05915995-e16b-4d90-8ef3-028aa4b5058e.jpg)
![Screenshot_20211111-133021](https://user-images.githubusercontent.com/16256168/141298968-572fa161-a5de-4eb1-9988-5be08e66f43d.jpg)
 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Also, on all the manga in personal library, using "Web View" button redirect to the main page of the site.

![Screenshot_20211111-133539](https://user-images.githubusercontent.com/16256168/141299174-d40ace48-a908-4ed4-aa68-fc267bff71c6.jpg)
![Screenshot_20211111-133559](https://user-images.githubusercontent.com/16256168/141299182-05d9ed7e-2b3b-4394-9adc-85c38e2b2ead.jpg)

Thanks for your time !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Adrus99** [comment]
Hi,
The URL of the web site look wrong. It's https://lelscan-vf.cc (and not https://lelscan-vf.co).
If it's can help !
thanks
