### ISSUE TITLE
'Mangachill' No chapters found

### ISSUE THREAD

**Issue by THEBlackswordsMAN0** [tachiyomiorg/tachiyomi-extensions#9796]
### Source information

MANGACHILL 1.2.13

### Steps to reproduce

OPEN THE MANGA CHILL EXT AND THEN SELECT ANY MANGA ITS SHOWS ZERO CHAPTERS

### Expected behavior

ITS SHOULD SHOW THE ALREADY RELEASED CHAPTERS 

### Actual behavior

ITS SHOWING ZERO CHAPTER IN MANGACHILL EXTENSION.

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
"Manga Chill" but you write like you're yelling, sheesh

**Comment by arkon** [comment]
Wtf is this
