### ISSUE TITLE
CatManga has ended its service

### ISSUE THREAD

**Issue by AlifianK** [tachiyomiorg/tachiyomi-extensions#9801]
### Source information

CatManga 1.2.7

### Steps to reproduce

CatManga has ended its service and closed their website.

### Expected behavior

-

### Actual behavior

-

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Closed by #9800
