### ISSUE TITLE
KlikManga : HTTP Error 400

### ISSUE THREAD

**Issue by willyreza** [tachiyomiorg/tachiyomi-extensions#9803]
### Source information

KlikManga 1.2.12 (Indonesian)

### Steps to reproduce

1. Navigate to the source
2. Open extension

### Expected behavior

Should Show Manga

### Actual behavior

HTTP error 400 : Check website in webview

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Change Domain
Old domain --->https://klikmanga.com
New domain --->https://klikmanga.id

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
Don't close your issue and make a new one again.

**Comment by willyreza** [comment]
> Don't close your issue and make a new one again.

Ok
