### ISSUE TITLE
Manhwamanga.net : blank coverweb view working

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#9804]
### Source information

Manhwamanga.net 1.2.5

### Steps to reproduce

![Screenshot_20211113-154748_Tachiyomi](https://user-images.githubusercontent.com/57017947/141617335-b9969c62-8d89-4e68-b8b5-41f8b84a49f2.jpg)

Not loading on app but working fine in webview 

### Expected behavior

Manhwa should be visible on tachi app
The page is blank 

### Actual behavior

The manhwa should be seen on app because it is working in webview

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ifteqarahmed** [comment]
Even I'm having the same problem tried using VPN still shows blank and it works fine in webview

**Comment by kenewjr** [comment]
when they changed domain to https://mwmanhwa.net/?

**Comment by dreamhaven97** [comment]
Having same issue, hoping for a fix

**Comment by fawadkhan121** [comment]
Issue fixed
