### ISSUE TITLE
Manhuaus source is broken

### ISSUE THREAD

**Issue by Estiak69** [tachiyomiorg/tachiyomi-extensions#9806]
### Source information

ManhuaUS 1.2.14

### Steps to reproduce

K

### Expected behavior

To open

### Actual behavior

Black screen

### Tachiyomi version

App version: 0.12.3-3937 (standard, 7ce011015, 71, 2021-11-06T21:07Z) Android version: 10 (SDK 29) 

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
Same here
![Screenshot_2021-11-14-02-17-27-47_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/79831076/141654857-46403705-773c-4bb8-82c8-de3dcb5f1f69.jpg)

**Comment by Riztard** [comment]
work for us (me, jet, curche). try troubleshoot, if still not working go to discord for support
