### ISSUE TITLE
Always 403

### ISSUE THREAD

**Issue by nadenagi** [tachiyomiorg/tachiyomi-extensions#9807]
### Source information

1st kiss

### Steps to reproduce

Nothing needed to do 1st kiss extension always throws a 403 error

### Expected behavior

Get chapters

### Actual behavior

Not getting any chapters and I try to update every 20 mins

### Tachiyomi version

Latest

### Android version

Latest

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#9377
