### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR accessing MangaSee

### ISSUE THREAD

**Issue by bboyz269** [tachiyomiorg/tachiyomi-extensions#9823]
### Source information

MangaSee 1.2.26

### Steps to reproduce

Just browse MangaSee catalog (All or Latest).

### Expected behavior

Can view MangaSee catalog.

### Actual behavior

Got one of following errors randomly
1. Failed to connect to /2606:4700:3030::6815:23a9:443
2. Unable to parse TLS packet header

### Tachiyomi version

Preview r3950 (1e4d7f8c6)

### Android version

Android 11

### Other details

The error only happens with certain conditions

**On mobile data:**
| Device  | Client | Can access MangaSee |
| ------------- | ------------- | ------------- |
| PC  | Any  | ✅ |
| Android  | Any | ✅|

**On home wifi:**
| Device  | Client | Can access MangaSee |
| ------------- | ------------- | ------------- |
| PC  | Any  | ✅ |
| Android  | Edge for android | ✅ |
| Android  | Chrome (initially) | ❌ |
| Android  | Chrome (after reset system time, clear browsing history, caches, ...) | ✅ |
| Android  | Android webview | ❌(randomly) |
| Android  | Tachiyomi | ❌(randomly) |
| Android | Any with VPN on | ✅ |

It seems to be network problem but see how Edge and Chrome can access consistently, I wonder if there's anything we can do about how Tachiyomi connects.

// All clients are at latest version possible.
// Tried all options of "DNS over HTTPS" in Tachiyomi.
// No difference in network settings between android and PC (on the same subnet, same DHCP server, same DNS, no proxy / filewall whatsoever)

<details>
<summary>Some screenshots</summary>

![1637026181178](https://user-images.githubusercontent.com/4453811/141879411-6a7650b8-34bf-45e7-9241-0a4becc0e09b.jpg)

![1637026181181](https://user-images.githubusercontent.com/4453811/141879419-312b122d-6f5b-45bf-a4a9-0b8ab452fae8.jpg)

![1637026181183](https://user-images.githubusercontent.com/4453811/141879420-e8e81266-f650-4628-997a-bc3178c02aef.jpg)

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is a known issue with some ISPs/countries. There's no plan to "fix" this on the app/extension side as it's ultimately censorship within your network, so you could consider using a VPN or using a different network.
