### ISSUE TITLE
Manga Park V3

### ISSUE THREAD

**Issue by vncrack** [tachiyomiorg/tachiyomi-extensions#9824]
### Source information

MangaPark V3 1.2.12

### Steps to reproduce

Update new chapters

### Expected behavior

Receive updated chapters

### Actual behavior

Receive "No chapters found"

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Webview works normally
![Screenshot_20211116-235837_Tachiyomi](https://user-images.githubusercontent.com/78357927/142030430-c4c96737-effc-48d7-af58-5984bfb0eef3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
The site had a update. Can you check if anything else is broken?

**Comment by vncrack** [comment]
> The site had a update. Can you check if anything else is broken?

I don't know if this count but I noticed when I update mangas in the library, my phone can get quite hot and changing to different tabs or any tasks become quite glitchy

**Comment by iprash2375** [comment]
M
When I got to update the library, it shows update failed with mangapark v3. What should I do.

**Comment by gan-of-culture** [comment]
Wait for update or migrate

**Comment by gan-of-culture** [comment]
@FourTOne5 will you update the extension?

**Comment by FourTOne5** [comment]
> @FourTOne5 will you update the extension?

If no does after a week.

**Comment by Jaykoerner** [comment]
ass a temp measure since I wasn't getting anywhere with editing the parser I moved the extension to the legacy front end, the only changes i saw where edits to the page structure for the chapter lists, mostly in how other languages are displayed, but some of the info used before now has to be requested to show on the page. anyways reverting to the legacy URL fixes it atm
