### ISSUE TITLE
MangaTeca Search

### ISSUE THREAD

**Issue by GMak9** [tachiyomiorg/tachiyomi-extensions#9845]
### Source information

MangaTeca 1.2.14

### Steps to reproduce

Click on the manga title 
Try looking for similar manga

### Expected behavior

Find the same sleeve in this source or similarFind the same mango in this source or similar. 

### Actual behavior

Currently it is impossible to find Manga in this source unless by itself. Briefly, there is a problem in global search from other sources. 

### Tachiyomi version

0.12.3

### Android version

Android 7.1.1

### Other details

Problems in global research. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please give examples of titles you're trying to find, otherwise this issue report is useless. Also, this source is known for blocking Tachiyomi requests and have a higher Cloudflare protection, nothing we can do about it.

Also, the global search problem is already reported and it's related to the source filters in the app.
