### ISSUE TITLE
MangaStic

### ISSUE THREAD

**Issue by MangaHeart** [tachiyomiorg/tachiyomi-extensions#9846]
### Source information

MangaStic

### Steps to reproduce

If I search a certain story and if it will appear in MangaStic, the story will appear to have no chapters.

### Expected behavior

The stories have chapters
![image](https://user-images.githubusercontent.com/94607520/142447659-a81bb9f4-1cb0-4c0d-b8a1-6f6c4be7df96.png)

### Actual behavior

All stories have no chapters
![image](https://user-images.githubusercontent.com/94607520/142447027-41b8dadf-2add-44ef-8403-ff3604bf783b.png)

### Tachiyomi version

0.11.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by StephenTheMoldovan** [comment]
seconding this bug

**Comment by Seishirou101** [comment]
Should be fixed #9948 as it looks to work for me
If you are still facing issues, make sure to try [Troubleshooting steps](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) or ask for help at the #support channel in Discord server.
