### ISSUE TITLE
Disaster Scans - Problem with Bypassing Cloudfire

### ISSUE THREAD

**Issue by CerealKiller7** [tachiyomiorg/tachiyomi-extensions#9852]
### Source information

Disaster Scans 1.2.13

### Steps to reproduce

Refreshing a manga from this source. 

### Expected behavior

The manga's chapter being updated.

### Actual behavior

The extension not finding any chapter

### Tachiyomi version

Tachiyomi J2K 1.4.3

### Android version

Android 11

### Other details

When you open any manga from this source it shows "No chapters found" error. Even after trying to read it using WebView the chapters weren't showing. Don't know if it is a problem of the extension or the app as the website, from their discord server, is having some issues, but don't know if it has any correlation with this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tyme2tb** [comment]
Having the same issue

**Comment by CerealKiller7** [comment]
Update 1.2.13 - While the problem of  "java.lang.Exception: Impossible to bypass Coudflare" doesn't occur anymore the mangas that are found in the source are without chapters. This is not a problem of the app it is of the website as it is having a problem loading the chapter list. Probably will close this issue soon.

**Comment by tyme2tb** [comment]
Loading chapter list in webview appears to be work g for me right now after I cleared cash, but it is still showing no chapters

**Comment by Matakor** [comment]
Can confirm. Clearing cache/data for both Tachiyomi and Android system WebView allows me to view the manga via WebView, but Tachiyomi continues to show no chapters, even after force stop.

**Comment by CerealKiller7** [comment]
Even after clearing the cache of the app and the WebView app, I wasn't able to see the chapters neither on the app nor in WebView. Even after clearing the cache partition of the phone was stumbling on the same problem.

**Comment by CerealKiller7** [comment]
The problem was fixed, thank you.
