### ISSUE TITLE
Bilibili different chapter numbering than website

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#9857]
### Source information

Bilibili comics 1.2.7

### Steps to reproduce

1. Open This Cultivator Came From The Future in bilibili

### Expected behavior

Same chapter numbering as on the website

### Actual behavior

Different numbering than on website

### Tachiyomi version

sy r414

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If you're talking about missing recent chapters, they're probably exclusive from their app and they isn't displayed at the extension.

**Comment by FourTOne5** [comment]
This is APIs fault best way to fix is this to not specify chapter number from API and let Tachi handle it.

**Comment by alessandrojean** [comment]
Handling it in the extension would lead to the problem that there's no way to know if the series starts the numbering in 0 or 1 for the first chapter, like in the example provided.

**Comment by alessandrojean** [comment]
This can be probably fixed by using the `short_title` attribute from the API response. I will make a fix.
