### ISSUE TITLE
Mangadraft

### ISSUE THREAD

**Issue by Scorvic** [tachiyomiorg/tachiyomi-extensions#9860]
### Source name

Mangadraft

### Source link

https://www.mangadraft.com/

### Language

French

### Other details

Hello, I wanted to propose this site because it is among one of my best sites that is regularly updated and offers manga and Webtoons that are increasingly rare on many French sites, please take my request into consideration, thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Duplicate of #5390

**Comment by Scorvic** [comment]
@alessandrojean unfortunately it is not there in the list of Tachiyomi extensions I looked for it several none, if it was available I was not going to make this request, otherwise if you have the extension can you mention it to me so that I download it from here because on the application I do not find any.

**Comment by Scorvic** [comment]
![Screenshot_20211124-130047](https://user-images.githubusercontent.com/93567405/143234743-0d512f1f-e2d6-45a9-8794-1b4dfde3fb15.png)

@alessandrojean, look at the screenshot there is no extension of Mangadraft, I believe that the request was made but was not realized or it was forgotten believing that it was realized, that is why the extension is not there.

**Comment by alessandrojean** [comment]
You need to wait until someone wants to work on it. This issue was close because it was a duplicate and there's already another open issue requesting this website. No ETA and please do not ping me.

**Comment by Scorvic** [comment]
Okay, sorry if you didn't appreciate that I tagged you otherwise it was the only way to make you quickly browse my comment because I didn't really understand your comment since you hadn't detailed everything about your answer, otherwise thank you and sorry again.
