### ISSUE TITLE
MangaGreat, manga1st and ManhuaUS - pages not found

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#9862]
### Source information

MangaGreat 1.2.12, manga1st 1.2.12, ManhuaUS 1.2.14

### Steps to reproduce

Look ant chapter in manhua on listed sources.

### Expected behavior

Read and download normally.

### Actual behavior

Extensions aren't detecting pages in the latest chapters

### Tachiyomi version

0.12.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1 issue per issue.
