### ISSUE TITLE
MangaGreat - pages not found

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#9865]
### Source information

MangaGreat 1.2.12

### Steps to reproduce

Look at chapter in manhua on listed source.

### Expected behavior

Read and download normally.

### Actual behavior

Extension isn't detecting pages in the latest chapters

### Tachiyomi version

0.12.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FaTe-code** [comment]
Also getting the same problem
