### ISSUE TITLE
Asura Scans - No Pages Found Error

### ISSUE THREAD

**Issue by KaoticOblivion** [tachiyomiorg/tachiyomi-extensions#9868]
### Source information

Asura Scans 1.2.18

### Steps to reproduce

1. Open Browse -> Sources tab in Tachiyomi
2. Open Asura Scans source list or any followed manga from the source
3. Open or download any chapter
4. Receive error "No Pages Found"

### Expected behavior

What *should* happen is the chapters should be able to be downloaded/opened for reading

### Actual behavior

unable to view contents of any chapter for any series  from Asura

### Tachiyomi version

0.12.3

### Android version

Andriod 11

### Other details

Pages do *eventually* load in webview, though it does take a while to do so. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SoloLeveller1** [comment]
Some manga that were already added to library show up as not added when browsing through the source. When again adding a manga to library, duplicate gets created with no chapters read.

**Comment by Astrokinng** [comment]
Even after updates it's the same
