### ISSUE TITLE
Mangaowl chapters are gone but in webview, all of them are there.

### ISSUE THREAD

**Issue by MangaHeart** [tachiyomiorg/tachiyomi-extensions#9871]
### Source information

MangaOwl 1.2.22

### Steps to reproduce

1. First open the tachiyomi app then wait for all subscribed chapters to load.
2. Observe properly that all stories in MangaOwl that has only 1 chapter left.
3. Visit the MangaOwl webview to see if all of the chapters also disappeared (apparently not).
4. Issue: The chapters are available on the WebView but not on the tachiyomi app itself.

### Expected behavior

All chapters are completed and the same as the webview.
![image](https://user-images.githubusercontent.com/94607520/142752417-8b8a4104-eedd-47b4-b5fa-45aa21325e27.png)
![image](https://user-images.githubusercontent.com/94607520/142752423-ed0d93a0-f36c-4014-8e2d-eb6a3fc637d6.png)

### Actual behavior

The chapters are gone in the tachiyomi app but in the webview version, all of them are there.
![image](https://user-images.githubusercontent.com/94607520/142752373-25f8bab5-8e14-424c-a70d-421e340c3160.png)
![Uploading image.png…]()

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Littlehuman19** [comment]
I have the same problem right now

**Comment by MangaHeart** [comment]
> I have the same problem right now

I don't know if it is the same issue on other sources but most stories in mangaowl is like that.

**Comment by Littlehuman19** [comment]
> 
I've been checking other sources but they're okay so maybe mangaowl is having a problem with their site.

**Comment by Mooni08** [comment]
I thought I was the only one having this same issue, is it a bug or something cause I literally tried everything but it's still showing me the same thing

**Comment by Mooni08** [comment]
Same here, is there a fix to it or something?

**Comment by MangaHeart** [comment]
I think there is a way to fix it but lets not hope that it will end like other sources.

**Comment by Littlehuman19** [comment]
I hope it will not be like manhuascan source

**Comment by arkon** [comment]
Please remember that GitHub issues are not a discussion forum. Please do not comment if you do not have anything insightful to add.
