### ISSUE TITLE
No pages found manga-raw.club and kissmanga.in

### ISSUE THREAD

**Issue by Chaosmayme** [tachiyomiorg/tachiyomi-extensions#9872]
### Source information

Manga-raw.club and kissmanga.in

### Steps to reproduce

It's normal before the update

### Expected behavior

Normal read and download

### Actual behavior

It's not loading new pages it's says no pages found

### Tachiyomi version

App version: 0.12.3-3977 (standard, 430ff8019, 71, 2021-11-20T21:08Z)

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
1 source per issue

**Comment by AaronDragneel** [comment]
I'm not able to read any manga or manhwa from manga-raw bcuz its shows no page found
