### ISSUE TITLE
Pururin: Chapter Error

### ISSUE THREAD

**Issue by AimannQn** [tachiyomiorg/tachiyomi-extensions#9875]
### Source information

Pururin 1.2.5

### Steps to reproduce

1. Open Doujin
2. Choose which chapter trying to read

### Expected behavior

I can read other chapter from 1 doujin

### Actual behavior

I can't read other chapter from 1 doujin. it say error 500. If i refresh the doujin, chapter 1-10 will disappear.

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11

### Other details

here when i ask in pururin

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
Chapters are no longer grouped since 726813f019c1d6f91dac92078995243214bd00e7

**Comment by AimannQn** [comment]
> Chapters are no longer grouped since [726813f](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/726813f019c1d6f91dac92078995243214bd00e7)

But the chapter from the website are group tho? didn't extension suppose to use their site api?

**Comment by ObserverOfTime** [comment]
The website API itself doesn't group the chapters. I don't know how their frontend does it.

**Comment by AimannQn** [comment]
> The website API itself doesn't group the chapters. I don't know how their frontend does it.

![Screenshot_20211122-235104_Chrome](https://user-images.githubusercontent.com/84202326/142892912-b50e3ad3-a06e-4a8f-9eaf-b11f2ccebb5b.jpg)
That's aren't group chapter?

**Comment by CarlosEsco** [comment]
1.  why would you ask them, as tachiyomi is 3rd party.
2.  Don't post nsfw pictures on github.  Crop the image

**Comment by AimannQn** [comment]
> 1. why would you ask them, as tachiyomi is 3rd party.
> 2. Don't post nsfw pictures on github.  Crop the image

My Bad. didn't know that.

**Comment by ObserverOfTime** [comment]
> That's aren't group chapter?

That's the frontend, not the API.
The extension uses the API now.

**Comment by ObserverOfTime** [comment]
Before the extension was updated, yes.
