### ISSUE TITLE
No page found

### ISSUE THREAD

**Issue by Rouruki** [tachiyomiorg/tachiyomi-extensions#9876]
### Source information

Manga-raw.club

### Steps to reproduce

No pages found

### Expected behavior

N/A

### Actual behavior

N/A

### Tachiyomi version

0.12.3

### Android version

Poco Phone F1

### Other details

No page found on every manga or manhua that I bookmark. The site is fine when visited but on the app cannot read the new chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AaronDragneel** [comment]
I'm having this problem too.

**Comment by AaronDragneel** [comment]
(Manga-Raw.club) Extension is opening like normal but whenever i try to read a manga or manhwa it says "No Page Found"

**Comment by ara8ara** [comment]
![Screenshot_20211121-234813](https://user-images.githubusercontent.com/15099415/142771247-60f477d2-96c4-48a4-bfd5-aa46cbc92bcb.png)

**Comment by NidPlays** [comment]
The chapter itself seems to load now though

**Comment by AaronDragneel** [comment]
Yeah now i'm also having this issue. Everytime i try to update a manga it shows "Attempt to invoke the virtual method"

**Comment by AaronDragneel** [comment]
> ![Screenshot_20211121-234813](https://user-images.githubusercontent.com/15099415/142771247-60f477d2-96c4-48a4-bfd5-aa46cbc92bcb.png)

I'm also having this issue now...

**Comment by Rouruki** [comment]
The issue came back again.
