### ISSUE TITLE
No page found 

### ISSUE THREAD

**Issue by pridechampionpowder** [tachiyomiorg/tachiyomi-extensions#9878]
### Source information

Mangaowl

### Steps to reproduce

I dunno

### Expected behavior

The pages should open and should've showed

### Actual behavior

Instead it didn't and every time i open a story all it says is no page found

### Tachiyomi version

1.4.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#9871
