### ISSUE TITLE
Asura Scans No Page found Error 

### ISSUE THREAD

**Issue by hemanthmannam** [tachiyomiorg/tachiyomi-extensions#9886]
### Source information

Asura Scans 1.2.18

### Steps to reproduce

Open Asura Scans 
Pick any Manhwa
Try to read 

### Expected behavior

Pages should render 

### Actual behavior

No Pages Error, Unable to Download 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hendiadyoin1** [comment]
This Issue still persists when trying to download a chapter.

**Comment by hemanthmannam** [comment]
> This Issue still persists when trying to download a chapter.

Downloading is working for me now

**Comment by Hendiadyoin1** [comment]
\*Now\* it seems to work too
Right after the update it didn't for some reason
(Also same manhua...)
