### ISSUE TITLE
Phoenix Fansub HTTP error 404 

### ISSUE THREAD

**Issue by Errede08** [tachiyomiorg/tachiyomi-extensions#9888]
### Source information

Phoenix Fansub 1.2.13

### Steps to reproduce

cant read any of the manga there every single one gives HTTP error 404  even with the webview 

if you try to read it on your browser it does work so i guess this is an issue with the extension

### Expected behavior

the chapters should show up and be able to read them

### Actual behavior

HTTP  Error 404

### Tachiyomi version

0.12.3

### Android version

MIUI Global 12.5.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Errede08** [comment]
![image_2021-11-21_145652](https://user-images.githubusercontent.com/94802414/142775277-e0ef64d4-20f1-47a1-a089-b8a0eab30bca.png)

**Comment by simonflo-afk** [comment]
Pueden arreglar el problema por favor quiero seguir leyendo los capítulos
