### ISSUE TITLE
Only chapters on the first page of the source are displayed.

### ISSUE THREAD

**Issue by nichols013** [tachiyomiorg/tachiyomi-extensions#9892]
### Source information

Meus Mangás 1.2.3 

### Steps to reproduce

1. Open source library;
2. Choose any manga.

### Expected behavior

When opening any manga, all available chapters should be available.

### Actual behavior

Instead of all available chapters being available, only the last 25 (belonging to the first page of WebView) appear.

### Tachiyomi version

0.12.3 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> I have updated all installed extensions.

You clearly did not update the extension since the last available version is v1.2.7, released today.
