### ISSUE TITLE
Mangas Origines X

### ISSUE THREAD

**Issue by Scorvic** [tachiyomiorg/tachiyomi-extensions#9893]
### Source name

Mangas Origines X

### Source link

https://x.mangas-origines.fr/

### Language

French

### Other details

Hello! This site is the Hentai and Pornhwa version of the Mangas-origines.fr, are different versions because they do not offer the same content despite it is the site belongs to the same person, I hope that my request will be taken into account as much as possible, thank you in advance. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Scorvic** [comment]
> /edit-title "Mangas Origines X"

Okay, I understood.

**Comment by H3ll-King** [comment]
Need this extension, where find it or stil in dev ?
