### ISSUE TITLE
Can't use filter on Hitomi.la

### ISSUE THREAD

**Issue by BTheBlood** [tachiyomiorg/tachiyomi-extensions#9901]
### Source information

Hitomi.la 1.2.11

### Steps to reproduce

1. Open any Hitomi language extension.
2. Try to use filter.
3. Get HTTP 404 error.

![Screenshot_20211123-055105](https://user-images.githubusercontent.com/91033720/142947587-98f4d40d-8834-4eea-add3-9767eccb49be.png)

### Expected behavior

can use filter like other extension.

### Actual behavior

HTTP 404 error please check webview

### Tachiyomi version

Stable 0.12.3

### Android version

Android 6.0.1 

### Other details

I can still search and open it normaly except filter it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Chan220** [comment]
Some chapter cannot load the image / page

**Comment by crse** [comment]
Sort by Date Added and Popularity also broken at the moment.
