### ISSUE TITLE
Penlab - A Filipino Source

### ISSUE THREAD

**Issue by a-france** [tachiyomiorg/tachiyomi-extensions#9902]
### Source name

Penlab

### Source link

https://penlab.ink

### Language

Filipino

### Other details

A source full of Filipino comics.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by otterlottery** [comment]
i agree. since penlab doesn't have an app itself

**Comment by Cloudre** [comment]
i hope it will be added too
