### ISSUE TITLE
Mixed manga - download or read chapter error

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#9903]
### Source information

Mixed manga 1.2.13

### Steps to reproduce

Download chapter or read chapter error. 
Read chapter not showing image but only retry. But on webview its fine. 
Download only show the total image but unable to download chapter successfully

### Expected behavior

Can download or read chapter

### Actual behavior

Download chapter or read chapter error. 
Read chapter not showing image but only retry. But on webview its fine. 
Download only show the total image but unable to download chapter successfully

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rouruki** [comment]
Same goes to manga-raw.club few hours ago till now. It also happen back then 2 days ago.

**Comment by samanta-widjaja** [comment]
Today suddenly it work for me. Does it fixed already?
