### ISSUE TITLE
MangaRaw: The latest page only show the newcomer manga 

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#9909]
### Source information

Mangaraw 1.2.3

### Steps to reproduce

Opening the latest tab

### Expected behavior

Seeing manga updates in the site

### Actual behavior

The latest page only show the new manga with one chapter only (新刊コミック) which can be seen from the link (https://manga1001.com/newmanga/)
But manga that already have chapters like onepiece doesn't appear in the latest page despite being having chapter released recently

### Tachiyomi version

Latest

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by armangido** [comment]
I doubt someone would optimize the code for this, it load fine for me no freeze whatsoever.

**Comment by sohilsayed** [comment]
> I doubt someone would optimize the code for this, it load fine for me no freeze whatsoever.

I updated the issue description for better understanding
