### ISSUE TITLE
Sugar Babies scan gives error

### ISSUE THREAD

**Issue by Eastral** [tachiyomiorg/tachiyomi-extensions#9910]
### Source information

sugar babies 1.2.13

### Steps to reproduce

Gives http error 404 while webview is normal

### Expected behavior

show manga list

### Actual behavior

giving http error 404

### Tachiyomi version

0.12.3

### Android version

Android version 8.1.0

### Other details

Webview from bookmarked manga only shows page is lost

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing in favor of #9911.
