### ISSUE TITLE
[Mangadex] add hasAvailableChapters filter

### ISSUE THREAD

**Issue by INSANEMODE** [tachiyomiorg/tachiyomi-extensions#9919]
### Describe your suggested feature

Looking at the api changelog for mangadex, it looks like they added a "hasAvailableChapter" filter recently.

I assume it means it will filter out series with no chapters.(probably for removed/licenced stuff, for the most part?)

Would this be something that would be easy to implement?

### Other details

Source for where I saw it mentioned:

 https://discord.com/channels/403905762268545024/839817812012826644/907223111890505739

![Screenshot_20211123-201855](https://user-images.githubusercontent.com/10606102/143160014-51ff3116-7b4c-4076-89ca-dd734e4b83f6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Cons of adding this is the manga would just not show at all when a user searches for it.

**Comment by INSANEMODE** [comment]
> Cons of adding this is the manga would just not show at all when a user searches for it.  

This is true. I should have been more clear. 

I want this to be a user selectable filter, kind of like the content rating or status check boxes.

Not that It should apply to all searches by default.

**Comment by alessandrojean** [comment]
I am working on the filter, but keep in mind `hasAvailableChapters` doesn't take into consideration the language, it only checks if it has any chapter of any language, so you can still find some titles that will appear when the filter is checked but don't have chapters in the selected language.

**Comment by CarlosEsco** [comment]
@alessandrojean you should be able to add availableTranslatedLanguage[]
