### ISSUE TITLE
Disaster Scan - No Chapters found Issue

### ISSUE THREAD

**Issue by I-Am-C0der** [tachiyomiorg/tachiyomi-extensions#9921]
### Source information

Disaster Scans 1.2.13

### Steps to reproduce

1.Install "Disaster Scans" Extension (Extension Version - 1.2.13)
2.Open any new manhua from Disaster Scan Source (-or-) try to update any Disaster Scan Manhua existing in library.

### Expected behavior

Chapter should be loaded or get updated.

### Actual behavior

**No chapters found**
**But able to see chapters in WebView**

App Source
![App](https://user-images.githubusercontent.com/51527183/143272012-2b0ec303-56ca-4e0f-937f-f84b15ac47bf.jpg)
WebView
![WebView](https://user-images.githubusercontent.com/51527183/143272115-b7e2d3a8-616b-4e37-bb8d-b70f1eb0c9ab.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Yogimoturi** [comment]
Yes it's still broken it isn't fixed yet watch status update channel in discord server for updates
