### ISSUE TITLE
Remove DoujinDesu

### ISSUE THREAD

**Issue by Seishirou101** [tachiyomiorg/tachiyomi-extensions#9924]
### Describe why this should be added

Proof of ownership was provided in discord.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by crse** [comment]
This website host other groups works, even possible removal of original fan translation credit.

Example:
https://exhentai.org/s/1831bee0d2/1953385-21 Tranalation by BigBro000
https://doujindesu.id/2021/07/25/ane-suki/

https://exhentai.org/g/2008350/4bb0fac9dd/ Translation by Gagak_Ireng
https://doujindesu.id/2021/09/13/chitanda-eru-no-sainan/ (credit removed and replaced by doujindesu credit)

https://exhentai.org/g/1975498/48c5b097e1/ Translation by IsengIsengTL
https://doujindesu.id/2021/08/04/tsumi-no-hako/

https://exhentai.org/g/1908400/cb88dd23d1/ Translation by 15tl_ID
https://doujindesu.id/2021/08/07/live-meat-04/ (credit removed and replaced by doujindesu credit)

**Comment by Soitora** [comment]
> This website host other groups works, even possible removal of original fan translation credit.
> 
> Example:
> https://exhentai.org/s/1831bee0d2/1953385-21 Translation by BigBro000
> https://doujindesu.id/2021/07/25/ane-suki/
> 
> https://exhentai.org/g/2008350/4bb0fac9dd/ Translation by Gagak_Ireng
> https://doujindesu.id/2021/09/13/chitanda-eru-no-sainan/ (credit removed and replaced by doujindesu credit)
> 
> https://exhentai.org/g/1975498/48c5b097e1/ Translation by IsengIsengTL
> https://doujindesu.id/2021/08/04/tsumi-no-hako/
> 
> https://exhentai.org/g/1908400/cb88dd23d1/ Translation by 15tl_ID
> https://doujindesu.id/2021/08/07/live-meat-04/ (credit removed and replaced by doujindesu credit)

Thank you, the request for removal is thus denied
