### ISSUE TITLE
ملوك الياوي

### ISSUE THREAD

**Issue by BungeeGUN** [tachiyomiorg/tachiyomi-extensions#9927]
### Source name

ملوك الياوي

### Source link

https://thekings.forumcommunity.net/m/

### Language

Arabic

### Other details

A great source for Bl  and GL manhwa and manga in Arabic. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
على ما يبدو ان هذا منتدى ولاتوجد طريقة لعرض محتوى بشكل مباشر ويتطلب حساب ايضاً
موقع غريب وسيتم غلق هذا طلب.

- It's a forum
