### ISSUE TITLE
Manhwa18 showing error 404

### ISSUE THREAD

**Issue by staudond** [tachiyomiorg/tachiyomi-extensions#9935]
### Source information

Manhwa18 1.2.6

### Steps to reproduce

Open manhwa18 extension

### Expected behavior

Show manga

### Actual behavior

Gets error 404, webview works fine

### Tachiyomi version

0.12.3

### Android version

11

### Other details

![screenshot](https://user-images.githubusercontent.com/36927218/143599392-4a2d8ea7-e67d-4ea5-b8f7-f42575916c96.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by armangido** [comment]
Working fine in my side.

**Comment by Not098** [comment]
Not working for me to

**Comment by github1994-bou** [comment]
Not working for me

**Comment by fawadkhan121** [comment]
The website  layout has changed and the site is now fully operational please look it up
