### ISSUE TITLE
Reaper Scans No Chapter Name and Date 

### ISSUE THREAD

**Issue by hemanthmannam** [tachiyomiorg/tachiyomi-extensions#9937]
### Source information

Reaper Scans

### Steps to reproduce

All the libraries in reaper scans are not displaying chapter name and updated on timestamp

### Expected behavior

Show display name

### Actual behavior

Empty name placeholder

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LeMyst** [comment]
Duplicate #9934
