### ISSUE TITLE
Chapter lists is empty & chapter updates no longer appear in updates tab

### ISSUE THREAD

**Issue by Pa3ckP7** [tachiyomiorg/tachiyomi-extensions#9940]
### Source information

Reaper Scans all 1.2.4

### Steps to reproduce

Open any mangwa/manhua
See chapter list empty

### Expected behavior

Upon opening a manga/manhua/mangwa a chapter list displays

Updates tab shows new chapters

### Actual behavior

No chapter show up in chapter list

Updates tab doesnt have any of the new chapters

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

I can still read chapters fine as the resume button works and pages do load. Web view works without a problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pa3ckP7** [comment]
typo in Source Info the version is 1.2.14 and not 1.2.4

**Comment by LeMyst** [comment]
Duplicate #9934
