### ISSUE TITLE
[ Loading Issue ] Asura Scans

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi-extensions#9941]
### Source information

Asura Scans v1.2.19

### Steps to reproduce

Go to Latest of Asura Scans and open any series.

### Expected behavior

The content of the series loads fast

### Actual behavior

The content of the series loads slow.

### Tachiyomi version

Tachiyomi v0.12.3

### Android version

Android 11

### Other details

Opening Asura Scans on the following scenario loads fast

- Via Desktop Browser
- Via Tachiyomi App > Asura Scans > Latest > Series > WebView

The slow loading only applies when viewing series normally on Tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's intentional, the extension have a rate limiting to avoid causing damage to the scanlator website.

**Comment by saket1999** [comment]
What is rate limiting and when can we expect the normal behaviour?

**Comment by alessandrojean** [comment]
> What is rate limiting and when can we expect the normal behaviour?

Wikipedia's article about [Rate limiting](https://en.m.wikipedia.org/wiki/Rate_limiting).

It's unlikely that it will be removed from the extension since without it a lot of users cause damage to the servers by downloading a lot of chapters at once.
