### ISSUE TITLE
Source request:cc-comic




### ISSUE THREAD

**Issue by sabatachi** [tachiyomiorg/tachiyomi-extensions#9949]
### Source name

cc-comic

### Source link

https://cc-comic.com/

### Language

japanese

### Other details

There are comics that other extensions do not have, such as Baki, which has many Japanese comics. However, the display is very slow probably because there is a problem with the speed of the server.
As an aside, please forgive it because it is the first post and there may be some mistakes. I would like to try to improve from the next time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by sohilsayed** [comment]
I think it wlould be better to rename the issue to (Source request:cc-comic) for better viewability
