### ISSUE TITLE
Can't download certain manga

### ISSUE THREAD

**Issue by EyangKodok** [tachiyomiorg/tachiyomi-extensions#9955]
### Source information

Mangadex, Mangakakalot, and Nightingale (Original),No Two Comics.

### Steps to reproduce

Just download like any others. Press download then the issue show up.

### Expected behavior

The manga get downloaded and i can read it when ever i want with out internet.

### Actual behavior

Download pause it self then a notice pop out says "Invalid download location" it happen only to certain manga It happen to:
"Sekai de Tadahitori no Mamono Tsukai ~Tenshoku Shitara Maou ni Machigawa Remashita~" on mangadex
"It's SuddenBut I Came To Another World! But I Hope To Live Safely" on mangakakalot.

### Tachiyomi version

App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)

### Android version

Android 11

### Other details

- download file location is at SDcard
- it happen after i move my download location to sd card
- most of my manga can download just fine
- kiriya.aoi says it might because the manga name is too long for the sd card to handle or the manga have characters that the sd card doesnt support or something along those line
- i suggest make us able to change the manga name

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please share the crash logs (really just error logs in this case) from More → Settings → Advanced → Dump crash logs.

**Comment by EyangKodok** [comment]
--------- beginning of main 11-29 09:03:34.995 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:04:42.226 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:05:56.432 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:06:19.069 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:13:21.757 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:13:51.330 12493 22247 E SQLiteLog: (284) automatic index on C(manga_id) 11-29 09:13:51.330 12493 22247 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 11-29 09:14:08.371 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:14:15.916 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:14:17.083 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:14:19.601 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:14:24.036 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 09:17:37.642 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:37:05.864 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:37:07.887 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:39:25.358 12493 20164 E DatabaseUtils: Writing exception to parcel 11-29 10:39:25.358 12493 20164 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=31001, uid=1000 requires the provider be exported, or grantUriPermission() 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: Writing exception to parcel 11-29 10:39:25.423 12493 20164 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=31001, uid=1000 requires the provider be exported, or grantUriPermission() 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: Writing exception to parcel 11-29 10:39:25.741 12493 20164 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=31001, uid=1000 requires the provider be exported, or grantUriPermission() 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159) App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.G985FXXSCDUJ5 Device brand: samsung Device manufacturer: samsung Device name: y2s Device model: SM-G985F Device product name: y2sxx

**Comment by arkon** [comment]
Is that right after a failed attempt to download with the "Invalid download location" error?

**Comment by EyangKodok** [comment]
No, ill send new one that after the error

**Comment by EyangKodok** [comment]
--------- beginning of main 11-29 10:37:05.864 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:37:07.887 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:39:25.358 12493 20164 E DatabaseUtils: Writing exception to parcel 11-29 10:39:25.358 12493 20164 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=31001, uid=1000 requires the provider be exported, or grantUriPermission() 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190) 11-29 10:39:25.358 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: Writing exception to parcel 11-29 10:39:25.423 12493 20164 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=31001, uid=1000 requires the provider be exported, or grantUriPermission() 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190) 11-29 10:39:25.423 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: Writing exception to parcel 11-29 10:39:25.741 12493 20164 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=31001, uid=1000 requires the provider be exported, or grantUriPermission() 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190) 11-29 10:39:25.741 12493 20164 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159) 11-29 10:44:09.372 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:44:10.259 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:44:11.381 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:44:16.087 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:45:39.572 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:46:09.995 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:46:20.696 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:46:32.437 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:46:51.493 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:47:10.063 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:47:11.295 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:47:40.890 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:48:01.034 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:49:03.926 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:49:05.140 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:49:06.502 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:51:02.070 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:51:04.076 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:51:06.082 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:51:11.675 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:51:27.215 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:51:51.615 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:53:43.482 12493 9582 E SQLiteLog: (284) automatic index on C(manga_id) 11-29 10:53:43.482 12493 9582 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 11-29 10:54:01.712 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:54:02.837 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:54:07.019 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: Failed to createFile 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:3293) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2380) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2369) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2352) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2415) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1377) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:3) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda6.call(Unknown Source:2) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 11-29 10:54:33.601 12493 10393 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:923) 11-29 10:54:33.723 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 11-29 10:54:34.984 12493 12493 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1 App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.G985FXXSCDUJ5 Device brand: samsung Device manufacturer: samsung Device name: y2s Device model: SM-G985F Device product name: y2sxx

**Comment by EyangKodok** [comment]
Btw i can download 2 manga that i mention above for some reason but still cant download on Song Of The Night Walkers on Mangakakalot

**Comment by arkon** [comment]
I doubt it's hitting the file name limit with short titles like that, but is failing to create files/folders for whatever reason. You could try a different SD card, but there's probably nothing that we can do about it without larger overhauls to the download system.

**Comment by EyangKodok** [comment]
Got it thank you very much for the very
Fast respond
