### ISSUE TITLE
Anime extension's are't very much

### ISSUE THREAD

**Issue by Colorstips** [tachiyomiorg/tachiyomi-extensions#9956]
### Source name

Animesuge,animehub,4anime

### Source link

https://animesuge.to/,https://animehub.ac/,https://4animes.org....

### Language

English subbed and dubbed

### Other details

reausakiwalter@gmail.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Colorstips** [comment]
Do something right now.

**Comment by loocool2** [comment]
We are not Aniyomi. Please do your due diligence and read what Tachiyomi supports before demanding us to do anything.
