### ISSUE TITLE
Yabutoons

### ISSUE THREAD

**Issue by deividgabrielpeira** [tachiyomiorg/tachiyomi-extensions#9958]
### Source name

yabutoons

### Source link

https://yabutoons.com/

### Language

Português

### Other details

WebSite variation for Webtoons

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Will not be added as it belongs to the same owners of MangaYabu that got removed since they don't want the extension to exist.
