### ISSUE TITLE
Mangakio

### ISSUE THREAD

**Issue by MangaHeart** [tachiyomiorg/tachiyomi-extensions#9964]
### Source name

Mangakio

### Source link

https://mangakio.com/

### Language

English

### Other details

![image](https://user-images.githubusercontent.com/94607520/144165665-f94b8415-d9e5-487f-89c5-cff255c02ded.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
already exist, pls do read the acknowledgements next time
