### ISSUE TITLE
动漫之家插件

### ISSUE THREAD

**Issue by zaqzdr** [tachiyomiorg/tachiyomi-extensions#9976]
### Describe your suggested feature

希望这个插件可以加入登录账号的功能

### Other details

我在APP上已经收藏了很多漫画，但在tachiyomi上观看需要逐个收藏，有些麻烦

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Omar-Abdul-Aziz** [comment]
You can backup library in the settings
![Screenshot_20211205-233324_Tachiyomi](https://user-images.githubusercontent.com/49833164/144764753-1d28e8ec-c0d6-42fb-a2df-4b02770bef8a.png)

**Comment by ringosham** [comment]
Your manga library from Copymanga will not sync with Tachiyomi. It simply won't be supported

**Comment by alessandrojean** [comment]
Closing since we don't offer this type of sync. Your only alternative is adding manually one by one.
