### ISSUE TITLE
Webtoons.com: can't browse or open chapters

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#9977]
### Source information

Webtoons.com 1.2.32

### Steps to reproduce

Open any chapter in webtoons.com

### Expected behavior

Chapters open corectly

### Actual behavior

![Screenshot_2021-12-02-15-38-18-340_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/39062952/144424776-aa7f5cb3-5c2c-43bb-aa74-e7a4cf114be2.jpg)

### Tachiyomi version

r3984

### Android version

Android 11. Miui 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by semiya5** [comment]
Just to add to this, opening extension in webview fixes the issue. Until you close the app, then you have to reopen webview again or you get the error

**Comment by scb261** [comment]
webtoons.com should send their certificate along with intermediate certificates, but they only send their own. From my testing this breaks the site in some browsers (since the site actually behaves wrong), but it works fine in most browsers - probably because the intermediate certificate is already known from other sites or because those browsers already have them built-in. 

It could be misconfiguration or attempt to block scrapers, I would wait a little to see if they fix it.

**Comment by catdevnull** [comment]
The missing certificate is GeoTrust RSA CA 2018. [SSL Labs test](https://www.ssllabs.com/ssltest/analyze.html?d=webtoons.com&s=223.130.195.138&latest)

Maybe the extension could bundle the certificate?

**Comment by ObserverOfTime** [comment]
> Maybe the extension could bundle the certificate?

It's doable (see #9414), but I'm sure they will fix the issue soon enough.

**Comment by catdevnull** [comment]
I don't see why they would fix it if it works fine on most browsers. To be clear, it's not that the CA is not trusted, it's just that the client must have the intermediate certificate to verify Webtoons' certificate but Webtoons isn't sending it.

**Comment by arkon** [comment]
As pointed out by fourquestionmarksokay#1087 on Discord, Android doesn't handle intermediate certificates properly while Chromium does. It may be possible to add logic within the app to handle them better, although I'm not sure if it's necessarily worth doing unless we start seeing it happen with more sources.

Perhaps the extension could just provide a better error message in the case of getting this exception for now?

**Comment by ObserverOfTime** [comment]
> I don't see why they would fix it if it works fine on most browsers.

I slid into their Twitter DMs to let them know about the missing certificate. Fingers crossed.

**Comment by FinaleRoyale** [comment]
Thanks guys I've been having this security issue as well, hope the plugin/API gets fixed soon...

**Comment by catdevnull** [comment]
I also sent a support ticket.

**Comment by Fliv25** [comment]
It's been 2 days (•́︿•̀)

**Comment by Omar-Abdul-Aziz** [comment]
Just open it in webview and it will be fixed until you close the app it's already mentioned above no need for spam comments
