### ISSUE TITLE
Geass Scan: Domain Changed

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#9979]
### Describe your suggested feature

Geassscan.net

### Other details

Trocar geassscan.xyz por geassscan.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please fill the form in English next time.

**Comment by alessandrojean** [comment]
Actually, closing since this isn't a feature request and should be a bug instead. I will fill another issue.
