### ISSUE TITLE
Geass Scanlator: Domain changed

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi-extensions#9980]
### Source information

Geass Scanlator v1.2.14

### Steps to reproduce

1. Open the extension catalog.

### Expected behavior

The extension catalog should load correctly.

### Actual behavior

It does load, but it's happening since the domain is redirecting for now. The domain needs to be updated in the extension otherwise it will break soon.

### Tachiyomi version

r3984

### Android version

Android 11

### Other details

Originally reported in #9979.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Raidre** [comment]
Bora adm atualizar a extensão logo kk to com os mangás tudo atrazado

**Comment by alessandrojean** [comment]
Sem previsão, esse é um projeto open source que as pessoas colaboram quando tem vontade e tempo livre. Aguarde ou migre, ficar cobrando não vai mudar em nada.
