### ISSUE TITLE
[Mangasee] Updates failed. Error: java.lang.String org.jsoup.nodes.Element.data()

### ISSUE THREAD

**Issue by ChineseOuchie** [tachiyomiorg/tachiyomi-extensions#9982]
### Source information

MangaSee 1.2.26

### Steps to reproduce

Update all manga

### Expected behavior

Expect to see new updates if available or nothing when no new update

### Actual behavior

Received this notification: "2 Update failed"

With this as content:
```
Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.data()' on a null object reference 
# MangaSee (EN) 
- Reincarnated as an Aristocrat with an Appraisal Skill 
- The Unsuccessful yet Academically Unparalleled Sage
```

### Tachiyomi version

0.12.3

### Android version

Android 12

### Other details

Device: Samsung S21 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by polydoo** [comment]
Same happened to me with 66 updates (Lector Manga, Nine Manga, Mangadex, MangaPark, MangaBat), but almost 80% or them are officially finished, so idk...

**Comment by paulo27ms** [comment]
MangaSee seems fine, site likely just went down for a bit or you faced some timeout. Get help on discord next time.

**Comment by ChineseOuchie** [comment]
All my manga are from the same extension but only "Reincarnated as an Aristocrat with an Appraisal" get this error. All the other manga are updating normally

**Comment by Seishirou101** [comment]
The error seems to fix itself after sometime so it may be something on their side. As of now, "Reincarnated as an Aristocrat with an Appraisal" works as intended as well as the other one in your example
