### ISSUE TITLE
Bilibili Comics: Titles with paid chapters doesn't appear in search

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#9984]
### Source information

Bilibili Comics 1.2.8

### Steps to reproduce

Search for example ,,Ruler of Infinite Realms". And if you added earlier, this comic's chapter show as no pages found.

### Expected behavior

Show many comics and one of them is  ,,Ruler of Infinite Realms".

### Actual behavior

Show many comics and no one of them is  ,,Ruler of Infinite Realms".

### Tachiyomi version

0.12.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It doesn't appear anymore in the Bilibili website, it most likely got removed by them. Nothing we can do about it, migrate to other sources.

**Comment by mcOz1** [comment]
For me it appeared. 
![image](https://user-images.githubusercontent.com/71328023/144562507-48bfefec-5ebf-4579-ae13-25672edef835.png)

**Comment by mcOz1** [comment]
@alessandrojean

**Comment by mcOz1** [comment]
I was using a browser.

**Comment by alessandrojean** [comment]
It appears on the search of the extension if you open in your browser and click on "Open in Bilibili" intent. If the intent does not appears for you, you can search for `id:mc221` and it will appears. We do not control the Bilibili search results, so there's nothing much we can do if this title in particular does not show up in the search, the extension does exactly the same request as the website.

**Comment by FourTOne5** [comment]
@alessandrojean seems like the culprit is this

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/63d8eb55546d61e1af4b4766c8307366a45b1bfd/src/en/bilibilicomics/src/eu/kanade/tachiyomi/extension/en/bilibilicomics/BilibiliComics.kt#L164

the app and the site uses -1

**Comment by alessandrojean** [comment]
Good catch. The series doesn't appear since a lot of their chapters are paid now.  The extension needs an update to remove these paid chapters from the chapter list too. I will reopen this one.

**Comment by alessandrojean** [comment]
/edit-title "Bilibili Comics: Titles with paid chapters doesn't appear in search"

**Comment by FourTOne5** [comment]
This also seems to be the case for popular and latest.

**Comment by alessandrojean** [comment]
Working on it now.
