### ISSUE TITLE
Bilibili Comics: Remove paid chapters from the chapter list

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#9987]
### Source information

Bilibili Comics 1.2.8

### Steps to reproduce

Search for example ,,Her Super Bodyguard". Comic's chapters show as no pages found

### Expected behavior

Read and download normally.

### Actual behavior

No pages found.

### Tachiyomi version

0.12.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The episodes that does not load for you are the last 4 that are exclusive for their app, so it won't work in the extension since they don't have the images in the API. Use their app to read them.

The extension should probably filter and remove them from the list, so I will let this open.

**Comment by alessandrojean** [comment]
/edit-title "Bilibili Comics: Remove app-exclusive chapters from the list"

**Comment by jopejoe1** [comment]
> The episodes that does not load for you are the last 4 that are exclusive for their app, so it won't work in the extension since they don't have the images in the website API.

This is not the case from what i see the ones that don't load are the login protected chapters. 

App exclusive chapters work totally fine. `The All-devouring Whale` app exclusive chapters for example load fine where for the one given here `Her Super Bodyguard` starting from chapter 40 all chapters are giving the `No Page` when looking at the website for these chapters you can see that login is required for these.

**Comment by alessandrojean** [comment]
As I said in the other issue, Bilibili is now making some chapters paid. It requires login so you can pay with coins (the API call for these chapters shows their price).

**Comment by FourTOne5** [comment]
The title is basically misleading we need to filter out paid chapters and not app exclusive chapters

**Comment by alessandrojean** [comment]
/edit-title "Bilibili Comics: Remove paid chapters from the chapter list"

**Comment by 8227846265** [comment]
Will the Bilibili extensions going to be updated soon? It seems more and more series are getting the paid chapter treatment, and it affects the `Download Chapter` function severely, showing not downloadable chapters proportionate to the number of series with paid chapters.

**Comment by alessandrojean** [comment]
Working on it. I will filter out the paid chapters for now.
