### ISSUE TITLE
مانغا العرب

### ISSUE THREAD

**Issue by BAKIRsan** [tachiyomiorg/tachiyomi-extensions#9994]
### Source name

مانغا العرب

### Source link

https://manga.ae/

### Language

العربية

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
مصدر موجود

![IMG_20211205_124158.jpg](https://user-images.githubusercontent.com/61906880/144744991-e3b205f3-6368-4156-9aeb-51a202cfdc7a.jpg)

لهذا سوف يتم غلق هذا طلب.
